import re
import generate_translations

all_texts = sorted(list(generate_translations.all_texts))

# Comprehensive translation dictionary
translations = {}

# 1. Base UI & Labels
base_map = {
    "Fragen & Spiele": "Questions & Games",
    "unterhaltung": "Entertainment",
    "dasoderdas": "This or That",
    "hochzeit": "Wedding",
    "kinder": "Children",
    "reden": "Discussion",
    "reisen": "Travel",
    "familie": "Family",
    "geld": "Money",
    "Kategorien": "Categories",
    "Tägliche Aktivität": "Daily activity",
    "🔥 Tägliche Aktivität": "🔥 Daily activity",
    "Für dich empfohlen": "Recommended for you",
    "Paar-Statistiken": "Couple statistics",
    "Gemeinsame Tage": "Days together",
    "Beantwortete Fragen": "Questions answered",
    "Besuchte Städte": "Cities visited",
    "Besuchte Länder": "Countries visited",
    "Widgets": "Widgets",
    "Du fehlst mir": "I miss you",
    "Denke an dich": "Thinking of you",
    "Kuss senden": "Send a kiss",
    "Kuss": "Kiss",
    "Aufwärmen": "Warm-up",
    "Beziehung": "Relationship",
    "Sex & Liebe": "Sex & Love",
    "Moralische Werte": "Moral values",
    "Geld & Finanzen": "Money & Finances",
    "Einander kennenlernen": "Getting to know each other",
    "Reisen": "Travel",
    "Familie": "Family",
    "Hobbys": "Hobbies",
    "Wer würde eher?": "Who's more likely?",
    "Zeichnen": "Draw",
    "Das oder das?": "This or That?",
    "Zustimmen oder Ablehnen": "Agree or Disagree",
    "Ich habe noch nie": "Never have I ever",
    "Was magst du lieber?": "Which do you prefer?",
    "Antwort mit einem Foto": "Answer with a photo",
    "Tiefe Gespräche": "Deep conversations",
    "Reden vor ...": "Talk before ...",
    "Zuhause & Alltag": "Home & everyday life",
    "Der perfekte Heiratsantrag": "The perfect proposal",
    "Vorlieben für den Antrag": "Proposal preferences",
    "Diskutiere vor dem Kinderkriegen": "Discuss before having children",
    "Vor der Anschaffung eines Haustiers besprechen": "Discuss before getting a pet",
    "Vor der gemeinsamen Reise besprechen": "Discuss before travelling together",
    "Vor dem Kauf eines Hauses besprechen": "Discuss before buying a house",
    "Reiseziele": "Travel destinations",
    "Alle": "All",
    "Du bist dran": "Your turn",
    "Beantwortet": "Answered",
    "Überspringen": "Skip",
    "Weiter": "Next",
    "Schließen": "Close",
    "Bearbeiten": "Edit",
    "Profil": "Profile",
    "Dein Name": "Your name",
    "Partnerin": "Partner",
    "Partner": "Partner",
    "Zusammen seit": "Together since",
    "Partner-Simulator": "Partner simulator",
    "Entwickler-Modus": "Developer mode",
    "Entwickler Studio Öffnen": "Open Developer Studio",
    "Sprache": "Language",
    "Deutsch": "German",
    "Englisch": "English",
    "KI-Beziehungscoach": "AI relationship coach",
    "KI-Date-Ideen": "AI date ideas",
    "Analyse starten": "Start analysis",
    "Ideen generieren": "Generate ideas",
    "Namen und Startdatum eurer Beziehung.": "Your names and relationship start date.",
    "Name Partnerin": "Partner's name",
    "Diskutiert eure Antworten": "Discuss your answers",
    "ERGEBNISSE": "RESULTS",
    "BEANTWORTE": "ANSWER",
    "Alle Pakete": "All packs",
    "Fertig": "Done",
    "Fertig!": "Done!",
    "Abbrechen": "Cancel",
    "Speichern": "Save",
    "Hinzufügen": "Add",
    "Momente": "Moments",
    "Titel": "Title",
    "Was ist passiert?": "What happened?",
    "Zurück": "Back",
    "Quiz verlassen?": "Leave quiz?",
    "Weiter spielen": "Keep playing",
    "Übernehmen": "Save",
    "Deine eigene Antwort": "Your own answer",
    "Deine Antwort...": "Your answer...",
    "Frage hinzufügen": "Add question",
    "Paar": "Pair",
    "Galerie": "Gallery",
    "Testen": "Test",
    "Spiel bearbeiten": "Edit game",
    "Neues Spiel": "New game",
    "Antwortähnlichkeit": "Answer similarity",
    "Diskussion": "Discussion",
    "✎ Tippe, um zu antworten": "✎ Tap to answer",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert.": "Are you sure you want to leave? Your progress will be saved.",
    "Schreib frei, was dir wirklich dazu einfällt.": "Write what truly comes to mind.",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!": "Did you discover surprising differences? Talk about why you prefer certain options!",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar.": "Your answers are saved. Once your partner finishes the pack, you will see both answers together.",
    "Schreibe deine eigene Antwort": "Write your own answer",
    "Oder": "Or",
    "oder": "or"
}

for k, v in base_map.items():
    translations[k] = v

# Dictionary for phrases and words replacement
dict_terms = [
    # Questions
    ("Was gefällt dir an deinem Zuhause am besten?", "What do you like most about your home?"),
    ("Welcher Raum sagt am meisten über dich aus?", "Which room says the most about you?"),
    ("Was würdest du sofort ändern, wenn Geld keine Rolle spielt?", "What would you change immediately if money were no object?"),
    ("Wie sieht dein perfekter Sonntag zuhause aus?", "What does your perfect Sunday at home look like?"),
    ("Welche Umgebung würdest du dir für einen Antrag wünschen?", "What kind of setting would you wish for a proposal?"),
    ("Magst du einen öffentlichen oder privaten Antrag lieber?", "Would you prefer a public or private proposal?"),
    ("Soll der Antrag eine Überraschung sein?", "Should the proposal be a surprise?"),
    ("Wie wichtig ist dir, dass der Moment festgehalten wird?", "How important is it to you that the moment is captured?"),
    ("Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?", "Do you prefer an extravagant proposal or something subtle?"),
    ("Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?", "What do you think of props (e.g. signs, balloons, etc.)?"),
    ("Wie wichtig ist dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?", "How important is it that the proposal reflects your hobbies or interests?"),
    ("Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?", "Would you prefer a proposal on vacation (combined with travel)?"),
    ("Wie lange nach dem Antrag möchtest du mit anderen feiern?", "How long after the proposal would you like to celebrate with others?"),
    ("Hättest du gerne einen geschriebenen Brief als Teil des Antrags?", "Would you like a written letter as part of the proposal?"),
    ("Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?", "Should the proposal include cultural or traditional elements?"),
    ("Was ist das Wichtigste beim Antrag?", "What is the most important thing about the proposal?"),
    ("Möchtest du, dass Haustiere beim Antrag dabei sind?", "Would you like pets to be present during the proposal?"),
    ("Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰", "Are we able to cover all costs for a child/children? 💰"),
    ("Werden wir genug Zeit für das Kind / die Kinder haben? ⏳", "Will we have enough time for the child/children? ⌛"),
    ("Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?", "How will we find time for our relationship when the baby arrives?"),
    ("Wie möchtest du, dass unsere Zukunft aussieht?", "How do you want our future to look?"),
    ("Wie würdest du sie/ihn nennen?", "What would you name him/her?"),
    ("Willst du ein Mädchen oder einen Jungen? 👶", "Do you want a girl or a boy? 👶"),
    ("Was soll aus unserem Kind werden, wenn es erwachsen ist?", "What do you hope our child becomes when they grow up?"),
    ("Wer übernimmt die tägliche Versorgung?", "Who will handle daily care?"),
    ("Was passiert mit dem Tier, wenn wir verreisen?", "What happens to the pet when we travel?"),
    ("Welches Budget planen wir für Futter und Tierarzt ein?", "What budget do we plan for food and vet costs?"),
    ("Passt ein Tier überhaupt zu unserem Alltag?", "Does a pet fit into our daily routine at all?"),
    ("Wie viel wollen wir insgesamt ausgeben?", "How much do we want to spend in total?"),
    ("Lieber durchgeplant oder spontan?", "Rather fully planned or spontaneous?"),
    ("Wie viel Zeit wollen wir getrennt verbringen?", "How much time do we want to spend apart?"),
    ("Was ist für jeden von uns das absolute Highlight?", "What is the absolute highlight for each of us?"),
    ("Wie viel Kredit ist für uns realistisch tragbar?", "How much mortgage can we realistically afford?"),
    ("Stadt oder Land — was ist uns wichtiger?", "City or countryside — which is more important to us?"),
    ("Wie lange wollen wir dort mindestens bleiben?", "How long do we plan to stay there at minimum?"),
    ("Wer kümmert sich um Renovierung und Instandhaltung?", "Who handles renovations and maintenance?"),
    ("Möglicherweise müssen wir Einsparungen vornehmen", "We might need to make budget cutbacks"),
    ("Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat.", "Yes, we will ensure family time is prioritized."),
    ("Regelmäßige Rendezvous oder gemeinsame Zeit einplanen", "Schedule regular date nights or quality time together"),
    ("Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden", "Travel the world together, explore new cultures and cuisines"),
    
    # Common Options & Pairs
    ("Gemütliches Wohnzimmer", "Cozy living room"),
    ("Küche als Herzstück", "Kitchen as the heart of the home"),
    ("Schlafzimmer als Rückzugsort", "Bedroom as a retreat"),
    ("Balkon / Garten", "Balcony / Garden"),
    ("Sehr wichtig, es sollte persönlich sein", "Very important, it should be personal"),
    ("Etwas, eine kleine Note wäre schön", "Somewhat, a small touch would be nice"),
    ("Nicht nötig, lieber klassisch bleiben", "Not necessary, prefer to keep it classic"),
    ("Ja, in einer aufregenden Stadt oder Sehenswürdigkeit", "Yes, in an exciting city or landmark"),
    ("Vielleicht, wenn es machbar ist", "Maybe, if it works out"),
    ("Nein, lieber vor Ort", "No, prefer local"),
    ("Am selben Tag mit Freunden/Familie", "On the same day with friends/family"),
    ("Etwa eine Woche später, erst mal nur wir", "About a week later, just us at first"),
    ("Keine Party nötig, privat halten", "No party needed, keep it private"),
    ("Ja, etwas zum Lesen und Aufbewahren", "Yes, something to read and keep"),
    ("Vielleicht, aber mündlich reicht", "Maybe, but verbal is enough"),
    ("Nein, einfach halten", "No, keep it simple"),
    ("Ja, Traditionen einbinden", "Yes, include traditions"),
    ("Ein paar kulturelle Anklänge sind okay", "A few cultural touches are okay"),
    ("Nein, modern halten", "No, keep it modern"),
    ("Die Umgebung und Atmosphäre", "The setting and atmosphere"),
    ("Die Worte und Emotionen", "The words and emotions"),
    ("Der Ring und die Geste", "The ring and the gesture"),
    ("Ja, sie gehören zur Familie!", "Yes, they are part of the family!"),
    ("Vielleicht, wenn es passt", "Maybe, if it fits"),
    ("Nein, nur wir", "No, just us"),
    
    # Housing & Destinations
    ("Altbau mit Charme", "Historic charm apartment"),
    ("Neubau mit Smart Home", "Modern smart home building"),
    ("Mitten in der Stadt", "In the city center"),
    ("Ruhiges Landleben", "Quiet countryside life"),
    ("Strandurlaub", "Beach vacation"),
    ("Städtetrip", "City trip"),
    ("Chalet in den Bergen", "Mountain chalet"),
    ("Bungalow am Strand", "Beachfront bungalow"),
    ("Kaffee am Morgen", "Morning coffee"),
    ("Tee am Abend", "Evening tea"),
    ("Hund als Begleiter", "Dog as a companion"),
    ("Katze als Gefährte", "Cat as a companion"),
    ("Sommer-Fan", "Summer lover"),
    ("Winter-Fan", "Winter lover"),
    ("Infinity-Pool", "Infinity pool"),
    ("Naturteich", "Natural pond"),
    ("Dachgeschosswohnung mit Aussicht", "Top floor apartment with a view"),
    ("Erdgeschoss mit eigenem Garten", "Ground floor with private garden"),
    ("Eigenes Gemüsebeet", "Home vegetable garden"),
    ("Blumenparadies", "Flower paradise"),
    ("Selbstgemachtes Pizza-Date", "Homemade pizza date"),
    ("Schickes Restaurant", "Fancy restaurant"),
    ("Feuerwerk-Spektakel", "Fireworks spectacle"),
    ("Gemütliches Lagerfeuer", "Cozy campfire"),
    ("Roadtrip durch Europa", "European road trip"),
    ("Fernreise nach Asien", "Long-haul trip to Asia"),
    ("Hausboot auf den Grachten", "Houseboat on the canals"),
    ("Tiny House in der Natur", "Tiny house in nature"),
    ("Sonnenaufgang auf dem Berg", "Sunrise on the mountain"),
    ("Sonnenuntergang am Meer", "Sunset by the sea"),
    ("Oldtimer-Cabrio", "Classic convertible car"),
    ("Elektro-Sportwagen", "Electric sports car"),
    ("Privat-Kino im Keller", "Private basement cinema"),
    ("Open-Air-Kino unter Sternen", "Open-air cinema under stars"),
    ("Whirlpool auf der Terrasse", "Hot tub on the terrace"),
    ("Sauna im Badezimmer", "Sauna in the bathroom"),
    ("Frühstück im Bett", "Breakfast in bed"),
    ("Mitternachtssnack am Kühlschrank", "Midnight snack at the fridge"),
    ("Festnetz mit Wählscheibe", "Vintage rotary telephone"),
    ("Neuestes Smartphone", "Latest smartphone"),
    ("Gedrucktes Buch aus Papier", "Printed paper book"),
    ("E-Book-Reader", "E-book reader"),
    ("Schallplattenspieler", "Vinyl record player"),
    ("Bluetooth-Lautsprecher", "Bluetooth speaker"),
    ("Kaminfeuer im Wohnzimmer", "Fireplace in the living room"),
    ("Klimaanlage im Schlafzimmer", "Air conditioning in the bedroom"),
    ("Hängematte unter Palmen", "Hammock under palm trees"),
    ("Ergonomischer Bürostuhl", "Ergonomic office chair"),
    ("Espressomaschine", "Espresso machine"),
    ("Klassischer Filterkaffee", "Classic filter coffee"),
    ("Sauerteigbrot selber backen", "Baking homemade sourdough bread"),
    ("Frische Brötchen vom Bäcker", "Fresh rolls from the bakery"),
    ("Kerzenschein beim Abendessen", "Candlelight at dinner"),
    ("Lichterkette auf dem Balkon", "String lights on the balcony"),
    ("Pickup für Abenteuer", "Adventure pickup truck"),
    ("Wohnmobil für Urlaube", "Camper van for vacations"),
    ("Spieleabend mit Freunden", "Board game night with friends"),
    ("Tanznacht im Club", "Dancing night at the club"),
    ("Picknick im Park", "Picnic in the park"),
    ("Gourmet-Menü im Restaurant", "Gourmet menu at a restaurant"),
    ("Zeltcampen im Wald", "Tent camping in the forest"),
    ("5-Sterne-Luxushotel", "5-star luxury hotel"),
    ("Schneemann bauen", "Building a snowman"),
    ("Sandburg bauen", "Building a sandcastle"),
    ("Klassisches Konzert", "Classical concert"),
    ("Rock-Festival", "Rock festival"),
    ("Paddeln auf dem Fluss", "Paddling on the river"),
    ("Segeln auf dem Meer", "Sailing on the sea"),
    ("Flohmarkt-Schatzsuche", "Flea market treasure hunt"),
    ("Shopping-Mall", "Shopping mall"),
    ("Täglich kochen", "Cooking every day"),
    ("Essen bestellen", "Ordering takeout"),
    ("Frühaufsteher", "Early bird"),
    ("Nachteule", "Night owl"),
    ("Sehr ordentlich", "Very tidy"),
    ("Entspanntes Chaos", "Relaxed chaos"),
    ("Spontan verreisen", "Spontaneous trips"),
    ("Monate vorausplanen", "Planning months ahead"),
    ("Action & Sport", "Action & Sports"),
    ("Entspannung & Wellness", "Relaxation & Wellness"),
    ("Süßes Frühstück", "Sweet breakfast"),
    ("Herzhaftes Frühstück", "Savory breakfast"),
    ("Mehrere kleine Geschenke", "Multiple small gifts"),
    ("Ein großes Hauptgeschenk", "One big main gift"),
    ("Lieber warmes Klima", "Warmer climate"),
    ("Lieber kühles Klima", "Cooler climate"),
    ("Krimi & Thriller", "Crime & Thrillers"),
    ("Komödie & Feelgood", "Comedy & Feelgood"),
    ("Stille genießen", "Enjoying quietness"),
    ("Hintergrundmusik laufen lassen", "Background music playing"),
    ("Direkt ansprechen", "Discussing immediately"),
    ("Erst mal verarbeiten", "Processing first"),
    ("Sparsam für die Zukunft", "Saving for the future"),
    ("Genießen im Hier und Jetzt", "Enjoying the present"),
    
    # Hugs & Preferences
    ("Derjenige sein, der umarmt wird", "Being the one who is hugged"),
    ("Diejenige sein, die umarmt", "Being the one who hugs"),
    ("Verbringe die Feiertage mit deiner Familie", "Spend the holidays with your family"),
    ("Die Feiertage mit der Familie deines Partners verbringen", "Spend the holidays with your partner's family"),
    
    # Love languages & affection
    ("Durch Worte", "Through words"),
    ("Durch Taten", "Through actions"),
    ("Durch Geschenke", "Through gifts"),
    ("Durch Zeit zu zweit", "Through quality time"),
    ("Durch Berührung", "Through touch"),
    ("Durch kleine Gesten", "Through small gestures")
]

for k, v in dict_terms:
    translations[k] = v

print(f"Total base translations mapped: {len(translations)}")

