import re
import sys

# Load all strings from generate_translations
import generate_translations
all_texts = generate_translations.all_texts

# Built-in high accuracy translation map
TRANSLATION_MAP = {
    # UI & Navigation
    "Fragen & Spiele": "Questions & Games",
    "unterhaltung": "Entertainment",
    "dasoderdas": "This or That",
    "hochzeit": "Wedding",
    "kinder": "Children",
    "reden": "Discussion",
    "reisen": "Travel",
    "familie": "Family",
    "Kategorien": "Categories",
    "Tägliche Aktivität": "Daily activity",
    "🔥 Tägliche Aktivität": "🔥 Daily activity",
    "Für dich empfohlen": "Recommended for you",
    "Paar-Statistiken": "Couple statistics",
    "Gemeinsame Tage": "Days together",
    "Beantwortete Fragen": "Questions answered",
    "Besuchte Städte": "Cities visited",
    "Besuchte Länder": "Countries visited",
    "Widgets": "Widgets",
    "Du fehlst mir": "I miss you",
    "Denke an dich": "Thinking of you",
    "Kuss senden": "Send a kiss",
    "Kuss": "Kiss",
    "Aufwärmen": "Warm-up",
    "Beziehung": "Relationship",
    "Sex & Liebe": "Sex & Love",
    "Moralische Werte": "Moral values",
    "Geld & Finanzen": "Money & Finances",
    "Einander kennenlernen": "Getting to know each other",
    "Reisen": "Travel",
    "Familie": "Family",
    "Hobbys": "Hobbies",
    "Wer würde eher?": "Who's more likely?",
    "Zeichnen": "Draw",
    "Das oder das?": "This or That?",
    "Zustimmen oder Ablehnen": "Agree or Disagree",
    "Ich habe noch nie": "Never have I ever",
    "Was magst du lieber?": "Which do you prefer?",
    "Antwort mit einem Foto": "Answer with a photo",
    "Tiefe Gespräche": "Deep conversations",
    "Reden vor ...": "Talk before ...",
    "Zuhause & Alltag": "Home & everyday life",
    "Der perfekte Heiratsantrag": "The perfect proposal",
    "Vorlieben für den Antrag": "Proposal preferences",
    "Diskutiere vor dem Kinderkriegen": "Discuss before having children",
    "Vor der Anschaffung eines Haustiers besprechen": "Discuss before getting a pet",
    "Vor der gemeinsamen Reise besprechen": "Discuss before travelling together",
    "Vor dem Kauf eines Hauses besprechen": "Discuss before buying a house",
    "Reiseziele": "Travel destinations",
    "Alle": "All",
    "Du bist dran": "Your turn",
    "Beantwortet": "Answered",
    "Überspringen": "Skip",
    "Weiter": "Next",
    "Schließen": "Close",
    "Bearbeiten": "Edit",
    "Profil": "Profile",
    "Dein Name": "Your name",
    "Partnerin": "Partner",
    "Partner": "Partner",
    "Zusammen seit": "Together since",
    "Partner-Simulator": "Partner simulator",
    "Entwickler-Modus": "Developer mode",
    "Entwickler Studio Öffnen": "Open Developer Studio",
    "Sprache": "Language",
    "Deutsch": "German",
    "Englisch": "English",
    "KI-Beziehungscoach": "AI relationship coach",
    "KI-Date-Ideen": "AI date ideas",
    "Analyse starten": "Start analysis",
    "Ideen generieren": "Generate ideas",
    "Namen und Startdatum eurer Beziehung.": "Your names and relationship start date.",
    "Name Partnerin": "Partner's name",
    "Diskutiert eure Antworten": "Discuss your answers",
    "ERGEBNISSE": "RESULTS",
    "BEANTWORTE": "ANSWER",
    "Alle Pakete": "All packs",
    "Fertig": "Done",
    "Fertig!": "Done!",
    "Abbrechen": "Cancel",
    "Speichern": "Save",
    "Hinzufügen": "Add",
    "Momente": "Moments",
    "Titel": "Title",
    "Was ist passiert?": "What happened?",
    "Zurück": "Back",
    "Quiz verlassen?": "Leave quiz?",
    "Weiter spielen": "Keep playing",
    "Übernehmen": "Save",
    "Deine eigene Antwort": "Your own answer",
    "Deine Antwort...": "Your answer...",
    "Frage hinzufügen": "Add question",
    "Paar": "Pair",
    "Galerie": "Gallery",
    "Testen": "Test",
    "Spiel bearbeiten": "Edit game",
    "Neues Spiel": "New game",
    "Antwortähnlichkeit": "Answer similarity",
    "Diskussion": "Discussion",
    "✎ Tippe, um zu antworten": "✎ Tap to answer",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert.": "Are you sure you want to leave? Your progress will be saved.",
    "Schreib frei, was dir wirklich dazu einfällt.": "Write what truly comes to mind.",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!": "Did you discover surprising differences? Talk about why you prefer certain options!",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar.": "Your answers are saved. Once your partner finishes the pack, you will see both answers together.",
    "Schreibe deine eigene Antwort": "Write your own answer",
    "Oder": "Or",
    "oder": "or"
}

