package com.example.data

/**
 * Defines which image source is allowed to win for "Das oder Das" cards.
 *
 * Images generated by a Dev-Studio export are user/project content and must never be
 * overwritten afterwards by the legacy APK/Drive installer. Refreshed compiled resources
 * can also opt out of the legacy installer so a newly shipped drawable is actually used.
 */
object TotImageSourcePolicy {

    fun shouldUseBundledInstallerImage(
        option: String,
        generatedOptionKeys: Set<String>,
        preferCompiledResource: Boolean = false
    ): Boolean {
        if (preferCompiledResource) return false

        val normalizedOption = option.trim()
        if (normalizedOption.isEmpty()) return false

        return generatedOptionKeys.none { key ->
            key.trim().equals(normalizedOption, ignoreCase = true)
        }
    }
}
