package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_AFRIKAANS_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 jaar",
    "1000 - 1500 im Monat" to "1000 - 1500 per maand",
    "1000 bis 3000" to "1000 tot 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 per maand",
    "3000 bis 5000" to "3000 tot 5000",
    "5-10 Jahre" to "5-10 jaar",
    "50-100€/Monat" to "50-100€/maand",
    "Ab 100€" to "Vanaf 100€",
    "Ab 500€" to "Vanaf € 500",
    "Ab 50€" to "Vanaf € 50",
    "Ab und zu" to "Elke nou en dan",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Hoeveel moet ons spandeer voordat ons 'n aankoop doen?",
    "Abbrechen" to "Kanselleer",
    "Abenteuer" to "Avontuur",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Aktiwiteite",
    "Alle" to "Almal",
    "Alle Pakete" to "Alle pakkette",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Verloor al jou vriende behalwe jou beste vriend",
    "Alle intimen Momente selbst initiieren" to "Begin alle intieme oomblikke self",
    "Alles davon" to "Dit alles",
    "Alles, was noch kommt" to "Alles wat gaan kom",
    "Alltagsroutine" to "Alledaagse roetine",
    "Alltägliche Berührungen" to "Alledaagse aanrakinge",
    "Altbau mit Charme" to "Ou gebou met sjarme",
    "Am Strand" to "Op die strand",
    "Am liebsten alles zusammen" to "Verkieslik alles saam",
    "Am selben Tag mit Freunden/Familie" to "Dieselfde dag saam met vriende/familie",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Nederland",
    "An das Gefühl" to "Van die gevoel",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "In 'n openbare plek met baie toeskouers",
    "An einen Geruch" to "Van 'n reuk",
    "An einen Song" to "Na 'n liedjie",
    "An etwas, das ich gesagt habe" to "Iets wat ek gesê het",
    "Analyse starten" to "Begin ontleding",
    "Analysiere eure Muster..." to "Ontleed jou patrone...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Ontleed jou antwoorde en geselsies volgens Gottman en GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Pynappel op pizza smaak heerlik.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Antwoord met 'n foto",
    "Antwortähnlichkeit" to "Antwoordooreenkoms",
    "App-Sprache auswählen" to "Kies programtaal",
    "Auf eine Bootsparty gehen" to "Gaan na 'n bootpartytjie",
    "Aufmerksamkeit" to "Aandag",
    "Aufräumen und Projekte angehen" to "Skoon op en pak projekte aan",
    "Aufwärmen" to "Warm op",
    "Aufwärmen: Einander kennenlernen" to "Opwarming: Leer mekaar ken",
    "Aus dem Urlaub" to "Van vakansie",
    "Ausgefallener Name" to "Fantastiese naam",
    "Ausschlafen und faulenzen" to "Slaap in en luier",
    "Ausschlafen und nichts tun" to "Slaap in en doen niks",
    "Aussehen" to "Voorkoms",
    "Auto" to "Outo",
    "Außenkamin" to "Buitelug kaggel",
    "BEANTWORTE" to "ANTWOORD",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonesië",
    "Banane" to "Piesang",
    "Beantwortet" to "Beantwoord",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Beantwoord vrae op dieselfde tyd – antwoorde sal nie sigbaar wees voordat julle albei klaar is nie.",
    "Beantwortete Fragen" to "Vrae beantwoord",
    "Bearbeiten" to "Wysig",
    "Bei Insider-Witzen" to "Vir binne-grappies",
    "Bei Memes" to "Op memes",
    "Bei einer spontanen Berührung" to "Wanneer dit spontaan aangeraak word",
    "Beide" to "Albei",
    "Beide gleich" to "Albei dieselfde",
    "Beide zusammen" to "Albei saam",
    "Beide, aber wir tun so als ob nicht" to "Albei, maar ons maak asof nie",
    "Beides" to "Albei",
    "Beides wäre schlimm" to "Albei sou sleg wees",
    "Beim Einschlafen nebeneinander" to "Aan die slaap raak langs mekaar",
    "Beim Reden" to "Terwyl jy praat",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Bekende toeristeplekke is altyd 'n teleurstelling.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Beskryf ons sekslewe met 'n emoji.",
    "Besser kommunizieren" to "Kommunikeer beter",
    "Bessere Lage" to "Beter ligging",
    "Bestellen" to "Bestelling",
    "Besuchte Länder" to "Lande wat besoek is",
    "Besuchte Städte" to "Stede besoek",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Verkies jy 'n buitensporige voorstel of iets subtiel?",
    "Beziehung" to "Verhouding",
    "Bibliothek" to "Biblioteek",
    "Bin manchmal unsicher" to "Ek is soms onseker",
    "Bist du ein Videospiel-Guru?" to "Is jy 'n videospeletjie-ghoeroe?",
    "Blumenwiese" to "Blommewei",
    "Bunte Blumenwiese" to "Kleurvolle blomweide",
    "Burger" to "Burgers",
    "Burger King" to "Burger King",
    "Chat" to "Gesels",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Koekiedeeg",
    "Dachgarten mit Lounge" to "Daktuin met sitkamer",
    "Dachterrasse" to "Dakterras",
    "Das Wetter an dem Tag" to "Die weer daardie dag",
    "Das erste Selfie" to "Die eerste selfie",
    "Das meiste weiß ich" to "Ek ken die meeste daarvan",
    "Das oder das?" to "Dit of dat?",
    "Das tägliche Leben" to "Daaglikse lewe",
    "Dass Zusagen gehalten werden" to "Dat beloftes nagekom word",
    "Dass alles meinen Stil hat" to "Dat alles my styl het",
    "Dass ich alles erzählen kann" to "Dat ek alles kan vertel",
    "Dass ich mich nicht sorgen muss" to "Dat ek nie hoef te bekommer nie",
    "Dass wir ungestört sind" to "Dat ons ongestoord is",
    "Dein Name" to "Jou naam",
    "Deine Antwort..." to "Jou antwoord...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Jou antwoorde is gestoor. Sodra Partner die pakket klaarmaak, sal albei antwoorde saam sigbaar wees.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Jou antwoorde is gestoor. Sodra \${profile.partnerName} die pakket voltooi het, sal albei antwoorde saam sigbaar wees.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Maak jou verhouding avontuurlik en spontaan",
    "Deine Beziehung stabil und sicher machen" to "Maak jou verhouding stabiel en veilig",
    "Deine eigene Antwort" to "Jou eie antwoord",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Dit is beter om jou diepste geheime met jou maat te deel",
    "Deinen besten Freund verlieren" to "Om jou beste vriend te verloor",
    "Denke an dich" to "Dink aan jouself",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Om dieselfde fliek twee keer te kyk, is 'n mors van tyd.",
    "Der Blick nach draußen" to "Die uitsig buite",
    "Der Garten" to "Die tuin",
    "Der Ort" to "Die plek",
    "Der Ring und die Geste" to "Die ring en die gebaar",
    "Der perfekte Heiratsantrag" to "Die perfekte huweliksaansoek",
    "Derjenige sein, der umarmt wird" to "Wees die een wat omhels word",
    "Deutsch" to "Duits",
    "Diamant" to "Diamant",
    "Diamanten im Band" to "Diamante in die band",
    "Die Distanz" to "Die afstand",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Spandeer die vakansie saam met jou maat se familie",
    "Die Gemütlichkeit und Ruhe" to "Die troos en vrede",
    "Die Menschen, die darin wohnen" to "Die mense wat daarin woon",
    "Die Umgebung und Atmosphäre" to "Die omgewing en atmosfeer",
    "Die Worte und Emotionen" to "Die woorde en emosies",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Die uiteindelike vermaak-trivia-uitdaging",
    "Diejenige sein, die umarmt" to "Wees die een wat drukkies",
    "Direkt ansprechen" to "Adres direk",
    "Diskussion" to "Bespreking",
    "Diskutiere vor dem Kinderkriegen" to "Bespreek voordat jy kinders kry",
    "Diskutiert eure Antworten" to "Bespreek jou antwoorde",
    "Disney" to "Disney",
    "Doch, schon mal" to "Ja, ja",
    "Draußen mit der Natur als Kulisse" to "Buite met die natuur as agtergrond",
    "Drei-Stein-Ring" to "Drie klip ring",
    "Du bist dran" to "Dit is jou beurt",
    "Du fehlst mir" to "Ek mis jou",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubai, VAE",
    "Dunkles Design" to "Donker tema",
    "Durch Berührung" to "Deur aanraking",
    "Durch Worte" to "Deur woorde",
    "Durch Zeit zu zweit" to "Deur tyd saam",
    "Durch kleine Gesten" to "Deur klein gebare",
    "Durchgeplant" to "Goed beplan",
    "ERGEBNISSE" to "RESULTATE",
    "Egal, Hauptsache gesund" to "Wat ook al, die belangrikste ding is gesond",
    "Ehepaar Leben" to "Getroude paartjie lewe",
    "Eher knapp" to "Eerder naby",
    "Eher nicht" to "Nie soseer nie",
    "Eher schwer" to "Nogal moeilik",
    "Eher schwierig" to "Nogal moeilik",
    "Eher zu" to "Meer soos",
    "Eifersucht ist ein Zeichen von Liebe." to "Jaloesie is 'n teken van liefde.",
    "Eigenes Gemüsebeet" to "Eie groentelappie",
    "Ein Abenteuer in einer neuen Stadt" to "'n Avontuur in 'n nuwe stad",
    "Ein Anker" to "'n Anker",
    "Ein Balkon oder Garten" to "'n Balkon of tuin",
    "Ein Filmabend" to "'n Fliekaand",
    "Ein Harmony-Meilenstein eurer Liebe." to "'n Harmonie-mylpaal van jou liefde.",
    "Ein Herz" to "'n Hart",
    "Ein Herz an der Tür" to "'n Hart by die deur",
    "Ein Jahr lang eine Fernbeziehung führen" to "Hou 'n langafstandverhouding vir 'n jaar",
    "Ein Kindheitsessen" to "'n Kindermaaltyd",
    "Ein Live-Musik-Konzert besuchen" to "Woon 'n lewendige musiekkonsert by",
    "Ein Museum besuchen" to "Besoek 'n museum",
    "Ein Spieleabend" to "'n Speletjieaand",
    "Ein Spieleabend mit Freunden" to "'n Spelaand saam met vriende",
    "Ein Urlaubsfoto" to "'n Vakansiefoto",
    "Ein aktives Abenteuer" to "'n Aktiewe avontuur",
    "Ein entspannender Spa-Tag" to "'n Ontspannende spa-dag",
    "Ein ganz normaler Alltagstag" to "'n Heeltemal normale alledaagse dag",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "'n Gesellige aand in die huis tydens 'n donderstorm",
    "Ein gemütliches Date drinnen" to "'n Gesellige afspraak binnenshuis",
    "Ein lustiges Bild" to "'n Snaakse prentjie",
    "Ein paar Handyfotos reichen" to "'n Paar selfoonfoto's is genoeg",
    "Ein paar Stunden" to "'n Paar uur",
    "Ein paar kulturelle Anklänge sind okay" to "'n Paar kulturele verwysings is in orde",
    "Ein romantischer Abend" to "'n Romantiese aand",
    "Ein romantisches Abendessen bei Kerzenlicht" to "'n Romantiese aandete by kerslig",
    "Ein romantisches Bild" to "'n Romantiese beeld",
    "Ein romantisches Picknick an einem schönen Ort" to "'n Romantiese piekniek op 'n pragtige plek",
    "Ein schwerer Moment, den wir geschafft haben" to "'n Moeilike oomblik wat ons reggekry het",
    "Ein tolles Date im Freien unter dem Mondlicht" to "'n Heerlike afspraak in die buitelug onder die maanlig",
    "Ein ungewöhnliches Gericht" to "'n Ongewone gereg",
    "Ein zufälliger Schnappschuss" to "'n Ewekansige kiekie",
    "Einander kennenlernen" to "Om mekaar te leer ken",
    "Eine Autoreise" to "'n Padreis",
    "Eine Brücke" to "'n Brug",
    "Eine Date-Nacht unter den Sternen" to "'n Afspraakaand onder die sterre",
    "Eine Million Dollar gewinnen" to "Wen 'n miljoen dollar",
    "Eine Million Dollar verdienen" to "Maak 'n miljoen dollar",
    "Eine Nacht in einem Club" to "'n Aand in 'n klub",
    "Eine Schokoladenverkostung" to "'n Sjokoladeproe",
    "Eine Wanderung mit Panoramablick machen" to "Neem 'n staptog met panoramiese uitsigte",
    "Eine Weinverkostung" to "'n Wynproe",
    "Eine gemeinsame Reise" to "'n Reis saam",
    "Eine gemütliche Nacht zu Hause" to "'n Gesellige aand by die huis",
    "Eine neue Sprache zu lernen ist einfach." to "Dit is maklik om 'n nuwe taal te leer.",
    "Einen Film anschauen" to "Kyk 'n fliek",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Praat vir 'n maand glad nie met mekaar nie",
    "Einen Tanzkurs besuchen" to "Neem 'n dansklas",
    "Einen Vergnügungspark erkunden" to "Verken 'n pretpark",
    "Einen Wellness-Tag" to "'n Welstandsdag",
    "Einen sehr emotionalen Partner haben" to "Om 'n baie emosionele maat te hê",
    "Einen sehr logischen Partner haben" to "Om 'n baie logiese vennoot te hê",
    "Einer zahlt alles" to "Een persoon betaal alles",
    "Einfach mehr Alltag" to "Eenvoudig meer alledaagse lewe",
    "Einfach nebeneinander sein" to "Wees net langs mekaar",
    "Einfach und intim" to "Eenvoudig en intiem",
    "Einige Dinge für dich behalten" to "Hou 'n paar dinge vir jouself",
    "Einmal" to "Een keer",
    "Eins, das nur wir kennen" to "Een wat net ons ken",
    "Englisch" to "Engels",
    "Entspannte Hängematte" to "Ontspanne hangmat",
    "Entspannung" to "Ontspanning",
    "Erdbeere" to "Aarbei",
    "Erfolgreich" to "Suksesvol",
    "Ergebnisse" to "Resultate",
    "Erst bei sehr großen Summen" to "Slegs vir baie groot bedrae",
    "Erst nur enge Freunde/Familie" to "Aanvanklik net goeie vriende/familie",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Dit irriteer my as my maat te lank neem om op boodskappe te reageer.",
    "Essen & Genuss" to "Kos en plesier",
    "Essensvorlieben" to "Kosvoorkeure",
    "Etwa eine Woche später, erst mal nur wir" to "Ongeveer 'n week later, eers net ons",
    "Etwas Neues ausprobieren" to "Probeer iets nuuts",
    "Etwas ganz anderes" to "Iets heeltemal anders",
    "Etwas sehr Scharfes" to "Iets baie skerp",
    "Etwas, das ich selbst gern erfinde" to "Iets wat ek graag self uitdink",
    "Etwas, eine kleine Note wäre schön" to "Iets, 'n klein nota sal lekker wees",
    "Familie" to "Familie",
    "Familie/Freunde" to "Familie/Vriende",
    "Familienmensch" to "Familieman",
    "Farbedelstein" to "Gekleurde edelsteen",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "TV-advertensies is soms interessant om te kyk.",
    "Fertig" to "Klaar",
    "Fertig!" to "Klaar!",
    "Feste Date-Nights" to "Vaste datum nagte",
    "Feuerstelle" to "Vuurput",
    "Filigran & schlicht" to "Filigraan en eenvoudig",
    "Filme/Serien" to "Flieks/reekse",
    "Formuliere um..." to "Herformuleer...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Herformuleer jou konsep op 'n nie-gewelddadige manier: waarneming, gevoel, behoefte, versoek.",
    "Frage hinzufügen" to "Voeg vraag by",
    "Fragen & Spiele" to "Vrae en speletjies",
    "Fragen für jede Gelegenheit" to "Vrae vir elke geleentheid",
    "Freizeitpark" to "Pretpark",
    "Freunde treffen" to "Ontmoet vriende",
    "Freundschaften mit Ex-Partnern sind okay." to "Vriendskappe met ekse is in orde.",
    "Früh aufstehen" to "Staan vroeg op",
    "Fußbodenheizung" to "Ondervloerse verhitting",
    "Führen wir getrennte oder gemeinsame Konten?" to "Het ons aparte of gesamentlike rekeninge?",
    "Für dich empfohlen" to "Vir jou aanbeveel",
    "Für die Zukunft" to "Vir die toekoms",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Geen ooreenstemmende vrae of speletjies is vir hierdie soektog gevind nie.",
    "Für immer" to "Vir altyd",
    "Fürsorglichkeit" to "Omgee",
    "GFK-Brücke" to "GRP-brug",
    "Galerie" to "Galery",
    "Gar nicht, der Moment gehört uns" to "Glad nie, die oomblik is ons s'n",
    "Gar nichts tun" to "Doen niks",
    "Geduld" to "Geduld",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Gaan vroeg in die oggend om die sonsopkoms te sien",
    "Geht so" to "Gaan so",
    "Geister existieren wirklich." to "Spoke bestaan regtig.",
    "Gelassenheit" to "Rustigheid",
    "Gelbgold" to "Geelgoud",
    "Geld & Finanzen" to "Geld & Finansies",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Reis die wêreld saam, verken nuwe kulture en kombuise",
    "Gemeinsam ein Lego bauen" to "Bou saam 'n Lego",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Probeer 'n nuwe resep saam in die kombuis",
    "Gemeinsame Konten" to "Gedeelde rekeninge",
    "Gemeinsame Nächte" to "Nagte saam",
    "Gemeinsame Tage" to "Dae saam",
    "Gemischt" to "Gemeng",
    "Gemüsebeet" to "Groentepleister",
    "Gemütliche Feuerstelle" to "Gesellige kaggel",
    "Gesprächsanreger" to "Gesprek beginner",
    "Getrennte Konten" to "Aparte rekeninge",
    "Getrennte Urlaube tun einer Beziehung gut." to "Aparte vakansies is goed vir 'n verhouding.",
    "Gewächshaus" to "Kweekhuis",
    "Glasfassade" to "Glasfasade",
    "Gleichgültigkeit" to "Onverskilligheid",
    "Glücklich und frei" to "Gelukkig en vry",
    "Gourmet Eis-Sorten" to "Gourmet-roomysvariëteite",
    "Gravur innen" to "Gravure binne",
    "Grillplatz" to "Braai area",
    "Groß & üppig" to "Groot en weelderig",
    "Große Familie" to "Groot familie",
    "Große Feier" to "Groot feesviering",
    "Große Fenster" to "Groot vensters",
    "Große Fensterfront" to "Groot venster voor",
    "Großer Außenpool" to "Groot buite swembad",
    "Großer Garten" to "Groot tuin",
    "Großer Stein" to "Groot klip",
    "Größere Küche" to "Groter kombuis",
    "Gutes Essen" to "Lekker kos",
    "Habe ich" to "Ek het",
    "Habe ich noch nie" to "Ek het nog nooit",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Het jy enige verrassende verskille ontdek? Praat oor hoekom jy van sekere opsies beter hou!",
    "Haus am See" to "Huis by die meer",
    "Haus/Wohnung" to "Huis/woonstel",
    "Hazelnut" to "Hazelnoot",
    "Heimkino" to "Tuis teater",
    "Herzhaft" to "Hartlik",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Hier is niks op die oomblik nie.\nVerander die filter of kies 'n ander onderwerp.",
    "Hilfe im Alltag" to "Hulp in die alledaagse lewe",
    "Himbeere" to "Framboos",
    "Hinzufügen" to "Voeg by",
    "Hobbys" to "Stokperdjies",
    "Hochzeitssträuße" to "Trouruikers",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Hogwarts Huistrots: Waar hoort jy?",
    "Home" to "Tuis",
    "Hot Tub" to "Bubbelbad",
    "Humor" to "Humor",
    "Hund" to "Hond",
    "Hängematte" to "Hangmat",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Wil jy 'n geskrewe brief hê as deel van die voorstel?",
    "IKEA" to "IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Ek verkies romantiese staptogte in die park as om na die bioskoop te gaan.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Ek het nog nooit in 'n bioskoop aan die slaap geraak nie.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Ek geniet dit om nuwe stokperdjies of aktiwiteite saam met my maat te ontdek.",
    "Ich finde eine Alternative" to "Ek sal 'n alternatief vind",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Ek geniet dit om nuwe restaurante saam met my maat te probeer in plaas daarvan om altyd na dieselfde plekke te gaan.",
    "Ich habe noch nie" to "Ek het nog nooit",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Ek was nog nooit bang vir 'n rollercoaster nie en ek het dit in elk geval aangepak.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Ek het nog nooit Fast Pass-kaartjies gekoop nie, want ek was ongeduldig.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Ek het nog nooit planne gekanselleer om tuis te bly en 'n TV-program te kyk nie.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Ek het nog nooit gewag vir my brief van Hogwarts nie.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Ek het nog nooit gesê dat Slytherin eintlik nie so erg was nie.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Ek het nog nooit gesê ek is te oud vir Disney-flieks nie (en het dit in die geheim geniet).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Ek het nog nooit opsetlik iemand met 'n blou tenk in Mario Kart neergeskiet nie.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Ek het nog nooit by 'n Disney-fliek gehuil nie.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Ek het nog nooit my oë toegemaak terwyl ek 'n gruwelfliek gekyk het nie.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Ek het nog nooit vergeet om 'n speletjie te stoor nie en het ure se vordering verloor.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Ek het nog nooit die kamer verlaat tydens 'n verleentheid nie (inkrimpende faktor).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Ek het nog nooit 'n snaakse pose gedoen terwyl ek 'n rollercoaster-foto geneem het nie.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Ek het nog nooit laat in die nag gespeel nie en was spyt hoe moeg ek die volgende dag was.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Ek het nog nooit die einde van 'n fliek gegoogle nie, want ek kon nie wag nie.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Ek het nog nooit gevoel of ek op 'n filmstel staan ​​nie.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Ek het nog nooit die inleiding van my gunstelingreeks oorgeslaan nie.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Ek het nog nooit iemand anders se Netflix-wagwoord gedeel nie.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Ek het nog nooit na 'n speletjie se klankbaan geluister terwyl ek gewerk of studeer het nie.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Ek het nog nooit die kontroleerder kwalik geneem toe ek verloor het nie.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Ek het nog nooit die sleutelbord of beheerder in woede weggegooi nie.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Ek het nog nooit vir 'n paar dae nat klere in die wasmasjien vergeet nie.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Ek het nog nooit regte geld spandeer op kosmetiese items in 'n speletjie nie.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Ek het nog nooit 'n motor in 'n vreemde land bestuur nie.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Ek het nog nooit 'n Disney-liedjie in die stort vasgebind nie.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Ek het nog nooit 'n elektriese motor bestuur nie.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Ek het nog nooit 'n foto met 'n park gelukbringer geneem nie.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Ek het nog nooit 'n troeteldier na 'n Hogwarts-karakter vernoem nie.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Ek het nog nooit springmielies in 'n fliekteater laat val nie en dit steeds geëet.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Ek het nog nooit 'n aanhaling van Meester Yoda van Star Wars in die alledaagse lewe gebruik nie.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Ek het nog nooit 'n te duur aandenking by 'n pretpark gekoop nie.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Ek het nog nooit 'n filmaanbeveling gegee wat die ander persoon verskriklik gevind het nie.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Ek het nog nooit 'n Oscars regstreeks in die middel van die nag gekyk nie.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Ek het nog nooit 'n reeks gekanselleer nie, want die laaste seisoen was so sleg.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Ek het nog nooit 'n hele seisoen van 'n reeks op een dag gekyk nie.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Ek het nog nooit 'n baas met die eerste probeerslag verslaan nie en het soos 'n god gevoel.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Ek het nog nooit 'n skurk koeler as die held gevind nie.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Ek het nog nooit 'n Toy Story-karakter in my eie speelgoed herken nie.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Ek het nog nooit 'n karakter in 'n RPG gemaak presies soos ek nie.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Ek het nog nooit 'n churro by 'n pretpark geëet nie.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Ek het nog nooit 'n Disney-rolprent drie keer in 'n ry gekyk nie.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Ek het nog nooit vir 'n hele week 'n pakkende Disney-deuntjie gehad nie.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Ek het nog nooit 'n rolprent gekyk net oor 'n sekere akteur nie.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Ek het nog nooit ure lank na 'n fliekklankbaan op herhaling geluister nie.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Ek het nog nooit 'n fliekbederf bekend gemaak nie en was dadelik spyt daaroor.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Ek het nog nooit 'n vriend gevind wat 'n ander moedertaal praat nie.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Ek het nog nooit 'n vriend gehad wat na 'n ander land verhuis het nie.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Ek het nog nooit 'n Harry Potter-fliekmarathon met Kersfees gedoen nie.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Ek het nog nooit 'n Marvel-fliek gekyk tot aan die einde nie, net as gevolg van die nakrediet-toneel.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Ek het nog nooit 'n NPC (Nie-speler-karakter) doelbewus vererg nie.",
    "Ich habe noch nie einen Nachtzug genommen." to "Ek het nog nooit 'n nagtrein geneem nie.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Ek het nog nooit 'n aanlyntoets afgelê om my Hogwarts-huis uit te vind nie.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Ek het nog nooit 'n plasing op sosiale media uitgevee nie, want dit het nie genoeg laaiks gekry nie.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Ek het nog nooit 'n dag by die pretpark die beste dag van die jaar genoem nie.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Ek het nog nooit 'n pretpark besoek nie en het van oggend tot aand daar gebly.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Ek het nog nooit 'n Transformers- of Marvel-rit heeltemal gefassineer gelaat nie.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Ek het nog nooit 'n woede opgehou en die speletjie verlaat nie.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Ek het nog nooit enige van die groot Harry Potter-bundels gelees nie.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Ek het nog nooit oor my gunstelingkarakter in 'n reeks geskok nie.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Ek het nog nooit daarvan gedroom om Kwiddiek te speel nie.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Ek het nog nooit in die geheim gegoogle hoe om 'n harde vlak op te los nie.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Ek het nog nooit heimlik gehoop dat my troeteldier kan praat soos in Disney nie.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Ek het nog nooit die swembadleier in Sims verwyder nie.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Ek het nog nooit my ore verloor in 'n 3D-simulatorrit nie.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Ek het nog nooit in 'n universiteitsportspan gespeel nie.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Ek het nog nooit meer as twee uur in die ry gewag vir 'n enkele besienswaardigheid nie.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Ek het nog nooit my waardevolle besittings natgemaak op 'n waterrit nie.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Ek het nog nooit met 'n vriend gestry oor watter huis die beste is nie.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Ek het nog nooit voorgegee ek het magiese kragte soos Elsa nie.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Ek het nog nooit so lekker gelag dat ek 'n belangrike toneel in 'n fliek gemis het nie.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Ek het nog nooit soveel adrenalien gevoel dat ek dadelik weer wou ry nie.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Ek het nog nooit saam met diere soos Sneeuwitjie probeer sing nie.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Ek het nog nooit gedroom van 'n reis na Disneyland nie.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Ek het nog nooit daarvan gedroom om die Jurassic Park-waterrit te ry nie.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Ek het nog nooit in 'n speletjie hardop geskree oor 'n skrikwekkende sprong nie.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Ek het nog nooit gehuil oor die finale van 'n TV-program nie.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Ek het nog nooit... 'n afspraak gekanselleer om tuis te bly nie.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Ek het nog nooit... 'n boodskap 10 keer herfraseer nie.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Ek het nog nooit... heimlik na my maat se selfoon gekyk nie.",
    "Ich habe noch nie!" to "Ek het nog nooit!",
    "Ich habe!" to "Ek het!",
    "Ich lache viel mit meinem Partner." to "Ek lag baie saam met my maat.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Ek hou daarvan om my maat se stokperdjies en belangstellings te leer ken.",
    "Ich liebe es" to "Ek is mal daaroor",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Ek is mal daaroor om saam met my maat flieks te kyk wat nie een van ons voorheen gesien het nie.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Ek is mal daaroor om my gunsteling musiek met my maat te deel.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Ek moes nog nooit hardloop om 'n verbindingsvlug te haal nie.",
    "Ich plane gerne Dates mit meinem Partner." to "Ek hou daarvan om afsprake met my maat te beplan.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Ek prioritiseer om tyd saam met my maat deur te bring, selfs wanneer ek besig is.",
    "Ich schreibe meinem Partner jeden Tag." to "Ek SMS my maat elke dag.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Ek deel graag memes en grappies met my maat.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Ek deel graag al die besonderhede van my dag met my maat.",
    "Ich würde es nie tun" to "Ek sal dit nooit doen nie",
    "Ich übe noch" to "Ek oefen steeds",
    "Ideen generieren" to "Genereer idees",
    "Im Haushalt helfen" to "Hulp om die huis",
    "In Chat einfügen" to "Voeg by klets",
    "In Stille nebeneinander" to "In stilte langs mekaar",
    "In den Bergen" to "In die berge",
    "In eine Bar gehen" to "Gaan na 'n kroeg",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Gaan na 'n strandkroeg om die sonsondergang te kyk",
    "In einem feinen Restaurant essen gehen" to "Uiteet in 'n goeie restaurant",
    "In einen Coffeeshop gehen" to "Gaan na 'n koffiewinkel",
    "In einer Beziehung sollte man alles voneinander wissen." to "In 'n verhouding behoort julle alles van mekaar te weet.",
    "Infinity-Pool" to "Oneindige swembad",
    "Innenpool" to "Binneshuise swembad",
    "Intelligenz" to "Intelligensie",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Hou net intieme oomblikke wanneer jou maat dit inisieer",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Uitnodigingskode: HRM-8731 · alles ontsluit",
    "Island" to "Ysland",
    "Ist okay für mich" to "Dit gaan goed met my",
    "Ist schon perfekt" to "Dit is perfek",
    "Ja, Traditionen einbinden" to "Ja, inkorporeer tradisies",
    "Ja, absolut" to "Ja, absoluut",
    "Ja, etwas zum Lesen und Aufbewahren" to "Ja, iets om te lees en te hou",
    "Ja, genug" to "Ja, genoeg",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Ja, in 'n opwindende stad of besienswaardigheid",
    "Ja, in- und auswendig" to "Ja, binne en buite",
    "Ja, komplett überraschend" to "Ja, heeltemal verbasend",
    "Ja, perfekt" to "Ja, perfek",
    "Ja, sie gehören zur Familie!" to "Ja, hulle is familie!",
    "Ja, sofort teilen" to "Ja, deel dadelik",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Ja, ons sal verseker dat gesinstyd 'n prioriteit is.",
    "Jacuzzi" to "Jacuzzi",
    "Jahr zusammen 🎉" to "jaar saam 🎉",
    "Jahre zusammen 🎉" to "Jare saam 🎉",
    "Jeder zahlt 50%" to "Almal betaal 50%",
    "Junge" to "Seun",
    "Kamin" to "Kaggel",
    "Karriere & Erfolg" to "Loopbaan en sukses",
    "Kategorien" to "Kategorieë",
    "Katze" to "Kat",
    "Keine Musik" to "Geen musiek nie",
    "Keine Party nötig, privat halten" to "Nie nodig vir 'n partytjie nie, hou dit privaat",
    "Keine Privatsphäre" to "Geen privaatheid nie",
    "Keine Treffer gefunden" to "Geen passings gevind nie",
    "Keiner" to "Geen",
    "Keiner von uns" to "Nie een van ons nie",
    "Kennst du die Essensvorlieben deines Partners?" to "Ken jy jou maat se kosvoorkeure?",
    "Kino" to "bioskoop",
    "Kirchlich" to "Kerklik",
    "Klassisch Solitär" to "Klassieke solitaire",
    "Klassisch gebunden" to "Klassiek gebind",
    "Klein & zart" to "Klein & delikaat",
    "Kleine Geschenke" to "Klein geskenkies",
    "Kleine Runde" to "Klein ronde",
    "Kochen und Freunde einladen" to "Kook en nooi vriende",
    "Kochkurs" to "Kookklas",
    "Kommt auf den Tag an" to "Hang af van die dag",
    "Kommt darauf an" to "Hang af van",
    "Kommt drauf an" to "Dit hang af",
    "Kommt mit" to "Kom saam met my",
    "Konzert" to "konsert",
    "Kräftige Farben" to "Sterk kleure",
    "Kräuterbeet" to "Kruiebed",
    "Kultur & Sehenswürdigkeiten" to "Kultuur & Besienswaardighede",
    "Kuscheln" to "Knuffel",
    "Kuss senden" to "Stuur soen",
    "Körperliche Annäherung" to "Fisiese benadering",
    "Körperliche Nähe" to "Fisiese nabyheid",
    "Küche" to "Kombuis",
    "Land" to "Land",
    "Landhaus" to "Plattelandshuis",
    "Landhausstil" to "Plattelandse huisstyl",
    "Lange wach bleiben" to "Bly laat op",
    "Lappland" to "Lapland",
    "Lappland, Finnland" to "Lapland, Finland",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Laat jou maat jou inspireer om jou beste self te wees",
    "Lehne ab" to "Weier",
    "Leichtigkeit" to "Ligheid",
    "Leidenschaft" to "Passie",
    "Liebe im Gleichgewicht" to "Liefde in balans",
    "Liebe sie, macht mehr Spaß" to "Hou van hulle, meer pret",
    "Lieber durchgeplant oder spontan?" to "Sou jy dit eerder planmatig of spontaan wou hê?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Wil jy eerder 'n rustige aand vir twee hê of saam met mense?",
    "Lieber nicht" to "Beter nie",
    "Lieber vorher grob absprechen" to "Dit is beter om dinge vooraf rofweg te bespreek",
    "Lokal einkaufen" to "Koop plaaslik",
    "London" to "Londen",
    "London, England" to "Londen, Engeland",
    "Lügen" to "Lieg",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Verkies jy 'n openbare of private voorstel?",
    "Malediven" to "Maldive",
    "Man sollte nie streitend einschlafen." to "Jy moet nooit aan die slaap raak terwyl jy stry nie.",
    "Mango Sorbet" to "Mango sorbet",
    "Markant & breit" to "Opvallend & wyd",
    "Marken & Alltag" to "Handelsmerke en alledaagse lewe",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "Mediterreense binnehof",
    "Mehr Unterstützung" to "Meer ondersteuning",
    "Mehr gemeinsame Zeit" to "Meer tyd saam",
    "Mehr zuhören" to "Luister meer",
    "Mehrgenerationenhaus" to "Multi-generasie huis",
    "Mein Arbeitsplatz" to "My werkplek",
    "Mein Partner" to "My maat",
    "Mich überraschen" to "Verras my",
    "Minimalistisches Interieur" to "Minimalistiese interieur",
    "Missverständnisse" to "Misverstande",
    "Mit Familie und engen Freunden" to "Saam met familie en goeie vriende",
    "Mit Kompromissen" to "Met kompromieë",
    "Mitgefühl" to "Deernis",
    "Mittelweg mit besonderen Details" to "Middelgrond met spesiale besonderhede",
    "Modern geometrisch" to "Moderne meetkunde",
    "Moderne Grillstation" to "Moderne braaistasie",
    "Moderner Name" to "Moderne naam",
    "Moderner Solitär" to "Moderne solitaire",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "Vang die oomblik vas",
    "Momente" to "oomblikke",
    "Monaco" to "Monaco",
    "Moralische Werte" to "Morele waardes",
    "Museum" to "Museum",
    "Musik" to "Musiek",
    "Mut" to "Moed",
    "Mädchen" to "Meisies",
    "Möbelhaus" to "Meubelwinkel",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Is jy seker jy wil die vasvra verlaat? Jou vorige vordering bly gestoor.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Wil jy hê troeteldiere moet by die aansoek ingesluit word?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Wil jy hê dat die oomblik onmiddellik op sosiale media gedeel moet word?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Ons sal dalk moet spaar",
    "Müssen es planen" to "Moet dit beplan",
    "Müssen sparen" to "Moet spaar",
    "Nachricht an" to "Boodskap",
    "Name Partnerin" to "Naam van vennoot",
    "Namen und Startdatum eurer Beziehung." to "Name en begindatum van jou verhouding.",
    "Natursteinfassade" to "Fasade van natuurlike klip",
    "Naturteich" to "Natuurlike dam",
    "Nein, einfach halten" to "Nee, hou net vas",
    "Nein, erstmal privat halten" to "Nee, hou dit vir eers privaat",
    "Nein, lieber vor Ort" to "Nee, beter op die terrein",
    "Nein, modern halten" to "Nee, hou dit modern",
    "Nein, nur wir" to "Nee, net ons",
    "Nein, zu ablenkend" to "Nee, te steurend",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Nuwe gebou met slim huis",
    "Neubau mit Technik" to "Nuwe gebou met tegnologie",
    "Neue Liebe, neue Erfahrungen" to "Nuwe liefde, nuwe ervarings",
    "Neues Hobby" to "Nuwe stokperdjie",
    "Neues Spiel" to "Nuwe speletjie",
    "Neugier" to "Nuuskierigheid",
    "New York" to "New York",
    "New York, USA" to "New York, VSA",
    "Nicht mein Fall" to "Nie my koppie tee nie",
    "Nicht nötig, lieber klassisch bleiben" to "Nie nodig nie, dis beter om klassiek te bly",
    "Nichts — es passt so" to "Niks – dit pas",
    "Nie wieder Burger" to "Nooit weer burgers nie",
    "Nie wieder Pizza" to "Nooit weer pizza nie",
    "Niemand" to "Niemand nie",
    "Niemand ohne Plan" to "Niemand sonder 'n plan nie",
    "Nike" to "Nike",
    "Nizza" to "Lekker",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Nog geen oomblikke nie.\nVad jou eerste ervaring vas 💞",
    "Nur bei wichtigen Themen" to "Slegs oor belangrike onderwerpe",
    "Nur wir beide" to "Net ons twee",
    "Nähe & Intimität" to "Nabyheid & intimiteit",
    "Obstgarten" to "boord",
    "Oder" to "Of",
    "Offene Küche" to "Oop kombuis",
    "Offene Wohnküche" to "Oop kombuis/sitkamer",
    "Ohne Stein" to "Sonder klip",
    "Open End" to "Oop einde",
    "Outdoor-Küche" to "Buitekombuis",
    "Outdoor-Sofa" to "Buitelugbank",
    "Outdoor-Whirlpool" to "Buitelugkolk",
    "Ovaler Diamant" to "Ovaal diamant",
    "Paar" to "Paar",
    "Paar-Statistiken" to "Paar statistieke",
    "Paris" to "Parys",
    "Paris, Frankreich" to "Parys, Frankryk",
    "Partner" to "vennoot",
    "Partner-Simulator" to "Vennoot simulator",
    "Partnerin" to "vennoot",
    "Party Edition" to "Party uitgawe",
    "Party Edition II" to "Party Uitgawe II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Pas 'n dier selfs in ons alledaagse lewe?",
    "Pasta" to "pasta",
    "Pastell" to "Pastel",
    "Penthouse mit Ausblick" to "Dakwoonstel met 'n uitsig",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pergola met sitkamer",
    "Pfingstrosen" to "Pioene",
    "Pinguin" to "Pikkewyn",
    "Pistazie" to "Pistache",
    "Pizza" to "Pizza",
    "Pizzaofen" to "Pizza oond",
    "Platin" to "Platinum",
    "PlayStation" to "PlayStation",
    "Pool" to "Swembad",
    "Pop" to "Pop",
    "Prasselnder Kamin" to "Brullende kaggel",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Prinsesse, seerowers en feetjiestof: Disney Vasvra",
    "Privater Innenhof" to "Privaat binnehof",
    "Profil" to "Profiel",
    "Profil bearbeiten" to "Wysig profiel",
    "Prozentual nach Einkommen" to "Persentasie gebaseer op inkomste",
    "Quiz verlassen" to "Hou op vasvra",
    "Quiz verlassen?" to "Los vasvra?",
    "Rausgehen in die Natur" to "Gaan uit in die natuur",
    "Reden vor ..." to "Praat met...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Beplan gereelde datums of tyd saam",
    "Reisen" to "Reis",
    "Reiseziele" to "Reisbestemmings",
    "Respektlosigkeit" to "Disrespek",
    "Restaurant" to "Restaurant",
    "RnB / Soul" to "RnB / Soul",
    "Rock" to "Rock",
    "Rom" to "Rome",
    "Rom, Italien" to "Rome, Italië",
    "Romantik" to "Romanse",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Romantiese gebare soos boodskappe, notas of geskenke maak my gelukkig.",
    "Romantische Stimmung" to "Romantiese bui",
    "Roségold" to "Roosgoud",
    "Ruhig zu zweit" to "Stil vir twee",
    "Runder Diamant" to "Ronde diamant",
    "Salted Caramel" to "Gesoute karamel",
    "Sammle Ideen..." to "Versamel idees...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Griekeland",
    "Saphir" to "Sapphire",
    "Saunahaus" to "Saunahuis",
    "Schickes Restaurant oder Hotel" to "Sjiek restaurant of hotel",
    "Schlafzimmer" to "Slaapkamer",
    "Schließen" to "Sluit",
    "Schmal & zart" to "Skraal en delikaat",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Foto's uit ons liefdesverhaal",
    "Schokolade" to "Sjokolade",
    "Schreib frei, was dir wirklich dazu einfällt." to "Skryf vrylik wat werklik by jou opkom.",
    "Schreibe deine eigene Antwort" to "Skryf jou eie antwoord",
    "Sehr gerne" to "Jy is welkom",
    "Sehr leicht" to "Baie lig",
    "Sehr wichtig — Fotos und Video" to "Baie belangrik — foto's en video",
    "Sehr wichtig, es sollte persönlich sein" to "Baie belangrik, dit moet persoonlik wees",
    "Selbst kochen" to "Kook self",
    "Senden" to "Stuur",
    "Separate Küche" to "Aparte kombuis",
    "Serie schauen" to "Kyk na die reeks",
    "Serienmarathon auf dem Sofa" to "Reeks marathon op die bank",
    "Sex & Liebe" to "Seks en liefde",
    "Seychellen" to "Seychelle",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Is ons in staat om alle kostes vir een kind/veelvuldige kinders te dek? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Moet die voorstel 'n verrassing wees?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Moet die aansoek kulturele of tradisionele elemente bevat?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Moet die aansoek kulturele of tradisionele elemente bevat?",
    "Sommerhochzeit" to "Somer troue",
    "Sonnige Dachterrasse" to "Sonnige dakterras",
    "Sowohl als auch" to "Beide en",
    "Spazieren" to "Gaan stap",
    "Spaß & Abenteuer" to "Pret en avontuur",
    "Speichern" to "Stoor",
    "Spiel bearbeiten" to "Wysig speletjie",
    "Spielbereich für Kinder" to "Speelarea vir kinders",
    "Spiele" to "speletjies",
    "Spiele spielen und Spaß haben" to "Speel speletjies en geniet dit",
    "Spontan" to "Spontaan",
    "Sportplatz" to "Sportveld",
    "Spotify" to "Spotify",
    "Sprache" to "Taal",
    "Stadt" to "Stad",
    "Stadt oder Land — was ist uns wichtiger?" to "Stad of land - wat is vir ons belangriker?",
    "Stadtvilla" to "Stadsvilla",
    "Standesamt & Party" to "Registerkantoor en party",
    "Statement-Ring" to "Verklaring ring",
    "Stilvolles Outdoor-Sofa" to "Stylvolle buitelugbank",
    "Stimme voll zu" to "Stem heeltemal saam",
    "Stimmt" to "Reg",
    "Stimmt nicht" to "Nie waar nie",
    "Stimmt, noch nie" to "Waar, nooit",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Stranddag",
    "Streit über Haushalt" to "Dispuut oor huishouding",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "Voortdurend",
    "Suche schließen" to "Maak soektog toe",
    "Suche zurücksetzen" to "Stel soektog terug",
    "Suche öffnen" to "Maak soektog oop",
    "Suchergebnisse" to "Soekresultate",
    "Sushi" to "Soesji",
    "Süß" to "Soet",
    "Tage zusammen 💞" to "dae saam 💞",
    "Tauche ins Unterbewusstsein" to "Duik in die onderbewussyn",
    "Teile alle deine Hobbys mit deinem Partner" to "Deel al jou stokperdjies met jou maat",
    "Teils teils" to "Gedeeltelik gedeeltelik",
    "Testen" to "Toets",
    "Themen" to "Onderwerpe",
    "Tiefe Gespräche" to "Diep gesprekke",
    "Tiefgründige Gespräche führen" to "Hou diep gesprekke",
    "Tierpension" to "Diere koshuis",
    "Tiny House" to "Klein Huisie",
    "Tippen zum Auswählen & Scrollen" to "Tik om te kies en te blaai",
    "Tippen zum Zuklappen" to "Tik om in te vou",
    "Titel" to "Titel",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Titel, Kategorie, Onderwerp, Merkers, Vrae...",
    "Tokyo, Japan" to "Tokio, Japan",
    "Traditioneller Name" to "Tradisionele naam",
    "Traumhaus Außenbereich" to "Droomhuis buite area",
    "Traumhochzeit" to "Droomtroue",
    "Treffer" to "Tref",
    "Tägliche Aktivität" to "Daaglikse aktiwiteit",
    "Umformulieren" to "Herformuleer",
    "Unbeantwortet" to "Onbeantwoord",
    "Unbeliebte Meinungen" to "Ongewilde opinies",
    "Universal Studios Genie oder Neuling?" to "Universal Studios genie of nuweling?",
    "Uns auseinanderzuleben" to "Om uitmekaar te groei",
    "Unser Intimleben" to "Ons intieme lewe",
    "Unser Traumhaus" to "Ons droomhuis",
    "Unser erstes Treffen" to "Ons eerste ontmoeting",
    "Unsere Gesichter" to "Ons gesigte",
    "Unsere eigenen Träume" to "Ons eie drome",
    "Unsere nächste Reise" to "Ons volgende reis",
    "Unter 1000" to "Onder 1000",
    "Unter 1000 im Monat" to "Onder 1000 per maand",
    "Unter 50€/Monat" to "Onder 50€/maand",
    "Unter Leuten" to "Onder mense",
    "Untreue" to "Ontrouheid",
    "Urlaub" to "Vakansie",
    "Vanille" to "Vanielje",
    "Venedig" to "Venesië",
    "Venedig, Italien" to "Venesië, Italië",
    "Verbinde dich mit" to "Maak kontak met",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Koppel aan \${profile.partnerName} om die antwoord te sien",
    "Verbindung" to "verbinding",
    "Verbringe die Feiertage mit deiner Familie" to "Spandeer die vakansie saam met jou gesin",
    "Verlobungsringe" to "Verloofringe",
    "Vertrautheit" to "Vertroudheid",
    "Viel getrennt" to "Baie skeiding",
    "Vielleicht ein oder zwei" to "Miskien een of twee",
    "Vielleicht, aber mündlich reicht" to "Miskien, maar verbaal is genoeg",
    "Vielleicht, wenn es machbar ist" to "Miskien, as dit moontlik is",
    "Vielleicht, wenn es passt" to "Miskien, as dit pas",
    "Vintage Art déco" to "Vintage Art Deco",
    "Vintage verspielt" to "Oesjaar speels",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Om deur jou maat aan nuwe stokperdjies bekendgestel te word",
    "Vor dem Kauf eines Hauses besprechen" to "Bespreek voor jy 'n huis koop",
    "Vor der Anschaffung eines Haustiers besprechen" to "Bespreek voor jy 'n troeteldier koop",
    "Vor der gemeinsamen Reise besprechen" to "Bespreek voordat jy saam reis",
    "Vor nichts" to "Niks nie",
    "Vorort" to "Voorstad",
    "Walnuss" to "Okkerneut",
    "Wandern" to "Stap",
    "Wann fühlst du dich mir am nächsten?" to "Wanneer voel jy die naaste aan my?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Wanneer voel jy fisiek die naaste aan my?",
    "Was bedeutet Vertrauen für dich konkret?" to "Wat beteken vertroue spesifiek vir jou?",
    "Was entspannt dich mehr?" to "Wat ontspan jou meer?",
    "Was fehlt dir über die Distanz am meisten?" to "Wat mis jy die meeste omtrent die afstand?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Waarvan hou jy die meeste van jou huis?",
    "Was hast du von deinem Partner gelernt?" to "Wat het jy by jou maat geleer?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Wat dink jy daarvan om saam na erotiese inhoud te kyk?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Wat dink jy van rekwisiete (bv. tekens, ballonne, ens.)?",
    "Was ist das Wichtigste beim Antrag?" to "Wat is die belangrikste wanneer jy aansoek doen?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Wat is die belangrikste ding waarna jy soek in 'n seksuele ontmoeting?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Wat is jou gunsteling foto van ons? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Wat is jou grootste vrees om saam te woon?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Wat is 'n kos waarvan jy hou, maar jou maat nie kan verstaan ​​nie?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Wat is 'n absolute dealbreaker vir jou?",
    "Was ist für jeden von uns das absolute Highlight?" to "Wat is die absolute hoogtepunt vir elkeen van ons?",
    "Was ist passiert?" to "Wat het gebeur?",
    "Was macht einen Moment für dich romantisch?" to "Wat maak 'n oomblik romanties vir jou?",
    "Was magst du an deinem Partner am liebsten?" to "Waarvan hou jy die meeste van jou maat?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Wat verkies jy: vroeg opstaan ​​of laat opbly?",
    "Was magst du lieber?" to "Waarvan hou jy beter?",
    "Was möchtest du eigentlich sagen?" to "Wat wil jy eintlik sê?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Wat sou jy graag wou hê moet jou maat meer gereeld doen?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Wat gebeur met die dier wanneer ons reis?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Wat gaan van ons kind word wanneer hy of sy groot is?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Wat moet ons nooit as ouers uit die oog verloor nie?",
    "Was war dein schönster Moment mit mir bisher?" to "Wat was jou beste oomblik saam met my tot dusver?",
    "Was wir gegessen haben" to "Wat ons geëet het",
    "Was wollt ihr nie vergessen?" to "Wat wil jy nooit vergeet nie?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Wat sal erger vir jou wees: nooit weer pizza of nooit weer burgers nie?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Wat sou jy die graagste wou doen op 'n dag saam?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Wat sou jy dadelik verander as geld nie 'n probleem was nie?",
    "Weiter" to "Volgende",
    "Weiter spielen" to "Gaan voort speel",
    "Weiß ich noch nicht" to "Ek weet nog nie",
    "Weiße Rosen" to "Wit rose",
    "Weißgold" to "Witgoud",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Watter kwaliteit moet ons kind beslis van ons kry?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Watter omgewing sou jy vir 'n voorstel wou hê?",
    "Welcher Raum sagt am meisten über dich aus?" to "Watter kamer sê die meeste van jou?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Watter begroting beplan ons vir kos en veearts?",
    "Welches Lied macht dich an? 🥵" to "Watter liedjie maak jou aan? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Watter gedeelde foto is jou gunsteling?",
    "Wellnessbad" to "Welstandsbad",
    "Wenn es schwierig ist" to "Wanneer dinge moeilik is",
    "Wenn ich müde bin" to "As ek moeg is",
    "Wenn wir uns lange umarmen" to "Wanneer ons lank druk",
    "Wenn wir zusammen lachen" to "Wanneer ons saam lag",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Wie besluit vinniger wat om te bestel?",
    "Wer findet die besten Restaurants?" to "Wie vind die beste restaurante?",
    "Wer gibt mehr Herzlichkeit?" to "Wie gee meer warmte?",
    "Wer hat den besseren Musikgeschmack?" to "Wie het 'n beter smaak in musiek?",
    "Wer hängt mehr an seinen Eltern?" to "Wie is meer geheg aan hul ouers?",
    "Wer ist besser organisiert?" to "Wie is beter georganiseer?",
    "Wer ist der Beste bei der Filmauswahl?" to "Wie is die beste om films te kies?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Wie is die beste om romantiese afsprake te beplan?",
    "Wer ist der beste Tänzer?" to "Wie is die beste danser?",
    "Wer ist romantischer?" to "Wie is meer romanties?",
    "Wer kocht besser?" to "Wie kook beter?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Wie sorg vir opknapping en instandhouding?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Wie merk vinniger op wanneer die ander persoon nie goed voel nie?",
    "Wer sucht am Ende wirklich den Film aus?" to "Wie kies regtig die film op die ou end?",
    "Wer vergisst eher einen Jahrestag?" to "Wie is meer geneig om 'n herdenking te vergeet?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Wie sal die volgende oggend meer geneig wees om hul eie naam te vergeet?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Wie sal meer geneig wees om die volgende dag 'n video te vind waarvan hulle niks weet nie?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Wie sal eerder die nag op 'n vreemdeling se bank deurbring?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Wie sal meer geneig wees om by 'n partytjie aan die slaap te raak en wakker te word met Sharpie op hul gesig?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Wie sal meer geneig wees om op die dansvloer te gly, maar dit na 'n koel beweging te laat lyk?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Wie is meer geneig om beheer oor die Spotify-snitlys by 'n huispartytjie te neem?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Wie sal meer geneig wees om pizza vir almal by 'n partytjie te bestel en dit self te eet?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Wie is meer geneig om eerste by 'n partytjie aan die slaap te raak?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Wie sal meer geneig wees om skielik by 'n partytjie te begin skoonmaak?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Wie sal meer geneig wees om te beweer dat hy heeltemal nugter is as die teenoorgestelde waar is?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Wie is meer geneig om eerste in 'n argument te gee?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Wie is meer geneig om te kul by 'n drankspeletjie?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Wie sal meer geneig wees om die buffet te stroop en kos in die geheim huis toe te neem?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Wie sal meer geneig wees om die mees verleentheid foto van die aand in hul storie te plaas?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Wie sal meer geneig wees om die DJ te irriteer om hul eie gunsteling liedjie aan te vra?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Wie sal meer geneig wees om die lirieke van 'n liedjie af te sing, maar met oortuiging?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Wie sal meer geneig wees om die duurste drankie op die spyskaart te bestel en daaroor spyt te wees?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Wie sal meer geneig wees om die bure oor te nooi as hulle oor die geraas kla?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Wie sal partytjiespeletjies (soos Beer Pong) te ernstig opneem?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Wie sal meer geneig wees om die uitsmyters te bevriend om BBP-toegang te kry?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Wie sal meer geneig wees om 'n spontane karaoke-stryd te begin?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Wie is meer geneig om 'n bottel oop te maak sonder om 'n botteloopmaker te gebruik?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Wie sal meer geneig wees om 'n toespraak te hou al het absoluut niemand gevra nie?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Wie sal meer geneig wees om 'n uur in die badkamer deur te bring om selfies te neem?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Wie sal meer geneig wees om 'n verleentheid te lewer en dit te vier?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Wie sal meer geneig wees om 'n voormalige vennoot te bel nadat die partytjie verby is?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Wie is meer geneig om 'n vreemde gas per ongeluk aanstoot te gee?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Wie sou meer geneig wees om die partytjie in die geheim te verlaat sonder om totsiens te sê?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Wie sal eerder met die gasheer se troeteldier speel as om met die gaste te praat?",
    "Wer würde eher spontan eine Reise buchen?" to "Wie sal meer geneig wees om spontaan 'n reis te bespreek?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Wie sal meer geneig wees om ure lank diep gesprekke in die kombuis te hê?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Wie is meer geneig om per ongeluk iemand anders se drankie te drink?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Wie is meer geneig om 'n duur vaas of iets broos per ongeluk om te slaan?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Wie sal meer geneig wees om self 'n ingewikkelde skemerkelkie te probeer meng en jammerlik misluk?",
    "Wer würde eher zu spät kommen?" to "Wie is meer geneig om laat te wees?",
    "Wer würde eher?" to "Wie wil eerder?",
    "Wer übernimmt die tägliche Versorgung?" to "Wie sorg vir die daaglikse versorging?",
    "Werde so akzeptiert, wie du bist" to "Word aanvaar soos jy is",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Sal ons genoeg tyd hê vir die kind/kinders? ⏳",
    "Whirlpool" to "Warmbad",
    "White Chocolate" to "Wit Sjokolade",
    "Widgets" to "Widgets",
    "Wie fühlst du dich am meisten geliebt?" to "Hoe voel jy die meeste geliefd?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Hoe hanteer ons verskillende inkomste?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Wat is die beste manier vir jou maat om seks met jou te begin?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Hoe kan jou maat 'n selfs beter maat vir jou wees?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Hoe lank na die voorstel wil jy saam met ander vier?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Hoe lank wil ons ten minste daar bly?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Hoe maklik is dit vir jou om oor wense te praat?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Hoe wil jy hê moet ons toekoms lyk?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Hoe lyk jou perfekte Sondag by die huis?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Hoe voel jy oor vuil praatjies tydens seks?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Hoeveel krediet kan ons realisties bekostig?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Hoeveel tyd wil ons apart spandeer?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Hoeveel wil ons in totaal spandeer?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Hoe sal ons tyd kry vir ons verhouding sodra die baba kom?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Hoe belangrik is dit vir jou dat die oomblik vasgevang word?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Hoe belangrik is dit vir jou dat die aansoek jou stokperdjies of belangstellings weerspieël?",
    "Wie würdest du sie/ihn nennen?" to "Wat sou jy hom/haar noem?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Wat is jou gunsteling manier om liefde buite seks te toon?",
    "Wildblumen" to "Veldblomme",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Wil jy 'n meisie of 'n seun hê? 👶",
    "Wintergarten" to "Wintertuin",
    "Winterhochzeit" to "Winter troue",
    "Wir bestellen einfach beides" to "Ons bestel net albei",
    "Wir brauchen ewig" to "Dit neem ons vir ewig",
    "Wir einigen uns nie" to "Ons stem nooit saam nie",
    "Wir entscheiden es gemeinsam" to "Ons besluit saam",
    "Wir treffen uns in der Mitte" to "Ons ontmoet in die middel",
    "Wir wechseln uns ab" to "Ons maak beurte",
    "Wird stressig" to "Raak stresvol",
    "Wobei lachst du am meisten?" to "Wat laat jou die meeste lag?",
    "Wofür sparen wir gemeinsam?" to "Waarvoor spaar ons saam?",
    "Wohnzimmer" to "Sitkamer",
    "Woran erinnerst du dich am lebhaftesten?" to "Wat onthou jy die lewendigste?",
    "Worauf freust du dich bei uns am meisten?" to "Waarna sien jy die meeste uit saam met ons?",
    "Worte/Komplimente" to "Woorde/komplimente",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Waarvoor is jy die bangste in ons verhouding?",
    "Wünsche? z.B. günstig, draußen" to "Wense? bv. goedkoop, buite",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Sou jy verkies om op vakansie voor te stel (wat reis behels)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube Musiek",
    "Zeichne für mich" to "Teken vir my",
    "Zeichne mich als Tier — welches wäre ich?" to "Teken my as 'n dier - wat sou ek wees?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Teken ons gevoelens teenoor mekaar as 'n simbool.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Teken ons droomhuis in een lyn. Wat is die treffendste ding?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Teken ons eerste afspraak – wat moet beslis in die prentjie wees?",
    "Zeichnen" to "Teken",
    "Zeit füreinander" to "Tyd vir mekaar",
    "Zeit, wenn das Baby schläft" to "Tyd wanneer die baba slaap",
    "Zelten gehen" to "Gaan kamp",
    "Zitrone" to "Suurlemoen",
    "Zu Hause, gemütlich und privat" to "By die huis, knus en privaat",
    "Zu einem Picknick gehen" to "Gaan na 'n piekniek",
    "Zu einem ausgefallenen Abendessen gehen" to "Gaan na 'n spoggerige aandete",
    "Zu zweit reisen" to "Reis as 'n paartjie",
    "Zuhause & Alltag" to "Huis en alledaagse lewe",
    "Zuhören" to "Luister",
    "Zurück" to "Terug",
    "Zusammen seit" to "Sedertdien saam",
    "Zusammen seit (TT.MM.JJJJ)" to "Saam sedert (DD.MM.JJJJ)",
    "Zusammenziehen" to "Kontrak",
    "Zustimmen oder Ablehnen" to "Stem saam of stem nie saam nie",
    "Zwei Kreise, die sich überschneiden" to "Twee sirkels wat oorvleuel",
    "Zwei Stühle davor" to "Twee stoele daarvoor",
    "Zärtlich sein" to "Wees sag",
    "Öfter als ich zugebe" to "Meer kere as wat ek erken",
    "Über 100€/Monat" to "Meer as 100€/maand",
    "Über 2000 im Monat" to "Meer as 2000 per maand",
    "Über mich selbst" to "Oor myself",
    "Übernehmen" to "Doen aansoek",
    "Überraschend" to "Verbasend",
    "Überraschung" to "Verrassing",
    "Überspringen" to "Slaan oor",
    "Übertrieben und großartig" to "Oor die top en ongelooflik",
    "✎ Tippe, um zu antworten" to "✎ Tik om te antwoord",
    "✨ GFK-Brücke" to "✨ GRP-brug",
)

internal fun localizeAfrikaansDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_AFRIKAANS_CONTENT)
