package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_AMHARIC_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 ዓመታት",
    "1000 - 1500 im Monat" to "1000 - 1500 በወር",
    "1000 bis 3000" to "ከ1000 እስከ 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 በወር",
    "3000 bis 5000" to "ከ3000 እስከ 5000",
    "5-10 Jahre" to "5-10 ዓመታት",
    "50-100€/Monat" to "50-100€ በወር",
    "Ab 100€" to "ከ100€",
    "Ab 500€" to "ከ 500€",
    "Ab 50€" to "ከ50€",
    "Ab und zu" to "በየጊዜው",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "ከመግዛታችን በፊት ምን ያህል ማውጣት አለብን?",
    "Abbrechen" to "ሰርዝ",
    "Abenteuer" to "ጀብዱ",
    "Adidas" to "አዲዳስ",
    "Aktivitäten" to "እንቅስቃሴዎች",
    "Alle" to "ሁሉም",
    "Alle Pakete" to "ሁሉም ጥቅሎች",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "ከእርስዎ የቅርብ ጓደኛ በስተቀር ሁሉንም ጓደኞችዎን ያጡ",
    "Alle intimen Momente selbst initiieren" to "ሁሉንም የቅርብ ጊዜዎች እራስዎ ይጀምሩ",
    "Alles davon" to "ሁሉም",
    "Alles, was noch kommt" to "የሚመጣው ሁሉ",
    "Alltagsroutine" to "የዕለት ተዕለት እንቅስቃሴ",
    "Alltägliche Berührungen" to "ዕለታዊ ንክኪዎች",
    "Altbau mit Charme" to "የድሮ ሕንፃ በማራኪ",
    "Am Strand" to "በባህር ዳርቻ ላይ",
    "Am liebsten alles zusammen" to "ቢቻል ሁሉም ነገር አንድ ላይ",
    "Am selben Tag mit Freunden/Familie" to "በተመሳሳይ ቀን ከጓደኞች/ቤተሰብ ጋር",
    "Amazon" to "Amazon",
    "Amsterdam" to "አምስተርዳም",
    "Amsterdam, Niederlande" to "አምስተርዳም፣ ኔዘርላንድስ",
    "An das Gefühl" to "ስለ ስሜቱ",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "ብዙ ተመልካቾች ባሉበት ህዝባዊ ቦታ ላይ",
    "An einen Geruch" to "የማሽተት",
    "An einen Song" to "ወደ ዘፈን",
    "An etwas, das ich gesagt habe" to "ያልኩት ነገር",
    "Analyse starten" to "ትንተና ጀምር",
    "Analysiere eure Muster..." to "ቅጦችዎን ይተንትኑ...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "በGottman እና GFK መሰረት የእርስዎን መልሶች እና ውይይቶች ይተንትኑ።",
    "Ananas auf der Pizza schmeckt köstlich." to "በፒዛ ላይ አናናስ ጣፋጭ ነው።",
    "Android" to "አንድሮይድ",
    "Antwort mit einem Foto" to "በፎቶ መልሱ",
    "Antwortähnlichkeit" to "መመሳሰልን መልሱ",
    "App-Sprache auswählen" to "የመተግበሪያ ቋንቋ ይምረጡ",
    "Auf eine Bootsparty gehen" to "ወደ ጀልባ ፓርቲ መሄድ",
    "Aufmerksamkeit" to "ትኩረት",
    "Aufräumen und Projekte angehen" to "ፕሮጀክቶችን አጽዳ እና መፍታት",
    "Aufwärmen" to "ይሞቁ",
    "Aufwärmen: Einander kennenlernen" to "መተዋወቅ፡ መተዋወቅ",
    "Aus dem Urlaub" to "ከእረፍት",
    "Ausgefallener Name" to "የሚያምር ስም",
    "Ausschlafen und faulenzen" to "ተኝተህ ዞር በል::",
    "Ausschlafen und nichts tun" to "ይተኛሉ እና ምንም ነገር አያድርጉ",
    "Aussehen" to "መልክ",
    "Auto" to "ራስ-ሰር",
    "Außenkamin" to "የውጪ ምድጃ",
    "BEANTWORTE" to "መልስ",
    "Bali" to "ባሊ",
    "Bali, Indonesien" to "ባሊ፣ ኢንዶኔዢያ",
    "Banane" to "ሙዝ",
    "Beantwortet" to "መለሰ",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "በተመሳሳይ ጊዜ ጥያቄዎችን ይመልሱ — ሁለታችሁም እስክትጨርሱ ድረስ መልሶች አይታዩም።",
    "Beantwortete Fragen" to "ለጥያቄዎች መልስ ሰጥተዋል",
    "Bearbeiten" to "አርትዕ",
    "Bei Insider-Witzen" to "ለውስጥ ቀልዶች",
    "Bei Memes" to "በሜምስ ላይ",
    "Bei einer spontanen Berührung" to "በድንገት ሲነካ",
    "Beide" to "ሁለቱም",
    "Beide gleich" to "ሁለቱም አንድ ናቸው።",
    "Beide zusammen" to "ሁለቱም አንድ ላይ",
    "Beide, aber wir tun so als ob nicht" to "ሁለቱም፣ ግን አስመስለን አይደለም።",
    "Beides" to "ሁለቱም",
    "Beides wäre schlimm" to "ሁለቱም መጥፎዎች ይሆናሉ",
    "Beim Einschlafen nebeneinander" to "እርስ በርሳችን አጠገብ መተኛት",
    "Beim Reden" to "እያወሩ ነው።",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "ታዋቂ የቱሪስት ቦታዎች ሁሌም ተስፋ አስቆራጭ ናቸው።",
    "Beschreibe unser Sexleben mit einem Emoji." to "የወሲብ ህይወታችንን በኢሞጂ ግለጽ።",
    "Besser kommunizieren" to "በተሻለ ሁኔታ ተገናኝ",
    "Bessere Lage" to "የተሻለ አካባቢ",
    "Bestellen" to "ያዝዙ",
    "Besuchte Länder" to "አገሮች ጎብኝተዋል።",
    "Besuchte Städte" to "ከተሞች ጎብኝተዋል።",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "ከልክ ያለፈ ፕሮፖዛል ወይስ ሌላ ነገር ትመርጣለህ?",
    "Beziehung" to "ግንኙነት",
    "Bibliothek" to "ቤተ-መጽሐፍት።",
    "Bin manchmal unsicher" to "አንዳንድ ጊዜ እርግጠኛ ነኝ",
    "Bist du ein Videospiel-Guru?" to "የቪዲዮ ጌም ጉሩ ነህ?",
    "Blumenwiese" to "የአበባ ሜዳ",
    "Bunte Blumenwiese" to "ባለቀለም የአበባ ሜዳ",
    "Burger" to "በርገርስ",
    "Burger King" to "በርገር ኪንግ",
    "Chat" to "ተወያይ",
    "Coca-Cola" to "ኮካ ኮላ",
    "Cookie Dough" to "የኩኪ ሊጥ",
    "Dachgarten mit Lounge" to "የጣሪያ የአትክልት ስፍራ ከሳሎን ጋር",
    "Dachterrasse" to "የጣሪያ እርከን",
    "Das Wetter an dem Tag" to "የዚያን ቀን የአየር ሁኔታ",
    "Das erste Selfie" to "የመጀመሪያው የራስ ፎቶ",
    "Das meiste weiß ich" to "አብዛኛውን አውቀዋለሁ",
    "Das oder das?" to "ይሄ ወይስ ያ?",
    "Das tägliche Leben" to "የዕለት ተዕለት ኑሮ",
    "Dass Zusagen gehalten werden" to "ያ ተስፋዎች ተጠብቀዋል።",
    "Dass alles meinen Stil hat" to "ሁሉም ነገር የእኔ ዘይቤ አለው።",
    "Dass ich alles erzählen kann" to "ሁሉንም ነገር መናገር እንደምችል",
    "Dass ich mich nicht sorgen muss" to "መጨነቅ እንደሌለብኝ",
    "Dass wir ungestört sind" to "ያልተጨነቅን ነን",
    "Dein Name" to "የእርስዎ ስም",
    "Deine Antwort..." to "መልስህ...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "መልሶችዎ ተቀምጠዋል። ልክ አጋር ጥቅሉን እንደጨረሰ ሁለቱም መልሶች አብረው ይታያሉ።",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "መልሶችዎ ተቀምጠዋል። አንዴ \${profile.partnerName} ጥቅሉን ካጠናቀቀ በኋላ ሁለቱም ምላሾች አብረው ይታያሉ።",
    "Deine Beziehung abenteuerlich und spontan machen" to "ግንኙነትዎን ጀብዱ እና ድንገተኛ ያድርጉት",
    "Deine Beziehung stabil und sicher machen" to "ግንኙነትዎን የተረጋጋ እና አስተማማኝ ያድርጉት",
    "Deine eigene Antwort" to "የራስህ መልስ",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "ጥልቅ ሚስጥሮችን ለባልደረባዎ ማካፈል ይሻላል",
    "Deinen besten Freund verlieren" to "የቅርብ ጓደኛዎን በማጣት ላይ",
    "Denke an dich" to "ለራስህ አስብ",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "ተመሳሳይ ፊልም ሁለት ጊዜ ማየት ጊዜ ማባከን ነው።",
    "Der Blick nach draußen" to "ውጫዊ እይታ",
    "Der Garten" to "የአትክልት ስፍራው።",
    "Der Ort" to "ቦታው",
    "Der Ring und die Geste" to "ቀለበት እና የእጅ ምልክቱ",
    "Der perfekte Heiratsantrag" to "ፍጹም የሆነ የጋብቻ ጥያቄ",
    "Derjenige sein, der umarmt wird" to "የታቀፉት ይሁኑ",
    "Deutsch" to "ጀርመንኛ",
    "Diamant" to "አልማዝ",
    "Diamanten im Band" to "አልማዞች ባንድ ውስጥ",
    "Die Distanz" to "ርቀቱ",
    "Die Feiertage mit der Familie deines Partners verbringen" to "በዓላቱን ከባልደረባዎ ቤተሰብ ጋር ያሳልፉ",
    "Die Gemütlichkeit und Ruhe" to "መጽናናትና ሰላም",
    "Die Menschen, die darin wohnen" to "በውስጡ የሚኖሩ ሰዎች",
    "Die Umgebung und Atmosphäre" to "አካባቢ እና ድባብ",
    "Die Worte und Emotionen" to "ቃላቶቹ እና ስሜቶች",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "የመጨረሻው የመዝናኛ ተራ ፈተና",
    "Diejenige sein, die umarmt" to "የምታቅፈው ሁን",
    "Direkt ansprechen" to "በቀጥታ አድራሻ",
    "Diskussion" to "ውይይት",
    "Diskutiere vor dem Kinderkriegen" to "ልጆች ከመውለድዎ በፊት ተወያዩ",
    "Diskutiert eure Antworten" to "በመልሶቻችሁ ላይ ተወያዩ",
    "Disney" to "ዲስኒ",
    "Doch, schon mal" to "አዎ፣ አዎ",
    "Draußen mit der Natur als Kulisse" to "ከተፈጥሮ ውጭ እንደ ዳራ",
    "Drei-Stein-Ring" to "ሶስት የድንጋይ ቀለበት",
    "Du bist dran" to "የእርስዎ ተራ ነው።",
    "Du fehlst mir" to "ናፍቄሻለሁ።",
    "Dubai" to "ዱባይ",
    "Dubai, VAE" to "ዱባይ፣ አረብ ኢሚሬትስ",
    "Dunkles Design" to "ጨለማ ገጽታ",
    "Durch Berührung" to "በመንካት",
    "Durch Worte" to "በቃላት",
    "Durch Zeit zu zweit" to "በአንድነት ጊዜ",
    "Durch kleine Gesten" to "በትንሽ ምልክቶች",
    "Durchgeplant" to "በደንብ ታቅዷል",
    "ERGEBNISSE" to "ውጤቶች",
    "Egal, Hauptsache gesund" to "ምንም ይሁን ምን ዋናው ነገር ጤናማ ነው።",
    "Ehepaar Leben" to "የተጋቡ የጥንዶች ሕይወት",
    "Eher knapp" to "ይልቁንስ ቅርብ",
    "Eher nicht" to "ብዙም አይደለም።",
    "Eher schwer" to "ይልቁንስ ከባድ",
    "Eher schwierig" to "ይልቁንስ ከባድ",
    "Eher zu" to "ተጨማሪ መውደድ",
    "Eifersucht ist ein Zeichen von Liebe." to "ቅናት የፍቅር ምልክት ነው።",
    "Eigenes Gemüsebeet" to "የራሱ የአትክልት ፕላስተር",
    "Ein Abenteuer in einer neuen Stadt" to "በአዲስ ከተማ ውስጥ ያለ ጀብዱ",
    "Ein Anker" to "መልህቅ",
    "Ein Balkon oder Garten" to "በረንዳ ወይም የአትክልት ስፍራ",
    "Ein Filmabend" to "የፊልም ምሽት",
    "Ein Harmony-Meilenstein eurer Liebe." to "የፍቅርህ የስምምነት ምዕራፍ።",
    "Ein Herz" to "ልብ",
    "Ein Herz an der Tür" to "በሩ ላይ ያለ ልብ",
    "Ein Jahr lang eine Fernbeziehung führen" to "ለአንድ አመት የርቀት ግንኙነት ይኑርዎት",
    "Ein Kindheitsessen" to "የልጅነት ምግብ",
    "Ein Live-Musik-Konzert besuchen" to "የቀጥታ የሙዚቃ ኮንሰርት ተገኝ",
    "Ein Museum besuchen" to "ሙዚየምን ይጎብኙ",
    "Ein Spieleabend" to "የጨዋታ ምሽት",
    "Ein Spieleabend mit Freunden" to "ከጓደኞች ጋር የጨዋታ ምሽት",
    "Ein Urlaubsfoto" to "የዕረፍት ጊዜ ፎቶ",
    "Ein aktives Abenteuer" to "ንቁ ጀብዱ",
    "Ein entspannender Spa-Tag" to "ዘና የሚያደርግ የስፓ ቀን",
    "Ein ganz normaler Alltagstag" to "ሙሉ በሙሉ የተለመደ የዕለት ተዕለት ቀን",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "በቤቱ ውስጥ በነጎድጓድ ጊዜ ምቹ ምሽት",
    "Ein gemütliches Date drinnen" to "ምቹ ቀን በቤት ውስጥ",
    "Ein lustiges Bild" to "አስቂኝ ምስል",
    "Ein paar Handyfotos reichen" to "ጥቂት የሞባይል ፎቶዎች በቂ ናቸው።",
    "Ein paar Stunden" to "ጥቂት ሰዓታት",
    "Ein paar kulturelle Anklänge sind okay" to "ጥቂት የባህል ማጣቀሻዎች ደህና ናቸው።",
    "Ein romantischer Abend" to "የፍቅር ምሽት",
    "Ein romantisches Abendessen bei Kerzenlicht" to "የፍቅር ሻማ የበራ እራት",
    "Ein romantisches Bild" to "የፍቅር ምስል",
    "Ein romantisches Picknick an einem schönen Ort" to "በሚያምር ቦታ ላይ የፍቅር ሽርሽር",
    "Ein schwerer Moment, den wir geschafft haben" to "የቻልንበት አስቸጋሪ ጊዜ",
    "Ein tolles Date im Freien unter dem Mondlicht" to "በጨረቃ ብርሃን ስር ከቤት ውጭ ጥሩ ቀን",
    "Ein ungewöhnliches Gericht" to "ያልተለመደ ምግብ",
    "Ein zufälliger Schnappschuss" to "የዘፈቀደ ቅጽበታዊ ገጽ እይታ",
    "Einander kennenlernen" to "እርስ በርስ መተዋወቅ",
    "Eine Autoreise" to "የመንገድ ጉዞ",
    "Eine Brücke" to "ድልድይ",
    "Eine Date-Nacht unter den Sternen" to "የቀን ምሽት ከከዋክብት በታች",
    "Eine Million Dollar gewinnen" to "አንድ ሚሊዮን ዶላር አሸንፉ",
    "Eine Million Dollar verdienen" to "አንድ ሚሊዮን ዶላር ያግኙ",
    "Eine Nacht in einem Club" to "በአንድ ክለብ ውስጥ ያለ ምሽት",
    "Eine Schokoladenverkostung" to "ቸኮሌት መቅመስ",
    "Eine Wanderung mit Panoramablick machen" to "በፓኖራሚክ እይታዎች የእግር ጉዞ ያድርጉ",
    "Eine Weinverkostung" to "ወይን መቅመስ",
    "Eine gemeinsame Reise" to "አንድ ላይ ጉዞ",
    "Eine gemütliche Nacht zu Hause" to "ምቹ ምሽት በቤት ውስጥ",
    "Eine neue Sprache zu lernen ist einfach." to "አዲስ ቋንቋ መማር ቀላል ነው።",
    "Einen Film anschauen" to "ፊልም ይመልከቱ",
    "Einen Monat lang überhaupt nicht miteinander reden" to "ለአንድ ወር ሙሉ በሙሉ አለመነጋገር",
    "Einen Tanzkurs besuchen" to "የዳንስ ክፍል ይውሰዱ",
    "Einen Vergnügungspark erkunden" to "የመዝናኛ ፓርክን ያስሱ",
    "Einen Wellness-Tag" to "የጤንነት ቀን",
    "Einen sehr emotionalen Partner haben" to "በጣም ስሜታዊ አጋር መኖር",
    "Einen sehr logischen Partner haben" to "በጣም ምክንያታዊ አጋር መኖር",
    "Einer zahlt alles" to "አንድ ሰው ሁሉንም ነገር ይከፍላል።",
    "Einfach mehr Alltag" to "በቀላሉ ተጨማሪ የዕለት ተዕለት ኑሮ",
    "Einfach nebeneinander sein" to "ብቻ እርስ በርሳችሁ አጠገብ ሁኑ",
    "Einfach und intim" to "ቀላል እና የጠበቀ",
    "Einige Dinge für dich behalten" to "አንዳንድ ነገሮችን ለራስህ አቆይ",
    "Einmal" to "አንድ ጊዜ",
    "Eins, das nur wir kennen" to "እኛ ብቻ የምናውቀው",
    "Englisch" to "እንግሊዝኛ",
    "Entspannte Hängematte" to "ዘና ያለ hammock",
    "Entspannung" to "መዝናናት",
    "Erdbeere" to "እንጆሪ",
    "Erfolgreich" to "ተሳክቷል።",
    "Ergebnisse" to "ውጤቶች",
    "Erst bei sehr großen Summen" to "በጣም ትልቅ በሆነ ድምር ብቻ",
    "Erst nur enge Freunde/Familie" to "መጀመሪያ ላይ የቅርብ ጓደኞች/ቤተሰብ ብቻ",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "ባልደረባዬ ለመልእክቶች ምላሽ ለመስጠት ብዙ ጊዜ ሲወስድ ያናድደኛል።",
    "Essen & Genuss" to "ምግብ እና ደስታ",
    "Essensvorlieben" to "የምግብ ምርጫዎች",
    "Etwa eine Woche später, erst mal nur wir" to "ከአንድ ሳምንት ገደማ በኋላ፣ ልክ እኛ መጀመሪያ",
    "Etwas Neues ausprobieren" to "አዲስ ነገር ይሞክሩ",
    "Etwas ganz anderes" to "ፍጹም የተለየ ነገር",
    "Etwas sehr Scharfes" to "በጣም ስለታም የሆነ ነገር",
    "Etwas, das ich selbst gern erfinde" to "ራሴን መፈልሰፍ የምወደው ነገር",
    "Etwas, eine kleine Note wäre schön" to "የሆነ ነገር፣ ትንሽ ማስታወሻ ጥሩ ይሆናል።",
    "Familie" to "ቤተሰብ",
    "Familie/Freunde" to "ቤተሰብ/ጓደኞች",
    "Familienmensch" to "የቤተሰብ ሰው",
    "Farbedelstein" to "ባለቀለም የከበረ ድንጋይ",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "የቲቪ ማስታወቂያዎች አንዳንድ ጊዜ ለመመልከት አስደሳች ናቸው።",
    "Fertig" to "ተከናውኗል",
    "Fertig!" to "ተከናውኗል!",
    "Feste Date-Nights" to "ቋሚ የቀን ምሽቶች",
    "Feuerstelle" to "የእሳት ጉድጓድ",
    "Filigran & schlicht" to "ፊሊግሪ እና ቀላል",
    "Filme/Serien" to "ፊልሞች/ተከታታይ",
    "Formuliere um..." to "እንደገና ሀረግ...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "ረቂቅዎን ረብሻ በሌለው መንገድ ይድገሙት፡ ምልከታ፣ ስሜት፣ ፍላጎት፣ ጥያቄ።",
    "Frage hinzufügen" to "ጥያቄ ጨምር",
    "Fragen & Spiele" to "ጥያቄዎች እና ጨዋታዎች",
    "Fragen für jede Gelegenheit" to "ለእያንዳንዱ አጋጣሚ ጥያቄዎች",
    "Freizeitpark" to "የመዝናኛ ፓርክ",
    "Freunde treffen" to "ከጓደኞች ጋር ይተዋወቁ",
    "Freundschaften mit Ex-Partnern sind okay." to "ከ exes ጋር ያለዎት ጓደኝነት ደህና ነው።",
    "Früh aufstehen" to "በማለዳ ተነሱ",
    "Fußbodenheizung" to "ወለል ማሞቂያ",
    "Führen wir getrennte oder gemeinsame Konten?" to "የተለየ ወይም የጋራ መለያ አለን?",
    "Für dich empfohlen" to "ለእርስዎ የሚመከር",
    "Für die Zukunft" to "ለወደፊቱ",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "ለዚህ ፍለጋ ምንም ተዛማጅ ጥያቄዎች ወይም ጨዋታዎች አልተገኙም።",
    "Für immer" to "ለዘላለም",
    "Fürsorglichkeit" to "እንክብካቤ",
    "GFK-Brücke" to "የጂፒፕ ድልድይ",
    "Galerie" to "ጋለሪ",
    "Gar nicht, der Moment gehört uns" to "በጭራሽ፣ ጊዜው የእኛ ነው።",
    "Gar nichts tun" to "ምንም አታድርጉ",
    "Geduld" to "ትዕግስት",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "የፀሐይ መውጣትን ለማየት በማለዳ ይሂዱ",
    "Geht so" to "እንደዚህ ይሄዳል",
    "Geister existieren wirklich." to "መናፍስት በእርግጥ አሉ።",
    "Gelassenheit" to "መረጋጋት",
    "Gelbgold" to "ቢጫ ወርቅ",
    "Geld & Finanzen" to "ገንዘብ እና ፋይናንስ",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "አብራችሁ አለምን ተጓዙ፣ አዳዲስ ባህሎችን እና ምግቦችን አስሱ",
    "Gemeinsam ein Lego bauen" to "ሌጎን አንድ ላይ ይገንቡ",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "አዲስ የምግብ አሰራር በኩሽና ውስጥ አብረው ይሞክሩ",
    "Gemeinsame Konten" to "የተጋሩ መለያዎች",
    "Gemeinsame Nächte" to "አብረው ምሽቶች",
    "Gemeinsame Tage" to "ቀናት አብረው",
    "Gemischt" to "የተቀላቀለ",
    "Gemüsebeet" to "የአትክልት ማጣበቂያ",
    "Gemütliche Feuerstelle" to "ምቹ የእሳት ቦታ",
    "Gesprächsanreger" to "የውይይት ጀማሪ",
    "Getrennte Konten" to "የተለዩ መለያዎች",
    "Getrennte Urlaube tun einer Beziehung gut." to "የተለየ የዕረፍት ጊዜ ለግንኙነት ጥሩ ነው።",
    "Gewächshaus" to "ግሪን ሃውስ",
    "Glasfassade" to "የመስታወት ፊት",
    "Gleichgültigkeit" to "ግዴለሽነት",
    "Glücklich und frei" to "ደስተኛ እና ነፃ",
    "Gourmet Eis-Sorten" to "Gourmet አይስ ክሬም ዝርያዎች",
    "Gravur innen" to "ውስጥ መቀረጽ",
    "Grillplatz" to "የባርበኪዩ አካባቢ",
    "Groß & üppig" to "ትልቅ እና ለምለም",
    "Große Familie" to "ትልቅ ቤተሰብ",
    "Große Feier" to "ትልቅ በዓል",
    "Große Fenster" to "ትልቅ መስኮቶች",
    "Große Fensterfront" to "ትልቅ መስኮት ፊት",
    "Großer Außenpool" to "ትልቅ የውጪ ገንዳ",
    "Großer Garten" to "ትልቅ የአትክልት ስፍራ",
    "Großer Stein" to "ትልቅ ድንጋይ",
    "Größere Küche" to "ትልቅ ወጥ ቤት",
    "Gutes Essen" to "ጥሩ ምግብ",
    "Habe ich" to "አደረግሁ",
    "Habe ich noch nie" to "በጭራሽ የለኝም",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "አስገራሚ ልዩነቶች አግኝተዋል? አንዳንድ አማራጮችን ለምን እንደወደዱ ይናገሩ!",
    "Haus am See" to "በሐይቁ አጠገብ ያለ ቤት",
    "Haus/Wohnung" to "ቤት/አፓርታማ",
    "Hazelnut" to "Hazelnut",
    "Heimkino" to "የቤት ቲያትር",
    "Herzhaft" to "ልባዊ",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "አሁን እዚህ ምንም የለም።\nማጣሪያውን ይቀይሩ ወይም የተለየ ርዕስ ይምረጡ።",
    "Hilfe im Alltag" to "በዕለት ተዕለት ሕይወት ውስጥ እገዛ",
    "Himbeere" to "Raspberry",
    "Hinzufügen" to "ያክሉ",
    "Hobbys" to "የትርፍ ጊዜ ማሳለፊያዎች",
    "Hochzeitssträuße" to "የሰርግ እቅፍ አበባዎች",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "የሆግዋርት ቤት ኩራት፡ የት ነው ያለህ?",
    "Home" to "ቤት",
    "Hot Tub" to "ሙቅ ገንዳ",
    "Humor" to "ቀልድ",
    "Hund" to "ውሻ",
    "Hängematte" to "ሃምሞክ",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "የሐሳቡ አካል የሆነ የጽሁፍ ደብዳቤ ይፈልጋሉ?",
    "IKEA" to "IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "ወደ ሲኒማ ከመሄድ በፓርኩ ውስጥ የፍቅር የእግር ጉዞዎችን እመርጣለሁ።",
    "Ich bin noch nie in einem Kino eingeschlafen." to "ሲኒማ ውስጥ ተኝቼ አላውቅም።",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "ከባልደረባዬ ጋር አዳዲስ የትርፍ ጊዜ ማሳለፊያዎችን ወይም እንቅስቃሴዎችን በማግኘት እወዳለሁ።",
    "Ich finde eine Alternative" to "አማራጭ አገኛለሁ።",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "ሁልጊዜ ወደ አንድ ቦታ ከመሄድ ይልቅ አዲስ ምግብ ቤቶችን ከባልደረባዬ ጋር መሞከር ያስደስተኛል",
    "Ich habe noch nie" to "በጭራሽ የለኝም",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "ሮለር ኮስተርን ፈርቼው አላውቅም እና ለማንኛውም ገባሁበት።",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "ትዕግስት ስለሌለኝ የፈጣን ማለፊያ ትኬቶችን ገዝቼ አላውቅም።",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "ቤት የመቆየት እና የቲቪ ትዕይንት የመመልከት ዕቅዴን ሰርጬ አላውቅም።",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "ከሆግዋርትስ ደብዳቤዬን ጠብቄው አላውቅም።",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "ስሊተሪን በእውነቱ ያን ያህል መጥፎ እንዳልሆነ ተናግሬ አላውቅም።",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "ለዲዝኒ ፊልሞች በጣም አርጅቻለሁ (እና በሚስጥር ወድጄዋለው) ተናግሬ አላውቅም።",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "በማሪዮ ካርት ውስጥ ሰማያዊ ታንክ ያለው ሰው ሆን ብዬ ተኩሼ አላውቅም።",
    "Ich habe noch nie bei einem Disney-Film geweint." to "በዲስኒ ፊልም ላይ አልቅሼ አላውቅም።",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "አስፈሪ ፊልም እያየሁ ዓይኖቼን ሸፍኜ አላውቅም።",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "አንድን ጨዋታ ማዳን ረስቼው አላውቅም እና የሰአታት እድገት ማጣት።",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "በሚያሳፍር ሁኔታ (ክሪንግ ፋክተር) ከክፍሉ ወጥቼ አላውቅም።",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "ሮለርኮስተር ፎቶ እያነሳሁ አስቂኝ አቀማመጥ ሰርቼ አላውቅም።",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "እስከ ማታ ድረስ ተጫውቼ አላውቅም እና በማግስቱ ምን ያህል እንደደከመኝ ተጸጽቼ አላውቅም።",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "መጠበቅ ስለማልችል የፊልም መጨረሻ ላይ ጎግል አድርጌ አላውቅም።",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "በፊልም ስብስብ ላይ የቆምኩ ያህል ተሰምቶኝ አያውቅም።",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "የምወደው ተከታታዮችን መግቢያ መቼም ዘልዬ አላውቅም።",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "የሌላ የማንም Netflix ይለፍ ቃል አጋርቼ አላውቅም።",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "እየሰራሁም ሆነ በምማርበት ጊዜ የጨዋታ ሙዚቃን አዳምጬ አላውቅም።",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "በተሸነፍኩበት ጊዜ ተቆጣጣሪውን ወቅሼ አላውቅም።",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "በንዴት ኪቦርዱን ወይም መቆጣጠሪያውን ጣልኩት አላውቅም።",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "እርጥብ ልብሶችን በልብስ ማጠቢያ ማሽን ውስጥ ለጥቂት ቀናት ረስቼው አላውቅም።",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "በጨዋታ ውስጥ ለመዋቢያ ዕቃዎች እውነተኛ ገንዘብ አውጥቼ አላውቅም።",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "በባዕድ አገር መኪና ነድቼ አላውቅም።",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "የዲስኒ ዘፈንን በሻወር ውስጥ ቀበቶ አውጥቼ አላውቅም።",
    "Ich habe noch nie ein Elektroauto gefahren." to "የኤሌክትሪክ መኪና ነድቼ አላውቅም።",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "ከመናፈሻ ሜዳ ጋር ፎቶ አንስቼ አላውቅም።",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "የቤት እንስሳ በሆግዋርትስ ገፀ ባህሪ ስም ሰይሜ አላውቅም።",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "በፊልም ቲያትር ውስጥ ፋንዲሻ ጥዬው አላውቅም አሁንም በልቼው አላውቅም።",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "በዕለት ተዕለት ሕይወቴ ከ Master Yoda ከ Star Wars የተናገረውን ጥቅስ ተጠቅሜ አላውቅም።",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "በገጽታ መናፈሻ መናፈሻ ውስጥ ከመጠን በላይ የሆነ መታሰቢያ ገዝቼ አላውቅም።",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "ሌላው ሰው አስከፊ ሆኖ ያገኘውን የፊልም ጥቆማ ሰጥቼ አላውቅም።",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "ኦስካር እኩለ ሌሊት ላይ በቀጥታ ስርጭት አይቼ አላውቅም።",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "ያለፈው ሲዝን በጣም መጥፎ ስለነበር ተከታታዩን ሰርዤ አላውቅም።",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "ሙሉውን ተከታታይ ሲዝን በአንድ ቀን ውስጥ በትኩረት አይቼ አላውቅም።",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "በመጀመሪያ ሙከራ አንድ አለቃን አሸንፌ አላውቅም እና እንደ አምላክ ተሰምቶኝ አያውቅም።",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "ከጀግናው የበለጠ ተንኮለኛ ሰው አላገኘሁም።",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "በገዛ አሻንጉሊቶች ውስጥ የአሻንጉሊት ታሪክ ገፀ ባህሪን ለይቼ አላውቅም።",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "ልክ እንደኔ በ RPG ውስጥ ገፀ ባህሪ ሰርቼ አላውቅም።",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "በአንድ ጭብጥ መናፈሻ ቦታ ቹሮ በልቼ አላውቅም።",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "የዲስኒ ፊልም በተከታታይ ሶስት ጊዜ አይቼ አላውቅም።",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "ለአንድ ሳምንት ሙሉ የዲስኒ ማራኪ ዜማ ኖሮኝ አያውቅም።",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "በአንድ ተዋናይ ምክንያት ብቻ ፊልም አይቼ አላውቅም።",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "ለሰዓታት በድግግሞሽ የፊልም ማጀቢያ ሰምቼ አላውቅም።",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "የፊልም አበላሹን ገልጬ አላውቅም እና ወዲያው ተጸጽቻለሁ።",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "ሌላ የአፍ መፍቻ ቋንቋ የሚናገር ጓደኛ አላገኘሁም።",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "ወደ ሌላ ሀገር የሄደ ጓደኛ ኖሮኝ አያውቅም።",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "ገና በገና የሃሪ ፖተር ፊልም ማራቶን ሰርቼ አላውቅም።",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "በድህረ ክሬዲት ትዕይንት ምክንያት የ Marvel ፊልም እስከ መጨረሻ አይቼ አላውቅም።",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "ሆን ብዬ NPC (ተጫዋች ያልሆነ ገጸ ባህሪ) አስቆጥቼ አላውቅም።",
    "Ich habe noch nie einen Nachtzug genommen." to "የምሽት ባቡር ወስጄ አላውቅም።",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "የሆግዋርትስ ቤቴን ለማወቅ የመስመር ላይ ፈተና ወስጄ አላውቅም።",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "በቂ መውደዶችን ስላላገኘ የማህበራዊ ሚዲያ ልጥፍን ሰርጬ አላውቅም።",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "በቴም ፓርክ ውስጥ አንድ ቀን የዓመቱ ምርጥ ቀን ብዬ ጠርቼ አላውቅም።",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "የገጽታ መናፈሻን ጎብኝቼ አላውቅም እና ከጠዋት እስከ ማታ ቆየሁ።",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "ከትራንስፎርመር ወይም ከማርቭል ግልቢያ ሙሉ በሙሉ ተማርኬ አላውቅም።",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "ተቆጥቼ ጨዋታውን አቋርጬ አላውቅም።",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "ከትልቁ የሃሪ ፖተር ጥራዝ አንብቤ አላውቅም።",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "በተከታታይ ስለምወደው ገፀ ባህሪ ተናፍቄ አላውቅም።",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "ኩዊዲች የመጫወት ህልም አላስብም ነበር።",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "ከባድ ደረጃን እንዴት እንደሚፈታ በድብቅ ጎግል ገልጬ አላውቅም።",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "የቤት እንስሳዬ በዲስኒ ውስጥ እንደሚናገሩ በድብቅ ተስፋ አድርጌ አላውቅም።",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "የመዋኛ ገንዳ መሪን በሲምስ ውስጥ አስወግጄው አላውቅም።",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "በ3-ል ሲሙሌተር ግልቢያ ውስጥ ድቤዬን አጥቼ አላውቅም።",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "በዩኒቨርሲቲ የስፖርት ቡድን ውስጥ ተጫውቼ አላውቅም።",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "ለአንድ መስህብ ከሁለት ሰአት በላይ ወረፋ ጠብቄ አላውቅም።",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "ውድ ዕቃዎቼን በውሃ ግልቢያ ላይ አርጥብ አላውቅም።",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "የትኛው ቤት የተሻለ እንደሆነ ከአንድ ጓደኛዬ ጋር ተከራክሬ አላውቅም።",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "እንደ ኤልሳ አስማታዊ ሃይሎች አለኝ ብዬ አስቤ አላውቅም።",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "በፊልም ውስጥ አንድ አስፈላጊ ትዕይንት እስኪያመልጥ ድረስ ጠንክሬ ሳቄ አላውቅም።",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "ይህን ያህል አድሬናሊን ተሰምቶኝ አያውቅም እናም ወዲያው እንደገና መንዳት ፈለግኩ።",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "እንደ በረዶ ነጭ ካሉ እንስሳት ጋር ለመዝፈን ሞክሬ አላውቅም።",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "ወደ Disneyland የመጓዝ ህልም አላየሁም።",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "በጁራሲክ ፓርክ የውሃ ግልቢያ ለመንዳት ህልሜ አላውቅም።",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "በአንድ ጨዋታ ውስጥ በዝላይ ፍርሃት ጮክ ብዬ ጮህኩ አላውቅም።",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "በአንድ የቲቪ ትዕይንት መጨረሻ ላይ አልቅሼ አላውቅም።",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "በጭራሽ... ቤት የምቆይበትን ቀን ሰርዤ አላውቅም።",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "አንድም ጊዜ... መልእክት 10 ጊዜ ደግሜ አላውቅም።",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "በጭራሽ...የባልደረባዬን ሞባይል በድብቅ አይቼ አላውቅም።",
    "Ich habe noch nie!" to "በጭራሽ የለኝም!",
    "Ich habe!" to "አለኝ!",
    "Ich lache viel mit meinem Partner." to "ከትዳር አጋሬ ጋር በጣም እስቃለሁ።",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "የባልደረባዬን የትርፍ ጊዜ ማሳለፊያዎች እና ፍላጎቶች ማወቅ እወዳለሁ።",
    "Ich liebe es" to "ወድጄዋለሁ",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "ከባልደረባዬ ጋር ከዚህ በፊት ሁለታችንም ያየናቸውን ፊልሞች ማየት እወዳለሁ።",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "የምወደውን ሙዚቃ ለባልደረባዬ ማካፈል እወዳለሁ።",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "የሚገናኝ በረራ ለመያዝ መሮጥ ነበረብኝ።",
    "Ich plane gerne Dates mit meinem Partner." to "ከባልደረባዬ ጋር ቀኖችን ማቀድ እወዳለሁ።",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "ስራ ቢበዛብኝም ከባልደረባዬ ጋር ጊዜ ለማሳለፍ ቅድሚያ እሰጣለሁ።",
    "Ich schreibe meinem Partner jeden Tag." to "ለባልደረባዬ በየቀኑ መልእክት እልካለሁ።",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "ትዝታዎችን እና ቀልዶችን ከባልደረባዬ ጋር መጋራት እወዳለሁ።",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "ሁሉንም የቀኔን ዝርዝሮች ለባልደረባዬ ማካፈል ወደድኩ።",
    "Ich würde es nie tun" to "በጭራሽ አላደርገውም።",
    "Ich übe noch" to "አሁንም እየተለማመድኩ ነው።",
    "Ideen generieren" to "ሀሳቦችን ይፍጠሩ",
    "Im Haushalt helfen" to "በቤቱ ዙሪያ እገዛ",
    "In Chat einfügen" to "ወደ ውይይት ያክሉ",
    "In Stille nebeneinander" to "እርስ በርስ በዝምታ",
    "In den Bergen" to "በተራሮች ላይ",
    "In eine Bar gehen" to "ወደ አሞሌ ይሂዱ",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "ጀምበር ስትጠልቅ ለመመልከት ወደ ባህር ዳርቻ ባር መሄድ",
    "In einem feinen Restaurant essen gehen" to "ጥሩ ምግብ ቤት ውስጥ መብላት",
    "In einen Coffeeshop gehen" to "ወደ ቡና ቤት ይሂዱ",
    "In einer Beziehung sollte man alles voneinander wissen." to "በግንኙነት ውስጥ ስለሌላው ሁሉንም ነገር ማወቅ አለባችሁ።",
    "Infinity-Pool" to "Infinity ገንዳ",
    "Innenpool" to "የቤት ውስጥ ገንዳ",
    "Intelligenz" to "ብልህነት",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "ጓደኛዎ ሲጀምራቸው የቅርብ ጊዜዎችን ብቻ ማግኘት",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "የግብዣ ኮድ፡ HRM-8731 · ሁሉም ነገር ተከፍቷል።",
    "Island" to "አይስላንድ",
    "Ist okay für mich" to "በኔ ምንም አይደለም።",
    "Ist schon perfekt" to "ፍጹም ነው።",
    "Ja, Traditionen einbinden" to "አዎ፣ ወጎችን አካትት።",
    "Ja, absolut" to "አዎ፣ በፍጹም",
    "Ja, etwas zum Lesen und Aufbewahren" to "አዎ፣ የሚነበብ እና የሚቀመጥ ነገር አለ።",
    "Ja, genug" to "አዎ በቃ",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "አዎ፣ በአስደሳች ከተማ ወይም መስህብ ውስጥ",
    "Ja, in- und auswendig" to "አዎ፣ ከውስጥም ከውጪም።",
    "Ja, komplett überraschend" to "አዎ፣ ሙሉ በሙሉ የሚገርም ነው።",
    "Ja, perfekt" to "አዎ፣ ፍጹም",
    "Ja, sie gehören zur Familie!" to "አዎ፣ ቤተሰብ ናቸው!",
    "Ja, sofort teilen" to "አዎ፣ ወዲያውኑ ያካፍሉ።",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "አዎ፣ የቤተሰብ ጊዜ ቅድሚያ የሚሰጠው መሆኑን እናረጋግጣለን።",
    "Jacuzzi" to "Jacuzzi",
    "Jahr zusammen 🎉" to "ዓመት አብረው 🎉",
    "Jahre zusammen 🎉" to "ዓመታት አብረው 🎉",
    "Jeder zahlt 50%" to "ሁሉም ሰው 50% ይከፍላል",
    "Junge" to "ወንድ ልጅ",
    "Kamin" to "የእሳት ቦታ",
    "Karriere & Erfolg" to "ሙያ እና ስኬት",
    "Kategorien" to "ምድቦች",
    "Katze" to "ድመት",
    "Keine Musik" to "ምንም ሙዚቃ የለም።",
    "Keine Party nötig, privat halten" to "ፓርቲ አያስፈልግም፣ ሚስጥራዊ ያድርጉት",
    "Keine Privatsphäre" to "ምንም ግላዊነት የለም።",
    "Keine Treffer gefunden" to "ምንም ተዛማጅ አልተገኙም።",
    "Keiner" to "ምንም",
    "Keiner von uns" to "ማናችንም ብንሆን",
    "Kennst du die Essensvorlieben deines Partners?" to "የአጋርዎን የምግብ ምርጫዎች ያውቃሉ?",
    "Kino" to "ሲኒማ",
    "Kirchlich" to "መክብብ",
    "Klassisch Solitär" to "ክላሲክ solitaire",
    "Klassisch gebunden" to "በክላሲካል የታሰረ",
    "Klein & zart" to "ትንሽ እና ስስ",
    "Kleine Geschenke" to "ትናንሽ ስጦታዎች",
    "Kleine Runde" to "ትንሽ ቡድን",
    "Kochen und Freunde einladen" to "ጓደኞችን ማብሰል እና መጋበዝ",
    "Kochkurs" to "የማብሰያ ክፍል",
    "Kommt auf den Tag an" to "በእለቱ ይወሰናል",
    "Kommt darauf an" to "ይወሰናል",
    "Kommt drauf an" to "ይወሰናል",
    "Kommt mit" to "ከእኔ ጋር ና",
    "Konzert" to "ኮንሰርት።",
    "Kräftige Farben" to "ጠንካራ ቀለሞች",
    "Kräuterbeet" to "የአትክልት አልጋ",
    "Kultur & Sehenswürdigkeiten" to "ባህል እና እይታዎች",
    "Kuscheln" to "መተቃቀፍ",
    "Kuss senden" to "መሳም ይላኩ።",
    "Körperliche Annäherung" to "አካላዊ አቀራረብ",
    "Körperliche Nähe" to "አካላዊ ቅርበት",
    "Küche" to "ወጥ ቤት",
    "Land" to "አገር",
    "Landhaus" to "የሀገር ቤት",
    "Landhausstil" to "የአገር ቤት ዘይቤ",
    "Lange wach bleiben" to "አርፍዱ",
    "Lappland" to "ላፕላንድ",
    "Lappland, Finnland" to "ላፕላንድ፣ ፊንላንድ",
    "Las Vegas" to "ላስ ቬጋስ",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "የእርስዎ አጋር ምርጥ እራስ እንድትሆኑ ያነሳሳህ",
    "Lehne ab" to "አትቀበል",
    "Leichtigkeit" to "ቀላልነት",
    "Leidenschaft" to "ፍቅር",
    "Liebe im Gleichgewicht" to "ፍቅር ሚዛን ነው።",
    "Liebe sie, macht mehr Spaß" to "እነሱን ውደዱ፣ የበለጠ አስደሳች",
    "Lieber durchgeplant oder spontan?" to "ይልቁን ታቅዶ ወይም ድንገተኛ እንዲሆን ይፈልጋሉ?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "ለሁለት ወይም ከሰዎች ጋር ጸጥ ያለ ምሽት ብታሳልፍ ይሻላል?",
    "Lieber nicht" to "ባይሆን ይሻላል",
    "Lieber vorher grob absprechen" to "ነገሮችን አስቀድመው መወያየት ይሻላል",
    "Lokal einkaufen" to "በአገር ውስጥ ይግዙ",
    "London" to "ለንደን",
    "London, England" to "ለንደን፣ እንግሊዝ",
    "Lügen" to "ውሸት",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "የህዝብ ወይም የግል ፕሮፖዛል ይመርጣሉ?",
    "Malediven" to "ማልዲቭስ",
    "Man sollte nie streitend einschlafen." to "በመከራከር በፍፁም መተኛት የለብዎትም።",
    "Mango Sorbet" to "ማንጎ ሶርቤት",
    "Markant & breit" to "አስደናቂ እና ሰፊ",
    "Marken & Alltag" to "የምርት ስሞች እና የዕለት ተዕለት ሕይወት",
    "McDonald’s" to "ማክዶናልድስ",
    "Mediterraner Innenhof" to "የሜዲትራኒያን ግቢ",
    "Mehr Unterstützung" to "ተጨማሪ ድጋፍ",
    "Mehr gemeinsame Zeit" to "ተጨማሪ ጊዜ አብራችሁ",
    "Mehr zuhören" to "የበለጠ ያዳምጡ",
    "Mehrgenerationenhaus" to "ባለብዙ-ትውልድ ቤት",
    "Mein Arbeitsplatz" to "የእኔ የስራ ቦታ",
    "Mein Partner" to "የእኔ አጋር",
    "Mich überraschen" to "ገረሙኝ።",
    "Minimalistisches Interieur" to "ዝቅተኛው የውስጥ ክፍል",
    "Missverständnisse" to "አለመግባባቶች",
    "Mit Familie und engen Freunden" to "ከቤተሰብ እና ከቅርብ ጓደኞች ጋር",
    "Mit Kompromissen" to "ከስምምነት ጋር",
    "Mitgefühl" to "ርህራሄ",
    "Mittelweg mit besonderen Details" to "መካከለኛው ሜዳ በልዩ ዝርዝሮች",
    "Modern geometrisch" to "ዘመናዊ ጂኦሜትሪክ",
    "Moderne Grillstation" to "ዘመናዊ ግሪል ጣቢያ",
    "Moderner Name" to "ዘመናዊ ስም",
    "Moderner Solitär" to "ዘመናዊ solitaire",
    "Moissanit" to "ሞይሳኒት",
    "Moment festhalten" to "ጊዜውን ያንሱ",
    "Momente" to "አፍታዎች",
    "Monaco" to "ሞናኮ",
    "Moralische Werte" to "የሥነ ምግባር እሴቶች",
    "Museum" to "ሙዚየም",
    "Musik" to "ሙዚቃ",
    "Mut" to "ድፍረት",
    "Mädchen" to "ሴት ልጆች",
    "Möbelhaus" to "የቤት ዕቃዎች መደብር",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "እርግጠኛ ነዎት ጥያቄውን መተው ይፈልጋሉ? ያለፈው እድገትህ እንደተቀመጠ ይቆያል።",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "የቤት እንስሳት በማመልከቻው ውስጥ እንዲካተቱ ይፈልጋሉ?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "ቅፅበት በማህበራዊ ሚዲያ ላይ ወዲያውኑ እንዲጋራ ይፈልጋሉ?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "ቁጠባ ማድረግ ሊያስፈልገን ይችላል።",
    "Müssen es planen" to "ማቀድ ያስፈልጋል",
    "Müssen sparen" to "ማስቀመጥ ያስፈልጋል",
    "Nachricht an" to "መልእክት",
    "Name Partnerin" to "የአጋር ስም",
    "Namen und Startdatum eurer Beziehung." to "የግንኙነትዎ ስሞች እና የመጀመሪያ ቀን።",
    "Natursteinfassade" to "የተፈጥሮ ድንጋይ ፊት ለፊት",
    "Naturteich" to "የተፈጥሮ ኩሬ",
    "Nein, einfach halten" to "አይ፣ ዝም ብለው ይያዙት።",
    "Nein, erstmal privat halten" to "አይ፣ ለጊዜው የግል ያድርጉት",
    "Nein, lieber vor Ort" to "አይ፣ በጣቢያው ላይ የተሻለ",
    "Nein, modern halten" to "አይ፣ ዘመናዊ ያድርጉት",
    "Nein, nur wir" to "አይ፣ እኛ ብቻ",
    "Nein, zu ablenkend" to "አይ፣ በጣም ትኩረትን የሚከፋፍል።",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "አዲስ ሕንፃ ከዘመናዊ ቤት ጋር",
    "Neubau mit Technik" to "አዲስ ሕንፃ በቴክኖሎጂ",
    "Neue Liebe, neue Erfahrungen" to "አዲስ ፍቅር፣ አዲስ ተሞክሮዎች",
    "Neues Hobby" to "አዲስ የትርፍ ጊዜ ማሳለፊያ",
    "Neues Spiel" to "አዲስ ጨዋታ",
    "Neugier" to "የማወቅ ጉጉት።",
    "New York" to "ኒው ዮርክ",
    "New York, USA" to "ኒው ዮርክ፣ አሜሪካ",
    "Nicht mein Fall" to "የእኔ ኩባያ ሻይ አይደለም።",
    "Nicht nötig, lieber klassisch bleiben" to "አስፈላጊ አይደለም፣ ክላሲክ ሆኖ መቆየት ይሻላል",
    "Nichts — es passt so" to "ምንም - ተስማሚ ነው።",
    "Nie wieder Burger" to "በጭራሽ በርገር አይሁን",
    "Nie wieder Pizza" to "ዳግም ፒዛ አታድርጉ",
    "Niemand" to "ማንም",
    "Niemand ohne Plan" to "ያለ እቅድ ማንም የለም።",
    "Nike" to "ናይክ",
    "Nizza" to "ጥሩ",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "ገና ምንም አፍታ የለም።\nየመጀመሪያ ልምድህን ያዝ 💞",
    "Nur bei wichtigen Themen" to "አስፈላጊ ለሆኑ ርዕሶች ብቻ",
    "Nur wir beide" to "ሁለታችንም ብቻ",
    "Nähe & Intimität" to "መቀራረብ እና መቀራረብ",
    "Obstgarten" to "የአትክልት ስፍራ",
    "Oder" to "ወይም",
    "Offene Küche" to "ወጥ ቤት ክፈት",
    "Offene Wohnküche" to "ወጥ ቤት/ሳሎን ክፈት",
    "Ohne Stein" to "ያለ ድንጋይ",
    "Open End" to "መጨረሻው ክፍት ነው።",
    "Outdoor-Küche" to "የውጪ ወጥ ቤት",
    "Outdoor-Sofa" to "የውጪ ሶፋ",
    "Outdoor-Whirlpool" to "የውጪ አዙሪት",
    "Ovaler Diamant" to "ሞላላ አልማዝ",
    "Paar" to "ጥንድ",
    "Paar-Statistiken" to "የጥንዶች ስታቲስቲክስ",
    "Paris" to "ፓሪስ",
    "Paris, Frankreich" to "ፓሪስ፣ ፈረንሳይ",
    "Partner" to "አጋር",
    "Partner-Simulator" to "የአጋር አስመሳይ",
    "Partnerin" to "አጋር",
    "Party Edition" to "የድግስ እትም።",
    "Party Edition II" to "የድግስ እትም II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "አንድ እንስሳ ከዕለት ተዕለት ሕይወታችን ጋር እንኳን ይስማማል?",
    "Pasta" to "ፓስታ",
    "Pastell" to "pastel",
    "Penthouse mit Ausblick" to "Penthouse ከእይታ ጋር",
    "Pepsi" to "ፔፕሲ",
    "Pergola mit Lounge" to "ፐርጎላ ከላውንጅ ጋር",
    "Pfingstrosen" to "ፒዮኒዎች",
    "Pinguin" to "ፔንግዊን።",
    "Pistazie" to "ፒስታቺዮ",
    "Pizza" to "ፒዛ",
    "Pizzaofen" to "ፒዛ ምድጃ",
    "Platin" to "ፕላቲነም",
    "PlayStation" to "PlayStation",
    "Pool" to "ገንዳ",
    "Pop" to "ፖፕ",
    "Prasselnder Kamin" to "የሚያገሣ የእሳት ቦታ",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "ልዕልቶች፣ ወንበዴዎች እና ተረት አቧራ፡ የዲስኒ ጥያቄዎች",
    "Privater Innenhof" to "የግል ግቢ",
    "Profil" to "መገለጫ",
    "Profil bearbeiten" to "መገለጫን ያርትዑ",
    "Prozentual nach Einkommen" to "በገቢ ላይ የተመሰረተ መቶኛ",
    "Quiz verlassen" to "ጥያቄዎችን አቋርጥ",
    "Quiz verlassen?" to "ጥያቄ ይተው?",
    "Rausgehen in die Natur" to "ወደ ተፈጥሮ ውጣ",
    "Reden vor ..." to "በማናገር ላይ...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "መደበኛ ቀኖችን ወይም ጊዜን አንድ ላይ ያውጡ",
    "Reisen" to "ጉዞ",
    "Reiseziele" to "የጉዞ መዳረሻዎች",
    "Respektlosigkeit" to "ንቀት",
    "Restaurant" to "ምግብ ቤት",
    "RnB / Soul" to "RnB / ሶል",
    "Rock" to "ሮክ",
    "Rom" to "ሮም",
    "Rom, Italien" to "ሮም፣ ጣሊያን",
    "Romantik" to "ፍቅር",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "እንደ መልዕክቶች፣ ማስታወሻዎች ወይም ስጦታዎች ያሉ የፍቅር ምልክቶች ደስተኛ ያደርጉኛል።",
    "Romantische Stimmung" to "የፍቅር ስሜት",
    "Roségold" to "ሮዝ ወርቅ",
    "Ruhig zu zweit" to "ለሁለት ጸጥታ",
    "Runder Diamant" to "ክብ አልማዝ",
    "Salted Caramel" to "ጨዋማ ካራሚል",
    "Sammle Ideen..." to "ሃሳቦችን ሰብስብ...",
    "Santorini" to "ሳንቶሪኒ",
    "Santorini, Griechenland" to "ሳንቶሪኒ፣ ግሪክ",
    "Saphir" to "ሰንፔር",
    "Saunahaus" to "ሳውና ቤት",
    "Schickes Restaurant oder Hotel" to "የሚያምር ምግብ ቤት ወይም ሆቴል",
    "Schlafzimmer" to "መኝታ ቤት",
    "Schließen" to "ዝጋ",
    "Schmal & zart" to "ቀጭን እና ቀጭን",
    "Schnappschüsse aus unserer Liebesgeschichte" to "የፍቅር ታሪካችን ቅጽበታዊ እይታዎች",
    "Schokolade" to "ቸኮሌት",
    "Schreib frei, was dir wirklich dazu einfällt." to "ወደ አእምሮ የሚመጣውን በነጻነት ይጻፉ።",
    "Schreibe deine eigene Antwort" to "የራስዎን መልስ ይጻፉ",
    "Sehr gerne" to "እንኳን ደህና መጣህ",
    "Sehr leicht" to "በጣም ቀላል",
    "Sehr wichtig — Fotos und Video" to "በጣም አስፈላጊ - ፎቶዎች እና ቪዲዮዎች",
    "Sehr wichtig, es sollte persönlich sein" to "በጣም አስፈላጊ፣ ግላዊ መሆን አለበት።",
    "Selbst kochen" to "ራስህን አብስል",
    "Senden" to "ላክ",
    "Separate Küche" to "የተለየ ወጥ ቤት",
    "Serie schauen" to "ተከታታዩን ይመልከቱ",
    "Serienmarathon auf dem Sofa" to "ተከታታይ ማራቶን በሶፋው ላይ",
    "Sex & Liebe" to "ወሲብ እና ፍቅር",
    "Seychellen" to "ሲሸልስ",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "ለአንድ ልጅ/በርካታ ልጆች ሁሉንም ወጪዎች መሸፈን እንችላለን? 💰",
    "Soll der Antrag eine Überraschung sein?" to "ሀሳቡ አስገራሚ ሊሆን ይገባል?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "አፕሊኬሽኑ ባህላዊ ወይም ባህላዊ አካላትን መያዝ አለበት?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "አፕሊኬሽኑ ባህላዊ ወይም ባህላዊ አካላትን መያዝ አለበት?",
    "Sommerhochzeit" to "የበጋ ሰርግ",
    "Sonnige Dachterrasse" to "ፀሐያማ የጣሪያ እርከን",
    "Sowohl als auch" to "ሁለቱም እና",
    "Spazieren" to "በእግር ይራመዱ",
    "Spaß & Abenteuer" to "አዝናኝ እና ጀብዱ",
    "Speichern" to "አስቀምጥ",
    "Spiel bearbeiten" to "ጨዋታውን ያርትዑ",
    "Spielbereich für Kinder" to "ለልጆች መጫወቻ ቦታ",
    "Spiele" to "ጨዋታዎች",
    "Spiele spielen und Spaß haben" to "ጨዋታዎችን ይጫወቱ እና ይዝናኑ",
    "Spontan" to "ድንገተኛ",
    "Sportplatz" to "የስፖርት ሜዳ",
    "Spotify" to "Spotify",
    "Sprache" to "ቋንቋ",
    "Stadt" to "ከተማ",
    "Stadt oder Land — was ist uns wichtiger?" to "ከተማ ወይም ሀገር - ለእኛ የበለጠ አስፈላጊ የሆነው ምንድነው?",
    "Stadtvilla" to "የከተማ ቪላ",
    "Standesamt & Party" to "መዝገብ ቤት እና ፓርቲ",
    "Statement-Ring" to "መግለጫ ቀለበት",
    "Stilvolles Outdoor-Sofa" to "የሚያምር የውጪ ሶፋ",
    "Stimme voll zu" to "ሙሉ በሙሉ እስማማለሁ።",
    "Stimmt" to "ትክክል",
    "Stimmt nicht" to "እውነት አይደለም።",
    "Stimmt, noch nie" to "እውነት ነው፣ በጭራሽ",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "የባህር ዳርቻ ቀን",
    "Streit über Haushalt" to "በቤተሰብ ጉዳይ ላይ አለመግባባት",
    "Studio Ghibli" to "ስቱዲዮ ጊቢሊ",
    "Ständig" to "ያለማቋረጥ",
    "Suche schließen" to "ፍለጋ ዝጋ",
    "Suche zurücksetzen" to "ፍለጋን ዳግም አስጀምር",
    "Suche öffnen" to "ፍለጋ ክፈት",
    "Suchergebnisse" to "የፍለጋ ውጤቶች",
    "Sushi" to "ሱሺ",
    "Süß" to "ጣፋጭ",
    "Tage zusammen 💞" to "ቀናት አብረው 💞",
    "Tauche ins Unterbewusstsein" to "ወደ ንዑስ ንቃተ ህሊና ዘልቀው ይግቡ",
    "Teile alle deine Hobbys mit deinem Partner" to "ሁሉንም የትርፍ ጊዜ ማሳለፊያዎችዎን ለባልደረባዎ ያካፍሉ።",
    "Teils teils" to "በከፊል ከፊል",
    "Testen" to "ሙከራ",
    "Themen" to "ርዕሰ ጉዳዮች",
    "Tiefe Gespräche" to "ጥልቅ ንግግሮች",
    "Tiefgründige Gespräche führen" to "ጥልቅ ውይይት አድርጉ",
    "Tierpension" to "የእንስሳት መሣፈሪያ",
    "Tiny House" to "ትንሽ ቤት",
    "Tippen zum Auswählen & Scrollen" to "ለመምረጥ እና ለማሸብለል ነካ ያድርጉ",
    "Tippen zum Zuklappen" to "ለመሰብሰብ መታ ያድርጉ",
    "Titel" to "ርዕስ",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "ርዕስ፣ ምድብ፣ ርዕስ፣ መለያዎች፣ ጥያቄዎች...",
    "Tokyo, Japan" to "ቶኪዮ፣ ጃፓን።",
    "Traditioneller Name" to "ባህላዊ ስም",
    "Traumhaus Außenbereich" to "የሕልም ቤት ከቤት ውጭ አካባቢ",
    "Traumhochzeit" to "ህልም ሰርግ",
    "Treffer" to "ምታ",
    "Tägliche Aktivität" to "ዕለታዊ እንቅስቃሴ",
    "Umformulieren" to "እንደገና ሀረግ",
    "Unbeantwortet" to "መልስ አላገኘም።",
    "Unbeliebte Meinungen" to "ተወዳጅ ያልሆኑ አስተያየቶች",
    "Universal Studios Genie oder Neuling?" to "ሁለንተናዊ ስቱዲዮ አዋቂ ወይስ አዲስ ሰው?",
    "Uns auseinanderzuleben" to "ተለያይቶ ለማደግ",
    "Unser Intimleben" to "የቅርብ ህይወታችን",
    "Unser Traumhaus" to "የኛ ህልም ቤት",
    "Unser erstes Treffen" to "የመጀመሪያ ስብሰባችን",
    "Unsere Gesichter" to "ፊቶቻችን",
    "Unsere eigenen Träume" to "የራሳችን ህልሞች",
    "Unsere nächste Reise" to "ቀጣዩ ጉዞአችን",
    "Unter 1000" to "ከ1000 በታች",
    "Unter 1000 im Monat" to "በወር ከ1000 በታች",
    "Unter 50€/Monat" to "ከ50€ በታች በወር",
    "Unter Leuten" to "በሰዎች መካከል",
    "Untreue" to "አለመታመን",
    "Urlaub" to "የእረፍት ጊዜ",
    "Vanille" to "ቫኒላ",
    "Venedig" to "ቬኒስ",
    "Venedig, Italien" to "ቬኒስ፣ ጣሊያን",
    "Verbinde dich mit" to "ተገናኝ",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "መልሱን ለማየት ከ \${profile.partnerName} ጋር ይገናኙ",
    "Verbindung" to "ግንኙነት",
    "Verbringe die Feiertage mit deiner Familie" to "በዓላቱን ከቤተሰብዎ ጋር ያሳልፉ",
    "Verlobungsringe" to "የተሳትፎ ቀለበቶች",
    "Vertrautheit" to "መተዋወቅ",
    "Viel getrennt" to "ብዙ መለያየት",
    "Vielleicht ein oder zwei" to "ምናልባት አንድ ወይም ሁለት",
    "Vielleicht, aber mündlich reicht" to "ምናልባት፣ ግን በቃላት በቂ ነው።",
    "Vielleicht, wenn es machbar ist" to "ምናልባት ከተቻለ",
    "Vielleicht, wenn es passt" to "ምናልባት የሚስማማ ከሆነ",
    "Vintage Art déco" to "ቪንቴጅ ጥበብ Deco",
    "Vintage verspielt" to "ቪንቴጅ ተጫዋች",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "በባልደረባዎ ከአዳዲስ የትርፍ ጊዜ ማሳለፊያዎች ጋር መተዋወቅ",
    "Vor dem Kauf eines Hauses besprechen" to "ቤት ከመግዛትዎ በፊት ተወያዩ",
    "Vor der Anschaffung eines Haustiers besprechen" to "የቤት እንስሳ ከመግዛትዎ በፊት ተወያዩ",
    "Vor der gemeinsamen Reise besprechen" to "አብራችሁ ከመጓዝዎ በፊት ተወያዩ",
    "Vor nichts" to "ምንም",
    "Vorort" to "የከተማ ዳርቻ",
    "Walnuss" to "ዋልነት",
    "Wandern" to "የእግር ጉዞ",
    "Wann fühlst du dich mir am nächsten?" to "መቼ ነው ለእኔ በጣም የቀረበህ የሚሰማህ?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "በአካል ከእኔ ጋር የቀረብከው መቼ ነው?",
    "Was bedeutet Vertrauen für dich konkret?" to "መተማመን ማለት ለእርስዎ ምን ማለት ነው?",
    "Was entspannt dich mehr?" to "የበለጠ ምን ያዝናናዎታል?",
    "Was fehlt dir über die Distanz am meisten?" to "ስለ ርቀቱ በጣም የሚናፍቀው ምንድን ነው?",
    "Was gefällt dir an deinem Zuhause am besten?" to "ስለ ቤትዎ በጣም የሚወዱት ምንድነው?",
    "Was hast du von deinem Partner gelernt?" to "ከባልደረባዎ ምን ተማራችሁ?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "ወሲባዊ ይዘት ያላቸውን አብረው ስለመመልከት ምን ያስባሉ?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "ስለ መደገፊያዎች (ለምሳሌ ምልክቶች፣ ፊኛዎች፣ ወዘተ) ምን ያስባሉ?",
    "Was ist das Wichtigste beim Antrag?" to "ሲያመለክቱ በጣም አስፈላጊው ነገር ምንድን ነው?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "በግብረ-ሥጋ ግንኙነት ውስጥ በጣም አስፈላጊው ነገር ምንድን ነው?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "የሚወዱት የእኛ ፎቶ የቱ ነው? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "አብሮ ለመኖር የሚያስፈራዎት ነገር ምንድን ነው?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "የምትወደው ምግብ ምንድን ነው ነገር ግን የትዳር ጓደኛህ ሊረዳው አልቻለም?",
    "Was ist für dich ein absoluter Dealbreaker?" to "ፍፁም ድርድር የሚያፈርስህ ምንድን ነው?",
    "Was ist für jeden von uns das absolute Highlight?" to "ለእያንዳንዳችን ፍጹም ድምቀት ምንድነው?",
    "Was ist passiert?" to "ምን ሆነ?",
    "Was macht einen Moment für dich romantisch?" to "አንድ አፍታ የፍቅር ስሜት የሚፈጥርልህ ምንድን ነው?",
    "Was magst du an deinem Partner am liebsten?" to "ስለ አጋርዎ በጣም የሚወዱት ምንድነው?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "የተሻለ ምን ይወዳሉ፡ በማለዳ መነሳት ወይስ በማረፍድ?",
    "Was magst du lieber?" to "የትኛውን የበለጠ ይወዳሉ?",
    "Was möchtest du eigentlich sagen?" to "በእውነቱ ምን ማለት ይፈልጋሉ?",
    "Was möchtest du, dass dein Partner öfter tut?" to "አጋርዎ ብዙ ጊዜ ምን እንዲያደርግ ይፈልጋሉ?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "ስንጓዝ እንስሳው ምን ይሆናል?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "ልጃችን ሲያድግ ምን ይሆናል?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "እንደ ወላጅ ፈጽሞ ልንረሳው የማይገባ ነገር ምንድን ነው?",
    "Was war dein schönster Moment mit mir bisher?" to "እስካሁን ከእኔ ጋር ያላችሁ ምርጥ ጊዜ ምን ነበር?",
    "Was wir gegessen haben" to "የበላነው",
    "Was wollt ihr nie vergessen?" to "በፍፁም መርሳት የሚፈልጉት ምንድን ነው?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "ለአንተ የሚከፋው ምንድን ነው፡ ዳግም ፒዛ አታድርግ ወይንስ በርገር አትሁን?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "አብራችሁ በአንድ ቀን ምን ማድረግ ትፈልጋላችሁ?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "ገንዘብ ችግር ካልሆነ ምን ይለውጣሉ?",
    "Weiter" to "ቀጣይ",
    "Weiter spielen" to "መጫወቱን ይቀጥሉ",
    "Weiß ich noch nicht" to "እስካሁን አላውቅም",
    "Weiße Rosen" to "ነጭ ጽጌረዳዎች",
    "Weißgold" to "ነጭ ወርቅ",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "ልጃችን በእርግጠኝነት ከእኛ ምን ዓይነት ጥራት ማግኘት አለበት?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "ለፕሮፖዛል ምን አካባቢ ይፈልጋሉ?",
    "Welcher Raum sagt am meisten über dich aus?" to "ስለእርስዎ የበለጠ የሚናገረው የትኛው ክፍል ነው?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "ለምግብ እና የእንስሳት ህክምና ምን ባጀት ነው ያቀድነው?",
    "Welches Lied macht dich an? 🥵" to "የትኛውን ዘፈን ነው የሚያበራህ? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "የሚወዱት የትኛውን የጋራ ፎቶ ነው?",
    "Wellnessbad" to "የጤንነት መታጠቢያ",
    "Wenn es schwierig ist" to "ነገሮች አስቸጋሪ ሲሆኑ",
    "Wenn ich müde bin" to "ሲደክመኝ",
    "Wenn wir uns lange umarmen" to "ለረጅም ጊዜ ስንተቃቀፍ",
    "Wenn wir zusammen lachen" to "አብረን ስንስቅ",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "ምን ማዘዝ እንዳለበት በፍጥነት የሚወስን ማነው?",
    "Wer findet die besten Restaurants?" to "ምርጥ ምግብ ቤቶችን የሚያገኘው ማነው?",
    "Wer gibt mehr Herzlichkeit?" to "የበለጠ ሙቀት የሚሰጠው ማነው?",
    "Wer hat den besseren Musikgeschmack?" to "በሙዚቃ የተሻለ ጣዕም ያለው ማነው?",
    "Wer hängt mehr an seinen Eltern?" to "ከወላጆቻቸው ጋር የበለጠ የተቆራኘ ማን ነው?",
    "Wer ist besser organisiert?" to "የተሻለ የተደራጀው ማነው?",
    "Wer ist der Beste bei der Filmauswahl?" to "ፊልሞችን በመምረጥ ረገድ ምርጡ የሆነው ማነው?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "የፍቅር ቀጠሮዎችን በማቀድ ምርጡ ማን ነው?",
    "Wer ist der beste Tänzer?" to "ምርጡ ዳንሰኛ ማን ነው?",
    "Wer ist romantischer?" to "የበለጠ የፍቅር ስሜት ያለው ማነው?",
    "Wer kocht besser?" to "የተሻለ የሚያበስለው ማነው?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "እድሳት እና ጥገናን የሚንከባከበው ማነው?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "ሌላው ሰው ጥሩ ስሜት ሳይሰማው ሲቀር ማን ቶሎ ያስተውላል?",
    "Wer sucht am Ende wirklich den Film aus?" to "ፊልሙን በመጨረሻ የመረጠው ማነው?",
    "Wer vergisst eher einen Jahrestag?" to "አመታዊ በዓልን የመርሳት ዕድሉ ከፍ ያለ ማነው?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "በማግስቱ ጠዋት የራሳቸውን ስም የመርሳት ዕድላቸው ሰፊ የሆነው ማን ነው?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "በማግስቱ ስለሱ ምንም የማያውቁትን ቪዲዮ የማግኘት ዕድሉ ሰፊ የሆነው ማን ነው?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "በማያውቁት ሰው ሶፋ ላይ ማደርን የሚመርጥ ማን ነው?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "ድግስ ላይ ተኝተው ሻርፒን ፊታቸው ላይ ደፍተው ከእንቅልፋቸው ሊነቁ የሚችሉት ማን ነው?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "በዳንስ ወለል ላይ ለመንሸራተት ግን አሪፍ እንቅስቃሴ የሚያስመስለው ማን ነው?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "በቤት ድግስ ላይ የSpotify አጫዋች ዝርዝሩን የመቆጣጠር ዕድሉ ከፍ ያለ ማን ነው?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "ፒዛን በፓርቲ ላይ ለሁሉም አዝዞ እራሱ የበላው ማን ነው?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "በፓርቲ ላይ መጀመሪያ የመተኛት ዕድሉ ማን ነው?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "ድግስ ላይ በድንገት ማጽዳት የሚጀምር ማን ነው?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "ተቃራኒው ከሆነ ሙሉ በሙሉ ጠንቃቃ ነኝ ሊል የሚችል ማን ነው?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "በመጀመሪያ በክርክር ውስጥ ለመስጠት የበለጠ ዕድል ያለው ማነው?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "በመጠጫ ጨዋታ ላይ ለማጭበርበር የበለጠ ዕድል ያለው ማነው?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "ቡፌውን ወርሮ በድብቅ ወደ ቤት ሊወስድ የሚችል ማን ነው?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "በጣም አሳፋሪ የሆነውን የምሽቱን ፎቶ በታሪካቸው ላይ ለመለጠፍ የበለጠ ዕድል ያለው ማን ነው?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "ዲጄው የራሳቸውን ተወዳጅ ዘፈን እንዲጠይቁ የበለጠ የሚያናድደው ማን ነው?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "ግጥሞቹን ከቁልፍ ውጪ ዘፈን የመዝፈን ዕድሉ ከፍ ያለ፣ ግን በእርግጠኝነት ማን ሊሆን ይችላል?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "በምናሌው ላይ በጣም ውድ የሆነውን መጠጥ ለማዘዝ እና የሚቆጨው ማን ነው?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "ጎረቤቶቹን በጩኸቱ ቢያማርሩ ማን ሊጋብዝ ይችላል?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "የፓርቲ ጨዋታዎችን (እንደ ቢራ ፖንግ) በቁም ነገር የሚመለከተው ማነው?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "ቪአይፒ መዳረሻ ለማግኘት ከወራሾቹ ጋር የበለጠ ጓደኝነት የሚፈጥር ማን ነው?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "ድንገተኛ የካራኦኬ ጦርነትን የመጀመር ዕድሉ ሰፊ የሆነው ማን ነው?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "ጠርሙስ መክፈቻ ሳይጠቀሙ ጠርሙስ የመክፈት እድሉ ማን ነው?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "ማንም የጠየቀ ባይኖርም ማን የበለጠ ንግግር ሊያደርግ ይችላል?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "በመታጠቢያ ቤት ውስጥ አንድ ሰዓት የራስ ፎቶዎችን በማንሳት የማሳለፍ ዕድሉ የበለጠ ማን ነው?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "አሳፋሪ የዳንስ ትርኢት ቀርቦ ለማክበር የበለጠ ማን ሊሆን ይችላል?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "ፓርቲው ካለቀ በኋላ ለቀድሞ አጋር የመጥራት ዕድሉ ሰፊ የሆነው ማን ነው?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "እንግዳ እንግዳን በአጋጣሚ ሊያሰናክል የሚችል ማን ነው?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "ሳይሰናበቱ ከፓርቲው በድብቅ የመውጣት ዕድሉ ማን ነው?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "እንግዶቹን ከማነጋገር ከአስተናጋጁ የቤት እንስሳ ጋር መጫወትን የሚመርጥ ማነው?",
    "Wer würde eher spontan eine Reise buchen?" to "በድንገት ጉዞ የመመዝገብ ዕድሉ ማን ነው?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "በኩሽና ውስጥ ለሰዓታት ጥልቅ ውይይት ለማድረግ የበለጠ ዕድል ያለው ማን ነው?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "የሌላ ሰውን መጠጥ በአጋጣሚ የመጠጣት ዕድሉ ከፍተኛ የሆነው ማን ነው?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "ውድ የአበባ ማስቀመጫ ወይም ደካማ የሆነ ነገር በድንገት ማንኳኳቱ የበለጠ ማን ሊሆን ይችላል?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "ውስብስብ ኮክቴልን ራሳቸው በማዋሃድ እና በከፋ ሁኔታ ለመክሸፍ የበለጠ የሚሞክር ማን ነው?",
    "Wer würde eher zu spät kommen?" to "ለማዘግየት የበለጠ ዕድል ያለው ማን ነው?",
    "Wer würde eher?" to "ማን ይመርጣል?",
    "Wer übernimmt die tägliche Versorgung?" to "የዕለት ተዕለት እንክብካቤን ማን ይንከባከባል?",
    "Werde so akzeptiert, wie du bist" to "እንዳንተ ተቀበል",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "ለልጁ/ልጆች በቂ ጊዜ ይኖረናል? ⏳",
    "Whirlpool" to "ሙቅ ገንዳ",
    "White Chocolate" to "ነጭ ቸኮሌት",
    "Widgets" to "መግብሮች",
    "Wie fühlst du dich am meisten geliebt?" to "በጣም እንደተወደዱ ምን ይሰማዎታል?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "ከተለያዩ ገቢዎች ጋር እንዴት እንይዛለን?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "የትዳር ጓደኛዎ ከእርስዎ ጋር የግብረ ሥጋ ግንኙነት ለመጀመር ከሁሉ የተሻለው መንገድ ምንድነው?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "አጋርዎ ለእርስዎ እንዴት የተሻለ አጋር ሊሆን ይችላል?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "ከፕሮፖዛሉ በኋላ ምን ያህል ጊዜ ከሌሎች ጋር ማክበር ይፈልጋሉ?",
    "Wie lange wollen wir dort mindestens bleiben?" to "ቢያንስ እዚያ ለምን ያህል ጊዜ መቆየት እንፈልጋለን?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "ስለ ምኞቶች ማውራት ለእርስዎ ምን ያህል ቀላል ነው?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "የወደፊት ሕይወታችን ምን እንዲመስል ይፈልጋሉ?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "ፍጹም የሆነ እሑድዎ በቤትዎ ምን ይመስላል?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "በወሲብ ወቅት ስለ ቆሻሻ ንግግር ምን ይሰማዎታል?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "በተጨባጭ ምን ያህል ብድር መክፈል እንችላለን?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "ተለያይተን ምን ያህል ጊዜ ማሳለፍ እንፈልጋለን?",
    "Wie viel wollen wir insgesamt ausgeben?" to "በአጠቃላይ ምን ያህል ማውጣት እንፈልጋለን?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "ሕፃኑ ከመጣ በኋላ እንዴት ለግንኙነታችን ጊዜ እናገኛለን?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "ጊዜው መያዙ ለእርስዎ ምን ያህል አስፈላጊ ነው?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "ማመልከቻው የትርፍ ጊዜ ማሳለፊያዎችዎን ወይም ፍላጎቶችዎን ማንጸባረቁ ለእርስዎ ምን ያህል አስፈላጊ ነው?",
    "Wie würdest du sie/ihn nennen?" to "ምን ብለው ይጠሩታል?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "ከወሲብ ውጪ ፍቅርን ለማሳየት የምትወደው መንገድ የትኛው ነው?",
    "Wildblumen" to "የዱር አበባዎች",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "ሴት ወይም ወንድ ልጅ ይፈልጋሉ? 👶",
    "Wintergarten" to "የክረምት የአትክልት ስፍራ",
    "Winterhochzeit" to "የክረምት ሰርግ",
    "Wir bestellen einfach beides" to "ሁለቱንም ብቻ እናዝዛለን።",
    "Wir brauchen ewig" to "ለዘላለም ይወስደናል።",
    "Wir einigen uns nie" to "በፍጹም አንስማማም።",
    "Wir entscheiden es gemeinsam" to "አብረን እንወስናለን።",
    "Wir treffen uns in der Mitte" to "መሀል ላይ እንገናኛለን።",
    "Wir wechseln uns ab" to "ተራ በተራ እናደርጋለን",
    "Wird stressig" to "ይጨነቃል",
    "Wobei lachst du am meisten?" to "በጣም የሚያስቅዎት ምንድን ነው?",
    "Wofür sparen wir gemeinsam?" to "አብረን ምን እያጠራቀምን ነው?",
    "Wohnzimmer" to "ሳሎን",
    "Woran erinnerst du dich am lebhaftesten?" to "በጣም ምን ታስታውሳለህ?",
    "Worauf freust du dich bei uns am meisten?" to "ከእኛ ጋር በጣም የሚፈልጉት ምንድን ነው?",
    "Worte/Komplimente" to "ቃላት/ምስጋናዎች",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "በግንኙነታችን ውስጥ በጣም የምትፈራው ምንድን ነው?",
    "Wünsche? z.B. günstig, draußen" to "ምኞቶች? ለምሳሌ. ርካሽ ፣ ውጭ",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "ለዕረፍት (ጉዞን ጨምሮ) ሀሳብ ማቅረብ ይፈልጋሉ?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube Music",
    "Zeichne für mich" to "ይሳሉልኝ",
    "Zeichne mich als Tier — welches wäre ich?" to "እንደ እንስሳ ይሳቡኝ - የትኛውን ልሆን?",
    "Zeichne unser Gefühl zueinander als Symbol." to "ስሜታችንን እርስ በርስ እንደ ምልክት ይሳሉ።",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "የህልም ቤታችንን በአንድ መስመር ይሳሉ። በጣም የሚያስደንቀው ነገር ምንድን ነው?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "የመጀመሪያ ቀኖቻችንን ይሳሉ - በምስሉ ላይ በእርግጠኝነት ምን መሆን አለበት?",
    "Zeichnen" to "ይሳሉ",
    "Zeit füreinander" to "የእርስ በርስ ጊዜ",
    "Zeit, wenn das Baby schläft" to "ህፃኑ የሚተኛበት ጊዜ",
    "Zelten gehen" to "ወደ ካምፕ ይሂዱ",
    "Zitrone" to "ሎሚ",
    "Zu Hause, gemütlich und privat" to "ቤት ውስጥ፣ ምቹ እና የግል",
    "Zu einem Picknick gehen" to "ወደ ሽርሽር መሄድ",
    "Zu einem ausgefallenen Abendessen gehen" to "ወደሚያምር እራት በመሄድ ላይ",
    "Zu zweit reisen" to "እንደ ጥንዶች ተጓዙ",
    "Zuhause & Alltag" to "ቤት እና የዕለት ተዕለት ኑሮ",
    "Zuhören" to "ያዳምጡ",
    "Zurück" to "ተመለስ",
    "Zusammen seit" to "ጀምሮ",
    "Zusammen seit (TT.MM.JJJJ)" to "ከ (ከዲ.ኤም. ዓ.ዓ.) ጀምሮ አንድ ላይ",
    "Zusammenziehen" to "ውል",
    "Zustimmen oder Ablehnen" to "እስማማለሁ ወይም አልስማማም።",
    "Zwei Kreise, die sich überschneiden" to "ሁለት የሚደራረቡ ክበቦች",
    "Zwei Stühle davor" to "ከፊት ለፊቱ ሁለት ወንበሮች",
    "Zärtlich sein" to "ጨረታ ሁን",
    "Öfter als ich zugebe" to "ከተቀበልኩት በላይ ብዙ ጊዜ",
    "Über 100€/Monat" to "በወር ከ100€ በላይ",
    "Über 2000 im Monat" to "በወር ከ2000 በላይ",
    "Über mich selbst" to "ስለራሴ",
    "Übernehmen" to "ያመልክቱ",
    "Überraschend" to "የሚገርም",
    "Überraschung" to "ይገርማል",
    "Überspringen" to "ዝለል",
    "Übertrieben und großartig" to "ከሁሉም በላይ እና ግሩም",
    "✎ Tippe, um zu antworten" to "ምላሽ ለመስጠት ንካ",
    "✨ GFK-Brücke" to "✨ ጂፒፕ ድልድይ",
)

internal fun localizeAmharicDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_AMHARIC_CONTENT)
