package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_ARABIC_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 سنوات",
    "1000 - 1500 im Monat" to "1000 - 1500 شهريا",
    "1000 bis 3000" to "من 1000 إلى 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 شهريا",
    "3000 bis 5000" to "من 3000 إلى 5000",
    "5-10 Jahre" to "5-10 سنوات",
    "50-100€/Monat" to "50-100 يورو/الشهر",
    "Ab 100€" to "ابتداءً من 100 يورو",
    "Ab 500€" to "ابتداءً من 500 يورو",
    "Ab 50€" to "ابتداءً من 50 يورو",
    "Ab und zu" to "بين الحين والآخر",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "ما المبلغ الذي نحتاج إلى إنفاقه قبل إجراء عملية الشراء؟",
    "Abbrechen" to "إلغاء",
    "Abenteuer" to "مغامرة",
    "Adidas" to "أديداس",
    "Aktivitäten" to "الأنشطة",
    "Alle" to "الكل",
    "Alle Pakete" to "جميع الحزم",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "اخسر كل أصدقائك باستثناء صديقك المفضل",
    "Alle intimen Momente selbst initiieren" to "ابدأ كل اللحظات الحميمية بنفسك",
    "Alles davon" to "كل ذلك",
    "Alles, was noch kommt" to "كل ما سيأتي",
    "Alltagsroutine" to "الروتين اليومي",
    "Alltägliche Berührungen" to "لمسات يومية",
    "Altbau mit Charme" to "مبنى قديم ذو سحر",
    "Am Strand" to "على الشاطئ",
    "Am liebsten alles zusammen" to "ويفضل أن يكون كل شيء معًا",
    "Am selben Tag mit Freunden/Familie" to "في نفس اليوم مع الأصدقاء/العائلة",
    "Amazon" to "أمازون",
    "Amsterdam" to "أمستردام",
    "Amsterdam, Niederlande" to "أمستردام، هولندا",
    "An das Gefühl" to "من الشعور",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "في مكان عام به العديد من المتفرجين",
    "An einen Geruch" to "من الرائحة",
    "An einen Song" to "إلى أغنية",
    "An etwas, das ich gesagt habe" to "شيء قلته",
    "Analyse starten" to "ابدأ التحليل",
    "Analysiere eure Muster..." to "قم بتحليل أنماطك...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "قم بتحليل إجاباتك ومحادثاتك وفقًا لـ Gottman وGFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "طعم الأناناس على البيتزا لذيذ.",
    "Android" to "أندرويد",
    "Antwort mit einem Foto" to "الرد بصورة",
    "Antwortähnlichkeit" to "تشابه الإجابة",
    "App-Sprache auswählen" to "حدد لغة التطبيق",
    "Auf eine Bootsparty gehen" to "الذهاب إلى حفلة على متن قارب",
    "Aufmerksamkeit" to "انتبه",
    "Aufräumen und Projekte angehen" to "تنظيف المشاريع ومعالجتها",
    "Aufwärmen" to "الإحماء",
    "Aufwärmen: Einander kennenlernen" to "الإحماء: التعرف على بعضنا البعض",
    "Aus dem Urlaub" to "من الإجازة",
    "Ausgefallener Name" to "اسم فاخر",
    "Ausschlafen und faulenzen" to "نم واسترخِ",
    "Ausschlafen und nichts tun" to "نم ولا تفعل شيئًا",
    "Aussehen" to "المظهر",
    "Auto" to "تلقائي",
    "Außenkamin" to "مدفأة خارجية",
    "BEANTWORTE" to "الإجابة",
    "Bali" to "بالي",
    "Bali, Indonesien" to "بالي، إندونيسيا",
    "Banane" to "الموز",
    "Beantwortet" to "تمت الإجابة عليه",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "أجب عن الأسئلة في نفس الوقت — لن تكون الإجابات مرئية إلا بعد الانتهاء من ذلك.",
    "Beantwortete Fragen" to "تمت الإجابة على الأسئلة",
    "Bearbeiten" to "تحرير",
    "Bei Insider-Witzen" to "للنكات الداخلية",
    "Bei Memes" to "على الميمات",
    "Bei einer spontanen Berührung" to "عند لمسها تلقائيًا",
    "Beide" to "كلاهما",
    "Beide gleich" to "كلاهما نفس الشيء",
    "Beide zusammen" to "كلاهما معًا",
    "Beide, aber wir tun so als ob nicht" to "كلاهما، ولكننا نتظاهر بعدم ذلك",
    "Beides" to "كلاهما",
    "Beides wäre schlimm" to "كلاهما سيكون سيئًا",
    "Beim Einschlafen nebeneinander" to "النوم بجانب بعضكم البعض",
    "Beim Reden" to "أثناء التحدث",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "الأماكن السياحية الشهيرة دائمًا ما تكون مخيبة للآمال.",
    "Beschreibe unser Sexleben mit einem Emoji." to "صف حياتنا الجنسية برمز تعبيري.",
    "Besser kommunizieren" to "التواصل بشكل أفضل",
    "Bessere Lage" to "موقع أفضل",
    "Bestellen" to "الطلب",
    "Besuchte Länder" to "الدول التي تمت زيارتها",
    "Besuchte Städte" to "المدن التي تمت زيارتها",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "هل تفضل الاقتراح الباهظ أم الخفي؟",
    "Beziehung" to "العلاقة",
    "Bibliothek" to "المكتبة",
    "Bin manchmal unsicher" to "أشعر أحيانًا بعدم الأمان",
    "Bist du ein Videospiel-Guru?" to "هل أنت خبير في ألعاب الفيديو؟",
    "Blumenwiese" to "مرج الزهور",
    "Bunte Blumenwiese" to "مرج الزهور الملونة",
    "Burger" to "البرغر",
    "Burger King" to "برجر كنج",
    "Chat" to "الدردشة",
    "Coca-Cola" to "كوكا كولا",
    "Cookie Dough" to "عجينة البسكويت",
    "Dachgarten mit Lounge" to "حديقة على السطح مع صالة",
    "Dachterrasse" to "تراس على السطح",
    "Das Wetter an dem Tag" to "الطقس في ذلك اليوم",
    "Das erste Selfie" to "أول صورة شخصية",
    "Das meiste weiß ich" to "أعرف معظمها",
    "Das oder das?" to "هذا أم ذاك؟",
    "Das tägliche Leben" to "الحياة اليومية",
    "Dass Zusagen gehalten werden" to "يتم الوفاء بهذه الوعود",
    "Dass alles meinen Stil hat" to "أن كل شيء له أسلوبي",
    "Dass ich alles erzählen kann" to "أستطيع أن أقول كل شيء",
    "Dass ich mich nicht sorgen muss" to "لا داعي للقلق",
    "Dass wir ungestört sind" to "أننا غير منزعجين",
    "Dein Name" to "اسمك",
    "Deine Antwort..." to "إجابتك...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "تم حفظ إجاباتك. بمجرد انتهاء الشريك من الحزمة، ستكون الإجابتان مرئيتين معًا.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "تم حفظ إجاباتك. بمجرد اكتمال \${profile.partnerName} للحزمة، ستكون الاستجابتان مرئيتين معًا.",
    "Deine Beziehung abenteuerlich und spontan machen" to "اجعل علاقتك مليئة بالمغامرة والعفوية",
    "Deine Beziehung stabil und sicher machen" to "اجعل علاقتك مستقرة وآمنة",
    "Deine eigene Antwort" to "إجابتك الخاصة",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "من الأفضل أن تشارك أسرارك العميقة مع شريكك",
    "Deinen besten Freund verlieren" to "فقدان أفضل صديق لك",
    "Denke an dich" to "فكر في نفسك",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "مشاهدة نفس الفيلم مرتين مضيعة للوقت.",
    "Der Blick nach draußen" to "المنظر بالخارج",
    "Der Garten" to "الحديقة",
    "Der Ort" to "المكان",
    "Der Ring und die Geste" to "الخاتم والإيماءة",
    "Der perfekte Heiratsantrag" to "عرض الزواج المثالي",
    "Derjenige sein, der umarmt wird" to "كن الشخص الذي يتم احتضانه",
    "Deutsch" to "الألمانية",
    "Diamant" to "الماس",
    "Diamanten im Band" to "الماس في الفرقة",
    "Die Distanz" to "المسافة",
    "Die Feiertage mit der Familie deines Partners verbringen" to "اقضي العطلة مع عائلة شريكك",
    "Die Gemütlichkeit und Ruhe" to "الراحة والسلام",
    "Die Menschen, die darin wohnen" to "الأشخاص الذين يعيشون فيها",
    "Die Umgebung und Atmosphäre" to "البيئة والجو",
    "Die Worte und Emotionen" to "الكلمات والعواطف",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "التحدي الترفيهي النهائي",
    "Diejenige sein, die umarmt" to "كن الشخص الذي يعانق",
    "Direkt ansprechen" to "العنوان مباشرة",
    "Diskussion" to "مناقشة",
    "Diskutiere vor dem Kinderkriegen" to "ناقش قبل إنجاب الأطفال",
    "Diskutiert eure Antworten" to "ناقش إجاباتك",
    "Disney" to "ديزني",
    "Doch, schon mal" to "نعم، نعم",
    "Draußen mit der Natur als Kulisse" to "في الخارج مع الطبيعة كخلفية",
    "Drei-Stein-Ring" to "خاتم بثلاثة أحجار",
    "Du bist dran" to "إنه دورك",
    "Du fehlst mir" to "أفتقدك",
    "Dubai" to "دبي",
    "Dubai, VAE" to "دبي، الإمارات العربية المتحدة",
    "Dunkles Design" to "المظهر الداكن",
    "Durch Berührung" to "عن طريق اللمس",
    "Durch Worte" to "من خلال الكلمات",
    "Durch Zeit zu zweit" to "عبر الزمن معًا",
    "Durch kleine Gesten" to "من خلال الإيماءات الصغيرة",
    "Durchgeplant" to "مخطط جيدًا",
    "ERGEBNISSE" to "النتائج",
    "Egal, Hauptsache gesund" to "مهما كان الأمر، الشيء الرئيسي هو التمتع بصحة جيدة",
    "Ehepaar Leben" to "الحياة الزوجية",
    "Eher knapp" to "قريب جدًا",
    "Eher nicht" to "ليس كثيرًا",
    "Eher schwer" to "صعب نوعًا ما",
    "Eher schwierig" to "صعب نوعًا ما",
    "Eher zu" to "أشبه",
    "Eifersucht ist ein Zeichen von Liebe." to "الغيرة علامة الحب.",
    "Eigenes Gemüsebeet" to "رقعة خضروات خاصة بك",
    "Ein Abenteuer in einer neuen Stadt" to "مغامرة في مدينة جديدة",
    "Ein Anker" to "مرساة",
    "Ein Balkon oder Garten" to "شرفة أو حديقة",
    "Ein Filmabend" to "ليلة سينمائية",
    "Ein Harmony-Meilenstein eurer Liebe." to "علامة فارقة في حبك.",
    "Ein Herz" to "قلب",
    "Ein Herz an der Tür" to "قلب عند الباب",
    "Ein Jahr lang eine Fernbeziehung führen" to "لديك علاقة بعيدة المدى لمدة عام",
    "Ein Kindheitsessen" to "وجبة الطفولة",
    "Ein Live-Musik-Konzert besuchen" to "حضور حفل موسيقي حي",
    "Ein Museum besuchen" to "قم بزيارة المتحف",
    "Ein Spieleabend" to "ليلة لعبة",
    "Ein Spieleabend mit Freunden" to "ليلة لعب مع الأصدقاء",
    "Ein Urlaubsfoto" to "صورة للإجازة",
    "Ein aktives Abenteuer" to "مغامرة نشطة",
    "Ein entspannender Spa-Tag" to "يوم سبا مريح",
    "Ein ganz normaler Alltagstag" to "يوم عادي تمامًا",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "أمسية مريحة في المنزل أثناء عاصفة رعدية",
    "Ein gemütliches Date drinnen" to "موعد مريح في الداخل",
    "Ein lustiges Bild" to "صورة مضحكة",
    "Ein paar Handyfotos reichen" to "تكفي بعض الصور بالهاتف الخلوي",
    "Ein paar Stunden" to "بضع ساعات",
    "Ein paar kulturelle Anklänge sind okay" to "لا بأس ببعض المراجع الثقافية",
    "Ein romantischer Abend" to "أمسية رومانسية",
    "Ein romantisches Abendessen bei Kerzenlicht" to "عشاء رومانسي على ضوء الشموع",
    "Ein romantisches Bild" to "صورة رومانسية",
    "Ein romantisches Picknick an einem schönen Ort" to "نزهة رومانسية في موقع جميل",
    "Ein schwerer Moment, den wir geschafft haben" to "لحظة صعبة تمكنا من إدارتها",
    "Ein tolles Date im Freien unter dem Mondlicht" to "موعد رائع في الهواء الطلق تحت ضوء القمر",
    "Ein ungewöhnliches Gericht" to "طبق غير عادي",
    "Ein zufälliger Schnappschuss" to "لقطة عشوائية",
    "Einander kennenlernen" to "التعرف على بعضنا البعض",
    "Eine Autoreise" to "رحلة برية",
    "Eine Brücke" to "جسر",
    "Eine Date-Nacht unter den Sternen" to "موعد ليلي تحت النجوم",
    "Eine Million Dollar gewinnen" to "اربح مليون دولار",
    "Eine Million Dollar verdienen" to "اربح مليون دولار",
    "Eine Nacht in einem Club" to "ليلة في النادي",
    "Eine Schokoladenverkostung" to "تذوق الشوكولاتة",
    "Eine Wanderung mit Panoramablick machen" to "قم بنزهة سيرًا على الأقدام واستمتع بالمناظر البانورامية",
    "Eine Weinverkostung" to "تذوق النبيذ",
    "Eine gemeinsame Reise" to "رحلة معًا",
    "Eine gemütliche Nacht zu Hause" to "ليلة مريحة في المنزل",
    "Eine neue Sprache zu lernen ist einfach." to "تعلم لغة جديدة أمر سهل.",
    "Einen Film anschauen" to "شاهد فيلمًا",
    "Einen Monat lang überhaupt nicht miteinander reden" to "عدم التحدث مع بعضكم البعض مطلقًا لمدة شهر",
    "Einen Tanzkurs besuchen" to "خذ دروسًا في الرقص",
    "Einen Vergnügungspark erkunden" to "اكتشف مدينة الملاهي",
    "Einen Wellness-Tag" to "يوم العافية",
    "Einen sehr emotionalen Partner haben" to "وجود شريك عاطفي للغاية",
    "Einen sehr logischen Partner haben" to "وجود شريك منطقي للغاية",
    "Einer zahlt alles" to "شخص واحد يدفع كل شيء",
    "Einfach mehr Alltag" to "ببساطة المزيد من الحياة اليومية",
    "Einfach nebeneinander sein" to "فقط كونوا بجانب بعضكم البعض",
    "Einfach und intim" to "بسيط وحميم",
    "Einige Dinge für dich behalten" to "احتفظ ببعض الأشياء لنفسك",
    "Einmal" to "مرة واحدة",
    "Eins, das nur wir kennen" to "واحد نعرفه نحن فقط",
    "Englisch" to "الإنجليزية",
    "Entspannte Hängematte" to "أرجوحة مريحة",
    "Entspannung" to "الاسترخاء",
    "Erdbeere" to "فراولة",
    "Erfolgreich" to "ناجح",
    "Ergebnisse" to "النتائج",
    "Erst bei sehr großen Summen" to "فقط للمبالغ الكبيرة جدًا",
    "Erst nur enge Freunde/Familie" to "فقط الأصدقاء المقربين/العائلة في البداية",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "يزعجني عندما يستغرق شريكي وقتًا طويلاً للرد على الرسائل.",
    "Essen & Genuss" to "الطعام والاستمتاع",
    "Essensvorlieben" to "تفضيلات الطعام",
    "Etwa eine Woche später, erst mal nur wir" to "بعد حوالي أسبوع، نحن فقط في البداية",
    "Etwas Neues ausprobieren" to "جرب شيئًا جديدًا",
    "Etwas ganz anderes" to "شيء مختلف تمامًا",
    "Etwas sehr Scharfes" to "شيء حاد جدًا",
    "Etwas, das ich selbst gern erfinde" to "شيء أحب أن أخترعه بنفسي",
    "Etwas, eine kleine Note wäre schön" to "شيء ما، ملاحظة صغيرة ستكون لطيفة",
    "Familie" to "العائلة",
    "Familie/Freunde" to "العائلة/الأصدقاء",
    "Familienmensch" to "رجل العائلة",
    "Farbedelstein" to "حجر كريم ملون",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "أحيانًا ما تكون الإعلانات التليفزيونية ممتعة للمشاهدة.",
    "Fertig" to "تم",
    "Fertig!" to "انتهيت!",
    "Feste Date-Nights" to "تاريخ ثابت لليالي",
    "Feuerstelle" to "حفرة النار",
    "Filigran & schlicht" to "تخريمية وبسيطة",
    "Filme/Serien" to "أفلام/مسلسلات",
    "Formuliere um..." to "إعادة الصياغة...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "أعد صياغة مسودتك بطريقة غير عنيفة: الملاحظة، الشعور، الحاجة، الطلب.",
    "Frage hinzufügen" to "أضف سؤالاً",
    "Fragen & Spiele" to "أسئلة وألعاب",
    "Fragen für jede Gelegenheit" to "أسئلة لكل مناسبة",
    "Freizeitpark" to "مدينة ملاهي",
    "Freunde treffen" to "التعرف على الأصدقاء",
    "Freundschaften mit Ex-Partnern sind okay." to "لا بأس بالصداقات مع السابقين.",
    "Früh aufstehen" to "استيقظ مبكرًا",
    "Fußbodenheizung" to "تدفئة تحت الأرضية",
    "Führen wir getrennte oder gemeinsame Konten?" to "هل لدينا حسابات منفصلة أو مشتركة؟",
    "Für dich empfohlen" to "موصى به لك",
    "Für die Zukunft" to "للمستقبل",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "لم يتم العثور على أسئلة أو ألعاب مطابقة لهذا البحث.",
    "Für immer" to "إلى الأبد",
    "Fürsorglichkeit" to "العناية",
    "GFK-Brücke" to "جسر GRP",
    "Galerie" to "المعرض",
    "Gar nicht, der Moment gehört uns" to "لا على الإطلاق، هذه اللحظة ملكنا",
    "Gar nichts tun" to "لا تفعل شيئًا",
    "Geduld" to "الصبر",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "اذهب مبكرًا في الصباح لمشاهدة شروق الشمس",
    "Geht so" to "يسير على هذا النحو",
    "Geister existieren wirklich." to "الأشباح موجودة بالفعل.",
    "Gelassenheit" to "الصفاء",
    "Gelbgold" to "ذهب أصفر",
    "Geld & Finanzen" to "المال والتمويل",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "سافروا حول العالم معًا واكتشفوا ثقافات ومأكولات جديدة",
    "Gemeinsam ein Lego bauen" to "قم ببناء قطعة ليغو معًا",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "جربوا وصفة جديدة معًا في المطبخ",
    "Gemeinsame Konten" to "الحسابات المشتركة",
    "Gemeinsame Nächte" to "ليالي معًا",
    "Gemeinsame Tage" to "أيام معًا",
    "Gemischt" to "مختلط",
    "Gemüsebeet" to "رقعة الخضار",
    "Gemütliche Feuerstelle" to "مدفأة مريحة",
    "Gesprächsanreger" to "بداية المحادثة",
    "Getrennte Konten" to "حسابات منفصلة",
    "Getrennte Urlaube tun einer Beziehung gut." to "الإجازات المنفصلة مفيدة للعلاقة.",
    "Gewächshaus" to "الدفيئة",
    "Glasfassade" to "واجهة زجاجية",
    "Gleichgültigkeit" to "اللامبالاة",
    "Glücklich und frei" to "سعيد ومجاني",
    "Gourmet Eis-Sorten" to "أصناف الآيس كريم الذواقة",
    "Gravur innen" to "نقش بالداخل",
    "Grillplatz" to "منطقة للشواء",
    "Groß & üppig" to "كبيرة ومورقة",
    "Große Familie" to "عائلة كبيرة",
    "Große Feier" to "احتفال كبير",
    "Große Fenster" to "نوافذ كبيرة",
    "Große Fensterfront" to "واجهة نافذة كبيرة",
    "Großer Außenpool" to "حمام سباحة خارجي كبير",
    "Großer Garten" to "حديقة كبيرة",
    "Großer Stein" to "حجر كبير",
    "Größere Küche" to "مطبخ أكبر",
    "Gutes Essen" to "طعام جيد",
    "Habe ich" to "لقد فعلت ذلك",
    "Habe ich noch nie" to "لم أفعل ذلك أبدًا",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "هل اكتشفت أي اختلافات مثيرة للدهشة؟ تحدث عن سبب إعجابك بخيارات معينة بشكل أفضل!",
    "Haus am See" to "منزل بجوار البحيرة",
    "Haus/Wohnung" to "منزل/شقة",
    "Hazelnut" to "البندق",
    "Heimkino" to "مسرح منزلي",
    "Herzhaft" to "القلبية",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "لا يوجد شيء هنا الآن.\nقم بتغيير عامل التصفية أو اختر موضوعًا مختلفًا.",
    "Hilfe im Alltag" to "المساعدة في الحياة اليومية",
    "Himbeere" to "توت العليق",
    "Hinzufügen" to "إضافة",
    "Hobbys" to "الهوايات",
    "Hochzeitssträuße" to "باقات الزفاف",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "فخر منزل هوجورتس: إلى أين تنتمي؟",
    "Home" to "الصفحة الرئيسية",
    "Hot Tub" to "حوض استحمام ساخن",
    "Humor" to "الفكاهة",
    "Hund" to "كلب",
    "Hängematte" to "أرجوحة",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "هل ترغب في الحصول على خطاب مكتوب كجزء من الاقتراح؟",
    "IKEA" to "ايكيا",
    "Ich" to "أنا",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "أفضّل المشي الرومانسي في الحديقة على الذهاب إلى السينما.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "لم أنم أبدًا في السينما.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "أستمتع باكتشاف هوايات أو أنشطة جديدة مع شريكي.",
    "Ich finde eine Alternative" to "سأجد بديلاً",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "أستمتع بتجربة مطاعم جديدة مع شريكي بدلاً من الذهاب دائمًا إلى نفس الأماكن.",
    "Ich habe noch nie" to "لم أفعل ذلك أبدًا",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "لم أخاف أبدًا من الأفعوانية وقد ركبتها على أي حال.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "لم أشتري أبدًا تذاكر Fast Pass لأنني كنت غير صبور.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "لم ألغي أبدًا خططي للبقاء في المنزل ومشاهدة برنامج تلفزيوني.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "لم أنتظر أبدًا رسالتي من هوجورتس.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "لم أقل أبدًا أن سليذرين لم يكن في الواقع بهذا السوء.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "لم أقل أبدًا أنني أكبر من أن أتمكن من مشاهدة أفلام ديزني (واستمتعت بها سرًا).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "لم أسقط مطلقًا عمدا أي شخص باستخدام دبابة زرقاء في ماريو كارت.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "لم أبكي أبدًا في فيلم ديزني.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "لم أغطي عيني مطلقًا أثناء مشاهدة فيلم رعب.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "لم أنس أبدًا حفظ لعبة وخسرت ساعات من التقدم.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "لم أغادر الغرفة مطلقًا أثناء مشهد محرج (عامل محرج).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "لم أقم مطلقًا باتخاذ وضعية مضحكة أثناء التقاط صورة الأفعوانية.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "لم يسبق لي أن لعبت في وقت متأخر من الليل وندمت على مدى التعب الذي شعرت به في اليوم التالي.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "لم يسبق لي أن بحثت في Google عن نهاية أي فيلم لأنني لم أستطع الانتظار.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "لم أشعر أبدًا وكأنني أقف في موقع تصوير فيلم.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "لم أتخطي مطلقًا مقدمة مسلسلي المفضل.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "لم أشارك مطلقًا كلمة مرور Netflix الخاصة بأي شخص آخر.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "لم أستمع مطلقًا إلى الموسيقى التصويرية للعبة أثناء العمل أو الدراسة.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "لم ألوم مطلقًا وحدة التحكم عندما خسرت.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "لم يسبق لي أن تخلصت من لوحة المفاتيح أو وحدة التحكم في حالة من الغضب.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "لم أنس أبدًا الملابس المبللة في الغسالة لبضعة أيام.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "لم أنفق أبدًا أموالًا حقيقية على عناصر تجميلية في إحدى الألعاب.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "لم يسبق لي قيادة سيارة في بلد أجنبي.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "لم يسبق لي أن قمت بغناء أغنية ديزني أثناء الاستحمام.",
    "Ich habe noch nie ein Elektroauto gefahren." to "لم يسبق لي قيادة سيارة كهربائية.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "لم يسبق لي أن التقطت صورة مع تميمة الحديقة.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "لم يسبق لي أن قمت بتسمية حيوان أليف على اسم إحدى شخصيات هوجورتس.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "لم يسبق لي أن أسقطت الفشار في صالة السينما ومازلت أتناوله.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "لم أستخدم أبدًا اقتباسًا من Master Yoda من Star Wars في حياتي اليومية.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "لم يسبق لي أن اشتريت تذكارًا باهظ الثمن في مدينة الملاهي.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "لم يسبق لي أن قدمت توصية لفيلم وجده الشخص الآخر سيئًا.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "لم يسبق لي أن شاهدت حفل توزيع جوائز الأوسكار مباشرة في منتصف الليل.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "لم أقم بإلغاء أي مسلسل أبدًا لأن الموسم الماضي كان سيئًا للغاية.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "لم يسبق لي أن شاهدت موسمًا كاملاً من المسلسل في يوم واحد.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "لم يسبق لي أن هزمت زعيمًا من المحاولة الأولى وشعرت وكأنني إله.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "لم أجد أبدًا شريرًا أفضل من البطل.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "لم أتعرف مطلقًا على شخصية Toy Story في ألعابي الخاصة.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "لم أقم بصنع شخصية في لعبة تقمص الأدوار مثلي تمامًا.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "لم يسبق لي أن أكلت التشورو في أي متنزه.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "لم يسبق لي أن شاهدت فيلمًا من أفلام ديزني ثلاث مرات متتالية.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "لم أسمع قط أغنية ديزني جذابة لمدة أسبوع كامل.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "لم يسبق لي أن شاهدت فيلمًا لمجرد ممثل معين.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "لم أستمع أبدًا إلى الموسيقى التصويرية لفيلم متكرر لساعات.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "لم أكشف أبدًا عن أي حرق للفيلم وندمت عليه على الفور.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "لم أجد أبدًا صديقًا يتحدث لغة أصلية أخرى.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "لم يكن لدي أي صديق انتقل إلى بلد آخر.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "لم يسبق لي أن شاركت في ماراثون فيلم هاري بوتر في عيد الميلاد.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "لم يسبق لي أن شاهدت فيلم Marvel حتى النهاية فقط بسبب مشهد ما بعد الائتمان.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "لم أتعمد مطلقًا إزعاج شخصية غير لاعب (NPC).",
    "Ich habe noch nie einen Nachtzug genommen." to "لم أستقل قطارًا ليليًا من قبل.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "لم أقم مطلقًا بإجراء اختبار عبر الإنترنت لاكتشاف منزلي في هوجورتس.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "لم أحذف مطلقًا منشورًا على وسائل التواصل الاجتماعي لأنه لم يحصل على عدد كافٍ من الإعجابات.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "لم يسبق لي أن وصفت يومًا في المتنزه بأنه أفضل يوم في السنة.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "لم يسبق لي أن زرت متنزهًا ترفيهيًا وبقيت هناك من الصباح حتى الليل.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "لم أترك مطلقًا رحلة Transformers أو Marvel مفتونة تمامًا.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "لم يسبق لي أن تركت اللعبة بغضب.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "لم أقرأ مطلقًا أيًا من مجلدات هاري بوتر الكبيرة.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "لم أهتم أبدًا بشخصيتي المفضلة في المسلسل.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "لم أحلم أبدًا بلعب لعبة كويدتش.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "لم يسبق لي أن بحثت سرًا عبر Google عن كيفية حل مستوى صعب.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "لم أتمنى سرًا أبدًا أن يتمكن حيواني الأليف من التحدث كما هو الحال في ديزني.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "لم أقم مطلقًا بإزالة قائد البلياردو في لعبة Sims.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "لم أفقد صوابي أبدًا في رحلة محاكاة ثلاثية الأبعاد.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "لم ألعب مطلقًا في فريق رياضي جامعي.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "لم أنتظر أبدًا في الطابور لأكثر من ساعتين للحصول على جاذبية واحدة.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "لم يسبق لي أن قمت بتبليل أشيائي الثمينة أثناء رحلة مائية.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "لم أتجادل أبدًا مع صديق حول أي منزل هو الأفضل.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "لم أتظاهر أبدًا بأن لدي قوى سحرية مثل إلسا.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "لم يسبق لي أن ضحكت بشدة لدرجة أنني فاتني مشهد مهم في الفيلم.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "لم أشعر أبدًا بكمية كبيرة من الأدرينالين لدرجة أنني أردت الركوب مرة أخرى على الفور.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "لم أحاول أبدًا الغناء مع حيوانات مثل بياض الثلج.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "لم أحلم أبدًا برحلة إلى ديزني لاند.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "لم أحلم أبدًا بركوب رحلة Jurassic Park المائية.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "لم يسبق لي أن صرخت بصوت عالٍ عند الخوف من القفز في إحدى الألعاب.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "لم أبكي أبدًا بسبب خاتمة برنامج تلفزيوني.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "لم أقم أبدًا بإلغاء موعد للبقاء في المنزل.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "لم يسبق لي أن قمت بإعادة صياغة الرسالة 10 مرات.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "لم يسبق لي أن نظرت سرًا إلى الهاتف الخلوي لشريكي.",
    "Ich habe noch nie!" to "لم أفعل ذلك أبدًا!",
    "Ich habe!" to "لدي!",
    "Ich lache viel mit meinem Partner." to "أضحك كثيرًا مع شريكي.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "أحب التعرف على هوايات واهتمامات شريكي.",
    "Ich liebe es" to "أنا أحب ذلك",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "أحب مشاهدة الأفلام مع شريكي والتي لم يشاهدها أي منا من قبل.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "أحب مشاركة الموسيقى المفضلة لدي مع شريكي.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "لم أضطر مطلقًا إلى الركض للحاق برحلة متصلة.",
    "Ich plane gerne Dates mit meinem Partner." to "أحب التخطيط للمواعيد مع شريكي.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "أعطي الأولوية لقضاء الوقت مع شريكي حتى عندما أكون مشغولاً.",
    "Ich schreibe meinem Partner jeden Tag." to "أرسل رسالة نصية إلى شريكي كل يوم.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "أحب مشاركة الميمات والنكات مع شريكي.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "أحب أن أشارك كل تفاصيل يومي مع شريكي.",
    "Ich würde es nie tun" to "لن أفعل ذلك أبدًا",
    "Ich übe noch" to "مازلت أتدرب",
    "Ideen generieren" to "توليد الأفكار",
    "Im Haushalt helfen" to "مساعدة في جميع أنحاء المنزل",
    "In Chat einfügen" to "أضف إلى الدردشة",
    "In Stille nebeneinander" to "في صمت بجانب بعضهما البعض",
    "In den Bergen" to "في الجبال",
    "In eine Bar gehen" to "اذهب إلى الحانة",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "الذهاب إلى حانة الشاطئ لمشاهدة غروب الشمس",
    "In einem feinen Restaurant essen gehen" to "تناول الطعام بالخارج في مطعم فاخر",
    "In einen Coffeeshop gehen" to "اذهب إلى المقهى",
    "In einer Beziehung sollte man alles voneinander wissen." to "في العلاقة يجب أن تعرفوا كل شيء عن بعضكم البعض.",
    "Infinity-Pool" to "حمام سباحة لا متناهي",
    "Innenpool" to "حمام سباحة داخلي",
    "Intelligenz" to "الذكاء",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "استمتع باللحظات الحميمة فقط عندما يبدأها شريكك",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "رمز الدعوة: HRM-8731 · كل شيء مفتوح",
    "Island" to "أيسلندا",
    "Ist okay für mich" to "لا بأس معي",
    "Ist schon perfekt" to "إنه مثالي",
    "Ja, Traditionen einbinden" to "نعم، قم بدمج التقاليد",
    "Ja, absolut" to "نعم بالتأكيد",
    "Ja, etwas zum Lesen und Aufbewahren" to "نعم، شيء يجب قراءته والاحتفاظ به",
    "Ja, genug" to "نعم يكفي",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "نعم، في مدينة أو منطقة جذب مثيرة",
    "Ja, in- und auswendig" to "نعم، من الداخل والخارج",
    "Ja, komplett überraschend" to "نعم، مفاجئ تمامًا",
    "Ja, perfekt" to "نعم، مثالي",
    "Ja, sie gehören zur Familie!" to "نعم، إنهم عائلة!",
    "Ja, sofort teilen" to "نعم، قم بالمشاركة على الفور",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "نعم، سوف نضمن أن يكون وقت العائلة هو الأولوية.",
    "Jacuzzi" to "جاكوزي",
    "Jahr zusammen 🎉" to "سنة معًا 🎉",
    "Jahre zusammen 🎉" to "سنوات معًا 🎉",
    "Jeder zahlt 50%" to "الجميع يدفع 50%",
    "Junge" to "صبي",
    "Kamin" to "المدفأة",
    "Karriere & Erfolg" to "المهنة والنجاح",
    "Kategorien" to "الفئات",
    "Katze" to "قطة",
    "Keine Musik" to "لا توجد موسيقى",
    "Keine Party nötig, privat halten" to "لا داعي لإقامة حفلة، ابقِ الأمر خاصًا",
    "Keine Privatsphäre" to "لا خصوصية",
    "Keine Treffer gefunden" to "لم يتم العثور على أي تطابقات",
    "Keiner" to "لا شيء",
    "Keiner von uns" to "لا أحد منا",
    "Kennst du die Essensvorlieben deines Partners?" to "هل تعرف تفضيلات الطعام لدى شريكك؟",
    "Kino" to "السينما",
    "Kirchlich" to "الكنسي",
    "Klassisch Solitär" to "سوليتير كلاسيكي",
    "Klassisch gebunden" to "مرتبط بشكل كلاسيكي",
    "Klein & zart" to "صغير وحساس",
    "Kleine Geschenke" to "هدايا صغيرة",
    "Kleine Runde" to "مجموعة صغيرة",
    "Kochen und Freunde einladen" to "الطبخ ودعوة الأصدقاء",
    "Kochkurs" to "فصل الطبخ",
    "Kommt auf den Tag an" to "يعتمد على اليوم",
    "Kommt darauf an" to "ذلك يعتمد",
    "Kommt drauf an" to "ذلك يعتمد",
    "Kommt mit" to "تعال معي",
    "Konzert" to "حفلة موسيقية",
    "Kräftige Farben" to "ألوان قوية",
    "Kräuterbeet" to "سرير عشبي",
    "Kultur & Sehenswürdigkeiten" to "الثقافة والمعالم السياحية",
    "Kuscheln" to "الحضن",
    "Kuss senden" to "أرسل قبلة",
    "Körperliche Annäherung" to "النهج الجسدي",
    "Körperliche Nähe" to "القرب الجسدي",
    "Küche" to "المطبخ",
    "Land" to "البلد",
    "Landhaus" to "منزل ريفي",
    "Landhausstil" to "نمط المنزل الريفي",
    "Lange wach bleiben" to "ابقَ مستيقظًا لوقت متأخر",
    "Lappland" to "لابلاند",
    "Lappland, Finnland" to "لابلاند، فنلندا",
    "Las Vegas" to "لاس فيغاس",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "دع شريكك يلهمك لتكون أفضل ما لديك",
    "Lehne ab" to "رفض",
    "Leichtigkeit" to "الخفة",
    "Leidenschaft" to "العاطفة",
    "Liebe im Gleichgewicht" to "الحب في الميزان",
    "Liebe sie, macht mehr Spaß" to "أحبهم، المزيد من المرح",
    "Lieber durchgeplant oder spontan?" to "هل تفضل أن يكون الأمر مخططًا له أم عفويًا؟",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "هل تفضل قضاء أمسية هادئة لشخصين أم مع الناس؟",
    "Lieber nicht" to "من الأفضل ألا تفعل ذلك",
    "Lieber vorher grob absprechen" to "من الأفضل مناقشة الأمور تقريبًا مسبقًا",
    "Lokal einkaufen" to "تسوق محليًا",
    "London" to "لندن",
    "London, England" to "لندن، إنجلترا",
    "Lügen" to "الأكاذيب",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "هل تفضل العرض العام أم الخاص؟",
    "Malediven" to "جزر المالديف",
    "Man sollte nie streitend einschlafen." to "يجب ألا تغفو أبدًا أثناء الجدال.",
    "Mango Sorbet" to "شربات المانجو",
    "Markant & breit" to "ملفت للنظر وواسع",
    "Marken & Alltag" to "العلامات التجارية والحياة اليومية",
    "McDonald’s" to "ماكدونالدز",
    "Mediterraner Innenhof" to "فناء البحر الأبيض المتوسط",
    "Mehr Unterstützung" to "المزيد من الدعم",
    "Mehr gemeinsame Zeit" to "المزيد من الوقت معًا",
    "Mehr zuhören" to "استمع أكثر",
    "Mehrgenerationenhaus" to "منزل متعدد الأجيال",
    "Mein Arbeitsplatz" to "مكان عملي",
    "Mein Partner" to "شريكي",
    "Mich überraschen" to "فاجأني",
    "Minimalistisches Interieur" to "تصميم داخلي بسيط",
    "Missverständnisse" to "سوء الفهم",
    "Mit Familie und engen Freunden" to "مع العائلة والأصدقاء المقربين",
    "Mit Kompromissen" to "مع التنازلات",
    "Mitgefühl" to "الرحمة",
    "Mittelweg mit besonderen Details" to "حل وسط بتفاصيل خاصة",
    "Modern geometrisch" to "هندسية حديثة",
    "Moderne Grillstation" to "محطة شواء حديثة",
    "Moderner Name" to "الاسم الحديث",
    "Moderner Solitär" to "سوليتير حديث",
    "Moissanit" to "مويسانيتي",
    "Moment festhalten" to "التقط اللحظة",
    "Momente" to "لحظات",
    "Monaco" to "موناكو",
    "Moralische Werte" to "القيم الأخلاقية",
    "Museum" to "متحف",
    "Musik" to "الموسيقى",
    "Mut" to "الشجاعة",
    "Mädchen" to "بنات",
    "Möbelhaus" to "محل أثاث",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "هل أنت متأكد أنك تريد مغادرة الاختبار؟ يظل تقدمك السابق محفوظًا.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "هل ترغب في تضمين الحيوانات الأليفة في التطبيق؟",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "هل تريد مشاركة اللحظة فورًا على وسائل التواصل الاجتماعي؟",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "قد نحتاج إلى توفير المال",
    "Müssen es planen" to "بحاجة إلى التخطيط لذلك",
    "Müssen sparen" to "بحاجة إلى الحفظ",
    "Nachricht an" to "الرسالة",
    "Name Partnerin" to "اسم الشريك",
    "Namen und Startdatum eurer Beziehung." to "أسماء وتاريخ بدء علاقتك.",
    "Natursteinfassade" to "واجهة من الحجر الطبيعي",
    "Naturteich" to "بركة طبيعية",
    "Nein, einfach halten" to "لا، فقط احتفظ به",
    "Nein, erstmal privat halten" to "لا، احتفظ بالأمر خاصًا في الوقت الحالي",
    "Nein, lieber vor Ort" to "لا، أفضل في الموقع",
    "Nein, modern halten" to "لا، اجعله عصريًا",
    "Nein, nur wir" to "لا، نحن فقط",
    "Nein, zu ablenkend" to "لا، تشتيت الانتباه للغاية",
    "Netflix" to "نيتفليكس",
    "Neubau mit Smart Home" to "مبنى جديد به منزل ذكي",
    "Neubau mit Technik" to "مبنى جديد مزود بالتكنولوجيا",
    "Neue Liebe, neue Erfahrungen" to "حب جديد، تجارب جديدة",
    "Neues Hobby" to "هواية جديدة",
    "Neues Spiel" to "لعبة جديدة",
    "Neugier" to "الفضول",
    "New York" to "نيويورك",
    "New York, USA" to "نيويورك، الولايات المتحدة الأمريكية",
    "Nicht mein Fall" to "ليس كوب الشاي الخاص بي",
    "Nicht nötig, lieber klassisch bleiben" to "ليس ضروريًا، فمن الأفضل أن تظل كلاسيكيًا",
    "Nichts — es passt so" to "لا شيء - إنه مناسب",
    "Nie wieder Burger" to "لا تتناول البرغر مرة أخرى",
    "Nie wieder Pizza" to "لا بيتزا مرة أخرى",
    "Niemand" to "لا أحد",
    "Niemand ohne Plan" to "لا أحد بدون خطة",
    "Nike" to "نايك",
    "Nizza" to "جميل",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "ليست هناك لحظات بعد.\nالتقط تجربتك الأولى 💞",
    "Nur bei wichtigen Themen" to "فقط للموضوعات المهمة",
    "Nur wir beide" to "نحن الاثنان فقط",
    "Nähe & Intimität" to "القرب والحميمية",
    "Obstgarten" to "بستان",
    "Oder" to "أو",
    "Offene Küche" to "مطبخ مفتوح",
    "Offene Wohnküche" to "مطبخ مفتوح/غرفة معيشة",
    "Ohne Stein" to "بدون حجر",
    "Open End" to "نهاية مفتوحة",
    "Outdoor-Küche" to "مطبخ خارجي",
    "Outdoor-Sofa" to "أريكة خارجية",
    "Outdoor-Whirlpool" to "دوامة خارجية",
    "Ovaler Diamant" to "الماسة البيضاوية",
    "Paar" to "زوج",
    "Paar-Statistiken" to "إحصائيات الزوجين",
    "Paris" to "باريس",
    "Paris, Frankreich" to "باريس، فرنسا",
    "Partner" to "شريك",
    "Partner-Simulator" to "محاكي الشريك",
    "Partnerin" to "شريك",
    "Party Edition" to "إصدار الحفلة",
    "Party Edition II" to "إصدار الحفلة II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "هل يتناسب الحيوان مع حياتنا اليومية؟",
    "Pasta" to "المعكرونة",
    "Pastell" to "باستيل",
    "Penthouse mit Ausblick" to "بنتهاوس بإطلالة",
    "Pepsi" to "بيبسي",
    "Pergola mit Lounge" to "برجولة مع صالة",
    "Pfingstrosen" to "الفاوانيا",
    "Pinguin" to "البطريق",
    "Pistazie" to "الفستق",
    "Pizza" to "بيتزا",
    "Pizzaofen" to "فرن البيتزا",
    "Platin" to "بلاتينيوم",
    "PlayStation" to "بلاي ستيشن",
    "Pool" to "حمام السباحة",
    "Pop" to "موسيقى البوب",
    "Prasselnder Kamin" to "مدفأة هادرة",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "الأميرات والقراصنة وغبار الجنيات: اختبار ديزني",
    "Privater Innenhof" to "فناء خاص",
    "Profil" to "الملف الشخصي",
    "Profil bearbeiten" to "تحرير الملف الشخصي",
    "Prozentual nach Einkommen" to "النسبة المئوية على أساس الدخل",
    "Quiz verlassen" to "قم بإنهاء الاختبار",
    "Quiz verlassen?" to "هل تريد مغادرة الاختبار؟",
    "Rausgehen in die Natur" to "اخرج إلى الطبيعة",
    "Reden vor ..." to "التحدث إلى...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "قم بجدولة مواعيد أو أوقات منتظمة معًا",
    "Reisen" to "السفر",
    "Reiseziele" to "وجهات السفر",
    "Respektlosigkeit" to "عدم الاحترام",
    "Restaurant" to "مطعم",
    "RnB / Soul" to "آر إن بي / سول",
    "Rock" to "صخرة",
    "Rom" to "روما",
    "Rom, Italien" to "روما، إيطاليا",
    "Romantik" to "الرومانسية",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "الإيماءات الرومانسية مثل الرسائل أو الملاحظات أو الهدايا تجعلني سعيدًا.",
    "Romantische Stimmung" to "مزاج رومانسي",
    "Roségold" to "ذهب وردي",
    "Ruhig zu zweit" to "هادئ لشخصين",
    "Runder Diamant" to "ماسة مستديرة",
    "Salted Caramel" to "كراميل مملح",
    "Sammle Ideen..." to "اجمع الأفكار...",
    "Santorini" to "سانتوريني",
    "Santorini, Griechenland" to "سانتوريني، اليونان",
    "Saphir" to "ياقوت",
    "Saunahaus" to "منزل الساونا",
    "Schickes Restaurant oder Hotel" to "مطعم أو فندق أنيق",
    "Schlafzimmer" to "غرفة النوم",
    "Schließen" to "إغلاق",
    "Schmal & zart" to "نحيف ورقيق",
    "Schnappschüsse aus unserer Liebesgeschichte" to "لقطات من قصة حبنا",
    "Schokolade" to "الشوكولاتة",
    "Schreib frei, was dir wirklich dazu einfällt." to "اكتب بحرية ما يتبادر إلى ذهنك حقًا.",
    "Schreibe deine eigene Antwort" to "اكتب إجابتك الخاصة",
    "Sehr gerne" to "مرحبًا بكم",
    "Sehr leicht" to "خفيف جدًا",
    "Sehr wichtig — Fotos und Video" to "مهم جدًا — الصور والفيديو",
    "Sehr wichtig, es sollte persönlich sein" to "مهم جدًا، يجب أن يكون شخصيًا",
    "Selbst kochen" to "اطبخ بنفسك",
    "Senden" to "أرسل",
    "Separate Küche" to "مطبخ منفصل",
    "Serie schauen" to "شاهد المسلسل",
    "Serienmarathon auf dem Sofa" to "سلسلة ماراثون على الأريكة",
    "Sex & Liebe" to "الجنس والحب",
    "Seychellen" to "سيشيل",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "هل نحن قادرون على تغطية جميع التكاليف لطفل واحد/عدة أطفال؟ 💰",
    "Soll der Antrag eine Überraschung sein?" to "هل يجب أن يكون الاقتراح مفاجأة؟",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "هل يجب أن يحتوي التطبيق على عناصر ثقافية أو تقليدية؟",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "هل يجب أن يحتوي التطبيق على عناصر ثقافية أو تقليدية؟",
    "Sommerhochzeit" to "حفل زفاف في الصيف",
    "Sonnige Dachterrasse" to "تراس مشمس على السطح",
    "Sowohl als auch" to "كلاهما و",
    "Spazieren" to "قم بالتمشية",
    "Spaß & Abenteuer" to "المرح والمغامرة",
    "Speichern" to "يحفظ",
    "Spiel bearbeiten" to "تحرير اللعبة",
    "Spielbereich für Kinder" to "منطقة لعب للأطفال",
    "Spiele" to "ألعاب",
    "Spiele spielen und Spaß haben" to "العب الألعاب واستمتع",
    "Spontan" to "تلقائي",
    "Sportplatz" to "المجال الرياضي",
    "Spotify" to "سبوتيفي",
    "Sprache" to "لغة",
    "Stadt" to "المدينة",
    "Stadt oder Land — was ist uns wichtiger?" to "المدينة أم البلد - ما هو الأهم بالنسبة لنا؟",
    "Stadtvilla" to "فيلا المدينة",
    "Standesamt & Party" to "مكتب التسجيل والحفلة",
    "Statement-Ring" to "خاتم البيان",
    "Stilvolles Outdoor-Sofa" to "أريكة خارجية أنيقة",
    "Stimme voll zu" to "أتفق معك تمامًا",
    "Stimmt" to "صحيح",
    "Stimmt nicht" to "غير صحيح",
    "Stimmt, noch nie" to "صحيح، أبدًا",
    "Stracciatella" to "ستراكياتيلا",
    "Strandtag" to "يوم الشاطئ",
    "Streit über Haushalt" to "نزاع حول الأسرة",
    "Studio Ghibli" to "ستوديو جيبلي",
    "Ständig" to "باستمرار",
    "Suche schließen" to "إغلاق البحث",
    "Suche zurücksetzen" to "إعادة ضبط البحث",
    "Suche öffnen" to "فتح البحث",
    "Suchergebnisse" to "نتائج البحث",
    "Sushi" to "سوشي",
    "Süß" to "حلو",
    "Tage zusammen 💞" to "أيام معًا",
    "Tauche ins Unterbewusstsein" to "انغمس في العقل الباطن",
    "Teile alle deine Hobbys mit deinem Partner" to "شارك كل هواياتك مع شريك حياتك",
    "Teils teils" to "جزئيًا جزئيًا",
    "Testen" to "اختبار",
    "Themen" to "المواضيع",
    "Tiefe Gespräche" to "محادثات عميقة",
    "Tiefgründige Gespräche führen" to "قم بإجراء محادثات عميقة",
    "Tierpension" to "دار رعاية الحيوانات",
    "Tiny House" to "منزل صغير",
    "Tippen zum Auswählen & Scrollen" to "اضغط للتحديد والتمرير",
    "Tippen zum Zuklappen" to "اضغط للتصغير",
    "Titel" to "العنوان",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "العنوان، الفئة، الموضوع، العلامات، الأسئلة...",
    "Tokyo, Japan" to "طوكيو، اليابان",
    "Traditioneller Name" to "الاسم التقليدي",
    "Traumhaus Außenbereich" to "منطقة خارجية لبيت الأحلام",
    "Traumhochzeit" to "حلم الزفاف",
    "Treffer" to "ضرب",
    "Tägliche Aktivität" to "النشاط اليومي",
    "Umformulieren" to "إعادة الصياغة",
    "Unbeantwortet" to "لم تتم الإجابة عليه",
    "Unbeliebte Meinungen" to "آراء لا تحظى بشعبية",
    "Universal Studios Genie oder Neuling?" to "يونيفرسال ستوديوز عبقري أم مبتدئ؟",
    "Uns auseinanderzuleben" to "للنمو بعيدًا",
    "Unser Intimleben" to "حياتنا الحميمة",
    "Unser Traumhaus" to "منزل أحلامنا",
    "Unser erstes Treffen" to "اجتماعنا الأول",
    "Unsere Gesichter" to "وجوهنا",
    "Unsere eigenen Träume" to "أحلامنا الخاصة",
    "Unsere nächste Reise" to "رحلتنا القادمة",
    "Unter 1000" to "أقل من 1000",
    "Unter 1000 im Monat" to "أقل من 1000 شهريًا",
    "Unter 50€/Monat" to "أقل من 50 يورو/الشهر",
    "Unter Leuten" to "بين الناس",
    "Untreue" to "الخيانة الزوجية",
    "Urlaub" to "إجازة",
    "Vanille" to "فانيليا",
    "Venedig" to "البندقية",
    "Venedig, Italien" to "البندقية، إيطاليا",
    "Verbinde dich mit" to "تواصل مع",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "اتصل بـ \${profile.partnerName} لترى الإجابة",
    "Verbindung" to "اتصال",
    "Verbringe die Feiertage mit deiner Familie" to "اقضي العطلة مع عائلتك",
    "Verlobungsringe" to "خواتم الخطوبة",
    "Vertrautheit" to "الألفة",
    "Viel getrennt" to "الكثير من الانفصال",
    "Vielleicht ein oder zwei" to "ربما واحد أو اثنين",
    "Vielleicht, aber mündlich reicht" to "ربما، ولكن لفظيًا يكفي",
    "Vielleicht, wenn es machbar ist" to "ربما، إذا كان ذلك ممكنًا",
    "Vielleicht, wenn es passt" to "ربما، إذا كان مناسبًا",
    "Vintage Art déco" to "آرت ديكو عتيق",
    "Vintage verspielt" to "مرح عتيق",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "تعريفك بهوايات جديدة من خلال شريكك",
    "Vor dem Kauf eines Hauses besprechen" to "ناقش الأمر قبل شراء منزل",
    "Vor der Anschaffung eines Haustiers besprechen" to "ناقش الأمر قبل شراء حيوان أليف",
    "Vor der gemeinsamen Reise besprechen" to "ناقش الأمر قبل السفر معًا",
    "Vor nichts" to "لا شيء",
    "Vorort" to "الضاحية",
    "Walnuss" to "الجوز",
    "Wandern" to "التنزه سيرًا على الأقدام",
    "Wann fühlst du dich mir am nächsten?" to "متى تشعر بأنك قريب مني؟",
    "Wann fühlst du dich mir körperlich am nächsten?" to "متى تشعر بأنك أقرب إلي جسديًا؟",
    "Was bedeutet Vertrauen für dich konkret?" to "ماذا تعني لك الثقة على وجه التحديد؟",
    "Was entspannt dich mehr?" to "ما الذي يريحك أكثر؟",
    "Was fehlt dir über die Distanz am meisten?" to "ما هو أكثر ما تفتقده في المسافة؟",
    "Was gefällt dir an deinem Zuhause am besten?" to "ما هو أكثر شيء يعجبك في منزلك؟",
    "Was hast du von deinem Partner gelernt?" to "ماذا تعلمت من شريك حياتك؟",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "ما رأيك في مشاهدة المحتوى المثير معًا؟",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "ما رأيك في الدعائم (مثل اللافتات والبالونات وما إلى ذلك)؟",
    "Was ist das Wichtigste beim Antrag?" to "ما هو أهم شيء عند التقديم؟",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "ما هو أهم شيء تبحث عنه في اللقاء الجنسي؟",
    "Was ist dein Lieblingsfoto von uns? 📸" to "ما هي صورتك المفضلة لنا؟ 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "ما هو أكبر مخاوفك بشأن العيش معًا؟",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "ما هو الطعام الذي تحبه لكن شريكك لا يستطيع فهمه؟",
    "Was ist für dich ein absoluter Dealbreaker?" to "ما هو الحل الأمثل بالنسبة لك؟",
    "Was ist für jeden von uns das absolute Highlight?" to "ما هو أبرز ما يميز كل واحد منا؟",
    "Was ist passiert?" to "ماذا حدث؟",
    "Was macht einen Moment für dich romantisch?" to "ما الذي يجعل اللحظة رومانسية بالنسبة لك؟",
    "Was magst du an deinem Partner am liebsten?" to "ما هو أكثر شيء يعجبك في شريك حياتك؟",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "ما الذي تفضله أكثر: الاستيقاظ مبكرًا أم السهر لوقت متأخر؟",
    "Was magst du lieber?" to "أيهما تفضل أكثر؟",
    "Was möchtest du eigentlich sagen?" to "ماذا تريد أن تقول بالفعل؟",
    "Was möchtest du, dass dein Partner öfter tut?" to "ما الذي تريد أن يفعله شريكك كثيرًا؟",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "ماذا يحدث للحيوان عندما نسافر؟",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "ماذا سيحدث لطفلنا عندما يكبر؟",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "ما الذي يجب ألا نغفل عنه أبدًا كآباء؟",
    "Was war dein schönster Moment mit mir bisher?" to "ما هي أفضل لحظة قضيتها معي حتى الآن؟",
    "Was wir gegessen haben" to "ماذا أكلنا",
    "Was wollt ihr nie vergessen?" to "ما الذي لا تريد أن تنساه أبدًا؟",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "ما الذي قد يكون أسوأ بالنسبة لك: عدم تناول البيتزا مرة أخرى أو عدم تناول البرجر مرة أخرى؟",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "ما هو أكثر شيء تحب أن تفعله في يومك معًا؟",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "ما الذي كنت ستغيره على الفور إذا لم يكن المال مشكلة؟",
    "Weiter" to "التالي",
    "Weiter spielen" to "استمر في اللعب",
    "Weiß ich noch nicht" to "لا أعرف بعد",
    "Weiße Rosen" to "الورود البيضاء",
    "Weißgold" to "الذهب الأبيض",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "ما هي الصفة التي يجب أن يحصل عليها طفلنا منا بالتأكيد؟",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "ما هي البيئة التي تريدها لمقترحك؟",
    "Welcher Raum sagt am meisten über dich aus?" to "ما هي الغرفة التي تعبر أكثر عنك؟",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "ما هي الميزانية التي نخطط لها للطعام والطبيب البيطري؟",
    "Welches Lied macht dich an? 🥵" to "ما هي الأغنية التي تثيرك؟ 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "ما هي الصورة المشتركة المفضلة لديك؟",
    "Wellnessbad" to "حمام العافية",
    "Wenn es schwierig ist" to "عندما تكون الأمور صعبة",
    "Wenn ich müde bin" to "عندما أكون متعبًا",
    "Wenn wir uns lange umarmen" to "عندما نتعانق لفترة طويلة",
    "Wenn wir zusammen lachen" to "عندما نضحك معًا",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "من الذي يقرر بسرعة أكبر ما الذي سيطلبه؟",
    "Wer findet die besten Restaurants?" to "من يجد أفضل المطاعم؟",
    "Wer gibt mehr Herzlichkeit?" to "من الذي يعطي المزيد من الدفء؟",
    "Wer hat den besseren Musikgeschmack?" to "من لديه ذوق أفضل في الموسيقى؟",
    "Wer hängt mehr an seinen Eltern?" to "من هو أكثر تعلقًا بوالديه؟",
    "Wer ist besser organisiert?" to "من هو الأفضل تنظيمًا؟",
    "Wer ist der Beste bei der Filmauswahl?" to "من هو الأفضل في اختيار الأفلام؟",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "من هو الأفضل في التخطيط للمواعيد الرومانسية؟",
    "Wer ist der beste Tänzer?" to "من هي أفضل راقصة؟",
    "Wer ist romantischer?" to "من هو الأكثر رومانسية؟",
    "Wer kocht besser?" to "من يطبخ بشكل أفضل؟",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "من يتولى التجديد والصيانة؟",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "من يلاحظ بشكل أسرع عندما يكون الشخص الآخر ليس على ما يرام؟",
    "Wer sucht am Ende wirklich den Film aus?" to "من الذي اختار الفيلم حقًا في النهاية؟",
    "Wer vergisst eher einen Jahrestag?" to "من هو الأكثر عرضة لنسيان الذكرى السنوية؟",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "من من المرجح أن ينسى اسمه في صباح اليوم التالي؟",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "من من المرجح أن يجد مقطع فيديو في اليوم التالي لا يعرف عنه شيئًا؟",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "من يفضل قضاء الليل على أريكة شخص غريب؟",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "من من المرجح أن ينام في إحدى الحفلات ويستيقظ مع شاربي على وجهه؟",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "من الذي من المرجح أن ينزلق على حلبة الرقص لكنه يجعلها تبدو كحركة رائعة؟",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "من المرجح أن يتحكم في قائمة تشغيل Spotify في حفلة منزلية؟",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "من المرجح أن يطلب البيتزا للجميع في الحفلة ويأكلها بنفسه؟",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "من هو الأكثر عرضة للنوم أولاً في الحفلة؟",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "من من المرجح أن يبدأ فجأة بالتنظيف في إحدى الحفلات؟",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "من الذي من المرجح أن يدعي أنه رزين تمامًا عندما يكون العكس هو الصحيح؟",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "من هو الأكثر احتمالا للاستسلام أولا في الجدال؟",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "من هو الأكثر عرضة للغش في لعبة الشرب؟",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "من سيكون أكثر عرضة لمداهمة البوفيه وأخذ الطعام سرًا إلى المنزل؟",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "من من المرجح أن ينشر الصورة الأكثر إحراجًا للمساء في قصته؟",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "من من شأنه أن يزعج DJ لطلب أغنيته المفضلة؟",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "من من المرجح أن يغني كلمات أغنية خارج نطاق المفاتيح، ولكن عن قناعة؟",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "من المرجح أن يطلب أغلى مشروب في القائمة ويندم عليه؟",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "من من المرجح أن يدعو الجيران إذا اشتكوا من الضوضاء؟",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "من سيأخذ ألعاب الحفلات (مثل Beer Pong) على محمل الجد؟",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "من الذي من المرجح أن يصادق الحراس ليحصل على وصول VIP؟",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "من من المرجح أن يبدأ معركة كاريوكي عفوية؟",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "من هو الأكثر احتمالا لفتح الزجاجة دون استخدام فتاحة الزجاجات؟",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "من هو الأكثر احتمالية لإلقاء خطاب على الرغم من عدم سؤال أحد عنه؟",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "من من المرجح أن يقضي ساعة في الحمام لالتقاط صور سيلفي؟",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "من من المرجح أن يقوم بأداء رقص محرج ويحتفل به؟",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "من من المرجح أن يتصل بشريكه السابق بعد انتهاء الحفلة؟",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "من هو الأكثر عرضة للإساءة لضيف غريب عن طريق الخطأ؟",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "من من المرجح أن يغادر الحفلة سرًا دون أن يقول وداعًا؟",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "من يفضل اللعب مع حيوان المضيف الأليف بدلاً من التحدث مع الضيوف؟",
    "Wer würde eher spontan eine Reise buchen?" to "من الذي من المرجح أن يحجز رحلة تلقائيًا؟",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "من الذي من المرجح أن يجري محادثات عميقة في المطبخ لساعات؟",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "من هو الأكثر عرضة لشرب مشروب شخص آخر عن طريق الخطأ؟",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "من هو الأكثر عرضة لضرب مزهرية باهظة الثمن أو شيء هش عن طريق الخطأ؟",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "من الذي من المرجح أن يحاول مزج كوكتيل معقد بنفسه ويفشل فشلاً ذريعًا؟",
    "Wer würde eher zu spät kommen?" to "من هو الأكثر احتمالا أن يتأخر؟",
    "Wer würde eher?" to "من يفضل؟",
    "Wer übernimmt die tägliche Versorgung?" to "من يتولى العناية اليومية؟",
    "Werde so akzeptiert, wie du bist" to "كن مقبولاً كما أنت",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "هل سيكون لدينا الوقت الكافي للطفل/الأطفال؟ ⏳",
    "Whirlpool" to "حوض استحمام ساخن",
    "White Chocolate" to "الشوكولاتة البيضاء",
    "Widgets" to "الأدوات",
    "Wie fühlst du dich am meisten geliebt?" to "ما هو شعورك بأنك محبوب؟",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "كيف نتعامل مع الدخول المختلفة؟",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "ما هي أفضل طريقة ليبدأ شريكك ممارسة الجنس معك؟",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "كيف يمكن لشريكك أن يكون شريكًا أفضل لك؟",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "ما المدة التي تريد الاحتفال بها مع الآخرين بعد الاقتراح؟",
    "Wie lange wollen wir dort mindestens bleiben?" to "إلى متى نريد البقاء هناك على الأقل؟",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "ما مدى سهولة التحدث عن الأمنيات بالنسبة لك؟",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "كيف تريد أن يبدو مستقبلنا؟",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "كيف يبدو يوم الأحد المثالي في المنزل؟",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "ما هو شعورك تجاه الكلام البذيء أثناء ممارسة الجنس؟",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "ما مقدار الفضل الذي يمكننا تحمله بشكل واقعي؟",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "كم من الوقت نريد أن نقضيه منفصلين؟",
    "Wie viel wollen wir insgesamt ausgeben?" to "ما هو المبلغ الإجمالي الذي نريد إنفاقه؟",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "كيف سنجد الوقت لعلاقتنا بمجرد ولادة الطفل؟",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "ما مدى أهمية التقاط اللحظة بالنسبة لك؟",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "ما مدى أهمية أن يعكس التطبيق هواياتك أو اهتماماتك بالنسبة لك؟",
    "Wie würdest du sie/ihn nennen?" to "ماذا ستسميه/ها؟",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "ما هي طريقتك المفضلة لإظهار المودة خارج نطاق الجنس؟",
    "Wildblumen" to "الزهور البرية",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "هل تريد فتاة أم ولد؟ 👶",
    "Wintergarten" to "حديقة الشتاء",
    "Winterhochzeit" to "زفاف الشتاء",
    "Wir bestellen einfach beides" to "نحن نطلب كليهما فقط",
    "Wir brauchen ewig" to "يأخذنا إلى الأبد",
    "Wir einigen uns nie" to "نحن لا نتفق أبدًا",
    "Wir entscheiden es gemeinsam" to "نحن نقرر معًا",
    "Wir treffen uns in der Mitte" to "نلتقي في المنتصف",
    "Wir wechseln uns ab" to "نحن نتناوب",
    "Wird stressig" to "يصبح مرهقًا",
    "Wobei lachst du am meisten?" to "ما هو أكثر شيء يجعلك تضحك؟",
    "Wofür sparen wir gemeinsam?" to "ما الذي ندخر من أجله معًا؟",
    "Wohnzimmer" to "غرفة المعيشة",
    "Woran erinnerst du dich am lebhaftesten?" to "ما هو أكثر ما تتذكره بوضوح؟",
    "Worauf freust du dich bei uns am meisten?" to "ما هو أكثر ما تتطلع إليه معنا؟",
    "Worte/Komplimente" to "كلمات/إطراءات",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "ما هو أكثر ما تخاف منه في علاقتنا؟",
    "Wünsche? z.B. günstig, draußen" to "الأمنيات؟ على سبيل المثال رخيصة، خارج",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "هل تفضل تقديم طلب الزواج في إجازة (تتضمن السفر)؟",
    "Xbox" to "اكس بوكس",
    "YouTube Music" to "يوتيوب ميوزك",
    "Zeichne für mich" to "ارسم لي",
    "Zeichne mich als Tier — welches wäre ich?" to "ارسمني كحيوان - أي حيوان سأكون؟",
    "Zeichne unser Gefühl zueinander als Symbol." to "ارسم مشاعرنا تجاه بعضنا البعض كرمز.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "ارسم منزل أحلامنا في سطر واحد. ما هو الشيء الأكثر لفتا للنظر؟",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "ارسم موعدنا الأول - ما الذي يجب أن يكون في الصورة بالتأكيد؟",
    "Zeichnen" to "ارسم",
    "Zeit füreinander" to "الوقت لبعضنا البعض",
    "Zeit, wenn das Baby schläft" to "الوقت الذي ينام فيه الطفل",
    "Zelten gehen" to "اذهب للتخييم",
    "Zitrone" to "ليمون",
    "Zu Hause, gemütlich und privat" to "في المنزل، مريح وخاص",
    "Zu einem Picknick gehen" to "الذهاب إلى نزهة",
    "Zu einem ausgefallenen Abendessen gehen" to "الذهاب إلى عشاء فاخر",
    "Zu zweit reisen" to "السفر كزوجين",
    "Zuhause & Alltag" to "المنزل والحياة اليومية",
    "Zuhören" to "استمع",
    "Zurück" to "العودة",
    "Zusammen seit" to "معًا منذ ذلك الحين",
    "Zusammen seit (TT.MM.JJJJ)" to "معًا منذ (DD.MM.YYYY)",
    "Zusammenziehen" to "العقد",
    "Zustimmen oder Ablehnen" to "أوافق أو لا أوافق",
    "Zwei Kreise, die sich überschneiden" to "دائرتان متداخلتان",
    "Zwei Stühle davor" to "أمامه كرسيان",
    "Zärtlich sein" to "كن لطيفًا",
    "Öfter als ich zugebe" to "مرات أكثر مما أعترف به",
    "Über 100€/Monat" to "أكثر من 100 يورو/الشهر",
    "Über 2000 im Monat" to "أكثر من 2000 شهريا",
    "Über mich selbst" to "عن نفسي",
    "Übernehmen" to "تطبيق",
    "Überraschend" to "مفاجئ",
    "Überraschung" to "مفاجأة",
    "Überspringen" to "تخطي",
    "Übertrieben und großartig" to "رائع ورائع",
    "✎ Tippe, um zu antworten" to "✎ اضغط للرد",
    "✨ GFK-Brücke" to "✨جسر GRP",
)

internal fun localizeArabicDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_ARABIC_CONTENT)
