package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_BURMESE_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "၁-၅ နှစ်",
    "1000 - 1500 im Monat" to "တစ်လလျှင် 1000 - 1500",
    "1000 bis 3000" to "၁၀၀၀ မှ ၃၀၀၀",
    "1500 - 2000 im Monat" to "တစ်လလျှင် 1500 - 2000",
    "3000 bis 5000" to "၃၀၀၀ မှ ၅၀၀၀",
    "5-10 Jahre" to "၅-၁၀ နှစ်",
    "50-100€/Monat" to "50-100€/လ",
    "Ab 100€" to "100€ မှ",
    "Ab 500€" to "500€ မှ",
    "Ab 50€" to "50€ မှ",
    "Ab und zu" to "ခဏခဏ",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "ဝယ်ယူမှုတစ်ခုမပြုလုပ်မီ ကျွန်ုပ်တို့မည်မျှသုံးစွဲရန် လိုအပ်သနည်း။",
    "Abbrechen" to "ပယ်ဖျက်ရန်",
    "Abenteuer" to "စွန့်စားခန်း",
    "Adidas" to "Adidas",
    "Aktivitäten" to "လှုပ်ရှားမှုများ",
    "Alle" to "အားလုံး",
    "Alle Pakete" to "ပက်ကေ့ဂျ်အားလုံး",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "မင်းရဲ့ အချစ်ဆုံးသူငယ်ချင်းကလွဲလို့ မင်းသူငယ်ချင်းအားလုံးကို ဆုံးရှုံးလိုက်ပါ။",
    "Alle intimen Momente selbst initiieren" to "ရင်းနှီးသော အခိုက်အတန့်အားလုံးကို သင်ကိုယ်တိုင် စတင်လိုက်ပါ။",
    "Alles davon" to "ဒါတွေအားလုံး",
    "Alles, was noch kommt" to "ဖြစ်လာမည့်အရာအားလုံး",
    "Alltagsroutine" to "နေ့စဉ်ပုံမှန်",
    "Alltägliche Berührungen" to "နေ့စဉ်ထိတွေ့မှုများ",
    "Altbau mit Charme" to "ကျက်သရေရှိသော ရှေးဟောင်းအဆောက်အအုံ",
    "Am Strand" to "ကမ်းခြေ",
    "Am liebsten alles zusammen" to "ဖြစ်နိုင်ရင် အရာအားလုံးကို အတူတူ",
    "Am selben Tag mit Freunden/Familie" to "ထိုနေ့တွင် သူငယ်ချင်းများ/မိသားစု",
    "Amazon" to "Amazon",
    "Amsterdam" to "အမ်စတာဒမ်",
    "Amsterdam, Niederlande" to "အမ်စတာဒမ်၊ နယ်သာလန်",
    "An das Gefühl" to "ဝေဒနာ",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "ပရိသတ်များစွာရှိသော အများသူငှာနေရာတစ်ခုတွင်",
    "An einen Geruch" to "အနံ့",
    "An einen Song" to "သီချင်းတစ်ပုဒ်အတွက်",
    "An etwas, das ich gesagt habe" to "ငါပြောခဲ့တာတစ်ခုရှိတယ်။",
    "Analyse starten" to "ခွဲခြမ်းစိတ်ဖြာမှု စတင်ပါ။",
    "Analysiere eure Muster..." to "သင့်ပုံစံများကို ခွဲခြမ်းစိတ်ဖြာပါ...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Gottman နှင့် GFK အရ သင့်အဖြေများနှင့် ချတ်များကို ပိုင်းခြားစိတ်ဖြာပါ။",
    "Ananas auf der Pizza schmeckt köstlich." to "ပီဇာပေါ်ရှိ နာနတ်သီးသည် အရသာရှိသည်။",
    "Android" to "Android",
    "Antwort mit einem Foto" to "ဓာတ်ပုံဖြင့် စာပြန်ပါ။",
    "Antwortähnlichkeit" to "တူညီသောအဖြေ",
    "App-Sprache auswählen" to "အက်ပ်ဘာသာစကားကို ရွေးပါ။",
    "Auf eine Bootsparty gehen" to "လှေပါတီကို သွားမယ်။",
    "Aufmerksamkeit" to "သတိ",
    "Aufräumen und Projekte angehen" to "ရှင်းလင်းပြီး ပရောဂျက်များကို ကိုင်တွယ်ဖြေရှင်းပါ။",
    "Aufwärmen" to "နွေး",
    "Aufwärmen: Einander kennenlernen" to "သွေးပူခြင်း- တစ်ယောက်နဲ့တစ်ယောက် သိခွင့်ရတယ်။",
    "Aus dem Urlaub" to "အားလပ်ရက်မှ",
    "Ausgefallener Name" to "ဖန်စီအမည်",
    "Ausschlafen und faulenzen" to "အိပ်ရေးဝဝ အိပ်ပါ။",
    "Ausschlafen und nichts tun" to "အိပ်ပြီး ဘာမှမလုပ်ပါနဲ့။",
    "Aussehen" to "အသွင်အပြင်",
    "Auto" to "အလိုအလျောက်",
    "Außenkamin" to "ပြင်ပမီးဖို",
    "BEANTWORTE" to "အဖြေ",
    "Bali" to "ဘာလီ",
    "Bali, Indonesien" to "ဘာလီ၊ အင်ဒိုနီးရှား",
    "Banane" to "ငှက်ပျောသီး",
    "Beantwortet" to "ဖြေသည်။",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "မေးခွန်းများကို တစ်ချိန်တည်းဖြေပါ — သင်နှစ်ယောက်လုံးပြီးသွားသည်အထိ အဖြေများကို မြင်နိုင်မည်မဟုတ်ပေ။",
    "Beantwortete Fragen" to "မေးခွန်းများကို ဖြေခဲ့သည်။",
    "Bearbeiten" to "တည်းဖြတ်ရန်",
    "Bei Insider-Witzen" to "အတွင်းပြက်လုံးများအတွက်",
    "Bei Memes" to "မီမီများ",
    "Bei einer spontanen Berührung" to "သူ့အလိုလို ထိတွေ့သောအခါ",
    "Beide" to "နှစ်ခုလုံး",
    "Beide gleich" to "နှစ်ခုလုံး အတူတူပါပဲ။",
    "Beide zusammen" to "နှစ်ယောက်စလုံး အတူတူ",
    "Beide, aber wir tun so als ob nicht" to "နှစ်ခုလုံး၊ ဒါပေမယ့် ငါတို့က ဟန်မဆောင်ဘူး။",
    "Beides" to "နှစ်ခုလုံး",
    "Beides wäre schlimm" to "နှစ်ခုလုံး မကောင်းဘူး။",
    "Beim Einschlafen nebeneinander" to "တစ်ယောက်နဲ့တစ်ယောက် အိပ်ပျော်သွားတယ်။",
    "Beim Reden" to "စကားပြောနေစဉ်",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "နာမည်ကြီး ခရီးသွားနေရာတွေက အမြဲတမ်း စိတ်ပျက်စရာပါ။",
    "Beschreibe unser Sexleben mit einem Emoji." to "ကျွန်ုပ်တို့၏ လိင်မှုဘဝကို အီမိုဂျီဖြင့် ဖော်ပြပါ။",
    "Besser kommunizieren" to "ပိုမိုကောင်းမွန်စွာ ပြောဆိုဆက်ဆံပါ။",
    "Bessere Lage" to "ပိုကောင်းတဲ့တည်နေရာ",
    "Bestellen" to "အော်ဒါ",
    "Besuchte Länder" to "နိုင်ငံများသို့ သွားရောက်ခဲ့သည်။",
    "Besuchte Städte" to "မြို့များကို လည်ပတ်ခဲ့သည်။",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "လွန်ကဲသော အဆိုပြုချက် သို့မဟုတ် သိမ်မွေ့သော အရာတစ်ခုကို သင်နှစ်သက်ပါသလား။",
    "Beziehung" to "ဆက်ဆံရေး",
    "Bibliothek" to "စာကြည့်တိုက်",
    "Bin manchmal unsicher" to "ကျွန်တော် တစ်ခါတလေ စိတ်မလုံခြုံဘူး။",
    "Bist du ein Videospiel-Guru?" to "သင်သည် ဗီဒီယိုဂိမ်းဆရာကြီးလား။",
    "Blumenwiese" to "ပန်းမြက်ခင်း",
    "Bunte Blumenwiese" to "ရောင်စုံပန်းပွင့် မြက်ခင်းပြင်",
    "Burger" to "ဘာဂါ",
    "Burger King" to "ဘာဂါဘုရင်",
    "Chat" to "ချတ်",
    "Coca-Cola" to "ကိုကာကိုလာ",
    "Cookie Dough" to "ကွတ်ကီးမုန့်စိမ်း",
    "Dachgarten mit Lounge" to "ဧည့်ခန်းနှင့် အမိုးဥယျာဉ်",
    "Dachterrasse" to "အိမ်ခေါင်မိုး",
    "Das Wetter an dem Tag" to "ထိုနေ့က ရာသီဥတု",
    "Das erste Selfie" to "ပထမဆုံး ဆယ်လ်ဖီ",
    "Das meiste weiß ich" to "ကျွန်တော် အများစု သိပါတယ်။",
    "Das oder das?" to "ဒါလား။",
    "Das tägliche Leben" to "နေ့စဉ်ဘဝ",
    "Dass Zusagen gehalten werden" to "ထိုကတိများကို ထိန်းသိမ်းထားသည်။",
    "Dass alles meinen Stil hat" to "အရာအားလုံးမှာ ငါ့စတိုင်ရှိတယ်။",
    "Dass ich alles erzählen kann" to "အဲဒါ ငါအကုန်ပြောပြနိုင်တယ်။",
    "Dass ich mich nicht sorgen muss" to "အဲဒါ ငါစိတ်ပူစရာ မလိုဘူး။",
    "Dass wir ungestört sind" to "ကျွန်ုပ်တို့သည် အနှောက်အယှက်မဖြစ်ပါ။",
    "Dein Name" to "မင်းနာမည်",
    "Deine Antwort..." to "မင်းရဲ့အဖြေ...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "သင့်အဖြေများကို သိမ်းဆည်းထားသည်။ ပါတနာသည် ပက်ကေ့ဂျ်ကို ပြီးသည်နှင့် တပြိုင်နက် အဖြေနှစ်ခုစလုံးကို အတူတကွ မြင်နိုင်မည်ဖြစ်သည်။",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "သင့်အဖြေများကို သိမ်းဆည်းထားသည်။ \${profile.partnerName} ပက်ကေ့ဂျ်ကို ပြီးသည်နှင့်၊ တုံ့ပြန်မှု နှစ်ခုလုံးကို တစ်ပြိုင်နက် မြင်ရပါမည်။",
    "Deine Beziehung abenteuerlich und spontan machen" to "သင့်ဆက်ဆံရေးကို စွန့်စားပြီး အလိုအလျောက်ဖြစ်စေပါ။",
    "Deine Beziehung stabil und sicher machen" to "သင့်ဆက်ဆံရေးကို တည်ငြိမ်ပြီး လုံခြုံအောင် ပြုလုပ်ပါ။",
    "Deine eigene Antwort" to "သင့်ကိုယ်ပိုင်အဖြေ",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "သင့်လက်တွဲဖော်နှင့် သင်၏အနက်ရှိုင်းဆုံးလျှို့ဝှက်ချက်များကို မျှဝေခြင်းက ပိုကောင်းပါတယ်။",
    "Deinen besten Freund verlieren" to "မင်းရဲ့ အချစ်ဆုံးသူငယ်ချင်းကို ဆုံးရှုံးလိုက်ရတာ။",
    "Denke an dich" to "သင့်ကိုယ်သင် စဉ်းစားကြည့်ပါ။",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "အတူတူရုပ်ရှင်ကို နှစ်ကြိမ်ကြည့်တာက အချိန်ဖြုန်းတယ်။",
    "Der Blick nach draußen" to "အပြင်ဘက်မြင်ကွင်း",
    "Der Garten" to "ဥယျာဉ်",
    "Der Ort" to "နေရာ",
    "Der Ring und die Geste" to "လက်စွပ်နှင့် အမူအရာ",
    "Der perfekte Heiratsantrag" to "ပြီးပြည့်စုံသော အိမ်ထောင်ရေး အဆိုပြုချက်",
    "Derjenige sein, der umarmt wird" to "ပွေ့ဖက်ခံရသူဖြစ်ပါစေ။",
    "Deutsch" to "ဂျာမန်",
    "Diamant" to "စိန်",
    "Diamanten im Band" to "တီးဝိုင်းထဲတွင် စိန်များ",
    "Die Distanz" to "အကွာအဝေး",
    "Die Feiertage mit der Familie deines Partners verbringen" to "အားလပ်ရက်များကို သင့်လက်တွဲဖော်၏ မိသားစုနှင့်အတူ ဖြတ်သန်းပါ။",
    "Die Gemütlichkeit und Ruhe" to "ချမ်းသာခြင်းနှင့် ငြိမ်သက်ခြင်း။",
    "Die Menschen, die darin wohnen" to "၎င်းတွင်နေထိုင်သောလူများ",
    "Die Umgebung und Atmosphäre" to "ပတ်ဝန်းကျင်နှင့် လေထု",
    "Die Worte und Emotionen" to "စကားလုံးများနှင့် ခံစားချက်များ",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "အဆုံးစွန်သော ဖျော်ဖြေရေးဉာဏ်စမ်း စိန်ခေါ်မှု",
    "Diejenige sein, die umarmt" to "ပွေ့ဖက်ထားသူဖြစ်ပါစေ။",
    "Direkt ansprechen" to "တိုက်ရိုက်လိပ်စာ",
    "Diskussion" to "ဆွေးနွေးခြင်း။",
    "Diskutiere vor dem Kinderkriegen" to "ကလေးမမွေးမီ ဆွေးနွေးပါ။",
    "Diskutiert eure Antworten" to "သင့်အဖြေများကို ဆွေးနွေးပါ။",
    "Disney" to "Disney",
    "Doch, schon mal" to "ဟုတ်ကဲ့၊ ဟုတ်ကဲ့",
    "Draußen mit der Natur als Kulisse" to "အပြင်ဘက်မှာ သဘာဝတရားနဲ့ နောက်ခံကားချပ်",
    "Drei-Stein-Ring" to "ကျောက်သုံးလက်စွပ်",
    "Du bist dran" to "မင်းအလှည့်ရောက်ပြီ။",
    "Du fehlst mir" to "ငါမင်းကိုလွမ်းတယ်။",
    "Dubai" to "ဒူဘိုင်း",
    "Dubai, VAE" to "ဒူဘိုင်း၊ UAE",
    "Dunkles Design" to "အမိုက်စား အပြင်အဆင်",
    "Durch Berührung" to "ထိခြင်းဖြင့်",
    "Durch Worte" to "စကားအားဖြင့်",
    "Durch Zeit zu zweit" to "အတူတူ အချိန်တွေကုန်တယ်။",
    "Durch kleine Gesten" to "သေးငယ်သော အမူအယာများဖြင့်",
    "Durchgeplant" to "ကောင်းမွန်စွာ စီစဉ်ထားပါသည်။",
    "ERGEBNISSE" to "ရလဒ်များ",
    "Egal, Hauptsache gesund" to "ဘာပဲဖြစ်ဖြစ် အဓိကကတော့ ကျန်းမာဖို့ပါပဲ။",
    "Ehepaar Leben" to "အိမ်ထောင်သည် စုံတွဲဘဝ",
    "Eher knapp" to "အနီးကပ်",
    "Eher nicht" to "သိပ်မများပါဘူး။",
    "Eher schwer" to "ခက်တယ်။",
    "Eher schwierig" to "ခက်တယ်။",
    "Eher zu" to "ပိုကြိုက်တယ်။",
    "Eifersucht ist ein Zeichen von Liebe." to "မနာလိုခြင်းသည် အချစ်၏ လက္ခဏာတစ်ခုဖြစ်သည်။",
    "Eigenes Gemüsebeet" to "ကိုယ်ပိုင် ဟင်းရွက်ဖာများ",
    "Ein Abenteuer in einer neuen Stadt" to "မြို့သစ်ရှိ စွန့်စားခန်း",
    "Ein Anker" to "ကျောက်ဆူးတစ်ခု",
    "Ein Balkon oder Garten" to "လသာဆောင် သို့မဟုတ် ပန်းခြံ",
    "Ein Filmabend" to "ရုပ်ရှင်ည",
    "Ein Harmony-Meilenstein eurer Liebe." to "သင့်ချစ်ခြင်းမေတ္တာ၏ ညီညွတ်သော မှတ်တိုင်တစ်ခု။",
    "Ein Herz" to "နှလုံးသား",
    "Ein Herz an der Tür" to "တံခါးဝက နှလုံးသား",
    "Ein Jahr lang eine Fernbeziehung führen" to "တစ်နှစ်တာ တာဝေးဆက်ဆံရေးရှိပါ။",
    "Ein Kindheitsessen" to "ငယ်စဉ်က အစားအသောက်",
    "Ein Live-Musik-Konzert besuchen" to "တိုက်ရိုက်ဂီတဖျော်ဖြေပွဲကို တက်ရောက်ပါ။",
    "Ein Museum besuchen" to "ပြတိုက်သို့ သွားပါ။",
    "Ein Spieleabend" to "ဂိမ်းည",
    "Ein Spieleabend mit Freunden" to "သူငယ်ချင်းများနှင့် ဂိမ်းည",
    "Ein Urlaubsfoto" to "အားလပ်ရက်ဓာတ်ပုံ",
    "Ein aktives Abenteuer" to "တက်ကြွသော စွန့်စားခန်း",
    "Ein entspannender Spa-Tag" to "အပန်းဖြေအနားယူနိုင်သော spa နေ့",
    "Ein ganz normaler Alltagstag" to "လုံးဝပုံမှန်နေ့စဉ်",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "မိုးကြိုးမုန်တိုင်း တိုက်ခတ်နေစဉ် အိမ်၌ သာယာသော ညနေခင်း",
    "Ein gemütliches Date drinnen" to "အိမ်ထဲတွင် ပျော်ရွှင်ဖွယ်နေ့စွဲ",
    "Ein lustiges Bild" to "ရယ်စရာပုံ",
    "Ein paar Handyfotos reichen" to "ဆဲလ်ဖုန်း ဓာတ်ပုံ အနည်းငယ် လုံလောက်ပါသည်။",
    "Ein paar Stunden" to "နာရီအနည်းငယ်",
    "Ein paar kulturelle Anklänge sind okay" to "ယဉ်ကျေးမှုဆိုင်ရာ ကိုးကားချက်အချို့ အဆင်ပြေပါသည်။",
    "Ein romantischer Abend" to "ရင်ခုန်စရာ ညနေခင်း",
    "Ein romantisches Abendessen bei Kerzenlicht" to "ရင်ခုန်စရာ ဖယောင်းတိုင်မီး ညစာ",
    "Ein romantisches Bild" to "ရင်ခုန်စရာပုံရိပ်",
    "Ein romantisches Picknick an einem schönen Ort" to "လှပသောနေရာရှိ ရင်ခုန်စရာ ပျော်ပွဲရွှင်ပွဲ",
    "Ein schwerer Moment, den wir geschafft haben" to "ကျွန်ုပ်တို့ စီမံခန့်ခွဲနိုင်သော ခက်ခဲသော အခိုက်အတန့်",
    "Ein tolles Date im Freien unter dem Mondlicht" to "လရောင်အောက်တွင် အပြင်ဘက်တွင် ကောင်းမွန်သော နေ့စွဲတစ်ခု",
    "Ein ungewöhnliches Gericht" to "ထူးထူးခြားခြား ဟင်းပွဲ",
    "Ein zufälliger Schnappschuss" to "ကျပန်းလျှပ်တစ်ပြက်ရိုက်ချက်",
    "Einander kennenlernen" to "တစ်ယောက်နဲ့တစ်ယောက် သိခွင့်ရတယ်။",
    "Eine Autoreise" to "လမ်းခရီး",
    "Eine Brücke" to "တံတား",
    "Eine Date-Nacht unter den Sternen" to "ကြယ်များအောက်မှ နေ့စွဲည",
    "Eine Million Dollar gewinnen" to "ဒေါ်လာတစ်သန်းအနိုင်ရ",
    "Eine Million Dollar verdienen" to "ဒေါ်လာတစ်သန်းလုပ်ပါ။",
    "Eine Nacht in einem Club" to "ကလပ်တွင် တစ်ည",
    "Eine Schokoladenverkostung" to "ချောကလက်အရသာ",
    "Eine Wanderung mit Panoramablick machen" to "မြင်ကွင်းကျယ် ရှုခင်းများနှင့်အတူ တောင်တက်ပါ။",
    "Eine Weinverkostung" to "ဝိုင်အရသာ",
    "Eine gemeinsame Reise" to "အတူခရီး",
    "Eine gemütliche Nacht zu Hause" to "အိမ်မှာ သာယာတဲ့ည",
    "Eine neue Sprache zu lernen ist einfach." to "ဘာသာစကားအသစ်တစ်ခုကို သင်ယူခြင်းသည် လွယ်ကူသည်။",
    "Einen Film anschauen" to "ရုပ်ရှင်ကြည့်",
    "Einen Monat lang überhaupt nicht miteinander reden" to "တစ်ယောက်နဲ့တစ်ယောက် စကားမပြောဖြစ်တာ တစ်လလောက်ရှိပြီ။",
    "Einen Tanzkurs besuchen" to "အကသင်တန်းတက်ပါ။",
    "Einen Vergnügungspark erkunden" to "အပန်းဖြေဥယျာဉ်ကို စူးစမ်းပါ။",
    "Einen Wellness-Tag" to "ကျန်းမာစေသည်။",
    "Einen sehr emotionalen Partner haben" to "အလွန်စိတ်လှုပ်ရှားစရာကောင်းသော လက်တွဲဖော်တစ်ဦးရှိခြင်း။",
    "Einen sehr logischen Partner haben" to "အလွန်ယုတ္တိတန်သော ပါတနာရှိခြင်း။",
    "Einer zahlt alles" to "လူတစ်ဦးသည် အရာအားလုံးကို ပေးဆောင်သည်။",
    "Einfach mehr Alltag" to "ပိုမိုရိုးရှင်းသော နေ့စဉ်ဘဝ",
    "Einfach nebeneinander sein" to "တစ်ယောက်နဲ့တစ်ယောက် ဘေးမှာရှိနေပါစေ။",
    "Einfach und intim" to "ရိုးရှင်းပြီး ရင်းနှီးသော",
    "Einige Dinge für dich behalten" to "အချို့သောအရာများကို သင့်ကိုယ်သင် ထိန်းသိမ်းပါ။",
    "Einmal" to "တစ်ကြိမ်",
    "Eins, das nur wir kennen" to "ငါတို့သာသိသောတစ်ခု",
    "Englisch" to "အင်္ဂလိပ်",
    "Entspannte Hängematte" to "သက်တောင့်သက်သာရှိသော ပုခက်",
    "Entspannung" to "အပန်းဖြေခြင်း။",
    "Erdbeere" to "စတော်ဘယ်ရီ",
    "Erfolgreich" to "အောင်မြင်သည်။",
    "Ergebnisse" to "ရလဒ်များ",
    "Erst bei sehr großen Summen" to "အလွန်ကြီးမားသော ပမာဏအတွက်သာ",
    "Erst nur enge Freunde/Familie" to "အစပိုင်းတွင် ရင်းနှီးသော သူငယ်ချင်းများ/ မိသားစုများသာ",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "ကျွန်ုပ်၏လက်တွဲဖော်သည် မက်ဆေ့ချ်များကို တုံ့ပြန်ရန် အချိန်အကြာကြီး အချိန်ယူရသောအခါတွင် ၎င်းသည် ကျွန်ုပ်အား စိတ်အနှောင့်အယှက်ဖြစ်စေပါသည်။",
    "Essen & Genuss" to "အစားအသောက်နှင့် ပျော်ပွဲရွှင်ပွဲ",
    "Essensvorlieben" to "အစားအစာ စိတ်ကြိုက်များ",
    "Etwa eine Woche später, erst mal nur wir" to "တစ်ပတ်လောက်ကြာတော့ ပထမတော့ ငါတို့ပဲ။",
    "Etwas Neues ausprobieren" to "အသစ်တစ်ခုကို စမ်းကြည့်ပါ။",
    "Etwas ganz anderes" to "လုံးဝခြားနားသော အရာတစ်ခု",
    "Etwas sehr Scharfes" to "အလွန်ထက်မြက်သော အရာတစ်ခု",
    "Etwas, das ich selbst gern erfinde" to "ကိုယ်တိုင်တီထွင်ရတာကြိုက်တယ်။",
    "Etwas, eine kleine Note wäre schön" to "တစ်ခုခု၊ မှတ်သားစရာလေး ကောင်းမယ်။",
    "Familie" to "မိသားစု",
    "Familie/Freunde" to "မိသားစု/သူငယ်ချင်းများ",
    "Familienmensch" to "မိသားစု ယောက်ျား",
    "Farbedelstein" to "ရောင်စုံကျောက်မျက်ရတနာ",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "တီဗီကြော်ငြာများသည် တစ်ခါတစ်ရံတွင် ကြည့်ရှုရန် စိတ်ဝင်စားစရာဖြစ်သည်။",
    "Fertig" to "ပြီးပါပြီ။",
    "Fertig!" to "ပြီးပါပြီ။",
    "Feste Date-Nights" to "ပုံသေရက်စွဲညများ",
    "Feuerstelle" to "မီးတွင်း",
    "Filigran & schlicht" to "နန်းကြိုးနှင့် ရိုးရှင်းသော",
    "Filme/Serien" to "ရုပ်ရှင်များ/စီးရီးများ",
    "Formuliere um..." to "ပြန်ဆိုချက်...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "သင်၏မူကြမ်းကို အကြမ်းမဖက်သောနည်းဖြင့် ပြန်ဆိုပါ- စူးစမ်းမှု၊ ခံစားချက်၊ လိုအပ်မှု၊ တောင်းဆိုမှု။",
    "Frage hinzufügen" to "မေးခွန်းထည့်ပါ။",
    "Fragen & Spiele" to "မေးခွန်းများနှင့် ဂိမ်းများ",
    "Fragen für jede Gelegenheit" to "အချိန်တိုင်းအတွက် မေးခွန်းများ",
    "Freizeitpark" to "အပန်းဖြေဥယျာဉ်",
    "Freunde treffen" to "သူငယ်ချင်းများနှင့် တွေ့ဆုံပါ။",
    "Freundschaften mit Ex-Partnern sind okay." to "exes နှင့် ခင်မင်ရင်းနှီးမှု အဆင်ပြေပါသည်။",
    "Früh aufstehen" to "စောစောထပါ။",
    "Fußbodenheizung" to "အောက်ထပ် အပူပေးခြင်း",
    "Führen wir getrennte oder gemeinsame Konten?" to "ကျွန်ုပ်တို့တွင် သီးခြား သို့မဟုတ် ပူးတွဲအကောင့်များ ရှိပါသလား။",
    "Für dich empfohlen" to "သင့်အတွက် အကြံပြုထားသည်။",
    "Für die Zukunft" to "အနာဂတ်အတွက်",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "ဤရှာဖွေမှုအတွက် တူညီသောမေးခွန်းများ သို့မဟုတ် ဂိမ်းများကို ရှာမတွေ့ပါ။",
    "Für immer" to "ထာဝရ",
    "Fürsorglichkeit" to "ဂရုစိုက်မှု",
    "GFK-Brücke" to "GRP တံတား",
    "Galerie" to "ပြခန်း",
    "Gar nicht, der Moment gehört uns" to "လုံးဝမဟုတ်ပါ၊ အခိုက်အတန့်သည် ကျွန်ုပ်တို့အတွက်ဖြစ်သည်။",
    "Gar nichts tun" to "ဘာမှမလုပ်နဲ့",
    "Geduld" to "သည်းခံခြင်း။",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "နေထွက်တာကိုကြည့်ဖို့ မနက်စောစောသွားပါ။",
    "Geht so" to "ဤအတိုင်းသွားပါသည်။",
    "Geister existieren wirklich." to "သရဲတွေ တကယ်ရှိတယ်။",
    "Gelassenheit" to "ငြိမ်သက်ခြင်း။",
    "Gelbgold" to "ရွှေဝါရောင်",
    "Geld & Finanzen" to "ငွေနှင့်ဘဏ္ဍာရေး",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "ကမ္ဘာကို အတူတကွ ခရီးသွားပါ၊ ယဉ်ကျေးမှုအသစ်များနှင့် အစားအစာများကို ရှာဖွေပါ။",
    "Gemeinsam ein Lego bauen" to "လီဂိုတစ်ခုကို အတူတကွတည်ဆောက်ပါ။",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "မီးဖိုချောင်တွင် ချက်နည်းအသစ်ကို အတူတူ စမ်းကြည့်ပါ။",
    "Gemeinsame Konten" to "မျှဝေထားသော အကောင့်များ",
    "Gemeinsame Nächte" to "အတူညများ",
    "Gemeinsame Tage" to "အတူတကွ နေ့ရက်များ",
    "Gemischt" to "ရောနှောထားသည်။",
    "Gemüsebeet" to "ဟင်းသီးဟင်းရွက်ဖာ",
    "Gemütliche Feuerstelle" to "အေးအေးချမ်းချမ်း မီးဖိုချောင်",
    "Gesprächsanreger" to "စကားဝိုင်း စတင်သူ",
    "Getrennte Konten" to "သီးခြားအကောင့်များ",
    "Getrennte Urlaube tun einer Beziehung gut." to "သီးခြားအားလပ်ရက်များသည် ဆက်ဆံရေးအတွက် ကောင်းမွန်သည်။",
    "Gewächshaus" to "ဖန်လုံအိမ်",
    "Glasfassade" to "မှန်မျက်နှာစာ",
    "Gleichgültigkeit" to "ဥပေက္ခာ",
    "Glücklich und frei" to "ပျော်ရွှင်ပြီး လွတ်လပ်တယ်။",
    "Gourmet Eis-Sorten" to "အရသာရှိသော ရေခဲမုန့်အမျိုးပေါင်း",
    "Gravur innen" to "အတွင်း၌ ထွင်းထုခြင်း။",
    "Grillplatz" to "အသားကင်ဧရိယာ",
    "Groß & üppig" to "ကြီးပြီး စိမ်းလန်းစိုပြေတယ်။",
    "Große Familie" to "မိသားစုကြီး",
    "Große Feier" to "ပွဲကြီးပွဲကောင်း",
    "Große Fenster" to "ကြီးမားသော ပြတင်းပေါက်များ",
    "Große Fensterfront" to "ကြီးမားသော ပြတင်းပေါက်ရှေ့",
    "Großer Außenpool" to "ကြီးမားသော ပြင်ပရေကူးကန်",
    "Großer Garten" to "ပန်းခြံကြီး",
    "Großer Stein" to "ကျောက်တုံးကြီး",
    "Größere Küche" to "ပိုကြီးသော မီးဖိုချောင်",
    "Gutes Essen" to "အစားအသောက်ကောင်း",
    "Habe ich" to "ငါလုပ်ခဲ့တယ်။",
    "Habe ich noch nie" to "ငါ့မှာ တစ်ခါမှမရှိဘူး။",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "အံ့သြစရာကောင်းတဲ့ ခြားနားချက်ကို သင်ရှာဖွေတွေ့ရှိခဲ့ပါသလား။ အချို့သောရွေးချယ်မှုများကို သင်ပို၍နှစ်သက်ရခြင်းအကြောင်း ဆွေးနွေးပါ။",
    "Haus am See" to "ရေကန်ဘေးရှိ အိမ်",
    "Haus/Wohnung" to "အိမ်/တိုက်ခန်း",
    "Hazelnut" to "Hazelnut",
    "Heimkino" to "အိမ်တွင်းရုပ်ရှင်ရုံ",
    "Herzhaft" to "ချစ်စရာ",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "ယခု ဤနေရာတွင် ဘာမှ မရှိပါ။\nစစ်ထုတ်မှုကို ပြောင်းလဲပါ သို့မဟုတ် အခြားခေါင်းစဉ်တစ်ခုကို ရွေးချယ်ပါ။",
    "Hilfe im Alltag" to "နေ့စဥ်ဘဝတွင် အကူအညီ",
    "Himbeere" to "ရက်စ်ဘယ်ရီ",
    "Hinzufügen" to "ထည့်ပါ။",
    "Hobbys" to "ဝါသနာ",
    "Hochzeitssträuße" to "မင်္ဂလာပန်းစည်းများ",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Hogwarts House Pride- မင်းဘယ်မှာပိုင်လဲ။",
    "Home" to "အိမ်",
    "Hot Tub" to "ရေပူကန်",
    "Humor" to "ဟာသ",
    "Hund" to "ခွေး",
    "Hängematte" to "ပုခက်",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "အဆိုပြုချက်၏ တစ်စိတ်တစ်ပိုင်းအဖြစ် ရေးထားသော စာတစ်စောင်ကို လိုချင်ပါသလား။",
    "IKEA" to "IKEA",
    "Ich" to "ငါ",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "ရုပ်ရှင်ရုံသို့သွားသည့် ပန်းခြံထဲတွင် ရင်ခုန်စရာ လမ်းလျှောက်ခြင်းကို ပိုနှစ်သက်သည်။",
    "Ich bin noch nie in einem Kino eingeschlafen." to "ရုပ်ရှင်ရုံထဲမှာ တစ်ခါမှ မအိပ်ဖူးဘူး။",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "ကျွန်ုပ်သည် ကျွန်ုပ်၏လုပ်ဖော်ကိုင်ဖက်နှင့်အတူ ဝါသနာအသစ်များ သို့မဟုတ် လှုပ်ရှားမှုများကို ရှာဖွေတွေ့ရှိခြင်းကို နှစ်သက်ပါသည်။",
    "Ich finde eine Alternative" to "အခြားရွေးချယ်စရာတစ်ခုကို ငါတွေ့မယ်။",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "တူညီသောနေရာများသို့ အမြဲသွားမည့်အစား ကျွန်ုပ်၏လုပ်ဖော်ကိုင်ဖက်နှင့် စားသောက်ဆိုင်အသစ်များကို စမ်းကြည့်ရတာကို နှစ်သက်ပါသည်။",
    "Ich habe noch nie" to "ငါ တစ်ခါမှ မရှိဘူး။",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "ငါ ရိုလာကိုစတာကို တစ်ခါမှ မကြောက်ဖူးဘဲ ဘာပဲဖြစ်ဖြစ် ငါတက်ခဲ့တယ်။",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "စိတ်မရှည်လို့ Fast Pass လက်မှတ်တွေကို တစ်ခါမှ မဝယ်ဖူးပါဘူး။",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "အိမ်မှာနေပြီး တီဗီရှိုးကြည့်ဖို့ အစီအစဉ်တွေကို ဘယ်တော့မှ မဖျက်ဖူးပါဘူး။",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Hogwarts မှ ငါ့စာကို ဘယ်တုန်းကမှ မစောင့်ခဲ့ဘူး။",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Slytherin ဟာ တကယ်တော့ ဒီလောက်မဆိုးဘူးလို့ တစ်ခါမှ မပြောဖူးပါဘူး။",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Disney ဇာတ်ကားများအတွက် ကျွန်ုပ်သည် အသက်ကြီးလွန်းသည်ဟု တစ်ခါမှ မပြောခဲ့ဖူးပါ (၎င်းတို့ကို တိတ်တဆိတ် နှစ်သက်သည်)။",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Mario Kart တွင် အပြာရောင်တင့်ကားပါသော တစ်စုံတစ်ယောက်ကို ရည်ရွယ်ချက်ရှိရှိနဲ့ ပစ်ချတာမျိုး တစ်ခါမှ မလုပ်ဖူးပါဘူး။",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Disney ရုပ်ရှင်မှာ တစ်ခါမှ မငိုဖူးဘူး။",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "သည်းထိတ်ရင်ဖိုရုပ်ရှင်ကြည့်ရင်း မျက်လုံးကို တစ်ခါမှ မကွယ်ဖူးပါဘူး။",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "ဂိမ်းတစ်ခုကို သိမ်းဆည်းဖို့ ဘယ်တော့မှ မမေ့ခဲ့သလို တိုးတက်မှု နာရီပေါင်းများစွာကို ဆုံးရှုံးခဲ့ရပါတယ်။",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "ရှက်စရာကောင်းတဲ့ မြင်ကွင်းတစ်ခုအတွင်း ကျွန်တော် အခန်းထဲက ဘယ်တော့မှ မထွက်လာဘူး (ယို့ယွင်းချက်အချက်)။",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "ရိုလာကိုစတာဓာတ်ပုံရိုက်ရင်း ရယ်စရာပုံမပြဖူးဘူး။",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "ငါ ညဉ့်နက်မှ ဂိမ်းမဆော့ဖူးဘဲ နောက်နေ့ ဘယ်လောက်ပင်ပန်းခဲ့လဲ နောင်တရတယ်။",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "ငါမစောင့်နိုင်လို့ ရုပ်ရှင်ရဲ့အဆုံးသတ်ကို ဘယ်တုန်းကမှ ဂူဂဲလ်မရှာဖူးဘူး။",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "ရုပ်ရှင်ကားကြီးပေါ်မှာ ရပ်တည်နေသလိုမျိုး တစ်ခါမှ မခံစားဖူးဘူး။",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "ကျွန်တော်အကြိုက်ဆုံးစီးရီးရဲ့ နိဒါန်းကို ဘယ်တော့မှ မကျော်ခဲ့ပါဘူး။",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "အခြားသူ၏ Netflix စကားဝှက်ကို ကျွန်တော် တစ်ခါမျှ မမျှဝေခဲ့ဖူးပါ။",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "အလုပ်လုပ်နေစဉ် သို့မဟုတ် ကျောင်းတက်နေစဉ် ဂိမ်း၏တေးသွားကို တစ်ခါမျှ နားမထောင်ဖူးပါ။",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "ကျွန်ုပ်သည် ထိန်းချုပ်ကိရိယာကို ဆုံးရှုံးသွားသောအခါတွင် မည်သည့်အခါမှ အပြစ်မတင်ခဲ့ပါ။",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "ဒေါသတကြီးဖြင့် ကီးဘုတ် သို့မဟုတ် ထိန်းချုပ်ကိရိယာကို ဘယ်သောအခါမှ မစွန့်ပစ်ခဲ့ပါ။",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "အဝတ်လျှော်စက်ထဲမှာ ရေစိုအဝတ်အစားတွေကို ရက်အနည်းငယ်ကြာအောင် ဘယ်တော့မှ မမေ့ခဲ့ဘူး။",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "ဂိမ်းတစ်ခုတွင် အလှကုန်ပစ္စည်းများအတွက် ငွေအစစ်အမှန်ကို ကျွန်ုပ်ဘယ်တုန်းကမှ မသုံးစွဲခဲ့ပါ။",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "နိုင်ငံခြားမှာ ကားမမောင်းဖူးဘူး။",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "ရေချိုးခန်းထဲမှာ Disney သီချင်းကို ဘယ်တုန်းကမှ ခါးမပတ်ဖူးဘူး။",
    "Ich habe noch nie ein Elektroauto gefahren." to "လျှပ်စစ်ကား မမောင်းဖူးဘူး။",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "ပန်းခြံ mascot နဲ့ ဓာတ်ပုံမရိုက်ဖူးဘူး။",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Hogwarts ဇာတ်ကောင်နောက်မှာ အိမ်မွေးတိရိစ္ဆာန်တစ်ကောင်ကို ဘယ်တုန်းကမှ နာမည်မပေးခဲ့ပါ။",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "ကျွန်တော် ပေါက်ပေါက်ကို ရုပ်ရှင်ရုံမှာ တစ်ခါမှ မချဖူးဘဲ စားနေတုန်းပါပဲ။",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Star Wars မှ ဆရာကြီး Yoda ၏ ကိုးကားချက်ကို ကျွန်ုပ်သည် နေ့စဉ်ဘ၀တွင် မသုံးဖူးပါ။",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "စျေးကြီးတဲ့ ပန်းခြံမှာ တစ်ခါမှ မဝယ်ဖူးဘူး။",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "တစ်ဖက်လူက ကြောက်စရာကောင်းတယ်လို့ ဇာတ်ကား အကြံပြုချက် တစ်ခါမှ မပေးဖူးဘူး။",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "ညသန်းခေါင်မှာ အော်စကာပွဲ တိုက်ရိုက်ထုတ်လွှင့်တာကို တစ်ခါမှ မကြည့်ဖူးဘူး။",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "ပြီးခဲ့တဲ့ရာသီက အရမ်းဆိုးနေတာကြောင့် စီးရီးတစ်ခုကို တစ်ခါမှ မဖျက်ဖူးပါဘူး။",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "စီးရီးတစ်ခု၏ ရာသီတစ်ခုလုံးကို တစ်ရက်တည်းဖြင့် တစ်ခါမှ မကြည့်ဖူးပါ။",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "ပထမဆုံးကြိုးစားမှုမှာ သူဌေးကို ငါဘယ်တုန်းကမှ မရှုံးနိမ့်ခဲ့ဖူးသလို ဘုရားလိုခံစားရတယ်။",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "ဟီးရိုးထက် ပိုအေးတဲ့ ဗီလိန်ကို မတွေ့ဖူးဘူး။",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "ကျွန်ုပ်သည် ကျွန်ုပ်၏ကိုယ်ပိုင်အရုပ်များတွင် Toy Story ဇာတ်ကောင်ကို မမှတ်မိခဲ့ပါ။",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "ကျွန်တော်နဲ့တူတဲ့ RPG မှာ ကာရိုက်တာ တစ်ခါမှ မဖန်တီးဖူးဘူး။",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "ပန်းခြံတစ်ခုမှာ churro မစားဖူးဘူး။",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Disney ရုပ်ရှင်ကို သုံးကြိမ်ဆက်တိုက် မကြည့်ဖူးဘူး။",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "တစ်ပတ်လုံးလုံး ကျွန်တော့်မှာ ဒစ်စနေးရဲ့ စွဲမက်ဖွယ်သံစဉ်ကို တစ်ခါမှ မတီးဖူးဘူး။",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "သရုပ်ဆောင်တစ်ယောက်ကြောင့်ပဲ ရုပ်ရှင်ကို တစ်ခါမှမကြည့်ဖူးဘူး။",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "ရုပ်ရှင်တေးသံကို နာရီပေါင်းများစွာ ထပ်ခါတလဲလဲ နားမထောင်ဖူးဘူး။",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "ကျွန်တော် ရုပ်ရှင် spoiler ကို တစ်ခါမှ မထုတ်ဖော်ဖူးဘဲ ချက်ချင်း နောင်တရမိတယ်။",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "အခြားမိခင်ဘာသာစကားပြောတတ်တဲ့ သူငယ်ချင်းကို မတွေ့ဖူးပါဘူး။",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "တခြားနိုင်ငံကို ပြောင်းရွှေ့လာတဲ့ သူငယ်ချင်းတစ်ယောက်မှ မရှိပါဘူး။",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "ခရစ္စမတ်မှာ Harry Potter ရုပ်ရှင် မာရသွန်ကို တစ်ခါမှ မလုပ်ဖူးဘူး။",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "အကြွေးတင်သွားတဲ့ မြင်ကွင်းကြောင့်ပဲ Marvel ရုပ်ရှင်ကို အဆုံးအထိ တစ်ခါမှ မကြည့်ဖူးပါဘူး။",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "NPC (ကစားသမားမဟုတ်သော ဇာတ်ကောင်) ကို ရည်ရွယ်ချက်ရှိရှိ စိတ်အနှောင့်အယှက်ဖြစ်အောင် ဘယ်တုန်းကမှ မပြုလုပ်ခဲ့ပါ။",
    "Ich habe noch nie einen Nachtzug genommen." to "ညရထား တစ်ခါမှ မစီးဖူးဘူး။",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "ကျွန်ုပ်၏ Hogwarts အိမ်အား သိရှိရန် အွန်လိုင်းစမ်းသပ်မှု တစ်ခါမှ မလုပ်ဖူးပါ။",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "လိုက်ခ်များ အလုံအလောက်မရသောကြောင့် ဆိုရှယ်မီဒီယာပို့စ်ကို ဘယ်တော့မှ မဖျက်ဖူးပါ။",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "တစ်နှစ်တာရဲ့ အကောင်းဆုံးနေ့ကို အပန်းဖြေကစားကွင်းမှာ ဘယ်တော့မှ မခေါ်ဖူးပါဘူး။",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "ကျွန်တော် ပန်းခြံကို တစ်ခါမှ မရောက်ဖူးဘဲ မနက်ကနေ ညအထိ အဲဒီမှာပဲ နေခဲ့တာ။",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "ငါ Transformers ဒါမှမဟုတ် Marvel စီးတာကို လုံးဝ စွဲလန်းဖို့ ဘယ်တော့မှ မထားခဲ့ဘူး။",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "ကျွန်တော် ဒေါသကို ဘယ်တော့မှ ဖြတ်မပစ်လိုက်ဘဲ ဂိမ်းကို ဖြတ်ပစ်လိုက်တယ်။",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Harry Potter အတွဲကြီးတွေကို တစ်ခါမှ မဖတ်ဖူးဘူး။",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "စီးရီးတစ်ခုမှာ ကျွန်တော်အကြိုက်ဆုံး ဇာတ်ကောင်အကြောင်း တစ်ခါမှ မမက်မောဖူးပါဘူး။",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Quidditch ကစားဖို့ တစ်ခါမှ စိတ်ကူးမယဉ်ဖူးဘူး။",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "ခက်ခဲတဲ့အဆင့်ကို ဖြေရှင်းနည်းကို ကျွန်တော် လျှို့ဝှက်စွာ google မရှာဖူးပါဘူး။",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "ကျွန်ုပ်၏အိမ်မွေးတိရစ္ဆာန်သည် Disney တွင်ကဲ့သို့ စကားပြောနိုင်မည်ဟု လျှို့ဝှက်မျှော်လင့်ထားခြင်းမရှိပေ။",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Sims ရှိ ရေကူးကန်ခေါင်းဆောင်ကို ကျွန်ုပ် ဘယ်သောအခါမှ မဖယ်ရှားခဲ့ပါ။",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "3D Simulator စီးနင်းမှုတွင် ကျွန်ုပ်၏ဝက်ဝံများကို ဘယ်သောအခါမှ မဆုံးရှုံးခဲ့ပါ။",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "ကျွန်တော် တက္ကသိုလ်အားကစားအဖွဲ့မှာ တစ်ခါမှ မကစားဖူးဘူး။",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "ဆွဲဆောင်မှုတစ်ခုအတွက် နှစ်နာရီထက် ပိုမစောင့်ဖူးပါ။",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "ကျွန်ုပ်သည် ကျွန်ုပ်၏ အဖိုးတန်ပစ္စည်းများကို ရေစီးရေလာပေါ်တွင် စိုစွတ်နေအောင် တစ်ခါမှ မရရှိခဲ့ပါ။",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "ဘယ်အိမ်က အကောင်းဆုံးလဲလို့ သူငယ်ချင်းတစ်ယောက်နဲ့ တစ်ခါမှ မငြင်းခုံဖူးပါဘူး။",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "အဲလ်ဆာလို မှော်အစွမ်းတွေရှိဖို့ ဘယ်တုန်းကမှ မဟန်ဆောင်ဖူးဘူး။",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "ရုပ်ရှင်တစ်ကားမှာ အရေးကြီးတဲ့ ဇာတ်ဝင်ခန်းတစ်ခုကို လွတ်သွားလို့ ဒီလောက်ပြင်းပြင်းထန်ထန် မရယ်ဖူးဘူး။",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "အက်ဒရီနယ်လင်းကို တစ်ခါမှ မခံစားဖူးတော့ ချက်ချင်းပြန်စီးချင်လာတယ်။",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Snow White လို တိရိစ္ဆာန်တွေနဲ့ သီချင်းဆိုဖို့ တစ်ခါမှ မကြိုးစားဖူးဘူး။",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Disneyland ကို ခရီးထွက်ဖို့ တစ်ခါမှ စိတ်ကူးမယဉ်ဖူးဘူး။",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Jurassic Park ရေစီးကြောင်းကို တစ်ခါမှ မမက်ဖူးပါဘူး။",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "ဂိမ်းထဲမှာ ခုန်ပေါက်ပြီး ကြောက်လန့်တကြား ကျယ်လောင်စွာ မအော်ခဲ့ဖူးပါဘူး။",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "တီဗီရှိုးတစ်ခုရဲ့ နောက်ဆုံးအဆင့်အတွက် တစ်ခါမှ မငိုဖူးဘူး။",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "အိမ်မှာနေရမယ့်ရက်ကို တစ်ခါမှ မဖျက်ဖူးဘူး။",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "မက်ဆေ့ချ်ကို 10 ကြိမ်ပြန်မရေးဖူးပါဘူး။",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "ငါဘယ်တုန်းကမှ... ငါ့လက်တွဲဖော်ရဲ့ လက်ကိုင်ဖုန်းကို တိတ်တဆိတ် မကြည့်ဖူးဘူး။",
    "Ich habe noch nie!" to "ငါ တစ်ခါမှ မရောက်ဖူးဘူး။",
    "Ich habe!" to "ငါ့မှာရှိတယ်။",
    "Ich lache viel mit meinem Partner." to "ငါ့အဖော်နဲ့ အရမ်းရယ်ရတယ်။",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "ကျွန်ုပ်သည် ကျွန်ုပ်၏ လုပ်ဖော်ကိုင်ဖက်၏ ဝါသနာနှင့် စိတ်ဝင်စားမှုများကို သိလိုပါသည်။",
    "Ich liebe es" to "ကြိုက်တယ်။",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "အရင်က တစ်ခါမှမမြင်ဖူးတဲ့ ငါ့အဖော်နဲ့ ရုပ်ရှင်တွေကြည့်ရတာ ကြိုက်တယ်။",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "ကျွန်ုပ်သည် ကျွန်ုပ်၏အနှစ်သက်ဆုံးဂီတကို ကျွန်ုပ်၏လုပ်ဖော်ကိုင်ဖက်နှင့် မျှဝေလိုပါသည်။",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "ချိတ်ဆက်နေတဲ့ လေယာဉ်ကို ဖမ်းဖို့ ဘယ်တုန်းကမှ မပြေးဖူးဘူး။",
    "Ich plane gerne Dates mit meinem Partner." to "ကျွန်ုပ်သည် ကျွန်ုပ်၏ လုပ်ဖော်ကိုင်ဖက်နှင့် ချိန်းတွေ့ရန် စီစဉ်ခြင်းကို နှစ်သက်ပါသည်။",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "ငါအလုပ်များနေရင်တောင် ငါ့အဖော်နဲ့ အချိန်ဖြုန်းတာကို ဦးစားပေးတယ်။",
    "Ich schreibe meinem Partner jeden Tag." to "ကျွန်ုပ်သည် ကျွန်ုပ်၏လက်တွဲဖော်ကို နေ့တိုင်း စာပို့ပါသည်။",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "ကျွန်ုပ်သည် ကျွန်ုပ်၏လုပ်ဖော်ကိုင်ဖက်နှင့် memes နှင့် ဟာသများမျှဝေခြင်းကို နှစ်သက်ပါသည်။",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "ကျွန်ုပ်၏တစ်နေ့တာ၏အသေးစိတ်အချက်အလက်များအားလုံးကို ကျွန်ုပ်၏လုပ်ဖော်ကိုင်ဖက်နှင့် မျှဝေလိုပါသည်။",
    "Ich würde es nie tun" to "ငါဘယ်တော့မှ မလုပ်ဘူး။",
    "Ich übe noch" to "ကျွန်တော် လေ့ကျင့်ဆဲပါ။",
    "Ideen generieren" to "စိတ်ကူးများ ဖန်တီးပါ။",
    "Im Haushalt helfen" to "အိမ်ပတ်ပတ်လည်ကို ကူညီပေးပါ။",
    "In Chat einfügen" to "ချတ်သို့ထည့်ပါ။",
    "In Stille nebeneinander" to "ဘေးနားတွင် တိတ်ဆိတ်စွာနေပါ။",
    "In den Bergen" to "တောင်များတွင်",
    "In eine Bar gehen" to "ဘားတစ်ခုသို့ သွားပါ။",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "နေဝင်ချိန်ကြည့်ရန် ကမ်းခြေဘားတစ်ခုသို့ သွားပါ။",
    "In einem feinen Restaurant essen gehen" to "ကောင်းမွန်သော စားသောက်ဆိုင်တွင် စားသောက်ခြင်း။",
    "In einen Coffeeshop gehen" to "ကော်ဖီဆိုင်ကို သွားပါ။",
    "In einer Beziehung sollte man alles voneinander wissen." to "ပေါင်းသင်းဆက်ဆံရေးတစ်ခုမှာ တစ်ယောက်နဲ့တစ်ယောက်အကြောင်း အရာအားလုံးကို သိထားသင့်ပါတယ်။",
    "Infinity-Pool" to "အဆုံးမရှိ ရေကန်",
    "Innenpool" to "မိုးလုံလေလုံရေကူးကန်",
    "Intelligenz" to "ထောက်လှမ်းရေး",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "သင့်လုပ်ဖော်ကိုင်ဖက်က ၎င်းတို့ကို အစပြုသောအခါတွင် ရင်းနှီးသောအချိန်များသာရှိခြင်း။",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "ဖိတ်ကြားချက် ကုဒ်- HRM-8731 · အရာအားလုံး လော့ခ်ဖွင့်ထားသည်။",
    "Island" to "အိုက်စလန်",
    "Ist okay für mich" to "ငါအဆင်ပြေပါတယ်။",
    "Ist schon perfekt" to "ပြီးပြည့်စုံတယ်။",
    "Ja, Traditionen einbinden" to "ဟုတ်ကဲ့၊ ဓလေ့ထုံးတမ်းတွေကို ပေါင်းစပ်ပါ။",
    "Ja, absolut" to "ဟုတ်ပါတယ်၊ လုံးဝ",
    "Ja, etwas zum Lesen und Aufbewahren" to "ဟုတ်ကဲ့၊ ဖတ်ပြီး သိမ်းထားရမယ့် အရာပါ။",
    "Ja, genug" to "ဟုတ်ကဲ့၊ လုံလောက်ပါပြီ။",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "ဟုတ်တယ်၊ စိတ်လှုပ်ရှားစရာမြို့ ဒါမှမဟုတ် ဆွဲဆောင်မှုတစ်ခုထဲမှာ",
    "Ja, in- und auswendig" to "ဟုတ်တယ်၊ အတွင်းနဲ့ အပြင်",
    "Ja, komplett überraschend" to "ဟုတ်တယ်၊ လုံးဝအံ့သြစရာပဲ။",
    "Ja, perfekt" to "ဟုတ်တယ်၊ ပြီးပြည့်စုံတယ်။",
    "Ja, sie gehören zur Familie!" to "ဟုတ်ပါတယ်၊ သူတို့က မိသားစုပါ။",
    "Ja, sofort teilen" to "ဟုတ်ကဲ့၊ ချက်ချင်းမျှဝေပါ။",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "ဟုတ်ကဲ့၊ မိသားစုအချိန်ကို ဦးစားပေးမှာ သေချာပါတယ်။",
    "Jacuzzi" to "Jacuzzi",
    "Jahr zusammen 🎉" to "အတူတူ 🎉",
    "Jahre zusammen 🎉" to "နှစ်တွေအတူတကွ 🎉",
    "Jeder zahlt 50%" to "လူတိုင်း 50% ပေးရသည်",
    "Junge" to "ကောင်လေး",
    "Kamin" to "မီးဖို",
    "Karriere & Erfolg" to "အလုပ်အကိုင်နှင့် အောင်မြင်မှု",
    "Kategorien" to "အမျိုးအစားများ",
    "Katze" to "ကြောင်",
    "Keine Musik" to "သီချင်းမရှိပါ။",
    "Keine Party nötig, privat halten" to "ပါတီပွဲအတွက် မလိုအပ်ပါ၊ သီးသန့်ထားပါ။",
    "Keine Privatsphäre" to "ကိုယ်ရေးကိုယ်တာ မရှိပါ။",
    "Keine Treffer gefunden" to "ကိုက်ညီမှုမရှိပါ။",
    "Keiner" to "မရှိပါ။",
    "Keiner von uns" to "ငါတို့ထဲက တစ်ယောက်မှ မဟုတ်ဘူး။",
    "Kennst du die Essensvorlieben deines Partners?" to "သင့်လုပ်ဖော်ကိုင်ဖက်၏ အစားအသောက် စိတ်ကြိုက်များကို သင်သိပါသလား။",
    "Kino" to "ရုပ်ရှင်ရုံ",
    "Kirchlich" to "ဒေသနာ",
    "Klassisch Solitär" to "ဂန္တဝင် solitaire",
    "Klassisch gebunden" to "ရှေးရိုးကျကျ ချည်နှောင်ထားသည်။",
    "Klein & zart" to "သေးငယ်ပြီး သိမ်မွေ့သည်။",
    "Kleine Geschenke" to "လက်ဆောင်လေးတွေ",
    "Kleine Runde" to "အဖွဲ့ငယ်",
    "Kochen und Freunde einladen" to "ချက်ပြုတ်ပြီး သူငယ်ချင်းများကို ဖိတ်ခေါ်ခြင်း။",
    "Kochkurs" to "ဟင်းချက်သင်တန်း",
    "Kommt auf den Tag an" to "နေ့ပေါ် မူတည်",
    "Kommt darauf an" to "အဲဒါမူတည်တယ်။",
    "Kommt drauf an" to "အဲဒါမူတည်တယ်။",
    "Kommt mit" to "ငါနှင့်အတူ လာပါ။",
    "Konzert" to "ဖျော်ဖြေပွဲ",
    "Kräftige Farben" to "ပြင်းထန်သောအရောင်များ",
    "Kräuterbeet" to "ဆေးဘက်ဝင်အိပ်ရာ",
    "Kultur & Sehenswürdigkeiten" to "ယဉ်ကျေးမှုနှင့် မြင်ကွင်းများ",
    "Kuscheln" to "ပွေ့ဖက်ခြင်း။",
    "Kuss senden" to "နမ်းလိုက်ပါ။",
    "Körperliche Annäherung" to "ရုပ်ပိုင်းဆိုင်ရာ ချဉ်းကပ်မှု",
    "Körperliche Nähe" to "ရုပ်ပိုင်းဆိုင်ရာ နီးစပ်မှု",
    "Küche" to "မီးဖိုချောင်",
    "Land" to "နိုင်ငံ",
    "Landhaus" to "ကျေးလက်အိမ်",
    "Landhausstil" to "ကျေးလက်အိမ်ပုံစံ",
    "Lange wach bleiben" to "နောက်ကျမှနေပါ။",
    "Lappland" to "Lapland",
    "Lappland, Finnland" to "Lapland၊ ဖင်လန်",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "သင့်လက်တွဲဖော်သည် သင့်အား သင့်ကိုယ်သင် အကောင်းဆုံးဖြစ်အောင် လှုံ့ဆော်ပေးပါစေ။",
    "Lehne ab" to "ငြင်းဆို",
    "Leichtigkeit" to "ပေါ့ပါးမှု",
    "Leidenschaft" to "ကိလေသာ",
    "Liebe im Gleichgewicht" to "မျှတသောအချစ်",
    "Liebe sie, macht mehr Spaß" to "သူတို့ကို ချစ်ပါ၊ ပိုပျော်စရာကောင်းတယ်။",
    "Lieber durchgeplant oder spontan?" to "အဲဒါကို အစီအစဥ်လုပ်ထားတာလား ဒါမှမဟုတ် သူ့အလိုလိုဖြစ်စေချင်လား။",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "နှစ်ယောက်အတူဖြစ်ဖြစ် လူများနဲ့ဖြစ်ဖြစ် အေးအေးဆေးဆေး ညချမ်းကို ကြိုက်မှာလား။",
    "Lieber nicht" to "မဟုတ်တာ ပိုကောင်းပါတယ်။",
    "Lieber vorher grob absprechen" to "အကြောင်းအရာတွေကို အကြမ်းဖျင်း ကြိုပြီး ဆွေးနွေးတာက ပိုကောင်းပါတယ်။",
    "Lokal einkaufen" to "ပြည်တွင်းတွင် ဈေးဝယ်ပါ။",
    "London" to "လန်ဒန်",
    "London, England" to "လန်ဒန်၊ အင်္ဂလန်",
    "Lügen" to "လိမ်ညာခြင်း။",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "အများသူငှာ သို့မဟုတ် ပုဂ္ဂလိက အဆိုပြုချက်ကို သင်နှစ်သက်ပါသလား။",
    "Malediven" to "မော်လ်ဒိုက်",
    "Man sollte nie streitend einschlafen." to "ငြင်းခုံရင်း ဘယ်တော့မှ အိပ်ပျော်မသွားသင့်ဘူး။",
    "Mango Sorbet" to "Mango Sorbet",
    "Markant & breit" to "ထိတ်လန့်ပြီး ကျယ်သည်။",
    "Marken & Alltag" to "အမှတ်တံဆိပ်များနှင့် နေ့စဉ်ဘဝ",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "မြေထဲပင်လယ် ခြံဝင်း",
    "Mehr Unterstützung" to "နောက်ထပ်ပံ့ပိုးမှု",
    "Mehr gemeinsame Zeit" to "အတူတူ အချိန်ပိုပေးပါ။",
    "Mehr zuhören" to "နောက်ထပ် နားထောင်ပါ။",
    "Mehrgenerationenhaus" to "မျိုးဆက်ပေါင်းစုံ အိမ်",
    "Mein Arbeitsplatz" to "ကျွန်ုပ်၏ လုပ်ငန်းခွင်",
    "Mein Partner" to "ငါ့အဖော်",
    "Mich überraschen" to "ငါ့ကို အံ့အားသင့်စေတယ်။",
    "Minimalistisches Interieur" to "ရိုးရှင်းသော အတွင်းခန်း",
    "Missverständnisse" to "နားလည်မှုလွဲမှားခြင်း။",
    "Mit Familie und engen Freunden" to "မိသားစုနှင့် ရင်းနှီးသော သူငယ်ချင်းများနှင့်အတူ",
    "Mit Kompromissen" to "အပေးအယူများဖြင့်",
    "Mitgefühl" to "ကရုဏာ",
    "Mittelweg mit besonderen Details" to "အထူးအသေးစိတ်အချက်များနှင့်အတူ အလယ်ဗဟို",
    "Modern geometrisch" to "ခေတ်မီဂျီဩမေတြီ",
    "Moderne Grillstation" to "ခေတ်မီ အကင်ဆိုင်",
    "Moderner Name" to "ခေတ်မီအမည်",
    "Moderner Solitär" to "ခေတ်မီ solitaire",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "အခိုက်အတန့်ကို ရိုက်ကူးပါ။",
    "Momente" to "အခိုက်အတန့်",
    "Monaco" to "မိုနာကို",
    "Moralische Werte" to "ကိုယ်ကျင့်တရားတန်ဖိုးများ",
    "Museum" to "ပြတိုက်",
    "Musik" to "သီချင်း",
    "Mut" to "သတ္တိ",
    "Mädchen" to "မိန်းကလေးများ",
    "Möbelhaus" to "ပရိဘောဂဆိုင်",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "ပဟေဠိကို ချန်ထားလိုသည်မှာ သေချာပါသလား။ သင်၏ယခင်တိုးတက်မှုကို သိမ်းဆည်းထားသည်။",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "အက်ပ်တွင် အိမ်မွေးတိရစ္ဆာန်များကို ထည့်သွင်းလိုပါသလား။",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "အခိုက်အတန့်ကို ဆိုရှယ်မီဒီယာပေါ်တွင် ချက်ချင်းမျှဝေလိုပါသလား။",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "ကျွန်ုပ်တို့သည် ငွေစုရန် လိုအပ်ပါသည်။",
    "Müssen es planen" to "၎င်းကို စီစဉ်ရန် လိုအပ်သည်။",
    "Müssen sparen" to "သိမ်းဆည်းရန် လိုအပ်သည်။",
    "Nachricht an" to "မက်ဆေ့ဂျ်",
    "Name Partnerin" to "ပါတနာအမည်",
    "Namen und Startdatum eurer Beziehung." to "သင့်ဆက်ဆံရေး၏ အမည်များနှင့် စတင်သည့်ရက်စွဲ။",
    "Natursteinfassade" to "သဘာဝကျောက်မျက်နှာစာ",
    "Naturteich" to "သဘာဝရေကန်",
    "Nein, einfach halten" to "မဟုတ်ဘူး၊ ကိုင်ထားလိုက်ပါ။",
    "Nein, erstmal privat halten" to "မဟုတ်ပါ၊ ၎င်းကို သီးသန့်ထားပါ။",
    "Nein, lieber vor Ort" to "မဟုတ်ဘူး၊ ဆိုက်မှာ ပိုကောင်းပါတယ်။",
    "Nein, modern halten" to "မဟုတ်ပါ၊ ခေတ်မီအောင်ထားပါ။",
    "Nein, nur wir" to "မဟုတ်ဘူး၊ ငါတို့ပဲ",
    "Nein, zu ablenkend" to "မဟုတ်ဘူး၊ အာရုံထွေပြားလွန်းတယ်။",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "စမတ်အိမ်ပါသော အဆောက်အဦအသစ်",
    "Neubau mit Technik" to "နည်းပညာဖြင့် အဆောက်အဦအသစ်",
    "Neue Liebe, neue Erfahrungen" to "အချစ်သစ်၊ အတွေ့အကြုံသစ်",
    "Neues Hobby" to "ဝါသနာအသစ်",
    "Neues Spiel" to "ဂိမ်းအသစ်",
    "Neugier" to "စူးစမ်းလိုစိတ်",
    "New York" to "နယူးယောက်",
    "New York, USA" to "နယူးယောက်၊ အမေရိကန်",
    "Nicht mein Fall" to "ငါ့လက်ဖက်ရည်ခွက် မဟုတ်ဘူး။",
    "Nicht nötig, lieber klassisch bleiben" to "မလိုအပ်ပါဘူး၊ ဂန္ထဝင်နေဖို့က ပိုကောင်းပါတယ်။",
    "Nichts — es passt so" to "ဘာမှ - တော်ပါတယ်။",
    "Nie wieder Burger" to "ဘာဂါ ဘယ်တော့မှ ထပ်မစားတော့ဘူး။",
    "Nie wieder Pizza" to "ပီဇာကို ဘယ်တော့မှ ထပ်မလုပ်တော့ဘူး။",
    "Niemand" to "ဘယ်သူမှ",
    "Niemand ohne Plan" to "အစီအစဉ်မရှိဘဲ မည်သူမျှ",
    "Nike" to "Nike",
    "Nizza" to "ကောင်းတယ်။",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "အခိုက်အတန့်မရှိသေးပါ။\nသင်၏ပထမဆုံးအတွေ့အကြုံကို ရိုက်ကူးပါ 💞",
    "Nur bei wichtigen Themen" to "အရေးကြီးသောအကြောင်းအရာများအတွက်သာ",
    "Nur wir beide" to "ငါတို့နှစ်ယောက်တည်းပဲ။",
    "Nähe & Intimität" to "ရင်းနှီးမှုနှင့် ရင်းနှီးမှု",
    "Obstgarten" to "သစ်သီးခြံ",
    "Oder" to "သို့မဟုတ်",
    "Offene Küche" to "မီးဖိုချောင်ဖွင့်ပါ။",
    "Offene Wohnküche" to "မီးဖိုချောင်/ဧည့်ခန်း ဖွင့်ပါ။",
    "Ohne Stein" to "ကျောက်မပါဘဲ",
    "Open End" to "အဖွင့်ဇာတ်သိမ်း",
    "Outdoor-Küche" to "ပြင်ပမီးဖိုချောင်",
    "Outdoor-Sofa" to "ပြင်ပဆိုဖာ",
    "Outdoor-Whirlpool" to "ပြင်ပ ရေပူကန်",
    "Ovaler Diamant" to "ဘဲဥပုံစိန်",
    "Paar" to "အတွဲ",
    "Paar-Statistiken" to "စုံတွဲ ကိန်းဂဏန်းများ",
    "Paris" to "ပါရီ",
    "Paris, Frankreich" to "ပါရီ၊ ပြင်သစ်",
    "Partner" to "ပါတနာ",
    "Partner-Simulator" to "ပါတနာ simulator",
    "Partnerin" to "ပါတနာ",
    "Party Edition" to "ပါတီထုတ်ဝေမှု",
    "Party Edition II" to "ပါတီထုတ်ဝေမှု II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "တိရစ္ဆာန်တစ်ကောင်သည် ကျွန်ုပ်တို့၏နေ့စဉ်ဘဝများတွင်ပင် အံဝင်ခွင်ကျဖြစ်ပါသလား။",
    "Pasta" to "ခေါက်ဆွဲ",
    "Pastell" to "Pastel",
    "Penthouse mit Ausblick" to "မြင်ကွင်းပါသော Penthouse",
    "Pepsi" to "ပက်စီ",
    "Pergola mit Lounge" to "နားနေခန်းပါသော Pergola",
    "Pfingstrosen" to "ပိတောက်ပင်",
    "Pinguin" to "ပင်ဂွင်း",
    "Pistazie" to "Pistachio",
    "Pizza" to "ပီဇာ",
    "Pizzaofen" to "ပီဇာမီးဖို",
    "Platin" to "ပလက်တီနမ်",
    "PlayStation" to "PlayStation",
    "Pool" to "ရေကန်",
    "Pop" to "ပေါ့ပ်",
    "Prasselnder Kamin" to "ဟောက်မီးဖို",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "မင်းသမီးများ၊ ပင်လယ်ဓားပြများနှင့် နတ်သမီးဖုန်မှုန့်- Disney Quiz",
    "Privater Innenhof" to "ကိုယ်ပိုင် ခြံဝင်း",
    "Profil" to "ပရိုဖိုင်",
    "Profil bearbeiten" to "ပရိုဖိုင်ကို တည်းဖြတ်ပါ။",
    "Prozentual nach Einkommen" to "ဝင်ငွေအပေါ်အခြေခံသည့် ရာခိုင်နှုန်း",
    "Quiz verlassen" to "ပဟေဠိကို ထွက်လိုက်ပါ။",
    "Quiz verlassen?" to "ပဟေဠိ ချန်ထားမလား။",
    "Rausgehen in die Natur" to "သဘာဝအတိုင်းထွက်လိုက်ပါ။",
    "Reden vor ..." to "စကားပြောနေသည်...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "ပုံမှန်ရက်စွဲများ သို့မဟုတ် အချိန်များကို အတူတကွ စီစဉ်ပါ။",
    "Reisen" to "ခရီးသွား",
    "Reiseziele" to "ခရီးသွားနေရာများ",
    "Respektlosigkeit" to "အရိုအသေပြုခြင်း။",
    "Restaurant" to "စားသောက်ဆိုင်",
    "RnB / Soul" to "RnB / Soul",
    "Rock" to "ရော့ခ်",
    "Rom" to "ရောမ",
    "Rom, Italien" to "ရောမ၊ အီတလီ",
    "Romantik" to "အချစ်ဇာတ်လမ်း",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "မက်ဆေ့ချ်များ၊ မှတ်စုများ သို့မဟုတ် လက်ဆောင်များကဲ့သို့သော ရိုမန်းတစ်အမူအရာများက ကျွန်ုပ်ကို ပျော်ရွှင်စေသည်။",
    "Romantische Stimmung" to "ရိုမန်းတစ်စိတ်ဓာတ်",
    "Roségold" to "နှင်းဆီရွှေ",
    "Ruhig zu zweit" to "နှစ်ယောက်အတွက် တိတ်ဆိတ်",
    "Runder Diamant" to "စိန်ဝိုင်း",
    "Salted Caramel" to "ဆားနယ် ကာရာမယ်လ်",
    "Sammle Ideen..." to "စိတ်ကူးများ စုဆောင်းပါ...",
    "Santorini" to "ဆန်တိုရီနီ",
    "Santorini, Griechenland" to "ဆန်တိုရီနီ၊ ဂရိ",
    "Saphir" to "နီလာ",
    "Saunahaus" to "Sauna အိမ်",
    "Schickes Restaurant oder Hotel" to "အမိုက်စား စားသောက်ဆိုင် သို့မဟုတ် ဟိုတယ်",
    "Schlafzimmer" to "အိပ်ခန်း",
    "Schließen" to "ပိတ်ပါ။",
    "Schmal & zart" to "ပါးလွှာပြီး သိမ်မွေ့သည်။",
    "Schnappschüsse aus unserer Liebesgeschichte" to "ကျွန်ုပ်တို့၏ အချစ်ဇာတ်လမ်းမှ လျှပ်တစ်ပြက်များ",
    "Schokolade" to "ချောကလက်",
    "Schreib frei, was dir wirklich dazu einfällt." to "အမှန်တကယ် စိတ်ထဲရောက်နေသည့်အရာကို လွတ်လပ်စွာရေးပါ။",
    "Schreibe deine eigene Antwort" to "သင့်ကိုယ်ပိုင်အဖြေကို ရေးပါ။",
    "Sehr gerne" to "ကြိုဆိုပါတယ်။",
    "Sehr leicht" to "အလွန်ပေါ့ပါးသည်။",
    "Sehr wichtig — Fotos und Video" to "အလွန်အရေးကြီး — ဓာတ်ပုံနှင့် ဗီဒီယို",
    "Sehr wichtig, es sollte persönlich sein" to "အလွန်အရေးကြီးသည်၊ ၎င်းသည် ပုဂ္ဂိုလ်ရေးအရ ဖြစ်သင့်သည်။",
    "Selbst kochen" to "ကိုယ်တိုင်ချက်ပြုတ်ပါ။",
    "Senden" to "ပို့ပါ။",
    "Separate Küche" to "သီးခြားမီးဖိုချောင်",
    "Serie schauen" to "စီးရီးကို ကြည့်ပါ။",
    "Serienmarathon auf dem Sofa" to "ဆိုဖာပေါ်တွင် မာရသွန်စီးရီးများ",
    "Sex & Liebe" to "လိင်နှင့်အချစ်",
    "Seychellen" to "Seychelles",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "ကလေးတစ်ဦး/ ကလေးအများအပြားအတွက် ကုန်ကျစရိတ်အားလုံးကို ကာမိနိုင်ပါသလား။ 💰",
    "Soll der Antrag eine Überraschung sein?" to "အဆိုပြုချက်သည် အံ့အားသင့်သင့်ပါသလား။",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "အပလီကေးရှင်းတွင် ယဉ်ကျေးမှု သို့မဟုတ် ရိုးရာဒြပ်စင်များ ပါဝင်သင့်ပါသလား။",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "အပလီကေးရှင်းတွင် ယဉ်ကျေးမှု သို့မဟုတ် ရိုးရာဒြပ်စင်များ ပါဝင်သင့်ပါသလား။",
    "Sommerhochzeit" to "နွေရာသီ မင်္ဂလာဆောင်",
    "Sonnige Dachterrasse" to "နေသာခေါင်မိုး လှေကားထစ်",
    "Sowohl als auch" to "နှစ်မျိုးလုံးနှင့်",
    "Spazieren" to "လမ်းလျှောက်ပါ။",
    "Spaß & Abenteuer" to "ပျော်စရာနှင့် စွန့်စားခန်း",
    "Speichern" to "သိမ်းဆည်းပါ။",
    "Spiel bearbeiten" to "ဂိမ်းကို တည်းဖြတ်ပါ။",
    "Spielbereich für Kinder" to "ကလေးများအတွက် ကစားကွင်း",
    "Spiele" to "ဂိမ်းများ",
    "Spiele spielen und Spaß haben" to "ဂိမ်းကစားပြီး ပျော်ရွှင်ပါစေ။",
    "Spontan" to "အလိုအလျောက်",
    "Sportplatz" to "အားကစားကွင်း",
    "Spotify" to "Spotify",
    "Sprache" to "ဘာသာစကား",
    "Stadt" to "မြို့",
    "Stadt oder Land — was ist uns wichtiger?" to "မြို့ သို့မဟုတ် နိုင်ငံ - ကျွန်ုပ်တို့အတွက် အဘယ်အရာက ပိုအရေးကြီးသနည်း။",
    "Stadtvilla" to "စီးတီးဗီလာ",
    "Standesamt & Party" to "မှတ်ပုံတင်ရုံးနှင့် ပါတီ",
    "Statement-Ring" to "ထုတ်ပြန်ချက် လက်စွပ်",
    "Stilvolles Outdoor-Sofa" to "စတိုင်ကျသော အပြင်ဘက်ဆိုဖာ",
    "Stimme voll zu" to "လုံးဝသဘောတူပါသည်။",
    "Stimmt" to "မှန်ပါတယ်။",
    "Stimmt nicht" to "မမှန်ပါ။",
    "Stimmt, noch nie" to "မှန်ပါတယ်၊ ဘယ်တော့မှ",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "ကမ်းခြေနေ့",
    "Streit über Haushalt" to "အိမ်ထောင်စုအတွက် အငြင်းပွားမှု",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "အဆက်မပြတ်",
    "Suche schließen" to "ရှာဖွေမှုကို ပိတ်ပါ။",
    "Suche zurücksetzen" to "ရှာဖွေမှုကို ပြန်လည်သတ်မှတ်ပါ။",
    "Suche öffnen" to "ရှာဖွေမှုကို ဖွင့်ပါ။",
    "Suchergebnisse" to "ရှာဖွေမှုရလဒ်များ",
    "Sushi" to "ဆူရှီ",
    "Süß" to "ချောတယ်။",
    "Tage zusammen 💞" to "အတူတူ ရက်တွေ 💞",
    "Tauche ins Unterbewusstsein" to "မသိစိတ်ထဲသို့ ထိုးဆင်းပါ။",
    "Teile alle deine Hobbys mit deinem Partner" to "သင့်ဝါသနာအားလုံးကို သင့်လုပ်ဖော်ကိုင်ဖက်နှင့် မျှဝေပါ။",
    "Teils teils" to "တစ်စိတ်တစ်ပိုင်း",
    "Testen" to "စမ်းသပ်မှု",
    "Themen" to "အကြောင်းအရာများ",
    "Tiefe Gespräche" to "နက်နဲသော စကားဝိုင်းများ",
    "Tiefgründige Gespräche führen" to "လေးနက်သော စကားပြောဆိုမှုများ ပြုလုပ်ပါ။",
    "Tierpension" to "တိရိစ္ဆာန် ဘော်ဒါဆောင်",
    "Tiny House" to "အိမ်သေးသေးလေး",
    "Tippen zum Auswählen & Scrollen" to "ရွေးချယ်ပြီး လှိမ့်ရန် တို့ပါ။",
    "Tippen zum Zuklappen" to "ပြိုကျရန် တို့ပါ။",
    "Titel" to "ခေါင်းစဉ်",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "ခေါင်းစဉ်၊ အမျိုးအစား၊ အကြောင်းအရာ၊ တဂ်များ၊ မေးခွန်းများ...",
    "Tokyo, Japan" to "တိုကျို၊ ဂျပန်",
    "Traditioneller Name" to "ရိုးရာအမည်",
    "Traumhaus Außenbereich" to "အိပ်မက်အိမ် အပြင်ဘက်ဧရိယာ",
    "Traumhochzeit" to "အိပ်မက်မင်္ဂလာ",
    "Treffer" to "ထိတယ်။",
    "Tägliche Aktivität" to "နေ့စဉ်လှုပ်ရှားမှု",
    "Umformulieren" to "ပြန်ဆိုချက်",
    "Unbeantwortet" to "ဖုန်းမဖြေပါ။",
    "Unbeliebte Meinungen" to "လူကြိုက်များသော အမြင်များ",
    "Universal Studios Genie oder Neuling?" to "Universal Studios ပါရမီရှင်လား ဒါမှမဟုတ် အသစ်လား။",
    "Uns auseinanderzuleben" to "ခြားနားရန်",
    "Unser Intimleben" to "ကျွန်ုပ်တို့၏ ရင်းနှီးသောဘဝ",
    "Unser Traumhaus" to "ကျွန်ုပ်တို့၏ အိပ်မက်အိမ်",
    "Unser erstes Treffen" to "ကျွန်ုပ်တို့၏ ပထမဆုံးတွေ့ဆုံမှု",
    "Unsere Gesichter" to "ကျွန်ုပ်တို့၏ မျက်နှာများ",
    "Unsere eigenen Träume" to "ကျွန်ုပ်တို့၏ကိုယ်ပိုင်အိပ်မက်များ",
    "Unsere nächste Reise" to "ကျွန်ုပ်တို့၏ နောက်ခရီးစဉ်",
    "Unter 1000" to "၁၀၀၀ အောက်",
    "Unter 1000 im Monat" to "တစ်လလျှင် 1000 အောက်",
    "Unter 50€/Monat" to "50€/လအောက်",
    "Unter Leuten" to "လူတွေကြားထဲမှာ",
    "Untreue" to "ဖောက်ပြန်မှု",
    "Urlaub" to "အားလပ်ရက်",
    "Vanille" to "ဗနီလာ",
    "Venedig" to "ဗင်းနစ်",
    "Venedig, Italien" to "ဗင်းနစ်၊ အီတလီ",
    "Verbinde dich mit" to "ဖြင့် ချိတ်ဆက်ပါ။",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "အဖြေကိုကြည့်ရန် \${profile.partnerName} သို့ ချိတ်ဆက်ပါ",
    "Verbindung" to "ချိတ်ဆက်မှု",
    "Verbringe die Feiertage mit deiner Familie" to "အားလပ်ရက်များကို သင့်မိသားစုနှင့် ဖြတ်သန်းပါ။",
    "Verlobungsringe" to "စေ့စပ်လက်စွပ်",
    "Vertrautheit" to "ရင်းနှီးမှု",
    "Viel getrennt" to "ခွဲခွာခြင်းများစွာ",
    "Vielleicht ein oder zwei" to "တစ်ခု သို့မဟုတ် နှစ်ခု ဖြစ်နိုင်သည်။",
    "Vielleicht, aber mündlich reicht" to "ဖြစ်နိုင်သည်၊ သို့သော် ဝစီကံအားဖြင့် လုံလောက်ပါသည်။",
    "Vielleicht, wenn es machbar ist" to "ဖြစ်နိုင်ရင် ဖြစ်နိုင်တယ်။",
    "Vielleicht, wenn es passt" to "အဆင်ပြေရင် ဖြစ်နိုင်တယ်။",
    "Vintage Art déco" to "ခေတ်ဟောင်း Art Deco",
    "Vintage verspielt" to "ခေတ်ဟောင်းအပျော်အပါး",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "သင့်လက်တွဲဖော်မှ ဝါသနာအသစ်များကို မိတ်ဆက်ပေးခြင်း။",
    "Vor dem Kauf eines Hauses besprechen" to "အိမ်မဝယ်မီ ဆွေးနွေးပါ။",
    "Vor der Anschaffung eines Haustiers besprechen" to "အိမ်မွေးတိရစ္ဆာန်မဝယ်မီ ဆွေးနွေးပါ။",
    "Vor der gemeinsamen Reise besprechen" to "ခရီးမထွက်ခင် ဆွေးနွေးပါ။",
    "Vor nichts" to "ဘာမှမဖြစ်ပါ။",
    "Vorort" to "ဆင်ခြေဖုံးရပ်ကွက်",
    "Walnuss" to "သစ်ကြားသီး",
    "Wandern" to "တောင်တက်",
    "Wann fühlst du dich mir am nächsten?" to "မင်းငါ့ကို ဘယ်အချိန်မှာ အရင်းနှီးဆုံးလို့ ခံစားရလဲ။",
    "Wann fühlst du dich mir körperlich am nächsten?" to "မင်းငါ့နဲ့ အနီးကပ်ဆုံးလို့ ဘယ်အချိန်မှာ ခံစားရလဲ။",
    "Was bedeutet Vertrauen für dich konkret?" to "ယုံကြည်မှုသည် သင့်အတွက် အထူးအဓိပ္ပာယ်ရှိသနည်း။",
    "Was entspannt dich mehr?" to "ဘယ်အရာက သင့်ကို ပိုပြီး စိတ်အပန်းပြေစေသလဲ။",
    "Was fehlt dir über die Distanz am meisten?" to "အကွာအဝေးနဲ့ ပတ်သက်ပြီး သင်ဘယ်အရာကို အလွမ်းဆုံးလဲ။",
    "Was gefällt dir an deinem Zuhause am besten?" to "သင့်အိမ်နဲ့ ပတ်သက်ပြီး သင်ဘယ်အရာကို အနှစ်သက်ဆုံးလဲ။",
    "Was hast du von deinem Partner gelernt?" to "သင့်လက်တွဲဖော်ထံမှ သင်ဘာသင်ယူခဲ့သနည်း။",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "စိတ်ရောကိုယ်ပါ အကြောင်းအရာတွေကို အတူတူကြည့်ဖို့ ဘယ်လိုထင်လဲ။",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "ကျားကွက်များ (ဥပမာ ဆိုင်းဘုတ်များ၊ မီးပုံးပျံများ စသည်) နှင့် ပတ်သက်၍ သင်မည်သို့ ထင်မြင်ပါသလဲ။",
    "Was ist das Wichtigste beim Antrag?" to "လျှောက်ထားရာတွင် အရေးကြီးဆုံးအချက်မှာ အဘယ်နည်း။",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "လိင်ဆက်ဆံမှုမှာ သင်ရှာတွေ့တဲ့ အရေးကြီးဆုံးအရာက ဘာလဲ။",
    "Was ist dein Lieblingsfoto von uns? 📸" to "ကျွန်ုပ်တို့၏ အကြိုက်ဆုံးဓာတ်ပုံကား အဘယ်နည်း။ 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "အတူတကွနေထိုင်ခြင်းအတွက် အကြီးမားဆုံးကြောက်ရွံ့မှုကား အဘယ်နည်း။",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "သင်နှစ်သက်တဲ့ အစားအစာက ဘာလဲ၊ ဒါပေမယ့် သင့်လက်တွဲဖော်က နားမလည်နိုင်ပါဘူး။",
    "Was ist für dich ein absoluter Dealbreaker?" to "သင့်အတွက် လုံးဝအပေးအယူလုပ်သူဆိုတာ ဘာလဲ။",
    "Was ist für jeden von uns das absolute Highlight?" to "ကျွန်ုပ်တို့တစ်ဦးစီအတွက် လုံးဝမီးမောင်းထိုးပြခြင်းကား အဘယ်နည်း။",
    "Was ist passiert?" to "ဘာဖြစ်သွားတာလဲ။",
    "Was macht einen Moment für dich romantisch?" to "သင့်အတွက် အခိုက်အတန့်ကို ဘာက ရိုမန်းတစ်ဖြစ်စေတာလဲ။",
    "Was magst du an deinem Partner am liebsten?" to "သင့်လက်တွဲဖော်နဲ့ ပတ်သက်ပြီး သင် ဘာကို အနှစ်သက်ဆုံးလဲ။",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "မင်းက ဘာကို ပိုကြိုက်လဲ- စောစောထတာ ဒါမှမဟုတ် နောက်ကျနေတာလား။",
    "Was magst du lieber?" to "ဘယ်ဟာပိုကြိုက်လဲ။",
    "Was möchtest du eigentlich sagen?" to "အမှန်တကယ် ဘာပြောချင်လဲ။",
    "Was möchtest du, dass dein Partner öfter tut?" to "သင့်လက်တွဲဖော်ကို ဘာကို ပိုမကြာခဏလုပ်စေချင်လဲ။",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "ခရီးသွားတဲ့အခါ တိရစ္ဆာန်က ဘာဖြစ်မလဲ။",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "ကြီးပြင်းလာသောအခါ ကျွန်ုပ်တို့၏ကလေးသည် မည်သို့ဖြစ်လာမည်နည်း။",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "မိဘတွေအနေနဲ့ ဘယ်တော့မှ မျက်ခြည်မပြတ်သင့်ဘူး။",
    "Was war dein schönster Moment mit mir bisher?" to "အခုထိ ငါနဲ့ မင်းအကောင်းဆုံးအချိန်က ဘာလဲ။",
    "Was wir gegessen haben" to "ငါတို့စားခဲ့တာ",
    "Was wollt ihr nie vergessen?" to "ဘယ်တော့မှ မမေ့ချင်ဘူး။",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "သင့်အတွက် ပိုဆိုးတာက ပီဇာကို ဘယ်တော့မှ ထပ်မစားပါနဲ့ ဒါမှမဟုတ် ဘာဂါ ဘယ်တော့မှ ထပ်မစားတော့ပါဘူး။",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "တစ်နေ့တာမှာ သင်ဘာလုပ်ချင်ဆုံးလဲ။",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "ငွေကြေးပြဿနာမဟုတ်ပါက သင်ချက်ချင်းပြောင်းလဲမည့်အရာ။",
    "Weiter" to "နောက်တစ်ခု",
    "Weiter spielen" to "ဆက်ကစားပါ။",
    "Weiß ich noch nicht" to "မသိသေးဘူး။",
    "Weiße Rosen" to "နှင်းဆီအဖြူ",
    "Weißgold" to "ရွှေဖြူ",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "ကျွန်ုပ်တို့၏ကလေးသည် ကျွန်ုပ်တို့ထံမှ မည်သည့်အရည်အသွေးကို ရရှိသင့်သနည်း။",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "အဆိုပြုချက်တစ်ခုအတွက် မည်သည့်ပတ်ဝန်းကျင်ကို လိုချင်သနည်း။",
    "Welcher Raum sagt am meisten über dich aus?" to "ဘယ်အခန်းက မင်းအကြောင်း အများဆုံးပြောလဲ။",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "အစားအသောက်နှင့် တိရစ္ဆာန်ဆေးကုဆရာဝန်အတွက် ကျွန်ုပ်တို့ အဘယ်ဘတ်ဂျက်လျာထားသနည်း။",
    "Welches Lied macht dich an? 🥵" to "ဘယ်သီချင်းက မင်းကို လွမ်းနေလဲ။ 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "မျှဝေထားသော ဓာတ်ပုံသည် သင်အကြိုက်ဆုံးဖြစ်ပါသလား။",
    "Wellnessbad" to "ကျန်းမာရေချိုးခြင်း။",
    "Wenn es schwierig ist" to "ခက်ခဲတဲ့အခါ",
    "Wenn ich müde bin" to "ပင်ပန်းနေချိန်",
    "Wenn wir uns lange umarmen" to "အချိန်အကြာကြီး ပွေ့ဖက်တဲ့အခါ",
    "Wenn wir zusammen lachen" to "အတူတူရယ်တဲ့အခါ",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "ဘာကို မှာရမလဲ ဘယ်သူက ပိုမြန်မြန် ဆုံးဖြတ်လဲ။",
    "Wer findet die besten Restaurants?" to "အကောင်းဆုံး စားသောက်ဆိုင်များကို ဘယ်သူက ရှာတွေ့လဲ။",
    "Wer gibt mehr Herzlichkeit?" to "ဘယ်သူက ပိုနွေးထွေးစေတာလဲ။",
    "Wer hat den besseren Musikgeschmack?" to "ဂီတမှာ ဘယ်သူက ပိုအရသာရှိလဲ။",
    "Wer hängt mehr an seinen Eltern?" to "မိဘတွေကို ဘယ်သူက ပိုတွယ်တာလဲ။",
    "Wer ist besser organisiert?" to "ဘယ်သူက ပိုကောင်းအောင် စည်းရုံးမလဲ။",
    "Wer ist der Beste bei der Filmauswahl?" to "ရုပ်ရှင်ရွေးချယ်ရာမှာ ဘယ်သူက အကောင်းဆုံးလဲ။",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "အချစ်နေ့စွဲများ စီစဉ်ရာတွင် ဘယ်သူက အကောင်းဆုံးလဲ။",
    "Wer ist der beste Tänzer?" to "အကောင်းဆုံး အကသမားက ဘယ်သူလဲ။",
    "Wer ist romantischer?" to "ဘယ်သူက အချစ်ပိုလဲ။",
    "Wer kocht besser?" to "ဘယ်သူက ပိုချက်ကောင်းလဲ။",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "ပြုပြင်မွမ်းမံခြင်းနှင့် ပြုပြင်ထိန်းသိမ်းခြင်းကို မည်သူက ဂရုစိုက်သနည်း။",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "တစ်ဖက်လူ နေမကောင်းတဲ့အခါ ဘယ်သူက ပိုသတိထားမိလဲ။",
    "Wer sucht am Ende wirklich den Film aus?" to "အဆုံးတွင် ဇာတ်ကားကို မည်သူက အမှန်တကယ် ရွေးချယ်သနည်း။",
    "Wer vergisst eher einen Jahrestag?" to "နှစ်ပတ်လည်နေ့ကို ဘယ်သူက ပိုမေ့နိုင်မလဲ။",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "နောက်နေ့မနက်မှာ ကိုယ့်နာမည်ကို ဘယ်သူက ပိုမေ့နိုင်မလဲ။",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "သူတို့ ဘာမှမသိတဲ့ နောက်နေ့မှာ ဗီဒီယိုတစ်ခုကို ဘယ်သူက ပိုရှာတွေ့နိုင်မလဲ။",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "သူစိမ်းတစ်ယောက်ရဲ့ ဆိုဖာပေါ်မှာ တစ်ညကို ဘယ်သူက ပိုကြိုက်လဲ။",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "ပါတီပွဲတစ်ခုမှာ အိပ်ပျော်ပြီး သူတို့ရဲ့မျက်နှာပေါ်မှာ Sharpie နဲ့ နိုးထဖို့ ဘယ်သူက ပိုဖြစ်နိုင်မလဲ။",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "အကကြမ်းပြင်မှာ ချော်လဲတတ်ပေမယ့် အလန်းစားပုံစံဖြစ်အောင် ဘယ်သူက ပိုဖြစ်မလဲ။",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "အိမ်ပါတီတစ်ခုတွင် Spotify အစီအစဉ်ကို မည်သူက ပိုထိန်းချုပ်နိုင်မည်နည်း။",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "ပါတီပွဲတစ်ခုတွင် လူတိုင်းအတွက် ပီဇာကို မှာကြားပြီး ကိုယ်တိုင်စားရန် မည်သူက ပိုဖြစ်နိုင်မည်နည်း။",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "ပါတီတစ်ခုတွင် မည်သူက ဦးစွာ အိပ်ပျော်နိုင်ခြေပိုများသနည်း။",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "ပါတီတစ်ခုတွင် ရုတ်တရက် သန့်ရှင်းရေးလုပ်ရန် မည်သူက ပိုဖြစ်နိုင်မည်နည်း။",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "ဆန့်ကျင်ဘက်မှန်သည်ဆိုပါက မည်သူက လုံးလုံးသတိဝီရိယရှိသူဟု ဆိုနိုင်မည်နည်း။",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "အငြင်းအခုံတစ်ခုတွင် မည်သူက ပထမဦးစားပေးရမည်နည်း။",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "အရက်သောက်တဲ့ဂိမ်းမှာ ဘယ်သူက လှည့်စားနိုင်ခြေပိုများလဲ။",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "ဘူဖေးကို ဝင်စီးပြီး အစားအသောက်ကို အိမ်မှာ တိတ်တဆိတ်ယူဖို့ ဘယ်သူက ပိုဖြစ်နိုင်မလဲ။",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "၎င်းတို့၏ ဇာတ်လမ်းတွင် ညနေခင်း၏ အရှက်ရဆုံး ဓာတ်ပုံကို မည်သူက ပိုတင်နိုင်မည်နည်း။",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "သူတို့ရဲ့ကိုယ်ပိုင်သီချင်းကို တောင်းဆိုဖို့အတွက် DJ ကို ဘယ်သူက ပိုပြီး စိတ်အနှောင့်အယှက်ဖြစ်စေမလဲ။",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "သော့ပိတ်သီချင်းတွင် သီချင်းစာသားကို မည်သူက ပို၍ သီဆိုနိုင်သနည်း၊ သို့သော် ယုံကြည်ချက်ဖြင့်။",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "မီနူးတွင် ဈေးအကြီးဆုံးအချိုရည်ကို ဘယ်သူက မှာပြီး နောင်တရနိုင်မည်နည်း။",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "ဆူညံသံနှင့် ပတ်သက်၍ ညည်းညူပါက အိမ်နီးချင်းများကို မည်သူက ပိုဖိတ်ကြားနိုင်မည်နည်း။",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "ပါတီဂိမ်းများ (Beer Pong ကဲ့သို့) ကို မည်သူက အလေးအနက်ထားမည်နည်း။",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "VIP ဝင်ခွင့်ရရှိရန် bouncers များနှင့် မိတ်ဖွဲ့ရန် အလားအလာ မည်သူနည်း။",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "အလိုလို ကာရာအိုကေ တိုက်ပွဲကို ဘယ်သူက ပိုဖြစ်နိုင်မလဲ။",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "ပုလင်းဖောက်စက်မသုံးဘဲ ပုလင်းကိုဖွင့်နိုင်ခြေက ဘယ်သူလဲ။",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "ဘယ်သူကမှ လုံးဝမမေးပေမယ့် မိန့်ခွန်းပြောဖို့ အလားအလာ ပိုရှိမှာလား။",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "ရေချိုးခန်းထဲမှာ ဆယ်လ်ဖီရိုက်ရင် ဘယ်သူက ပိုဖြစ်နိုင်မလဲ။",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "ရှက်စရာကောင်းတဲ့ အကဖျော်ဖြေပွဲကို ဘယ်သူက ပိုပြီး ဂုဏ်ပြုနိုင်မလဲ။",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "ပါတီပြီးသွားတဲ့အခါ ဘယ်သူက ပါတနာဟောင်းကို ခေါ်နိုင်မလဲ။",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "ထူးဆန်းသောဧည့်သည်ကို မတော်တဆစော်ကားရန် မည်သူက ပိုဖြစ်နိုင်မည်နည်း။",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "နှုတ်မဆက်ဘဲ ပါတီကို တိတ်တဆိတ် ထွက်သွားဖို့ ဘယ်သူက ပိုဖြစ်နိုင်မလဲ။",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "ဧည့်သည်တွေနဲ့ စကားပြောတာထက် အိမ်ရှင်ရဲ့ အိမ်မွေးတိရစ္ဆာန်နဲ့ ကစားတာက ဘယ်သူက ပိုကြိုက်လဲ။",
    "Wer würde eher spontan eine Reise buchen?" to "ခရီးစဉ်ကို အလိုလို ဘွတ်ကင်လုပ်ဖို့ ဘယ်သူက ပိုဖြစ်နိုင်မလဲ။",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "မီးဖိုချောင်ထဲမှာ နာရီပေါင်းများစွာ လေးလေးနက်နက် စကားပြောဆိုဖို့ ဘယ်သူက ပိုဖြစ်နိုင်မလဲ။",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "အခြားသူ၏အရက်ကို မတော်တဆသောက်မိပါက မည်သူကပိုများသနည်း။",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "ဈေးကြီးတဲ့ ပန်းအိုးကို မတော်တဆ ခေါက်မိရင် ဘယ်သူက ပိုဖြစ်နိုင်မလဲ။",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "ရှုပ်ထွေးတဲ့ ကော့တေးကို ကိုယ်တိုင်ရောစပ်ပြီး စိတ်ဆင်းရဲစွာ ပျက်ကွက်ဖို့ ဘယ်သူက ပိုဖြစ်နိုင်မလဲ။",
    "Wer würde eher zu spät kommen?" to "ဘယ်သူက ပိုနောက်ကျနိုင်လဲ။",
    "Wer würde eher?" to "ဘယ်သူက ပိုကြိုက်လဲ။",
    "Wer übernimmt die tägliche Versorgung?" to "နေ့စဥ်စောင့်ရှောက်မှုကို ဘယ်သူက ဂရုစိုက်တာလဲ။",
    "Werde so akzeptiert, wie du bist" to "သင်ကဲ့သို့ လက်ခံပါ။",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "ကလေး/ကလေးများအတွက် အချိန်လုံလောက်ပါ့မလား။ ⏳",
    "Whirlpool" to "ရေပူကန်",
    "White Chocolate" to "ချောကလက်အဖြူ",
    "Widgets" to "ဝစ်ဂျက်များ",
    "Wie fühlst du dich am meisten geliebt?" to "အချစ်ဆုံးလို့ ဘယ်လိုခံစားရလဲ။",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "မတူညီသော ၀င်ငွေများကို ကျွန်ုပ်တို့ မည်သို့ကိုင်တွယ်ဖြေရှင်းမည်နည်း။",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "သင့်လက်တွဲဖော်သည် သင်နှင့်လိင်ဆက်ဆံရန် အကောင်းဆုံးနည်းလမ်းမှာ အဘယ်နည်း။",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "သင့်လက်တွဲဖော်သည် သင့်အတွက် ပို၍ပင် ပိုမိုကောင်းမွန်သော လုပ်ဖော်ကိုင်ဖက် ဖြစ်လာနိုင်မည်နည်း။",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "အဆိုပြုချက်ပြီးနောက် မည်မျှကြာအောင် အခြားသူများနှင့် ဂုဏ်ပြုလိုပါသလဲ။",
    "Wie lange wollen wir dort mindestens bleiben?" to "အနည်းဆုံး ဘယ်လောက်ကြာကြာ နေချင်လဲ။",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "ဆန္ဒများအကြောင်းပြောရန် မည်မျှလွယ်ကူသနည်း။",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "ငါတို့ရဲ့အနာဂတ်ကို မင်းဘယ်လိုမြင်စေချင်တာလဲ။",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "သင့်အိမ်မှာ ပြီးပြည့်စုံတဲ့ တနင်္ဂနွေနေ့က ဘယ်လိုပုံစံလဲ။",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "လိင်ဆက်ဆံစဉ် ညစ်ညမ်းစကားပြောဆိုခြင်းကို သင်မည်ကဲ့သို့ခံစားရသနည်း။",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "ကျွန်ုပ်တို့ လက်တွေ့ကျကျ တတ်နိုင်သော ခရက်ဒစ်မည်မျှ တတ်နိုင်မည်နည်း။",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "ငါတို့ အချိန်ဘယ်လောက်ခြားချင်လဲ။",
    "Wie viel wollen wir insgesamt ausgeben?" to "စုစုပေါင်း ဘယ်လောက်သုံးချင်လဲ။",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "ကလေးမွေးဖွားပြီးသည်နှင့် ကျွန်ုပ်တို့၏ဆက်ဆံရေးအတွက် အချိန်ကို မည်သို့ရှာဖွေမည်နည်း။",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "အခိုက်အတန့်ကို ဖမ်းဆုပ်ထားဖို့က မင်းအတွက် ဘယ်လောက်အရေးကြီးလဲ။",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "အပလီကေးရှင်းသည် သင့်ဝါသနာ သို့မဟုတ် စိတ်ဝင်စားမှုများကို ရောင်ပြန်ဟပ်ရန် မည်မျှအရေးကြီးသနည်း။",
    "Wie würdest du sie/ihn nennen?" to "သူ့ကို ဘယ်လိုခေါ်မလဲ။",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "လိင်အပြင်ဘက်မှာ ချစ်ခင်မှုပြဖို့ သင်အကြိုက်ဆုံးနည်းလမ်းက ဘာလဲ။",
    "Wildblumen" to "တောရိုင်းပန်းများ",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "မိန်းကလေးလား ယောက်ျားလေးလိုချင်လား။ 👶",
    "Wintergarten" to "ဆောင်းရာသီပန်းခြံ",
    "Winterhochzeit" to "ဆောင်းရာသီ မင်္ဂလာပွဲ",
    "Wir bestellen einfach beides" to "နှစ်ခုလုံးကို မှာလိုက်ရုံပါပဲ။",
    "Wir brauchen ewig" to "၎င်းသည် ကျွန်ုပ်တို့ကို ထာဝရ ယူဆောင်သွားပါသည်။",
    "Wir einigen uns nie" to "ကျွန်တော်တို့ ဘယ်တော့မှ သဘောမတူဘူး။",
    "Wir entscheiden es gemeinsam" to "အတူတူ ဆုံးဖြတ်ခဲ့ကြတယ်။",
    "Wir treffen uns in der Mitte" to "အလယ်မှာဆုံတယ်။",
    "Wir wechseln uns ab" to "ငါတို့ အလှည့်ကျ",
    "Wird stressig" to "စိတ်ဖိစီးမှုများလာသည်။",
    "Wobei lachst du am meisten?" to "ဘာက မင်းကို အရယ်ရဆုံး ဖြစ်စေတာလဲ။",
    "Wofür sparen wir gemeinsam?" to "ငါတို့အတူတကွဘာတွေစုနေကြတာလဲ။",
    "Wohnzimmer" to "ဧည့်ခန်း",
    "Woran erinnerst du dich am lebhaftesten?" to "ဘာကို မှတ်မှတ်ရရ အမှတ်မိဆုံးလဲ။",
    "Worauf freust du dich bei uns am meisten?" to "မင်းက ငါတို့အတွက် ဘာကို စောင့်မျှော်နေတာလဲ။",
    "Worte/Komplimente" to "စကားလုံးများ/ ချီးကျူးစကားများ",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "ငါတို့ဆက်ဆံရေးမှာ မင်းအကြောက်ဆုံးက ဘာလဲ။",
    "Wünsche? z.B. günstig, draußen" to "ဆန္ဒများလား။ ဥပမာ အပြင်မှာ ဈေးပေါတယ်။",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "အားလပ်ရက် (ခရီးသွားခြင်းပါ၀င်သည်) ကို အဆိုပြုလိုပါသလား။",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube Music",
    "Zeichne für mich" to "ကျွန်ုပ်အတွက် ဆွဲပါ။",
    "Zeichne mich als Tier — welches wäre ich?" to "ငါ့ကို တိရိစ္ဆာန်အဖြစ်ဆွဲပါ - ငါဘယ်ကောင်ဖြစ်မလဲ။",
    "Zeichne unser Gefühl zueinander als Symbol." to "ကျွန်ုပ်တို့၏ခံစားချက်များကို သင်္ကေတအဖြစ် အချင်းချင်းဆွဲပါ။",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "ကျွန်ုပ်တို့၏အိပ်မက်အိမ်ကို တစ်ကြောင်းတည်းဆွဲပါ။ အထူးခြားဆုံးအရာကဘာလဲ။",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "ကျွန်ုပ်တို့၏ပထမဆုံးရက်စွဲကိုဆွဲပါ - ပုံတွင်သေချာပေါက်ဘာရှိရန်လိုအပ်သနည်း။",
    "Zeichnen" to "ဆွဲပါ။",
    "Zeit füreinander" to "အချင်းချင်းအတွက် အချိန်",
    "Zeit, wenn das Baby schläft" to "ကလေးအိပ်ချိန်",
    "Zelten gehen" to "စခန်းချသွားပါ။",
    "Zitrone" to "သံပုရာ",
    "Zu Hause, gemütlich und privat" to "အိမ်မှာ၊ အေးအေးချမ်းချမ်းနဲ့ သီးသန့်",
    "Zu einem Picknick gehen" to "ပျော်ပွဲစားသွားမယ်။",
    "Zu einem ausgefallenen Abendessen gehen" to "ဖန်စီညစာစားပွဲကို သွားမယ်။",
    "Zu zweit reisen" to "စုံတွဲအဖြစ် ခရီးသွားပါ။",
    "Zuhause & Alltag" to "အိမ်နှင့်နေ့စဉ်ဘဝ",
    "Zuhören" to "နားထောင်ပါ။",
    "Zurück" to "နောက်ပြန်",
    "Zusammen seit" to "ကတည်းက အတူတူ",
    "Zusammen seit (TT.MM.JJJJ)" to "(DD.MM.YYYY) ကတည်းက အတူတူ",
    "Zusammenziehen" to "စာချုပ်",
    "Zustimmen oder Ablehnen" to "သဘောတူသည် သို့မဟုတ် သဘောမတူ",
    "Zwei Kreise, die sich überschneiden" to "ထပ်နေသော စက်ဝိုင်းနှစ်ခု",
    "Zwei Stühle davor" to "သူ့ရှေ့မှာ ကုလားထိုင်နှစ်လုံး",
    "Zärtlich sein" to "နူးညံ့သိမ်မွေ့ပါစေ။",
    "Öfter als ich zugebe" to "ကျွန်တော် ဝန်ခံသည်ထက် အကြိမ်ရေ ပိုများသည်။",
    "Über 100€/Monat" to "100€/လကျော်",
    "Über 2000 im Monat" to "တစ်လ 2000 ကျော်",
    "Über mich selbst" to "ကိုယ့်အကြောင်း",
    "Übernehmen" to "လျှောက်ထားပါ။",
    "Überraschend" to "အံ့သြစရာ",
    "Überraschung" to "အံ့အားသင့်စရာ",
    "Überspringen" to "ကျော်ပါ။",
    "Übertrieben und großartig" to "ထိပ်တန်းနှင့် အံမခန်း",
    "✎ Tippe, um zu antworten" to "✎ အကြောင်းပြန်ရန် တို့ပါ။",
    "✨ GFK-Brücke" to "✨ GRP တံတား",
)

internal fun localizeBurmeseDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_BURMESE_CONTENT)
