package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_CHINESE_TRADITIONAL_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5年",
    "1000 - 1500 im Monat" to "每月 1000 - 1500",
    "1000 bis 3000" to "1000 至 3000",
    "1500 - 2000 im Monat" to "每月 1500 - 2000",
    "3000 bis 5000" to "3000至5000",
    "5-10 Jahre" to "5-10年",
    "50-100€/Monat" to "50-100歐元/月",
    "Ab 100€" to "100 歐元起",
    "Ab 500€" to "500 歐元起",
    "Ab 50€" to "50 歐元起",
    "Ab und zu" to "時不時",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "在購買之前我們談論了多少？",
    "Abbrechen" to "取消",
    "Abenteuer" to "冒險",
    "Adidas" to "阿迪達斯",
    "Aktivitäten" to "活動",
    "Alle" to "全部",
    "Alle Pakete" to "所有套餐",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "失去除了你最好的朋友之外的所有朋友",
    "Alle intimen Momente selbst initiieren" to "所有親密時刻都由你自己發起",
    "Alles davon" to "所有這一切",
    "Alles, was noch kommt" to "即將到來的一切",
    "Alltagsroutine" to "日常生活",
    "Alltägliche Berührungen" to "日常接觸",
    "Altbau mit Charme" to "古建築韻味十足",
    "Am Strand" to "在海灘上",
    "Am liebsten alles zusammen" to "最好一切都在一起",
    "Am selben Tag mit Freunden/Familie" to "與朋友/家人同一天",
    "Amazon" to "亞馬遜",
    "Amsterdam" to "阿姆斯特丹",
    "Amsterdam, Niederlande" to "荷蘭阿姆斯特丹",
    "An das Gefühl" to "的感覺",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "在有許多觀眾的公共場所",
    "An einen Geruch" to "有一種氣味",
    "An einen Song" to "一首歌曲",
    "An etwas, das ich gesagt habe" to "我說過的話",
    "Analyse starten" to "開始分析",
    "Analysiere eure Muster..." to "分析你的模式...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "根据 Gottman 和 GFK 分析您的答案和聊天。",
    "Ananas auf der Pizza schmeckt köstlich." to "披薩上的鳳梨味道鮮美。",
    "Android" to "安卓",
    "Antwort mit einem Foto" to "用照片回复",
    "Antwortähnlichkeit" to "答案相似度",
    "App-Sprache auswählen" to "選擇 App 語言",
    "Auf eine Bootsparty gehen" to "去參加船上派對",
    "Aufmerksamkeit" to "注意力",
    "Aufräumen und Projekte angehen" to "清理和解決項目",
    "Aufwärmen" to "熱身",
    "Aufwärmen: Einander kennenlernen" to "暖身：互相了解",
    "Aus dem Urlaub" to "假期開始",
    "Ausgefallener Name" to "好聽的名字",
    "Ausschlafen und faulenzen" to "睡個懶覺",
    "Ausschlafen und nichts tun" to "睡覺什麼都不做",
    "Aussehen" to "外貌",
    "Auto" to "自動",
    "Außenkamin" to "戶外壁爐",
    "BEANTWORTE" to "回答",
    "Bali" to "峇里島",
    "Bali, Indonesien" to "印尼峇裡島",
    "Banane" to "香蕉",
    "Beantwortet" to "已回答",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "同時回答問題 - 直到你們都完成後才能看到答案。",
    "Beantwortete Fragen" to "已回答的問題",
    "Bearbeiten" to "編輯",
    "Bei Insider-Witzen" to "內部笑話",
    "Bei Memes" to "關於迷因",
    "Bei einer spontanen Berührung" to "自發性觸摸時",
    "Beide" to "兩者",
    "Beide gleich" to "兩者都一樣",
    "Beide zusammen" to "兩者在一起",
    "Beide, aber wir tun so als ob nicht" to "兩者都有，但我們假裝沒有",
    "Beides" to "兩者",
    "Beides wäre schlimm" to "兩者都不好",
    "Beim Einschlafen nebeneinander" to "挨著睡著了",
    "Beim Reden" to "說話時",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "著名的旅遊勝地總是讓人失望。",
    "Beschreibe unser Sexleben mit einem Emoji." to "用表情符號描述我們的性生活。",
    "Besser kommunizieren" to "更好地溝通",
    "Bessere Lage" to "更好的位置",
    "Bestellen" to "訂單",
    "Besuchte Länder" to "造訪過的國家",
    "Besuchte Städte" to "造訪過的城市",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "你喜歡奢侈的求婚還是微妙的求婚？",
    "Beziehung" to "關係",
    "Bibliothek" to "圖書館",
    "Bin manchmal unsicher" to "我有時缺乏安全感",
    "Bist du ein Videospiel-Guru?" to "您是電玩大師嗎？",
    "Blumenwiese" to "花草甸",
    "Bunte Blumenwiese" to "七彩花草甸",
    "Burger" to "漢堡",
    "Burger King" to "漢堡王",
    "Chat" to "聊天",
    "Coca-Cola" to "可口可樂",
    "Cookie Dough" to "餅乾麵團",
    "Dachgarten mit Lounge" to "附休息室的屋頂花園",
    "Dachterrasse" to "屋頂露台",
    "Das Wetter an dem Tag" to "當天的天氣",
    "Das erste Selfie" to "第一張自拍",
    "Das meiste weiß ich" to "我知道大部分",
    "Das oder das?" to "這個還是那個？",
    "Das tägliche Leben" to "日常生活",
    "Dass Zusagen gehalten werden" to "信守諾言",
    "Dass alles meinen Stil hat" to "一切都有我的風格",
    "Dass ich alles erzählen kann" to "我可以告訴一切",
    "Dass ich mich nicht sorgen muss" to "我不用担心",
    "Dass wir ungestört sind" to "我们不受打扰",
    "Dein Name" to "你的名字",
    "Deine Antwort..." to "你的答案...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "您的答案已保存。合作夥伴完成包後，兩個答案將同時顯示。",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "您的答案已保存。一旦 \${profile.partnerName} 結束包，兩個響應將同時可見。",
    "Deine Beziehung abenteuerlich und spontan machen" to "讓你們的關係充滿冒險和自發性",
    "Deine Beziehung stabil und sicher machen" to "让你们的关系稳定、安全",
    "Deine eigene Antwort" to "你自己的答案",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "最好與您的伴侶分享您最深的秘密",
    "Deinen besten Freund verlieren" to "失去你最好的朋友",
    "Denke an dich" to "想想你自己",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "同一部電影看兩次是浪費時間。",
    "Der Blick nach draußen" to "外面的景色",
    "Der Garten" to "花園",
    "Der Ort" to "這個地方",
    "Der Ring und die Geste" to "戒指與手勢",
    "Der perfekte Heiratsantrag" to "完美求婚",
    "Derjenige sein, der umarmt wird" to "成為被擁抱的人",
    "Deutsch" to "德語",
    "Diamant" to "鑽石",
    "Diamanten im Band" to "戒指中的鑽石",
    "Die Distanz" to "距離",
    "Die Feiertage mit der Familie deines Partners verbringen" to "與伴侶的家人一起度過假期",
    "Die Gemütlichkeit und Ruhe" to "舒適與平靜",
    "Die Menschen, die darin wohnen" to "住在裡面的人",
    "Die Umgebung und Atmosphäre" to "環境氛圍",
    "Die Worte und Emotionen" to "言語與情感",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "終極娛樂問答挑戰",
    "Diejenige sein, die umarmt" to "成為擁抱的人",
    "Direkt ansprechen" to "直接定址",
    "Diskussion" to "討論",
    "Diskutiere vor dem Kinderkriegen" to "生孩子前討論",
    "Diskutiert eure Antworten" to "討論你的答案",
    "Disney" to "迪士尼",
    "Doch, schon mal" to "是的，是的",
    "Draußen mit der Natur als Kulisse" to "室外以自然為背景",
    "Drei-Stein-Ring" to "三石戒指",
    "Du bist dran" to "輪到你了",
    "Du fehlst mir" to "我想你",
    "Dubai" to "杜拜",
    "Dubai, VAE" to "阿聯酋杜拜",
    "Dunkles Design" to "黑暗主題",
    "Durch Berührung" to "透過觸摸",
    "Durch Worte" to "透過文字",
    "Durch Zeit zu zweit" to "一起度過時光",
    "Durch kleine Gesten" to "透過小手勢",
    "Durchgeplant" to "精心策劃",
    "ERGEBNISSE" to "結果",
    "Egal, Hauptsache gesund" to "沒關係，健康最​​重要",
    "Ehepaar Leben" to "夫妻生活",
    "Eher knapp" to "相當接近",
    "Eher nicht" to "而不是",
    "Eher schwer" to "比較困難",
    "Eher schwierig" to "比較困難",
    "Eher zu" to "還不如",
    "Eifersucht ist ein Zeichen von Liebe." to "嫉妒是愛的標誌。",
    "Eigenes Gemüsebeet" to "自己的菜地",
    "Ein Abenteuer in einer neuen Stadt" to "新城市的冒險",
    "Ein Anker" to "錨",
    "Ein Balkon oder Garten" to "陽台或花園",
    "Ein Filmabend" to "電影之夜",
    "Ein Harmony-Meilenstein eurer Liebe." to "你們愛情中的和諧里程碑。",
    "Ein Herz" to "一顆心",
    "Ein Herz an der Tür" to "一顆心在門口",
    "Ein Jahr lang eine Fernbeziehung führen" to "異地戀一年",
    "Ein Kindheitsessen" to "童年的一頓飯",
    "Ein Live-Musik-Konzert besuchen" to "參加現場音樂會",
    "Ein Museum besuchen" to "參觀博物館",
    "Ein Spieleabend" to "遊戲之夜",
    "Ein Spieleabend mit Freunden" to "與朋友一起玩遊戲之夜",
    "Ein Urlaubsfoto" to "度假照片",
    "Ein aktives Abenteuer" to "積極的冒險",
    "Ein entspannender Spa-Tag" to "輕鬆的水療日",
    "Ein ganz normaler Alltagstag" to "完全正常的一天",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "雷雨天氣，在家裡度過一個舒適的夜晚",
    "Ein gemütliches Date drinnen" to "舒適的室內約會",
    "Ein lustiges Bild" to "搞笑圖片",
    "Ein paar Handyfotos reichen" to "幾張手機照片就夠了",
    "Ein paar Stunden" to "幾個小時",
    "Ein paar kulturelle Anklänge sind okay" to "一些文化參考是可以的",
    "Ein romantischer Abend" to "一個浪漫的夜晚",
    "Ein romantisches Abendessen bei Kerzenlicht" to "浪漫的燭光晚餐",
    "Ein romantisches Bild" to "浪漫的形象",
    "Ein romantisches Picknick an einem schönen Ort" to "在美麗的地方來一場浪漫的野餐",
    "Ein schwerer Moment, den wir geschafft haben" to "我們度過了一個艱難的時刻",
    "Ein tolles Date im Freien unter dem Mondlicht" to "月光下的戶外美好約會",
    "Ein ungewöhnliches Gericht" to "一道不尋常的菜餚",
    "Ein zufälliger Schnappschuss" to "隨機快照",
    "Einander kennenlernen" to "互相了解",
    "Eine Autoreise" to "公路旅行",
    "Eine Brücke" to "一座橋",
    "Eine Date-Nacht unter den Sternen" to "星空下的約會之夜",
    "Eine Million Dollar gewinnen" to "贏得一百萬美元",
    "Eine Million Dollar verdienen" to "賺一百萬美元",
    "Eine Nacht in einem Club" to "在俱樂部的夜晚",
    "Eine Schokoladenverkostung" to "巧克力品嚐",
    "Eine Wanderung mit Panoramablick machen" to "徒步欣賞全景",
    "Eine Weinverkostung" to "品酒會",
    "Eine gemeinsame Reise" to "一起旅行",
    "Eine gemütliche Nacht zu Hause" to "在家度過一個舒適的夜晚",
    "Eine neue Sprache zu lernen ist einfach." to "學習一門新語言很容易。",
    "Einen Film anschauen" to "看電影",
    "Einen Monat lang überhaupt nicht miteinander reden" to "一個月沒有互相說話",
    "Einen Tanzkurs besuchen" to "參加舞蹈課",
    "Einen Vergnügungspark erkunden" to "探索遊樂園",
    "Einen Wellness-Tag" to "健康日",
    "Einen sehr emotionalen Partner haben" to "有一個非常情緒化的伴侶",
    "Einen sehr logischen Partner haben" to "擁有一個非常合乎邏輯的合作夥伴",
    "Einer zahlt alles" to "一個人付出一切",
    "Einfach mehr Alltag" to "更簡單的日常生活",
    "Einfach nebeneinander sein" to "彼此相鄰",
    "Einfach und intim" to "簡單又貼心",
    "Einige Dinge für dich behalten" to "有些事留給自己",
    "Einmal" to "一次",
    "Eins, das nur wir kennen" to "只有我們知道的一個",
    "Englisch" to "英語",
    "Entspannte Hängematte" to "輕鬆的吊床",
    "Entspannung" to "鬆弛",
    "Erdbeere" to "草莓",
    "Erfolgreich" to "成功的",
    "Ergebnisse" to "結果",
    "Erst bei sehr großen Summen" to "僅限巨額金額",
    "Erst nur enge Freunde/Familie" to "起初只有親密的朋友/家人",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "當我的伴侶花很長時間回覆訊息時，我會很惱火。",
    "Essen & Genuss" to "美食與享受",
    "Essensvorlieben" to "食物偏好",
    "Etwa eine Woche später, erst mal nur wir" to "大約一週後，一開始只有我們",
    "Etwas Neues ausprobieren" to "嘗試新事物",
    "Etwas ganz anderes" to "完全不同的東西",
    "Etwas sehr Scharfes" to "非常鋒利的東西",
    "Etwas, das ich selbst gern erfinde" to "我喜歡自己發明的東西",
    "Etwas, eine kleine Note wäre schön" to "一些東西，一點點觸摸會很好",
    "Familie" to "家庭",
    "Familie/Freunde" to "家人/朋友",
    "Familienmensch" to "有家室的男人",
    "Farbedelstein" to "有色寶石",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "電視廣告有時很有趣。",
    "Fertig" to "準備好",
    "Fertig!" to "完全的！",
    "Feste Date-Nights" to "固定約會之夜",
    "Feuerstelle" to "火坑",
    "Filigran & schlicht" to "花絲和簡單",
    "Filme/Serien" to "電影/連續劇",
    "Formuliere um..." to "改寫...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "以非暴力方式重新表述您的草稿：觀察、感受、需要、請求。",
    "Frage hinzufügen" to "新增問題",
    "Fragen & Spiele" to "問題與遊戲",
    "Fragen für jede Gelegenheit" to "適合各種場合的問題",
    "Freizeitpark" to "遊樂園",
    "Freunde treffen" to "認識朋友",
    "Freundschaften mit Ex-Partnern sind okay." to "與前任的友誼還可以。",
    "Früh aufstehen" to "為了早起",
    "Fußbodenheizung" to "地暖",
    "Führen wir getrennte oder gemeinsame Konten?" to "我們有獨立帳戶還是聯名帳戶？",
    "Für dich empfohlen" to "為您推薦",
    "Für die Zukunft" to "為了未來",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "未找到與此搜尋相符的問題或遊戲。",
    "Für immer" to "永遠",
    "Fürsorglichkeit" to "關懷",
    "GFK-Brücke" to "玻璃鋼橋",
    "Galerie" to "畫廊",
    "Gar nicht, der Moment gehört uns" to "不，這一刻是我們的",
    "Gar nichts tun" to "什麼都不做",
    "Geduld" to "耐心",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "一大早去看看日出",
    "Geht so" to "它的運作原理是這樣的",
    "Geister existieren wirklich." to "鬼真的存在。",
    "Gelassenheit" to "寧靜",
    "Gelbgold" to "黃金",
    "Geld & Finanzen" to "貨幣與金融",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "一起環遊世界，探索新文化和美食",
    "Gemeinsam ein Lego bauen" to "一起搭建樂高",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "在廚房一起嘗試新食譜",
    "Gemeinsame Konten" to "共享帳戶",
    "Gemeinsame Nächte" to "一起度過的夜晚",
    "Gemeinsame Tage" to "在一起的日子",
    "Gemischt" to "混合",
    "Gemüsebeet" to "蔬菜地",
    "Gemütliche Feuerstelle" to "舒適的壁爐",
    "Gesprächsanreger" to "對話開始",
    "Getrennte Konten" to "獨立帳戶",
    "Getrennte Urlaube tun einer Beziehung gut." to "單獨的假期有利於戀愛關係。",
    "Gewächshaus" to "溫室",
    "Glasfassade" to "玻璃帷幕牆",
    "Gleichgültigkeit" to "冷漠",
    "Glücklich und frei" to "快樂自由",
    "Gourmet Eis-Sorten" to "美味冰淇淋品種",
    "Gravur innen" to "內部雕刻",
    "Grillplatz" to "燒烤區",
    "Groß & üppig" to "又大又鬱鬱蔥蔥",
    "Große Familie" to "大家庭",
    "Große Feier" to "盛大的慶祝活動",
    "Große Fenster" to "大窗戶",
    "Große Fensterfront" to "大窗前",
    "Großer Außenpool" to "大型戶外泳池",
    "Großer Garten" to "大花園",
    "Großer Stein" to "大石頭",
    "Größere Küche" to "更大的廚房",
    "Gutes Essen" to "美食",
    "Habe ich" to "我有",
    "Habe ich noch nie" to "我從來沒有",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "你有沒有發現任何令人驚訝的差異？談談為什麼您更喜歡某些選項！",
    "Haus am See" to "湖邊的房子",
    "Haus/Wohnung" to "獨立屋/公寓",
    "Hazelnut" to "榛子",
    "Heimkino" to "家庭劇院",
    "Herzhaft" to "爽朗",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "目前這裡沒有任何內容。 \n更改篩選器或選擇其他主題。",
    "Hilfe im Alltag" to "日常生活中的幫助",
    "Himbeere" to "覆盆子",
    "Hinzufügen" to "添加",
    "Hobbys" to "興趣嗜好",
    "Hochzeitssträuße" to "婚禮花束",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "霍格華茲學院的驕傲：你屬於哪裡？",
    "Home" to "家",
    "Hot Tub" to "熱水浴缸",
    "Humor" to "幽默",
    "Hund" to "狗",
    "Hängematte" to "吊床",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "您想要一封書面信作為申請的一部分嗎？",
    "IKEA" to "IKEA",
    "Ich" to "我",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "比起去電影院，我更喜歡在公園裡浪漫散步。",
    "Ich bin noch nie in einem Kino eingeschlafen." to "我從來沒有在電影院睡著過。",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "我喜歡和我的伴侶一起發現新的嗜好或活動。",
    "Ich finde eine Alternative" to "我會找到替代方案",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "我喜歡和我的伴侶一起嘗試新餐廳，而不是總是去同一個地方。",
    "Ich habe noch nie" to "我從來沒有",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "我從來不害怕過山車，但無論如何我還是上了它。",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "我從來沒有買過快速通票，因為我沒有耐心。",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "我從未取消過待在家裡看電視節目的計劃。",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "我從未等到霍格華茲的來信。",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "我從來沒有說過史萊哲林其實沒有那麼邪惡。",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "我從來沒有說過我對迪士尼電影來說太老了（並且偷偷地喜歡它們）。",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "我從來沒有在《瑪利歐賽車》中故意用藍色坦克擊落過某人。",
    "Ich habe noch nie bei einem Disney-Film geweint." to "我從來沒有在迪士尼電影中哭過。",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "我看恐怖電影時從來沒有遮住眼睛。",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "我從來沒有忘記保存遊戲並損失了幾個小時的進度。",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "我從來沒有在尷尬的場景中離開過房間（畏縮因素）。",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "我從未在拍攝過山車照片時做過有趣的姿勢。",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "我從來沒有玩到深夜，然後後悔第二天我有多累。",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "我從來沒有用谷歌搜尋過電影的結局，因為我等不及了。",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "我從來沒有感覺自己站在電影佈景上。",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "我從來沒有跳過我最喜歡的系列的介紹。",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "我從未分享過其他人的 Netflix 密碼。",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "我從來沒有在工作或學習時聽過遊戲的配樂。",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "當我輸了的時候，我從來沒有責怪控制器。",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "我從來沒有因為憤怒而扔掉過鍵盤或控制器。",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "我從來沒有忘記把濕衣服放進洗衣機裡幾天。",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "我從來沒有在遊戲中花過真錢購買化妝品。",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "我從來沒有在國外開過車。",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "我從來沒有在洗澡時大聲唱過迪士尼歌曲。",
    "Ich habe noch nie ein Elektroauto gefahren." to "我從來沒有開過電動車。",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "我從來沒有和公園吉祥物合過影。",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "我從未以霍格華茲角色的名字命名過寵物。",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "我從來沒有在電影院裡掉過爆米花，但仍然把牠吃了。",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "我在日常生活中從未使用過《星際大戰》尤達大師的名言。",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "我從來沒有在主題樂園買過價格過高的紀念品。",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "我從來沒有推薦過別人覺得糟糕的電影。",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "我從來沒有在半夜看過奧斯卡現場直播。",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "我從來沒有因為上一季太糟糕而取消過一個系列。",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "我從來沒有在一天內一口氣看完一整季的劇集。",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "我從來沒有在第一次嘗試時就擊敗過 Boss，感覺自己像個神。",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "我從來沒有發現過比英雄更酷的反派。",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "我從未在自己的玩具中認出玩具總動員角色。",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "我從未在角色扮演遊戲中創造過與我一模一樣的角色。",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "我從來沒有在主題樂園吃過西班牙油條。",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "我從來沒有連續看過三次迪士尼電影。",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "我整整一週都沒有聽過迪士尼朗朗上口的曲子。",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "我從來沒有因為某個演員而看過一部電影。",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "我從來沒有連續幾個小時重複聽過電影配樂。",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "我從來沒有透露過電影劇透，立刻就後悔了。",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "我從未找到會說另一種母語的朋友。",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "我从未有过搬到另一个国家的朋友。",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "我從來沒有在聖誕節參加過哈利波特電影馬拉松。",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "我從來沒有看過漫威電影直到最後，只是因為片尾的場景。",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "我從來沒有故意惹惱 NPC（非玩家角色）。",
    "Ich habe noch nie einen Nachtzug genommen." to "我从来没有坐过夜车。",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "我從未參加過線上測驗來找出我的霍格華茲學院。",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "我從未因為沒有獲得足夠的讚而刪除社群媒體貼文。",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "我從來沒有把主題樂園裡的一天稱為一年中最好的一天。",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "我從來沒有去過主題樂園，從早到晚都待在那裡。",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "我從來沒有完全著迷於變形金剛或漫威遊樂設施。",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "我從來沒有因為憤怒而退出遊戲。",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "我從來沒有讀過任何一本哈利波特的大書。",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "我從來沒有對系列中我最喜歡的角色讚不絕口。",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "我從來沒有夢想過打魁地奇。",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "我從來沒有偷偷用谷歌搜尋過如何解決困難關卡。",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "我從來沒有暗自希望我的寵物能像迪士尼一樣說話。",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "我從未移除《模擬市民》中的池首領。",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "我從未在 3D 模擬器騎行中迷失方向。",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "我從未參加過大學運動隊。",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "我從來沒有為一個景點排隊等待超過兩個小時。",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "我從來沒有在水上遊樂設施上弄濕過我的貴重物品。",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "我從來沒有和朋友爭論過哪棟房子最好。",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "我從來沒有假裝擁有像艾爾莎一樣的魔力。",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "我從來沒有笑得太厲害以至於錯過了電影中的重要場景。",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "我從來沒有感受到如此強烈的腎上腺素，以至於我立即想再次騎行。",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "我從未嘗試過與白雪公主這樣的動物一起唱歌。",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "我從來沒有夢想過去迪士尼樂園旅行。",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "我從來沒有夢想過乘坐侏羅紀公園的水上遊樂設施。",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "我從來沒有因為遊戲中的跳躍驚嚇而大聲尖叫過。",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "我從來沒有因為電視節目的結局而哭泣。",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "我從來沒有...取消過待在家裡的約會。",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "我從來沒有…將一則訊息改寫過 10 次。",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "我從來沒有…偷偷看過我伴侶的手機。",
    "Ich habe noch nie!" to "我從來沒有！",
    "Ich habe!" to "我有！",
    "Ich lache viel mit meinem Partner." to "我和我的伴侶常常笑。",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "我喜歡了解伴侶的嗜好和興趣。",
    "Ich liebe es" to "我喜歡",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "我喜歡和我的伴侶一起看我們以前都沒看過的電影。",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "我喜歡與我的伴侶分享我最喜歡的音樂。",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "我從來沒有需要跑去趕轉機航班。",
    "Ich plane gerne Dates mit meinem Partner." to "我喜歡和我的伴侶一起計劃約會。",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "即使我很忙，我也會優先考慮與伴侶共度時光。",
    "Ich schreibe meinem Partner jeden Tag." to "我每天都會傳簡訊給我的伴侶。",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "我喜歡與我的伴侶分享表情包和笑話。",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "我喜歡與我的伴侶分享一天中的所有細節。",
    "Ich würde es nie tun" to "我永遠不會這樣做",
    "Ich übe noch" to "我還在練習",
    "Ideen generieren" to "產生想法",
    "Im Haushalt helfen" to "幫忙做家事",
    "In Chat einfügen" to "加入聊天",
    "In Stille nebeneinander" to "彼此沉默",
    "In den Bergen" to "在山裡",
    "In eine Bar gehen" to "去酒吧",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "去海邊酒吧看日落",
    "In einem feinen Restaurant essen gehen" to "在高級餐廳外出用餐",
    "In einen Coffeeshop gehen" to "去咖啡廳",
    "In einer Beziehung sollte man alles voneinander wissen." to "在戀愛關係中，你們應該了解彼此的一切。",
    "Infinity-Pool" to "無邊際泳池",
    "Innenpool" to "室內泳池",
    "Intelligenz" to "智能",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "只有當你的伴侶發起親密時刻時",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "邀請碼：HRM-8731·一切解鎖",
    "Island" to "冰島",
    "Ist okay für mich" to "我覺得沒問題",
    "Ist schon perfekt" to "太完美了",
    "Ja, Traditionen einbinden" to "是的，融入傳統",
    "Ja, absolut" to "是的，絕對",
    "Ja, etwas zum Lesen und Aufbewahren" to "是的，需要閱讀和保存的東西",
    "Ja, genug" to "是的，夠了",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "是的，在令人興奮的城市或景點",
    "Ja, in- und auswendig" to "是的，從裡到外",
    "Ja, komplett überraschend" to "是的，完全令人驚訝",
    "Ja, perfekt" to "是的，完美",
    "Ja, sie gehören zur Familie!" to "是的，他們是一家人！",
    "Ja, sofort teilen" to "是的，立即分享",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "是的，我們將確保優先考慮家庭時間。",
    "Jacuzzi" to "按摩浴缸",
    "Jahr zusammen 🎉" to "一起過年🎉",
    "Jahre zusammen 🎉" to "在一起的歲月🎉",
    "Jeder zahlt 50%" to "每個人支付50%",
    "Junge" to "男生",
    "Kamin" to "煙囪",
    "Karriere & Erfolg" to "職業與成功",
    "Kategorien" to "類別",
    "Katze" to "貓",
    "Keine Musik" to "沒有音樂",
    "Keine Party nötig, privat halten" to "不需要聚會，保密",
    "Keine Privatsphäre" to "沒有隱私",
    "Keine Treffer gefunden" to "未找到符合項",
    "Keiner" to "無",
    "Keiner von uns" to "我們都沒有",
    "Kennst du die Essensvorlieben deines Partners?" to "你知道你的伴侣的食物偏好吗？",
    "Kino" to "電影院",
    "Kirchlich" to "教會",
    "Klassisch Solitär" to "經典紙牌",
    "Klassisch gebunden" to "經典結合",
    "Klein & zart" to "小巧精緻",
    "Kleine Geschenke" to "小禮物",
    "Kleine Runde" to "小組",
    "Kochen und Freunde einladen" to "烹飪並邀請朋友",
    "Kochkurs" to "烹飪課",
    "Kommt auf den Tag an" to "取決於當天",
    "Kommt darauf an" to "這取決於",
    "Kommt drauf an" to "這取決於",
    "Kommt mit" to "跟我來",
    "Konzert" to "演唱會",
    "Kräftige Farben" to "強烈的色彩",
    "Kräuterbeet" to "香草床",
    "Kultur & Sehenswürdigkeiten" to "文化與景點",
    "Kuscheln" to "擁抱",
    "Kuss senden" to "送一個吻",
    "Körperliche Annäherung" to "物理方法",
    "Körperliche Nähe" to "身體上的親密",
    "Küche" to "廚房",
    "Land" to "國家",
    "Landhaus" to "鄉村別墅",
    "Landhausstil" to "鄉村別墅風格",
    "Lange wach bleiben" to "晚點保持清醒",
    "Lappland" to "拉普蘭",
    "Lappland, Finnland" to "芬蘭拉普蘭",
    "Las Vegas" to "拉斯維加斯",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "讓你的伴侶激勵你成為最好的自己",
    "Lehne ab" to "衰退",
    "Leichtigkeit" to "舒適",
    "Leidenschaft" to "熱情",
    "Liebe im Gleichgewicht" to "平衡的愛",
    "Liebe sie, macht mehr Spaß" to "愛他們，更有趣",
    "Lieber durchgeplant oder spontan?" to "您願意有計畫的還是自發性的？",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "您願意享受兩個人還是與人一起度過一個安靜的夜晚？",
    "Lieber nicht" to "最好不要",
    "Lieber vorher grob absprechen" to "最好事先大致討論一下",
    "Lokal einkaufen" to "本地購物",
    "London" to "倫敦",
    "London, England" to "英國倫敦",
    "Lügen" to "說謊",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "您喜歡公開提案還是私人提案？",
    "Malediven" to "馬爾地夫",
    "Man sollte nie streitend einschlafen." to "你永遠不應該在爭論中入睡。",
    "Mango Sorbet" to "芒果冰淇淋",
    "Markant & breit" to "引人注目且寬闊",
    "Marken & Alltag" to "品牌與日常生活",
    "McDonald’s" to "麥當勞",
    "Mediterraner Innenhof" to "地中海庭院",
    "Mehr Unterstützung" to "更多支持",
    "Mehr gemeinsame Zeit" to "更多的時間在一起",
    "Mehr zuhören" to "多聽",
    "Mehrgenerationenhaus" to "多代的房子",
    "Mein Arbeitsplatz" to "我的工作場所",
    "Mein Partner" to "我的夥伴",
    "Mich überraschen" to "給我一個驚喜",
    "Minimalistisches Interieur" to "極簡主義內飾",
    "Missverständnisse" to "誤會",
    "Mit Familie und engen Freunden" to "與家人和親密的朋友",
    "Mit Kompromissen" to "妥協",
    "Mitgefühl" to "同情心",
    "Mittelweg mit besonderen Details" to "具有特殊細節的中間立場",
    "Modern geometrisch" to "現代幾何",
    "Moderne Grillstation" to "現代燒烤台",
    "Moderner Name" to "現代名稱",
    "Moderner Solitär" to "現代紙牌",
    "Moissanit" to "莫桑石",
    "Moment festhalten" to "捕捉精彩瞬間",
    "Momente" to "瞬間",
    "Monaco" to "摩納哥",
    "Moralische Werte" to "道德價值觀",
    "Museum" to "博物館",
    "Musik" to "音樂",
    "Mut" to "勇氣",
    "Mädchen" to "女孩",
    "Möbelhaus" to "家具店",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "您確定要退出測驗嗎？您之前的進度仍然儲存。",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "您希望寵物包含在應用程式中嗎？",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "想要在社群媒體上立即分享這一刻嗎？",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "我們可能需要存錢",
    "Müssen es planen" to "需要規劃一下",
    "Müssen sparen" to "需要保存",
    "Nachricht an" to "留言",
    "Name Partnerin" to "合作夥伴姓名",
    "Namen und Startdatum eurer Beziehung." to "你們關係的姓名和開始日期。",
    "Natursteinfassade" to "天然石材立面",
    "Naturteich" to "天然池塘",
    "Nein, einfach halten" to "不，只要握住它",
    "Nein, erstmal privat halten" to "不，暫時保密",
    "Nein, lieber vor Ort" to "不，現場更好",
    "Nein, modern halten" to "不，保持現代感",
    "Nein, nur wir" to "不，只有我們",
    "Nein, zu ablenkend" to "不，太分散注意力",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "新大樓配備智慧家居",
    "Neubau mit Technik" to "科技新建築",
    "Neue Liebe, neue Erfahrungen" to "新的愛情，新的體驗",
    "Neues Hobby" to "新爱好",
    "Neues Spiel" to "新游戏",
    "Neugier" to "好奇心",
    "New York" to "纽约",
    "New York, USA" to "美國紐約",
    "Nicht mein Fall" to "不是我喜歡的",
    "Nicht nötig, lieber klassisch bleiben" to "沒必要，保持經典就好",
    "Nichts — es passt so" to "沒什麼 - 很合適",
    "Nie wieder Burger" to "再也不會吃漢堡了",
    "Nie wieder Pizza" to "再也不會吃披薩了",
    "Niemand" to "沒有人",
    "Niemand ohne Plan" to "沒有計劃就沒有人",
    "Nike" to "耐吉",
    "Nizza" to "不錯",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "還沒有任何時刻。 \n記錄您的第一次體驗 💞",
    "Nur bei wichtigen Themen" to "只討論重要議題",
    "Nur wir beide" to "只有我們兩個人",
    "Nähe & Intimität" to "親密與親密",
    "Obstgarten" to "果園",
    "Oder" to "或者",
    "Offene Küche" to "開放式廚房",
    "Offene Wohnküche" to "開放式廚房/客廳",
    "Ohne Stein" to "沒有石頭",
    "Open End" to "開放式結局",
    "Outdoor-Küche" to "戶外廚房",
    "Outdoor-Sofa" to "戶外沙發",
    "Outdoor-Whirlpool" to "露天熱水浴缸",
    "Ovaler Diamant" to "橢圓形鑽石",
    "Paar" to "一對",
    "Paar-Statistiken" to "情侶統計",
    "Paris" to "巴黎",
    "Paris, Frankreich" to "法國巴黎",
    "Partner" to "夥伴",
    "Partner-Simulator" to "夥伴模擬器",
    "Partnerin" to "夥伴",
    "Party Edition" to "派對版",
    "Party Edition II" to "派對版II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "動物適合我們的日常生活嗎？",
    "Pasta" to "義大利麵",
    "Pastell" to "粉彩",
    "Penthouse mit Ausblick" to "景觀頂層公寓",
    "Pepsi" to "百事可樂",
    "Pergola mit Lounge" to "附休息室的涼棚",
    "Pfingstrosen" to "牡丹",
    "Pinguin" to "企鵝",
    "Pistazie" to "開心果",
    "Pizza" to "披薩",
    "Pizzaofen" to "披薩烤箱",
    "Platin" to "鉑",
    "PlayStation" to "遊戲機",
    "Pool" to "水池",
    "Pop" to "流行音樂",
    "Prasselnder Kamin" to "熊熊燃燒的壁爐",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "公主、海盜與仙塵：迪士尼測驗",
    "Privater Innenhof" to "私人庭院",
    "Profil" to "簡介",
    "Profil bearbeiten" to "編輯個人資料",
    "Prozentual nach Einkommen" to "基於收入的百分比",
    "Quiz verlassen" to "退出測驗",
    "Quiz verlassen?" to "退出測驗？",
    "Rausgehen in die Natur" to "走進大自然",
    "Reden vor ..." to "致詞...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "安排固定的日期或時間在一起",
    "Reisen" to "旅行",
    "Reiseziele" to "旅遊目的地",
    "Respektlosigkeit" to "不尊重",
    "Restaurant" to "餐廳",
    "RnB / Soul" to "RnB / 靈魂",
    "Rock" to "搖滾",
    "Rom" to "羅馬",
    "Rom, Italien" to "義大利羅馬",
    "Romantik" to "浪漫",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "消息、便條或禮物等浪漫的舉動讓我感到高興。",
    "Romantische Stimmung" to "浪漫心情",
    "Roségold" to "玫瑰金",
    "Ruhig zu zweit" to "兩個人安靜",
    "Runder Diamant" to "圓形鑽石",
    "Salted Caramel" to "鹹焦糖",
    "Sammle Ideen..." to "收集想法...",
    "Santorini" to "聖托里尼島",
    "Santorini, Griechenland" to "希臘聖托里尼島",
    "Saphir" to "藍寶石",
    "Saunahaus" to "三溫暖",
    "Schickes Restaurant oder Hotel" to "別緻的餐廳或飯店",
    "Schlafzimmer" to "臥室",
    "Schließen" to "關閉",
    "Schmal & zart" to "纖薄精緻",
    "Schnappschüsse aus unserer Liebesgeschichte" to "我們的愛情故事快照",
    "Schokolade" to "巧克力",
    "Schreib frei, was dir wirklich dazu einfällt." to "自由地寫下真正想到的內容。",
    "Schreibe deine eigene Antwort" to "寫下你自己的答案",
    "Sehr gerne" to "不客氣",
    "Sehr leicht" to "很輕",
    "Sehr wichtig — Fotos und Video" to "非常重要 — 照片與影片",
    "Sehr wichtig, es sollte persönlich sein" to "非常重要，應該是個人的",
    "Selbst kochen" to "自己煮飯",
    "Senden" to "發送",
    "Separate Küche" to "獨立廚房",
    "Serie schauen" to "觀看該系列",
    "Serienmarathon auf dem Sofa" to "系列沙發上的馬拉松",
    "Sex & Liebe" to "性與愛",
    "Seychellen" to "塞席爾",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "我們能夠負擔一個孩子/多個孩子的所有費用嗎？ 💰",
    "Soll der Antrag eine Überraschung sein?" to "該提案應該令人驚訝嗎？",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "應用程式應該包含文化或傳統元素嗎？",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "應用程式應該包含文化或傳統元素嗎？",
    "Sommerhochzeit" to "夏季婚禮",
    "Sonnige Dachterrasse" to "陽光明媚的屋頂露台",
    "Sowohl als auch" to "兩者都和",
    "Spazieren" to "散步",
    "Spaß & Abenteuer" to "樂趣與冒險",
    "Speichern" to "保存",
    "Spiel bearbeiten" to "編輯遊戲",
    "Spielbereich für Kinder" to "兒童遊樂區",
    "Spiele" to "遊戲",
    "Spiele spielen und Spaß haben" to "玩遊戲，玩得開心",
    "Spontan" to "自發",
    "Sportplatz" to "運動場",
    "Spotify" to "Spotify",
    "Sprache" to "語言",
    "Stadt" to "城市",
    "Stadt oder Land — was ist uns wichtiger?" to "城市和國家－哪個對我們比較重要？",
    "Stadtvilla" to "城市別墅",
    "Standesamt & Party" to "登記處及聚會",
    "Statement-Ring" to "個性戒指",
    "Stilvolles Outdoor-Sofa" to "時尚戶外沙發",
    "Stimme voll zu" to "完全同意",
    "Stimmt" to "對",
    "Stimmt nicht" to "不正確",
    "Stimmt, noch nie" to "確實，從來沒有",
    "Stracciatella" to "斯特拉西亞特拉",
    "Strandtag" to "海灘日",
    "Streit über Haushalt" to "家庭糾紛",
    "Studio Ghibli" to "吉卜力工作室",
    "Ständig" to "持續的",
    "Suche schließen" to "關閉搜尋",
    "Suche zurücksetzen" to "重置搜尋",
    "Suche öffnen" to "開啟搜尋",
    "Suchergebnisse" to "搜尋結果",
    "Sushi" to "壽司",
    "Süß" to "甜的",
    "Tage zusammen 💞" to "在一起的日子💞",
    "Tauche ins Unterbewusstsein" to "潛入潛意識",
    "Teile alle deine Hobbys mit deinem Partner" to "與你的伴侶分享你所有的愛好",
    "Teils teils" to "部分 部分",
    "Testen" to "測試",
    "Themen" to "主題",
    "Tiefe Gespräche" to "深入对话",
    "Tiefgründige Gespräche führen" to "進行深入對話",
    "Tierpension" to "動物寄宿處",
    "Tiny House" to "小房子",
    "Tippen zum Auswählen & Scrollen" to "點選選擇並捲動",
    "Tippen zum Zuklappen" to "點選折疊",
    "Titel" to "标题",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "標題、類別、主題、標籤、問題...",
    "Tokyo, Japan" to "日本東京",
    "Traditioneller Name" to "傳統名稱",
    "Traumhaus Außenbereich" to "夢想屋戶外區域",
    "Traumhochzeit" to "夢想婚禮",
    "Treffer" to "命中",
    "Tägliche Aktivität" to "日常活動",
    "Umformulieren" to "改寫",
    "Unbeantwortet" to "未回答",
    "Unbeliebte Meinungen" to "不受歡迎的意見",
    "Universal Studios Genie oder Neuling?" to "環球影城天才還是新手？",
    "Uns auseinanderzuleben" to "日漸疏遠",
    "Unser Intimleben" to "我們的親密生活",
    "Unser Traumhaus" to "我們的夢想之家",
    "Unser erstes Treffen" to "我們的第一次見面",
    "Unsere Gesichter" to "我們的臉",
    "Unsere eigenen Träume" to "我們自己的夢想",
    "Unsere nächste Reise" to "我們的下一次旅行",
    "Unter 1000" to "1000 以下",
    "Unter 1000 im Monat" to "每月1000以下",
    "Unter 50€/Monat" to "每月 50 歐元以下",
    "Unter Leuten" to "人與人之間",
    "Untreue" to "不忠",
    "Urlaub" to "假期",
    "Vanille" to "香草",
    "Venedig" to "威尼斯",
    "Venedig, Italien" to "義大利威尼斯",
    "Verbinde dich mit" to "連接到",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "连接到 \${profile.partnerName} 查看答案",
    "Verbindung" to "連接",
    "Verbringe die Feiertage mit deiner Familie" to "與家人一起度過假期",
    "Verlobungsringe" to "訂婚戒指",
    "Vertrautheit" to "熟悉度",
    "Viel getrennt" to "很多分離",
    "Vielleicht ein oder zwei" to "也許一兩個",
    "Vielleicht, aber mündlich reicht" to "也許吧，但口頭就夠了",
    "Vielleicht, wenn es machbar ist" to "也許吧，如果可以的話",
    "Vielleicht, wenn es passt" to "也許吧，如果適當的話",
    "Vintage Art déco" to "復古裝飾藝術",
    "Vintage verspielt" to "復古俏皮",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "被你的伴侶介紹新的嗜好",
    "Vor dem Kauf eines Hauses besprechen" to "買房前討論",
    "Vor der Anschaffung eines Haustiers besprechen" to "購買寵物前討論",
    "Vor der gemeinsamen Reise besprechen" to "一起旅行前討論",
    "Vor nichts" to "什麼也沒有",
    "Vorort" to "市郊",
    "Walnuss" to "核桃",
    "Wandern" to "遠足",
    "Wann fühlst du dich mir am nächsten?" to "你什麼時候感覺離我最近？",
    "Wann fühlst du dich mir körperlich am nächsten?" to "你什麼時候覺得身體上離我最近？",
    "Was bedeutet Vertrauen für dich konkret?" to "信任對您來說具體意味著什麼？",
    "Was entspannt dich mehr?" to "什麼讓你更放鬆？",
    "Was fehlt dir über die Distanz am meisten?" to "距離讓你最懷念什麼？",
    "Was gefällt dir an deinem Zuhause am besten?" to "你最喜歡你家的什麼？",
    "Was hast du von deinem Partner gelernt?" to "你從你的伴侶身上學到了什麼？",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "你覺得一起看色情內容怎麼樣？",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "您對道具（例如標誌、氣球等）有何看法？",
    "Was ist das Wichtigste beim Antrag?" to "申請時最重要的是什麼？",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "在性接觸中您最重視的是什麼？",
    "Was ist dein Lieblingsfoto von uns? 📸" to "你最喜歡我們的哪張照片？ 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "對於同居，您最大的恐懼是什麼？",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "有一種食物你很喜歡，但你的伴侶卻聽不懂？",
    "Was ist für dich ein absoluter Dealbreaker?" to "對您而言，什麼是絕對破壞交易的因素？",
    "Was ist für jeden von uns das absolute Highlight?" to "對我們每個人來說，絕對的亮點是什麼？",
    "Was ist passiert?" to "發生了什麼事？",
    "Was macht einen Moment für dich romantisch?" to "是什麼讓您的時刻變得浪漫？",
    "Was magst du an deinem Partner am liebsten?" to "你最喜歡你的伴侶什麼？",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "你比較喜歡哪一個：早起還是熬夜？",
    "Was magst du lieber?" to "你比較喜歡哪一個？",
    "Was möchtest du eigentlich sagen?" to "你到底想說什麼？",
    "Was möchtest du, dass dein Partner öfter tut?" to "您希望您的伴侶更頻繁地做什麼？",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "當我們旅行時，動物會發生什麼事？",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "我們的孩子長大後會變成什麼樣子？",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "身為父母，我們永遠不能忽視什麼？",
    "Was war dein schönster Moment mit mir bisher?" to "到目前為止，你和我在一起最美好的時刻是什麼？",
    "Was wir gegessen haben" to "我們吃了什麼",
    "Was wollt ihr nie vergessen?" to "你永遠不想忘記什麼？",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "對您來說，什麼會更糟：再也不會吃披薩或再也不會吃漢堡？",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "在一起的一天你最想做什麼？",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "如果錢不是問題，你會立即改變什麼？",
    "Weiter" to "下一步",
    "Weiter spielen" to "繼續播放",
    "Weiß ich noch nicht" to "我還不知道",
    "Weiße Rosen" to "白玫瑰",
    "Weißgold" to "白金",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "我們的孩子絕對應該從我們身上獲得什麼特質？",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "您想要什麼樣的環境來求婚？",
    "Welcher Raum sagt am meisten über dich aus?" to "哪個房間最能展現您的個性？",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "我們為食品和獸醫計劃的預算是多少？",
    "Welches Lied macht dich an? 🥵" to "哪首歌讓你興奮？ 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "您最喜歡哪一張分享的照片？",
    "Wellnessbad" to "健康沐浴",
    "Wenn es schwierig ist" to "當事情困難時",
    "Wenn ich müde bin" to "當我累了",
    "Wenn wir uns lange umarmen" to "當我們擁抱很久",
    "Wenn wir zusammen lachen" to "當我們一起笑的時候",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "誰能更快決定點什麼？",
    "Wer findet die besten Restaurants?" to "誰找到最好的餐廳？",
    "Wer gibt mehr Herzlichkeit?" to "誰給予更多溫暖？",
    "Wer hat den besseren Musikgeschmack?" to "誰的音樂品味比較好？",
    "Wer hängt mehr an seinen Eltern?" to "誰比較依戀父母？",
    "Wer ist besser organisiert?" to "誰更有組織性？",
    "Wer ist der Beste bei der Filmauswahl?" to "誰最會選片？",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "誰最擅長策劃浪漫約會？",
    "Wer ist der beste Tänzer?" to "誰是最好的舞者？",
    "Wer ist romantischer?" to "誰比較浪漫？",
    "Wer kocht besser?" to "誰做菜比較好？",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "誰負責裝修和維護？",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "當對方覺得不舒服時，誰能更快注意到？",
    "Wer sucht am Ende wirklich den Film aus?" to "最終誰真正選擇了這部電影？",
    "Wer vergisst eher einen Jahrestag?" to "誰更有可能忘記週年紀念日？",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "誰更有可能在第二天早上忘記自己的名字？",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "誰更有可能在第二天找到他們一無所知的影片？",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "誰願意在陌生人的沙發上過夜？",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "誰更有可能在聚會上睡著，醒來時臉上沾著記號筆？",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "誰更有可能在舞池裡滑倒，但又讓它看起來很酷？",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "誰更有可能在家庭聚會上控制 Spotify 播放清單？",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "誰更有可能在聚會上為每個人訂披薩並自己吃？",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "誰更有可能在聚會上先睡著？",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "誰更有可能突然開始在聚會上打掃？",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "當事實相反時，誰更有可能聲稱自己完全清醒？",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "在爭論中誰更有可能先讓步？",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "誰更有可能在飲酒遊戲中作弊？",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "誰更有可能闖入自助餐並偷偷把食物帶回家？",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "誰更有可能在他們的故事中發布當晚最尷尬的照片？",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "誰更有可能惹惱 DJ 要求他們最喜歡的歌曲？",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "誰更有可能錯誤地跟著歌詞一起唱，但又充滿信心？",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "誰更有可能點了菜單上最貴的飲料併後悔？",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "如果鄰居抱怨噪音，誰更有可能邀請他們過來？",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "誰會太認真地對待派對遊戲（如啤酒乒乓球）？",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "誰更有可能與保鑣交朋友以獲得 VIP 訪問權限？",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "誰更有可能發起一場自發性的卡拉 OK 大戰？",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "誰更有可能在不使用開瓶器的情況下打開瓶子？",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "即使完全沒有人提出要求，誰更有可能發表演講？",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "誰更有可能在浴室裡花一個小時自拍？",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "誰更有可能表演令人尷尬的舞蹈表演並慶祝？",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "聚會結束後，誰更有可能打電話給前伴侶？",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "誰更有可能不小心得罪陌生客人？",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "誰更有可能不辭而別地偷偷離開聚會？",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "誰寧願和主人的寵物一起玩，也不願和客人說話？",
    "Wer würde eher spontan eine Reise buchen?" to "誰更有可能自發性預訂旅行？",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "誰更有可能在廚房裡進行幾個小時的深入交談？",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "誰更有可能不小心喝到別人的飲料？",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "誰更有可能不小心打翻昂貴的花瓶或易碎物品？",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "誰更有可能嘗試自己調製複雜的雞尾酒並慘敗？",
    "Wer würde eher zu spät kommen?" to "誰更有可能遲到？",
    "Wer würde eher?" to "誰願意？",
    "Wer übernimmt die tägliche Versorgung?" to "日常護理誰負責？",
    "Werde so akzeptiert, wie du bist" to "接受你原本的樣子",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "我们有足够的时间陪伴孩子们吗？ ⏳",
    "Whirlpool" to "熱水浴缸",
    "White Chocolate" to "白巧克力",
    "Widgets" to "小部件",
    "Wie fühlst du dich am meisten geliebt?" to "你觉得最被爱的感觉如何？",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "我們如何因應不同的收入？",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "您的伴侣向您发起性行为的最佳方式是什么？",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "您的伴侶如何成為您更好的伴侶？",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "你想在求婚後多久和別人一起慶祝？",
    "Wie lange wollen wir dort mindestens bleiben?" to "我們至少想在那裡待多久？",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "您談論願望有多容易？",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "你希望我們的未來是什麼樣子？",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "你家完美的星期日是什麼樣的？",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "性愛時說髒話你有何感想？",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "我們實際上可以負擔多少信貸？",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "我們想分開多久？",
    "Wie viel wollen wir insgesamt ausgeben?" to "我們總共要花多少錢？",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "寶寶出生後，我們如何找到時間來處理我們的關係？",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "捕捉瞬間對您來說有多重要？",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "應用程式反映您的愛好或興趣對您來說有多重要？",
    "Wie würdest du sie/ihn nennen?" to "你會怎麼稱呼他/她？",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "除了性之外，你最喜歡用什麼方式表達愛意？",
    "Wildblumen" to "野花",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "你想要女孩還是男孩？ 👶",
    "Wintergarten" to "冬季花園",
    "Winterhochzeit" to "冬季婚禮",
    "Wir bestellen einfach beides" to "我們只訂購兩者",
    "Wir brauchen ewig" to "這需要我們永遠",
    "Wir einigen uns nie" to "我們從不同意",
    "Wir entscheiden es gemeinsam" to "我們一起決定",
    "Wir treffen uns in der Mitte" to "我們在中間相遇",
    "Wir wechseln uns ab" to "我們輪流",
    "Wird stressig" to "壓力很大",
    "Wobei lachst du am meisten?" to "什麼最讓你笑？",
    "Wofür sparen wir gemeinsam?" to "我們一起存錢是為了什麼？",
    "Wohnzimmer" to "客廳",
    "Woran erinnerst du dich am lebhaftesten?" to "你印象最深刻的是什麼？",
    "Worauf freust du dich bei uns am meisten?" to "您最期待我們的什麼？",
    "Worte/Komplimente" to "言語/讚美",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "在我們的關係中你最害怕什麼？",
    "Wünsche? z.B. günstig, draußen" to "願望？例如便宜，外面",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "您願意在假期（涉及旅行）求婚嗎？",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube 音樂",
    "Zeichne für mich" to "為我畫畫",
    "Zeichne mich als Tier — welches wäre ich?" to "把我畫成一隻動物 - 我會是哪一種？",
    "Zeichne unser Gefühl zueinander als Symbol." to "將我們對彼此的感情當作象徵。",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "用一條線畫出我們夢想中的房子。最引人注目的是什麼？",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "畫出我們的第一次約會－圖中一定需要有什麼？",
    "Zeichnen" to "畫",
    "Zeit füreinander" to "彼此的時間",
    "Zeit, wenn das Baby schläft" to "寶寶睡覺的時間",
    "Zelten gehen" to "去露營",
    "Zitrone" to "檸檬",
    "Zu Hause, gemütlich und privat" to "在家裡，舒適又私密",
    "Zu einem Picknick gehen" to "去野餐",
    "Zu einem ausgefallenen Abendessen gehen" to "去吃一頓豐盛的晚餐",
    "Zu zweit reisen" to "情侶旅行",
    "Zuhause & Alltag" to "居家與日常生活",
    "Zuhören" to "聽著",
    "Zurück" to "返回",
    "Zusammen seit" to "在一起以來",
    "Zusammen seit (TT.MM.JJJJ)" to "在一起 (DD.MM.YYYY)",
    "Zusammenziehen" to "承包",
    "Zustimmen oder Ablehnen" to "同意或拒絕",
    "Zwei Kreise, die sich überschneiden" to "兩個重疊的圓",
    "Zwei Stühle davor" to "前面有兩把椅子",
    "Zärtlich sein" to "溫柔一點",
    "Öfter als ich zugebe" to "比我承認的更頻繁",
    "Über 100€/Monat" to "超過 100 歐元/月",
    "Über 2000 im Monat" to "一個月2000多",
    "Über mich selbst" to "關於我自己",
    "Übernehmen" to "接管",
    "Überraschend" to "奇怪",
    "Überraschung" to "驚喜",
    "Überspringen" to "跳過",
    "Übertrieben und großartig" to "超越頂部，棒極了",
    "✎ Tippe, um zu antworten" to "✎ 點擊回复",
    "✨ GFK-Brücke" to "✨ 玻璃鋼橋",
)

internal fun localizeChineseTraditionalDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_CHINESE_TRADITIONAL_CONTENT)
