package com.example.ui

val EXACT_ENGLISH_CONTENT: Map<String, String> = mapOf(
    "Tauche ins Unterbewusstsein" to "Dive into the Subconscious",
    "Themen" to "Topics",
    "Merken" to "Remember",
    "Das müssen wir uns merken" to "Things we need to remember",
    "Gemeinsam sammeln. Nie vergessen." to "Collect together. Never forget.",
    "Aktuell" to "Current",
    "Erledigte Notizen" to "Completed notes",
    "Filme" to "Movies",
    "Serien" to "Series",
    "Ideen" to "Ideas",
    "Orte" to "Places",
    "Sonstiges" to "Other",
    "Notiz" to "Note",
    "Liste" to "List",
    "Link" to "Link",
    "Wiederherstellen" to "Restore",
    "Endgültig löschen" to "Delete permanently",
    "Vorschau erneut laden" to "Retry preview",
    "Notiz hinzufügen" to "Add note",
    "Kategorie hinzufügen" to "Add category",
    "Keine Einträge gefunden" to "No entries found",
    "Bitte gib einen Titel ein" to "Please enter a title",
    "Bitte gib mindestens einen Eintrag ein" to "Please enter at least one item",
    "Bitte gib einen gültigen HTTP- oder HTTPS-Link ein" to "Please enter a valid HTTP or HTTPS link",
    "Notiz konnte nicht gespeichert werden" to "The note could not be saved",
    "Kategorie konnte nicht gespeichert werden" to "The category could not be saved",
    "Möchtest du diesen Eintrag endgültig löschen?" to "Do you want to permanently delete this item?",
    "Löschen" to "Delete",
    "Suchen" to "Search",
    "Notiz, Liste oder Link" to "Note, list, or link",
    "Beschreibung" to "Description",
    "Eine Notiz pro Zeile" to "One note per line",
    "Kategorie" to "Category",
    "Name" to "Name",
    "Farbe" to "Color",
    "Symbol" to "Icon",
    "Kategorie bearbeiten" to "Edit category",
    "Einträge verschieben nach" to "Move items to",
    "Erledigt" to "Completed",
    ", listOf(" to ", listOf(",
    "1-5 Jahre" to "1-5 years",
    "1000 - 1500 im Monat" to "1000 - 1500 a month",
    "1000 bis 3000" to "1000 to 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 a month",
    "3000 bis 5000" to "3000 to 5000",
    "5-10 Jahre" to "5-10 years",
    "50-100€/Monat" to "50-100€/month",
    "Ab 100€" to "From 100€",
    "Ab 500€" to "From 500€",
    "Ab 50€" to "From 50€",
    "Ab und zu" to "From time to time",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Above what amount do we discuss before making a purchase?",
    "Abbrechen" to "Cancel",
    "Abenteuer" to "Adventure",
    "Aktivitäten" to "Activities",
    "Alle" to "All",
    "Alle Pakete" to "All packs",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Lose all your friends except your best friend",
    "Alle intimen Momente selbst initiieren" to "Initiate all intimate moments yourself",
    "Alles davon" to "All of the above",
    "Alles, was noch kommt" to "Everything yet to come",
    "Alltagsroutine" to "Everyday routine",
    "Alltägliche Berührungen" to "Everyday physical touch",
    "Altbau mit Charme" to "Historic charm apartment",
    "Am Strand" to "At the beach",
    "Am liebsten alles zusammen" to "Preferably everything together",
    "Am selben Tag mit Freunden/Familie" to "On the same day with friends/family",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Netherlands",
    "An das Gefühl" to "Remembering the feeling",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "In a public place with many spectators",
    "An einen Geruch" to "Remembering a scent",
    "An einen Song" to "Remembering a song",
    "An etwas, das ich gesagt habe" to "Something I said",
    "Analyse starten" to "Start analysis",
    "Analysiere eure Muster..." to "Analyzing your patterns...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Analyzes your answers & chats using Gottman and NVC.",
    "Ananas auf der Pizza schmeckt köstlich." to "Pineapple on pizza tastes delicious.",
    "Antwort mit einem Foto" to "Answer with a photo",
    "Antwortähnlichkeit" to "Answer similarity",
    "App-Sprache auswählen" to "Select App Language",
    "Auf eine Bootsparty gehen" to "Go to a boat party",
    "Aufmerksamkeit" to "Attention",
    "Aufräumen und Projekte angehen" to "Tidying up and tackling projects",
    "Aufwärmen" to "Warm-up",
    "Aufwärmen: Einander kennenlernen" to "Warm-up: Getting to know each other",
    "Aus dem Urlaub" to "From the vacation",
    "Ausgefallener Name" to "Unusual name",
    "Ausschlafen und faulenzen" to "Sleeping in and lounging around",
    "Ausschlafen und nichts tun" to "Sleeping in and doing nothing",
    "Aussehen" to "Looks",
    "Auto" to "Car",
    "Außenkamin" to "Outdoor fireplace",
    "BEANTWORTE" to "ANSWER",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonesia",
    "Banane" to "Banana",
    "Beantwortet" to "Answered",
    "Unbeantwortet" to "Unanswered",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Answer questions simultaneously — answers will only appear once both of you are done.",
    "Beantwortete Fragen" to "Questions answered",
    "Bearbeiten" to "Edit",
    "Bei Insider-Witzen" to "At inside jokes",
    "Bei Memes" to "At memes",
    "Bei einer spontanen Berührung" to "At a spontaneous touch",
    "Beide" to "Both",
    "Beide gleich" to "Both equally",
    "Beide zusammen" to "Both together",
    "Beide, aber wir tun so als ob nicht" to "Both, but we pretend not to",
    "Beides" to "Both",
    "Beim Einschlafen nebeneinander" to "Falling asleep next to each other",
    "Beim Reden" to "While talking",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Famous tourist spots are always a disappointment.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Describe our sex life with an emoji.",
    "Besser kommunizieren" to "Communicate better",
    "Bessere Lage" to "Better location",
    "Bestellen" to "Order",
    "Besuchte Länder" to "Countries visited",
    "Besuchte Städte" to "Cities visited",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Do you prefer an extravagant proposal or something subtle?",
    "Beziehung" to "Relationship",
    "Bibliothek" to "Library",
    "Bin manchmal unsicher" to "I'm sometimes unsure",
    "Bist du ein Videospiel-Guru?" to "Are you a Video Game Guru?",
    "Blumenwiese" to "Flower meadow",
    "Bunte Blumenwiese" to "Colorful flower meadow",
    "Burger" to "Burger",
    "Chat" to "Chat",
    "Cookie Dough" to "Cookie dough",
    "Dachgarten mit Lounge" to "Roof garden with lounge",
    "Dachterrasse" to "Roof terrace",
    "Das Wetter an dem Tag" to "The weather that day",
    "Das erste Selfie" to "The first selfie",
    "Das meiste weiß ich" to "I know most of it",
    "Das oder das?" to "This or That?",
    "Das tägliche Leben" to "Daily Life",
    "Dass Zusagen gehalten werden" to "That promises are kept",
    "Dass alles meinen Stil hat" to "That everything matches my style",
    "Dass ich alles erzählen kann" to "That I can talk about anything",
    "Dass ich mich nicht sorgen muss" to "That I don't have to worry",
    "Dass wir ungestört sind" to "That we are undisturbed",
    "Dein Name" to "Your name",
    "Deine Antwort..." to "Your answer...",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Your answers are saved. As soon as \${profile.partnerName} finishes the pack, both answers will be visible together.",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Your answers are saved. Once your partner finishes the pack, you will see both answers together.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Make your relationship adventurous and spontaneous",
    "Deine Beziehung stabil und sicher machen" to "Make your relationship stable and secure",
    "Deine eigene Antwort" to "Your own answer",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Prefer sharing your deepest secrets with your partner",
    "Deinen besten Freund verlieren" to "Lose your best friend",
    "Denke an dich" to "Thinking of you",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Watching the same movie twice is a waste of time.",
    "Der Blick nach draußen" to "The view outside",
    "Der Garten" to "The garden",
    "Der Ort" to "The location",
    "Der Ring und die Geste" to "The ring and the gesture",
    "Der perfekte Heiratsantrag" to "The perfect proposal",
    "Derjenige sein, der umarmt wird" to "Being the one who is hugged",
    "Deutsch" to "German",
    "Diamant" to "Diamond",
    "Diamanten im Band" to "Diamonds in the band",
    "Die Distanz" to "The distance",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Spend the holidays with your partner's family",
    "Die Gemütlichkeit und Ruhe" to "The coziness and peace",
    "Die Menschen, die darin wohnen" to "The people living inside",
    "Die Umgebung und Atmosphäre" to "The setting and atmosphere",
    "Die Worte und Emotionen" to "The words and emotions",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "The Ultimate Entertainment Quiz Challenge",
    "Diejenige sein, die umarmt" to "Being the one who hugs",
    "Direkt ansprechen" to "Discussing immediately",
    "Diskussion" to "Discussion",
    "Diskutiere vor dem Kinderkriegen" to "Discuss before having children",
    "Diskutiert eure Antworten" to "Discuss your answers",
    "Doch, schon mal" to "Yes, actually before",
    "Draußen mit der Natur als Kulisse" to "Outdoors with nature as a backdrop",
    "Drei-Stein-Ring" to "Three-stone ring",
    "Du bist dran" to "Your turn",
    "Du fehlst mir" to "I miss you",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubai, UAE",
    "Dunkles Design" to "Dark Mode",
    "Durch Berührung" to "Through touch",
    "Durch Worte" to "Through words",
    "Durch Zeit zu zweit" to "Through quality time",
    "Durch kleine Gesten" to "Through small gestures",
    "Durchgeplant" to "Fully planned",
    "ERGEBNISSE" to "RESULTS",
    "Egal, Hauptsache gesund" to "Doesn't matter, as long as it's healthy",
    "Ehepaar Leben" to "Married Couple Life",
    "Eher knapp" to "Rather tight",
    "Eher nicht" to "Rather not",
    "Eher schwer" to "Rather hard",
    "Eher schwierig" to "Rather difficult",
    "Eher zu" to "Rather closed",
    "Eifersucht ist ein Zeichen von Liebe." to "Jealousy is a sign of love.",
    "Eigenes Gemüsebeet" to "Home vegetable garden",
    "Ein Abenteuer in einer neuen Stadt" to "An adventure in a new city",
    "Ein Anker" to "An anchor",
    "Ein Balkon oder Garten" to "A balcony or garden",
    "Ein Filmabend" to "A movie night",
    "Ein Harmony-Meilenstein eurer Liebe." to "A Harmony milestone of your love.",
    "Ein Herz" to "A heart",
    "Ein Herz an der Tür" to "A heart on the door",
    "Ein Jahr lang eine Fernbeziehung führen" to "Have a long-distance relationship for a year",
    "Ein Live-Musik-Konzert besuchen" to "Attend a live music concert",
    "Ein Museum besuchen" to "Visit a museum",
    "Ein Spieleabend" to "A game night",
    "Ein Spieleabend mit Freunden" to "A game night with friends",
    "Ein Urlaubsfoto" to "A vacation photo",
    "Ein aktives Abenteuer" to "An active adventure",
    "Ein entspannender Spa-Tag" to "A relaxing spa day",
    "Ein ganz normaler Alltagstag" to "An ordinary everyday day",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "A cozy evening indoors during a thunderstorm",
    "Ein gemütliches Date drinnen" to "A cozy indoor date",
    "Ein lustiges Bild" to "A funny picture",
    "Ein paar Handyfotos reichen" to "A few phone photos are enough",
    "Ein paar Stunden" to "A few hours",
    "Ein paar kulturelle Anklänge sind okay" to "A few cultural touches are okay",
    "Ein romantischer Abend" to "A romantic evening",
    "Ein romantisches Abendessen bei Kerzenlicht" to "A romantic candlelit dinner",
    "Ein romantisches Bild" to "A romantic picture",
    "Ein romantisches Picknick an einem schönen Ort" to "A romantic picnic in a beautiful spot",
    "Ein schwerer Moment, den wir geschafft haben" to "A difficult moment we overcame",
    "Ein tolles Date im Freien unter dem Mondlicht" to "A great outdoor date under the moonlight",
    "Ein zufälliger Schnappschuss" to "A random snapshot",
    "Einander kennenlernen" to "Getting to know each other",
    "Eine Autoreise" to "A road trip",
    "Eine Brücke" to "A bridge",
    "Eine Date-Nacht unter den Sternen" to "A date night under the stars",
    "Eine Million Dollar gewinnen" to "Win a million dollars",
    "Eine Million Dollar verdienen" to "Earn a million dollars",
    "Eine Nacht in einem Club" to "A night in a club",
    "Eine Schokoladenverkostung" to "A chocolate tasting",
    "Eine Wanderung mit Panoramablick machen" to "Go on a hike with a panoramic view",
    "Eine Weinverkostung" to "A wine tasting",
    "Eine gemeinsame Reise" to "A trip together",
    "Eine gemütliche Nacht zu Hause" to "A cozy night at home",
    "Eine neue Sprache zu lernen ist einfach." to "Learning a new language is easy.",
    "Einen Film anschauen" to "Watch a movie",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Not talk to each other at all for a month",
    "Einen Tanzkurs besuchen" to "Take a dance class",
    "Einen Vergnügungspark erkunden" to "Explore an amusement park",
    "Einen Wellness-Tag" to "A wellness day",
    "Einen sehr emotionalen Partner haben" to "Have a very emotional partner",
    "Einen sehr logischen Partner haben" to "Have a very logical partner",
    "Einer zahlt alles" to "One pays everything",
    "Einfach mehr Alltag" to "Just more everyday life",
    "Einfach nebeneinander sein" to "Just being side by side",
    "Einfach und intim" to "Simple and intimate",
    "Einige Dinge für dich behalten" to "Keep some things to yourself",
    "Einmal" to "Once",
    "Eins, das nur wir kennen" to "One that only we know",
    "Englisch" to "English",
    "Entspannte Hängematte" to "Relaxing hammock",
    "Entspannung" to "Relaxation",
    "Entwickler Studio Öffnen" to "Open Developer Studio",
    "Entwickler-Modus" to "Developer mode",
    "Erdbeere" to "Strawberry",
    "Erfolgreich" to "Successful",
    "Ergebnisse" to "Results",
    "Erst bei sehr großen Summen" to "Only for very large amounts",
    "Erst nur enge Freunde/Familie" to "First only close friends/family",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "It annoys me when my partner takes too long to reply to messages.",
    "Essensvorlieben" to "Food Preferences",
    "Etwa eine Woche später, erst mal nur wir" to "About a week later, just us at first",
    "Etwas Neues ausprobieren" to "Trying something new",
    "Etwas ganz anderes" to "Something completely different",
    "Etwas, eine kleine Note wäre schön" to "Somewhat, a small touch would be nice",
    "Familie" to "Family",
    "Familie/Freunde" to "Family/Friends",
    "Familienmensch" to "Family person",
    "Farbedelstein" to "Colored gemstone",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "TV commercials are sometimes interesting to watch.",
    "Fertig" to "Done",
    "Fertig!" to "Done!",
    "Feste Date-Nights" to "Fixed date nights",
    "Feuerstelle" to "Fire pit",
    "Filigran & schlicht" to "Filigree & simple",
    "Filme/Serien" to "Movies/Series",
    "Formuliere um..." to "Rewriting...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Rewrites your draft using NVC: observation, feeling, need, request.",
    "Frage hinzufügen" to "Add question",
    "Fragen & Spiele" to "Questions & Games",
    "Fragen für jede Gelegenheit" to "Questions for Every Occasion",
    "Freizeitpark" to "Amusement park",
    "Freunde treffen" to "Meeting friends",
    "Freundschaften mit Ex-Partnern sind okay." to "Friendships with ex-partners are okay.",
    "Früh aufstehen" to "Wake up early",
    "Fußbodenheizung" to "Underfloor heating",
    "Führen wir getrennte oder gemeinsame Konten?" to "Do we keep separate or joint accounts?",
    "Für dich empfohlen" to "Recommended for you",
    "Für die Zukunft" to "For the future",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "No matching questions or games found for this search.",
    "Für immer" to "Forever",
    "Fürsorglichkeit" to "Caring",
    "GFK-Brücke" to "NVC Bridge",
    "Galerie" to "Gallery",
    "Gar nicht, der Moment gehört uns" to "Not at all, the moment belongs to us",
    "Gar nichts tun" to "Doing nothing at all",
    "Geduld" to "Patience",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Go early in the morning to watch the sunrise",
    "Geht so" to "So-so",
    "Geister existieren wirklich." to "Ghosts really exist.",
    "Gelassenheit" to "Serenity",
    "Gelbgold" to "Yellow gold",
    "Geld & Finanzen" to "Money & Finances",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Travel the world together, explore new cultures and cuisines",
    "Gemeinsam ein Lego bauen" to "Build Lego together",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Try out a new recipe in the kitchen together",
    "Gemeinsame Konten" to "Joint accounts",
    "Gemeinsame Nächte" to "Nights together",
    "Gemeinsame Tage" to "Days together",
    "Gemischt" to "Mixed",
    "Gemüsebeet" to "Vegetable patch",
    "Gemütliche Feuerstelle" to "Cozy fire pit",
    "Gesprächsanreger" to "Conversation Starter",
    "Getrennte Konten" to "Separate accounts",
    "Getrennte Urlaube tun einer Beziehung gut." to "Taking separate vacations is good for a relationship.",
    "Gewächshaus" to "Greenhouse",
    "Glasfassade" to "Glass facade",
    "Gleichgültigkeit" to "Indifference",
    "Glücklich und frei" to "Happy and free",
    "Gourmet Eis-Sorten" to "Gourmet ice cream flavors",
    "Gravur innen" to "Engraving inside",
    "Grillplatz" to "BBQ area",
    "Groß & üppig" to "Large & lavish",
    "Große Familie" to "Big family",
    "Große Feier" to "Big celebration",
    "Große Fenster" to "Large windows",
    "Große Fensterfront" to "Large window front",
    "Großer Außenpool" to "Large outdoor pool",
    "Großer Garten" to "Large garden",
    "Großer Stein" to "Large stone",
    "Größere Küche" to "Larger kitchen",
    "Gutes Essen" to "Good food",
    "Habe ich" to "I have",
    "Habe ich noch nie" to "Never have I ever",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Did you discover surprising differences? Talk about why you prefer certain options!",
    "Haus am See" to "House by the lake",
    "Haus/Wohnung" to "House/Apartment",
    "Hazelnut" to "Hazelnut",
    "Heimkino" to "Home cinema",
    "Herzhaft" to "Savory",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Nothing here right now.\nChange the filter or choose another topic.",
    "Hilfe im Alltag" to "Help in everyday life",
    "Himbeere" to "Raspberry",
    "Hinzufügen" to "Add",
    "Hobbys" to "Hobbies",
    "Hochzeitssträuße" to "Wedding Bouquets",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Hogwarts House Pride: Where do you belong?",
    "Home" to "Home",
    "Hot Tub" to "Hot tub",
    "Humor" to "Humor",
    "Hund" to "Dog",
    "Hängematte" to "Hammock",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Would you like a written letter as part of the proposal?",
    "Ich" to "Me",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "I prefer romantic walks in the park over going to the cinema.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "I have never fallen asleep in a cinema.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "I enjoy exploring new hobbies or activities with my partner.",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "I enjoy trying new restaurants with my partner instead of always going to the same places.",
    "Ich habe noch nie" to "Never have I ever",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Never have I ever been terrified of a roller coaster and ridden it anyway.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Never have I ever bought Fast Pass tickets because I was impatient.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "I have never canceled plans just to stay home and watch a TV show.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Never have I ever waited for my letter from Hogwarts.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Never have I ever claimed that Slytherin really isn't that evil.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Never have I ever claimed I was too old for Disney movies (and secretly enjoyed them).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Never have I ever intentionally blasted someone with a blue shell in Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Never have I ever cried during a Disney movie.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Never have I ever covered my eyes during a horror movie.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Never have I ever forgotten to save a game and lost hours of progress.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Never have I ever left the room during a cringe-worthy movie scene.",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Never have I ever struck a funny pose for the on-ride roller coaster photo.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Never have I ever gamed late into the night and regretted how tired I was the next day.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Never have I ever Googled the ending of a movie because I couldn't wait.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Never have I ever felt like I was standing in a real movie set.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Never have I ever skipped the intro of my favorite TV show.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Never have I ever used someone else's Netflix password.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Never have I ever listened to a video game soundtrack while working or studying.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Never have I ever blamed the controller when I lost.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Never have I ever thrown the keyboard or controller in rage.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "I have never forgotten wet clothes in the washing machine for a few days.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Never have I ever spent real money on cosmetic in-game items.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "I have never driven a car in a foreign country.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Never have I ever belted out a Disney song in the shower.",
    "Ich habe noch nie ein Elektroauto gefahren." to "I have never driven an electric car.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Never have I ever taken a picture with a theme park mascot.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Never have I ever named a pet after a Hogwarts character.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Never have I ever dropped popcorn at the movies and eaten it anyway.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Never have I ever used a Master Yoda quote in everyday life.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Never have I ever bought an overpriced souvenir at an amusement park.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Never have I ever recommended a movie that the other person found terrible.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Never have I ever watched the Oscars live in the middle of the night.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Never have I ever dropped a series because the final season was awful.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Never have I ever binge-watched an entire season of a show in one day.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Never have I ever beat a boss on the first try and felt like a gaming god.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Never have I ever found the villain cooler than the hero.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Never have I ever recognized a Toy Story character in my own toys.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Never have I ever created an RPG character to look exactly like myself.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Never have I ever eaten a churro in a theme park.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Never have I ever watched a Disney movie three times in a row.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Never have I ever had a Disney earworm stuck in my head for an entire week.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Never have I ever watched a movie solely because of a specific actor.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Never have I ever listened to a movie soundtrack on repeat for hours.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Never have I ever dropped a movie spoiler and instantly regretted it.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "I have never made a friend who speaks a different native language.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "I have never had a friend who moved to another country.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Never have I ever had a Harry Potter movie marathon at Christmas.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Never have I ever sat through a Marvel movie solely for the post-credits scene.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Never have I ever intentionally messed with an NPC in a game.",
    "Ich habe noch nie einen Nachtzug genommen." to "I have never taken a night train.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Never have I ever taken an online quiz to find out my Hogwarts house.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "I have never deleted a social media post because it didn't get enough likes.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Never have I ever called a day at a theme park the best day of the year.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Never have I ever visited a theme park and stayed open to close.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Never have I ever walked off a Transformers or Marvel ride completely amazed.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Never have I ever rage-quit a game in frustration.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Never have I ever read one of the thick Harry Potter books.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Never have I ever crushed hard on my favorite TV show character.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Never have I ever dreamed of playing Quidditch.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Never have I ever secretly Googled how to beat a difficult video game level.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Never have I ever secretly hoped my pet could talk just like in Disney movies.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Never have I ever removed the pool ladder in The Sims.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Never have I ever lost my sense of balance on a 3D simulator ride.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "I have never played on a university sports team.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Never have I ever waited more than two hours in line for a single ride.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Never have I ever soaked my valuables on a water ride.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Never have I ever argued with a friend over which Hogwarts house is the best.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Never have I ever pretended to have ice magic powers like Elsa.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Never have I ever laughed so loud that I missed an important movie scene.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Never have I ever had such an adrenaline rush that I wanted to ride again immediately.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Never have I ever tried singing to animals like Snow White.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Never have I ever dreamed of a trip to Disneyland.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Never have I ever dreamed of riding the Jurassic Park river adventure.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Never have I ever screamed out loud from a video game jump-scare.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "I have never cried over a TV show finale.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Never have I ever... canceled a date to stay at home.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Never have I ever... rephrased a message 10 times.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Never have I ever... secretly checked my partner's phone.",
    "Ich habe noch nie!" to "Never have I ever!",
    "Ich habe!" to "I have!",
    "Ich lache viel mit meinem Partner." to "I laugh a lot with my partner.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "I enjoy getting to know my partner's hobbies and interests.",
    "Ich liebe es" to "I love it",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "I love watching movies with my partner that neither of us has seen before.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "I love sharing my favorite music with my partner.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "I have never had to run to catch a connecting flight.",
    "Ich plane gerne Dates mit meinem Partner." to "I like planning dates with my partner.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "I prioritize spending time with my partner even when I am busy.",
    "Ich schreibe meinem Partner jeden Tag." to "I text my partner every day.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "I like sharing memes and jokes with my partner.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "I like sharing all the details of my day with my partner.",
    "Ich würde es nie tun" to "I would never do it",
    "Ich übe noch" to "I'm still practicing",
    "Ideen generieren" to "Generate ideas",
    "Im Haushalt helfen" to "Help in the household",
    "In Chat einfügen" to "Insert into chat",
    "In Stille nebeneinander" to "In silence next to each other",
    "In den Bergen" to "In the mountains",
    "In eine Bar gehen" to "Go to a bar",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Go to a beach bar to watch the sunset",
    "In einem feinen Restaurant essen gehen" to "Go out for dinner at a fine restaurant",
    "In einen Coffeeshop gehen" to "Go to a coffee shop",
    "In einer Beziehung sollte man alles voneinander wissen." to "In a relationship, you should know everything about each other.",
    "Infinity-Pool" to "Infinity pool",
    "Innenpool" to "Indoor pool",
    "Intelligenz" to "Intelligence",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Having intimate moments only when initiated by your partner",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Invite code: HRM-8731 · everything unlocked",
    "Island" to "Iceland",
    "Ist okay für mich" to "It's okay for me",
    "Ist schon perfekt" to "It's already perfect",
    "Ja, Traditionen einbinden" to "Yes, include traditions",
    "Ja, absolut" to "Yes, absolutely",
    "Ja, etwas zum Lesen und Aufbewahren" to "Yes, something to read and keep",
    "Ja, genug" to "Yes, enough",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Yes, in an exciting city or landmark",
    "Ja, in- und auswendig" to "Yes, inside out",
    "Ja, komplett überraschend" to "Yes, completely surprising",
    "Ja, perfekt" to "Yes, perfect",
    "Ja, sie gehören zur Familie!" to "Yes, they are part of the family!",
    "Ja, sofort teilen" to "Yes, share immediately",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Yes, we will ensure family time is prioritized.",
    "Jacuzzi" to "Jacuzzi",
    "Jahr zusammen 🎉" to "year together 🎉",
    "Jahre zusammen 🎉" to "years together 🎉",
    "Jeder zahlt 50%" to "Each pays 50%",
    "Junge" to "Boy",
    "Kamin" to "Fireplace",
    "Karriere & Erfolg" to "Career & Success",
    "Kategorien" to "Categories",
    "Katze" to "Cat",
    "Keine Musik" to "No music",
    "Keine Party nötig, privat halten" to "No party needed, keep it private",
    "Keine Privatsphäre" to "No privacy",
    "Keine Treffer gefunden" to "No matches found",
    "Keiner" to "Neither",
    "Keiner von uns" to "Neither of us",
    "Kennst du die Essensvorlieben deines Partners?" to "Do you know your partner's food preferences?",
    "Kino" to "Cinema",
    "Kirchlich" to "Church / Religious",
    "Klassisch Solitär" to "Classic solitaire",
    "Klassisch gebunden" to "Classically bound",
    "Klein & zart" to "Small & delicate",
    "Kleine Geschenke" to "Small gifts",
    "Kleine Runde" to "Small group",
    "Kochen und Freunde einladen" to "Cooking and inviting friends over",
    "Kochkurs" to "Cooking class",
    "Kommt auf den Tag an" to "Depends on the day",
    "Kommt drauf an" to "Depends",
    "Kommt mit" to "Comes with us",
    "Konzert" to "Concert",
    "Kräftige Farben" to "Vibrant colors",
    "Kräuterbeet" to "Herb garden",
    "Kultur & Sehenswürdigkeiten" to "Culture & Sights",
    "Kuscheln" to "Cuddling",
    "Kuss senden" to "Send a kiss",
    "Körperliche Annäherung" to "Physical approach",
    "Körperliche Nähe" to "Physical closeness",
    "Küche" to "Kitchen",
    "Land" to "Countryside",
    "Landhaus" to "Country house",
    "Landhausstil" to "Country house style",
    "Lange wach bleiben" to "Stay up late",
    "Lappland" to "Lapland",
    "Lappland, Finnland" to "Lapland, Finland",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Let your partner inspire you to be your best self",
    "Lehne ab" to "Decline",
    "Leidenschaft" to "Passion",
    "Liebe im Gleichgewicht" to "Love in Balance",
    "Liebe sie, macht mehr Spaß" to "Love them, it's more fun",
    "Lieber durchgeplant oder spontan?" to "Rather fully planned or spontaneous?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Prefer a quiet evening together or out with people?",
    "Lieber nicht" to "Prefer not to",
    "Lieber vorher grob absprechen" to "Prefer to roughly agree beforehand",
    "London" to "London",
    "London, England" to "London, England",
    "Lügen" to "Lies",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Would you prefer a public or private proposal?",
    "Malediven" to "Maldives",
    "Man sollte nie streitend einschlafen." to "You should never go to sleep angry.",
    "Mango Sorbet" to "Mango sorbet",
    "Markant & breit" to "Striking & wide",
    "Mediterraner Innenhof" to "Mediterranean courtyard",
    "Mehr Unterstützung" to "More support",
    "Mehr gemeinsame Zeit" to "More time together",
    "Mehr zuhören" to "Listen more",
    "Mehrgenerationenhaus" to "Multi-generational home",
    "Mein Arbeitsplatz" to "My workplace",
    "Mein Partner" to "My partner",
    "Mich überraschen" to "Surprise me",
    "Minimalistisches Interieur" to "Minimalist interior",
    "Missverständnisse" to "Misunderstandings",
    "Mit Familie und engen Freunden" to "With family and close friends",
    "Mit Kompromissen" to "With compromises",
    "Mittelweg mit besonderen Details" to "Middle ground with special details",
    "Modern geometrisch" to "Modern geometric",
    "Moderne Grillstation" to "Modern BBQ station",
    "Moderner Name" to "Modern name",
    "Moderner Solitär" to "Modern solitaire",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "Capture moment",
    "Momente" to "Moments",
    "Monaco" to "Monaco",
    "Moralische Werte" to "Moral values",
    "Museum" to "Museum",
    "Musik" to "Music",
    "Mädchen" to "Girl",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Are you sure you want to leave the quiz? Your progress so far will be saved.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Would you like pets to be present during the proposal?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Would you like the moment to be shared on social media immediately?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "We might need to make budget cutbacks",
    "Müssen es planen" to "We have to plan it",
    "Müssen sparen" to "We have to save",
    "Nachricht an" to "Message to",
    "Name Partnerin" to "Partner's name",
    "Namen und Startdatum eurer Beziehung." to "Your names and relationship start date.",
    "Natursteinfassade" to "Natural stone facade",
    "Naturteich" to "Natural pond",
    "Nein, einfach halten" to "No, keep it simple",
    "Nein, erstmal privat halten" to "No, keep it private at first",
    "Nein, lieber vor Ort" to "No, prefer local",
    "Nein, modern halten" to "No, keep it modern",
    "Nein, nur wir" to "No, just us",
    "Nein, zu ablenkend" to "No, too distracting",
    "Neubau mit Smart Home" to "Modern smart home building",
    "Neubau mit Technik" to "New build with tech",
    "Neue Liebe, neue Erfahrungen" to "New Love, New Experiences",
    "Neues Hobby" to "New hobby",
    "Neues Spiel" to "New game",
    "New York" to "New York",
    "New York, USA" to "New York, USA",
    "Nicht mein Fall" to "Not my thing",
    "Nicht nötig, lieber klassisch bleiben" to "Not necessary, prefer to keep it classic",
    "Nichts — es passt so" to "Nothing — it's good as it is",
    "Niemand" to "Neither",
    "Niemand ohne Plan" to "Nobody without a plan",
    "Nizza" to "Nice",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "No moments yet.\nCapture your first memory 💞",
    "Nur bei wichtigen Themen" to "Only for important topics",
    "Nur wir beide" to "Just the two of us",
    "Nähe & Intimität" to "Closeness & Intimacy",
    "Obstgarten" to "Orchard",
    "Oder" to "Or",
    "Offene Küche" to "Open kitchen",
    "Offene Wohnküche" to "Open-plan kitchen-living area",
    "Ohne Stein" to "Without stone",
    "Open End" to "Open end",
    "Outdoor-Küche" to "Outdoor kitchen",
    "Outdoor-Sofa" to "Outdoor sofa",
    "Outdoor-Whirlpool" to "Outdoor whirlpool",
    "Ovaler Diamant" to "Oval diamond",
    "Paar" to "Pair",
    "Paar-Statistiken" to "Couple statistics",
    "Paris" to "Paris",
    "Paris, Frankreich" to "Paris, France",
    "Partner" to "Partner",
    "Partner-Simulator" to "Partner simulator",
    "Partnerin" to "Partner",
    "Party Edition" to "Party Edition",
    "Party Edition II" to "Party Edition II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Does a pet fit into our daily routine at all?",
    "Pasta" to "Pasta",
    "Pastell" to "Pastel",
    "Penthouse mit Ausblick" to "Penthouse with a view",
    "Pergola mit Lounge" to "Pergola with lounge",
    "Pfingstrosen" to "Peonies",
    "Pinguin" to "Penguin",
    "Pistazie" to "Pistachio",
    "Pizza" to "Pizza",
    "Pizzaofen" to "Pizza oven",
    "Platin" to "Platinum",
    "Pool" to "Pool",
    "Pop" to "Pop",
    "Prasselnder Kamin" to "Crackling fireplace",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Princesses, Pirates and Pixie Dust: Disney Quiz",
    "Privater Innenhof" to "Private courtyard",
    "Profil" to "Profile",
    "Profil bearbeiten" to "Edit Profile",
    "Prozentual nach Einkommen" to "Proportional to income",
    "Quiz verlassen" to "Leave Quiz",
    "Quiz verlassen?" to "Leave quiz?",
    "Rausgehen in die Natur" to "Going out into nature",
    "Reden vor ..." to "Talk before ...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Schedule regular date nights or quality time together",
    "Reisen" to "Travel",
    "Reiseziele" to "Travel destinations",
    "Respektlosigkeit" to "Disrespect",
    "Restaurant" to "Restaurant",
    "RnB / Soul" to "RnB / Soul",
    "Rock" to "Rock",
    "Rom" to "Rome",
    "Rom, Italien" to "Rome, Italy",
    "Romantik" to "Romance",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Romantic gestures like messages, notes, or small gifts make me happy.",
    "Romantische Stimmung" to "Romantic mood",
    "Roségold" to "Rose gold",
    "Ruhig zu zweit" to "Quietly together",
    "Runder Diamant" to "Round diamond",
    "Salted Caramel" to "Salted caramel",
    "Sammle Ideen..." to "Gathering ideas...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Greece",
    "Saphir" to "Sapphire",
    "Saunahaus" to "Sauna house",
    "Schickes Restaurant oder Hotel" to "Fancy restaurant or hotel",
    "Schlafzimmer" to "Bedroom",
    "Schließen" to "Close",
    "Schmal & zart" to "Narrow & delicate",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Snapshots from our love story",
    "Schokolade" to "Chocolate",
    "Schreib frei, was dir wirklich dazu einfällt." to "Write what truly comes to mind.",
    "Schreibe deine eigene Antwort" to "Write your own answer",
    "Sehr gerne" to "Very much",
    "Sehr leicht" to "Very easy",
    "Sehr wichtig — Fotos und Video" to "Very important — photos and video",
    "Sehr wichtig, es sollte persönlich sein" to "Very important, it should be personal",
    "Selbst kochen" to "Cook ourselves",
    "Senden" to "Send",
    "Separate Küche" to "Separate kitchen",
    "Serie schauen" to "Watch a series",
    "Serienmarathon auf dem Sofa" to "Series marathon on the couch",
    "Sex & Liebe" to "Sex & Love",
    "Seychellen" to "Seychelles",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Are we able to cover all costs for a child/children? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Should the proposal be a surprise?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Should the proposal include cultural or traditional elements?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Should the proposal include cultural or traditional elements?",
    "Sommerhochzeit" to "Summer wedding",
    "Sonnige Dachterrasse" to "Sonnige Dachterrasse",
    "Sowohl als auch" to "Both",
    "Spazieren" to "Spazieren",
    "Spaß & Abenteuer" to "Fun & Adventure",
    "Speichern" to "Save",
    "Spiel bearbeiten" to "Edit game",
    "Spielbereich für Kinder" to "Spielbereich für Kinder",
    "Spiele" to "Games",
    "Spiele & Städte bearbeiten, Ordner reinladen, Bilder anpassen" to "Edit games & cities, import folders, adjust images",
    "Spiele spielen und Spaß haben" to "Spiele spielen und Spaß haben",
    "Spontan" to "Spontaneous",
    "Sportplatz" to "Sportplatz",
    "Sprache" to "Language",
    "Stadt" to "City",
    "Stadt oder Land — was ist uns wichtiger?" to "City or countryside — which is more important to us?",
    "Stadtvilla" to "Stadtvilla",
    "Standesamt & Party" to "Standesamt & Party",
    "Statement-Ring" to "Statement-Ring",
    "Stilvolles Outdoor-Sofa" to "Stilvolles Outdoor-Sofa",
    "Stimme voll zu" to "Stimme voll zu",
    "Stimmt" to "Agree",
    "Stimmt nicht" to "Disagree",
    "Stimmt, noch nie" to "Stimmt, noch nie",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Strandtag",
    "Streit über Haushalt" to "Arguments about household",
    "Ständig" to "Ständig",
    "Suche schließen" to "Close search",
    "Suche zurücksetzen" to "Reset search",
    "Suche öffnen" to "Open search",
    "Suchergebnisse" to "Search results",
    "Sushi" to "Sushi",
    "Süß" to "Süß",
    "Tage zusammen 💞" to "days together 💞",
    "Teile alle deine Hobbys mit deinem Partner" to "Teile alle deine Hobbys mit deinem Partner",
    "Teils teils" to "Somewhat agree",
    "Testen" to "Test",
    "Tiefe Gespräche" to "Deep conversations",
    "Tiefgründige Gespräche führen" to "Tiefgründige Gespräche führen",
    "Tierpension" to "Pet boarding",
    "Tiny House" to "Tiny House",
    "Tippen zum Auswählen & Scrollen" to "Tap to select & scroll",
    "Tippen zum Zuklappen" to "Tap to collapse",
    "Titel" to "Title",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Title, category, topic, tags, questions...",
    "Tokyo, Japan" to "Tokyo, Japan",
    "Traditioneller Name" to "Traditional name",
    "Traumhaus Außenbereich" to "Dream House Outdoor Area",
    "Traumhochzeit" to "Dream Wedding",
    "Treffer" to "Matches",
    "Tägliche Aktivität" to "Daily activity",
    "Umformulieren" to "Rewrite",
    "Unbeliebte Meinungen" to "Unpopular Opinions",
    "Universal Studios Genie oder Neuling?" to "Universal Studios Genius or Rookie?",
    "Uns auseinanderzuleben" to "Uns auseinanderzuleben",
    "Unser Intimleben" to "Our Intimate Life",
    "Unser Traumhaus" to "Our Dream House",
    "Unser erstes Treffen" to "Unser erstes Treffen",
    "Unsere Gesichter" to "Unsere Gesichter",
    "Unsere nächste Reise" to "Unsere nächste Reise",
    "Unter 1000" to "Under 1000",
    "Unter 1000 im Monat" to "Under 1000 a month",
    "Unter 50€/Monat" to "Under 50€/month",
    "Unter Leuten" to "Unter Leuten",
    "Untreue" to "Untreue",
    "Urlaub" to "Vacation",
    "Vanille" to "Vanille",
    "Venedig" to "Venedig",
    "Venedig, Italien" to "Venedig, Italien",
    "Verbinde dich mit" to "Connect with",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Connect with \${profile.partnerName} to see the answer",
    "Verbindung" to "Connection",
    "Verbringe die Feiertage mit deiner Familie" to "Spend the holidays with your family",
    "Verlobungsringe" to "Engagement Rings",
    "Vertrautheit" to "Vertrautheit",
    "Viel getrennt" to "A lot apart",
    "Vielleicht ein oder zwei" to "Vielleicht ein oder zwei",
    "Vielleicht, aber mündlich reicht" to "Maybe, but verbal is enough",
    "Vielleicht, wenn es machbar ist" to "Maybe, if it works out",
    "Vielleicht, wenn es passt" to "Maybe, if it fits",
    "Vintage Art déco" to "Vintage Art déco",
    "Vintage verspielt" to "Vintage verspielt",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Von deinem Partner in neue Hobbys eingeführt werden",
    "Vor dem Kauf eines Hauses besprechen" to "Discuss before buying a house",
    "Vor der Anschaffung eines Haustiers besprechen" to "Discuss before getting a pet",
    "Vor der gemeinsamen Reise besprechen" to "Discuss before travelling together",
    "Vor nichts" to "Vor nichts",
    "Vorort" to "Suburb",
    "Walnuss" to "Walnuss",
    "Wandern" to "Wandern",
    "Wann fühlst du dich mir am nächsten?" to "Wann fühlst du dich mir am nächsten?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Wann fühlst du dich mir körperlich am nächsten?",
    "Was bedeutet Vertrauen für dich konkret?" to "Was bedeutet Vertrauen für dich konkret?",
    "Was entspannt dich mehr?" to "Was entspannt dich mehr?",
    "Was fehlt dir über die Distanz am meisten?" to "Was fehlt dir über die Distanz am meisten?",
    "Was gefällt dir an deinem Zuhause am besten?" to "What do you like most about your home?",
    "Was hast du von deinem Partner gelernt?" to "Was hast du von deinem Partner gelernt?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "What do you think of props (e.g. signs, balloons, etc.)?",
    "Was ist das Wichtigste beim Antrag?" to "What is the most important thing about the proposal?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Was ist dein Lieblingsfoto von uns? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Was ist deine größte Angst vor dem Zusammenleben?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Was ist für dich ein absoluter Dealbreaker?",
    "Was ist für jeden von uns das absolute Highlight?" to "What is the absolute highlight for each of us?",
    "Was ist passiert?" to "What happened?",
    "Was macht einen Moment für dich romantisch?" to "Was macht einen Moment für dich romantisch?",
    "Was magst du an deinem Partner am liebsten?" to "Was magst du an deinem Partner am liebsten?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Was magst du lieber: früh aufstehen oder lange wach bleiben?",
    "Was magst du lieber?" to "Which do you prefer?",
    "Was möchtest du eigentlich sagen?" to "What do you really want to say?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Was möchtest du, dass dein Partner öfter tut?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "What happens to the pet when we travel?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "What do you hope our child becomes when they grow up?",
    "Was war dein schönster Moment mit mir bisher?" to "Was war dein schönster Moment mit mir bisher?",
    "Was wir gegessen haben" to "Was wir gegessen haben",
    "Was wollt ihr nie vergessen?" to "What do you never want to forget?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Was würdest du an einem gemeinsamen Tag am liebsten machen?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "What would you change immediately if money were no object?",
    "Weiter" to "Next",
    "Weiter spielen" to "Keep playing",
    "Weiß ich noch nicht" to "I don't know yet",
    "Weiße Rosen" to "Weiße Rosen",
    "Weißgold" to "Weißgold",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "What kind of setting would you wish for a proposal?",
    "Welcher Raum sagt am meisten über dich aus?" to "Which room says the most about you?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "What budget do we plan for food and vet costs?",
    "Welches Lied macht dich an? 🥵" to "Welches Lied macht dich an? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Welches gemeinsame Foto ist dein Lieblingsfoto?",
    "Wellnessbad" to "Wellnessbad",
    "Wenn es schwierig ist" to "Wenn es schwierig ist",
    "Wenn ich müde bin" to "Wenn ich müde bin",
    "Wenn wir uns lange umarmen" to "Wenn wir uns lange umarmen",
    "Wenn wir zusammen lachen" to "Wenn wir zusammen lachen",
    "Wer findet die besten Restaurants?" to "Wer findet die besten Restaurants?",
    "Wer gibt mehr Herzlichkeit?" to "Wer gibt mehr Herzlichkeit?",
    "Wer hat den besseren Musikgeschmack?" to "Wer hat den besseren Musikgeschmack?",
    "Wer hängt mehr an seinen Eltern?" to "Wer hängt mehr an seinen Eltern?",
    "Wer ist besser organisiert?" to "Wer ist besser organisiert?",
    "Wer ist der Beste bei der Filmauswahl?" to "Wer ist der Beste bei der Filmauswahl?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Wer ist der Beste bei der Planung romantischer Dates?",
    "Wer ist der beste Tänzer?" to "Wer ist der beste Tänzer?",
    "Wer ist romantischer?" to "Wer ist romantischer?",
    "Wer kocht besser?" to "Wer kocht besser?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Who handles renovations and maintenance?",
    "Wer vergisst eher einen Jahrestag?" to "Wer vergisst eher einen Jahrestag?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Who would be more likely to forget their own name the next morning?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Who would be more likely to find a video the next day they had no memory of?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Who would be more likely to sleep on a stranger's couch?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Who would be more likely to fall asleep at the party and wake up with Sharpie on their face?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Who would be more likely to slip on the dance floor and make it look like a cool move?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Who would be more likely to hijack the Spotify playlist at a house party?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Who would be more likely to order pizza for everyone at a party and eat it all themselves?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Who would be more likely to be the first one to fall asleep at a party?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Who would be more likely to suddenly start cleaning up at a party?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Who would be more likely to claim they're totally sober when the opposite is true?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Wer würde eher bei einem Streit als Erstes einlenken?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Who would be more likely to cheat in a drinking game?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Who would be more likely to raid the buffet and sneak food home?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Who would be more likely to post the most embarrassing photo of the night on their story?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Who would be more likely to annoy the DJ to request their favorite song?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Who would be more likely to sing song lyrics wrong with absolute confidence?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Who would be more likely to order the most expensive drink on the menu and regret it?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Who would be more likely to invite the neighbors inside when they complain about the noise?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Who would be more likely to take party games (like beer pong) way too seriously?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Who would be more likely to befriend the bouncers to get VIP access?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Who would be more likely to start a spontaneous karaoke battle?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Who would be more likely to open a bottle without using a bottle opener?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Who would be more likely to give a speech when absolutely nobody asked for one?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Who would be more likely to spend an hour in the bathroom taking selfies?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Who would be more likely to pull off an embarrassing dance performance and embrace it?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Who would be more likely to call an ex after the party is over?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Who would be more likely to accidentally insult a random guest?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Who would be more likely to secretly leave the party without saying goodbye (Irish exit)?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Who would be more likely to play with the host's pet instead of talking to guests?",
    "Wer würde eher spontan eine Reise buchen?" to "Wer würde eher spontan eine Reise buchen?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Who would be more likely to spend hours having deep conversations in the kitchen?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Who would be more likely to accidentally drink someone else's drink?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Who would be more likely to accidentally knock over an expensive vase or something fragile?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Who would be more likely to attempt making a complicated cocktail and fail miserably?",
    "Wer würde eher zu spät kommen?" to "Wer würde eher zu spät kommen?",
    "Wer würde eher?" to "Who's more likely?",
    "Wer übernimmt die tägliche Versorgung?" to "Who will handle daily care?",
    "Werde so akzeptiert, wie du bist" to "Werde so akzeptiert, wie du bist",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Will we have enough time for the child/children? ⌛",
    "Whirlpool" to "Whirlpool",
    "White Chocolate" to "White Chocolate",
    "Widgets" to "Widgets",
    "Wie fühlst du dich am meisten geliebt?" to "Wie fühlst du dich am meisten geliebt?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Wie gehen wir mit unterschiedlichen Einkommen um?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Wie kann dein Partner am besten Sex mit dir initiieren?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Wie kann dein Partner ein noch besserer Partner für dich sein?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "How long after the proposal would you like to celebrate with others?",
    "Wie lange wollen wir dort mindestens bleiben?" to "How long do we plan to stay there at minimum?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Wie leicht fällt es dir, über Wünsche zu sprechen?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "How do you want our future to look?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "What does your perfect Sunday at home look like?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Wie stehst du zu schmutzigem Gerede beim Sex?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "How much mortgage can we realistically afford?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "How much time do we want to spend apart?",
    "Wie viel wollen wir insgesamt ausgeben?" to "How much do we want to spend in total?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "How will we find time for our relationship when the baby arrives?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "How important is it to you that the moment is captured?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?",
    "Wie würdest du sie/ihn nennen?" to "What would you name him/her?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?",
    "Wildblumen" to "Wildblumen",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Do you want a girl or a boy? 👶",
    "Wintergarten" to "Wintergarten",
    "Winterhochzeit" to "Winterhochzeit",
    "Wir entscheiden es gemeinsam" to "Wir entscheiden es gemeinsam",
    "Wir treffen uns in der Mitte" to "Wir treffen uns in der Mitte",
    "Wird stressig" to "It will be stressful",
    "Wobei lachst du am meisten?" to "Wobei lachst du am meisten?",
    "Wofür sparen wir gemeinsam?" to "Wofür sparen wir gemeinsam?",
    "Wohnzimmer" to "Wohnzimmer",
    "Woran erinnerst du dich am lebhaftesten?" to "Woran erinnerst du dich am lebhaftesten?",
    "Worauf freust du dich bei uns am meisten?" to "Worauf freust du dich bei uns am meisten?",
    "Worte/Komplimente" to "Words/Compliments",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Wovor hast du in unserer Beziehung am meisten Angst?",
    "Wünsche? z.B. günstig, draußen" to "Wishes? e.g. budget-friendly, outdoors",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Would you prefer a proposal on vacation (combined with travel)?",
    "Zeichne für mich" to "Draw for me",
    "Zeichne mich als Tier — welches wäre ich?" to "Zeichne mich als Tier — welches wäre ich?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Zeichne unser Gefühl zueinander als Symbol.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?",
    "Zeichnen" to "Draw",
    "Zeit, wenn das Baby schläft" to "Time when the baby sleeps",
    "Zelten gehen" to "Zelten gehen",
    "Zitrone" to "Zitrone",
    "Zu Hause, gemütlich und privat" to "Zu Hause, gemütlich und privat",
    "Zu einem Picknick gehen" to "Zu einem Picknick gehen",
    "Zu einem ausgefallenen Abendessen gehen" to "Zu einem ausgefallenen Abendessen gehen",
    "Zu zweit reisen" to "Travel as a couple",
    "Zuhause & Alltag" to "Home & everyday life",
    "Zuhören" to "Listen",
    "Zurück" to "Back",
    "Zusammen seit" to "Together since",
    "Zusammen seit (TT.MM.JJJJ)" to "Together since (DD.MM.YYYY)",
    "Zusammenziehen" to "Zusammenziehen",
    "Zustimmen oder Ablehnen" to "Agree or Disagree",
    "Zwei Kreise, die sich überschneiden" to "Zwei Kreise, die sich überschneiden",
    "Zwei Stühle davor" to "Zwei Stühle davor",
    "Zärtlich sein" to "Be affectionate",
    "aufwaermen" to "aufwaermen",
    "custom_gourmet_eissorten" to "custom_gourmet_eissorten",
    "dasoderdas" to "This or That",
    "disney" to "disney",
    "entertainment" to "entertainment",
    "familie" to "Family",
    "games" to "games",
    "harrypotter" to "harrypotter",
    "hochzeit" to "Wedding",
    "ichhabenochnie" to "ichhabenochnie",
    "kinder" to "Children",
    "oder" to "or",
    "parks" to "parks",
    "party" to "party",
    "reden" to "Discussion",
    "reisen" to "Travel",
    "tot" to "tot",
    "universal" to "universal",
    "unterhaltung" to "Entertainment",
    "wer" to "wer",
    "werwuerde" to "werwuerde",
    "zuhause" to "zuhause",
    "{partner}" to "{partner}",
    "{user}" to "{user}",
    "Öfter als ich zugebe" to "Öfter als ich zugebe",
    "Über 100€/Monat" to "Over 100€/month",
    "Über 2000 im Monat" to "Over 2000 a month",
    "Über mich selbst" to "Über mich selbst",
    "Übernehmen" to "Save",
    "Überraschend" to "Surprising",
    "Überraschung" to "Überraschung",
    "Überspringen" to "Skip",
    "Übertrieben und großartig" to "Übertrieben und großartig",
    "☀️" to "☀️",
    "✎ Tippe, um zu antworten" to "✎ Tap to answer",
    "✨ GFK-Brücke" to "✨ NVC Bridge",
    "❤️" to "❤️",
    "🛠️ Entwickler-Modus" to "🛠️ Developer Mode",
    "Essen & Genuss" to "Food & Dining",
    "Marken & Alltag" to "Brands & Everyday Life",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "What is a food you love that your partner cannot understand?",
    "Etwas sehr Scharfes" to "Something very spicy",
    "Ein ungewöhnliches Gericht" to "An unusual dish",
    "Ein Kindheitsessen" to "A childhood meal",
    "Etwas, das ich selbst gern erfinde" to "Something I like inventing myself",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "What would be worse for you: never eating pizza again or never eating burgers again?",
    "Nie wieder Pizza" to "Never pizza again",
    "Nie wieder Burger" to "Never burgers again",
    "Beides wäre schlimm" to "Both would be terrible",
    "Ich finde eine Alternative" to "I'll find an alternative",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Who decides faster what to order?",
    "Wir brauchen ewig" to "We take forever",
    "Wir bestellen einfach beides" to "We just order both",
    "McDonald’s" to "McDonald’s",
    "Burger King" to "Burger King",
    "iPhone" to "iPhone",
    "Android" to "Android",
    "Netflix" to "Netflix",
    "Kino" to "Cinema",
    "Nike" to "Nike",
    "Adidas" to "Adidas",
    "Spotify" to "Spotify",
    "YouTube Music" to "YouTube Music",
    "PlayStation" to "PlayStation",
    "Xbox" to "Xbox",
    "Coca-Cola" to "Coca-Cola",
    "Pepsi" to "Pepsi",
    "IKEA" to "IKEA",
    "Möbelhaus" to "Furniture store",
    "Amazon" to "Amazon",
    "Lokal einkaufen" to "Shopping locally",
    "Disney" to "Disney",
    "Studio Ghibli" to "Studio Ghibli",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Who notices faster when the other isn't doing well?",
    "Kommt darauf an" to "It depends",
    "Wer sucht am Ende wirklich den Film aus?" to "Who actually ends up picking the movie?",
    "Wir wechseln uns ab" to "We take turns",
    "Wir einigen uns nie" to "We never agree",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Which trait should our child definitely inherit from us?",
    "Humor" to "Humor",
    "Mut" to "Courage",
    "Mitgefühl" to "Compassion",
    "Neugier" to "Curiosity",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "What should we never lose sight of as parents?",
    "Zeit füreinander" to "Time for each other",
    "Geduld" to "Patience",
    "Unsere eigenen Träume" to "Our own dreams",
    "Leichtigkeit" to "Lightheartedness",
    "Was war dein schönster Moment mit mir bisher?" to "What has been your most beautiful moment with me so far?",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Which photo of us together is your favorite?",
    "essen" to "Food",
)
