package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_ESTONIAN_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1–5 aastat",
    "1000 - 1500 im Monat" to "1000–1500 kuus",
    "1000 bis 3000" to "1000 kuni 3000",
    "1500 - 2000 im Monat" to "1500–2000 kuus",
    "3000 bis 5000" to "3000 kuni 5000",
    "5-10 Jahre" to "5–10 aastat",
    "50-100€/Monat" to "50-100 €/kuus",
    "Ab 100€" to "Alates 100 eurost",
    "Ab 500€" to "Alates 500 eurost",
    "Ab 50€" to "Alates 50 eurost",
    "Ab und zu" to "Aeg-ajalt",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Kui palju peame enne ostu sooritamist kulutama?",
    "Abbrechen" to "Tühista",
    "Abenteuer" to "Seiklus",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Tegevused",
    "Alle" to "Kõik",
    "Alle Pakete" to "Kõik paketid",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Kaota kõik oma sõbrad peale parima sõbra",
    "Alle intimen Momente selbst initiieren" to "Algatage kõik intiimsed hetked ise",
    "Alles davon" to "Kõik see",
    "Alles, was noch kommt" to "Kõik, mis tuleb",
    "Alltagsroutine" to "Igapäevane rutiin",
    "Alltägliche Berührungen" to "Igapäevased puudutused",
    "Altbau mit Charme" to "Vana hoone võlu",
    "Am Strand" to "Rannas",
    "Am liebsten alles zusammen" to "Eelistatavalt kõik koos",
    "Am selben Tag mit Freunden/Familie" to "Samal päeval sõprade/perega",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Holland",
    "An das Gefühl" to "Tundest",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "Avalikus kohas, kus on palju pealtvaatajaid",
    "An einen Geruch" to "Lõhna järgi",
    "An einen Song" to "Loole",
    "An etwas, das ich gesagt habe" to "Midagi ma ütlesin",
    "Analyse starten" to "Alustage analüüsi",
    "Analysiere eure Muster..." to "Analüüsige oma mustreid...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Analüüsige oma vastuseid ja vestlusi Gottmani ja GFK järgi.",
    "Ananas auf der Pizza schmeckt köstlich." to "Ananass pitsal maitseb hõrgult.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Vasta fotoga",
    "Antwortähnlichkeit" to "Vastuste sarnasus",
    "App-Sprache auswählen" to "Valige rakenduse keel",
    "Auf eine Bootsparty gehen" to "Lähen paadipeole",
    "Aufmerksamkeit" to "Tähelepanu",
    "Aufräumen und Projekte angehen" to "Koristage projekte ja tegelege nendega",
    "Aufwärmen" to "Soojendage",
    "Aufwärmen: Einander kennenlernen" to "Soojendus: üksteisega tutvumine",
    "Aus dem Urlaub" to "Puhkusest",
    "Ausgefallener Name" to "Väljamõeldud nimi",
    "Ausschlafen und faulenzen" to "Magage ja laisklege",
    "Ausschlafen und nichts tun" to "Magage ja ärge tehke midagi",
    "Aussehen" to "Välimus",
    "Auto" to "Automaatne",
    "Außenkamin" to "Välikamin",
    "BEANTWORTE" to "VASTUS",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indoneesia",
    "Banane" to "Banaan",
    "Beantwortet" to "Vastatud",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Vastake küsimustele samal ajal – vastuseid ei kuvata enne, kui olete mõlemad lõpetanud.",
    "Beantwortete Fragen" to "Vastatud küsimustele",
    "Bearbeiten" to "Redigeeri",
    "Bei Insider-Witzen" to "Sisemiste naljade jaoks",
    "Bei Memes" to "Meemide kohta",
    "Bei einer spontanen Berührung" to "Spontaansel puudutamisel",
    "Beide" to "Mõlemad",
    "Beide gleich" to "Mõlemad samad",
    "Beide zusammen" to "Mõlemad koos",
    "Beide, aber wir tun so als ob nicht" to "Mõlemad, aga me teeskleme, et mitte",
    "Beides" to "Mõlemad",
    "Beides wäre schlimm" to "Mõlemad oleksid halvad",
    "Beim Einschlafen nebeneinander" to "Kõrvuti magama jäämine",
    "Beim Reden" to "Rääkimise ajal",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Kuulsad turismipaigad valmistavad alati pettumuse.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Kirjeldage meie seksuaalelu emotikoniga.",
    "Besser kommunizieren" to "Suhtle paremini",
    "Bessere Lage" to "Parem asukoht",
    "Bestellen" to "Käsk",
    "Besuchte Länder" to "Külastatud riigid",
    "Besuchte Städte" to "Külastatud linnad",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Kas eelistate ekstravagantset ettepanekut või midagi peent?",
    "Beziehung" to "Suhe",
    "Bibliothek" to "raamatukogu",
    "Bin manchmal unsicher" to "Olen mõnikord ebakindel",
    "Bist du ein Videospiel-Guru?" to "Kas olete videomänguguru?",
    "Blumenwiese" to "Lilleniit",
    "Bunte Blumenwiese" to "Värviline lilleniit",
    "Burger" to "Burgerid",
    "Burger King" to "Burger King",
    "Chat" to "Vestlus",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Küpsisetainas",
    "Dachgarten mit Lounge" to "Katuseaed koos puhketoaga",
    "Dachterrasse" to "Katuseterrass",
    "Das Wetter an dem Tag" to "Ilm sellel päeval",
    "Das erste Selfie" to "Esimene selfie",
    "Das meiste weiß ich" to "Ma tean enamikku sellest",
    "Das oder das?" to "Seda või teist?",
    "Das tägliche Leben" to "Igapäevaelu",
    "Dass Zusagen gehalten werden" to "Et lubadusi peetakse",
    "Dass alles meinen Stil hat" to "Et kõigel on minu stiil",
    "Dass ich alles erzählen kann" to "Et ma võin kõike rääkida",
    "Dass ich mich nicht sorgen muss" to "Et ma ei peaks muretsema",
    "Dass wir ungestört sind" to "Et me oleksime häirimatud",
    "Dein Name" to "Teie nimi",
    "Deine Antwort..." to "Teie vastus...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Teie vastused on salvestatud. Niipea, kui Partner paketi lõpetab, on mõlemad vastused koos nähtavad.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Teie vastused on salvestatud. Kui \${profile.partnerName} on paketi lõpule viinud, on mõlemad vastused koos nähtavad.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Muutke oma suhe seikluslikuks ja spontaanseks",
    "Deine Beziehung stabil und sicher machen" to "Muutke oma suhe stabiilseks ja turvaliseks",
    "Deine eigene Antwort" to "Teie enda vastus",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Parem on jagada oma sügavaimaid saladusi oma partneriga",
    "Deinen besten Freund verlieren" to "Parima sõbra kaotamine",
    "Denke an dich" to "Mõelge iseendale",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Sama filmi kaks korda vaatamine on ajaraiskamine.",
    "Der Blick nach draußen" to "Vaade väljast",
    "Der Garten" to "Aed",
    "Der Ort" to "Koht",
    "Der Ring und die Geste" to "Helin ja žest",
    "Der perfekte Heiratsantrag" to "Ideaalne abieluettepanek",
    "Derjenige sein, der umarmt wird" to "Olge see, keda kallistatakse",
    "Deutsch" to "saksa keel",
    "Diamant" to "Teemant",
    "Diamanten im Band" to "Teemandid bändis",
    "Die Distanz" to "Kaugus",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Veetke pühad oma partneri perega",
    "Die Gemütlichkeit und Ruhe" to "Mugavus ja rahu",
    "Die Menschen, die darin wohnen" to "Inimesed, kes selles elavad",
    "Die Umgebung und Atmosphäre" to "Keskkond ja atmosfäär",
    "Die Worte und Emotionen" to "Sõnad ja emotsioonid",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Ülim meelelahutuslik väljakutse",
    "Diejenige sein, die umarmt" to "Ole see, kes kallistab",
    "Direkt ansprechen" to "Aadress otse",
    "Diskussion" to "Arutelu",
    "Diskutiere vor dem Kinderkriegen" to "Arutage enne laste saamist",
    "Diskutiert eure Antworten" to "Arutage oma vastuseid",
    "Disney" to "Disney",
    "Doch, schon mal" to "Jah, jah",
    "Draußen mit der Natur als Kulisse" to "Väljas, taustaks loodus",
    "Drei-Stein-Ring" to "Kolme kivi sõrmus",
    "Du bist dran" to "On teie kord",
    "Du fehlst mir" to "Ma igatsen sind",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubai, AÜE",
    "Dunkles Design" to "Tume teema",
    "Durch Berührung" to "Puudutusega",
    "Durch Worte" to "Sõnade kaudu",
    "Durch Zeit zu zweit" to "Läbi ühise aja",
    "Durch kleine Gesten" to "Väikeste žestide kaudu",
    "Durchgeplant" to "Hästi planeeritud",
    "ERGEBNISSE" to "TULEMUSED",
    "Egal, Hauptsache gesund" to "Mis iganes, peaasi, et terve",
    "Ehepaar Leben" to "Abielupaarielu",
    "Eher knapp" to "Pigem lähedal",
    "Eher nicht" to "Mitte nii väga",
    "Eher schwer" to "Üsna raske",
    "Eher schwierig" to "Üsna raske",
    "Eher zu" to "Rohkem nagu",
    "Eifersucht ist ein Zeichen von Liebe." to "Armukadedus on armastuse märk.",
    "Eigenes Gemüsebeet" to "Oma juurviljalapp",
    "Ein Abenteuer in einer neuen Stadt" to "Seiklus uues linnas",
    "Ein Anker" to "Ankur",
    "Ein Balkon oder Garten" to "Rõdu või aed",
    "Ein Filmabend" to "Filmiõhtu",
    "Ein Harmony-Meilenstein eurer Liebe." to "Teie armastuse harmoonia verstapost.",
    "Ein Herz" to "Süda",
    "Ein Herz an der Tür" to "Süda ukse taga",
    "Ein Jahr lang eine Fernbeziehung führen" to "Sul on kaugsuhe aastaks",
    "Ein Kindheitsessen" to "Lapsepõlve söök",
    "Ein Live-Musik-Konzert besuchen" to "Osalege elava muusika kontserdil",
    "Ein Museum besuchen" to "Külastage muuseumi",
    "Ein Spieleabend" to "Mängude õhtu",
    "Ein Spieleabend mit Freunden" to "Mänguõhtu sõpradega",
    "Ein Urlaubsfoto" to "Puhkusefoto",
    "Ein aktives Abenteuer" to "Aktiivne seiklus",
    "Ein entspannender Spa-Tag" to "Lõõgastav spaapäev",
    "Ein ganz normaler Alltagstag" to "Täiesti tavaline igapäevane päev",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Õdus õhtu majas äikesetormi ajal",
    "Ein gemütliches Date drinnen" to "Hubane kohting siseruumides",
    "Ein lustiges Bild" to "Naljakas pilt",
    "Ein paar Handyfotos reichen" to "Piisab mõnest mobiiltelefonist tehtud fotost",
    "Ein paar Stunden" to "Mõni tund",
    "Ein paar kulturelle Anklänge sind okay" to "Mõned kultuurilised viited on okei",
    "Ein romantischer Abend" to "Romantiline õhtu",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Romantiline õhtusöök küünlavalgel",
    "Ein romantisches Bild" to "Romantiline pilt",
    "Ein romantisches Picknick an einem schönen Ort" to "Romantiline piknik kaunis kohas",
    "Ein schwerer Moment, den wir geschafft haben" to "Raske hetk, millega saime hakkama",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Suurepärane kohting õues kuuvalguses",
    "Ein ungewöhnliches Gericht" to "Ebatavaline roog",
    "Ein zufälliger Schnappschuss" to "Juhuslik hetktõmmis",
    "Einander kennenlernen" to "Üksteise tundmaõppimine",
    "Eine Autoreise" to "Reis",
    "Eine Brücke" to "Sild",
    "Eine Date-Nacht unter den Sternen" to "Kohtinguõhtu tähtede all",
    "Eine Million Dollar gewinnen" to "Võida miljon dollarit",
    "Eine Million Dollar verdienen" to "Teenige miljon dollarit",
    "Eine Nacht in einem Club" to "Öö klubis",
    "Eine Schokoladenverkostung" to "Šokolaadi degusteerimine",
    "Eine Wanderung mit Panoramablick machen" to "Matkake panoraamvaadetega",
    "Eine Weinverkostung" to "Veinide degusteerimine",
    "Eine gemeinsame Reise" to "Reis koos",
    "Eine gemütliche Nacht zu Hause" to "Õdus öö kodus",
    "Eine neue Sprache zu lernen ist einfach." to "Uue keele õppimine on lihtne.",
    "Einen Film anschauen" to "Vaadake filmi",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Kuu aega ei rääkinud üldse",
    "Einen Tanzkurs besuchen" to "Mine tantsutundi",
    "Einen Vergnügungspark erkunden" to "Avastage lõbustusparki",
    "Einen Wellness-Tag" to "Tervisepäev",
    "Einen sehr emotionalen Partner haben" to "Väga emotsionaalne partner",
    "Einen sehr logischen Partner haben" to "Väga loogiline partner",
    "Einer zahlt alles" to "Üks inimene maksab kõik",
    "Einfach mehr Alltag" to "Lihtsalt rohkem igapäevaelu",
    "Einfach nebeneinander sein" to "Olge lihtsalt üksteise kõrval",
    "Einfach und intim" to "Lihtne ja intiimne",
    "Einige Dinge für dich behalten" to "Hoidke mõned asjad enda teada",
    "Einmal" to "Üks kord",
    "Eins, das nur wir kennen" to "Üks, mida teame ainult meie",
    "Englisch" to "inglise keel",
    "Entspannte Hängematte" to "Lõõgastav võrkkiik",
    "Entspannung" to "Lõõgastus",
    "Erdbeere" to "Maasikas",
    "Erfolgreich" to "Õnnestus",
    "Ergebnisse" to "Tulemused",
    "Erst bei sehr großen Summen" to "Ainult väga suurte summade puhul",
    "Erst nur enge Freunde/Familie" to "Algul ainult lähedased sõbrad/perekond",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Mind ajab närvi, kui mu partneril võtab sõnumitele vastamine liiga kaua aega.",
    "Essen & Genuss" to "Toit ja nauding",
    "Essensvorlieben" to "Toidueelistused",
    "Etwa eine Woche später, erst mal nur wir" to "Umbes nädal hiljem, alguses ainult meie",
    "Etwas Neues ausprobieren" to "Proovige midagi uut",
    "Etwas ganz anderes" to "Midagi täiesti erinevat",
    "Etwas sehr Scharfes" to "Midagi väga teravat",
    "Etwas, das ich selbst gern erfinde" to "Midagi, mida mulle meeldib ise välja mõelda",
    "Etwas, eine kleine Note wäre schön" to "Midagi, väike märkus oleks tore",
    "Familie" to "Perekond",
    "Familie/Freunde" to "Perekond/sõbrad",
    "Familienmensch" to "Pereisa",
    "Farbedelstein" to "Värviline kalliskivi",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Telereklaame on mõnikord huvitav vaadata.",
    "Fertig" to "Valmis",
    "Fertig!" to "Valmis!",
    "Feste Date-Nights" to "Fikseeritud kuupäevaõhtud",
    "Feuerstelle" to "Lõkkease",
    "Filigran & schlicht" to "Filigraanne ja lihtne",
    "Filme/Serien" to "Filmid/sarjad",
    "Formuliere um..." to "Sõnastage ümber...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Sõnastage oma mustand ümber vägivallavabalt: tähelepanek, tunne, vajadus, taotlus.",
    "Frage hinzufügen" to "Lisage küsimus",
    "Fragen & Spiele" to "Küsimused ja mängud",
    "Fragen für jede Gelegenheit" to "Küsimusi igaks juhuks",
    "Freizeitpark" to "Lõbustuspark",
    "Freunde treffen" to "Kohtuge sõpradega",
    "Freundschaften mit Ex-Partnern sind okay." to "Sõprussuhted endistega on okei.",
    "Früh aufstehen" to "Tõuse vara üles",
    "Fußbodenheizung" to "Põrandaküte",
    "Führen wir getrennte oder gemeinsame Konten?" to "Kas meil on eraldi või ühised kontod?",
    "Für dich empfohlen" to "Soovitatav teile",
    "Für die Zukunft" to "Tuleviku jaoks",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Selle otsingu jaoks ei leitud ühtegi vastavat küsimust ega mängu.",
    "Für immer" to "Igavesti",
    "Fürsorglichkeit" to "Hoolimine",
    "GFK-Brücke" to "GRP sild",
    "Galerie" to "galerii",
    "Gar nicht, der Moment gehört uns" to "Üldse mitte, hetk on meie",
    "Gar nichts tun" to "Ärge tehke midagi",
    "Geduld" to "Kannatlikkust",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Minge varahommikul päikesetõusu vaatama",
    "Geht so" to "Läheb nii",
    "Geister existieren wirklich." to "Kummitusi on tõesti olemas.",
    "Gelassenheit" to "Rahulikkus",
    "Gelbgold" to "Kollane kuld",
    "Geld & Finanzen" to "Raha ja rahandus",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Reisige koos maailmas, avastage uusi kultuure ja kööke",
    "Gemeinsam ein Lego bauen" to "Ehitage koos Lego",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Proovige koos köögis uut retsepti",
    "Gemeinsame Konten" to "Jagatud kontod",
    "Gemeinsame Nächte" to "Ööd koos",
    "Gemeinsame Tage" to "Päevad koos",
    "Gemischt" to "Segatud",
    "Gemüsebeet" to "Köögiviljaplaaster",
    "Gemütliche Feuerstelle" to "Hubane kamin",
    "Gesprächsanreger" to "Vestluse alustaja",
    "Getrennte Konten" to "Eraldi kontod",
    "Getrennte Urlaube tun einer Beziehung gut." to "Eraldi puhkused on suhtele head.",
    "Gewächshaus" to "Kasvuhoone",
    "Glasfassade" to "Klaasfassaad",
    "Gleichgültigkeit" to "Ükskõiksus",
    "Glücklich und frei" to "Õnnelik ja vaba",
    "Gourmet Eis-Sorten" to "Gurmeejäätisesordid",
    "Gravur innen" to "Graveering sees",
    "Grillplatz" to "Grillimisala",
    "Groß & üppig" to "Suur ja lopsakas",
    "Große Familie" to "Suur pere",
    "Große Feier" to "Suur pidu",
    "Große Fenster" to "Suured aknad",
    "Große Fensterfront" to "Suur aken",
    "Großer Außenpool" to "Suur välibassein",
    "Großer Garten" to "Suur aed",
    "Großer Stein" to "Suur kivi",
    "Größere Küche" to "Suurem köök",
    "Gutes Essen" to "Hea toit",
    "Habe ich" to "Ma tegin",
    "Habe ich noch nie" to "Mul pole kunagi olnud",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Kas olete avastanud üllatavaid erinevusi? Rääkige, miks teile teatud valikud rohkem meeldivad!",
    "Haus am See" to "Maja järve ääres",
    "Haus/Wohnung" to "Maja/korter",
    "Hazelnut" to "Sarapuupähkel",
    "Heimkino" to "Kodukino",
    "Herzhaft" to "Südamlik",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Siin pole praegu midagi.\nMuutke filtrit või valige mõni muu teema.",
    "Hilfe im Alltag" to "Abi igapäevaelus",
    "Himbeere" to "Vaarikas",
    "Hinzufügen" to "Lisa",
    "Hobbys" to "Hobid",
    "Hochzeitssträuße" to "Pulmakimbud",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Sigatüüka maja uhkus: kuhu te kuulute?",
    "Home" to "Avaleht",
    "Hot Tub" to "Mullivann",
    "Humor" to "Huumor",
    "Hund" to "Koer",
    "Hängematte" to "Võrkkiik",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Kas soovite ettepaneku osana kirjalikku kirja?",
    "IKEA" to "IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Eelistan kinoskäimisele romantilisi jalutuskäike pargis.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Ma pole kunagi kinos magama jäänud.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Mulle meeldib koos oma partneriga uusi hobisid või tegevusi avastada.",
    "Ich finde eine Alternative" to "Ma leian alternatiivi",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Mulle meeldib proovida oma partneriga uusi restorane selle asemel, et käia alati samades kohtades.",
    "Ich habe noch nie" to "Ma pole kunagi",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Ma pole kunagi rullnokka kartnud ja sain selle igatahes peale.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Ma pole kunagi Fast Passi pileteid ostnud, sest olin kannatamatu.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Ma pole kunagi tühistanud plaane jääda koju ja telesaadet vaadata.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Ma pole kunagi oodanud oma kirja Sigatüükast.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Ma pole kunagi öelnud, et Slytherin polnud tegelikult nii halb.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Ma pole kunagi öelnud, et olen Disney filmide jaoks liiga vana (ja nautisin neid salaja).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Ma pole kunagi Mario Kartis sinise tankiga kedagi tahtlikult alla tulistanud.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Ma pole kunagi Disney filmi juures nutnud.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Ma pole kunagi õudusfilmi vaadates silmi kinni katnud.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Ma pole kunagi unustanud mängu salvestada ega kaotanud tunde edenemist.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Ma ei ole kunagi piinliku stseeni ajal ruumist lahkunud (krimpsufaktor).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Ma pole kunagi rullnokkfotot tehes naljakat poosi teinud.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Ma pole kunagi hilisõhtuni mänginud ja kahetsenud, kui väsinud ma järgmisel päeval olin.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Ma pole kunagi ühegi filmi lõppu googeldanud, sest ei jõudnud ära oodata.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Ma pole kunagi tundnud, et seisaksin võtteplatsil.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Ma pole kunagi oma lemmiksarja sissejuhatust vahele jätnud.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Ma pole kunagi jaganud kellegi teise Netflixi parooli.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Ma pole kunagi töö või õppimise ajal ühegi mängu heliriba kuulanud.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Ma pole kunagi kaotuses kontrollerit süüdistanud.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Ma pole kunagi vihasena klaviatuuri ega kontrollerit ära visanud.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Ma pole kunagi mõneks päevaks märgasid riideid pesumasinasse unustanud.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Ma pole kunagi mängudes kosmeetikatoodetele päris raha kulutanud.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Ma pole kunagi võõras riigis autoga sõitnud.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Ma pole kunagi duši all ühtegi Disney laulu välja mänginud.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Ma pole kunagi elektriautoga sõitnud.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Ma pole kunagi pargimaskotiga fotot teinud.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Ma pole kunagi pannud lemmikloomale Sigatüüka tegelase järgi nime.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Ma pole kunagi popkorni kinos tilkunud ja ikka söönud.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Ma pole kunagi kasutanud igapäevaelus Tähesõdade meister Yoda tsitaati.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Ma pole kunagi teemapargist ülehinnatud suveniiri ostnud.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Ma pole kunagi soovitanud filmi, mis oleks teisele inimesele kohutav.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Ma pole kunagi keset ööd Oscarit otseülekandes vaadanud.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Ma pole kunagi ühtegi sarja ära jätnud, sest eelmine hooaeg oli nii halb.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Ma pole kunagi ühe päevaga tervet sarja hooaega vaadanud.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Ma pole kunagi ülemusest esimesel katsel jagu saanud ja tundsin end jumalana.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Ma pole kunagi leidnud kangelasest lahedamat kaabakat.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Ma ei ole kunagi oma mänguasjades Toy Story tegelast ära tundnud.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Ma pole kunagi teinud rollimängus täpselt sellist tegelast nagu mina.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Ma pole kunagi teemapargis churrot söönud.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Ma pole kunagi Disney filmi kolm korda järjest vaadanud.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Mul pole terve nädal olnud Disney kaasahaarav lugu.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Ma pole kunagi filmi vaadanud ainult teatud näitleja pärast.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Ma pole kordagi tundide kaupa ühe filmi heliriba kuulanud.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Ma pole kunagi avaldanud filmi spoilerit ja kahetsesin seda kohe.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Ma pole kunagi leidnud sõpra, kes räägiks teist emakeelt.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Mul pole kunagi olnud sõpra, kes oleks teise riiki kolinud.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Ma pole kunagi jõulude ajal Harry Potteri filmimaratoni läbinud.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Ma pole kunagi ühtki Marveli filmi lõpuni vaadanud ainult krediteerimisjärgse stseeni tõttu.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Ma pole kunagi NPC-d (mittemängija tegelane) tahtlikult häirinud.",
    "Ich habe noch nie einen Nachtzug genommen." to "Ma pole kunagi öörongiga sõitnud.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Ma pole kunagi sooritanud veebitesti, et teada saada oma Sigatüüka maja.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Ma pole kunagi sotsiaalmeedia postitust kustutanud, kuna see ei saanud piisavalt meeldimisi.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Ma pole kunagi nimetanud ühtegi päeva teemapargis aasta parimaks päevaks.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Ma pole kunagi teemapargis käinud ja viibisin seal hommikust õhtuni.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Ma pole kunagi Transformeri või Marveli sõidust täielikult lummatud.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Ma ei ole kunagi vihastanud ja mängust lahkunud.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Ma pole kunagi lugenud ühtegi suurt Harry Potteri köidet.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Ma pole kunagi vaimustanud oma lemmiktegelasest sarjas.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Ma pole kunagi unistanud kviditši mängimisest.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Ma pole kunagi salaja googeldanud, kuidas rasket taset lahendada.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Ma pole kunagi salamisi lootnud, et mu lemmikloom oskab rääkida nagu Disney’s.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Ma pole kunagi Simsis basseini juhti eemaldanud.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Ma pole kunagi 3D-simulaatoriga sõites oma suunda kaotanud.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Ma pole kunagi ülikooli spordimeeskonnas mänginud.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Ma pole kunagi ühe atraktsiooni jaoks üle kahe tunni järjekorras seisnud.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Ma pole kunagi oma väärisesemeid veesõidul märjaks saanud.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Ma pole kunagi sõbraga vaielnud, milline maja on parim.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Ma pole kunagi teeselnud, et mul on maagilisi võimeid nagu Elsal.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Ma pole kunagi nii kõvasti naernud, et oleksin filmis olulise stseeni vahele jätnud.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Ma pole kunagi nii palju adrenaliini tundnud, et oleks kohe tahtnud uuesti sõita.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Ma pole kunagi proovinud selliste loomadega laulmist nagu Lumivalgeke.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Ma pole kunagi unistanud reisist Disneylandi.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Ma pole kunagi unistanud Jurassic Parki veesõidust.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Ma pole kunagi mängus hüppehirmu peale valjult karjunud.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Ma pole kunagi telesaate finaali pärast nutnud.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Ma pole kunagi... tühistanud kohtingut, et koju jääda.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Ma pole kunagi... sõnumit 10 korda ümber sõnastanud.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Ma pole kunagi... salaja oma partneri mobiiltelefoni vaadanud.",
    "Ich habe noch nie!" to "Ma pole kunagi!",
    "Ich habe!" to "Mul on!",
    "Ich lache viel mit meinem Partner." to "Naeran koos oma partneriga palju.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Mulle meeldib oma partneri hobide ja huvidega tutvuda.",
    "Ich liebe es" to "Mulle meeldib see",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Mulle meeldib oma partneriga vaadata filme, mida me kumbki pole varem näinud.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Mulle meeldib jagada oma lemmikmuusikat oma partneriga.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Ma pole kunagi pidanud jooksma, et jätkulennule jõuda.",
    "Ich plane gerne Dates mit meinem Partner." to "Mulle meeldib oma partneriga kohtinguid planeerida.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Ma eelistan oma partneriga aega veeta isegi siis, kui olen hõivatud.",
    "Ich schreibe meinem Partner jeden Tag." to "Saadan oma partnerile iga päev sõnumeid.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Mulle meeldib oma partneriga meeme ja nalju jagada.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Mulle meeldib jagada oma partneriga kõiki oma päeva üksikasju.",
    "Ich würde es nie tun" to "Ma ei teeks seda kunagi",
    "Ich übe noch" to "Harjutan endiselt",
    "Ideen generieren" to "Looge ideid",
    "Im Haushalt helfen" to "Abi majapidamises",
    "In Chat einfügen" to "Lisa vestlusesse",
    "In Stille nebeneinander" to "Vaikuses üksteise kõrval",
    "In den Bergen" to "Mägedes",
    "In eine Bar gehen" to "Minge baari",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Lähen rannabaari päikeseloojangut vaatama",
    "In einem feinen Restaurant essen gehen" to "Söömine peenes restoranis",
    "In einen Coffeeshop gehen" to "Minge kohvikusse",
    "In einer Beziehung sollte man alles voneinander wissen." to "Suhtes peaksite üksteise kohta kõike teadma.",
    "Infinity-Pool" to "Lõpmatuse bassein",
    "Innenpool" to "Sisebassein",
    "Intelligenz" to "Intelligentsus",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Intiimsed hetked on ainult siis, kui teie partner neid algatab",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Kutse kood: HRM-8731 · kõik on lukustamata",
    "Island" to "Island",
    "Ist okay für mich" to "Minuga on kõik korras",
    "Ist schon perfekt" to "See on täiuslik",
    "Ja, Traditionen einbinden" to "Jah, kaasake traditsioone",
    "Ja, absolut" to "Jah, absoluutselt",
    "Ja, etwas zum Lesen und Aufbewahren" to "Jah, midagi lugeda ja alles hoida",
    "Ja, genug" to "Jah, piisab",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Jah, põnevas linnas või vaatamisväärsuses",
    "Ja, in- und auswendig" to "Jah, seest ja väljast",
    "Ja, komplett überraschend" to "Jah, täiesti üllatav",
    "Ja, perfekt" to "Jah, täiuslik",
    "Ja, sie gehören zur Familie!" to "Jah, nad on perekond!",
    "Ja, sofort teilen" to "Jah, jagage kohe",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Jah, tagame, et perekondlik aeg on prioriteet.",
    "Jacuzzi" to "Mullivann",
    "Jahr zusammen 🎉" to "aasta koos 🎉",
    "Jahre zusammen 🎉" to "Koos oldud aastad 🎉",
    "Jeder zahlt 50%" to "Kõik maksavad 50%",
    "Junge" to "Poiss",
    "Kamin" to "Kamin",
    "Karriere & Erfolg" to "Karjäär ja edu",
    "Kategorien" to "Kategooriad",
    "Katze" to "Kass",
    "Keine Musik" to "Muusika puudub",
    "Keine Party nötig, privat halten" to "Pole vaja pidu pidada, hoidke seda privaatsena",
    "Keine Privatsphäre" to "Privaatsus puudub",
    "Keine Treffer gefunden" to "Ühtegi vastet ei leitud",
    "Keiner" to "Puudub",
    "Keiner von uns" to "Mitte keegi meist",
    "Kennst du die Essensvorlieben deines Partners?" to "Kas teate oma partneri toidueelistusi?",
    "Kino" to "Kino",
    "Kirchlich" to "Kiriklik",
    "Klassisch Solitär" to "Klassikaline pasjanss",
    "Klassisch gebunden" to "Klassikaliselt köidetud",
    "Klein & zart" to "Väike ja õrn",
    "Kleine Geschenke" to "Väikesed kingitused",
    "Kleine Runde" to "Väike grupp",
    "Kochen und Freunde einladen" to "Söögitegemine ja sõprade kutsumine",
    "Kochkurs" to "Kokandustund",
    "Kommt auf den Tag an" to "Oleneb päevast",
    "Kommt darauf an" to "Oleneb",
    "Kommt drauf an" to "Oleneb",
    "Kommt mit" to "Tule minuga",
    "Konzert" to "Kontsert",
    "Kräftige Farben" to "Tugevad värvid",
    "Kräuterbeet" to "Ürdipeenar",
    "Kultur & Sehenswürdigkeiten" to "Kultuur ja vaatamisväärsused",
    "Kuscheln" to "Kaisutamine",
    "Kuss senden" to "Saada suudlus",
    "Körperliche Annäherung" to "Füüsiline lähenemine",
    "Körperliche Nähe" to "Füüsiline lähedus",
    "Küche" to "Köök",
    "Land" to "Riik",
    "Landhaus" to "Maakodu",
    "Landhausstil" to "Maakodu stiil",
    "Lange wach bleiben" to "Olge hilja üleval",
    "Lappland" to "Lapimaa",
    "Lappland, Finnland" to "Lapimaa, Soome",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Laske oma partneril inspireerida teid olema parim mina",
    "Lehne ab" to "Langus",
    "Leichtigkeit" to "Kergus",
    "Leidenschaft" to "Kirg",
    "Liebe im Gleichgewicht" to "Armastus tasakaalus",
    "Liebe sie, macht mehr Spaß" to "Armasta neid, lõbusam",
    "Lieber durchgeplant oder spontan?" to "Kas eelistaksite seda plaanipäraselt või spontaanselt?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Kas teile meeldiks vaikne õhtu kahekesi või inimestega?",
    "Lieber nicht" to "Parem mitte",
    "Lieber vorher grob absprechen" to "Parem on asju enne laias laastus arutada",
    "Lokal einkaufen" to "Ostke kohapeal",
    "London" to "London",
    "London, England" to "London, Inglismaa",
    "Lügen" to "Valed",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Kas eelistate avalikku või eraettepanekut?",
    "Malediven" to "Maldiivid",
    "Man sollte nie streitend einschlafen." to "Te ei tohiks kunagi tülitsedes magama jääda.",
    "Mango Sorbet" to "Mangosorbett",
    "Markant & breit" to "Rabav ja lai",
    "Marken & Alltag" to "Brändid ja igapäevaelu",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "Vahemere sisehoov",
    "Mehr Unterstützung" to "Rohkem tuge",
    "Mehr gemeinsame Zeit" to "Rohkem aega koos",
    "Mehr zuhören" to "Kuulake rohkem",
    "Mehrgenerationenhaus" to "Mitme põlvkonna maja",
    "Mein Arbeitsplatz" to "Minu töökoht",
    "Mein Partner" to "Minu partner",
    "Mich überraschen" to "Üllata mind",
    "Minimalistisches Interieur" to "Minimalistlik interjöör",
    "Missverständnisse" to "Arusaamatused",
    "Mit Familie und engen Freunden" to "Pere ja lähedaste sõpradega",
    "Mit Kompromissen" to "Kompromissidega",
    "Mitgefühl" to "Kaastunne",
    "Mittelweg mit besonderen Details" to "Eriliste detailidega kesktee",
    "Modern geometrisch" to "Moodne geomeetriline",
    "Moderne Grillstation" to "Moodne grillijaam",
    "Moderner Name" to "Moodne nimi",
    "Moderner Solitär" to "Moodne pasjanss",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "Jäädvustage hetk",
    "Momente" to "hetked",
    "Monaco" to "Monaco",
    "Moralische Werte" to "Moraalsed väärtused",
    "Museum" to "Muuseum",
    "Musik" to "Muusika",
    "Mut" to "Julgus",
    "Mädchen" to "Tüdrukud",
    "Möbelhaus" to "Mööblipood",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Kas soovite kindlasti viktoriinist lahkuda? Teie eelmine edenemine jääb salvestatuks.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Kas soovite, et lemmikloomi lisataks rakendusse?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Kas soovite, et seda hetke sotsiaalmeedias kohe jagataks?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Võimalik, et peame kokku hoidma",
    "Müssen es planen" to "Peab seda planeerima",
    "Müssen sparen" to "Vaja salvestada",
    "Nachricht an" to "Sõnum",
    "Name Partnerin" to "Partneri nimi",
    "Namen und Startdatum eurer Beziehung." to "Teie suhte nimed ja alguskuupäev.",
    "Natursteinfassade" to "Looduskivist fassaad",
    "Naturteich" to "Looduslik tiik",
    "Nein, einfach halten" to "Ei, lihtsalt hoidke seda",
    "Nein, erstmal privat halten" to "Ei, hoidke see praegu privaatsena",
    "Nein, lieber vor Ort" to "Ei, parem kohapeal",
    "Nein, modern halten" to "Ei, hoidke seda kaasaegsena",
    "Nein, nur wir" to "Ei, ainult meie",
    "Nein, zu ablenkend" to "Ei, liiga segav",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Uus hoone targa koduga",
    "Neubau mit Technik" to "Tehnikaga uus hoone",
    "Neue Liebe, neue Erfahrungen" to "Uus armastus, uued kogemused",
    "Neues Hobby" to "Uus hobi",
    "Neues Spiel" to "Uus mäng",
    "Neugier" to "Uudishimu",
    "New York" to "New York",
    "New York, USA" to "New York, USA",
    "Nicht mein Fall" to "Pole minu tass teed",
    "Nicht nötig, lieber klassisch bleiben" to "Pole vaja, parem on jääda klassikaks",
    "Nichts — es passt so" to "Mitte midagi – see sobib",
    "Nie wieder Burger" to "Mitte kunagi enam burgereid",
    "Nie wieder Pizza" to "Mitte kunagi enam pitsat",
    "Niemand" to "Mitte keegi",
    "Niemand ohne Plan" to "Ilma plaanita pole kedagi",
    "Nike" to "Nike",
    "Nizza" to "Tore",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Hetkel pole veel hetki.\nJäädvustage oma esimene kogemus 💞",
    "Nur bei wichtigen Themen" to "Ainult oluliste teemade puhul",
    "Nur wir beide" to "Ainult meie kahekesi",
    "Nähe & Intimität" to "Lähedus ja intiimsus",
    "Obstgarten" to "Viljaaed",
    "Oder" to "Or",
    "Offene Küche" to "Avatud köök",
    "Offene Wohnküche" to "Avatud köök/elutuba",
    "Ohne Stein" to "Ilma kivita",
    "Open End" to "Avatud lõpp",
    "Outdoor-Küche" to "Väliköök",
    "Outdoor-Sofa" to "Välidiivan",
    "Outdoor-Whirlpool" to "Välimullivann",
    "Ovaler Diamant" to "Ovaalne teemant",
    "Paar" to "Paar",
    "Paar-Statistiken" to "Paari statistika",
    "Paris" to "Pariis",
    "Paris, Frankreich" to "Pariis, Prantsusmaa",
    "Partner" to "Partner",
    "Partner-Simulator" to "Partnerite simulaator",
    "Partnerin" to "Partner",
    "Party Edition" to "Party Edition",
    "Party Edition II" to "Party Edition II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Kas loom üldse sobib meie igapäevaellu?",
    "Pasta" to "Pasta",
    "Pastell" to "Pastell",
    "Penthouse mit Ausblick" to "Vaatega katusekorter",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pergola koos puhketoaga",
    "Pfingstrosen" to "Pojengid",
    "Pinguin" to "Pingviin",
    "Pistazie" to "Pistaatsia",
    "Pizza" to "Pitsa",
    "Pizzaofen" to "Pitsaahi",
    "Platin" to "Plaatina",
    "PlayStation" to "PlayStation",
    "Pool" to "Bassein",
    "Pop" to "Pop",
    "Prasselnder Kamin" to "Möirgav kamin",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Printsessid, piraadid ja haldjatolm: Disney viktoriin",
    "Privater Innenhof" to "Privaatne sisehoov",
    "Profil" to "Profiil",
    "Profil bearbeiten" to "Muuda profiili",
    "Prozentual nach Einkommen" to "Sissetulekul põhinev protsent",
    "Quiz verlassen" to "Välju viktoriinist",
    "Quiz verlassen?" to "Kas lahkuda viktoriinist?",
    "Rausgehen in die Natur" to "Minge loodusesse",
    "Reden vor ..." to "Rääkides...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Planeerige ühised kuupäevad või kellaajad",
    "Reisen" to "Reisimine",
    "Reiseziele" to "Reisisihtkohad",
    "Respektlosigkeit" to "Lugupidamatus",
    "Restaurant" to "Restoran",
    "RnB / Soul" to "RnB / Soul",
    "Rock" to "Rokk",
    "Rom" to "Rooma",
    "Rom, Italien" to "Rooma, Itaalia",
    "Romantik" to "Romantika",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Romantilised žestid, nagu sõnumid, märkmed või kingitused, teevad mind õnnelikuks.",
    "Romantische Stimmung" to "Romantiline meeleolu",
    "Roségold" to "Roosa kuld",
    "Ruhig zu zweit" to "Vaikne kahele",
    "Runder Diamant" to "Ümar teemant",
    "Salted Caramel" to "Soolakaramell",
    "Sammle Ideen..." to "Koguge ideid...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Kreeka",
    "Saphir" to "Safiir",
    "Saunahaus" to "Saunamaja",
    "Schickes Restaurant oder Hotel" to "Šikk restoran või hotell",
    "Schlafzimmer" to "Magamistuba",
    "Schließen" to "Sule",
    "Schmal & zart" to "Õhuke ja õrn",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Pilte meie armastusloost",
    "Schokolade" to "Šokolaad",
    "Schreib frei, was dir wirklich dazu einfällt." to "Kirjutage vabalt, mis teile tegelikult meelde tuleb.",
    "Schreibe deine eigene Antwort" to "Kirjutage oma vastus",
    "Sehr gerne" to "Tere tulemast",
    "Sehr leicht" to "Väga kerge",
    "Sehr wichtig — Fotos und Video" to "Väga oluline – fotod ja videod",
    "Sehr wichtig, es sollte persönlich sein" to "Väga oluline, see peaks olema isiklik",
    "Selbst kochen" to "Tehke ise süüa",
    "Senden" to "Saada",
    "Separate Küche" to "Eraldi köök",
    "Serie schauen" to "Vaadake seriaali",
    "Serienmarathon auf dem Sofa" to "Sarjamaraton diivanil",
    "Sex & Liebe" to "Seks ja armastus",
    "Seychellen" to "Seišellid",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Kas suudame ühe lapse/mitme lapse puhul kõik kulud katta? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Kas ettepanek peaks olema üllatus?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Kas rakendus peaks sisaldama kultuurilisi või traditsioonilisi elemente?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Kas taotlus peaks sisaldama kultuurilisi või traditsioonilisi elemente?",
    "Sommerhochzeit" to "Suvised pulmad",
    "Sonnige Dachterrasse" to "Päikeseline katuseterrass",
    "Sowohl als auch" to "Nii ja",
    "Spazieren" to "Jalutage",
    "Spaß & Abenteuer" to "Lõbu ja seiklus",
    "Speichern" to "Salvesta",
    "Spiel bearbeiten" to "Muutke mängu",
    "Spielbereich für Kinder" to "Mänguala lastele",
    "Spiele" to "Mängud",
    "Spiele spielen und Spaß haben" to "Mängige mänge ja lõbutsege",
    "Spontan" to "Spontaanne",
    "Sportplatz" to "Spordiväljak",
    "Spotify" to "Spotify",
    "Sprache" to "Keel",
    "Stadt" to "Linn",
    "Stadt oder Land — was ist uns wichtiger?" to "Linn või riik – mis on meie jaoks tähtsam?",
    "Stadtvilla" to "Linnavilla",
    "Standesamt & Party" to "Registribüroo ja partei",
    "Statement-Ring" to "Avaldusrõngas",
    "Stilvolles Outdoor-Sofa" to "Stiilne välidiivan",
    "Stimme voll zu" to "Täiesti nõus",
    "Stimmt" to "Õige",
    "Stimmt nicht" to "Ei ole tõsi",
    "Stimmt, noch nie" to "Tõsi, mitte kunagi",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Rannapäev",
    "Streit über Haushalt" to "Vaidlus majapidamise üle",
    "Studio Ghibli" to "Stuudio Ghibli",
    "Ständig" to "Pidevalt",
    "Suche schließen" to "Sule otsing",
    "Suche zurücksetzen" to "Lähtestage otsing",
    "Suche öffnen" to "Ava otsing",
    "Suchergebnisse" to "Otsingutulemused",
    "Sushi" to "Sushi",
    "Süß" to "Armas",
    "Tage zusammen 💞" to "päeva koos 💞",
    "Tauche ins Unterbewusstsein" to "Sukeldu alateadvusesse",
    "Teile alle deine Hobbys mit deinem Partner" to "Jagage oma partneriga kõiki oma hobisid",
    "Teils teils" to "Osaliselt osaliselt",
    "Testen" to "Test",
    "Themen" to "Teemad",
    "Tiefe Gespräche" to "Sügavad vestlused",
    "Tiefgründige Gespräche führen" to "Vestelge sügavalt",
    "Tierpension" to "Loomade pansionaat",
    "Tiny House" to "Pisike maja",
    "Tippen zum Auswählen & Scrollen" to "Puudutage valimiseks ja kerimiseks",
    "Tippen zum Zuklappen" to "Puudutage ahendamiseks",
    "Titel" to "Pealkiri",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Pealkiri, kategooria, teema, sildid, küsimused...",
    "Tokyo, Japan" to "Tokyo, Jaapan",
    "Traditioneller Name" to "Traditsiooniline nimi",
    "Traumhaus Außenbereich" to "Unistuste maja väliala",
    "Traumhochzeit" to "Unistuste pulm",
    "Treffer" to "Hitt",
    "Tägliche Aktivität" to "Igapäevane tegevus",
    "Umformulieren" to "Sõnastage ümber",
    "Unbeantwortet" to "Vastamata",
    "Unbeliebte Meinungen" to "Ebapopulaarsed arvamused",
    "Universal Studios Genie oder Neuling?" to "Universal Studiosi geenius või algaja?",
    "Uns auseinanderzuleben" to "Lahku kasvada",
    "Unser Intimleben" to "Meie intiimne elu",
    "Unser Traumhaus" to "Meie unistuste maja",
    "Unser erstes Treffen" to "Meie esimene kohtumine",
    "Unsere Gesichter" to "Meie näod",
    "Unsere eigenen Träume" to "Meie enda unistused",
    "Unsere nächste Reise" to "Meie järgmine reis",
    "Unter 1000" to "Alla 1000",
    "Unter 1000 im Monat" to "Alla 1000 kuus",
    "Unter 50€/Monat" to "Alla 50 €/kuus",
    "Unter Leuten" to "Inimeste seas",
    "Untreue" to "Truudusetus",
    "Urlaub" to "Puhkus",
    "Vanille" to "Vanill",
    "Venedig" to "Veneetsia",
    "Venedig, Italien" to "Veneetsia, Itaalia",
    "Verbinde dich mit" to "Ühendage seadmega",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Vastuse nägemiseks looge ühendus seadmega \${profile.partnerName}",
    "Verbindung" to "ühendus",
    "Verbringe die Feiertage mit deiner Familie" to "Veetke pühad perega",
    "Verlobungsringe" to "Kihlasõrmused",
    "Vertrautheit" to "Tuttavus",
    "Viel getrennt" to "Palju lahusolekut",
    "Vielleicht ein oder zwei" to "Võib-olla üks või kaks",
    "Vielleicht, aber mündlich reicht" to "Võib-olla, aga verbaalselt piisab",
    "Vielleicht, wenn es machbar ist" to "Võib-olla, kui see on võimalik",
    "Vielleicht, wenn es passt" to "Võib-olla, kui sobib",
    "Vintage Art déco" to "Vintage Art Deco",
    "Vintage verspielt" to "Vintage mänguline",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Teie partner tutvustab teile uusi hobisid",
    "Vor dem Kauf eines Hauses besprechen" to "Arutage enne maja ostmist",
    "Vor der Anschaffung eines Haustiers besprechen" to "Arutage enne lemmiklooma ostmist",
    "Vor der gemeinsamen Reise besprechen" to "Arutage enne koos reisimist",
    "Vor nichts" to "Mitte midagi",
    "Vorort" to "Eeslinn",
    "Walnuss" to "Pähkel",
    "Wandern" to "Matkamine",
    "Wann fühlst du dich mir am nächsten?" to "Millal tunnete end minuga kõige lähedasemana?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Millal tunnete end minuga füüsiliselt kõige lähedasemana?",
    "Was bedeutet Vertrauen für dich konkret?" to "Mida usaldus teie jaoks konkreetselt tähendab?",
    "Was entspannt dich mehr?" to "Mis teid rohkem lõdvestab?",
    "Was fehlt dir über die Distanz am meisten?" to "Millest sa distantsi juures kõige rohkem puudust tunned?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Mis teile oma kodu juures kõige rohkem meeldib?",
    "Was hast du von deinem Partner gelernt?" to "Mida olete oma partnerilt õppinud?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Mida arvate koos erootilise sisu vaatamisest?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Mida arvate rekvisiitidest (nt sildid, õhupallid jne)?",
    "Was ist das Wichtigste beim Antrag?" to "Mis on kandideerimisel kõige olulisem?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Mis on kõige olulisem asi, mida sa seksuaalvahekorras ootad?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Mis on teie lemmikfoto meist? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Mis on teie suurim hirm kooselu ees?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Mis on toit, mida sa armastad, kuid su partner ei saa aru?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Mis on teie jaoks absoluutne diilimurdja?",
    "Was ist für jeden von uns das absolute Highlight?" to "Mis on meie kõigi jaoks absoluutne tipphetk?",
    "Was ist passiert?" to "Mis juhtus?",
    "Was macht einen Moment für dich romantisch?" to "Mis teeb hetke sinu jaoks romantiliseks?",
    "Was magst du an deinem Partner am liebsten?" to "Mis sulle oma partneri juures kõige rohkem meeldib?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Mis teile rohkem meeldib: varakult tõusta või hilja üleval olla?",
    "Was magst du lieber?" to "Kumb teile rohkem meeldib?",
    "Was möchtest du eigentlich sagen?" to "Mida sa tegelikult öelda tahad?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Mida soovite, et teie partner sagedamini teeks?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Mis juhtub loomaga, kui me reisime?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Mis saab meie lapsest, kui ta suureks kasvab?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Mida me lapsevanematena kunagi silmist ei tohiks unustada?",
    "Was war dein schönster Moment mit mir bisher?" to "Mis oli teie seni parim hetk minuga?",
    "Was wir gegessen haben" to "Mida me sõime",
    "Was wollt ihr nie vergessen?" to "Mida sa ei taha kunagi unustada?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Mis oleks teie jaoks hullem: mitte kunagi enam pitsat või mitte kunagi enam burgereid?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Mida tahaksite kõige meelsamini ühisel päeval teha?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Mida muudaksite kohe, kui raha poleks probleem?",
    "Weiter" to "Järgmine",
    "Weiter spielen" to "Jätkake esitamist",
    "Weiß ich noch nicht" to "Ma ei tea veel",
    "Weiße Rosen" to "Valged roosid",
    "Weißgold" to "Valge kuld",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Millise kvaliteedi peaks meie laps meilt kindlasti saama?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Millist keskkonda soovite ettepaneku jaoks?",
    "Welcher Raum sagt am meisten über dich aus?" to "Milline tuba ütleb sinu kohta kõige rohkem?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Kui suur eelarve on meil toidu ja loomaarsti jaoks?",
    "Welches Lied macht dich an? 🥵" to "Milline laul paneb sind käima? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Milline jagatud foto on teie lemmik?",
    "Wellnessbad" to "Tervisevann",
    "Wenn es schwierig ist" to "Kui asjad on keerulised",
    "Wenn ich müde bin" to "Kui ma olen väsinud",
    "Wenn wir uns lange umarmen" to "Kui kallistame pikka aega",
    "Wenn wir zusammen lachen" to "Kui me koos naerame",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Kes otsustab kiiremini, mida tellida?",
    "Wer findet die besten Restaurants?" to "Kes leiab parimad restoranid?",
    "Wer gibt mehr Herzlichkeit?" to "Kes annab rohkem soojust?",
    "Wer hat den besseren Musikgeschmack?" to "Kellel on parem muusikamaitse?",
    "Wer hängt mehr an seinen Eltern?" to "Kes on oma vanematesse rohkem kiindunud?",
    "Wer ist besser organisiert?" to "Kes on paremini organiseeritud?",
    "Wer ist der Beste bei der Filmauswahl?" to "Kes valib filme kõige paremini?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Kes oskab kõige paremini romantilisi kohtinguid planeerida?",
    "Wer ist der beste Tänzer?" to "Kes on parim tantsija?",
    "Wer ist romantischer?" to "Kes on romantilisem?",
    "Wer kocht besser?" to "Kes teeb paremini süüa?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Kes hoolitseb renoveerimise ja hoolduse eest?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Kes märkab kiiremini, kui teine ​​inimene ei tunne end hästi?",
    "Wer sucht am Ende wirklich den Film aus?" to "Kes tegelikult filmi lõpuks valib?",
    "Wer vergisst eher einen Jahrestag?" to "Kes unustab suurema tõenäosusega aastapäeva?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Kes unustaks järgmisel hommikul oma nime tõenäolisemalt?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Kes leiaks järgmisel päeval tõenäolisemalt video, millest ta midagi ei tea?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Kes eelistaks ööbida võõral diivanil?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Kes jääks suurema tõenäosusega peol magama ja ärkaks Sharpie näol?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Kes libiseb tõenäolisemalt tantsupõrandal, kuid jätab selle laheda liigutuse mulje?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Kes võtab majapeol tõenäolisemalt Spotify esitusloendi üle kontrolli?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Kes telliks tõenäolisemalt peol kõigile pitsa ja sööks seda ise?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Kes jääb peol suurema tõenäosusega esimesena magama?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Kes hakkaks suurema tõenäosusega äkki peol koristama?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Kes võiks tõenäolisemalt väita, et on täiesti kaine, kui tõsi on vastupidi?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Kes annab vaidluses tõenäolisemalt esimesena järele?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Kes on suurem tõenäosus joomamängus petta?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Kes tungiks tõenäolisemalt puhvetisse ja viiks salaja toitu koju?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Kes postitaks tõenäolisemalt oma loosse õhtu kõige piinlikuma foto?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Kes ärritaks tõenäolisemalt DJ-d oma lemmiklaulu nõudmisel?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Kes laulaks tõenäolisemalt laulu sõnu väljalülitatud võtmega, kuid veendunult?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Kes oleks tõenäolisem, et telliks menüüs kõige kallima joogi ja kahetseks seda?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Kes kutsuks tõenäolisemalt naabreid külla, kui nad müra üle kurdavad?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Kes võtaks seltskonnamänge (nagu Beer Pong) liiga tõsiselt?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Kes sõbrustab suurema tõenäosusega väljaviskajatega, et saada VIP-juurdepääs?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Kes alustaks suurema tõenäosusega spontaanset karaokelahingut?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Kes avab tõenäolisemalt pudeli ilma pudeliavajat kasutamata?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Kes peaks tõenäolisemalt kõnet pidama, kuigi absoluutselt keegi ei küsinud?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Kes veedaks suurema tõenäosusega tund aega vannitoas selfisid tehes?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Kes korraldaks tõenäolisemalt piinliku tantsuetenduse ja tähistaks seda?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Kes helistaks tõenäolisemalt endisele partnerile pärast peo lõppu?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Kes võiks tõenäolisemalt võõrast külalist kogemata solvata?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Kes lahkuks suurema tõenäosusega peolt salaja hüvasti jätmata?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Kes eelistaks võõrustaja lemmikloomaga mängida kui külalistega rääkida?",
    "Wer würde eher spontan eine Reise buchen?" to "Kes broneeriks suurema tõenäosusega reisi spontaanselt?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Kes peaks tõenäolisemalt tundide kaupa köögis sügavaid vestlusi?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Kes joob suurema tõenäosusega kogemata kellegi teise jooki?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Kes lööks tõenäolisemalt kogemata ümber kalli vaasi või midagi hapra?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Kes prooviks suurema tõenäosusega ise keerulist kokteili kokku segada ja ebaõnnestub haledalt?",
    "Wer würde eher zu spät kommen?" to "Kes hilineb tõenäolisemalt?",
    "Wer würde eher?" to "Kes eelistaks?",
    "Wer übernimmt die tägliche Versorgung?" to "Kes hoolitseb igapäevase hoolduse eest?",
    "Werde so akzeptiert, wie du bist" to "Olge aktsepteeritud sellisena, nagu olete",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Kas meil jääb lapse/laste jaoks piisavalt aega? ⏳",
    "Whirlpool" to "Mullivann",
    "White Chocolate" to "Valge šokolaad",
    "Widgets" to "Vidinad",
    "Wie fühlst du dich am meisten geliebt?" to "Kuidas tunnete end kõige rohkem armastatuna?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Kuidas tuleme toime erinevate sissetulekutega?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Milline on teie partneri jaoks parim viis teiega seksi algatamiseks?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Kuidas saab teie partner olla teile veelgi parem partner?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Kui kaua pärast ettepanekut soovite koos teistega tähistada?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Kui kauaks me sinna vähemalt jääda tahame?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Kui lihtne on teil soovidest rääkida?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Kuidas soovite, et meie tulevik välja näeks?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Milline näeb välja teie ideaalne pühapäev kodus?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Kuidas suhtute seksi ajal räpasse juttusse?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Kui palju krediiti saame endale reaalselt lubada?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Kui palju aega tahame lahus veeta?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Kui palju tahame kokku kulutada?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Kuidas leiame oma suhte jaoks aega, kui laps sünnib?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Kui oluline on teie jaoks hetke tabamine?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Kui oluline on teie jaoks, et rakendus kajastaks teie hobisid või huvisid?",
    "Wie würdest du sie/ihn nennen?" to "Kuidas te teda nimetaksite?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Milline on teie lemmikviis väljaspool seksi kiindumust näidata?",
    "Wildblumen" to "Metslilled",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Kas sa tahad tüdrukut või poissi? 👶",
    "Wintergarten" to "Talveaed",
    "Winterhochzeit" to "Talvised pulmad",
    "Wir bestellen einfach beides" to "Tellime lihtsalt mõlemad",
    "Wir brauchen ewig" to "See võtab meid igavesti",
    "Wir einigen uns nie" to "Me ei nõustu kunagi",
    "Wir entscheiden es gemeinsam" to "Otsustame koos",
    "Wir treffen uns in der Mitte" to "Kohtume keskel",
    "Wir wechseln uns ab" to "Me käime kordamööda",
    "Wird stressig" to "Muutub stressi",
    "Wobei lachst du am meisten?" to "Mis sind kõige rohkem naerma ajab?",
    "Wofür sparen wir gemeinsam?" to "Milleks me koos säästame?",
    "Wohnzimmer" to "Elutuba",
    "Woran erinnerst du dich am lebhaftesten?" to "Mis on teile kõige eredamalt meelde jäänud?",
    "Worauf freust du dich bei uns am meisten?" to "Mida te meie juurest kõige rohkem ootate?",
    "Worte/Komplimente" to "Sõnad/komplimendid",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Mida sa meie suhtes kõige rohkem kardad?",
    "Wünsche? z.B. günstig, draußen" to "Soovid? nt. odav, väljas",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Kas eelistaksite teha puhkuseettepaneku (sealhulgas reisimisega)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube Music",
    "Zeichne für mich" to "Joonistage mulle",
    "Zeichne mich als Tier — welches wäre ich?" to "Joonistage mind kui looma – milline ma oleksin?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Joonistage meie tunded üksteise vastu sümbolina.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Joonistage meie unistuste maja ühele joonele. Mis on kõige silmatorkavam?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Joonistage meie esimene kohting – mis peab kindlasti pildil olema?",
    "Zeichnen" to "Loosimine",
    "Zeit füreinander" to "Aega teineteise jaoks",
    "Zeit, wenn das Baby schläft" to "Aeg, mil laps magab",
    "Zelten gehen" to "Minge telkima",
    "Zitrone" to "Sidrun",
    "Zu Hause, gemütlich und privat" to "Kodus, hubane ja privaatne",
    "Zu einem Picknick gehen" to "Piknikule minek",
    "Zu einem ausgefallenen Abendessen gehen" to "Lähen uhkele õhtusöögile",
    "Zu zweit reisen" to "Reisige paarina",
    "Zuhause & Alltag" to "Kodu ja igapäevaelu",
    "Zuhören" to "Kuulake",
    "Zurück" to "Tagasi",
    "Zusammen seit" to "Alates sellest ajast koos",
    "Zusammen seit (TT.MM.JJJJ)" to "Koos alates (PP.KK.AAAA)",
    "Zusammenziehen" to "Leping",
    "Zustimmen oder Ablehnen" to "Nõus või mitte",
    "Zwei Kreise, die sich überschneiden" to "Kaks ringi, mis kattuvad",
    "Zwei Stühle davor" to "Kaks tooli selle ees",
    "Zärtlich sein" to "Olge õrn",
    "Öfter als ich zugebe" to "Rohkem kordi, kui ma tunnistan",
    "Über 100€/Monat" to "Üle 100 € kuus",
    "Über 2000 im Monat" to "Üle 2000 kuus",
    "Über mich selbst" to "Minust endast",
    "Übernehmen" to "Rakenda",
    "Überraschend" to "Üllatav",
    "Überraschung" to "Üllatus",
    "Überspringen" to "Jäta vahele",
    "Übertrieben und großartig" to "Ületav ja vinge",
    "✎ Tippe, um zu antworten" to "✎ Puudutage vastamiseks",
    "✨ GFK-Brücke" to "✨ GRP sild",
)

internal fun localizeEstonianDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_ESTONIAN_CONTENT)
