package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_FILIPINO_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 taon",
    "1000 - 1500 im Monat" to "1000 - 1500 bawat buwan",
    "1000 bis 3000" to "1000 hanggang 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 bawat buwan",
    "3000 bis 5000" to "3000 hanggang 5000",
    "5-10 Jahre" to "5-10 taon",
    "50-100€/Monat" to "50-100€/buwan",
    "Ab 100€" to "Mula 100€",
    "Ab 500€" to "Mula 500€",
    "Ab 50€" to "Mula 50€",
    "Ab und zu" to "Paminsan-minsan",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Magkano ang kailangan nating gastusin bago bumili?",
    "Abbrechen" to "Kanselahin",
    "Abenteuer" to "Pakikipagsapalaran",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Mga aktibidad",
    "Alle" to "Lahat",
    "Alle Pakete" to "Lahat ng package",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Mawalan ng lahat ng kaibigan mo maliban sa matalik mong kaibigan",
    "Alle intimen Momente selbst initiieren" to "Magsimula ka sa lahat ng intimate moments",
    "Alles davon" to "Lahat ng ito",
    "Alles, was noch kommt" to "Lahat ng darating",
    "Alltagsroutine" to "Araw-araw na gawain",
    "Alltägliche Berührungen" to "Araw-araw na pagpindot",
    "Altbau mit Charme" to "Lumang gusali na may kagandahan",
    "Am Strand" to "Sa beach",
    "Am liebsten alles zusammen" to "Mas mabuti na magkasama ang lahat",
    "Am selben Tag mit Freunden/Familie" to "Parehong araw kasama ang mga kaibigan/pamilya",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Netherlands",
    "An das Gefühl" to "Ng pakiramdam",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "Sa pampublikong lugar na maraming manonood",
    "An einen Geruch" to "Isang amoy",
    "An einen Song" to "Sa isang kanta",
    "An etwas, das ich gesagt habe" to "May sinabi ako",
    "Analyse starten" to "Simulan ang pagsusuri",
    "Analysiere eure Muster..." to "Suriin ang iyong mga pattern...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Suriin ang iyong mga sagot at chat ayon kay Gottman at GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Masarap ang lasa ng pinya sa pizza.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Tumugon nang may larawan",
    "Antwortähnlichkeit" to "Sagot pagkakatulad",
    "App-Sprache auswählen" to "Pumili ng wika ng app",
    "Auf eine Bootsparty gehen" to "Pupunta sa isang boat party",
    "Aufmerksamkeit" to "Pansin",
    "Aufräumen und Projekte angehen" to "Linisin at harapin ang mga proyekto",
    "Aufwärmen" to "Warm up",
    "Aufwärmen: Einander kennenlernen" to "Warm-up: Pagkilala sa isa't isa",
    "Aus dem Urlaub" to "Mula bakasyon",
    "Ausgefallener Name" to "Magarbong pangalan",
    "Ausschlafen und faulenzen" to "Matulog ka at maglambing",
    "Ausschlafen und nichts tun" to "Matulog ka na at walang gawin",
    "Aussehen" to "Hitsura",
    "Auto" to "Auto",
    "Außenkamin" to "Fireplace sa labas",
    "BEANTWORTE" to "SAGOT",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonesia",
    "Banane" to "Saging",
    "Beantwortet" to "Sumagot",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Sabay-sabay na sagutin ang mga tanong — hindi makikita ang mga sagot hangga't hindi kayo tapos.",
    "Beantwortete Fragen" to "Sinagot ang mga tanong",
    "Bearbeiten" to "I-edit",
    "Bei Insider-Witzen" to "Para sa inside jokes",
    "Bei Memes" to "Sa mga meme",
    "Bei einer spontanen Berührung" to "Kapag kusang hinawakan",
    "Beide" to "Pareho",
    "Beide gleich" to "Parehong pareho",
    "Beide zusammen" to "Parehong magkasama",
    "Beide, aber wir tun so als ob nicht" to "Pareho, pero nagpapanggap kaming hindi",
    "Beides" to "Pareho",
    "Beides wäre schlimm" to "Parehong masama",
    "Beim Einschlafen nebeneinander" to "Nakatulog sa tabi ng isa't isa",
    "Beim Reden" to "Habang nag-uusap",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Ang mga sikat na lugar ng turista ay palaging isang pagkabigo.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Ilarawan ang aming buhay sex gamit ang isang emoji.",
    "Besser kommunizieren" to "Makipag-usap nang mas mahusay",
    "Bessere Lage" to "Mas magandang lokasyon",
    "Bestellen" to "Order",
    "Besuchte Länder" to "Mga binisita na bansa",
    "Besuchte Städte" to "Mga lungsod na binisita",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Mas gusto mo ba ang isang labis na panukala o isang bagay na banayad?",
    "Beziehung" to "Relasyon",
    "Bibliothek" to "Library",
    "Bin manchmal unsicher" to "Minsan insecure ako",
    "Bist du ein Videospiel-Guru?" to "Isa ka bang video game guru?",
    "Blumenwiese" to "Bulaklak na parang",
    "Bunte Blumenwiese" to "Makukulay na bulaklak na parang",
    "Burger" to "Mga Burger",
    "Burger King" to "Burger King",
    "Chat" to "Makipag-chat",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Cookie Dough",
    "Dachgarten mit Lounge" to "Roof garden na may lounge",
    "Dachterrasse" to "terrace sa bubong",
    "Das Wetter an dem Tag" to "Ang lagay ng panahon noong araw na iyon",
    "Das erste Selfie" to "Ang unang selfie",
    "Das meiste weiß ich" to "Alam ko karamihan dito",
    "Das oder das?" to "Ito o iyon?",
    "Das tägliche Leben" to "Pang-araw-araw na buhay",
    "Dass Zusagen gehalten werden" to "Ang mga pangakong iyon ay tinutupad",
    "Dass alles meinen Stil hat" to "Na ang lahat ay may aking istilo",
    "Dass ich alles erzählen kann" to "Na kaya kong sabihin lahat",
    "Dass ich mich nicht sorgen muss" to "Na hindi ko kailangang mag-alala",
    "Dass wir ungestört sind" to "Na kami ay hindi nagagambala",
    "Dein Name" to "Pangalan mo",
    "Deine Antwort..." to "Ang sagot mo...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Ang iyong mga sagot ay naka-save. Sa sandaling matapos ng Partner ang package, makikita nang magkasama ang parehong mga sagot.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Naka-save ang iyong mga sagot. Kapag nakumpleto na ng \${profile.partnerName} ang package, makikita ang parehong mga tugon nang magkasama.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Gawing adventurous at spontaneous ang iyong relasyon",
    "Deine Beziehung stabil und sicher machen" to "Gawing matatag at secure ang iyong relasyon",
    "Deine eigene Antwort" to "Sarili mong sagot",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Mas mainam na ibahagi ang iyong pinakamalalim na sikreto sa iyong kapareha",
    "Deinen besten Freund verlieren" to "Ang pagkawala ng iyong matalik na kaibigan",
    "Denke an dich" to "Isipin mo ang iyong sarili",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Ang panonood ng parehong pelikula ng dalawang beses ay isang pag-aaksaya ng oras.",
    "Der Blick nach draußen" to "Ang view sa labas",
    "Der Garten" to "Ang hardin",
    "Der Ort" to "Ang lugar",
    "Der Ring und die Geste" to "Ang singsing at ang kilos",
    "Der perfekte Heiratsantrag" to "Ang perpektong proposal ng kasal",
    "Derjenige sein, der umarmt wird" to "Maging ang niyayakap",
    "Deutsch" to "German",
    "Diamant" to "Brilyante",
    "Diamanten im Band" to "Mga diamante sa banda",
    "Die Distanz" to "Ang layo",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Spend the holidays with your partner's family",
    "Die Gemütlichkeit und Ruhe" to "Ang ginhawa at kapayapaan",
    "Die Menschen, die darin wohnen" to "Ang mga taong nakatira dito",
    "Die Umgebung und Atmosphäre" to "Ang kapaligiran at kapaligiran",
    "Die Worte und Emotionen" to "Ang mga salita at damdamin",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Ang ultimate entertainment trivia challenge",
    "Diejenige sein, die umarmt" to "Maging ang yumayakap",
    "Direkt ansprechen" to "Direktang address",
    "Diskussion" to "Talakayan",
    "Diskutiere vor dem Kinderkriegen" to "Pag-usapan bago magkaanak",
    "Diskutiert eure Antworten" to "Talakayin ang iyong mga sagot",
    "Disney" to "Disney",
    "Doch, schon mal" to "Oo, oo",
    "Draußen mit der Natur als Kulisse" to "Sa labas na may kalikasan bilang backdrop",
    "Drei-Stein-Ring" to "Tatlong singsing na bato",
    "Du bist dran" to "Ikaw na",
    "Du fehlst mir" to "Miss na kita",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubai, UAE",
    "Dunkles Design" to "Madilim na tema",
    "Durch Berührung" to "Sa pamamagitan ng pagpindot",
    "Durch Worte" to "Sa pamamagitan ng mga salita",
    "Durch Zeit zu zweit" to "Sa paglipas ng panahon na magkasama",
    "Durch kleine Gesten" to "Sa pamamagitan ng maliliit na kilos",
    "Durchgeplant" to "Mahusay na binalak",
    "ERGEBNISSE" to "RESULTA",
    "Egal, Hauptsache gesund" to "Anuman, ang pangunahing bagay ay malusog",
    "Ehepaar Leben" to "Buhay ng mag-asawa",
    "Eher knapp" to "Medyo malapit",
    "Eher nicht" to "Hindi masyado",
    "Eher schwer" to "Medyo mahirap",
    "Eher schwierig" to "Medyo mahirap",
    "Eher zu" to "More like",
    "Eifersucht ist ein Zeichen von Liebe." to "Ang selos ay tanda ng pagmamahal.",
    "Eigenes Gemüsebeet" to "Sariling tagpi ng gulay",
    "Ein Abenteuer in einer neuen Stadt" to "Isang pakikipagsapalaran sa isang bagong lungsod",
    "Ein Anker" to "Isang anchor",
    "Ein Balkon oder Garten" to "Isang balkonahe o hardin",
    "Ein Filmabend" to "Isang gabi ng pelikula",
    "Ein Harmony-Meilenstein eurer Liebe." to "Isang harmony milestone ng iyong pagmamahalan.",
    "Ein Herz" to "Isang puso",
    "Ein Herz an der Tür" to "Isang puso sa pintuan",
    "Ein Jahr lang eine Fernbeziehung führen" to "Magkaroon ng long-distance relationship sa loob ng isang taon",
    "Ein Kindheitsessen" to "Isang pagkain noong bata pa",
    "Ein Live-Musik-Konzert besuchen" to "Dumalo sa isang live music concert",
    "Ein Museum besuchen" to "Bumisita sa isang museo",
    "Ein Spieleabend" to "Isang gabi ng laro",
    "Ein Spieleabend mit Freunden" to "Isang gabi ng laro kasama ang mga kaibigan",
    "Ein Urlaubsfoto" to "Isang larawan sa bakasyon",
    "Ein aktives Abenteuer" to "Isang aktibong pakikipagsapalaran",
    "Ein entspannender Spa-Tag" to "Isang nakakarelaks na araw ng spa",
    "Ein ganz normaler Alltagstag" to "Isang ganap na normal na araw-araw na araw",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Isang maaliwalas na gabi sa bahay sa panahon ng bagyo",
    "Ein gemütliches Date drinnen" to "Isang maaliwalas na date sa loob ng bahay",
    "Ein lustiges Bild" to "Isang nakakatawang larawan",
    "Ein paar Handyfotos reichen" to "Sapat na ang ilang larawan ng cellphone",
    "Ein paar Stunden" to "Ilang oras",
    "Ein paar kulturelle Anklänge sind okay" to "Okay lang ang ilang cultural reference",
    "Ein romantischer Abend" to "Isang romantikong gabi",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Isang romantikong candlelit dinner",
    "Ein romantisches Bild" to "Isang romantikong imahe",
    "Ein romantisches Picknick an einem schönen Ort" to "Isang romantikong piknik sa magandang lokasyon",
    "Ein schwerer Moment, den wir geschafft haben" to "Isang mahirap na sandali na kinaya namin",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Isang magandang date sa labas sa ilalim ng liwanag ng buwan",
    "Ein ungewöhnliches Gericht" to "Isang hindi pangkaraniwang ulam",
    "Ein zufälliger Schnappschuss" to "Isang random na snapshot",
    "Einander kennenlernen" to "Pagkilala sa isa't isa",
    "Eine Autoreise" to "Isang road trip",
    "Eine Brücke" to "Isang tulay",
    "Eine Date-Nacht unter den Sternen" to "Isang gabi ng pakikipag-date sa ilalim ng mga bituin",
    "Eine Million Dollar gewinnen" to "Manalo ng isang milyong dolyar",
    "Eine Million Dollar verdienen" to "Kumita ng isang milyong dolyar",
    "Eine Nacht in einem Club" to "Isang gabi sa isang club",
    "Eine Schokoladenverkostung" to "Isang pagtikim ng tsokolate",
    "Eine Wanderung mit Panoramablick machen" to "Maglakad na may malalawak na tanawin",
    "Eine Weinverkostung" to "Isang pagtikim ng alak",
    "Eine gemeinsame Reise" to "Isang paglalakbay na magkasama",
    "Eine gemütliche Nacht zu Hause" to "Isang maaliwalas na gabi sa bahay",
    "Eine neue Sprache zu lernen ist einfach." to "Ang pag-aaral ng bagong wika ay madali.",
    "Einen Film anschauen" to "Manood ng pelikula",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Hindi nag-uusap sa isa't isa sa loob ng isang buwan",
    "Einen Tanzkurs besuchen" to "Kumuha ng dance class",
    "Einen Vergnügungspark erkunden" to "Mag-explore ng amusement park",
    "Einen Wellness-Tag" to "Isang araw ng kalusugan",
    "Einen sehr emotionalen Partner haben" to "Ang pagkakaroon ng napaka-emosyonal na kapareha",
    "Einen sehr logischen Partner haben" to "Ang pagkakaroon ng napakalohikal na kapareha",
    "Einer zahlt alles" to "Isang tao ang nagbabayad ng lahat",
    "Einfach mehr Alltag" to "Mas pang-araw-araw na buhay",
    "Einfach nebeneinander sein" to "Magkatabi lang kayo",
    "Einfach und intim" to "Simple at intimate",
    "Einige Dinge für dich behalten" to "Panatilihin ang ilang bagay sa iyong sarili",
    "Einmal" to "Minsan",
    "Eins, das nur wir kennen" to "Isa na tayo lang ang nakakaalam",
    "Englisch" to "Ingles",
    "Entspannte Hängematte" to "Nakaka-relax na duyan",
    "Entspannung" to "Relaxation",
    "Erdbeere" to "Strawberry",
    "Erfolgreich" to "Matagumpay",
    "Ergebnisse" to "Mga Resulta",
    "Erst bei sehr großen Summen" to "Para lang sa napakalaking halaga",
    "Erst nur enge Freunde/Familie" to "Mga malalapit na kaibigan/pamilya lang sa una",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Naiinis ako kapag masyadong matagal tumugon ang partner ko sa mga mensahe.",
    "Essen & Genuss" to "Pagkain at kasiyahan",
    "Essensvorlieben" to "Mga kagustuhan sa pagkain",
    "Etwa eine Woche später, erst mal nur wir" to "Makalipas ang halos isang linggo, kami lang muna",
    "Etwas Neues ausprobieren" to "Subukan ang bago",
    "Etwas ganz anderes" to "Isang bagay na ganap na naiiba",
    "Etwas sehr Scharfes" to "Isang bagay na napakatalim",
    "Etwas, das ich selbst gern erfinde" to "Isang bagay na gusto kong imbentuhin sa aking sarili",
    "Etwas, eine kleine Note wäre schön" to "Isang bagay, isang maliit na tala ay magiging maganda",
    "Familie" to "Pamilya",
    "Familie/Freunde" to "Pamilya/Kaibigan",
    "Familienmensch" to "Pamilyar",
    "Farbedelstein" to "May kulay na gemstone",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Minsan kawili-wiling panoorin ang mga patalastas sa TV.",
    "Fertig" to "Tapos na",
    "Fertig!" to "Tapos na!",
    "Feste Date-Nights" to "Mga gabi ng nakatakdang petsa",
    "Feuerstelle" to "Fire pit",
    "Filigran & schlicht" to "Filigree at simple",
    "Filme/Serien" to "Mga pelikula/serye",
    "Formuliere um..." to "Muling parirala...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "I-rephrase ang iyong draft sa paraang hindi marahas: pagmamasid, pakiramdam, pangangailangan, kahilingan.",
    "Frage hinzufügen" to "Magdagdag ng tanong",
    "Fragen & Spiele" to "Mga Tanong at Laro",
    "Fragen für jede Gelegenheit" to "Mga tanong para sa bawat okasyon",
    "Freizeitpark" to "Amusement park",
    "Freunde treffen" to "Kilalanin ang mga kaibigan",
    "Freundschaften mit Ex-Partnern sind okay." to "Okay lang ang pagkakaibigan sa mga ex.",
    "Früh aufstehen" to "Gumising ka ng maaga",
    "Fußbodenheizung" to "Underfloor heating",
    "Führen wir getrennte oder gemeinsame Konten?" to "Mayroon ba tayong hiwalay o pinagsamang mga account?",
    "Für dich empfohlen" to "Inirerekomenda para sa iyo",
    "Für die Zukunft" to "Para sa hinaharap",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Walang nahanap na tumutugmang mga tanong o laro para sa paghahanap na ito.",
    "Für immer" to "Magpakailanman",
    "Fürsorglichkeit" to "Mapagmalasakit",
    "GFK-Brücke" to "GRP tulay",
    "Galerie" to "Gallery",
    "Gar nicht, der Moment gehört uns" to "Hindi naman, ang moment ay atin na",
    "Gar nichts tun" to "Huwag kang gumawa",
    "Geduld" to "Pasensya",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Pumunta ng maaga sa umaga para makita ang pagsikat ng araw",
    "Geht so" to "Nagiging ganito",
    "Geister existieren wirklich." to "May mga multo talaga.",
    "Gelassenheit" to "Katahimikan",
    "Gelbgold" to "Dilaw na ginto",
    "Geld & Finanzen" to "Pera at Pananalapi",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Maglakbay sa mundo nang magkasama, galugarin ang mga bagong kultura at lutuin",
    "Gemeinsam ein Lego bauen" to "Magkasamang bumuo ng Lego",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Subukan ang isang bagong recipe nang magkasama sa kusina",
    "Gemeinsame Konten" to "Mga nakabahaging account",
    "Gemeinsame Nächte" to "Mga gabing magkasama",
    "Gemeinsame Tage" to "Mga araw na magkasama",
    "Gemischt" to "Pinaghalo",
    "Gemüsebeet" to "Tagpi-tagpi ng gulay",
    "Gemütliche Feuerstelle" to "Maginhawang fireplace",
    "Gesprächsanreger" to "Panimula ng pag-uusap",
    "Getrennte Konten" to "Paghiwalayin ang mga account",
    "Getrennte Urlaube tun einer Beziehung gut." to "Ang mga hiwalay na bakasyon ay mabuti para sa isang relasyon.",
    "Gewächshaus" to "Greenhouse",
    "Glasfassade" to "Glass facade",
    "Gleichgültigkeit" to "Kawalang-interes",
    "Glücklich und frei" to "Masaya at libre",
    "Gourmet Eis-Sorten" to "Mga uri ng gourmet ice cream",
    "Gravur innen" to "Pag-ukit sa loob",
    "Grillplatz" to "Lugar ng barbecue",
    "Groß & üppig" to "Malaki at malago",
    "Große Familie" to "Malaking pamilya",
    "Große Feier" to "Malaking pagdiriwang",
    "Große Fenster" to "Malaking bintana",
    "Große Fensterfront" to "Malaking bintana sa harap",
    "Großer Außenpool" to "Malaking outdoor pool",
    "Großer Garten" to "Malaking hardin",
    "Großer Stein" to "Malaking bato",
    "Größere Küche" to "Mas malaking kusina",
    "Gutes Essen" to "Masarap na pagkain",
    "Habe ich" to "Ginawa ko",
    "Habe ich noch nie" to "Hindi ko naranasan",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "May natuklasan ka bang nakakagulat na pagkakaiba? Pag-usapan kung bakit mas gusto mo ang ilang mga opsyon!",
    "Haus am See" to "Bahay sa tabi ng lawa",
    "Haus/Wohnung" to "Bahay/apartment",
    "Hazelnut" to "Hazelnut",
    "Heimkino" to "Home theater",
    "Herzhaft" to "Nakabubusog",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Wala dito ngayon.\nBaguhin ang filter o pumili ng ibang paksa.",
    "Hilfe im Alltag" to "Tulong sa pang-araw-araw na buhay",
    "Himbeere" to "Raspberry",
    "Hinzufügen" to "Idagdag",
    "Hobbys" to "Mga libangan",
    "Hochzeitssträuße" to "Mga bouquet sa kasal",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Hogwarts House Pride: Saan Ka Ba?",
    "Home" to "Tahanan",
    "Hot Tub" to "Hot Tub",
    "Humor" to "Katatawanan",
    "Hund" to "Aso",
    "Hängematte" to "Duyan",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Gusto mo ba ng nakasulat na liham bilang bahagi ng panukala?",
    "IKEA" to "IKEA",
    "Ich" to "Ako",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Mas gusto ko ang mga romantikong paglalakad sa parke kaysa pagpunta sa sinehan.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Hindi pa ako nakatulog sa sinehan.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Nasisiyahan akong tumuklas ng mga bagong libangan o aktibidad kasama ang aking kapareha.",
    "Ich finde eine Alternative" to "Hahanap ako ng alternatibo",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Nasisiyahan akong sumubok ng mga bagong restaurant kasama ang aking partner sa halip na palaging pumunta sa parehong mga lugar.",
    "Ich habe noch nie" to "Hindi ko pa kailanman",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Hindi ako natatakot sa isang roller coaster at nakasakay pa rin ako dito.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Hindi pa ako nakabili ng Fast Pass ticket dahil naiinip ako.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Hindi ko kailanman kinansela ang mga planong manatili sa bahay at manood ng palabas sa TV.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Hindi ko na hinintay ang sulat ko mula sa Hogwarts.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Hindi ko pa nasabi na hindi ganoon kalala si Slytherin.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Hindi ko sinabing masyado na akong matanda para sa mga pelikulang Disney (at lihim na nag-enjoy sa kanila).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Hindi ko sinasadyang barilin ang isang taong may asul na tangke sa Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Hindi pa ako naiyak sa isang pelikula sa Disney.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Never kong tinakpan ang mata ko habang nanonood ng horror movie.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Hindi ko nakalimutang mag-save ng isang laro at nawala ang mga oras ng pag-unlad.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Hindi pa ako lumabas ng kwarto sa isang nakakahiyang eksena (cringe factor).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Hindi pa ako nakagawa ng nakakatawang pose habang kumukuha ng rollercoaster na larawan.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Hindi pa ako naglaro hanggang gabi at pinagsisihan ang pagod ko kinabukasan.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Hindi ko na na-google ang ending ng isang pelikula dahil hindi ako makapaghintay.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Hindi ko naramdaman na nakatayo ako sa set ng pelikula.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Hindi ko na nilaktawan ang intro ng paborito kong serye.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Hindi pa ako nagbahagi ng password sa Netflix ng sinuman.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Hindi pa ako nakikinig sa soundtrack ng laro habang nagtatrabaho o nag-aaral.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Hindi ko kailanman sinisi ang controller kapag natalo ako.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Hindi ko kailanman itinapon ang keyboard o controller sa galit.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Hindi ko nakakalimutan ang mga basang damit sa washing machine sa loob ng ilang araw.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Hindi pa ako gumastos ng totoong pera sa mga cosmetic item sa isang laro.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Hindi pa ako nagmaneho ng kotse sa ibang bansa.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Hindi pa ako nakapag-belt ng isang Disney song sa shower.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Hindi pa ako nagmaneho ng electric car.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Hindi pa ako nakakuha ng litrato na may park mascot.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Hindi ko pa pinangalanan ang isang alagang hayop sa isang karakter ng Hogwarts.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Hindi pa ako naghulog ng popcorn sa isang sinehan at kinakain ko pa rin ito.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Hindi pa ako gumamit ng quote mula kay Master Yoda mula sa Star Wars sa pang-araw-araw na buhay.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Hindi pa ako nakabili ng sobrang mahal na souvenir sa isang theme park.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Hindi pa ako nagbigay ng rekomendasyon sa pelikula na nakita ng ibang tao na kakila-kilabot.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Hindi pa ako nakapanood ng Oscars nang live sa kalagitnaan ng gabi.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Wala akong kinansela na serye dahil napakasama ng huling season.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Hindi pa ako nakakapanood ng isang buong season ng isang serye sa isang araw.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Hindi ko pa natalo ang isang boss sa unang pagsubok at pakiramdam ko ay isang diyos.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Wala pa akong nakitang kontrabida na mas cool kaysa sa bida.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Wala pa akong nakilalang karakter ng Toy Story sa sarili kong mga laruan.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Hindi pa ako nakagawa ng character sa isang RPG na eksaktong katulad ko.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Hindi pa ako nakakakain ng churro sa isang theme park.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Hindi pa ako nakapanood ng pelikulang Disney nang tatlong sunod-sunod na beses.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Wala pa akong Disney catchy tune sa isang buong linggo.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Hindi pa ako nakapanood ng pelikula dahil lang sa isang artista.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Hindi pa ako nakikinig ng soundtrack ng pelikula nang paulit-ulit nang maraming oras.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Hindi pa ako nagsiwalat ng spoiler ng pelikula at agad kong pinagsisihan ito.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Wala pa akong nahanap na kaibigan na nagsasalita ng ibang katutubong wika.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Wala pa akong kaibigan na lumipat sa ibang bansa.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Hindi pa ako nakakagawa ng Harry Potter movie marathon sa Pasko.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Hindi pa ako nakapanood ng Marvel movie hanggang sa huli dahil lang sa post-credit scene.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Hindi ko sinasadyang inisin ang isang NPC (Non-Player Character).",
    "Ich habe noch nie einen Nachtzug genommen." to "Hindi pa ako nakasakay ng night train.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Hindi pa ako kumuha ng online na pagsusulit para malaman ang aking bahay sa Hogwarts.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Hindi ako kailanman nag-delete ng post sa social media dahil hindi ito nakakuha ng sapat na likes.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Hindi ko kailanman tinawag ang isang araw sa theme park na pinakamagandang araw ng taon.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Hindi pa ako nakabisita sa isang theme park at nanatili doon mula umaga hanggang gabi.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Hindi pa ako nag-iwan ng biyaheng Transformers o Marvel na talagang nabighani.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Hindi ako kailanman naglabas ng galit na huminto at huminto sa laro.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Hindi ko pa nabasa ang alinman sa malalaking volume ng Harry Potter.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Hindi pa ako nag-rave tungkol sa paborito kong karakter sa isang serye.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Hindi ko pinangarap na maglaro ng Quidditch.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Hindi pa ako lihim na nag-google kung paano mag-solve ng hard level.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Hindi ako lihim na umaasa na ang aking alaga ay maaaring magsalita tulad ng sa Disney.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Hindi ko pa inalis ang pinuno ng pool sa Sims.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Hindi pa ako nawawalan ng bearings sa isang 3D simulator ride.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Hindi pa ako nakakalaro sa isang sports team ng unibersidad.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Hindi pa ako naghintay sa pila nang higit sa dalawang oras para sa isang atraksyon.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Hindi ko pa nabasa ang aking mahahalagang gamit sa pagsakay sa tubig.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Hindi pa ako nakipagtalo sa isang kaibigan tungkol sa kung aling bahay ang pinakamaganda.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Never akong nagpanggap na may mahiwagang kapangyarihan gaya ni Elsa.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Kailanman ay hindi ako tumawa nang labis na na-miss ko ang isang mahalagang eksena sa isang pelikula.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Hindi ko pa naramdaman ang labis na adrenaline na gusto kong sumakay muli.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Hindi ko pa nasusubukang kumanta kasama ang mga hayop tulad ni Snow White.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Hindi ko pinangarap na makapunta sa Disneyland.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Hindi ko pinangarap na makasakay sa Jurassic Park water ride.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Hindi pa ako nakasigaw ng malakas sa isang jump scare sa isang laro.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Hindi pa ako naiyak sa finale ng isang palabas sa TV.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Hindi ko kailanman... kinansela ang isang petsa para manatili sa bahay.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Hindi ko kailanman... ni-rephrase ang isang mensahe nang 10 beses.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Hindi ko pa... palihim na tiningnan ang cell phone ng partner ko.",
    "Ich habe noch nie!" to "Hindi ko pa kailanman!",
    "Ich habe!" to "Meron ako!",
    "Ich lache viel mit meinem Partner." to "Tawa ako ng tawa kasama ang partner ko.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Gusto kong kilalanin ang mga libangan at interes ng aking kapareha.",
    "Ich liebe es" to "Gusto ko ito",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Gustung-gusto kong manood ng mga pelikula kasama ang aking kapareha na hindi pa namin nakita noon.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Gusto kong ibahagi ang aking paboritong musika sa aking kapareha.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Hindi ko na kinailangan pang tumakbo para sumakay ng connecting flight.",
    "Ich plane gerne Dates mit meinem Partner." to "Gusto kong magplano ng mga petsa kasama ang aking kapareha.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Mas inuuna ko ang paggugol ng oras sa aking kapareha kahit na ako ay abala.",
    "Ich schreibe meinem Partner jeden Tag." to "Araw-araw akong nagte-text sa partner ko.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Gusto kong magbahagi ng mga meme at biro sa aking kapareha.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Gusto kong ibahagi ang lahat ng detalye ng araw ko sa aking kapareha.",
    "Ich würde es nie tun" to "Hinding-hindi ko gagawin ito",
    "Ich übe noch" to "Nagpa-practice pa ako",
    "Ideen generieren" to "Bumuo ng mga ideya",
    "Im Haushalt helfen" to "Tulong sa paligid ng bahay",
    "In Chat einfügen" to "Idagdag sa chat",
    "In Stille nebeneinander" to "Sa katahimikan sa tabi ng isa't isa",
    "In den Bergen" to "Sa kabundukan",
    "In eine Bar gehen" to "Pumunta sa isang bar",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Pupunta sa isang beach bar para panoorin ang paglubog ng araw",
    "In einem feinen Restaurant essen gehen" to "Kumakain sa labas sa isang magandang restaurant",
    "In einen Coffeeshop gehen" to "Pumunta sa isang coffee shop",
    "In einer Beziehung sollte man alles voneinander wissen." to "Sa isang relasyon dapat alam niyo lahat ng tungkol sa isa't isa.",
    "Infinity-Pool" to "Infinity pool",
    "Innenpool" to "Panloob na pool",
    "Intelligenz" to "Katalinuhan",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Nagkakaroon lang ng intimate moments kapag sinimulan sila ng iyong partner",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Invite code: HRM-8731 · lahat ay naka-unlock",
    "Island" to "Iceland",
    "Ist okay für mich" to "Okay lang sa akin",
    "Ist schon perfekt" to "Ito ay perpekto",
    "Ja, Traditionen einbinden" to "Oo, isama ang mga tradisyon",
    "Ja, absolut" to "Oo, talagang",
    "Ja, etwas zum Lesen und Aufbewahren" to "Oo, isang bagay na dapat basahin at panatilihin",
    "Ja, genug" to "Oo, sapat na",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Oo, sa isang kapana-panabik na lungsod o atraksyon",
    "Ja, in- und auswendig" to "Oo, sa loob at labas",
    "Ja, komplett überraschend" to "Oo, talagang nakakagulat",
    "Ja, perfekt" to "Oo, perpekto",
    "Ja, sie gehören zur Familie!" to "Oo, pamilya sila!",
    "Ja, sofort teilen" to "Oo, share agad",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Oo, sisiguraduhin naming priority ang family time.",
    "Jacuzzi" to "Jacuzzi",
    "Jahr zusammen 🎉" to "taon na magkasama 🎉",
    "Jahre zusammen 🎉" to "Taon na magkasama 🎉",
    "Jeder zahlt 50%" to "Lahat ay nagbabayad ng 50%",
    "Junge" to "Boy",
    "Kamin" to "Fireplace",
    "Karriere & Erfolg" to "Karera at Tagumpay",
    "Kategorien" to "Mga Kategorya",
    "Katze" to "Cat",
    "Keine Musik" to "Walang musika",
    "Keine Party nötig, privat halten" to "No need for a party, keep it private",
    "Keine Privatsphäre" to "Walang privacy",
    "Keine Treffer gefunden" to "Walang nakitang tugma",
    "Keiner" to "Wala",
    "Keiner von uns" to "Wala sa amin",
    "Kennst du die Essensvorlieben deines Partners?" to "Alam mo ba ang mga kagustuhan sa pagkain ng iyong partner?",
    "Kino" to "Sinehan",
    "Kirchlich" to "Eklesiastiko",
    "Klassisch Solitär" to "Klasikong solitaryo",
    "Klassisch gebunden" to "Classically bound",
    "Klein & zart" to "Maliit at maselan",
    "Kleine Geschenke" to "Maliit na regalo",
    "Kleine Runde" to "Maliit na grupo",
    "Kochen und Freunde einladen" to "Nagluluto at nag-iimbita ng mga kaibigan",
    "Kochkurs" to "Klase sa pagluluto",
    "Kommt auf den Tag an" to "Depende sa araw",
    "Kommt darauf an" to "Depende",
    "Kommt drauf an" to "Depende",
    "Kommt mit" to "Sumama ka sa akin",
    "Konzert" to "Concert",
    "Kräftige Farben" to "Matitinding kulay",
    "Kräuterbeet" to "Herb bed",
    "Kultur & Sehenswürdigkeiten" to "Kultura at Tanawin",
    "Kuscheln" to "Niyakap",
    "Kuss senden" to "Magpadala ng halik",
    "Körperliche Annäherung" to "Pisikal na diskarte",
    "Körperliche Nähe" to "Pisikal na closeness",
    "Küche" to "Kusina",
    "Land" to "Bansa",
    "Landhaus" to "Bahay sa kanayunan",
    "Landhausstil" to "Estilo ng country house",
    "Lange wach bleiben" to "Mapuyat ka",
    "Lappland" to "Lapland",
    "Lappland, Finnland" to "Lapland, Finland",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Hayaan ang iyong kapareha na magbigay ng inspirasyon sa iyo na maging ang iyong pinakamahusay na sarili",
    "Lehne ab" to "Tanggihan",
    "Leichtigkeit" to "Ang gaan",
    "Leidenschaft" to "Pasyon",
    "Liebe im Gleichgewicht" to "Pag-ibig sa balanse",
    "Liebe sie, macht mehr Spaß" to "Mahalin mo sila, mas masaya",
    "Lieber durchgeplant oder spontan?" to "Mas gugustuhin mo bang planado ito o kusang-loob?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Mas gusto mo bang magkaroon ng tahimik na gabi para sa dalawa o kasama ng mga tao?",
    "Lieber nicht" to "Mas mabuting hindi",
    "Lieber vorher grob absprechen" to "Mas mabuting pag-usapan muna ang mga bagay-bagay",
    "Lokal einkaufen" to "Mamili nang lokal",
    "London" to "London",
    "London, England" to "London, England",
    "Lügen" to "Kasinungalingan",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Mas gusto mo ba ang pampubliko o pribadong panukala?",
    "Malediven" to "Maldives",
    "Man sollte nie streitend einschlafen." to "Hindi ka dapat matulog sa pakikipagtalo.",
    "Mango Sorbet" to "Mango Sorbet",
    "Markant & breit" to "Kapansin-pansin at malawak",
    "Marken & Alltag" to "Mga tatak at pang-araw-araw na buhay",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "Mediterranean courtyard",
    "Mehr Unterstützung" to "Higit pang suporta",
    "Mehr gemeinsame Zeit" to "Mas maraming oras na magkasama",
    "Mehr zuhören" to "Makinig pa",
    "Mehrgenerationenhaus" to "Multi-generational na bahay",
    "Mein Arbeitsplatz" to "Ang lugar ng trabaho ko",
    "Mein Partner" to "Yung partner ko",
    "Mich überraschen" to "Surprise ako",
    "Minimalistisches Interieur" to "Minimalist na interior",
    "Missverständnisse" to "Mga hindi pagkakaunawaan",
    "Mit Familie und engen Freunden" to "Kasama ang pamilya at malalapit na kaibigan",
    "Mit Kompromissen" to "Sa mga kompromiso",
    "Mitgefühl" to "Habag",
    "Mittelweg mit besonderen Details" to "Gitnang lupa na may mga espesyal na detalye",
    "Modern geometrisch" to "Modernong geometriko",
    "Moderne Grillstation" to "Modernong istasyon ng grill",
    "Moderner Name" to "Modernong pangalan",
    "Moderner Solitär" to "Modernong solitaryo",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "Kunin ang sandali",
    "Momente" to "sandali",
    "Monaco" to "Monaco",
    "Moralische Werte" to "Mga pagpapahalagang moral",
    "Museum" to "Museo",
    "Musik" to "Musika",
    "Mut" to "Lakas ng loob",
    "Mädchen" to "Mga babae",
    "Möbelhaus" to "Tindahan ng muwebles",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Sigurado ka bang gusto mong umalis sa pagsusulit? Ang iyong nakaraang pag-unlad ay nananatiling naka-save.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Gusto mo bang maisama ang mga alagang hayop sa application?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Gusto mo bang maibahagi agad ang sandali sa social media?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Maaaring kailanganin nating mag-ipon",
    "Müssen es planen" to "Kailangang planuhin ito",
    "Müssen sparen" to "Kailangang magtipid",
    "Nachricht an" to "Mensahe",
    "Name Partnerin" to "Pangalan ng partner",
    "Namen und Startdatum eurer Beziehung." to "Mga pangalan at petsa ng pagsisimula ng iyong relasyon.",
    "Natursteinfassade" to "Natural na batong harapan",
    "Naturteich" to "Natural pond",
    "Nein, einfach halten" to "Hindi, hawakan mo lang",
    "Nein, erstmal privat halten" to "Hindi, panatilihin itong pribado sa ngayon",
    "Nein, lieber vor Ort" to "Hindi, mas maganda sa site",
    "Nein, modern halten" to "Hindi, panatilihin itong moderno",
    "Nein, nur wir" to "Hindi, kami lang",
    "Nein, zu ablenkend" to "Hindi, masyadong nakakagambala",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Bagong gusaling may matalinong tahanan",
    "Neubau mit Technik" to "Bagong gusali na may teknolohiya",
    "Neue Liebe, neue Erfahrungen" to "Bagong pag-ibig, bagong karanasan",
    "Neues Hobby" to "Bagong libangan",
    "Neues Spiel" to "Bagong laro",
    "Neugier" to "Pagkausyoso",
    "New York" to "New York",
    "New York, USA" to "New York, USA",
    "Nicht mein Fall" to "Hindi ang aking tasa ng tsaa",
    "Nicht nötig, lieber klassisch bleiben" to "Hindi kailangan, mas mabuting manatiling classic",
    "Nichts — es passt so" to "Wala - kasya",
    "Nie wieder Burger" to "Huwag nang mag-burger",
    "Nie wieder Pizza" to "Huwag nang magpi-pizza muli",
    "Niemand" to "Walang tao",
    "Niemand ohne Plan" to "Walang sinumang walang plano",
    "Nike" to "Nike",
    "Nizza" to "Magaling",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Wala pang sandali.\nKunin ang iyong unang karanasan 💞",
    "Nur bei wichtigen Themen" to "Para lang sa mahahalagang paksa",
    "Nur wir beide" to "Tayong dalawa lang",
    "Nähe & Intimität" to "Closeness at Intimacy",
    "Obstgarten" to "Orchard",
    "Oder" to "O kaya",
    "Offene Küche" to "Open kitchen",
    "Offene Wohnküche" to "Buksan ang kusina/sala",
    "Ohne Stein" to "Walang bato",
    "Open End" to "Open ending",
    "Outdoor-Küche" to "Panlabas na kusina",
    "Outdoor-Sofa" to "Panlabas na sofa",
    "Outdoor-Whirlpool" to "Outdoor whirlpool",
    "Ovaler Diamant" to "Oval na brilyante",
    "Paar" to "Pares",
    "Paar-Statistiken" to "Mga istatistika ng mag-asawa",
    "Paris" to "Paris",
    "Paris, Frankreich" to "Paris, France",
    "Partner" to "Kasosyo",
    "Partner-Simulator" to "Partner simulator",
    "Partnerin" to "Kasosyo",
    "Party Edition" to "Party Edition",
    "Party Edition II" to "Party Edition II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Bagay ba ang isang hayop sa ating pang-araw-araw na buhay?",
    "Pasta" to "Pasta",
    "Pastell" to "Pastel",
    "Penthouse mit Ausblick" to "Penthouse na may tanawin",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pergola na may lounge",
    "Pfingstrosen" to "Peonies",
    "Pinguin" to "Penguin",
    "Pistazie" to "Pistachio",
    "Pizza" to "Pizza",
    "Pizzaofen" to "Pizza oven",
    "Platin" to "Platinum",
    "PlayStation" to "PlayStation",
    "Pool" to "Pool",
    "Pop" to "Pop",
    "Prasselnder Kamin" to "Umaatungal na tsiminea",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Mga Prinsesa, Pirata at Alikabok ng Diwata: Pagsusulit sa Disney",
    "Privater Innenhof" to "Pribadong patyo",
    "Profil" to "Profile",
    "Profil bearbeiten" to "I-edit ang profile",
    "Prozentual nach Einkommen" to "Porsyento batay sa kita",
    "Quiz verlassen" to "Tumigil sa pagsusulit",
    "Quiz verlassen?" to "Umalis sa pagsusulit?",
    "Rausgehen in die Natur" to "Lumabas sa kalikasan",
    "Reden vor ..." to "Nagsasalita sa...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Mag-iskedyul ng mga regular na petsa o oras nang magkasama",
    "Reisen" to "Paglalakbay",
    "Reiseziele" to "Mga destinasyon sa paglalakbay",
    "Respektlosigkeit" to "Kawalang-galang",
    "Restaurant" to "Restaurant",
    "RnB / Soul" to "RnB / Soul",
    "Rock" to "Bato",
    "Rom" to "Roma",
    "Rom, Italien" to "Roma, Italy",
    "Romantik" to "Romansa",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Ang mga romantikong galaw gaya ng mga mensahe, tala o regalo ay nagpapasaya sa akin.",
    "Romantische Stimmung" to "Romantikong mood",
    "Roségold" to "Rose gold",
    "Ruhig zu zweit" to "Tahimik para sa dalawa",
    "Runder Diamant" to "Bilog na brilyante",
    "Salted Caramel" to "Salted Caramel",
    "Sammle Ideen..." to "Mangolekta ng mga ideya...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Greece",
    "Saphir" to "Sapiro",
    "Saunahaus" to "Sauna house",
    "Schickes Restaurant oder Hotel" to "Magandang restaurant o hotel",
    "Schlafzimmer" to "Silid-tulugan",
    "Schließen" to "Isara",
    "Schmal & zart" to "Payat at maselan",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Mga snapshot mula sa aming love story",
    "Schokolade" to "Tsokolate",
    "Schreib frei, was dir wirklich dazu einfällt." to "Malayang isulat kung ano talaga ang nasa isip.",
    "Schreibe deine eigene Antwort" to "Sumulat ng sarili mong sagot",
    "Sehr gerne" to "Bahala ka",
    "Sehr leicht" to "Napakagaan",
    "Sehr wichtig — Fotos und Video" to "Napakahalaga — mga larawan at video",
    "Sehr wichtig, es sollte persönlich sein" to "Napakahalaga, dapat personal",
    "Selbst kochen" to "Magluto ka",
    "Senden" to "Ipadala",
    "Separate Küche" to "Hiwalay na kusina",
    "Serie schauen" to "Panoorin ang serye",
    "Serienmarathon auf dem Sofa" to "Series marathon sa sofa",
    "Sex & Liebe" to "Sex at Pag-ibig",
    "Seychellen" to "Seychelles",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Nagagawa ba namin ang lahat ng gastos para sa isang bata/maraming bata? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Dapat bang sorpresa ang panukala?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Dapat bang maglaman ang application ng mga kultural o tradisyonal na elemento?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Dapat bang maglaman ang application ng mga kultural o tradisyonal na elemento?",
    "Sommerhochzeit" to "Kasal sa tag-araw",
    "Sonnige Dachterrasse" to "Maaraw na terrace sa bubong",
    "Sowohl als auch" to "Pareho at",
    "Spazieren" to "Maglakad-lakad",
    "Spaß & Abenteuer" to "Kasiyahan at Pakikipagsapalaran",
    "Speichern" to "I-save",
    "Spiel bearbeiten" to "I-edit ang laro",
    "Spielbereich für Kinder" to "Palaruan para sa mga bata",
    "Spiele" to "Mga laro",
    "Spiele spielen und Spaß haben" to "Maglaro at magsaya",
    "Spontan" to "Kusang",
    "Sportplatz" to "Sports field",
    "Spotify" to "Spotify",
    "Sprache" to "Wika",
    "Stadt" to "Lungsod",
    "Stadt oder Land — was ist uns wichtiger?" to "Lungsod o bansa - ano ang mas mahalaga sa atin?",
    "Stadtvilla" to "City villa",
    "Standesamt & Party" to "Registry office at party",
    "Statement-Ring" to "Singsing ng pahayag",
    "Stilvolles Outdoor-Sofa" to "Naka-istilong outdoor sofa",
    "Stimme voll zu" to "Ganap na sumasang-ayon",
    "Stimmt" to "Tama",
    "Stimmt nicht" to "Hindi totoo",
    "Stimmt, noch nie" to "Totoo, hindi kailanman",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Araw ng beach",
    "Streit über Haushalt" to "Hindi pagkakaunawaan tungkol sa sambahayan",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "Patuloy",
    "Suche schließen" to "Isara ang paghahanap",
    "Suche zurücksetzen" to "I-reset ang paghahanap",
    "Suche öffnen" to "Buksan ang paghahanap",
    "Suchergebnisse" to "Mga resulta ng paghahanap",
    "Sushi" to "Sushi",
    "Süß" to "Ang sweet",
    "Tage zusammen 💞" to "araw na magkasama 💞",
    "Tauche ins Unterbewusstsein" to "Sumisid sa subconscious",
    "Teile alle deine Hobbys mit deinem Partner" to "Ibahagi ang lahat ng iyong libangan sa iyong kapareha",
    "Teils teils" to "Bahagyang bahagyang",
    "Testen" to "Pagsubok",
    "Themen" to "Mga Paksa",
    "Tiefe Gespräche" to "Malalim na pag-uusap",
    "Tiefgründige Gespräche führen" to "Magkaroon ng malalim na pag-uusap",
    "Tierpension" to "Boarding house ng hayop",
    "Tiny House" to "Maliit na Bahay",
    "Tippen zum Auswählen & Scrollen" to "I-tap para piliin at mag-scroll",
    "Tippen zum Zuklappen" to "I-tap para i-collapse",
    "Titel" to "Pamagat",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Pamagat, Kategorya, Paksa, Mga Tag, Mga Tanong...",
    "Tokyo, Japan" to "Tokyo, Japan",
    "Traditioneller Name" to "Tradisyonal na pangalan",
    "Traumhaus Außenbereich" to "Dream house outdoor area",
    "Traumhochzeit" to "Pangarap na kasal",
    "Treffer" to "Hit",
    "Tägliche Aktivität" to "Pang-araw-araw na aktibidad",
    "Umformulieren" to "Muling parirala",
    "Unbeantwortet" to "Hindi nasagot",
    "Unbeliebte Meinungen" to "Mga hindi sikat na opinyon",
    "Universal Studios Genie oder Neuling?" to "Universal Studios henyo o newbie?",
    "Uns auseinanderzuleben" to "Para magkahiwalay",
    "Unser Intimleben" to "Ang aming matalik na buhay",
    "Unser Traumhaus" to "Ang pangarap naming bahay",
    "Unser erstes Treffen" to "Ang una nating pagkikita",
    "Unsere Gesichter" to "Yung mga mukha namin",
    "Unsere eigenen Träume" to "Sariling pangarap",
    "Unsere nächste Reise" to "Ang aming susunod na paglalakbay",
    "Unter 1000" to "Wala pang 1000",
    "Unter 1000 im Monat" to "Wala pang 1000 kada buwan",
    "Unter 50€/Monat" to "Wala pang 50€/buwan",
    "Unter Leuten" to "Sa mga tao",
    "Untreue" to "Pagtataksil",
    "Urlaub" to "Bakasyon",
    "Vanille" to "Vanilla",
    "Venedig" to "Venice",
    "Venedig, Italien" to "Venice, Italy",
    "Verbinde dich mit" to "Kumonekta sa",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Kumonekta sa \${profile.partnerName} para makita ang sagot",
    "Verbindung" to "koneksyon",
    "Verbringe die Feiertage mit deiner Familie" to "Gumugol ng bakasyon kasama ang iyong pamilya",
    "Verlobungsringe" to "Engagement ring na",
    "Vertrautheit" to "Pamilyar",
    "Viel getrennt" to "Maraming paghihiwalay",
    "Vielleicht ein oder zwei" to "Siguro isa o dalawa",
    "Vielleicht, aber mündlich reicht" to "Siguro, pero verbally is enough",
    "Vielleicht, wenn es machbar ist" to "Siguro, kung pwede lang",
    "Vielleicht, wenn es passt" to "Siguro, kung magkasya",
    "Vintage Art déco" to "Vintage Art Deco",
    "Vintage verspielt" to "Vintage na mapaglaro",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Ipinakilala sa mga bagong libangan ng iyong kapareha",
    "Vor dem Kauf eines Hauses besprechen" to "Pag-usapan bago bumili ng bahay",
    "Vor der Anschaffung eines Haustiers besprechen" to "Pag-usapan bago bumili ng alagang hayop",
    "Vor der gemeinsamen Reise besprechen" to "Pag-usapan bago maglakbay nang magkasama",
    "Vor nichts" to "Wala",
    "Vorort" to "Suburb",
    "Walnuss" to "Walnut",
    "Wandern" to "Hiking",
    "Wann fühlst du dich mir am nächsten?" to "Kailan mo pakiramdam na pinakamalapit sa akin?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Kailan mo pakiramdam na pinakamalapit sa akin?",
    "Was bedeutet Vertrauen für dich konkret?" to "Ano ang ibig sabihin ng tiwala para sa iyo?",
    "Was entspannt dich mehr?" to "Ano ang mas nakakapagpapahinga sa iyo?",
    "Was fehlt dir über die Distanz am meisten?" to "Ano ang pinakanami-miss mo sa layo?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Ano ang pinakagusto mo sa iyong tahanan?",
    "Was hast du von deinem Partner gelernt?" to "Ano ang natutunan mo sa iyong partner?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Ano sa tingin mo ang tungkol sa panonood ng erotikong nilalaman nang magkasama?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Ano sa palagay mo ang tungkol sa mga props (hal. mga karatula, lobo, atbp.)?",
    "Was ist das Wichtigste beim Antrag?" to "Ano ang pinakamahalagang bagay kapag nag-a-apply?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Ano ang pinakamahalagang bagay na hinahanap mo sa isang pakikipagtalik?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Ano ang paborito mong larawan namin? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Ano ang pinakamalaking kinatatakutan mo tungkol sa pamumuhay nang magkasama?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Ano ang paborito mong pagkain ngunit hindi maintindihan ng iyong partner?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Ano ang isang ganap na dealbreaker para sa iyo?",
    "Was ist für jeden von uns das absolute Highlight?" to "Ano ang ganap na highlight para sa bawat isa sa atin?",
    "Was ist passiert?" to "Anong nangyari?",
    "Was macht einen Moment für dich romantisch?" to "Ano ang ginagawang romantiko para sa iyo?",
    "Was magst du an deinem Partner am liebsten?" to "Ano ang pinakagusto mo sa iyong partner?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Ano ang mas gusto mo: gumising ng maaga o magpuyat?",
    "Was magst du lieber?" to "Alin ang mas gusto mo?",
    "Was möchtest du eigentlich sagen?" to "Ano ba talaga ang gusto mong sabihin?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Ano ang gusto mong gawin ng iyong partner nang mas madalas?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Ano ang nangyayari sa hayop kapag naglalakbay tayo?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Ano kaya ang magiging anak natin paglaki nito?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Ano ang hindi natin dapat kalimutan bilang mga magulang?",
    "Was war dein schönster Moment mit mir bisher?" to "Ano ang pinakamagandang sandali mo sa akin sa ngayon?",
    "Was wir gegessen haben" to "Yung kinain namin",
    "Was wollt ihr nie vergessen?" to "Ano ang hindi mo gustong kalimutan?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Ano ang mas masahol para sa iyo: hindi na muling magpi-pizza o hindi na mag-burger?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Ano ang pinakagusto mong gawin sa isang araw na magkasama?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Ano ang babaguhin mo kaagad kung hindi isyu ang pera?",
    "Weiter" to "Susunod",
    "Weiter spielen" to "Magpatuloy sa paglalaro",
    "Weiß ich noch nicht" to "Hindi ko pa alam",
    "Weiße Rosen" to "Mga puting rosas",
    "Weißgold" to "Puting ginto",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Anong kalidad ang tiyak na makukuha ng ating anak sa atin?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Anong kapaligiran ang gusto mo para sa isang panukala?",
    "Welcher Raum sagt am meisten über dich aus?" to "Aling kwarto ang higit na nagsasabi tungkol sa iyo?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Anong budget ang plano natin para sa pagkain at vet?",
    "Welches Lied macht dich an? 🥵" to "Aling kanta ang nakaka-on sa iyo? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Aling nakabahaging larawan ang paborito mo?",
    "Wellnessbad" to "Wellness bath",
    "Wenn es schwierig ist" to "Kapag mahirap ang mga bagay",
    "Wenn ich müde bin" to "Kapag pagod na ako",
    "Wenn wir uns lange umarmen" to "Kapag magkayakap kami ng matagal",
    "Wenn wir zusammen lachen" to "Kapag sabay tayong tumatawa",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Sino ang mas mabilis na magpapasya kung ano ang iuutos?",
    "Wer findet die besten Restaurants?" to "Sino ang nakakahanap ng pinakamagagandang restaurant?",
    "Wer gibt mehr Herzlichkeit?" to "Sino ang nagbibigay ng higit na init?",
    "Wer hat den besseren Musikgeschmack?" to "Sino ang mas mahilig sa musika?",
    "Wer hängt mehr an seinen Eltern?" to "Sino ang mas attached sa kanilang mga magulang?",
    "Wer ist besser organisiert?" to "Sino ang mas organisado?",
    "Wer ist der Beste bei der Filmauswahl?" to "Sino ang pinakamagaling sa pagpili ng mga pelikula?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Sino ang pinakamahusay sa pagpaplano ng mga romantikong petsa?",
    "Wer ist der beste Tänzer?" to "Sino ang pinakamahusay na mananayaw?",
    "Wer ist romantischer?" to "Sino ang mas romantic?",
    "Wer kocht besser?" to "Sino ang mas magaling magluto?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Sino ang nag-aalaga ng renovation at maintenance?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Sino ang mas mabilis na nakakapansin kapag ang kausap ay hindi maganda ang pakiramdam?",
    "Wer sucht am Ende wirklich den Film aus?" to "Sino ba talaga ang pipili ng pelikula sa huli?",
    "Wer vergisst eher einen Jahrestag?" to "Sino ang mas malamang na makakalimutan ang isang anibersaryo?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Sino ang mas malamang na makakalimutan ang kanilang sariling pangalan sa susunod na umaga?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Sino ang mas malamang na makahanap ng video sa susunod na araw na hindi nila alam?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Sino ang mas gugustuhing magpalipas ng gabi sa sofa ng isang estranghero?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Sino ang mas malamang na makatulog sa isang party at magising na may mukha si Sharpie?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Sino ang mas malamang na madulas sa dance floor ngunit gagawin itong parang isang cool na galaw?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Sino ang mas malamang na kumokontrol sa playlist ng Spotify sa isang house party?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Sino ang mas malamang na mag-order ng pizza para sa lahat sa isang party at sila mismo ang kakain nito?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Sino ang mas malamang na makatulog muna sa isang party?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Sino ang mas malamang na biglang magsimulang maglinis sa isang party?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Sino ang mas malamang na mag-aangkin na ganap na matino kung ang kabaligtaran ay totoo?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Sino ang mas malamang na unang sumuko sa isang argumento?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Sino ang mas malamang na mandaya sa isang laro ng inuman?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Sino ang mas malamang na sumalakay sa buffet at palihim na mag-uuwi ng pagkain?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Sino ang mas malamang na mag-post ng pinakanakakahiya na larawan ng gabi sa kanilang kuwento?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Sino ang mas maiinis sa DJ para mag-request ng sarili nilang paboritong kanta?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Sino ang mas malamang na kantahin ang lyrics ng isang kanta na off key, ngunit may paninindigan?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Sino ang mas malamang na mag-order ng pinakamahal na inumin sa menu at pagsisihan ito?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Sino ang mas malamang na mag-imbita sa mga kapitbahay kung magrereklamo sila tungkol sa ingay?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Sino ang masyadong sineseryoso ang mga party games (tulad ng Beer Pong)?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Sino ang mas malamang na kaibiganin ang mga bouncer para makakuha ng VIP access?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Sino ang mas malamang na magsimula ng kusang labanan sa karaoke?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Sino ang mas malamang na magbukas ng bote nang hindi gumagamit ng pambukas ng bote?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Sino ang mas malamang na magbigay ng talumpati kahit na talagang walang nagtanong?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Sino ang mas malamang na gumugol ng isang oras sa banyo para mag-selfie?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Sino ang mas malamang na magsagawa ng isang nakakahiyang pagtatanghal ng sayaw at ipagdiwang ito?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Sino ang mas malamang na tatawag sa isang dating kasosyo pagkatapos ng party?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Sino ang mas malamang na hindi sinasadyang masaktan ang isang kakaibang bisita?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Sino ang mas malamang na palihim na umalis sa party nang walang paalam?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Sino ang mas pipiliing makipaglaro sa alaga ng host kaysa makipag-usap sa mga bisita?",
    "Wer würde eher spontan eine Reise buchen?" to "Sino ang mas malamang na mag-book ng biyahe nang kusa?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Sino ang mas malamang na magkaroon ng malalim na pag-uusap sa kusina nang maraming oras?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Sino ang mas malamang na hindi sinasadyang uminom ng inumin ng iba?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Sino ang mas malamang na aksidenteng matumba ang isang mamahaling plorera o isang bagay na marupok?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Sino ang mas malamang na subukang maghalo ng isang kumplikadong cocktail sa kanilang sarili at mabibigo nang husto?",
    "Wer würde eher zu spät kommen?" to "Sino ang mas malamang na ma-late?",
    "Wer würde eher?" to "Sino ang mas pipiliin?",
    "Wer übernimmt die tägliche Versorgung?" to "Sino ang nangangalaga sa pang-araw-araw na pangangalaga?",
    "Werde so akzeptiert, wie du bist" to "Tanggapin bilang ikaw",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Magkakaroon ba tayo ng sapat na oras para sa bata/mga bata? ⏳",
    "Whirlpool" to "Hot tub",
    "White Chocolate" to "Puting Tsokolate",
    "Widgets" to "Mga Widget",
    "Wie fühlst du dich am meisten geliebt?" to "Ano ang nararamdaman mong pinakamamahal?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Paano natin haharapin ang iba't ibang kita?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Ano ang pinakamahusay na paraan para simulan ng iyong partner ang pakikipagtalik sa iyo?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Paano magiging mas mabuting kapareha para sa iyo ang iyong kapareha?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Gaano katagal pagkatapos ng proposal gusto mong magdiwang kasama ang iba?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Hanggang kailan natin gustong manatili doon kahit papaano?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Gaano kadali para sa iyo na magsalita tungkol sa mga hiling?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Ano ang gusto mong hitsura ng ating kinabukasan?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Ano ang hitsura ng iyong perpektong Linggo sa bahay?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Ano ang pakiramdam mo tungkol sa maruming usapan habang nakikipagtalik?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Gaano karaming kredito ang makatotohanan natin?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Ilang oras ang gusto nating maghiwalay?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Magkano ang gusto nating gastusin sa kabuuan?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Paano tayo makakahanap ng oras para sa ating relasyon kapag dumating na ang baby?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Gaano kahalaga sa iyo na makunan ang sandali?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Gaano kahalaga sa iyo na ang application ay nagpapakita ng iyong mga libangan o interes?",
    "Wie würdest du sie/ihn nennen?" to "Ano ang itatawag mo sa kanya?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Ano ang paborito mong paraan para magpakita ng pagmamahal sa labas ng sex?",
    "Wildblumen" to "Mga Wildflower",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Gusto mo ba ng babae o lalaki? 👶",
    "Wintergarten" to "Hardin sa taglamig",
    "Winterhochzeit" to "Kasal sa taglamig",
    "Wir bestellen einfach beides" to "Order lang kami pareho",
    "Wir brauchen ewig" to "Aabutin tayo magpakailanman",
    "Wir einigen uns nie" to "Hindi kami magkasundo",
    "Wir entscheiden es gemeinsam" to "Magkasama kaming nagdedesisyon",
    "Wir treffen uns in der Mitte" to "Nagkita kami sa gitna",
    "Wir wechseln uns ab" to "Salitan kami",
    "Wird stressig" to "Nakaka-stress",
    "Wobei lachst du am meisten?" to "Ano ang pinakanakakatawa sa iyo?",
    "Wofür sparen wir gemeinsam?" to "Para saan tayo nag-iipon?",
    "Wohnzimmer" to "Sala",
    "Woran erinnerst du dich am lebhaftesten?" to "Ano ang pinakamatingkad mong naaalala?",
    "Worauf freust du dich bei uns am meisten?" to "Ano ang pinakahihintay mo sa amin?",
    "Worte/Komplimente" to "Mga Salita/Papuri",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Ano ang pinakakinatatakutan mo sa relasyon natin?",
    "Wünsche? z.B. günstig, draußen" to "Nais? hal. mura, sa labas",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Mas gusto mo bang mag-propose sa bakasyon (kasangkot sa paglalakbay)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube Music",
    "Zeichne für mich" to "Gumuhit para sa akin",
    "Zeichne mich als Tier — welches wäre ich?" to "Iguhit mo ako bilang isang hayop - alin ako?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Iguhit ang ating damdamin sa isa't isa bilang simbolo.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Iguhit ang pangarap nating bahay sa isang linya. Ano ang pinaka-kapansin-pansin na bagay?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Iguhit ang ating unang petsa - ano ang talagang kailangang nasa larawan?",
    "Zeichnen" to "Gumuhit",
    "Zeit füreinander" to "Oras para sa isa't isa",
    "Zeit, wenn das Baby schläft" to "Oras kung kailan natutulog ang sanggol",
    "Zelten gehen" to "Magkamping",
    "Zitrone" to "Lemon",
    "Zu Hause, gemütlich und privat" to "Sa bahay, maaliwalas at pribado",
    "Zu einem Picknick gehen" to "Pupunta sa isang picnic",
    "Zu einem ausgefallenen Abendessen gehen" to "Pupunta sa isang magarbong hapunan",
    "Zu zweit reisen" to "Maglakbay bilang mag-asawa",
    "Zuhause & Alltag" to "Tahanan at pang-araw-araw na buhay",
    "Zuhören" to "Makinig",
    "Zurück" to "Bumalik",
    "Zusammen seit" to "Magkasama mula noon",
    "Zusammen seit (TT.MM.JJJJ)" to "Magkasama mula noong (DD.MM.YYYY)",
    "Zusammenziehen" to "Kontrata",
    "Zustimmen oder Ablehnen" to "Sang-ayon o Hindi Sumasang-ayon",
    "Zwei Kreise, die sich überschneiden" to "Dalawang bilog na nagsasapawan",
    "Zwei Stühle davor" to "Dalawang upuan sa harap nito",
    "Zärtlich sein" to "Maging malambing ka",
    "Öfter als ich zugebe" to "Mas maraming beses kaysa inaamin ko",
    "Über 100€/Monat" to "Higit sa 100€/buwan",
    "Über 2000 im Monat" to "Mahigit 2000 sa isang buwan",
    "Über mich selbst" to "Tungkol sa sarili ko",
    "Übernehmen" to "Mag-apply",
    "Überraschend" to "Nakakagulat",
    "Überraschung" to "Sorpresa",
    "Überspringen" to "Laktawan",
    "Übertrieben und großartig" to "Over the top and awesome",
    "✎ Tippe, um zu antworten" to "✎ I-tap para tumugon",
    "✨ GFK-Brücke" to "✨ GRP tulay",
)

internal fun localizeFilipinoDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_FILIPINO_CONTENT)
