package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_GUJARATI_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 વર્ષ",
    "1000 - 1500 im Monat" to "1000 - 1500 દર મહિને",
    "1000 bis 3000" to "1000 થી 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 દર મહિને",
    "3000 bis 5000" to "3000 થી 5000",
    "5-10 Jahre" to "5-10 વર્ષ",
    "50-100€/Monat" to "50-100€/મહિને",
    "Ab 100€" to "100€ થી",
    "Ab 500€" to "500€ થી",
    "Ab 50€" to "50€ થી",
    "Ab und zu" to "હવે પછી",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "ખરીદી કરતા પહેલા આપણે કેટલી વાત કરી રહ્યા છીએ?",
    "Abbrechen" to "રદ કરો",
    "Abenteuer" to "સાહસ",
    "Adidas" to "એડિડાસ",
    "Aktivitäten" to "પ્રવૃત્તિઓ",
    "Alle" to "બધા",
    "Alle Pakete" to "બધા પેકેજો",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "તમારા શ્રેષ્ઠ મિત્ર સિવાય તમારા બધા મિત્રોને ગુમાવો",
    "Alle intimen Momente selbst initiieren" to "બધી ઘનિષ્ઠ ક્ષણો જાતે શરૂ કરો",
    "Alles davon" to "તે બધા",
    "Alles, was noch kommt" to "જે આવવાનું છે તે બધું",
    "Alltagsroutine" to "રોજિંદી દિનચર્યા",
    "Alltägliche Berührungen" to "રોજેરોજ સ્પર્શે છે",
    "Altbau mit Charme" to "વશીકરણ સાથે જૂની ઇમારત",
    "Am Strand" to "બીચ પર",
    "Am liebsten alles zusammen" to "પ્રાધાન્ય બધું એકસાથે",
    "Am selben Tag mit Freunden/Familie" to "તે જ દિવસે મિત્રો/પરિવાર સાથે",
    "Amazon" to "એમેઝોન",
    "Amsterdam" to "એમ્સ્ટર્ડમ",
    "Amsterdam, Niederlande" to "એમ્સ્ટરડેમ, નેધરલેન્ડ",
    "An das Gefühl" to "લાગણીની",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "ઘણા દર્શકો સાથે જાહેર સ્થળે",
    "An einen Geruch" to "ગંધની",
    "An einen Song" to "ગીત માટે",
    "An etwas, das ich gesagt habe" to "મેં કંઈક કહ્યું",
    "Analyse starten" to "વિશ્લેષણ શરૂ કરો",
    "Analysiere eure Muster..." to "તમારી પેટર્નનું વિશ્લેષણ કરો...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Gottman અને GFK અનુસાર તમારા જવાબો અને ચેટ્સનું વિશ્લેષણ કરો.",
    "Ananas auf der Pizza schmeckt köstlich." to "પિઝા પર પાઈનેપલ સ્વાદિષ્ટ લાગે છે.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "ફોટો સાથે જવાબ આપો",
    "Antwortähnlichkeit" to "જવાબની સમાનતા",
    "App-Sprache auswählen" to "એપ્લિકેશન ભાષા પસંદ કરો",
    "Auf eine Bootsparty gehen" to "બોટ પાર્ટીમાં જવું",
    "Aufmerksamkeit" to "ધ્યાન",
    "Aufräumen und Projekte angehen" to "પ્રોજેક્ટ સાફ કરો અને તેનો સામનો કરો",
    "Aufwärmen" to "ગરમ કરો",
    "Aufwärmen: Einander kennenlernen" to "વોર્મ-અપ: એકબીજાને જાણવું",
    "Aus dem Urlaub" to "વેકેશનમાંથી",
    "Ausgefallener Name" to "ફેન્સી નામ",
    "Ausschlafen und faulenzen" to "સૂઈ જાઓ અને આસપાસ આળસ કરો",
    "Ausschlafen und nichts tun" to "સૂઈ જાઓ અને કંઈ કરશો નહીં",
    "Aussehen" to "જુઓ",
    "Auto" to "કાર",
    "Außenkamin" to "આઉટડોર ફાયરપ્લેસ",
    "BEANTWORTE" to "જવાબ",
    "Bali" to "બાલી",
    "Bali, Indonesien" to "બાલી, ઇન્ડોનેશિયા",
    "Banane" to "કેળા",
    "Beantwortet" to "જવાબ આપ્યો",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "એક જ સમયે પ્રશ્નોના જવાબ આપો — જ્યાં સુધી તમે બંને સમાપ્ત ન કરો ત્યાં સુધી જવાબો દેખાશે નહીં.",
    "Beantwortete Fragen" to "પ્રશ્નોના જવાબ આપ્યા",
    "Bearbeiten" to "સંપાદિત કરો",
    "Bei Insider-Witzen" to "અંદરના જોક્સ માટે",
    "Bei Memes" to "મીમ્સ પર",
    "Bei einer spontanen Berührung" to "જ્યારે સ્વયંભૂ સ્પર્શ કરવામાં આવે છે",
    "Beide" to "બંને",
    "Beide gleich" to "બંને સરખા",
    "Beide zusammen" to "બંને એકસાથે",
    "Beide, aber wir tun so als ob nicht" to "બંને, પરંતુ અમે ડોળ કરતા નથી",
    "Beides" to "બંને",
    "Beides wäre schlimm" to "બંને ખરાબ હશે",
    "Beim Einschlafen nebeneinander" to "એકબીજાની બાજુમાં સૂઈ જવું",
    "Beim Reden" to "વાત કરતી વખતે",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "પ્રખ્યાત પર્યટન સ્થળો હંમેશા નિરાશાજનક હોય છે.",
    "Beschreibe unser Sexleben mit einem Emoji." to "ઇમોજી વડે અમારી સેક્સ લાઇફનું વર્ણન કરો.",
    "Besser kommunizieren" to "વધુ સારી રીતે વાતચીત કરો",
    "Bessere Lage" to "બહેતર સ્થાન",
    "Bestellen" to "ઓર્ડર",
    "Besuchte Länder" to "મુલાકાત લીધેલ દેશો",
    "Besuchte Städte" to "શહેરોની મુલાકાત લીધી",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "શું તમે ઉડાઉ દરખાસ્ત પસંદ કરો છો કે કંઈક સૂક્ષ્મ?",
    "Beziehung" to "સંબંધ",
    "Bibliothek" to "પુસ્તકાલય",
    "Bin manchmal unsicher" to "હું ક્યારેક અસુરક્ષિત હોઉં છું",
    "Bist du ein Videospiel-Guru?" to "શું તમે વીડિયો ગેમના ગુરુ છો?",
    "Blumenwiese" to "ફૂલ ઘાસનું મેદાન",
    "Bunte Blumenwiese" to "રંગબેરંગી ફૂલોનું મેદાન",
    "Burger" to "બર્ગર",
    "Burger King" to "બર્ગર કિંગ",
    "Chat" to "ચેટ",
    "Coca-Cola" to "કોકા કોલા",
    "Cookie Dough" to "કૂકી કણક",
    "Dachgarten mit Lounge" to "લાઉન્જ સાથેનો છતનો બગીચો",
    "Dachterrasse" to "છતની ટેરેસ",
    "Das Wetter an dem Tag" to "તે દિવસે હવામાન",
    "Das erste Selfie" to "પ્રથમ સેલ્ફી",
    "Das meiste weiß ich" to "હું તેમાંથી મોટાભાગની જાણું છું",
    "Das oder das?" to "આ કે તે?",
    "Das tägliche Leben" to "દૈનિક જીવન",
    "Dass Zusagen gehalten werden" to "એ વચનો પાળવામાં આવે છે",
    "Dass alles meinen Stil hat" to "કે દરેક વસ્તુ મારી શૈલી ધરાવે છે",
    "Dass ich alles erzählen kann" to "કે હું બધું કહી શકું",
    "Dass ich mich nicht sorgen muss" to "કે મારે ચિંતા કરવાની જરૂર નથી",
    "Dass wir ungestört sind" to "કે આપણે અવિચલિત છીએ",
    "Dein Name" to "તમારું નામ",
    "Deine Antwort..." to "તમારો જવાબ...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "તમારા જવાબો સાચવવામાં આવ્યા છે. પાર્ટનર પૅકેજ પૂરું કરતાંની સાથે જ બંને જવાબો એકસાથે દેખાશે.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "તમારા જવાબો સાચવવામાં આવ્યા છે. એકવાર \${profile.partnerName} પેકેજ પૂર્ણ કરે, બંને પ્રતિભાવો એકસાથે દેખાશે.",
    "Deine Beziehung abenteuerlich und spontan machen" to "તમારા સંબંધોને સાહસિક અને સ્વયંસ્ફુરિત બનાવો",
    "Deine Beziehung stabil und sicher machen" to "તમારા સંબંધોને સ્થિર અને સુરક્ષિત બનાવો",
    "Deine eigene Antwort" to "તમારો પોતાનો જવાબ",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "તમારા જીવનસાથી સાથે તમારા ઊંડા રહસ્યો શેર કરવા વધુ સારું છે",
    "Deinen besten Freund verlieren" to "તમારો શ્રેષ્ઠ મિત્ર ગુમાવવો",
    "Denke an dich" to "તમારા વિશે વિચારો",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "એક જ ફિલ્મ બે વાર જોવી એ સમયનો બગાડ છે.",
    "Der Blick nach draußen" to "બહારનું દૃશ્ય",
    "Der Garten" to "બગીચો",
    "Der Ort" to "સ્થળ",
    "Der Ring und die Geste" to "રિંગ અને હાવભાવ",
    "Der perfekte Heiratsantrag" to "સંપૂર્ણ લગ્ન પ્રસ્તાવ",
    "Derjenige sein, der umarmt wird" to "જેને ગળે લગાડવામાં આવે છે તે બનો",
    "Deutsch" to "જર્મન",
    "Diamant" to "હીરા",
    "Diamanten im Band" to "બેન્ડમાં હીરા",
    "Die Distanz" to "અંતર",
    "Die Feiertage mit der Familie deines Partners verbringen" to "તમારા જીવનસાથીના પરિવાર સાથે રજાઓ વિતાવો",
    "Die Gemütlichkeit und Ruhe" to "આરામ અને શાંતિ",
    "Die Menschen, die darin wohnen" to "જે લોકો ત્યાં રહે છે",
    "Die Umgebung und Atmosphäre" to "પર્યાવરણ અને વાતાવરણ",
    "Die Worte und Emotionen" to "શબ્દો અને લાગણીઓ",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "અંતિમ મનોરંજન ક્વિઝ પડકાર",
    "Diejenige sein, die umarmt" to "આલિંગન આપનાર બનો",
    "Direkt ansprechen" to "સીધું સરનામું",
    "Diskussion" to "ચર્ચા",
    "Diskutiere vor dem Kinderkriegen" to "બાળકો પેદા કરતા પહેલા ચર્ચા કરો",
    "Diskutiert eure Antworten" to "તમારા જવાબોની ચર્ચા કરો",
    "Disney" to "ડિઝની",
    "Doch, schon mal" to "હા, પહેલેથી જ",
    "Draußen mit der Natur als Kulisse" to "પૃષ્ઠભૂમિ તરીકે પ્રકૃતિ સાથે બહાર",
    "Drei-Stein-Ring" to "ત્રણ પથ્થરની વીંટી",
    "Du bist dran" to "તમારો વારો છે",
    "Du fehlst mir" to "હું તમને યાદ કરું છું",
    "Dubai" to "દુબઈ",
    "Dubai, VAE" to "દુબઈ, યુએઈ",
    "Dunkles Design" to "ડાર્ક ડિઝાઇન",
    "Durch Berührung" to "સ્પર્શ દ્વારા",
    "Durch Worte" to "શબ્દો દ્વારા",
    "Durch Zeit zu zweit" to "સમય સાથે મળીને",
    "Durch kleine Gesten" to "નાના હાવભાવ દ્વારા",
    "Durchgeplant" to "આયોજિત",
    "ERGEBNISSE" to "પરિણામો",
    "Egal, Hauptsache gesund" to "કોઈ બાબત નથી, મુખ્ય વસ્તુ સ્વસ્થ છે",
    "Ehepaar Leben" to "દાંપત્યજીવન",
    "Eher knapp" to "તેના બદલે બંધ",
    "Eher nicht" to "બલ્કે નહિ",
    "Eher schwer" to "તેના બદલે મુશ્કેલ",
    "Eher schwierig" to "તેના બદલે મુશ્કેલ",
    "Eher zu" to "તેના બદલે પણ",
    "Eifersucht ist ein Zeichen von Liebe." to "ઈર્ષ્યા એ પ્રેમની નિશાની છે.",
    "Eigenes Gemüsebeet" to "પોતાની વનસ્પતિ પેચ",
    "Ein Abenteuer in einer neuen Stadt" to "નવા શહેરમાં એક સાહસ",
    "Ein Anker" to "એક એન્કર",
    "Ein Balkon oder Garten" to "બાલ્કની અથવા બગીચો",
    "Ein Filmabend" to "મૂવી નાઇટ",
    "Ein Harmony-Meilenstein eurer Liebe." to "તમારા પ્રેમનો સંવાદિતા સીમાચિહ્નરૂપ.",
    "Ein Herz" to "હૃદય",
    "Ein Herz an der Tür" to "દરવાજા પર હૃદય",
    "Ein Jahr lang eine Fernbeziehung führen" to "એક વર્ષ સુધી લાંબા અંતરનો સંબંધ રાખો",
    "Ein Kindheitsessen" to "બાળપણનું ભોજન",
    "Ein Live-Musik-Konzert besuchen" to "લાઇવ મ્યુઝિક કોન્સર્ટમાં હાજરી આપો",
    "Ein Museum besuchen" to "મ્યુઝિયમની મુલાકાત લો",
    "Ein Spieleabend" to "રમતની રાત",
    "Ein Spieleabend mit Freunden" to "મિત્રો સાથે રમતની રાત્રિ",
    "Ein Urlaubsfoto" to "વેકેશનનો ફોટો",
    "Ein aktives Abenteuer" to "એક સક્રિય સાહસ",
    "Ein entspannender Spa-Tag" to "આરામદાયક સ્પા દિવસ",
    "Ein ganz normaler Alltagstag" to "સંપૂર્ણપણે સામાન્ય રોજિંદા દિવસ",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "વાવાઝોડા દરમિયાન ઘરમાં આરામદાયક સાંજ",
    "Ein gemütliches Date drinnen" to "ઘરની અંદર આરામદાયક તારીખ",
    "Ein lustiges Bild" to "એક રમુજી ચિત્ર",
    "Ein paar Handyfotos reichen" to "સેલ ફોનના થોડા ફોટા પૂરતા છે",
    "Ein paar Stunden" to "થોડા કલાકો",
    "Ein paar kulturelle Anklänge sind okay" to "થોડા સાંસ્કૃતિક સંદર્ભો ઠીક છે",
    "Ein romantischer Abend" to "એક રોમેન્ટિક સાંજ",
    "Ein romantisches Abendessen bei Kerzenlicht" to "રોમેન્ટિક કેન્ડલલાઇટ ડિનર",
    "Ein romantisches Bild" to "એક રોમેન્ટિક છબી",
    "Ein romantisches Picknick an einem schönen Ort" to "સુંદર સ્થાન પર રોમેન્ટિક પિકનિક",
    "Ein schwerer Moment, den wir geschafft haben" to "એક મુશ્કેલ ક્ષણ જે અમે મેનેજ કરી",
    "Ein tolles Date im Freien unter dem Mondlicht" to "મૂનલાઇટ હેઠળ બહાર એક મહાન તારીખ",
    "Ein ungewöhnliches Gericht" to "એક અસામાન્ય વાનગી",
    "Ein zufälliger Schnappschuss" to "એક રેન્ડમ સ્નેપશોટ",
    "Einander kennenlernen" to "એકબીજાને જાણવું",
    "Eine Autoreise" to "રોડ ટ્રીપ",
    "Eine Brücke" to "એક પુલ",
    "Eine Date-Nacht unter den Sternen" to "તારાઓની નીચે તારીખની રાત",
    "Eine Million Dollar gewinnen" to "એક મિલિયન ડોલર જીતો",
    "Eine Million Dollar verdienen" to "એક મિલિયન ડોલર કમાઓ",
    "Eine Nacht in einem Club" to "ક્લબમાં એક રાત",
    "Eine Schokoladenverkostung" to "ચોકલેટનો સ્વાદ ચાખવો",
    "Eine Wanderung mit Panoramablick machen" to "મનોહર દૃશ્યો સાથે હાઇક લો",
    "Eine Weinverkostung" to "વાઇન ટેસ્ટિંગ",
    "Eine gemeinsame Reise" to "એક સાથે પ્રવાસ",
    "Eine gemütliche Nacht zu Hause" to "ઘરમાં આરામદાયક રાત",
    "Eine neue Sprache zu lernen ist einfach." to "નવી ભાષા શીખવી સરળ છે.",
    "Einen Film anschauen" to "મૂવી જુઓ",
    "Einen Monat lang überhaupt nicht miteinander reden" to "એક મહિના સુધી એકબીજા સાથે બિલકુલ વાત કરતા નથી",
    "Einen Tanzkurs besuchen" to "ડાન્સ ક્લાસ લો",
    "Einen Vergnügungspark erkunden" to "મનોરંજન પાર્કનું અન્વેષણ કરો",
    "Einen Wellness-Tag" to "એક સુખાકારી દિવસ",
    "Einen sehr emotionalen Partner haben" to "ખૂબ જ લાગણીશીલ જીવનસાથી હોય",
    "Einen sehr logischen Partner haben" to "ખૂબ જ તાર્કિક ભાગીદાર હોય",
    "Einer zahlt alles" to "એક વ્યક્તિ બધું ચૂકવે છે",
    "Einfach mehr Alltag" to "ફક્ત વધુ રોજિંદા જીવન",
    "Einfach nebeneinander sein" to "બસ એકબીજાની બાજુમાં રહો",
    "Einfach und intim" to "સરળ અને ઘનિષ્ઠ",
    "Einige Dinge für dich behalten" to "કેટલીક વસ્તુઓ તમારી પાસે રાખો",
    "Einmal" to "એકવાર",
    "Eins, das nur wir kennen" to "એક જે ફક્ત આપણે જાણીએ છીએ",
    "Englisch" to "અંગ્રેજી",
    "Entspannte Hängematte" to "હળવા ઝૂલા",
    "Entspannung" to "આરામ",
    "Erdbeere" to "સ્ટ્રોબેરી",
    "Erfolgreich" to "સફળ",
    "Ergebnisse" to "પરિણામો",
    "Erst bei sehr großen Summen" to "માત્ર ખૂબ મોટી રકમ માટે",
    "Erst nur enge Freunde/Familie" to "પહેલા ફક્ત નજીકના મિત્રો/કુટુંબ",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "જ્યારે મારો સાથી સંદેશાનો જવાબ આપવામાં ઘણો સમય લે છે ત્યારે તે મને હેરાન કરે છે.",
    "Essen & Genuss" to "ખોરાક અને આનંદ",
    "Essensvorlieben" to "ખોરાકની પસંદગીઓ",
    "Etwa eine Woche später, erst mal nur wir" to "લગભગ એક અઠવાડિયા પછી, પહેલા તો અમે",
    "Etwas Neues ausprobieren" to "કંઈક નવું અજમાવો",
    "Etwas ganz anderes" to "કંઈક સંપૂર્ણપણે અલગ",
    "Etwas sehr Scharfes" to "કંઈક ખૂબ જ તીક્ષ્ણ",
    "Etwas, das ich selbst gern erfinde" to "કંઈક મને મારી જાતે શોધવું ગમે છે",
    "Etwas, eine kleine Note wäre schön" to "કંઈક, થોડી નોંધ સરસ રહેશે",
    "Familie" to "કુટુંબ",
    "Familie/Freunde" to "કુટુંબ/મિત્રો",
    "Familienmensch" to "કુટુંબનો માણસ",
    "Farbedelstein" to "રંગીન રત્ન",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "ટીવી કમર્શિયલ જોવા માટે ક્યારેક રસપ્રદ હોય છે.",
    "Fertig" to "થઈ ગયું",
    "Fertig!" to "થઈ ગયું!",
    "Feste Date-Nights" to "નિશ્ચિત તારીખની રાત",
    "Feuerstelle" to "આગનો ખાડો",
    "Filigran & schlicht" to "ફીલીગ્રી અને સરળ",
    "Filme/Serien" to "ફિલ્મો/શ્રેણી",
    "Formuliere um..." to "રીફ્રેઝ...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "તમારા ડ્રાફ્ટને અહિંસક રીતે ફરીથી લખો: અવલોકન, લાગણી, જરૂરિયાત, વિનંતી.",
    "Frage hinzufügen" to "પ્રશ્ન ઉમેરો",
    "Fragen & Spiele" to "પ્રશ્નો અને રમતો",
    "Fragen für jede Gelegenheit" to "દરેક પ્રસંગ માટે પ્રશ્નો",
    "Freizeitpark" to "એમ્યુઝમેન્ટ પાર્ક",
    "Freunde treffen" to "મિત્રોને મળો",
    "Freundschaften mit Ex-Partnern sind okay." to "exes સાથે મિત્રતા ઠીક છે.",
    "Früh aufstehen" to "વહેલા ઉઠો",
    "Fußbodenheizung" to "અન્ડરફ્લોર હીટિંગ",
    "Führen wir getrennte oder gemeinsame Konten?" to "શું અમારી પાસે અલગ કે સંયુક્ત એકાઉન્ટ છે?",
    "Für dich empfohlen" to "તમારા માટે ભલામણ કરેલ",
    "Für die Zukunft" to "ભવિષ્ય માટે",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "આ શોધ માટે કોઈ મેળ ખાતા પ્રશ્નો અથવા રમતો મળી નથી.",
    "Für immer" to "કાયમ",
    "Fürsorglichkeit" to "કાળજી",
    "GFK-Brücke" to "જીઆરપી બ્રિજ",
    "Galerie" to "ગેલેરી",
    "Gar nicht, der Moment gehört uns" to "બિલકુલ નહીં, ક્ષણ આપણી છે",
    "Gar nichts tun" to "બિલકુલ ન કરો",
    "Geduld" to "ધીરજ",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "સૂર્યોદય જોવા માટે વહેલી સવારે જાઓ",
    "Geht so" to "તે બરાબર ચાલી રહ્યું છે",
    "Geister existieren wirklich." to "ભૂત ખરેખર અસ્તિત્વ ધરાવે છે.",
    "Gelassenheit" to "શાંતિ",
    "Gelbgold" to "પીળું સોનું",
    "Geld & Finanzen" to "નાણાં અને નાણાં",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "એકસાથે વિશ્વની મુસાફરી કરો, નવી સંસ્કૃતિઓ અને વાનગીઓનું અન્વેષણ કરો",
    "Gemeinsam ein Lego bauen" to "સાથે મળીને લેગો બનાવો",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "રસોડામાં સાથે મળીને એક નવી રેસીપી અજમાવી જુઓ",
    "Gemeinsame Konten" to "સંયુક્ત એકાઉન્ટ્સ",
    "Gemeinsame Nächte" to "સાથે રાત",
    "Gemeinsame Tage" to "વહેંચાયેલા દિવસો",
    "Gemischt" to "મિશ્ર",
    "Gemüsebeet" to "વનસ્પતિ પેચ",
    "Gemütliche Feuerstelle" to "હૂંફાળું આગ ખાડો",
    "Gesprächsanreger" to "વાતચીતની શરૂઆત",
    "Getrennte Konten" to "અલગ એકાઉન્ટ્સ",
    "Getrennte Urlaube tun einer Beziehung gut." to "સંબંધ માટે અલગ રજાઓ સારી છે.",
    "Gewächshaus" to "ગ્રીનહાઉસ",
    "Glasfassade" to "કાચ રવેશ",
    "Gleichgültigkeit" to "ઉદાસીનતા",
    "Glücklich und frei" to "ખુશ અને મફત",
    "Gourmet Eis-Sorten" to "દારૂનું આઈસ્ક્રીમની જાતો",
    "Gravur innen" to "અંદર કોતરણી",
    "Grillplatz" to "બરબેકયુ વિસ્તાર",
    "Groß & üppig" to "મોટા અને રસદાર",
    "Große Familie" to "મોટો પરિવાર",
    "Große Feier" to "મોટી ઉજવણી",
    "Große Fenster" to "મોટી બારીઓ",
    "Große Fensterfront" to "મોટી બારી આગળ",
    "Großer Außenpool" to "વિશાળ આઉટડોર પૂલ",
    "Großer Garten" to "મોટો બગીચો",
    "Großer Stein" to "મોટો પથ્થર",
    "Größere Küche" to "મોટું રસોડું",
    "Gutes Essen" to "સારો ખોરાક",
    "Habe ich" to "મેં કર્યું",
    "Habe ich noch nie" to "મારી પાસે ક્યારેય નથી",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "શું તમે કોઈ આશ્ચર્યજનક તફાવતો શોધી કાઢ્યા છે? તમને ચોક્કસ વિકલ્પો કેમ વધુ ગમે છે તે વિશે વાત કરો!",
    "Haus am See" to "તળાવ પાસે ઘર",
    "Haus/Wohnung" to "ઘર/એપાર્ટમેન્ટ",
    "Hazelnut" to "હેઝલનટ",
    "Heimkino" to "હોમ થિયેટર",
    "Herzhaft" to "હાર્દિક",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "અત્યારે અહીં કંઈ નથી.\nફિલ્ટર બદલો અથવા કોઈ અલગ વિષય પસંદ કરો.",
    "Hilfe im Alltag" to "રોજિંદા જીવનમાં મદદ કરો",
    "Himbeere" to "રાસ્પબેરી",
    "Hinzufügen" to "ઉમેરો",
    "Hobbys" to "શોખ",
    "Hochzeitssträuße" to "લગ્ન bouquets",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "હોગવર્ટ્સ હાઉસ પ્રાઇડ: તમે ક્યાંથી છો?",
    "Home" to "ઘર",
    "Hot Tub" to "ગરમ ટબ",
    "Humor" to "રમૂજ",
    "Hund" to "કૂતરો",
    "Hängematte" to "ઝૂલો",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "શું તમે અરજીના ભાગરૂપે લેખિત પત્ર ઈચ્છો છો?",
    "IKEA" to "IKEA",
    "Ich" to "આઈ",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "હું સિનેમા જોવા જવા કરતાં પાર્કમાં રોમેન્ટિક વોક પસંદ કરું છું.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "હું ક્યારેય સિનેમામાં સૂઈ ગયો નથી.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "મને મારા જીવનસાથી સાથે નવા શોખ અથવા પ્રવૃત્તિઓ શોધવામાં આનંદ આવે છે.",
    "Ich finde eine Alternative" to "હું એક વિકલ્પ શોધીશ",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "મને હંમેશા એક જ જગ્યાએ જવાને બદલે મારા પાર્ટનર સાથે નવી રેસ્ટોરન્ટ અજમાવવાનો આનંદ આવે છે.",
    "Ich habe noch nie" to "મેં ક્યારેય કર્યું નથી",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "હું ક્યારેય રોલર કોસ્ટરથી ડરતો નથી અને કોઈપણ રીતે હું તેના પર પહોંચી ગયો.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "મેં ક્યારેય ફાસ્ટ પાસની ટિકિટ ખરીદી નથી કારણ કે હું અધીરો હતો.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "મેં ઘરે રહેવાની અને ટીવી શો જોવાની યોજના ક્યારેય રદ કરી નથી.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "મેં ક્યારેય હોગવર્ટ્સના મારા પત્રની રાહ જોઈ નથી.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "મેં ક્યારેય કહ્યું નથી કે સ્લિથરિન ખરેખર એટલી ખરાબ ન હતી.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "મેં ક્યારેય કહ્યું નથી કે હું ડિઝની મૂવીઝ માટે ખૂબ વૃદ્ધ હતો (અને ગુપ્ત રીતે તેનો આનંદ માણતો હતો).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "મેં ક્યારેય ઈરાદાપૂર્વક મારિયો કાર્ટમાં વાદળી ટાંકીવાળા કોઈને ગોળી મારી નથી.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "હું ક્યારેય ડિઝની મૂવીમાં રડ્યો નથી.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "હોરર મૂવી જોતી વખતે મેં ક્યારેય મારી આંખો ઢાંકી નથી.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "હું રમતને સાચવવાનું અને પ્રગતિના કલાકો ગુમાવવાનું ક્યારેય ભૂલ્યો નથી.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "શરમજનક દ્રશ્ય (ક્રિંજ ફેક્ટર) દરમિયાન મેં ક્યારેય રૂમ છોડ્યો નથી.",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "રોલરકોસ્ટર ફોટો લેતી વખતે મેં ક્યારેય રમુજી પોઝ આપ્યો નથી.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "મેં ક્યારેય મોડી રાત સુધી રમત રમી નથી અને બીજા દિવસે હું કેટલો થાકી ગયો તેનો અફસોસ હતો.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "મેં ક્યારેય મૂવીનો અંત ગૂગલ કર્યો નથી કારણ કે હું રાહ જોઈ શકતો નથી.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "મને ક્યારેય એવું લાગ્યું નથી કે હું ફિલ્મના સેટ પર ઊભો છું.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "મેં મારી મનપસંદ શ્રેણીનો પ્રસ્તાવના ક્યારેય છોડ્યો નથી.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "મેં ક્યારેય બીજા કોઈનો Netflix પાસવર્ડ શેર કર્યો નથી.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "કામ કરતી વખતે અથવા અભ્યાસ કરતી વખતે મેં ક્યારેય ગેમનો સાઉન્ડટ્રેક સાંભળ્યો નથી.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "જ્યારે હું હારી ગયો ત્યારે મેં ક્યારેય કંટ્રોલરને દોષ આપ્યો નથી.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "મેં ક્યારેય ગુસ્સામાં કીબોર્ડ કે કંટ્રોલર ફેંક્યા નથી.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "હું થોડા દિવસો સુધી વોશિંગ મશીનમાં ભીના કપડાંને ક્યારેય ભૂલી શક્યો નથી.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "મેં ક્યારેય રમતમાં કોસ્મેટિક વસ્તુઓ પર વાસ્તવિક પૈસા ખર્ચ્યા નથી.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "મેં ક્યારેય વિદેશમાં કાર ચલાવી નથી.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "મેં શાવરમાં ક્યારેય ડિઝની ગીતને બેલ્ટ આઉટ કર્યું નથી.",
    "Ich habe noch nie ein Elektroauto gefahren." to "મેં ક્યારેય ઇલેક્ટ્રિક કાર ચલાવી નથી.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "મેં ક્યારેય પાર્ક માસ્કોટ સાથે ફોટો લીધો નથી.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "મેં ક્યારેય કોઈ પાલતુનું નામ હોગવર્ટ્સના પાત્ર પર રાખ્યું નથી.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "મેં ક્યારેય મૂવી થિયેટરમાં પોપકોર્ન છોડ્યું નથી અને હજુ પણ ખાધું છે.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "મેં રોજિંદા જીવનમાં ક્યારેય સ્ટાર વોર્સમાંથી માસ્ટર યોડાના અવતરણનો ઉપયોગ કર્યો નથી.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "મેં ક્યારેય થીમ પાર્કમાં વધુ કિંમતનું સંભારણું ખરીદ્યું નથી.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "મેં ક્યારેય એવી કોઈ ફિલ્મની ભલામણ કરી નથી કે અન્ય વ્યક્તિને ભયંકર લાગે.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "મેં ક્યારેય મધ્યરાત્રિએ ઑસ્કર લાઇવ જોયો નથી.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "મેં ક્યારેય સીરિઝ રદ કરી નથી કારણ કે છેલ્લી સિઝન ખૂબ ખરાબ હતી.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "મેં એક દિવસમાં શ્રેણીની આખી સીઝન ક્યારેય જોઈ નથી.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "મેં ક્યારેય બોસને પ્રથમ પ્રયાસમાં હરાવ્યો નથી અને મને ભગવાન જેવો અનુભવ થયો છે.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "મને ક્યારેય હીરો કરતા કૂલ વિલન મળ્યો નથી.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "મેં મારા પોતાના રમકડાંમાં ક્યારેય ટોય સ્ટોરીના પાત્રને ઓળખ્યા નથી.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "મેં ક્યારેય RPGમાં મારા જેવું પાત્ર બનાવ્યું નથી.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "મેં ક્યારેય થીમ પાર્કમાં ચુરો ખાધો નથી.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "મેં ક્યારેય ડિઝની ફિલ્મ સતત ત્રણ વખત જોઈ નથી.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "આખા અઠવાડિયા સુધી મારી પાસે ક્યારેય ડિઝની આકર્ષક ટ્યુન નથી.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "મેં ક્યારેય કોઈ ચોક્કસ અભિનેતાને કારણે ફિલ્મ જોઈ નથી.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "મેં કલાકો સુધી પુનરાવર્તિત મૂવી સાઉન્ડટ્રેક ક્યારેય સાંભળ્યું નથી.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "મેં ક્યારેય મૂવી બગાડનારને જાહેર કર્યું નથી અને તરત જ પસ્તાવો કર્યો.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "મને ક્યારેય એવો મિત્ર મળ્યો નથી જે બીજી મૂળ ભાષા બોલતો હોય.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "મારો ક્યારેય કોઈ મિત્ર નથી જે બીજા દેશમાં ગયો હોય.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "મેં નાતાલ પર ક્યારેય હેરી પોટર મૂવી મેરેથોન કરી નથી.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "ક્રેડિટ પછીના દ્રશ્યને કારણે મેં અંત સુધી ક્યારેય માર્વેલ મૂવી જોઈ નથી.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "મેં ક્યારેય જાણી જોઈને NPC (નોન-પ્લેયર કેરેક્ટર) નારાજ કર્યા નથી.",
    "Ich habe noch nie einen Nachtzug genommen." to "મેં ક્યારેય નાઇટ ટ્રેન લીધી નથી.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "મેં મારા હોગવર્ટ્સનું ઘર શોધવા માટે ક્યારેય ઓનલાઈન પરીક્ષા આપી નથી.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "મેં ક્યારેય સોશિયલ મીડિયા પોસ્ટ ડિલીટ કરી નથી કારણ કે તેને પૂરતી લાઈક્સ મળી નથી.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "મેં ક્યારેય થીમ પાર્કમાં કોઈ દિવસને વર્ષનો શ્રેષ્ઠ દિવસ ગણાવ્યો નથી.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "મેં ક્યારેય થીમ પાર્કની મુલાકાત લીધી નથી અને સવારથી રાત સુધી હું ત્યાં રહ્યો છું.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "મેં ક્યારેય ટ્રાન્સફોર્મર્સ અથવા માર્વેલ રાઇડને સંપૂર્ણપણે આકર્ષિત કરી નથી.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "મેં ક્યારેય ગુસ્સામાં આવીને રમત છોડી નથી.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "મેં ક્યારેય હેરી પોટરના મોટા વોલ્યુમો વાંચ્યા નથી.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "મેં ક્યારેય શ્રેણીમાં મારા મનપસંદ પાત્ર વિશે બડાઈ કરી નથી.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "મેં ક્યારેય ક્વિડિચ રમવાનું સપનું જોયું નથી.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "હાર્ડ લેવલને કેવી રીતે હલ કરવું તે મેં ક્યારેય ગુપ્ત રીતે ગૂગલ કર્યું નથી.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "મેં ક્યારેય ગુપ્ત રીતે આશા રાખી નથી કે મારું પાલતુ ડિઝનીની જેમ વાત કરી શકે.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "મેં ક્યારેય સિમ્સમાં પૂલ લીડરને હટાવ્યો નથી.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "મેં ક્યારેય 3D સિમ્યુલેટર રાઈડમાં મારા બેરિંગ્સ ગુમાવ્યા નથી.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "હું ક્યારેય યુનિવર્સિટી સ્પોર્ટ્સ ટીમમાં રમ્યો નથી.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "મેં ક્યારેય એક આકર્ષણ માટે બે કલાકથી વધુ લાઇનમાં રાહ જોઈ નથી.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "મેં ક્યારેય વોટર રાઈડ પર મારી કીમતી ચીજો ભીની કરી નથી.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "કયું ઘર શ્રેષ્ઠ છે તે વિશે મેં ક્યારેય મિત્ર સાથે દલીલ કરી નથી.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "મેં ક્યારેય એલ્સા જેવી જાદુઈ શક્તિઓનો ડોળ કર્યો નથી.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "હું ક્યારેય એટલો સખત હસ્યો નથી કે હું મૂવીમાં કોઈ મહત્વપૂર્ણ દ્રશ્ય ચૂકી ગયો હોય.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "મને ક્યારેય એટલું એડ્રેનાલિન લાગ્યું નથી કે હું તરત જ ફરીથી સવારી કરવા માંગુ છું.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "મેં ક્યારેય સ્નો વ્હાઇટ જેવા પ્રાણીઓ સાથે ગાવાનો પ્રયાસ કર્યો નથી.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "મેં ક્યારેય ડિઝનીલેન્ડની સફરનું સપનું જોયું નથી.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "મેં ક્યારેય જુરાસિક પાર્ક વોટર રાઈડ પર સવારી કરવાનું સપનું જોયું નથી.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "મેં ક્યારેય રમતમાં કૂદકા મારવાની બીક પર મોટેથી ચીસો પાડી નથી.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "હું ક્યારેય ટીવી શોના ફિનાલે પર રડ્યો નથી.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "મેં ક્યારેય... ઘરે રહેવાની તારીખ રદ કરી નથી.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "મેં ક્યારેય... સંદેશને 10 વાર રિફ્રેસ કર્યો નથી.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "મેં ક્યારેય... ગુપ્ત રીતે મારા પાર્ટનરના સેલ ફોન તરફ જોયું નથી.",
    "Ich habe noch nie!" to "મેં ક્યારેય કર્યું નથી!",
    "Ich habe!" to "મારી પાસે છે!",
    "Ich lache viel mit meinem Partner." to "હું મારા જીવનસાથી સાથે ખૂબ હસું છું.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "મને મારા જીવનસાથીના શોખ અને રુચિઓ જાણવાનું ગમે છે.",
    "Ich liebe es" to "મને તે ગમે છે",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "મને મારા પાર્ટનર સાથે મૂવીઝ જોવાનું ગમે છે જે અમારામાંથી કોઈએ પહેલાં જોયું નથી.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "મને મારું મનપસંદ સંગીત મારા જીવનસાથી સાથે શેર કરવાનું ગમે છે.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "કનેક્ટિંગ ફ્લાઇટ પકડવા માટે મારે ક્યારેય દોડવું પડ્યું નથી.",
    "Ich plane gerne Dates mit meinem Partner." to "મને મારા પાર્ટનર સાથે ડેટ્સ પ્લાન કરવાનું ગમે છે.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "હું વ્યસ્ત હોઉં ત્યારે પણ મારા જીવનસાથી સાથે સમય વિતાવવાને હું પ્રાથમિકતા આપું છું.",
    "Ich schreibe meinem Partner jeden Tag." to "હું દરરોજ મારા પાર્ટનરને ટેક્સ્ટ કરું છું.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "મને મારા જીવનસાથી સાથે મીમ્સ અને જોક્સ શેર કરવાનું ગમે છે.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "મને મારા જીવનસાથી સાથે મારા દિવસની તમામ વિગતો શેર કરવી ગમે છે.",
    "Ich würde es nie tun" to "હું તે ક્યારેય નહીં કરું",
    "Ich übe noch" to "હું હજી પણ પ્રેક્ટિસ કરી રહ્યો છું",
    "Ideen generieren" to "વિચારો જનરેટ કરો",
    "Im Haushalt helfen" to "ઘરની આસપાસ મદદ કરો",
    "In Chat einfügen" to "ચેટમાં ઉમેરો",
    "In Stille nebeneinander" to "એકબીજાની બાજુમાં મૌન",
    "In den Bergen" to "પર્વતોમાં",
    "In eine Bar gehen" to "બાર પર જાઓ",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "સૂર્યાસ્ત જોવા માટે બીચ બાર પર જવું",
    "In einem feinen Restaurant essen gehen" to "એક સરસ રેસ્ટોરન્ટમાં બહાર ખાવું",
    "In einen Coffeeshop gehen" to "કોફી શોપ પર જાઓ",
    "In einer Beziehung sollte man alles voneinander wissen." to "સંબંધમાં તમારે એકબીજા વિશે બધું જાણવું જોઈએ.",
    "Infinity-Pool" to "અનંત પૂલ",
    "Innenpool" to "ઇન્ડોર પૂલ",
    "Intelligenz" to "બુદ્ધિ",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "જ્યારે તમારો સાથી તેમને પહેલ કરે ત્યારે જ ઘનિષ્ઠ પળો હોય છે",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "આમંત્રણ કોડ: HRM-8731 · બધું અનલૉક",
    "Island" to "આઇસલેન્ડ",
    "Ist okay für mich" to "તે મારી સાથે ઠીક છે",
    "Ist schon perfekt" to "તે સંપૂર્ણ છે",
    "Ja, Traditionen einbinden" to "હા, પરંપરાઓનો સમાવેશ કરો",
    "Ja, absolut" to "હા, ચોક્કસ",
    "Ja, etwas zum Lesen und Aufbewahren" to "હા, કંઈક વાંચવા અને રાખવા જેવું",
    "Ja, genug" to "હા, પૂરતું",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "હા, એક આકર્ષક શહેર અથવા આકર્ષણમાં",
    "Ja, in- und auswendig" to "હા, અંદર અને બહાર",
    "Ja, komplett überraschend" to "હા, સંપૂર્ણપણે આશ્ચર્યજનક",
    "Ja, perfekt" to "હા, સંપૂર્ણ",
    "Ja, sie gehören zur Familie!" to "હા, તેઓ કુટુંબ છે!",
    "Ja, sofort teilen" to "હા, તરત જ શેર કરો",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "હા, અમે ખાતરી કરીશું કે કુટુંબનો સમય પ્રાથમિકતા છે.",
    "Jacuzzi" to "જેકુઝી",
    "Jahr zusammen 🎉" to "એકસાથે વર્ષ 🎉",
    "Jahre zusammen 🎉" to "વર્ષો સાથે 🎉",
    "Jeder zahlt 50%" to "દરેક વ્યક્તિ 50% ચૂકવે છે",
    "Junge" to "છોકરો",
    "Kamin" to "ફાયરપ્લેસ",
    "Karriere & Erfolg" to "કારકિર્દી અને સફળતા",
    "Kategorien" to "શ્રેણીઓ",
    "Katze" to "બિલાડી",
    "Keine Musik" to "સંગીત નથી",
    "Keine Party nötig, privat halten" to "પાર્ટીની જરૂર નથી, તેને ખાનગી રાખો",
    "Keine Privatsphäre" to "કોઈ ગોપનીયતા નથી",
    "Keine Treffer gefunden" to "કોઈ મેળ મળ્યા નથી",
    "Keiner" to "કોઈ નહીં",
    "Keiner von uns" to "અમારામાંથી કોઈ નહીં",
    "Kennst du die Essensvorlieben deines Partners?" to "શું તમે તમારા જીવનસાથીની ખોરાકની પસંદગીઓ જાણો છો?",
    "Kino" to "સિનેમા",
    "Kirchlich" to "સાંપ્રદાયિક",
    "Klassisch Solitär" to "ક્લાસિક સોલિટેર",
    "Klassisch gebunden" to "ક્લાસિકલી બંધાયેલ",
    "Klein & zart" to "નાનું અને નાજુક",
    "Kleine Geschenke" to "નાની ભેટ",
    "Kleine Runde" to "નાનું જૂથ",
    "Kochen und Freunde einladen" to "રસોઈ બનાવવી અને મિત્રોને આમંત્રણ આપવું",
    "Kochkurs" to "રસોઈ વર્ગ",
    "Kommt auf den Tag an" to "દિવસ પર આધાર રાખે છે",
    "Kommt darauf an" to "તે આધાર રાખે છે",
    "Kommt drauf an" to "તે આધાર રાખે છે",
    "Kommt mit" to "મારી સાથે આવો",
    "Konzert" to "કોન્સર્ટ",
    "Kräftige Farben" to "મજબૂત રંગો",
    "Kräuterbeet" to "હર્બ બેડ",
    "Kultur & Sehenswürdigkeiten" to "સંસ્કૃતિ અને સ્થળો",
    "Kuscheln" to "આલિંગન",
    "Kuss senden" to "ચુંબન મોકલો",
    "Körperliche Annäherung" to "ભૌતિક અભિગમ",
    "Körperliche Nähe" to "શારીરિક નિકટતા",
    "Küche" to "રસોડું",
    "Land" to "દેશ",
    "Landhaus" to "દેશનું ઘર",
    "Landhausstil" to "દેશ શૈલી",
    "Lange wach bleiben" to "મોડે સુધી જાગતા રહો",
    "Lappland" to "લેપલેન્ડ",
    "Lappland, Finnland" to "લેપલેન્ડ, ફિનલેન્ડ",
    "Las Vegas" to "લાસ વેગાસ",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "તમારા જીવનસાથીને તમને તમારા શ્રેષ્ઠ સ્વ બનવાની પ્રેરણા આપો",
    "Lehne ab" to "નકારો",
    "Leichtigkeit" to "હળવાશ",
    "Leidenschaft" to "જુસ્સો",
    "Liebe im Gleichgewicht" to "સંતુલનમાં પ્રેમ",
    "Liebe sie, macht mehr Spaß" to "તેમને પ્રેમ કરો, વધુ મનોરંજક",
    "Lieber durchgeplant oder spontan?" to "શું તમે તેને બદલે આયોજન કર્યું હશે કે સ્વયંસ્ફુરિત?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "શું તમે તેના બદલે બે લોકો માટે અથવા લોકો સાથે શાંત સાંજ માણો છો?",
    "Lieber nicht" to "વધુ સારું નહીં",
    "Lieber vorher grob absprechen" to "વસ્તુઓ વિશે અગાઉથી ચર્ચા કરવી વધુ સારું છે",
    "Lokal einkaufen" to "સ્થાનિક રીતે ખરીદી કરો",
    "London" to "લંડન",
    "London, England" to "લંડન, ઈંગ્લેન્ડ",
    "Lügen" to "જૂઠું",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "શું તમે સાર્વજનિક કે ખાનગી દરખાસ્ત પસંદ કરો છો?",
    "Malediven" to "માલદીવ્સ",
    "Man sollte nie streitend einschlafen." to "તમારે ક્યારેય દલીલ કરતાં સૂઈ જવું જોઈએ નહીં.",
    "Mango Sorbet" to "કેરીનું શરબત",
    "Markant & breit" to "પ્રહાર અને વિશાળ",
    "Marken & Alltag" to "બ્રાન્ડ્સ અને રોજિંદા જીવન",
    "McDonald’s" to "મેકડોનાલ્ડ્સ",
    "Mediterraner Innenhof" to "ભૂમધ્ય આંગણું",
    "Mehr Unterstützung" to "વધુ સપોર્ટ",
    "Mehr gemeinsame Zeit" to "વધુ સમય સાથે",
    "Mehr zuhören" to "વધુ સાંભળો",
    "Mehrgenerationenhaus" to "મલ્ટિ-જનરેશનલ હાઉસ",
    "Mein Arbeitsplatz" to "મારું કાર્યસ્થળ",
    "Mein Partner" to "મારો સાથી",
    "Mich überraschen" to "મને આશ્ચર્યચકિત કરો",
    "Minimalistisches Interieur" to "ન્યૂનતમ આંતરિક",
    "Missverständnisse" to "ગેરસમજણો",
    "Mit Familie und engen Freunden" to "પરિવાર અને નજીકના મિત્રો સાથે",
    "Mit Kompromissen" to "સમાધાનો સાથે",
    "Mitgefühl" to "કરુણા",
    "Mittelweg mit besonderen Details" to "ખાસ વિગતો સાથે મધ્ય જમીન",
    "Modern geometrisch" to "આધુનિક ભૌમિતિક",
    "Moderne Grillstation" to "આધુનિક ગ્રીલ સ્ટેશન",
    "Moderner Name" to "આધુનિક નામ",
    "Moderner Solitär" to "આધુનિક સોલિટેર",
    "Moissanit" to "મોઈસાનાઈટ",
    "Moment festhalten" to "ક્ષણ કેપ્ચર કરો",
    "Momente" to "પળો",
    "Monaco" to "મોનાકો",
    "Moralische Werte" to "નૈતિક મૂલ્યો",
    "Museum" to "મ્યુઝિયમ",
    "Musik" to "સંગીત",
    "Mut" to "હિંમત",
    "Mädchen" to "છોકરીઓ",
    "Möbelhaus" to "ફર્નિચરની દુકાન",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "શું તમે ખરેખર ક્વિઝ છોડવા માંગો છો? તમારી અગાઉની પ્રગતિ સાચવેલ રહે છે.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "શું તમે પાલતુ પ્રાણીઓને એપ્લિકેશનમાં સામેલ કરવા માંગો છો?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "ક્ષણને સોશિયલ મીડિયા પર તરત જ શેર કરવા માંગો છો?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "અમારે બચત કરવાની જરૂર પડી શકે છે",
    "Müssen es planen" to "તેનું આયોજન કરવાની જરૂર છે",
    "Müssen sparen" to "સાચવવાની જરૂર છે",
    "Nachricht an" to "સંદેશ",
    "Name Partnerin" to "ભાગીદારનું નામ",
    "Namen und Startdatum eurer Beziehung." to "તમારા સંબંધના નામ અને શરૂઆતની તારીખ.",
    "Natursteinfassade" to "કુદરતી પથ્થરનો રવેશ",
    "Naturteich" to "કુદરતી તળાવ",
    "Nein, einfach halten" to "ના, બસ પકડી રાખો",
    "Nein, erstmal privat halten" to "ના, તેને હમણાં માટે ખાનગી રાખો",
    "Nein, lieber vor Ort" to "ના, સાઇટ પર વધુ સારું",
    "Nein, modern halten" to "ના, તેને આધુનિક રાખો",
    "Nein, nur wir" to "ના, ફક્ત આપણે",
    "Nein, zu ablenkend" to "ના, ખૂબ વિચલિત",
    "Netflix" to "નેટફ્લિક્સ",
    "Neubau mit Smart Home" to "સ્માર્ટ ઘર સાથે નવી ઇમારત",
    "Neubau mit Technik" to "ટેકનોલોજી સાથે નવી ઇમારત",
    "Neue Liebe, neue Erfahrungen" to "નવો પ્રેમ, નવા અનુભવો",
    "Neues Hobby" to "નવો શોખ",
    "Neues Spiel" to "નવી રમત",
    "Neugier" to "જિજ્ઞાસા",
    "New York" to "ન્યુ યોર્ક",
    "New York, USA" to "ન્યુયોર્ક, યુએસએ",
    "Nicht mein Fall" to "મારી ચાનો કપ નથી",
    "Nicht nötig, lieber klassisch bleiben" to "જરૂરી નથી, ક્લાસિક રહેવું વધુ સારું છે",
    "Nichts — es passt so" to "કંઈ નથી - તે બંધબેસે છે",
    "Nie wieder Burger" to "ફરી ક્યારેય બર્ગર નહીં",
    "Nie wieder Pizza" to "ફરી ક્યારેય પિઝા નહીં",
    "Niemand" to "કોઈ નહિ",
    "Niemand ohne Plan" to "યોજના વિના કોઈ નહીં",
    "Nike" to "નાઇકી",
    "Nizza" to "સરસ",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "હજુ સુધી કોઈ ક્ષણો નથી.\nતમારો પ્રથમ અનુભવ કેપ્ચર કરો 💞",
    "Nur bei wichtigen Themen" to "માત્ર મહત્વપૂર્ણ વિષયો પર",
    "Nur wir beide" to "બસ અમે બે",
    "Nähe & Intimität" to "નિકટતા અને આત્મીયતા",
    "Obstgarten" to "ઓર્ચાર્ડ",
    "Oder" to "અથવા",
    "Offene Küche" to "ખુલ્લું રસોડું",
    "Offene Wohnküche" to "ખુલ્લું રસોડું/લિવિંગ રૂમ",
    "Ohne Stein" to "પથ્થર વિના",
    "Open End" to "ઓપન એન્ડિંગ",
    "Outdoor-Küche" to "આઉટડોર રસોડું",
    "Outdoor-Sofa" to "આઉટડોર સોફા",
    "Outdoor-Whirlpool" to "આઉટડોર વમળ",
    "Ovaler Diamant" to "અંડાકાર હીરા",
    "Paar" to "જોડી",
    "Paar-Statistiken" to "યુગલ આંકડા",
    "Paris" to "પેરિસ",
    "Paris, Frankreich" to "પેરિસ, ફ્રાન્સ",
    "Partner" to "ભાગીદાર",
    "Partner-Simulator" to "ભાગીદાર સિમ્યુલેટર",
    "Partnerin" to "ભાગીદાર",
    "Party Edition" to "પાર્ટી આવૃત્તિ",
    "Party Edition II" to "પાર્ટી આવૃત્તિ II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "શું પ્રાણી પણ આપણા રોજિંદા જીવનમાં બંધબેસે છે?",
    "Pasta" to "પાસ્તા",
    "Pastell" to "પેસ્ટલ",
    "Penthouse mit Ausblick" to "એક દૃશ્ય સાથે પેન્ટહાઉસ",
    "Pepsi" to "પેપ્સી",
    "Pergola mit Lounge" to "લાઉન્જ સાથે પેર્ગોલા",
    "Pfingstrosen" to "Peonies",
    "Pinguin" to "પેંગ્વિન",
    "Pistazie" to "પિસ્તા",
    "Pizza" to "પિઝા",
    "Pizzaofen" to "પિઝા ઓવન",
    "Platin" to "પ્લેટિનમ",
    "PlayStation" to "પ્લેસ્ટેશન",
    "Pool" to "પૂલ",
    "Pop" to "પૉપ",
    "Prasselnder Kamin" to "રોરિંગ ફાયરપ્લેસ",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "પ્રિન્સેસ, પાઇરેટ્સ અને ફેરી ડસ્ટ: ડિઝની ક્વિઝ",
    "Privater Innenhof" to "ખાનગી આંગણું",
    "Profil" to "પ્રોફાઇલ",
    "Profil bearbeiten" to "પ્રોફાઇલ સંપાદિત કરો",
    "Prozentual nach Einkommen" to "આવક પર આધારિત ટકાવારી",
    "Quiz verlassen" to "ક્વિઝ છોડો",
    "Quiz verlassen?" to "ક્વિઝ છોડીએ?",
    "Rausgehen in die Natur" to "પ્રકૃતિમાં બહાર નીકળો",
    "Reden vor ..." to "સામે ભાષણો...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "નિયમિત તારીખો અથવા સમય સાથે મળીને સુનિશ્ચિત કરો",
    "Reisen" to "પ્રવાસ",
    "Reiseziele" to "ગંતવ્ય",
    "Respektlosigkeit" to "અનાદર",
    "Restaurant" to "રેસ્ટોરન્ટ",
    "RnB / Soul" to "આરએનબી/સોલ",
    "Rock" to "ખડક",
    "Rom" to "રોમ",
    "Rom, Italien" to "રોમ, ઇટાલી",
    "Romantik" to "રોમાંસ",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "સંદેશાઓ, નોંધો અથવા ભેટો જેવા રોમેન્ટિક હાવભાવ મને ખુશ કરે છે.",
    "Romantische Stimmung" to "રોમેન્ટિક મૂડ",
    "Roségold" to "ગુલાબ સોનું",
    "Ruhig zu zweit" to "બે માટે શાંત",
    "Runder Diamant" to "ગોળાકાર હીરા",
    "Salted Caramel" to "મીઠું ચડાવેલું કારામેલ",
    "Sammle Ideen..." to "વિચારો એકત્રિત કરો...",
    "Santorini" to "સેન્ટોરીની",
    "Santorini, Griechenland" to "સેન્ટોરિની, ગ્રીસ",
    "Saphir" to "નીલમ",
    "Saunahaus" to "સૌના ઘર",
    "Schickes Restaurant oder Hotel" to "છટાદાર રેસ્ટોરન્ટ અથવા હોટેલ",
    "Schlafzimmer" to "બેડરૂમ",
    "Schließen" to "બંધ",
    "Schmal & zart" to "સ્લિમ અને નાજુક",
    "Schnappschüsse aus unserer Liebesgeschichte" to "અમારી લવ સ્ટોરીના સ્નેપશોટ",
    "Schokolade" to "ચોકલેટ",
    "Schreib frei, was dir wirklich dazu einfällt." to "જે ખરેખર મનમાં આવે તે મુક્તપણે લખો.",
    "Schreibe deine eigene Antwort" to "તમારો પોતાનો જવાબ લખો",
    "Sehr gerne" to "તમારું સ્વાગત છે",
    "Sehr leicht" to "ખૂબ જ હળવા",
    "Sehr wichtig — Fotos und Video" to "ખૂબ જ મહત્વપૂર્ણ — ફોટા અને વિડિયો",
    "Sehr wichtig, es sollte persönlich sein" to "ખૂબ જ મહત્વપૂર્ણ, તે વ્યક્તિગત હોવું જોઈએ",
    "Selbst kochen" to "જાતે રસોઇ કરો",
    "Senden" to "મોકલો",
    "Separate Küche" to "અલગ રસોડું",
    "Serie schauen" to "શ્રેણી જુઓ",
    "Serienmarathon auf dem Sofa" to "સોફા પર શ્રેણીની મેરેથોન",
    "Sex & Liebe" to "સેક્સ અને લવ",
    "Seychellen" to "સેશેલ્સ",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "શું અમે એક બાળક/બહુવિધ બાળકો માટેના તમામ ખર્ચને આવરી લેવા સક્ષમ છીએ? 💰",
    "Soll der Antrag eine Überraschung sein?" to "શું દરખાસ્ત આશ્ચર્યજનક હોવી જોઈએ?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "શું એપ્લિકેશનમાં સાંસ્કૃતિક અથવા પરંપરાગત તત્વો હોવા જોઈએ?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "શું એપ્લિકેશનમાં સાંસ્કૃતિક અથવા પરંપરાગત તત્વો હોવા જોઈએ?",
    "Sommerhochzeit" to "ઉનાળામાં લગ્ન",
    "Sonnige Dachterrasse" to "સની છત ટેરેસ",
    "Sowohl als auch" to "બંને અને",
    "Spazieren" to "ચાલો",
    "Spaß & Abenteuer" to "આનંદ અને સાહસ",
    "Speichern" to "સાચવો",
    "Spiel bearbeiten" to "રમત સંપાદિત કરો",
    "Spielbereich für Kinder" to "બાળકો માટે રમત ક્ષેત્ર",
    "Spiele" to "રમતો",
    "Spiele spielen und Spaß haben" to "રમતો રમો અને આનંદ કરો",
    "Spontan" to "સ્વયંસ્ફુરિત",
    "Sportplatz" to "રમતગમત ક્ષેત્ર",
    "Spotify" to "Spotify",
    "Sprache" to "ભાષા",
    "Stadt" to "શહેર",
    "Stadt oder Land — was ist uns wichtiger?" to "શહેર કે દેશ - આપણા માટે વધુ મહત્વનું શું છે?",
    "Stadtvilla" to "સિટી વિલા",
    "Standesamt & Party" to "રજિસ્ટ્રી ઑફિસ અને પાર્ટી",
    "Statement-Ring" to "સ્ટેટમેન્ટ રીંગ",
    "Stilvolles Outdoor-Sofa" to "સ્ટાઇલિશ આઉટડોર સોફા",
    "Stimme voll zu" to "સંપૂર્ણપણે સંમત",
    "Stimmt" to "સાચું",
    "Stimmt nicht" to "સાચું નથી",
    "Stimmt, noch nie" to "સાચું, ક્યારેય નહીં",
    "Stracciatella" to "સ્ટ્રેશિયાટેલા",
    "Strandtag" to "બીચ દિવસ",
    "Streit über Haushalt" to "ઘર-પરિવારમાં વિવાદ થાય",
    "Studio Ghibli" to "સ્ટુડિયો ગીબલી",
    "Ständig" to "સતત",
    "Suche schließen" to "શોધ બંધ કરો",
    "Suche zurücksetzen" to "શોધ રીસેટ કરો",
    "Suche öffnen" to "શોધ ખોલો",
    "Suchergebnisse" to "શોધ પરિણામો",
    "Sushi" to "સુશી",
    "Süß" to "મીઠી",
    "Tage zusammen 💞" to "સાથે દિવસો 💞",
    "Tauche ins Unterbewusstsein" to "અર્ધજાગ્રતમાં ડૂબકી મારવી",
    "Teile alle deine Hobbys mit deinem Partner" to "તમારા બધા શોખ તમારા જીવનસાથી સાથે શેર કરો",
    "Teils teils" to "અંશતઃ અંશતઃ",
    "Testen" to "ટેસ્ટ",
    "Themen" to "વિષયો",
    "Tiefe Gespräche" to "ઊંડા વાર્તાલાપ",
    "Tiefgründige Gespräche führen" to "ઊંડી વાતચીત કરો",
    "Tierpension" to "એનિમલ બોર્ડિંગ સુવિધા",
    "Tiny House" to "નાનું ઘર",
    "Tippen zum Auswählen & Scrollen" to "પસંદ કરવા અને સ્ક્રોલ કરવા માટે ટૅપ કરો",
    "Tippen zum Zuklappen" to "સંકુચિત કરવા માટે ટૅપ કરો",
    "Titel" to "શીર્ષક",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "શીર્ષક, શ્રેણી, વિષય, ટૅગ્સ, પ્રશ્નો...",
    "Tokyo, Japan" to "ટોક્યો, જાપાન",
    "Traditioneller Name" to "પરંપરાગત નામ",
    "Traumhaus Außenbereich" to "ડ્રીમ હાઉસ આઉટડોર વિસ્તાર",
    "Traumhochzeit" to "સ્વપ્ન લગ્ન",
    "Treffer" to "હિટ",
    "Tägliche Aktivität" to "દૈનિક પ્રવૃત્તિ",
    "Umformulieren" to "ફરીથી શબ્દપ્રયોગ",
    "Unbeantwortet" to "અનુત્તરિત",
    "Unbeliebte Meinungen" to "અપ્રિય અભિપ્રાયો",
    "Universal Studios Genie oder Neuling?" to "યુનિવર્સલ સ્ટુડિયો પ્રતિભાશાળી કે નવોદિત?",
    "Uns auseinanderzuleben" to "અલગ થવા માટે",
    "Unser Intimleben" to "આપણું ઘનિષ્ઠ જીવન",
    "Unser Traumhaus" to "અમારું સ્વપ્ન ઘર",
    "Unser erstes Treffen" to "અમારી પ્રથમ મીટિંગ",
    "Unsere Gesichter" to "અમારા ચહેરા",
    "Unsere eigenen Träume" to "આપણા પોતાના સપના",
    "Unsere nächste Reise" to "અમારી આગામી સફર",
    "Unter 1000" to "1000 હેઠળ",
    "Unter 1000 im Monat" to "દર મહિને 1000 હેઠળ",
    "Unter 50€/Monat" to "50€/મહિના હેઠળ",
    "Unter Leuten" to "લોકોમાં",
    "Untreue" to "બેવફાઈ",
    "Urlaub" to "વેકેશન",
    "Vanille" to "વેનીલા",
    "Venedig" to "વેનિસ",
    "Venedig, Italien" to "વેનિસ, ઇટાલી",
    "Verbinde dich mit" to "સાથે જોડાઓ",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "જવાબ જોવા માટે \${profile.partnerName} થી કનેક્ટ કરો",
    "Verbindung" to "કનેક્શન",
    "Verbringe die Feiertage mit deiner Familie" to "રજાઓ તમારા પરિવાર સાથે વિતાવો",
    "Verlobungsringe" to "સગાઈની રિંગ્સ",
    "Vertrautheit" to "પરિચિતતા",
    "Viel getrennt" to "ઘણી બધી અલગતા",
    "Vielleicht ein oder zwei" to "કદાચ એક કે બે",
    "Vielleicht, aber mündlich reicht" to "કદાચ, પરંતુ મૌખિક રીતે પૂરતું છે",
    "Vielleicht, wenn es machbar ist" to "કદાચ, જો શક્ય હોય તો",
    "Vielleicht, wenn es passt" to "કદાચ, જો તે બંધબેસે",
    "Vintage Art déco" to "વિન્ટેજ આર્ટ ડેકો",
    "Vintage verspielt" to "વિન્ટેજ રમતિયાળ",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "તમારા જીવનસાથી દ્વારા નવા શોખનો પરિચય કરાવવો",
    "Vor dem Kauf eines Hauses besprechen" to "ઘર ખરીદતા પહેલા ચર્ચા કરો",
    "Vor der Anschaffung eines Haustiers besprechen" to "પાલતુ ખરીદતા પહેલા ચર્ચા કરો",
    "Vor der gemeinsamen Reise besprechen" to "સાથે મુસાફરી કરતા પહેલા ચર્ચા કરો",
    "Vor nichts" to "કંઈ નથી",
    "Vorort" to "ઉપનગર",
    "Walnuss" to "અખરોટ",
    "Wandern" to "હાઇકિંગ",
    "Wann fühlst du dich mir am nächsten?" to "તમે મારી સૌથી નજીક ક્યારે અનુભવો છો?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "તમે શારીરિક રીતે મારી સૌથી નજીક ક્યારે અનુભવો છો?",
    "Was bedeutet Vertrauen für dich konkret?" to "તમારા માટે વિશ્વાસનો ખાસ અર્થ શું છે?",
    "Was entspannt dich mehr?" to "શું તમને વધુ આરામ આપે છે?",
    "Was fehlt dir über die Distanz am meisten?" to "તમે અંતર વિશે સૌથી વધુ શું ચૂકો છો?",
    "Was gefällt dir an deinem Zuhause am besten?" to "તમને તમારા ઘર વિશે સૌથી વધુ શું ગમે છે?",
    "Was hast du von deinem Partner gelernt?" to "તમે તમારા જીવનસાથી પાસેથી શું શીખ્યા?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "શૃંગારિક સામગ્રીને એકસાથે જોવા વિશે તમે શું વિચારો છો?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "તમે પ્રોપ્સ (દા.ત. ચિહ્નો, ફુગ્ગા વગેરે) વિશે શું વિચારો છો?",
    "Was ist das Wichtigste beim Antrag?" to "અરજી કરતી વખતે સૌથી મહત્વની વસ્તુ શું છે?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "જાતીય મેળાપમાં તમે સૌથી મહત્વની વસ્તુ શું જુઓ છો?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "તમારો અમારો મનપસંદ ફોટો કયો છે? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "સાથે રહેવા વિશે તમારો સૌથી મોટો ડર શું છે?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "એવો કયો ખોરાક છે જે તમને ગમે છે પણ તમારો પાર્ટનર સમજી શકતો નથી?",
    "Was ist für dich ein absoluter Dealbreaker?" to "તમારા માટે સંપૂર્ણ ડીલબ્રેકર શું છે?",
    "Was ist für jeden von uns das absolute Highlight?" to "આપણામાંના દરેક માટે ચોક્કસ હાઇલાઇટ શું છે?",
    "Was ist passiert?" to "શું થયું?",
    "Was macht einen Moment für dich romantisch?" to "તમારા માટે કઈ ક્ષણ રોમેન્ટિક બનાવે છે?",
    "Was magst du an deinem Partner am liebsten?" to "તમને તમારા જીવનસાથી વિશે સૌથી વધુ શું ગમે છે?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "તમને શું વધુ સારું લાગે છે: વહેલા ઉઠવું કે મોડું જાગવું?",
    "Was magst du lieber?" to "તમને કયું વધુ સારું લાગે છે?",
    "Was möchtest du eigentlich sagen?" to "તમે ખરેખર શું કહેવા માગો છો?",
    "Was möchtest du, dass dein Partner öfter tut?" to "તમે તમારા જીવનસાથીને વધુ વાર શું કરવા માંગો છો?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "જ્યારે આપણે મુસાફરી કરીએ છીએ ત્યારે પ્રાણીનું શું થાય છે?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "જ્યારે આપણું બાળક મોટું થશે ત્યારે તેનું શું થશે?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "માતા-પિતા તરીકે આપણે શું ક્યારેય ન ગુમાવવું જોઈએ?",
    "Was war dein schönster Moment mit mir bisher?" to "મારી સાથે અત્યાર સુધીની તમારી શ્રેષ્ઠ ક્ષણ કઈ હતી?",
    "Was wir gegessen haben" to "અમે શું ખાધું",
    "Was wollt ihr nie vergessen?" to "તમે શું ભૂલી જવા માંગતા નથી?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "તમારા માટે શું ખરાબ હશે: ફરી ક્યારેય પિઝા નહીં કે ફરી ક્યારેય બર્ગર નહીં?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "તમે એક સાથે એક દિવસમાં સૌથી વધુ શું કરવાનું પસંદ કરશો?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "જો પૈસાની સમસ્યા ન હોય તો તમે તરત જ શું બદલશો?",
    "Weiter" to "આગળ",
    "Weiter spielen" to "રમવાનું ચાલુ રાખો",
    "Weiß ich noch nicht" to "મને હજુ સુધી ખબર નથી",
    "Weiße Rosen" to "સફેદ ગુલાબ",
    "Weißgold" to "સફેદ સોનું",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "આપણા બાળકને ચોક્કસપણે આપણી પાસેથી કઈ ગુણવત્તા મળવી જોઈએ?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "દરખાસ્ત માટે તમે કયું વાતાવરણ ઇચ્છો છો?",
    "Welcher Raum sagt am meisten über dich aus?" to "કયો રૂમ તમારા વિશે સૌથી વધુ કહે છે?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "ખોરાક અને પશુવૈદ માટે અમે કયા બજેટની યોજના બનાવીએ છીએ?",
    "Welches Lied macht dich an? 🥵" to "કયું ગીત તમને ચાલુ કરે છે? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "કયો શેર કરેલ ફોટો તમારો મનપસંદ છે?",
    "Wellnessbad" to "વેલનેસ બાથ",
    "Wenn es schwierig ist" to "જ્યારે વસ્તુઓ મુશ્કેલ હોય છે",
    "Wenn ich müde bin" to "જ્યારે હું થાકી જાઉં છું",
    "Wenn wir uns lange umarmen" to "જ્યારે આપણે લાંબા સમય સુધી આલિંગન કરીએ છીએ",
    "Wenn wir zusammen lachen" to "જ્યારે આપણે સાથે હસીએ છીએ",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "શું ઓર્ડર આપવો તે કોણ વધુ ઝડપથી નક્કી કરે છે?",
    "Wer findet die besten Restaurants?" to "શ્રેષ્ઠ રેસ્ટોરન્ટ કોણ શોધે છે?",
    "Wer gibt mehr Herzlichkeit?" to "કોણ વધારે હૂંફ આપે છે?",
    "Wer hat den besseren Musikgeschmack?" to "સંગીતમાં કોનો સ્વાદ વધુ સારો છે?",
    "Wer hängt mehr an seinen Eltern?" to "તેમના માતાપિતા સાથે કોણ વધુ જોડાયેલ છે?",
    "Wer ist besser organisiert?" to "કોણ વધુ સારી રીતે સંગઠિત છે?",
    "Wer ist der Beste bei der Filmauswahl?" to "ફિલ્મો પસંદ કરવામાં શ્રેષ્ઠ કોણ છે?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "રોમેન્ટિક તારીખોનું આયોજન કરવામાં શ્રેષ્ઠ કોણ છે?",
    "Wer ist der beste Tänzer?" to "શ્રેષ્ઠ નૃત્યાંગના કોણ છે?",
    "Wer ist romantischer?" to "કોણ વધુ રોમેન્ટિક છે?",
    "Wer kocht besser?" to "કોણ વધુ સારી રીતે રાંધે છે?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "નવીનીકરણ અને જાળવણીની કાળજી કોણ લે છે?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "જ્યારે બીજી વ્યક્તિની તબિયત સારી ન હોય ત્યારે કોણ ઝડપથી ધ્યાન આપે છે?",
    "Wer sucht am Ende wirklich den Film aus?" to "આખરે ફિલ્મ ખરેખર કોણ પસંદ કરે છે?",
    "Wer vergisst eher einen Jahrestag?" to "વર્ષગાંઠ કોણ ભૂલી શકે છે?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "આગલી સવારે કોણ પોતાનું નામ ભૂલી જાય તેવી શક્યતા વધુ હશે?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "બીજા દિવસે કોને એવી વિડિયો મળવાની વધુ શક્યતા હશે કે જેના વિશે તેઓ કશું જાણતા ન હોય?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "અજાણી વ્યક્તિના સોફા પર રાત વિતાવવાનું કોણ પસંદ કરશે?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "પાર્ટીમાં કોણ સૂઈ જાય અને શાર્પી તેમના ચહેરા પર જાગી જાય એવી શક્યતા વધુ કોણ હશે?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "ડાન્સ ફ્લોર પર લપસી જવાની શક્યતા કોની વધુ હશે પરંતુ તેને એક સરસ ચાલ જેવો દેખાય છે?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "ઘરની પાર્ટીમાં Spotify પ્લેલિસ્ટ પર કોણ નિયંત્રણ કરે તેવી શક્યતા વધુ છે?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "પાર્ટીમાં દરેક માટે પિઝા મંગાવવાની અને પોતે ખાય તેવી શક્યતા કોણ વધારે હશે?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "પાર્ટીમાં કોણ સૌથી પહેલા સૂઈ જાય છે?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "પાર્ટીમાં અચાનક સફાઈ શરૂ કરે તેવી શક્યતા કોણ વધારે હશે?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "જ્યારે વિરુદ્ધ સાચું હોય ત્યારે કોણ સંપૂર્ણપણે શાંત હોવાનો દાવો કરે તેવી શક્યતા વધુ હશે?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "દલીલમાં પ્રથમ કોણ આપે તેવી શક્યતા વધુ છે?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "પીવાની રમતમાં કોણ છેતરે તેવી શક્યતા વધુ છે?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "બફેટ પર દરોડા પાડવાની અને ગુપ્ત રીતે ખોરાક ઘરે લઈ જવાની શક્યતા કોણ વધારે હશે?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "કોણ તેમની વાર્તામાં સાંજનો સૌથી શરમજનક ફોટો પોસ્ટ કરે તેવી શક્યતા વધુ હશે?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "પોતાના મનપસંદ ગીતની વિનંતી કરવા માટે ડીજેને કોણ વધુ હેરાન કરશે?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "ગીત ઓફ કીના ગીતો કોણ ગાશે તેવી શક્યતા વધુ હશે, પરંતુ ખાતરી સાથે?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "મેનૂ પર સૌથી મોંઘા પીણું મંગાવવાની અને અફસોસ કરવાની શક્યતા કોણ વધારે હશે?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "જો પડોશીઓને ઘોંઘાટ વિશે ફરિયાદ કરવામાં આવે તો તેઓને કોણ આમંત્રિત કરે તેવી શક્યતા વધુ હશે?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "પાર્ટીની રમતો (જેમ કે બીયર પૉંગ) કોણ ખૂબ ગંભીરતાથી લેશે?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "VIP ઍક્સેસ મેળવવા માટે બાઉન્સરો સાથે કોણ મિત્રતા કરે તેવી શક્યતા વધુ હશે?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "સ્વયંસ્ફુરિત કરાઓકે યુદ્ધ શરૂ કરવાની સંભાવના કોણ વધારે હશે?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "બોટલ ઓપનરનો ઉપયોગ કર્યા વિના બોટલ ખોલવાની શક્યતા કોણ વધારે છે?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "કોઈએ પૂછ્યું ન હોવા છતાં કોણ ભાષણ આપે તેવી શક્યતા વધુ હશે?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "બાથરૂમમાં સેલ્ફી લેવામાં એક કલાક કોણ વધારે વિતાવે છે?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "શરમજનક નૃત્ય પ્રદર્શન અને તેની ઉજવણી કરવા માટે કોણ વધુ સંભવ હશે?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "પાર્ટી પૂરી થયા પછી ભૂતપૂર્વ પાર્ટનરને કોને બોલાવવાની શક્યતા વધુ હશે?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "અજાણ્યા મહેમાનને આકસ્મિક રીતે નારાજ કરવાની શક્યતા કોની વધુ હશે?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "ગુડબાય કહ્યા વિના ગુપ્ત રીતે પાર્ટી છોડી દે તેવી શક્યતા કોણ વધારે હશે?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "મહેમાનો સાથે વાત કરવા કરતાં યજમાનના પાલતુ સાથે કોણ રમવાનું પસંદ કરશે?",
    "Wer würde eher spontan eine Reise buchen?" to "સહજતાથી ટ્રિપ બુક કરવાની શક્યતા કોણ વધારે હશે?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "રસોડામાં કલાકો સુધી ઊંડાણપૂર્વક વાતચીત કરવાની કોની શક્યતા વધુ હશે?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "આકસ્મિક રીતે બીજાનું પીણું કોણ પી જાય તેવી શક્યતા વધુ છે?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "આકસ્મિક રીતે મોંઘી ફૂલદાની અથવા નાજુક વસ્તુ પર કોણ પછાડે તેવી શક્યતા વધુ હશે?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "એક જટિલ કોકટેલને જાતે ભેળવવાનો પ્રયાસ કરે અને ખરાબ રીતે નિષ્ફળ જાય તેવી શક્યતા કોણ હશે?",
    "Wer würde eher zu spät kommen?" to "કોણ મોડું થવાની શક્યતા વધારે છે?",
    "Wer würde eher?" to "તેના બદલે કોણ કરશે?",
    "Wer übernimmt die tägliche Versorgung?" to "દૈનિક સંભાળની કાળજી કોણ લે છે?",
    "Werde so akzeptiert, wie du bist" to "તમે જેમ છો તેમ સ્વીકારો",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "શું આપણી પાસે બાળક/બાળકો માટે પૂરતો સમય હશે? ⏳",
    "Whirlpool" to "ગરમ ટબ",
    "White Chocolate" to "સફેદ ચોકલેટ",
    "Widgets" to "વિજેટ્સ",
    "Wie fühlst du dich am meisten geliebt?" to "તમને સૌથી વધુ પ્રેમ કેવો લાગે છે?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "આપણે વિવિધ આવક સાથે કેવી રીતે વ્યવહાર કરીએ છીએ?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "તમારા જીવનસાથી માટે તમારી સાથે સેક્સ શરૂ કરવાની શ્રેષ્ઠ રીત કઈ છે?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "તમારો પાર્ટનર તમારા માટે વધુ સારો પાર્ટનર કેવી રીતે બની શકે?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "પ્રસ્તાવના કેટલા સમય પછી તમે અન્ય લોકો સાથે ઉજવણી કરવા માંગો છો?",
    "Wie lange wollen wir dort mindestens bleiben?" to "આપણે ત્યાં ઓછામાં ઓછો કેટલો સમય રહેવા માંગીએ છીએ?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "ઈચ્છાઓ વિશે વાત કરવી તમારા માટે કેટલું સરળ છે?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "તમે અમારું ભવિષ્ય કેવું જોવા માંગો છો?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "ઘર પર તમારો સંપૂર્ણ રવિવાર કેવો દેખાય છે?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "સેક્સ દરમિયાન ગંદી વાતો વિશે તમને કેવું લાગે છે?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "આપણે વાસ્તવિક રીતે કેટલી ક્રેડિટ આપી શકીએ?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "આપણે કેટલો સમય વિતાવવા માંગીએ છીએ?",
    "Wie viel wollen wir insgesamt ausgeben?" to "આપણે કુલ કેટલો ખર્ચ કરવા માંગીએ છીએ?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "એકવાર બાળક આવી જાય પછી અમે અમારા સંબંધ માટે સમય કેવી રીતે શોધીશું?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "તે ક્ષણ કેદ કરવામાં આવે તે તમારા માટે કેટલું મહત્વનું છે?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "એપ્લિકેશન તમારા શોખ અથવા રુચિઓને પ્રતિબિંબિત કરે તે તમારા માટે કેટલું મહત્વનું છે?",
    "Wie würdest du sie/ihn nennen?" to "તમે તેને શું કહેશો?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "સેક્સની બહાર સ્નેહ દર્શાવવાની તમારી મનપસંદ રીત કઈ છે?",
    "Wildblumen" to "જંગલી ફૂલો",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "તમને છોકરી જોઈએ છે કે છોકરો? 👶",
    "Wintergarten" to "શિયાળુ બગીચો",
    "Winterhochzeit" to "શિયાળામાં લગ્ન",
    "Wir bestellen einfach beides" to "અમે ફક્ત બંનેનો ઓર્ડર આપીએ છીએ",
    "Wir brauchen ewig" to "તે આપણને કાયમ માટે લઈ જાય છે",
    "Wir einigen uns nie" to "અમે ક્યારેય સંમત થતા નથી",
    "Wir entscheiden es gemeinsam" to "અમે સાથે મળીને નક્કી કરીએ છીએ",
    "Wir treffen uns in der Mitte" to "અમે મધ્યમાં મળીએ છીએ",
    "Wir wechseln uns ab" to "અમે વળાંક લઈએ છીએ",
    "Wird stressig" to "તણાવપૂર્ણ બને છે",
    "Wobei lachst du am meisten?" to "તમને સૌથી વધુ શું હસવું આવે છે?",
    "Wofür sparen wir gemeinsam?" to "આપણે સાથે મળીને શું બચત કરીએ છીએ?",
    "Wohnzimmer" to "લિવિંગ રૂમ",
    "Woran erinnerst du dich am lebhaftesten?" to "તમને સૌથી વધુ આબેહૂબ રીતે શું યાદ છે?",
    "Worauf freust du dich bei uns am meisten?" to "તમે અમારી સાથે સૌથી વધુ શેની રાહ જોઈ રહ્યા છો?",
    "Worte/Komplimente" to "શબ્દો/પ્રશંસા",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "અમારા સંબંધોમાં તમને સૌથી વધુ શું ડર લાગે છે?",
    "Wünsche? z.B. günstig, draußen" to "શુભેચ્છાઓ? દા.ત. સસ્તું, બહાર",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "શું તમે વેકેશન (મુસાફરી સહિત) પર પ્રસ્તાવ મૂકવાનું પસંદ કરશો?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube સંગીત",
    "Zeichne für mich" to "મારા માટે દોરો",
    "Zeichne mich als Tier — welches wäre ich?" to "મને પ્રાણી તરીકે દોરો - હું કયો હોઈશ?",
    "Zeichne unser Gefühl zueinander als Symbol." to "આપણી લાગણીઓને એકબીજા પ્રત્યે પ્રતીક તરીકે દોરો.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "અમારા સપનાનું ઘર એક લીટીમાં દોરો. સૌથી આકર્ષક વસ્તુ શું છે?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "અમારી પ્રથમ તારીખ દોરો - ચિત્રમાં ચોક્કસપણે શું હોવું જોઈએ?",
    "Zeichnen" to "દોરો",
    "Zeit füreinander" to "એકબીજા માટે સમય",
    "Zeit, wenn das Baby schläft" to "સમય જ્યારે બાળક ઊંઘે છે",
    "Zelten gehen" to "કેમ્પિંગ જાઓ",
    "Zitrone" to "લીંબુ",
    "Zu Hause, gemütlich und privat" to "ઘરે, હૂંફાળું અને ખાનગી",
    "Zu einem Picknick gehen" to "પિકનિક પર જવાનું",
    "Zu einem ausgefallenen Abendessen gehen" to "ફેન્સી ડિનર પર જવું",
    "Zu zweit reisen" to "દંપતી તરીકે મુસાફરી કરો",
    "Zuhause & Alltag" to "ઘર અને રોજિંદા જીવન",
    "Zuhören" to "સાંભળો",
    "Zurück" to "પાછળ",
    "Zusammen seit" to "ત્યારથી એકસાથે",
    "Zusammen seit (TT.MM.JJJJ)" to "ત્યારથી સાથે (DD.MM.YYYY)",
    "Zusammenziehen" to "કરાર",
    "Zustimmen oder Ablehnen" to "સંમત કે નકારવું",
    "Zwei Kreise, die sich überschneiden" to "બે વર્તુળો જે ઓવરલેપ થાય છે",
    "Zwei Stühle davor" to "તેની સામે બે ખુરશીઓ",
    "Zärtlich sein" to "કોમળ બનો",
    "Öfter als ich zugebe" to "હું કબૂલ કરું છું તેના કરતાં વધુ વખત",
    "Über 100€/Monat" to "100€/મહિનાથી વધુ",
    "Über 2000 im Monat" to "મહિને 2000 થી વધુ",
    "Über mich selbst" to "મારા વિશે",
    "Übernehmen" to "ટેક",
    "Überraschend" to "આશ્ચર્યજનક",
    "Überraschung" to "આશ્ચર્ય",
    "Überspringen" to "છોડો",
    "Übertrieben und großartig" to "ટોચ પર અને અદ્ભુત",
    "✎ Tippe, um zu antworten" to "✎ જવાબ આપવા માટે ટૅપ કરો",
    "✨ GFK-Brücke" to "✨ GRP બ્રિજ",
)

internal fun localizeGujaratiDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_GUJARATI_CONTENT)
