package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_HAUSA_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "shekaru 1-5",
    "1000 - 1500 im Monat" to "1000 - 1500 kowane wata",
    "1000 bis 3000" to "1000 zuwa 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 kowane wata",
    "3000 bis 5000" to "3000 zuwa 5000",
    "5-10 Jahre" to "shekaru 5-10",
    "50-100€/Monat" to "50-100€/ wata",
    "Ab 100€" to "Daga 100 €",
    "Ab 500€" to "Daga 500 €",
    "Ab 50€" to "Daga 50 €",
    "Ab und zu" to "Yanzu da kuma",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Nawa muke magana kafin yin siya?",
    "Abbrechen" to "Soke",
    "Abenteuer" to "kasada",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Ayyuka",
    "Alle" to "Duka",
    "Alle Pakete" to "Duk fakiti",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Ka rasa duk abokanka sai babban abokinka",
    "Alle intimen Momente selbst initiieren" to "Ƙaddamar da duk lokacin m da kanka",
    "Alles davon" to "Duka shi",
    "Alles, was noch kommt" to "Duk abin da zai zo",
    "Alltagsroutine" to "Ayyukan yau da kullun",
    "Alltägliche Berührungen" to "Abubuwan da ke faruwa na yau da kullun",
    "Altbau mit Charme" to "Tsohon gini mai fara'a",
    "Am Strand" to "A bakin teku",
    "Am liebsten alles zusammen" to "Zai fi dacewa komai tare",
    "Am selben Tag mit Freunden/Familie" to "Rana guda tare da abokai/iyali",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Netherlands",
    "An das Gefühl" to "Na ji",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "A wurin taron jama'a mai yawan 'yan kallo",
    "An einen Geruch" to "Na kamshi",
    "An einen Song" to "Na waka",
    "An etwas, das ich gesagt habe" to "Game da wani abu na ce",
    "Analyse starten" to "Fara bincike",
    "Analysiere eure Muster..." to "Yi nazarin tsarin ku...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Yi nazarin amsoshinku & hirarrakin ku bisa ga Gottman da GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Abarba a kan pizza yana da daɗi.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Amsa da hoto",
    "Antwortähnlichkeit" to "Amsa kamanceceniya",
    "App-Sprache auswählen" to "Zaɓi harshen app",
    "Auf eine Bootsparty gehen" to "Je zuwa wurin bikin jirgin ruwa",
    "Aufmerksamkeit" to "Hankali",
    "Aufräumen und Projekte angehen" to "Tsaftace da magance ayyukan",
    "Aufwärmen" to "Dumama",
    "Aufwärmen: Einander kennenlernen" to "Dumu-dumu: sanin juna",
    "Aus dem Urlaub" to "Daga hutu",
    "Ausgefallener Name" to "Sunan kyan gani",
    "Ausschlafen und faulenzen" to "Barci kuma kuyi lallausan",
    "Ausschlafen und nichts tun" to "Barci kuma kada ku yi komai",
    "Aussehen" to "Fitowa",
    "Auto" to "Mota",
    "Außenkamin" to "Wurin murhu na waje",
    "BEANTWORTE" to "AMSA",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonesia",
    "Banane" to "Ayaba",
    "Beantwortet" to "An amsa",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Amsa tambayoyi a lokaci guda - ba za a iya ganin amsoshin ba har sai kun gama duka.",
    "Beantwortete Fragen" to "An amsa tambayoyin",
    "Bearbeiten" to "Gyara",
    "Bei Insider-Witzen" to "Domin barkwanci na ciki",
    "Bei Memes" to "A kan memes",
    "Bei einer spontanen Berührung" to "Lokacin da aka taɓa shi ba zato ba tsammani",
    "Beide" to "Duka",
    "Beide gleich" to "Duk iri ɗaya ne",
    "Beide zusammen" to "Duka tare",
    "Beide, aber wir tun so als ob nicht" to "Dukansu, amma ba mu yi kamar ba",
    "Beides" to "Duka",
    "Beides wäre schlimm" to "Dukansu za su zama mara kyau",
    "Beim Einschlafen nebeneinander" to "Har bacci ya kwashesu",
    "Beim Reden" to "Yayin magana",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Shahararrun wuraren yawon bude ido koyaushe abin takaici ne.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Bayyana rayuwar jima'i ta hanyar emoji.",
    "Besser kommunizieren" to "Sadarwa da kyau",
    "Bessere Lage" to "Mafi kyawun wuri",
    "Bestellen" to "Oda",
    "Besuchte Länder" to "Kasashen da aka ziyarta",
    "Besuchte Städte" to "Biranen da aka ziyarta",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Shin kun fi son wani tsari na almubazzaranci ko wani abu mara hankali?",
    "Beziehung" to "Dangantaka",
    "Bibliothek" to "ɗakin karatu",
    "Bin manchmal unsicher" to "Wani lokaci ba ni da tsaro",
    "Bist du ein Videospiel-Guru?" to "Shin ku guru wasan bidiyo ne?",
    "Blumenwiese" to "Furen makiyaya",
    "Bunte Blumenwiese" to "makiyayar furanni masu launi",
    "Burger" to "Jama'a",
    "Burger King" to "Burger King",
    "Chat" to "Taɗi",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Kullun kuki",
    "Dachgarten mit Lounge" to "Lambun rufi tare da falo",
    "Dachterrasse" to "Rufin terrace",
    "Das Wetter an dem Tag" to "Yanayin ranar",
    "Das erste Selfie" to "Selfie na farko",
    "Das meiste weiß ich" to "Na san mafi yawansa",
    "Das oder das?" to "Wannan ko wancan?",
    "Das tägliche Leben" to "Rayuwar yau da kullun",
    "Dass Zusagen gehalten werden" to "An cika alkawuran",
    "Dass alles meinen Stil hat" to "Cewa komai yana da salo na",
    "Dass ich alles erzählen kann" to "Cewa zan iya faɗi komai",
    "Dass ich mich nicht sorgen muss" to "Cewa bazan damu ba",
    "Dass wir ungestört sind" to "Cewa ba mu da damuwa",
    "Dein Name" to "Sunan ku",
    "Deine Antwort..." to "Amsan ku...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "An adana amsoshin ku. Da zaran Abokin Hulɗa ya gama kunshin, duka amsoshin za su kasance tare.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "An adana amsoshin ku. Da zarar \${profile.partnerName} ta gama kunshin, za a ga dukkan martanin tare.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Sanya dangantakarku ta zama abin ban sha'awa da kuma na kwatsam",
    "Deine Beziehung stabil und sicher machen" to "Sanya dangantakarku ta tabbata kuma amintacciya",
    "Deine eigene Antwort" to "Amsar ku",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Yana da kyau ku raba mafi zurfin sirrinku tare da abokin tarayya",
    "Deinen besten Freund verlieren" to "Rashin babban abokin ku",
    "Denke an dich" to "Ka yi tunanin kanka",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Kallon fim ɗaya sau biyu bata lokaci ne.",
    "Der Blick nach draußen" to "Duba waje",
    "Der Garten" to "Lambun",
    "Der Ort" to "Wuri",
    "Der Ring und die Geste" to "Zobe da ishara",
    "Der perfekte Heiratsantrag" to "Cikakken shawarar aure",
    "Derjenige sein, der umarmt wird" to "Ka zama wanda ake runguma",
    "Deutsch" to "Jamusanci",
    "Diamant" to "lu'u-lu'u",
    "Diamanten im Band" to "Diamonds a cikin band",
    "Die Distanz" to "Nisa",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Ku ciyar da hutu tare da dangin abokin tarayya",
    "Die Gemütlichkeit und Ruhe" to "Kwanciyar hankali da kwanciyar hankali",
    "Die Menschen, die darin wohnen" to "Mutanen da suke zaune a can",
    "Die Umgebung und Atmosphäre" to "Muhalli da yanayi",
    "Die Worte und Emotionen" to "Kalmomin da motsin rai",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Babban ƙalubalen nishaɗin nishaɗi",
    "Diejenige sein, die umarmt" to "Ka kasance mai runguma",
    "Direkt ansprechen" to "Adireshi kai tsaye",
    "Diskussion" to "Tattaunawa",
    "Diskutiere vor dem Kinderkriegen" to "Tattaunawa kafin haihuwa",
    "Diskutiert eure Antworten" to "Tattauna amsoshinku",
    "Disney" to "Disney",
    "Doch, schon mal" to "Ee, iya",
    "Draußen mit der Natur als Kulisse" to "A waje tare da yanayi azaman tushen baya",
    "Drei-Stein-Ring" to "Zoben dutse uku",
    "Du bist dran" to "Lokaci naku ne",
    "Du fehlst mir" to "Ina kewar ku",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubai, UAE",
    "Dunkles Design" to "Jigo mai duhu",
    "Durch Berührung" to "Ta hanyar taɓawa",
    "Durch Worte" to "Ta hanyar kalmomi",
    "Durch Zeit zu zweit" to "Ta hanyar lokaci tare",
    "Durch kleine Gesten" to "Ta hanyar ƙananan motsi",
    "Durchgeplant" to "An shirya",
    "ERGEBNISSE" to "SAKAMAKO",
    "Egal, Hauptsache gesund" to "Komai, babban abu yana da lafiya",
    "Ehepaar Leben" to "Rayuwar ma'aurata",
    "Eher knapp" to "Maimakon kusa",
    "Eher nicht" to "Maimakon haka",
    "Eher schwer" to "Maimakon wahala",
    "Eher schwierig" to "Maimakon wahala",
    "Eher zu" to "Maimakon haka kuma",
    "Eifersucht ist ein Zeichen von Liebe." to "Kishi alamar soyayya ce.",
    "Eigenes Gemüsebeet" to "Facin kayan lambu na kansa",
    "Ein Abenteuer in einer neuen Stadt" to "Kasada a cikin sabon birni",
    "Ein Anker" to "Anga",
    "Ein Balkon oder Garten" to "baranda ko lambu",
    "Ein Filmabend" to "Daren fim",
    "Ein Harmony-Meilenstein eurer Liebe." to "Matsayin jituwa a cikin ƙaunar ku.",
    "Ein Herz" to "Zuciya",
    "Ein Herz an der Tür" to "Zuciya a bakin kofa",
    "Ein Jahr lang eine Fernbeziehung führen" to "Yi dangantaka mai nisa har tsawon shekara guda",
    "Ein Kindheitsessen" to "Abincin yara",
    "Ein Live-Musik-Konzert besuchen" to "Halarci wasan kida kai tsaye",
    "Ein Museum besuchen" to "Ziyarci gidan kayan gargajiya",
    "Ein Spieleabend" to "Daren wasa",
    "Ein Spieleabend mit Freunden" to "Daren wasa tare da abokai",
    "Ein Urlaubsfoto" to "Hoton hutu",
    "Ein aktives Abenteuer" to "Kasada mai aiki",
    "Ein entspannender Spa-Tag" to "Ranar hutu mai annashuwa",
    "Ein ganz normaler Alltagstag" to "Gaba ɗaya na yau da kullun na yau da kullun",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Maraice mai jin daɗi a cikin gidan yayin da ake tsawa",
    "Ein gemütliches Date drinnen" to "Kwanan wata jin daɗi a cikin gida",
    "Ein lustiges Bild" to "Hoto mai ban dariya",
    "Ein paar Handyfotos reichen" to "Hotunan wayar salula kaɗan sun isa",
    "Ein paar Stunden" to "Sa'o'i kaɗan",
    "Ein paar kulturelle Anklänge sind okay" to "Bayanan al'adu kaɗan ba su da kyau",
    "Ein romantischer Abend" to "Maraice na soyayya",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Abincin dare na soyayya ta hasken kyandir",
    "Ein romantisches Bild" to "Hoton soyayya",
    "Ein romantisches Picknick an einem schönen Ort" to "Fikin soyayya a cikin kyakkyawan wuri",
    "Ein schwerer Moment, den wir geschafft haben" to "Lokaci mai wahala da muka gudanar",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Kyakkyawan kwanan wata a waje a ƙarƙashin hasken wata",
    "Ein ungewöhnliches Gericht" to "Abincin da ba a saba gani ba",
    "Ein zufälliger Schnappschuss" to "Hoton bazuwar",
    "Einander kennenlernen" to "Sanin juna",
    "Eine Autoreise" to "Tafiyar hanya",
    "Eine Brücke" to "Gada",
    "Eine Date-Nacht unter den Sternen" to "Daren dabino a karkashin taurari",
    "Eine Million Dollar gewinnen" to "Lashe dala miliyan",
    "Eine Million Dollar verdienen" to "Yi dala miliyan",
    "Eine Nacht in einem Club" to "Dare a cikin kulob",
    "Eine Schokoladenverkostung" to "Dandanan cakulan",
    "Eine Wanderung mit Panoramablick machen" to "Yi tafiya tare da ra'ayoyi masu ban mamaki",
    "Eine Weinverkostung" to "Dandanan giya",
    "Eine gemeinsame Reise" to "Tafiya tare",
    "Eine gemütliche Nacht zu Hause" to "Dare mai daɗi a gida",
    "Eine neue Sprache zu lernen ist einfach." to "Koyan sabon harshe abu ne mai sauƙi.",
    "Einen Film anschauen" to "Kalli fim",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Rashin magana da juna kwata-kwata har tsawon wata guda",
    "Einen Tanzkurs besuchen" to "Ɗauki darasi na rawa",
    "Einen Vergnügungspark erkunden" to "Bincika wurin shakatawa",
    "Einen Wellness-Tag" to "Ranar lafiya",
    "Einen sehr emotionalen Partner haben" to "Samun abokin tarayya mai motsin rai",
    "Einen sehr logischen Partner haben" to "Samun abokin tarayya mai ma'ana",
    "Einer zahlt alles" to "Mutum daya ke biyan komai",
    "Einfach mehr Alltag" to "Kawai ƙarin rayuwar yau da kullun",
    "Einfach nebeneinander sein" to "Ku kasance kusa da juna",
    "Einfach und intim" to "Sauƙi kuma m",
    "Einige Dinge für dich behalten" to "Ka ajiye wasu abubuwa a kanka",
    "Einmal" to "Sau ɗaya",
    "Eins, das nur wir kennen" to "Wanda mu kadai muka sani",
    "Englisch" to "Turanci",
    "Entspannte Hängematte" to "Hulba mai annashuwa",
    "Entspannung" to "shakatawa",
    "Erdbeere" to "Strawberry",
    "Erfolgreich" to "Nasara",
    "Ergebnisse" to "Sakamako",
    "Erst bei sehr großen Summen" to "Sai kawai akan manyan kudade",
    "Erst nur enge Freunde/Familie" to "Abokai/iyali na kurkusa ne kawai a farkon",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Yana ba ni haushi lokacin da abokin tarayya ya ɗauki lokaci mai yawa don amsa saƙonni.",
    "Essen & Genuss" to "Abinci & jin daɗi",
    "Essensvorlieben" to "Abubuwan zaɓin abinci",
    "Etwa eine Woche später, erst mal nur wir" to "Bayan mako guda, mu kawai a farkon",
    "Etwas Neues ausprobieren" to "Gwada sabon abu",
    "Etwas ganz anderes" to "Wani abu daban",
    "Etwas sehr Scharfes" to "Wani abu mai kaifi sosai",
    "Etwas, das ich selbst gern erfinde" to "Wani abu da nake so in ƙirƙira kaina",
    "Etwas, eine kleine Note wäre schön" to "Wani abu, ƙaramin rubutu zai yi kyau",
    "Familie" to "Iyali",
    "Familie/Freunde" to "Iyali/Abokai",
    "Familienmensch" to "Mutumin iyali",
    "Farbedelstein" to "Gemstone mai launi",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Tallace-tallacen TV wani lokaci suna da ban sha'awa don kallo.",
    "Fertig" to "Shirya",
    "Fertig!" to "Kammala!",
    "Feste Date-Nights" to "Kafaffen daren kwanan wata",
    "Feuerstelle" to "Ramin wuta",
    "Filigran & schlicht" to "Filigree & sauki",
    "Filme/Serien" to "Fina-finai/jeri",
    "Formuliere um..." to "Sake magana...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Maimaita daftarin ku ba tare da tashin hankali ba: kallo, ji, buƙata, buƙata.",
    "Frage hinzufügen" to "Ƙara tambaya",
    "Fragen & Spiele" to "Tambayoyi & wasanni",
    "Fragen für jede Gelegenheit" to "Tambayoyi ga kowane lokaci",
    "Freizeitpark" to "Wurin nishadi",
    "Freunde treffen" to "saduwa da abokai",
    "Freundschaften mit Ex-Partnern sind okay." to "Abota da exes ba su da kyau.",
    "Früh aufstehen" to "Don tashi da wuri",
    "Fußbodenheizung" to "Ƙarƙashin ƙasa dumama",
    "Führen wir getrennte oder gemeinsame Konten?" to "Shin muna da asusun daban ko haɗin gwiwa?",
    "Für dich empfohlen" to "An ba ku shawarar",
    "Für die Zukunft" to "Domin nan gaba",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Ba a sami madaidaicin tambayoyi ko wasanni don wannan binciken ba.",
    "Für immer" to "Har abada",
    "Fürsorglichkeit" to "Kulawa",
    "GFK-Brücke" to "GRP gada",
    "Galerie" to "Gallery",
    "Gar nicht, der Moment gehört uns" to "Ba komai ba, lokacin namu ne",
    "Gar nichts tun" to "Kada ku yi komai",
    "Geduld" to "Hakuri",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Ku tafi da sassafe don ganin fitowar rana",
    "Geht so" to "Yana tafiya kamar haka",
    "Geister existieren wirklich." to "Da gaske fatalwowi sun wanzu.",
    "Gelassenheit" to "Natsuwa",
    "Gelbgold" to "Ruwan zinare",
    "Geld & Finanzen" to "Kudi & Kudi",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Yi balaguron duniya tare, bincika sabbin al'adu da abinci",
    "Gemeinsam ein Lego bauen" to "Gina Lego tare",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Gwada sabon girke-girke tare a cikin kicin",
    "Gemeinsame Konten" to "Shared asusu",
    "Gemeinsame Nächte" to "Dare tare",
    "Gemeinsame Tage" to "Kwanaki tare",
    "Gemischt" to "Gauraye",
    "Gemüsebeet" to "Facin kayan lambu",
    "Gemütliche Feuerstelle" to "Wurin murhu mai daɗi",
    "Gesprächsanreger" to "Mafarin tattaunawa",
    "Getrennte Konten" to "Rarraba asusu",
    "Getrennte Urlaube tun einer Beziehung gut." to "Raba hutu yana da kyau ga dangantaka.",
    "Gewächshaus" to "Gidan lambu",
    "Glasfassade" to "Facade na gilashi",
    "Gleichgültigkeit" to "Rashin damuwa",
    "Glücklich und frei" to "Mai farin ciki da kyauta",
    "Gourmet Eis-Sorten" to "Gourmet ice cream iri",
    "Gravur innen" to "Zane ciki",
    "Grillplatz" to "Yankin Barbecue",
    "Groß & üppig" to "Babban & lush",
    "Große Familie" to "Babban iyali",
    "Große Feier" to "Babban biki",
    "Große Fenster" to "Manyan tagogi",
    "Große Fensterfront" to "Babban taga gaban",
    "Großer Außenpool" to "Babban tafkin waje",
    "Großer Garten" to "Babban lambu",
    "Großer Stein" to "Babban dutse",
    "Größere Küche" to "Babban kicin",
    "Gutes Essen" to "A ci abinci lafiya",
    "Habe ich" to "ina da",
    "Habe ich noch nie" to "Ban taba samun ba",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Shin kun gano wasu bambance-bambance masu ban mamaki? Yi magana game da dalilin da yasa kuke son wasu zaɓuɓɓukan mafi kyau!",
    "Haus am See" to "Gidan kusa da tafkin",
    "Haus/Wohnung" to "Gida/Apartment",
    "Hazelnut" to "Hazelnut",
    "Heimkino" to "Gidan wasan kwaikwayo",
    "Herzhaft" to "Madalla",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Babu komai a nan yanzu.\n Canza tace ko zaɓi wani batu na daban.",
    "Hilfe im Alltag" to "Taimako a rayuwar yau da kullun",
    "Himbeere" to "Rasberi",
    "Hinzufügen" to "Ƙara",
    "Hobbys" to "Abubuwan sha'awa",
    "Hochzeitssträuße" to "Bikin aure",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Girman Gidan Hogwarts: Ina Ku?",
    "Home" to "Gida",
    "Hot Tub" to "Wurin Wuta",
    "Humor" to "Abin dariya",
    "Hund" to "Kare",
    "Hängematte" to "Hammock",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Kuna son rubutaccen wasiƙa a matsayin wani ɓangare na shawarwarin?",
    "IKEA" to "IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Na fi son yawo na soyayya a wurin shakatawa da zuwa sinima.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Ban taba yin barci a sinima ba.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Ina jin daɗin gano sabbin abubuwan sha'awa ko ayyuka tare da abokina.",
    "Ich finde eine Alternative" to "Zan sami madadin",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Ina jin daɗin gwada sabbin gidajen cin abinci tare da abokiyar zama a maimakon koyaushe zuwa wurare iri ɗaya.",
    "Ich habe noch nie" to "Ban taba ba",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Ban taba jin tsoron abin nadi ba kuma na hau shi.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Ban taba sayen tikitin Fast Pass ba saboda rashin hakuri.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Ban taba soke shirin zama a gida da kallon shirin talabijin ba.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Ban taba jiran wasikata daga Hogwarts ba.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Ban taɓa cewa Slytherin ba a zahiri ba daidai ba ne.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Ban taba da'awar na tsufa sosai don fina-finan Disney ba (kuma na ji daɗin su a asirce).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Ban taba harbin wani da gangan ba tare da tanki mai shudi a cikin Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Ban taba kuka a fim din Disney ba.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Ban taba rufe idona ba yayin da nake kallon wani fim mai ban tsoro.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Ban taba mantawa da ajiye wasa ba kuma na rasa sa'o'i na ci gaba.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Ban taba barin dakin ba yayin wani abin kunya (cringe factor).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Ban taba yin wani abin ban dariya ba yayin da nake daukar hoton abin nadi.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Ban taba yin wasa da dare ba kuma na yi nadamar gajiyar da nake yi washegari.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Ban taba google din karshen fim din ba saboda na kasa jira.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Ban taba jin ina cikin shirin fim ba.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Ban taba tsallake gabatarwar jerin da na fi so ba.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Ban taba raba wani ta Netflix kalmar sirri.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Ban taɓa sauraron sautin sautin wasa yayin aiki ko karatu ba.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Ban taɓa zargin mai gudanarwa ba lokacin da na rasa.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Ban taɓa jefar da madannai ko mai sarrafawa cikin fushi ba.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Ban taɓa manta rigar rigar a cikin injin wanki na ƴan kwanaki ba.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Ban taɓa kashe kuɗi na gaske akan kayan kwalliya a wasa ba.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Ban taba tuka mota a wata kasa ba.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Ban taɓa ɗaukar waƙar Disney a cikin shawa ba.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Ban taba tuka motar lantarki ba.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Ban taɓa ɗaukar hoto tare da mascot na wurin shakatawa ba.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Ban taɓa sanya wa dabba suna bayan halin Hogwarts ba.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Ban taba jefa popcorn a gidan wasan kwaikwayo ba kuma har yanzu na ci.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Ban taɓa amfani da zance daga Master Yoda daga Star Wars a rayuwar yau da kullun ba.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Ban taba sayen abin tunawa da ya wuce kima ba a wurin shakatawa na jigo.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Ban taba ba da shawarar fim da wani ya sami muni ba.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Ban taba kallon Oscars kai tsaye da tsakar dare ba.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Ban taba soke jerin shirye-shirye ba saboda kakar wasan da ta gabata ta yi muni sosai.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Ban taɓa kallon ƙwazo ba a tsawon lokaci na jerin a rana ɗaya.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Ban taba doke shugaba ba a farkon gwaji na ji kamar allah.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Ban taba samun mai sanyaya mugu kamar jarumi ba.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Ban taba gane halin Labari na Toy a cikin kayan wasan yara na ba.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Ban taɓa yin wani hali a cikin RPG daidai da ni ba.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Ban taɓa cin churro a wurin shakatawar jigo ba.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Ban taɓa kallon fim ɗin Disney sau uku a jere ba.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Ban taɓa samun waƙa mai kayatarwa ta Disney tsawon mako guda ba.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Ban taba kallon fim ba saboda wani jarumi.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Ban taɓa sauraron sautin fim ɗin akan maimaitawa na awoyi ba.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Ban taba bayyana mai lalata fim ba kuma nan da nan na yi nadama.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Ban taɓa samun aboki da ke jin wani yare na asali ba.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Ban taɓa samun aboki da ya ƙaura zuwa wata ƙasa ba.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Ban taɓa yin gudun fanfalaki na fim ɗin Harry Potter a Kirsimeti ba.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Ban taɓa kallon fim ɗin Marvel ba har zuwa ƙarshe saboda yanayin da aka yi bayan samun kuɗi.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Ban taɓa jin haushin wani NPC da gangan ba (Halin da ba ɗan wasa ba).",
    "Ich habe noch nie einen Nachtzug genommen." to "Ban taba hawan jirgin kasa na dare ba.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Ban taɓa yin gwajin kan layi don gano gidana na Hogwarts ba.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Ban taɓa goge wani rubutu na kafofin watsa labarun ba saboda bai sami isassun so ba.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Ban taɓa kiran rana ɗaya a wurin shakatawar jigo mafi kyawun ranar shekara ba.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Ban taɓa ziyartar wurin shakatawa na jigo ba kuma na zauna a can daga safiya zuwa dare.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Ban taɓa barin Transformers ko abin hawa mai ban sha'awa gaba ɗaya ba.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Ban taɓa yin fushi na bar wasan ba.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Ban taɓa karanta ɗayan manyan littattafan Harry Potter ba.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Ban taɓa jin daɗin halin da na fi so a cikin jerin abubuwa ba.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Ban taba mafarkin wasa Quidditch ba.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Ban taba yin google a asirce yadda ake warware matsala ba.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Ban taba begen asirce na dabba na zai iya magana kamar yadda suke yi a Disney ba.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Ban taba cire tsanin tafkin a Sims ba.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Ban taɓa yin hasarar ra'ayi na ba a cikin hawan na'urar kwaikwayo na 3D.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Ban taba taka leda a kungiyar wasanni ta jami'a ba.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Ban taba jiran layi sama da awanni biyu don jan hankali daya ba.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Ban taba jike kayana masu kima a kan tukin ruwa ba.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Ban taba yin gardama da wani abokina a kan wane gida ne ya fi kyau ba.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Ban taba yin kamar ina da ikon sihiri kamar Elsa ba.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Ban taba yin dariya ba har na rasa wani muhimmin lamari a fim.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Ban taba jin adrenaline da yawa ba wanda nan da nan na so in sake hawa.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Ban taɓa ƙoƙarin yin waƙa da dabbobi kamar Snow White ba.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Ban taba mafarkin tafiya zuwa Disneyland ba.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Ban taba mafarkin hawan Jurassic Park ruwa ba.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Ban taba yin kururuwa da babbar murya ba saboda tsallen da aka yi a wasa.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Ban taba yin kuka ba a kan wasan karshe na wani shirin talabijin.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Ban taba... soke kwanan wata don zama a gida ba.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Ban taba ... sake maimaita sako sau 10 ba.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Ban taba... a asirce na kalli wayar abokina ba.",
    "Ich habe noch nie!" to "Ban taba ba!",
    "Ich habe!" to "Ina da!",
    "Ich lache viel mit meinem Partner." to "Ina dariya sosai tare da abokin tarayya.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Ina son sanin abubuwan sha'awa da sha'awar abokina.",
    "Ich liebe es" to "Ina son shi",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Ina son kallon fina-finai tare da abokina wanda ba mu taɓa gani ba.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Ina son raba waƙar da na fi so tare da abokin tarayya na.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Ban taɓa gudu don kama jirgin da ke haɗi ba.",
    "Ich plane gerne Dates mit meinem Partner." to "Ina son tsara kwanan wata tare da abokin tarayya.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Na ba da fifiko wajen ciyar da lokaci tare da abokiyar zama ko da lokacin da nake aiki.",
    "Ich schreibe meinem Partner jeden Tag." to "Ina aika wa abokin tarayya wasiƙa kowace rana.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Ina son raba memes da barkwanci tare da abokina.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Ina so in raba duk bayanan rana ta tare da abokin tarayya na.",
    "Ich würde es nie tun" to "Ba zan taɓa yi ba",
    "Ich übe noch" to "Har yanzu ina aiki",
    "Ideen generieren" to "Ƙirƙirar ra'ayoyi",
    "Im Haushalt helfen" to "Taimako a kusa da gidan",
    "In Chat einfügen" to "Ƙara zuwa taɗi",
    "In Stille nebeneinander" to "A shiru kusa da juna",
    "In den Bergen" to "A cikin duwatsu",
    "In eine Bar gehen" to "Je zuwa mashaya",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Je zuwa mashaya bakin ruwa don kallon faɗuwar rana",
    "In einem feinen Restaurant essen gehen" to "Cin abinci a cikin gidan abinci mai kyau",
    "In einen Coffeeshop gehen" to "Je zuwa kantin kofi",
    "In einer Beziehung sollte man alles voneinander wissen." to "A cikin dangantaka ya kamata ku san komai game da juna.",
    "Infinity-Pool" to "Infinity pool",
    "Innenpool" to "Wuraren cikin gida",
    "Intelligenz" to "hankali",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Samun lokacin kusanci ne kawai lokacin da abokin tarayya ya fara su",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Lambar gayyata: HRM-8731 · komai a buɗe",
    "Island" to "Iceland",
    "Ist okay für mich" to "Ba komai a wurina",
    "Ist schon perfekt" to "Daidai ne",
    "Ja, Traditionen einbinden" to "Ee, haɗa hadisai",
    "Ja, absolut" to "Ee, kwata-kwata",
    "Ja, etwas zum Lesen und Aufbewahren" to "Ee, wani abu don karantawa da adanawa",
    "Ja, genug" to "Ee, ya isa",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Ee, a cikin birni mai ban sha'awa ko jan hankali",
    "Ja, in- und auswendig" to "Ee, ciki da waje",
    "Ja, komplett überraschend" to "E, gaba daya abin mamaki",
    "Ja, perfekt" to "Ee, cikakke",
    "Ja, sie gehören zur Familie!" to "Ee, dangi ne!",
    "Ja, sofort teilen" to "Ee, raba nan da nan",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Ee, za mu tabbatar da cewa lokacin iyali shine fifiko.",
    "Jacuzzi" to "Jacuzzi",
    "Jahr zusammen 🎉" to "shekara tare 🎉",
    "Jahre zusammen 🎉" to "Shekaru tare 🎉",
    "Jeder zahlt 50%" to "Kowa yana biya 50%",
    "Junge" to "Yaro",
    "Kamin" to "Wuta",
    "Karriere & Erfolg" to "Sana'a & Nasara",
    "Kategorien" to "Rukuni",
    "Katze" to "Cat",
    "Keine Musik" to "Babu kiɗa",
    "Keine Party nötig, privat halten" to "Babu buƙatar liyafa, kiyaye ta cikin sirri",
    "Keine Privatsphäre" to "Babu keɓantawa",
    "Keine Treffer gefunden" to "Ba a sami daidaito ba",
    "Keiner" to "Babu",
    "Keiner von uns" to "Babu ɗayanmu",
    "Kennst du die Essensvorlieben deines Partners?" to "Shin kun san abubuwan da abokin tarayya ke so?",
    "Kino" to "Cinema",
    "Kirchlich" to "Malami",
    "Klassisch Solitär" to "Classic Solitaire",
    "Klassisch gebunden" to "An ɗaure ta na gargajiya",
    "Klein & zart" to "Karami & m",
    "Kleine Geschenke" to "Ƙananan kyaututtuka",
    "Kleine Runde" to "Karamin rukuni",
    "Kochen und Freunde einladen" to "Dafa abinci da gayyatar abokai",
    "Kochkurs" to "Ajin dafa abinci",
    "Kommt auf den Tag an" to "Ya dogara da ranar",
    "Kommt darauf an" to "Ya dogara",
    "Kommt drauf an" to "Ya dogara",
    "Kommt mit" to "Ku zo tare da ni",
    "Konzert" to "Concert",
    "Kräftige Farben" to "Launuka masu ƙarfi",
    "Kräuterbeet" to "Ganye gado",
    "Kultur & Sehenswürdigkeiten" to "Al'adu & Abubuwan gani",
    "Kuscheln" to "Tausayi",
    "Kuss senden" to "Aika sumbata",
    "Körperliche Annäherung" to "Hanyar jiki",
    "Körperliche Nähe" to "kusancin jiki",
    "Küche" to "Kitchen",
    "Land" to "Ƙasa",
    "Landhaus" to "Gidan gida",
    "Landhausstil" to "Salon gidan kasa",
    "Lange wach bleiben" to "Tsaya a makara",
    "Lappland" to "Lapland",
    "Lappland, Finnland" to "Lapland, Finland",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Bari abokin tarayya ya ƙarfafa ku don zama mafi kyawun ku",
    "Lehne ab" to "Karya",
    "Leichtigkeit" to "sauki",
    "Leidenschaft" to "Sha'awa",
    "Liebe im Gleichgewicht" to "Soyayya cikin daidaito",
    "Liebe sie, macht mehr Spaß" to "Ƙaunar su, ƙarin jin daɗi",
    "Lieber durchgeplant oder spontan?" to "Shin za ku gwammace ku shirya shi ko kuma ba zato ba tsammani?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Shin za ku gwammace ku yi shiru maraice na biyu ko tare da mutane?",
    "Lieber nicht" to "Maimakon haka",
    "Lieber vorher grob absprechen" to "Yana da kyau a tattauna a kai a kai",
    "Lokal einkaufen" to "Siyayya a gida",
    "London" to "London",
    "London, England" to "London, Ingila",
    "Lügen" to "Karya",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Kun fi son tsari na jama'a ko na sirri?",
    "Malediven" to "Maldives",
    "Man sollte nie streitend einschlafen." to "Kada ku yi barci kuna jayayya.",
    "Mango Sorbet" to "Mangoro sorbet",
    "Markant & breit" to "Bugawa & fadi",
    "Marken & Alltag" to "Brands & rayuwar yau da kullun",
    "McDonald’s" to "McDonald ta",
    "Mediterraner Innenhof" to "farfajiyar Bahar Rum",
    "Mehr Unterstützung" to "Ƙarin tallafi",
    "Mehr gemeinsame Zeit" to "Karin lokaci tare",
    "Mehr zuhören" to "A kara saurare",
    "Mehrgenerationenhaus" to "Multi-generational gidan",
    "Mein Arbeitsplatz" to "Wurin aiki na",
    "Mein Partner" to "Abokina na",
    "Mich überraschen" to "Ka bani mamaki",
    "Minimalistisches Interieur" to "Ƙananan ciki",
    "Missverständnisse" to "Rashin fahimta",
    "Mit Familie und engen Freunden" to "Tare da dangi da abokai na kud da kud",
    "Mit Kompromissen" to "Tare da sasantawa",
    "Mitgefühl" to "Tausayi",
    "Mittelweg mit besonderen Details" to "Tsakiyar ƙasa tare da cikakkun bayanai na musamman",
    "Modern geometrisch" to "Geometric na zamani",
    "Moderne Grillstation" to "Tashar gasa ta zamani",
    "Moderner Name" to "Sunan zamani",
    "Moderner Solitär" to "Solitaire na zamani",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "Ɗauki lokacin",
    "Momente" to "lokacin",
    "Monaco" to "Monaco",
    "Moralische Werte" to "Ƙimar ɗabi'a",
    "Museum" to "gidan kayan gargajiya",
    "Musik" to "Kiɗa",
    "Mut" to "karfin hali",
    "Mädchen" to "Yarinya",
    "Möbelhaus" to "kantin kayan daki",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Kuna so ku bar tambayoyin? Ci gaban ku na baya ya kasance a ajiye.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Kuna so a saka dabbobi a cikin aikace-aikacen?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Kuna so a raba lokacin nan take akan kafofin watsa labarun?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Wataƙila muna buƙatar yin tanadi",
    "Müssen es planen" to "Bukatar tsara shi",
    "Müssen sparen" to "Bukatar adanawa",
    "Nachricht an" to "Sako",
    "Name Partnerin" to "Sunan abokin tarayya",
    "Namen und Startdatum eurer Beziehung." to "Sunaye da ranar fara dangantakar ku.",
    "Natursteinfassade" to "Facade na dutse na halitta",
    "Naturteich" to "Tafki na halitta",
    "Nein, einfach halten" to "A'a, riƙe shi kawai",
    "Nein, erstmal privat halten" to "A'a, kiyaye sirrin yanzu",
    "Nein, lieber vor Ort" to "A'a, mafi kyau akan rukunin yanar gizon",
    "Nein, modern halten" to "A'a, ci gaba da zamani",
    "Nein, nur wir" to "A'a, mu kawai",
    "Nein, zu ablenkend" to "A'a, kuma mai ban sha'awa",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Sabon gini tare da gida mai wayo",
    "Neubau mit Technik" to "Sabon gini tare da fasaha",
    "Neue Liebe, neue Erfahrungen" to "Sabuwar soyayya, sabbin abubuwa",
    "Neues Hobby" to "Sabuwar sha'awa",
    "Neues Spiel" to "Sabon wasa",
    "Neugier" to "son sani",
    "New York" to "New York",
    "New York, USA" to "New York, Amurka",
    "Nicht mein Fall" to "Ba lamarina ba",
    "Nicht nötig, lieber klassisch bleiben" to "Ba lallai ba ne, yana da kyau a zauna classic",
    "Nichts — es passt so" to "Babu wani abu - ya dace da haka",
    "Nie wieder Burger" to "Kar a sake burgewa",
    "Nie wieder Pizza" to "Kar a sake yin pizza",
    "Niemand" to "Babu kowa",
    "Niemand ohne Plan" to "Babu wanda ba tare da tsari ba",
    "Nike" to "Nike",
    "Nizza" to "Yayi kyau",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Ba wani lokaci tukuna.\n Ɗauki gogewar ku ta farko 💞",
    "Nur bei wichtigen Themen" to "Sai kawai don mahimman batutuwa",
    "Nur wir beide" to "Mu biyu kawai",
    "Nähe & Intimität" to "Kusanci & Zumunci",
    "Obstgarten" to "Orchard",
    "Oder" to "Ko",
    "Offene Küche" to "Bude kicin",
    "Offene Wohnküche" to "Bude kicin/dakin falo",
    "Ohne Stein" to "Ba tare da dutse ba",
    "Open End" to "Buɗe ƙarewa",
    "Outdoor-Küche" to "Wurin dafa abinci na waje",
    "Outdoor-Sofa" to "Sofa na waje",
    "Outdoor-Whirlpool" to "Guguwa na waje",
    "Ovaler Diamant" to "Lu'u-lu'u mai tsayi",
    "Paar" to "Biyu",
    "Paar-Statistiken" to "Ƙididdigar ma'aurata",
    "Paris" to "Paris",
    "Paris, Frankreich" to "Paris, Faransa",
    "Partner" to "abokin tarayya",
    "Partner-Simulator" to "Abokin na'urar kwaikwayo",
    "Partnerin" to "abokin tarayya",
    "Party Edition" to "Buga na jam'iyya",
    "Party Edition II" to "Buga na Jam'iyya II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Shin dabba ma ta dace da rayuwarmu ta yau da kullun?",
    "Pasta" to "taliya",
    "Pastell" to "pastel",
    "Penthouse mit Ausblick" to "Penthouse tare da kallo",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pergola tare da falo",
    "Pfingstrosen" to "Peonies",
    "Pinguin" to "penguin",
    "Pistazie" to "pistachio",
    "Pizza" to "pizza",
    "Pizzaofen" to "Pizza tanda",
    "Platin" to "platinum",
    "PlayStation" to "PlayStation",
    "Pool" to "tafkin",
    "Pop" to "pop",
    "Prasselnder Kamin" to "Wurin murhu mai ruri",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Gimbiya, 'yan fashin teku da ƙura mai ƙura: Disney Quiz",
    "Privater Innenhof" to "tsakar gida mai zaman kansa",
    "Profil" to "bayanin martaba",
    "Profil bearbeiten" to "Gyara bayanin martaba",
    "Prozentual nach Einkommen" to "Kashi bisa ga kudin shiga",
    "Quiz verlassen" to "Bar tambayoyin",
    "Quiz verlassen?" to "A daina tambaya?",
    "Rausgehen in die Natur" to "Fita cikin yanayi",
    "Reden vor ..." to "Yana magana da...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Tsara kwanan wata ko lokaci tare",
    "Reisen" to "Tafiya",
    "Reiseziele" to "Wuraren balaguro",
    "Respektlosigkeit" to "Rashin girmamawa",
    "Restaurant" to "Gidan cin abinci",
    "RnB / Soul" to "RnB / Soul",
    "Rock" to "Dutse",
    "Rom" to "Rome",
    "Rom, Italien" to "Rome, Italiya",
    "Romantik" to "soyayya",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Karimcin soyayya kamar saƙonni, bayanin kula ko kyaututtuka suna sa ni farin ciki.",
    "Romantische Stimmung" to "Yanayin soyayya",
    "Roségold" to "Zinare mai fure",
    "Ruhig zu zweit" to "Shuru na biyu",
    "Runder Diamant" to "Lu'u-lu'u zagaye",
    "Salted Caramel" to "Caramel gishiri",
    "Sammle Ideen..." to "Tattara dabaru...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Girka",
    "Saphir" to "Sapphire",
    "Saunahaus" to "Sauna House",
    "Schickes Restaurant oder Hotel" to "Gidan cin abinci ko otal",
    "Schlafzimmer" to "Bedroom",
    "Schließen" to "Rufe",
    "Schmal & zart" to "Slim & m",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Hoto daga labarin soyayya",
    "Schokolade" to "Chocolate",
    "Schreib frei, was dir wirklich dazu einfällt." to "Rubuta abin da gaske ya zo a zuciya kyauta.",
    "Schreibe deine eigene Antwort" to "Rubuta amsar ku",
    "Sehr gerne" to "Da murna sosai",
    "Sehr leicht" to "Haske sosai",
    "Sehr wichtig — Fotos und Video" to "Mahimmanci sosai - hotuna da bidiyo",
    "Sehr wichtig, es sollte persönlich sein" to "Yana da mahimmanci, ya kamata ya zama na sirri",
    "Selbst kochen" to "Dafa kanka",
    "Senden" to "Aika",
    "Separate Küche" to "Wurin kicin",
    "Serie schauen" to "Kalli jerin",
    "Serienmarathon auf dem Sofa" to "Series marathon akan sofa",
    "Sex & Liebe" to "Jima'i & Soyayya",
    "Seychellen" to "Seychelles",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Shin za mu iya biyan duk farashi na yaro ɗaya/yaya da yawa? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Shin shawarar ta zama abin mamaki?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Shin ya kamata aikace-aikacen ya ƙunshi abubuwan al'adu ko na gargajiya?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Shin ya kamata aikace-aikacen ya ƙunshi abubuwan al'adu ko na gargajiya?",
    "Sommerhochzeit" to "Auren bazara",
    "Sonnige Dachterrasse" to "Filin rufin rana",
    "Sowohl als auch" to "Duka kuma",
    "Spazieren" to "Yi tafiya",
    "Spaß & Abenteuer" to "Nishaɗi & Kasada",
    "Speichern" to "Ajiye",
    "Spiel bearbeiten" to "Gyara wasan",
    "Spielbereich für Kinder" to "Wurin wasa don yara",
    "Spiele" to "wasanni",
    "Spiele spielen und Spaß haben" to "Yi wasanni kuma ku more",
    "Spontan" to "Kwatsam",
    "Sportplatz" to "Filin wasanni",
    "Spotify" to "Spotify",
    "Sprache" to "Harshe",
    "Stadt" to "Garin",
    "Stadt oder Land — was ist uns wichtiger?" to "Birni ko ƙasa - menene ya fi mahimmanci a gare mu?",
    "Stadtvilla" to "Birnin villa",
    "Standesamt & Party" to "Ofishin rajista & jam'iyya",
    "Statement-Ring" to "zoben sanarwa",
    "Stilvolles Outdoor-Sofa" to "Sofa mai salo na waje",
    "Stimme voll zu" to "Gaba ɗaya yarda",
    "Stimmt" to "Gaskiya",
    "Stimmt nicht" to "Ba gaskiya bane",
    "Stimmt, noch nie" to "Haka ne, ba",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Ranar bakin teku",
    "Streit über Haushalt" to "Rikici kan gida",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "Ko da yaushe",
    "Suche schließen" to "Rufe bincike",
    "Suche zurücksetzen" to "Sake saita bincike",
    "Suche öffnen" to "Bude bincike",
    "Suchergebnisse" to "Sakamakon bincike",
    "Sushi" to "Sushi",
    "Süß" to "Mai dadi",
    "Tage zusammen 💞" to "kwana tare 💞",
    "Tauche ins Unterbewusstsein" to "Nutse cikin abin da ba a sani ba",
    "Teile alle deine Hobbys mit deinem Partner" to "Raba duk abubuwan sha'awa ga abokin tarayya",
    "Teils teils" to "Wani bangare",
    "Testen" to "Gwaji",
    "Themen" to "Batutuwa",
    "Tiefe Gespräche" to "Tattaunawa masu zurfi",
    "Tiefgründige Gespräche führen" to "Yi tattaunawa mai zurfi",
    "Tierpension" to "Gidan kwana na dabbobi",
    "Tiny House" to "Karamin Gida",
    "Tippen zum Auswählen & Scrollen" to "Taɓa don zaɓar & gungurawa",
    "Tippen zum Zuklappen" to "Matsa don rugujewa",
    "Titel" to "Take",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Take, Categories, Take, Tags, Tambayoyi...",
    "Tokyo, Japan" to "Tokyo, Japan",
    "Traditioneller Name" to "Sunan gargajiya",
    "Traumhaus Außenbereich" to "Gidan mafarkin waje",
    "Traumhochzeit" to "Mafarkin aure",
    "Treffer" to "Buga",
    "Tägliche Aktivität" to "Ayyukan yau da kullun",
    "Umformulieren" to "Sake magana",
    "Unbeantwortet" to "Ba a amsa ba",
    "Unbeliebte Meinungen" to "Ra'ayoyin da ba sa so",
    "Universal Studios Genie oder Neuling?" to "Hazaka na Studios na Duniya ko sabon?",
    "Uns auseinanderzuleben" to "Don girma dabam",
    "Unser Intimleben" to "Rayuwar mu ta kusa",
    "Unser Traumhaus" to "Gidan mafarkinmu",
    "Unser erstes Treffen" to "Haɗuwarmu ta farko",
    "Unsere Gesichter" to "Fuskokin mu",
    "Unsere eigenen Träume" to "Burin mu",
    "Unsere nächste Reise" to "Tafiyarmu ta gaba",
    "Unter 1000" to "Kasa da 1000",
    "Unter 1000 im Monat" to "Kasa da 1000 a wata",
    "Unter 50€/Monat" to "Kasa da 50 € / watan",
    "Unter Leuten" to "Daga cikin mutane",
    "Untreue" to "kafirci",
    "Urlaub" to "Hutu",
    "Vanille" to "Vanilla",
    "Venedig" to "Venice",
    "Venedig, Italien" to "Venice, Italiya",
    "Verbinde dich mit" to "Haɗa tare da",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Haɗa zuwa \${profile.partnerName} don ganin amsar",
    "Verbindung" to "haɗi",
    "Verbringe die Feiertage mit deiner Familie" to "Ku ciyar da hutu tare da dangin ku",
    "Verlobungsringe" to "zoben haɗin gwiwa",
    "Vertrautheit" to "Sani",
    "Viel getrennt" to "Yawan rabuwa",
    "Vielleicht ein oder zwei" to "Wataƙila ɗaya ko biyu",
    "Vielleicht, aber mündlich reicht" to "Wataƙila, amma da baki ya isa",
    "Vielleicht, wenn es machbar ist" to "Wataƙila, idan zai yiwu",
    "Vielleicht, wenn es passt" to "Wataƙila, idan ya dace",
    "Vintage Art déco" to "Vintage Art Deco",
    "Vintage verspielt" to "Vintage mai wasa",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Abokin aikin ku yana gabatar da sabbin abubuwan sha'awa",
    "Vor dem Kauf eines Hauses besprechen" to "Tattaunawa kafin siyan gida",
    "Vor der Anschaffung eines Haustiers besprechen" to "Tattaunawa kafin siyan dabbar dabba",
    "Vor der gemeinsamen Reise besprechen" to "Tattaunawa kafin tafiya tare",
    "Vor nichts" to "Babu komai",
    "Vorort" to "Unguwa",
    "Walnuss" to "gyada",
    "Wandern" to "Tafiya",
    "Wann fühlst du dich mir am nächsten?" to "Yaushe kuka fi kusanci da ni?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Yaushe kuka fi kusanci da ni a jiki?",
    "Was bedeutet Vertrauen für dich konkret?" to "Menene amana ke nufi a gare ku musamman?",
    "Was entspannt dich mehr?" to "Me ya kara kwantar maka da hankali?",
    "Was fehlt dir über die Distanz am meisten?" to "Me kuka fi rasa game da nisa?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Me kuka fi so game da gidan ku?",
    "Was hast du von deinem Partner gelernt?" to "Menene ka koya daga abokin tarayya?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Me kuke tunani game da kallon abubuwan batsa tare?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Me kuke tunani game da kayan kwalliya (misali alamu, balloons, da sauransu)?",
    "Was ist das Wichtigste beim Antrag?" to "Menene abu mafi mahimmanci lokacin nema?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Menene mafi mahimmancin abu da kuke nema a cikin saduwar jima'i?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Wane hoto kuka fi so na mu? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Menene babban tsoronku game da zama tare?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Menene abincin da kuke so amma abokin tarayya ba zai iya fahimta ba?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Menene cikakken dillali a gare ku?",
    "Was ist für jeden von uns das absolute Highlight?" to "Menene cikakken haske ga kowannenmu?",
    "Was ist passiert?" to "Me ya faru?",
    "Was macht einen Moment für dich romantisch?" to "Me ke sa lokacin soyayya a gare ku?",
    "Was magst du an deinem Partner am liebsten?" to "Menene kuka fi so game da abokin tarayya?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Me kuka fi so: tashi da wuri ko kuma yin makara?",
    "Was magst du lieber?" to "Me kuka fi so?",
    "Was möchtest du eigentlich sagen?" to "Me kuke so ku ce a zahiri?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Me kuke so abokin tarayya ya yawaita yi?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Me ke faruwa da dabbar idan muka yi tafiya?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Menene zai faru da yaranmu sa’ad da ya girma?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Menene bai kamata mu manta a matsayin iyaye ba?",
    "Was war dein schönster Moment mit mir bisher?" to "Menene mafi kyawun lokacinku tare da ni zuwa yanzu?",
    "Was wir gegessen haben" to "Abin da muka ci",
    "Was wollt ihr nie vergessen?" to "Me ba za ku taɓa mantawa da shi ba?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Me zai fi muku muni: ba za a sake yin pizza ba ko kuma ba za a sake burgewa ba?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Me kuke so ku yi a rana tare?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Me za ku canza nan da nan idan kudi ba batun bane?",
    "Weiter" to "Na gaba",
    "Weiter spielen" to "Ci gaba da wasa",
    "Weiß ich noch nicht" to "Ban sani ba tukuna",
    "Weiße Rosen" to "Farin wardi",
    "Weißgold" to "Farar gwal",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Wane inganci ya kamata yaranmu ya samu daga gare mu?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Wane yanayi kuke so don shawara?",
    "Welcher Raum sagt am meisten über dich aus?" to "Wane daki ne ya fi bayanin ku?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Wane kasafin kudi muke tsarawa don abinci da likitan dabbobi?",
    "Welches Lied macht dich an? 🥵" to "Wace waka ce ke kunna ku? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Wane hoto aka raba ku kuka fi so?",
    "Wellnessbad" to "Wankan lafiya",
    "Wenn es schwierig ist" to "Lokacin da abubuwa suka yi wahala",
    "Wenn ich müde bin" to "Lokacin da na gaji",
    "Wenn wir uns lange umarmen" to "Idan muka dade da runguma",
    "Wenn wir zusammen lachen" to "Idan muna dariya tare",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Wanene ya fi saurin yanke shawarar abin da zai yi oda?",
    "Wer findet die besten Restaurants?" to "Wanene ya sami mafi kyawun gidajen abinci?",
    "Wer gibt mehr Herzlichkeit?" to "Wanene ke ba da ƙarin dumi?",
    "Wer hat den besseren Musikgeschmack?" to "Wanene ya fi ɗanɗano a cikin kiɗa?",
    "Wer hängt mehr an seinen Eltern?" to "Wa ya fi son iyayensu?",
    "Wer ist besser organisiert?" to "Wa ya fi tsari?",
    "Wer ist der Beste bei der Filmauswahl?" to "Wanene ya fi dacewa a zabar fina-finai?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Wanene ya fi dacewa a tsara kwanakin soyayya?",
    "Wer ist der beste Tänzer?" to "Wanene ya fi kowa rawa?",
    "Wer ist romantischer?" to "Wanene ya fi soyayya?",
    "Wer kocht besser?" to "Wa ya fi girki?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Wanene ke kula da gyarawa da kulawa?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Wanene yake lura da sauri lokacin da ɗayan ba ya jin daɗi?",
    "Wer sucht am Ende wirklich den Film aus?" to "Wanene ya zaɓi fim ɗin a ƙarshe?",
    "Wer vergisst eher einen Jahrestag?" to "Wanene ya fi iya mantawa da ranar tunawa?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Washe gari waye zai fi manta sunan nasu?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Waye yafi iya samun bidiyon washegarin da basu sani ba?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Wa zai fi kwana a kan gadon baƙo?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Wanene zai iya yin barci a wurin biki kuma ya tashi tare da Sharpie a fuskar su?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Wanene zai fi iya zamewa a filin rawa amma ya sa ya zama kamar motsi mai sanyi?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Wanene ya fi dacewa ya mallaki jerin waƙoƙin Spotify a gidan liyafa?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Wanene zai fi dacewa ya ba da odar pizza ga kowa da kowa a wurin biki kuma ya ci da kansa?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Wane ne ya fi fara barci a wurin biki?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Wanene zai iya fara tsaftacewa ba zato ba tsammani a wurin biki?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Wanene zai fi dacewa ya yi iƙirarin cewa yana da hankali sosai idan akasin haka?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Wane ne ya fi dacewa ya ba da farko a cikin jayayya?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Wanene zai fi yin yaudara a wasan sha?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Wanene zai fi dacewa ya kai hari gidan abinci kuma ya kai abinci a asirce?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Wanene zai fi iya sanya hoton maraice mafi kunya a cikin labarinsu?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Wanene zai fi jin haushin DJ don neman waƙar da suka fi so?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Wanene zai fi iya rera waƙoƙin zuwa maɓalli na kashe waƙa, amma tare da tabbaci?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Wanene zai fi dacewa ya ba da odar abin sha mafi tsada akan menu kuma yayi nadama?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Wane ne zai fi gayyatar makwabta idan sun koka da hayaniyar?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Wanene zai fi dacewa ya ɗauki wasannin liyafa (kamar giya pong) hanya da mahimmanci?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Wanene zai fi son abokantaka da bouncers don samun damar VIP?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Wanene zai fi dacewa ya fara yaƙin karaoke na gaggawa?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Wanene zai fi iya bude kwalba ba tare da amfani da mabudin kwalba ba?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Wa zai fi yin magana duk da cewa babu wanda ya tambaya?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Wanene zai fi dacewa ya shafe awa daya a bandaki yana daukar selfie?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Wanene zai fi iya yin wasan raye-raye mai ban kunya kuma ya yi murna da shi?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Wanene zai iya kiran tsohon abokin tarayya bayan an gama bikin?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Wanene zai fi saurin ɓata wa baƙo laifi da gangan?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Wa zai fi yin fice a asirce ba tare da yin bankwana ba?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Wanene zai fi son yin wasa da dabbar mai masaukin baki fiye da yin magana da baƙi?",
    "Wer würde eher spontan eine Reise buchen?" to "Wanene zai fi dacewa ya yi ajiyar tafiya ba tare da bata lokaci ba?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Wanene zai fi iya yin tattaunawa mai zurfi a cikin kicin na sa'o'i?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Wanene ya fi saurin shan abin sha na wani?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Wanene zai fi dacewa ya kwankwasa gilashi mai tsada da gangan ko wani abu mara ƙarfi?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Wanene zai fi iya ƙoƙarin haɗa hadaddiyar giyar da kansu kuma ya gaza cikin wahala?",
    "Wer würde eher zu spät kommen?" to "Wanene yafi dacewa ya makara?",
    "Wer würde eher?" to "Wanene zai fi so?",
    "Wer übernimmt die tägliche Versorgung?" to "Wanene ke kula da kulawar yau da kullun?",
    "Werde so akzeptiert, wie du bist" to "Karba kamar yadda kuke",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Shin za mu sami isasshen lokaci don yaro/yara? ⏳",
    "Whirlpool" to "Ruwan zafi",
    "White Chocolate" to "Farin Chocolate",
    "Widgets" to "Widgets",
    "Wie fühlst du dich am meisten geliebt?" to "Yaya aka fi son ku?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Ta yaya za mu yi mu'amala da kudaden shiga daban-daban?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Wace hanya ce mafi kyau ga abokin tarayya don fara jima'i da ku?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Ta yaya abokin tarayya zai zama abokin tarayya mafi kyau a gare ku?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Har yaushe bayan shawarwarin kuke son yin bikin tare da wasu?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Har yaushe muke son zama a can akalla?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Yaya sauƙi a gare ku don yin magana game da buri?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Yaya kuke son makomarmu ta kasance?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Yaya cikakkiyar ranar Lahadin ku a gida tayi kama?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Yaya kuke ji game da kazanta yayin jima'i?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Nawa za mu iya bayarwa a zahiri?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Yaya lokaci nawa muke son kashewa?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Nawa muke son kashewa gabaɗaya?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Ta yaya za mu sami lokaci don dangantakarmu da zarar jariri ya zo?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Yaya mahimmanci a gare ku cewa an kama lokacin?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Yaya mahimmanci a gare ku cewa aikace-aikacen yana nuna abubuwan sha'awa ko abubuwan da kuke so?",
    "Wie würdest du sie/ihn nennen?" to "Me za ku kira shi/ta?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Menene hanyar da kuka fi so don nuna ƙauna a wajen jima'i?",
    "Wildblumen" to "Furen daji",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Shin kuna son mace ko namiji? 👶",
    "Wintergarten" to "Lambun hunturu",
    "Winterhochzeit" to "Bikin aure na hunturu",
    "Wir bestellen einfach beides" to "Muna yin odar duka biyu kawai",
    "Wir brauchen ewig" to "Yana daukan mu har abada",
    "Wir einigen uns nie" to "Ba mu taba yarda ba",
    "Wir entscheiden es gemeinsam" to "Mu yanke shawara tare",
    "Wir treffen uns in der Mitte" to "Zamu hadu a tsakiya",
    "Wir wechseln uns ab" to "Muna ɗaukar bi da bi",
    "Wird stressig" to "Yana samun damuwa",
    "Wobei lachst du am meisten?" to "Me ya fi baka dariya?",
    "Wofür sparen wir gemeinsam?" to "Me muke tarawa tare?",
    "Wohnzimmer" to "Falo",
    "Woran erinnerst du dich am lebhaftesten?" to "Me kuka fi tunawa a sarari?",
    "Worauf freust du dich bei uns am meisten?" to "Menene kuke fata tare da mu?",
    "Worte/Komplimente" to "Kalmomi/yabo",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Menene kuka fi tsoro a cikin dangantakarmu?",
    "Wünsche? z.B. günstig, draußen" to "Buri? misali arha, waje",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Kuna so ku ba da shawara kan hutu (wanda ya shafi tafiya)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "Waƙar YouTube",
    "Zeichne für mich" to "Zana min",
    "Zeichne mich als Tier — welches wäre ich?" to "Zana ni a matsayin dabba - menene zan zama?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Zana tunaninmu ga junanmu a matsayin alama.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Zana gidan mafarkinmu a layi daya. Menene ya fi daukar hankali?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Zana kwanan watanmu na farko - menene tabbas ya kamata ya kasance a cikin hoton?",
    "Zeichnen" to "Zana",
    "Zeit füreinander" to "Lokaci ga juna",
    "Zeit, wenn das Baby schläft" to "Lokacin da jariri ke barci",
    "Zelten gehen" to "Tafi zango",
    "Zitrone" to "Lemun tsami",
    "Zu Hause, gemütlich und privat" to "A gida, jin daɗi da sirri",
    "Zu einem Picknick gehen" to "Tafiya zuwa fitifiki",
    "Zu einem ausgefallenen Abendessen gehen" to "Zuwa wurin cin abinci mai ban sha'awa",
    "Zu zweit reisen" to "Tafiya kamar ma'aurata",
    "Zuhause & Alltag" to "Gida & Rayuwar yau da kullun",
    "Zuhören" to "Saurara",
    "Zurück" to "Komawa",
    "Zusammen seit" to "Tare tun",
    "Zusammen seit (TT.MM.JJJJ)" to "Tare tun (DD.MM.YYYY)",
    "Zusammenziehen" to "Kwangila",
    "Zustimmen oder Ablehnen" to "Na yarda ko Ban yarda ba",
    "Zwei Kreise, die sich überschneiden" to "Da'irori biyu da suka zo juna",
    "Zwei Stühle davor" to "Kujeru biyu a gabanta",
    "Zärtlich sein" to "Yi tausasawa",
    "Öfter als ich zugebe" to "Mafi sau fiye da yadda na yarda",
    "Über 100€/Monat" to "Sama da 100 € / wata",
    "Über 2000 im Monat" to "Sama da 2000 a wata",
    "Über mich selbst" to "Game da kaina",
    "Übernehmen" to "Aiwatar",
    "Überraschend" to "Abin mamaki",
    "Überraschung" to "Mamaki",
    "Überspringen" to "Tsallake",
    "Übertrieben und großartig" to "Sama da ban mamaki",
    "✎ Tippe, um zu antworten" to "✎ Taɓa don ba da amsa",
    "✨ GFK-Brücke" to "✨ GRP gada",
)

internal fun localizeHausaDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_HAUSA_CONTENT)
