package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_HEBREW_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 שנים",
    "1000 - 1500 im Monat" to "1000 - 1500 לחודש",
    "1000 bis 3000" to "1000 עד 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 לחודש",
    "3000 bis 5000" to "3000 עד 5000",
    "5-10 Jahre" to "5-10 שנים",
    "50-100€/Monat" to "50-100€ לחודש",
    "Ab 100€" to "החל מ-100€",
    "Ab 500€" to "החל מ-500 אירו",
    "Ab 50€" to "החל מ-50 אירו",
    "Ab und zu" to "מדי פעם",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "כמה אנחנו צריכים להוציא לפני ביצוע רכישה?",
    "Abbrechen" to "בטל",
    "Abenteuer" to "הרפתקאות",
    "Adidas" to "אדידס",
    "Aktivitäten" to "פעילויות",
    "Alle" to "הכל",
    "Alle Pakete" to "כל החבילות",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "אבד את כל החברים שלך מלבד החבר הכי טוב שלך",
    "Alle intimen Momente selbst initiieren" to "יזום את כל הרגעים האינטימיים בעצמך",
    "Alles davon" to "הכל",
    "Alles, was noch kommt" to "כל מה שעתיד לבוא",
    "Alltagsroutine" to "שגרת יומיום",
    "Alltägliche Berührungen" to "נגיעות יומיומיות",
    "Altbau mit Charme" to "בניין ישן עם קסם",
    "Am Strand" to "על החוף",
    "Am liebsten alles zusammen" to "רצוי הכל ביחד",
    "Am selben Tag mit Freunden/Familie" to "באותו יום עם חברים/משפחה",
    "Amazon" to "אמזון",
    "Amsterdam" to "אמסטרדם",
    "Amsterdam, Niederlande" to "אמסטרדם, הולנד",
    "An das Gefühl" to "מההרגשה",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "במקום ציבורי עם הרבה צופים",
    "An einen Geruch" to "של ריח",
    "An einen Song" to "לשיר",
    "An etwas, das ich gesagt habe" to "משהו שאמרתי",
    "Analyse starten" to "התחל ניתוח",
    "Analysiere eure Muster..." to "נתח את הדפוסים שלך...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "נתח את התשובות והצ'אטים שלך לפי גוטמן ו-GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "אננס על פיצה טעים.",
    "Android" to "אנדרואיד",
    "Antwort mit einem Foto" to "השב עם תמונה",
    "Antwortähnlichkeit" to "דמיון תשובה",
    "App-Sprache auswählen" to "בחר את שפת האפליקציה",
    "Auf eine Bootsparty gehen" to "הולך למסיבת סירה",
    "Aufmerksamkeit" to "שימו לב",
    "Aufräumen und Projekte angehen" to "נקה והתמודד עם פרויקטים",
    "Aufwärmen" to "חימום",
    "Aufwärmen: Einander kennenlernen" to "חימום: היכרות",
    "Aus dem Urlaub" to "מחופשה",
    "Ausgefallener Name" to "שם מפואר",
    "Ausschlafen und faulenzen" to "לישון ולהתעצל",
    "Ausschlafen und nichts tun" to "לישון בלי לעשות כלום",
    "Aussehen" to "הופעה",
    "Auto" to "אוטומטי",
    "Außenkamin" to "אח חיצוני",
    "BEANTWORTE" to "תשובה",
    "Bali" to "באלי",
    "Bali, Indonesien" to "באלי, אינדונזיה",
    "Banane" to "בננה",
    "Beantwortet" to "ענה",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "ענה על שאלות בו-זמנית - התשובות לא יהיו גלויות עד ששניכם תסיימו.",
    "Beantwortete Fragen" to "ענה על שאלות",
    "Bearbeiten" to "ערוך",
    "Bei Insider-Witzen" to "לבדיחות פנימיות",
    "Bei Memes" to "על ממים",
    "Bei einer spontanen Berührung" to "כשנוגעים בו באופן ספונטני",
    "Beide" to "שניהם",
    "Beide gleich" to "שניהם אותו דבר",
    "Beide zusammen" to "שניהם יחד",
    "Beide, aber wir tun so als ob nicht" to "שניהם, אבל אנחנו מעמידים פנים שלא",
    "Beides" to "שניהם",
    "Beides wäre schlimm" to "שניהם יהיו גרועים",
    "Beim Einschlafen nebeneinander" to "נרדמים אחד ליד השני",
    "Beim Reden" to "תוך כדי דיבור",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "מקומות תיירות מפורסמים הם תמיד אכזבה.",
    "Beschreibe unser Sexleben mit einem Emoji." to "תאר את חיי המין שלנו עם אימוג'י.",
    "Besser kommunizieren" to "תקשר טוב יותר",
    "Bessere Lage" to "מיקום טוב יותר",
    "Bestellen" to "הזמנה",
    "Besuchte Länder" to "מדינות שביקרו בהן",
    "Besuchte Städte" to "ערים ביקרו",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "האם אתה מעדיף הצעה אקסטרווגנטית או משהו עדין?",
    "Beziehung" to "מערכת יחסים",
    "Bibliothek" to "ספרייה",
    "Bin manchmal unsicher" to "לפעמים אני חסר ביטחון",
    "Bist du ein Videospiel-Guru?" to "האם אתה גורו של משחקי וידאו?",
    "Blumenwiese" to "אחו פרחים",
    "Bunte Blumenwiese" to "אחו פרחים צבעוני",
    "Burger" to "המבורגרים",
    "Burger King" to "בורגר קינג",
    "Chat" to "צ'אט",
    "Coca-Cola" to "קוקה קולה",
    "Cookie Dough" to "בצק עוגיות",
    "Dachgarten mit Lounge" to "גינת גג עם טרקלין",
    "Dachterrasse" to "מרפסת גג",
    "Das Wetter an dem Tag" to "מזג האוויר באותו יום",
    "Das erste Selfie" to "הסלפי הראשון",
    "Das meiste weiß ich" to "אני מכיר את רוב זה",
    "Das oder das?" to "זה או זה?",
    "Das tägliche Leben" to "חיי היומיום",
    "Dass Zusagen gehalten werden" to "שהבטחות מתקיימות",
    "Dass alles meinen Stil hat" to "שלכל דבר יש את הסגנון שלי",
    "Dass ich alles erzählen kann" to "שאני יכול לספר הכל",
    "Dass ich mich nicht sorgen muss" to "שאני לא צריך לדאוג",
    "Dass wir ungestört sind" to "שאנחנו לא מופרעים",
    "Dein Name" to "השם שלך",
    "Deine Antwort..." to "התשובה שלך...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "התשובות שלך נשמרות. ברגע שפרטנר תסיים את החבילה, שתי התשובות יהיו גלויות יחד.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "התשובות שלך נשמרות. לאחר ש-\${profile.partnerName} ישלים את החבילה, שתי התגובות יהיו גלויות יחד.",
    "Deine Beziehung abenteuerlich und spontan machen" to "הפוך את מערכת היחסים שלך להרפתקנית וספונטנית",
    "Deine Beziehung stabil und sicher machen" to "הפוך את מערכת היחסים שלך ליציבה ובטוחה",
    "Deine eigene Antwort" to "תשובה משלך",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "עדיף לחלוק את הסודות העמוקים ביותר שלך עם השותף שלך",
    "Deinen besten Freund verlieren" to "מאבד את החבר הכי טוב שלך",
    "Denke an dich" to "תחשוב על עצמך",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "צפייה באותו סרט פעמיים זה בזבוז זמן.",
    "Der Blick nach draußen" to "הנוף בחוץ",
    "Der Garten" to "הגן",
    "Der Ort" to "המקום",
    "Der Ring und die Geste" to "הטבעת והמחווה",
    "Der perfekte Heiratsantrag" to "הצעת הנישואין המושלמת",
    "Derjenige sein, der umarmt wird" to "תהיה זה שמחבק",
    "Deutsch" to "גרמנית",
    "Diamant" to "יהלום",
    "Diamanten im Band" to "יהלומים בלהקה",
    "Die Distanz" to "המרחק",
    "Die Feiertage mit der Familie deines Partners verbringen" to "בלו את החגים עם המשפחה של בן הזוג",
    "Die Gemütlichkeit und Ruhe" to "הנוחות והשלווה",
    "Die Menschen, die darin wohnen" to "האנשים שחיים בה",
    "Die Umgebung und Atmosphäre" to "הסביבה והאווירה",
    "Die Worte und Emotionen" to "המילים והרגשות",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "אתגר הטריוויה הבידורי האולטימטיבי",
    "Diejenige sein, die umarmt" to "תהיה זה שמחבק",
    "Direkt ansprechen" to "כתובת ישירות",
    "Diskussion" to "דיון",
    "Diskutiere vor dem Kinderkriegen" to "שוחח לפני הבאת ילדים",
    "Diskutiert eure Antworten" to "דנו בתשובות שלכם",
    "Disney" to "דיסני",
    "Doch, schon mal" to "כן, כן",
    "Draußen mit der Natur als Kulisse" to "בחוץ עם הטבע כרקע",
    "Drei-Stein-Ring" to "טבעת שלוש אבנים",
    "Du bist dran" to "זה תורך",
    "Du fehlst mir" to "אני מתגעגע אליך",
    "Dubai" to "דובאי",
    "Dubai, VAE" to "דובאי, איחוד האמירויות",
    "Dunkles Design" to "ערכת נושא כהה",
    "Durch Berührung" to "באמצעות מגע",
    "Durch Worte" to "באמצעות מילים",
    "Durch Zeit zu zweit" to "דרך זמן ביחד",
    "Durch kleine Gesten" to "באמצעות מחוות קטנות",
    "Durchgeplant" to "מתוכנן היטב",
    "ERGEBNISSE" to "תוצאות",
    "Egal, Hauptsache gesund" to "מה שלא יהיה, העיקר בריא",
    "Ehepaar Leben" to "חיי זוג נשואים",
    "Eher knapp" to "די קרוב",
    "Eher nicht" to "לא כל כך",
    "Eher schwer" to "די קשה",
    "Eher schwierig" to "די קשה",
    "Eher zu" to "עוד כמו",
    "Eifersucht ist ein Zeichen von Liebe." to "קנאה היא סימן לאהבה.",
    "Eigenes Gemüsebeet" to "חלקת ירקות משלו",
    "Ein Abenteuer in einer neuen Stadt" to "הרפתקה בעיר חדשה",
    "Ein Anker" to "עוגן",
    "Ein Balkon oder Garten" to "מרפסת או גינה",
    "Ein Filmabend" to "ערב סרטים",
    "Ein Harmony-Meilenstein eurer Liebe." to "אבן דרך בהרמוניה של אהבתך.",
    "Ein Herz" to "לב",
    "Ein Herz an der Tür" to "לב ליד הדלת",
    "Ein Jahr lang eine Fernbeziehung führen" to "לנהל מערכת יחסים למרחקים ארוכים במשך שנה",
    "Ein Kindheitsessen" to "ארוחת ילדות",
    "Ein Live-Musik-Konzert besuchen" to "השתתף בהופעה של מוזיקה חיה",
    "Ein Museum besuchen" to "בקר במוזיאון",
    "Ein Spieleabend" to "ערב משחקים",
    "Ein Spieleabend mit Freunden" to "ערב משחקים עם חברים",
    "Ein Urlaubsfoto" to "תמונת חופשה",
    "Ein aktives Abenteuer" to "הרפתקה פעילה",
    "Ein entspannender Spa-Tag" to "יום ספא מרגיע",
    "Ein ganz normaler Alltagstag" to "יום יומי רגיל לחלוטין",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "ערב נעים בבית בזמן סופת רעמים",
    "Ein gemütliches Date drinnen" to "דייט נעים בתוך הבית",
    "Ein lustiges Bild" to "תמונה מצחיקה",
    "Ein paar Handyfotos reichen" to "מספיק כמה תמונות בטלפון סלולרי",
    "Ein paar Stunden" to "כמה שעות",
    "Ein paar kulturelle Anklänge sind okay" to "כמה התייחסויות תרבותיות בסדר",
    "Ein romantischer Abend" to "ערב רומנטי",
    "Ein romantisches Abendessen bei Kerzenlicht" to "ארוחת ערב רומנטית לאור נרות",
    "Ein romantisches Bild" to "תמונה רומנטית",
    "Ein romantisches Picknick an einem schönen Ort" to "פיקניק רומנטי במיקום יפהפה",
    "Ein schwerer Moment, den wir geschafft haben" to "רגע קשה שהצלחנו",
    "Ein tolles Date im Freien unter dem Mondlicht" to "דייט נהדר בחוץ תחת אור הירח",
    "Ein ungewöhnliches Gericht" to "מנה יוצאת דופן",
    "Ein zufälliger Schnappschuss" to "תמונת מצב אקראית",
    "Einander kennenlernen" to "להכיר אחד את השני",
    "Eine Autoreise" to "טיול בכביש",
    "Eine Brücke" to "גשר",
    "Eine Date-Nacht unter den Sternen" to "לילה דייט מתחת לכוכבים",
    "Eine Million Dollar gewinnen" to "זכה במיליון דולר",
    "Eine Million Dollar verdienen" to "תרוויח מיליון דולר",
    "Eine Nacht in einem Club" to "לילה במועדון",
    "Eine Schokoladenverkostung" to "טעימת שוקולד",
    "Eine Wanderung mit Panoramablick machen" to "צאו לטיול רגלי עם נוף פנורמי",
    "Eine Weinverkostung" to "טעימת יין",
    "Eine gemeinsame Reise" to "מסע ביחד",
    "Eine gemütliche Nacht zu Hause" to "לילה נעים בבית",
    "Eine neue Sprache zu lernen ist einfach." to "קל ללמוד שפה חדשה.",
    "Einen Film anschauen" to "צפה בסרט",
    "Einen Monat lang überhaupt nicht miteinander reden" to "לא מדברים אחד עם השני בכלל במשך חודש",
    "Einen Tanzkurs besuchen" to "קח שיעור ריקוד",
    "Einen Vergnügungspark erkunden" to "חקור פארק שעשועים",
    "Einen Wellness-Tag" to "יום בריאות",
    "Einen sehr emotionalen Partner haben" to "בעל שותף מאוד רגשי",
    "Einen sehr logischen Partner haben" to "בעל שותף מאוד הגיוני",
    "Einer zahlt alles" to "אדם אחד משלם הכל",
    "Einfach mehr Alltag" to "פשוט יותר חיי היומיום",
    "Einfach nebeneinander sein" to "פשוט תהיו אחד ליד השני",
    "Einfach und intim" to "פשוט ואינטימי",
    "Einige Dinge für dich behalten" to "שמור כמה דברים לעצמך",
    "Einmal" to "פעם אחת",
    "Eins, das nur wir kennen" to "אחד שרק אנחנו מכירים",
    "Englisch" to "אנגלית",
    "Entspannte Hängematte" to "ערסל רגוע",
    "Entspannung" to "הרפיה",
    "Erdbeere" to "תות",
    "Erfolgreich" to "מוצלח",
    "Ergebnisse" to "תוצאות",
    "Erst bei sehr großen Summen" to "רק בסכומים גבוהים מאוד",
    "Erst nur enge Freunde/Familie" to "בהתחלה רק חברים/משפחה קרובים",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "זה מעצבן אותי שלבן הזוג שלי לוקח יותר מדי זמן להגיב להודעות.",
    "Essen & Genuss" to "אוכל והנאה",
    "Essensvorlieben" to "העדפות מזון",
    "Etwa eine Woche später, erst mal nur wir" to "כשבוע לאחר מכן, רק אנחנו בהתחלה",
    "Etwas Neues ausprobieren" to "נסה משהו חדש",
    "Etwas ganz anderes" to "משהו אחר לגמרי",
    "Etwas sehr Scharfes" to "משהו מאוד חד",
    "Etwas, das ich selbst gern erfinde" to "משהו שאני אוהב להמציא בעצמי",
    "Etwas, eine kleine Note wäre schön" to "משהו, הערה קטנה תהיה נחמדה",
    "Familie" to "משפחה",
    "Familie/Freunde" to "משפחה/חברים",
    "Familienmensch" to "איש משפחה",
    "Farbedelstein" to "אבן חן צבעונית",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "פרסומות טלוויזיה מעניינות לפעמים לצפייה.",
    "Fertig" to "בוצע",
    "Fertig!" to "בוצע!",
    "Feste Date-Nights" to "לילות תאריך קבועים",
    "Feuerstelle" to "בור אש",
    "Filigran & schlicht" to "פיליגרן ופשוט",
    "Filme/Serien" to "סרטים/סדרות",
    "Formuliere um..." to "ניסוח מחדש...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "נסח מחדש את הטיוטה שלך בצורה לא אלימה: התבוננות, תחושה, צורך, בקשה.",
    "Frage hinzufügen" to "הוסף שאלה",
    "Fragen & Spiele" to "שאלות ומשחקים",
    "Fragen für jede Gelegenheit" to "שאלות לכל אירוע",
    "Freizeitpark" to "פארק שעשועים",
    "Freunde treffen" to "הכירו חברים",
    "Freundschaften mit Ex-Partnern sind okay." to "חברות עם אקסים זה בסדר.",
    "Früh aufstehen" to "קום מוקדם",
    "Fußbodenheizung" to "חימום תת רצפתי",
    "Führen wir getrennte oder gemeinsame Konten?" to "האם יש לנו חשבונות נפרדים או משותפים?",
    "Für dich empfohlen" to "מומלץ עבורך",
    "Für die Zukunft" to "לעתיד",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "לא נמצאו שאלות או משחקים תואמים לחיפוש זה.",
    "Für immer" to "לנצח",
    "Fürsorglichkeit" to "אכפתיות",
    "GFK-Brücke" to "גשר GRP",
    "Galerie" to "גלריה",
    "Gar nicht, der Moment gehört uns" to "בכלל לא, הרגע הוא שלנו",
    "Gar nichts tun" to "אל תעשה דבר",
    "Geduld" to "סבלנות",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "לך מוקדם בבוקר לראות את הזריחה",
    "Geht so" to "הולך ככה",
    "Geister existieren wirklich." to "רוחות רפאים באמת קיימות.",
    "Gelassenheit" to "שלווה",
    "Gelbgold" to "זהב צהוב",
    "Geld & Finanzen" to "כסף ומימון",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "טיילו יחד בעולם, חקרו תרבויות ומטבחים חדשים",
    "Gemeinsam ein Lego bauen" to "בנו יחד לגו",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "נסו יחד מתכון חדש במטבח",
    "Gemeinsame Konten" to "חשבונות משותפים",
    "Gemeinsame Nächte" to "לילות ביחד",
    "Gemeinsame Tage" to "ימים ביחד",
    "Gemischt" to "מעורב",
    "Gemüsebeet" to "מדבקת ירקות",
    "Gemütliche Feuerstelle" to "אח נעים",
    "Gesprächsanreger" to "מתחיל שיחה",
    "Getrennte Konten" to "חשבונות נפרדים",
    "Getrennte Urlaube tun einer Beziehung gut." to "חופשות נפרדות טובות לזוגיות.",
    "Gewächshaus" to "חממה",
    "Glasfassade" to "חזית זכוכית",
    "Gleichgültigkeit" to "אדישות",
    "Glücklich und frei" to "שמח וחופשי",
    "Gourmet Eis-Sorten" to "זני גלידת גורמה",
    "Gravur innen" to "חריטה בפנים",
    "Grillplatz" to "אזור ברביקיו",
    "Groß & üppig" to "גדול ושופע",
    "Große Familie" to "משפחה גדולה",
    "Große Feier" to "חגיגה גדולה",
    "Große Fenster" to "חלונות גדולים",
    "Große Fensterfront" to "חלון גדול בחזית",
    "Großer Außenpool" to "בריכה חיצונית גדולה",
    "Großer Garten" to "גינה גדולה",
    "Großer Stein" to "אבן גדולה",
    "Größere Küche" to "מטבח גדול יותר",
    "Gutes Essen" to "אוכל טוב",
    "Habe ich" to "עשיתי זאת",
    "Habe ich noch nie" to "אף פעם לא היה לי",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "האם גילית הבדלים מפתיעים? דבר על למה אתה אוהב יותר אפשרויות מסוימות!",
    "Haus am See" to "בית ליד האגם",
    "Haus/Wohnung" to "בית/דירה",
    "Hazelnut" to "אגוז לוז",
    "Heimkino" to "קולנוע ביתי",
    "Herzhaft" to "לבבי",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "אין כאן שום דבר כרגע.\nשנה את המסנן או בחר נושא אחר.",
    "Hilfe im Alltag" to "עזרה בחיי היומיום",
    "Himbeere" to "פטל",
    "Hinzufügen" to "הוסף",
    "Hobbys" to "תחביבים",
    "Hochzeitssträuße" to "זרי חתונה",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "גאווה בבית הוגוורטס: לאן אתה שייך?",
    "Home" to "בית",
    "Hot Tub" to "ג'קוזי",
    "Humor" to "הומור",
    "Hund" to "כלב",
    "Hängematte" to "ערסל",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "האם תרצה מכתב כתוב כחלק מההצעה?",
    "IKEA" to "איקאה",
    "Ich" to "אני",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "אני מעדיף טיולים רומנטיים בפארק מאשר ללכת לקולנוע.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "מעולם לא נרדמתי בקולנוע.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "אני נהנה לגלות תחביבים חדשים או פעילויות עם בן זוגי.",
    "Ich finde eine Alternative" to "אני אמצא חלופה",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "אני נהנה לנסות מסעדות חדשות עם בן זוגי במקום ללכת תמיד לאותם מקומות.",
    "Ich habe noch nie" to "מעולם לא",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "מעולם לא פחדתי מרכבת הרים ועליתי עליה בכל מקרה.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "מעולם לא קניתי כרטיסי Fast Pass כי הייתי חסר סבלנות.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "מעולם לא ביטלתי תוכניות להישאר בבית ולצפות בתוכנית טלוויזיה.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "מעולם לא חיכיתי למכתב שלי מהוגוורטס.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "מעולם לא אמרתי שסלית'רין לא היה כל כך גרוע.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "מעולם לא אמרתי שאני מבוגר מדי לסרטי דיסני (ונהניתי מהם בסתר).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "מעולם לא יריתי בכוונה מישהו עם טנק כחול ב-Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "מעולם לא בכיתי בסרט של דיסני.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "מעולם לא כיסיתי את עיני בזמן שצפיתי בסרט אימה.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "מעולם לא שכחתי לשמור משחק ואיבדתי שעות של התקדמות.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "מעולם לא יצאתי מהחדר במהלך סצנה מביכה (גורם התכווצות).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "מעולם לא עשיתי פוזה מצחיקה בזמן שצילמתי תמונה של רכבת הרים.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "מעולם לא שיחקתי עד מאוחר בלילה והתחרטתי על כמה עייף הייתי למחרת.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "מעולם לא חיפשתי בגוגל את הסוף של סרט כי לא יכולתי לחכות.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "מעולם לא הרגשתי שאני עומד על סט של סרט.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "מעולם לא דילגתי על ההקדמה של הסדרה האהובה עליי.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "מעולם לא שיתפתי את הסיסמה של נטפליקס של מישהו אחר.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "מעולם לא הקשבתי לפסקול של משחק בזמן עבודה או לימודים.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "מעולם לא האשמתי את הבקר כשהפסדתי.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "מעולם לא זרקתי את המקלדת או הבקר בכעס.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "מעולם לא שכחתי בגדים רטובים במכונת הכביסה במשך כמה ימים.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "מעולם לא הוצאתי כסף אמיתי על פריטים קוסמטיים במשחק.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "מעולם לא נהגתי במכונית במדינה זרה.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "מעולם לא חגרתי שיר של דיסני במקלחת.",
    "Ich habe noch nie ein Elektroauto gefahren." to "מעולם לא נהגתי במכונית חשמלית.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "מעולם לא צילמתי תמונה עם קמע בפארק.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "מעולם לא קראתי חיית מחמד על שם דמות של הוגוורטס.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "מעולם לא שמתי פופקורן באולם קולנוע ועדיין אכלתי אותו.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "מעולם לא השתמשתי בחיי היומיום בציטוט של מאסטר יודה ממלחמת הכוכבים.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "מעולם לא קניתי מזכרת במחיר מופקע בפארק שעשועים.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "מעולם לא נתתי המלצה לסרט שהאדם השני מצא נורא.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "מעולם לא צפיתי באוסקר בשידור חי באמצע הלילה.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "מעולם לא ביטלתי סדרה כי העונה האחרונה הייתה כל כך גרועה.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "מעולם לא צפיתי בבולמוס בעונה שלמה של סדרה ביום אחד.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "מעולם לא ניצחתי בוס בניסיון הראשון והרגשתי כמו אלוהים.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "מעולם לא מצאתי נבל מגניב יותר מהגיבור.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "מעולם לא זיהיתי דמות של צעצוע של סיפור בצעצועים שלי.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "מעולם לא יצרתי דמות ב-RPG בדיוק כמוני.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "מעולם לא אכלתי צ'ורו בפארק שעשועים.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "מעולם לא צפיתי בסרט של דיסני שלוש פעמים ברציפות.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "מעולם לא היה לי מנגינה קליטה של ​​דיסני במשך שבוע שלם.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "מעולם לא צפיתי בסרט רק בגלל שחקן מסוים.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "אף פעם לא הקשבתי לפסקול סרט בשידור חוזר במשך שעות.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "מעולם לא חשפתי ספוילר לסרט ומיד התחרטתי.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "מעולם לא מצאתי חבר שמדבר שפת אם אחרת.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "מעולם לא היה לי חבר שעבר למדינה אחרת.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "מעולם לא עשיתי מרתון סרטים של הארי פוטר בחג המולד.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "מעולם לא צפיתי בסרט של מארוול עד הסוף רק בגלל סצנת הפוסט-קרדיט.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "מעולם לא עצבנתי בכוונה NPC (דמות ללא נגן).",
    "Ich habe noch nie einen Nachtzug genommen." to "מעולם לא נסעתי ברכבת לילה.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "מעולם לא עשיתי מבחן מקוון כדי לגלות את הבית שלי בהוגוורטס.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "מעולם לא מחקתי פוסט במדיה החברתית כי הוא לא קיבל מספיק לייקים.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "מעולם לא קראתי ליום אחד בפארק השעשועים ליום הטוב ביותר בשנה.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "מעולם לא ביקרתי בפארק שעשועים ונשארתי בו מהבוקר עד הלילה.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "מעולם לא השארתי רכיבה של רובוטריקים או מארוול מוקסמת לחלוטין.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "מעולם לא עזבתי את הזעם ועזבתי את המשחק.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "מעולם לא קראתי אף אחד מהכרכים הגדולים של הארי פוטר.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "מעולם לא התלהבתי מהדמות האהובה עליי בסדרה.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "מעולם לא חלמתי לשחק קווידיץ'.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "מעולם לא חיפשתי בגוגל בסתר איך לפתור רמה קשה.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "מעולם לא קיוויתי בסתר שחיית המחמד שלי תוכל לדבר כמו בדיסני.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "מעולם לא הסרתי את מוביל הבריכה בסימס.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "מעולם לא איבדתי את הכיוון ברכיבה בסימולטור תלת מימד.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "מעולם לא שיחקתי בקבוצת ספורט באוניברסיטה.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "מעולם לא חיכיתי בתור יותר משעתיים לאטרקציה אחת.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "מעולם לא הרטבתי את חפצי הערך שלי בנסיעה במים.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "מעולם לא התווכחתי עם חבר על איזה בית הוא הטוב ביותר.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "מעולם לא העמדתי פנים שיש לי כוחות קסם כמו אלזה.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "מעולם לא צחקתי כל כך עד שפספסתי סצנה חשובה בסרט.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "מעולם לא הרגשתי כל כך הרבה אדרנלין שמיד רציתי לרכוב שוב.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "מעולם לא ניסיתי לשיר עם חיות כמו שלגיה.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "מעולם לא חלמתי על טיול לדיסנילנד.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "מעולם לא חלמתי לרכוב על רכיבת המים בפארק היורה.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "אף פעם לא צרחתי בקול בהלת קפיצה במשחק.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "מעולם לא בכיתי על הגמר של תוכנית טלוויזיה.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "מעולם לא... ביטלתי דייט כדי להישאר בבית.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "מעולם לא... ניסחתי מחדש הודעה 10 פעמים.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "מעולם לא... הסתכלתי בסתר בטלפון הנייד של בן זוגי.",
    "Ich habe noch nie!" to "מעולם לא!",
    "Ich habe!" to "יש לי!",
    "Ich lache viel mit meinem Partner." to "אני צוחק הרבה עם בן זוגי.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "אני אוהב להכיר את התחביבים ותחומי העניין של בן זוגי.",
    "Ich liebe es" to "אני אוהב את זה",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "אני אוהב לצפות בסרטים עם בן זוגי שאף אחד מאיתנו לא ראה בעבר.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "אני אוהב לחלוק את המוזיקה האהובה עליי עם בן זוגי.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "מעולם לא נאלצתי לרוץ כדי לתפוס טיסת המשך.",
    "Ich plane gerne Dates mit meinem Partner." to "אני אוהב לתכנן דייטים עם בן זוגי.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "אני מעדיף לבלות עם בן זוגי גם כשאני עסוק.",
    "Ich schreibe meinem Partner jeden Tag." to "אני שולח הודעה לבן הזוג שלי כל יום.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "אני אוהב לשתף ממים ובדיחות עם בן זוגי.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "אני אוהב לחלוק את כל הפרטים של היום שלי עם בן זוגי.",
    "Ich würde es nie tun" to "לעולם לא אעשה את זה",
    "Ich übe noch" to "אני עדיין מתאמן",
    "Ideen generieren" to "צור רעיונות",
    "Im Haushalt helfen" to "עזרה בבית",
    "In Chat einfügen" to "הוסף לצ'אט",
    "In Stille nebeneinander" to "בשתיקה אחד ליד השני",
    "In den Bergen" to "בהרים",
    "In eine Bar gehen" to "לך לבר",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "הולך לבר חוף לצפות בשקיעה",
    "In einem feinen Restaurant essen gehen" to "אוכלים בחוץ במסעדה משובחת",
    "In einen Coffeeshop gehen" to "לך לבית קפה",
    "In einer Beziehung sollte man alles voneinander wissen." to "במערכת יחסים אתם צריכים לדעת הכל אחד על השני.",
    "Infinity-Pool" to "בריכת אינסוף",
    "Innenpool" to "בריכה מקורה",
    "Intelligenz" to "מודיעין",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "יש רק רגעים אינטימיים שבהם בן הזוג יוזם אותם",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "קוד הזמנה: HRM-8731 · הכל לא נעול",
    "Island" to "איסלנד",
    "Ist okay für mich" to "זה בסדר מבחינתי",
    "Ist schon perfekt" to "זה מושלם",
    "Ja, Traditionen einbinden" to "כן, שלבו מסורות",
    "Ja, absolut" to "כן, בהחלט",
    "Ja, etwas zum Lesen und Aufbewahren" to "כן, משהו לקרוא ולשמור",
    "Ja, genug" to "כן, מספיק",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "כן, בעיר או באטרקציה מרגשת",
    "Ja, in- und auswendig" to "כן, מבפנים ומבחוץ",
    "Ja, komplett überraschend" to "כן, לגמרי מפתיע",
    "Ja, perfekt" to "כן, מושלם",
    "Ja, sie gehören zur Familie!" to "כן, הם משפחה!",
    "Ja, sofort teilen" to "כן, שתף מיד",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "כן, אנחנו נדאג שזמן המשפחה יהיה בראש סדר העדיפויות.",
    "Jacuzzi" to "ג'קוזי",
    "Jahr zusammen 🎉" to "שנה ביחד 🎉",
    "Jahre zusammen 🎉" to "שנים ביחד 🎉",
    "Jeder zahlt 50%" to "כולם משלמים 50%",
    "Junge" to "ילד",
    "Kamin" to "אח",
    "Karriere & Erfolg" to "קריירה והצלחה",
    "Kategorien" to "קטגוריות",
    "Katze" to "חתול",
    "Keine Musik" to "אין מוזיקה",
    "Keine Party nötig, privat halten" to "אין צורך במסיבה, שמרו על פרטיות",
    "Keine Privatsphäre" to "אין פרטיות",
    "Keine Treffer gefunden" to "לא נמצאו התאמות",
    "Keiner" to "אין",
    "Keiner von uns" to "אף אחד מאיתנו",
    "Kennst du die Essensvorlieben deines Partners?" to "האם אתה מכיר את העדפות האוכל של בן הזוג שלך?",
    "Kino" to "קולנוע",
    "Kirchlich" to "כנסייתי",
    "Klassisch Solitär" to "סוליטר קלאסי",
    "Klassisch gebunden" to "כרוך קלאסית",
    "Klein & zart" to "קטן ועדין",
    "Kleine Geschenke" to "מתנות קטנות",
    "Kleine Runde" to "קבוצה קטנה",
    "Kochen und Freunde einladen" to "מבשלים ומזמינים חברים",
    "Kochkurs" to "שיעור בישול",
    "Kommt auf den Tag an" to "תלוי ביום",
    "Kommt darauf an" to "זה תלוי",
    "Kommt drauf an" to "זה תלוי",
    "Kommt mit" to "בואי איתי",
    "Konzert" to "קונצרט",
    "Kräftige Farben" to "צבעים חזקים",
    "Kräuterbeet" to "ערוגת עשבים",
    "Kultur & Sehenswürdigkeiten" to "תרבות ומראות",
    "Kuscheln" to "חיבוק",
    "Kuss senden" to "שלח נשיקה",
    "Körperliche Annäherung" to "גישה פיזית",
    "Körperliche Nähe" to "קרבה פיזית",
    "Küche" to "מטבח",
    "Land" to "מדינה",
    "Landhaus" to "בית כפרי",
    "Landhausstil" to "סגנון בית כפרי",
    "Lange wach bleiben" to "הישארו ערים עד מאוחר",
    "Lappland" to "לפלנד",
    "Lappland, Finnland" to "לפלנד, פינלנד",
    "Las Vegas" to "לאס וגאס",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "תן לבן הזוג שלך לעורר אותך להיות האני הטוב ביותר שלך",
    "Lehne ab" to "דחה",
    "Leichtigkeit" to "קלילות",
    "Leidenschaft" to "תשוקה",
    "Liebe im Gleichgewicht" to "אהבה באיזון",
    "Liebe sie, macht mehr Spaß" to "אוהב אותם, יותר כיף",
    "Lieber durchgeplant oder spontan?" to "האם אתה מעדיף שזה יהיה מתוכנן או ספונטני?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "האם אתה מעדיף ערב שקט לשניים או עם אנשים?",
    "Lieber nicht" to "עדיף שלא",
    "Lieber vorher grob absprechen" to "עדיף לדון בדברים בערך לפני כן",
    "Lokal einkaufen" to "קניות מקומיות",
    "London" to "לונדון",
    "London, England" to "לונדון, אנגליה",
    "Lügen" to "שקרים",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "האם אתה מעדיף הצעה ציבורית או פרטית?",
    "Malediven" to "האיים המלדיביים",
    "Man sollte nie streitend einschlafen." to "לעולם אל תירדם בוויכוחים.",
    "Mango Sorbet" to "סורבה מנגו",
    "Markant & breit" to "בולט ורחב",
    "Marken & Alltag" to "מותגים וחיי היומיום",
    "McDonald’s" to "מקדונלדס",
    "Mediterraner Innenhof" to "חצר ים תיכונית",
    "Mehr Unterstützung" to "תמיכה נוספת",
    "Mehr gemeinsame Zeit" to "עוד זמן ביחד",
    "Mehr zuhören" to "האזן עוד",
    "Mehrgenerationenhaus" to "בית רב-דורי",
    "Mein Arbeitsplatz" to "מקום העבודה שלי",
    "Mein Partner" to "השותף שלי",
    "Mich überraschen" to "תפתיע אותי",
    "Minimalistisches Interieur" to "פנים מינימליסטי",
    "Missverständnisse" to "אי הבנות",
    "Mit Familie und engen Freunden" to "עם משפחה וחברים קרובים",
    "Mit Kompromissen" to "עם פשרות",
    "Mitgefühl" to "חמלה",
    "Mittelweg mit besonderen Details" to "קרקע ביניים עם פרטים מיוחדים",
    "Modern geometrisch" to "גיאומטרי מודרני",
    "Moderne Grillstation" to "תחנת גריל מודרנית",
    "Moderner Name" to "שם מודרני",
    "Moderner Solitär" to "סוליטר מודרני",
    "Moissanit" to "מויסניט",
    "Moment festhalten" to "תפוס את הרגע",
    "Momente" to "רגעים",
    "Monaco" to "מונקו",
    "Moralische Werte" to "ערכי מוסר",
    "Museum" to "מוזיאון",
    "Musik" to "מוזיקה",
    "Mut" to "אומץ",
    "Mädchen" to "בנות",
    "Möbelhaus" to "חנות רהיטים",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "האם אתה בטוח שאתה רוצה לעזוב את החידון? ההתקדמות הקודמת שלך נשארת שמורה.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "האם תרצה שחיות מחמד ייכללו באפליקציה?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "רוצה שהרגע ישותף באופן מיידי ברשתות החברתיות?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "ייתכן שנצטרך לחסוך",
    "Müssen es planen" to "צריך לתכנן את זה",
    "Müssen sparen" to "צריך לשמור",
    "Nachricht an" to "הודעה",
    "Name Partnerin" to "שם השותף",
    "Namen und Startdatum eurer Beziehung." to "שמות ותאריך התחלה של מערכת היחסים שלכם.",
    "Natursteinfassade" to "חזית אבן טבעית",
    "Naturteich" to "בריכה טבעית",
    "Nein, einfach halten" to "לא, פשוט תחזיק את זה",
    "Nein, erstmal privat halten" to "לא, השאר את זה פרטי לעת עתה",
    "Nein, lieber vor Ort" to "לא, עדיף באתר",
    "Nein, modern halten" to "לא, שמור על זה מודרני",
    "Nein, nur wir" to "לא, רק אנחנו",
    "Nein, zu ablenkend" to "לא, מפריע מדי",
    "Netflix" to "נטפליקס",
    "Neubau mit Smart Home" to "בניין חדש עם בית חכם",
    "Neubau mit Technik" to "בניין חדש עם טכנולוגיה",
    "Neue Liebe, neue Erfahrungen" to "אהבה חדשה, חוויות חדשות",
    "Neues Hobby" to "תחביב חדש",
    "Neues Spiel" to "משחק חדש",
    "Neugier" to "סקרנות",
    "New York" to "ניו יורק",
    "New York, USA" to "ניו יורק, ארה\\\"ב",
    "Nicht mein Fall" to "לא כוס התה שלי",
    "Nicht nötig, lieber klassisch bleiben" to "אין צורך, עדיף להישאר קלאסי",
    "Nichts — es passt so" to "כלום - זה מתאים",
    "Nie wieder Burger" to "לעולם לא עוד המבורגרים",
    "Nie wieder Pizza" to "לעולם לא פיצה שוב",
    "Niemand" to "אף אחד",
    "Niemand ohne Plan" to "אף אחד בלי תוכנית",
    "Nike" to "נייקי",
    "Nizza" to "נחמד",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "עדיין אין רגעים.\nתפוס את החוויה הראשונה שלך 💞",
    "Nur bei wichtigen Themen" to "רק לנושאים חשובים",
    "Nur wir beide" to "רק שנינו",
    "Nähe & Intimität" to "קרבה ואינטימיות",
    "Obstgarten" to "בוסתן",
    "Oder" to "או",
    "Offene Küche" to "מטבח פתוח",
    "Offene Wohnküche" to "מטבח/סלון פתוח",
    "Ohne Stein" to "ללא אבן",
    "Open End" to "סוף פתוח",
    "Outdoor-Küche" to "מטבח חיצוני",
    "Outdoor-Sofa" to "ספה חיצונית",
    "Outdoor-Whirlpool" to "ג'קוזי חיצוני",
    "Ovaler Diamant" to "יהלום סגלגל",
    "Paar" to "זוג",
    "Paar-Statistiken" to "נתונים סטטיסטיים של זוג",
    "Paris" to "פריז",
    "Paris, Frankreich" to "פריז, צרפת",
    "Partner" to "שותף",
    "Partner-Simulator" to "סימולטור שותפים",
    "Partnerin" to "שותף",
    "Party Edition" to "מהדורת מסיבות",
    "Party Edition II" to "מהדורת מסיבה II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "האם חיה בכלל מתאימה לחיי היומיום שלנו?",
    "Pasta" to "פסטה",
    "Pastell" to "פסטל",
    "Penthouse mit Ausblick" to "פנטהאוז עם נוף",
    "Pepsi" to "פפסי",
    "Pergola mit Lounge" to "פרגולה עם טרקלין",
    "Pfingstrosen" to "אדמוניות",
    "Pinguin" to "פינגווין",
    "Pistazie" to "פיסטוק",
    "Pizza" to "פיצה",
    "Pizzaofen" to "תנור פיצה",
    "Platin" to "פלטינה",
    "PlayStation" to "פלייסטיישן",
    "Pool" to "בריכה",
    "Pop" to "פופ",
    "Prasselnder Kamin" to "אח שואג",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "נסיכות, פיראטים ואבק פיות: חידון דיסני",
    "Privater Innenhof" to "חצר פרטית",
    "Profil" to "פרופיל",
    "Profil bearbeiten" to "ערוך פרופיל",
    "Prozentual nach Einkommen" to "אחוז מבוסס על הכנסה",
    "Quiz verlassen" to "צא מהחידון",
    "Quiz verlassen?" to "לעזוב את החידון?",
    "Rausgehen in die Natur" to "צאו אל הטבע",
    "Reden vor ..." to "מדבר אל...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "תזמן תאריכים או שעה קבועים ביחד",
    "Reisen" to "נסיעות",
    "Reiseziele" to "יעדי טיול",
    "Respektlosigkeit" to "חוסר כבוד",
    "Restaurant" to "מסעדה",
    "RnB / Soul" to "RnB / נשמה",
    "Rock" to "רוק",
    "Rom" to "רומא",
    "Rom, Italien" to "רומא, איטליה",
    "Romantik" to "רומנטיקה",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "מחוות רומנטיות כמו הודעות, פתקים או מתנות משמחות אותי.",
    "Romantische Stimmung" to "מצב רוח רומנטי",
    "Roségold" to "רוז זהב",
    "Ruhig zu zweit" to "שקט לשניים",
    "Runder Diamant" to "יהלום עגול",
    "Salted Caramel" to "קרמל מלוח",
    "Sammle Ideen..." to "אסוף רעיונות...",
    "Santorini" to "סנטוריני",
    "Santorini, Griechenland" to "סנטוריני, יוון",
    "Saphir" to "ספיר",
    "Saunahaus" to "בית סאונה",
    "Schickes Restaurant oder Hotel" to "מסעדה או מלון אופנתיים",
    "Schlafzimmer" to "חדר שינה",
    "Schließen" to "סגור",
    "Schmal & zart" to "דק ועדין",
    "Schnappschüsse aus unserer Liebesgeschichte" to "תמונות מסיפור האהבה שלנו",
    "Schokolade" to "שוקולד",
    "Schreib frei, was dir wirklich dazu einfällt." to "כתבו בחופשיות מה שבאמת עולה לכם בראש.",
    "Schreibe deine eigene Antwort" to "כתוב את התשובה שלך",
    "Sehr gerne" to "אתה מוזמן",
    "Sehr leicht" to "קל מאוד",
    "Sehr wichtig — Fotos und Video" to "חשוב מאוד - תמונות ווידאו",
    "Sehr wichtig, es sollte persönlich sein" to "חשוב מאוד, זה צריך להיות אישי",
    "Selbst kochen" to "תבשל את עצמך",
    "Senden" to "שלח",
    "Separate Küche" to "מטבח נפרד",
    "Serie schauen" to "צפו בסדרה",
    "Serienmarathon auf dem Sofa" to "מרתון סדרה על הספה",
    "Sex & Liebe" to "סקס ואהבה",
    "Seychellen" to "איי סיישל",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "האם אנחנו יכולים לכסות את כל העלויות עבור ילד אחד/מספר ילדים? 💰",
    "Soll der Antrag eine Überraschung sein?" to "האם ההצעה צריכה להיות הפתעה?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "האם האפליקציה צריכה להכיל אלמנטים תרבותיים או מסורתיים?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "האם האפליקציה צריכה להכיל אלמנטים תרבותיים או מסורתיים?",
    "Sommerhochzeit" to "חתונת קיץ",
    "Sonnige Dachterrasse" to "מרפסת גג שטופת שמש",
    "Sowohl als auch" to "גם וגם",
    "Spazieren" to "צאו לטייל",
    "Spaß & Abenteuer" to "כיף והרפתקאות",
    "Speichern" to "שמור",
    "Spiel bearbeiten" to "ערוך משחק",
    "Spielbereich für Kinder" to "אזור משחקים לילדים",
    "Spiele" to "משחקים",
    "Spiele spielen und Spaß haben" to "שחקו משחקים ותהנו",
    "Spontan" to "ספונטני",
    "Sportplatz" to "מגרש ספורט",
    "Spotify" to "ספוטיפיי",
    "Sprache" to "שפה",
    "Stadt" to "עיר",
    "Stadt oder Land — was ist uns wichtiger?" to "עיר או מדינה - מה יותר חשוב לנו?",
    "Stadtvilla" to "וילה עירונית",
    "Standesamt & Party" to "משרד הרישום והמפלגה",
    "Statement-Ring" to "צלצול הצהרות",
    "Stilvolles Outdoor-Sofa" to "ספה חיצונית מסוגננת",
    "Stimme voll zu" to "מסכים לחלוטין",
    "Stimmt" to "נכון",
    "Stimmt nicht" to "לא נכון",
    "Stimmt, noch nie" to "נכון, לעולם לא",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "יום חוף",
    "Streit über Haushalt" to "מחלוקת על משק בית",
    "Studio Ghibli" to "סטודיו ג'יבלי",
    "Ständig" to "כל הזמן",
    "Suche schließen" to "סגור חיפוש",
    "Suche zurücksetzen" to "אפס את החיפוש",
    "Suche öffnen" to "פתח את החיפוש",
    "Suchergebnisse" to "תוצאות חיפוש",
    "Sushi" to "סושי",
    "Süß" to "מתוק",
    "Tage zusammen 💞" to "ימים ביחד 💞",
    "Tauche ins Unterbewusstsein" to "צלול לתוך התת מודע",
    "Teile alle deine Hobbys mit deinem Partner" to "שתף את כל התחביבים שלך עם השותף שלך",
    "Teils teils" to "חלקית חלקית",
    "Testen" to "מבחן",
    "Themen" to "נושאים",
    "Tiefe Gespräche" to "שיחות עמוקות",
    "Tiefgründige Gespräche führen" to "נהלו שיחות עמוקות",
    "Tierpension" to "פנסיון לבעלי חיים",
    "Tiny House" to "בית זעיר",
    "Tippen zum Auswählen & Scrollen" to "הקש כדי לבחור ולגלול",
    "Tippen zum Zuklappen" to "הקש כדי לכווץ",
    "Titel" to "כותרת",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "כותרת, קטגוריה, נושא, תגיות, שאלות...",
    "Tokyo, Japan" to "טוקיו, יפן",
    "Traditioneller Name" to "שם מסורתי",
    "Traumhaus Außenbereich" to "אזור חיצוני של בית חלומות",
    "Traumhochzeit" to "חתונת חלומות",
    "Treffer" to "פגע",
    "Tägliche Aktivität" to "פעילות יומית",
    "Umformulieren" to "ניסוח מחדש",
    "Unbeantwortet" to "ללא מענה",
    "Unbeliebte Meinungen" to "דעות לא פופולריות",
    "Universal Studios Genie oder Neuling?" to "אולפני יוניברסל גאון או חדש?",
    "Uns auseinanderzuleben" to "להתרחק",
    "Unser Intimleben" to "החיים האינטימיים שלנו",
    "Unser Traumhaus" to "בית החלומות שלנו",
    "Unser erstes Treffen" to "הפגישה הראשונה שלנו",
    "Unsere Gesichter" to "הפנים שלנו",
    "Unsere eigenen Träume" to "החלומות שלנו",
    "Unsere nächste Reise" to "הטיול הבא שלנו",
    "Unter 1000" to "מתחת ל-1000",
    "Unter 1000 im Monat" to "פחות מ-1000 לחודש",
    "Unter 50€/Monat" to "מתחת ל-50€ לחודש",
    "Unter Leuten" to "בין אנשים",
    "Untreue" to "בגידה",
    "Urlaub" to "חופשה",
    "Vanille" to "וניל",
    "Venedig" to "ונציה",
    "Venedig, Italien" to "ונציה, איטליה",
    "Verbinde dich mit" to "התחבר עם",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "התחבר אל \${profile.partnerName} כדי לראות את התשובה",
    "Verbindung" to "חיבור",
    "Verbringe die Feiertage mit deiner Familie" to "לבלות את החגים עם המשפחה שלך",
    "Verlobungsringe" to "טבעות אירוסין",
    "Vertrautheit" to "היכרות",
    "Viel getrennt" to "הרבה הפרדה",
    "Vielleicht ein oder zwei" to "אולי אחד או שניים",
    "Vielleicht, aber mündlich reicht" to "אולי, אבל מילולית זה מספיק",
    "Vielleicht, wenn es machbar ist" to "אולי, אם זה אפשרי",
    "Vielleicht, wenn es passt" to "אולי, אם זה מתאים",
    "Vintage Art déco" to "ארט דקו וינטג'",
    "Vintage verspielt" to "וינטג' שובב",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "היכרות עם תחביבים חדשים על ידי בן הזוג שלך",
    "Vor dem Kauf eines Hauses besprechen" to "דיון לפני קניית בית",
    "Vor der Anschaffung eines Haustiers besprechen" to "שוחח לפני רכישת חיית מחמד",
    "Vor der gemeinsamen Reise besprechen" to "שוחחו לפני שאתם נוסעים יחד",
    "Vor nichts" to "כלום",
    "Vorort" to "פרבר",
    "Walnuss" to "אגוז",
    "Wandern" to "טיולים",
    "Wann fühlst du dich mir am nächsten?" to "מתי אתה מרגיש הכי קרוב אליי?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "מתי אתה מרגיש הכי קרוב אלי פיזית?",
    "Was bedeutet Vertrauen für dich konkret?" to "מה המשמעות של אמון עבורך ספציפית?",
    "Was entspannt dich mehr?" to "מה מרגיע אותך יותר?",
    "Was fehlt dir über die Distanz am meisten?" to "למה אתה הכי מתגעגע למרחק?",
    "Was gefällt dir an deinem Zuhause am besten?" to "מה אתה הכי אוהב בבית שלך?",
    "Was hast du von deinem Partner gelernt?" to "מה למדת מבן הזוג שלך?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "מה דעתך על צפייה משותפת בתוכן אירוטי?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "מה אתה חושב על אביזרים (למשל שלטים, בלונים וכו')?",
    "Was ist das Wichtigste beim Antrag?" to "מה הדבר החשוב ביותר בעת הגשת הבקשה?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "מה הדבר הכי חשוב שאתה מחפש במפגש מיני?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "מהי התמונה האהובה עליך עלינו? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "מה הפחד הכי גדול שלך מהחיים המשותפים?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "מהו אוכל שאתה אוהב אבל בן הזוג שלך לא יכול להבין?",
    "Was ist für dich ein absoluter Dealbreaker?" to "מה זה שובר עסקות מוחלט עבורך?",
    "Was ist für jeden von uns das absolute Highlight?" to "מהי גולת הכותרת המוחלטת עבור כל אחד מאיתנו?",
    "Was ist passiert?" to "מה קרה?",
    "Was macht einen Moment für dich romantisch?" to "מה הופך רגע לרומנטי עבורך?",
    "Was magst du an deinem Partner am liebsten?" to "מה אתה הכי אוהב בשותף שלך?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "מה אתה אוהב יותר: לקום מוקדם או להישאר ער עד מאוחר?",
    "Was magst du lieber?" to "מה אתה אוהב יותר?",
    "Was möchtest du eigentlich sagen?" to "מה אתה בעצם רוצה לומר?",
    "Was möchtest du, dass dein Partner öfter tut?" to "מה היית רוצה שהשותף שלך יעשה לעתים קרובות יותר?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "מה קורה לבעל החיים כשאנחנו מטיילים?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "מה יהיה עם הילד שלנו כשיגדל?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "מה לעולם אל לנו לאבד מעינינו כהורים?",
    "Was war dein schönster Moment mit mir bisher?" to "מה היה הרגע הכי טוב שלך איתי עד כה?",
    "Was wir gegessen haben" to "מה אכלנו",
    "Was wollt ihr nie vergessen?" to "מה אתה לעולם לא רוצה לשכוח?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "מה יהיה יותר גרוע עבורך: לעולם לא פיצה שוב או לעולם לא שוב המבורגרים?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "מה הכי היית רוצה לעשות ביום משותף?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "מה היית משנה מיד אם כסף לא היה בעיה?",
    "Weiter" to "הבא",
    "Weiter spielen" to "המשך לנגן",
    "Weiß ich noch nicht" to "אני עדיין לא יודע",
    "Weiße Rosen" to "ורדים לבנים",
    "Weißgold" to "זהב לבן",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "איזו איכות הילד שלנו בהחלט צריך לקבל מאיתנו?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "איזו סביבה תרצה להצעה?",
    "Welcher Raum sagt am meisten über dich aus?" to "איזה חדר אומר עליך הכי הרבה?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "איזה תקציב אנחנו מתכננים למזון ולווטרינר?",
    "Welches Lied macht dich an? 🥵" to "איזה שיר מדליק אותך? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "איזו תמונה משותפת היא המועדפת עליך?",
    "Wellnessbad" to "אמבט בריאות",
    "Wenn es schwierig ist" to "כשדברים קשים",
    "Wenn ich müde bin" to "כשאני עייף",
    "Wenn wir uns lange umarmen" to "כשאנחנו מתחבקים הרבה זמן",
    "Wenn wir zusammen lachen" to "כשאנחנו צוחקים ביחד",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "מי מחליט מהר יותר מה להזמין?",
    "Wer findet die besten Restaurants?" to "מי מוצא את המסעדות הטובות ביותר?",
    "Wer gibt mehr Herzlichkeit?" to "מי נותן יותר חום?",
    "Wer hat den besseren Musikgeschmack?" to "למי יש טעם טוב יותר במוזיקה?",
    "Wer hängt mehr an seinen Eltern?" to "מי קשור יותר להורים שלו?",
    "Wer ist besser organisiert?" to "מי מאורגן טוב יותר?",
    "Wer ist der Beste bei der Filmauswahl?" to "מי הכי טוב בבחירת סרטים?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "מי הכי טוב בתכנון דייטים רומנטיים?",
    "Wer ist der beste Tänzer?" to "מי הרקדן הטוב ביותר?",
    "Wer ist romantischer?" to "מי יותר רומנטי?",
    "Wer kocht besser?" to "מי מבשל טוב יותר?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "מי דואג לשיפוץ ותחזוקה?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "מי שם לב יותר מהר כשהאדם השני לא מרגיש טוב?",
    "Wer sucht am Ende wirklich den Film aus?" to "מי באמת בוחר בסרט בסופו של דבר?",
    "Wer vergisst eher einen Jahrestag?" to "למי יש סיכוי גבוה יותר לשכוח יום נישואין?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "למי יש סיכוי גבוה יותר לשכוח את השם שלו למחרת בבוקר?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "למי יש סיכוי גבוה יותר למצוא סרטון למחרת שהוא לא יודע עליו כלום?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "מי מעדיף לבלות את הלילה על ספה של זר?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "למי יש סיכוי גבוה יותר להירדם במסיבה ולהתעורר עם שארפי על הפנים?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "למי יש סיכוי גבוה יותר להחליק על רחבת הריקודים אבל לגרום לזה להיראות כמו מהלך מגניב?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "למי יש סיכוי גבוה יותר להשתלט על רשימת ההשמעה של Spotify במסיבת בית?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "למי יש סיכוי גבוה יותר להזמין פיצה לכל אחד במסיבה ולאכול אותה בעצמו?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "למי יש סיכוי גבוה יותר להירדם ראשון במסיבה?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "למי יש סיכוי גבוה יותר שיתחיל פתאום לנקות במסיבה?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "למי יש סיכוי גבוה יותר לטעון שהוא מפוכח לחלוטין כאשר ההפך הוא הנכון?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "למי יש יותר סיכוי להיכנע ראשון בוויכוח?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "למי יש סיכוי גבוה יותר לבגוד במשחק שתייה?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "למי יש סיכוי גבוה יותר לפשוט על המזנון ולקחת אוכל בחשאי הביתה?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "למי יש סיכוי גבוה יותר שיפרסם את התמונה המביכה ביותר של הערב בסיפור שלו?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "למי יש סיכוי גבוה יותר לעצבן את התקליטן כדי לבקש את השיר האהוב עליו?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "למי יש סיכוי גבוה יותר לשיר את המילים לשיר אוף קי, אבל עם שכנוע?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "למי יש סיכוי גבוה יותר להזמין את המשקה היקר ביותר בתפריט ולהתחרט?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "למי יש סיכוי גבוה יותר להזמין את השכנים אם יתלוננו על הרעש?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "מי ייקח משחקי מסיבה (כמו ביר פונג) יותר מדי ברצינות?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "למי יש סיכוי גבוה יותר להתיידד עם הסדרנים כדי לקבל גישת VIP?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "למי יש סיכוי גבוה יותר להתחיל בקרב קריוקי ספונטני?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "למי יש סיכוי גבוה יותר לפתוח בקבוק בלי להשתמש בפותחן בקבוקים?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "למי יש סיכוי גבוה יותר לשאת נאום למרות שאף אחד לא שאל?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "למי יש סיכוי גבוה יותר לבלות שעה בשירותים בצילום סלפי?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "למי יש סיכוי גבוה יותר להעלות הופעת ריקוד מביכה ולחגוג אותה?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "למי יש סיכוי גבוה יותר להתקשר לבן זוג לשעבר אחרי שהמסיבה תסתיים?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "למי יש סיכוי גבוה יותר לפגוע בטעות באורח זר?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "למי יש סיכוי גבוה יותר שיעזוב את המסיבה בסתר מבלי להיפרד?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "מי מעדיף לשחק עם חיית המחמד של המארח מאשר לדבר עם האורחים?",
    "Wer würde eher spontan eine Reise buchen?" to "למי יש סיכוי גבוה יותר להזמין טיול באופן ספונטני?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "למי יש סיכוי גבוה יותר לנהל שיחות עמוקות במטבח במשך שעות?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "למי יש סיכוי גבוה יותר לשתות בטעות משקה של מישהו אחר?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "למי יש סיכוי גבוה יותר להפיל בטעות אגרטל יקר או משהו שביר?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "למי יש סיכוי גבוה יותר לנסות לערבב קוקטייל מסובך בעצמו ולהיכשל כישלון חרוץ?",
    "Wer würde eher zu spät kommen?" to "למי יש סיכוי גבוה יותר שיאחר?",
    "Wer würde eher?" to "מי מעדיף?",
    "Wer übernimmt die tägliche Versorgung?" to "מי דואג לטיפול היומיומי?",
    "Werde so akzeptiert, wie du bist" to "תתקבל כפי שאתה",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "האם יהיה לנו מספיק זמן לילד/הילדים? ⏳",
    "Whirlpool" to "ג'קוזי",
    "White Chocolate" to "שוקולד לבן",
    "Widgets" to "ווידג'טים",
    "Wie fühlst du dich am meisten geliebt?" to "איך אתה מרגיש הכי אהוב?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "כיצד אנו מתמודדים עם הכנסות שונות?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "מהי הדרך הטובה ביותר עבור בן הזוג שלך ליזום איתך יחסי מין?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "איך בן זוגך יכול להיות שותף אפילו טוב יותר עבורך?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "כמה זמן אחרי ההצעה אתה רוצה לחגוג עם אחרים?",
    "Wie lange wollen wir dort mindestens bleiben?" to "כמה זמן אנחנו רוצים להישאר שם לפחות?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "כמה קל לך לדבר על משאלות?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "איך אתה רוצה שהעתיד שלנו ייראה?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "איך נראה יום ראשון המושלם שלך בבית?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "איך אתה מרגיש לגבי דיבורים מלוכלכים במהלך סקס?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "כמה אשראי אנחנו יכולים להרשות לעצמנו באופן ריאלי?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "כמה זמן אנחנו רוצים לבלות בנפרד?",
    "Wie viel wollen wir insgesamt ausgeben?" to "כמה אנחנו רוצים להוציא בסך הכל?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "איך נמצא זמן למערכת היחסים שלנו ברגע שהתינוק יגיע?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "עד כמה חשוב לך שהרגע יתפוס?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "עד כמה חשוב לך שהאפליקציה תשקף את התחביבים או תחומי העניין שלך?",
    "Wie würdest du sie/ihn nennen?" to "איך היית קורא לו/ה?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "מהי הדרך המועדפת עליך להראות חיבה מחוץ לסקס?",
    "Wildblumen" to "פרחי בר",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "האם אתה רוצה בת או בן? 👶",
    "Wintergarten" to "גן חורף",
    "Winterhochzeit" to "חתונת חורף",
    "Wir bestellen einfach beides" to "אנחנו פשוט מזמינים את שניהם",
    "Wir brauchen ewig" to "זה לוקח לנו נצח",
    "Wir einigen uns nie" to "אנחנו אף פעם לא מסכימים",
    "Wir entscheiden es gemeinsam" to "אנחנו מחליטים ביחד",
    "Wir treffen uns in der Mitte" to "אנחנו נפגשים באמצע",
    "Wir wechseln uns ab" to "אנחנו מתחלפים",
    "Wird stressig" to "נהיה מלחיץ",
    "Wobei lachst du am meisten?" to "מה הכי מצחיק אותך?",
    "Wofür sparen wir gemeinsam?" to "בשביל מה אנחנו חוסכים ביחד?",
    "Wohnzimmer" to "סלון",
    "Woran erinnerst du dich am lebhaftesten?" to "מה אתה זוכר בצורה הכי חיה?",
    "Worauf freust du dich bei uns am meisten?" to "למה אתה הכי מצפה איתנו?",
    "Worte/Komplimente" to "מילים/מחמאות",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "ממה אתה הכי מפחד במערכת היחסים שלנו?",
    "Wünsche? z.B. günstig, draußen" to "משאלות? לְמָשָׁל זול, בחוץ",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "האם תעדיף להציע נישואין בחופשה (כולל נסיעות)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube Music",
    "Zeichne für mich" to "צייר בשבילי",
    "Zeichne mich als Tier — welches wäre ich?" to "צייר אותי כחיה - איזו אני אהיה?",
    "Zeichne unser Gefühl zueinander als Symbol." to "צייר את רגשותינו אחד כלפי השני כסמל.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "צייר את בית החלומות שלנו בשורה אחת. מה הדבר הכי בולט?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "צייר את הדייט הראשון שלנו - מה בהחלט צריך להיות בתמונה?",
    "Zeichnen" to "צייר",
    "Zeit füreinander" to "זמן אחד לשני",
    "Zeit, wenn das Baby schläft" to "הזמן שבו התינוק ישן",
    "Zelten gehen" to "צא לקמפינג",
    "Zitrone" to "לימון",
    "Zu Hause, gemütlich und privat" to "בבית, נעים ופרטי",
    "Zu einem Picknick gehen" to "הולכים לפיקניק",
    "Zu einem ausgefallenen Abendessen gehen" to "הולך לארוחת ערב מפוארת",
    "Zu zweit reisen" to "נסיעות בזוג",
    "Zuhause & Alltag" to "בית וחיי היומיום",
    "Zuhören" to "תקשיב",
    "Zurück" to "חזרה",
    "Zusammen seit" to "ביחד מאז",
    "Zusammen seit (TT.MM.JJJJ)" to "ביחד מאז (DD.MM.YYYY)",
    "Zusammenziehen" to "חוזה",
    "Zustimmen oder Ablehnen" to "מסכים או לא מסכים",
    "Zwei Kreise, die sich überschneiden" to "שני עיגולים חופפים",
    "Zwei Stühle davor" to "שני כיסאות לפניו",
    "Zärtlich sein" to "תהיה עדין",
    "Öfter als ich zugebe" to "יותר פעמים ממה שאני מודה",
    "Über 100€/Monat" to "מעל 100€ לחודש",
    "Über 2000 im Monat" to "למעלה מ-2000 בחודש",
    "Über mich selbst" to "על עצמי",
    "Übernehmen" to "הגש בקשה",
    "Überraschend" to "מפתיע",
    "Überraschung" to "הפתעה",
    "Überspringen" to "דלג",
    "Übertrieben und großartig" to "מוגזם ומדהים",
    "✎ Tippe, um zu antworten" to "✎ הקש כדי להשיב",
    "✨ GFK-Brücke" to "✨ גשר GRP",
)

internal fun localizeHebrewDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_HEBREW_CONTENT)
