package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_IGBO_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "afọ 1-5",
    "1000 - 1500 im Monat" to "1000 - 1500 kwa ọnwa",
    "1000 bis 3000" to "1000 ruo 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 kwa ọnwa",
    "3000 bis 5000" to "3000 ruo 5000",
    "5-10 Jahre" to "afọ 5-10",
    "50-100€/Monat" to "50-100€ kwa ọnwa",
    "Ab 100€" to "Site na 100 €",
    "Ab 500€" to "Site na 500 €",
    "Ab 50€" to "Site na € 50",
    "Ab und zu" to "Mgbe ụfọdụ",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Ego ole ka anyị kwesịrị ime tupu ịzụrụ ihe?",
    "Abbrechen" to "Kagbuo",
    "Abenteuer" to "Njem",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Ihe omume",
    "Alle" to "Ha niile",
    "Alle Pakete" to "ngwugwu niile",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Tụfuo ndị enyi gị niile ma e wezụga ezigbo enyi gị",
    "Alle intimen Momente selbst initiieren" to "Wepụta oge niile na-akpachi anya n'onwe gị",
    "Alles davon" to "Ya niile",
    "Alles, was noch kommt" to "Ihe niile ga-abịa",
    "Alltagsroutine" to "Usoro ụbọchị niile",
    "Alltägliche Berührungen" to "Emetụ aka kwa ụbọchị",
    "Altbau mit Charme" to "Ụlọ ochie nwere ọmarịcha",
    "Am Strand" to "N'akụkụ osimiri",
    "Am liebsten alles zusammen" to "Ọkachamma ihe niile ọnụ",
    "Am selben Tag mit Freunden/Familie" to "Otu ụbọchị ya na ndị enyi/ezinụlọ",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Netherlands",
    "An das Gefühl" to "Nke mmetụta",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "N'ebe ọha na eze nwere ọtụtụ ndị nkiri",
    "An einen Geruch" to "Isi ísì",
    "An einen Song" to "Maka egwu",
    "An etwas, das ich gesagt habe" to "Ihe m kwuru",
    "Analyse starten" to "Malite nyocha",
    "Analysiere eure Muster..." to "Nyochaa ụkpụrụ gị...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Nyochaa azịza gị na nkata gị dịka Gottman na GFK siri kwuo.",
    "Ananas auf der Pizza schmeckt köstlich." to "Pineapple na pizza na-atọ ụtọ.",
    "Android" to "gam akporo",
    "Antwort mit einem Foto" to "jiri foto zaghachi",
    "Antwortähnlichkeit" to "Zaa myirịta",
    "App-Sprache auswählen" to "Họrọ asụsụ ngwa",
    "Auf eine Bootsparty gehen" to "Ịga oriri nke ụgbọ mmiri",
    "Aufmerksamkeit" to "Nlebara anya",
    "Aufräumen und Projekte angehen" to "Hichaa ma rụọ ọrụ",
    "Aufwärmen" to "Na-ekpo ọkụ",
    "Aufwärmen: Einander kennenlernen" to "Na-ekpo ọkụ: Ịmata ibe anyị",
    "Aus dem Urlaub" to "Site na ezumike",
    "Ausgefallener Name" to "Aha mara mma",
    "Ausschlafen und faulenzen" to "Dina ma hie ụra",
    "Ausschlafen und nichts tun" to "Ụra na ime ihe ọ bụla",
    "Aussehen" to "Mpụta",
    "Auto" to "akpaaka",
    "Außenkamin" to "Ebe ọkụ dị n'èzí",
    "BEANTWORTE" to "AZỊA",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonesia",
    "Banane" to "banana",
    "Beantwortet" to "Zara",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Zaa ajụjụ n'otu oge - agaghị ahụ azịza ya ruo mgbe ịmechara.",
    "Beantwortete Fragen" to "zara ajụjụ",
    "Bearbeiten" to "Dezie",
    "Bei Insider-Witzen" to "Maka njakịrị n'ime",
    "Bei Memes" to "Na memes",
    "Bei einer spontanen Berührung" to "Mgbe emetụ ya aka ozugbo",
    "Beide" to "Abụọ",
    "Beide gleich" to "Ha abụọ bụ otu",
    "Beide zusammen" to "Ha abụọ ọnụ",
    "Beide, aber wir tun so als ob nicht" to "Ha abụọ, mana anyị anaghị eme ka à ga-asị",
    "Beides" to "Abụọ",
    "Beides wäre schlimm" to "Ha abụọ ga-adị njọ",
    "Beim Einschlafen nebeneinander" to "Na-ehi ụra n'akụkụ ibe",
    "Beim Reden" to "Mgbe a na-ekwu okwu",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Ebe ndị njem ama ama na-abụ nkụda mmụọ mgbe niile.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Jiri emoji kọwaa ndụ mmekọahụ anyị.",
    "Besser kommunizieren" to "Na-akpakọrịta nke ọma",
    "Bessere Lage" to "Ebe ka mma",
    "Bestellen" to "ịtụ",
    "Besuchte Länder" to "Mba ndị a gara",
    "Besuchte Städte" to "Obodo ndị gara",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Ị masịrị atụmatụ imebiga ihe ókè ma ọ bụ ihe aghụghọ?",
    "Beziehung" to "Mmekọrịta",
    "Bibliothek" to "Ọbá akwụkwọ",
    "Bin manchmal unsicher" to "Obi anaghị adị m mgbe ụfọdụ",
    "Bist du ein Videospiel-Guru?" to "Ị bụ onye guru egwuregwu vidiyo?",
    "Blumenwiese" to "Ala ahịhịa",
    "Bunte Blumenwiese" to "Ala ahịhịa ifuru mara mma",
    "Burger" to "Burgers",
    "Burger King" to "Burger King",
    "Chat" to "Mkparịta ụka",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Mgwakota agwa kuki",
    "Dachgarten mit Lounge" to "Ubi elu ụlọ nwere ụlọ ezumike",
    "Dachterrasse" to "Ulo elu ụlọ",
    "Das Wetter an dem Tag" to "ihu igwe ụbọchị ahụ",
    "Das erste Selfie" to "Selfie mbụ",
    "Das meiste weiß ich" to "Amaara m ọtụtụ n'ime ya",
    "Das oder das?" to "Nke a ma ọ bụ nke ahụ?",
    "Das tägliche Leben" to "Ndụ kwa ụbọchị",
    "Dass Zusagen gehalten werden" to "Emebere nkwa ahụ",
    "Dass alles meinen Stil hat" to "Na ihe niile nwere ụdị m",
    "Dass ich alles erzählen kann" to "Na m nwere ike ikwu ihe niile",
    "Dass ich mich nicht sorgen muss" to "Na enweghị m nchegbu",
    "Dass wir ungestört sind" to "Na anyị enweghị nsogbu",
    "Dein Name" to "Aha gị",
    "Deine Antwort..." to "Azịza gị...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "A na-echekwa azịza gị. Ozugbo Onye Mmekọ mechara ngwugwu ahụ, azịza abụọ a ga-ahụ ọnụ.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "A na-echekwa azịza gị. Ozugbo \${profile.partnerName} mezuru ngwungwu a, a ga-ahụ nzaghachi abụọ ahụ ọnụ.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Mee ka mmekọrịta gị bụrụ ihe na-akpali agụụ mmekọahụ na nke a na-atụghị anya ya",
    "Deine Beziehung stabil und sicher machen" to "Mee ka mmekọrịta gị kwụsie ike na ntụkwasị obi",
    "Deine eigene Antwort" to "Azịza nke gị",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Ọ ka mma ịkọrọ onye gị na ya na-emekọ ihe nzuzo gị",
    "Deinen besten Freund verlieren" to "Enyi gị kacha mma na-efunahụ gị",
    "Denke an dich" to "Chee echiche banyere onwe gị",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Ikiri otu ihe nkiri ugboro abụọ bụ igbu oge.",
    "Der Blick nach draußen" to "Echiche n'èzí",
    "Der Garten" to "Ogige ahụ",
    "Der Ort" to "Ebe ahụ",
    "Der Ring und die Geste" to "mgbanaka na mmegharị ahụ",
    "Der perfekte Heiratsantrag" to "Atụmatụ alụmdi na nwunye zuru oke",
    "Derjenige sein, der umarmt wird" to "Bụrụ onye a na-amakụ",
    "Deutsch" to "German",
    "Diamant" to "diamond",
    "Diamanten im Band" to "diamond n'ime otu ahụ",
    "Die Distanz" to "Ebe dị anya",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Gị na ezinụlọ onye òtù ọlụlụ gị nọrọ ezumike ahụ",
    "Die Gemütlichkeit und Ruhe" to "Nkasi obi na udo",
    "Die Menschen, die darin wohnen" to "Ndị bi na ya",
    "Die Umgebung und Atmosphäre" to "Gburugburu na ikuku",
    "Die Worte und Emotionen" to "Okwu na mmetụta uche",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Ihe ịma aka ntụrụndụ kacha mma",
    "Diejenige sein, die umarmt" to "Bụrụ onye na-amakụ",
    "Direkt ansprechen" to "Adreesị ozugbo",
    "Diskussion" to "Mkparịta ụka",
    "Diskutiere vor dem Kinderkriegen" to "Kwurịtanụ tupu ha amụọ ụmụ",
    "Diskutiert eure Antworten" to "Kwurịta azịza gị",
    "Disney" to "Disney",
    "Doch, schon mal" to "Ee, ee",
    "Draußen mit der Natur als Kulisse" to "N'èzí nwere ọdịdị dị ka ndabere",
    "Drei-Stein-Ring" to "mgbanaka nkume atọ",
    "Du bist dran" to "Ọ bụ oge gị",
    "Du fehlst mir" to "A na m atụ uche gị",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubai, UAE",
    "Dunkles Design" to "Isiokwu gbara ọchịchịrị",
    "Durch Berührung" to "Site na imetụ aka",
    "Durch Worte" to "Site n'okwu",
    "Durch Zeit zu zweit" to "Site na oge ọnụ",
    "Durch kleine Gesten" to "Site na mmegharị ahụ dị nta",
    "Durchgeplant" to "Ezubere nke ọma",
    "ERGEBNISSE" to "Nsonaazụ",
    "Egal, Hauptsache gesund" to "Ihe ọ bụla, isi ihe dị mma",
    "Ehepaar Leben" to "Ndụ di na nwunye",
    "Eher knapp" to "Kama nso",
    "Eher nicht" to "Ọ bụghị nke ukwuu",
    "Eher schwer" to "Kama siri ike",
    "Eher schwierig" to "Kama siri ike",
    "Eher zu" to "Ndị ọzọ dị ka",
    "Eifersucht ist ein Zeichen von Liebe." to "Ekworo bụ ihe ịrịba ama nke ịhụnanya.",
    "Eigenes Gemüsebeet" to "Patch inine nke ya",
    "Ein Abenteuer in einer neuen Stadt" to "Njem njem n'ime obodo ọhụrụ",
    "Ein Anker" to "Arịlịka",
    "Ein Balkon oder Garten" to "mbara ihu ma ọ bụ ubi",
    "Ein Filmabend" to "Abalị ihe nkiri",
    "Ein Harmony-Meilenstein eurer Liebe." to "Ihe omume nkwekọ n'ịhụnanya gị.",
    "Ein Herz" to "Obi",
    "Ein Herz an der Tür" to "Obi n'ọnụ ụzọ",
    "Ein Jahr lang eine Fernbeziehung führen" to "Nwee mmekọrịta dị anya ruo otu afọ",
    "Ein Kindheitsessen" to "Nri nwata",
    "Ein Live-Musik-Konzert besuchen" to "Gaa egwu egwu dị ndụ",
    "Ein Museum besuchen" to "Gaa na ụlọ ngosi ihe mgbe ochie",
    "Ein Spieleabend" to "Abalị egwuregwu",
    "Ein Spieleabend mit Freunden" to "Abalị egwuregwu ya na ndị enyi ya",
    "Ein Urlaubsfoto" to "Foto ezumike",
    "Ein aktives Abenteuer" to "Njem njem na-arụ ọrụ",
    "Ein entspannender Spa-Tag" to "Ụbọchị ezumike na-atụrụ ndụ",
    "Ein ganz normaler Alltagstag" to "Ụbọchị na-adị kwa ụbọchị",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Mgbede mara mma n'ime ụlọ n'oge égbè eluigwe",
    "Ein gemütliches Date drinnen" to "Ụbọchị mara mma n'ime ụlọ",
    "Ein lustiges Bild" to "Foto na-atọ ọchị",
    "Ein paar Handyfotos reichen" to "Foto ekwentị ole na ole ezuola",
    "Ein paar Stunden" to "Aka elekere ole na ole",
    "Ein paar kulturelle Anklänge sind okay" to "Ntụaka omenala ole na ole dị mma",
    "Ein romantischer Abend" to "Mgbede ihunanya",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Nri abalị ọkụ kandụl ihunanya",
    "Ein romantisches Bild" to "Foto ihunanya",
    "Ein romantisches Picknick an einem schönen Ort" to "picnic ihunanya na ebe mara mma",
    "Ein schwerer Moment, den wir geschafft haben" to "Oge siri ike nke anyị jisiri ike",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Ezigbo ụbọchị n'èzí n'okpuru ọnwa",
    "Ein ungewöhnliches Gericht" to "Nri pụrụ iche",
    "Ein zufälliger Schnappschuss" to "Ihe onyonyo enweghị usoro",
    "Einander kennenlernen" to "Ịmata ibe anyị",
    "Eine Autoreise" to "Njem okporo ụzọ",
    "Eine Brücke" to "Akwa akwa",
    "Eine Date-Nacht unter den Sternen" to "Abalị ụbọchị n'okpuru kpakpando",
    "Eine Million Dollar gewinnen" to "Nweta otu nde dollar",
    "Eine Million Dollar verdienen" to "Mee otu nde dollar",
    "Eine Nacht in einem Club" to "Abalị na klọb",
    "Eine Schokoladenverkostung" to "Nri chocolate",
    "Eine Wanderung mit Panoramablick machen" to "Jiri echiche panoramic were mee njem",
    "Eine Weinverkostung" to "Ọnụ ọnụ mmanya",
    "Eine gemeinsame Reise" to "Njem ọnụ",
    "Eine gemütliche Nacht zu Hause" to "Abalị mara mma n'ụlọ",
    "Eine neue Sprache zu lernen ist einfach." to "Ịmụ asụsụ ọhụrụ dị mfe.",
    "Einen Film anschauen" to "Lelee ihe nkiri",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Anaghị agwa ibe anyị okwu ma ọlị otu ọnwa",
    "Einen Tanzkurs besuchen" to "Were klas ịgba egwu",
    "Einen Vergnügungspark erkunden" to "Chọgharịa ogige ntụrụndụ",
    "Einen Wellness-Tag" to "Ụbọchị ahụike",
    "Einen sehr emotionalen Partner haben" to "Inwe ezigbo onye mmekọ",
    "Einen sehr logischen Partner haben" to "Inwe onye mmekọ ezi uche dị na ya",
    "Einer zahlt alles" to "Otu onye na-akwụ ihe niile",
    "Einfach mehr Alltag" to "Naanị karịa ndụ kwa ụbọchị",
    "Einfach nebeneinander sein" to "Naanị na-esote ibe gị",
    "Einfach und intim" to "Dị mfe ma nwee mmekọrịta chiri anya",
    "Einige Dinge für dich behalten" to "Debe ihe ụfọdụ n'onwe gị",
    "Einmal" to "Otu ugboro",
    "Eins, das nur wir kennen" to "Otu nke naanị anyị maara",
    "Englisch" to "Bekee",
    "Entspannte Hängematte" to "hammock izu ike",
    "Entspannung" to "izu ike",
    "Erdbeere" to "Strawberry",
    "Erfolgreich" to "Emeela nke ọma",
    "Ergebnisse" to "Nsonaazụ",
    "Erst bei sehr großen Summen" to "Naanị maka nnukwu ego",
    "Erst nur enge Freunde/Familie" to "Naanị ezigbo ndị enyi/ezinụlọ na mbụ",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Ọ na-akpasu m iwe mgbe onye otu m na-ewe ogologo oge iji zaghachi ozi.",
    "Essen & Genuss" to "Nri na ụtọ",
    "Essensvorlieben" to "Mmasị nri",
    "Etwa eine Woche später, erst mal nur wir" to "Ihe dị ka otu izu ka e mesịrị, naanị anyị na mbụ",
    "Etwas Neues ausprobieren" to "Gbalịa ihe ọhụrụ",
    "Etwas ganz anderes" to "Ihe dị nnọọ iche",
    "Etwas sehr Scharfes" to "Ihe dị nkọ",
    "Etwas, das ich selbst gern erfinde" to "Ihe masịrị m chepụta onwe m",
    "Etwas, eine kleine Note wäre schön" to "Ihe, ntakịrị ndetu ga-adị mma",
    "Familie" to "Ezinụlọ",
    "Familie/Freunde" to "Ezinụlọ/Enyi",
    "Familienmensch" to "Nwoke ezinụlọ",
    "Farbedelstein" to "Nkume bara nnukwu uru",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Mgbasa ozi TV na-atọ ụtọ ikiri mgbe ụfọdụ.",
    "Fertig" to "Emeela",
    "Fertig!" to "Emeela!",
    "Feste Date-Nights" to "Abalị ụbọchị edobere",
    "Feuerstelle" to "Ọkụ ọkụ",
    "Filigran & schlicht" to "Mpempe akwụkwọ & dị mfe",
    "Filme/Serien" to "Ihe nkiri/usoro",
    "Formuliere um..." to "Tụgharịa...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Tụgharịa akwụkwọ gị n'ụzọ na-adịghị eme ihe ike: nleba anya, mmetụta, mkpa, arịrịọ.",
    "Frage hinzufügen" to "Tinye ajụjụ",
    "Fragen & Spiele" to "Ajụjụ & Egwuregwu",
    "Fragen für jede Gelegenheit" to "Ajụjụ maka oge ọ bụla",
    "Freizeitpark" to "ogige ntụrụndụ",
    "Freunde treffen" to "Zute ndị enyi",
    "Freundschaften mit Ex-Partnern sind okay." to "Enyi na exes adịghị mma.",
    "Früh aufstehen" to "Bilie n'isi ụtụtụ",
    "Fußbodenheizung" to "Igwe ọkụ n'okpuru ala",
    "Führen wir getrennte oder gemeinsame Konten?" to "Anyị nwere akaụntụ dị iche ma ọ bụ nkwonkwo?",
    "Für dich empfohlen" to "Akwadoro maka gị",
    "Für die Zukunft" to "Maka ọdịnihu",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Ọnweghị ajụjụ ma ọ bụ egwuregwu dakọtara ahụrụ maka ọchụchọ a.",
    "Für immer" to "Ruo mgbe ebighị ebi",
    "Fürsorglichkeit" to "Ilekọta",
    "GFK-Brücke" to "akwa mmiri GRP",
    "Galerie" to "Ụlọ ihe ngosi nka",
    "Gar nicht, der Moment gehört uns" to "Ọbụghị ma ọlị, oge a bụ nke anyị",
    "Gar nichts tun" to "Emela ihe ọ bụla",
    "Geduld" to "Ndi",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Gaa n'isi ụtụtụ ka ịhụ ọwụwa anyanwụ",
    "Geht so" to "na-aga otu a",
    "Geister existieren wirklich." to "Mụọ dị adị n'ezie.",
    "Gelassenheit" to "Obi iru ala",
    "Gelbgold" to "Ọlaedo edo edo",
    "Geld & Finanzen" to "Ego & Ego",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Gagharịa ụwa ọnụ, chọpụta omenala na nri ọhụrụ",
    "Gemeinsam ein Lego bauen" to "Mee otu Lego ọnụ",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Gbalịa mee ihe oriri ọhụrụ ọnụ na kichin",
    "Gemeinsame Konten" to "Akaụntụ ekekọrịtara",
    "Gemeinsame Nächte" to "Abalị ọnụ",
    "Gemeinsame Tage" to "Ụbọchị ọnụ",
    "Gemischt" to "agwakọtara",
    "Gemüsebeet" to "Mpempe akwụkwọ nri",
    "Gemütliche Feuerstelle" to "Ebe ọkụ dị mma",
    "Gesprächsanreger" to "Mmalite mkparịta ụka",
    "Getrennte Konten" to "Akaụntụ dị iche",
    "Getrennte Urlaube tun einer Beziehung gut." to "ezumike dị iche iche dị mma maka mmekọrịta.",
    "Gewächshaus" to "griin haus",
    "Glasfassade" to "Facade iko",
    "Gleichgültigkeit" to "Enweghị mmasị",
    "Glücklich und frei" to "Obi ụtọ na efu",
    "Gourmet Eis-Sorten" to "Ụdị ice cream gourmet",
    "Gravur innen" to "Ihe osise n'ime",
    "Grillplatz" to "Mpaghara mmanya",
    "Groß & üppig" to "Nnukwu & ahịhịa",
    "Große Familie" to "Nnukwu ezinụlọ",
    "Große Feier" to "Nnukwu emume",
    "Große Fenster" to "Window buru ibu",
    "Große Fensterfront" to "Nnukwu windo n'ihu",
    "Großer Außenpool" to "Nnukwu ọdọ mmiri dị n'èzí",
    "Großer Garten" to "Ogige buru ibu",
    "Großer Stein" to "Nkume buru ibu",
    "Größere Küche" to "kichin buru ibu",
    "Gutes Essen" to "Ezi nri",
    "Habe ich" to "Emere m",
    "Habe ich noch nie" to "Enweghị m",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Ị chọpụtala ndịiche dị ịtụnanya ọ bụla? Kwuo ihe mere nhọrọ ụfọdụ ji amasị gị!",
    "Haus am See" to "Ụlọ dị n'akụkụ ọdọ mmiri",
    "Haus/Wohnung" to "Ụlọ/ụlọ",
    "Hazelnut" to "Hazelnut",
    "Heimkino" to "Ụlọ ihe nkiri",
    "Herzhaft" to "Obi ụtọ",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Enweghị ihe ọ bụla ebe a ugbu a.\n Gbanwee nzacha ma ọ bụ họrọ isiokwu dị iche.",
    "Hilfe im Alltag" to "Enyemaka na ndụ kwa ụbọchị",
    "Himbeere" to "Raspberry",
    "Hinzufügen" to "Tinye",
    "Hobbys" to "Ihe omume ntụrụndụ",
    "Hochzeitssträuße" to "bouquet agbamakwụkwọ",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Nganko Ụlọ Hogwarts: Ebee ka I nọ?",
    "Home" to "Ụlọ",
    "Hot Tub" to "Ebe a na-ekpo ọkụ",
    "Humor" to "ọchị",
    "Hund" to "Nkịta",
    "Hängematte" to "Hammock",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Ọ ga-amasị gị akwụkwọ ozi edere dịka akụkụ nke atụmatụ a?",
    "IKEA" to "IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Ọ na-amasị m ịga ije n'ogige ntụrụndụ karịa ịga sinima.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Ọ dịtụbeghị mgbe m dara n'ụra na sinima.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Ọ na-atọ m ụtọ iso onye mụ na ya na-emekọrịta ihe ma ọ bụ ihe omume ọhụrụ.",
    "Ich finde eine Alternative" to "Aga m achọta ụzọ ọzọ",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Ọ na-atọ m ụtọ iso onye mụ na ya na-emekọ ihe na-aga ụlọ oriri na ọṅụṅụ ọhụrụ kama ịga otu ebe mgbe niile.",
    "Ich habe noch nie" to "enwebeghị m",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Ọ dịtụbeghị mgbe m tụrụ egwu igwe ihe na-agbagharị agbagharị wee banye na ya.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Enwetabeghị m tiketi Fast Pass n'ihi na enweghị m ndidi.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Ọ dịtụbeghị mgbe m kagburu atụmatụ ịnọrọ n'ụlọ na ikiri ihe nkiri TV.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Ọ dịbeghị mgbe m chere akwụkwọ ozi m sitere na Hogwarts.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Ọ dịtụbeghị mgbe m kwuru na Slytherin adịchaghị njọ otú ahụ.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Ọ dịtụbeghị mgbe m kwuru na m merela agadi maka ihe nkiri Disney (ma nwee mmasị na ha na nzuzo).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Ọ dịtụbeghị mgbe m kpachapụrụ anya gbatuo onye nwere tank na-acha anụnụ anụnụ na Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Ọ dịtụbeghị mgbe m bere ákwá na ihe nkiri Disney.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Ọ dịtụbeghị mgbe m kpuchiri anya m mgbe m na-ekiri ihe nkiri egwu.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Echefubeghị m ichekwa egwuregwu na awa agamnihu m tụfuru.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Ọ dịbeghị mgbe m si n'ọnụ ụlọ pụọ n'oge ihere na-emenye ihere.",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Emebeghị m ihe ọchị mgbe m na-ese foto rolacoaster.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Ọ dịtụbeghị mgbe m na-egwu egwuregwu n'ime abalị wee kwara ụta na ike gwụrụ m n'echi ya.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Enwetụbeghị m google ngwụcha ihe nkiri n'ihi na enweghị m ike ichere.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Ọ dịtụbeghị mgbe ọ dị m ka m guzo na ihe nkiri.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Ọ dịtụbeghị mgbe m gafere mmalite nke usoro ọkacha mmasị m.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Ọ dịtụbeghị mgbe m kekọrịtara paswọọdụ Netflix onye ọ bụla.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Ọ dịtụbeghị mgbe m gere egwu egwu egwuregwu mgbe m na-arụ ọrụ ma ọ bụ na-agụ akwụkwọ.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Ọ dịtụbeghị mgbe m tara onye njikwa ahụ ụta mgbe m furu efu.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Ọ dịtụbeghị mgbe m ji iwe tufuo kiiboodu ma ọ bụ njikwa.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Echefuru m uwe mmiri na igwe na-asa ákwà ruo ụbọchị ole na ole.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Enwetụbeghị m ezigbo ego maka ihe ịchọ mma n'egwuregwu.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Ahụtụbeghị m ụgbọ ala ná mba ọzọ.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Enwetụbeghị m egwu Disney n'ime mmiri ịsa ahụ.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Ahụtụbeghị m ụgbọ ala eletrik.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Ọ dịtụbeghị mgbe m ji mascot ogige see foto.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Ọ dịtụbeghị mgbe m gụrụ anụ ụlọ n'aha agwa Hogwarts.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Ọ dịtụbeghị mgbe m tụfuru popcorn n'ụlọ ihe nkiri ma rie ya.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Ejibeghị m okwu sitere na Master Yoda sitere na Star Wars na ndụ kwa ụbọchị.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Ọ dịtụbeghị mgbe m zụtara ihe ncheta dị oke ọnụ na ogige ntụrụndụ.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Ọ dịtụbeghị mgbe m nyere ntụnye ihe nkiri nke onye nke ọzọ hụrụ na ọ jọgburu onwe ya.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Ahụtụbeghị m Oscar ka ọ na-ebi n'etiti abalị.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Akagbubeghị m usoro n'ihi na oge ikpeazụ dị njọ.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Ahụtụbeghị m ogologo oge nke usoro usoro n'otu ụbọchị.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Ọ dịtụbeghị mgbe m meriri onye isi na nnwale mbụ wee dị m ka chi.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Ahụtụbeghị m onye na-ajụ oyi karịa dike.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Amatabeghị m agwa Toy Story n'ime ihe egwuregwu ụmụaka nke m.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Emebeghị m agwa n'ime RPG dị ka m.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Enwetụbeghị m churro n'ogige ntụrụndụ isiokwu.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Ahụtụbeghị m ihe nkiri Disney ugboro atọ n'usoro.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Enwetụbeghị m egwu Disney na-adọrọ adọrọ otu izu.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Ahụtụbeghị m ihe nkiri naanị n'ihi otu onye na-eme ihe nkiri.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Ọ dịtụbeghị mgbe m gere egwu egwu ihe nkiri na-emegharị ruo ọtụtụ awa.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Ahụbeghị m ihe na-emebi ihe nkiri wee kwaa ụta ozugbo.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Ahụtụbeghị m enyi na-asụ asụsụ ọzọ.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Enwetụbeghị m enyi m kwagara obodo ọzọ.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Emebeghị m marathon ihe nkiri Harry Potter na ekeresimesi.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Ahụtụbeghị m ihe nkiri Marvel ruo ọgwụgwụ naanị n'ihi ihe ngosi mgbe kredit gachara.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Ọ dịtụbeghị mgbe m kpachapụrụ anya kpasuo NPC iwe (agwa anaghị eme egwuregwu).",
    "Ich habe noch nie einen Nachtzug genommen." to "Enwetụbeghị m ụgbọ oloko abalị.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Enwetụbeghị m ule ịntanetị iji chọpụta ụlọ Hogwarts m.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Ọ dịtụbeghị mgbe m ehichapụrụ mgbasa ozi soshal midia n'ihi na ọ nwetaghị mmasị zuru oke.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Ahụtụbeghị m otu ụbọchị na ogige ntụrụndụ ụbọchị kacha mma n'afọ.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Ahụtụbeghị m ogige ntụrụndụ ma nọrọ ebe ahụ site n'ụtụtụ ruo n'abalị.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Ọ dịtụbeghị mgbe m hapụrụ Transformers ma ọ bụ ịgba ọsọ Marvel masịrị m kpamkpam.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Ọ dịtụbeghị mgbe m tụpụrụ iwe ma kwụsị egwuregwu ahụ.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Agụtụbeghị m akwụkwọ mpịakọta Harry Potter ọ bụla.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Ọ dịtụbeghị mgbe m na-ekwu maka agwa ọkacha mmasị m na usoro.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Ọ dịtụbeghị mgbe m rọrọ nrọ ịkpọ Quidditch.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Enwetụbeghị m google nzuzo ka esi edozi ọkwa siri ike.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Ọ dịtụbeghị mgbe m tụrụ anya na nzuzo na anụ ụlọ m nwere ike ikwu okwu dị ka na Disney.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Ọ dịbeghị mgbe m wepụrụ onye isi ọdọ mmiri na Sims.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Ọ dịtụghị mgbe m tụfuru agba m n'ime simulator 3D.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Ọ dịtụbeghị mgbe m gbara n'òtù egwuregwu mahadum mahadum.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Ọ dịtụbeghị mgbe m chere n'ahịrị ruo ihe karịrị awa abụọ maka otu mmasị.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Enwetabeghị m ihe bara uru m n'ụgbọ mmiri.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Ọ dịtụbeghị mgbe mụ na enyi m rụrụ ụka banyere ụlọ kacha mma.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Ọ dịtụbeghị mgbe m mere ka à ga-asị na m nwere ikike anwansi dị ka Elsa.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Ọ dịtụbeghị mgbe m chịrị ọchị nke ukwuu nke na agbaghara m otu ihe nkiri dị mkpa na fim.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Ahụtụbeghị m adrenaline nke na m chọrọ ozugbo ịnya ụgbọ ala ọzọ.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Ọ dịtụbeghị mgbe m nwara iso anụmanụ dị ka Snow White bụrụ abụ.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Ọ dịtụbeghị mgbe m rọrọ nrọ maka njem na Disneyland.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Ọ dịtụbeghị mgbe m rọrọ nrọ ịnya ụgbọ mmiri Jurassic Park.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Ọ dịtụbeghị mgbe m tiri mkpu n'oké ụjọ maka ịwụli elu n'ime egwuregwu.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Ọ dịtụbeghị mgbe m bewere ihe nkiri TV mechara.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Ọ dịtụbeghị mgbe m kagburu ụbọchị m ga-anọ n'ụlọ.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Ọ dịtụbeghị mgbe m degharịrị ozi ugboro iri.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Ahụtụbeghị m ekwentị onye ibe m na nzuzo.",
    "Ich habe noch nie!" to "Enwetụbeghị m!",
    "Ich habe!" to "Enwere m!",
    "Ich lache viel mit meinem Partner." to "Mụ na onye ibe m na-achị ọchị nke ukwuu.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Ọ na-amasị m ịmata ihe omume ntụrụndụ na mmasị onye ọlụlụ m.",
    "Ich liebe es" to "Ahụrụ m ya n'anya",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Ọ na-amasị m iso onye mụ na ya na-eme ihe nkiri na-ekiri ihe ọ bụla n’ime anyị ahụtụbeghị mbụ.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Ọ na-amasị m ịkọrọ onye m na-egwu egwu kacha amasị m.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Ọ dịtụbeghị mgbe m ga-agba ọsọ iji nweta ụgbọ elu njikọ.",
    "Ich plane gerne Dates mit meinem Partner." to "Ọ na-amasị m iso onye mụ na ya na-emekọ ihe.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Ana m ebute ụzọ iso onye mụ na ya na-anọrị na-anọrị ọbụna mgbe m ji ọrụ n'aka.",
    "Ich schreibe meinem Partner jeden Tag." to "Ana m ezigara onye mụ na ya ozi ozi kwa ụbọchị.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Ọ na-amasị m isoro onye otu m na-ekerịta memes na ihe ọchị.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Ọ na-amasị m ịkọrọ onye ọlụlụ m nkọwa niile nke ụbọchị m.",
    "Ich würde es nie tun" to "Agaghị m eme ya",
    "Ich übe noch" to "M ka na-eme ya",
    "Ideen generieren" to "Mepụta echiche",
    "Im Haushalt helfen" to "Enyemaka gburugburu ụlọ",
    "In Chat einfügen" to "Tinye na nkata",
    "In Stille nebeneinander" to "N'ịdị jụụ n'akụkụ ibe ya",
    "In den Bergen" to "N'ime ugwu",
    "In eine Bar gehen" to "Gaa n'ụlọ mmanya",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Ịga n'ụlọ mmanya dị n'akụkụ mmiri ka ikiri ọdịda anyanwụ",
    "In einem feinen Restaurant essen gehen" to "Na-eri nri n'ụlọ nri mara mma",
    "In einen Coffeeshop gehen" to "Gaa n'ụlọ ahịa kọfị",
    "In einer Beziehung sollte man alles voneinander wissen." to "Na mmekọrịta unu kwesịrị ịma ihe niile gbasara ibe gị.",
    "Infinity-Pool" to "ọdọ mmiri enweghị ngwụcha",
    "Innenpool" to "ọdọ mmiri ime ụlọ",
    "Intelligenz" to "ọgụgụ isi",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Naanị inwe oge chiri anya mgbe onye gị na ya na-emekọrịta ihe malitere ha",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Koodu ọkpụkpọ: HRM-8731 · ihe niile emechiri",
    "Island" to "Iceland",
    "Ist okay für mich" to "Ọ dị m mma",
    "Ist schon perfekt" to "Ọ zuru oke",
    "Ja, Traditionen einbinden" to "Ee, tinye omenala",
    "Ja, absolut" to "Ee, n'ezie",
    "Ja, etwas zum Lesen und Aufbewahren" to "Ee, ihe a ga-agụ ma debe",
    "Ja, genug" to "Ee, ezuola",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Ee, n'obodo ma ọ bụ ihe nkiri na-atọ ụtọ",
    "Ja, in- und auswendig" to "Ee, n'ime na n'èzí",
    "Ja, komplett überraschend" to "Ee, ọ tụrụ n'anya kpamkpam",
    "Ja, perfekt" to "Ee, zuru oke",
    "Ja, sie gehören zur Familie!" to "Ee, ha bụ ezinụlọ!",
    "Ja, sofort teilen" to "Ee, kesaa ozigbo",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Ee, anyị ga-ahụ na oge ezinụlọ bụ ihe kacha mkpa.",
    "Jacuzzi" to "Jacuzzi",
    "Jahr zusammen 🎉" to "afọ ọnụ 🎉",
    "Jahre zusammen 🎉" to "Afọ ọnụ 🎉",
    "Jeder zahlt 50%" to "Onye ọ bụla na-akwụ 50%",
    "Junge" to "Nwa nwoke",
    "Kamin" to "Ebe ọkụ",
    "Karriere & Erfolg" to "Ọrụ & Ọganiihu",
    "Kategorien" to "Otu",
    "Katze" to "Nwamba",
    "Keine Musik" to "Enweghị egwu",
    "Keine Party nötig, privat halten" to "Enweghị mkpa maka oriri, debe ya na nzuzo",
    "Keine Privatsphäre" to "Enweghị nzuzo",
    "Keine Treffer gefunden" to "Ọnweghị ihe egwuregwu ahụrụ",
    "Keiner" to "Ọ nweghị",
    "Keiner von uns" to "Ọ dịghị onye n'ime anyị",
    "Kennst du die Essensvorlieben deines Partners?" to "Ị maara ọkacha mmasị onye gị na ya na-eri nri?",
    "Kino" to "sinima",
    "Kirchlich" to "Ekliziastis",
    "Klassisch Solitär" to "Omuma solitaire",
    "Klassisch gebunden" to "Kekọtara na oge gboo",
    "Klein & zart" to "Obere & siri ike",
    "Kleine Geschenke" to "Obere onyinye",
    "Kleine Runde" to "Obere otu",
    "Kochen und Freunde einladen" to "Isi nri na ịkpọ ndị enyi",
    "Kochkurs" to "Klas isi nri",
    "Kommt auf den Tag an" to "dabere na ụbọchị",
    "Kommt darauf an" to "Ọ dabere",
    "Kommt drauf an" to "Ọ dabere",
    "Kommt mit" to "Soro m",
    "Konzert" to "Ihe nkiri",
    "Kräftige Farben" to "Agba siri ike",
    "Kräuterbeet" to "akwa akwa",
    "Kultur & Sehenswürdigkeiten" to "Omenala & Nlegharị anya",
    "Kuscheln" to "Nchikota",
    "Kuss senden" to "Zipụ nsusu ọnụ",
    "Körperliche Annäherung" to "Ụzọ anụ ahụ",
    "Körperliche Nähe" to "nso nso nke anụ ahụ",
    "Küche" to "kichin",
    "Land" to "Obodo",
    "Landhaus" to "Ụlọ obodo",
    "Landhausstil" to "Ụdị ụlọ obodo",
    "Lange wach bleiben" to "Nọrọ abalị",
    "Lappland" to "Lapland",
    "Lappland, Finnland" to "Lapland, Finland",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Kwe ka onye mmekọ gị kpalie gị ịbụ onye kacha mma",
    "Lehne ab" to "Ajụ",
    "Leichtigkeit" to "Ìhè",
    "Leidenschaft" to "Mmasị",
    "Liebe im Gleichgewicht" to "Ịhụnanya n'ụzọ ziri ezi",
    "Liebe sie, macht mehr Spaß" to "Hụ ha n'anya, na-atọ ụtọ karịa",
    "Lieber durchgeplant oder spontan?" to "Ọ ga-akara gị mma ime atụmatụ ya ma ọ bụ na mberede?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Ọ ga-amasị gị ịnwe mgbede dị jụụ maka mmadụ abụọ ma ọ bụ gị na ndị mmadụ?",
    "Lieber nicht" to "Ọ ka mma",
    "Lieber vorher grob absprechen" to "Ọ ka mma ka anyị kparịta ihe ozugbo",
    "Lokal einkaufen" to "ịzụ ahịa na mpaghara",
    "London" to "London",
    "London, England" to "London, England",
    "Lügen" to "Ụgha",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Ị masịrị atụmatụ ọha ma ọ bụ nkeonwe?",
    "Malediven" to "Maldives",
    "Man sollte nie streitend einschlafen." to "I kwesịghị ịrahụ ụra na-arụ ụka.",
    "Mango Sorbet" to "Mango Sorbet",
    "Markant & breit" to "Na-egbu ma gbasaa",
    "Marken & Alltag" to "Ụdị & ndụ kwa ụbọchị",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "ogige Mediterranean",
    "Mehr Unterstützung" to "Nkwado ndị ọzọ",
    "Mehr gemeinsame Zeit" to "Ọtụtụ oge ọnụ",
    "Mehr zuhören" to "Gee ntị ọzọ",
    "Mehrgenerationenhaus" to "Ụlọ ọtụtụ ọgbọ",
    "Mein Arbeitsplatz" to "Ebe ọrụ m",
    "Mein Partner" to "Onye ibe m",
    "Mich überraschen" to "Iju m anya",
    "Minimalistisches Interieur" to "Ime nke kacha nta",
    "Missverständnisse" to "nghọtahie",
    "Mit Familie und engen Freunden" to "Mụ na ezinụlọ na ezigbo ndị enyi",
    "Mit Kompromissen" to "Site na nkwekọrịta",
    "Mitgefühl" to "Obi ebere",
    "Mittelweg mit besonderen Details" to "Ebe etiti nwere nkọwa pụrụ iche",
    "Modern geometrisch" to "geometric ọgbara ọhụrụ",
    "Moderne Grillstation" to "Ọdụ mmiri ihe eji eme ihe ọgbara ọhụrụ",
    "Moderner Name" to "Aha ọgbara ọhụrụ",
    "Moderner Solitär" to "Solitaire ọgbara ọhụrụ",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "Wepụta oge",
    "Momente" to "oge",
    "Monaco" to "Monaco",
    "Moralische Werte" to "Ụkpụrụ omume",
    "Museum" to "Ụlọ ihe ngosi nka",
    "Musik" to "Egwu",
    "Mut" to "Obi ike",
    "Mädchen" to "Ụmụ agbọghọ",
    "Möbelhaus" to "Ụlọ ahịa ngwá ụlọ",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Ị ji n'aka na ị chọrọ ịhapụ ajụjụ ahụ? Ọganihu gị gara aga ka echekwara.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Ọ ga-amasị gị ka etinye anụ ụlọ n'ime ngwa ahụ?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Chọrọ ka ekesaa oge ahụ ozugbo na soshal midia?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Anyị nwere ike ị nweta ego",
    "Müssen es planen" to "Kwesịrị ịhazi ya",
    "Müssen sparen" to "Kwesịrị ịchekwa",
    "Nachricht an" to "Ozi",
    "Name Partnerin" to "Aha onye mmekọ",
    "Namen und Startdatum eurer Beziehung." to "Aha na ụbọchị mmalite nke mmekọrịta gị.",
    "Natursteinfassade" to "ihu nkume okike",
    "Naturteich" to "ọdọ mmiri eke",
    "Nein, einfach halten" to "Mba, jide naanị ya",
    "Nein, erstmal privat halten" to "Mba, debe ya na nzuzo ugbu a",
    "Nein, lieber vor Ort" to "Mba, ka mma na saịtị",
    "Nein, modern halten" to "Mba, mee ka ọ bụrụ ọgbara ọhụrụ",
    "Nein, nur wir" to "Mba, naanị anyị",
    "Nein, zu ablenkend" to "Mba, na-adọpụ uche ya",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Ụlọ ọhụrụ nwere ụlọ mara mma",
    "Neubau mit Technik" to "Ụlọ ọhụrụ nwere teknụzụ",
    "Neue Liebe, neue Erfahrungen" to "Ịhụnanya ọhụrụ, ahụmihe ọhụrụ",
    "Neues Hobby" to "Ihe omume ntụrụndụ ọhụrụ",
    "Neues Spiel" to "Egwuregwu ọhụrụ",
    "Neugier" to "Ịchọ ịmata ihe",
    "New York" to "New York",
    "New York, USA" to "New York, USA",
    "Nicht mein Fall" to "Ọ bụghị iko tii m",
    "Nicht nötig, lieber klassisch bleiben" to "Ọ dịghị mkpa, ọ ka mma ịnọrọ nke ọma",
    "Nichts — es passt so" to "Ọ dịghị ihe - ọ dabara",
    "Nie wieder Burger" to "Emela burger ọzọ",
    "Nie wieder Pizza" to "Emela pizza ọzọ",
    "Niemand" to "Ọ dịghị onye",
    "Niemand ohne Plan" to "Ọ dịghị onye na-enweghị atụmatụ",
    "Nike" to "Nike",
    "Nizza" to "mara mma",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "O nwebeghị oge.\nWepụta ahụmịhe mbụ gị 💞",
    "Nur bei wichtigen Themen" to "Naanị maka isiokwu ndị dị mkpa",
    "Nur wir beide" to "Naanị anyị abụọ",
    "Nähe & Intimität" to "Mkpebi na mmekọrịta chiri anya",
    "Obstgarten" to "Osisi ubi",
    "Oder" to "Ma ọ bụ",
    "Offene Küche" to "Mepee kichin",
    "Offene Wohnküche" to "Mepee kichin/ime ụlọ",
    "Ohne Stein" to "Enweghị nkume",
    "Open End" to "ngwụcha meghere",
    "Outdoor-Küche" to "kichin dị n'èzí",
    "Outdoor-Sofa" to "Sofa dị n'èzí",
    "Outdoor-Whirlpool" to "Ọdụ mmiri dị n'èzí",
    "Ovaler Diamant" to "diamond oval",
    "Paar" to "Mmakọ",
    "Paar-Statistiken" to "Ọnụ ọgụgụ di na nwunye",
    "Paris" to "Paris",
    "Paris, Frankreich" to "Paris, France",
    "Partner" to "Onye mmekọ",
    "Partner-Simulator" to "Onye mmekọ simulator",
    "Partnerin" to "Onye mmekọ",
    "Party Edition" to "Mbipụta Party",
    "Party Edition II" to "Mbipụta Party II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Anumanu ọ̀ dabara na ndụ anyị kwa ụbọchị?",
    "Pasta" to "pasta",
    "Pastell" to "pastel",
    "Penthouse mit Ausblick" to "Penthouse nwere nlele",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pergola nwere ụlọ ezumike",
    "Pfingstrosen" to "Peonies",
    "Pinguin" to "Penguin",
    "Pistazie" to "Pistachio",
    "Pizza" to "Pizza",
    "Pizzaofen" to "oven Pizza",
    "Platin" to "Platinum",
    "PlayStation" to "PlayStation",
    "Pool" to "ọdọ mmiri",
    "Pop" to "Pop",
    "Prasselnder Kamin" to "Ebe ọkụ na-ebigbọ",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Princesses, Pirates na Fary Dust: Disney Quiz",
    "Privater Innenhof" to "Ogige nkeonwe",
    "Profil" to "Profaịlụ",
    "Profil bearbeiten" to "Dezie profaịlụ",
    "Prozentual nach Einkommen" to "Pasent dabere na ego ha nwetara",
    "Quiz verlassen" to "Kwụsị ajụjụ",
    "Quiz verlassen?" to "Hapụ ajụjụ?",
    "Rausgehen in die Natur" to "Pụta n'ime okike",
    "Reden vor ..." to "Na-agwa...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Hazie ụbọchị ma ọ bụ oge ọnụ",
    "Reisen" to "Njem",
    "Reiseziele" to "Ebe njem",
    "Respektlosigkeit" to "enweghị nkwanye ùgwù",
    "Restaurant" to "Ụlọ oriri na ọṅụṅụ",
    "RnB / Soul" to "RnB / Mkpụrụ obi",
    "Rock" to "Nkume",
    "Rom" to "Rome",
    "Rom, Italien" to "Rome, Italy",
    "Romantik" to "Mkparịta ụka",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Mmegharị ahụ ihunanya dị ka ozi, ndetu ma ọ bụ onyinye na-eme m obi ụtọ.",
    "Romantische Stimmung" to "Ọnọdụ ihunanya",
    "Roségold" to "ọla edo edo",
    "Ruhig zu zweit" to "Dịrị jụụ maka abụọ",
    "Runder Diamant" to "diamond gburugburu",
    "Salted Caramel" to "Caramel nnu",
    "Sammle Ideen..." to "Chịkọta echiche...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Greece",
    "Saphir" to "Safaịre",
    "Saunahaus" to "Ụlọ sauna",
    "Schickes Restaurant oder Hotel" to "Ụlọ oriri na ọṅụṅụ ma ọ bụ ụlọ oriri na ọṅụṅụ Chic",
    "Schlafzimmer" to "Ime ụlọ",
    "Schließen" to "Mechie",
    "Schmal & zart" to "Slim & dị nro",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Foto sitere na akụkọ ịhụnanya anyị",
    "Schokolade" to "Chocolate",
    "Schreib frei, was dir wirklich dazu einfällt." to "Dee ihe na-abata n'uche n'efu.",
    "Schreibe deine eigene Antwort" to "Dee azịza nke gị",
    "Sehr gerne" to "Nnọọ gị",
    "Sehr leicht" to "Nnukwu ọkụ",
    "Sehr wichtig — Fotos und Video" to "Dị oke mkpa - foto na vidiyo",
    "Sehr wichtig, es sollte persönlich sein" to "Ọ dị oke mkpa, ọ kwesịrị ịbụ nkeonwe",
    "Selbst kochen" to "sie onwe gị",
    "Senden" to "Zipụ",
    "Separate Küche" to "kichin dị iche",
    "Serie schauen" to "Lelee usoro a",
    "Serienmarathon auf dem Sofa" to "Usoro marathon na sofa",
    "Sex & Liebe" to "Mmekọahụ & Ịhụnanya",
    "Seychellen" to "Seychelles",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Anyị enwere ike ịkwụ ụgwọ niile maka otu nwatakịrị/ọtụtụ ụmụaka? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Atụmatụ a kwesịrị ịbụ ihe ijuanya?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Ngwa kwesịrị inwe ihe ọdịnala ma ọ bụ ọdịnala?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Ngwa kwesịrị inwe ihe ọdịnala ma ọ bụ ọdịnala?",
    "Sommerhochzeit" to "Agbamakwụkwọ ọkọchị",
    "Sonnige Dachterrasse" to "Ulo elu ụlọ anwụ na-acha",
    "Sowohl als auch" to "Ha abụọ ma",
    "Spazieren" to "Gagharịa",
    "Spaß & Abenteuer" to "ihe ọchị na ihe omume",
    "Speichern" to "Chekwa",
    "Spiel bearbeiten" to "Dezie egwuregwu",
    "Spielbereich für Kinder" to "Mpaghara egwuregwu ụmụaka",
    "Spiele" to "Egwuregwu",
    "Spiele spielen und Spaß haben" to "Gwuo egwuregwu ma nwee anụrị",
    "Spontan" to "Ọbụlagodi",
    "Sportplatz" to "Ogige egwuregwu",
    "Spotify" to "Spotify",
    "Sprache" to "Asụsụ",
    "Stadt" to "Obodo",
    "Stadt oder Land — was ist uns wichtiger?" to "Obodo ma ọ bụ obodo - kedu ihe dị anyị mkpa?",
    "Stadtvilla" to "Villa obodo",
    "Standesamt & Party" to "Ụlọ ọrụ ndekọ & oriri na ọṅụṅụ",
    "Statement-Ring" to "mgbanaka nkwupụta",
    "Stilvolles Outdoor-Sofa" to "Sofa dị n'èzí mara mma",
    "Stimme voll zu" to "Ekwenyere kpamkpam",
    "Stimmt" to "Eziokwu",
    "Stimmt nicht" to "Ọ bụghị eziokwu",
    "Stimmt, noch nie" to "N'eziokwu, ọ dịghị mgbe",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Ụbọchị osimiri",
    "Streit über Haushalt" to "Esemokwu gbasara ezi na ụlọ",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "Mgbe niile",
    "Suche schließen" to "Mechie ọchụchọ",
    "Suche zurücksetzen" to "Tọgharịa ọchụchọ",
    "Suche öffnen" to "Mepee ọchụchọ",
    "Suchergebnisse" to "rịzọlt ọchụchọ",
    "Sushi" to "Sushi",
    "Süß" to "ụtọ",
    "Tage zusammen 💞" to "ụbọchị ọnụ 💞",
    "Tauche ins Unterbewusstsein" to "Banye n'ime ihe nzuzo",
    "Teile alle deine Hobbys mit deinem Partner" to "Kekọrịta onye mmekọ gị ihe omume ntụrụndụ gị niile",
    "Teils teils" to "Otu akụkụ",
    "Testen" to "Nwale",
    "Themen" to "Isiokwu",
    "Tiefe Gespräche" to "Mkparịta ụka miri emi",
    "Tiefgründige Gespräche führen" to "Nwee mkparịta ụka miri emi",
    "Tierpension" to "Ụlọ obibi ụmụ anụmanụ",
    "Tiny House" to "Obere Ụlọ",
    "Tippen zum Auswählen & Scrollen" to "Pịa ka ịhọrọ wee pịgharịa",
    "Tippen zum Zuklappen" to "Pịa ka daa",
    "Titel" to "Aha",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Aha, Otu, Isiokwu, Tags, Ajụjụ...",
    "Tokyo, Japan" to "Tokyo, Japan",
    "Traditioneller Name" to "Aha ọdịnala",
    "Traumhaus Außenbereich" to "Ebe nrọ dị n'èzí",
    "Traumhochzeit" to "Agbamakwụkwọ nrọ",
    "Treffer" to "Kụtara",
    "Tägliche Aktivität" to "Omume kwa ụbọchị",
    "Umformulieren" to "Kwuo okwu",
    "Unbeantwortet" to "azaghị ya",
    "Unbeliebte Meinungen" to "Echiche ndị na-ewu ewu",
    "Universal Studios Genie oder Neuling?" to "Ọkaibe Studios Universal ka ọ bụ onye ọhụrụ?",
    "Uns auseinanderzuleben" to "Iji kewapụ iche",
    "Unser Intimleben" to "Ndụ mmekọrịta chiri anya",
    "Unser Traumhaus" to "Ụlọ nrọ anyị",
    "Unser erstes Treffen" to "Nzukọ nke mbụ anyị",
    "Unsere Gesichter" to "Ihu anyị",
    "Unsere eigenen Träume" to "Nrọ nke anyị",
    "Unsere nächste Reise" to "Njem anyị ọzọ",
    "Unter 1000" to "N'okpuru 1000",
    "Unter 1000 im Monat" to "N'okpuru 1000 kwa ọnwa",
    "Unter 50€/Monat" to "N'okpuru 50€ kwa ọnwa",
    "Unter Leuten" to "N'ime ndị mmadụ",
    "Untreue" to "Ekwesịghị ntụkwasị obi",
    "Urlaub" to "ezumike",
    "Vanille" to "Vanilla",
    "Venedig" to "Venice",
    "Venedig, Italien" to "Venice, Ịtali",
    "Verbinde dich mit" to "Jikọọ na",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Jikọọ na \${profile.partnerName} ka ịhụ azịza ya",
    "Verbindung" to "njikọ",
    "Verbringe die Feiertage mit deiner Familie" to "Gị na ezinụlọ gị nọrọ ezumike ahụ",
    "Verlobungsringe" to "mgbanaka njikọ aka",
    "Vertrautheit" to "Amamihe",
    "Viel getrennt" to "Ọtụtụ nkewa",
    "Vielleicht ein oder zwei" to "Ikekwe otu ma ọ bụ abụọ",
    "Vielleicht, aber mündlich reicht" to "Ikekwe, mana n'ọnụ ezuola",
    "Vielleicht, wenn es machbar ist" to "Ikekwe, ọ bụrụ na ọ ga-ekwe omume",
    "Vielleicht, wenn es passt" to "Ikekwe, ọ bụrụ na ọ dabara",
    "Vintage Art déco" to "Vintage Art Deco",
    "Vintage verspielt" to "Vintage na-egwu egwu",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Onye mmekọ gị webatara gị na ihe omume ntụrụndụ ọhụrụ",
    "Vor dem Kauf eines Hauses besprechen" to "Kwurịtanụ tupu ịzụrụ ụlọ",
    "Vor der Anschaffung eines Haustiers besprechen" to "Kwurịtanụ tupu ịzụrụ anụ ụlọ",
    "Vor der gemeinsamen Reise besprechen" to "Kwurịtanụ ihe tupu unu emee njem ọnụ",
    "Vor nichts" to "Ọ dịghị ihe",
    "Vorort" to "Ime obodo",
    "Walnuss" to "ukpa",
    "Wandern" to "Ime njem",
    "Wann fühlst du dich mir am nächsten?" to "Olee mgbe ị na-eche m kacha nso?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Olee mgbe ọ na-adị gị ka mụ na ya dị ná mma?",
    "Was bedeutet Vertrauen für dich konkret?" to "Gịnị ka ntụkwasị obi pụtara nye gị kpọmkwem?",
    "Was entspannt dich mehr?" to "Gịnị na-eme ka ahụ́ ruo gị ala karị?",
    "Was fehlt dir über die Distanz am meisten?" to "Kedu ihe na-atụ gị anya maka ebe dị anya?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Kedu ihe kacha amasị gị gbasara ụlọ gị?",
    "Was hast du von deinem Partner gelernt?" to "Kedu ihe ị mụtara n'aka onye òtù ọlụlụ gị?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Kedu ihe ị chere maka ikirikọ ọdịnaya agụụ mmekọahụ ọnụ?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Kedu ihe ị chere gbasara ihe nkwado (dịka akara, balloons, wdg)?",
    "Was ist das Wichtigste beim Antrag?" to "Gịnị bụ ihe kacha mkpa mgbe itinye?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Gịnị bụ ihe kacha mkpa ị na-achọ na mmekọahụ?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Gịnị bụ foto anyị kacha amasị gị? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Kedu ihe kacha atụ egwu gị maka ibikọ ọnụ?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Kedu nri ị hụrụ n'anya mana onye gị na ya na-enweghị ike ịghọta?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Gịnị bụ ihe na-emebi azụmahịa zuru oke maka gị?",
    "Was ist für jeden von uns das absolute Highlight?" to "Gịnị bụ ihe kacha pụta ìhè nye onye ọ bụla n'ime anyị?",
    "Was ist passiert?" to "Gịnị mere?",
    "Was macht einen Moment für dich romantisch?" to "Gịnị na-eme gị oge ịhụnanya?",
    "Was magst du an deinem Partner am liebsten?" to "Kedu ihe kacha amasị gị gbasara onye mmekọ gị?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Kedu ihe na-amasị gị karịa: ibili n'isi ụtụtụ ka ọ bụ ịmụrụ anya?",
    "Was magst du lieber?" to "Kedu nke kacha amasị gị?",
    "Was möchtest du eigentlich sagen?" to "Gịnị ka ị chọrọ ikwu?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Kedu ihe ị ga-achọ ka onye gị na ya na-emekọ ihe na-emekarị?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Gịnị na-eme anụmanụ ma anyị na-eme njem?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Gịnị ga-eme nwa anyị ma o too?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Gịnị ka anyị na-ekwesịghị ileghara anya dị ka nne na nna?",
    "Was war dein schönster Moment mit mir bisher?" to "Kedu oge kacha mma gị na m nọ?",
    "Was wir gegessen haben" to "Ihe anyị riri",
    "Was wollt ihr nie vergessen?" to "Kedu ihe ị na-achọghị ichefu?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Kedu ihe ga-akara gị njọ: agakwaghị Pizza ọzọ ma ọ bụ na ọ gaghị abụ burgers ọzọ?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Kedu ihe ga-amasị gị ime n'otu ụbọchị ọnụ?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Gịnị ka ị ga-agbanwe ozugbo ma ọ bụrụ na ego abụghị nsogbu?",
    "Weiter" to "Na-esote",
    "Weiter spielen" to "Gaa n'ihu na-egwu egwu",
    "Weiß ich noch nicht" to "Amabeghị m",
    "Weiße Rosen" to "Roses ọcha",
    "Weißgold" to "Ọla edo ọcha",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Olee àgwà nwa anyị kwesịrị inweta n'aka anyị?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Kedu gburugburu ị ga-achọ maka atụmatụ?",
    "Welcher Raum sagt am meisten über dich aus?" to "Kedu ọnụ ụlọ kacha ekwu maka gị?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Kedu mmefu ego anyị na-eme atụmatụ maka nri na anụ anụmanụ?",
    "Welches Lied macht dich an? 🥵" to "Kedu egwu na-atụgharị gị? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Kedu foto ekekọrịtara kacha amasị gị?",
    "Wellnessbad" to "Ịsa ahụ nke ọma",
    "Wenn es schwierig ist" to "Mgbe ihe siri ike",
    "Wenn ich müde bin" to "Mgbe ike gwụrụ m",
    "Wenn wir uns lange umarmen" to "Mgbe anyị na-amakụ ruo ogologo oge",
    "Wenn wir zusammen lachen" to "Mgbe anyị na-achịkọta ọnụ",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Onye na-ekpebi ngwa ngwa ihe ọ ga-atụ?",
    "Wer findet die besten Restaurants?" to "Ònye na-achọta ụlọ oriri na ọṅụṅụ kacha mma?",
    "Wer gibt mehr Herzlichkeit?" to "Onye na-enye ọkụ karịa?",
    "Wer hat den besseren Musikgeschmack?" to "Ònye kacha amasị egwu?",
    "Wer hängt mehr an seinen Eltern?" to "Ònye na-enwe mmasị n'ebe nne na nna ha nọ?",
    "Wer ist besser organisiert?" to "Ònye ka ahaziri nke ọma?",
    "Wer ist der Beste bei der Filmauswahl?" to "Kedu onye kacha mma n'ịhọrọ ihe nkiri?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Kedu onye kacha mma na-eme atụmatụ ụbọchị ịhụnanya?",
    "Wer ist der beste Tänzer?" to "Onye kacha agba egwu?",
    "Wer ist romantischer?" to "Ònye bụ ịhụnanya karịa?",
    "Wer kocht besser?" to "Onye na-esi nri ka mma?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Ònye na-ahụ maka mmezigharị na mmezi?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Ònye na-achọpụta ngwa ngwa mgbe ahụ́ adịghị onye nke ọzọ?",
    "Wer sucht am Ende wirklich den Film aus?" to "Ònye na-ahọrọ ihe nkiri ahụ n'ikpeazụ?",
    "Wer vergisst eher einen Jahrestag?" to "Ònye ka ọ ga-echefu ụbọchị ncheta?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Ònye ga-akacha chefuo aha nke ha n'ụtụtụ echi?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Ònye nwere ike ịhụ vidiyo n'echi ya nke ha na-amaghị ihe ọ bụla gbasara ya?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Ònye ga-akara ya mma ịnọrọ n'elu sofa onye ọ na-amabughị?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Kedu onye ọ ga-abụ na ọ ga-adaba ụra na nnọkọ oriri na ọṅụṅụ wee teta na Sharpie n'ihu ha?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Kedu onye ga-akacha ada n'elu ebe a na-agba egwu mana mee ka ọ dị ka njem dị mma?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Kedu onye nwere ike chịkwaa ndepụta ọkpụkpọ Spotify na nnọkọ ụlọ?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Kedu onye ga-akarịrị ịtụ onye ọ bụla na oriri Pizza wee rie ya n'onwe ya?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Kedu onye nwere ike buru ụzọ hie ụra na oriri?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Ònye ga-akacha ebido na mberede na-ehicha ụlọ oriri na ọṅụṅụ?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Ònye ga-akacha ekwu na ya nwere uche kpamkpam mgbe ihe dị iche bụ eziokwu?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Ònye nwere ike inye na mbụ n'esemokwu?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Ònye nwere ike ịghọ aghụghọ n'egwuregwu ịṅụ mmanya?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Ònye nwere ike ịwakpo ebe a na-eri nri wee buru nri na nzuzo n'ụlọ?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Ònye ga-akacha ebisa foto na-emenye ihere nke mgbede na akụkọ ha?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Kedu onye ga-akacha were kpasuo DJ iwe ịrịọ egwu nke ha kacha amasị?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Kedu onye ga-akacha abụ abụ a na-agụghị akwụkwọ, ma nwee nkwenye?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Kedu onye ga-akarịrị ịtụ ihe ọṅụṅụ kachasị ọnụ na menu wee kwaakwa ụta?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Ònye ga-enwe ike ịkpọ ndị agbata obi ha ma ọ bụrụ na ha emee mkpesa banyere mkpọtụ ahụ?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Ònye ga-eji egwuregwu oriri na ọṅụṅụ (dị ka Beer Pong) kpọrọ ihe?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Kedu onye ga-enwe ike ime enyi ndị bouncers ka ha nweta ohere VIP?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Kedu onye ga-enwe ike ịmalite agha karaoke na mberede?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Kedu onye ga-emepe karama na-ejighi ihe mgbochi karama?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Ònye ga-akacha ekwu okwu n'agbanyeghị na ọ dịghị onye jụrụ ya?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Kedu onye ga-enwe ike nọrọ otu awa n'ime ụlọ ịsa ahụ na-ese foto selfie?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Ònye ga-akacha eme ka ịgba egwú na-emenye ihere wee mee ememe ya?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Kedu onye ga-enwe ike ịkpọ onye ya na ya na-akpabu mgbe oriri na ọṅụṅụ gachara?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Ònye ga-enwe ike imejọ onye ọbịa na mberede na mberede?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Kedu onye ga-akacha mma ịhapụ nnọkọ oriri na ọṅụṅụ na nzuzo n'ekwughị nke ọma?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Ònye ga-amasị ka ya na anụ ụlọ onye ọbịa gwurie egwu karịa ịgwa ndị ọbịa okwu?",
    "Wer würde eher spontan eine Reise buchen?" to "Ònye ga-enwe ike idebe njem n'onwe ya?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Ònye ga-akacha enwe mkparịta ụka miri emi na kichin ruo ọtụtụ awa?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Ònye nwere ike ịṅụ ihe ọṅụṅụ onye ọzọ na mberede?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Ònye ga-enwe ike ịkụtu ite dị oké ọnụ ahịa na mberede ma ọ bụ ihe na-esighị ike?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Ònye ga-akacha agbalị ịgwakọta mmanya dị mgbagwoju anya n'onwe ha wee daa nke ọma?",
    "Wer würde eher zu spät kommen?" to "Ònye ka ọ ga-abụ n'oge?",
    "Wer würde eher?" to "Onye ga-aka mma?",
    "Wer übernimmt die tägliche Versorgung?" to "Ònye na-elekọta nlekọta kwa ụbọchị?",
    "Werde so akzeptiert, wie du bist" to "Nabata dị ka ị na-",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Anyị a ga-enwe oge zuru oke maka nwata ahụ/ụmụaka? ⏳",
    "Whirlpool" to "Igwe mmiri ọkụ",
    "White Chocolate" to "Chocolate ọcha",
    "Widgets" to "Ngwa wijetị",
    "Wie fühlst du dich am meisten geliebt?" to "Olee otú ọ dị gị ka a kacha hụ gị n'anya?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Olee otú anyị si emeso ego dị iche iche?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Olee ụzọ kacha mma onye gị na ya ga-esi malite inwe mmekọahụ?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Kedu ka onye gị na ya na-emekọ ihe ga-esi bụrụ ezigbo enyi gị?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Ogologo oge ole ka amụma ahụ gachara ka ị chọrọ iso ndị ọzọ mee mmemme?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Ogologo oge ole ka anyị chọrọ ịnọ ebe ahụ opekata mpe?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Olee otú ọ dịịrị gị mfe ikwu maka ọchịchọ?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Kedu ihe ị chọrọ ka ọdịnihu anyị dị ka?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Kedu ka ụbọchị izu ụka gị zuru oke n'ụlọ dị?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Olee otú okwu rụrụ arụ na-adị gị mgbe a na-enwe mmekọahụ?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Ego ole ka anyị ga-enweta n'ezie?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Ogologo oge ole ka anyị chọrọ ịnọpụ iche?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Ego ole ka anyị chọrọ imefu na mkpokọta?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Olee otú anyị ga-esi nweta oge maka mmekọrịta anyị ozugbo nwa ahụ bịara?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Kedu ka ọ dị gị mkpa na ejidere oge ahụ?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Olee otú ọ dị gị mkpa na ngwa ahụ gosipụtara ihe omume ntụrụndụ gị ma ọ bụ mmasị gị?",
    "Wie würdest du sie/ihn nennen?" to "Gịnị ka ị ga-akpọ ya?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Olee ụzọ kacha amasị gị isi gosi ịhụnanya na-abụghị mmekọahụ?",
    "Wildblumen" to "Osisi ọhịa",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Ị chọrọ nwa agbọghọ ma ọ bụ nwoke? 👶",
    "Wintergarten" to "Ogige oyi",
    "Winterhochzeit" to "Agbamakwụkwọ oyi",
    "Wir bestellen einfach beides" to "Anyị na-atụ ha abụọ",
    "Wir brauchen ewig" to "Ọ na-ewe anyị ruo mgbe ebighị ebi",
    "Wir einigen uns nie" to "Ọ dịghị mgbe anyị kwenyere",
    "Wir entscheiden es gemeinsam" to "Anyị na-ekpebi ọnụ",
    "Wir treffen uns in der Mitte" to "Anyị na-ezute n'etiti",
    "Wir wechseln uns ab" to "Anyị na-atụgharị",
    "Wird stressig" to "Na-enwe nchekasị",
    "Wobei lachst du am meisten?" to "Gịnị na-akacha achị ọchị?",
    "Wofür sparen wir gemeinsam?" to "Kedu ihe anyị na-echekwa maka ọnụ?",
    "Wohnzimmer" to "Ime ụlọ",
    "Woran erinnerst du dich am lebhaftesten?" to "Gịnị ka ị na-echeta nke ọma?",
    "Worauf freust du dich bei uns am meisten?" to "Kedu ihe ị na-atụsi anya ya na anyị?",
    "Worte/Komplimente" to "Okwu/Ekele",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Kedu ihe na-atụ gị ụjọ na mmekọrịta anyị?",
    "Wünsche? z.B. günstig, draußen" to "Achọrọ m? eg. ọnụ ala, n'èzí",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Ọ ga-amasị gị ịtụ aro maka ezumike (gụnyere njem)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "Egwu YouTube",
    "Zeichne für mich" to "Seere m",
    "Zeichne mich als Tier — welches wäre ich?" to "See m dị ka anụmanụ - kedu nke m ga-abụ?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Dịrị mmetụta anyị n'ebe ibe anyị nọ dị ka akara.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "See ụlọ nrọ anyị n'otu ahịrị. Kedu ihe kacha pụta ìhè?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "See ụbọchị mbụ anyị - kedu ihe kwesịrị ịdị na foto a?",
    "Zeichnen" to "sere",
    "Zeit füreinander" to "Oge maka ibe ya",
    "Zeit, wenn das Baby schläft" to "Oge nwata na-ehi ụra",
    "Zelten gehen" to "Gaa maa ụlọikwuu",
    "Zitrone" to "lemon",
    "Zu Hause, gemütlich und privat" to "N'ụlọ, mara mma na nkeonwe",
    "Zu einem Picknick gehen" to "Ịga picnic",
    "Zu einem ausgefallenen Abendessen gehen" to "Ịga nri abalị mara mma",
    "Zu zweit reisen" to "Njem dị ka di na nwunye",
    "Zuhause & Alltag" to "Ụlọ na ndụ kwa ụbọchị",
    "Zuhören" to "Gee ntị",
    "Zurück" to "Azụ",
    "Zusammen seit" to "Ọnụ kemgbe",
    "Zusammen seit (TT.MM.JJJJ)" to "Ọnụ kemgbe (DD.MM.YYYY)",
    "Zusammenziehen" to "Nkwekọrịta",
    "Zustimmen oder Ablehnen" to "Kweere ma ọ bụ ekwetaghị",
    "Zwei Kreise, die sich überschneiden" to "okirikiri abụọ na-agbakọ",
    "Zwei Stühle davor" to "Oche abụọ dị n'ihu ya",
    "Zärtlich sein" to "Dị nro",
    "Öfter als ich zugebe" to "Ọtụtụ oge karịa ka m kwetara",
    "Über 100€/Monat" to "Ihe karịrị 100€ kwa ọnwa",
    "Über 2000 im Monat" to "Ihe karịrị 2000 kwa ọnwa",
    "Über mich selbst" to "Banyere onwe m",
    "Übernehmen" to "Tinye akwụkwọ",
    "Überraschend" to "Ijuanya",
    "Überraschung" to "Ijuanya",
    "Überspringen" to "Mafere",
    "Übertrieben und großartig" to "Karịrị elu na ọmarịcha",
    "✎ Tippe, um zu antworten" to "Pịa ka ịzaghachi",
    "✨ GFK-Brücke" to "✨ GRP akwa",
)

internal fun localizeIgboDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_IGBO_CONTENT)
