package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_INDONESIAN_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 tahun",
    "1000 - 1500 im Monat" to "1000 - 1500 per bulan",
    "1000 bis 3000" to "1000 hingga 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 per bulan",
    "3000 bis 5000" to "3000 hingga 5000",
    "5-10 Jahre" to "5-10 tahun",
    "50-100€/Monat" to "50-100€/bulan",
    "Ab 100€" to "Mulai 100€",
    "Ab 500€" to "Mulai 500€",
    "Ab 50€" to "Mulai 50€",
    "Ab und zu" to "Sesekali",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Berapa biaya yang perlu kita keluarkan sebelum melakukan pembelian?",
    "Abbrechen" to "Batal",
    "Abenteuer" to "Petualangan",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Kegiatan",
    "Alle" to "Semuanya",
    "Alle Pakete" to "Semua paket",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Kehilangan semua temanmu kecuali sahabatmu",
    "Alle intimen Momente selbst initiieren" to "Mulailah sendiri semua momen intim",
    "Alles davon" to "Semuanya",
    "Alles, was noch kommt" to "Segala sesuatu yang akan datang",
    "Alltagsroutine" to "Rutinitas sehari-hari",
    "Alltägliche Berührungen" to "Sentuhan sehari-hari",
    "Altbau mit Charme" to "Bangunan tua dengan pesona",
    "Am Strand" to "Di pantai",
    "Am liebsten alles zusammen" to "Sebaiknya semuanya bersama-sama",
    "Am selben Tag mit Freunden/Familie" to "Hari yang sama dengan teman/keluarga",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Belanda",
    "An das Gefühl" to "Tentang perasaan",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "Di tempat umum yang banyak penontonnya",
    "An einen Geruch" to "Dari suatu bau",
    "An einen Song" to "Untuk sebuah lagu",
    "An etwas, das ich gesagt habe" to "Sesuatu yang saya katakan",
    "Analyse starten" to "Mulai analisis",
    "Analysiere eure Muster..." to "Analisis pola Anda...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Analisis jawaban & obrolan Anda menurut Gottman dan GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Nanas di atas pizza rasanya enak.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Balas dengan foto",
    "Antwortähnlichkeit" to "Kesamaan jawaban",
    "App-Sprache auswählen" to "Pilih bahasa aplikasi",
    "Auf eine Bootsparty gehen" to "Pergi ke pesta perahu",
    "Aufmerksamkeit" to "Perhatian",
    "Aufräumen und Projekte angehen" to "Bersihkan dan tangani proyek",
    "Aufwärmen" to "Pemanasan",
    "Aufwärmen: Einander kennenlernen" to "Pemanasan: Mengenal satu sama lain",
    "Aus dem Urlaub" to "Dari liburan",
    "Ausgefallener Name" to "Nama yang mewah",
    "Ausschlafen und faulenzen" to "Tidur dan bermalas-malasan",
    "Ausschlafen und nichts tun" to "Tidurlah dan jangan lakukan apa pun",
    "Aussehen" to "Lihat",
    "Auto" to "mobil",
    "Außenkamin" to "Perapian luar ruangan",
    "BEANTWORTE" to "MENJAWAB",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonesia",
    "Banane" to "pisang",
    "Beantwortet" to "Dijawab",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Jawab pertanyaan secara bersamaan — jawaban tidak akan terlihat sampai Anda berdua selesai.",
    "Beantwortete Fragen" to "Menjawab pertanyaan",
    "Bearbeiten" to "Sunting",
    "Bei Insider-Witzen" to "Untuk lelucon batin",
    "Bei Memes" to "Tentang meme",
    "Bei einer spontanen Berührung" to "Bila disentuh secara spontan",
    "Beide" to "Keduanya",
    "Beide gleich" to "Keduanya sama saja",
    "Beide zusammen" to "Keduanya bersamaan",
    "Beide, aber wir tun so als ob nicht" to "Keduanya, tapi kami berpura-pura tidak",
    "Beides" to "Keduanya",
    "Beides wäre schlimm" to "Keduanya akan buruk",
    "Beim Einschlafen nebeneinander" to "Tertidur bersebelahan",
    "Beim Reden" to "Sambil berbicara",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Tempat wisata terkenal memang selalu mengecewakan.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Gambarkan kehidupan seks kami dengan emoji.",
    "Besser kommunizieren" to "Berkomunikasi dengan lebih baik",
    "Bessere Lage" to "Lokasi lebih baik",
    "Bestellen" to "Pesan",
    "Besuchte Länder" to "Negara-negara yang dikunjungi",
    "Besuchte Städte" to "Kota-kota yang dikunjungi",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Apakah Anda lebih suka lamaran yang mewah atau sesuatu yang halus?",
    "Beziehung" to "Hubungan",
    "Bibliothek" to "Perpustakaan",
    "Bin manchmal unsicher" to "Aku terkadang merasa tidak aman",
    "Bist du ein Videospiel-Guru?" to "Apakah Anda seorang ahli video game?",
    "Blumenwiese" to "Padang rumput bunga",
    "Bunte Blumenwiese" to "Padang rumput bunga berwarna-warni",
    "Burger" to "Burger",
    "Burger King" to "Burger King",
    "Chat" to "Obrolan",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Adonan kue",
    "Dachgarten mit Lounge" to "Taman atap dengan lounge",
    "Dachterrasse" to "Teras atap",
    "Das Wetter an dem Tag" to "Cuaca hari itu",
    "Das erste Selfie" to "Selfie pertama",
    "Das meiste weiß ich" to "Saya tahu sebagian besarnya",
    "Das oder das?" to "Ini atau itu?",
    "Das tägliche Leben" to "Kehidupan sehari-hari",
    "Dass Zusagen gehalten werden" to "Janji itu ditepati",
    "Dass alles meinen Stil hat" to "Semuanya sesuai gayaku",
    "Dass ich alles erzählen kann" to "Bahwa aku bisa menceritakan semuanya",
    "Dass ich mich nicht sorgen muss" to "Saya tidak perlu khawatir",
    "Dass wir ungestört sind" to "Bahwa kita tidak terganggu",
    "Dein Name" to "Nama Anda",
    "Deine Antwort..." to "Jawaban Anda...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Jawaban Anda disimpan. Segera setelah Mitra menyelesaikan paketnya, kedua jawaban akan terlihat bersamaan.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Jawaban Anda disimpan. Setelah \${profile.partnerName} menyelesaikan paket, kedua respons akan terlihat bersamaan.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Jadikan hubungan Anda penuh petualangan dan spontan",
    "Deine Beziehung stabil und sicher machen" to "Jadikan hubungan Anda stabil dan aman",
    "Deine eigene Antwort" to "Jawaban Anda sendiri",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Lebih baik berbagi rahasia terdalammu dengan pasanganmu",
    "Deinen besten Freund verlieren" to "Kehilangan sahabatmu",
    "Denke an dich" to "Pikirkan dirimu sendiri",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Menonton film yang sama dua kali hanya membuang-buang waktu.",
    "Der Blick nach draußen" to "Pemandangan diluar",
    "Der Garten" to "Taman",
    "Der Ort" to "Tempatnya",
    "Der Ring und die Geste" to "Cincin dan isyaratnya",
    "Der perfekte Heiratsantrag" to "Lamaran pernikahan yang sempurna",
    "Derjenige sein, der umarmt wird" to "Jadilah orang yang dipeluk",
    "Deutsch" to "Jerman",
    "Diamant" to "Berlian",
    "Diamanten im Band" to "Berlian di band",
    "Die Distanz" to "Jaraknya",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Habiskan liburan bersama keluarga pasanganmu",
    "Die Gemütlichkeit und Ruhe" to "Kenyamanan dan kedamaian",
    "Die Menschen, die darin wohnen" to "Orang-orang yang tinggal di dalamnya",
    "Die Umgebung und Atmosphäre" to "Lingkungan dan suasana",
    "Die Worte und Emotionen" to "Kata-kata dan emosi",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Tantangan kuis hiburan terbaik",
    "Diejenige sein, die umarmt" to "Jadilah orang yang memeluk",
    "Direkt ansprechen" to "Alamat secara langsung",
    "Diskussion" to "diskusi",
    "Diskutiere vor dem Kinderkriegen" to "Diskusikan sebelum memiliki anak",
    "Diskutiert eure Antworten" to "Diskusikan jawaban Anda",
    "Disney" to "disney",
    "Doch, schon mal" to "iya sudah",
    "Draußen mit der Natur als Kulisse" to "Di luar dengan alam sebagai latar belakang",
    "Drei-Stein-Ring" to "Tiga cincin batu",
    "Du bist dran" to "Sekarang giliranmu",
    "Du fehlst mir" to "Aku merindukanmu",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubai, UEA",
    "Dunkles Design" to "Desain gelap",
    "Durch Berührung" to "Dengan sentuhan",
    "Durch Worte" to "Melalui kata-kata",
    "Durch Zeit zu zweit" to "Melalui waktu bersama",
    "Durch kleine Gesten" to "Melalui gerakan kecil",
    "Durchgeplant" to "Direncanakan dengan baik",
    "ERGEBNISSE" to "HASIL",
    "Egal, Hauptsache gesund" to "Apapun, yang penting sehat",
    "Ehepaar Leben" to "Kehidupan pasangan menikah",
    "Eher knapp" to "Hampir saja",
    "Eher nicht" to "Tidak terlalu banyak",
    "Eher schwer" to "Agak sulit",
    "Eher schwierig" to "Agak sulit",
    "Eher zu" to "Lebih tepatnya",
    "Eifersucht ist ein Zeichen von Liebe." to "Kecemburuan adalah tanda cinta.",
    "Eigenes Gemüsebeet" to "Kebun sayur milik sendiri",
    "Ein Abenteuer in einer neuen Stadt" to "Sebuah petualangan di kota baru",
    "Ein Anker" to "Sebuah jangkar",
    "Ein Balkon oder Garten" to "Balkon atau taman",
    "Ein Filmabend" to "Malam menonton film",
    "Ein Harmony-Meilenstein eurer Liebe." to "Sebuah tonggak harmoni cinta Anda.",
    "Ein Herz" to "Sebuah hati",
    "Ein Herz an der Tür" to "Hati di depan pintu",
    "Ein Jahr lang eine Fernbeziehung führen" to "Menjalani hubungan jarak jauh selama setahun",
    "Ein Kindheitsessen" to "Makanan masa kecil",
    "Ein Live-Musik-Konzert besuchen" to "Hadiri konser musik live",
    "Ein Museum besuchen" to "Kunjungi museum",
    "Ein Spieleabend" to "Malam permainan",
    "Ein Spieleabend mit Freunden" to "Malam permainan bersama teman-teman",
    "Ein Urlaubsfoto" to "Foto liburan",
    "Ein aktives Abenteuer" to "Petualangan yang aktif",
    "Ein entspannender Spa-Tag" to "Hari spa yang menenangkan",
    "Ein ganz normaler Alltagstag" to "Hari-hari yang benar-benar normal setiap hari",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Malam yang nyaman di rumah saat terjadi badai petir",
    "Ein gemütliches Date drinnen" to "Kencan yang nyaman di dalam ruangan",
    "Ein lustiges Bild" to "Gambar yang lucu",
    "Ein paar Handyfotos reichen" to "Beberapa foto ponsel sudah cukup",
    "Ein paar Stunden" to "Beberapa jam",
    "Ein paar kulturelle Anklänge sind okay" to "Beberapa referensi budaya boleh saja",
    "Ein romantischer Abend" to "Malam yang romantis",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Makan malam romantis dengan penerangan lilin",
    "Ein romantisches Bild" to "Gambaran romantis",
    "Ein romantisches Picknick an einem schönen Ort" to "Piknik romantis di lokasi yang indah",
    "Ein schwerer Moment, den wir geschafft haben" to "Momen sulit yang kami kelola",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Kencan luar ruangan yang menyenangkan di bawah sinar bulan",
    "Ein ungewöhnliches Gericht" to "Hidangan yang tidak biasa",
    "Ein zufälliger Schnappschuss" to "Cuplikan acak",
    "Einander kennenlernen" to "Mengenal satu sama lain",
    "Eine Autoreise" to "Sebuah perjalanan darat",
    "Eine Brücke" to "Sebuah jembatan",
    "Eine Date-Nacht unter den Sternen" to "Kencan malam di bawah bintang-bintang",
    "Eine Million Dollar gewinnen" to "Menangkan satu juta dolar",
    "Eine Million Dollar verdienen" to "Hasilkan satu juta dolar",
    "Eine Nacht in einem Club" to "Suatu malam di klub",
    "Eine Schokoladenverkostung" to "Mencicipi coklat",
    "Eine Wanderung mit Panoramablick machen" to "Lakukan pendakian dengan pemandangan yang indah",
    "Eine Weinverkostung" to "Mencicipi anggur",
    "Eine gemeinsame Reise" to "Sebuah perjalanan bersama",
    "Eine gemütliche Nacht zu Hause" to "Malam yang nyaman di rumah",
    "Eine neue Sprache zu lernen ist einfach." to "Mempelajari bahasa baru itu mudah.",
    "Einen Film anschauen" to "Tonton film",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Tidak berbicara satu sama lain sama sekali selama sebulan",
    "Einen Tanzkurs besuchen" to "Ikuti kelas dansa",
    "Einen Vergnügungspark erkunden" to "Jelajahi taman hiburan",
    "Einen Wellness-Tag" to "Hari kesehatan",
    "Einen sehr emotionalen Partner haben" to "Memiliki pasangan yang sangat emosional",
    "Einen sehr logischen Partner haben" to "Memiliki pasangan yang sangat logis",
    "Einer zahlt alles" to "Satu orang membayar semuanya",
    "Einfach mehr Alltag" to "Lebih banyak kehidupan sehari-hari",
    "Einfach nebeneinander sein" to "Berdampingan saja",
    "Einfach und intim" to "Sederhana dan intim",
    "Einige Dinge für dich behalten" to "Simpan beberapa hal untuk dirimu sendiri",
    "Einmal" to "Sekali",
    "Eins, das nur wir kennen" to "Yang hanya kita yang tahu",
    "Englisch" to "Bahasa Inggris",
    "Entspannte Hängematte" to "Tempat tidur gantung santai",
    "Entspannung" to "Relaksasi",
    "Erdbeere" to "Stroberi",
    "Erfolgreich" to "Berhasil",
    "Ergebnisse" to "Hasil",
    "Erst bei sehr großen Summen" to "Hanya untuk jumlah yang sangat besar",
    "Erst nur enge Freunde/Familie" to "Awalnya hanya teman dekat/keluarga",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Aku kesal jika pasanganku terlalu lama membalas pesan.",
    "Essen & Genuss" to "Makanan & kenikmatan",
    "Essensvorlieben" to "Preferensi makanan",
    "Etwa eine Woche später, erst mal nur wir" to "Sekitar seminggu kemudian, awalnya hanya kami",
    "Etwas Neues ausprobieren" to "Cobalah sesuatu yang baru",
    "Etwas ganz anderes" to "Sesuatu yang sangat berbeda",
    "Etwas sehr Scharfes" to "Sesuatu yang sangat tajam",
    "Etwas, das ich selbst gern erfinde" to "Sesuatu yang ingin saya ciptakan sendiri",
    "Etwas, eine kleine Note wäre schön" to "Sesuatu, catatan kecil akan menyenangkan",
    "Familie" to "Keluarga",
    "Familie/Freunde" to "Keluarga/Teman",
    "Familienmensch" to "Pria berkeluarga",
    "Farbedelstein" to "Batu permata berwarna",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Iklan TV terkadang menarik untuk ditonton.",
    "Fertig" to "Selesai",
    "Fertig!" to "Selesai!",
    "Feste Date-Nights" to "Malam kencan tetap",
    "Feuerstelle" to "Lubang api",
    "Filigran & schlicht" to "Kerawang & sederhana",
    "Filme/Serien" to "Film/serial",
    "Formuliere um..." to "Ulangi...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Susun ulang draf Anda dengan cara tanpa kekerasan: observasi, perasaan, kebutuhan, permintaan.",
    "Frage hinzufügen" to "Tambahkan pertanyaan",
    "Fragen & Spiele" to "Soal & Permainan",
    "Fragen für jede Gelegenheit" to "Pertanyaan untuk setiap kesempatan",
    "Freizeitpark" to "Taman hiburan",
    "Freunde treffen" to "Temui teman",
    "Freundschaften mit Ex-Partnern sind okay." to "Persahabatan dengan mantan baik-baik saja.",
    "Früh aufstehen" to "Bangun pagi",
    "Fußbodenheizung" to "Pemanas di bawah lantai",
    "Führen wir getrennte oder gemeinsame Konten?" to "Apakah kami mempunyai rekening terpisah atau gabungan?",
    "Für dich empfohlen" to "Direkomendasikan untuk Anda",
    "Für die Zukunft" to "Untuk masa depan",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Tidak ditemukan pertanyaan atau permainan yang cocok untuk penelusuran ini.",
    "Für immer" to "Selamanya",
    "Fürsorglichkeit" to "Peduli",
    "GFK-Brücke" to "Jembatan GRP",
    "Galerie" to "Galeri",
    "Gar nicht, der Moment gehört uns" to "Tidak sama sekali, momen ini adalah milik kita",
    "Gar nichts tun" to "Jangan lakukan apa pun",
    "Geduld" to "Sabar",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Pergi pagi-pagi sekali untuk melihat matahari terbit",
    "Geht so" to "Jadi seperti ini",
    "Geister existieren wirklich." to "Hantu benar-benar ada.",
    "Gelassenheit" to "Ketenangan",
    "Gelbgold" to "Emas kuning",
    "Geld & Finanzen" to "Uang & Keuangan",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Jelajahi dunia bersama, jelajahi budaya dan masakan baru",
    "Gemeinsam ein Lego bauen" to "Bangun Lego bersama",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Cobalah resep baru bersama di dapur",
    "Gemeinsame Konten" to "Akun bersama",
    "Gemeinsame Nächte" to "Malam bersama",
    "Gemeinsame Tage" to "Hari bersama",
    "Gemischt" to "Campuran",
    "Gemüsebeet" to "Kebun sayur",
    "Gemütliche Feuerstelle" to "Perapian yang nyaman",
    "Gesprächsanreger" to "Pembuka percakapan",
    "Getrennte Konten" to "Pisahkan akun",
    "Getrennte Urlaube tun einer Beziehung gut." to "Liburan terpisah baik untuk sebuah hubungan.",
    "Gewächshaus" to "Rumah Kaca",
    "Glasfassade" to "Fasad kaca",
    "Gleichgültigkeit" to "Ketidakpedulian",
    "Glücklich und frei" to "Senang dan bebas",
    "Gourmet Eis-Sorten" to "Variasi es krim gourmet",
    "Gravur innen" to "Ukiran di dalamnya",
    "Grillplatz" to "Area barbekyu",
    "Groß & üppig" to "Besar & subur",
    "Große Familie" to "Keluarga besar",
    "Große Feier" to "Perayaan besar",
    "Große Fenster" to "Jendela besar",
    "Große Fensterfront" to "Jendela depan besar",
    "Großer Außenpool" to "Kolam renang luar ruangan yang besar",
    "Großer Garten" to "Taman yang luas",
    "Großer Stein" to "Batu besar",
    "Größere Küche" to "Dapur lebih besar",
    "Gutes Essen" to "Makanan enak",
    "Habe ich" to "Benar",
    "Habe ich noch nie" to "Belum pernah",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Pernahkah Anda menemukan perbedaan yang mengejutkan? Bicarakan mengapa Anda lebih menyukai opsi tertentu!",
    "Haus am See" to "Rumah di tepi danau",
    "Haus/Wohnung" to "Rumah/apartemen",
    "Hazelnut" to "Kemiri",
    "Heimkino" to "Teater rumah",
    "Herzhaft" to "Hangat",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Saat ini tidak ada apa pun di sini.\nUbah filter atau pilih topik lain.",
    "Hilfe im Alltag" to "Membantu dalam kehidupan sehari-hari",
    "Himbeere" to "Raspberry",
    "Hinzufügen" to "Tambah",
    "Hobbys" to "Hobi",
    "Hochzeitssträuße" to "Karangan bunga pernikahan",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Kebanggaan Rumah Hogwarts: Di Mana Anda Berada?",
    "Home" to "Rumah",
    "Hot Tub" to "Bak mandi air panas",
    "Humor" to "humor",
    "Hund" to "Anjing",
    "Hängematte" to "tempat tidur gantung",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Apakah Anda ingin surat tertulis sebagai bagian dari lamaran?",
    "IKEA" to "IKEA",
    "Ich" to "SAYA",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Saya lebih suka jalan-jalan romantis di taman daripada pergi ke bioskop.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Saya tidak pernah tertidur di bioskop.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Saya senang menemukan hobi atau aktivitas baru bersama pasangan saya.",
    "Ich finde eine Alternative" to "Saya akan mencari alternatif",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Saya senang mencoba restoran baru bersama pasangan saya daripada selalu pergi ke tempat yang sama.",
    "Ich habe noch nie" to "Saya belum pernah",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Aku tidak pernah takut dengan roller coaster dan aku tetap menaikinya.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Saya belum pernah membeli tiket Fast Pass karena tidak sabar.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Saya tidak pernah membatalkan rencana untuk tinggal di rumah dan menonton acara TV.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Aku tidak pernah menunggu suratku dari Hogwarts.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Aku tidak pernah mengatakan bahwa Slytherin sebenarnya tidak seburuk itu.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Saya tidak pernah mengatakan saya terlalu tua untuk film Disney (dan diam-diam menikmatinya).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Saya tidak pernah dengan sengaja menembak jatuh seseorang dengan tank biru di Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Saya tidak pernah menangis saat menonton film Disney.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Saya tidak pernah menutup mata saat menonton film horor.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Saya tidak pernah lupa menyimpan permainan dan kehilangan beberapa jam kemajuan.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Saya tidak pernah meninggalkan ruangan selama adegan memalukan (faktor ngeri).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Saya belum pernah melakukan pose lucu saat mengambil foto rollercoaster.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Aku belum pernah bermain game sampai larut malam dan menyesali betapa lelahnya aku keesokan harinya.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Saya belum pernah mencari bagian akhir sebuah film di Google karena saya tidak sabar menunggu.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Saya tidak pernah merasa seperti sedang berdiri di lokasi syuting.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Saya tidak pernah melewatkan intro serial favorit saya.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Saya tidak pernah membagikan kata sandi Netflix kepada orang lain.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Saya belum pernah mendengarkan soundtrack game saat bekerja atau belajar.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Saya tidak pernah menyalahkan pengontrol ketika saya kalah.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Saya tidak pernah membuang keyboard atau pengontrol karena marah.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Saya tidak pernah melupakan pakaian basah di mesin cuci selama beberapa hari.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Saya tidak pernah menghabiskan uang sungguhan untuk membeli item kosmetik dalam game.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Saya belum pernah mengendarai mobil di luar negeri.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Saya belum pernah menyanyikan lagu Disney di kamar mandi.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Saya belum pernah mengendarai mobil listrik.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Saya belum pernah berfoto dengan maskot taman.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Saya belum pernah menamai hewan peliharaan dengan nama karakter Hogwarts.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Saya belum pernah menjatuhkan popcorn di bioskop dan masih memakannya.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Saya belum pernah menggunakan kutipan Master Yoda dari Star Wars dalam kehidupan sehari-hari.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Saya belum pernah membeli oleh-oleh yang mahal di taman hiburan.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Saya tidak pernah memberikan rekomendasi film yang dianggap buruk oleh orang lain.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Saya belum pernah menonton Oscar secara langsung di tengah malam.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Saya tidak pernah membatalkan serial karena musim lalu sangat buruk.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Saya belum pernah menonton seluruh season sebuah serial secara berlebihan dalam satu hari.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Saya belum pernah mengalahkan bos pada percobaan pertama dan merasa seperti dewa.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Saya belum pernah menemukan penjahat yang lebih keren dari pahlawan.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Saya tidak pernah mengenali karakter Toy Story di mainan saya sendiri.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Saya belum pernah membuat karakter dalam RPG persis seperti saya.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Aku belum pernah makan churro di taman hiburan.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Saya belum pernah menonton film Disney tiga kali berturut-turut.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Saya belum pernah mendengarkan lagu Disney yang menarik selama seminggu penuh.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Saya belum pernah menonton film hanya karena aktor tertentu.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Saya belum pernah mendengarkan soundtrack film berulang-ulang selama berjam-jam.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Saya tidak pernah mengungkapkan spoiler film dan langsung menyesalinya.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Saya belum pernah menemukan teman yang berbicara bahasa ibu lain.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Saya belum pernah mempunyai teman yang pindah ke negara lain.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Saya belum pernah melakukan maraton film Harry Potter saat Natal.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Saya belum pernah menonton film Marvel sampai akhir hanya karena adegan pasca-kreditnya.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Saya tidak pernah dengan sengaja mengganggu NPC (Karakter Non-Pemain).",
    "Ich habe noch nie einen Nachtzug genommen." to "Saya belum pernah naik kereta malam.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Saya belum pernah mengikuti tes online untuk mengetahui rumah Hogwarts saya.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Saya tidak pernah menghapus postingan media sosial karena tidak mendapat cukup suka.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Saya tidak pernah menyebut hari di taman hiburan sebagai hari terbaik dalam setahun.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Saya belum pernah mengunjungi taman hiburan dan menginap di sana dari pagi hingga malam.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Saya tidak pernah terpesona saat mengendarai Transformers atau Marvel.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Saya tidak pernah marah dan keluar dari permainan.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Saya belum pernah membaca volume besar Harry Potter.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Saya belum pernah memuji karakter favorit saya dalam sebuah serial.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Saya tidak pernah bermimpi bermain Quidditch.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Saya tidak pernah diam-diam mencari di Google cara menyelesaikan level sulit.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Aku tidak pernah diam-diam berharap hewan peliharaanku bisa berbicara seperti di Disney.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Saya belum pernah menghapus pool leader di Sims.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Saya tidak pernah kehilangan arah dalam perjalanan simulator 3D.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Saya belum pernah bermain di tim olahraga universitas.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Saya tidak pernah mengantri lebih dari dua jam untuk satu atraksi.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Barang-barang berhargaku belum pernah basah kuyup saat naik air.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Saya tidak pernah berdebat dengan teman tentang rumah mana yang terbaik.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Aku tidak pernah berpura-pura memiliki kekuatan magis seperti Elsa.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Saya belum pernah tertawa sekeras ini hingga saya melewatkan adegan penting dalam sebuah film.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Saya belum pernah merasakan adrenalin sebesar ini sehingga saya langsung ingin bersepeda lagi.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Aku belum pernah mencoba bernyanyi dengan binatang seperti Putri Salju.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Saya tidak pernah memimpikan perjalanan ke Disneyland.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Saya tidak pernah bermimpi menaiki wahana air Jurassic Park.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Aku belum pernah berteriak sekeras-kerasnya saat ada jumpscare di dalam game.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Saya tidak pernah menangisi akhir acara TV.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Aku tidak pernah... membatalkan kencan untuk tinggal di rumah.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Saya belum pernah... mengulangi pesan sebanyak 10 kali.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Aku tidak pernah... diam-diam melihat ponsel pasanganku.",
    "Ich habe noch nie!" to "Saya belum pernah!",
    "Ich habe!" to "Sudah!",
    "Ich lache viel mit meinem Partner." to "Aku banyak tertawa bersama pasanganku.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Saya ingin mengetahui hobi dan minat pasangan saya.",
    "Ich liebe es" to "Saya menyukainya",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Saya suka menonton film bersama pasangan saya yang belum pernah kami tonton sebelumnya.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Saya suka berbagi musik favorit saya dengan pasangan saya.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Saya tidak pernah harus berlari untuk mengejar penerbangan lanjutan.",
    "Ich plane gerne Dates mit meinem Partner." to "Saya suka merencanakan kencan dengan pasangan saya.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Saya memprioritaskan menghabiskan waktu bersama pasangan saya bahkan ketika saya sedang sibuk.",
    "Ich schreibe meinem Partner jeden Tag." to "Saya mengirim pesan kepada pasangan saya setiap hari.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Saya suka berbagi meme dan lelucon dengan pasangan saya.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Saya ingin berbagi semua detail hari saya dengan pasangan saya.",
    "Ich würde es nie tun" to "Saya tidak akan pernah melakukannya",
    "Ich übe noch" to "Saya masih berlatih",
    "Ideen generieren" to "Hasilkan ide",
    "Im Haushalt helfen" to "Bantuan di sekitar rumah",
    "In Chat einfügen" to "Tambahkan ke obrolan",
    "In Stille nebeneinander" to "Dalam diam bersebelahan",
    "In den Bergen" to "Di pegunungan",
    "In eine Bar gehen" to "Pergi ke bar",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Pergi ke bar pantai untuk menyaksikan matahari terbenam",
    "In einem feinen Restaurant essen gehen" to "Makan di restoran mewah",
    "In einen Coffeeshop gehen" to "Pergi ke kedai kopi",
    "In einer Beziehung sollte man alles voneinander wissen." to "Dalam suatu hubungan kalian harus mengetahui segalanya tentang satu sama lain.",
    "Infinity-Pool" to "Kolam tanpa batas",
    "Innenpool" to "Kolam renang dalam ruangan",
    "Intelligenz" to "Kecerdasan",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Hanya memiliki momen intim ketika pasangan Anda yang memulainya",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Kode undangan: HRM-8731 · semuanya tidak terkunci",
    "Island" to "Islandia",
    "Ist okay für mich" to "Tidak apa-apa bagiku",
    "Ist schon perfekt" to "Sempurna",
    "Ja, Traditionen einbinden" to "Ya, gabungkan tradisi",
    "Ja, absolut" to "Ya, tentu saja",
    "Ja, etwas zum Lesen und Aufbewahren" to "Ya, sesuatu untuk dibaca dan disimpan",
    "Ja, genug" to "Ya, cukup",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Ya, di kota atau objek wisata yang menarik",
    "Ja, in- und auswendig" to "Ya, luar dan dalam",
    "Ja, komplett überraschend" to "Ya, benar-benar mengejutkan",
    "Ja, perfekt" to "Ya, sempurna",
    "Ja, sie gehören zur Familie!" to "Ya, mereka adalah keluarga!",
    "Ja, sofort teilen" to "Ya, segera bagikan",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Ya, kami akan memastikan bahwa waktu bersama keluarga adalah prioritas.",
    "Jacuzzi" to "Jacuzzi",
    "Jahr zusammen 🎉" to "setahun bersama 🎉",
    "Jahre zusammen 🎉" to "Bertahun-tahun bersama 🎉",
    "Jeder zahlt 50%" to "Setiap orang membayar 50%",
    "Junge" to "Wah",
    "Kamin" to "Perapian",
    "Karriere & Erfolg" to "Karier & Kesuksesan",
    "Kategorien" to "Kategori",
    "Katze" to "Kucing",
    "Keine Musik" to "Tidak ada musik",
    "Keine Party nötig, privat halten" to "Tidak perlu mengadakan pesta, jaga kerahasiaannya",
    "Keine Privatsphäre" to "Tidak ada privasi",
    "Keine Treffer gefunden" to "Tidak ditemukan kecocokan",
    "Keiner" to "Tidak ada",
    "Keiner von uns" to "Tak satu pun dari kita",
    "Kennst du die Essensvorlieben deines Partners?" to "Tahukah Anda kesukaan makanan pasangan Anda?",
    "Kino" to "Bioskop",
    "Kirchlich" to "Gerejawi",
    "Klassisch Solitär" to "Solitaire klasik",
    "Klassisch gebunden" to "Terikat secara klasik",
    "Klein & zart" to "Kecil & halus",
    "Kleine Geschenke" to "Hadiah kecil",
    "Kleine Runde" to "Kelompok kecil",
    "Kochen und Freunde einladen" to "Memasak dan mengundang teman",
    "Kochkurs" to "Kelas memasak",
    "Kommt auf den Tag an" to "Tergantung harinya",
    "Kommt darauf an" to "Tergantung",
    "Kommt drauf an" to "Tergantung",
    "Kommt mit" to "Ikutlah denganku",
    "Konzert" to "Konser",
    "Kräftige Farben" to "Warna yang kuat",
    "Kräuterbeet" to "Tempat tidur herbal",
    "Kultur & Sehenswürdigkeiten" to "Budaya & Pemandangan",
    "Kuscheln" to "Berpelukan",
    "Kuss senden" to "Kirim ciuman",
    "Körperliche Annäherung" to "Pendekatan fisik",
    "Körperliche Nähe" to "Kedekatan fisik",
    "Küche" to "Dapur",
    "Land" to "negara",
    "Landhaus" to "rumah pedesaan",
    "Landhausstil" to "Gaya pedesaan",
    "Lange wach bleiben" to "Tetap terjaga hingga larut malam",
    "Lappland" to "Laplandia",
    "Lappland, Finnland" to "Lapland, Finlandia",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Biarkan pasanganmu menginspirasimu untuk menjadi dirimu yang terbaik",
    "Lehne ab" to "Penurunan",
    "Leichtigkeit" to "Ringan",
    "Leidenschaft" to "Gairah",
    "Liebe im Gleichgewicht" to "Cinta dalam keseimbangan",
    "Liebe sie, macht mehr Spaß" to "Cintai mereka, lebih menyenangkan",
    "Lieber durchgeplant oder spontan?" to "Apakah Anda lebih suka merencanakannya atau spontan?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Apakah Anda lebih suka menikmati malam yang tenang untuk dua orang atau bersama orang lain?",
    "Lieber nicht" to "Lebih baik tidak",
    "Lieber vorher grob absprechen" to "Lebih baik mendiskusikan semuanya secara kasar terlebih dahulu",
    "Lokal einkaufen" to "Berbelanja secara lokal",
    "London" to "London",
    "London, England" to "London, Inggris",
    "Lügen" to "Berbohong",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Apakah Anda lebih suka proposal publik atau pribadi?",
    "Malediven" to "Maladewa",
    "Man sollte nie streitend einschlafen." to "Anda tidak boleh tertidur saat berdebat.",
    "Mango Sorbet" to "Sorbet mangga",
    "Markant & breit" to "Mencolok & melebar",
    "Marken & Alltag" to "Merek & kehidupan sehari-hari",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "Halaman Mediterania",
    "Mehr Unterstützung" to "Lebih banyak dukungan",
    "Mehr gemeinsame Zeit" to "Lebih banyak waktu bersama",
    "Mehr zuhören" to "Dengarkan lebih lanjut",
    "Mehrgenerationenhaus" to "Rumah multigenerasi",
    "Mein Arbeitsplatz" to "Tempat kerjaku",
    "Mein Partner" to "Rekan saya",
    "Mich überraschen" to "Kejutkan aku",
    "Minimalistisches Interieur" to "Interior minimalis",
    "Missverständnisse" to "Kesalahpahaman",
    "Mit Familie und engen Freunden" to "Bersama keluarga dan teman dekat",
    "Mit Kompromissen" to "Dengan kompromi",
    "Mitgefühl" to "Kasih sayang",
    "Mittelweg mit besonderen Details" to "Jalan tengah dengan detail khusus",
    "Modern geometrisch" to "Geometris modern",
    "Moderne Grillstation" to "Stasiun pemanggang modern",
    "Moderner Name" to "Nama modern",
    "Moderner Solitär" to "Solitaire modern",
    "Moissanit" to "Moissanit",
    "Moment festhalten" to "Abadikan momennya",
    "Momente" to "momen",
    "Monaco" to "Monako",
    "Moralische Werte" to "Nilai moral",
    "Museum" to "Museum",
    "Musik" to "Musik",
    "Mut" to "Keberanian",
    "Mädchen" to "Gadis-gadis",
    "Möbelhaus" to "Toko furnitur",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Apakah Anda yakin ingin keluar dari kuis? Kemajuan Anda sebelumnya tetap tersimpan.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Apakah Anda ingin hewan peliharaan disertakan dalam aplikasi?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Ingin momennya langsung dibagikan ke media sosial?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Kita mungkin perlu melakukan penghematan",
    "Müssen es planen" to "Perlu direncanakan",
    "Müssen sparen" to "Perlu disimpan",
    "Nachricht an" to "Pesan",
    "Name Partnerin" to "Nama mitra",
    "Namen und Startdatum eurer Beziehung." to "Nama dan tanggal mulai hubungan Anda.",
    "Natursteinfassade" to "Fasad batu alam",
    "Naturteich" to "Kolam alami",
    "Nein, einfach halten" to "Tidak, tahan saja",
    "Nein, erstmal privat halten" to "Tidak, jaga kerahasiaannya untuk saat ini",
    "Nein, lieber vor Ort" to "Tidak, lebih baik di lokasi",
    "Nein, modern halten" to "Tidak, tetap modern",
    "Nein, nur wir" to "Tidak, hanya kami",
    "Nein, zu ablenkend" to "Tidak, terlalu mengganggu",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Gedung baru dengan rumah pintar",
    "Neubau mit Technik" to "Bangunan baru dengan teknologi",
    "Neue Liebe, neue Erfahrungen" to "Cinta baru, pengalaman baru",
    "Neues Hobby" to "Hobi baru",
    "Neues Spiel" to "Permainan baru",
    "Neugier" to "rasa ingin tahu",
    "New York" to "New York",
    "New York, USA" to "New York, AS",
    "Nicht mein Fall" to "Bukan kasus saya",
    "Nicht nötig, lieber klassisch bleiben" to "Tidak perlu, lebih baik tetap klasik",
    "Nichts — es passt so" to "Tidak ada - cocok seperti itu",
    "Nie wieder Burger" to "Tidak pernah lagi burger",
    "Nie wieder Pizza" to "Jangan pernah makan pizza lagi",
    "Niemand" to "Tidak seorang pun",
    "Niemand ohne Plan" to "Tak seorang pun tanpa rencana",
    "Nike" to "Nike",
    "Nizza" to "Bagus",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Belum ada momen.\nRekam pengalaman pertama Anda 💞",
    "Nur bei wichtigen Themen" to "Hanya pada topik penting",
    "Nur wir beide" to "Hanya kita berdua",
    "Nähe & Intimität" to "Kedekatan & keintiman",
    "Obstgarten" to "kebun buah-buahan",
    "Oder" to "Atau",
    "Offene Küche" to "Dapur terbuka",
    "Offene Wohnküche" to "Dapur/ruang tamu terbuka",
    "Ohne Stein" to "Tanpa batu",
    "Open End" to "Akhir yang terbuka",
    "Outdoor-Küche" to "Dapur luar ruangan",
    "Outdoor-Sofa" to "Sofa luar ruangan",
    "Outdoor-Whirlpool" to "Pusaran air luar ruangan",
    "Ovaler Diamant" to "Berlian berbentuk oval",
    "Paar" to "Sepasang",
    "Paar-Statistiken" to "Statistik pasangan",
    "Paris" to "Paris",
    "Paris, Frankreich" to "Paris, Prancis",
    "Partner" to "mitra",
    "Partner-Simulator" to "Simulator mitra",
    "Partnerin" to "mitra",
    "Party Edition" to "Edisi pesta",
    "Party Edition II" to "Edisi Pesta II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Apakah seekor binatang cocok dengan kehidupan kita sehari-hari?",
    "Pasta" to "pasta",
    "Pastell" to "Pastel",
    "Penthouse mit Ausblick" to "Penthouse dengan pemandangan",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pergola dengan lounge",
    "Pfingstrosen" to "Peony",
    "Pinguin" to "penguin",
    "Pistazie" to "pistachio",
    "Pizza" to "pizza",
    "Pizzaofen" to "oven piza",
    "Platin" to "platinum",
    "PlayStation" to "PlayStation",
    "Pool" to "Kolam renang",
    "Pop" to "Pop",
    "Prasselnder Kamin" to "Perapian menderu",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Putri, Bajak Laut, dan Debu Peri: Kuis Disney",
    "Privater Innenhof" to "Halaman pribadi",
    "Profil" to "Profil",
    "Profil bearbeiten" to "Edit profil",
    "Prozentual nach Einkommen" to "Persentase berdasarkan pendapatan",
    "Quiz verlassen" to "Keluar dari kuis",
    "Quiz verlassen?" to "Tinggalkan kuis?",
    "Rausgehen in die Natur" to "Keluarlah ke alam terbuka",
    "Reden vor ..." to "Berbicara kepada...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Jadwalkan tanggal atau waktu bersama yang teratur",
    "Reisen" to "Perjalanan",
    "Reiseziele" to "Tujuan perjalanan",
    "Respektlosigkeit" to "Tidak hormat",
    "Restaurant" to "Restoran",
    "RnB / Soul" to "RnB / Jiwa",
    "Rock" to "Batu",
    "Rom" to "Roma",
    "Rom, Italien" to "Roma, Italia",
    "Romantik" to "roman",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Gerakan romantis seperti pesan, catatan, atau hadiah membuatku bahagia.",
    "Romantische Stimmung" to "Suasana romantis",
    "Roségold" to "Mawar emas",
    "Ruhig zu zweit" to "Tenang untuk dua orang",
    "Runder Diamant" to "Berlian bulat",
    "Salted Caramel" to "Karamel asin",
    "Sammle Ideen..." to "Kumpulkan ide...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Yunani",
    "Saphir" to "Safir",
    "Saunahaus" to "Rumah sauna",
    "Schickes Restaurant oder Hotel" to "Restoran atau hotel mewah",
    "Schlafzimmer" to "Kamar Tidur",
    "Schließen" to "Tutup",
    "Schmal & zart" to "Ramping & halus",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Cuplikan dari kisah cinta kami",
    "Schokolade" to "Coklat",
    "Schreib frei, was dir wirklich dazu einfällt." to "Tulis dengan bebas apa yang benar-benar terlintas dalam pikiran.",
    "Schreibe deine eigene Antwort" to "Tulis jawaban Anda sendiri",
    "Sehr gerne" to "Sama-sama",
    "Sehr leicht" to "Sangat ringan",
    "Sehr wichtig — Fotos und Video" to "Sangat penting — foto dan video",
    "Sehr wichtig, es sollte persönlich sein" to "Sangat penting, harus bersifat pribadi",
    "Selbst kochen" to "Masak sendiri",
    "Senden" to "Kirim",
    "Separate Küche" to "Dapur terpisah",
    "Serie schauen" to "Tonton serialnya",
    "Serienmarathon auf dem Sofa" to "Seri maraton di sofa",
    "Sex & Liebe" to "Seks & Cinta",
    "Seychellen" to "Seychelles",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Apakah kami mampu menanggung seluruh biaya untuk satu anak/beberapa anak? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Haruskah lamaran itu menjadi kejutan?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Haruskah aplikasi mengandung unsur budaya atau tradisional?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Haruskah aplikasi mengandung unsur budaya atau tradisional?",
    "Sommerhochzeit" to "Pernikahan musim panas",
    "Sonnige Dachterrasse" to "Teras atap yang cerah",
    "Sowohl als auch" to "Keduanya dan",
    "Spazieren" to "Jalan-jalan",
    "Spaß & Abenteuer" to "Kegembiraan & Petualangan",
    "Speichern" to "Simpan",
    "Spiel bearbeiten" to "Edit permainan",
    "Spielbereich für Kinder" to "Area bermain untuk anak-anak",
    "Spiele" to "Permainan",
    "Spiele spielen und Spaß haben" to "Mainkan game dan bersenang-senang",
    "Spontan" to "Spontan",
    "Sportplatz" to "Lapangan olah raga",
    "Spotify" to "Spotify",
    "Sprache" to "Bahasa",
    "Stadt" to "Kota",
    "Stadt oder Land — was ist uns wichtiger?" to "Kota atau negara - mana yang lebih penting bagi kami?",
    "Stadtvilla" to "Vila kota",
    "Standesamt & Party" to "Kantor pendaftaran & pesta",
    "Statement-Ring" to "Cincin pernyataan",
    "Stilvolles Outdoor-Sofa" to "Sofa luar ruangan yang bergaya",
    "Stimme voll zu" to "Sangat setuju",
    "Stimmt" to "Benar",
    "Stimmt nicht" to "Tidak benar",
    "Stimmt, noch nie" to "Benar, tidak pernah",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "hari pantai",
    "Streit über Haushalt" to "Perselisihan rumah tangga",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "Konstan",
    "Suche schließen" to "Tutup pencarian",
    "Suche zurücksetzen" to "Setel ulang pencarian",
    "Suche öffnen" to "Buka pencarian",
    "Suchergebnisse" to "Hasil pencarian",
    "Sushi" to "sushi",
    "Süß" to "Manis",
    "Tage zusammen 💞" to "hari bersama 💞",
    "Tauche ins Unterbewusstsein" to "Selami alam bawah sadar",
    "Teile alle deine Hobbys mit deinem Partner" to "Bagikan semua hobi Anda dengan pasangan Anda",
    "Teils teils" to "Sebagian sebagian",
    "Testen" to "Tes",
    "Themen" to "Topik",
    "Tiefe Gespräche" to "Percakapan mendalam",
    "Tiefgründige Gespräche führen" to "Lakukan percakapan yang mendalam",
    "Tierpension" to "Asrama Hewan",
    "Tiny House" to "Rumah Mungil",
    "Tippen zum Auswählen & Scrollen" to "Ketuk untuk memilih & menggulir",
    "Tippen zum Zuklappen" to "Ketuk untuk menutup",
    "Titel" to "Judul",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Judul, Kategori, Topik, Tag, Pertanyaan...",
    "Tokyo, Japan" to "Tokyo, Jepang",
    "Traditioneller Name" to "Nama tradisional",
    "Traumhaus Außenbereich" to "Area outdoor rumah impian",
    "Traumhochzeit" to "Pernikahan impian",
    "Treffer" to "Pukul",
    "Tägliche Aktivität" to "Aktivitas harian",
    "Umformulieren" to "Ulangi kalimatnya",
    "Unbeantwortet" to "Belum terjawab",
    "Unbeliebte Meinungen" to "Pendapat yang tidak populer",
    "Universal Studios Genie oder Neuling?" to "Jenius atau pemula Universal Studios?",
    "Uns auseinanderzuleben" to "Untuk tumbuh terpisah",
    "Unser Intimleben" to "Kehidupan intim kami",
    "Unser Traumhaus" to "Rumah impian kami",
    "Unser erstes Treffen" to "Pertemuan pertama kita",
    "Unsere Gesichter" to "Wajah kita",
    "Unsere eigenen Träume" to "Impian kita sendiri",
    "Unsere nächste Reise" to "Perjalanan kita berikutnya",
    "Unter 1000" to "Di bawah 1000",
    "Unter 1000 im Monat" to "Di bawah 1000 per bulan",
    "Unter 50€/Monat" to "Di bawah 50€/bulan",
    "Unter Leuten" to "Di antara orang-orang",
    "Untreue" to "Perselingkuhan",
    "Urlaub" to "Liburan",
    "Vanille" to "Vanila",
    "Venedig" to "Venesia",
    "Venedig, Italien" to "Venesia, Italia",
    "Verbinde dich mit" to "Terhubung dengan",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Hubungkan ke \${profile.partnerName} untuk melihat jawabannya",
    "Verbindung" to "koneksi",
    "Verbringe die Feiertage mit deiner Familie" to "Habiskan liburan bersama keluarga",
    "Verlobungsringe" to "Cincin pertunangan",
    "Vertrautheit" to "Keakraban",
    "Viel getrennt" to "Banyak perpisahan",
    "Vielleicht ein oder zwei" to "Mungkin satu atau dua",
    "Vielleicht, aber mündlich reicht" to "Mungkin, tapi secara lisan saja sudah cukup",
    "Vielleicht, wenn es machbar ist" to "Mungkin, jika memungkinkan",
    "Vielleicht, wenn es passt" to "Mungkin, kalau cocok",
    "Vintage Art déco" to "Art Deco Antik",
    "Vintage verspielt" to "Vintage yang lucu",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Diperkenalkan pada hobi baru oleh pasangan Anda",
    "Vor dem Kauf eines Hauses besprechen" to "Diskusikan sebelum membeli rumah",
    "Vor der Anschaffung eines Haustiers besprechen" to "Diskusikan sebelum membeli hewan peliharaan",
    "Vor der gemeinsamen Reise besprechen" to "Diskusikan sebelum bepergian bersama",
    "Vor nichts" to "Tidak ada",
    "Vorort" to "Pinggiran kota",
    "Walnuss" to "Kenari",
    "Wandern" to "Mendaki gunung",
    "Wann fühlst du dich mir am nächsten?" to "Kapan kamu merasa paling dekat denganku?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Kapan kamu merasa paling dekat secara fisik denganku?",
    "Was bedeutet Vertrauen für dich konkret?" to "Apa arti kepercayaan secara khusus bagi Anda?",
    "Was entspannt dich mehr?" to "Apa yang lebih membuatmu rileks?",
    "Was fehlt dir über die Distanz am meisten?" to "Apa yang paling kamu rindukan dari jarak?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Apa yang paling Anda sukai dari rumah Anda?",
    "Was hast du von deinem Partner gelernt?" to "Apa yang telah kamu pelajari dari pasanganmu?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Apa pendapat Anda tentang menonton konten erotis bersama?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Apa pendapat Anda tentang alat peraga (misalnya tanda, balon, dll.)?",
    "Was ist das Wichtigste beim Antrag?" to "Apa hal terpenting saat melamar?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Apa hal terpenting yang Anda cari dalam hubungan seksual?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Apa foto kami yang paling kamu sukai? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Apa ketakutan terbesarmu tentang hidup bersama?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Makanan apa yang kamu suka tapi pasanganmu tidak mengerti?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Apa yang menjadi penghalang mutlak bagi Anda?",
    "Was ist für jeden von uns das absolute Highlight?" to "Apa yang paling menonjol dari kita masing-masing?",
    "Was ist passiert?" to "Apa yang terjadi?",
    "Was macht einen Moment für dich romantisch?" to "Apa yang membuat momen romantis bagimu?",
    "Was magst du an deinem Partner am liebsten?" to "Apa yang paling kamu sukai dari pasanganmu?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Mana yang lebih kamu sukai: bangun pagi atau begadang?",
    "Was magst du lieber?" to "Mana yang lebih kamu sukai?",
    "Was möchtest du eigentlich sagen?" to "Apa sebenarnya yang ingin kamu katakan?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Apa yang Anda ingin pasangan Anda lakukan lebih sering?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Apa yang terjadi pada hewan saat kita bepergian?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Apa yang akan terjadi pada anak kita jika sudah besar nanti?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Apa yang tidak boleh kita lupakan sebagai orang tua?",
    "Was war dein schönster Moment mit mir bisher?" to "Apa momen terbaikmu bersamaku sejauh ini?",
    "Was wir gegessen haben" to "Apa yang kami makan",
    "Was wollt ihr nie vergessen?" to "Apa yang tidak ingin kamu lupakan?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Apa yang lebih buruk bagi Anda: tidak pernah makan pizza lagi atau tidak pernah makan burger lagi?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Apa yang paling ingin kamu lakukan pada hari bersama?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Apa yang akan segera Anda ubah jika uang tidak menjadi masalah?",
    "Weiter" to "Selanjutnya",
    "Weiter spielen" to "Lanjutkan pemutaran",
    "Weiß ich noch nicht" to "Saya belum tahu",
    "Weiße Rosen" to "Mawar putih",
    "Weißgold" to "Emas putih",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Kualitas apa yang pasti anak kita dapatkan dari kita?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Lingkungan seperti apa yang Anda inginkan untuk proposal?",
    "Welcher Raum sagt am meisten über dich aus?" to "Ruangan manakah yang paling banyak mengungkapkan tentangmu?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Berapa anggaran yang kita rencanakan untuk makanan dan dokter hewan?",
    "Welches Lied macht dich an? 🥵" to "Lagu apa yang membuatmu bergairah? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Foto bersama manakah yang menjadi favorit Anda?",
    "Wellnessbad" to "Mandi kesehatan",
    "Wenn es schwierig ist" to "Saat keadaan sulit",
    "Wenn ich müde bin" to "Saat aku lelah",
    "Wenn wir uns lange umarmen" to "Saat kita berpelukan dalam waktu yang lama",
    "Wenn wir zusammen lachen" to "Saat kita tertawa bersama",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Siapa yang lebih cepat memutuskan apa yang akan dipesan?",
    "Wer findet die besten Restaurants?" to "Siapa yang menemukan restoran terbaik?",
    "Wer gibt mehr Herzlichkeit?" to "Siapa yang memberi lebih banyak kehangatan?",
    "Wer hat den besseren Musikgeschmack?" to "Siapa yang punya selera musik lebih baik?",
    "Wer hängt mehr an seinen Eltern?" to "Siapa yang lebih dekat dengan orang tuanya?",
    "Wer ist besser organisiert?" to "Siapa yang lebih terorganisir?",
    "Wer ist der Beste bei der Filmauswahl?" to "Siapa yang paling jago memilih film?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Siapa yang paling baik dalam merencanakan kencan romantis?",
    "Wer ist der beste Tänzer?" to "Siapa penari terbaik?",
    "Wer ist romantischer?" to "Siapa yang lebih romantis?",
    "Wer kocht besser?" to "Siapa yang memasak lebih baik?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Siapa yang mengurus renovasi dan pemeliharaan?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Siapa yang lebih cepat menyadari saat orang lain sedang tidak enak badan?",
    "Wer sucht am Ende wirklich den Film aus?" to "Siapa sebenarnya yang memilih film pada akhirnya?",
    "Wer vergisst eher einen Jahrestag?" to "Siapa yang lebih mungkin melupakan hari jadi?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Siapa yang lebih mungkin lupa namanya keesokan paginya?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Siapa yang lebih mungkin menemukan video keesokan harinya yang tidak mereka ketahui sama sekali?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Siapa yang lebih suka bermalam di sofa orang asing?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Siapa yang lebih mungkin tertidur di pesta dan terbangun dengan Sharpie di wajahnya?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Siapa yang lebih mungkin terpeleset di lantai dansa namun membuatnya terlihat seperti gerakan yang keren?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Siapa yang lebih mungkin mengendalikan playlist Spotify di pesta rumah?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Siapa yang lebih mungkin memesan pizza untuk semua orang di sebuah pesta dan memakannya sendiri?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Siapa yang lebih mungkin tertidur terlebih dahulu di sebuah pesta?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Siapa yang lebih mungkin tiba-tiba mulai bersih-bersih di pesta?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Siapa yang lebih mungkin mengaku sadar sepenuhnya padahal yang terjadi justru sebaliknya?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Siapa yang lebih mungkin menyerah terlebih dahulu dalam sebuah argumen?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Siapa yang lebih mungkin berbuat curang dalam permainan minum?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Siapa yang lebih mungkin menyerbu prasmanan dan diam-diam membawa pulang makanan?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Siapa yang lebih mungkin memposting foto paling memalukan pada malam itu di story mereka?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Siapa yang lebih mungkin mengganggu DJ dengan meminta lagu favoritnya sendiri?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Siapa yang lebih mungkin menyanyikan lirik sebuah lagu tanpa nada, namun dengan keyakinan?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Siapa yang lebih mungkin memesan minuman termahal di menu dan menyesalinya?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Siapa yang lebih mungkin mengundang tetangga jika mereka mengeluh tentang kebisingan?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Siapa yang menganggap permainan pesta (seperti Beer Pong) terlalu serius?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Siapa yang lebih mungkin berteman dengan penjaga untuk mendapatkan akses VIP?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Siapa yang lebih mungkin memulai pertarungan karaoke spontan?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Siapa yang lebih mungkin membuka botol tanpa menggunakan pembuka botol?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Siapa yang lebih berpeluang memberikan pidato meski sama sekali tidak ada yang bertanya?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Siapa yang lebih mungkin menghabiskan satu jam di kamar mandi untuk mengambil foto selfie?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Siapa yang lebih mungkin menampilkan pertunjukan tari yang memalukan dan merayakannya?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Siapa yang lebih mungkin menelepon mantan pasangannya setelah pesta selesai?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Siapa yang lebih mungkin menyinggung tamu asing secara tidak sengaja?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Siapa yang lebih mungkin meninggalkan pesta secara diam-diam tanpa pamit?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Siapa yang lebih suka bermain dengan hewan peliharaan tuan rumah daripada berbicara dengan para tamu?",
    "Wer würde eher spontan eine Reise buchen?" to "Siapa yang lebih mungkin memesan perjalanan secara spontan?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Siapa yang lebih mungkin melakukan percakapan mendalam di dapur selama berjam-jam?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Siapa yang lebih mungkin meminum minuman orang lain secara tidak sengaja?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Siapa yang lebih mungkin secara tidak sengaja menjatuhkan vas mahal atau sesuatu yang rapuh?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Siapa yang lebih mungkin mencoba membuat koktail rumit sendiri dan gagal total?",
    "Wer würde eher zu spät kommen?" to "Siapa yang lebih mungkin terlambat?",
    "Wer würde eher?" to "Siapa yang lebih suka?",
    "Wer übernimmt die tägliche Versorgung?" to "Siapa yang mengurus perawatan sehari-hari?",
    "Werde so akzeptiert, wie du bist" to "Diterima apa adanya",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Akankah kita punya cukup waktu untuk anak/anak-anak? ⏳",
    "Whirlpool" to "Bak mandi air panas",
    "White Chocolate" to "Coklat Putih",
    "Widgets" to "Widget",
    "Wie fühlst du dich am meisten geliebt?" to "Bagaimana perasaanmu paling dicintai?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Bagaimana kita menghadapi perbedaan pendapatan?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Apa cara terbaik bagi pasangan Anda untuk memulai hubungan seks dengan Anda?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Bagaimana pasangan Anda bisa menjadi mitra yang lebih baik lagi bagi Anda?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Berapa lama setelah lamaran Anda ingin merayakannya bersama orang lain?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Berapa lama kita ingin tinggal di sana setidaknya?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Seberapa mudahnya bagimu untuk membicarakan keinginan?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Anda ingin masa depan kita seperti apa?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Seperti apa hari Minggu sempurnamu di rumah?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Bagaimana perasaan Anda tentang pembicaraan kotor saat berhubungan seks?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Berapa jumlah kredit yang mampu kita bayar secara realistis?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Berapa banyak waktu yang ingin kita habiskan secara terpisah?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Berapa total yang ingin kita belanjakan?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Bagaimana kita bisa meluangkan waktu untuk hubungan kita setelah bayinya lahir?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Seberapa penting bagi Anda untuk mengabadikan momen tersebut?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Seberapa penting bagi Anda bahwa aplikasi tersebut mencerminkan hobi atau minat Anda?",
    "Wie würdest du sie/ihn nennen?" to "Kamu akan memanggilnya apa?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Apa cara favoritmu untuk menunjukkan kasih sayang di luar seks?",
    "Wildblumen" to "Bunga liar",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Mau yang cewek atau cowok? 👶",
    "Wintergarten" to "Taman musim dingin",
    "Winterhochzeit" to "Pernikahan musim dingin",
    "Wir bestellen einfach beides" to "Kami pesan keduanya saja",
    "Wir brauchen ewig" to "Kita butuh waktu selamanya",
    "Wir einigen uns nie" to "Kami tidak pernah setuju",
    "Wir entscheiden es gemeinsam" to "Kita putuskan bersama",
    "Wir treffen uns in der Mitte" to "Kita bertemu di tengah",
    "Wir wechseln uns ab" to "Kami bergiliran",
    "Wird stressig" to "Menjadi stres",
    "Wobei lachst du am meisten?" to "Apa yang paling membuatmu tertawa?",
    "Wofür sparen wir gemeinsam?" to "Untuk apa kita menabung bersama?",
    "Wohnzimmer" to "Ruang tamu",
    "Woran erinnerst du dich am lebhaftesten?" to "Apa yang paling Anda ingat dengan jelas?",
    "Worauf freust du dich bei uns am meisten?" to "Apa yang paling Anda nantikan bersama kami?",
    "Worte/Komplimente" to "Kata-kata/Pujian",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Apa yang paling kamu takuti dalam hubungan kita?",
    "Wünsche? z.B. günstig, draußen" to "Harapan? misalnya murah, di luar",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Apakah Anda lebih suka melamar liburan (melibatkan perjalanan)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube Musik",
    "Zeichne für mich" to "Gambarlah untukku",
    "Zeichne mich als Tier — welches wäre ich?" to "Gambarkan aku sebagai binatang - aku akan menjadi binatang yang mana?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Gambarkan perasaan kita terhadap satu sama lain sebagai simbol.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Gambarlah rumah impian kita dalam satu garis. Hal apa yang paling mencolok?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Gambarlah kencan pertama kita - apa yang pasti ada di gambar itu?",
    "Zeichnen" to "Seri",
    "Zeit füreinander" to "Waktunya untuk satu sama lain",
    "Zeit, wenn das Baby schläft" to "Waktu bayi tidur",
    "Zelten gehen" to "Pergi berkemah",
    "Zitrone" to "Jeruk nipis",
    "Zu Hause, gemütlich und privat" to "Di rumah, nyaman dan pribadi",
    "Zu einem Picknick gehen" to "Pergi piknik",
    "Zu einem ausgefallenen Abendessen gehen" to "Pergi ke makan malam mewah",
    "Zu zweit reisen" to "Bepergian bersama pasangan",
    "Zuhause & Alltag" to "Rumah & kehidupan sehari-hari",
    "Zuhören" to "Dengar",
    "Zurück" to "Kembali",
    "Zusammen seit" to "Bersama sejak itu",
    "Zusammen seit (TT.MM.JJJJ)" to "Bersama sejak (DD.MM.YYYY)",
    "Zusammenziehen" to "Kontrak",
    "Zustimmen oder Ablehnen" to "Setuju atau Tidak Setuju",
    "Zwei Kreise, die sich überschneiden" to "Dua lingkaran yang saling tumpang tindih",
    "Zwei Stühle davor" to "Dua kursi di depannya",
    "Zärtlich sein" to "Bersikaplah lembut",
    "Öfter als ich zugebe" to "Lebih sering dari yang saya akui",
    "Über 100€/Monat" to "Lebih dari 100€/bulan",
    "Über 2000 im Monat" to "Lebih dari 2000 sebulan",
    "Über mich selbst" to "Tentang diriku sendiri",
    "Übernehmen" to "Terapkan",
    "Überraschend" to "Mengejutkan",
    "Überraschung" to "Kejutan",
    "Überspringen" to "Lewati",
    "Übertrieben und großartig" to "Berlebihan dan mengagumkan",
    "✎ Tippe, um zu antworten" to "✎ Ketuk untuk membalas",
    "✨ GFK-Brücke" to "✨ Jembatan GRP",
)

internal fun localizeIndonesianDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_INDONESIAN_CONTENT)
