package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_KHMER_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 ឆ្នាំ។",
    "1000 - 1500 im Monat" to "1000 - 1500 ក្នុងមួយខែ",
    "1000 bis 3000" to "1000 ទៅ 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 ក្នុងមួយខែ",
    "3000 bis 5000" to "ពី 3000 ទៅ 5000",
    "5-10 Jahre" to "៥-១០ ឆ្នាំ។",
    "50-100€/Monat" to "50-100€/ខែ",
    "Ab 100€" to "ពី 100 €",
    "Ab 500€" to "ពី 500 €",
    "Ab 50€" to "ពី 50€",
    "Ab und zu" to "រាល់ពេលឥឡូវនេះ",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "តើយើងត្រូវចំណាយប៉ុន្មានមុននឹងធ្វើការទិញ?",
    "Abbrechen" to "បោះបង់",
    "Abenteuer" to "ដំណើរផ្សងព្រេង",
    "Adidas" to "អាឌីដាស",
    "Aktivitäten" to "សកម្មភាព",
    "Alle" to "ទាំងអស់។",
    "Alle Pakete" to "កញ្ចប់ទាំងអស់។",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "បាត់បង់មិត្តរបស់អ្នកទាំងអស់ លើកលែងតែមិត្តល្អបំផុតរបស់អ្នក។",
    "Alle intimen Momente selbst initiieren" to "ចាប់ផ្តើមគ្រាស្និទ្ធស្នាលទាំងអស់ដោយខ្លួនឯង។",
    "Alles davon" to "ទាំងអស់។",
    "Alles, was noch kommt" to "អ្វីគ្រប់យ៉ាងដែលនឹងមកដល់",
    "Alltagsroutine" to "ទម្លាប់ប្រចាំថ្ងៃ",
    "Alltägliche Berührungen" to "ប៉ះរាល់ថ្ងៃ",
    "Altbau mit Charme" to "អាគារចាស់ដែលមានមន្តស្នេហ៍",
    "Am Strand" to "នៅលើឆ្នេរខ្សាច់",
    "Am liebsten alles zusammen" to "ចូលចិត្តអ្វីគ្រប់យ៉ាងរួមគ្នា",
    "Am selben Tag mit Freunden/Familie" to "ថ្ងៃតែមួយជាមួយមិត្តភក្តិ/គ្រួសារ",
    "Amazon" to "Amazon",
    "Amsterdam" to "ទីក្រុង Amsterdam",
    "Amsterdam, Niederlande" to "ទីក្រុង Amsterdam ប្រទេសហូឡង់",
    "An das Gefühl" to "នៃអារម្មណ៍",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "នៅកន្លែងសាធារណៈដែលមានអ្នកទស្សនាច្រើន។",
    "An einen Geruch" to "ក្លិនក្រអូប",
    "An einen Song" to "ទៅបទចម្រៀងមួយ។",
    "An etwas, das ich gesagt habe" to "អ្វីមួយដែលខ្ញុំបាននិយាយ",
    "Analyse starten" to "ចាប់ផ្តើមការវិភាគ",
    "Analysiere eure Muster..." to "វិភាគគំរូរបស់អ្នក...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "វិភាគចម្លើយ និងការជជែករបស់អ្នកយោងទៅតាម Gottman និង GFK ។",
    "Ananas auf der Pizza schmeckt köstlich." to "ម្នាស់នៅលើភីហ្សាមានរសជាតិឆ្ងាញ់។",
    "Android" to "ប្រព័ន្ធប្រតិបត្តិការ Android",
    "Antwort mit einem Foto" to "ឆ្លើយតបជាមួយរូបថត",
    "Antwortähnlichkeit" to "ឆ្លើយស្រដៀងគ្នា",
    "App-Sprache auswählen" to "ជ្រើសរើសភាសាកម្មវិធី",
    "Auf eine Bootsparty gehen" to "ទៅពិធីជប់លៀងទូក",
    "Aufmerksamkeit" to "យកចិត្តទុកដាក់",
    "Aufräumen und Projekte angehen" to "សម្អាត និងដោះស្រាយគម្រោង",
    "Aufwärmen" to "កំដៅឡើង",
    "Aufwärmen: Einander kennenlernen" to "កក់ក្តៅ៖ ស្គាល់គ្នា។",
    "Aus dem Urlaub" to "ពីវិស្សមកាល",
    "Ausgefallener Name" to "ឈ្មោះក្លែងក្លាយ",
    "Ausschlafen und faulenzen" to "គេងហើយខ្ជិលជុំវិញ",
    "Ausschlafen und nichts tun" to "ចូលគេងហើយមិនធ្វើអ្វីសោះ",
    "Aussehen" to "រូបរាង",
    "Auto" to "ស្វ័យប្រវត្តិ",
    "Außenkamin" to "ចើងរកានកមដោខាងក្រៅ",
    "BEANTWORTE" to "ចម្លើយ",
    "Bali" to "បាលី",
    "Bali, Indonesien" to "កោះបាលី ប្រទេសឥណ្ឌូនេស៊ី",
    "Banane" to "ចេក",
    "Beantwortet" to "ឆ្លើយ",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "ឆ្លើយសំណួរក្នុងពេលតែមួយ — ចម្លើយនឹងមិនអាចមើលឃើញទេ រហូតដល់អ្នកទាំងពីរបានបញ្ចប់។",
    "Beantwortete Fragen" to "បានឆ្លើយសំណួរ",
    "Bearbeiten" to "កែសម្រួល",
    "Bei Insider-Witzen" to "សម្រាប់រឿងកំប្លែងខាងក្នុង",
    "Bei Memes" to "នៅលើ memes",
    "Bei einer spontanen Berührung" to "ពេលប៉ះដោយឯកឯង",
    "Beide" to "ទាំងពីរ",
    "Beide gleich" to "ទាំងពីរដូចគ្នា។",
    "Beide zusammen" to "ទាំងពីររួមគ្នា",
    "Beide, aber wir tun so als ob nicht" to "ទាំងពីរ ប៉ុន្តែយើងធ្វើពុតជាមិនមែនទេ។",
    "Beides" to "ទាំងពីរ",
    "Beides wäre schlimm" to "ទាំងពីរនឹងអាក្រក់",
    "Beim Einschlafen nebeneinander" to "ដេកលក់ក្បែរគ្នា។",
    "Beim Reden" to "ពេលកំពុងនិយាយ",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "កន្លែងទេសចរណ៍ល្បីៗតែងតែមានការខកចិត្ត។",
    "Beschreibe unser Sexleben mit einem Emoji." to "ពិពណ៌នាអំពីជីវិតផ្លូវភេទរបស់យើងជាមួយនឹងសញ្ញាអារម្មណ៍។",
    "Besser kommunizieren" to "ទំនាក់ទំនងកាន់តែប្រសើរ",
    "Bessere Lage" to "ទីតាំងកាន់តែប្រសើរ",
    "Bestellen" to "បញ្ជាទិញ",
    "Besuchte Länder" to "ប្រទេសដែលបានទស្សនា",
    "Besuchte Städte" to "ទីក្រុងបានទស្សនា",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "តើ​អ្នក​ចូលចិត្ត​សំណើ​ហួសហេតុ​ឬ​អ្វី​ដែល​ស្រទន់?",
    "Beziehung" to "ទំនាក់ទំនង",
    "Bibliothek" to "បណ្ណាល័យ",
    "Bin manchmal unsicher" to "ពេលខ្លះខ្ញុំគ្មានសុវត្ថិភាព",
    "Bist du ein Videospiel-Guru?" to "តើអ្នកជាគ្រូវីដេអូហ្គេមមែនទេ?",
    "Blumenwiese" to "វាលស្មៅផ្កា",
    "Bunte Blumenwiese" to "វាលស្មៅផ្កាចម្រុះពណ៌",
    "Burger" to "ប៊ឺហ្គឺ",
    "Burger King" to "ប៊ឺហ្គឺឃីង",
    "Chat" to "ជជែក",
    "Coca-Cola" to "កូកាកូឡា",
    "Cookie Dough" to "Cookie Dough",
    "Dachgarten mit Lounge" to "សួនដំបូលជាមួយកន្លែងទទួលភ្ញៀវ",
    "Dachterrasse" to "ដំបូលរាបស្មើ",
    "Das Wetter an dem Tag" to "អាកាសធាតុនៅថ្ងៃនោះ។",
    "Das erste Selfie" to "ការថតសែលហ្វីដំបូង",
    "Das meiste weiß ich" to "ខ្ញុំស្គាល់វាភាគច្រើន",
    "Das oder das?" to "នេះឬនោះ?",
    "Das tägliche Leben" to "ជីវិតប្រចាំថ្ងៃ",
    "Dass Zusagen gehalten werden" to "ការសន្យានោះត្រូវបានរក្សាទុក",
    "Dass alles meinen Stil hat" to "ថាអ្វីគ្រប់យ៉ាងមានស្ទីលរបស់ខ្ញុំ",
    "Dass ich alles erzählen kann" to "ដែលខ្ញុំអាចប្រាប់អ្វីៗទាំងអស់។",
    "Dass ich mich nicht sorgen muss" to "ថាខ្ញុំមិនចាំបាច់បារម្ភទេ។",
    "Dass wir ungestört sind" to "ថាយើងមិនរំខាន",
    "Dein Name" to "ឈ្មោះរបស់អ្នក។",
    "Deine Antwort..." to "ចម្លើយរបស់អ្នក...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "ចម្លើយរបស់អ្នកត្រូវបានរក្សាទុក។ ដរាបណាដៃគូបញ្ចប់កញ្ចប់ ចម្លើយទាំងពីរនឹងអាចមើលឃើញជាមួយគ្នា។",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "ចម្លើយរបស់អ្នកត្រូវបានរក្សាទុក។ នៅពេលដែល \${profile.partnerName} បញ្ចប់កញ្ចប់ ការឆ្លើយតបទាំងពីរនឹងអាចមើលឃើញជាមួយគ្នា។",
    "Deine Beziehung abenteuerlich und spontan machen" to "ធ្វើឱ្យទំនាក់ទំនងរបស់អ្នកដំណើរផ្សងព្រេង និងដោយឯកឯង",
    "Deine Beziehung stabil und sicher machen" to "ធ្វើឱ្យទំនាក់ទំនងរបស់អ្នកមានស្ថេរភាព និងសុវត្ថិភាព",
    "Deine eigene Antwort" to "ចម្លើយផ្ទាល់ខ្លួនរបស់អ្នក។",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "វាជាការប្រសើរក្នុងការចែករំលែកអាថ៌កំបាំងដ៏ជ្រាលជ្រៅរបស់អ្នកជាមួយដៃគូរបស់អ្នក។",
    "Deinen besten Freund verlieren" to "បាត់បង់មិត្តល្អបំផុតរបស់អ្នក។",
    "Denke an dich" to "គិតពីខ្លួនឯង",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "មើលរឿងដដែលពីរដងគឺខ្ជះខ្ជាយពេលវេលា។",
    "Der Blick nach draußen" to "ទិដ្ឋភាពខាងក្រៅ",
    "Der Garten" to "សួន",
    "Der Ort" to "កន្លែង",
    "Der Ring und die Geste" to "ចិញ្ចៀន និងកាយវិការ",
    "Der perfekte Heiratsantrag" to "សំណើអាពាហ៍ពិពាហ៍ដ៏ល្អឥតខ្ចោះ",
    "Derjenige sein, der umarmt wird" to "ធ្វើជាមនុស្សដែលត្រូវឱប",
    "Deutsch" to "អាឡឺម៉ង់",
    "Diamant" to "ពេជ្រ",
    "Diamanten im Band" to "ពេជ្រក្នុងក្រុម",
    "Die Distanz" to "ចម្ងាយ",
    "Die Feiertage mit der Familie deines Partners verbringen" to "ចំណាយពេលវិស្សមកាលជាមួយគ្រួសារដៃគូរបស់អ្នក។",
    "Die Gemütlichkeit und Ruhe" to "ការលួងលោម និងសន្តិភាព",
    "Die Menschen, die darin wohnen" to "មនុស្សដែលរស់នៅក្នុងនោះ។",
    "Die Umgebung und Atmosphäre" to "បរិស្ថាន និងបរិយាកាស",
    "Die Worte und Emotionen" to "ពាក្យនិងអារម្មណ៍",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "ការប្រកួតកំសាន្ដកំសាន្ដចុងក្រោយ",
    "Diejenige sein, die umarmt" to "ធ្វើជាអ្នកឱប",
    "Direkt ansprechen" to "អាស័យដ្ឋានដោយផ្ទាល់",
    "Diskussion" to "ការពិភាក្សា",
    "Diskutiere vor dem Kinderkriegen" to "ពិភាក្សាមុនពេលមានកូន",
    "Diskutiert eure Antworten" to "ពិភាក្សាអំពីចម្លើយរបស់អ្នក។",
    "Disney" to "Disney",
    "Doch, schon mal" to "បាទ បាទ",
    "Draußen mit der Natur als Kulisse" to "នៅខាងក្រៅជាមួយធម្មជាតិជាផ្ទៃខាងក្រោយ",
    "Drei-Stein-Ring" to "ចិញ្ចៀនថ្មបី",
    "Du bist dran" to "ដល់វេនអ្នក។",
    "Du fehlst mir" to "ខ្ញុំនឹកអ្នក។",
    "Dubai" to "ឌូបៃ",
    "Dubai, VAE" to "ឌូបៃ អារ៉ាប់រួម",
    "Dunkles Design" to "រូបរាងងងឹត",
    "Durch Berührung" to "ដោយការប៉ះ",
    "Durch Worte" to "តាមរយៈពាក្យ",
    "Durch Zeit zu zweit" to "ឆ្លងកាត់ពេលវេលាជាមួយគ្នា",
    "Durch kleine Gesten" to "តាមរយៈកាយវិការតូចៗ",
    "Durchgeplant" to "រៀបចំផែនការបានល្អ",
    "ERGEBNISSE" to "លទ្ធផល",
    "Egal, Hauptsache gesund" to "អ្វីក៏ដោយ សំខាន់គឺសុខភាព",
    "Ehepaar Leben" to "ជីវិតប្តីប្រពន្ធ",
    "Eher knapp" to "ជិតដល់ហើយ។",
    "Eher nicht" to "មិនច្រើនទេ។",
    "Eher schwer" to "ពិបាកណាស់។",
    "Eher schwierig" to "ពិបាកណាស់។",
    "Eher zu" to "ចូលចិត្តច្រើនទៀត",
    "Eifersucht ist ein Zeichen von Liebe." to "ការច្រណែនគឺជាសញ្ញានៃសេចក្តីស្រឡាញ់។",
    "Eigenes Gemüsebeet" to "បំណះបន្លែផ្ទាល់ខ្លួន",
    "Ein Abenteuer in einer neuen Stadt" to "ដំណើរផ្សងព្រេងក្នុងទីក្រុងថ្មី។",
    "Ein Anker" to "យុថ្កា",
    "Ein Balkon oder Garten" to "យ៉រ ឬសួនច្បារ",
    "Ein Filmabend" to "រាត្រីភាពយន្ត",
    "Ein Harmony-Meilenstein eurer Liebe." to "ភាពសុខដុមរមនានៃសេចក្តីស្រឡាញ់របស់អ្នក។",
    "Ein Herz" to "បេះដូង",
    "Ein Herz an der Tür" to "បេះដូងនៅមាត់ទ្វារ",
    "Ein Jahr lang eine Fernbeziehung führen" to "មានទំនាក់ទំនងផ្លូវឆ្ងាយរយៈពេលមួយឆ្នាំ",
    "Ein Kindheitsessen" to "អាហារកុមារភាព",
    "Ein Live-Musik-Konzert besuchen" to "ចូលរួមការប្រគុំតន្ត្រីបន្តផ្ទាល់",
    "Ein Museum besuchen" to "ទស្សនាសារមន្ទីរមួយ។",
    "Ein Spieleabend" to "យប់លេងហ្គេម",
    "Ein Spieleabend mit Freunden" to "រាត្រីលេងហ្គេមជាមួយមិត្តភក្តិ",
    "Ein Urlaubsfoto" to "រូបថតវិស្សមកាល",
    "Ein aktives Abenteuer" to "ដំណើរផ្សងព្រេងសកម្ម",
    "Ein entspannender Spa-Tag" to "ថ្ងៃសម្រាកស្ប៉ា",
    "Ein ganz normaler Alltagstag" to "ប្រចាំថ្ងៃធម្មតាទាំងស្រុង",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "រាត្រីដ៏កក់ក្ដៅនៅក្នុងផ្ទះ ពេលមានផ្គររន្ទះ",
    "Ein gemütliches Date drinnen" to "កាលបរិច្ឆេទដ៏កក់ក្ដៅក្នុងផ្ទះ",
    "Ein lustiges Bild" to "រូបភាពគួរឱ្យអស់សំណើច",
    "Ein paar Handyfotos reichen" to "រូបថតទូរសព្ទដៃពីរបីគឺគ្រប់គ្រាន់ហើយ។",
    "Ein paar Stunden" to "ពីរបីម៉ោង",
    "Ein paar kulturelle Anklänge sind okay" to "ឯកសារយោងវប្បធម៌មួយចំនួនមិនអីទេ។",
    "Ein romantischer Abend" to "រាត្រីស្នេហា",
    "Ein romantisches Abendessen bei Kerzenlicht" to "អាហារពេលល្ងាចក្រោមភ្លើងទៀនដ៏រ៉ូមែនទិក",
    "Ein romantisches Bild" to "រូបភាពមនោសញ្ចេតនា",
    "Ein romantisches Picknick an einem schönen Ort" to "អាហារដ្ឋានបែបរ៉ូមែនទិកនៅទីតាំងដ៏ស្រស់ស្អាត",
    "Ein schwerer Moment, den wir geschafft haben" to "គ្រាដ៏លំបាកមួយដែលយើងបានគ្រប់គ្រង",
    "Ein tolles Date im Freien unter dem Mondlicht" to "កាលបរិច្ឆេទដ៏អស្ចារ្យនៅខាងក្រៅក្រោមពន្លឺព្រះច័ន្ទ",
    "Ein ungewöhnliches Gericht" to "ម្ហូបមិនធម្មតា",
    "Ein zufälliger Schnappschuss" to "រូបថតចៃដន្យ",
    "Einander kennenlernen" to "ស្គាល់គ្នា។",
    "Eine Autoreise" to "ការធ្វើដំណើរតាមផ្លូវ",
    "Eine Brücke" to "ស្ពាន",
    "Eine Date-Nacht unter den Sternen" to "រាត្រីណាត់ជួបក្រោមផ្កាយ",
    "Eine Million Dollar gewinnen" to "ឈ្នះមួយលានដុល្លារ",
    "Eine Million Dollar verdienen" to "រកបានមួយលានដុល្លារ",
    "Eine Nacht in einem Club" to "យប់មួយក្នុងក្លឹប",
    "Eine Schokoladenverkostung" to "រសជាតិសូកូឡា",
    "Eine Wanderung mit Panoramablick machen" to "ដើរលេងជាមួយទេសភាពបែប Panoramic",
    "Eine Weinverkostung" to "រសជាតិស្រា",
    "Eine gemeinsame Reise" to "ដំណើរកំសាន្តជាមួយគ្នា",
    "Eine gemütliche Nacht zu Hause" to "រាត្រីដ៏កក់ក្ដៅនៅផ្ទះ",
    "Eine neue Sprache zu lernen ist einfach." to "ការរៀនភាសាថ្មីគឺងាយស្រួល។",
    "Einen Film anschauen" to "មើលភាពយន្ត",
    "Einen Monat lang überhaupt nicht miteinander reden" to "មិននិយាយរកគ្នាអស់មួយខែ",
    "Einen Tanzkurs besuchen" to "ចូលរៀនរាំ",
    "Einen Vergnügungspark erkunden" to "រុករកសួនកម្សាន្ត",
    "Einen Wellness-Tag" to "ថ្ងៃសុខភាព",
    "Einen sehr emotionalen Partner haben" to "មានដៃគូរអារម្មណ៍ខ្លាំង",
    "Einen sehr logischen Partner haben" to "មានដៃគូសមហេតុផលណាស់។",
    "Einer zahlt alles" to "មនុស្សម្នាក់បង់អ្វីៗគ្រប់យ៉ាង",
    "Einfach mehr Alltag" to "ជីវិតប្រចាំថ្ងៃកាន់តែសាមញ្ញ",
    "Einfach nebeneinander sein" to "គ្រាន់តែនៅក្បែរគ្នា។",
    "Einfach und intim" to "សាមញ្ញ និងស្និទ្ធស្នាល។",
    "Einige Dinge für dich behalten" to "រក្សារបស់ខ្លះសម្រាប់ខ្លួនអ្នក",
    "Einmal" to "ម្តង",
    "Eins, das nur wir kennen" to "មានតែយើងទេដែលដឹង",
    "Englisch" to "ភាសាអង់គ្លេស",
    "Entspannte Hängematte" to "អង្រឹងសម្រាក",
    "Entspannung" to "ការសំរាកលំហែ",
    "Erdbeere" to "ផ្លែស្ត្របឺរី",
    "Erfolgreich" to "ជោគជ័យ",
    "Ergebnisse" to "លទ្ធផល",
    "Erst bei sehr großen Summen" to "សម្រាប់តែផលបូកធំប៉ុណ្ណោះ។",
    "Erst nur enge Freunde/Familie" to "មានតែមិត្តភ័ក្តិជិតស្និទ្ធ/គ្រួសារដំបូងប៉ុណ្ណោះ។",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "វារំខានខ្ញុំនៅពេលដែលដៃគូរបស់ខ្ញុំចំណាយពេលយូរពេកក្នុងការឆ្លើយតបទៅនឹងសារ។",
    "Essen & Genuss" to "អាហារ និងការកម្សាន្ត",
    "Essensvorlieben" to "ចំណូលចិត្តអាហារ",
    "Etwa eine Woche später, erst mal nur wir" to "ប្រហែលមួយសប្តាហ៍ក្រោយមក គ្រាន់តែពួកយើងដំបូងប៉ុណ្ណោះ។",
    "Etwas Neues ausprobieren" to "សាកល្បងអ្វីថ្មី។",
    "Etwas ganz anderes" to "មានអ្វីខុសគ្នាទាំងស្រុង",
    "Etwas sehr Scharfes" to "អ្វីមួយច្បាស់ណាស់។",
    "Etwas, das ich selbst gern erfinde" to "អ្វីមួយដែលខ្ញុំចូលចិត្តបង្កើតខ្លួនឯង",
    "Etwas, eine kleine Note wäre schön" to "អ្វីមួយ ចំណាំតូចមួយនឹងល្អ។",
    "Familie" to "គ្រួសារ",
    "Familie/Freunde" to "គ្រួសារ/មិត្តភក្តិ",
    "Familienmensch" to "បុរសគ្រួសារ",
    "Farbedelstein" to "ត្បូងពណ៌",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "ការផ្សាយពាណិជ្ជកម្មតាមទូរទស្សន៍ ជួនកាលគួរឱ្យចាប់អារម្មណ៍ក្នុងការមើល។",
    "Fertig" to "រួចរាល់",
    "Fertig!" to "រួចរាល់!",
    "Feste Date-Nights" to "យប់កាលបរិច្ឆេទថេរ",
    "Feuerstelle" to "រណ្តៅភ្លើង",
    "Filigran & schlicht" to "Filigree & សាមញ្ញ",
    "Filme/Serien" to "ភាពយន្ត/ស៊េរី",
    "Formuliere um..." to "ប្រយោគ...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "សរសេរឡើងវិញនូវសេចក្តីព្រាងរបស់អ្នកតាមរបៀបអហិង្សា៖ ការសង្កេត អារម្មណ៍ តម្រូវការ សំណើ។",
    "Frage hinzufügen" to "បន្ថែមសំណួរ",
    "Fragen & Spiele" to "សំណួរ និងហ្គេម",
    "Fragen für jede Gelegenheit" to "សំណួរសម្រាប់គ្រប់ឱកាស",
    "Freizeitpark" to "សួនកម្សាន្ត",
    "Freunde treffen" to "ជួបមិត្តភក្តិ",
    "Freundschaften mit Ex-Partnern sind okay." to "មិត្តភាពជាមួយ exe មិនអីទេ។",
    "Früh aufstehen" to "ក្រោកពីព្រលឹម",
    "Fußbodenheizung" to "កំដៅក្រោមដី",
    "Führen wir getrennte oder gemeinsame Konten?" to "តើយើងមានគណនីដាច់ដោយឡែក ឬរួមគ្នាទេ?",
    "Für dich empfohlen" to "បានណែនាំសម្រាប់អ្នក",
    "Für die Zukunft" to "សម្រាប់ពេលអនាគត",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "រកមិនឃើញសំណួរ ឬហ្គេមដែលត្រូវគ្នាសម្រាប់ការស្វែងរកនេះទេ។",
    "Für immer" to "ជារៀងរហូត",
    "Fürsorglichkeit" to "ការយកចិត្តទុកដាក់",
    "GFK-Brücke" to "ស្ពាន GRP",
    "Galerie" to "វិចិត្រសាល",
    "Gar nicht, der Moment gehört uns" to "មិនមែនទាល់តែសោះ ពេលនេះជារបស់យើងហើយ។",
    "Gar nichts tun" to "កុំធ្វើអ្វី",
    "Geduld" to "អត់ធ្មត់",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "ទៅព្រលឹមដើម្បីមើលថ្ងៃរះ",
    "Geht so" to "ទៅដូចនេះ",
    "Geister existieren wirklich." to "ខ្មោចពិតជាមានមែន។",
    "Gelassenheit" to "ភាពស្ងប់ស្ងាត់",
    "Gelbgold" to "មាសលឿង",
    "Geld & Finanzen" to "លុយ និងហិរញ្ញវត្ថុ",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "ធ្វើដំណើរជុំវិញពិភពលោកជាមួយគ្នា ស្វែងយល់ពីវប្បធម៌ និងមុខម្ហូបថ្មីៗ",
    "Gemeinsam ein Lego bauen" to "បង្កើត Lego ជាមួយគ្នា",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "សាកល្បងរូបមន្តថ្មីជាមួយគ្នានៅក្នុងផ្ទះបាយ",
    "Gemeinsame Konten" to "គណនីដែលបានចែករំលែក",
    "Gemeinsame Nächte" to "យប់ជាមួយគ្នា",
    "Gemeinsame Tage" to "ថ្ងៃជាមួយគ្នា",
    "Gemischt" to "លាយ",
    "Gemüsebeet" to "បំណះបន្លែ",
    "Gemütliche Feuerstelle" to "ចើងរកានកមដោ",
    "Gesprächsanreger" to "ការចាប់ផ្តើមការសន្ទនា",
    "Getrennte Konten" to "គណនីដាច់ដោយឡែក",
    "Getrennte Urlaube tun einer Beziehung gut." to "វិស្សមកាលដាច់ដោយឡែកគឺល្អសម្រាប់ទំនាក់ទំនង។",
    "Gewächshaus" to "ផ្ទះកញ្ចក់",
    "Glasfassade" to "មុខកញ្ចក់",
    "Gleichgültigkeit" to "ព្រងើយកណ្តើយ",
    "Glücklich und frei" to "រីករាយ និងឥតគិតថ្លៃ",
    "Gourmet Eis-Sorten" to "ប្រភេទការ៉េមឆ្ងាញ់",
    "Gravur innen" to "ឆ្លាក់នៅខាងក្នុង",
    "Grillplatz" to "កន្លែងសាច់អាំង",
    "Groß & üppig" to "ធំ & ខៀវស្រងាត់",
    "Große Familie" to "គ្រួសារធំ",
    "Große Feier" to "ការប្រារព្ធពិធីដ៏ធំ",
    "Große Fenster" to "បង្អួចធំ",
    "Große Fensterfront" to "មុខបង្អួចធំ",
    "Großer Außenpool" to "អាងហែលទឹកខាងក្រៅដ៏ធំ",
    "Großer Garten" to "សួនច្បារធំ",
    "Großer Stein" to "ថ្មធំ",
    "Größere Küche" to "ផ្ទះបាយធំជាង",
    "Gutes Essen" to "អាហារឆ្ងាញ់",
    "Habe ich" to "ខ្ញុំបានធ្វើ",
    "Habe ich noch nie" to "ខ្ញុំមិនដែលមានទេ។",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "តើអ្នកបានរកឃើញភាពខុសគ្នាគួរឱ្យភ្ញាក់ផ្អើលទេ? និយាយអំពីមូលហេតុដែលអ្នកចូលចិត្តជម្រើសជាក់លាក់ប្រសើរជាង!",
    "Haus am See" to "ផ្ទះក្បែរបឹង",
    "Haus/Wohnung" to "ផ្ទះ/អាផាតមិន",
    "Hazelnut" to "ហាហ្សែលណាត់",
    "Heimkino" to "ល្ខោនផ្ទះ",
    "Herzhaft" to "ពិរោះ",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "មិនមានអ្វីនៅទីនេះទេឥឡូវនេះ។\nផ្លាស់ប្តូរតម្រង ឬជ្រើសរើសប្រធានបទផ្សេង។",
    "Hilfe im Alltag" to "ជួយក្នុងជីវិតប្រចាំថ្ងៃ",
    "Himbeere" to "Raspberry",
    "Hinzufügen" to "បន្ថែម",
    "Hobbys" to "ចំណូលចិត្ត",
    "Hochzeitssträuße" to "ភួងអាពាហ៍ពិពាហ៍",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Hogwarts House Pride៖ តើអ្នកជាកម្មសិទ្ធិនៅឯណា?",
    "Home" to "ផ្ទះ",
    "Hot Tub" to "ធុងទឹកក្តៅ",
    "Humor" to "កំប្លែង",
    "Hund" to "ឆ្កែ",
    "Hängematte" to "អង្រឹង",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "តើអ្នកចង់បានសំបុត្រជាលាយលក្ខណ៍អក្សរជាផ្នែកនៃសំណើរទេ?",
    "IKEA" to "IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "ខ្ញុំចូលចិត្តដើរលេងបែបរ៉ូមែនទិកក្នុងសួន ដើម្បីទៅរោងកុន។",
    "Ich bin noch nie in einem Kino eingeschlafen." to "ខ្ញុំមិនដែលដេកលក់ក្នុងរោងកុនទេ។",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "ខ្ញុំរីករាយក្នុងការស្វែងរកចំណូលចិត្ត ឬសកម្មភាពថ្មីៗជាមួយដៃគូរបស់ខ្ញុំ។",
    "Ich finde eine Alternative" to "ខ្ញុំនឹងរកជម្រើសជំនួស",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "ខ្ញុំចូលចិត្តសាកល្បងភោជនីយដ្ឋានថ្មីៗជាមួយដៃគូរបស់ខ្ញុំ ជាជាងទៅកន្លែងដដែលៗ។",
    "Ich habe noch nie" to "ខ្ញុំមិនដែលទេ។",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "ខ្ញុំមិនដែលខ្លាចរទេះរុញទេ ហើយខ្ញុំក៏ឡើងលើវាដែរ។",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "ខ្ញុំមិនដែលទិញសំបុត្រ Fast Pass ទេ ព្រោះខ្ញុំមិនចេះអត់ធ្មត់។",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "ខ្ញុំមិនដែលលុបចោលគម្រោងស្នាក់នៅផ្ទះ និងមើលកម្មវិធីទូរទស្សន៍ទេ។",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "ខ្ញុំមិនដែលរង់ចាំសំបុត្ររបស់ខ្ញុំពី Hogwarts ទេ។",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "ខ្ញុំមិនដែលនិយាយថា Slytherin ពិតជាមិនអាក្រក់នោះទេ។",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "ខ្ញុំមិនដែលនិយាយថាខ្ញុំចាស់ពេកសម្រាប់ភាពយន្ត Disney (ហើយចូលចិត្តវាដោយសម្ងាត់)។",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "ខ្ញុំមិនដែលមានចេតនាបាញ់ទម្លាក់នរណាម្នាក់ដែលមានធុងពណ៌ខៀវនៅក្នុង Mario Kart ទេ។",
    "Ich habe noch nie bei einem Disney-Film geweint." to "ខ្ញុំមិនដែលយំនៅភាពយន្ត Disney ទេ។",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "ខ្ញុំមិនដែលបិទភ្នែកទេ ពេលកំពុងមើលរឿងភ័យរន្ធត់។",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "ខ្ញុំមិនដែលភ្លេចរក្សាទុកហ្គេមទេ ហើយបាត់បង់ដំណើរការជាច្រើនម៉ោង។",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "ខ្ញុំមិនដែលចេញពីបន្ទប់ទេ អំឡុងពេលមានឈុតឆាកដ៏អាម៉ាស់ (កត្តាគួរឱ្យខ្លាច)។",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "ខ្ញុំមិនដែលធ្វើរូបកំប្លែងពេលកំពុងថតរូប rollercoaster ទេ។",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "ខ្ញុំមិនដែលលេងហ្គេមយប់ជ្រៅទេ ហើយស្ដាយក្រោយដែលខ្ញុំនឿយហត់នៅថ្ងៃបន្ទាប់។",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "ខ្ញុំមិនដែលស្វែងរកការបញ្ចប់នៃភាពយន្តទេ ព្រោះខ្ញុំមិនអាចរង់ចាំបាន។",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "ខ្ញុំមិនដែលមានអារម្មណ៍ថាខ្ញុំកំពុងឈរនៅលើឈុតភាពយន្តទេ។",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "ខ្ញុំមិនដែលរំលងការណែនាំនៃស៊េរីដែលខ្ញុំចូលចិត្តនោះទេ។",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "ខ្ញុំមិនដែលបានចែករំលែកពាក្យសម្ងាត់ Netflix របស់នរណាម្នាក់ផ្សេងទៀតទេ។",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "ខ្ញុំមិនដែលស្តាប់បទភ្លេងរបស់ហ្គេមនៅពេលធ្វើការ ឬសិក្សាទេ។",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "ខ្ញុំមិនដែលបន្ទោសឧបករណ៍បញ្ជាទេនៅពេលខ្ញុំបាត់។",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "ខ្ញុំមិនដែលបោះចោលក្តារចុច ឬឧបករណ៍បញ្ជាដោយកំហឹងទេ។",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "ខ្ញុំមិនដែលភ្លេចសម្លៀកបំពាក់សើមនៅក្នុងម៉ាស៊ីនបោកគក់ប៉ុន្មានថ្ងៃមកហើយ។",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "ខ្ញុំមិនដែលចំណាយលុយពិតប្រាកដលើគ្រឿងសម្អាងនៅក្នុងហ្គេមទេ។",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "ខ្ញុំមិនដែលបើកឡាននៅបរទេសទេ។",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "ខ្ញុំមិនដែលច្រៀងចម្រៀង Disney នៅក្នុងផ្កាឈូកទេ។",
    "Ich habe noch nie ein Elektroauto gefahren." to "ខ្ញុំមិនដែលបើកឡានអគ្គីសនីទេ។",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "ខ្ញុំមិនដែលថតរូបជាមួយម៉ាស្កូតសួនទេ។",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "ខ្ញុំមិនដែលដាក់ឈ្មោះសត្វចិញ្ចឹមតាមតួអង្គ Hogwarts ទេ។",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "ខ្ញុំមិនដែលទម្លាក់ពោតលីងនៅក្នុងរោងកុនទេ ហើយនៅតែញ៉ាំវា។",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "ខ្ញុំមិនដែលប្រើសម្រង់សម្តីរបស់ Master Yoda ពី Star Wars ក្នុងជីវិតប្រចាំថ្ងៃទេ។",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "ខ្ញុំមិនដែលទិញវត្ថុអនុស្សាវរីយថ្លៃលើសនៅសួនកម្សាន្តទេ។",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "ខ្ញុំមិនដែលផ្តល់ការណែនាំអំពីភាពយន្តដែលថាអ្នកដ៏ទៃឃើញអាក្រក់នោះទេ។",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "ខ្ញុំមិនដែលបានមើលការផ្សាយផ្ទាល់របស់ Oscar នៅកណ្តាលយប់ទេ។",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "ខ្ញុំមិនដែលលុបចោលស៊េរីទេ ពីព្រោះរដូវកាលចុងក្រោយគឺអាក្រក់ណាស់។",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "ខ្ញុំមិនដែលបានមើលរដូវកាលទាំងមូលនៃស៊េរីមួយក្នុងមួយថ្ងៃទេ។",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "ខ្ញុំមិនដែលចាញ់ចៅហ្វាយលើការសាកល្បងលើកដំបូងទេ ហើយមានអារម្មណ៍ថាដូចជាព្រះ។",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "ខ្ញុំមិនដែលរកឃើញមនុស្សអាក្រក់ជាងវីរបុរសទេ។",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "ខ្ញុំមិនដែលស្គាល់តួអង្គ Toy Story នៅក្នុងប្រដាប់ប្រដាក្មេងលេងផ្ទាល់ខ្លួនរបស់ខ្ញុំទេ។",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "ខ្ញុំមិនដែលបង្កើតតួអង្គក្នុង RPG ដូចខ្ញុំទេ។",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "ខ្ញុំមិនដែលញ៉ាំ churro នៅសួនកម្សាន្តទេ។",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "ខ្ញុំមិនដែលមើលរឿង Disney បីដងជាប់គ្នាទេ។",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "ខ្ញុំមិនដែលមានបទភ្លេងដ៏ទាក់ទាញរបស់ Disney ពេញមួយសប្តាហ៍។",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "ខ្ញុំមិនដែលមើលភាពយន្តទេ ដោយសារតួសម្តែងជាក់លាក់។",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "ខ្ញុំមិនដែលបានស្តាប់បទភ្លេងភាពយន្តម្តងហើយម្តងទៀតជាច្រើនម៉ោង។",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "ខ្ញុំមិនដែលបង្ហាញរឿង spoiler ភាពយន្តទេ ហើយសោកស្តាយភ្លាមៗ។",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "ខ្ញុំមិនបានរកឃើញមិត្តដែលនិយាយភាសាកំណើតផ្សេងទៀតទេ។",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "ខ្ញុំមិនដែលមានមិត្តភក្ដិដែលផ្លាស់ទៅប្រទេសផ្សេងទេ។",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "ខ្ញុំមិនដែលធ្វើម៉ារ៉ាតុងភាពយន្ត Harry Potter នៅបុណ្យណូអែលទេ។",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "ខ្ញុំមិនដែលមើលរឿង Marvel រហូតដល់ចប់ទេ ដោយសារតែឈុតក្រោយក្រេឌីត។",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "ខ្ញុំមិនដែលមានចេតនារំខាន NPC (តួអក្សរដែលមិនមែនជាអ្នកលេង) ទេ។",
    "Ich habe noch nie einen Nachtzug genommen." to "ខ្ញុំមិនដែលជិះរថភ្លើងពេលយប់ទេ។",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "ខ្ញុំមិនដែលបានធ្វើតេស្តតាមអ៊ីនធឺណិត ដើម្បីស្វែងរកផ្ទះ Hogwarts របស់ខ្ញុំទេ។",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "ខ្ញុំមិនដែលលុបការបង្ហោះតាមប្រព័ន្ធផ្សព្វផ្សាយសង្គមទេព្រោះវាមិនទទួលបានការចូលចិត្តគ្រប់គ្រាន់។",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "ខ្ញុំមិនដែលហៅមួយថ្ងៃនៅសួនកម្សាន្តថាជាថ្ងៃល្អបំផុតប្រចាំឆ្នាំទេ។",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "ខ្ញុំមិនដែលទៅលេងសួនកម្សាន្តទេ ហើយស្នាក់នៅទីនោះតាំងពីព្រឹកដល់យប់។",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "ខ្ញុំមិនដែលចាកចេញពីការជិះ Transformers ឬ Marvel គួរឱ្យចាប់អារម្មណ៍ទាំងស្រុងនោះទេ។",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "ខ្ញុំមិនដែលចោលកំហឹង ហើយឈប់លេងហ្គេមទេ។",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "ខ្ញុំមិនដែលអានសៀវភៅ Harry Potter ខ្នាតធំណាមួយទេ។",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "ខ្ញុំមិនដែលឈ្លក់វង្វេងនឹងតួអង្គដែលខ្ញុំចូលចិត្តក្នុងរឿងភាគទេ។",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "ខ្ញុំមិនដែលស្រមៃចង់លេង Quidditch ទេ។",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "ខ្ញុំមិនដែលលួចលាក់ Google ពីរបៀបដោះស្រាយកម្រិតពិបាកនោះទេ។",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "ខ្ញុំមិនដែលសង្ឃឹមថាសត្វចិញ្ចឹមរបស់ខ្ញុំអាចនិយាយដូចនៅក្នុង Disney នោះទេ។",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "ខ្ញុំមិនដែលដកប្រធានក្រុមនៅក្នុង Sims ចេញទេ។",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "ខ្ញុំមិនដែលបាត់បង់ខ្លាឃ្មុំរបស់ខ្ញុំក្នុងការជិះក្លែងធ្វើ 3D ទេ។",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "ខ្ញុំមិនដែលលេងក្នុងក្រុមកីឡាសាកលវិទ្យាល័យទេ។",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "ខ្ញុំមិនដែលរង់ចាំក្នុងជួរលើសពីពីរម៉ោងសម្រាប់ការទាក់ទាញតែមួយទេ។",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "ខ្ញុំមិនដែលយករបស់មានតម្លៃរបស់ខ្ញុំសើមពេលជិះទឹក។",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "ខ្ញុំមិនដែលប្រកែកជាមួយមិត្តភ័ក្តិអំពីផ្ទះមួយណាដែលល្អបំផុតនោះទេ។",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "ខ្ញុំមិនដែលធ្វើពុតថាមានអំណាចវេទមន្តដូច Elsa ទេ។",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "ខ្ញុំមិនដែលសើចខ្លាំងដែលខ្ញុំខកខានឈុតសំខាន់ក្នុងភាពយន្តនោះទេ។",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "ខ្ញុំមិនដែលមានអារម្មណ៍ adrenaline ច្រើនទេ ដែលខ្ញុំចង់ជិះម្តងទៀតភ្លាមៗ។",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "ខ្ញុំមិនដែលសាកល្បងច្រៀងជាមួយសត្វដូចជា Snow White ទេ។",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "ខ្ញុំមិនដែលស្រមៃចង់ទៅលេង Disneyland ទេ។",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "ខ្ញុំមិនដែលស្រមៃចង់ជិះលើទឹក Jurassic Park ទេ។",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "ខ្ញុំមិនដែលស្រែកខ្លាំងៗនៅពេលលោតបន្លាចក្នុងហ្គេមទេ។",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "ខ្ញុំមិនដែលយំនៅវគ្គផ្តាច់ព្រ័ត្រនៃកម្មវិធីទូរទស្សន៍ទេ។",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "ខ្ញុំមិនដែល... លុបចោលកាលបរិច្ឆេទដើម្បីស្នាក់នៅផ្ទះទេ។",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "ខ្ញុំមិនដែល ... សរសេរសារឡើងវិញ 10 ដងទេ។",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "ខ្ញុំមិនដែល...លួចមើលទូរសព្ទដៃរបស់ដៃគូខ្ញុំទេ។",
    "Ich habe noch nie!" to "ខ្ញុំមិនដែល!",
    "Ich habe!" to "ខ្ញុំមាន!",
    "Ich lache viel mit meinem Partner." to "ខ្ញុំសើចច្រើនជាមួយដៃគូរបស់ខ្ញុំ។",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "ខ្ញុំចូលចិត្តស្វែងយល់ពីចំណូលចិត្ត និងចំណាប់អារម្មណ៍របស់ដៃគូខ្ញុំ។",
    "Ich liebe es" to "ខ្ញុំចូលចិត្តវា។",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "ខ្ញុំចូលចិត្តមើលកុនជាមួយដៃគូរបស់ខ្ញុំ ដែលយើងទាំងពីរនាក់មិនដែលឃើញពីមុនមក។",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "ខ្ញុំចូលចិត្តចែករំលែកតន្ត្រីដែលខ្ញុំចូលចិត្តជាមួយដៃគូរបស់ខ្ញុំ។",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "ខ្ញុំមិនដែលរត់ដើម្បីចាប់ជើងហោះហើរដែលភ្ជាប់គ្នាទេ។",
    "Ich plane gerne Dates mit meinem Partner." to "ខ្ញុំចូលចិត្តរៀបចំកាលបរិច្ឆេទជាមួយដៃគូរបស់ខ្ញុំ។",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "ខ្ញុំផ្តល់អាទិភាពលើការចំណាយពេលវេលាជាមួយដៃគូរបស់ខ្ញុំ ទោះបីជាខ្ញុំរវល់ក៏ដោយ។",
    "Ich schreibe meinem Partner jeden Tag." to "ខ្ញុំផ្ញើសារទៅដៃគូរបស់ខ្ញុំជារៀងរាល់ថ្ងៃ។",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "ខ្ញុំចូលចិត្តចែករំលែក memes និងរឿងកំប្លែងជាមួយដៃគូរបស់ខ្ញុំ។",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "ខ្ញុំចូលចិត្តចែករំលែកព័ត៌មានលម្អិតនៃថ្ងៃរបស់ខ្ញុំជាមួយដៃគូរបស់ខ្ញុំ។",
    "Ich würde es nie tun" to "ខ្ញុំមិនដែលធ្វើវាទេ។",
    "Ich übe noch" to "ខ្ញុំនៅតែហាត់",
    "Ideen generieren" to "បង្កើតគំនិត",
    "Im Haushalt helfen" to "ជួយជុំវិញផ្ទះ",
    "In Chat einfügen" to "បន្ថែមទៅការជជែក",
    "In Stille nebeneinander" to "នៅស្ងៀមក្បែរគ្នា។",
    "In den Bergen" to "នៅលើភ្នំ",
    "In eine Bar gehen" to "ទៅរបារមួយ។",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "ទៅរបារឆ្នេរដើម្បីមើលថ្ងៃលិច",
    "In einem feinen Restaurant essen gehen" to "ញ៉ាំអាហារនៅភោជនីយដ្ឋានដ៏ល្អមួយ។",
    "In einen Coffeeshop gehen" to "ទៅហាងកាហ្វេ",
    "In einer Beziehung sollte man alles voneinander wissen." to "ក្នុងទំនាក់ទំនង អ្នកគួរតែដឹងគ្រប់យ៉ាងអំពីគ្នាទៅវិញទៅមក។",
    "Infinity-Pool" to "អាងទឹកគ្មានទីបញ្ចប់",
    "Innenpool" to "អាងហែលទឹកក្នុងផ្ទះ",
    "Intelligenz" to "បញ្ញា",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "មានតែពេលស្និទ្ធស្នាលប៉ុណ្ណោះ នៅពេលដែលដៃគូរបស់អ្នកផ្តួចផ្តើមគំនិតពួកគេ។",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "លេខកូដអញ្ជើញ៖ HRM-8731 · អ្វីគ្រប់យ៉ាងត្រូវបានដោះសោ",
    "Island" to "អ៊ីស្លង់",
    "Ist okay für mich" to "មិនអីទេជាមួយខ្ញុំ",
    "Ist schon perfekt" to "វាល្អឥតខ្ចោះ",
    "Ja, Traditionen einbinden" to "បាទ បញ្ចូលប្រពៃណី",
    "Ja, absolut" to "បាទ!",
    "Ja, etwas zum Lesen und Aufbewahren" to "បាទ មានអ្វីមួយដែលត្រូវអាន និងរក្សាទុក",
    "Ja, genug" to "បាទ គ្រប់គ្រាន់ហើយ។",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "បាទ នៅទីក្រុង ឬកន្លែងទាក់ទាញ",
    "Ja, in- und auswendig" to "បាទ ខាងក្នុង និងខាងក្រៅ",
    "Ja, komplett überraschend" to "បាទ គួរឱ្យភ្ញាក់ផ្អើលទាំងស្រុង",
    "Ja, perfekt" to "បាទ ល្អឥតខ្ចោះ",
    "Ja, sie gehören zur Familie!" to "បាទ ពួកគេជាគ្រួសារ!",
    "Ja, sofort teilen" to "បាទ ចែករំលែកភ្លាមៗ",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "បាទ យើងនឹងធានាថាពេលវេលាគ្រួសារជាអាទិភាព។",
    "Jacuzzi" to "Jacuzzi",
    "Jahr zusammen 🎉" to "ឆ្នាំជាមួយគ្នា 🎉",
    "Jahre zusammen 🎉" to "ឆ្នាំជាមួយគ្នា 🎉",
    "Jeder zahlt 50%" to "អ្នកគ្រប់គ្នាបង់ 50%",
    "Junge" to "ប្រុស",
    "Kamin" to "ចើងរកានកមដោ",
    "Karriere & Erfolg" to "អាជីព & ជោគជ័យ",
    "Kategorien" to "ប្រភេទ",
    "Katze" to "ឆ្មា",
    "Keine Musik" to "គ្មានតន្ត្រី",
    "Keine Party nötig, privat halten" to "មិនចាំបាច់មានពិធីជប់លៀងទេ ទុកវាជាឯកជន",
    "Keine Privatsphäre" to "គ្មានភាពឯកជនទេ។",
    "Keine Treffer gefunden" to "រកមិនឃើញការប្រកួតទេ។",
    "Keiner" to "គ្មានទេ។",
    "Keiner von uns" to "គ្មាននរណាម្នាក់ក្នុងចំណោមពួកយើងទេ។",
    "Kennst du die Essensvorlieben deines Partners?" to "តើអ្នកដឹងពីចំណូលចិត្តអាហាររបស់ដៃគូអ្នកទេ?",
    "Kino" to "រោងកុន",
    "Kirchlich" to "សាស្តា",
    "Klassisch Solitär" to "ទោលបុរាណ",
    "Klassisch gebunden" to "ចងបុរាណ",
    "Klein & zart" to "តូច និងឆ្ងាញ់",
    "Kleine Geschenke" to "អំណោយតូចៗ",
    "Kleine Runde" to "ក្រុមតូច",
    "Kochen und Freunde einladen" to "ធ្វើម្ហូប និងអញ្ជើញមិត្តភក្តិ",
    "Kochkurs" to "ថ្នាក់ធ្វើម្ហូប",
    "Kommt auf den Tag an" to "អាស្រ័យលើថ្ងៃ",
    "Kommt darauf an" to "វាអាស្រ័យ",
    "Kommt drauf an" to "វាអាស្រ័យ",
    "Kommt mit" to "មកជាមួយខ្ញុំ",
    "Konzert" to "ការប្រគុំតន្ត្រី",
    "Kräftige Farben" to "ពណ៌ខ្លាំង",
    "Kräuterbeet" to "គ្រែរុក្ខជាតិ",
    "Kultur & Sehenswürdigkeiten" to "វប្បធម៌ និងទេសភាព",
    "Kuscheln" to "ការថើប",
    "Kuss senden" to "ផ្ញើស្នាមថើបមួយ។",
    "Körperliche Annäherung" to "កាយវិការ",
    "Körperliche Nähe" to "ភាពជិតស្និទ្ធខាងរាងកាយ",
    "Küche" to "ផ្ទះបាយ",
    "Land" to "ប្រទេស",
    "Landhaus" to "ផ្ទះប្រទេស",
    "Landhausstil" to "រចនាប័ទ្មផ្ទះប្រទេស",
    "Lange wach bleiben" to "ចូលគេងយឺត",
    "Lappland" to "ឡាបលែន",
    "Lappland, Finnland" to "Lapland ប្រទេសហ្វាំងឡង់",
    "Las Vegas" to "ឡាសវេហ្គាស",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "អនុញ្ញាតឱ្យដៃគូរបស់អ្នកជម្រុញអ្នកឱ្យក្លាយជាខ្លួនឯងដ៏ល្អបំផុតរបស់អ្នក។",
    "Lehne ab" to "បដិសេធ",
    "Leichtigkeit" to "ពន្លឺ",
    "Leidenschaft" to "តណ្ហា",
    "Liebe im Gleichgewicht" to "ស្នេហាក្នុងតុល្យភាព",
    "Liebe sie, macht mehr Spaß" to "ស្រលាញ់គេ សប្បាយជាង",
    "Lieber durchgeplant oder spontan?" to "តើ​អ្នក​ចង់​មាន​គម្រោង​ចេញ​ឬ​ដោយ​ឯកឯង​ទេ?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "តើអ្នកចង់មានល្ងាចដ៏ស្ងប់ស្ងាត់សម្រាប់ពីរនាក់ ឬជាមួយមនុស្សទេ?",
    "Lieber nicht" to "មិនប្រសើរជាង",
    "Lieber vorher grob absprechen" to "វាជាការប្រសើរក្នុងការពិភាក្សាអំពីរឿងជាមុន",
    "Lokal einkaufen" to "ទិញទំនិញក្នុងស្រុក",
    "London" to "ទីក្រុងឡុងដ៍",
    "London, England" to "ទីក្រុងឡុង ប្រទេសអង់គ្លេស",
    "Lügen" to "កុហក",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "តើអ្នកចូលចិត្តសំណើសាធារណៈ ឬឯកជនទេ?",
    "Malediven" to "ម៉ាល់ឌីវ",
    "Man sollte nie streitend einschlafen." to "អ្នកមិនគួរដេកលក់ឡើយ",
    "Mango Sorbet" to "Mango Sorbet",
    "Markant & breit" to "វាយលុក និងធំទូលាយ",
    "Marken & Alltag" to "ម៉ាក និងជីវិតប្រចាំថ្ងៃ",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "ទីធ្លាមេឌីទែរ៉ាណេ",
    "Mehr Unterstützung" to "ការគាំទ្របន្ថែមទៀត",
    "Mehr gemeinsame Zeit" to "ពេលវេលាជាមួយគ្នាបន្ថែមទៀត",
    "Mehr zuhören" to "ស្តាប់ច្រើនទៀត",
    "Mehrgenerationenhaus" to "ផ្ទះពហុជំនាន់",
    "Mein Arbeitsplatz" to "កន្លែងធ្វើការរបស់ខ្ញុំ",
    "Mein Partner" to "ដៃគូរបស់ខ្ញុំ",
    "Mich überraschen" to "ធ្វើឱ្យខ្ញុំភ្ញាក់ផ្អើល",
    "Minimalistisches Interieur" to "ផ្ទៃខាងក្នុងតូច",
    "Missverständnisse" to "ការយល់ច្រលំ",
    "Mit Familie und engen Freunden" to "ជាមួយគ្រួសារ និងមិត្តភក្តិជិតស្និទ្ធ",
    "Mit Kompromissen" to "ជាមួយនឹងការសម្របសម្រួល",
    "Mitgefühl" to "មេត្តា",
    "Mittelweg mit besonderen Details" to "ចំណុចកណ្តាលដែលមានព័ត៌មានលម្អិតពិសេស",
    "Modern geometrisch" to "ធរណីមាត្រទំនើប",
    "Moderne Grillstation" to "ស្ថានីយ៍ដុតដ៏ទំនើប",
    "Moderner Name" to "ឈ្មោះទំនើប",
    "Moderner Solitär" to "Solitaire ទំនើប",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "ចាប់យកពេលបច្ចុប្បន្ន",
    "Momente" to "គ្រា",
    "Monaco" to "ម៉ូណាកូ",
    "Moralische Werte" to "តម្លៃសីលធម៌",
    "Museum" to "សារមន្ទីរ",
    "Musik" to "តន្ត្រី",
    "Mut" to "ភាពក្លាហាន",
    "Mädchen" to "ក្មេងស្រី",
    "Möbelhaus" to "ហាងលក់គ្រឿងសង្ហារិម",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "តើអ្នកប្រាកដថាចង់ចាកចេញពីសំណួរមែនទេ? វឌ្ឍនភាពពីមុនរបស់អ្នកនៅតែត្រូវបានរក្សាទុក។",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "តើ​អ្នក​ចង់​ឱ្យ​សត្វ​ចិញ្ចឹម​ត្រូវ​បាន​រួម​បញ្ចូល​ក្នុង​កម្មវិធី​ដែរ​ឬ​ទេ?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "ចង់ឱ្យពេលវេលាត្រូវបានចែករំលែកភ្លាមៗនៅលើប្រព័ន្ធផ្សព្វផ្សាយសង្គមមែនទេ?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "យើងប្រហែលជាត្រូវសន្សំប្រាក់",
    "Müssen es planen" to "ត្រូវរៀបចំផែនការ",
    "Müssen sparen" to "ត្រូវការរក្សាទុក",
    "Nachricht an" to "សារ",
    "Name Partnerin" to "ឈ្មោះដៃគូ",
    "Namen und Startdatum eurer Beziehung." to "ឈ្មោះ និងកាលបរិច្ឆេទចាប់ផ្តើមនៃទំនាក់ទំនងរបស់អ្នក។",
    "Natursteinfassade" to "facade ថ្មធម្មជាតិ",
    "Naturteich" to "ស្រះធម្មជាតិ",
    "Nein, einfach halten" to "ទេ គ្រាន់តែកាន់វា។",
    "Nein, erstmal privat halten" to "ទេ សូមរក្សាវាទុកជាឯកជនឥឡូវនេះ",
    "Nein, lieber vor Ort" to "ទេ ប្រសើរជាងនៅលើគេហទំព័រ",
    "Nein, modern halten" to "ទេ រក្សាវាឱ្យទាន់សម័យ",
    "Nein, nur wir" to "ទេ គ្រាន់តែពួកយើងប៉ុណ្ណោះ។",
    "Nein, zu ablenkend" to "ទេ រំខានពេក",
    "Netflix" to "ក្រុមហ៊ុន Netflix",
    "Neubau mit Smart Home" to "អគារថ្មីជាមួយផ្ទះឆ្លាតវៃ",
    "Neubau mit Technik" to "អគារថ្មីជាមួយបច្ចេកវិទ្យា",
    "Neue Liebe, neue Erfahrungen" to "ស្នេហាថ្មី បទពិសោធន៍ថ្មី។",
    "Neues Hobby" to "ចំណូលចិត្តថ្មី។",
    "Neues Spiel" to "ហ្គេមថ្មី។",
    "Neugier" to "ការចង់ដឹងចង់ឃើញ",
    "New York" to "ញូវយ៉ក",
    "New York, USA" to "ញូវយ៉ក សហរដ្ឋអាមេរិក",
    "Nicht mein Fall" to "មិនមែនជាពែងតែរបស់ខ្ញុំទេ។",
    "Nicht nötig, lieber klassisch bleiben" to "មិនចាំបាច់ទេ វាជាការប្រសើរក្នុងការរក្សាភាពបុរាណ",
    "Nichts — es passt so" to "គ្មានអ្វីទេ - វាសម",
    "Nie wieder Burger" to "មិនធ្លាប់មានប៊ឺហ្គឺ",
    "Nie wieder Pizza" to "កុំភីហ្សាម្តងទៀត",
    "Niemand" to "គ្មាននរណាម្នាក់",
    "Niemand ohne Plan" to "គ្មាននរណាម្នាក់ដោយគ្មានផែនការទេ។",
    "Nike" to "Nike",
    "Nizza" to "ល្អណាស់",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "មិនទាន់មានពេលវេលានៅឡើយ។\nចាប់យកបទពិសោធន៍ដំបូងរបស់អ្នក 💞",
    "Nur bei wichtigen Themen" to "សម្រាប់តែប្រធានបទសំខាន់ៗប៉ុណ្ណោះ។",
    "Nur wir beide" to "គ្រាន់តែពួកយើងពីរនាក់",
    "Nähe & Intimität" to "ភាពស្និទ្ធស្នាល និងភាពស្និទ្ធស្នាល។",
    "Obstgarten" to "សួនផ្កា",
    "Oder" to "ឬ",
    "Offene Küche" to "ផ្ទះបាយបើកចំហ",
    "Offene Wohnküche" to "បើកផ្ទះបាយ/បន្ទប់ទទួលភ្ញៀវ",
    "Ohne Stein" to "ដោយគ្មានថ្ម",
    "Open End" to "បើកបញ្ចប់",
    "Outdoor-Küche" to "ផ្ទះបាយក្រៅ",
    "Outdoor-Sofa" to "សាឡុងខាងក្រៅ",
    "Outdoor-Whirlpool" to "ទឹកកួចក្រៅ",
    "Ovaler Diamant" to "ពេជ្ររាងពងក្រពើ",
    "Paar" to "គូ",
    "Paar-Statistiken" to "ស្ថិតិគូស្នេហ៍",
    "Paris" to "ប៉ារីស",
    "Paris, Frankreich" to "ប៉ារីស ប្រទេសបារាំង",
    "Partner" to "ដៃគូ",
    "Partner-Simulator" to "កម្មវិធីត្រាប់តាមដៃគូ",
    "Partnerin" to "ដៃគូ",
    "Party Edition" to "Party Edition",
    "Party Edition II" to "Party Edition II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "តើសត្វមួយណាសមនឹងជីវិតប្រចាំថ្ងៃរបស់យើងទេ?",
    "Pasta" to "ប៉ាស្តា",
    "Pastell" to "ប៉ាស្តា",
    "Penthouse mit Ausblick" to "Penthouse ដែលមានទេសភាព",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pergola ជាមួយបន្ទប់ទទួលភ្ញៀវ",
    "Pfingstrosen" to "Peonies",
    "Pinguin" to "ភេនឃ្វីន",
    "Pistazie" to "ភីស្តាស៊ីយ៉ូ",
    "Pizza" to "ភីហ្សា",
    "Pizzaofen" to "ឡដុតភីហ្សា",
    "Platin" to "ប្លាទីន",
    "PlayStation" to "PlayStation",
    "Pool" to "អាង",
    "Pop" to "ប៉ុប",
    "Prasselnder Kamin" to "ចើងរកានកមដោ",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "ព្រះនាង ចោរសមុទ្រ និងទេពអប្សរធូលី៖ Disney Quiz",
    "Privater Innenhof" to "ទីធ្លាឯកជន",
    "Profil" to "ប្រវត្តិរូប",
    "Profil bearbeiten" to "កែទម្រង់",
    "Prozentual nach Einkommen" to "ភាគរយផ្អែកលើប្រាក់ចំណូល",
    "Quiz verlassen" to "ចេញសំណួរ",
    "Quiz verlassen?" to "ចាកចេញពីសំណួរ?",
    "Rausgehen in die Natur" to "ចេញទៅធម្មជាតិ",
    "Reden vor ..." to "និយាយទៅកាន់...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "កំណត់កាលបរិច្ឆេទ ឬពេលវេលាទៀងទាត់ជាមួយគ្នា",
    "Reisen" to "ការធ្វើដំណើរ",
    "Reiseziele" to "ទិសដៅទេសចរណ៍",
    "Respektlosigkeit" to "ការមិនគោរព",
    "Restaurant" to "ភោជនីយដ្ឋាន",
    "RnB / Soul" to "RnB / ព្រលឹង",
    "Rock" to "រ៉ុក",
    "Rom" to "ទីក្រុងរ៉ូម",
    "Rom, Italien" to "ទីក្រុងរ៉ូម ប្រទេសអ៊ីតាលី",
    "Romantik" to "មនោសញ្ចេតនា",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "កាយវិការមនោសញ្ចេតនា ដូចជាសារ កំណត់ចំណាំ ឬអំណោយធ្វើឱ្យខ្ញុំសប្បាយចិត្ត។",
    "Romantische Stimmung" to "មនោសញ្ចេតនា",
    "Roségold" to "មាសផ្កាឈូក",
    "Ruhig zu zweit" to "ស្ងាត់សម្រាប់ពីរនាក់",
    "Runder Diamant" to "ពេជ្រមូល",
    "Salted Caramel" to "ការ៉ាមែលអំបិល",
    "Sammle Ideen..." to "ប្រមូលគំនិត...",
    "Santorini" to "សាន់តូរីនី",
    "Santorini, Griechenland" to "Santorini ប្រទេសក្រិក",
    "Saphir" to "ត្បូងកណ្តៀង",
    "Saunahaus" to "ផ្ទះសូណា",
    "Schickes Restaurant oder Hotel" to "ភោជនីយដ្ឋាន ឬសណ្ឋាគារឡូយ",
    "Schlafzimmer" to "បន្ទប់គេង",
    "Schließen" to "បិទ",
    "Schmal & zart" to "ស្ដើង និងឆ្ងាញ់",
    "Schnappschüsse aus unserer Liebesgeschichte" to "កម្រងរូបភាពពីរឿងស្នេហារបស់យើង។",
    "Schokolade" to "សូកូឡា",
    "Schreib frei, was dir wirklich dazu einfällt." to "សរសេរដោយសេរីនូវអ្វីដែលពិតជានឹកឃើញ។",
    "Schreibe deine eigene Antwort" to "សរសេរចម្លើយផ្ទាល់ខ្លួនរបស់អ្នក។",
    "Sehr gerne" to "សូមស្វាគមន៍",
    "Sehr leicht" to "ស្រាលណាស់។",
    "Sehr wichtig — Fotos und Video" to "សំខាន់ណាស់ — រូបថត និងវីដេអូ",
    "Sehr wichtig, es sollte persönlich sein" to "សំខាន់ណាស់ វាគួរតែមានលក្ខណៈផ្ទាល់ខ្លួន",
    "Selbst kochen" to "ចម្អិនដោយខ្លួនឯង។",
    "Senden" to "ផ្ញើ",
    "Separate Küche" to "ផ្ទះបាយដាច់ដោយឡែក",
    "Serie schauen" to "មើលស៊េរី",
    "Serienmarathon auf dem Sofa" to "ស៊េរីម៉ារ៉ាតុងនៅលើសាឡុង",
    "Sex & Liebe" to "ការរួមភេទ និងស្នេហា",
    "Seychellen" to "សីស្ហែល",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "តើយើងអាចរ៉ាប់រងការចំណាយទាំងអស់សម្រាប់កុមារម្នាក់/កូនច្រើនបានទេ? 💰",
    "Soll der Antrag eine Überraschung sein?" to "តើសំណើរគួរភ្ញាក់ផ្អើលទេ?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "តើកម្មវិធីគួរមានធាតុវប្បធម៌ ឬប្រពៃណីទេ?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "តើកម្មវិធីគួរមានធាតុវប្បធម៌ ឬប្រពៃណីទេ?",
    "Sommerhochzeit" to "អាពាហ៍ពិពាហ៍រដូវក្តៅ",
    "Sonnige Dachterrasse" to "ដំបូលមានពន្លឺថ្ងៃ",
    "Sowohl als auch" to "ទាំងពីរ និង",
    "Spazieren" to "ដើរលេង",
    "Spaß & Abenteuer" to "ភាពសប្បាយរីករាយ និងដំណើរផ្សងព្រេង",
    "Speichern" to "រក្សាទុក",
    "Spiel bearbeiten" to "កែសម្រួលហ្គេម",
    "Spielbereich für Kinder" to "កន្លែងលេងសម្រាប់កុមារ",
    "Spiele" to "ហ្គេម",
    "Spiele spielen und Spaß haben" to "លេងហ្គេម និងរីករាយ",
    "Spontan" to "ដោយឯកឯង",
    "Sportplatz" to "វាលកីឡា",
    "Spotify" to "Spotify",
    "Sprache" to "ភាសា",
    "Stadt" to "ទីក្រុង",
    "Stadt oder Land — was ist uns wichtiger?" to "ទីក្រុង ឬប្រទេស - តើអ្វីដែលសំខាន់សម្រាប់យើង?",
    "Stadtvilla" to "វីឡាក្នុងទីក្រុង",
    "Standesamt & Party" to "ការិយាល័យចុះបញ្ជី និងភាគី",
    "Statement-Ring" to "ចិញ្ចៀនសេចក្តីថ្លែងការណ៍",
    "Stilvolles Outdoor-Sofa" to "សាឡុងខាងក្រៅទាន់សម័យ",
    "Stimme voll zu" to "យល់ព្រមទាំងស្រុង",
    "Stimmt" to "ត្រូវហើយ។",
    "Stimmt nicht" to "មិនពិតទេ។",
    "Stimmt, noch nie" to "ពិត មិនដែល",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "ថ្ងៃឆ្នេរ",
    "Streit über Haushalt" to "ជម្លោះគ្រួសារ",
    "Studio Ghibli" to "ស្ទូឌីយោ Ghibli",
    "Ständig" to "ឥតឈប់ឈរ",
    "Suche schließen" to "បិទការស្វែងរក",
    "Suche zurücksetzen" to "កំណត់ការស្វែងរកឡើងវិញ",
    "Suche öffnen" to "បើកការស្វែងរក",
    "Suchergebnisse" to "លទ្ធផលស្វែងរក",
    "Sushi" to "ស៊ូស៊ី",
    "Süß" to "ផ្អែម",
    "Tage zusammen 💞" to "ថ្ងៃជាមួយគ្នា💞",
    "Tauche ins Unterbewusstsein" to "ជ្រមុជចូលទៅក្នុង subconscious",
    "Teile alle deine Hobbys mit deinem Partner" to "ចែករំលែកចំណូលចិត្តរបស់អ្នកជាមួយដៃគូរបស់អ្នក។",
    "Teils teils" to "មួយផ្នែក",
    "Testen" to "តេស្ត",
    "Themen" to "ប្រធានបទ",
    "Tiefe Gespräche" to "ការសន្ទនាដ៏ស៊ីជម្រៅ",
    "Tiefgründige Gespräche führen" to "មានការសន្ទនាយ៉ាងស៊ីជម្រៅ",
    "Tierpension" to "ផ្ទះសំណាក់សត្វ",
    "Tiny House" to "ផ្ទះតូច",
    "Tippen zum Auswählen & Scrollen" to "ប៉ះដើម្បីជ្រើសរើស និងរមូរ",
    "Tippen zum Zuklappen" to "ប៉ះដើម្បីបង្រួម",
    "Titel" to "ចំណងជើង",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "ចំណងជើង, ប្រភេទ, ប្រធានបទ, ស្លាក, សំណួរ...",
    "Tokyo, Japan" to "តូក្យូ ប្រទេសជប៉ុន",
    "Traditioneller Name" to "ឈ្មោះប្រពៃណី",
    "Traumhaus Außenbereich" to "ផ្ទះក្នុងសុបិន តំបន់ក្រៅផ្ទះ",
    "Traumhochzeit" to "អាពាហ៍ពិពាហ៍ក្នុងសុបិន",
    "Treffer" to "បុក",
    "Tägliche Aktivität" to "សកម្មភាពប្រចាំថ្ងៃ",
    "Umformulieren" to "ប្រយោគឡើងវិញ",
    "Unbeantwortet" to "មិនទាន់មានចម្លើយ",
    "Unbeliebte Meinungen" to "មតិដែលមិនពេញនិយម",
    "Universal Studios Genie oder Neuling?" to "Universal Studios genius ឬអ្នកថ្មី?",
    "Uns auseinanderzuleben" to "បែកគ្នា",
    "Unser Intimleben" to "ជីវិតស្និទ្ធស្នាលរបស់យើង។",
    "Unser Traumhaus" to "ផ្ទះក្នុងក្តីស្រមៃរបស់យើង។",
    "Unser erstes Treffen" to "ការប្រជុំដំបូងរបស់យើង។",
    "Unsere Gesichter" to "មុខរបស់យើង។",
    "Unsere eigenen Träume" to "ក្តីស្រមៃរបស់យើង។",
    "Unsere nächste Reise" to "ការធ្វើដំណើរបន្ទាប់របស់យើង។",
    "Unter 1000" to "ក្រោម 1000",
    "Unter 1000 im Monat" to "ក្រោម 1000 ក្នុងមួយខែ",
    "Unter 50€/Monat" to "ក្រោម 50€/ខែ",
    "Unter Leuten" to "ក្នុងចំណោមមនុស្ស",
    "Untreue" to "ភាពមិនស្មោះត្រង់",
    "Urlaub" to "វិស្សមកាល",
    "Vanille" to "វ៉ានីឡា",
    "Venedig" to "ទីក្រុង Venice",
    "Venedig, Italien" to "ទីក្រុង Venice ប្រទេសអ៊ីតាលី",
    "Verbinde dich mit" to "ភ្ជាប់ជាមួយ",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "ភ្ជាប់ទៅ \${profile.partnerName} ដើម្បីមើលចម្លើយ",
    "Verbindung" to "ការតភ្ជាប់",
    "Verbringe die Feiertage mit deiner Familie" to "ចំណាយពេលវិស្សមកាលជាមួយគ្រួសាររបស់អ្នក។",
    "Verlobungsringe" to "ចិញ្ចៀនភ្ជាប់ពាក្យ",
    "Vertrautheit" to "ស្គាល់",
    "Viel getrennt" to "បែកគ្នាច្រើន។",
    "Vielleicht ein oder zwei" to "ប្រហែលមួយ ឬពីរ",
    "Vielleicht, aber mündlich reicht" to "ប្រហែលជា ប៉ុន្តែពាក្យសំដីគឺគ្រប់គ្រាន់ហើយ។",
    "Vielleicht, wenn es machbar ist" to "ប្រហែលជាប្រសិនបើវាអាចទៅរួច",
    "Vielleicht, wenn es passt" to "ប្រហែលជាប្រសិនបើវាសម",
    "Vintage Art déco" to "Vintage Art Deco",
    "Vintage verspielt" to "លេងបែបបុរាណ",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "ត្រូវបានណែនាំដល់ចំណូលចិត្តថ្មីដោយដៃគូរបស់អ្នក។",
    "Vor dem Kauf eines Hauses besprechen" to "ពិភាក្សាមុននឹងទិញផ្ទះ",
    "Vor der Anschaffung eines Haustiers besprechen" to "ពិភាក្សាមុននឹងទិញសត្វចិញ្ចឹម",
    "Vor der gemeinsamen Reise besprechen" to "ពិភាក្សាមុនពេលធ្វើដំណើរជាមួយគ្នា",
    "Vor nichts" to "គ្មានអ្វីទេ។",
    "Vorort" to "ជាយក្រុង",
    "Walnuss" to "វ៉ាល់ណាត់",
    "Wandern" to "ដើរលេង",
    "Wann fühlst du dich mir am nächsten?" to "តើពេលណាដែលអ្នកមានអារម្មណ៍ថានៅជិតខ្ញុំជាងគេ?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "តើពេលណាដែលអ្នកមានអារម្មណ៍ថានៅជិតខ្ញុំជាងគេ?",
    "Was bedeutet Vertrauen für dich konkret?" to "តើការទុកចិត្តមានន័យយ៉ាងណាចំពោះអ្នក?",
    "Was entspannt dich mehr?" to "តើអ្វីធ្វើអោយអ្នកធូរស្បើយជាងនេះ?",
    "Was fehlt dir über die Distanz am meisten?" to "តើអ្នកនឹកអ្វីជាងគេអំពីចម្ងាយ?",
    "Was gefällt dir an deinem Zuhause am besten?" to "តើអ្នកចូលចិត្តអ្វីជាងគេអំពីផ្ទះរបស់អ្នក?",
    "Was hast du von deinem Partner gelernt?" to "តើអ្នកបានរៀនអ្វីខ្លះពីដៃគូរបស់អ្នក?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "តើប្រិយមិត្តយល់យ៉ាងណាដែរចំពោះការទស្សនារឿងមនោសញ្ចេតនាជាមួយគ្នា?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "តើអ្នកគិតយ៉ាងណាចំពោះឧបករណ៍ (ឧ. សញ្ញា ប៉េងប៉ោង ។ល។)?",
    "Was ist das Wichtigste beim Antrag?" to "តើអ្វីដែលសំខាន់បំផុតនៅពេលដាក់ពាក្យ?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "តើអ្វីជារឿងសំខាន់បំផុតដែលអ្នកស្វែងរកនៅក្នុងការជួបផ្លូវភេទ?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "តើរូបថតមួយណាដែលអ្នកចូលចិត្តជាងគេ? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "តើអ្វីជាការភ័យខ្លាចធំបំផុតរបស់អ្នកអំពីការរស់នៅជាមួយគ្នា?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "ម្ហូបអ្វីដែលអ្នកចូលចិត្ត ប៉ុន្តែដៃគូរបស់អ្នកមិនយល់?",
    "Was ist für dich ein absoluter Dealbreaker?" to "តើអ្វីជាភ្នាក់ងារផ្តាច់មុខសម្រាប់អ្នក?",
    "Was ist für jeden von uns das absolute Highlight?" to "តើអ្វីជាចំណុចសំខាន់សម្រាប់យើងម្នាក់ៗ?",
    "Was ist passiert?" to "តើមានអ្វីកើតឡើង?",
    "Was macht einen Moment für dich romantisch?" to "តើ​អ្វី​ដែល​ធ្វើ​ឱ្យ​អ្នក​មាន​មនោសញ្ចេតនា​មួយ​ភ្លែត?",
    "Was magst du an deinem Partner am liebsten?" to "តើអ្នកចូលចិត្តអ្វីជាងគេអំពីដៃគូរបស់អ្នក?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "តើអ្នកចូលចិត្តអ្វីល្អជាង៖ ក្រោកពីព្រលឹម ឬគេងយឺត?",
    "Was magst du lieber?" to "តើអ្នកចូលចិត្តមួយណាល្អជាង?",
    "Was möchtest du eigentlich sagen?" to "តើអ្នកចង់និយាយអ្វី?",
    "Was möchtest du, dass dein Partner öfter tut?" to "តើអ្នកចង់ឱ្យដៃគូរបស់អ្នកធ្វើអ្វីញឹកញាប់ជាងនេះ?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "តើមានអ្វីកើតឡើងចំពោះសត្វនៅពេលយើងធ្វើដំណើរ?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "តើកូនរបស់យើងនឹងទៅជាយ៉ាងណានៅពេលវាធំឡើង?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "អ្វី​ដែល​យើង​មិន​គួរ​មើល​រំលង​ក្នុង​នាម​ជា​ឪពុក​ម្តាយ?",
    "Was war dein schönster Moment mit mir bisher?" to "តើអ្វីជាពេលវេលាដ៏ល្អបំផុតរបស់អ្នកជាមួយខ្ញុំមកទល់ពេលនេះ?",
    "Was wir gegessen haben" to "អ្វីដែលយើងបានញ៉ាំ",
    "Was wollt ihr nie vergessen?" to "អ្វីដែលអ្នកមិនដែលចង់បំភ្លេច?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "តើអ្វីនឹងកាន់តែអាក្រក់សម្រាប់អ្នក៖ មិនដែលភីហ្សាម្តងទៀត ឬមិនដែលប៊ឺហ្គឺទៀតទេ?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "តើអ្នកចង់ធ្វើអ្វីជាងគេនៅថ្ងៃជាមួយគ្នា?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "តើអ្នកនឹងផ្លាស់ប្តូរអ្វីភ្លាមៗ ប្រសិនបើលុយមិនមែនជាបញ្ហា?",
    "Weiter" to "បន្ទាប់",
    "Weiter spielen" to "បន្តលេង",
    "Weiß ich noch nicht" to "ខ្ញុំមិនទាន់ដឹងទេ។",
    "Weiße Rosen" to "ផ្កាកុលាបពណ៌ស",
    "Weißgold" to "មាសស",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "តើគុណភាពអ្វីដែលកូនរបស់យើងគួរទទួលបានពីយើង?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "តើបរិយាកាសបែបណាដែលអ្នកចង់បានសម្រាប់សំណើ?",
    "Welcher Raum sagt am meisten über dich aus?" to "តើបន្ទប់ណានិយាយអំពីអ្នកច្រើនជាងគេ?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "តើយើងមានគម្រោងថវិកាអ្វីខ្លះសម្រាប់អាហារ និងពេទ្យសត្វ?",
    "Welches Lied macht dich an? 🥵" to "តើបទមួយណាធ្វើអោយអ្នកស្តាប់? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "តើរូបថតចែករំលែកមួយណាដែលអ្នកចូលចិត្តជាងគេ?",
    "Wellnessbad" to "ងូតទឹកសុខភាព",
    "Wenn es schwierig ist" to "នៅពេលដែលអ្វីៗពិបាក",
    "Wenn ich müde bin" to "ពេលខ្ញុំហត់",
    "Wenn wir uns lange umarmen" to "ពេលយើងឱបយូរ",
    "Wenn wir zusammen lachen" to "ពេលយើងសើចជាមួយគ្នា",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "តើអ្នកណាសម្រេចចិត្តលឿនជាងនេះដើម្បីបញ្ជាទិញអ្វី?",
    "Wer findet die besten Restaurants?" to "តើអ្នកណារកឃើញភោជនីយដ្ឋានល្អបំផុត?",
    "Wer gibt mehr Herzlichkeit?" to "អ្នកណាផ្តល់ភាពកក់ក្តៅជាង?",
    "Wer hat den besseren Musikgeschmack?" to "តើអ្នកណាមានរសជាតិតន្ត្រីល្អជាង?",
    "Wer hängt mehr an seinen Eltern?" to "តើអ្នកណាដែលនៅជាមួយឪពុកម្តាយច្រើនជាង?",
    "Wer ist besser organisiert?" to "តើអ្នកណារៀបចំបានល្អជាង?",
    "Wer ist der Beste bei der Filmauswahl?" to "តើនរណាជាអ្នកជ្រើសរើសភាពយន្តល្អបំផុត?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "តើនរណាជាអ្នករៀបចំផែនការណាត់ជួបស្នេហាល្អបំផុត?",
    "Wer ist der beste Tänzer?" to "តើអ្នកណាជាអ្នករាំល្អបំផុត?",
    "Wer ist romantischer?" to "អ្នកណារ៉ូមែនទិកជាង?",
    "Wer kocht besser?" to "តើអ្នកណាចម្អិនបានល្អជាង?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "តើនរណាជាអ្នកថែរក្សាជួសជុល និងថែទាំ?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "តើអ្នកណាកត់សម្គាល់បានលឿនជាងពេលអ្នកផ្សេងទៀតមានអារម្មណ៍មិនល្អ?",
    "Wer sucht am Ende wirklich den Film aus?" to "តើអ្នកណាជាអ្នកជ្រើសរើសភាពយន្តនៅទីបញ្ចប់?",
    "Wer vergisst eher einen Jahrestag?" to "តើអ្នកណាទំនងជាភ្លេចខួប?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "តើអ្នកណាទំនងជាភ្លេចឈ្មោះខ្លួនឯងនៅព្រឹកបន្ទាប់?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "តើអ្នកណាទំនងជានឹងស្វែងរកវីដេអូនៅថ្ងៃបន្ទាប់ដែលពួកគេមិនដឹងអ្វីទាំងអស់?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "តើអ្នកណាចង់ចំណាយពេលយប់នៅលើសាឡុងរបស់មនុស្សចម្លែក?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "តើអ្នកណាទំនងជាងងុយគេងនៅឯពិធីជប់លៀង ហើយក្រោកឡើងជាមួយ Sharpie នៅលើមុខរបស់ពួកគេ?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "តើអ្នកណាទំនងជារអិលលើកម្រាលរាំ ប៉ុន្តែមើលទៅហាក់ដូចជាក្បាច់រាំឡូយ?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "តើអ្នកណាទំនងជាគ្រប់គ្រងបញ្ជីចាក់ Spotify ក្នុងពិធីជប់លៀងនៅផ្ទះ?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "តើអ្នកណាទំនងជានឹងបញ្ជាទិញភីហ្សាសម្រាប់អ្នករាល់គ្នានៅឯពិធីជប់លៀង ហើយញ៉ាំវាដោយខ្លួនឯង?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "តើអ្នកណាទំនងជាងងុយគេងមុនគេនៅឯពិធីជប់លៀង?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "តើអ្នកណាទំនងជានឹងចាប់ផ្តើមសម្អាតភ្លាមៗនៅឯពិធីជប់លៀងមួយ?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "តើអ្នកណានឹងទំនងជាអះអាងថាមានសុវត្ថភាពទាំងស្រុងនៅពេលដែលផ្ទុយពីការពិត?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "តើអ្នកណាដែលទំនងជានឹងផ្តល់ឱ្យមុននៅក្នុងអាគុយម៉ង់?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "តើអ្នកណាទំនងជាបោកប្រាស់ក្នុងល្បែងផឹកស៊ី?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "តើអ្នកណាទំនងជាឆ្មក់ចូលអាហារប៊ូហ្វេ ហើយលួចយកអាហារទៅផ្ទះ?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "តើអ្នកណាទំនងជាបង្ហោះរូបថតដ៏អាម៉ាស់បំផុតនៅពេលល្ងាចក្នុងរឿងរបស់ពួកគេ?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "តើអ្នកណាទំនងជារំខាន DJ ដើម្បីស្នើសុំបទចម្រៀងផ្ទាល់ខ្លួន?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "តើអ្នកណាទំនងជាអាចច្រៀងទំនុកច្រៀងទៅជាបទចម្រៀងបិទគន្លឹះ ប៉ុន្តែដោយមានទំនុកចិត្ត?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "តើអ្នកណាទំនងជានឹងបញ្ជាទិញភេសជ្ជៈថ្លៃបំផុតនៅលើម៉ឺនុយ ហើយសោកស្តាយវា?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "តើអ្នកណាទំនងជានឹងអញ្ជើញអ្នកជិតខាងមកមើល ប្រសិនបើពួកគេត្អូញត្អែរអំពីសម្លេងរំខាននោះ?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "តើអ្នកណានឹងយកហ្គេមជប់លៀង (ដូចជាស្រាបៀរប៉ុង) ខ្លាំងពេក?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "អ្នកណាខ្លះទំនងក្លាយជាមិត្តនឹងអ្នកលោតដើម្បីទទួលបានវីអាយភី?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "តើអ្នកណាទំនងជាចាប់ផ្តើមសមរភូមិខារ៉ាអូខេដោយឯកឯង?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "តើអ្នកណាទំនងជាបើកដបដោយមិនប្រើឧបករណ៍បើកដប?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "តើអ្នកណាទំនងជានឹងថ្លែងសុន្ទរកថា បើទោះជាគ្មាននរណាម្នាក់សួរ?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "តើអ្នកណាទំនងជាចំណាយពេលមួយម៉ោងក្នុងបន្ទប់ទឹកថតរូប Selfie?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "តើអ្នកណាទំនងជានឹងសម្តែងរបាំដ៏អាម៉ាស់ ហើយអបអរសាទរវា?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "តើអ្នកណាទំនងជាហៅអតីតដៃគូបន្ទាប់ពីពិធីជប់លៀងបានបញ្ចប់?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "តើអ្នកណាទំនងជាធ្វើបាបភ្ញៀវចម្លែកដោយចៃដន្យ?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "តើអ្នកណាទំនងជាចាកចេញពីបក្សដោយមិននិយាយលា?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "តើអ្នកណាចូលចិត្តលេងជាមួយសត្វចិញ្ចឹមរបស់ម្ចាស់ផ្ទះ ជាជាងនិយាយជាមួយភ្ញៀវ?",
    "Wer würde eher spontan eine Reise buchen?" to "តើអ្នកណាទំនងជាកក់ដំណើរកម្សាន្តដោយឯកឯង?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "តើអ្នកណាទំនងជាមានការសន្ទនាជ្រៅនៅក្នុងផ្ទះបាយរាប់ម៉ោង?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "តើអ្នកណាទំនងជាផឹកភេសជ្ជៈរបស់អ្នកដទៃដោយចៃដន្យ?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "តើអ្នកណាទំនងជាគោះដោយចៃដន្យលើថូថ្លៃ ឬរបស់ដែលផុយស្រួយ?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "តើអ្នកណាទំនងជាព្យាយាមលាយស្រាក្រឡុកដ៏ស្មុគស្មាញដោយខ្លួនឯង ហើយបរាជ័យយ៉ាងវេទនា?",
    "Wer würde eher zu spät kommen?" to "តើអ្នកណាទំនងជាយឺត?",
    "Wer würde eher?" to "តើអ្នកណាចង់?",
    "Wer übernimmt die tägliche Versorgung?" to "តើអ្នកណាជាអ្នកមើលថែទាំប្រចាំថ្ងៃ?",
    "Werde so akzeptiert, wie du bist" to "ត្រូវទទួលយកដូចអ្នកដែរ។",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "តើយើងនឹងមានពេលគ្រប់គ្រាន់សម្រាប់កូន/កូនទេ? ⏳",
    "Whirlpool" to "អាងទឹកក្តៅ",
    "White Chocolate" to "សូកូឡាស",
    "Widgets" to "ធាតុក្រាហ្វិក",
    "Wie fühlst du dich am meisten geliebt?" to "តើអ្នកមានអារម្មណ៍បែបណាដែលស្រលាញ់ជាងគេ?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "តើ​យើង​ដោះស្រាយ​ជាមួយ​ចំណូល​ខុស​គ្នា​ដោយ​របៀប​ណា?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "តើអ្វីជាវិធីល្អបំផុតសម្រាប់ដៃគូរបស់អ្នកក្នុងការផ្តួចផ្តើមការរួមភេទជាមួយអ្នក?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "តើដៃគូររបស់អ្នកអាចក្លាយជាដៃគូរកាន់តែប្រសើរសម្រាប់អ្នកដោយរបៀបណា?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "តើ​អ្នក​ចង់​ប្រារព្ធ​ពិធី​ជាមួយ​អ្នក​ដទៃ​យូរ​ប៉ុណ្ណា​បន្ទាប់​ពី​សំណើ​នេះ?",
    "Wie lange wollen wir dort mindestens bleiben?" to "តើ​យើង​ចង់​ស្នាក់​នៅ​ទី​នោះ​យូរ​ប៉ុណ្ណា?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "តើវាងាយស្រួលប៉ុណ្ណាសម្រាប់អ្នកក្នុងការនិយាយអំពីបំណងប្រាថ្នា?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "តើអ្នកចង់អោយអនាគតរបស់យើងទៅជាយ៉ាងណា?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "តើថ្ងៃអាទិត្យដ៏ល្អឥតខ្ចោះរបស់អ្នកនៅផ្ទះមើលទៅដូចអ្វី?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "តើអ្នកមានអារម្មណ៍យ៉ាងណាចំពោះការនិយាយកខ្វក់អំឡុងពេលរួមភេទ?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "តើយើងអាចផ្តល់ឥណទានពិតប្រាកដបានប៉ុន្មាន?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "តើយើងចង់បែកគ្នាប៉ុន្មានម៉ោង?",
    "Wie viel wollen wir insgesamt ausgeben?" to "តើយើងចង់ចំណាយសរុបប៉ុន្មាន?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "តើយើងនឹងរកពេលវេលាសម្រាប់ទំនាក់ទំនងរបស់យើងដោយរបៀបណា នៅពេលដែលទារកមក?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "តើវាសំខាន់យ៉ាងណាចំពោះអ្នក ដែលពេលវេលាត្រូវបានចាប់យក?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "តើវាមានសារៈសំខាន់យ៉ាងណាចំពោះអ្នក ដែលពាក្យសុំឆ្លុះបញ្ចាំងពីចំណូលចិត្ត ឬចំណាប់អារម្មណ៍របស់អ្នក?",
    "Wie würdest du sie/ihn nennen?" to "តើអ្នកនឹងហៅគាត់ថាម៉េច?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "តើវិធីមួយណាដែលអ្នកពេញចិត្តក្នុងការបង្ហាញការស្រលាញ់នៅខាងក្រៅការរួមភេទ?",
    "Wildblumen" to "ផ្កាព្រៃ",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "តើអ្នកចង់បានស្រី ឬប្រុសទេ? 👶",
    "Wintergarten" to "សួនរដូវរងា",
    "Winterhochzeit" to "អាពាហ៍ពិពាហ៍រដូវរងា",
    "Wir bestellen einfach beides" to "យើងគ្រាន់តែបញ្ជាទិញទាំងពីរ",
    "Wir brauchen ewig" to "វានាំយើងជារៀងរហូត",
    "Wir einigen uns nie" to "យើងមិនដែលយល់ព្រមទេ។",
    "Wir entscheiden es gemeinsam" to "យើងសម្រេចចិត្តរួមគ្នា",
    "Wir treffen uns in der Mitte" to "យើងជួបគ្នានៅកណ្តាល",
    "Wir wechseln uns ab" to "យើងប្តូរវេន",
    "Wird stressig" to "តានតឹង",
    "Wobei lachst du am meisten?" to "តើអ្វីធ្វើឱ្យអ្នកសើចជាងគេ?",
    "Wofür sparen wir gemeinsam?" to "តើយើងសន្សំអ្វីជាមួយគ្នា?",
    "Wohnzimmer" to "បន្ទប់ទទួលភ្ញៀវ",
    "Woran erinnerst du dich am lebhaftesten?" to "តើអ្នកចងចាំអ្វីជាងគេ?",
    "Worauf freust du dich bei uns am meisten?" to "តើអ្នកទន្ទឹងរង់ចាំអ្វីជាងគេជាមួយយើង?",
    "Worte/Komplimente" to "ពាក្យ/សរសើរ",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "តើអ្នកខ្លាចអ្វីជាងគេក្នុងទំនាក់ទំនងរបស់យើង?",
    "Wünsche? z.B. günstig, draußen" to "ប្រាថ្នា? ឧ. ថោក, ខាងក្រៅ",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "តើអ្នកចង់ស្នើសុំវិស្សមកាល (ពាក់ព័ន្ធនឹងការធ្វើដំណើរ) ទេ?",
    "Xbox" to "Xbox",
    "YouTube Music" to "តន្ត្រី YouTube",
    "Zeichne für mich" to "គូរអោយខ្ញុំ",
    "Zeichne mich als Tier — welches wäre ich?" to "គូរខ្ញុំជាសត្វ - តើមួយណាជាខ្ញុំ?",
    "Zeichne unser Gefühl zueinander als Symbol." to "គូរអារម្មណ៍របស់យើងចំពោះគ្នាទៅវិញទៅមកជានិមិត្តសញ្ញា។",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "គូរផ្ទះក្នុងក្តីស្រមៃរបស់យើងក្នុងមួយជួរ។ តើ​អ្វី​ជា​អ្វី​ដែល​ទាក់ទាញ​បំផុត?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "គូរកាលបរិច្ឆេទដំបូងរបស់យើង - តើអ្វីដែលត្រូវមាននៅក្នុងរូបភាព?",
    "Zeichnen" to "គូរ",
    "Zeit füreinander" to "ពេលវេលាសម្រាប់គ្នាទៅវិញទៅមក",
    "Zeit, wenn das Baby schläft" to "ពេលវេលាដែលទារកគេង",
    "Zelten gehen" to "ទៅបោះជំរុំ",
    "Zitrone" to "ក្រូចឆ្មា",
    "Zu Hause, gemütlich und privat" to "នៅផ្ទះ កក់ក្ដៅ និងឯកជន",
    "Zu einem Picknick gehen" to "ទៅញាំុបាយ",
    "Zu einem ausgefallenen Abendessen gehen" to "ទៅញ៉ាំអាហារពេលល្ងាច",
    "Zu zweit reisen" to "ធ្វើដំណើរជាប្តីប្រពន្ធ",
    "Zuhause & Alltag" to "ផ្ទះ និងជីវិតប្រចាំថ្ងៃ",
    "Zuhören" to "ស្តាប់",
    "Zurück" to "ត្រឡប់មកវិញ",
    "Zusammen seit" to "រួមគ្នាតាំងពីពេលនោះមក",
    "Zusammen seit (TT.MM.JJJJ)" to "រួមគ្នាតាំងពី (DD.MM.YYYY)",
    "Zusammenziehen" to "កិច្ចសន្យា",
    "Zustimmen oder Ablehnen" to "យល់ព្រម ឬមិនយល់ស្រប",
    "Zwei Kreise, die sich überschneiden" to "រង្វង់ពីរដែលត្រួតគ្នា។",
    "Zwei Stühle davor" to "កៅអីពីរនៅពីមុខវា។",
    "Zärtlich sein" to "ទន់ភ្លន់",
    "Öfter als ich zugebe" to "ច្រើនជាងខ្ញុំទទួលស្គាល់",
    "Über 100€/Monat" to "លើសពី 100€/ខែ",
    "Über 2000 im Monat" to "ជាង 2000 ក្នុងមួយខែ",
    "Über mich selbst" to "អំពីខ្លួនខ្ញុំ",
    "Übernehmen" to "ដាក់ពាក្យ",
    "Überraschend" to "គួរឱ្យភ្ញាក់ផ្អើល",
    "Überraschung" to "ភ្ញាក់ផ្អើល",
    "Überspringen" to "រំលង",
    "Übertrieben und großartig" to "លើសហើយអស្ចារ្យមែន",
    "✎ Tippe, um zu antworten" to "✎ ប៉ះដើម្បីឆ្លើយតប",
    "✨ GFK-Brücke" to "✨ ស្ពាន GRP",
)

internal fun localizeKhmerDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_KHMER_CONTENT)
