package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_LATVIAN_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 gadi",
    "1000 - 1500 im Monat" to "1000–1500 mēnesī",
    "1000 bis 3000" to "no 1000 līdz 3000",
    "1500 - 2000 im Monat" to "1500–2000 mēnesī",
    "3000 bis 5000" to "no 3000 līdz 5000",
    "5-10 Jahre" to "5-10 gadi",
    "50-100€/Monat" to "50-100 €/mēn",
    "Ab 100€" to "No 100 €",
    "Ab 500€" to "No 500 €",
    "Ab 50€" to "No 50 €",
    "Ab und zu" to "Šad un tad",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Cik daudz mums ir jāiztērē pirms pirkuma veikšanas?",
    "Abbrechen" to "Atcelt",
    "Abenteuer" to "Piedzīvojums",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Darbības",
    "Alle" to "Viss",
    "Alle Pakete" to "Visas paketes",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Pazaudējiet visus savus draugus, izņemot labāko draugu",
    "Alle intimen Momente selbst initiieren" to "Uzsāciet visus intīmos brīžus pats",
    "Alles davon" to "Tas viss",
    "Alles, was noch kommt" to "Viss, kas gaidāms",
    "Alltagsroutine" to "Ikdienas rutīna",
    "Alltägliche Berührungen" to "Ikdienas pieskārieni",
    "Altbau mit Charme" to "Veca ēka ar šarmu",
    "Am Strand" to "Pludmalē",
    "Am liebsten alles zusammen" to "Vēlams viss kopā",
    "Am selben Tag mit Freunden/Familie" to "Viena diena ar draugiem/ģimeni",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdama",
    "Amsterdam, Niederlande" to "Amsterdama, Nīderlande",
    "An das Gefühl" to "Par sajūtu",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "Publiskā vietā, kur ir daudz skatītāju",
    "An einen Geruch" to "No smaržas",
    "An einen Song" to "Dziesmai",
    "An etwas, das ich gesagt habe" to "Kaut ko es teicu",
    "Analyse starten" to "Sāciet analīzi",
    "Analysiere eure Muster..." to "Analizējiet savus modeļus...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Analizējiet savas atbildes un tērzēšanas sarunas saskaņā ar Gotmenu un GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Ananāss uz picas garšo garšīgi.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Atbildiet ar fotoattēlu",
    "Antwortähnlichkeit" to "Atbildes līdzība",
    "App-Sprache auswählen" to "Atlasiet lietotnes valodu",
    "Auf eine Bootsparty gehen" to "Došanās uz laivu ballīti",
    "Aufmerksamkeit" to "Uzmanību!",
    "Aufräumen und Projekte angehen" to "Sakopiet un risiniet projektus",
    "Aufwärmen" to "Iesildieties",
    "Aufwärmen: Einander kennenlernen" to "Iesildīšanās: iepazīšanās",
    "Aus dem Urlaub" to "No atvaļinājuma",
    "Ausgefallener Name" to "Iedomāts nosaukums",
    "Ausschlafen und faulenzen" to "Guliet un slinkojiet",
    "Ausschlafen und nichts tun" to "Guliet un neko nedariet",
    "Aussehen" to "Izskats",
    "Auto" to "Auto",
    "Außenkamin" to "Āra kamīns",
    "BEANTWORTE" to "ATBILDE",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonēzija",
    "Banane" to "Banāns",
    "Beantwortet" to "Atbildēts",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Atbildiet uz jautājumiem vienlaikus — atbildes nebūs redzamas, kamēr jūs abi nebūsiet pabeiguši.",
    "Beantwortete Fragen" to "Atbildēti uz jautājumiem",
    "Bearbeiten" to "Rediģēt",
    "Bei Insider-Witzen" to "Par iekšējiem jokiem",
    "Bei Memes" to "Par mēmiem",
    "Bei einer spontanen Berührung" to "Spontāni pieskaroties",
    "Beide" to "Abi",
    "Beide gleich" to "Abi vienādi",
    "Beide zusammen" to "Abi kopā",
    "Beide, aber wir tun so als ob nicht" to "Abi, bet mēs izliekamies, ka nē",
    "Beides" to "Abi",
    "Beides wäre schlimm" to "Abi būtu slikti",
    "Beim Einschlafen nebeneinander" to "Aizmigt viens otram blakus",
    "Beim Reden" to "Runājot",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Slavenas tūristu vietas vienmēr sagādā vilšanos.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Aprakstiet mūsu seksuālo dzīvi ar emocijzīmi.",
    "Besser kommunizieren" to "Sazinieties labāk",
    "Bessere Lage" to "Labāka atrašanās vieta",
    "Bestellen" to "Pasūtījums",
    "Besuchte Länder" to "Apmeklētās valstis",
    "Besuchte Städte" to "Apmeklētās pilsētas",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Vai dodat priekšroku ekstravagantam priekšlikumam vai kaut kam smalkam?",
    "Beziehung" to "Attiecības",
    "Bibliothek" to "Bibliotēka",
    "Bin manchmal unsicher" to "Es dažreiz jūtos nedrošs",
    "Bist du ein Videospiel-Guru?" to "Vai jūs esat videospēļu guru?",
    "Blumenwiese" to "Ziedu pļava",
    "Bunte Blumenwiese" to "Krāsaina ziedu pļava",
    "Burger" to "Burgeri",
    "Burger King" to "Burger King",
    "Chat" to "Tērzēšana",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Cepumu mīkla",
    "Dachgarten mit Lounge" to "Jumta dārzs ar atpūtas telpu",
    "Dachterrasse" to "Jumta terase",
    "Das Wetter an dem Tag" to "Laikapstākļi tajā dienā",
    "Das erste Selfie" to "Pirmais selfijs",
    "Das meiste weiß ich" to "Es zinu lielāko daļu no tā",
    "Das oder das?" to "Tas vai tas?",
    "Das tägliche Leben" to "Ikdienas dzīve",
    "Dass Zusagen gehalten werden" to "Ka solījumi tiek turēti",
    "Dass alles meinen Stil hat" to "Ka visam ir mans stils",
    "Dass ich alles erzählen kann" to "Ka es varu izstāstīt visu",
    "Dass ich mich nicht sorgen muss" to "Lai man nebūtu jāuztraucas",
    "Dass wir ungestört sind" to "Ka mēs esam netraucēti",
    "Dein Name" to "Jūsu vārds",
    "Deine Antwort..." to "Jūsu atbilde...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Jūsu atbildes ir saglabātas. Tiklīdz partneris pabeigs paketi, abas atbildes būs redzamas kopā.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Jūsu atbildes ir saglabātas. Kad \${profile.partnerName} pabeigs pakotni, abas atbildes būs redzamas kopā.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Padariet savas attiecības piedzīvojumiem bagātas un spontānas",
    "Deine Beziehung stabil und sicher machen" to "Padariet savas attiecības stabilas un drošas",
    "Deine eigene Antwort" to "Jūsu atbilde",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Labāk dalieties savos dziļākajos noslēpumos ar savu partneri",
    "Deinen besten Freund verlieren" to "Labākā drauga zaudēšana",
    "Denke an dich" to "Padomājiet par sevi",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Vienas un tās pašas filmas skatīšanās divas reizes ir laika izšķiešana.",
    "Der Blick nach draußen" to "Skats ārpusē",
    "Der Garten" to "Dārzs",
    "Der Ort" to "Vieta",
    "Der Ring und die Geste" to "Zvans un žests",
    "Der perfekte Heiratsantrag" to "Ideāls laulības priekšlikums",
    "Derjenige sein, der umarmt wird" to "Esi tas, kurš tiek apskauts",
    "Deutsch" to "vācu",
    "Diamant" to "Dimants",
    "Diamanten im Band" to "Dimanti grupā",
    "Die Distanz" to "Attālums",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Pavadiet brīvdienas kopā ar partnera ģimeni",
    "Die Gemütlichkeit und Ruhe" to "Komforts un miers",
    "Die Menschen, die darin wohnen" to "Cilvēki, kas tajā dzīvo",
    "Die Umgebung und Atmosphäre" to "Vide un atmosfēra",
    "Die Worte und Emotionen" to "Vārdi un emocijas",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Lielisks izklaides nieku izaicinājums",
    "Diejenige sein, die umarmt" to "Esi tas, kurš apskauj",
    "Direkt ansprechen" to "Adrese tieši",
    "Diskussion" to "Diskusija",
    "Diskutiere vor dem Kinderkriegen" to "Pārrunājiet pirms bērnu piedzimšanas",
    "Diskutiert eure Antworten" to "Apspriediet savas atbildes",
    "Disney" to "Disnejs",
    "Doch, schon mal" to "Jā, jā",
    "Draußen mit der Natur als Kulisse" to "Ārā ar dabu kā fonu",
    "Drei-Stein-Ring" to "Trīs akmeņu gredzens",
    "Du bist dran" to "Pienākusi jūsu kārta",
    "Du fehlst mir" to "Man tevis pietrūkst",
    "Dubai" to "Dubaija",
    "Dubai, VAE" to "Dubaija, AAE",
    "Dunkles Design" to "Tumšs motīvs",
    "Durch Berührung" to "Ar pieskārienu",
    "Durch Worte" to "Caur vārdiem",
    "Durch Zeit zu zweit" to "Kopā pavadītais laiks",
    "Durch kleine Gesten" to "Ar maziem žestiem",
    "Durchgeplant" to "Labi plānots",
    "ERGEBNISSE" to "REZULTĀTI",
    "Egal, Hauptsache gesund" to "Lai nu kā, galvenais vesels",
    "Ehepaar Leben" to "Dzīve laulībā",
    "Eher knapp" to "Drīzāk tuvu",
    "Eher nicht" to "Ne tik ļoti",
    "Eher schwer" to "Diezgan grūti",
    "Eher schwierig" to "Diezgan grūti",
    "Eher zu" to "Vairāk līdzīgs",
    "Eifersucht ist ein Zeichen von Liebe." to "Greizsirdība ir mīlestības pazīme.",
    "Eigenes Gemüsebeet" to "Savs dārzeņu plāksteris",
    "Ein Abenteuer in einer neuen Stadt" to "Piedzīvojums jaunā pilsētā",
    "Ein Anker" to "Enkurs",
    "Ein Balkon oder Garten" to "Balkons vai dārzs",
    "Ein Filmabend" to "Kinovakars",
    "Ein Harmony-Meilenstein eurer Liebe." to "Jūsu mīlestības harmonijas pavērsiens.",
    "Ein Herz" to "Sirds",
    "Ein Herz an der Tür" to "Sirds pie durvīm",
    "Ein Jahr lang eine Fernbeziehung führen" to "Izveidojiet tālsatiksmes attiecības uz gadu",
    "Ein Kindheitsessen" to "Bērnības maltīte",
    "Ein Live-Musik-Konzert besuchen" to "Apmeklējiet dzīvās mūzikas koncertu",
    "Ein Museum besuchen" to "Apmeklējiet muzeju",
    "Ein Spieleabend" to "Spēļu vakars",
    "Ein Spieleabend mit Freunden" to "Spēļu vakars ar draugiem",
    "Ein Urlaubsfoto" to "Atvaļinājuma fotoattēls",
    "Ein aktives Abenteuer" to "Aktīvs piedzīvojums",
    "Ein entspannender Spa-Tag" to "Relaksējoša spa diena",
    "Ein ganz normaler Alltagstag" to "Pilnīgi parasta ikdiena",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "omulīgs vakars mājā negaisa laikā",
    "Ein gemütliches Date drinnen" to "Mājīgs randiņš iekštelpās",
    "Ein lustiges Bild" to "Smieklīga bilde",
    "Ein paar Handyfotos reichen" to "Pietiek ar dažiem mobilā tālruņa fotoattēliem",
    "Ein paar Stunden" to "Dažas stundas",
    "Ein paar kulturelle Anklänge sind okay" to "Dažas kultūras atsauces ir piemērotas",
    "Ein romantischer Abend" to "Romantisks vakars",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Romantiskas vakariņas sveču gaismā",
    "Ein romantisches Bild" to "Romantisks tēls",
    "Ein romantisches Picknick an einem schönen Ort" to "Romantisks pikniks skaistā vietā",
    "Ein schwerer Moment, den wir geschafft haben" to "Grūts brīdis, kas mums izdevās",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Lielisks randiņš brīvā dabā mēness gaismā",
    "Ein ungewöhnliches Gericht" to "Neparasts ēdiens",
    "Ein zufälliger Schnappschuss" to "Nejaušs momentuzņēmums",
    "Einander kennenlernen" to "Iepazīšanās",
    "Eine Autoreise" to "Ceļojums",
    "Eine Brücke" to "Tilts",
    "Eine Date-Nacht unter den Sternen" to "Randiņu vakars zem zvaigznēm",
    "Eine Million Dollar gewinnen" to "Laimē miljonu dolāru",
    "Eine Million Dollar verdienen" to "Pelniet miljonu dolāru",
    "Eine Nacht in einem Club" to "Nakts klubā",
    "Eine Schokoladenverkostung" to "Šokolādes degustācija",
    "Eine Wanderung mit Panoramablick machen" to "Dodieties pārgājienā ar panorāmas skatu",
    "Eine Weinverkostung" to "Vīna degustācija",
    "Eine gemeinsame Reise" to "Kopīgs ceļojums",
    "Eine gemütliche Nacht zu Hause" to "Mājīga nakts mājās",
    "Eine neue Sprache zu lernen ist einfach." to "Jaunas valodas apguve ir vienkārša.",
    "Einen Film anschauen" to "Skatieties filmu",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Mēnesi vispār nerunājamies savā starpā",
    "Einen Tanzkurs besuchen" to "Apmeklējiet deju nodarbību",
    "Einen Vergnügungspark erkunden" to "Izpētiet atrakciju parku",
    "Einen Wellness-Tag" to "Labsajūtas diena",
    "Einen sehr emotionalen Partner haben" to "Jums ir ļoti emocionāls partneris",
    "Einen sehr logischen Partner haben" to "Ļoti loģisks partneris",
    "Einer zahlt alles" to "Viens cilvēks maksā visu",
    "Einfach mehr Alltag" to "Vienkārši vairāk ikdienas",
    "Einfach nebeneinander sein" to "Esiet viens otram blakus",
    "Einfach und intim" to "Vienkāršs un intīms",
    "Einige Dinge für dich behalten" to "Dažas lietas paturiet pie sevis",
    "Einmal" to "Vienreiz",
    "Eins, das nur wir kennen" to "Tādu, ko zinām tikai mēs",
    "Englisch" to "angļu",
    "Entspannte Hängematte" to "Atvieglināts šūpuļtīkls",
    "Entspannung" to "Atpūta",
    "Erdbeere" to "Zemene",
    "Erfolgreich" to "Veiksmīgi",
    "Ergebnisse" to "Rezultāti",
    "Erst bei sehr großen Summen" to "Tikai ļoti lielām summām",
    "Erst nur enge Freunde/Familie" to "Sākumā tikai tuvākie draugi/ģimene",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Mani kaitina, ja manam partnerim ir pārāk ilgs laiks, lai atbildētu uz ziņojumiem.",
    "Essen & Genuss" to "Ēdiens un baudījums",
    "Essensvorlieben" to "Ēdienu preferences",
    "Etwa eine Woche später, erst mal nur wir" to "Apmēram pēc nedēļas, sākumā tikai mēs",
    "Etwas Neues ausprobieren" to "Izmēģiniet kaut ko jaunu",
    "Etwas ganz anderes" to "Kaut kas pavisam cits",
    "Etwas sehr Scharfes" to "Kaut kas ļoti ass",
    "Etwas, das ich selbst gern erfinde" to "Kaut kas man patīk pašam izdomāt",
    "Etwas, eine kleine Note wäre schön" to "Kaut kas, neliela piezīme būtu jauki",
    "Familie" to "Ģimene",
    "Familie/Freunde" to "Ģimene/draugi",
    "Familienmensch" to "Ģimenes cilvēks",
    "Farbedelstein" to "Krāsains dārgakmens",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "TV reklāmas reizēm ir interesanti skatīties.",
    "Fertig" to "Gatavs",
    "Fertig!" to "Gatavs!",
    "Feste Date-Nights" to "Fiksētas randiņu naktis",
    "Feuerstelle" to "Uguns bedre",
    "Filigran & schlicht" to "Filigrāni un vienkārši",
    "Filme/Serien" to "Filmas/seriāls",
    "Formuliere um..." to "Pārfrāzēt...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Pārfrāzējiet savu melnrakstu nevardarbīgā veidā: novērojums, sajūta, vajadzība, lūgums.",
    "Frage hinzufügen" to "Pievienojiet jautājumu",
    "Fragen & Spiele" to "Jautājumi un spēles",
    "Fragen für jede Gelegenheit" to "Jautājumi katram gadījumam",
    "Freizeitpark" to "Atrakciju parks",
    "Freunde treffen" to "Satiec draugus",
    "Freundschaften mit Ex-Partnern sind okay." to "Draudzības ar bijušajiem ir labi.",
    "Früh aufstehen" to "Celies agri",
    "Fußbodenheizung" to "Apsildāmās grīdas",
    "Führen wir getrennte oder gemeinsame Konten?" to "Vai mums ir atsevišķi vai kopīgi konti?",
    "Für dich empfohlen" to "Ieteicams jums",
    "Für die Zukunft" to "Nākotnei",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Šim meklējumam netika atrasts neviens atbilstošs jautājums vai spēle.",
    "Für immer" to "Uz visiem laikiem",
    "Fürsorglichkeit" to "Rūpes",
    "GFK-Brücke" to "GRP tilts",
    "Galerie" to "Galerija",
    "Gar nicht, der Moment gehört uns" to "Nebūt ne, šis brīdis ir mūsu",
    "Gar nichts tun" to "Nedariet neko",
    "Geduld" to "Pacietību",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Dodieties agri no rīta, lai redzētu saullēktu",
    "Geht so" to "Izskatās šādi",
    "Geister existieren wirklich." to "Spoki patiešām pastāv.",
    "Gelassenheit" to "Rāmums",
    "Gelbgold" to "Dzeltenais zelts",
    "Geld & Finanzen" to "Nauda un finanses",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Ceļojiet pa pasauli kopā, izpētiet jaunas kultūras un virtuves",
    "Gemeinsam ein Lego bauen" to "Kopā uzbūvējiet Lego",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Izmēģiniet jaunu recepti kopā virtuvē",
    "Gemeinsame Konten" to "Koplietojamie konti",
    "Gemeinsame Nächte" to "Naktis kopā",
    "Gemeinsame Tage" to "Dienas kopā",
    "Gemischt" to "Jaukts",
    "Gemüsebeet" to "Dārzeņu plāksteris",
    "Gemütliche Feuerstelle" to "Mājīgs kamīns",
    "Gesprächsanreger" to "Sarunas iesācējs",
    "Getrennte Konten" to "Atsevišķi konti",
    "Getrennte Urlaube tun einer Beziehung gut." to "Atsevišķas brīvdienas nāk par labu attiecībām.",
    "Gewächshaus" to "Siltumnīca",
    "Glasfassade" to "Stikla fasāde",
    "Gleichgültigkeit" to "Vienaldzība",
    "Glücklich und frei" to "Laimīgs un brīvs",
    "Gourmet Eis-Sorten" to "Gardēžu saldējuma šķirnes",
    "Gravur innen" to "Gravējums iekšpusē",
    "Grillplatz" to "Barbekjū zona",
    "Groß & üppig" to "Liels un sulīgs",
    "Große Familie" to "Liela ģimene",
    "Große Feier" to "Lieli svētki",
    "Große Fenster" to "Lieli logi",
    "Große Fensterfront" to "Liela loga priekšpuse",
    "Großer Außenpool" to "Liels āra baseins",
    "Großer Garten" to "Liels dārzs",
    "Großer Stein" to "Liels akmens",
    "Größere Küche" to "Lielāka virtuve",
    "Gutes Essen" to "Labs ēdiens",
    "Habe ich" to "Es to izdarīju",
    "Habe ich noch nie" to "Man nekad nav bijis",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Vai esat atklājis kādas pārsteidzošas atšķirības? Runājiet par to, kāpēc jums labāk patīk noteiktas iespējas!",
    "Haus am See" to "Māja pie ezera",
    "Haus/Wohnung" to "Māja/dzīvoklis",
    "Hazelnut" to "Lazdu rieksts",
    "Heimkino" to "Mājas kinozāle",
    "Herzhaft" to "Sirsnīgs",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Pašlaik šeit nav nekā.\nMainiet filtru vai izvēlieties citu tēmu.",
    "Hilfe im Alltag" to "Palīdzība ikdienā",
    "Himbeere" to "Avene",
    "Hinzufügen" to "Pievienot",
    "Hobbys" to "Hobiji",
    "Hochzeitssträuße" to "Kāzu pušķi",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Cūkkārpas mājas lepnums: kur tu piederi?",
    "Home" to "Sākums",
    "Hot Tub" to "burbuļvanna",
    "Humor" to "Humors",
    "Hund" to "Suns",
    "Hängematte" to "Šūpuļtīkls",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Vai vēlaties saņemt rakstisku vēstuli kā daļu no priekšlikuma?",
    "IKEA" to "IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Man labāk patīk romantiskas pastaigas pa parku, nevis kino.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Es nekad neesmu aizmidzis kinoteātrī.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Man patīk atklāt jaunus hobijus vai aktivitātes kopā ar savu partneri.",
    "Ich finde eine Alternative" to "Es atradīšu alternatīvu",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Man patīk izmēģināt jaunus restorānus kopā ar savu partneri, nevis vienmēr doties uz vienu un to pašu vietu.",
    "Ich habe noch nie" to "Es nekad neesmu",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Es nekad neesmu baidījies no amerikāņu kalniņiem un tik un tā tiku uz tiem.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Es nekad neesmu pircis Fast Pass biļetes, jo biju nepacietīgs.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Es nekad neesmu atcēlis plānu palikt mājās un skatīties TV pārraidi.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Es nekad neesmu gaidījis savu vēstuli no Cūkkārpas.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Es nekad neesmu teicis, ka Slytherin patiesībā nebija tik slikts.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Es nekad neesmu teicis, ka esmu pārāk vecs Disneja filmām (un slepus izbaudīju tās).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Es nekad neesmu apzināti notriecis kādu ar zilu tanku Mario Kartā.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Es nekad neesmu raudājis Disneja filmās.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Es nekad neesmu aizsegusi acis, skatoties šausmu filmu.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Es nekad neesmu aizmirsis saglabāt spēli un zaudējis stundas progresa.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Es nekad neesmu izgājis no telpas apkaunojošas ainas laikā (satraukuma faktors).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Fotografējot amerikāņu kalniņos, es nekad neesmu pozējis smieklīgas.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Es nekad neesmu spēlējis spēles līdz vēlam vakaram un nožēloju, cik noguris biju nākamajā dienā.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Es nekad neesmu meklējis Google filmas beigas, jo nevarēju sagaidīt.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Es nekad neesmu jutusies tā, it kā stāvu filmēšanas laukumā.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Es nekad neesmu izlaidis sava iecienītākā seriāla ievadu.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Es nekad neesmu kopīgojis neviena cita Netflix paroli.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Es nekad neesmu klausījies spēles skaņu celiņu darba vai mācību laikā.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Es nekad neesmu vainojis kontrolieri, kad es zaudēju.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Es nekad neesmu dusmās izmetis tastatūru vai kontrolieri.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Es uz dažām dienām neesmu aizmirsis slapjās drēbes veļas mašīnā.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Es nekad neesmu tērējis reālu naudu par kosmētikas precēm spēlē.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Es nekad neesmu braucis ar automašīnu svešā valstī.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Es nekad dušā neesmu izpildījis Disneja dziesmu.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Es nekad neesmu braucis ar elektromobili.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Es nekad neesmu fotografējis ar parka talismanu.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Es nekad neesmu nosaucis mājdzīvnieku Cūkkārpas varoņa vārdā.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Es nekad neesmu pilējis popkornu kinoteātrī un joprojām to ēdu.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Es nekad savā dzīvē neesmu izmantojis meistara Jodas citātu no Zvaigžņu kariem.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Es nekad neesmu pircis pārāk dārgu suvenīru atrakciju parkā.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Es nekad neesmu ieteicis filmu, kas otrai personai būtu šķitis briesmīga.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Es nekad neesmu skatījies Oskaru tiešraidē nakts vidū.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Es nekad neesmu atcēlis seriālu, jo pēdējā sezona bija tik slikta.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Es nekad neesmu noskatījies visu seriāla sezonu vienā dienā.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Es nekad neesmu uzveicis priekšnieku ar pirmo mēģinājumu un jutos kā dievs.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Es nekad neesmu atradis ļaunāku, kas būtu foršāks par varoni.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Es savās rotaļlietās nekad neesmu atpazinis Rotaļlietu stāsta varoni.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Es nekad neesmu veidojis tādu lomu spēlētāja tēlu kā es.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Es nekad neesmu ēdis churro atrakciju parkā.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Es nekad neesmu skatījies Disneja filmu trīs reizes pēc kārtas.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Man nekad nav bijusi Disneja lipīga melodija veselu nedēļu.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Es nekad neesmu skatījies filmu tikai noteikta aktiera dēļ.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Es nekad neesmu stundām ilgi klausījies filmas skaņu celiņu atkārtojumā.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Es nekad neesmu atklājis filmas spoileri un uzreiz to nožēloju.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Es nekad neesmu atradis draugu, kurš runātu citā dzimtajā valodā.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Man nekad nav bijis neviena drauga, kurš būtu pārcēlies uz dzīvi citā valstī.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Es nekad neesmu veicis Harija Potera filmu maratonu Ziemassvētkos.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Es nekad neesmu noskatījies Marvel filmu līdz galam tikai pēckredīta ainas dēļ.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Es nekad neesmu apzināti kaitinājusi NPC (nespēlētāja tēlu).",
    "Ich habe noch nie einen Nachtzug genommen." to "Es nekad neesmu braucis ar nakts vilcienu.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Es nekad neesmu veicis tiešsaistes testu, lai noskaidrotu savu Cūkkārpas māju.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Es nekad neesmu izdzēsis ziņu sociālajos tīklos, jo tas nesaņēma pietiekami daudz atzīmju Patīk.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Es nekad neesmu nosaucis dienu atrakciju parkā par gada labāko dienu.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Es nekad neesmu apmeklējis atrakciju parku un uzturējos tur no rīta līdz vakaram.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Es nekad neesmu atstājis Transformeru vai Marvel braucienu pilnībā aizrāvies.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Es nekad neesmu dusmās pametis spēli.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Es nekad neesmu lasījis nevienu no Harija Potera lielajiem sējumiem.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Es nekad neesmu murgojis par savu iecienītāko seriāla varoni.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Es nekad neesmu sapņojis spēlēt kvidiču.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Es nekad slepus googlē neesmu meklējis, kā atrisināt cieto līmeni.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Es nekad klusībā nebiju cerējis, ka mans mīlulis varētu runāt kā Disnejā.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Es nekad neesmu noņēmis Sims grupas līderi.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Es nekad neesmu zaudējis orientāciju 3D simulatora braucienā.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Es nekad neesmu spēlējis universitātes sporta komandā.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Es nekad neesmu gaidījis rindā ilgāk par divām stundām uz vienu atrakciju.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Es nekad neesmu samirkusi savas vērtslietas, braucot ar ūdeni.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Es nekad neesmu strīdējies ar draugu par to, kura māja ir labākā.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Es nekad neesmu izlikusies, ka man piemīt maģiskas spējas kā Elzai.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Es nekad neesmu smējies tik smagi, ka palaidu garām svarīgu ainu filmā.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Nekad nebiju izjutis tik daudz adrenalīna, ka uzreiz gribējās braukt vēlreiz.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Es nekad neesmu mēģinājis dziedāt ar tādiem dzīvniekiem kā Sniegbaltīte.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Es nekad neesmu sapņojis par ceļojumu uz Disnejlendu.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Es nekad neesmu sapņojis braukt ar Jurassic Park ūdens braucienu.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Es nekad neesmu skaļi kliedzis, izbiedējot lēcienu spēlē.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Es nekad neesmu raudājis par TV šova finālu.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Es nekad... neesmu atcēlis randiņu, lai paliktu mājās.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Es nekad neesmu... 10 reizes pārfrāzējis ziņojumu.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Es nekad... slepus neesmu skatījies sava partnera mobilajā telefonā.",
    "Ich habe noch nie!" to "Es nekad!",
    "Ich habe!" to "Man ir!",
    "Ich lache viel mit meinem Partner." to "Es daudz smejos kopā ar savu partneri.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Man patīk iepazīt sava partnera vaļaspriekus un intereses.",
    "Ich liebe es" to "Man tas patīk",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Man patīk kopā ar savu partneri skatīties filmas, kuras neviens no mums vēl nav redzējis.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Man patīk dalīties ar savu mīļāko mūziku ar savu partneri.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Man nekad nav bijis jāskrien, lai paspētu uz pārsēšanos.",
    "Ich plane gerne Dates mit meinem Partner." to "Man patīk plānot randiņus ar savu partneri.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Es uzskatu par prioritāti laika pavadīšanu kopā ar savu partneri, pat ja esmu aizņemts.",
    "Ich schreibe meinem Partner jeden Tag." to "Es īsziņu savam partnerim katru dienu.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Man patīk dalīties ar mēmiem un jokiem ar savu partneri.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Man patīk dalīties ar savu partneri visās savas dienas detaļās.",
    "Ich würde es nie tun" to "Es nekad to nedarītu",
    "Ich übe noch" to "Es joprojām trenējos",
    "Ideen generieren" to "Ģenerējiet idejas",
    "Im Haushalt helfen" to "Palīdziet ap māju",
    "In Chat einfügen" to "Pievienot tērzēšanai",
    "In Stille nebeneinander" to "Klusumā viens otram blakus",
    "In den Bergen" to "Kalnos",
    "In eine Bar gehen" to "Dodieties uz bāru",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Došanās uz pludmales bāru skatīties saulrietu",
    "In einem feinen Restaurant essen gehen" to "Ēdiet izsmalcinātā restorānā",
    "In einen Coffeeshop gehen" to "Dodieties uz kafejnīcu",
    "In einer Beziehung sollte man alles voneinander wissen." to "Attiecībās jums vajadzētu zināt vienam par otru visu.",
    "Infinity-Pool" to "Bezgalības baseins",
    "Innenpool" to "Iekštelpu baseins",
    "Intelligenz" to "Intelekts",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Intīmi brīži ir tikai tad, kad partneris tos ierosina",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Uzaicinājuma kods: HRM-8731 · viss ir atbloķēts",
    "Island" to "Islande",
    "Ist okay für mich" to "Ar mani viss ir kārtībā",
    "Ist schon perfekt" to "Tas ir ideāli",
    "Ja, Traditionen einbinden" to "Jā, iekļaujiet tradīcijas",
    "Ja, absolut" to "Jā, pilnīgi noteikti",
    "Ja, etwas zum Lesen und Aufbewahren" to "Jā, ko lasīt un paturēt",
    "Ja, genug" to "Jā, pietiek",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Jā, aizraujošā pilsētā vai apskates objektā",
    "Ja, in- und auswendig" to "Jā, iekšā un ārā",
    "Ja, komplett überraschend" to "Jā, pilnīgi pārsteidzoši",
    "Ja, perfekt" to "Jā, ideāli",
    "Ja, sie gehören zur Familie!" to "Jā, viņi ir ģimene!",
    "Ja, sofort teilen" to "Jā, kopīgot nekavējoties",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Jā, mēs nodrošināsim, lai ģimenes laiks būtu prioritāte.",
    "Jacuzzi" to "Džakuzi",
    "Jahr zusammen 🎉" to "gads kopā 🎉",
    "Jahre zusammen 🎉" to "Kopā pavadītie gadi 🎉",
    "Jeder zahlt 50%" to "Visi maksā 50%",
    "Junge" to "Puika",
    "Kamin" to "Kamīns",
    "Karriere & Erfolg" to "Karjera un panākumi",
    "Kategorien" to "Kategorijas",
    "Katze" to "Kat",
    "Keine Musik" to "Nav mūzikas",
    "Keine Party nötig, privat halten" to "Nav nepieciešama ballīte, saglabājiet to privāti",
    "Keine Privatsphäre" to "Nav privātuma",
    "Keine Treffer gefunden" to "Atbilstība nav atrasta",
    "Keiner" to "Nav",
    "Keiner von uns" to "Neviens no mums",
    "Kennst du die Essensvorlieben deines Partners?" to "Vai jūs zināt sava partnera ēdienu izvēli?",
    "Kino" to "Kino",
    "Kirchlich" to "Baznīcas",
    "Klassisch Solitär" to "Klasisks solitārs",
    "Klassisch gebunden" to "Klasiski iesiets",
    "Klein & zart" to "Mazs un smalks",
    "Kleine Geschenke" to "Mazas dāvanas",
    "Kleine Runde" to "Mazā grupa",
    "Kochen und Freunde einladen" to "Ēdienu gatavošana un draugu uzaicināšana",
    "Kochkurs" to "Ēdienu gatavošanas nodarbība",
    "Kommt auf den Tag an" to "Atkarīgs no dienas",
    "Kommt darauf an" to "Tas ir atkarīgs",
    "Kommt drauf an" to "Tas ir atkarīgs",
    "Kommt mit" to "Nāc man līdzi",
    "Konzert" to "Koncerts",
    "Kräftige Farben" to "Spēcīgas krāsas",
    "Kräuterbeet" to "Garšaugu dobe",
    "Kultur & Sehenswürdigkeiten" to "Kultūra un apskates objekti",
    "Kuscheln" to "Pieglausties",
    "Kuss senden" to "Nosūtiet skūpstu",
    "Körperliche Annäherung" to "Fiziskā pieeja",
    "Körperliche Nähe" to "Fizisks tuvums",
    "Küche" to "Virtuve",
    "Land" to "Valsts",
    "Landhaus" to "Lauku māja",
    "Landhausstil" to "Lauku mājas stils",
    "Lange wach bleiben" to "Palieciet vēlu",
    "Lappland" to "Lapzeme",
    "Lappland, Finnland" to "Lapzeme, Somija",
    "Las Vegas" to "Lasvegasa",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Ļaujiet savam partnerim iedvesmot jūs kļūt par labāko sevi",
    "Lehne ab" to "Noraidījums",
    "Leichtigkeit" to "Vieglums",
    "Leidenschaft" to "Kaislība",
    "Liebe im Gleichgewicht" to "Mīlestība līdzsvarā",
    "Liebe sie, macht mehr Spaß" to "Mīli tos, jautrāk",
    "Lieber durchgeplant oder spontan?" to "Vai vēlaties, lai tas būtu plānots vai spontāni?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Vai jūs labprātāk pavadītu klusu vakaru divatā vai ar cilvēkiem?",
    "Lieber nicht" to "Labāk ne",
    "Lieber vorher grob absprechen" to "Labāk ir pārrunāt lietas aptuveni iepriekš",
    "Lokal einkaufen" to "Iepērcieties uz vietas",
    "London" to "Londona",
    "London, England" to "Londona, Anglija",
    "Lügen" to "Meli",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Vai dodat priekšroku publiskam vai privātam piedāvājumam?",
    "Malediven" to "Maldīvija",
    "Man sollte nie streitend einschlafen." to "Nekad nevajadzētu aizmigt strīdoties.",
    "Mango Sorbet" to "Mango sorbets",
    "Markant & breit" to "Pārsteidzošs un plašs",
    "Marken & Alltag" to "Zīmoli un ikdiena",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "Vidusjūras pagalms",
    "Mehr Unterstützung" to "Vairāk atbalsta",
    "Mehr gemeinsame Zeit" to "Vairāk laika kopā",
    "Mehr zuhören" to "Klausieties vairāk",
    "Mehrgenerationenhaus" to "Vairāku paaudžu māja",
    "Mein Arbeitsplatz" to "Mana darba vieta",
    "Mein Partner" to "Mans partneris",
    "Mich überraschen" to "Pārsteidz mani",
    "Minimalistisches Interieur" to "Minimālistisks interjers",
    "Missverständnisse" to "Pārpratumi",
    "Mit Familie und engen Freunden" to "Ar ģimeni un tuviem draugiem",
    "Mit Kompromissen" to "Ar kompromisiem",
    "Mitgefühl" to "Līdzjūtība",
    "Mittelweg mit besonderen Details" to "Vidusceļš ar īpašām detaļām",
    "Modern geometrisch" to "Modernā ģeometriskā",
    "Moderne Grillstation" to "Moderna grila stacija",
    "Moderner Name" to "Mūsdienu nosaukums",
    "Moderner Solitär" to "Moderns solitārs",
    "Moissanit" to "Moisanīts",
    "Moment festhalten" to "Iemūžiniet mirkli",
    "Momente" to "mirkļi",
    "Monaco" to "Monako",
    "Moralische Werte" to "Morālās vērtības",
    "Museum" to "Muzejs",
    "Musik" to "Mūzika",
    "Mut" to "Drosme",
    "Mädchen" to "Meitenes",
    "Möbelhaus" to "Mēbeļu veikals",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Vai tiešām vēlaties pamest viktorīnu? Jūsu iepriekšējais progress paliek saglabāts.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Vai vēlaties, lai pieteikumā tiktu iekļauti mājdzīvnieki?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Vai vēlaties, lai mirklis tiktu nekavējoties kopīgots sociālajos medijos?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Iespējams, mums vajadzēs ietaupīt",
    "Müssen es planen" to "Tas ir jāplāno",
    "Müssen sparen" to "Jāsaglabā",
    "Nachricht an" to "Ziņojums",
    "Name Partnerin" to "Partnera vārds",
    "Namen und Startdatum eurer Beziehung." to "Jūsu attiecību vārdi un sākuma datums.",
    "Natursteinfassade" to "Dabīgā akmens fasāde",
    "Naturteich" to "Dabīgs dīķis",
    "Nein, einfach halten" to "Nē, turiet to",
    "Nein, erstmal privat halten" to "Nē, pagaidām paturiet to privāti",
    "Nein, lieber vor Ort" to "Nē, labāk uz vietas",
    "Nein, modern halten" to "Nē, saglabājiet to modernu",
    "Nein, nur wir" to "Nē, tikai mēs",
    "Nein, zu ablenkend" to "Nē, pārāk novērš uzmanību",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Jauna ēka ar viedo māju",
    "Neubau mit Technik" to "Jauna ēka ar tehnoloģijām",
    "Neue Liebe, neue Erfahrungen" to "Jauna mīlestība, jauna pieredze",
    "Neues Hobby" to "Jauns hobijs",
    "Neues Spiel" to "Jauna spēle",
    "Neugier" to "Zinātkāre",
    "New York" to "Ņujorka",
    "New York, USA" to "Ņujorka, ASV",
    "Nicht mein Fall" to "Nav mana tējas tase",
    "Nicht nötig, lieber klassisch bleiben" to "Nav nepieciešams, labāk palikt klasikai",
    "Nichts — es passt so" to "Nekas — der",
    "Nie wieder Burger" to "Nekad vairs burgeri",
    "Nie wieder Pizza" to "Nekad vairs picu",
    "Niemand" to "Neviens",
    "Niemand ohne Plan" to "Neviens bez plāna",
    "Nike" to "Nike",
    "Nizza" to "Jauki",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Vēl nav mirkļu.\nIemūžiniet savu pirmo pieredzi 💞",
    "Nur bei wichtigen Themen" to "Tikai svarīgām tēmām",
    "Nur wir beide" to "Mēs esam tikai divi",
    "Nähe & Intimität" to "Tuvums un tuvība",
    "Obstgarten" to "Augļu dārzs",
    "Oder" to "Or",
    "Offene Küche" to "Atvērta virtuve",
    "Offene Wohnküche" to "Atvērta virtuve/dzīvojamā istaba",
    "Ohne Stein" to "Bez akmens",
    "Open End" to "Atvērts beigas",
    "Outdoor-Küche" to "Āra virtuve",
    "Outdoor-Sofa" to "Āra dīvāns",
    "Outdoor-Whirlpool" to "Āra burbuļvanna",
    "Ovaler Diamant" to "Ovāls dimants",
    "Paar" to "Pāris",
    "Paar-Statistiken" to "Pāru statistika",
    "Paris" to "Parīze",
    "Paris, Frankreich" to "Parīze, Francija",
    "Partner" to "Partneris",
    "Partner-Simulator" to "Partneru simulators",
    "Partnerin" to "Partneris",
    "Party Edition" to "Party Edition",
    "Party Edition II" to "Party Edition II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Vai dzīvnieks vispār iederas mūsu ikdienā?",
    "Pasta" to "Makaroni",
    "Pastell" to "Pastelis",
    "Penthouse mit Ausblick" to "Penthouse ar skatu",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Lapene ar atpūtas telpu",
    "Pfingstrosen" to "Peonijas",
    "Pinguin" to "Pingvīns",
    "Pistazie" to "Pistācijas",
    "Pizza" to "Pica",
    "Pizzaofen" to "Picas krāsns",
    "Platin" to "Platīns",
    "PlayStation" to "PlayStation",
    "Pool" to "Baseins",
    "Pop" to "Pop",
    "Prasselnder Kamin" to "Dārd kamīns",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Princeses, pirāti un pasaku putekļi: Disneja viktorīna",
    "Privater Innenhof" to "Privāts pagalms",
    "Profil" to "profils",
    "Profil bearbeiten" to "Rediģēt profilu",
    "Prozentual nach Einkommen" to "Procenti, pamatojoties uz ienākumiem",
    "Quiz verlassen" to "Iziet no viktorīnas",
    "Quiz verlassen?" to "Vai pamest viktorīnu?",
    "Rausgehen in die Natur" to "Dodieties dabā",
    "Reden vor ..." to "Runājot ar...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Ieplānojiet regulārus datumus vai laiku kopā",
    "Reisen" to "Ceļošana",
    "Reiseziele" to "Ceļojumu galamērķi",
    "Respektlosigkeit" to "Necieņa",
    "Restaurant" to "Restorāns",
    "RnB / Soul" to "RnB / Soul",
    "Rock" to "Roks",
    "Rom" to "Roma",
    "Rom, Italien" to "Roma, Itālija",
    "Romantik" to "Romantika",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Mani iepriecina romantiski žesti, piemēram, ziņas, piezīmes vai dāvanas.",
    "Romantische Stimmung" to "Romantiska noskaņa",
    "Roségold" to "Rozā zelts",
    "Ruhig zu zweit" to "Kluss diviem",
    "Runder Diamant" to "Apaļš dimants",
    "Salted Caramel" to "Sālīta karamele",
    "Sammle Ideen..." to "Apkopojiet idejas...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Grieķija",
    "Saphir" to "Safīrs",
    "Saunahaus" to "Pirts māja",
    "Schickes Restaurant oder Hotel" to "Šiks restorāns vai viesnīca",
    "Schlafzimmer" to "Guļamistaba",
    "Schließen" to "Aizvērt",
    "Schmal & zart" to "Plāns un smalks",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Momentuzņēmumi no mūsu mīlas stāsta",
    "Schokolade" to "Šokolāde",
    "Schreib frei, was dir wirklich dazu einfällt." to "Brīvi rakstiet to, kas patiešām ienāk prātā.",
    "Schreibe deine eigene Antwort" to "Uzrakstiet savu atbildi",
    "Sehr gerne" to "Esiet laipni gaidīti",
    "Sehr leicht" to "Ļoti viegls",
    "Sehr wichtig — Fotos und Video" to "Ļoti svarīgi — fotoattēli un video",
    "Sehr wichtig, es sollte persönlich sein" to "Ļoti svarīgi, tam jābūt personiskam",
    "Selbst kochen" to "Gatavojiet pats",
    "Senden" to "Sūtīt",
    "Separate Küche" to "Atsevišķa virtuve",
    "Serie schauen" to "Skatieties seriālu",
    "Serienmarathon auf dem Sofa" to "Sērijas maratons uz dīvāna",
    "Sex & Liebe" to "Sekss un mīlestība",
    "Seychellen" to "Seišelu salas",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Vai varam segt visas izmaksas vienam bērnam/vairākiem bērniem? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Vai priekšlikumam jābūt pārsteigumam?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Vai pieteikumā jāiekļauj kultūras vai tradicionālie elementi?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Vai pieteikumā jāiekļauj kultūras vai tradicionālie elementi?",
    "Sommerhochzeit" to "Vasaras kāzas",
    "Sonnige Dachterrasse" to "Saulaina jumta terase",
    "Sowohl als auch" to "Gan un",
    "Spazieren" to "Pastaigājieties",
    "Spaß & Abenteuer" to "Izklaide un piedzīvojumi",
    "Speichern" to "Saglabāt",
    "Spiel bearbeiten" to "Rediģēt spēli",
    "Spielbereich für Kinder" to "Rotaļu laukums bērniem",
    "Spiele" to "Spēles",
    "Spiele spielen und Spaß haben" to "Spēlējiet spēles un izklaidējieties",
    "Spontan" to "Spontāns",
    "Sportplatz" to "Sporta laukums",
    "Spotify" to "Spotify",
    "Sprache" to "Valoda",
    "Stadt" to "Pilsēta",
    "Stadt oder Land — was ist uns wichtiger?" to "Pilsēta vai valsts — kas mums ir svarīgāks?",
    "Stadtvilla" to "Pilsētas villa",
    "Standesamt & Party" to "Dzimtsarakstu nodaļa un partija",
    "Statement-Ring" to "Paziņojumu gredzens",
    "Stilvolles Outdoor-Sofa" to "Stilīgs āra dīvāns",
    "Stimme voll zu" to "Pilnīgi piekrītu",
    "Stimmt" to "Pareizi",
    "Stimmt nicht" to "Nav taisnība",
    "Stimmt, noch nie" to "Tiesa, nekad",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Pludmales diena",
    "Streit über Haushalt" to "Strīds par mājsaimniecību",
    "Studio Ghibli" to "Studija Ghibli",
    "Ständig" to "Pastāvīgi",
    "Suche schließen" to "Aizvērt meklēšanu",
    "Suche zurücksetzen" to "Atiestatīt meklēšanu",
    "Suche öffnen" to "Atvērt meklēšanu",
    "Suchergebnisse" to "Meklēšanas rezultāti",
    "Sushi" to "Suši",
    "Süß" to "Jauki",
    "Tage zusammen 💞" to "dienas kopā 💞",
    "Tauche ins Unterbewusstsein" to "Ienirstiet zemapziņā",
    "Teile alle deine Hobbys mit deinem Partner" to "Dalieties visos savos hobijos ar savu partneri",
    "Teils teils" to "Daļēji daļēji",
    "Testen" to "Pārbaude",
    "Themen" to "Tēmas",
    "Tiefe Gespräche" to "Dziļas sarunas",
    "Tiefgründige Gespräche führen" to "Padziļinātas sarunas",
    "Tierpension" to "Dzīvnieku pansija",
    "Tiny House" to "Mazā māja",
    "Tippen zum Auswählen & Scrollen" to "Pieskarieties, lai atlasītu un ritinātu",
    "Tippen zum Zuklappen" to "Pieskarieties, lai sakļautu",
    "Titel" to "Nosaukums",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Nosaukums, kategorija, tēma, atzīmes, jautājumi...",
    "Tokyo, Japan" to "Tokija, Japāna",
    "Traditioneller Name" to "Tradicionālais nosaukums",
    "Traumhaus Außenbereich" to "Sapņu mājas āra zona",
    "Traumhochzeit" to "Sapņu kāzas",
    "Treffer" to "Hīts",
    "Tägliche Aktivität" to "Ikdienas aktivitātes",
    "Umformulieren" to "Pārfrāzēt",
    "Unbeantwortet" to "Neatbildēts",
    "Unbeliebte Meinungen" to "Nepopulāri viedokļi",
    "Universal Studios Genie oder Neuling?" to "Universal Studios ģēnijs vai iesācējs?",
    "Uns auseinanderzuleben" to "Izaugt atsevišķi",
    "Unser Intimleben" to "Mūsu intīmā dzīve",
    "Unser Traumhaus" to "Mūsu sapņu māja",
    "Unser erstes Treffen" to "Mūsu pirmā tikšanās",
    "Unsere Gesichter" to "Mūsu sejas",
    "Unsere eigenen Träume" to "Mūsu pašu sapņi",
    "Unsere nächste Reise" to "Mūsu nākamais ceļojums",
    "Unter 1000" to "Zem 1000",
    "Unter 1000 im Monat" to "Zem 1000 mēnesī",
    "Unter 50€/Monat" to "Zem 50 €/mēnesī",
    "Unter Leuten" to "Starp cilvēkiem",
    "Untreue" to "Neticība",
    "Urlaub" to "Atvaļinājums",
    "Vanille" to "Vaniļa",
    "Venedig" to "Venēcija",
    "Venedig, Italien" to "Venēcija, Itālija",
    "Verbinde dich mit" to "Sazinieties ar",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Lai skatītu atbildi, izveidojiet savienojumu ar \${profile.partnerName}",
    "Verbindung" to "savienojums",
    "Verbringe die Feiertage mit deiner Familie" to "Pavadiet brīvdienas kopā ar ģimeni",
    "Verlobungsringe" to "Saderināšanās gredzeni",
    "Vertrautheit" to "Iepazans",
    "Viel getrennt" to "Daudz šķirtības",
    "Vielleicht ein oder zwei" to "Varbūt viens vai divi",
    "Vielleicht, aber mündlich reicht" to "Varbūt, bet verbāli pietiek",
    "Vielleicht, wenn es machbar ist" to "Varbūt, ja tas ir iespējams",
    "Vielleicht, wenn es passt" to "Varbūt, ja der",
    "Vintage Art déco" to "Vintage Art Deco",
    "Vintage verspielt" to "Vintage rotaļīgs",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Jūsu partneris iepazīstina ar jauniem vaļaspriekiem",
    "Vor dem Kauf eines Hauses besprechen" to "Apspriediet pirms mājas iegādes",
    "Vor der Anschaffung eines Haustiers besprechen" to "Apspriediet pirms mājdzīvnieka iegādes",
    "Vor der gemeinsamen Reise besprechen" to "Apspriediet pirms došanās kopā",
    "Vor nichts" to "Nekas",
    "Vorort" to "Priekšpilsēta",
    "Walnuss" to "Valrieksts",
    "Wandern" to "Pārgājieni",
    "Wann fühlst du dich mir am nächsten?" to "Kad tu jūties man vistuvāk?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Kad jūs jūtaties man fiziski vistuvāk?",
    "Was bedeutet Vertrauen für dich konkret?" to "Ko tieši jums nozīmē uzticēšanās?",
    "Was entspannt dich mehr?" to "Kas jūs vairāk atslābina?",
    "Was fehlt dir über die Distanz am meisten?" to "Kas tev visvairāk pietrūkst distancē?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Kas jums visvairāk patīk jūsu mājās?",
    "Was hast du von deinem Partner gelernt?" to "Ko jūs esat iemācījušies no sava partnera?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Ko jūs domājat par erotiska satura skatīšanos kopā?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Ko jūs domājat par rekvizītiem (piem., izkārtnēm, baloniem utt.)?",
    "Was ist das Wichtigste beim Antrag?" to "Kas ir vissvarīgākais, piesakoties?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Kas ir vissvarīgākais, ko meklējat seksuālās saskarsmē?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Kura ir jūsu mīļākā mūsu fotogrāfija? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Kas ir jūsu lielākās bailes no kopdzīves?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Kāds ēdiens jums patīk, bet partneris to nesaprot?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Kas jums ir absolūts darījumu lauzējs?",
    "Was ist für jeden von uns das absolute Highlight?" to "Kas mums katram ir vissvarīgākais?",
    "Was ist passiert?" to "Kas noticis?",
    "Was macht einen Moment für dich romantisch?" to "Kas jums padara mirkli romantisku?",
    "Was magst du an deinem Partner am liebsten?" to "Kas tev visvairāk patīk savā partnerī?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Kas jums patīk labāk: agri celties vai vēlu?",
    "Was magst du lieber?" to "Kurš jums patīk labāk?",
    "Was möchtest du eigentlich sagen?" to "Ko jūs patiesībā vēlaties pateikt?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Ko jūs vēlētos, lai jūsu partneris darītu biežāk?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Kas notiek ar dzīvnieku, kad mēs ceļojam?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Kas notiks ar mūsu bērnu, kad viņš izaugs liels?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Ko mēs kā vecāki nekad nedrīkstam aizmirst no redzesloka?",
    "Was war dein schönster Moment mit mir bisher?" to "Kāds bija jūsu līdz šim labākais brīdis ar mani?",
    "Was wir gegessen haben" to "Ko mēs ēdām",
    "Was wollt ihr nie vergessen?" to "Ko jūs nekad nevēlaties aizmirst?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Kas jums būtu sliktāk: nekad vairs neēst picu vai nekad vairs neēst burgerus?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Ko jūs vēlētos darīt kopā dienā?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Ko jūs nekavējoties mainītu, ja nauda nebūtu problēma?",
    "Weiter" to "Nākamais",
    "Weiter spielen" to "Turpiniet atskaņošanu",
    "Weiß ich noch nicht" to "Es vēl nezinu",
    "Weiße Rosen" to "Baltas rozes",
    "Weißgold" to "Baltais zelts",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Kādu kvalitāti mūsu bērnam noteikti vajadzētu iegūt no mums?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Kādu vidi jūs vēlētos iesniegt priekšlikumam?",
    "Welcher Raum sagt am meisten über dich aus?" to "Kura istaba par tevi stāsta visvairāk?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Kādu budžetu mēs plānojam pārtikai un veterinārārstam?",
    "Welches Lied macht dich an? 🥵" to "Kura dziesma tevi aizrauj? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Kurš kopīgotais fotoattēls ir jūsu mīļākais?",
    "Wellnessbad" to "Labsajūtas vanna",
    "Wenn es schwierig ist" to "Kad ir grūti",
    "Wenn ich müde bin" to "Kad esmu noguris",
    "Wenn wir uns lange umarmen" to "Kad mēs ilgi apskaujamies",
    "Wenn wir zusammen lachen" to "Kad mēs smejamies kopā",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Kurš ātrāk izlemj, ko pasūtīt?",
    "Wer findet die besten Restaurants?" to "Kurš atrod labākos restorānus?",
    "Wer gibt mehr Herzlichkeit?" to "Kurš dod vairāk siltuma?",
    "Wer hat den besseren Musikgeschmack?" to "Kuram ir labāka mūzikas gaume?",
    "Wer hängt mehr an seinen Eltern?" to "Kurš ir vairāk pieķēries saviem vecākiem?",
    "Wer ist besser organisiert?" to "Kurš ir labāk organizēts?",
    "Wer ist der Beste bei der Filmauswahl?" to "Kurš vislabāk izvēlas filmas?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Kurš vislabāk plāno romantiskus randiņus?",
    "Wer ist der beste Tänzer?" to "Kurš ir labākais dejotājs?",
    "Wer ist romantischer?" to "Kurš ir romantiskāks?",
    "Wer kocht besser?" to "Kurš gatavo labāk?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Kas rūpējas par renovāciju un apkopi?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Kurš ātrāk pamana, kad otra persona nejūtas labi?",
    "Wer sucht am Ende wirklich den Film aus?" to "Kurš tad īsti galu galā izvēlas filmu?",
    "Wer vergisst eher einen Jahrestag?" to "Kurš, visticamāk, aizmirsīs jubileju?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Kurš, visticamāk, aizmirsīs savu vārdu nākamajā rītā?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Kuram būtu lielāka iespēja nākamajā dienā atrast videoklipu, par kuru viņš neko nezina?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Kurš gan labprātāk pavadītu nakti uz sveša dīvāna?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Kurš, visticamāk, aizmigs ballītē un pamostos ar Šārpiju uz sejas?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Kurš, visticamāk, paslīdētu uz deju grīdas, bet liktu tam izskatīties kā forša kustība?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Kurš, visticamāk, pārņems kontroli pār Spotify atskaņošanas sarakstu mājas ballītē?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Kurš, visticamāk, pasūtīs picu visiem ballītē un ēdīs pats?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Kurš, visticamāk, ballītē aizmigs pirmais?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Kurš, visticamāk, pēkšņi sāks uzkopt ballītē?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Kurš, visticamāk, apgalvotu, ka ir pilnīgi prātīgs, ja ir pretējais?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Kurš, visticamāk, vispirms piekāpsies strīdā?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Kurš, visticamāk, krāpsies dzeršanas spēlē?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Kurš, visticamāk, iebruks bufetē un slepus nesīs ēdienu mājās?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Kurš, visticamāk, savā stāstā publicēs vakara apkaunojošāko fotoattēlu?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Kurš, visticamāk, kaitinās dīdžeju, lai pieprasītu savu iecienītāko dziesmu?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Kurš, visticamāk, dziedātu dziesmas vārdus ar izslēgtu taustiņu, bet ar pārliecību?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Kurš, visticamāk, pasūtītu ēdienkartē visdārgāko dzērienu un to nožēlotu?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Kurš, visticamāk, aicinās pie sevis kaimiņus, ja viņi sūdzētos par troksni?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Kurš gan viesību spēles (piemēram, Beer Pong) uztvertu pārāk nopietni?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Kurš, visticamāk, sadraudzēsies ar izlēcējiem, lai iegūtu VIP piekļuvi?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Kurš, visticamāk, sāks spontānu karaoke cīņu?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Kurš, visticamāk, atvērs pudeli, neizmantojot pudeļu attaisāmo?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Kurš, visticamāk, teiks runu, lai gan absolūti neviens to nejautā?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Kurš, visticamāk, pavadīs stundu vannas istabā, uzņemot selfijus?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Kurš, visticamāk, sarīkos apkaunojošu deju priekšnesumu un nosvinēs to?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Kurš, visticamāk, piezvanīs bijušajam partnerim pēc ballītes beigām?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Kurš, visticamāk, nejauši aizskartu dīvainu viesi?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Kuram būtu lielāka iespēja slepeni pamest ballīti, neatvadoties?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Kuram gan labāk patiks spēlēties ar saimnieka mājdzīvnieku, nekā runāt ar viesiem?",
    "Wer würde eher spontan eine Reise buchen?" to "Kurš, visticamāk, rezervēs ceļojumu spontāni?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Kuram būtu lielāka iespēja stundām ilgi virtuvē vest dziļas sarunas?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Kurš, visticamāk, nejauši iedzers kāda cita dzērienu?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Kuram ir lielāka iespēja nejauši apgāzt dārgu vāzi vai ko trauslu?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Kuram gan būtu lielāka iespēja, ka mēģinātu pats sajaukt sarežģītu kokteili un tas neizdosies?",
    "Wer würde eher zu spät kommen?" to "Kurš, visticamāk, kavēs?",
    "Wer würde eher?" to "Kuram labāk patiktu?",
    "Wer übernimmt die tägliche Versorgung?" to "Kas rūpējas par ikdienas aprūpi?",
    "Werde so akzeptiert, wie du bist" to "Esi pieņemts tāds, kāds esi",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Vai mums pietiks laika bērnam/bērniem? ⏳",
    "Whirlpool" to "Karstā vanna",
    "White Chocolate" to "Baltā šokolāde",
    "Widgets" to "Logrīki",
    "Wie fühlst du dich am meisten geliebt?" to "Kā jūs jūtaties visvairāk mīlēts?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Kā tiekam galā ar dažādiem ienākumiem?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Kāds ir labākais veids, kā jūsu partneris var uzsākt seksu ar jums?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Kā jūsu partneris var būt vēl labāks partneris jums?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Cik ilgi pēc priekšlikuma vēlaties svinēt kopā ar citiem?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Cik ilgi mēs vēlamies tur palikt vismaz?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Cik viegli jums ir runāt par vēlmēm?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Kā jūs vēlaties, lai izskatās mūsu nākotne?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Kā izskatās tava ideālā svētdiena mājās?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Kā jūs jūtaties par netīrām runām seksa laikā?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Cik lielu kredītu mēs reāli varam atļauties?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Cik daudz laika mēs vēlamies pavadīt šķirti?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Cik mēs kopumā vēlamies tērēt?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Kā mēs atradīsim laiku savām attiecībām, kad piedzims bērniņš?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Cik jums ir svarīgi, lai mirklis tiktu notverts?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Cik jums ir svarīgi, lai pieteikums atspoguļotu jūsu vaļaspriekus vai intereses?",
    "Wie würdest du sie/ihn nennen?" to "Kā jūs viņu nosauktu?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Kāds ir tavs mīļākais veids, kā izrādīt mīlestību ārpus seksa?",
    "Wildblumen" to "Savvaļas ziedi",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Vai vēlaties meiteni vai zēnu? 👶",
    "Wintergarten" to "Ziemas dārzs",
    "Winterhochzeit" to "Ziemas kāzas",
    "Wir bestellen einfach beides" to "Mēs vienkārši pasūtām abus",
    "Wir brauchen ewig" to "Tas mūs aizņem uz visiem laikiem",
    "Wir einigen uns nie" to "Mēs nekad nepiekrītam",
    "Wir entscheiden es gemeinsam" to "Mēs izlemjam kopā",
    "Wir treffen uns in der Mitte" to "Pa vidu tiekamies",
    "Wir wechseln uns ab" to "Mēs ejam pārmaiņus",
    "Wird stressig" to "Kļūst stresains",
    "Wobei lachst du am meisten?" to "Kas tev liek visvairāk smieties?",
    "Wofür sparen wir gemeinsam?" to "Kam mēs kopā taupām?",
    "Wohnzimmer" to "Dzīvojamā istaba",
    "Woran erinnerst du dich am lebhaftesten?" to "Kas jums visspilgtāk palicis atmiņā?",
    "Worauf freust du dich bei uns am meisten?" to "Ko jūs visvairāk gaidāt kopā ar mums?",
    "Worte/Komplimente" to "Vārdi/komplimenti",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "No kā jūs visvairāk baidāties mūsu attiecībās?",
    "Wünsche? z.B. günstig, draußen" to "Vēlas? piem. lēti, ārpusē",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Vai jūs vēlētos piedāvāt atvaļinājumu (ar ceļošanu)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube mūzika",
    "Zeichne für mich" to "Uzzīmējiet man",
    "Zeichne mich als Tier — welches wäre ich?" to "Uzzīmē mani kā dzīvnieku — kurš es būtu?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Uzzīmējiet mūsu jūtas vienam pret otru kā simbolu.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Uzzīmējiet mūsu sapņu māju vienā līnijā. Kas ir visspilgtākais?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Uzzīmē mūsu pirmo randiņu – kam noteikti ir jābūt attēlā?",
    "Zeichnen" to "Izloze",
    "Zeit füreinander" to "Laiks viens otram",
    "Zeit, wenn das Baby schläft" to "Laiks, kad mazulis guļ",
    "Zelten gehen" to "Dodieties kempingā",
    "Zitrone" to "Citrons",
    "Zu Hause, gemütlich und privat" to "Mājās, mājīgi un privāti",
    "Zu einem Picknick gehen" to "Došanās uz pikniku",
    "Zu einem ausgefallenen Abendessen gehen" to "Dodos uz greznām vakariņām",
    "Zu zweit reisen" to "Ceļojiet kā pāris",
    "Zuhause & Alltag" to "Māja un ikdiena",
    "Zuhören" to "Klausieties",
    "Zurück" to "Atpakaļ",
    "Zusammen seit" to "Kopā kopš",
    "Zusammen seit (TT.MM.JJJJ)" to "Kopā kopš (DD.MM.GGGG)",
    "Zusammenziehen" to "Līgums",
    "Zustimmen oder Ablehnen" to "Piekrītu vai nepiekrītu",
    "Zwei Kreise, die sich überschneiden" to "Divi apļi, kas pārklājas",
    "Zwei Stühle davor" to "Priekšā divi krēsli",
    "Zärtlich sein" to "Esiet maigs",
    "Öfter als ich zugebe" to "Vairāk reižu, nekā es atzīstu",
    "Über 100€/Monat" to "Vairāk nekā 100 €/mēnesī",
    "Über 2000 im Monat" to "Vairāk nekā 2000 mēnesī",
    "Über mich selbst" to "Par sevi",
    "Übernehmen" to "Pieteikties",
    "Überraschend" to "Pārsteidzoši",
    "Überraschung" to "Pārsteigums",
    "Überspringen" to "Izlaist",
    "Übertrieben und großartig" to "Lieliski un lieliski",
    "✎ Tippe, um zu antworten" to "✎ Pieskarieties, lai atbildētu",
    "✨ GFK-Brücke" to "✨ GRP tilts",
)

internal fun localizeLatvianDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_LATVIAN_CONTENT)
