package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_LITHUANIAN_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1–5 metai",
    "1000 - 1500 im Monat" to "1000–1500 per mėnesį",
    "1000 bis 3000" to "nuo 1000 iki 3000",
    "1500 - 2000 im Monat" to "1500–2000 per mėnesį",
    "3000 bis 5000" to "nuo 3000 iki 5000",
    "5-10 Jahre" to "5–10 metų",
    "50-100€/Monat" to "50-100 €/mėn",
    "Ab 100€" to "Nuo 100 €",
    "Ab 500€" to "Nuo 500 €",
    "Ab 50€" to "Nuo 50 €",
    "Ab und zu" to "Retkarčiais",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Kiek turime išleisti prieš perkant?",
    "Abbrechen" to "Atšaukti",
    "Abenteuer" to "Nuotykiai",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Veikla",
    "Alle" to "Viskas",
    "Alle Pakete" to "Visi paketai",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Praraskite visus draugus, išskyrus geriausią draugą",
    "Alle intimen Momente selbst initiieren" to "Visas intymias akimirkas inicijuokite patys",
    "Alles davon" to "Visa tai",
    "Alles, was noch kommt" to "Viskas, kas ateis",
    "Alltagsroutine" to "Kasdienybė",
    "Alltägliche Berührungen" to "Kasdieniai prisilietimai",
    "Altbau mit Charme" to "Senas pastatas su žavesiu",
    "Am Strand" to "Paplūdimyje",
    "Am liebsten alles zusammen" to "Pageidautina viskas kartu",
    "Am selben Tag mit Freunden/Familie" to "Ta pati diena su draugais / šeima",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdamas",
    "Amsterdam, Niederlande" to "Amsterdamas, Nyderlandai",
    "An das Gefühl" to "Jausmo",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "Viešoje vietoje, kur yra daug žiūrovų",
    "An einen Geruch" to "Kvapo",
    "An einen Song" to "Į dainą",
    "An etwas, das ich gesagt habe" to "Kažką pasakiau",
    "Analyse starten" to "Pradėkite analizę",
    "Analysiere eure Muster..." to "Analizuokite savo modelius...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Analizuokite savo atsakymus ir pokalbius pagal Gottmaną ir GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Ananasai ant picos skanūs.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Atsakykite su nuotrauka",
    "Antwortähnlichkeit" to "Atsakymo panašumas",
    "App-Sprache auswählen" to "Pasirinkite programos kalbą",
    "Auf eine Bootsparty gehen" to "Ėjimas į valčių vakarėlį",
    "Aufmerksamkeit" to "Dėmesio",
    "Aufräumen und Projekte angehen" to "Išvalykite ir spręskite projektus",
    "Aufwärmen" to "Apšilimas",
    "Aufwärmen: Einander kennenlernen" to "Apšilimas: vienas kito pažinimas",
    "Aus dem Urlaub" to "Iš atostogų",
    "Ausgefallener Name" to "Išgalvotas pavadinimas",
    "Ausschlafen und faulenzen" to "Miegokite ir tinginiaukite",
    "Ausschlafen und nichts tun" to "Miegokite ir nieko nedarykite",
    "Aussehen" to "Išvaizda",
    "Auto" to "Auto",
    "Außenkamin" to "Lauko židinys",
    "BEANTWORTE" to "ATSAKYMAS",
    "Bali" to "Balis",
    "Bali, Indonesien" to "Balis, Indonezija",
    "Banane" to "Bananas",
    "Beantwortet" to "Atsakyta",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Atsakykite į klausimus tuo pačiu metu – atsakymai nebus matomi, kol abu nebaigsite.",
    "Beantwortete Fragen" to "Atsakė į klausimus",
    "Bearbeiten" to "Redaguoti",
    "Bei Insider-Witzen" to "Vidiniams juokeliams",
    "Bei Memes" to "Apie memus",
    "Bei einer spontanen Berührung" to "Spontaniškai palietus",
    "Beide" to "Abu",
    "Beide gleich" to "Abu vienodi",
    "Beide zusammen" to "Abu kartu",
    "Beide, aber wir tun so als ob nicht" to "Abu, bet apsimetame, kad ne",
    "Beides" to "Abu",
    "Beides wäre schlimm" to "Abu būtų blogi",
    "Beim Einschlafen nebeneinander" to "Užmiega vienas šalia kito",
    "Beim Reden" to "Kalbėdamas",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Įžymios turistinės vietos visada nuvilia.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Apibūdinkite mūsų seksualinį gyvenimą naudodami jaustuką.",
    "Besser kommunizieren" to "Geriau bendraukite",
    "Bessere Lage" to "Geresnė vieta",
    "Bestellen" to "Įsakymas",
    "Besuchte Länder" to "Aplankytos šalys",
    "Besuchte Städte" to "Aplankyti miestai",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Ar jums labiau patinka ekstravagantiškas pasiūlymas ar kažkas subtilaus?",
    "Beziehung" to "Santykiai",
    "Bibliothek" to "biblioteka",
    "Bin manchmal unsicher" to "Kartais esu nesaugus",
    "Bist du ein Videospiel-Guru?" to "Ar esate vaizdo žaidimų guru?",
    "Blumenwiese" to "Gėlių pieva",
    "Bunte Blumenwiese" to "Spalvinga gėlių pieva",
    "Burger" to "Mėsainiai",
    "Burger King" to "Burger King",
    "Chat" to "Pokalbis",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Sausainių tešla",
    "Dachgarten mit Lounge" to "Sodas ant stogo su poilsio erdve",
    "Dachterrasse" to "Stogo terasa",
    "Das Wetter an dem Tag" to "Oras tą dieną",
    "Das erste Selfie" to "Pirmoji asmenukė",
    "Das meiste weiß ich" to "Aš žinau daugumą",
    "Das oder das?" to "Tai ar anas?",
    "Das tägliche Leben" to "Kasdienis gyvenimas",
    "Dass Zusagen gehalten werden" to "Kad pažadai yra laikomi",
    "Dass alles meinen Stil hat" to "Kad viskas turi mano stilių",
    "Dass ich alles erzählen kann" to "Kad galiu pasakyti viską",
    "Dass ich mich nicht sorgen muss" to "Kad man nereikėtų jaudintis",
    "Dass wir ungestört sind" to "Kad būtume netrikdomi",
    "Dein Name" to "Jūsų vardas",
    "Deine Antwort..." to "Jūsų atsakymas...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Jūsų atsakymai išsaugoti. Kai tik partneris užbaigs paketą, abu atsakymai bus matomi kartu.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Jūsų atsakymai išsaugoti. Kai \${profile.partnerName} užbaigs paketą, abu atsakymai bus matomi kartu.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Padarykite savo santykius nuotykių kupinus ir spontaniškus",
    "Deine Beziehung stabil und sicher machen" to "Padarykite savo santykius stabilius ir saugius",
    "Deine eigene Antwort" to "Jūsų atsakymas",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Geriau pasidalykite savo giliausiomis paslaptimis su savo partneriu",
    "Deinen besten Freund verlieren" to "Prarasti savo geriausią draugą",
    "Denke an dich" to "Pagalvokite apie save",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Žiūrėti tą patį filmą du kartus yra laiko švaistymas.",
    "Der Blick nach draußen" to "Vaizdas lauke",
    "Der Garten" to "Sodas",
    "Der Ort" to "Vieta",
    "Der Ring und die Geste" to "Skambutis ir gestas",
    "Der perfekte Heiratsantrag" to "Tobulas vedybų pasiūlymas",
    "Derjenige sein, der umarmt wird" to "Būkite tas, kuris yra apkabintas",
    "Deutsch" to "Vokiečių kalba",
    "Diamant" to "Deimantas",
    "Diamanten im Band" to "Deimantai juostoje",
    "Die Distanz" to "Atstumas",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Praleiskite atostogas su savo partnerio šeima",
    "Die Gemütlichkeit und Ruhe" to "Jaukumas ir ramybė",
    "Die Menschen, die darin wohnen" to "Jame gyvenantys žmonės",
    "Die Umgebung und Atmosphäre" to "Aplinka ir atmosfera",
    "Die Worte und Emotionen" to "Žodžiai ir emocijos",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Didžiausias pramogų smulkmenų iššūkis",
    "Diejenige sein, die umarmt" to "Būk tas, kuris apkabina",
    "Direkt ansprechen" to "Adresas tiesiogiai",
    "Diskussion" to "Diskusija",
    "Diskutiere vor dem Kinderkriegen" to "Aptarkite prieš susilaukdami vaikų",
    "Diskutiert eure Antworten" to "Aptarkite savo atsakymus",
    "Disney" to "„Disney“.",
    "Doch, schon mal" to "Taip, taip",
    "Draußen mit der Natur als Kulisse" to "Lauke su gamta kaip fonas",
    "Drei-Stein-Ring" to "Trijų akmenų žiedas",
    "Du bist dran" to "Jūsų eilė",
    "Du fehlst mir" to "Pasiilgau tavęs",
    "Dubai" to "Dubajus",
    "Dubai, VAE" to "Dubajus, JAE",
    "Dunkles Design" to "Tamsi tema",
    "Durch Berührung" to "Liečiant",
    "Durch Worte" to "Per žodžius",
    "Durch Zeit zu zweit" to "Per laiką kartu",
    "Durch kleine Gesten" to "Mažais gestais",
    "Durchgeplant" to "Gerai suplanuota",
    "ERGEBNISSE" to "REZULTATAI",
    "Egal, Hauptsache gesund" to "Kad ir kaip būtų, svarbiausia sveika",
    "Ehepaar Leben" to "Santuokos poros gyvenimas",
    "Eher knapp" to "Gan arti",
    "Eher nicht" to "Ne tiek daug",
    "Eher schwer" to "Gana sunku",
    "Eher schwierig" to "Gana sunku",
    "Eher zu" to "Labiau panašus",
    "Eifersucht ist ein Zeichen von Liebe." to "Pavydas yra meilės ženklas.",
    "Eigenes Gemüsebeet" to "Nuosavas daržovių lopinėlis",
    "Ein Abenteuer in einer neuen Stadt" to "Nuotykis naujame mieste",
    "Ein Anker" to "Inkaras",
    "Ein Balkon oder Garten" to "Balkonas arba sodas",
    "Ein Filmabend" to "Kino vakaras",
    "Ein Harmony-Meilenstein eurer Liebe." to "Jūsų meilės harmonijos etapas.",
    "Ein Herz" to "Širdis",
    "Ein Herz an der Tür" to "Širdis prie durų",
    "Ein Jahr lang eine Fernbeziehung führen" to "Palaikykite ilgalaikius santykius metus",
    "Ein Kindheitsessen" to "Vaikystės valgis",
    "Ein Live-Musik-Konzert besuchen" to "Dalyvaukite gyvos muzikos koncerte",
    "Ein Museum besuchen" to "Apsilankykite muziejuje",
    "Ein Spieleabend" to "Žaidimų vakaras",
    "Ein Spieleabend mit Freunden" to "Žaidimų vakaras su draugais",
    "Ein Urlaubsfoto" to "Atostogų nuotrauka",
    "Ein aktives Abenteuer" to "Aktyvus nuotykis",
    "Ein entspannender Spa-Tag" to "Atpalaiduojanti SPA diena",
    "Ein ganz normaler Alltagstag" to "Visiškai įprasta kasdienė diena",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Jaukus vakaras namuose per perkūniją",
    "Ein gemütliches Date drinnen" to "Jaukus pasimatymas patalpose",
    "Ein lustiges Bild" to "Juokingas vaizdas",
    "Ein paar Handyfotos reichen" to "Pakanka kelių mobiliojo telefono nuotraukų",
    "Ein paar Stunden" to "Kelios valandos",
    "Ein paar kulturelle Anklänge sind okay" to "Kelios kultūros nuorodos yra tinkamos",
    "Ein romantischer Abend" to "Romantiškas vakaras",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Romantiška vakarienė žvakių šviesoje",
    "Ein romantisches Bild" to "Romantiškas vaizdas",
    "Ein romantisches Picknick an einem schönen Ort" to "Romantiškas piknikas gražioje vietoje",
    "Ein schwerer Moment, den wir geschafft haben" to "Sunkus momentas, kurį įveikėme",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Puikus pasimatymas lauke po mėnulio šviesa",
    "Ein ungewöhnliches Gericht" to "Neįprastas patiekalas",
    "Ein zufälliger Schnappschuss" to "Atsitiktinė momentinė nuotrauka",
    "Einander kennenlernen" to "Susipažinimas",
    "Eine Autoreise" to "Kelionė",
    "Eine Brücke" to "Tiltas",
    "Eine Date-Nacht unter den Sternen" to "Pasimatymo naktis po žvaigždėmis",
    "Eine Million Dollar gewinnen" to "Laimėk milijoną dolerių",
    "Eine Million Dollar verdienen" to "Uždirbkite milijoną dolerių",
    "Eine Nacht in einem Club" to "Naktis klube",
    "Eine Schokoladenverkostung" to "Šokolado degustacija",
    "Eine Wanderung mit Panoramablick machen" to "Leiskitės į žygį su panoraminiais vaizdais",
    "Eine Weinverkostung" to "Vyno degustacija",
    "Eine gemeinsame Reise" to "Kelionė kartu",
    "Eine gemütliche Nacht zu Hause" to "Jauki naktis namuose",
    "Eine neue Sprache zu lernen ist einfach." to "Išmokti naują kalbą lengva.",
    "Einen Film anschauen" to "Žiūrėkite filmą",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Mėnesį visiškai nesusikalbame",
    "Einen Tanzkurs besuchen" to "Eikite į šokių pamoką",
    "Einen Vergnügungspark erkunden" to "Naršykite pramogų parką",
    "Einen Wellness-Tag" to "Sveikatingumo diena",
    "Einen sehr emotionalen Partner haben" to "Turėti labai emocingą partnerį",
    "Einen sehr logischen Partner haben" to "Turėti labai logišką partnerį",
    "Einer zahlt alles" to "Vienas žmogus moka viską",
    "Einfach mehr Alltag" to "Tiesiog daugiau kasdienybės",
    "Einfach nebeneinander sein" to "Tiesiog būkite šalia vienas kito",
    "Einfach und intim" to "Paprasta ir intymi",
    "Einige Dinge für dich behalten" to "Kai kuriuos dalykus pasilikite sau",
    "Einmal" to "Kartą",
    "Eins, das nur wir kennen" to "Tik mes žinome",
    "Englisch" to "anglų k",
    "Entspannte Hängematte" to "Atsipalaidavęs hamakas",
    "Entspannung" to "Atsipalaidavimas",
    "Erdbeere" to "Braškė",
    "Erfolgreich" to "Sėkmingai",
    "Ergebnisse" to "Rezultatai",
    "Erst bei sehr großen Summen" to "Tik labai didelėms sumoms",
    "Erst nur enge Freunde/Familie" to "Iš pradžių tik artimi draugai/šeima",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Mane erzina, kai mano partneris per ilgai atsako į žinutes.",
    "Essen & Genuss" to "Maistas ir malonumas",
    "Essensvorlieben" to "Maisto pasirinkimai",
    "Etwa eine Woche später, erst mal nur wir" to "Maždaug po savaitės, iš pradžių tik mes",
    "Etwas Neues ausprobieren" to "Išbandykite ką nors naujo",
    "Etwas ganz anderes" to "Visai kas kita",
    "Etwas sehr Scharfes" to "Kažkas labai aštraus",
    "Etwas, das ich selbst gern erfinde" to "Kažką man patinka sugalvoti pačiam",
    "Etwas, eine kleine Note wäre schön" to "Kažkas būtų gerai",
    "Familie" to "Šeima",
    "Familie/Freunde" to "Šeima / draugai",
    "Familienmensch" to "Šeimos žmogus",
    "Farbedelstein" to "Spalvotas brangakmenis",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "TV reklamas kartais įdomu žiūrėti.",
    "Fertig" to "Atlikta",
    "Fertig!" to "Atlikta!",
    "Feste Date-Nights" to "Fiksuotos datos naktys",
    "Feuerstelle" to "Gaisro duobė",
    "Filigran & schlicht" to "Filigranas ir paprastas",
    "Filme/Serien" to "Filmai / serialai",
    "Formuliere um..." to "Perfrazuoti...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Perfrazuokite juodraštį neprievartingai: pastebėjimas, jausmas, poreikis, prašymas.",
    "Frage hinzufügen" to "Pridėti klausimą",
    "Fragen & Spiele" to "Klausimai ir žaidimai",
    "Fragen für jede Gelegenheit" to "Klausimai kiekvienai progai",
    "Freizeitpark" to "Pramogų parkas",
    "Freunde treffen" to "Susitikite su draugais",
    "Freundschaften mit Ex-Partnern sind okay." to "Draugystė su buvusiaisiais yra gerai.",
    "Früh aufstehen" to "Kelkitės anksti",
    "Fußbodenheizung" to "Grindinis šildymas",
    "Führen wir getrennte oder gemeinsame Konten?" to "Ar turime atskiras ar bendras sąskaitas?",
    "Für dich empfohlen" to "Rekomenduojama jums",
    "Für die Zukunft" to "Ateičiai",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Šiai paieškai nerasta jokių atitinkančių klausimų ar žaidimų.",
    "Für immer" to "Amžinai",
    "Fürsorglichkeit" to "Rūpestingumas",
    "GFK-Brücke" to "GRP tiltas",
    "Galerie" to "Galerija",
    "Gar nicht, der Moment gehört uns" to "Visai ne, momentas yra mūsų",
    "Gar nichts tun" to "Nieko nedaryti",
    "Geduld" to "Kantrybės",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Eikite anksti ryte pažiūrėti saulėtekio",
    "Geht so" to "Taip",
    "Geister existieren wirklich." to "Vaiduokliai tikrai egzistuoja.",
    "Gelassenheit" to "Ramybė",
    "Gelbgold" to "Geltonas auksas",
    "Geld & Finanzen" to "Pinigai ir finansai",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Keliaukite po pasaulį kartu, tyrinėkite naujas kultūras ir virtuves",
    "Gemeinsam ein Lego bauen" to "Sukurkite Lego kartu",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Išbandykite naują receptą kartu virtuvėje",
    "Gemeinsame Konten" to "Bendrinamos paskyros",
    "Gemeinsame Nächte" to "Naktys kartu",
    "Gemeinsame Tage" to "Dienos kartu",
    "Gemischt" to "Mišrus",
    "Gemüsebeet" to "Daržovių pleistras",
    "Gemütliche Feuerstelle" to "Jaukus židinys",
    "Gesprächsanreger" to "Pokalbio pradžia",
    "Getrennte Konten" to "Atskiros paskyros",
    "Getrennte Urlaube tun einer Beziehung gut." to "Santykiams palankios atskiros atostogos.",
    "Gewächshaus" to "Šiltnamis",
    "Glasfassade" to "Stiklinis fasadas",
    "Gleichgültigkeit" to "Abejingumas",
    "Glücklich und frei" to "Laimingas ir laisvas",
    "Gourmet Eis-Sorten" to "Gurmaniškų ledų rūšys",
    "Gravur innen" to "Graviravimas viduje",
    "Grillplatz" to "Grilis",
    "Groß & üppig" to "Didelis ir sodrus",
    "Große Familie" to "Didelė šeima",
    "Große Feier" to "Didelė šventė",
    "Große Fenster" to "Dideli langai",
    "Große Fensterfront" to "Didelis priekinis langas",
    "Großer Außenpool" to "Didelis lauko baseinas",
    "Großer Garten" to "Didelis sodas",
    "Großer Stein" to "Didelis akmuo",
    "Größere Küche" to "Didesnė virtuvė",
    "Gutes Essen" to "Geras maistas",
    "Habe ich" to "Aš padariau",
    "Habe ich noch nie" to "Niekada neturėjau",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Ar atradote kokių nors stebinančių skirtumų? Pakalbėkite apie tai, kodėl jums labiau patinka tam tikri variantai!",
    "Haus am See" to "Namas prie ežero",
    "Haus/Wohnung" to "Namas/butas",
    "Hazelnut" to "Lazdyno riešutas",
    "Heimkino" to "Namų kinas",
    "Herzhaft" to "Nuoširdus",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Šiuo metu čia nieko nėra.\nPakeiskite filtrą arba pasirinkite kitą temą.",
    "Hilfe im Alltag" to "Pagalba kasdieniame gyvenime",
    "Himbeere" to "Avietė",
    "Hinzufügen" to "Pridėti",
    "Hobbys" to "Pomėgiai",
    "Hochzeitssträuße" to "Vestuvinės puokštės",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Hogvartso namų pasididžiavimas: kur tu priklausai?",
    "Home" to "Pagrindinis puslapis",
    "Hot Tub" to "Sūkurinė vonia",
    "Humor" to "Humoras",
    "Hund" to "Šuo",
    "Hängematte" to "Hamakas",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Ar norėtumėte gauti raštišką laišką kaip pasiūlymo dalį?",
    "IKEA" to "IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Man labiau patinka romantiški pasivaikščiojimai parke, o ne ėjimas į kiną.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Niekada nebuvau užmigęs kine.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Mėgstu atrasti naujus pomėgius ar veiklą su savo partneriu.",
    "Ich finde eine Alternative" to "Aš surasiu alternatyvą",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Man patinka išbandyti naujus restoranus su savo partneriu, o ne visada lankytis tose pačiose vietose.",
    "Ich habe noch nie" to "Aš niekada",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Niekada nebijojau amerikietiškų kalnelių ir vis tiek patekau į juos.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Niekada nepirkau Fast Pass bilietų, nes buvau nekantrus.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Niekada neatšaukiau planų likti namuose ir žiūrėti televizijos laidą.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Niekada nelaukiau savo laiško iš Hogvartso.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Niekada nesakiau, kad Slytherin iš tikrųjų nebuvo toks blogas.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Niekada nesakiau, kad esu per sena „Disney“ filmams (ir slapta jais mėgavausi).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Niekada nesu tyčia ko nors numušęs mėlynu tanku Mario Karte.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Niekada neverkiau „Disney“ filme.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Niekada neuždengiau akių žiūrėdama siaubo filmą.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Niekada nepamiršau išsaugoti žaidimo ir praradau kelias valandas.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Niekada neišėjau iš kambario per gėdingą sceną (suspaudimo faktorius).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Niekada nedariau juokingos pozos fotografuodamas kalnelius.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Niekada nežaidžiau iki vėlumos ir gailėjausi, kad kitą dieną buvau pavargęs.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Niekada „Google“ neieškojau filmo pabaigos, nes negalėjau sulaukti.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Niekada nesijaučiau lyg stovėčiau filmavimo aikštelėje.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Niekada nepraleidau savo mėgstamo serialo įvado.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Niekada nesidalinau kieno nors kito „Netflix“ slaptažodžiu.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Niekada neklausiau žaidimo garso takelio dirbdamas ar mokydamasis.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Niekada nekaltinau valdiklio, kai pamečiau.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Aš niekada neišmečiau klaviatūros ar valdiklio supykęs.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Aš keletą dienų nepamiršau šlapių drabužių skalbimo mašinoje.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Niekada neišleidau tikrų pinigų kosmetikos gaminiams žaidime.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Niekada nesu vairavęs automobilio svečioje šalyje.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Niekada negirdėjau Disnėjaus dainos duše.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Niekada nevairavau elektromobilio.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Niekada nesifotografavau su parko talismanu.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Niekada nepavadinau augintinio Hogvartso veikėjo vardu.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Niekada nemesiau spragėsių į kino salę ir vis tiek valgiau.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Niekada kasdieniame gyvenime nenaudojau meistro Yodos citatos iš „Žvaigždžių karų“.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Niekada nepirkau per brangaus suvenyro pramogų parke.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Niekada nedaviau filmo rekomendacijos, kuri kitam žmogui atrodė siaubinga.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Niekada nežiūrėjau „Oskarų“ ceremonijos tiesiogiai vidury nakties.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Niekada neatšaukiau serialo, nes praėjęs sezonas buvo toks blogas.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Niekada neperžiūrėjau viso serialo sezono per vieną dieną.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Niekada nenugalėjau viršininko pirmu bandymu ir jaučiausi kaip dievas.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Niekada neradau blogesnio už herojų.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Savo žaisluose niekada neatpažinau „Toy Story“ personažo.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Aš niekada nesukūriau tokio RPG veikėjo, kaip aš.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Niekada nevalgiau churro teminiame parke.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Aš niekada nežiūrėjau Disnėjaus filmo tris kartus iš eilės.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Visą savaitę negirdėjau patrauklios Disney melodijos.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Niekada nežiūrėjau filmo tik dėl tam tikro aktoriaus.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Niekada neklausiau filmo garso takelio kartojant valandų valandas.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Niekada neatskleidžiau filmo spoilerio ir iškart dėl ​​to gailėjausi.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Niekada neradau draugo, kuris kalba kita gimtąja kalba.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Niekada neturėjau draugo, kuris būtų persikėlęs į kitą šalį.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Niekada per Kalėdas nesu dalyvavęs Hario Poterio filmų maratone.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Niekada nežiūrėjau „Marvel“ filmo iki galo tik dėl scenos po kreditų.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Niekada tyčia neerzinau NPC (ne žaidėjo veikėjo).",
    "Ich habe noch nie einen Nachtzug genommen." to "Niekada nevažiavau naktiniu traukiniu.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Niekada nedariau internetinio testo, kad išsiaiškinčiau savo namą Hogvartse.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Niekada neištryniau socialinių tinklų įrašo, nes jis nesulaukė pakankamai teigiamų įvertinimų.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Nė vienos dienos pramogų parke nepavadinau geriausia metų diena.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Niekada nesilankiau pramogų parke ir būdavau jame nuo ryto iki vakaro.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Niekada neišėjau iš „Transformerių“ ar „Marvel“ važiavimo visiškai susižavėjęs.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Niekada nesipykau ir mesti žaidimą.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Niekada neskaičiau jokių didelių Hario Poterio tomų.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Niekada nepykau apie savo mėgstamą serialo personažą.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Niekada nesvajojau žaisti kvidičo.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Niekada slapta neieškojau „Google“, kaip išspręsti sudėtingą lygį.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Niekada slapta nesitikėjau, kad mano augintinis galės kalbėti kaip „Disney“.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Niekada nepašalinau „Sims“ grupės lyderio.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "3D simuliatoriuje niekada nepasimetiau.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Niekada nežaidžiau universiteto sporto komandoje.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Niekada nelaukiau eilėje ilgiau nei dvi valandas prie vienos atrakcijos.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Aš niekada nesušlapau savo vertingų daiktų važiuodamas vandeniu.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Niekada nesiginčijau su draugu, kuris namas yra geriausias.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Niekada neapsimečiau, kad turiu tokių magiškų galių kaip Elsa.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Niekada taip nesijuokiau, kad praleisčiau svarbią filmo sceną.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Niekada nejaučiau tiek adrenalino, kad iškart norėjau važiuoti dar kartą.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Niekada nebandžiau dainuoti su tokiais gyvūnais kaip Snieguolė.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Niekada nesvajojau apie kelionę į Disneilendą.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Niekada nesvajojau pasivažinėti Juros periodo parko vandens atrakcionu.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Niekada nesu garsiai rėkęs išgąsdindamas šuolį žaidime.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Niekada neverkiau dėl televizijos laidos finalo.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Aš niekada... neatšaukiau pasimatymo, kad likčiau namuose.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Niekada... 10 kartų neperfrazavau žinutės.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Niekada... slapta nežiūrėjau į savo partnerio mobilųjį telefoną.",
    "Ich habe noch nie!" to "Aš niekada!",
    "Ich habe!" to "Turiu!",
    "Ich lache viel mit meinem Partner." to "Aš daug juokiuosi su savo partneriu.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Man patinka pažinti savo partnerio pomėgius ir pomėgius.",
    "Ich liebe es" to "Man tai patinka",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Mėgstu su savo partneriu žiūrėti filmus, kurių nė vienas iš mūsų dar nematė.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Man patinka dalintis savo mėgstama muzika su savo partneriu.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Man niekada neteko bėgti, kad spėčiau į jungiamąjį skrydį.",
    "Ich plane gerne Dates mit meinem Partner." to "Man patinka planuoti pasimatymus su savo partneriu.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Pirmenybę teikiu leisti laiką su savo partneriu net tada, kai esu užsiėmęs.",
    "Ich schreibe meinem Partner jeden Tag." to "Kasdien rašau savo partneriui žinutes.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Man patinka dalytis memais ir juokeliais su savo partneriu.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Man patinka su savo partneriu dalytis visomis savo dienos detalėmis.",
    "Ich würde es nie tun" to "Niekada to nedaryčiau",
    "Ich übe noch" to "Vis dar praktikuojuosi",
    "Ideen generieren" to "Generuokite idėjas",
    "Im Haushalt helfen" to "Pagalba namuose",
    "In Chat einfügen" to "Pridėti prie pokalbio",
    "In Stille nebeneinander" to "Tyloje vienas šalia kito",
    "In den Bergen" to "Kalnuose",
    "In eine Bar gehen" to "Eikite į barą",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Eikite į paplūdimio barą žiūrėti saulėlydžio",
    "In einem feinen Restaurant essen gehen" to "Valgykite puikiame restorane",
    "In einen Coffeeshop gehen" to "Eikite į kavinę",
    "In einer Beziehung sollte man alles voneinander wissen." to "Santykiuose turėtumėte žinoti viską apie vienas kitą.",
    "Infinity-Pool" to "Begalybės baseinas",
    "Innenpool" to "Vidinis baseinas",
    "Intelligenz" to "Intelektas",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Intymias akimirkas patirkite tik tada, kai partneris jas inicijuoja",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Kvietimo kodas: HRM-8731 · viskas atrakinta",
    "Island" to "Islandija",
    "Ist okay für mich" to "Man viskas gerai",
    "Ist schon perfekt" to "Tai tobula",
    "Ja, Traditionen einbinden" to "Taip, įtraukite tradicijas",
    "Ja, absolut" to "Taip, tikrai",
    "Ja, etwas zum Lesen und Aufbewahren" to "Taip, yra ką perskaityti ir pasilikti",
    "Ja, genug" to "Taip, gana",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Taip, įdomiame mieste ar lankytinoje vietoje",
    "Ja, in- und auswendig" to "Taip, viduje ir išorėje",
    "Ja, komplett überraschend" to "Taip, visiškai stebina",
    "Ja, perfekt" to "Taip, tobula",
    "Ja, sie gehören zur Familie!" to "Taip, jie yra šeima!",
    "Ja, sofort teilen" to "Taip, nedelsdami bendrinkite",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Taip, mes užtikrinsime, kad šeimos laikas būtų prioritetas.",
    "Jacuzzi" to "sūkurinė vonia",
    "Jahr zusammen 🎉" to "metai kartu 🎉",
    "Jahre zusammen 🎉" to "Metai kartu 🎉",
    "Jeder zahlt 50%" to "Visi moka 50 proc.",
    "Junge" to "Berniukas",
    "Kamin" to "Židinys",
    "Karriere & Erfolg" to "Karjera ir sėkmė",
    "Kategorien" to "Kategorijos",
    "Katze" to "Kat",
    "Keine Musik" to "Nėra muzikos",
    "Keine Party nötig, privat halten" to "Nereikia vakarėlio, laikykite jį privačiu",
    "Keine Privatsphäre" to "Nėra privatumo",
    "Keine Treffer gefunden" to "Atitikčių nerasta",
    "Keiner" to "Nėra",
    "Keiner von uns" to "Nė vienas iš mūsų",
    "Kennst du die Essensvorlieben deines Partners?" to "Ar žinote savo partnerio maisto pasirinkimą?",
    "Kino" to "Kinas",
    "Kirchlich" to "Bažnytinė",
    "Klassisch Solitär" to "Klasikinis pasjansas",
    "Klassisch gebunden" to "Klasikinis įrišimas",
    "Klein & zart" to "Mažas ir subtilus",
    "Kleine Geschenke" to "Mažos dovanos",
    "Kleine Runde" to "Maža grupė",
    "Kochen und Freunde einladen" to "Gaminame maistą ir kviečiame draugus",
    "Kochkurs" to "Maisto gaminimo pamoka",
    "Kommt auf den Tag an" to "Priklauso nuo dienos",
    "Kommt darauf an" to "Tai priklauso",
    "Kommt drauf an" to "Tai priklauso",
    "Kommt mit" to "Eime su manimi",
    "Konzert" to "Koncertas",
    "Kräftige Farben" to "Stiprios spalvos",
    "Kräuterbeet" to "Žolelių lova",
    "Kultur & Sehenswürdigkeiten" to "Kultūra ir įžymybės",
    "Kuscheln" to "Apkabinimas",
    "Kuss senden" to "Nusiųskite bučinį",
    "Körperliche Annäherung" to "Fizinis požiūris",
    "Körperliche Nähe" to "Fizinis artumas",
    "Küche" to "Virtuvė",
    "Land" to "Šalis",
    "Landhaus" to "Užmiesčio namas",
    "Landhausstil" to "Užmiesčio stiliaus",
    "Lange wach bleiben" to "Nemiegokite iki vėlumos",
    "Lappland" to "Laplandija",
    "Lappland, Finnland" to "Laplandija, Suomija",
    "Las Vegas" to "Las Vegasas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Tegul jūsų partneris įkvepia jus būti geriausiu savimi",
    "Lehne ab" to "Atmetimas",
    "Leichtigkeit" to "Lengvumas",
    "Leidenschaft" to "Aistra",
    "Liebe im Gleichgewicht" to "Meilė pusiausvyroje",
    "Liebe sie, macht mehr Spaß" to "Mylėk juos, smagiau",
    "Lieber durchgeplant oder spontan?" to "Ar norėtumėte, kad tai būtų suplanuota ar spontaniška?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Ar norėtumėte ramiai praleisti vakarą dviese ar su žmonėmis?",
    "Lieber nicht" to "Geriau ne",
    "Lieber vorher grob absprechen" to "Geriau viską apytiksliai aptarti iš anksto",
    "Lokal einkaufen" to "Apsipirkite vietoje",
    "London" to "Londonas",
    "London, England" to "Londonas, Anglija",
    "Lügen" to "Melas",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Ar jums labiau patinka viešas ar privatus pasiūlymas?",
    "Malediven" to "Maldyvai",
    "Man sollte nie streitend einschlafen." to "Niekada neturėtumėte užmigti ginčydamiesi.",
    "Mango Sorbet" to "Mango šerbetas",
    "Markant & breit" to "Stulbinantis ir platus",
    "Marken & Alltag" to "Prekiniai ženklai ir kasdienis gyvenimas",
    "McDonald’s" to "„McDonald's“.",
    "Mediterraner Innenhof" to "Viduržemio jūros kiemas",
    "Mehr Unterstützung" to "Daugiau paramos",
    "Mehr gemeinsame Zeit" to "Daugiau laiko kartu",
    "Mehr zuhören" to "Klausykite daugiau",
    "Mehrgenerationenhaus" to "Kelių kartų namas",
    "Mein Arbeitsplatz" to "Mano darbo vieta",
    "Mein Partner" to "Mano partneris",
    "Mich überraschen" to "Nustebink mane",
    "Minimalistisches Interieur" to "Minimalistinis interjeras",
    "Missverständnisse" to "Nesusipratimai",
    "Mit Familie und engen Freunden" to "Su šeima ir artimais draugais",
    "Mit Kompromissen" to "Su kompromisais",
    "Mitgefühl" to "Užuojauta",
    "Mittelweg mit besonderen Details" to "Viduržemis su ypatingomis detalėmis",
    "Modern geometrisch" to "Šiuolaikinė geometrinė",
    "Moderne Grillstation" to "Šiuolaikinė grilio stotis",
    "Moderner Name" to "Šiuolaikinis pavadinimas",
    "Moderner Solitär" to "Šiuolaikinis pasjansas",
    "Moissanit" to "Moissanitas",
    "Moment festhalten" to "Užfiksuokite akimirką",
    "Momente" to "akimirkos",
    "Monaco" to "Monakas",
    "Moralische Werte" to "Moralinės vertybės",
    "Museum" to "muziejus",
    "Musik" to "Muzika",
    "Mut" to "Drąsa",
    "Mädchen" to "Merginos",
    "Möbelhaus" to "Baldų parduotuvė",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Ar tikrai norite išeiti iš viktorinos? Jūsų ankstesnė pažanga išlieka išsaugota.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Ar norėtumėte, kad į paraišką būtų įtraukti augintiniai?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Norite, kad akimirka būtų akimirksniu pasidalinta socialinėje žiniasklaidoje?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Gali tekti sutaupyti",
    "Müssen es planen" to "Reikia planuoti",
    "Müssen sparen" to "Reikia išsaugoti",
    "Nachricht an" to "Pranešimas",
    "Name Partnerin" to "Partnerio vardas ir pavardė",
    "Namen und Startdatum eurer Beziehung." to "Jūsų santykių vardai ir pradžios data.",
    "Natursteinfassade" to "Natūralaus akmens fasadas",
    "Naturteich" to "Natūralus tvenkinys",
    "Nein, einfach halten" to "Ne, tiesiog palaikykite",
    "Nein, erstmal privat halten" to "Ne, kol kas laikykite jį privačiu",
    "Nein, lieber vor Ort" to "Ne, geriau vietoje",
    "Nein, modern halten" to "Ne, būkite šiuolaikiški",
    "Nein, nur wir" to "Ne, tik mes",
    "Nein, zu ablenkend" to "Ne, per daug blaško",
    "Netflix" to "„Netflix“.",
    "Neubau mit Smart Home" to "Naujas pastatas su išmaniaisiais namais",
    "Neubau mit Technik" to "Naujas pastatas su technologijomis",
    "Neue Liebe, neue Erfahrungen" to "Nauja meilė, nauji potyriai",
    "Neues Hobby" to "Naujas pomėgis",
    "Neues Spiel" to "Naujas žaidimas",
    "Neugier" to "Smalsumas",
    "New York" to "Niujorkas",
    "New York, USA" to "Niujorkas, JAV",
    "Nicht mein Fall" to "Ne mano arbatos puodelis",
    "Nicht nötig, lieber klassisch bleiben" to "Nebūtina, geriau likti klasika",
    "Nichts — es passt so" to "Nieko – tinka",
    "Nie wieder Burger" to "Niekada daugiau mėsainių",
    "Nie wieder Pizza" to "Niekada daugiau picos",
    "Niemand" to "Niekas",
    "Niemand ohne Plan" to "Niekas be plano",
    "Nike" to "Nike",
    "Nizza" to "Puiku",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Dar nėra akimirkų.\nUžfiksuokite savo pirmąją patirtį 💞",
    "Nur bei wichtigen Themen" to "Tik svarbioms temoms",
    "Nur wir beide" to "Tik mes dviese",
    "Nähe & Intimität" to "Artumas ir intymumas",
    "Obstgarten" to "Sodas",
    "Oder" to "Or",
    "Offene Küche" to "Atvira virtuvė",
    "Offene Wohnküche" to "Atvira virtuvė/svetainė",
    "Ohne Stein" to "Be akmens",
    "Open End" to "Nebaigta",
    "Outdoor-Küche" to "Lauko virtuvė",
    "Outdoor-Sofa" to "Lauko sofa",
    "Outdoor-Whirlpool" to "Lauko sūkurinė vonia",
    "Ovaler Diamant" to "Ovalus deimantas",
    "Paar" to "Pora",
    "Paar-Statistiken" to "Poros statistika",
    "Paris" to "Paryžius",
    "Paris, Frankreich" to "Paryžius, Prancūzija",
    "Partner" to "Partneris",
    "Partner-Simulator" to "Partnerių simuliatorius",
    "Partnerin" to "Partneris",
    "Party Edition" to "Party Edition",
    "Party Edition II" to "Party Edition II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Ar gyvūnas netgi tinka mūsų kasdieniame gyvenime?",
    "Pasta" to "Makaronai",
    "Pastell" to "Pastelė",
    "Penthouse mit Ausblick" to "Mansarda su vaizdu",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pavėsinė su poilsio kambariu",
    "Pfingstrosen" to "Bijūnai",
    "Pinguin" to "Pingvinas",
    "Pistazie" to "Pistacijos",
    "Pizza" to "Pica",
    "Pizzaofen" to "Picos orkaitė",
    "Platin" to "Platina",
    "PlayStation" to "PlayStation",
    "Pool" to "Baseinas",
    "Pop" to "Pop",
    "Prasselnder Kamin" to "Rūkantis židinys",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Princesės, piratai ir fėjų dulkės: Disnėjaus viktorina",
    "Privater Innenhof" to "Privatus kiemas",
    "Profil" to "profilis",
    "Profil bearbeiten" to "Redaguoti profilį",
    "Prozentual nach Einkommen" to "Procentas, pagrįstas pajamomis",
    "Quiz verlassen" to "Baigti testą",
    "Quiz verlassen?" to "Išeiti iš viktorinos?",
    "Rausgehen in die Natur" to "Išeikite į gamtą",
    "Reden vor ..." to "Kalbėdamas su...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Kartu suplanuokite įprastas datas arba laiką",
    "Reisen" to "Kelionės",
    "Reiseziele" to "Kelionių kryptys",
    "Respektlosigkeit" to "Nepagarba",
    "Restaurant" to "Restoranas",
    "RnB / Soul" to "RnB / Soul",
    "Rock" to "Rokas",
    "Rom" to "Roma",
    "Rom, Italien" to "Roma, Italija",
    "Romantik" to "Romantika",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Mane džiugina romantiški gestai, tokie kaip žinutės, užrašai ar dovanos.",
    "Romantische Stimmung" to "Romantiška nuotaika",
    "Roségold" to "Rožinis auksas",
    "Ruhig zu zweit" to "Ramiai dviems",
    "Runder Diamant" to "Apvalus deimantas",
    "Salted Caramel" to "Sūdyta karamelė",
    "Sammle Ideen..." to "Surinkite idėjas...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Graikija",
    "Saphir" to "Safyras",
    "Saunahaus" to "Pirties namelis",
    "Schickes Restaurant oder Hotel" to "Prašmatnus restoranas arba viešbutis",
    "Schlafzimmer" to "Miegamasis",
    "Schließen" to "Uždaryti",
    "Schmal & zart" to "Plonas ir subtilus",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Mūsų meilės istorijos momentinės nuotraukos",
    "Schokolade" to "Šokoladas",
    "Schreib frei, was dir wirklich dazu einfällt." to "Rašykite laisvai tai, kas iš tikrųjų ateina į galvą.",
    "Schreibe deine eigene Antwort" to "Parašykite savo atsakymą",
    "Sehr gerne" to "Sveiki",
    "Sehr leicht" to "Labai lengvas",
    "Sehr wichtig — Fotos und Video" to "Labai svarbu – nuotraukos ir vaizdo įrašai",
    "Sehr wichtig, es sollte persönlich sein" to "Labai svarbu, tai turėtų būti asmeniška",
    "Selbst kochen" to "Gaminkite patys",
    "Senden" to "Siųsti",
    "Separate Küche" to "Atskira virtuvė",
    "Serie schauen" to "Žiūrėkite serialą",
    "Serienmarathon auf dem Sofa" to "Serijos maratonas ant sofos",
    "Sex & Liebe" to "Seksas ir meilė",
    "Seychellen" to "Seišeliai",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Ar galime padengti visas išlaidas vienam vaikui / keliems vaikams? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Ar pasiūlymas turėtų nustebinti?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Ar paraiškoje turi būti kultūros ar tradicinių elementų?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Ar paraiškoje turi būti kultūros ar tradicinių elementų?",
    "Sommerhochzeit" to "Vasaros vestuvės",
    "Sonnige Dachterrasse" to "Saulėta stogo terasa",
    "Sowohl als auch" to "Tiek ir",
    "Spazieren" to "Pasivaikščiokite",
    "Spaß & Abenteuer" to "Linksmybės ir nuotykiai",
    "Speichern" to "Išsaugokite",
    "Spiel bearbeiten" to "Redaguoti žaidimą",
    "Spielbereich für Kinder" to "Vaikų žaidimų aikštelė",
    "Spiele" to "Žaidimai",
    "Spiele spielen und Spaß haben" to "Žaiskite žaidimus ir linksminkitės",
    "Spontan" to "Spontaniškas",
    "Sportplatz" to "Sporto aikštelė",
    "Spotify" to "„Spotify“.",
    "Sprache" to "Kalba",
    "Stadt" to "Miestas",
    "Stadt oder Land — was ist uns wichtiger?" to "Miestas ar šalis – kas mums svarbiau?",
    "Stadtvilla" to "Miesto vila",
    "Standesamt & Party" to "Registro įstaiga ir partija",
    "Statement-Ring" to "Pareiškimo žiedas",
    "Stilvolles Outdoor-Sofa" to "Stilinga lauko sofa",
    "Stimme voll zu" to "Visiškai sutinku",
    "Stimmt" to "Teisingai",
    "Stimmt nicht" to "Netiesa",
    "Stimmt, noch nie" to "Tiesa, niekada",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Paplūdimio diena",
    "Streit über Haushalt" to "Ginčas dėl namų ūkio",
    "Studio Ghibli" to "Studija Ghibli",
    "Ständig" to "Nuolat",
    "Suche schließen" to "Uždaryti paiešką",
    "Suche zurücksetzen" to "Iš naujo nustatyti paiešką",
    "Suche öffnen" to "Atidaryti paiešką",
    "Suchergebnisse" to "Paieškos rezultatai",
    "Sushi" to "Sušiai",
    "Süß" to "Miela",
    "Tage zusammen 💞" to "dienų kartu 💞",
    "Tauche ins Unterbewusstsein" to "Pasinerkite į pasąmonę",
    "Teile alle deine Hobbys mit deinem Partner" to "Pasidalykite visais savo pomėgiais su savo partneriu",
    "Teils teils" to "Iš dalies iš dalies",
    "Testen" to "Bandymas",
    "Themen" to "Temos",
    "Tiefe Gespräche" to "Gilūs pokalbiai",
    "Tiefgründige Gespräche führen" to "Kalbėkite giliai",
    "Tierpension" to "Gyvūnų pensionas",
    "Tiny House" to "Mažas namas",
    "Tippen zum Auswählen & Scrollen" to "Palieskite, kad pasirinktumėte ir slinktumėte",
    "Tippen zum Zuklappen" to "Palieskite, kad sutrauktumėte",
    "Titel" to "Pavadinimas",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Pavadinimas, kategorija, tema, žymos, klausimai...",
    "Tokyo, Japan" to "Tokijas, Japonija",
    "Traditioneller Name" to "Tradicinis pavadinimas",
    "Traumhaus Außenbereich" to "Svajonių namo lauko zona",
    "Traumhochzeit" to "Svajonių vestuvės",
    "Treffer" to "Hitas",
    "Tägliche Aktivität" to "Kasdienė veikla",
    "Umformulieren" to "Perfrazuoti",
    "Unbeantwortet" to "Neatsakyta",
    "Unbeliebte Meinungen" to "Nepopuliarios nuomonės",
    "Universal Studios Genie oder Neuling?" to "„Universal Studios“ genijus ar naujokas?",
    "Uns auseinanderzuleben" to "Atsiskirti",
    "Unser Intimleben" to "Mūsų intymus gyvenimas",
    "Unser Traumhaus" to "Mūsų svajonių namas",
    "Unser erstes Treffen" to "Mūsų pirmasis susitikimas",
    "Unsere Gesichter" to "Mūsų veidai",
    "Unsere eigenen Träume" to "Mūsų pačių svajonės",
    "Unsere nächste Reise" to "Kita mūsų kelionė",
    "Unter 1000" to "Iki 1000",
    "Unter 1000 im Monat" to "Mažiau nei 1 000 per mėnesį",
    "Unter 50€/Monat" to "Mažiau 50 €/mėn",
    "Unter Leuten" to "Tarp žmonių",
    "Untreue" to "Neištikimybė",
    "Urlaub" to "Atostogos",
    "Vanille" to "Vanilė",
    "Venedig" to "Venecija",
    "Venedig, Italien" to "Venecija, Italija",
    "Verbinde dich mit" to "Prisijunkite su",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Prisijunkite prie \${profile.partnerName}, kad pamatytumėte atsakymą",
    "Verbindung" to "ryšį",
    "Verbringe die Feiertage mit deiner Familie" to "Praleiskite atostogas su šeima",
    "Verlobungsringe" to "Sužadėtuvių žiedai",
    "Vertrautheit" to "Susipažinimas",
    "Viel getrennt" to "Daug išsiskyrimo",
    "Vielleicht ein oder zwei" to "Gal vienas ar du",
    "Vielleicht, aber mündlich reicht" to "Galbūt, bet užtenka žodžiu",
    "Vielleicht, wenn es machbar ist" to "Galbūt, jei įmanoma",
    "Vielleicht, wenn es passt" to "Galbūt, jei tinka",
    "Vintage Art déco" to "Vintage Art Deco",
    "Vintage verspielt" to "Vintažinis žaismingas",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Jūsų partneris supažindino su naujais pomėgiais",
    "Vor dem Kauf eines Hauses besprechen" to "Aptarkite prieš pirkdami namą",
    "Vor der Anschaffung eines Haustiers besprechen" to "Aptarkite prieš įsigydami augintinį",
    "Vor der gemeinsamen Reise besprechen" to "Aptarkite prieš keliaudami kartu",
    "Vor nichts" to "Nieko",
    "Vorort" to "Priemiestis",
    "Walnuss" to "Riešutas",
    "Wandern" to "Žygiai",
    "Wann fühlst du dich mir am nächsten?" to "Kada jautiesi arčiausiai manęs?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Kada jautiesi fiziškai arčiausiai manęs?",
    "Was bedeutet Vertrauen für dich konkret?" to "Ką konkrečiai jums reiškia pasitikėjimas?",
    "Was entspannt dich mehr?" to "Kas labiau atpalaiduoja?",
    "Was fehlt dir über die Distanz am meisten?" to "Ko labiausiai pasiilgai per atstumą?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Kas jums labiausiai patinka savo namuose?",
    "Was hast du von deinem Partner gelernt?" to "Ko išmokote iš savo partnerio?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Ką manote apie erotinio turinio žiūrėjimą kartu?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Ką manote apie rekvizitus (pvz., ženklus, balionus ir kt.)?",
    "Was ist das Wichtigste beim Antrag?" to "Kas svarbiausia teikiant paraišką?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Ko svarbiausia, ko ieškote per seksualinius santykius?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Kokia jūsų mėgstamiausia mūsų nuotrauka? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Ko labiausiai bijote gyvenant kartu?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Kokį maistą mėgstate, bet jūsų partneris negali suprasti?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Kas jums yra absoliutus susitarimo nutraukėjas?",
    "Was ist für jeden von uns das absolute Highlight?" to "Kas yra svarbiausia kiekvienam iš mūsų?",
    "Was ist passiert?" to "Kas atsitiko?",
    "Was macht einen Moment für dich romantisch?" to "Kas akimirką paverčia romantiška?",
    "Was magst du an deinem Partner am liebsten?" to "Kas jums labiausiai patinka savo partneryje?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Kas jums labiau patinka: anksti keltis ar vėlai keltis?",
    "Was magst du lieber?" to "Kuris jums labiau patinka?",
    "Was möchtest du eigentlich sagen?" to "Ką iš tikrųjų norite pasakyti?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Ką norėtumėte, kad jūsų partneris darytų dažniau?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Kas nutinka gyvūnui, kai keliaujame?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Kas bus su mūsų vaiku, kai jis užaugs?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Ko niekada neturėtume pamiršti, kaip tėvai?",
    "Was war dein schönster Moment mit mir bisher?" to "Koks buvo jūsų geriausias momentas su manimi iki šiol?",
    "Was wir gegessen haben" to "Ką valgėme",
    "Was wollt ihr nie vergessen?" to "Ko niekada nenorite pamiršti?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Kas jums būtų blogiau: daugiau niekada nevalgykite picos ar niekada daugiau mėsainių?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Ką labiausiai norėtumėte veikti per dieną kartu?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Ką iš karto pakeistumėte, jei pinigai nebūtų problema?",
    "Weiter" to "Kitas",
    "Weiter spielen" to "Tęskite grojimą",
    "Weiß ich noch nicht" to "Dar nežinau",
    "Weiße Rosen" to "Baltos rožės",
    "Weißgold" to "Baltasis auksas",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Kokią kokybę mūsų vaikas tikrai turėtų gauti iš mūsų?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Kokioje aplinkoje norėtumėte pateikti pasiūlymą?",
    "Welcher Raum sagt am meisten über dich aus?" to "Kuris kambarys apie jus pasako labiausiai?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Kokį biudžetą planuojame maistui ir veterinarui?",
    "Welches Lied macht dich an? 🥵" to "Kuri daina jus įkvepia? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Kuri bendrinama nuotrauka yra jūsų mėgstamiausia?",
    "Wellnessbad" to "Sveikatingumo vonia",
    "Wenn es schwierig ist" to "Kai viskas sunku",
    "Wenn ich müde bin" to "Kai esu pavargęs",
    "Wenn wir uns lange umarmen" to "Kai ilgai apsikabiname",
    "Wenn wir zusammen lachen" to "Kai juokiamės kartu",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Kas greičiau nusprendžia, ką užsisakyti?",
    "Wer findet die besten Restaurants?" to "Kas randa geriausius restoranus?",
    "Wer gibt mehr Herzlichkeit?" to "Kas suteikia daugiau šilumos?",
    "Wer hat den besseren Musikgeschmack?" to "Kas turi geresnį muzikos skonį?",
    "Wer hängt mehr an seinen Eltern?" to "Kas labiau prisirišęs prie savo tėvų?",
    "Wer ist besser organisiert?" to "Kas yra geriau organizuotas?",
    "Wer ist der Beste bei der Filmauswahl?" to "Kas geriausiai renkasi filmus?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Kas geriausiai planuoja romantiškus pasimatymus?",
    "Wer ist der beste Tänzer?" to "Kas yra geriausias šokėjas?",
    "Wer ist romantischer?" to "Kas romantiškesnis?",
    "Wer kocht besser?" to "Kas gamina geriau?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Kas rūpinasi renovacija ir priežiūra?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Kas greičiau pastebi, kai kitas žmogus nesijaučia gerai?",
    "Wer sucht am Ende wirklich den Film aus?" to "Kas iš tikrųjų galiausiai pasirenka filmą?",
    "Wer vergisst eher einen Jahrestag?" to "Kas greičiausiai pamirš jubiliejų?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Kas kitą rytą greičiausiai pamirš savo vardą?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Kas greičiausiai kitą dieną ras vaizdo įrašą, apie kurį nieko nežinojo?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Kas mieliau praleistų naktį ant svetimos sofos?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Kas labiau užmigs vakarėlyje ir pabus su Šarpiu ant veido?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Kas greičiausiai paslys šokių aikštelėje, bet atrodys kaip šaunus žingsnis?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Kas labiau tikėtina, kad per namų vakarėlį perims „Spotify“ grojaraščio valdymą?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Kas būtų labiau linkęs užsisakyti picą visiems vakarėlyje ir suvalgyti pats?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Kas vakarėlyje labiau užmigs pirmas?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Kas labiau tikėtina, kad vakarėlyje staiga pradėtų tvarkytis?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Kas galėtų tvirtinti, kad yra visiškai blaivus, kai yra priešingai?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Kas yra labiau linkęs pirmas pasiduoti ginče?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Kas labiau linkęs sukčiauti gėrimo žaidime?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Kas labiau linkęs užpulti bufetą ir slapta parsinešti maistą namo?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Kas labiau tikėtina, kad savo istorijoje paskelbtų gėdingiausią vakaro nuotrauką?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Kas labiau suerzintų didžėjų, prašydamas savo mėgstamos dainos?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Kas būtų labiau linkęs dainuoti dainos žodžius išjungus klavišą, bet su įsitikinimu?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Kas greičiausiai užsisakytų brangiausią gėrimą iš meniu ir dėl to gailėtųsi?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Kas būtų labiau linkęs pakviesti kaimynus, jei šie skųstųsi dėl triukšmo?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Kas per rimtai žiūrėtų į vakarėlių žaidimus (pvz., Beer Pong)?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Kas būtų labiau linkęs susidraugauti su atšokusiais, kad gautų VIP prieigą?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Kas greičiausiai pradės spontanišką karaokės mūšį?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Kas labiau linkęs atidaryti butelį nenaudodamas butelių atidarytuvo?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Kas būtų labiau linkęs pasakyti kalbą, nors absoliučiai niekas neklaustų?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Kas labiau linkęs praleisti valandą vonioje darydamas asmenukes?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Kas būtų labiau linkęs surengti gėdingą šokio spektaklį ir jį švęsti?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Kas būtų labiau linkęs paskambinti buvusiam partneriui pasibaigus vakarėliui?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Kas galėtų netyčia įžeisti keistą svečią?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Kas būtų labiau linkęs slapta palikti vakarėlį neatsisveikinęs?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Kas mieliau žaistų su šeimininko augintiniu nei kalbėtųsi su svečiais?",
    "Wer würde eher spontan eine Reise buchen?" to "Kas būtų labiau linkęs užsisakyti kelionę spontaniškai?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Kas būtų labiau linkęs giliai kalbėtis virtuvėje valandų valandas?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Kas labiau linkęs netyčia išgerti kito gėrimo?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Kas labiau tikėtina, kad netyčia nuvers brangią vazą ar ką nors trapaus?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Kas labiau tikėtina, kad pats pabandys susimaišyti sudėtingą kokteilį ir nesėkmingai?",
    "Wer würde eher zu spät kommen?" to "Kas dažniau vėluoja?",
    "Wer würde eher?" to "Kas verčiau?",
    "Wer übernimmt die tägliche Versorgung?" to "Kas rūpinasi kasdiene priežiūra?",
    "Werde so akzeptiert, wie du bist" to "Būkite priimti tokie, kokie esate",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Ar turėsime pakankamai laiko vaikui/vaikams? ⏳",
    "Whirlpool" to "Sūkurinė vonia",
    "White Chocolate" to "Baltasis šokoladas",
    "Widgets" to "Valdikliai",
    "Wie fühlst du dich am meisten geliebt?" to "Kaip jaučiatės labiausiai mylimas?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Kaip elgiamės su skirtingomis pajamomis?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Koks yra geriausias būdas jūsų partneriui inicijuoti seksą su jumis?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Kaip jūsų partneris gali būti dar geresnis jūsų partneris?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Kiek laiko po pasiūlymo norite švęsti su kitais?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Kiek ilgai norime ten pasilikti?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Kaip lengva jums kalbėti apie norus?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Kaip norite, kad atrodytų mūsų ateitis?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Kaip atrodo jūsų tobulas sekmadienis namuose?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Kaip manote apie nešvankias kalbas sekso metu?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Kiek kredito realiai galime sau leisti?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Kiek laiko norime praleisti atskirai?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Kiek iš viso norime išleisti?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Kaip rasime laiko santykiams gimus kūdikiui?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Kiek jums svarbu, kad akimirka būtų užfiksuota?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Ar jums svarbu, kad programa atspindėtų jūsų pomėgius ar pomėgius?",
    "Wie würdest du sie/ihn nennen?" to "Kaip jį/ją pavadintumėte?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Koks jūsų mėgstamiausias būdas parodyti meilę ne sekso metu?",
    "Wildblumen" to "Laukinės gėlės",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Nori mergaitės ar berniuko? 👶",
    "Wintergarten" to "Žiemos sodas",
    "Winterhochzeit" to "Žiemos vestuvės",
    "Wir bestellen einfach beides" to "Tiesiog užsakome abu",
    "Wir brauchen ewig" to "Tai trunka amžinai",
    "Wir einigen uns nie" to "Mes niekada nesutinkame",
    "Wir entscheiden es gemeinsam" to "Nusprendžiame kartu",
    "Wir treffen uns in der Mitte" to "Susitinkame viduryje",
    "Wir wechseln uns ab" to "Mes paeiliui",
    "Wird stressig" to "Patiria stresą",
    "Wobei lachst du am meisten?" to "Kas jus labiausiai juokina?",
    "Wofür sparen wir gemeinsam?" to "Kam mes kartu taupome?",
    "Wohnzimmer" to "Svetainė",
    "Woran erinnerst du dich am lebhaftesten?" to "Kas jums įsiminė ryškiausiai?",
    "Worauf freust du dich bei uns am meisten?" to "Ko labiausiai laukiate su mumis?",
    "Worte/Komplimente" to "Žodžiai / komplimentai",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Ko labiausiai bijai mūsų santykiuose?",
    "Wünsche? z.B. günstig, draußen" to "Linkėjimai? pvz. pigu, lauke",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Ar norėtumėte pasiūlyti atostogas (su kelionėmis)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "„YouTube Music“.",
    "Zeichne für mich" to "Pieškite man",
    "Zeichne mich als Tier — welches wäre ich?" to "Nupiešk mane kaip gyvūną – koks aš būčiau?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Nubrėžkite mūsų jausmus vienas kitam kaip simbolį.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Viena linija nupieškite mūsų svajonių namą. Kas labiausiai stebina?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Nupieškite mūsų pirmąjį pasimatymą – kas būtinai turi būti nuotraukoje?",
    "Zeichnen" to "Lygiosios",
    "Zeit füreinander" to "Laikas vienas kitam",
    "Zeit, wenn das Baby schläft" to "Laikas, kai kūdikis miega",
    "Zelten gehen" to "Eikite į stovyklą",
    "Zitrone" to "Citrina",
    "Zu Hause, gemütlich und privat" to "Namuose, jaukiai ir privačiai",
    "Zu einem Picknick gehen" to "Iškylauti",
    "Zu einem ausgefallenen Abendessen gehen" to "Einate į prabangią vakarienę",
    "Zu zweit reisen" to "Keliaukite kaip pora",
    "Zuhause & Alltag" to "Namai ir kasdienybė",
    "Zuhören" to "Klausykite",
    "Zurück" to "Atgal",
    "Zusammen seit" to "Kartu nuo",
    "Zusammen seit (TT.MM.JJJJ)" to "Kartu nuo (DD.MM.YYYY)",
    "Zusammenziehen" to "Sutartis",
    "Zustimmen oder Ablehnen" to "Sutinku arba nesutinku",
    "Zwei Kreise, die sich überschneiden" to "Du apskritimai, kurie persidengia",
    "Zwei Stühle davor" to "Dvi kėdės priešais",
    "Zärtlich sein" to "Būkite švelnūs",
    "Öfter als ich zugebe" to "Daugiau kartų, nei pripažįstu",
    "Über 100€/Monat" to "Daugiau nei 100 €/mėn",
    "Über 2000 im Monat" to "Daugiau nei 2000 per mėnesį",
    "Über mich selbst" to "Apie save",
    "Übernehmen" to "Taikyti",
    "Überraschend" to "Stebina",
    "Überraschung" to "staigmena",
    "Überspringen" to "Praleisti",
    "Übertrieben und großartig" to "Puiku ir nuostabu",
    "✎ Tippe, um zu antworten" to "✎ Palieskite, kad atsakytumėte",
    "✨ GFK-Brücke" to "✨ GRP tiltas",
)

internal fun localizeLithuanianDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_LITHUANIAN_CONTENT)
