package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_MALAY_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 tahun",
    "1000 - 1500 im Monat" to "1000 - 1500 sebulan",
    "1000 bis 3000" to "1000 hingga 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 sebulan",
    "3000 bis 5000" to "3000 hingga 5000",
    "5-10 Jahre" to "5-10 tahun",
    "50-100€/Monat" to "50-100€/bulan",
    "Ab 100€" to "Daripada 100€",
    "Ab 500€" to "Daripada 500€",
    "Ab 50€" to "Daripada 50€",
    "Ab und zu" to "Sekarang dan kemudian",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Berapa banyak yang kita bincangkan sebelum membuat pembelian?",
    "Abbrechen" to "Batal",
    "Abenteuer" to "pengembaraan",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Aktiviti",
    "Alle" to "Semua",
    "Alle Pakete" to "Semua pakej",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Kehilangan semua kawan anda kecuali kawan baik anda",
    "Alle intimen Momente selbst initiieren" to "Mulakan semua detik intim sendiri",
    "Alles davon" to "Semuanya",
    "Alles, was noch kommt" to "Semua yang akan datang",
    "Alltagsroutine" to "Rutin harian",
    "Alltägliche Berührungen" to "Sentuhan setiap hari",
    "Altbau mit Charme" to "Bangunan lama dengan daya tarikan",
    "Am Strand" to "Di pantai",
    "Am liebsten alles zusammen" to "Sebaiknya semuanya bersama",
    "Am selben Tag mit Freunden/Familie" to "Hari yang sama dengan kawan/keluarga",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Belanda",
    "An das Gefühl" to "Dari perasaan",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "Di tempat awam yang ramai penonton",
    "An einen Geruch" to "Daripada bau",
    "An einen Song" to "Dari sebuah lagu",
    "An etwas, das ich gesagt habe" to "Tentang sesuatu yang saya katakan",
    "Analyse starten" to "Mulakan analisis",
    "Analysiere eure Muster..." to "Analisis corak anda...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Analisis jawapan & sembang anda mengikut Gottman dan GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Nanas pada pizza rasanya lazat.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Balas dengan foto",
    "Antwortähnlichkeit" to "Menjawab persamaan",
    "App-Sprache auswählen" to "Pilih bahasa apl",
    "Auf eine Bootsparty gehen" to "Pergi ke pesta bot",
    "Aufmerksamkeit" to "Perhatian",
    "Aufräumen und Projekte angehen" to "Membersihkan dan menangani projek",
    "Aufwärmen" to "memanaskan badan",
    "Aufwärmen: Einander kennenlernen" to "Memanaskan badan: mengenali antara satu sama lain",
    "Aus dem Urlaub" to "Dari bercuti",
    "Ausgefallener Name" to "Nama mewah",
    "Ausschlafen und faulenzen" to "Tidur dan bermalas-malasan",
    "Ausschlafen und nichts tun" to "Tidur dan tidak berbuat apa-apa",
    "Aussehen" to "Tengok",
    "Auto" to "kereta",
    "Außenkamin" to "Perapian luar",
    "BEANTWORTE" to "JAWAPAN",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonesia",
    "Banane" to "pisang",
    "Beantwortet" to "Dijawab",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Jawab soalan pada masa yang sama — jawapan tidak akan kelihatan sehingga anda berdua selesai.",
    "Beantwortete Fragen" to "Soalan yang dijawab",
    "Bearbeiten" to "Sunting",
    "Bei Insider-Witzen" to "Dengan jenaka dalaman",
    "Bei Memes" to "Dalam meme",
    "Bei einer spontanen Berührung" to "Dengan sentuhan spontan",
    "Beide" to "Kedua-duanya",
    "Beide gleich" to "Kedua-duanya sama",
    "Beide zusammen" to "Kedua-duanya bersama",
    "Beide, aber wir tun so als ob nicht" to "Kedua-duanya, tetapi kami berpura-pura tidak",
    "Beides" to "Kedua-duanya",
    "Beides wäre schlimm" to "Kedua-duanya akan menjadi buruk",
    "Beim Einschlafen nebeneinander" to "Tertidur bersebelahan",
    "Beim Reden" to "Sambil bercakap",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Tempat pelancongan terkenal sentiasa mengecewakan.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Terangkan kehidupan seks kita dengan emoji.",
    "Besser kommunizieren" to "Berkomunikasi dengan lebih baik",
    "Bessere Lage" to "Lokasi yang lebih baik",
    "Bestellen" to "Pesanan",
    "Besuchte Länder" to "Negara yang dilawati",
    "Besuchte Städte" to "Bandar yang dilawati",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Adakah anda lebih suka cadangan yang berlebihan atau sesuatu yang halus?",
    "Beziehung" to "Perhubungan",
    "Bibliothek" to "perpustakaan",
    "Bin manchmal unsicher" to "Saya kadang-kadang tidak selamat",
    "Bist du ein Videospiel-Guru?" to "Adakah anda seorang guru permainan video?",
    "Blumenwiese" to "padang rumput bunga",
    "Bunte Blumenwiese" to "Padang rumput bunga berwarna-warni",
    "Burger" to "Warganegara",
    "Burger King" to "Burger King",
    "Chat" to "Sembang",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Doh biskut",
    "Dachgarten mit Lounge" to "Taman bumbung dengan ruang istirahat",
    "Dachterrasse" to "Teras bumbung",
    "Das Wetter an dem Tag" to "Cuaca hari tu",
    "Das erste Selfie" to "Selfie pertama",
    "Das meiste weiß ich" to "Saya tahu kebanyakannya",
    "Das oder das?" to "Ini atau itu?",
    "Das tägliche Leben" to "Kehidupan seharian",
    "Dass Zusagen gehalten werden" to "Janji itu ditepati",
    "Dass alles meinen Stil hat" to "Bahawa segala-galanya mempunyai gaya saya",
    "Dass ich alles erzählen kann" to "Bahawa saya boleh memberitahu segala-galanya",
    "Dass ich mich nicht sorgen muss" to "Itu saya tidak perlu risau",
    "Dass wir ungestört sind" to "Bahawa kita tidak terganggu",
    "Dein Name" to "nama awak",
    "Deine Antwort..." to "Jawapan awak...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Jawapan anda disimpan. Sebaik sahaja Rakan Kongsi menyelesaikan pakej, kedua-dua jawapan akan kelihatan bersama-sama.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Jawapan anda disimpan. Setelah \${profile.partnerName} melengkapkan pakej, kedua-dua respons akan kelihatan bersama-sama.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Jadikan hubungan anda mencabar dan spontan",
    "Deine Beziehung stabil und sicher machen" to "Jadikan hubungan anda stabil dan terjamin",
    "Deine eigene Antwort" to "Jawapan anda sendiri",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Sebaliknya kongsi rahsia terdalam anda dengan pasangan anda",
    "Deinen besten Freund verlieren" to "Kehilangan kawan baik anda",
    "Denke an dich" to "Fikirkan tentang diri anda",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Menonton filem yang sama dua kali adalah membuang masa.",
    "Der Blick nach draußen" to "Pemandangan di luar",
    "Der Garten" to "Taman itu",
    "Der Ort" to "tempat itu",
    "Der Ring und die Geste" to "Cincin dan isyarat",
    "Der perfekte Heiratsantrag" to "Cadangan perkahwinan yang sempurna",
    "Derjenige sein, der umarmt wird" to "Jadilah yang dipeluk",
    "Deutsch" to "Jerman",
    "Diamant" to "berlian",
    "Diamanten im Band" to "Berlian dalam kumpulan itu",
    "Die Distanz" to "Jaraknya",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Luangkan masa cuti bersama keluarga pasangan anda",
    "Die Gemütlichkeit und Ruhe" to "Keselesaan dan kedamaian",
    "Die Menschen, die darin wohnen" to "Orang yang tinggal di sana",
    "Die Umgebung und Atmosphäre" to "Persekitaran dan suasana",
    "Die Worte und Emotionen" to "Kata-kata dan emosi",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Cabaran kuiz hiburan muktamad",
    "Diejenige sein, die umarmt" to "Jadilah orang yang memeluk",
    "Direkt ansprechen" to "Alamat terus",
    "Diskussion" to "perbincangan",
    "Diskutiere vor dem Kinderkriegen" to "Berbincang sebelum mempunyai anak",
    "Diskutiert eure Antworten" to "Bincangkan jawapan anda",
    "Disney" to "Disney",
    "Doch, schon mal" to "Ya, sudah",
    "Draußen mit der Natur als Kulisse" to "Luar dengan alam semula jadi sebagai latar belakang",
    "Drei-Stein-Ring" to "Cincin batu tiga",
    "Du bist dran" to "Giliran awak",
    "Du fehlst mir" to "saya rindu awak",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubai, UAE",
    "Dunkles Design" to "Reka bentuk gelap",
    "Durch Berührung" to "Dengan sentuhan",
    "Durch Worte" to "Melalui kata-kata",
    "Durch Zeit zu zweit" to "Melalui masa bersama",
    "Durch kleine Gesten" to "Melalui isyarat kecil",
    "Durchgeplant" to "Terancang",
    "ERGEBNISSE" to "KEPUTUSAN",
    "Egal, Hauptsache gesund" to "Mana taknya, yang penting sihat",
    "Ehepaar Leben" to "Kehidupan pasangan suami isteri",
    "Eher knapp" to "Agak dekat",
    "Eher nicht" to "Sebaliknya tidak",
    "Eher schwer" to "Agak sukar",
    "Eher schwierig" to "Agak sukar",
    "Eher zu" to "Sebaliknya juga",
    "Eifersucht ist ein Zeichen von Liebe." to "Cemburu adalah tanda cinta.",
    "Eigenes Gemüsebeet" to "Tompok sayur sendiri",
    "Ein Abenteuer in einer neuen Stadt" to "Pengembaraan di bandar baru",
    "Ein Anker" to "sauh",
    "Ein Balkon oder Garten" to "Balkoni atau taman",
    "Ein Filmabend" to "Malam filem",
    "Ein Harmony-Meilenstein eurer Liebe." to "Satu pencapaian harmoni cinta anda.",
    "Ein Herz" to "Sebuah hati",
    "Ein Herz an der Tür" to "Hati di pintu",
    "Ein Jahr lang eine Fernbeziehung führen" to "Mempunyai hubungan jarak jauh selama setahun",
    "Ein Kindheitsessen" to "Hidangan zaman kanak-kanak",
    "Ein Live-Musik-Konzert besuchen" to "Hadiri konsert muzik secara langsung",
    "Ein Museum besuchen" to "Lawati muzium",
    "Ein Spieleabend" to "Malam permainan",
    "Ein Spieleabend mit Freunden" to "Malam permainan bersama rakan-rakan",
    "Ein Urlaubsfoto" to "Foto percutian",
    "Ein aktives Abenteuer" to "Pengembaraan yang aktif",
    "Ein entspannender Spa-Tag" to "Hari spa yang menenangkan",
    "Ein ganz normaler Alltagstag" to "Hari biasa setiap hari",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Petang yang selesa di rumah semasa ribut petir",
    "Ein gemütliches Date drinnen" to "Temu janji yang selesa di dalam rumah",
    "Ein lustiges Bild" to "Gambar yang kelakar",
    "Ein paar Handyfotos reichen" to "Beberapa gambar telefon bimbit sudah memadai",
    "Ein paar Stunden" to "Beberapa jam",
    "Ein paar kulturelle Anklänge sind okay" to "Sedikit rujukan budaya tidak mengapa",
    "Ein romantischer Abend" to "Malam yang romantis",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Makan malam romantis diterangi cahaya lilin",
    "Ein romantisches Bild" to "Imej romantik",
    "Ein romantisches Picknick an einem schönen Ort" to "Perkelahan romantis di lokasi yang indah",
    "Ein schwerer Moment, den wir geschafft haben" to "Saat sukar yang kami jayakan",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Temu janji yang hebat di luar rumah di bawah cahaya bulan",
    "Ein ungewöhnliches Gericht" to "Hidangan yang luar biasa",
    "Ein zufälliger Schnappschuss" to "Gambar rawak",
    "Einander kennenlernen" to "Mengenali antara satu sama lain",
    "Eine Autoreise" to "Perjalanan jalan raya",
    "Eine Brücke" to "Jambatan",
    "Eine Date-Nacht unter den Sternen" to "Malam temu janji di bawah bintang",
    "Eine Million Dollar gewinnen" to "Menangi satu juta dolar",
    "Eine Million Dollar verdienen" to "Buat satu juta dolar",
    "Eine Nacht in einem Club" to "Malam di sebuah kelab",
    "Eine Schokoladenverkostung" to "Rasa coklat",
    "Eine Wanderung mit Panoramablick machen" to "Berjalan mendaki dengan pemandangan panoramik",
    "Eine Weinverkostung" to "Rasa wain",
    "Eine gemeinsame Reise" to "Sebuah perjalanan bersama",
    "Eine gemütliche Nacht zu Hause" to "Malam yang nyaman di rumah",
    "Eine neue Sprache zu lernen ist einfach." to "Mempelajari bahasa baharu adalah mudah.",
    "Einen Film anschauen" to "Tonton filem",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Sebulan tidak bercakap sesama sendiri",
    "Einen Tanzkurs besuchen" to "Ambil kelas tarian",
    "Einen Vergnügungspark erkunden" to "Terokai taman hiburan",
    "Einen Wellness-Tag" to "Hari kesihatan",
    "Einen sehr emotionalen Partner haben" to "Mempunyai pasangan yang sangat emosional",
    "Einen sehr logischen Partner haben" to "Mempunyai pasangan yang sangat logik",
    "Einer zahlt alles" to "Satu orang membayar segala-galanya",
    "Einfach mehr Alltag" to "Lebih banyak kehidupan seharian",
    "Einfach nebeneinander sein" to "Bersebelahan sahaja",
    "Einfach und intim" to "Ringkas dan intim",
    "Einige Dinge für dich behalten" to "Simpan beberapa perkara untuk diri sendiri",
    "Einmal" to "sekali",
    "Eins, das nur wir kennen" to "Satu yang hanya kita tahu",
    "Englisch" to "Bahasa Inggeris",
    "Entspannte Hängematte" to "Buaian santai",
    "Entspannung" to "Relaksasi",
    "Erdbeere" to "Strawberi",
    "Erfolgreich" to "Berjaya",
    "Ergebnisse" to "Keputusan",
    "Erst bei sehr großen Summen" to "Hanya untuk jumlah yang sangat besar",
    "Erst nur enge Freunde/Familie" to "Hanya kawan rapat/keluarga pada mulanya",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Saya menjengkelkan apabila pasangan saya mengambil masa terlalu lama untuk membalas mesej.",
    "Essen & Genuss" to "Makanan & keseronokan",
    "Essensvorlieben" to "Keutamaan makanan",
    "Etwa eine Woche später, erst mal nur wir" to "Kira-kira seminggu kemudian, hanya kami pada mulanya",
    "Etwas Neues ausprobieren" to "Cuba sesuatu yang baru",
    "Etwas ganz anderes" to "Sesuatu yang berbeza sama sekali",
    "Etwas sehr Scharfes" to "Sesuatu yang sangat tajam",
    "Etwas, das ich selbst gern erfinde" to "Sesuatu yang saya suka cipta sendiri",
    "Etwas, eine kleine Note wäre schön" to "Sesuatu, sedikit sentuhan pasti bagus",
    "Familie" to "Keluarga",
    "Familie/Freunde" to "Keluarga/kawan",
    "Familienmensch" to "Lelaki keluarga",
    "Farbedelstein" to "Batu permata berwarna",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Iklan TV kadangkala menarik untuk ditonton.",
    "Fertig" to "Selesai",
    "Fertig!" to "Selesai!",
    "Feste Date-Nights" to "Malam tarikh tetap",
    "Feuerstelle" to "Lubang api",
    "Filigran & schlicht" to "Kerawang & ringkas",
    "Filme/Serien" to "Filem/siri",
    "Formuliere um..." to "Ungkapan semula...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Ungkapkan semula draf anda dengan cara yang tidak ganas: pemerhatian, perasaan, keperluan, permintaan.",
    "Frage hinzufügen" to "Tambah soalan",
    "Fragen & Spiele" to "Soalan & Permainan",
    "Fragen für jede Gelegenheit" to "Soalan untuk setiap kesempatan",
    "Freizeitpark" to "Taman hiburan",
    "Freunde treffen" to "Temui rakan-rakan",
    "Freundschaften mit Ex-Partnern sind okay." to "Persahabatan dengan bekas tidak mengapa.",
    "Früh aufstehen" to "Bangun awal",
    "Fußbodenheizung" to "Pemanasan bawah lantai",
    "Führen wir getrennte oder gemeinsame Konten?" to "Adakah kita mempunyai akaun berasingan atau bersama?",
    "Für dich empfohlen" to "Disyorkan untuk anda",
    "Für die Zukunft" to "Untuk masa hadapan",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Tiada soalan atau permainan yang sepadan ditemui untuk carian ini.",
    "Für immer" to "Selamanya",
    "Fürsorglichkeit" to "penyayang",
    "GFK-Brücke" to "jambatan GRP",
    "Galerie" to "galeri",
    "Gar nicht, der Moment gehört uns" to "Tidak sama sekali, masa ini adalah milik kita",
    "Gar nichts tun" to "Buat apa-apa pun",
    "Geduld" to "kesabaran",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Pergi awal pagi untuk melihat matahari terbit",
    "Geht so" to "Ia akan ok",
    "Geister existieren wirklich." to "Hantu memang wujud.",
    "Gelassenheit" to "ketenangan",
    "Gelbgold" to "Emas kuning",
    "Geld & Finanzen" to "Wang & Kewangan",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Kembara dunia bersama-sama, terokai budaya dan masakan baharu",
    "Gemeinsam ein Lego bauen" to "Bina Lego bersama-sama",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Cuba resipi baru bersama-sama di dapur",
    "Gemeinsame Konten" to "Akaun bersama",
    "Gemeinsame Nächte" to "Malam bersama",
    "Gemeinsame Tage" to "Hari yang dikongsi",
    "Gemischt" to "bercampur",
    "Gemüsebeet" to "tampalan sayur",
    "Gemütliche Feuerstelle" to "Lubang api yang selesa",
    "Gesprächsanreger" to "Permulaan perbualan",
    "Getrennte Konten" to "Akaun berasingan",
    "Getrennte Urlaube tun einer Beziehung gut." to "Percutian berasingan adalah baik untuk hubungan.",
    "Gewächshaus" to "rumah hijau",
    "Glasfassade" to "Fasad kaca",
    "Gleichgültigkeit" to "sikap acuh tak acuh",
    "Glücklich und frei" to "Gembira dan bebas",
    "Gourmet Eis-Sorten" to "Jenis aiskrim gourmet",
    "Gravur innen" to "Ukiran di dalam",
    "Grillplatz" to "Kawasan barbeku",
    "Groß & üppig" to "Besar & subur",
    "Große Familie" to "Keluarga besar",
    "Große Feier" to "Sambutan besar",
    "Große Fenster" to "Tingkap besar",
    "Große Fensterfront" to "Hadapan tingkap besar",
    "Großer Außenpool" to "Kolam renang luaran yang besar",
    "Großer Garten" to "Taman besar",
    "Großer Stein" to "Batu besar",
    "Größere Küche" to "Dapur yang lebih besar",
    "Gutes Essen" to "Selamat menjamu selera",
    "Habe ich" to "saya ada",
    "Habe ich noch nie" to "Saya tidak pernah",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Adakah anda menemui sebarang perbezaan yang mengejutkan? Bercakap tentang sebab anda lebih menyukai pilihan tertentu!",
    "Haus am See" to "Rumah di tepi tasik",
    "Haus/Wohnung" to "Rumah/apartmen",
    "Hazelnut" to "Hazelnut",
    "Heimkino" to "Teater rumah",
    "Herzhaft" to "Sedap",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Tiada apa-apa di sini sekarang.\nTukar penapis atau pilih topik lain.",
    "Hilfe im Alltag" to "Membantu dalam kehidupan seharian",
    "Himbeere" to "raspberi",
    "Hinzufügen" to "Tambah",
    "Hobbys" to "hobi",
    "Hochzeitssträuße" to "Sejambak perkahwinan",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Kebanggaan Rumah Hogwarts: Di Mana Anda Milik?",
    "Home" to "Rumah",
    "Hot Tub" to "Tab mandi panas",
    "Humor" to "jenaka",
    "Hund" to "anjing",
    "Hängematte" to "buaian",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Adakah anda mahu surat bertulis sebagai sebahagian daripada permohonan?",
    "IKEA" to "IKEA",
    "Ich" to "saya",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Saya lebih suka berjalan-jalan romantis di taman daripada pergi ke pawagam.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Saya tidak pernah tertidur di pawagam.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Saya seronok menemui hobi atau aktiviti baharu bersama pasangan saya.",
    "Ich finde eine Alternative" to "Saya akan cari alternatif",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Saya seronok mencuba restoran baharu bersama pasangan saya dan bukannya selalu pergi ke tempat yang sama.",
    "Ich habe noch nie" to "Saya tidak pernah",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Saya tidak pernah takut dengan roller coaster dan saya tetap menaikinya.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Saya tidak pernah membeli tiket Fast Pass kerana saya tidak sabar.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Saya tidak pernah membatalkan rancangan untuk tinggal di rumah dan menonton rancangan TV.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Saya tidak pernah menunggu surat saya daripada Hogwarts.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Saya tidak pernah mengatakan bahawa Slytherin sebenarnya tidak seteruk itu.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Saya tidak pernah mengatakan saya terlalu tua untuk filem Disney (dan diam-diam menikmatinya).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Saya tidak pernah sengaja menembak jatuh seseorang yang mempunyai kereta kebal biru dalam Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Saya tidak pernah menangis di filem Disney.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Saya tidak pernah menutup mata semasa menonton filem seram.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Saya tidak pernah lupa untuk menyimpan permainan dan kehilangan kemajuan berjam-jam.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Saya tidak pernah keluar dari bilik semasa adegan memalukan (faktor ngeri).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Saya tidak pernah melakukan pose lucu semasa mengambil gambar rollercoaster.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Saya tidak pernah bermain hingga larut malam dan menyesali keletihan saya pada keesokan harinya.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Saya tidak pernah google kesudahan filem kerana saya tidak sabar.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Saya tidak pernah berasa seperti saya berdiri di atas set filem.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Saya tidak pernah melangkau intro siri kegemaran saya.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Saya tidak pernah berkongsi kata laluan Netflix orang lain.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Saya tidak pernah mendengar runut bunyi permainan semasa bekerja atau belajar.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Saya tidak pernah menyalahkan pengawal apabila saya kalah.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Saya tidak pernah membuang papan kekunci atau pengawal kerana marah.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Saya tidak pernah lupa pakaian basah di mesin basuh selama beberapa hari.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Saya tidak pernah membelanjakan wang sebenar untuk barangan kosmetik dalam permainan.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Saya tidak pernah memandu kereta di negara asing.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Saya tidak pernah menyanyikan lagu Disney semasa mandi.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Saya tidak pernah memandu kereta elektrik.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Saya tidak pernah mengambil gambar dengan maskot taman.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Saya tidak pernah menamakan haiwan peliharaan sempena watak Hogwarts.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Saya tidak pernah menjatuhkan popcorn di panggung wayang dan masih memakannya.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Saya tidak pernah menggunakan petikan daripada Master Yoda daripada Star Wars dalam kehidupan seharian.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Saya tidak pernah membeli cenderahati terlalu mahal di taman tema.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Saya tidak pernah memberikan syor filem yang dianggap buruk oleh orang lain.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Saya tidak pernah menonton Oscar secara langsung di tengah malam.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Saya tidak pernah membatalkan satu siri kerana musim lepas sangat teruk.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Saya tidak pernah menonton keseluruhan musim siri dalam satu hari.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Saya tidak pernah mengalahkan bos pada percubaan pertama dan berasa seperti tuhan.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Saya tidak pernah menemui penjahat yang lebih hebat daripada wira.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Saya tidak pernah mengenali watak Toy Story dalam mainan saya sendiri.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Saya tidak pernah membuat watak dalam RPG sama seperti saya.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Saya tidak pernah makan churro di taman tema.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Saya tidak pernah menonton filem Disney tiga kali berturut-turut.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Saya tidak pernah mempunyai lagu Disney yang menarik sepanjang minggu.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Saya tidak pernah menonton filem hanya kerana pelakon tertentu.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Saya tidak pernah mendengar runut bunyi filem berulang selama berjam-jam.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Saya tidak pernah mendedahkan spoiler filem dan segera menyesalinya.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Saya tidak pernah menemui rakan yang bercakap bahasa ibunda lain.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Saya tidak pernah mempunyai kawan yang berpindah ke negara lain.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Saya tidak pernah melakukan maraton filem Harry Potter pada Krismas.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Saya tidak pernah menonton filem Marvel sehingga tamat hanya kerana adegan pasca kredit.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Saya tidak pernah dengan sengaja mengganggu NPC (Watak Bukan Pemain).",
    "Ich habe noch nie einen Nachtzug genommen." to "Saya tidak pernah menaiki kereta api malam.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Saya tidak pernah mengambil ujian dalam talian untuk mengetahui rumah Hogwarts saya.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Saya tidak pernah memadamkan siaran media sosial kerana ia tidak mendapat cukup suka.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Saya tidak pernah menyebut satu hari di taman tema sebagai hari terbaik dalam setahun.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Saya tidak pernah melawat taman tema dan menginap di sana dari pagi hingga malam.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Saya tidak pernah meninggalkan tunggangan Transformers atau Marvel sepenuhnya terpesona.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Saya tidak pernah marah berhenti dan berhenti permainan.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Saya tidak pernah membaca mana-mana jilid besar Harry Potter.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Saya tidak pernah meracau tentang watak kegemaran saya dalam satu siri.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Saya tidak pernah bermimpi bermain Quidditch.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Saya tidak pernah diam-diam google cara menyelesaikan tahap yang sukar.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Saya tidak pernah diam-diam berharap haiwan kesayangan saya boleh bercakap seperti di Disney.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Saya tidak pernah mengalih keluar ketua kumpulan dalam Sims.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Saya tidak pernah kehilangan galas saya dalam perjalanan simulator 3D.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Saya tidak pernah bermain dalam pasukan sukan universiti.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Saya tidak pernah menunggu dalam barisan selama lebih daripada dua jam untuk satu tarikan.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Saya tidak pernah membasahkan barang berharga saya semasa menaiki air.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Saya tidak pernah berdebat dengan rakan tentang rumah mana yang terbaik.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Saya tidak pernah berpura-pura mempunyai kuasa ajaib seperti Elsa.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Saya tidak pernah ketawa terlalu kuat sehingga saya terlepas babak penting dalam filem.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Saya tidak pernah merasakan adrenalin yang tinggi sehingga saya segera mahu menunggang semula.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Saya tidak pernah mencuba menyanyi dengan haiwan seperti Snow White.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Saya tidak pernah mengimpikan perjalanan ke Disneyland.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Saya tidak pernah bermimpi untuk menaiki water ride Jurassic Park.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Saya tidak pernah menjerit dengan kuat pada lompat ketakutan dalam permainan.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Saya tidak pernah menangis di akhir rancangan TV.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Saya tidak pernah... membatalkan tarikh untuk tinggal di rumah.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Saya tidak pernah... mengutarakan semula mesej sebanyak 10 kali.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Saya tidak pernah... diam-diam melihat telefon bimbit pasangan saya.",
    "Ich habe noch nie!" to "Saya tidak pernah!",
    "Ich habe!" to "Saya ada!",
    "Ich lache viel mit meinem Partner." to "Saya banyak ketawa dengan pasangan saya.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Saya suka mengenali hobi dan minat pasangan saya.",
    "Ich liebe es" to "Saya sukakannya",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Saya suka menonton filem dengan pasangan saya yang tidak pernah kami tonton sebelum ini.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Saya suka berkongsi muzik kegemaran saya dengan pasangan saya.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Saya tidak pernah perlu berlari untuk mengejar penerbangan sambungan.",
    "Ich plane gerne Dates mit meinem Partner." to "Saya suka merancang tarikh dengan pasangan saya.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Saya mengutamakan meluangkan masa bersama pasangan walaupun saya sibuk.",
    "Ich schreibe meinem Partner jeden Tag." to "Saya menghantar mesej kepada pasangan saya setiap hari.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Saya suka berkongsi meme dan jenaka dengan pasangan saya.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Saya suka berkongsi semua butiran hari saya dengan pasangan saya.",
    "Ich würde es nie tun" to "Saya tidak akan melakukannya",
    "Ich übe noch" to "Saya masih berlatih",
    "Ideen generieren" to "Menjana idea",
    "Im Haushalt helfen" to "Membantu di sekeliling rumah",
    "In Chat einfügen" to "Tambahkan pada sembang",
    "In Stille nebeneinander" to "Dalam diam bersebelahan",
    "In den Bergen" to "Di pergunungan",
    "In eine Bar gehen" to "Pergi ke bar",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Pergi ke bar pantai untuk melihat matahari terbenam",
    "In einem feinen Restaurant essen gehen" to "Makan di luar di restoran yang lazat",
    "In einen Coffeeshop gehen" to "Pergi ke kedai kopi",
    "In einer Beziehung sollte man alles voneinander wissen." to "Dalam hubungan anda harus tahu segala-galanya tentang satu sama lain.",
    "Infinity-Pool" to "Kolam infiniti",
    "Innenpool" to "Kolam dalaman",
    "Intelligenz" to "kecerdasan",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Hanya mempunyai detik-detik intim apabila pasangan anda memulakannya",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Kod jemputan: HRM-8731 · semuanya dibuka kunci",
    "Island" to "Iceland",
    "Ist okay für mich" to "Tak apa bagi saya",
    "Ist schon perfekt" to "Ia sudah sempurna",
    "Ja, Traditionen einbinden" to "Ya, masukkan tradisi",
    "Ja, absolut" to "Ya, sama sekali",
    "Ja, etwas zum Lesen und Aufbewahren" to "Ya, sesuatu untuk dibaca dan disimpan",
    "Ja, genug" to "Ya, cukup",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Ya, di bandar atau tarikan yang menarik",
    "Ja, in- und auswendig" to "Ya, dalam dan luar",
    "Ja, komplett überraschend" to "Ya, benar-benar mengejutkan",
    "Ja, perfekt" to "Ya, sempurna",
    "Ja, sie gehören zur Familie!" to "Ya, mereka adalah keluarga!",
    "Ja, sofort teilen" to "Ya, kongsi segera",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Ya, kami akan memastikan masa keluarga menjadi keutamaan.",
    "Jacuzzi" to "Jakuzi",
    "Jahr zusammen 🎉" to "tahun bersama 🎉",
    "Jahre zusammen 🎉" to "Bertahun bersama 🎉",
    "Jeder zahlt 50%" to "Semua orang membayar 50%",
    "Junge" to "budak lelaki",
    "Kamin" to "cerobong asap",
    "Karriere & Erfolg" to "Kerjaya & Kejayaan",
    "Kategorien" to "Kategori",
    "Katze" to "Kucing",
    "Keine Musik" to "Tiada muzik",
    "Keine Party nötig, privat halten" to "Tidak perlu parti, rahsiakan",
    "Keine Privatsphäre" to "Tiada privasi",
    "Keine Treffer gefunden" to "Tiada hasil ditemui",
    "Keiner" to "tiada",
    "Keiner von uns" to "Tiada seorang pun daripada kita",
    "Kennst du die Essensvorlieben deines Partners?" to "Adakah anda tahu pilihan makanan pasangan anda?",
    "Kino" to "pawagam",
    "Kirchlich" to "Eklesiastik",
    "Klassisch Solitär" to "solitaire klasik",
    "Klassisch gebunden" to "Terikat secara klasik",
    "Klein & zart" to "Kecil & halus",
    "Kleine Geschenke" to "Hadiah kecil",
    "Kleine Runde" to "Bulat kecil",
    "Kochen und Freunde einladen" to "Masak dan ajak kawan-kawan",
    "Kochkurs" to "Kelas memasak",
    "Kommt auf den Tag an" to "Bergantung pada hari",
    "Kommt darauf an" to "Bergantung pada",
    "Kommt drauf an" to "Ia bergantung",
    "Kommt mit" to "Jom ikut saya",
    "Konzert" to "konsert",
    "Kräftige Farben" to "Warna yang kuat",
    "Kräuterbeet" to "Katil herba",
    "Kultur & Sehenswürdigkeiten" to "Budaya & Pemandangan",
    "Kuscheln" to "Peluk",
    "Kuss senden" to "Hantar ciuman",
    "Körperliche Annäherung" to "Pendekatan fizikal",
    "Körperliche Nähe" to "Keakraban fizikal",
    "Küche" to "Dapur",
    "Land" to "negara",
    "Landhaus" to "rumah desa",
    "Landhausstil" to "Gaya desa",
    "Lange wach bleiben" to "Berjaga lewat",
    "Lappland" to "Lapland",
    "Lappland, Finnland" to "Lapland, Finland",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Biarkan pasangan anda memberi inspirasi kepada anda untuk menjadi diri anda yang terbaik",
    "Lehne ab" to "Tolak",
    "Leichtigkeit" to "memudahkan",
    "Leidenschaft" to "Keghairahan",
    "Liebe im Gleichgewicht" to "Cinta dalam keseimbangan",
    "Liebe sie, macht mehr Spaß" to "Sayangi mereka, lebih seronok",
    "Lieber durchgeplant oder spontan?" to "Adakah anda lebih suka melakukannya secara terancang atau spontan?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Adakah anda lebih suka mempunyai malam yang tenang untuk dua orang atau bersama orang ramai?",
    "Lieber nicht" to "Sebaliknya tidak",
    "Lieber vorher grob absprechen" to "Lebih baik bincang secara kasar terlebih dahulu",
    "Lokal einkaufen" to "Beli secara tempatan",
    "London" to "London",
    "London, England" to "London, England",
    "Lügen" to "Bohong",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Adakah anda lebih suka cadangan awam atau swasta?",
    "Malediven" to "Maldives",
    "Man sollte nie streitend einschlafen." to "Anda tidak boleh tertidur bertengkar.",
    "Mango Sorbet" to "Sorbet mangga",
    "Markant & breit" to "Menyerang & lebar",
    "Marken & Alltag" to "Jenama & kehidupan seharian",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "Halaman Mediterranean",
    "Mehr Unterstützung" to "Lagi sokongan",
    "Mehr gemeinsame Zeit" to "Lebih banyak masa bersama",
    "Mehr zuhören" to "Dengar lagi",
    "Mehrgenerationenhaus" to "Rumah pelbagai generasi",
    "Mein Arbeitsplatz" to "Tempat kerja saya",
    "Mein Partner" to "Pasangan saya",
    "Mich überraschen" to "Kejutkan saya",
    "Minimalistisches Interieur" to "Dalaman minimalis",
    "Missverständnisse" to "Salah faham",
    "Mit Familie und engen Freunden" to "Bersama keluarga dan kawan rapat",
    "Mit Kompromissen" to "Dengan kompromi",
    "Mitgefühl" to "belas kasihan",
    "Mittelweg mit besonderen Details" to "Jalan tengah dengan butiran istimewa",
    "Modern geometrisch" to "Geometrik moden",
    "Moderne Grillstation" to "Stesen gril moden",
    "Moderner Name" to "Nama moden",
    "Moderner Solitär" to "solitaire moden",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "Abadikan detik ini",
    "Momente" to "detik-detik",
    "Monaco" to "Monaco",
    "Moralische Werte" to "Nilai moral",
    "Museum" to "muzium",
    "Musik" to "Muzik",
    "Mut" to "keberanian",
    "Mädchen" to "perempuan",
    "Möbelhaus" to "Kedai perabot",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Adakah anda benar-benar mahu meninggalkan kuiz? Kemajuan anda sebelum ini kekal disimpan.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Adakah anda mahu haiwan peliharaan dimasukkan ke dalam aplikasi?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Mahukan detik itu dikongsi di media sosial serta-merta?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Kita mungkin perlu membuat simpanan",
    "Müssen es planen" to "Kena rancang",
    "Müssen sparen" to "Perlu berjimat",
    "Nachricht an" to "Mesej kepada",
    "Name Partnerin" to "Nama pasangan",
    "Namen und Startdatum eurer Beziehung." to "Nama dan tarikh mula perhubungan anda.",
    "Natursteinfassade" to "Fasad batu semula jadi",
    "Naturteich" to "Kolam semula jadi",
    "Nein, einfach halten" to "Tidak, pegang sahaja",
    "Nein, erstmal privat halten" to "Tidak, rahsiakannya buat masa ini",
    "Nein, lieber vor Ort" to "Tidak, lebih baik di tapak",
    "Nein, modern halten" to "Tidak, kekalkan ia moden",
    "Nein, nur wir" to "Tidak, hanya kami",
    "Nein, zu ablenkend" to "Tidak, terlalu mengganggu",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Bangunan baharu dengan rumah pintar",
    "Neubau mit Technik" to "Bangunan baharu dengan teknologi",
    "Neue Liebe, neue Erfahrungen" to "Cinta baharu, pengalaman baharu",
    "Neues Hobby" to "hobi baru",
    "Neues Spiel" to "Permainan baru",
    "Neugier" to "rasa ingin tahu",
    "New York" to "New York",
    "New York, USA" to "New York, Amerika Syarikat",
    "Nicht mein Fall" to "Bukan kes saya",
    "Nicht nötig, lieber klassisch bleiben" to "Tidak perlu, lebih baik kekal klasik",
    "Nichts — es passt so" to "Tiada apa-apa - ia sesuai seperti itu",
    "Nie wieder Burger" to "Tidak pernah lagi burger",
    "Nie wieder Pizza" to "Tidak pernah pizza lagi",
    "Niemand" to "tiada sesiapa",
    "Niemand ohne Plan" to "Tiada siapa tanpa rancangan",
    "Nike" to "Nike",
    "Nizza" to "bagus",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Tiada detik lagi.\nAbadikan pengalaman pertama anda 💞",
    "Nur bei wichtigen Themen" to "Hanya pada topik penting",
    "Nur wir beide" to "Hanya kami berdua",
    "Nähe & Intimität" to "Keakraban & keintiman",
    "Obstgarten" to "kebun buah",
    "Oder" to "Ataupun",
    "Offene Küche" to "Dapur terbuka",
    "Offene Wohnküche" to "Dapur terbuka/ruang tamu",
    "Ohne Stein" to "Tanpa batu",
    "Open End" to "Pengakhiran terbuka",
    "Outdoor-Küche" to "Dapur luar",
    "Outdoor-Sofa" to "Sofa luar",
    "Outdoor-Whirlpool" to "Tab mandi panas luar",
    "Ovaler Diamant" to "Berlian bujur",
    "Paar" to "berpasangan",
    "Paar-Statistiken" to "Statistik Berpasangan",
    "Paris" to "Paris",
    "Paris, Frankreich" to "Paris, Perancis",
    "Partner" to "pasangan",
    "Partner-Simulator" to "Simulator rakan kongsi",
    "Partnerin" to "pasangan",
    "Party Edition" to "Edisi parti",
    "Party Edition II" to "Parti Edisi II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Adakah haiwan sesuai dengan kehidupan seharian kita?",
    "Pasta" to "pasta",
    "Pastell" to "Pastel",
    "Penthouse mit Ausblick" to "Penthouse dengan pemandangan",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pergola dengan ruang istirahat",
    "Pfingstrosen" to "Peonies",
    "Pinguin" to "penguin",
    "Pistazie" to "pistachio",
    "Pizza" to "piza",
    "Pizzaofen" to "Ketuhar pizza",
    "Platin" to "platinum",
    "PlayStation" to "PlayStation",
    "Pool" to "kolam",
    "Pop" to "pop",
    "Prasselnder Kamin" to "Perapian menderu",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Puteri, Lanun dan Debu Peri: Kuiz Disney",
    "Privater Innenhof" to "Halaman peribadi",
    "Profil" to "profil",
    "Profil bearbeiten" to "Edit profil",
    "Prozentual nach Einkommen" to "Peratusan berdasarkan pendapatan",
    "Quiz verlassen" to "Tinggalkan kuiz",
    "Quiz verlassen?" to "Berhenti kuiz?",
    "Rausgehen in die Natur" to "Keluar ke alam semula jadi",
    "Reden vor ..." to "Ucapan di hadapan...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Jadualkan tarikh atau masa biasa bersama-sama",
    "Reisen" to "Perjalanan",
    "Reiseziele" to "Destinasi",
    "Respektlosigkeit" to "tidak hormat",
    "Restaurant" to "restoran",
    "RnB / Soul" to "RnB/Jiwa",
    "Rock" to "batu",
    "Rom" to "Rom",
    "Rom, Italien" to "Rom, Itali",
    "Romantik" to "percintaan",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Gerak isyarat romantis seperti mesej, nota atau hadiah membuatkan saya gembira.",
    "Romantische Stimmung" to "Mood romantik",
    "Roségold" to "Mawar emas",
    "Ruhig zu zweit" to "Sunyi untuk dua orang",
    "Runder Diamant" to "Berlian bulat",
    "Salted Caramel" to "karamel masin",
    "Sammle Ideen..." to "Kumpul idea...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Greece",
    "Saphir" to "nilam",
    "Saunahaus" to "Rumah sauna",
    "Schickes Restaurant oder Hotel" to "Restoran atau hotel yang bergaya",
    "Schlafzimmer" to "bilik tidur",
    "Schließen" to "tutup",
    "Schmal & zart" to "Langsing & halus",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Gambar dari kisah cinta kami",
    "Schokolade" to "coklat",
    "Schreib frei, was dir wirklich dazu einfällt." to "Tulis secara bebas apa yang benar-benar terlintas di fikiran.",
    "Schreibe deine eigene Antwort" to "Tulis jawapan anda sendiri",
    "Sehr gerne" to "sangat gembira",
    "Sehr leicht" to "Sangat ringan",
    "Sehr wichtig — Fotos und Video" to "Sangat penting — foto dan video",
    "Sehr wichtig, es sollte persönlich sein" to "Sangat penting, ia harus bersifat peribadi",
    "Selbst kochen" to "Masak sendiri",
    "Senden" to "Hantar",
    "Separate Küche" to "Dapur berasingan",
    "Serie schauen" to "Tonton siri",
    "Serienmarathon auf dem Sofa" to "Siri maraton di atas sofa",
    "Sex & Liebe" to "Seks & Cinta",
    "Seychellen" to "Seychelles",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Adakah kita mampu untuk menampung semua kos untuk seorang anak/berbilang anak? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Adakah cadangan itu patut mengejutkan?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Sekiranya aplikasi itu mengandungi unsur budaya atau tradisional?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Sekiranya aplikasi itu mengandungi unsur budaya atau tradisional?",
    "Sommerhochzeit" to "Perkahwinan musim panas",
    "Sonnige Dachterrasse" to "Teres bumbung yang cerah",
    "Sowohl als auch" to "Serta",
    "Spazieren" to "Bersiar-siar",
    "Spaß & Abenteuer" to "Keseronokan & Pengembaraan",
    "Speichern" to "Jimat",
    "Spiel bearbeiten" to "Edit permainan",
    "Spielbereich für Kinder" to "Kawasan permainan untuk kanak-kanak",
    "Spiele" to "permainan",
    "Spiele spielen und Spaß haben" to "Main permainan dan berseronok",
    "Spontan" to "Spontan",
    "Sportplatz" to "Padang sukan",
    "Spotify" to "Spotify",
    "Sprache" to "Bahasa",
    "Stadt" to "Bandar",
    "Stadt oder Land — was ist uns wichtiger?" to "Bandar atau negara – apakah yang lebih penting bagi kami?",
    "Stadtvilla" to "Vila bandar",
    "Standesamt & Party" to "Pejabat pendaftaran & parti",
    "Statement-Ring" to "Cincin kenyataan",
    "Stilvolles Outdoor-Sofa" to "Sofa luar yang bergaya",
    "Stimme voll zu" to "Setuju sangat",
    "Stimmt" to "betul",
    "Stimmt nicht" to "Tidak benar",
    "Stimmt, noch nie" to "Betul, tidak pernah",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Hari pantai",
    "Streit über Haushalt" to "Pertikaian tentang rumah tangga",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "berterusan",
    "Suche schließen" to "Tutup carian",
    "Suche zurücksetzen" to "Tetapkan semula carian",
    "Suche öffnen" to "Buka carian",
    "Suchergebnisse" to "Hasil carian",
    "Sushi" to "Sushi",
    "Süß" to "manis",
    "Tage zusammen 💞" to "Hari bersama 💞",
    "Tauche ins Unterbewusstsein" to "Menyelam ke alam bawah sedar",
    "Teile alle deine Hobbys mit deinem Partner" to "Kongsi semua hobi anda dengan pasangan anda",
    "Teils teils" to "Sebahagian sebahagiannya",
    "Testen" to "Ujian",
    "Themen" to "Topik",
    "Tiefe Gespräche" to "Perbualan yang mendalam",
    "Tiefgründige Gespräche führen" to "Mempunyai perbualan yang mendalam",
    "Tierpension" to "Kemudahan asrama haiwan",
    "Tiny House" to "rumah kecik",
    "Tippen zum Auswählen & Scrollen" to "Ketik untuk memilih & tatal",
    "Tippen zum Zuklappen" to "Ketik untuk runtuh",
    "Titel" to "tajuk",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Tajuk, Kategori, Topik, Tag, Soalan...",
    "Tokyo, Japan" to "Tokyo, Jepun",
    "Traditioneller Name" to "Nama tradisional",
    "Traumhaus Außenbereich" to "Kawasan luar rumah idaman",
    "Traumhochzeit" to "Perkahwinan impian",
    "Treffer" to "Pukul",
    "Tägliche Aktivität" to "Aktiviti harian",
    "Umformulieren" to "Ungkapan semula",
    "Unbeantwortet" to "Tidak dijawab",
    "Unbeliebte Meinungen" to "Pendapat yang tidak popular",
    "Universal Studios Genie oder Neuling?" to "Universal Studios genius atau baru?",
    "Uns auseinanderzuleben" to "Untuk berkembang terpisah",
    "Unser Intimleben" to "Kehidupan intim kami",
    "Unser Traumhaus" to "Rumah idaman kami",
    "Unser erstes Treffen" to "Pertemuan pertama kami",
    "Unsere Gesichter" to "muka kita",
    "Unsere eigenen Träume" to "Impian kita sendiri",
    "Unsere nächste Reise" to "Perjalanan kami seterusnya",
    "Unter 1000" to "Bawah 1000",
    "Unter 1000 im Monat" to "Bawah 1000 sebulan",
    "Unter 50€/Monat" to "Bawah 50€/bulan",
    "Unter Leuten" to "Di kalangan manusia",
    "Untreue" to "perselingkuhan",
    "Urlaub" to "bercuti",
    "Vanille" to "Vanila",
    "Venedig" to "Venice",
    "Venedig, Italien" to "Venice, Itali",
    "Verbinde dich mit" to "Berhubung dengan",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Sambung ke \${profile.partnerName} untuk melihat jawapannya",
    "Verbindung" to "sambungan",
    "Verbringe die Feiertage mit deiner Familie" to "Luangkan masa cuti bersama keluarga anda",
    "Verlobungsringe" to "Cincin pertunangan",
    "Vertrautheit" to "Keakraban",
    "Viel getrennt" to "Banyak perpisahan",
    "Vielleicht ein oder zwei" to "Mungkin satu atau dua",
    "Vielleicht, aber mündlich reicht" to "Mungkin, tetapi secara lisan sudah memadai",
    "Vielleicht, wenn es machbar ist" to "Mungkin, jika ia boleh dilaksanakan",
    "Vielleicht, wenn es passt" to "Mungkin, jika ia sesuai",
    "Vintage Art déco" to "Art Deco Vintaj",
    "Vintage verspielt" to "Vintaj suka bermain",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Diperkenalkan kepada hobi baru oleh pasangan anda",
    "Vor dem Kauf eines Hauses besprechen" to "Berbincang sebelum membeli rumah",
    "Vor der Anschaffung eines Haustiers besprechen" to "Berbincang sebelum membeli haiwan peliharaan",
    "Vor der gemeinsamen Reise besprechen" to "Berbincang sebelum melancong bersama",
    "Vor nichts" to "Tiada apa-apa",
    "Vorort" to "pinggir bandar",
    "Walnuss" to "kenari",
    "Wandern" to "Kenaikan",
    "Wann fühlst du dich mir am nächsten?" to "Bila awak rasa paling dekat dengan saya?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Bilakah anda berasa paling dekat dengan saya?",
    "Was bedeutet Vertrauen für dich konkret?" to "Apakah erti kepercayaan kepada anda secara khusus?",
    "Was entspannt dich mehr?" to "Apa yang lebih melegakan anda?",
    "Was fehlt dir über die Distanz am meisten?" to "Apa yang paling anda rindui tentang jarak?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Apa yang paling anda suka tentang rumah anda?",
    "Was hast du von deinem Partner gelernt?" to "Apa yang anda pelajari daripada pasangan anda?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Apakah pendapat anda tentang menonton kandungan erotik bersama-sama?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Apakah pendapat anda tentang prop (cth. papan tanda, belon, dll.)?",
    "Was ist das Wichtigste beim Antrag?" to "Apakah perkara yang paling penting semasa memohon?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Apakah perkara paling penting yang anda cari dalam pertemuan seksual?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Apakah foto kegemaran anda tentang kami? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Apakah ketakutan terbesar anda tentang hidup bersama?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Apakah makanan yang anda suka tetapi pasangan anda tidak faham?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Apakah pemecah perjanjian mutlak untuk anda?",
    "Was ist für jeden von uns das absolute Highlight?" to "Apakah sorotan mutlak bagi setiap daripada kita?",
    "Was ist passiert?" to "Apa yang berlaku?",
    "Was macht einen Moment für dich romantisch?" to "Apa yang menjadikan momen romantis untuk anda?",
    "Was magst du an deinem Partner am liebsten?" to "Apa yang paling anda suka tentang pasangan anda?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Apa yang anda lebih suka: bangun awal atau berjaga lewat?",
    "Was magst du lieber?" to "Apa yang anda lebih suka?",
    "Was möchtest du eigentlich sagen?" to "Apa yang awak nak cakap sebenarnya?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Apakah yang anda mahu pasangan anda lakukan lebih kerap?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Apakah yang berlaku kepada haiwan itu apabila kita mengembara?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Apa akan jadi dengan anak kita apabila dia besar nanti?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Apa yang tidak boleh kita lupakan sebagai ibu bapa?",
    "Was war dein schönster Moment mit mir bisher?" to "Apakah saat terbaik anda bersama saya setakat ini?",
    "Was wir gegessen haben" to "Apa yang kami makan",
    "Was wollt ihr nie vergessen?" to "Apa yang anda tidak mahu lupakan?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Apa yang lebih teruk untuk anda: jangan makan pizza lagi atau jangan makan burger lagi?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Apa yang paling anda ingin lakukan pada hari bersama?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Apakah yang akan anda ubah serta-merta jika wang tidak menjadi isu?",
    "Weiter" to "Selanjutnya",
    "Weiter spielen" to "Teruskan bermain",
    "Weiß ich noch nicht" to "Saya tidak tahu lagi",
    "Weiße Rosen" to "Mawar putih",
    "Weißgold" to "emas putih",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Apakah kualiti yang pasti anak kita perolehi daripada kita?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Persekitaran apa yang anda mahukan untuk cadangan?",
    "Welcher Raum sagt am meisten über dich aus?" to "Bilik manakah yang paling banyak menceritakan tentang anda?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Berapa bajet yang kita rancang untuk makanan dan doktor haiwan?",
    "Welches Lied macht dich an? 🥵" to "Lagu manakah yang menghidupkan anda? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Foto bersama yang manakah kegemaran anda?",
    "Wellnessbad" to "Mandian kesihatan",
    "Wenn es schwierig ist" to "Apabila keadaan sukar",
    "Wenn ich müde bin" to "Bila dah penat",
    "Wenn wir uns lange umarmen" to "Apabila kita berpelukan lama",
    "Wenn wir zusammen lachen" to "Apabila kita ketawa bersama",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Siapa yang memutuskan dengan lebih cepat apa yang hendak dipesan?",
    "Wer findet die besten Restaurants?" to "Siapa yang mencari restoran terbaik?",
    "Wer gibt mehr Herzlichkeit?" to "Siapa yang memberi lebih kehangatan?",
    "Wer hat den besseren Musikgeschmack?" to "Siapa yang mempunyai cita rasa yang lebih baik dalam muzik?",
    "Wer hängt mehr an seinen Eltern?" to "Siapa yang lebih menyayangi ibu bapa mereka?",
    "Wer ist besser organisiert?" to "Siapa yang lebih teratur?",
    "Wer ist der Beste bei der Filmauswahl?" to "Siapa yang paling pandai memilih filem?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Siapa yang paling pandai merancang tarikh romantis?",
    "Wer ist der beste Tänzer?" to "Siapa penari terbaik?",
    "Wer ist romantischer?" to "Siapa yang lebih romantik?",
    "Wer kocht besser?" to "Siapa yang pandai memasak?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Siapa yang menjaga pengubahsuaian dan penyelenggaraan?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Siapa yang lebih cepat perasan apabila orang lain tidak sihat?",
    "Wer sucht am Ende wirklich den Film aus?" to "Siapa sebenarnya yang memilih filem itu pada akhirnya?",
    "Wer vergisst eher einen Jahrestag?" to "Siapa yang lebih cenderung untuk melupakan ulang tahun?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Siapakah yang lebih cenderung untuk melupakan nama mereka sendiri pada keesokan harinya?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Siapa yang lebih berkemungkinan mencari video pada hari berikutnya yang mereka tidak tahu apa-apa?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Siapa yang lebih suka bermalam di sofa orang yang tidak dikenali?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Siapa yang lebih cenderung tertidur di pesta dan bangun dengan wajah Sharpie?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Siapa yang lebih berkemungkinan tergelincir di lantai tarian tetapi menjadikannya kelihatan seperti gerakan yang menarik?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Siapa yang lebih cenderung untuk mengawal senarai main Spotify di pesta rumah?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Siapa yang lebih cenderung untuk memesan pizza untuk semua orang di pesta dan memakannya sendiri?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Siapa yang lebih cenderung untuk tidur terlebih dahulu di pesta?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Siapa yang lebih berkemungkinan tiba-tiba mula membersihkan diri di pesta?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Siapakah yang lebih berkemungkinan mendakwa dirinya benar-benar sedar sedangkan sebaliknya adalah benar?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Siapa yang lebih cenderung mengalah dahulu dalam pertengkaran?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Siapa yang lebih cenderung untuk menipu dalam permainan minum?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Siapakah yang lebih berkemungkinan menyerbu bufet dan membawa pulang makanan secara rahsia?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Siapa yang lebih cenderung untuk menyiarkan foto yang paling memalukan pada malam itu dalam cerita mereka?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Siapa yang lebih cenderung untuk mengganggu DJ untuk meminta lagu kegemaran mereka sendiri?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Siapakah yang lebih berkemungkinan menyanyikan lirik lagu di luar kekunci, tetapi dengan keyakinan?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Siapa yang lebih cenderung untuk memesan minuman paling mahal pada menu dan menyesalinya?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Siapakah yang lebih berkemungkinan akan menjemput jiran-jiran jika mereka mengadu tentang bunyi bising itu?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Siapa yang lebih cenderung untuk mengambil permainan parti (seperti beer pong) terlalu serius?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Siapa yang lebih berkemungkinan berkawan dengan bouncer untuk mendapatkan akses VIP?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Siapa yang lebih cenderung untuk memulakan pertempuran karaoke dadakan?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Siapa yang lebih cenderung untuk membuka botol tanpa menggunakan pembuka botol?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Siapa yang lebih berkemungkinan untuk berucap walaupun langsung tidak ada yang bertanya?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Siapa yang lebih berkemungkinan menghabiskan satu jam di dalam bilik air untuk mengambil gambar diri sendiri?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Siapa yang lebih cenderung untuk membuat persembahan tarian yang memalukan dan meraikannya?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Siapakah yang lebih berkemungkinan untuk menghubungi bekas rakan kongsi selepas parti itu tamat?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Siapakah yang lebih berkemungkinan menyinggung perasaan tetamu aneh secara tidak sengaja?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Siapakah yang lebih berkemungkinan meninggalkan parti secara rahsia tanpa mengucapkan selamat tinggal?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Siapa yang lebih suka bermain dengan haiwan peliharaan tuan rumah daripada bercakap dengan tetamu?",
    "Wer würde eher spontan eine Reise buchen?" to "Siapa yang lebih cenderung untuk menempah perjalanan secara spontan?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Siapakah yang lebih berkemungkinan melakukan perbualan yang mendalam di dapur selama berjam-jam?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Siapa yang lebih berkemungkinan meminum minuman orang lain secara tidak sengaja?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Siapakah yang lebih berkemungkinan terlanggar pasu mahal atau sesuatu yang rapuh secara tidak sengaja?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Siapakah yang lebih berkemungkinan cuba mencampurkan sendiri koktel yang rumit dan gagal dengan teruk?",
    "Wer würde eher zu spät kommen?" to "Siapa yang lebih berkemungkinan lambat?",
    "Wer würde eher?" to "Siapa lebih suka?",
    "Wer übernimmt die tägliche Versorgung?" to "Siapa yang menjaga penjagaan harian?",
    "Werde so akzeptiert, wie du bist" to "Diterima seadanya",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Adakah kita mempunyai masa yang cukup untuk anak/anak? ⏳",
    "Whirlpool" to "Jakuzi",
    "White Chocolate" to "coklat putih",
    "Widgets" to "Widget",
    "Wie fühlst du dich am meisten geliebt?" to "Bagaimana perasaan anda paling disayangi?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Bagaimana kita menangani pendapatan yang berbeza?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Apakah cara terbaik untuk pasangan anda memulakan hubungan seks dengan anda?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Bagaimanakah pasangan anda boleh menjadi pasangan yang lebih baik untuk anda?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Berapa lama selepas cadangan itu anda mahu meraikan dengan orang lain?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Berapa lama kita mahu tinggal di sana sekurang-kurangnya?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Betapa mudahnya untuk anda bercakap tentang hasrat?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Apa yang anda mahukan masa depan kita?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Apakah rupa Ahad anda yang sempurna di rumah?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Apakah perasaan anda tentang bercakap kotor semasa hubungan seks?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Berapa banyak kredit yang kita mampu secara realistik?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Berapa banyak masa yang kita mahu luangkan?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Berapakah jumlah yang kita mahu belanjakan?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Bagaimanakah kita akan mencari masa untuk hubungan kita sebaik sahaja bayi itu datang?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Seberapa penting bagi anda bahawa detik itu dirakamkan?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Sejauh manakah pentingnya bagi anda bahawa permohonan itu mencerminkan hobi atau minat anda?",
    "Wie würdest du sie/ihn nennen?" to "Apa yang anda akan panggil dia?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Apakah cara kegemaran anda untuk menunjukkan kasih sayang di luar seks?",
    "Wildblumen" to "Bunga liar",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Adakah anda mahu perempuan atau lelaki? 👶",
    "Wintergarten" to "Taman musim sejuk",
    "Winterhochzeit" to "Perkahwinan musim sejuk",
    "Wir bestellen einfach beides" to "Kami hanya memesan kedua-duanya",
    "Wir brauchen ewig" to "Ia membawa kita selama-lamanya",
    "Wir einigen uns nie" to "Kami tidak pernah bersetuju",
    "Wir entscheiden es gemeinsam" to "Kita putuskan bersama",
    "Wir treffen uns in der Mitte" to "Kita jumpa di tengah-tengah",
    "Wir wechseln uns ab" to "Kami bergilir-gilir",
    "Wird stressig" to "Menjadi tertekan",
    "Wobei lachst du am meisten?" to "Apa yang paling membuatkan anda ketawa?",
    "Wofür sparen wir gemeinsam?" to "Untuk apa kita simpan bersama?",
    "Wohnzimmer" to "ruang tamu",
    "Woran erinnerst du dich am lebhaftesten?" to "Apakah yang anda ingat dengan jelas?",
    "Worauf freust du dich bei uns am meisten?" to "Apa yang paling anda nantikan bersama kami?",
    "Worte/Komplimente" to "Kata-kata/pujian",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Apa yang paling awak takutkan dalam hubungan kita?",
    "Wünsche? z.B. günstig, draußen" to "Keinginan? cth. murah, luar",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Adakah anda lebih suka melamar bercuti (melibatkan perjalanan)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube Music",
    "Zeichne für mich" to "Lukis untuk saya",
    "Zeichne mich als Tier — welches wäre ich?" to "Lukiskan saya sebagai haiwan - apakah saya?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Lukiskan perasaan kita terhadap satu sama lain sebagai simbol.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Lukis rumah idaman kita dalam satu baris. Apakah perkara yang paling menarik?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Lukis tarikh pertama kita - apa yang pasti perlu ada dalam gambar?",
    "Zeichnen" to "Lukis",
    "Zeit füreinander" to "Masa untuk satu sama lain",
    "Zeit, wenn das Baby schläft" to "Masa apabila bayi tidur",
    "Zelten gehen" to "Pergi berkhemah",
    "Zitrone" to "limau",
    "Zu Hause, gemütlich und privat" to "Di rumah, selesa dan peribadi",
    "Zu einem Picknick gehen" to "Pergi berkelah",
    "Zu einem ausgefallenen Abendessen gehen" to "Pergi makan malam mewah",
    "Zu zweit reisen" to "Perjalanan sebagai pasangan",
    "Zuhause & Alltag" to "Rumah & kehidupan seharian",
    "Zuhören" to "Dengar",
    "Zurück" to "belakang",
    "Zusammen seit" to "Bersama sejak",
    "Zusammen seit (TT.MM.JJJJ)" to "Bersama-sama sejak (DD.MM.YYYY)",
    "Zusammenziehen" to "Berkontrak",
    "Zustimmen oder Ablehnen" to "Setuju atau tolak",
    "Zwei Kreise, die sich überschneiden" to "Dua bulatan yang bertindih",
    "Zwei Stühle davor" to "Dua kerusi di hadapannya",
    "Zärtlich sein" to "Jadilah lembut",
    "Öfter als ich zugebe" to "Lebih kerap daripada yang saya akui",
    "Über 100€/Monat" to "Lebih 100€/bulan",
    "Über 2000 im Monat" to "Lebih 2000 sebulan",
    "Über mich selbst" to "Tentang diri saya",
    "Übernehmen" to "ambil alih",
    "Überraschend" to "Mengejutkan",
    "Überraschung" to "Kejutan",
    "Überspringen" to "Langkau",
    "Übertrieben und großartig" to "Over the top dan hebat",
    "✎ Tippe, um zu antworten" to "✎ Ketik untuk membalas",
    "✨ GFK-Brücke" to "✨ Jambatan GRP",
)

internal fun localizeMalayDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_MALAY_CONTENT)
