package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_MALAYALAM_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 വർഷം",
    "1000 - 1500 im Monat" to "പ്രതിമാസം 1000 - 1500",
    "1000 bis 3000" to "1000 മുതൽ 3000 വരെ",
    "1500 - 2000 im Monat" to "പ്രതിമാസം 1500 - 2000",
    "3000 bis 5000" to "3000 മുതൽ 5000 വരെ",
    "5-10 Jahre" to "5-10 വർഷം",
    "50-100€/Monat" to "50-100€/മാസം",
    "Ab 100€" to "100€ മുതൽ",
    "Ab 500€" to "500€ മുതൽ",
    "Ab 50€" to "50€ മുതൽ",
    "Ab und zu" to "ഇടയ്ക്കിടെ",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "ഒരു വാങ്ങൽ നടത്തുന്നതിന് മുമ്പ് നമ്മൾ എത്രമാത്രം ചെലവഴിക്കണം?",
    "Abbrechen" to "റദ്ദാക്കുക",
    "Abenteuer" to "സാഹസികത",
    "Adidas" to "അഡിഡാസ്",
    "Aktivitäten" to "പ്രവർത്തനങ്ങൾ",
    "Alle" to "എല്ലാം",
    "Alle Pakete" to "എല്ലാ പാക്കേജുകളും",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "നിങ്ങളുടെ ഉറ്റ ചങ്ങാതി ഒഴികെ എല്ലാ സുഹൃത്തുക്കളെയും നഷ്‌ടപ്പെടുത്തുക",
    "Alle intimen Momente selbst initiieren" to "എല്ലാ അടുപ്പമുള്ള നിമിഷങ്ങളും സ്വയം ആരംഭിക്കുക",
    "Alles davon" to "എല്ലാം",
    "Alles, was noch kommt" to "വരാനിരിക്കുന്നതെല്ലാം",
    "Alltagsroutine" to "ദൈനംദിന ദിനചര്യ",
    "Alltägliche Berührungen" to "ദൈനംദിന സ്പർശനങ്ങൾ",
    "Altbau mit Charme" to "ആകർഷകമായ പഴയ കെട്ടിടം",
    "Am Strand" to "കടൽത്തീരത്ത്",
    "Am liebsten alles zusammen" to "വെയിലത്ത് എല്ലാം ഒരുമിച്ച്",
    "Am selben Tag mit Freunden/Familie" to "സുഹൃത്തുക്കൾ/കുടുംബത്തോടൊപ്പം ഒരേ ദിവസം",
    "Amazon" to "ആമസോൺ",
    "Amsterdam" to "ആംസ്റ്റർഡാം",
    "Amsterdam, Niederlande" to "ആംസ്റ്റർഡാം, നെതർലാൻഡ്സ്",
    "An das Gefühl" to "വികാരത്തിൻ്റെ",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "ധാരാളം കാണികളുള്ള ഒരു പൊതു സ്ഥലത്ത്",
    "An einen Geruch" to "ഒരു മണം",
    "An einen Song" to "ഒരു പാട്ടിലേക്ക്",
    "An etwas, das ich gesagt habe" to "ഞാൻ എന്തോ പറഞ്ഞു",
    "Analyse starten" to "വിശകലനം ആരംഭിക്കുക",
    "Analysiere eure Muster..." to "നിങ്ങളുടെ പാറ്റേണുകൾ വിശകലനം ചെയ്യുക...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Gottman, GFK എന്നിവ പ്രകാരം നിങ്ങളുടെ ഉത്തരങ്ങളും ചാറ്റുകളും വിശകലനം ചെയ്യുക.",
    "Ananas auf der Pizza schmeckt köstlich." to "പിസ്സയിലെ പൈനാപ്പിൾ സ്വാദിഷ്ടമാണ്.",
    "Android" to "ആൻഡ്രോയിഡ്",
    "Antwort mit einem Foto" to "ഒരു ഫോട്ടോ സഹിതം മറുപടി നൽകുക",
    "Antwortähnlichkeit" to "സമാനതയ്ക്ക് ഉത്തരം നൽകുക",
    "App-Sprache auswählen" to "ആപ്പ് ഭാഷ തിരഞ്ഞെടുക്കുക",
    "Auf eine Bootsparty gehen" to "ഒരു ബോട്ട് പാർട്ടിക്ക് പോകുന്നു",
    "Aufmerksamkeit" to "ശ്രദ്ധ",
    "Aufräumen und Projekte angehen" to "പ്രോജക്‌റ്റുകൾ വൃത്തിയാക്കുകയും കൈകാര്യം ചെയ്യുകയും ചെയ്യുക",
    "Aufwärmen" to "ചൂടാക്കുക",
    "Aufwärmen: Einander kennenlernen" to "വാം-അപ്പ്: പരസ്പരം അറിയുക",
    "Aus dem Urlaub" to "അവധിക്കാലം മുതൽ",
    "Ausgefallener Name" to "ഫാൻസി പേര്",
    "Ausschlafen und faulenzen" to "ഉറങ്ങുകയും അലസമായി ഇരിക്കുകയും ചെയ്യുക",
    "Ausschlafen und nichts tun" to "ഉറങ്ങുക, ഒന്നും ചെയ്യരുത്",
    "Aussehen" to "രൂപഭാവം",
    "Auto" to "ഓട്ടോ",
    "Außenkamin" to "ഔട്ട്‌ഡോർ അടുപ്പ്",
    "BEANTWORTE" to "ഉത്തരം",
    "Bali" to "ബാലി",
    "Bali, Indonesien" to "ബാലി, ഇന്തോനേഷ്യ",
    "Banane" to "വാഴപ്പഴം",
    "Beantwortet" to "ഉത്തരം നൽകി",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "ഒരേ സമയം ചോദ്യങ്ങൾക്ക് ഉത്തരം നൽകുക - നിങ്ങൾ രണ്ടുപേരും പൂർത്തിയാക്കുന്നത് വരെ ഉത്തരങ്ങൾ ദൃശ്യമാകില്ല.",
    "Beantwortete Fragen" to "ചോദ്യങ്ങൾക്ക് ഉത്തരം നൽകി",
    "Bearbeiten" to "എഡിറ്റ് ചെയ്യുക",
    "Bei Insider-Witzen" to "ഉള്ളിലെ തമാശകളോടെ",
    "Bei Memes" to "മെമ്മുകളിൽ",
    "Bei einer spontanen Berührung" to "സ്വതസിദ്ധമായ ഒരു സ്പർശനത്തോടെ",
    "Beide" to "രണ്ടും",
    "Beide gleich" to "രണ്ടും ഒന്നുതന്നെ",
    "Beide zusammen" to "രണ്ടും ഒരുമിച്ച്",
    "Beide, aber wir tun so als ob nicht" to "രണ്ടും, പക്ഷേ ഞങ്ങൾ നടിക്കുന്നില്ല",
    "Beides" to "രണ്ടും",
    "Beides wäre schlimm" to "രണ്ടും മോശമായിരിക്കും",
    "Beim Einschlafen nebeneinander" to "പരസ്പരം അടുത്ത് ഉറങ്ങുന്നു",
    "Beim Reden" to "സംസാരിക്കുന്നതിനിടയിൽ",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "പ്രശസ്തമായ വിനോദസഞ്ചാര കേന്ദ്രങ്ങൾ എപ്പോഴും നിരാശയാണ്.",
    "Beschreibe unser Sexleben mit einem Emoji." to "ഒരു ഇമോജി ഉപയോഗിച്ച് ഞങ്ങളുടെ ലൈംഗിക ജീവിതം വിവരിക്കുക.",
    "Besser kommunizieren" to "നന്നായി ആശയവിനിമയം നടത്തുക",
    "Bessere Lage" to "മെച്ചപ്പെട്ട സ്ഥാനം",
    "Bestellen" to "ഓർഡർ ചെയ്യുക",
    "Besuchte Länder" to "രാജ്യങ്ങൾ സന്ദർശിച്ചു",
    "Besuchte Städte" to "നഗരങ്ങൾ സന്ദർശിച്ചു",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "അതിരുകടന്ന നിർദ്ദേശമാണോ അതോ സൂക്ഷ്മമായ മറ്റെന്തെങ്കിലുമോ നിങ്ങൾ ഇഷ്ടപ്പെടുന്നത്?",
    "Beziehung" to "ബന്ധം",
    "Bibliothek" to "ലൈബ്രറി",
    "Bin manchmal unsicher" to "എനിക്ക് ചിലപ്പോൾ സുരക്ഷിതത്വമില്ല",
    "Bist du ein Videospiel-Guru?" to "നിങ്ങളൊരു വീഡിയോ ഗെയിം ഗുരു ആണോ?",
    "Blumenwiese" to "പുഷ്പ പുൽമേട്",
    "Bunte Blumenwiese" to "വർണ്ണാഭമായ പുൽമേട്",
    "Burger" to "ബർഗറുകൾ",
    "Burger King" to "ബർഗർ കിംഗ്",
    "Chat" to "ചാറ്റ്",
    "Coca-Cola" to "കൊക്ക കോള",
    "Cookie Dough" to "കുക്കി മാവ്",
    "Dachgarten mit Lounge" to "വിശ്രമമുറിയോടുകൂടിയ റൂഫ് ഗാർഡൻ",
    "Dachterrasse" to "റൂഫ് ടെറസ്",
    "Das Wetter an dem Tag" to "അന്നത്തെ കാലാവസ്ഥ",
    "Das erste Selfie" to "ആദ്യത്തെ സെൽഫി",
    "Das meiste weiß ich" to "എനിക്കതിൽ ഭൂരിഭാഗവും അറിയാം",
    "Das oder das?" to "ഇതോ അതോ?",
    "Das tägliche Leben" to "ദൈനംദിന ജീവിതം",
    "Dass Zusagen gehalten werden" to "ആ വാഗ്ദാനങ്ങൾ പാലിക്കപ്പെടുന്നു",
    "Dass alles meinen Stil hat" to "എല്ലാത്തിനും എൻ്റെ ശൈലിയുണ്ടെന്ന്",
    "Dass ich alles erzählen kann" to "എനിക്ക് എല്ലാം പറയാം",
    "Dass ich mich nicht sorgen muss" to "ഞാൻ വിഷമിക്കേണ്ടതില്ല",
    "Dass wir ungestört sind" to "ഞങ്ങൾ അസ്വസ്ഥരാണെന്ന്",
    "Dein Name" to "നിങ്ങളുടെ പേര്",
    "Deine Antwort..." to "നിങ്ങളുടെ ഉത്തരം...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "നിങ്ങളുടെ ഉത്തരങ്ങൾ സംരക്ഷിച്ചു. പങ്കാളി പാക്കേജ് പൂർത്തിയാക്കിയാലുടൻ, രണ്ട് ഉത്തരങ്ങളും ഒരുമിച്ച് ദൃശ്യമാകും.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "നിങ്ങളുടെ ഉത്തരങ്ങൾ സംരക്ഷിച്ചു. \${profile.partnerName} പാക്കേജ് പൂർത്തിയാക്കിയാൽ, രണ്ട് പ്രതികരണങ്ങളും ഒരുമിച്ച് ദൃശ്യമാകും.",
    "Deine Beziehung abenteuerlich und spontan machen" to "നിങ്ങളുടെ ബന്ധം സാഹസികവും സ്വതസിദ്ധവുമാക്കുക",
    "Deine Beziehung stabil und sicher machen" to "നിങ്ങളുടെ ബന്ധം സുസ്ഥിരവും സുരക്ഷിതവുമാക്കുക",
    "Deine eigene Antwort" to "നിങ്ങളുടെ സ്വന്തം ഉത്തരം",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "നിങ്ങളുടെ ആഴത്തിലുള്ള രഹസ്യങ്ങൾ പങ്കാളിയുമായി പങ്കിടുന്നതാണ് നല്ലത്",
    "Deinen besten Freund verlieren" to "നിങ്ങളുടെ ഉറ്റ സുഹൃത്തിനെ നഷ്ടപ്പെടുന്നു",
    "Denke an dich" to "സ്വയം ചിന്തിക്കുക",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "ഒരേ സിനിമ രണ്ടുതവണ കാണുന്നത് സമയം പാഴാക്കലാണ്.",
    "Der Blick nach draußen" to "പുറത്തെ കാഴ്ച",
    "Der Garten" to "പൂന്തോട്ടം",
    "Der Ort" to "സ്ഥലം",
    "Der Ring und die Geste" to "മോതിരവും ആംഗ്യവും",
    "Der perfekte Heiratsantrag" to "തികഞ്ഞ വിവാഹാലോചന",
    "Derjenige sein, der umarmt wird" to "ആലിംഗനം ചെയ്യപ്പെടുന്ന ആളായിരിക്കുക",
    "Deutsch" to "ജർമ്മൻ",
    "Diamant" to "വജ്രം",
    "Diamanten im Band" to "ബാൻഡിലെ വജ്രങ്ങൾ",
    "Die Distanz" to "ദൂരം",
    "Die Feiertage mit der Familie deines Partners verbringen" to "നിങ്ങളുടെ പങ്കാളിയുടെ കുടുംബത്തോടൊപ്പം അവധിക്കാലം ചെലവഴിക്കുക",
    "Die Gemütlichkeit und Ruhe" to "സുഖവും സമാധാനവും",
    "Die Menschen, die darin wohnen" to "അതിൽ താമസിക്കുന്ന ആളുകൾ",
    "Die Umgebung und Atmosphäre" to "പരിസ്ഥിതിയും അന്തരീക്ഷവും",
    "Die Worte und Emotionen" to "വാക്കുകളും വികാരങ്ങളും",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "ആത്യന്തിക വിനോദ ട്രിവിയ വെല്ലുവിളി",
    "Diejenige sein, die umarmt" to "ആലിംഗനം ചെയ്യുന്നവരായിരിക്കുക",
    "Direkt ansprechen" to "നേരിട്ട് വിലാസം",
    "Diskussion" to "ചർച്ച",
    "Diskutiere vor dem Kinderkriegen" to "കുട്ടികളുണ്ടാകുന്നതിന് മുമ്പ് ചർച്ച ചെയ്യുക",
    "Diskutiert eure Antworten" to "നിങ്ങളുടെ ഉത്തരങ്ങൾ ചർച്ച ചെയ്യുക",
    "Disney" to "ഡിസ്നി",
    "Doch, schon mal" to "അതെ, അതെ",
    "Draußen mit der Natur als Kulisse" to "പ്രകൃതിയെ പശ്ചാത്തലമാക്കി പുറത്ത്",
    "Drei-Stein-Ring" to "മൂന്ന് കല്ല് വളയം",
    "Du bist dran" to "ഇത് നിങ്ങളുടെ ഊഴമാണ്",
    "Du fehlst mir" to "ഞാൻ നിന്നെ മിസ്സ് ചെയ്യുന്നു",
    "Dubai" to "ദുബായ്",
    "Dubai, VAE" to "ദുബായ്, യു.എ.ഇ",
    "Dunkles Design" to "ഇരുണ്ട തീം",
    "Durch Berührung" to "സ്പർശനത്തിലൂടെ",
    "Durch Worte" to "വാക്കുകളിലൂടെ",
    "Durch Zeit zu zweit" to "ഒരുമിച്ചുള്ള സമയത്തിലൂടെ",
    "Durch kleine Gesten" to "ചെറിയ ആംഗ്യങ്ങളിലൂടെ",
    "Durchgeplant" to "നന്നായി ആസൂത്രണം ചെയ്തിട്ടുണ്ട്",
    "ERGEBNISSE" to "ഫലങ്ങൾ",
    "Egal, Hauptsache gesund" to "എന്തായാലും, പ്രധാന കാര്യം ആരോഗ്യകരമാണ്",
    "Ehepaar Leben" to "വിവാഹിത ദമ്പതികളുടെ ജീവിതം",
    "Eher knapp" to "പകരം അടുത്ത്",
    "Eher nicht" to "അത്രയല്ല",
    "Eher schwer" to "പകരം ബുദ്ധിമുട്ടാണ്",
    "Eher schwierig" to "പകരം ബുദ്ധിമുട്ടാണ്",
    "Eher zu" to "കൂടുതൽ ഇഷ്‌ടപ്പെടുന്നു",
    "Eifersucht ist ein Zeichen von Liebe." to "അസൂയ സ്നേഹത്തിൻ്റെ അടയാളമാണ്.",
    "Eigenes Gemüsebeet" to "സ്വന്തം പച്ചക്കറി പാച്ച്",
    "Ein Abenteuer in einer neuen Stadt" to "ഒരു പുതിയ നഗരത്തിലെ ഒരു സാഹസിക യാത്ര",
    "Ein Anker" to "ഒരു ആങ്കർ",
    "Ein Balkon oder Garten" to "ഒരു ബാൽക്കണി അല്ലെങ്കിൽ പൂന്തോട്ടം",
    "Ein Filmabend" to "ഒരു സിനിമാ രാത്രി",
    "Ein Harmony-Meilenstein eurer Liebe." to "നിങ്ങളുടെ സ്‌നേഹത്തിൻ്റെ ഒരു നാഴികക്കല്ല്.",
    "Ein Herz" to "ഒരു ഹൃദയം",
    "Ein Herz an der Tür" to "വാതിൽക്കൽ ഒരു ഹൃദയം",
    "Ein Jahr lang eine Fernbeziehung führen" to "ഒരു വർഷത്തേക്ക് ദീർഘദൂര ബന്ധം പുലർത്തുക",
    "Ein Kindheitsessen" to "കുട്ടിക്കാലത്തെ ഭക്ഷണം",
    "Ein Live-Musik-Konzert besuchen" to "ഒരു തത്സമയ സംഗീത കച്ചേരിയിൽ പങ്കെടുക്കുക",
    "Ein Museum besuchen" to "ഒരു മ്യൂസിയം സന്ദർശിക്കുക",
    "Ein Spieleabend" to "ഒരു ഗെയിം രാത്രി",
    "Ein Spieleabend mit Freunden" to "സുഹൃത്തുക്കളുമൊത്തുള്ള ഒരു ഗെയിം നൈറ്റ്",
    "Ein Urlaubsfoto" to "ഒരു അവധിക്കാല ഫോട്ടോ",
    "Ein aktives Abenteuer" to "ഒരു സജീവ സാഹസികത",
    "Ein entspannender Spa-Tag" to "വിശ്രമിക്കുന്ന ഒരു സ്പാ ദിനം",
    "Ein ganz normaler Alltagstag" to "തികച്ചും സാധാരണമായ ദൈനംദിന ദിനം",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "ഇടിമിന്നലുള്ള സമയത്ത് വീട്ടിൽ ഒരു സുഖകരമായ സായാഹ്നം",
    "Ein gemütliches Date drinnen" to "വീടിനുള്ളിൽ ഒരു സുഖകരമായ തീയതി",
    "Ein lustiges Bild" to "ഒരു തമാശ ചിത്രം",
    "Ein paar Handyfotos reichen" to "കുറച്ച് സെൽ ഫോൺ ഫോട്ടോകൾ മതി",
    "Ein paar Stunden" to "കുറച്ച് മണിക്കൂറുകൾ",
    "Ein paar kulturelle Anklänge sind okay" to "കുറച്ച് സാംസ്കാരിക പരാമർശങ്ങൾ ശരിയാണ്",
    "Ein romantischer Abend" to "ഒരു പ്രണയ സായാഹ്നം",
    "Ein romantisches Abendessen bei Kerzenlicht" to "ഒരു റൊമാൻ്റിക് മെഴുകുതിരി അത്താഴം",
    "Ein romantisches Bild" to "ഒരു റൊമാൻ്റിക് ചിത്രം",
    "Ein romantisches Picknick an einem schönen Ort" to "മനോഹരമായ ഒരു സ്ഥലത്ത് ഒരു റൊമാൻ്റിക് പിക്നിക്",
    "Ein schwerer Moment, den wir geschafft haben" to "ഞങ്ങൾ കൈകാര്യം ചെയ്ത പ്രയാസകരമായ നിമിഷം",
    "Ein tolles Date im Freien unter dem Mondlicht" to "നിലാവെളിച്ചത്തിന് കീഴിൽ അതിഗംഭീരമായ ഒരു തീയതി",
    "Ein ungewöhnliches Gericht" to "അസാധാരണമായ ഒരു വിഭവം",
    "Ein zufälliger Schnappschuss" to "ഒരു റാൻഡം സ്നാപ്പ്ഷോട്ട്",
    "Einander kennenlernen" to "പരസ്പരം അറിയുന്നു",
    "Eine Autoreise" to "ഒരു റോഡ് യാത്ര",
    "Eine Brücke" to "ഒരു പാലം",
    "Eine Date-Nacht unter den Sternen" to "നക്ഷത്രങ്ങൾക്ക് കീഴിലുള്ള ഒരു രാത്രി",
    "Eine Million Dollar gewinnen" to "ഒരു ദശലക്ഷം ഡോളർ നേടൂ",
    "Eine Million Dollar verdienen" to "ഒരു ദശലക്ഷം ഡോളർ സമ്പാദിക്കുക",
    "Eine Nacht in einem Club" to "ഒരു ക്ലബ്ബിലെ ഒരു രാത്രി",
    "Eine Schokoladenverkostung" to "ഒരു ചോക്ലേറ്റ് രുചിക്കൽ",
    "Eine Wanderung mit Panoramablick machen" to "പനോരമിക് കാഴ്‌ചകൾക്കൊപ്പം ഒരു യാത്ര നടത്തുക",
    "Eine Weinverkostung" to "ഒരു വൈൻ രുചിക്കൽ",
    "Eine gemeinsame Reise" to "ഒരുമിച്ചുള്ള യാത്ര",
    "Eine gemütliche Nacht zu Hause" to "വീട്ടിൽ ഒരു സുഖകരമായ രാത്രി",
    "Eine neue Sprache zu lernen ist einfach." to "ഒരു പുതിയ ഭാഷ പഠിക്കുന്നത് എളുപ്പമാണ്.",
    "Einen Film anschauen" to "ഒരു സിനിമ കാണുക",
    "Einen Monat lang überhaupt nicht miteinander reden" to "ഒരു മാസത്തേക്ക് പരസ്പരം സംസാരിക്കാറില്ല",
    "Einen Tanzkurs besuchen" to "ഒരു നൃത്ത ക്ലാസ് എടുക്കുക",
    "Einen Vergnügungspark erkunden" to "ഒരു അമ്യൂസ്‌മെൻ്റ് പാർക്ക് പര്യവേക്ഷണം ചെയ്യുക",
    "Einen Wellness-Tag" to "ഒരു ആരോഗ്യ ദിനം",
    "Einen sehr emotionalen Partner haben" to "വളരെ വൈകാരികമായ ഒരു പങ്കാളിയുണ്ട്",
    "Einen sehr logischen Partner haben" to "വളരെ യുക്തിസഹമായ ഒരു പങ്കാളിയുണ്ട്",
    "Einer zahlt alles" to "ഒരാൾ എല്ലാത്തിനും പണം നൽകുന്നു",
    "Einfach mehr Alltag" to "കൂടുതൽ ദൈനംദിന ജീവിതം",
    "Einfach nebeneinander sein" to "പരസ്പരം അടുത്തിരിക്കുക",
    "Einfach und intim" to "ലളിതവും അടുപ്പവും",
    "Einige Dinge für dich behalten" to "ചില കാര്യങ്ങൾ സ്വയം സൂക്ഷിക്കുക",
    "Einmal" to "ഒരിക്കൽ",
    "Eins, das nur wir kennen" to "നമുക്ക് മാത്രം അറിയാവുന്ന ഒന്ന്",
    "Englisch" to "ഇംഗ്ലീഷ്",
    "Entspannte Hängematte" to "റിലാക്‌സ്ഡ് ഹമ്മോക്ക്",
    "Entspannung" to "വിശ്രമം",
    "Erdbeere" to "സ്ട്രോബെറി",
    "Erfolgreich" to "വിജയിച്ചു",
    "Ergebnisse" to "ഫലങ്ങൾ",
    "Erst bei sehr großen Summen" to "വളരെ വലിയ തുകകൾക്ക് മാത്രം",
    "Erst nur enge Freunde/Familie" to "ആദ്യം അടുത്ത സുഹൃത്തുക്കൾ/കുടുംബം മാത്രം",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "എൻ്റെ പങ്കാളി സന്ദേശങ്ങളോട് പ്രതികരിക്കാൻ കൂടുതൽ സമയമെടുക്കുമ്പോൾ അത് എന്നെ അലോസരപ്പെടുത്തുന്നു.",
    "Essen & Genuss" to "ഭക്ഷണവും ആസ്വാദനവും",
    "Essensvorlieben" to "ഭക്ഷണ മുൻഗണനകൾ",
    "Etwa eine Woche später, erst mal nur wir" to "ഏകദേശം ഒരാഴ്ച കഴിഞ്ഞ്, ആദ്യം ഞങ്ങൾ മാത്രം",
    "Etwas Neues ausprobieren" to "പുതിയ എന്തെങ്കിലും പരീക്ഷിക്കുക",
    "Etwas ganz anderes" to "തികച്ചും വ്യത്യസ്തമായ ഒന്ന്",
    "Etwas sehr Scharfes" to "വളരെ മൂർച്ചയുള്ള എന്തോ ഒന്ന്",
    "Etwas, das ich selbst gern erfinde" to "ഞാൻ സ്വയം കണ്ടുപിടിക്കാൻ ഇഷ്ടപ്പെടുന്ന ഒന്ന്",
    "Etwas, eine kleine Note wäre schön" to "എന്തെങ്കിലും, ഒരു ചെറിയ കുറിപ്പ് നന്നായിരിക്കും",
    "Familie" to "കുടുംബം",
    "Familie/Freunde" to "കുടുംബം/സുഹൃത്തുക്കൾ",
    "Familienmensch" to "കുടുംബാംഗം",
    "Farbedelstein" to "നിറമുള്ള രത്നം",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "ടിവി പരസ്യങ്ങൾ ചിലപ്പോൾ കാണാൻ രസകരമാണ്.",
    "Fertig" to "ചെയ്തു",
    "Fertig!" to "ചെയ്തു!",
    "Feste Date-Nights" to "നിശ്ചിത തീയതി രാത്രികൾ",
    "Feuerstelle" to "അഗ്നികുണ്ഡം",
    "Filigran & schlicht" to "ഫിലിഗ്രിയും ലളിതവും",
    "Filme/Serien" to "സിനിമകൾ/പരമ്പരകൾ",
    "Formuliere um..." to "പുനർവാചകം...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "നിങ്ങളുടെ ഡ്രാഫ്റ്റ് അഹിംസാത്മകമായ രീതിയിൽ പുനഃക്രമീകരിക്കുക: നിരീക്ഷണം, വികാരം, ആവശ്യം, അഭ്യർത്ഥന.",
    "Frage hinzufügen" to "ചോദ്യം ചേർക്കുക",
    "Fragen & Spiele" to "ചോദ്യങ്ങളും ഗെയിമുകളും",
    "Fragen für jede Gelegenheit" to "എല്ലാ അവസരങ്ങൾക്കും ചോദ്യങ്ങൾ",
    "Freizeitpark" to "അമ്യൂസ്‌മെൻ്റ് പാർക്ക്",
    "Freunde treffen" to "സുഹൃത്തുക്കളെ കണ്ടുമുട്ടുക",
    "Freundschaften mit Ex-Partnern sind okay." to "പഴയവരുമായുള്ള സൗഹൃദം ശരിയാണ്.",
    "Früh aufstehen" to "നേരത്തെ എഴുന്നേൽക്കുക",
    "Fußbodenheizung" to "തറ ചൂടാക്കൽ",
    "Führen wir getrennte oder gemeinsame Konten?" to "ഞങ്ങൾക്ക് പ്രത്യേകമോ സംയുക്തമോ ആയ അക്കൗണ്ടുകളുണ്ടോ?",
    "Für dich empfohlen" to "നിങ്ങൾക്കായി ശുപാർശ ചെയ്‌തിരിക്കുന്നു",
    "Für die Zukunft" to "ഭാവിയിലേക്ക്",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "ഈ തിരയലിനായി പൊരുത്തപ്പെടുന്ന ചോദ്യങ്ങളോ ഗെയിമുകളോ കണ്ടെത്തിയില്ല.",
    "Für immer" to "എന്നേക്കും",
    "Fürsorglichkeit" to "കരുതൽ",
    "GFK-Brücke" to "GRP പാലം",
    "Galerie" to "ഗാലറി",
    "Gar nicht, der Moment gehört uns" to "അല്ല, ഈ നിമിഷം നമ്മുടേതാണ്",
    "Gar nichts tun" to "ഒന്നും ചെയ്യരുത്",
    "Geduld" to "ക്ഷമ",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "സൂര്യോദയം കാണാൻ അതിരാവിലെ പോകൂ",
    "Geht so" to "ഇതുപോലെ പോകുന്നു",
    "Geister existieren wirklich." to "പ്രേതങ്ങൾ ശരിക്കും നിലവിലുണ്ട്.",
    "Gelassenheit" to "ശാന്തത",
    "Gelbgold" to "മഞ്ഞ സ്വർണ്ണം",
    "Geld & Finanzen" to "പണവും സാമ്പത്തികവും",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "ഒരുമിച്ച് ലോകം ചുറ്റി സഞ്ചരിക്കുക, പുതിയ സംസ്‌കാരങ്ങളും പാചകരീതികളും പര്യവേക്ഷണം ചെയ്യുക",
    "Gemeinsam ein Lego bauen" to "ഒരുമിച്ച് ഒരു ലെഗോ നിർമ്മിക്കുക",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "അടുക്കളയിൽ ഒരുമിച്ച് ഒരു പുതിയ പാചകക്കുറിപ്പ് പരീക്ഷിക്കുക",
    "Gemeinsame Konten" to "പങ്കിട്ട അക്കൗണ്ടുകൾ",
    "Gemeinsame Nächte" to "ഒരുമിച്ച് രാത്രികൾ",
    "Gemeinsame Tage" to "ഒരുമിച്ച് ദിവസങ്ങൾ",
    "Gemischt" to "മിക്സഡ്",
    "Gemüsebeet" to "പച്ചക്കറി പാച്ച്",
    "Gemütliche Feuerstelle" to "സുഖപ്രദമായ അടുപ്പ്",
    "Gesprächsanreger" to "സംഭാഷണ സ്റ്റാർട്ടർ",
    "Getrennte Konten" to "പ്രത്യേക അക്കൗണ്ടുകൾ",
    "Getrennte Urlaube tun einer Beziehung gut." to "ഒരു ബന്ധത്തിന് പ്രത്യേക അവധികൾ നല്ലതാണ്.",
    "Gewächshaus" to "ഹരിതഗൃഹം",
    "Glasfassade" to "ഗ്ലാസ് മുൻഭാഗം",
    "Gleichgültigkeit" to "നിസ്സംഗത",
    "Glücklich und frei" to "സന്തോഷവും സൗജന്യവും",
    "Gourmet Eis-Sorten" to "രുചികരമായ ഐസ്ക്രീം ഇനങ്ങൾ",
    "Gravur innen" to "ഉള്ളിൽ കൊത്തുപണി",
    "Grillplatz" to "ബാർബിക്യൂ ഏരിയ",
    "Groß & üppig" to "വലുതും സമൃദ്ധവുമാണ്",
    "Große Familie" to "വലിയ കുടുംബം",
    "Große Feier" to "വലിയ ആഘോഷം",
    "Große Fenster" to "വലിയ വിൻഡോകൾ",
    "Große Fensterfront" to "വലിയ വിൻഡോ ഫ്രണ്ട്",
    "Großer Außenpool" to "വലിയ ഔട്ട്‌ഡോർ കുളം",
    "Großer Garten" to "വലിയ പൂന്തോട്ടം",
    "Großer Stein" to "വലിയ കല്ല്",
    "Größere Küche" to "വലിയ അടുക്കള",
    "Gutes Essen" to "നല്ല ഭക്ഷണം",
    "Habe ich" to "ഞാൻ ചെയ്തു",
    "Habe ich noch nie" to "എനിക്കൊരിക്കലും ഇല്ല",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "നിങ്ങൾ ആശ്ചര്യപ്പെടുത്തുന്ന എന്തെങ്കിലും വ്യത്യാസങ്ങൾ കണ്ടെത്തിയോ? എന്തുകൊണ്ടാണ് നിങ്ങൾ ചില ഓപ്ഷനുകൾ കൂടുതൽ ഇഷ്ടപ്പെടുന്നതെന്നതിനെക്കുറിച്ച് സംസാരിക്കുക!",
    "Haus am See" to "തടാകത്തിനരികിലുള്ള വീട്",
    "Haus/Wohnung" to "വീട്/അപ്പാർട്ട്മെൻ്റ്",
    "Hazelnut" to "ഹസൽനട്ട്",
    "Heimkino" to "ഹോം തിയേറ്റർ",
    "Herzhaft" to "ഹൃദയംഗമമായ",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "ഇപ്പോൾ ഇവിടെ ഒന്നുമില്ല.\nഫിൽട്ടർ മാറ്റുക അല്ലെങ്കിൽ മറ്റൊരു വിഷയം തിരഞ്ഞെടുക്കുക.",
    "Hilfe im Alltag" to "ദൈനംദിന ജീവിതത്തിൽ സഹായം",
    "Himbeere" to "റാസ്‌ബെറി",
    "Hinzufügen" to "ചേർക്കുക",
    "Hobbys" to "ഹോബികൾ",
    "Hochzeitssträuße" to "വിവാഹ പൂച്ചെണ്ടുകൾ",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "ഹോഗ്‌വാർട്ട്‌സ് ഹൗസ് പ്രൈഡ്: നിങ്ങൾ എവിടെയാണ്?",
    "Home" to "വീട്",
    "Hot Tub" to "ഹോട്ട് ടബ്",
    "Humor" to "നർമ്മം",
    "Hund" to "നായ",
    "Hängematte" to "ഹമ്മോക്ക്",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "നിർദ്ദേശത്തിൻ്റെ ഭാഗമായി നിങ്ങൾക്ക് ഒരു രേഖാമൂലമുള്ള കത്ത് വേണോ?",
    "IKEA" to "ഐ.കെ.ഇ.എ",
    "Ich" to "ഐ",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "സിനിമയിൽ പോകുന്നതിനേക്കാൾ പാർക്കിലെ റൊമാൻ്റിക് നടത്തങ്ങളാണ് ഞാൻ ഇഷ്ടപ്പെടുന്നത്.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "ഞാൻ ഒരു സിനിമയിലും ഉറങ്ങിയിട്ടില്ല.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "എൻ്റെ പങ്കാളിയുമായി പുതിയ ഹോബികളോ പ്രവർത്തനങ്ങളോ കണ്ടെത്തുന്നത് ഞാൻ ആസ്വദിക്കുന്നു.",
    "Ich finde eine Alternative" to "ഞാൻ ഒരു ബദൽ കണ്ടെത്തും",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "എപ്പോഴും ഒരേ സ്ഥലങ്ങളിൽ പോകുന്നതിനുപകരം എൻ്റെ പങ്കാളിയുമായി പുതിയ റെസ്റ്റോറൻ്റുകൾ പരീക്ഷിക്കുന്നത് ഞാൻ ആസ്വദിക്കുന്നു.",
    "Ich habe noch nie" to "ഞാനൊരിക്കലും ഇല്ല",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "ഞാൻ ഒരു റോളർ കോസ്റ്ററിനെ ഒരിക്കലും ഭയപ്പെട്ടിട്ടില്ല, എന്തായാലും ഞാൻ അതിൽ കയറി.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "ഞാൻ അക്ഷമനായതിനാൽ ഒരിക്കലും ഫാസ്റ്റ് പാസ് ടിക്കറ്റുകൾ വാങ്ങിയിട്ടില്ല.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "വീട്ടിലിരുന്ന് ടിവി ഷോ കാണാനുള്ള പദ്ധതികൾ ഞാൻ ഒരിക്കലും റദ്ദാക്കിയിട്ടില്ല.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "ഹോഗ്‌വാർട്ട്‌സിൽ നിന്നുള്ള എൻ്റെ കത്തിനായി ഞാൻ ഒരിക്കലും കാത്തിരുന്നിട്ടില്ല.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "സ്ലിതറിൻ അത്ര മോശമായിരുന്നില്ല എന്ന് ഞാൻ ഒരിക്കലും പറഞ്ഞിട്ടില്ല.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "എനിക്ക് ഡിസ്‌നി സിനിമകൾക്ക് പ്രായമുണ്ടെന്ന് ഞാൻ ഒരിക്കലും പറഞ്ഞിട്ടില്ല (അവ രഹസ്യമായി ആസ്വദിച്ചു).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "മരിയോ കാർട്ടിൽ നീല ടാങ്ക് കൊണ്ട് ഒരാളെ ഞാൻ മനഃപൂർവം വെടിവെച്ചിട്ടില്ല.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "ഞാൻ ഒരിക്കലും ഒരു ഡിസ്നി സിനിമയിൽ കരഞ്ഞിട്ടില്ല.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "ഒരു ഹൊറർ സിനിമ കാണുമ്പോൾ ഞാനൊരിക്കലും എൻ്റെ കണ്ണുകൾ മൂടിയിട്ടില്ല.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "ഒരു ഗെയിം സേവ് ചെയ്യാൻ ഞാൻ ഒരിക്കലും മറന്നിട്ടില്ല, മണിക്കൂറുകളുടെ പുരോഗതി നഷ്‌ടപ്പെട്ടു.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "നാണക്കേടുണ്ടാക്കുന്ന ഒരു രംഗത്തിനിടയിൽ ഞാൻ ഒരിക്കലും മുറി വിട്ടിട്ടില്ല (ഭീകര ഘടകം).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "ഒരു റോളർകോസ്റ്റർ ഫോട്ടോ എടുക്കുമ്പോൾ ഞാനൊരിക്കലും രസകരമായ ഒരു പോസ് ചെയ്തിട്ടില്ല.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "രാത്രി വൈകിയും ഞാൻ ഒരിക്കലും ഗെയിം കളിച്ചിട്ടില്ല, അടുത്ത ദിവസം ഞാൻ എത്ര ക്ഷീണിതനായിരുന്നു എന്നതിൽ ഖേദിക്കുന്നു.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "കാത്തിരിക്കാൻ വയ്യാത്തതിനാൽ ഞാൻ ഒരിക്കലും ഒരു സിനിമയുടെ അവസാനം ഗൂഗിൾ ചെയ്‌തിട്ടില്ല.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "ഞാൻ ഒരു സിനിമാ സെറ്റിൽ നിൽക്കുന്നതായി എനിക്ക് ഒരിക്കലും തോന്നിയിട്ടില്ല.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "എൻ്റെ പ്രിയപ്പെട്ട പരമ്പരയുടെ ആമുഖം ഞാൻ ഒരിക്കലും ഒഴിവാക്കിയിട്ടില്ല.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "ഞാൻ മറ്റാരുടെയും Netflix പാസ്‌വേഡ് പങ്കിട്ടിട്ടില്ല.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "ജോലി ചെയ്യുമ്പോഴോ പഠിക്കുമ്പോഴോ ഞാൻ ഒരിക്കലും ഒരു ഗെയിമിൻ്റെ സൗണ്ട് ട്രാക്ക് ശ്രദ്ധിച്ചിട്ടില്ല.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "തോറ്റപ്പോൾ ഞാൻ ഒരിക്കലും കൺട്രോളറെ കുറ്റപ്പെടുത്തിയിട്ടില്ല.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "ഞാൻ ഒരിക്കലും ദേഷ്യത്തിൽ കീബോർഡോ കൺട്രോളറോ വലിച്ചെറിഞ്ഞിട്ടില്ല.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "കുറച്ച് ദിവസത്തേക്ക് വാഷിംഗ് മെഷീനിൽ നനഞ്ഞ വസ്ത്രങ്ങൾ ഞാൻ ഒരിക്കലും മറന്നിട്ടില്ല.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "ഞാൻ ഒരിക്കലും ഒരു ഗെയിമിൽ സൗന്ദര്യവർദ്ധക വസ്തുക്കൾക്കായി യഥാർത്ഥ പണം ചെലവഴിച്ചിട്ടില്ല.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "ഞാൻ ഒരു വിദേശ രാജ്യത്തും കാർ ഓടിച്ചിട്ടില്ല.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "ഞാൻ ഒരിക്കലും ഷവറിൽ ഒരു ഡിസ്നി ഗാനം ബെൽറ്റ് ചെയ്തിട്ടില്ല.",
    "Ich habe noch nie ein Elektroauto gefahren." to "ഞാൻ ഒരിക്കലും ഇലക്ട്രിക് കാർ ഓടിച്ചിട്ടില്ല.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "ഞാനൊരിക്കലും പാർക്ക് മാസ്കോട്ടിനൊപ്പം ഫോട്ടോ എടുത്തിട്ടില്ല.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "ഞാൻ ഒരിക്കലും ഒരു വളർത്തുമൃഗത്തിന് ഹോഗ്‌വാർട്ട്സ് കഥാപാത്രത്തിൻ്റെ പേര് നൽകിയിട്ടില്ല.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "ഞാൻ ഒരിക്കലും ഒരു സിനിമാ തിയേറ്ററിൽ പോപ്‌കോൺ ഇട്ടിട്ടില്ല, ഇപ്പോഴും അത് കഴിച്ചിട്ടില്ല.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "സ്റ്റാർ വാർസിൽ നിന്നുള്ള മാസ്റ്റർ യോഡയിൽ നിന്നുള്ള ഒരു ഉദ്ധരണി ഞാൻ ദൈനംദിന ജീവിതത്തിൽ ഉപയോഗിച്ചിട്ടില്ല.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "ഞാൻ ഒരിക്കലും ഒരു തീം പാർക്കിൽ അമിത വിലയുള്ള സുവനീർ വാങ്ങിയിട്ടില്ല.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "മറ്റൊരാൾക്ക് ഭയങ്കരമായി തോന്നിയ ഒരു സിനിമ ഞാൻ ഒരിക്കലും നൽകിയിട്ടില്ല.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "ഞാൻ ഒരിക്കലും അർദ്ധരാത്രിയിൽ ഒരു ഓസ്കാർ തൽസമയം കണ്ടിട്ടില്ല.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "കഴിഞ്ഞ സീസൺ വളരെ മോശമായതിനാൽ ഞാൻ ഒരു പരമ്പരയും റദ്ദാക്കിയിട്ടില്ല.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "ഒരു സീരീസിൻ്റെ മുഴുവൻ സീസണും ഞാൻ ഒരു ദിവസം പോലും അമിതമായി കണ്ടിട്ടില്ല.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "ആദ്യ ശ്രമത്തിൽ തന്നെ ഞാൻ ഒരിക്കലും ഒരു ബോസിനെ തോൽപ്പിച്ചിട്ടില്ല, ഒരു ദൈവമായി എനിക്ക് തോന്നിയിട്ടില്ല.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "നായകനെക്കാൾ ശാന്തനായ ഒരു വില്ലനെ ഞാൻ ഇതുവരെ കണ്ടെത്തിയിട്ടില്ല.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "എൻ്റെ സ്വന്തം കളിപ്പാട്ടങ്ങളിലെ ടോയ് സ്റ്റോറി കഥാപാത്രത്തെ ഞാൻ ഒരിക്കലും തിരിച്ചറിഞ്ഞിട്ടില്ല.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "ഞാൻ ഒരിക്കലും എന്നെപ്പോലെ ഒരു RPG-യിൽ ഒരു കഥാപാത്രം ചെയ്തിട്ടില്ല.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "ഞാൻ ഒരിക്കലും ഒരു തീം പാർക്കിൽ നിന്ന് ഒരു ചുറോ കഴിച്ചിട്ടില്ല.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "ഞാൻ ഒരു ഡിസ്‌നി ഫിലിം തുടർച്ചയായി മൂന്ന് തവണ കണ്ടിട്ടില്ല.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "ഒരു ആഴ്‌ച മുഴുവൻ എനിക്ക് ഡിസ്‌നിയുടെ ആകർഷകമായ ട്യൂൺ ഉണ്ടായിട്ടില്ല.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "ഒരു പ്രത്യേക നടൻ കാരണം ഞാൻ ഒരിക്കലും സിനിമ കണ്ടിട്ടില്ല.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "ഞാൻ മണിക്കൂറുകളോളം ഒരു സിനിമാ സൗണ്ട് ട്രാക്ക് ആവർത്തിച്ച് കേട്ടിട്ടില്ല.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "ഞാനൊരിക്കലും ഒരു സിനിമ സ്‌പോയിലർ വെളിപ്പെടുത്തിയിട്ടില്ല, ഉടനെ അതിൽ ഖേദിക്കുന്നു.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "മറ്റൊരു മാതൃഭാഷ സംസാരിക്കുന്ന ഒരു സുഹൃത്തിനെ ഞാൻ ഇതുവരെ കണ്ടെത്തിയിട്ടില്ല.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "മറ്റൊരു രാജ്യത്തേക്ക് മാറിയ ഒരു സുഹൃത്തും എനിക്കുണ്ടായിട്ടില്ല.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "ക്രിസ്‌മസിന് ഞാനൊരിക്കലും ഹാരി പോട്ടർ സിനിമാ മാരത്തൺ നടത്തിയിട്ടില്ല.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "പോസ്റ്റ് ക്രെഡിറ്റ് സീൻ കാരണം ഞാൻ ഒരു മാർവൽ സിനിമയും അവസാനം വരെ കണ്ടിട്ടില്ല.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "ഞാൻ ഒരിക്കലും ഒരു NPC (നോൺ-പ്ലേയർ ക്യാരക്ടർ) മനഃപൂർവ്വം ശല്യപ്പെടുത്തിയിട്ടില്ല.",
    "Ich habe noch nie einen Nachtzug genommen." to "ഞാൻ ഒരിക്കലും രാത്രി ട്രെയിനിൽ കയറിയിട്ടില്ല.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "എൻ്റെ ഹോഗ്‌വാർട്‌സ് വീട് കണ്ടെത്താൻ ഞാൻ ഒരിക്കലും ഒരു ഓൺലൈൻ ടെസ്റ്റ് നടത്തിയിട്ടില്ല.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "വേണ്ടത്ര ലൈക്കുകൾ ലഭിക്കാത്തതിനാൽ ഞാനൊരിക്കലും ഒരു സോഷ്യൽ മീഡിയ പോസ്‌റ്റ് ഇല്ലാതാക്കിയിട്ടില്ല.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "തീം പാർക്കിലെ ഒരു ദിവസത്തെ ഈ വർഷത്തെ ഏറ്റവും മികച്ച ദിവസമെന്ന് ഞാൻ ഒരിക്കലും വിളിച്ചിട്ടില്ല.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "ഞാൻ ഒരിക്കലും ഒരു തീം പാർക്ക് സന്ദർശിച്ചിട്ടില്ല, രാവിലെ മുതൽ രാത്രി വരെ അവിടെ താമസിച്ചിട്ടില്ല.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "ഞാൻ ഒരിക്കലും ഒരു ട്രാൻസ്‌ഫോർമേഴ്‌സ് അല്ലെങ്കിൽ മാർവൽ റൈഡ് പൂർണ്ണമായും ആകർഷിച്ചിട്ടില്ല.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "ഞാനൊരിക്കലും രോഷം വെടിഞ്ഞ് കളി ഉപേക്ഷിച്ചിട്ടില്ല.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "വലിയ ഹാരി പോട്ടർ വാല്യങ്ങളൊന്നും ഞാൻ വായിച്ചിട്ടില്ല.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "ഒരു സീരിയലിലെ എൻ്റെ പ്രിയപ്പെട്ട കഥാപാത്രത്തെക്കുറിച്ച് ഞാൻ ഒരിക്കലും ആക്രോശിച്ചിട്ടില്ല.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "ക്വിഡിച്ച് കളിക്കുമെന്ന് ഞാൻ ഒരിക്കലും സ്വപ്നം കണ്ടിട്ടില്ല.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "ഹാർഡ് ലെവൽ എങ്ങനെ പരിഹരിക്കാമെന്ന് ഞാൻ രഹസ്യമായി ഗൂഗിൾ ചെയ്‌തിട്ടില്ല.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "ഡിസ്നിയിലെ പോലെ എൻ്റെ വളർത്തുമൃഗത്തിന് സംസാരിക്കാൻ കഴിയുമെന്ന് ഞാൻ ഒരിക്കലും രഹസ്യമായി പ്രതീക്ഷിച്ചിരുന്നില്ല.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "ഞാൻ ഒരിക്കലും സിംസിലെ പൂൾ ലീഡറെ നീക്കം ചെയ്തിട്ടില്ല.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "ഒരു 3D സിമുലേറ്റർ റൈഡിൽ ഒരിക്കലും എൻ്റെ ബെയറിംഗുകൾ നഷ്ടപ്പെട്ടിട്ടില്ല.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "ഞാൻ ഒരിക്കലും ഒരു യൂണിവേഴ്സിറ്റി സ്പോർട്സ് ടീമിൽ കളിച്ചിട്ടില്ല.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "ഒരു ആകർഷണത്തിനായി ഞാൻ ഒരിക്കലും രണ്ട് മണിക്കൂറിൽ കൂടുതൽ വരിയിൽ നിന്നിട്ടില്ല.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "എൻ്റെ വിലപിടിപ്പുള്ള സാധനങ്ങൾ ജലയാത്രയിൽ ഒരിക്കലും നനഞ്ഞിട്ടില്ല.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "ഏത് വീടാണ് ഏറ്റവും മികച്ചതെന്ന് ഞാൻ ഒരിക്കലും ഒരു സുഹൃത്തിനോട് തർക്കിച്ചിട്ടില്ല.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "എൽസയെപ്പോലെ മാന്ത്രിക ശക്തികൾ ഉള്ളതായി ഞാൻ ഒരിക്കലും നടിച്ചിട്ടില്ല.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "ഒരു സിനിമയിലെ പ്രധാനപ്പെട്ട ഒരു രംഗം കാണാതെ പോകത്തക്കവണ്ണം ഞാൻ ഒരിക്കലും ചിരിച്ചിട്ടില്ല.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "എനിക്കൊരിക്കലും ഇത്രയധികം അഡ്രിനാലിൻ അനുഭവപ്പെട്ടിട്ടില്ല, പെട്ടെന്ന് വീണ്ടും ഓടിക്കാൻ ഞാൻ ആഗ്രഹിച്ചു.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "സ്നോ വൈറ്റ് പോലുള്ള മൃഗങ്ങൾക്കൊപ്പം പാടാൻ ഞാൻ ഒരിക്കലും ശ്രമിച്ചിട്ടില്ല.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "ഡിസ്‌നിലാൻഡിലേക്കുള്ള ഒരു യാത്ര ഞാൻ ഒരിക്കലും സ്വപ്നം കണ്ടിട്ടില്ല.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "ജുറാസിക് പാർക്ക് വാട്ടർ റൈഡ് ഞാൻ ഒരിക്കലും സ്വപ്നം കണ്ടിട്ടില്ല.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "ഒരു ഗെയിമിലെ ജമ്പ് സ്‌കെയറിൽ ഞാൻ ഒരിക്കലും ഉറക്കെ നിലവിളിച്ചിട്ടില്ല.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "ഒരു ടിവി ഷോയുടെ അവസാനത്തെച്ചൊല്ലി ഞാൻ ഒരിക്കലും കരഞ്ഞിട്ടില്ല.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "ഞാൻ ഒരിക്കലും... വീട്ടിലിരിക്കാനുള്ള തീയതി റദ്ദാക്കിയിട്ടില്ല.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "ഞാനൊരിക്കലും... ഒരു സന്ദേശം 10 തവണ റീഫ്രാസ് ചെയ്തിട്ടില്ല.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "ഞാൻ ഒരിക്കലും... എൻ്റെ പങ്കാളിയുടെ സെൽ ഫോണിലേക്ക് രഹസ്യമായി നോക്കിയിട്ടില്ല.",
    "Ich habe noch nie!" to "ഞാനൊരിക്കലും ഇല്ല!",
    "Ich habe!" to "എനിക്കുണ്ട്!",
    "Ich lache viel mit meinem Partner." to "ഞാൻ എൻ്റെ പങ്കാളിയുമായി ഒരുപാട് ചിരിക്കുന്നു.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "എൻ്റെ പങ്കാളിയുടെ ഹോബികളും താൽപ്പര്യങ്ങളും അറിയാൻ ഞാൻ ആഗ്രഹിക്കുന്നു.",
    "Ich liebe es" to "എനിക്കത് ഇഷ്ടമാണ്",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "ഞങ്ങൾ രണ്ടുപേരും മുമ്പ് കണ്ടിട്ടില്ലാത്ത സിനിമകൾ എൻ്റെ പങ്കാളിയോടൊപ്പം കാണാൻ ഞാൻ ഇഷ്ടപ്പെടുന്നു.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "എൻ്റെ പ്രിയപ്പെട്ട സംഗീതം എൻ്റെ പങ്കാളിയുമായി പങ്കിടുന്നത് ഞാൻ ഇഷ്ടപ്പെടുന്നു.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "കണക്റ്റിംഗ് ഫ്ലൈറ്റ് പിടിക്കാൻ എനിക്ക് ഒരിക്കലും ഓടേണ്ടി വന്നിട്ടില്ല.",
    "Ich plane gerne Dates mit meinem Partner." to "എൻ്റെ പങ്കാളിയുമായി തീയതികൾ ആസൂത്രണം ചെയ്യാൻ ഞാൻ ഇഷ്ടപ്പെടുന്നു.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "ഞാൻ തിരക്കിലായിരിക്കുമ്പോൾ പോലും എൻ്റെ പങ്കാളിയോടൊപ്പം സമയം ചിലവഴിക്കുന്നതിന് മുൻഗണന നൽകുന്നു.",
    "Ich schreibe meinem Partner jeden Tag." to "ഞാൻ എൻ്റെ പങ്കാളിക്ക് എല്ലാ ദിവസവും മെസേജ് അയയ്ക്കുന്നു.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "എൻ്റെ പങ്കാളിയുമായി മെമ്മുകളും തമാശകളും പങ്കിടാൻ ഞാൻ ഇഷ്ടപ്പെടുന്നു.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "എൻ്റെ ദിവസത്തിൻ്റെ എല്ലാ വിശദാംശങ്ങളും എൻ്റെ പങ്കാളിയുമായി പങ്കിടാൻ ഞാൻ ആഗ്രഹിക്കുന്നു.",
    "Ich würde es nie tun" to "ഞാനത് ഒരിക്കലും ചെയ്യില്ല",
    "Ich übe noch" to "ഞാൻ ഇപ്പോഴും പരിശീലിക്കുന്നു",
    "Ideen generieren" to "ആശയങ്ങൾ സൃഷ്ടിക്കുക",
    "Im Haushalt helfen" to "വീടിന് ചുറ്റുമുള്ള സഹായം",
    "In Chat einfügen" to "ചാറ്റിലേക്ക് ചേർക്കുക",
    "In Stille nebeneinander" to "നിശ്ശബ്ദതയിൽ പരസ്പരം",
    "In den Bergen" to "മലനിരകളിൽ",
    "In eine Bar gehen" to "ഒരു ബാറിലേക്ക് പോകുക",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "സൂര്യാസ്തമയം കാണാൻ ബീച്ച് ബാറിലേക്ക് പോകുന്നു",
    "In einem feinen Restaurant essen gehen" to "നല്ല ഭക്ഷണശാലയിൽ നിന്ന് ഭക്ഷണം കഴിക്കുന്നു",
    "In einen Coffeeshop gehen" to "ഒരു കോഫി ഷോപ്പിലേക്ക് പോകുക",
    "In einer Beziehung sollte man alles voneinander wissen." to "ഒരു ബന്ധത്തിൽ നിങ്ങൾ പരസ്പരം എല്ലാം അറിഞ്ഞിരിക്കണം.",
    "Infinity-Pool" to "ഇൻഫിനിറ്റി പൂൾ",
    "Innenpool" to "ഇൻഡോർ പൂൾ",
    "Intelligenz" to "ഇൻ്റലിജൻസ്",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "നിങ്ങളുടെ പങ്കാളി അത് ആരംഭിക്കുമ്പോൾ മാത്രം അടുപ്പമുള്ള നിമിഷങ്ങൾ",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "ക്ഷണ കോഡ്: HRM-8731 · എല്ലാം അൺലോക്ക് ചെയ്തു",
    "Island" to "ഐസ്‌ലാൻഡ്",
    "Ist okay für mich" to "എനിക്ക് കുഴപ്പമില്ല",
    "Ist schon perfekt" to "ഇത് തികഞ്ഞതാണ്",
    "Ja, Traditionen einbinden" to "അതെ, പാരമ്പര്യങ്ങൾ ഉൾപ്പെടുത്തുക",
    "Ja, absolut" to "അതെ, തീർച്ചയായും",
    "Ja, etwas zum Lesen und Aufbewahren" to "അതെ, വായിക്കാനും സൂക്ഷിക്കാനും എന്തെങ്കിലും",
    "Ja, genug" to "അതെ, മതി",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "അതെ, ആവേശകരമായ ഒരു നഗരത്തിലോ ആകർഷണത്തിലോ",
    "Ja, in- und auswendig" to "അതെ, അകത്തും പുറത്തും",
    "Ja, komplett überraschend" to "അതെ, തികച്ചും ആശ്ചര്യകരമാണ്",
    "Ja, perfekt" to "അതെ, തികഞ്ഞതാണ്",
    "Ja, sie gehören zur Familie!" to "അതെ, അവർ കുടുംബമാണ്!",
    "Ja, sofort teilen" to "അതെ, ഉടൻ പങ്കിടുക",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "അതെ, കുടുംബ സമയം മുൻഗണനയാണെന്ന് ഞങ്ങൾ ഉറപ്പാക്കും.",
    "Jacuzzi" to "ജാക്കൂസി",
    "Jahr zusammen 🎉" to "വർഷം ഒരുമിച്ച് 🎉",
    "Jahre zusammen 🎉" to "വർഷങ്ങൾ ഒരുമിച്ച് 🎉",
    "Jeder zahlt 50%" to "എല്ലാവരും 50% നൽകുന്നു",
    "Junge" to "ആൺകുട്ടി",
    "Kamin" to "അടുപ്പ്",
    "Karriere & Erfolg" to "കരിയറും വിജയവും",
    "Kategorien" to "വിഭാഗങ്ങൾ",
    "Katze" to "പൂച്ച",
    "Keine Musik" to "സംഗീതമില്ല",
    "Keine Party nötig, privat halten" to "ഒരു പാർട്ടിയുടെ ആവശ്യമില്ല, അത് സ്വകാര്യമായി സൂക്ഷിക്കുക",
    "Keine Privatsphäre" to "സ്വകാര്യതയില്ല",
    "Keine Treffer gefunden" to "പൊരുത്തങ്ങളൊന്നും കണ്ടെത്തിയില്ല",
    "Keiner" to "ഒന്നുമില്ല",
    "Keiner von uns" to "ഞങ്ങളിൽ ആരുമില്ല",
    "Kennst du die Essensvorlieben deines Partners?" to "നിങ്ങളുടെ പങ്കാളിയുടെ ഭക്ഷണ മുൻഗണനകൾ നിങ്ങൾക്ക് അറിയാമോ?",
    "Kino" to "സിനിമ",
    "Kirchlich" to "സഭാപരമായ",
    "Klassisch Solitär" to "ക്ലാസിക് സോളിറ്റയർ",
    "Klassisch gebunden" to "ക്ലാസിക്കൽ ബൗണ്ട്",
    "Klein & zart" to "ചെറുതും അതിലോലമായതും",
    "Kleine Geschenke" to "ചെറിയ സമ്മാനങ്ങൾ",
    "Kleine Runde" to "ചെറിയ ഗ്രൂപ്പ്",
    "Kochen und Freunde einladen" to "പാചകം ചെയ്യുകയും സുഹൃത്തുക്കളെ ക്ഷണിക്കുകയും ചെയ്യുന്നു",
    "Kochkurs" to "പാചക ക്ലാസ്",
    "Kommt auf den Tag an" to "ദിവസത്തെ ആശ്രയിച്ചിരിക്കുന്നു",
    "Kommt darauf an" to "അത് ആശ്രയിച്ചിരിക്കുന്നു",
    "Kommt drauf an" to "അത് ആശ്രയിച്ചിരിക്കുന്നു",
    "Kommt mit" to "എന്നോടൊപ്പം വരൂ",
    "Konzert" to "കച്ചേരി",
    "Kräftige Farben" to "ശക്തമായ നിറങ്ങൾ",
    "Kräuterbeet" to "ഔഷധ കിടക്ക",
    "Kultur & Sehenswürdigkeiten" to "സംസ്കാരവും കാഴ്ചകളും",
    "Kuscheln" to "ആലിംഗനം",
    "Kuss senden" to "ഒരു ചുംബനം അയയ്ക്കുക",
    "Körperliche Annäherung" to "ശാരീരിക സമീപനം",
    "Körperliche Nähe" to "ശാരീരിക അടുപ്പം",
    "Küche" to "അടുക്കള",
    "Land" to "രാജ്യം",
    "Landhaus" to "നാടൻ വീട്",
    "Landhausstil" to "കൺട്രി ഹൗസ് ശൈലി",
    "Lange wach bleiben" to "വൈകി ഉണരുക",
    "Lappland" to "ലാപ്‌ലാൻഡ്",
    "Lappland, Finnland" to "ലാപ്‌ലാൻഡ്, ഫിൻലാൻഡ്",
    "Las Vegas" to "ലാസ് വെഗാസ്",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "നിങ്ങളുടെ ഏറ്റവും മികച്ച വ്യക്തിയാകാൻ നിങ്ങളുടെ പങ്കാളി നിങ്ങളെ പ്രചോദിപ്പിക്കട്ടെ",
    "Lehne ab" to "നിരസിക്കുക",
    "Leichtigkeit" to "ലഘുത്വം",
    "Leidenschaft" to "പാഷൻ",
    "Liebe im Gleichgewicht" to "സമനിലയിൽ സ്നേഹം",
    "Liebe sie, macht mehr Spaß" to "അവരെ സ്നേഹിക്കൂ, കൂടുതൽ രസകരം",
    "Lieber durchgeplant oder spontan?" to "നിങ്ങൾ അത് ആസൂത്രണം ചെയ്യുന്നതാണോ അതോ സ്വയമേവയുള്ളതാണോ?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "നിങ്ങൾ രണ്ടുപേർക്ക് വേണ്ടിയോ ആളുകൾക്കൊപ്പമോ ശാന്തമായ ഒരു സായാഹ്നം ആസ്വദിക്കണോ?",
    "Lieber nicht" to "അല്ലാത്തതാണ് നല്ലത്",
    "Lieber vorher grob absprechen" to "കാര്യങ്ങൾ ഏകദേശം മുൻകൂട്ടി ചർച്ച ചെയ്യുന്നതാണ് നല്ലത്",
    "Lokal einkaufen" to "പ്രാദേശികമായി ഷോപ്പുചെയ്യുക",
    "London" to "ലണ്ടൻ",
    "London, England" to "ലണ്ടൻ, ഇംഗ്ലണ്ട്",
    "Lügen" to "നുണകൾ",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "നിങ്ങൾ ഒരു പൊതു അല്ലെങ്കിൽ സ്വകാര്യ നിർദ്ദേശമാണോ തിരഞ്ഞെടുക്കുന്നത്?",
    "Malediven" to "മാലിദ്വീപ്",
    "Man sollte nie streitend einschlafen." to "തർക്കിച്ചുകൊണ്ട് നിങ്ങൾ ഒരിക്കലും ഉറങ്ങരുത്.",
    "Mango Sorbet" to "മാമ്പഴ സർബത്ത്",
    "Markant & breit" to "സ്‌ട്രൈക്കിംഗ് & വൈഡ്",
    "Marken & Alltag" to "ബ്രാൻഡുകളും ദൈനംദിന ജീവിതവും",
    "McDonald’s" to "മക്ഡൊണാൾഡ്സ്",
    "Mediterraner Innenhof" to "മെഡിറ്ററേനിയൻ മുറ്റം",
    "Mehr Unterstützung" to "കൂടുതൽ പിന്തുണ",
    "Mehr gemeinsame Zeit" to "കൂടുതൽ സമയം ഒരുമിച്ച്",
    "Mehr zuhören" to "കൂടുതൽ കേൾക്കൂ",
    "Mehrgenerationenhaus" to "ഒന്നിലധികം തലമുറകളുള്ള വീട്",
    "Mein Arbeitsplatz" to "എൻ്റെ ജോലിസ്ഥലം",
    "Mein Partner" to "എൻ്റെ പങ്കാളി",
    "Mich überraschen" to "എന്നെ അത്ഭുതപ്പെടുത്തൂ",
    "Minimalistisches Interieur" to "മിനിമലിസ്റ്റ് ഇൻ്റീരിയർ",
    "Missverständnisse" to "തെറ്റിദ്ധാരണകൾ",
    "Mit Familie und engen Freunden" to "കുടുംബത്തിനും അടുത്ത സുഹൃത്തുക്കൾക്കുമൊപ്പം",
    "Mit Kompromissen" to "വിട്ടുവീഴ്ചകളോടെ",
    "Mitgefühl" to "അനുകമ്പ",
    "Mittelweg mit besonderen Details" to "പ്രത്യേക വിശദാംശങ്ങളുള്ള മിഡിൽ ഗ്രൗണ്ട്",
    "Modern geometrisch" to "ആധുനിക ജ്യാമിതീയ",
    "Moderne Grillstation" to "ആധുനിക ഗ്രിൽ സ്റ്റേഷൻ",
    "Moderner Name" to "ആധുനിക നാമം",
    "Moderner Solitär" to "ആധുനിക സോളിറ്റയർ",
    "Moissanit" to "മൊയ്‌സാനൈറ്റ്",
    "Moment festhalten" to "നിമിഷം ക്യാപ്‌ചർ ചെയ്യുക",
    "Momente" to "നിമിഷങ്ങൾ",
    "Monaco" to "മൊണാക്കോ",
    "Moralische Werte" to "ധാർമ്മിക മൂല്യങ്ങൾ",
    "Museum" to "മ്യൂസിയം",
    "Musik" to "സംഗീതം",
    "Mut" to "ധൈര്യം",
    "Mädchen" to "പെൺകുട്ടികൾ",
    "Möbelhaus" to "ഫർണിച്ചർ സ്റ്റോർ",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "ക്വിസ് ഉപേക്ഷിക്കണമെന്ന് തീർച്ചയാണോ? നിങ്ങളുടെ മുൻ പുരോഗതി സംരക്ഷിക്കപ്പെട്ടിരിക്കുന്നു.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "ആപ്ലിക്കേഷനിൽ വളർത്തുമൃഗങ്ങളെ ഉൾപ്പെടുത്താൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "ഈ നിമിഷം സോഷ്യൽ മീഡിയയിൽ തൽക്ഷണം പങ്കിടാൻ ആഗ്രഹിക്കുന്നുണ്ടോ?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "നമുക്ക് സമ്പാദ്യം ആവശ്യമായി വന്നേക്കാം",
    "Müssen es planen" to "അത് ആസൂത്രണം ചെയ്യേണ്ടതുണ്ട്",
    "Müssen sparen" to "സംരക്ഷിക്കേണ്ടതുണ്ട്",
    "Nachricht an" to "സന്ദേശം",
    "Name Partnerin" to "പങ്കാളിയുടെ പേര്",
    "Namen und Startdatum eurer Beziehung." to "നിങ്ങളുടെ ബന്ധത്തിൻ്റെ പേരുകളും ആരംഭ തീയതിയും.",
    "Natursteinfassade" to "പ്രകൃതിദത്ത കല്ലിൻ്റെ മുൻഭാഗം",
    "Naturteich" to "സ്വാഭാവിക കുളം",
    "Nein, einfach halten" to "ഇല്ല, പിടിക്കൂ",
    "Nein, erstmal privat halten" to "ഇല്ല, ഇപ്പോൾ ഇത് സ്വകാര്യമായി സൂക്ഷിക്കുക",
    "Nein, lieber vor Ort" to "ഇല്ല, സൈറ്റിൽ മികച്ചതാണ്",
    "Nein, modern halten" to "ഇല്ല, അത് ആധുനികമായി സൂക്ഷിക്കുക",
    "Nein, nur wir" to "ഇല്ല, ഞങ്ങൾ മാത്രം",
    "Nein, zu ablenkend" to "ഇല്ല, വളരെ ശ്രദ്ധ തിരിക്കുന്നു",
    "Netflix" to "നെറ്റ്ഫ്ലിക്സ്",
    "Neubau mit Smart Home" to "സ്മാർട്ട് ഹോം ഉള്ള പുതിയ കെട്ടിടം",
    "Neubau mit Technik" to "സാങ്കേതികവിദ്യയുള്ള പുതിയ കെട്ടിടം",
    "Neue Liebe, neue Erfahrungen" to "പുതിയ പ്രണയം, പുതിയ അനുഭവങ്ങൾ",
    "Neues Hobby" to "പുതിയ ഹോബി",
    "Neues Spiel" to "പുതിയ ഗെയിം",
    "Neugier" to "ജിജ്ഞാസ",
    "New York" to "ന്യൂയോർക്ക്",
    "New York, USA" to "ന്യൂയോർക്ക്, യുഎസ്എ",
    "Nicht mein Fall" to "എൻ്റെ കപ്പ് ചായയല്ല",
    "Nicht nötig, lieber klassisch bleiben" to "ആവശ്യമില്ല, ക്ലാസിക് ആയി തുടരുന്നതാണ് നല്ലത്",
    "Nichts — es passt so" to "ഒന്നുമില്ല - അത് യോജിക്കുന്നു",
    "Nie wieder Burger" to "ഇനിയൊരിക്കലും ബർഗറുകൾ പാടില്ല",
    "Nie wieder Pizza" to "ഇനി ഒരിക്കലും പിസ്സ പാടില്ല",
    "Niemand" to "ആരുമില്ല",
    "Niemand ohne Plan" to "പദ്ധതിയില്ലാതെ ആരുമില്ല",
    "Nike" to "നൈക്ക്",
    "Nizza" to "കൊള്ളാം",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "ഇതുവരെ നിമിഷങ്ങളൊന്നുമില്ല.\nനിങ്ങളുടെ ആദ്യ അനുഭവം പകർത്തൂ 💞",
    "Nur bei wichtigen Themen" to "പ്രധാനപ്പെട്ട വിഷയങ്ങൾക്ക് മാത്രം",
    "Nur wir beide" to "ഞങ്ങൾ രണ്ടുപേർ മാത്രം",
    "Nähe & Intimität" to "അടുപ്പവും അടുപ്പവും",
    "Obstgarten" to "തോട്ടം",
    "Oder" to "അല്ലെങ്കിൽ",
    "Offene Küche" to "തുറന്ന അടുക്കള",
    "Offene Wohnküche" to "തുറന്ന അടുക്കള/ലിവിംഗ് റൂം",
    "Ohne Stein" to "കല്ലില്ലാതെ",
    "Open End" to "തുറന്ന അവസാനം",
    "Outdoor-Küche" to "ഔട്ട്‌ഡോർ അടുക്കള",
    "Outdoor-Sofa" to "ഔട്ട്‌ഡോർ സോഫ",
    "Outdoor-Whirlpool" to "ഔട്ട്‌ഡോർ വേൾപൂൾ",
    "Ovaler Diamant" to "ഓവൽ വജ്രം",
    "Paar" to "ജോഡി",
    "Paar-Statistiken" to "ദമ്പതികളുടെ സ്ഥിതിവിവരക്കണക്കുകൾ",
    "Paris" to "പാരീസ്",
    "Paris, Frankreich" to "പാരീസ്, ഫ്രാൻസ്",
    "Partner" to "പങ്കാളി",
    "Partner-Simulator" to "പങ്കാളി സിമുലേറ്റർ",
    "Partnerin" to "പങ്കാളി",
    "Party Edition" to "പാർട്ടി പതിപ്പ്",
    "Party Edition II" to "പാർട്ടി പതിപ്പ് II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "നമ്മുടെ ദൈനംദിന ജീവിതത്തിൽ പോലും ഒരു മൃഗം യോജിക്കുമോ?",
    "Pasta" to "പാസ്ത",
    "Pastell" to "പാസ്റ്റൽ",
    "Penthouse mit Ausblick" to "കാഴ്ചയുള്ള പെൻ്റ്‌ഹൗസ്",
    "Pepsi" to "പെപ്സി",
    "Pergola mit Lounge" to "വിശ്രമമുറിയോടുകൂടിയ പെർഗോള",
    "Pfingstrosen" to "പിയോണികൾ",
    "Pinguin" to "പെൻഗ്വിൻ",
    "Pistazie" to "പിസ്ത",
    "Pizza" to "പിസ്സ",
    "Pizzaofen" to "പിസ്സ ഓവൻ",
    "Platin" to "പ്ലാറ്റിനം",
    "PlayStation" to "പ്ലേസ്റ്റേഷൻ",
    "Pool" to "പൂൾ",
    "Pop" to "പോപ്പ്",
    "Prasselnder Kamin" to "അലറുന്ന അടുപ്പ്",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "രാജകുമാരിമാർ, കടൽക്കൊള്ളക്കാർ, ഫെയറി ഡസ്റ്റ്: ഡിസ്നി ക്വിസ്",
    "Privater Innenhof" to "സ്വകാര്യ മുറ്റം",
    "Profil" to "പ്രൊഫൈൽ",
    "Profil bearbeiten" to "പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക",
    "Prozentual nach Einkommen" to "വരുമാനത്തെ അടിസ്ഥാനമാക്കിയുള്ള ശതമാനം",
    "Quiz verlassen" to "ക്വിസ് അവസാനിപ്പിക്കുക",
    "Quiz verlassen?" to "ക്വിസ് വിടണോ?",
    "Rausgehen in die Natur" to "പ്രകൃതിയിലേക്ക് ഇറങ്ങുക",
    "Reden vor ..." to "സംസാരിക്കുന്നു...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "പതിവ് തീയതികളോ സമയമോ ഒരുമിച്ച് ഷെഡ്യൂൾ ചെയ്യുക",
    "Reisen" to "യാത്ര",
    "Reiseziele" to "യാത്രാ ലക്ഷ്യസ്ഥാനങ്ങൾ",
    "Respektlosigkeit" to "അനാദരവ്",
    "Restaurant" to "റെസ്റ്റോറൻ്റ്",
    "RnB / Soul" to "RnB / സോൾ",
    "Rock" to "പാറ",
    "Rom" to "റോം",
    "Rom, Italien" to "റോം, ഇറ്റലി",
    "Romantik" to "പ്രണയം",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "സന്ദേശങ്ങൾ, കുറിപ്പുകൾ അല്ലെങ്കിൽ സമ്മാനങ്ങൾ പോലുള്ള റൊമാൻ്റിക് ആംഗ്യങ്ങൾ എന്നെ സന്തോഷിപ്പിക്കുന്നു.",
    "Romantische Stimmung" to "റൊമാൻ്റിക് മൂഡ്",
    "Roségold" to "റോസ് ഗോൾഡ്",
    "Ruhig zu zweit" to "രണ്ടുപേർക്ക് നിശബ്ദത",
    "Runder Diamant" to "വൃത്താകൃതിയിലുള്ള വജ്രം",
    "Salted Caramel" to "ഉപ്പിട്ട കാരമൽ",
    "Sammle Ideen..." to "ആശയങ്ങൾ ശേഖരിക്കുക...",
    "Santorini" to "സാൻ്റോറിനി",
    "Santorini, Griechenland" to "സാൻ്റോറിനി, ഗ്രീസ്",
    "Saphir" to "നീലക്കല്ലു",
    "Saunahaus" to "സൗന വീട്",
    "Schickes Restaurant oder Hotel" to "ചിക് റെസ്റ്റോറൻ്റ് അല്ലെങ്കിൽ ഹോട്ടൽ",
    "Schlafzimmer" to "കിടപ്പുമുറി",
    "Schließen" to "അടയ്ക്കുക",
    "Schmal & zart" to "മെലിഞ്ഞതും അതിലോലമായതും",
    "Schnappschüsse aus unserer Liebesgeschichte" to "ഞങ്ങളുടെ പ്രണയകഥയിൽ നിന്നുള്ള സ്നാപ്പ്ഷോട്ടുകൾ",
    "Schokolade" to "ചോക്കലേറ്റ്",
    "Schreib frei, was dir wirklich dazu einfällt." to "യഥാർത്ഥത്തിൽ മനസ്സിൽ വരുന്നത് സ്വതന്ത്രമായി എഴുതുക.",
    "Schreibe deine eigene Antwort" to "നിങ്ങളുടെ സ്വന്തം ഉത്തരം എഴുതുക",
    "Sehr gerne" to "നിങ്ങൾക്ക് സ്വാഗതം",
    "Sehr leicht" to "വളരെ ഭാരം കുറഞ്ഞതാണ്",
    "Sehr wichtig — Fotos und Video" to "വളരെ പ്രധാനമാണ് - ഫോട്ടോകളും വീഡിയോയും",
    "Sehr wichtig, es sollte persönlich sein" to "വളരെ പ്രധാനമാണ്, അത് വ്യക്തിപരമായിരിക്കണം",
    "Selbst kochen" to "സ്വയം പാചകം ചെയ്യുക",
    "Senden" to "അയയ്‌ക്കുക",
    "Separate Küche" to "പ്രത്യേക അടുക്കള",
    "Serie schauen" to "പരമ്പര കാണുക",
    "Serienmarathon auf dem Sofa" to "സോഫയിൽ സീരീസ് മാരത്തൺ",
    "Sex & Liebe" to "ലൈംഗികതയും പ്രണയവും",
    "Seychellen" to "സീഷെൽസ്",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "ഒരു കുട്ടിക്ക്/ഒന്നിലധികം കുട്ടികൾക്കുള്ള എല്ലാ ചെലവുകളും വഹിക്കാൻ ഞങ്ങൾക്ക് കഴിയുമോ? 💰",
    "Soll der Antrag eine Überraschung sein?" to "ഈ നിർദ്ദേശം അതിശയിപ്പിക്കുന്നതാണോ?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "ആപ്ലിക്കേഷനിൽ സാംസ്കാരികമോ പരമ്പരാഗതമോ ആയ ഘടകങ്ങൾ അടങ്ങിയിരിക്കണമോ?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "ആപ്ലിക്കേഷനിൽ സാംസ്കാരികമോ പരമ്പരാഗതമോ ആയ ഘടകങ്ങൾ അടങ്ങിയിരിക്കണമോ?",
    "Sommerhochzeit" to "വേനൽക്കാല വിവാഹം",
    "Sonnige Dachterrasse" to "സണ്ണി റൂഫ് ടെറസ്",
    "Sowohl als auch" to "രണ്ടും കൂടാതെ",
    "Spazieren" to "നടക്കുക",
    "Spaß & Abenteuer" to "വിനോദവും സാഹസികതയും",
    "Speichern" to "സംരക്ഷിക്കുക",
    "Spiel bearbeiten" to "ഗെയിം എഡിറ്റ് ചെയ്യുക",
    "Spielbereich für Kinder" to "കുട്ടികൾക്കുള്ള കളിസ്ഥലം",
    "Spiele" to "ഗെയിമുകൾ",
    "Spiele spielen und Spaß haben" to "ഗെയിമുകൾ കളിക്കുക, ആസ്വദിക്കൂ",
    "Spontan" to "സ്വയമേവ",
    "Sportplatz" to "സ്പോർട്സ് ഫീൽഡ്",
    "Spotify" to "Spotify",
    "Sprache" to "ഭാഷ",
    "Stadt" to "നഗരം",
    "Stadt oder Land — was ist uns wichtiger?" to "നഗരം അല്ലെങ്കിൽ രാജ്യം - എന്താണ് ഞങ്ങൾക്ക് കൂടുതൽ പ്രധാനം?",
    "Stadtvilla" to "സിറ്റി വില്ല",
    "Standesamt & Party" to "രജിസ്ട്രി ഓഫീസും പാർട്ടിയും",
    "Statement-Ring" to "പ്രസ്താവന മോതിരം",
    "Stilvolles Outdoor-Sofa" to "സ്റ്റൈലിഷ് ഔട്ട്‌ഡോർ സോഫ",
    "Stimme voll zu" to "പൂർണ്ണമായും സമ്മതിക്കുന്നു",
    "Stimmt" to "ശരിയാണ്",
    "Stimmt nicht" to "ശരിയല്ല",
    "Stimmt, noch nie" to "ശരിയാണ്, ഒരിക്കലും",
    "Stracciatella" to "സ്ട്രാസിയാറ്റെല്ല",
    "Strandtag" to "ബീച്ച് ദിനം",
    "Streit über Haushalt" to "വീട്ടുകാരുമായി ബന്ധപ്പെട്ട തർക്കം",
    "Studio Ghibli" to "സ്റ്റുഡിയോ ഗിബ്ലി",
    "Ständig" to "നിരന്തരം",
    "Suche schließen" to "തിരയൽ അടയ്ക്കുക",
    "Suche zurücksetzen" to "തിരയൽ പുനഃസജ്ജമാക്കുക",
    "Suche öffnen" to "തിരയൽ തുറക്കുക",
    "Suchergebnisse" to "തിരയൽ ഫലങ്ങൾ",
    "Sushi" to "സുഷി",
    "Süß" to "മധുരം",
    "Tage zusammen 💞" to "ദിവസങ്ങൾ ഒരുമിച്ച് 💞",
    "Tauche ins Unterbewusstsein" to "ഉപബോധമനസ്സിലേക്ക് മുങ്ങുക",
    "Teile alle deine Hobbys mit deinem Partner" to "നിങ്ങളുടെ എല്ലാ ഹോബികളും പങ്കാളിയുമായി പങ്കിടുക",
    "Teils teils" to "ഭാഗികമായി ഭാഗികമായി",
    "Testen" to "ടെസ്റ്റ്",
    "Themen" to "വിഷയങ്ങൾ",
    "Tiefe Gespräche" to "ആഴത്തിലുള്ള സംഭാഷണങ്ങൾ",
    "Tiefgründige Gespräche führen" to "ആഴത്തിലുള്ള സംഭാഷണങ്ങൾ നടത്തുക",
    "Tierpension" to "ആനിമൽ ബോർഡിംഗ് ഹൗസ്",
    "Tiny House" to "ചെറിയ വീട്",
    "Tippen zum Auswählen & Scrollen" to "തിരഞ്ഞെടുത്ത് സ്ക്രോൾ ചെയ്യാൻ ടാപ്പ് ചെയ്യുക",
    "Tippen zum Zuklappen" to "ചുരുക്കാൻ ടാപ്പ് ചെയ്യുക",
    "Titel" to "തലക്കെട്ട്",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "ശീർഷകം, വിഭാഗം, വിഷയം, ടാഗുകൾ, ചോദ്യങ്ങൾ...",
    "Tokyo, Japan" to "ടോക്കിയോ, ജപ്പാൻ",
    "Traditioneller Name" to "പരമ്പരാഗത നാമം",
    "Traumhaus Außenbereich" to "ഡ്രീം ഹൗസ് ഔട്ട്ഡോർ ഏരിയ",
    "Traumhochzeit" to "സ്വപ്ന കല്യാണം",
    "Treffer" to "ഹിറ്റ്",
    "Tägliche Aktivität" to "പ്രതിദിന പ്രവർത്തനം",
    "Umformulieren" to "പുനരാവിഷ്കാരം",
    "Unbeantwortet" to "ഉത്തരമില്ല",
    "Unbeliebte Meinungen" to "ജനപ്രീതിയില്ലാത്ത അഭിപ്രായങ്ങൾ",
    "Universal Studios Genie oder Neuling?" to "യൂണിവേഴ്സൽ സ്റ്റുഡിയോയിലെ പ്രതിഭയാണോ അതോ പുതുമുഖമാണോ?",
    "Uns auseinanderzuleben" to "വേർപിരിയാൻ",
    "Unser Intimleben" to "ഞങ്ങളുടെ അടുപ്പമുള്ള ജീവിതം",
    "Unser Traumhaus" to "ഞങ്ങളുടെ സ്വപ്ന ഭവനം",
    "Unser erstes Treffen" to "ഞങ്ങളുടെ ആദ്യ മീറ്റിംഗ്",
    "Unsere Gesichter" to "ഞങ്ങളുടെ മുഖങ്ങൾ",
    "Unsere eigenen Träume" to "നമ്മുടെ സ്വന്തം സ്വപ്നങ്ങൾ",
    "Unsere nächste Reise" to "ഞങ്ങളുടെ അടുത്ത യാത്ര",
    "Unter 1000" to "1000-ത്തിൽ താഴെ",
    "Unter 1000 im Monat" to "പ്രതിമാസം 1000-ത്തിൽ താഴെ",
    "Unter 50€/Monat" to "50€/മാസം",
    "Unter Leuten" to "ആളുകൾക്കിടയിൽ",
    "Untreue" to "അവിശ്വാസം",
    "Urlaub" to "അവധിക്കാലം",
    "Vanille" to "വാനില",
    "Venedig" to "വെനീസ്",
    "Venedig, Italien" to "വെനീസ്, ഇറ്റലി",
    "Verbinde dich mit" to "ഇതുമായി ബന്ധിപ്പിക്കുക",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "ഉത്തരം കാണുന്നതിന് \${profile.partnerName}-ലേക്ക് കണക്റ്റുചെയ്യുക",
    "Verbindung" to "കണക്ഷൻ",
    "Verbringe die Feiertage mit deiner Familie" to "നിങ്ങളുടെ കുടുംബത്തോടൊപ്പം അവധിക്കാലം ചെലവഴിക്കുക",
    "Verlobungsringe" to "വിവാഹനിശ്ചയ വളയങ്ങൾ",
    "Vertrautheit" to "പരിചയം",
    "Viel getrennt" to "ഒരുപാട് വേർപിരിയൽ",
    "Vielleicht ein oder zwei" to "ഒന്നോ രണ്ടോ ആയിരിക്കാം",
    "Vielleicht, aber mündlich reicht" to "ഒരുപക്ഷെ, പക്ഷേ വാക്കാൽ മതി",
    "Vielleicht, wenn es machbar ist" to "ഒരുപക്ഷേ, സാധ്യമെങ്കിൽ",
    "Vielleicht, wenn es passt" to "ഒരുപക്ഷേ, അനുയോജ്യമാണെങ്കിൽ",
    "Vintage Art déco" to "വിൻ്റേജ് ആർട്ട് ഡെക്കോ",
    "Vintage verspielt" to "വിൻ്റേജ് കളി",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "നിങ്ങളുടെ പങ്കാളി പുതിയ ഹോബികൾ പരിചയപ്പെടുത്തുന്നു",
    "Vor dem Kauf eines Hauses besprechen" to "ഒരു വീട് വാങ്ങുന്നതിന് മുമ്പ് ചർച്ച ചെയ്യുക",
    "Vor der Anschaffung eines Haustiers besprechen" to "ഒരു വളർത്തുമൃഗത്തെ വാങ്ങുന്നതിന് മുമ്പ് ചർച്ച ചെയ്യുക",
    "Vor der gemeinsamen Reise besprechen" to "ഒരുമിച്ച് യാത്ര ചെയ്യുന്നതിന് മുമ്പ് ചർച്ച ചെയ്യുക",
    "Vor nichts" to "ഒന്നുമില്ല",
    "Vorort" to "സബർബ്",
    "Walnuss" to "വാൽനട്ട്",
    "Wandern" to "കാൽനടയാത്ര",
    "Wann fühlst du dich mir am nächsten?" to "എപ്പോഴാണ് നിങ്ങൾക്ക് എന്നോട് ഏറ്റവും അടുത്തതായി തോന്നുന്നത്?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "എപ്പോഴാണ് നിങ്ങൾക്ക് എന്നോട് ശാരീരികമായി കൂടുതൽ അടുപ്പം തോന്നുന്നത്?",
    "Was bedeutet Vertrauen für dich konkret?" to "വിശ്വാസം നിങ്ങൾക്ക് പ്രത്യേകമായി എന്താണ് അർത്ഥമാക്കുന്നത്?",
    "Was entspannt dich mehr?" to "എന്താണ് നിങ്ങളെ കൂടുതൽ ആശ്വസിപ്പിക്കുന്നത്?",
    "Was fehlt dir über die Distanz am meisten?" to "ദൂരത്തെക്കുറിച്ച് നിങ്ങൾക്ക് ഏറ്റവും കൂടുതൽ നഷ്ടമാകുന്നത് എന്താണ്?",
    "Was gefällt dir an deinem Zuhause am besten?" to "നിങ്ങളുടെ വീടിനെക്കുറിച്ച് നിങ്ങൾക്ക് ഏറ്റവും ഇഷ്ടപ്പെട്ടത് എന്താണ്?",
    "Was hast du von deinem Partner gelernt?" to "നിങ്ങളുടെ പങ്കാളിയിൽ നിന്ന് നിങ്ങൾ എന്താണ് പഠിച്ചത്?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "ലൈംഗിക ഉള്ളടക്കം ഒരുമിച്ച് കാണുന്നതിനെക്കുറിച്ച് നിങ്ങൾ എന്താണ് ചിന്തിക്കുന്നത്?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "പ്രോപ്പുകളെ കുറിച്ച് (ഉദാ. അടയാളങ്ങൾ, ബലൂണുകൾ മുതലായവ) നിങ്ങൾ എന്താണ് ചിന്തിക്കുന്നത്?",
    "Was ist das Wichtigste beim Antrag?" to "അപേക്ഷിക്കുമ്പോൾ ഏറ്റവും പ്രധാനപ്പെട്ട കാര്യം എന്താണ്?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "ലൈംഗിക ബന്ധത്തിൽ നിങ്ങൾ ഏറ്റവും പ്രധാനപ്പെട്ട കാര്യം എന്താണ്?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "ഞങ്ങളുടെ പ്രിയപ്പെട്ട ഫോട്ടോ ഏതാണ്? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "ഒരുമിച്ച് ജീവിക്കുന്നതിൽ നിങ്ങളുടെ ഏറ്റവും വലിയ ഭയം എന്താണ്?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "നിങ്ങൾ ഇഷ്ടപ്പെടുന്നതും എന്നാൽ നിങ്ങളുടെ പങ്കാളിക്ക് മനസ്സിലാക്കാൻ കഴിയാത്തതുമായ ഭക്ഷണം ഏതാണ്?",
    "Was ist für dich ein absoluter Dealbreaker?" to "നിങ്ങൾക്ക് ഒരു സമ്പൂർണ്ണ ഡീൽ ബ്രേക്കർ എന്താണ്?",
    "Was ist für jeden von uns das absolute Highlight?" to "എന്താണ് നമുക്ക് ഓരോരുത്തർക്കും ഉള്ള ഹൈലൈറ്റ്?",
    "Was ist passiert?" to "എന്താണ് സംഭവിച്ചത്?",
    "Was macht einen Moment für dich romantisch?" to "എന്താണ് നിങ്ങൾക്ക് ഒരു നിമിഷത്തെ റൊമാൻ്റിക് ആക്കുന്നത്?",
    "Was magst du an deinem Partner am liebsten?" to "നിങ്ങളുടെ പങ്കാളിയെക്കുറിച്ച് നിങ്ങൾക്ക് ഏറ്റവും ഇഷ്ടപ്പെട്ടത് എന്താണ്?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "നിങ്ങൾക്ക് എന്താണ് കൂടുതൽ ഇഷ്ടം: നേരത്തെ എഴുന്നേൽക്കണോ അതോ വൈകി എഴുന്നേൽക്കണോ?",
    "Was magst du lieber?" to "ഏതാണ് നിങ്ങൾക്ക് കൂടുതൽ ഇഷ്ടം?",
    "Was möchtest du eigentlich sagen?" to "നിങ്ങൾ യഥാർത്ഥത്തിൽ എന്താണ് പറയാൻ ആഗ്രഹിക്കുന്നത്?",
    "Was möchtest du, dass dein Partner öfter tut?" to "നിങ്ങളുടെ പങ്കാളി കൂടുതൽ തവണ എന്തുചെയ്യണമെന്നാണ് നിങ്ങൾ ആഗ്രഹിക്കുന്നത്?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "നമ്മൾ യാത്ര ചെയ്യുമ്പോൾ മൃഗത്തിന് എന്ത് സംഭവിക്കും?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "നമ്മുടെ കുട്ടി വളരുമ്പോൾ എന്തായിരിക്കും?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "മാതാപിതാക്കളെന്ന നിലയിൽ നമുക്ക് ഒരിക്കലും നഷ്ടപ്പെടാൻ പാടില്ലാത്തത് എന്താണ്?",
    "Was war dein schönster Moment mit mir bisher?" to "എന്നോടൊപ്പമുള്ള നിങ്ങളുടെ ഏറ്റവും മികച്ച നിമിഷം ഏതാണ്?",
    "Was wir gegessen haben" to "ഞങ്ങൾ കഴിച്ചത്",
    "Was wollt ihr nie vergessen?" to "നിങ്ങൾ ഒരിക്കലും മറക്കാൻ ആഗ്രഹിക്കാത്തത് എന്താണ്?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "നിങ്ങൾക്ക് ഏറ്റവും മോശമായത് എന്തായിരിക്കും: ഇനി ഒരിക്കലും പിസ്സ കഴിക്കരുത് അല്ലെങ്കിൽ ഇനി ഒരിക്കലും ബർഗർ ചെയ്യരുത്?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "ഒരുമിച്ചുള്ള ഒരു ദിവസം നിങ്ങൾ ഏറ്റവും കൂടുതൽ എന്താണ് ചെയ്യാൻ ആഗ്രഹിക്കുന്നത്?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "പണം ഒരു പ്രശ്നമല്ലെങ്കിൽ നിങ്ങൾ ഉടനടി എന്ത് മാറ്റും?",
    "Weiter" to "അടുത്തത്",
    "Weiter spielen" to "കളിക്കുന്നത് തുടരുക",
    "Weiß ich noch nicht" to "എനിക്കിതുവരെ അറിയില്ല",
    "Weiße Rosen" to "വെളുത്ത റോസാപ്പൂക്കൾ",
    "Weißgold" to "വെളുത്ത സ്വർണ്ണം",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "നമ്മുടെ കുട്ടിക്ക് നമ്മിൽ നിന്ന് എന്ത് ഗുണമേന്മയാണ് ലഭിക്കേണ്ടത്?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "ഒരു നിർദ്ദേശത്തിന് നിങ്ങൾ എന്ത് അന്തരീക്ഷമാണ് ആഗ്രഹിക്കുന്നത്?",
    "Welcher Raum sagt am meisten über dich aus?" to "ഏത് മുറിയാണ് നിങ്ങളെ കുറിച്ച് കൂടുതൽ പറയുന്നത്?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "ഭക്ഷണത്തിനും വെറ്റിനും വേണ്ടി ഞങ്ങൾ എന്ത് ബജറ്റാണ് പ്ലാൻ ചെയ്യുന്നത്?",
    "Welches Lied macht dich an? 🥵" to "ഏത് ഗാനമാണ് നിങ്ങളെ ഓണാക്കുന്നത്? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "ഏത് പങ്കിട്ട ഫോട്ടോയാണ് നിങ്ങൾക്ക് പ്രിയപ്പെട്ടത്?",
    "Wellnessbad" to "വെൽനസ് ബാത്ത്",
    "Wenn es schwierig ist" to "കാര്യങ്ങൾ ബുദ്ധിമുട്ടുള്ളപ്പോൾ",
    "Wenn ich müde bin" to "ഞാൻ തളർന്നിരിക്കുമ്പോൾ",
    "Wenn wir uns lange umarmen" to "ഞങ്ങൾ ദീർഘനേരം കെട്ടിപ്പിടിക്കുമ്പോൾ",
    "Wenn wir zusammen lachen" to "നമ്മൾ ഒരുമിച്ച് ചിരിക്കുമ്പോൾ",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "എന്താണ് ഓർഡർ ചെയ്യേണ്ടതെന്ന് ആരാണ് കൂടുതൽ വേഗത്തിൽ തീരുമാനിക്കുന്നത്?",
    "Wer findet die besten Restaurants?" to "ആരാണ് മികച്ച റെസ്റ്റോറൻ്റുകൾ കണ്ടെത്തുന്നത്?",
    "Wer gibt mehr Herzlichkeit?" to "ആരാണ് കൂടുതൽ ഊഷ്മളത നൽകുന്നത്?",
    "Wer hat den besseren Musikgeschmack?" to "ആർക്കാണ് സംഗീതത്തിൽ മികച്ച അഭിരുചിയുള്ളത്?",
    "Wer hängt mehr an seinen Eltern?" to "ആരാണ് അവരുടെ മാതാപിതാക്കളോട് കൂടുതൽ അടുപ്പമുള്ളത്?",
    "Wer ist besser organisiert?" to "ആരാണ് മികച്ച സംഘടിതർ?",
    "Wer ist der Beste bei der Filmauswahl?" to "സിനിമകൾ തിരഞ്ഞെടുക്കുന്നതിൽ ആരാണ് മികച്ചത്?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "റൊമാൻ്റിക് തീയതികൾ ആസൂത്രണം ചെയ്യുന്നതിൽ ആരാണ് മികച്ചത്?",
    "Wer ist der beste Tänzer?" to "ആരാണ് മികച്ച നർത്തകി?",
    "Wer ist romantischer?" to "ആരാണ് കൂടുതൽ റൊമാൻ്റിക്?",
    "Wer kocht besser?" to "ആരാണ് നന്നായി പാചകം ചെയ്യുന്നത്?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "ആരാണ് നവീകരണവും പരിപാലനവും നടത്തുന്നത്?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "മറ്റൊരാൾക്ക് സുഖമില്ലെങ്കിൽ ആരാണ് വേഗത്തിൽ ശ്രദ്ധിക്കുന്നത്?",
    "Wer sucht am Ende wirklich den Film aus?" to "ഒടുവിൽ ആരാണ് സിനിമ തിരഞ്ഞെടുക്കുന്നത്?",
    "Wer vergisst eher einen Jahrestag?" to "ആർക്കാണ് വാർഷികം മറക്കാൻ കൂടുതൽ സാധ്യത?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "അടുത്ത ദിവസം രാവിലെ ആരാണ് സ്വന്തം പേര് മറക്കാൻ കൂടുതൽ സാധ്യത?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "ആർക്കും ഒന്നും അറിയാത്ത ഒരു വീഡിയോ അടുത്ത ദിവസം കണ്ടെത്താൻ ആരാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "ആരാണ് അപരിചിതൻ്റെ സോഫയിൽ രാത്രി ചെലവഴിക്കുന്നത്?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "ഒരു പാർട്ടിയിൽ ഉറങ്ങാനും ഷാർപ്പി മുഖത്ത് നോക്കി എഴുന്നേൽക്കാനും ആർക്കാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "ഡാൻസ് ഫ്‌ളോറിൽ വഴുതി വീഴാൻ കൂടുതൽ സാധ്യതയുള്ളവർ ആരായിരിക്കും, പക്ഷേ അത് ഒരു രസകരമായ നീക്കമായി തോന്നും?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "ഒരു ഹൗസ് പാർട്ടിയിൽ ആരാണ് Spotify പ്ലേലിസ്റ്റിൻ്റെ നിയന്ത്രണം ഏറ്റെടുക്കാൻ കൂടുതൽ സാധ്യത?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "പാർട്ടിയിൽ എല്ലാവർക്കും പിസ്സ ഓർഡർ ചെയ്യാനും അത് സ്വയം കഴിക്കാനും ആർക്കാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "പാർട്ടിയിൽ ആരാണ് ആദ്യം ഉറങ്ങാൻ സാധ്യത?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "ഒരു പാർട്ടിയിൽ പെട്ടെന്ന് വൃത്തിയാക്കാൻ തുടങ്ങാൻ ആരാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "നേരെ വിപരീതമായിരിക്കുമ്പോൾ ആർക്കാണ് പൂർണ്ണമായും ശാന്തനാണെന്ന് അവകാശപ്പെടാൻ കൂടുതൽ സാധ്യത?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "ആർക്കാണ് തർക്കത്തിൽ ആദ്യം വഴങ്ങാൻ സാധ്യത?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "മദ്യപാന ഗെയിമിൽ ആരാണ് കൂടുതൽ ചതിക്കാൻ സാധ്യതയുള്ളത്?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "ബുഫെ റെയ്ഡ് ചെയ്യാനും രഹസ്യമായി ഭക്ഷണം വീട്ടിലേക്ക് കൊണ്ടുപോകാനും ആർക്കാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "വൈകുന്നേരത്തെ ഏറ്റവും ലജ്ജാകരമായ ഫോട്ടോ അവരുടെ കഥയിൽ പോസ്റ്റ് ചെയ്യാൻ ആരാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "സ്വന്തം ഇഷ്ടഗാനം അഭ്യർത്ഥിക്കാൻ ഡിജെയെ ശല്യപ്പെടുത്താൻ ആർക്കാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "ഒരു ഗാനത്തിൻ്റെ വരികൾ ആലപിക്കാൻ ആരാണ് കൂടുതൽ സാധ്യതയുള്ളത്, പക്ഷേ ബോധ്യത്തോടെ?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "മെനുവിലെ ഏറ്റവും ചെലവേറിയ പാനീയം ഓർഡർ ചെയ്യാനും അതിൽ ഖേദിക്കാനും ആർക്കാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "ബഹളത്തെക്കുറിച്ച് പരാതിപ്പെട്ടാൽ അയൽവാസികൾ ആരായിരിക്കും അവരെ ക്ഷണിക്കാൻ കൂടുതൽ സാധ്യത?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "പാർട്ടി ഗെയിമുകൾ (ബിയർ പോംഗ് പോലെയുള്ളത്) ആരാണ് ഗൗരവമായി എടുക്കുക?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "വിഐപി ആക്‌സസ് ലഭിക്കാൻ ബൗൺസർമാരുമായി ചങ്ങാത്തം കൂടാൻ ആരാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "ആർക്കാണ് സ്വതസിദ്ധമായ കരോക്കെ യുദ്ധം ആരംഭിക്കാൻ കൂടുതൽ സാധ്യത?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "ബോട്ടിൽ ഓപ്പണർ ഉപയോഗിക്കാതെ ആരാണ് കുപ്പി തുറക്കാൻ കൂടുതൽ സാധ്യത?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "ആരും ചോദിച്ചില്ലെങ്കിലും ആരാണ് പ്രസംഗം നടത്താൻ കൂടുതൽ സാധ്യത?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "കുളിമുറിയിൽ സെൽഫിയെടുക്കാൻ ആർക്കാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "നാണംകെട്ട ഒരു നൃത്തപ്രകടനം നടത്താനും അത് ആഘോഷിക്കാനും ആർക്കാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "പാർട്ടി അവസാനിച്ചതിന് ശേഷം ആരാണ് മുൻ പങ്കാളിയെ വിളിക്കാൻ കൂടുതൽ സാധ്യത?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "ഒരു വിചിത്ര അതിഥിയെ ആകസ്മികമായി വ്രണപ്പെടുത്താൻ ആരാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "വിട പറയാതെ ആരാണ് രഹസ്യമായി പാർട്ടി വിടാൻ കൂടുതൽ സാധ്യത?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "അതിഥികളോട് സംസാരിക്കുന്നതിനേക്കാൾ ആതിഥേയൻ്റെ വളർത്തുമൃഗത്തോടൊപ്പം കളിക്കാൻ ആർക്കാണ് ഇഷ്ടം?",
    "Wer würde eher spontan eine Reise buchen?" to "ആർക്കാണ് സ്വയമേവ ഒരു യാത്ര ബുക്ക് ചെയ്യാൻ കൂടുതൽ സാധ്യത?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "ആരാണ് അടുക്കളയിൽ മണിക്കൂറുകളോളം ആഴത്തിലുള്ള സംഭാഷണങ്ങൾ നടത്താൻ കൂടുതൽ സാധ്യത?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "മറ്റാരുടെയെങ്കിലും പാനീയം ആകസ്മികമായി കുടിക്കാൻ ആരാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "വിലകൂടിയ പാത്രമോ ദുർബലമായ മറ്റെന്തെങ്കിലുമോ ആകസ്മികമായി തട്ടിയെടുക്കാൻ ആർക്കാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "സങ്കീർണ്ണമായ ഒരു കോക്ടെയ്ൽ സ്വയം കലർത്തി ദയനീയമായി പരാജയപ്പെടാൻ ആർക്കാണ് കൂടുതൽ സാധ്യത?",
    "Wer würde eher zu spät kommen?" to "ആരാണ് വൈകാൻ കൂടുതൽ സാധ്യത?",
    "Wer würde eher?" to "ആർക്കാണ് കൂടുതൽ ഇഷ്ടം?",
    "Wer übernimmt die tägliche Versorgung?" to "ആരാണ് ദൈനംദിന പരിചരണം നടത്തുന്നത്?",
    "Werde so akzeptiert, wie du bist" to "നിങ്ങളെപ്പോലെ തന്നെ അംഗീകരിക്കുക",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "കുട്ടിക്ക്/കുട്ടികൾക്ക് വേണ്ടത്ര സമയം ലഭിക്കുമോ? ⏳",
    "Whirlpool" to "ഹോട്ട് ടബ്",
    "White Chocolate" to "വൈറ്റ് ചോക്ലേറ്റ്",
    "Widgets" to "വിജറ്റുകൾ",
    "Wie fühlst du dich am meisten geliebt?" to "നിങ്ങൾക്ക് ഏറ്റവും പ്രിയപ്പെട്ടതായി എങ്ങനെ തോന്നുന്നു?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "വ്യത്യസ്‌ത വരുമാനങ്ങളുമായി ഞങ്ങൾ എങ്ങനെ ഇടപെടും?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "നിങ്ങളുമായി ലൈംഗിക ബന്ധത്തിൽ ഏർപ്പെടാൻ നിങ്ങളുടെ പങ്കാളിക്ക് ഏറ്റവും നല്ല മാർഗം ഏതാണ്?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "എങ്ങനെയാണ് നിങ്ങളുടെ പങ്കാളി നിങ്ങൾക്ക് കൂടുതൽ മികച്ച പങ്കാളിയാകുന്നത്?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "നിർദ്ദേശം കഴിഞ്ഞ് എത്ര കാലം കഴിഞ്ഞ് മറ്റുള്ളവരുമായി ആഘോഷിക്കാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നു?",
    "Wie lange wollen wir dort mindestens bleiben?" to "ഞങ്ങൾ അവിടെ എത്ര കാലമെങ്കിലും താമസിക്കാൻ ആഗ്രഹിക്കുന്നു?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "ആഗ്രഹങ്ങളെക്കുറിച്ച് സംസാരിക്കുന്നത് നിങ്ങൾക്ക് എത്ര എളുപ്പമാണ്?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "ഞങ്ങളുടെ ഭാവി എങ്ങനെയായിരിക്കണമെന്നാണ് നിങ്ങൾ ആഗ്രഹിക്കുന്നത്?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "വീട്ടിലെ നിങ്ങളുടെ തികഞ്ഞ ഞായറാഴ്ച എങ്ങനെയിരിക്കും?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "ലൈംഗികവേളയിൽ വൃത്തികെട്ട സംസാരത്തെക്കുറിച്ച് നിങ്ങൾക്ക് എന്തു തോന്നുന്നു?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "യഥാർത്ഥത്തിൽ നമുക്ക് എത്ര ക്രെഡിറ്റ് താങ്ങാൻ കഴിയും?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "നമ്മൾ എത്ര സമയം വേറിട്ട് ചെലവഴിക്കാൻ ആഗ്രഹിക്കുന്നു?",
    "Wie viel wollen wir insgesamt ausgeben?" to "മൊത്തത്തിൽ ഞങ്ങൾ എത്രമാത്രം ചെലവഴിക്കാൻ ആഗ്രഹിക്കുന്നു?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "കുഞ്ഞ് വന്നാൽ എങ്ങനെ നമ്മുടെ ബന്ധത്തിന് സമയം കണ്ടെത്തും?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "ആ നിമിഷം പകർത്തുന്നത് നിങ്ങൾക്ക് എത്രത്തോളം പ്രധാനമാണ്?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "ആപ്ലിക്കേഷൻ നിങ്ങളുടെ ഹോബികളെയോ താൽപ്പര്യങ്ങളെയോ പ്രതിഫലിപ്പിക്കുന്നു എന്നത് നിങ്ങൾക്ക് എത്രത്തോളം പ്രധാനമാണ്?",
    "Wie würdest du sie/ihn nennen?" to "നിങ്ങൾ അവനെ/അവളെ എന്ത് വിളിക്കും?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "ലൈംഗികതയ്ക്ക് പുറത്ത് സ്‌നേഹം പ്രകടിപ്പിക്കാനുള്ള നിങ്ങളുടെ പ്രിയപ്പെട്ട മാർഗം ഏതാണ്?",
    "Wildblumen" to "കാട്ടുപൂക്കൾ",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "നിങ്ങൾക്ക് ഒരു പെൺകുട്ടിയെ വേണോ ആൺകുട്ടിയെ വേണോ? 👶",
    "Wintergarten" to "ശീതകാല പൂന്തോട്ടം",
    "Winterhochzeit" to "ശീതകാല വിവാഹം",
    "Wir bestellen einfach beides" to "ഞങ്ങൾ രണ്ടും ഓർഡർ ചെയ്യുന്നു",
    "Wir brauchen ewig" to "അത് നമ്മെ എന്നെന്നേക്കുമായി കൊണ്ടുപോകുന്നു",
    "Wir einigen uns nie" to "ഞങ്ങൾ ഒരിക്കലും സമ്മതിക്കുന്നില്ല",
    "Wir entscheiden es gemeinsam" to "ഞങ്ങൾ ഒരുമിച്ച് തീരുമാനിക്കും",
    "Wir treffen uns in der Mitte" to "ഞങ്ങൾ മധ്യത്തിൽ കണ്ടുമുട്ടുന്നു",
    "Wir wechseln uns ab" to "ഞങ്ങൾ മാറിമാറി എടുക്കുന്നു",
    "Wird stressig" to "സമ്മർദ്ദത്തിലാകുന്നു",
    "Wobei lachst du am meisten?" to "നിങ്ങളെ ഏറ്റവും കൂടുതൽ ചിരിപ്പിക്കുന്നത് എന്താണ്?",
    "Wofür sparen wir gemeinsam?" to "നമ്മൾ ഒരുമിച്ച് എന്തിനുവേണ്ടിയാണ് ലാഭിക്കുന്നത്?",
    "Wohnzimmer" to "സ്വീകരണമുറി",
    "Woran erinnerst du dich am lebhaftesten?" to "എന്താണ് നിങ്ങൾ ഏറ്റവും വ്യക്തമായി ഓർക്കുന്നത്?",
    "Worauf freust du dich bei uns am meisten?" to "നിങ്ങൾ ഞങ്ങളോടൊപ്പം ഏറ്റവും കൂടുതൽ പ്രതീക്ഷിക്കുന്നത് എന്താണ്?",
    "Worte/Komplimente" to "വാക്കുകൾ/അഭിനന്ദനങ്ങൾ",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "ഞങ്ങളുടെ ബന്ധത്തിൽ നിങ്ങൾ ഏറ്റവും ഭയപ്പെടുന്നത് എന്തിനെയാണ്?",
    "Wünsche? z.B. günstig, draußen" to "ആഗ്രഹങ്ങൾ? ഉദാ. വിലകുറഞ്ഞ, പുറത്ത്",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "അവധിക്കാലത്ത് (യാത്ര ഉൾപ്പെടുന്ന) പ്രൊപ്പോസ് ചെയ്യാൻ നിങ്ങൾക്ക് താൽപ്പര്യമുണ്ടോ?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube സംഗീതം",
    "Zeichne für mich" to "എനിക്കായി വരയ്ക്കുക",
    "Zeichne mich als Tier — welches wäre ich?" to "എന്നെ ഒരു മൃഗമായി വരയ്ക്കുക - ഞാൻ ആരായിരിക്കും?",
    "Zeichne unser Gefühl zueinander als Symbol." to "ഒരു പ്രതീകമായി നമ്മുടെ വികാരങ്ങൾ പരസ്പരം വരയ്ക്കുക.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "ഞങ്ങളുടെ സ്വപ്ന ഭവനം ഒരു വരിയിൽ വരയ്ക്കുക. ഏറ്റവും ശ്രദ്ധേയമായ കാര്യം എന്താണ്?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "ഞങ്ങളുടെ ആദ്യ തീയതി വരയ്ക്കുക - ചിത്രത്തിൽ തീർച്ചയായും എന്താണ് ഉണ്ടായിരിക്കേണ്ടത്?",
    "Zeichnen" to "വരയ്ക്കുക",
    "Zeit füreinander" to "പരസ്പരം സമയം",
    "Zeit, wenn das Baby schläft" to "കുഞ്ഞ് ഉറങ്ങുന്ന സമയം",
    "Zelten gehen" to "ക്യാമ്പിംഗിന് പോകൂ",
    "Zitrone" to "നാരങ്ങ",
    "Zu Hause, gemütlich und privat" to "വീട്ടിൽ, സുഖകരവും സ്വകാര്യവും",
    "Zu einem Picknick gehen" to "ഒരു പിക്നിക്കിന് പോകുന്നു",
    "Zu einem ausgefallenen Abendessen gehen" to "ഒരു ഫാൻസി ഡിന്നറിന് പോകുന്നു",
    "Zu zweit reisen" to "ദമ്പതികളായി യാത്ര ചെയ്യുക",
    "Zuhause & Alltag" to "വീടും ദൈനംദിന ജീവിതവും",
    "Zuhören" to "കേൾക്കൂ",
    "Zurück" to "തിരികെ",
    "Zusammen seit" to "മുതൽ ഒരുമിച്ച്",
    "Zusammen seit (TT.MM.JJJJ)" to "മുതൽ ഒരുമിച്ച് (DD.MM.YYYY)",
    "Zusammenziehen" to "കരാർ",
    "Zustimmen oder Ablehnen" to "സമ്മതിക്കുകയോ വിയോജിക്കുകയോ ചെയ്യുക",
    "Zwei Kreise, die sich überschneiden" to "ഓവർലാപ്പ് ചെയ്യുന്ന രണ്ട് സർക്കിളുകൾ",
    "Zwei Stühle davor" to "അതിന് മുന്നിൽ രണ്ട് കസേരകൾ",
    "Zärtlich sein" to "മൃദുവായിരിക്കുക",
    "Öfter als ich zugebe" to "ഞാൻ സമ്മതിക്കുന്നതിനേക്കാൾ കൂടുതൽ തവണ",
    "Über 100€/Monat" to "100€/മാസം",
    "Über 2000 im Monat" to "പ്രതിമാസം 2000-ത്തിലധികം",
    "Über mich selbst" to "എന്നെ കുറിച്ച്",
    "Übernehmen" to "പ്രയോഗിക്കുക",
    "Überraschend" to "ആശ്ചര്യപ്പെടുത്തുന്നു",
    "Überraschung" to "ആശ്ചര്യം",
    "Überspringen" to "ഒഴിവാക്കുക",
    "Übertrieben und großartig" to "ഏറ്റവും മികച്ചതും ആകർഷകവുമാണ്",
    "✎ Tippe, um zu antworten" to "✎ മറുപടി നൽകാൻ ടാപ്പ് ചെയ്യുക",
    "✨ GFK-Brücke" to "✨ GRP പാലം",
)

internal fun localizeMalayalamDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_MALAYALAM_CONTENT)
