package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_MARATHI_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 वर्षे",
    "1000 - 1500 im Monat" to "1000 - 1500 प्रति महिना",
    "1000 bis 3000" to "1000 ते 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 प्रति महिना",
    "3000 bis 5000" to "3000 ते 5000",
    "5-10 Jahre" to "5-10 वर्षे",
    "50-100€/Monat" to "50-100€/महिना",
    "Ab 100€" to "100€ पासून",
    "Ab 500€" to "500€ पासून",
    "Ab 50€" to "50€ पासून",
    "Ab und zu" to "प्रत्येक वेळी आणि नंतर",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "खरेदी करण्यापूर्वी आम्हाला किती खर्च करावा लागेल?",
    "Abbrechen" to "रद्द करा",
    "Abenteuer" to "साहस",
    "Adidas" to "आदिदास",
    "Aktivitäten" to "उपक्रम",
    "Alle" to "सर्व",
    "Alle Pakete" to "सर्व पॅकेजेस",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "तुमचा सर्वात चांगला मित्र सोडून तुमचे सर्व मित्र गमावा",
    "Alle intimen Momente selbst initiieren" to "सर्व जिव्हाळ्याचे क्षण स्वतःच सुरू करा",
    "Alles davon" to "हे सर्व",
    "Alles, was noch kommt" to "येणारे सर्व काही",
    "Alltagsroutine" to "रोजचा दिनक्रम",
    "Alltägliche Berührungen" to "रोजचा स्पर्श",
    "Altbau mit Charme" to "मोहिनी असलेली जुनी इमारत",
    "Am Strand" to "समुद्रकिनाऱ्यावर",
    "Am liebsten alles zusammen" to "शक्यतो सर्वकाही एकत्र",
    "Am selben Tag mit Freunden/Familie" to "त्याच दिवशी मित्र/कुटुंबासोबत",
    "Amazon" to "Amazon",
    "Amsterdam" to "आम्सटरडॅम",
    "Amsterdam, Niederlande" to "आम्सटरडॅम, नेदरलँड",
    "An das Gefühl" to "भावना",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "अनेक प्रेक्षकांसह सार्वजनिक ठिकाणी",
    "An einen Geruch" to "वासाचा",
    "An einen Song" to "गाण्यासाठी",
    "An etwas, das ich gesagt habe" to "मी म्हणालो काहीतरी",
    "Analyse starten" to "विश्लेषण सुरू करा",
    "Analysiere eure Muster..." to "तुमच्या पॅटर्नचे विश्लेषण करा...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Gottman आणि GFK नुसार तुमची उत्तरे आणि चॅटचे विश्लेषण करा.",
    "Ananas auf der Pizza schmeckt köstlich." to "पिझ्झावर अननस चवदार लागते.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "फोटोसह उत्तर द्या",
    "Antwortähnlichkeit" to "उत्तर समानता",
    "App-Sprache auswählen" to "ॲप भाषा निवडा",
    "Auf eine Bootsparty gehen" to "बोट पार्टीला जात आहे",
    "Aufmerksamkeit" to "लक्ष द्या",
    "Aufräumen und Projekte angehen" to "प्रकल्प साफ करा आणि हाताळा",
    "Aufwärmen" to "वार्म अप",
    "Aufwärmen: Einander kennenlernen" to "वार्म-अप: एकमेकांना जाणून घेणे",
    "Aus dem Urlaub" to "सुट्टीपासून",
    "Ausgefallener Name" to "फॅन्सी नाव",
    "Ausschlafen und faulenzen" to "झोपा आणि आजूबाजूला आळशी व्हा",
    "Ausschlafen und nichts tun" to "झोपा आणि काहीही करू नका",
    "Aussehen" to "पहा",
    "Auto" to "कार",
    "Außenkamin" to "बाहेरची फायरप्लेस",
    "BEANTWORTE" to "उत्तर",
    "Bali" to "बाली",
    "Bali, Indonesien" to "बाली, इंडोनेशिया",
    "Banane" to "केळी",
    "Beantwortet" to "उत्तर दिले",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "एकाच वेळी प्रश्नांची उत्तरे द्या — तुम्ही दोघे पूर्ण होईपर्यंत उत्तरे दिसणार नाहीत.",
    "Beantwortete Fragen" to "प्रश्नांची उत्तरे दिली",
    "Bearbeiten" to "संपादित करा",
    "Bei Insider-Witzen" to "आतल्या विनोदांसाठी",
    "Bei Memes" to "मीम्सवर",
    "Bei einer spontanen Berührung" to "जेव्हा उत्स्फूर्तपणे स्पर्श केला जातो",
    "Beide" to "दोन्ही",
    "Beide gleich" to "दोन्ही सारखेच",
    "Beide zusammen" to "दोघेही एकत्र",
    "Beide, aber wir tun so als ob nicht" to "दोन्ही, पण आम्ही ढोंग करत नाही",
    "Beides" to "दोन्ही",
    "Beides wäre schlimm" to "दोन्ही वाईट असतील",
    "Beim Einschlafen nebeneinander" to "एकमेकांच्या शेजारी झोपणे",
    "Beim Reden" to "बोलत असताना",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "प्रसिद्ध पर्यटन स्थळे नेहमीच निराशाजनक असतात.",
    "Beschreibe unser Sexleben mit einem Emoji." to "इमोजीसह आमच्या लैंगिक जीवनाचे वर्णन करा.",
    "Besser kommunizieren" to "चांगले संवाद साधा",
    "Bessere Lage" to "उत्तम स्थान",
    "Bestellen" to "ऑर्डर",
    "Besuchte Länder" to "भेट दिलेले देश",
    "Besuchte Städte" to "शहरांना भेट दिली",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "तुम्हाला अवाजवी प्रस्ताव आवडतो की काहीतरी सूक्ष्म?",
    "Beziehung" to "संबंध",
    "Bibliothek" to "लायब्ररी",
    "Bin manchmal unsicher" to "मी कधीकधी असुरक्षित असतो",
    "Bist du ein Videospiel-Guru?" to "तुम्ही व्हिडिओ गेम गुरू आहात का?",
    "Blumenwiese" to "फुलांचे कुरण",
    "Bunte Blumenwiese" to "रंगीत फुलांचे कुरण",
    "Burger" to "बर्गर",
    "Burger King" to "बर्गर किंग",
    "Chat" to "गप्पा",
    "Coca-Cola" to "कोका कोला",
    "Cookie Dough" to "कुकी पीठ",
    "Dachgarten mit Lounge" to "लाउंजसह छतावरील बाग",
    "Dachterrasse" to "छताची टेरेस",
    "Das Wetter an dem Tag" to "त्या दिवशीचे हवामान",
    "Das erste Selfie" to "पहिला सेल्फी",
    "Das meiste weiß ich" to "मला बहुतेक माहित आहे",
    "Das oder das?" to "हे किंवा ते?",
    "Das tägliche Leben" to "दैनंदिन जीवन",
    "Dass Zusagen gehalten werden" to "ती आश्वासने पाळली जातात",
    "Dass alles meinen Stil hat" to "प्रत्येक गोष्टीची माझी शैली आहे",
    "Dass ich alles erzählen kann" to "की मी सर्व काही सांगू शकतो",
    "Dass ich mich nicht sorgen muss" to "मला काळजी करण्याची गरज नाही",
    "Dass wir ungestört sind" to "की आम्ही अबाधित आहोत",
    "Dein Name" to "तुमचे नाव",
    "Deine Antwort..." to "तुमचे उत्तर...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "तुमची उत्तरे जतन केली आहेत. भागीदार पॅकेज पूर्ण करताच, दोन्ही उत्तरे एकत्र दिसतील.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "तुमची उत्तरे सेव्ह केली आहेत. एकदा \${profile.partnerName} ने पॅकेज पूर्ण केले की, दोन्ही प्रतिसाद एकत्र दिसतील.",
    "Deine Beziehung abenteuerlich und spontan machen" to "तुमचे नाते साहसी आणि उत्स्फूर्त बनवा",
    "Deine Beziehung stabil und sicher machen" to "तुमचे नाते स्थिर आणि सुरक्षित बनवा",
    "Deine eigene Antwort" to "तुमचे स्वतःचे उत्तर",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "तुमची सखोल रहस्ये तुमच्या जोडीदारासोबत शेअर करणे चांगले",
    "Deinen besten Freund verlieren" to "तुमचा सर्वात चांगला मित्र गमावला",
    "Denke an dich" to "स्वतःचा विचार करा",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "एकच चित्रपट दोनदा पाहणे म्हणजे वेळेचा अपव्यय आहे.",
    "Der Blick nach draußen" to "बाहेरचे दृश्य",
    "Der Garten" to "बाग",
    "Der Ort" to "ठिकाण",
    "Der Ring und die Geste" to "अंगठी आणि हावभाव",
    "Der perfekte Heiratsantrag" to "परिपूर्ण लग्नाचा प्रस्ताव",
    "Derjenige sein, der umarmt wird" to "मिठी मारणारे व्हा",
    "Deutsch" to "जर्मन",
    "Diamant" to "हिरा",
    "Diamanten im Band" to "बँडमधील हिरे",
    "Die Distanz" to "अंतर",
    "Die Feiertage mit der Familie deines Partners verbringen" to "सुट्ट्या तुमच्या जोडीदाराच्या कुटुंबासोबत घालवा",
    "Die Gemütlichkeit und Ruhe" to "आराम आणि शांतता",
    "Die Menschen, die darin wohnen" to "त्यात राहणारे लोक",
    "Die Umgebung und Atmosphäre" to "वातावरण आणि वातावरण",
    "Die Worte und Emotionen" to "शब्द आणि भावना",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "अंतिम मनोरंजन ट्रिव्हिया आव्हान",
    "Diejenige sein, die umarmt" to "मिठी मारणारे व्हा",
    "Direkt ansprechen" to "थेट पत्ता",
    "Diskussion" to "चर्चा",
    "Diskutiere vor dem Kinderkriegen" to "मुले होण्यापूर्वी चर्चा करा",
    "Diskutiert eure Antworten" to "तुमच्या उत्तरांची चर्चा करा",
    "Disney" to "डिस्ने",
    "Doch, schon mal" to "होय, होय",
    "Draußen mit der Natur als Kulisse" to "पार्श्वभूमी म्हणून निसर्गाच्या बाहेर",
    "Drei-Stein-Ring" to "तीन दगडी अंगठी",
    "Du bist dran" to "आता तुमची पाळी आहे",
    "Du fehlst mir" to "मला तुझी आठवण येते",
    "Dubai" to "दुबई",
    "Dubai, VAE" to "दुबई, UAE",
    "Dunkles Design" to "गडद थीम",
    "Durch Berührung" to "स्पर्शाने",
    "Durch Worte" to "शब्दांद्वारे",
    "Durch Zeit zu zweit" to "वेळ एकत्र",
    "Durch kleine Gesten" to "लहान हावभावांद्वारे",
    "Durchgeplant" to "सुनियोजित",
    "ERGEBNISSE" to "परिणाम",
    "Egal, Hauptsache gesund" to "काहीही असो, मुख्य गोष्ट आरोग्यदायी आहे",
    "Ehepaar Leben" to "विवाहित दाम्पत्य जीवन",
    "Eher knapp" to "त्याऐवजी बंद",
    "Eher nicht" to "इतके नाही",
    "Eher schwer" to "त्याऐवजी कठीण",
    "Eher schwierig" to "त्यापेक्षा अवघड",
    "Eher zu" to "अधिक आवडले",
    "Eifersucht ist ein Zeichen von Liebe." to "मत्सर हे प्रेमाचे लक्षण आहे.",
    "Eigenes Gemüsebeet" to "स्वतःचा भाजीपाला पॅच",
    "Ein Abenteuer in einer neuen Stadt" to "नवीन शहरात एक साहस",
    "Ein Anker" to "एक अँकर",
    "Ein Balkon oder Garten" to "एक बाल्कनी किंवा बाग",
    "Ein Filmabend" to "चित्रपटाची रात्र",
    "Ein Harmony-Meilenstein eurer Liebe." to "तुमच्या प्रेमाचा एक सुसंवाद मैलाचा दगड.",
    "Ein Herz" to "एक हृदय",
    "Ein Herz an der Tür" to "दारात हृदय",
    "Ein Jahr lang eine Fernbeziehung führen" to "एका वर्षासाठी दीर्घ-अंतराचा संबंध ठेवा",
    "Ein Kindheitsessen" to "बालपणीचे जेवण",
    "Ein Live-Musik-Konzert besuchen" to "थेट संगीत मैफिलीत सहभागी व्हा",
    "Ein Museum besuchen" to "संग्रहालयाला भेट द्या",
    "Ein Spieleabend" to "खेळाची रात्र",
    "Ein Spieleabend mit Freunden" to "मित्रांसह खेळाची रात्र",
    "Ein Urlaubsfoto" to "सुट्टीतील फोटो",
    "Ein aktives Abenteuer" to "एक सक्रिय साहस",
    "Ein entspannender Spa-Tag" to "आरामदायी स्पा दिवस",
    "Ein ganz normaler Alltagstag" to "एक पूर्णपणे सामान्य दररोजचा दिवस",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "वादळाच्या वेळी घरात एक आरामदायक संध्याकाळ",
    "Ein gemütliches Date drinnen" to "घरामध्ये एक आरामदायक तारीख",
    "Ein lustiges Bild" to "एक मजेदार चित्र",
    "Ein paar Handyfotos reichen" to "सेल फोनचे काही फोटो पुरेसे आहेत",
    "Ein paar Stunden" to "काही तास",
    "Ein paar kulturelle Anklänge sind okay" to "काही सांस्कृतिक संदर्भ ठीक आहेत",
    "Ein romantischer Abend" to "एक रोमँटिक संध्याकाळ",
    "Ein romantisches Abendessen bei Kerzenlicht" to "एक रोमँटिक कँडललाइट डिनर",
    "Ein romantisches Bild" to "एक रोमँटिक प्रतिमा",
    "Ein romantisches Picknick an einem schönen Ort" to "एका सुंदर ठिकाणी रोमँटिक पिकनिक",
    "Ein schwerer Moment, den wir geschafft haben" to "एक कठीण क्षण जो आम्ही व्यवस्थापित केला",
    "Ein tolles Date im Freien unter dem Mondlicht" to "चंद्रप्रकाशात घराबाहेर एक उत्तम तारीख",
    "Ein ungewöhnliches Gericht" to "एक असामान्य डिश",
    "Ein zufälliger Schnappschuss" to "एक यादृच्छिक स्नॅपशॉट",
    "Einander kennenlernen" to "एकमेकांना जाणून घेणे",
    "Eine Autoreise" to "एक रोड ट्रिप",
    "Eine Brücke" to "एक पूल",
    "Eine Date-Nacht unter den Sternen" to "ताऱ्यांखाली एक तारखेची रात्र",
    "Eine Million Dollar gewinnen" to "दशलक्ष डॉलर्स जिंका",
    "Eine Million Dollar verdienen" to "दशलक्ष डॉलर कमवा",
    "Eine Nacht in einem Club" to "क्लबमध्ये एक रात्र",
    "Eine Schokoladenverkostung" to "चॉकलेट चाखणे",
    "Eine Wanderung mit Panoramablick machen" to "विहंगम दृश्यांसह एक फेरी काढा",
    "Eine Weinverkostung" to "वाइन चाखणे",
    "Eine gemeinsame Reise" to "एकत्र प्रवास",
    "Eine gemütliche Nacht zu Hause" to "घरी एक आरामदायक रात्र",
    "Eine neue Sprache zu lernen ist einfach." to "नवीन भाषा शिकणे सोपे आहे.",
    "Einen Film anschauen" to "चित्रपट पहा",
    "Einen Monat lang überhaupt nicht miteinander reden" to "महिनाभर एकमेकांशी अजिबात बोलत नाही",
    "Einen Tanzkurs besuchen" to "डान्स क्लास घ्या",
    "Einen Vergnügungspark erkunden" to "मनोरंजन पार्क एक्सप्लोर करा",
    "Einen Wellness-Tag" to "निरोगीपणाचा दिवस",
    "Einen sehr emotionalen Partner haben" to "खूप भावनिक जोडीदार असणे",
    "Einen sehr logischen Partner haben" to "खूप तार्किक भागीदार असणे",
    "Einer zahlt alles" to "एक व्यक्ती सर्व काही देते",
    "Einfach mehr Alltag" to "फक्त अधिक दैनंदिन जीवन",
    "Einfach nebeneinander sein" to "फक्त एकमेकांच्या शेजारी रहा",
    "Einfach und intim" to "साधे आणि जिव्हाळ्याचे",
    "Einige Dinge für dich behalten" to "काही गोष्टी स्वतःकडे ठेवा",
    "Einmal" to "एकदा",
    "Eins, das nur wir kennen" to "एक जे फक्त आम्हाला माहीत आहे",
    "Englisch" to "इंग्रजी",
    "Entspannte Hängematte" to "आरामशीर झूला",
    "Entspannung" to "विश्रांती",
    "Erdbeere" to "स्ट्रॉबेरी",
    "Erfolgreich" to "यशस्वी",
    "Ergebnisse" to "परिणाम",
    "Erst bei sehr großen Summen" to "फक्त खूप मोठ्या रकमेसाठी",
    "Erst nur enge Freunde/Familie" to "सुरुवातीला फक्त जवळचे मित्र/कुटुंब",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "जेव्हा माझा जोडीदार संदेशांना प्रतिसाद देण्यासाठी खूप वेळ घेतो तेव्हा ते मला त्रास देते.",
    "Essen & Genuss" to "अन्न आणि आनंद",
    "Essensvorlieben" to "अन्न प्राधान्ये",
    "Etwa eine Woche später, erst mal nur wir" to "सुमारे एक आठवड्यानंतर, प्रथम फक्त आम्ही",
    "Etwas Neues ausprobieren" to "काहीतरी नवीन करून पहा",
    "Etwas ganz anderes" to "काहीतरी पूर्णपणे वेगळे",
    "Etwas sehr Scharfes" to "काहीतरी खूप तीक्ष्ण आहे",
    "Etwas, das ich selbst gern erfinde" to "मला स्वतःचा शोध लावायला आवडते",
    "Etwas, eine kleine Note wäre schön" to "काहीतरी, थोडे नोट छान होईल",
    "Familie" to "कुटुंब",
    "Familie/Freunde" to "कुटुंब/मित्र",
    "Familienmensch" to "कुटुंबातील माणूस",
    "Farbedelstein" to "रंगीत रत्न",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "टीव्ही जाहिराती कधी कधी पाहण्यासाठी मनोरंजक असतात.",
    "Fertig" to "पूर्ण झाले",
    "Fertig!" to "पूर्ण झाले!",
    "Feste Date-Nights" to "निश्चित तारखेच्या रात्री",
    "Feuerstelle" to "फायर पिट",
    "Filigran & schlicht" to "फिलीग्री आणि साधे",
    "Filme/Serien" to "चित्रपट/मालिका",
    "Formuliere um..." to "रीफ्रेस...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "तुमचा मसुदा अहिंसक पद्धतीने पुन्हा सांगा: निरीक्षण, भावना, गरज, विनंती.",
    "Frage hinzufügen" to "प्रश्न जोडा",
    "Fragen & Spiele" to "प्रश्न आणि खेळ",
    "Fragen für jede Gelegenheit" to "प्रत्येक प्रसंगासाठी प्रश्न",
    "Freizeitpark" to "मनोरंजन उद्यान",
    "Freunde treffen" to "मित्रांना भेटा",
    "Freundschaften mit Ex-Partnern sind okay." to "exes सह मैत्री ठीक आहे.",
    "Früh aufstehen" to "लवकर उठा",
    "Fußbodenheizung" to "अंडरफ्लोर हीटिंग",
    "Führen wir getrennte oder gemeinsame Konten?" to "आमच्याकडे स्वतंत्र किंवा संयुक्त खाती आहेत का?",
    "Für dich empfohlen" to "तुमच्यासाठी शिफारस केलेले",
    "Für die Zukunft" to "भविष्यासाठी",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "या शोधासाठी कोणतेही जुळणारे प्रश्न किंवा गेम आढळले नाहीत.",
    "Für immer" to "कायमचे",
    "Fürsorglichkeit" to "काळजी घेणे",
    "GFK-Brücke" to "GRP पूल",
    "Galerie" to "गॅलरी",
    "Gar nicht, der Moment gehört uns" to "अजिबात नाही, क्षण आमचा आहे",
    "Gar nichts tun" to "काहीही करू नका",
    "Geduld" to "संयम",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "सूर्योदय पाहण्यासाठी पहाटे जा",
    "Geht so" to "असे होते",
    "Geister existieren wirklich." to "भुते खरोखर अस्तित्वात आहेत.",
    "Gelassenheit" to "शांतता",
    "Gelbgold" to "पिवळे सोने",
    "Geld & Finanzen" to "पैसा आणि वित्त",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "जगाचा एकत्र प्रवास करा, नवीन संस्कृती आणि पाककृती एक्सप्लोर करा",
    "Gemeinsam ein Lego bauen" to "एकत्र एक लेगो तयार करा",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "स्वयंपाकघरात एकत्र एक नवीन रेसिपी वापरून पहा",
    "Gemeinsame Konten" to "शेअर केलेली खाती",
    "Gemeinsame Nächte" to "रात्री एकत्र",
    "Gemeinsame Tage" to "दिवस एकत्र",
    "Gemischt" to "मिश्रित",
    "Gemüsebeet" to "भाजीपाला पॅच",
    "Gemütliche Feuerstelle" to "आरामदायक फायरप्लेस",
    "Gesprächsanreger" to "संभाषण प्रारंभकर्ता",
    "Getrennte Konten" to "वेगळी खाती",
    "Getrennte Urlaube tun einer Beziehung gut." to "नात्यासाठी वेगळी सुट्टी चांगली असते.",
    "Gewächshaus" to "हरितगृह",
    "Glasfassade" to "काचेचा दर्शनी भाग",
    "Gleichgültigkeit" to "उदासीनता",
    "Glücklich und frei" to "आनंदी आणि विनामूल्य",
    "Gourmet Eis-Sorten" to "गोरमेट आइस्क्रीमचे प्रकार",
    "Gravur innen" to "आत खोदकाम",
    "Grillplatz" to "बार्बेक्यू क्षेत्र",
    "Groß & üppig" to "मोठा आणि हिरवागार",
    "Große Familie" to "मोठे कुटुंब",
    "Große Feier" to "मोठा उत्सव",
    "Große Fenster" to "मोठ्या खिडक्या",
    "Große Fensterfront" to "समोर मोठी खिडकी",
    "Großer Außenpool" to "मोठा मैदानी पूल",
    "Großer Garten" to "मोठी बाग",
    "Großer Stein" to "मोठा दगड",
    "Größere Küche" to "मोठे स्वयंपाकघर",
    "Gutes Essen" to "चांगले अन्न",
    "Habe ich" to "मी केले",
    "Habe ich noch nie" to "माझ्याकडे कधीच नाही",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "तुम्हाला काही आश्चर्यकारक फरक आढळले आहेत का? तुम्हाला काही पर्याय चांगले का आवडतात याबद्दल बोला!",
    "Haus am See" to "तलावाजवळ घर",
    "Haus/Wohnung" to "घर/अपार्टमेंट",
    "Hazelnut" to "हेझलनट",
    "Heimkino" to "होम थिएटर",
    "Herzhaft" to "हार्दिक",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "येथे सध्या काहीही नाही.\nफिल्टर बदला किंवा वेगळा विषय निवडा.",
    "Hilfe im Alltag" to "दैनंदिन जीवनात मदत",
    "Himbeere" to "रास्पबेरी",
    "Hinzufügen" to "जोडा",
    "Hobbys" to "छंद",
    "Hochzeitssträuße" to "लग्नाचे पुष्पगुच्छ",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "हॉगवर्ट्स हाऊस प्राइड: तुमचा संबंध कोठे आहे?",
    "Home" to "घर",
    "Hot Tub" to "गरम टब",
    "Humor" to "विनोद",
    "Hund" to "कुत्रा",
    "Hängematte" to "झूला",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "तुम्हाला अर्जाचा एक भाग म्हणून लिखित पत्र हवे आहे का?",
    "IKEA" to "IKEA",
    "Ich" to "आय",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "मी सिनेमाला जाण्यापेक्षा पार्कमध्ये रोमँटिक वॉकला प्राधान्य देतो.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "मी सिनेमात कधीच झोपलो नाही.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "मला माझ्या जोडीदारासोबत नवीन छंद किंवा क्रियाकलाप शोधण्यात आनंद होतो.",
    "Ich finde eine Alternative" to "मी एक पर्याय शोधेन",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "मला नेहमी एकाच ठिकाणी जाण्याऐवजी माझ्या जोडीदारासोबत नवीन रेस्टॉरंट वापरण्याचा आनंद मिळतो.",
    "Ich habe noch nie" to "मी कधीच नाही",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "मला कधीही रोलर कोस्टरची भीती वाटली नाही आणि तरीही मी त्यावर चढलो.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "मी कधीच फास्ट पासची तिकिटे विकत घेतली नाहीत कारण मी अधीर होतो.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "मी घरी राहून टीव्ही शो पाहण्याच्या योजना कधीही रद्द केल्या नाहीत.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "मी हॉगवर्ट्सच्या माझ्या पत्राची कधीच वाट पाहिली नाही.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "स्लिथरिन प्रत्यक्षात इतकी वाईट नव्हती असे मी कधीच म्हटले नाही.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "डिस्ने चित्रपटांसाठी मी खूप जुने आहे असे मी कधीही म्हटले नाही (आणि गुप्तपणे त्यांचा आनंद घेतला).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "मी कधीच मारियो कार्टमध्ये निळ्या टँक असलेल्या एखाद्याला हेतुपुरस्सर गोळ्या झाडल्या नाहीत.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "मी डिस्ने चित्रपटात कधीही रडलो नाही.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "भयपट पाहताना मी माझे डोळे कधीच झाकले नाहीत.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "मी गेम जतन करण्यास विसरलो नाही आणि प्रगतीचे तास गमावले.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "लाजिरवाण्या दृश्यादरम्यान (क्रिंज फॅक्टर) मी कधीही खोली सोडली नाही.",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "रोलरकोस्टर फोटो घेताना मी कधीही मजेदार पोझ दिलेली नाही.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "मी कधीही रात्री उशिरापर्यंत खेळलो नाही आणि दुसऱ्या दिवशी मी किती थकलो याची खंत वाटते.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "मी कधीही चित्रपटाचा शेवट गुगल केला नाही कारण मी थांबू शकलो नाही.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "मी चित्रपटाच्या सेटवर उभा आहे असे मला कधीच वाटले नाही.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "मी माझ्या आवडत्या मालिकेचा परिचय कधीही वगळला नाही.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "मी कधीही इतर कोणाचा Netflix पासवर्ड शेअर केलेला नाही.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "काम करताना किंवा अभ्यास करताना मी कधीही गेमचा साउंडट्रॅक ऐकला नाही.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "मी हरलो तेव्हा मी कंट्रोलरला कधीही दोष दिला नाही.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "मी रागाच्या भरात कधीही कीबोर्ड किंवा कंट्रोलर फेकून दिलेला नाही.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "मी काही दिवस वॉशिंग मशिनमध्ये ओले कपडे कधीच विसरलो नाही.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "मी कधीही गेममध्ये कॉस्मेटिक वस्तूंवर खरे पैसे खर्च केले नाहीत.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "मी परदेशात कधीही कार चालवली नाही.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "मी शॉवरमध्ये डिस्ने गाणे कधीही बेल्ट आउट केले नाही.",
    "Ich habe noch nie ein Elektroauto gefahren." to "मी कधीही इलेक्ट्रिक कार चालवली नाही.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "मी पार्कच्या शुभंकरासह कधीही फोटो काढला नाही.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "हॉगवर्ट्सच्या पात्राच्या नावावर मी कधीही पाळीव प्राण्याचे नाव ठेवले नाही.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "मी कधीही चित्रपटगृहात पॉपकॉर्न टाकले नाही आणि तरीही ते खाल्ले आहे.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "मी दैनंदिन जीवनात स्टार वॉर्समधील मास्टर योडा मधील कोट कधीही वापरला नाही.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "मी थीम पार्कमध्ये कधीही जास्त किंमतीची स्मरणिका विकत घेतली नाही.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "समोरच्या व्यक्तीला भयंकर वाटेल अशा चित्रपटाची शिफारस मी कधीही केलेली नाही.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "मी मध्यरात्री कधीही ऑस्कर लाइव्ह पाहिला नाही.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "मी कधीही मालिका रद्द केली नाही कारण शेवटचा सीझन खूप वाईट होता.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "मी एका दिवसात मालिकेचा संपूर्ण सीझन कधीच पाहिला नाही.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "मी पहिल्याच प्रयत्नात कधीही बॉसला हरवले नाही आणि मला देवासारखे वाटले.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "मला नायकापेक्षा कूलर खलनायक सापडला नाही.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "मी माझ्या स्वतःच्या खेळण्यांमधील टॉय स्टोरीचे पात्र कधीच ओळखले नाही.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "मी कधीही RPG मध्ये माझ्यासारखे पात्र बनवलेले नाही.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "मी थीम पार्कमध्ये चुरो कधीच खाल्ले नाही.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "मी डिस्ने चित्रपट सलग तीन वेळा पाहिला नाही.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "माझ्याकडे संपूर्ण आठवडाभर कधीही डिस्नेची आकर्षक ट्यून आली नाही.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "केवळ एका अभिनेत्यामुळे मी कधीही चित्रपट पाहिला नाही.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "मी चित्रपटाचा साउंडट्रॅक तासनतास पुन्हा ऐकला नाही.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "मी कधीही चित्रपट बिघडवणारा खुलासा केला नाही आणि लगेच खेद व्यक्त केला.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "मला दुसरी मूळ भाषा बोलणारा मित्र सापडला नाही.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "दुसऱ्या देशात गेलेला माझा मित्र कधीच नव्हता.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "मी ख्रिसमसमध्ये हॅरी पॉटर मूव्ही मॅरेथॉन कधीच केली नाही.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "क्रेडिटनंतरच्या दृश्यामुळे मी शेवटपर्यंत मार्वल चित्रपट कधीच पाहिला नाही.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "मी NPC (नॉन-प्लेअर कॅरेक्टर) जाणूनबुजून कधीही नाराज केले नाही.",
    "Ich habe noch nie einen Nachtzug genommen." to "मी कधीही रात्रीची ट्रेन पकडली नाही.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "माझे हॉगवर्ट्स घर शोधण्यासाठी मी कधीही ऑनलाइन चाचणी घेतली नाही.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "मी सोशल मीडिया पोस्ट कधीही डिलीट केली नाही कारण तिला पुरेसे लाईक्स मिळाले नाहीत.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "मी कधीही थीम पार्कमधील एका दिवसाला वर्षातील सर्वोत्तम दिवस म्हटलेले नाही.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "मी कधीही थीम पार्कला भेट दिली नाही आणि सकाळपासून रात्रीपर्यंत तिथे राहिलो.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "मी कधीही ट्रान्सफॉर्मर्स किंवा मार्व्हल राइड पूर्णपणे मोहून टाकले नाही.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "मी कधीही रागावून खेळ सोडला नाही.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "मी कधीही हॅरी पॉटरचे मोठे खंड वाचलेले नाहीत.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "मी मालिकेतील माझ्या आवडत्या व्यक्तिरेखेबद्दल कधीही नाराजी व्यक्त केली नाही.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "क्विडिच खेळण्याचे मी स्वप्नातही पाहिले नव्हते.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "हार्ड लेव्हल कसे सोडवायचे ते मी कधीही गुपचूप गुगल केले नाही.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "माझे पाळीव प्राणी डिस्ने प्रमाणे बोलू शकतील अशी मी गुप्तपणे कधीही आशा केली नाही.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "मी सिम्समधील पूल लीडर कधीही काढला नाही.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "मी 3D सिम्युलेटर राइडमध्ये माझे बेअरिंग कधीही गमावले नाही.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "मी कधीही विद्यापीठ क्रीडा संघात खेळलो नाही.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "मी कधीही एकाच आकर्षणासाठी दोन तासांपेक्षा जास्त रांगेत थांबलो नाही.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "मी माझ्या मौल्यवान वस्तू वॉटर राईडवर कधीच ओल्या केल्या नाहीत.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "कोणते घर सर्वोत्तम आहे याबद्दल मी मित्राशी कधीही वाद घातला नाही.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "मी कधीही एल्सा सारख्या जादुई शक्तींचा आव आणला नाही.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "चित्रपटातील महत्त्वाचा सीन चुकवण्याइतपत मी कधीही हसलो नाही.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "मला कधीच इतके एड्रेनालाईन वाटले नाही की मला लगेच पुन्हा सायकल चालवायची होती.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "मी कधीही स्नो व्हाइट सारख्या प्राण्यांसोबत गाण्याचा प्रयत्न केला नाही.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "मी डिस्नेलँडच्या सहलीचे स्वप्न पाहिले नाही.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "ज्युरासिक पार्क वॉटर राइड चालवण्याचे मी स्वप्नातही पाहिले नव्हते.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "मी कधीही गेममध्ये उडी मारताना मोठ्याने ओरडलो नाही.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "मी टीव्ही शोच्या फिनालेवर कधीही रडलो नाही.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "मी कधीही... घरी राहण्याची तारीख रद्द केली नाही.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "मी कधीही... १० वेळा मेसेज रिफ्रेस केलेला नाही.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "मी कधीच... माझ्या जोडीदाराच्या सेल फोनकडे गुप्तपणे पाहिले नाही.",
    "Ich habe noch nie!" to "मी कधीच नाही!",
    "Ich habe!" to "माझ्याकडे आहे!",
    "Ich lache viel mit meinem Partner." to "मी माझ्या जोडीदारासोबत खूप हसतो.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "मला माझ्या जोडीदाराचे छंद आणि आवडी जाणून घेणे आवडते.",
    "Ich liebe es" to "मला ते आवडते",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "मला माझ्या जोडीदारासोबत चित्रपट पाहणे आवडते जे आम्ही दोघांनीही यापूर्वी पाहिलेले नाहीत.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "मला माझे आवडते संगीत माझ्या जोडीदारासोबत शेअर करायला आवडते.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "मला कधीही कनेक्टिंग फ्लाइट पकडण्यासाठी पळावे लागले नाही.",
    "Ich plane gerne Dates mit meinem Partner." to "मला माझ्या जोडीदारासोबत तारखांचे नियोजन करायला आवडते.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "मी व्यस्त असताना देखील माझ्या जोडीदारासोबत वेळ घालवण्यास प्राधान्य देतो.",
    "Ich schreibe meinem Partner jeden Tag." to "मी माझ्या जोडीदाराला दररोज मजकूर पाठवतो.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "मला माझ्या जोडीदारासोबत मीम्स आणि विनोद शेअर करायला आवडते.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "मला माझ्या दिवसाचे सर्व तपशील माझ्या जोडीदारासोबत शेअर करायला आवडते.",
    "Ich würde es nie tun" to "मी ते कधीच करणार नाही",
    "Ich übe noch" to "मी अजूनही सराव करत आहे",
    "Ideen generieren" to "कल्पना निर्माण करा",
    "Im Haushalt helfen" to "घराभोवती मदत करा",
    "In Chat einfügen" to "चॅटमध्ये जोडा",
    "In Stille nebeneinander" to "एकमेकांच्या शेजारी शांततेत",
    "In den Bergen" to "पर्वतांमध्ये",
    "In eine Bar gehen" to "बारमध्ये जा",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "सूर्यास्त पाहण्यासाठी बीच बारमध्ये जात आहे",
    "In einem feinen Restaurant essen gehen" to "एका उत्तम रेस्टॉरंटमध्ये बाहेर खाणे",
    "In einen Coffeeshop gehen" to "कॉफी शॉपमध्ये जा",
    "In einer Beziehung sollte man alles voneinander wissen." to "नात्यात तुम्हाला एकमेकांबद्दल सर्व काही माहित असले पाहिजे.",
    "Infinity-Pool" to "अनंत पूल",
    "Innenpool" to "इनडोअर पूल",
    "Intelligenz" to "बुद्धिमत्ता",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "तुमच्या जोडीदाराने सुरुवात केल्यावरच जिव्हाळ्याचे क्षण येतात",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "आमंत्रण कोड: HRM-8731 · सर्व काही अनलॉक केले",
    "Island" to "आइसलँड",
    "Ist okay für mich" to "हे माझ्यासाठी ठीक आहे",
    "Ist schon perfekt" to "ते परिपूर्ण आहे",
    "Ja, Traditionen einbinden" to "होय, परंपरांचा समावेश करा",
    "Ja, absolut" to "होय, अगदी",
    "Ja, etwas zum Lesen und Aufbewahren" to "होय, वाचण्यासाठी आणि ठेवण्यासाठी काहीतरी",
    "Ja, genug" to "होय, पुरेसे आहे",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "होय, एका रोमांचक शहरात किंवा आकर्षणात",
    "Ja, in- und auswendig" to "होय, आत आणि बाहेर",
    "Ja, komplett überraschend" to "होय, पूर्णपणे आश्चर्यकारक",
    "Ja, perfekt" to "होय, परिपूर्ण",
    "Ja, sie gehören zur Familie!" to "होय, ते कुटुंब आहेत!",
    "Ja, sofort teilen" to "होय, लगेच शेअर करा",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "होय, कौटुंबिक वेळेला प्राधान्य आहे याची आम्ही खात्री करू.",
    "Jacuzzi" to "जकूझी",
    "Jahr zusammen 🎉" to "वर्ष एकत्र 🎉",
    "Jahre zusammen 🎉" to "वर्षे एकत्र 🎉",
    "Jeder zahlt 50%" to "प्रत्येकजण 50% पैसे देतो",
    "Junge" to "मुलगा",
    "Kamin" to "फायरप्लेस",
    "Karriere & Erfolg" to "करिअर आणि यश",
    "Kategorien" to "श्रेणी",
    "Katze" to "मांजर",
    "Keine Musik" to "संगीत नाही",
    "Keine Party nötig, privat halten" to "पार्टीची गरज नाही, ती खाजगी ठेवा",
    "Keine Privatsphäre" to "गोपनीयता नाही",
    "Keine Treffer gefunden" to "कोणतेही जुळले नाहीत",
    "Keiner" to "काहीही नाही",
    "Keiner von uns" to "आमच्यापैकी कोणीही नाही",
    "Kennst du die Essensvorlieben deines Partners?" to "तुम्हाला तुमच्या जोडीदाराच्या खाण्याच्या आवडीनिवडी माहीत आहेत का?",
    "Kino" to "सिनेमा",
    "Kirchlich" to "चर्चसंबंधी",
    "Klassisch Solitär" to "क्लासिक सॉलिटेअर",
    "Klassisch gebunden" to "शास्त्रीयदृष्ट्या बांधील",
    "Klein & zart" to "लहान आणि नाजूक",
    "Kleine Geschenke" to "लहान भेटवस्तू",
    "Kleine Runde" to "लहान गट",
    "Kochen und Freunde einladen" to "स्वयंपाक करणे आणि मित्रांना आमंत्रित करणे",
    "Kochkurs" to "पाककला वर्ग",
    "Kommt auf den Tag an" to "दिवसावर अवलंबून असते",
    "Kommt darauf an" to "ते अवलंबून आहे",
    "Kommt drauf an" to "ते अवलंबून आहे",
    "Kommt mit" to "माझ्याबरोबर चल",
    "Konzert" to "मैफल",
    "Kräftige Farben" to "मजबूत रंग",
    "Kräuterbeet" to "औषधी वनस्पती बेड",
    "Kultur & Sehenswürdigkeiten" to "संस्कृती आणि ठिकाणे",
    "Kuscheln" to "मिठी मारणे",
    "Kuss senden" to "चुंबन पाठवा",
    "Körperliche Annäherung" to "शारीरिक दृष्टीकोन",
    "Körperliche Nähe" to "शारीरिक जवळीक",
    "Küche" to "स्वयंपाकघर",
    "Land" to "देश",
    "Landhaus" to "देशाचे घर",
    "Landhausstil" to "देशाच्या घराची शैली",
    "Lange wach bleiben" to "उशिरापर्यंत जा",
    "Lappland" to "लॅपलँड",
    "Lappland, Finnland" to "लॅपलँड, फिनलंड",
    "Las Vegas" to "लास वेगास",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "तुमच्या जोडीदाराला तुम्हाला तुमचा सर्वोत्कृष्ट होण्यासाठी प्रेरित करू द्या",
    "Lehne ab" to "नकार",
    "Leichtigkeit" to "हलकेपणा",
    "Leidenschaft" to "आवड",
    "Liebe im Gleichgewicht" to "प्रेम संतुलनात आहे",
    "Liebe sie, macht mehr Spaß" to "त्यांच्यावर प्रेम करा, अधिक मजेदार",
    "Lieber durchgeplant oder spontan?" to "तुम्ही ते नियोजित केले असेल की उत्स्फूर्त?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "त्यापेक्षा तुम्ही दोघांसाठी किंवा लोकांसोबत शांत संध्याकाळ घालवू इच्छिता?",
    "Lieber nicht" to "चांगले नाही",
    "Lieber vorher grob absprechen" to "गोष्टींबद्दल आधी चर्चा करणे चांगले",
    "Lokal einkaufen" to "स्थानिक पातळीवर खरेदी करा",
    "London" to "लंडन",
    "London, England" to "लंडन, इंग्लंड",
    "Lügen" to "खोटे",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "तुम्ही सार्वजनिक किंवा खाजगी प्रस्तावाला प्राधान्य देता का?",
    "Malediven" to "मालदीव",
    "Man sollte nie streitend einschlafen." to "तुम्ही कधीही वाद घालत झोपू नये.",
    "Mango Sorbet" to "आंब्याचे सरबत",
    "Markant & breit" to "धक्कादायक आणि रुंद",
    "Marken & Alltag" to "ब्रँड आणि दैनंदिन जीवन",
    "McDonald’s" to "मॅकडोनाल्ड",
    "Mediterraner Innenhof" to "भूमध्यसागरीय अंगण",
    "Mehr Unterstützung" to "अधिक समर्थन",
    "Mehr gemeinsame Zeit" to "एकत्र जास्त वेळ",
    "Mehr zuhören" to "आणखी ऐका",
    "Mehrgenerationenhaus" to "बहु-पिढीचे घर",
    "Mein Arbeitsplatz" to "माझे कामाचे ठिकाण",
    "Mein Partner" to "माझा जोडीदार",
    "Mich überraschen" to "मला आश्चर्यचकित करा",
    "Minimalistisches Interieur" to "मिनिमलिस्ट इंटीरियर",
    "Missverständnisse" to "गैरसमज",
    "Mit Familie und engen Freunden" to "कुटुंब आणि जवळच्या मित्रांसह",
    "Mit Kompromissen" to "तडजोडीसह",
    "Mitgefühl" to "करुणा",
    "Mittelweg mit besonderen Details" to "विशेष तपशीलांसह मधले मैदान",
    "Modern geometrisch" to "आधुनिक भौमितिक",
    "Moderne Grillstation" to "आधुनिक ग्रील स्टेशन",
    "Moderner Name" to "आधुनिक नाव",
    "Moderner Solitär" to "आधुनिक सॉलिटेअर",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "क्षण कॅप्चर करा",
    "Momente" to "क्षण",
    "Monaco" to "मोनॅको",
    "Moralische Werte" to "नैतिक मूल्ये",
    "Museum" to "संग्रहालय",
    "Musik" to "संगीत",
    "Mut" to "धैर्य",
    "Mädchen" to "मुली",
    "Möbelhaus" to "फर्निचरचे दुकान",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "तुम्हाला खात्री आहे की तुम्ही प्रश्नमंजुषा सोडू इच्छिता? तुमची मागील प्रगती जतन केली जाते.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "तुम्हाला पाळीव प्राणी अनुप्रयोगात समाविष्ट करायचे आहेत का?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "क्षण सोशल मीडियावर झटपट शेअर करू इच्छिता?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "आम्हाला कदाचित बचत करावी लागेल",
    "Müssen es planen" to "त्याचे नियोजन करणे आवश्यक आहे",
    "Müssen sparen" to "जतन करणे आवश्यक आहे",
    "Nachricht an" to "संदेश",
    "Name Partnerin" to "भागीदाराचे नाव",
    "Namen und Startdatum eurer Beziehung." to "तुमच्या नात्याची नावे आणि सुरुवातीची तारीख.",
    "Natursteinfassade" to "नैसर्गिक दगडाचा दर्शनी भाग",
    "Naturteich" to "नैसर्गिक तलाव",
    "Nein, einfach halten" to "नाही, धरा",
    "Nein, erstmal privat halten" to "नाही, ते आतासाठी खाजगी ठेवा",
    "Nein, lieber vor Ort" to "नाही, साइटवर चांगले",
    "Nein, modern halten" to "नाही, आधुनिक ठेवा",
    "Nein, nur wir" to "नाही, फक्त आम्ही",
    "Nein, zu ablenkend" to "नाही, खूप विचलित करणारे",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "स्मार्ट घरासह नवीन इमारत",
    "Neubau mit Technik" to "तंत्रज्ञानासह नवीन इमारत",
    "Neue Liebe, neue Erfahrungen" to "नवीन प्रेम, नवीन अनुभव",
    "Neues Hobby" to "नवीन छंद",
    "Neues Spiel" to "नवीन गेम",
    "Neugier" to "कुतूहल",
    "New York" to "न्यूयॉर्क",
    "New York, USA" to "न्यूयॉर्क, यूएसए",
    "Nicht mein Fall" to "माझा चहाचा कप नाही",
    "Nicht nötig, lieber klassisch bleiben" to "आवश्यक नाही, क्लासिक राहणे चांगले",
    "Nichts — es passt so" to "काहीही नाही - ते बसते",
    "Nie wieder Burger" to "पुन्हा कधीही बर्गर नाही",
    "Nie wieder Pizza" to "पुन्हा कधीही पिझ्झा करू नका",
    "Niemand" to "कोणीही नाही",
    "Niemand ohne Plan" to "योजनेशिवाय कोणीही नाही",
    "Nike" to "नायके",
    "Nizza" to "छान",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "अजून काही क्षण नाहीत.\nतुमचा पहिला अनुभव कॅप्चर करा 💞",
    "Nur bei wichtigen Themen" to "फक्त महत्त्वाच्या विषयांसाठी",
    "Nur wir beide" to "फक्त आम्ही दोघे",
    "Nähe & Intimität" to "जवळीक आणि जवळीक",
    "Obstgarten" to "फळबागा",
    "Oder" to "किंवा",
    "Offene Küche" to "उघडे स्वयंपाकघर",
    "Offene Wohnküche" to "किचन/लिव्हिंग रूम उघडा",
    "Ohne Stein" to "दगडाशिवाय",
    "Open End" to "ओपन एंडिंग",
    "Outdoor-Küche" to "बाहेरचे स्वयंपाकघर",
    "Outdoor-Sofa" to "बाहेरचा सोफा",
    "Outdoor-Whirlpool" to "आउटडोअर व्हर्लपूल",
    "Ovaler Diamant" to "अंडाकृती हिरा",
    "Paar" to "जोडी",
    "Paar-Statistiken" to "जोडप्यांची आकडेवारी",
    "Paris" to "पॅरिस",
    "Paris, Frankreich" to "पॅरिस, फ्रान्स",
    "Partner" to "भागीदार",
    "Partner-Simulator" to "भागीदार सिम्युलेटर",
    "Partnerin" to "भागीदार",
    "Party Edition" to "पार्टी संस्करण",
    "Party Edition II" to "पार्टी संस्करण II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "एखादा प्राणी आपल्या दैनंदिन जीवनात बसतो का?",
    "Pasta" to "पास्ता",
    "Pastell" to "पेस्टल",
    "Penthouse mit Ausblick" to "दृश्यासह पेंटहाउस",
    "Pepsi" to "पेप्सी",
    "Pergola mit Lounge" to "लाउंजसह पेर्गोला",
    "Pfingstrosen" to "peonies",
    "Pinguin" to "पेंग्विन",
    "Pistazie" to "पिस्ता",
    "Pizza" to "पिझ्झा",
    "Pizzaofen" to "पिझ्झा ओव्हन",
    "Platin" to "प्लॅटिनम",
    "PlayStation" to "प्लेस्टेशन",
    "Pool" to "पूल",
    "Pop" to "पॉप",
    "Prasselnder Kamin" to "गर्जना करणारी शेकोटी",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "राजकुमारी, समुद्री डाकू आणि फेयरी डस्ट: डिस्ने क्विझ",
    "Privater Innenhof" to "खाजगी अंगण",
    "Profil" to "प्रोफाइल",
    "Profil bearbeiten" to "प्रोफाइल संपादित करा",
    "Prozentual nach Einkommen" to "उत्पन्नावर आधारित टक्केवारी",
    "Quiz verlassen" to "क्विझ सोडा",
    "Quiz verlassen?" to "प्रश्नमंजुषा सोडायची?",
    "Rausgehen in die Natur" to "निसर्गात बाहेर पडा",
    "Reden vor ..." to "यांच्याशी बोलत आहे...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "नियमित तारखा किंवा वेळ एकत्र शेड्युल करा",
    "Reisen" to "प्रवास",
    "Reiseziele" to "प्रवासाची ठिकाणे",
    "Respektlosigkeit" to "अनादर",
    "Restaurant" to "रेस्टॉरंट",
    "RnB / Soul" to "RnB / सोल",
    "Rock" to "रॉक",
    "Rom" to "रोम",
    "Rom, Italien" to "रोम, इटली",
    "Romantik" to "प्रणय",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "संदेश, नोट्स किंवा भेटवस्तू यासारखे रोमँटिक जेश्चर मला आनंदित करतात.",
    "Romantische Stimmung" to "रोमँटिक मूड",
    "Roségold" to "गुलाब सोने",
    "Ruhig zu zweit" to "दोघांसाठी शांत",
    "Runder Diamant" to "गोल हिरा",
    "Salted Caramel" to "खारट कारमेल",
    "Sammle Ideen..." to "कल्पना गोळा करा...",
    "Santorini" to "सँटोरिनी",
    "Santorini, Griechenland" to "सँटोरिनी, ग्रीस",
    "Saphir" to "नीलम",
    "Saunahaus" to "सौना घर",
    "Schickes Restaurant oder Hotel" to "आकर्षक रेस्टॉरंट किंवा हॉटेल",
    "Schlafzimmer" to "शयनकक्ष",
    "Schließen" to "बंद करा",
    "Schmal & zart" to "सडपातळ आणि नाजूक",
    "Schnappschüsse aus unserer Liebesgeschichte" to "आमच्या प्रेमकथेचे स्नॅपशॉट",
    "Schokolade" to "चॉकलेट",
    "Schreib frei, was dir wirklich dazu einfällt." to "मनाला येईल ते मोकळेपणाने लिहा.",
    "Schreibe deine eigene Antwort" to "तुमचे स्वतःचे उत्तर लिहा",
    "Sehr gerne" to "तुमचे स्वागत आहे",
    "Sehr leicht" to "खूप हलके",
    "Sehr wichtig — Fotos und Video" to "खूप महत्वाचे — फोटो आणि व्हिडिओ",
    "Sehr wichtig, es sollte persönlich sein" to "खूप महत्वाचे, ते वैयक्तिक असावे",
    "Selbst kochen" to "स्वतःला शिजवा",
    "Senden" to "पाठवा",
    "Separate Küche" to "वेगळे स्वयंपाकघर",
    "Serie schauen" to "मालिका पहा",
    "Serienmarathon auf dem Sofa" to "सोफ्यावर मालिका मॅरेथॉन",
    "Sex & Liebe" to "सेक्स आणि प्रेम",
    "Seychellen" to "सेशेल्स",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "आम्ही एका मुलासाठी/एकाहून अधिक मुलांसाठी सर्व खर्च कव्हर करू शकतो का? 💰",
    "Soll der Antrag eine Überraschung sein?" to "प्रस्ताव आश्चर्यकारक असावा का?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "अनुप्रयोगामध्ये सांस्कृतिक किंवा पारंपारिक घटक असावेत?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "अनुप्रयोगामध्ये सांस्कृतिक किंवा पारंपारिक घटक असावेत?",
    "Sommerhochzeit" to "उन्हाळी लग्न",
    "Sonnige Dachterrasse" to "सनी छताची टेरेस",
    "Sowohl als auch" to "दोन्ही आणि",
    "Spazieren" to "फिरायला जा",
    "Spaß & Abenteuer" to "मजा आणि साहस",
    "Speichern" to "जतन करा",
    "Spiel bearbeiten" to "गेम संपादित करा",
    "Spielbereich für Kinder" to "मुलांसाठी खेळण्याची जागा",
    "Spiele" to "खेळ",
    "Spiele spielen und Spaß haben" to "गेम खेळा आणि मजा करा",
    "Spontan" to "उत्स्फूर्त",
    "Sportplatz" to "क्रीडा क्षेत्र",
    "Spotify" to "Spotify",
    "Sprache" to "भाषा",
    "Stadt" to "शहर",
    "Stadt oder Land — was ist uns wichtiger?" to "शहर किंवा देश - आमच्यासाठी अधिक महत्त्वाचे काय आहे?",
    "Stadtvilla" to "सिटी व्हिला",
    "Standesamt & Party" to "नोंदणी कार्यालय आणि पक्ष",
    "Statement-Ring" to "स्टेटमेंट रिंग",
    "Stilvolles Outdoor-Sofa" to "स्टायलिश मैदानी सोफा",
    "Stimme voll zu" to "पूर्णपणे सहमत",
    "Stimmt" to "बरोबर",
    "Stimmt nicht" to "खरे नाही",
    "Stimmt, noch nie" to "खरे, कधीच नाही",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "बीच दिवस",
    "Streit über Haushalt" to "घरातील वाद",
    "Studio Ghibli" to "स्टुडिओ घिबली",
    "Ständig" to "सतत",
    "Suche schließen" to "शोध बंद करा",
    "Suche zurücksetzen" to "शोध रीसेट करा",
    "Suche öffnen" to "शोध उघडा",
    "Suchergebnisse" to "शोध परिणाम",
    "Sushi" to "सुशी",
    "Süß" to "गोड",
    "Tage zusammen 💞" to "दिवस एकत्र 💞",
    "Tauche ins Unterbewusstsein" to "अवचेतन मध्ये जा",
    "Teile alle deine Hobbys mit deinem Partner" to "तुमचे सर्व छंद तुमच्या जोडीदारासोबत शेअर करा",
    "Teils teils" to "अंशतः अंशतः",
    "Testen" to "चाचणी",
    "Themen" to "विषय",
    "Tiefe Gespräche" to "सखोल संभाषणे",
    "Tiefgründige Gespräche führen" to "सखोल संभाषण करा",
    "Tierpension" to "प्राणी बोर्डिंग हाऊस",
    "Tiny House" to "लहान घर",
    "Tippen zum Auswählen & Scrollen" to "निवडण्यासाठी आणि स्क्रोल करण्यासाठी टॅप करा",
    "Tippen zum Zuklappen" to "कोलॅप्स करण्यासाठी टॅप करा",
    "Titel" to "शीर्षक",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "शीर्षक, श्रेणी, विषय, टॅग्ज, प्रश्न...",
    "Tokyo, Japan" to "टोकियो, जपान",
    "Traditioneller Name" to "पारंपारिक नाव",
    "Traumhaus Außenbereich" to "स्वप्नातील घराबाहेरील क्षेत्र",
    "Traumhochzeit" to "स्वप्नातील लग्न",
    "Treffer" to "हिट",
    "Tägliche Aktivität" to "दैनिक क्रियाकलाप",
    "Umformulieren" to "रिफ्रेस",
    "Unbeantwortet" to "अनुत्तरित",
    "Unbeliebte Meinungen" to "लोकप्रिय नसलेली मते",
    "Universal Studios Genie oder Neuling?" to "युनिव्हर्सल स्टुडिओ प्रतिभावान किंवा नवशिक्या?",
    "Uns auseinanderzuleben" to "वेगळे वाढणे",
    "Unser Intimleben" to "आमचे जिव्हाळ्याचे जीवन",
    "Unser Traumhaus" to "आमचे स्वप्नातील घर",
    "Unser erstes Treffen" to "आमची पहिली भेट",
    "Unsere Gesichter" to "आमचे चेहरे",
    "Unsere eigenen Träume" to "आमची स्वतःची स्वप्ने",
    "Unsere nächste Reise" to "आमची पुढची सहल",
    "Unter 1000" to "1000 अंतर्गत",
    "Unter 1000 im Monat" to "दरमहा 1000 च्या खाली",
    "Unter 50€/Monat" to "50€/महिना अंतर्गत",
    "Unter Leuten" to "लोकांमध्ये",
    "Untreue" to "बेवफाई",
    "Urlaub" to "सुट्टी",
    "Vanille" to "व्हॅनिला",
    "Venedig" to "व्हेनिस",
    "Venedig, Italien" to "व्हेनिस, इटली",
    "Verbinde dich mit" to "सह कनेक्ट करा",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "उत्तर पाहण्यासाठी \${profile.partnerName} शी कनेक्ट करा",
    "Verbindung" to "कनेक्शन",
    "Verbringe die Feiertage mit deiner Familie" to "सुट्टी तुमच्या कुटुंबासोबत घालवा",
    "Verlobungsringe" to "प्रतिबद्धता रिंग",
    "Vertrautheit" to "परिचित",
    "Viel getrennt" to "खूप वेगळेपणा",
    "Vielleicht ein oder zwei" to "कदाचित एक किंवा दोन",
    "Vielleicht, aber mündlich reicht" to "कदाचित, पण तोंडी पुरेसे आहे",
    "Vielleicht, wenn es machbar ist" to "कदाचित, शक्य असल्यास",
    "Vielleicht, wenn es passt" to "कदाचित, जर ते फिट असेल",
    "Vintage Art déco" to "विंटेज आर्ट डेको",
    "Vintage verspielt" to "विंटेज खेळकर",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "तुमच्या जोडीदाराकडून नवीन छंदांची ओळख करून देणे",
    "Vor dem Kauf eines Hauses besprechen" to "घर खरेदी करण्यापूर्वी चर्चा करा",
    "Vor der Anschaffung eines Haustiers besprechen" to "पाळीव प्राणी खरेदी करण्यापूर्वी चर्चा करा",
    "Vor der gemeinsamen Reise besprechen" to "एकत्र प्रवास करण्यापूर्वी चर्चा करा",
    "Vor nichts" to "काहीही नाही",
    "Vorort" to "उपनगर",
    "Walnuss" to "अक्रोड",
    "Wandern" to "हायकिंग",
    "Wann fühlst du dich mir am nächsten?" to "तुला माझ्या सर्वात जवळचे कधी वाटते?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "तुम्हाला माझ्या शारीरिकदृष्ट्या सर्वात जवळचे कधी वाटते?",
    "Was bedeutet Vertrauen für dich konkret?" to "तुमच्यासाठी विश्वासाचा विशेष अर्थ काय?",
    "Was entspannt dich mehr?" to "कशामुळे तुम्हाला अधिक आराम मिळतो?",
    "Was fehlt dir über die Distanz am meisten?" to "अंतराबद्दल तुम्हाला सर्वात जास्त काय चुकते?",
    "Was gefällt dir an deinem Zuhause am besten?" to "तुम्हाला तुमच्या घरामध्ये सर्वात जास्त काय आवडते?",
    "Was hast du von deinem Partner gelernt?" to "तुम्ही तुमच्या जोडीदाराकडून काय शिकलात?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "कामुक सामग्री एकत्र पाहण्याबद्दल तुम्हाला काय वाटते?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "तुम्हाला प्रॉप्सबद्दल काय वाटते (उदा. चिन्हे, फुगे इ.)?",
    "Was ist das Wichtigste beim Antrag?" to "अर्ज करताना सर्वात महत्वाची गोष्ट कोणती आहे?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "लैंगिक चकमकीत तुम्ही सर्वात महत्वाची गोष्ट कोणती पहाता?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "तुमचा आमचा आवडता फोटो कोणता आहे? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "एकत्र राहण्याबद्दल तुमची सर्वात मोठी भीती काय आहे?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "तुम्हाला आवडते पण तुमच्या जोडीदाराला समजू शकत नाही असे अन्न कोणते आहे?",
    "Was ist für dich ein absoluter Dealbreaker?" to "तुमच्यासाठी परिपूर्ण डीलब्रेकर काय आहे?",
    "Was ist für jeden von uns das absolute Highlight?" to "आपल्यापैकी प्रत्येकासाठी परिपूर्ण हायलाइट काय आहे?",
    "Was ist passiert?" to "काय झाले?",
    "Was macht einen Moment für dich romantisch?" to "तुमच्यासाठी एखादा क्षण रोमँटिक कशामुळे होतो?",
    "Was magst du an deinem Partner am liebsten?" to "तुम्हाला तुमच्या जोडीदाराबद्दल सर्वात जास्त काय आवडते?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "तुम्हाला काय चांगले आवडते: लवकर उठणे किंवा उशिरा उठणे?",
    "Was magst du lieber?" to "तुम्हाला कोणते चांगले आवडते?",
    "Was möchtest du eigentlich sagen?" to "तुम्हाला नेमकं काय म्हणायचं आहे?",
    "Was möchtest du, dass dein Partner öfter tut?" to "तुम्हाला तुमच्या जोडीदाराने जास्त वेळा काय करायला आवडेल?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "आपण प्रवास करतो तेव्हा प्राण्याचे काय होते?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "आपल्या मुलाचे मोठे झाल्यावर त्याचे काय होईल?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "पालक म्हणून आपण कोणत्या गोष्टीकडे दुर्लक्ष करू नये?",
    "Was war dein schönster Moment mit mir bisher?" to "माझ्यासोबतचा तुमचा आतापर्यंतचा सर्वोत्तम क्षण कोणता होता?",
    "Was wir gegessen haben" to "आम्ही काय खाल्ले",
    "Was wollt ihr nie vergessen?" to "तुम्हाला काय विसरायचे नाही?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "तुमच्यासाठी काय वाईट होईल: पुन्हा कधीही पिझ्झा किंवा पुन्हा कधीही बर्गर करू नका?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "तुम्हाला एका दिवशी एकत्र काय करायला आवडेल?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "पैशाची समस्या नसल्यास तुम्ही लगेच काय बदलाल?",
    "Weiter" to "पुढे",
    "Weiter spielen" to "खेळणे सुरू ठेवा",
    "Weiß ich noch nicht" to "मला अजून माहित नाही",
    "Weiße Rosen" to "पांढरे गुलाब",
    "Weißgold" to "पांढरे सोने",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "आपल्या मुलाने आपल्याकडून नक्की कोणती गुणवत्ता मिळवावी?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "तुम्हाला प्रस्तावासाठी कोणते वातावरण हवे आहे?",
    "Welcher Raum sagt am meisten über dich aus?" to "कोणती खोली तुमच्याबद्दल सर्वात जास्त सांगते?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "आम्ही अन्न आणि पशुवैद्यकीयांसाठी कोणत्या बजेटची योजना करतो?",
    "Welches Lied macht dich an? 🥵" to "कोणते गाणे तुम्हाला चालू करते? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "कोणता शेअर केलेला फोटो तुमचा आवडता आहे?",
    "Wellnessbad" to "वेलनेस बाथ",
    "Wenn es schwierig ist" to "जेव्हा गोष्टी कठीण असतात",
    "Wenn ich müde bin" to "जेव्हा मी थकलो असतो",
    "Wenn wir uns lange umarmen" to "जेव्हा आपण बराच वेळ मिठी मारतो",
    "Wenn wir zusammen lachen" to "जेव्हा आपण एकत्र हसतो",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "काय ऑर्डर करायचे ते कोण अधिक लवकर ठरवते?",
    "Wer findet die besten Restaurants?" to "सर्वोत्तम रेस्टॉरंट कोणाला सापडतात?",
    "Wer gibt mehr Herzlichkeit?" to "कोण जास्त उबदारपणा देतो?",
    "Wer hat den besseren Musikgeschmack?" to "संगीताची आवड कोणाला चांगली आहे?",
    "Wer hängt mehr an seinen Eltern?" to "त्यांच्या पालकांशी कोण जास्त संलग्न आहे?",
    "Wer ist besser organisiert?" to "कोण अधिक व्यवस्थित आहे?",
    "Wer ist der Beste bei der Filmauswahl?" to "चित्रपट निवडण्यात सर्वोत्तम कोण आहे?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "रोमँटिक तारखांचे नियोजन करण्यात सर्वोत्तम कोण आहे?",
    "Wer ist der beste Tänzer?" to "सर्वोत्तम नर्तक कोण आहे?",
    "Wer ist romantischer?" to "कोण जास्त रोमँटिक आहे?",
    "Wer kocht besser?" to "कोण चांगले शिजवते?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "नूतनीकरण आणि देखभालीची काळजी कोण घेते?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "समोरची व्यक्ती बरी नसताना कोणाला लवकर लक्षात येते?",
    "Wer sucht am Ende wirklich den Film aus?" to "शेवटी चित्रपट कोण निवडतो?",
    "Wer vergisst eher einen Jahrestag?" to "वर्धापनदिन कोण विसरण्याची जास्त शक्यता आहे?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "दुसऱ्या दिवशी सकाळी स्वतःचे नाव विसरण्याची शक्यता कोण जास्त असेल?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "दुसऱ्या दिवशी कोणाला व्हिडिओ सापडण्याची अधिक शक्यता आहे ज्याबद्दल त्यांना काहीही माहिती नाही?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "अनोळखी व्यक्तीच्या सोफ्यावर रात्र घालवणे कोणाला आवडेल?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "पार्टीत कोणाला झोप लागण्याची आणि त्यांच्या चेहऱ्यावर शार्पीने उठण्याची जास्त शक्यता असते?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "डान्स फ्लोअरवर घसरण्याची जास्त शक्यता कोण असेल पण ती मस्त चाल सारखी दिसेल?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "घरच्या पार्टीत स्पॉटिफाई प्लेलिस्टवर कोण नियंत्रण ठेवण्याची शक्यता जास्त आहे?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "पार्टीत प्रत्येकासाठी पिझ्झा मागवण्याची आणि स्वतः खाण्याची अधिक शक्यता कोण असेल?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "पार्टीत आधी कोणाला झोप लागण्याची शक्यता जास्त असते?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "पार्टीमध्ये अचानक साफसफाई करण्यास कोणाची अधिक शक्यता असते?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "उलट सत्य असताना पूर्णपणे शांत असल्याचा दावा कोण करू शकेल?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "वादात प्रथम कोणाची बाजू घेण्याची अधिक शक्यता आहे?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "मद्यपानाच्या खेळात कोणाची फसवणूक होण्याची जास्त शक्यता असते?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "बुफेवर छापा टाकून गुपचूप अन्न घरी नेण्याची शक्यता कोण जास्त असेल?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "त्यांच्या कथेत संध्याकाळचा सर्वात लाजिरवाणा फोटो कोण पोस्ट करेल?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "स्वतःच्या आवडत्या गाण्याची विनंती करण्यासाठी डीजेला कोण जास्त त्रास देऊ शकेल?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "गाण्याचे बोल गाण्याची अधिक शक्यता कोण असेल, पण खात्रीने?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "मेनूमधील सर्वात महाग पेय ऑर्डर करण्याची आणि त्याबद्दल खेद वाटण्याची अधिक शक्यता कोण असेल?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "शेजाऱ्यांनी गोंगाटाची तक्रार केल्यास त्यांना आमंत्रित करण्याची अधिक शक्यता कोण असेल?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "पार्टी गेम्स (जसे की बिअर पाँग) कोण खूप गांभीर्याने घेईल?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "व्हीआयपी प्रवेश मिळवण्यासाठी बाऊन्सरशी मैत्री करण्याची अधिक शक्यता कोणाला असेल?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "उत्स्फूर्त कराओके लढाई सुरू करण्याची अधिक शक्यता कोण असेल?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "बॉटल ओपनर न वापरता बाटली उघडण्याची शक्यता कोण जास्त आहे?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "कोणीही विचारले नसले तरीही भाषण देण्याची अधिक शक्यता कोण असेल?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "बाथरूममध्ये एक तास सेल्फी घेण्यात कोण जास्त वेळ घालवू शकेल?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "लाजीरवाणी नृत्य सादर करून ते साजरे करण्याची अधिक शक्यता कोण असेल?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "पार्टी संपल्यानंतर माजी जोडीदाराला कॉल करण्याची अधिक शक्यता कोणाला असेल?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "एखाद्या अनोळखी पाहुण्याला चुकून नाराज करण्याची अधिक शक्यता कोणाला असेल?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "गुपचूप निरोप न घेता पार्टी सोडण्याची अधिक शक्यता कोण असेल?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "पाहुण्यांशी बोलण्यापेक्षा यजमानाच्या पाळीव प्राण्याबरोबर कोण खेळू शकेल?",
    "Wer würde eher spontan eine Reise buchen?" to "उत्स्फूर्तपणे ट्रिप बुक करण्याची अधिक शक्यता कोण असेल?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "स्वयंपाकघरात तासनतास सखोल गप्पा मारण्याची जास्त शक्यता कोणाला असेल?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "चुकून कोणाचे ड्रिंक पिण्याची जास्त शक्यता असते?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "चुकून महागड्या फुलदाण्यावर किंवा नाजूक वस्तूवर कोणाची टकटक होण्याची जास्त शक्यता असते?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "एक क्लिष्ट कॉकटेल स्वतः मिसळण्याचा प्रयत्न करण्याची आणि अयशस्वी होण्याची अधिक शक्यता कोण असेल?",
    "Wer würde eher zu spät kommen?" to "कोणाला उशीर होण्याची शक्यता जास्त आहे?",
    "Wer würde eher?" to "त्याऐवजी कोण करेल?",
    "Wer übernimmt die tägliche Versorgung?" to "रोजची काळजी कोण घेते?",
    "Werde so akzeptiert, wie du bist" to "तुम्ही जसे आहात तसे स्वीकारा",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "आमच्याकडे मुला/मुलांसाठी पुरेसा वेळ असेल का? ⏳",
    "Whirlpool" to "गरम टब",
    "White Chocolate" to "व्हाईट चॉकलेट",
    "Widgets" to "विजेट्स",
    "Wie fühlst du dich am meisten geliebt?" to "तुम्हाला सर्वात प्रिय कसे वाटते?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "आम्ही वेगवेगळ्या उत्पन्नांना कसे सामोरे जाऊ?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "तुमच्या जोडीदारासाठी तुमच्यासोबत सेक्स सुरू करण्याचा सर्वोत्तम मार्ग कोणता आहे?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "तुमचा जोडीदार तुमच्यासाठी आणखी चांगला भागीदार कसा असू शकतो?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "प्रस्तावानंतर तुम्हाला इतरांसोबत किती दिवस साजरे करायचे आहेत?",
    "Wie lange wollen wir dort mindestens bleiben?" to "आम्हाला तिथे किमान किती काळ राहायचे आहे?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "तुमच्यासाठी शुभेच्छांबद्दल बोलणे किती सोपे आहे?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "आमचे भविष्य कसे दिसावे असे तुम्हाला वाटते?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "तुमचा घरातील परिपूर्ण रविवार कसा दिसतो?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "सेक्स दरम्यान घाणेरड्या बोलण्याबद्दल तुम्हाला कसे वाटते?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "आपण वास्तविकपणे किती क्रेडिट घेऊ शकतो?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "आम्हाला किती वेळ घालवायचा आहे?",
    "Wie viel wollen wir insgesamt ausgeben?" to "आम्हाला एकूण किती खर्च करायचा आहे?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "बाळ आल्यावर आम्ही आमच्या नात्यासाठी वेळ कसा काढू?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "तो क्षण कॅप्चर करणे तुमच्यासाठी किती महत्त्वाचे आहे?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "अनुप्रयोग तुमचे छंद किंवा आवडी प्रतिबिंबित करतो हे तुमच्यासाठी किती महत्त्वाचे आहे?",
    "Wie würdest du sie/ihn nennen?" to "तुम्ही त्याला/तिला काय म्हणाल?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "सेक्सच्या बाहेर आपुलकी दाखवण्याचा तुमचा आवडता मार्ग कोणता आहे?",
    "Wildblumen" to "रानफुले",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "तुम्हाला मुलगी हवी आहे की मुलगा? 👶",
    "Wintergarten" to "हिवाळी बाग",
    "Winterhochzeit" to "हिवाळी लग्न",
    "Wir bestellen einfach beides" to "आम्ही फक्त दोन्ही ऑर्डर करतो",
    "Wir brauchen ewig" to "हे आपल्याला कायमचे घेते",
    "Wir einigen uns nie" to "आम्ही कधीही सहमत नाही",
    "Wir entscheiden es gemeinsam" to "आम्ही एकत्र ठरवतो",
    "Wir treffen uns in der Mitte" to "आम्ही मध्यभागी भेटतो",
    "Wir wechseln uns ab" to "आम्ही वळणे घेतो",
    "Wird stressig" to "तणावपूर्ण होतो",
    "Wobei lachst du am meisten?" to "तुम्हाला सर्वात जास्त हसायला कशामुळे येते?",
    "Wofür sparen wir gemeinsam?" to "आपण एकत्र कशासाठी बचत करत आहोत?",
    "Wohnzimmer" to "लिव्हिंग रूम",
    "Woran erinnerst du dich am lebhaftesten?" to "तुम्हाला सर्वात स्पष्टपणे काय आठवते?",
    "Worauf freust du dich bei uns am meisten?" to "तुम्ही आमच्यासोबत सर्वात जास्त कशाची वाट पाहत आहात?",
    "Worte/Komplimente" to "शब्द/स्तुती",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "आमच्या नात्यात तुम्हाला सर्वात जास्त कशाची भीती वाटते?",
    "Wünsche? z.B. günstig, draußen" to "शुभेच्छा? उदा. स्वस्त, बाहेर",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "तुम्ही सुट्टीत (प्रवासाचा समावेश असलेल्या) प्रपोज करण्यास प्राधान्य द्याल का?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube संगीत",
    "Zeichne für mich" to "माझ्यासाठी काढा",
    "Zeichne mich als Tier — welches wäre ich?" to "मला प्राणी म्हणून काढा - मी कोणता असेल?",
    "Zeichne unser Gefühl zueinander als Symbol." to "एक प्रतीक म्हणून आपल्या भावना एकमेकांकडे काढा.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "आमचे स्वप्नातील घर एका ओळीत काढा. सर्वात धक्कादायक गोष्ट काय आहे?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "आमची पहिली तारीख काढा - चित्रात नक्की काय असावे?",
    "Zeichnen" to "काढा",
    "Zeit füreinander" to "एकमेकांसाठी वेळ",
    "Zeit, wenn das Baby schläft" to "बाळाच्या झोपण्याची वेळ",
    "Zelten gehen" to "कॅम्पिंगला जा",
    "Zitrone" to "लिंबू",
    "Zu Hause, gemütlich und privat" to "घरी, आरामदायक आणि खाजगी",
    "Zu einem Picknick gehen" to "पिकनिकला जात आहे",
    "Zu einem ausgefallenen Abendessen gehen" to "एका फॅन्सी डिनरला जात आहे",
    "Zu zweit reisen" to "जोडपे म्हणून प्रवास करा",
    "Zuhause & Alltag" to "घर आणि दैनंदिन जीवन",
    "Zuhören" to "ऐका",
    "Zurück" to "मागे",
    "Zusammen seit" to "तेव्हापासून एकत्र",
    "Zusammen seit (TT.MM.JJJJ)" to "पासून एकत्र (DD.MM.YYYY)",
    "Zusammenziehen" to "करार",
    "Zustimmen oder Ablehnen" to "सहमत किंवा असहमत",
    "Zwei Kreise, die sich überschneiden" to "ओव्हरलॅप होणारी दोन मंडळे",
    "Zwei Stühle davor" to "समोर दोन खुर्च्या",
    "Zärtlich sein" to "कोमल व्हा",
    "Öfter als ich zugebe" to "मी कबूल करतो त्यापेक्षा जास्त वेळा",
    "Über 100€/Monat" to "100€/महिना पेक्षा जास्त",
    "Über 2000 im Monat" to "महिन्याला 2000 पेक्षा जास्त",
    "Über mich selbst" to "माझ्याबद्दल",
    "Übernehmen" to "लागू करा",
    "Überraschend" to "आश्चर्यकारक",
    "Überraschung" to "आश्चर्य",
    "Überspringen" to "वगळा",
    "Übertrieben und großartig" to "वरच्या बाजूला आणि छान",
    "✎ Tippe, um zu antworten" to "✎ उत्तर देण्यासाठी टॅप करा",
    "✨ GFK-Brücke" to "✨ GRP पूल",
)

internal fun localizeMarathiDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_MARATHI_CONTENT)
