package com.example.ui

/** Complete Polish locale pack. Canonical German keys, IDs and placeholders stay unchanged. */
internal val EXACT_POLISH_CONTENT: Map<String, String> = mapOf(
    "'{TITEL}' gelöscht." to "Usunięto „{TITEL}”.",
    "'{TITEL}' gespeichert." to "Zapisano „{TITEL}”.",
    "+ Hinzufügen" to "+ Dodaj",
    ", listOf(" to ", lista(",
    "1 Jahr lang in {ORT}" to "1 rok w {ORT}",
    "1 Jahr lang in {}" to "przez 1 rok w {}",
    "1 Jahr zusammen 🎉" to "1 rok razem 🎉",
    "1-5 Jahre" to "1-5 lat",
    "1000 - 1500 im Monat" to "1000 - 1500 miesięcznie",
    "1000 bis 3000" to "1000 do 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 miesięcznie",
    "2 Jahre zusammen 🎉" to "2 lata razem 🎉",
    "3 Jahre zusammen 🎉" to "3 lata razem 🎉",
    "3000 bis 5000" to "3000 do 5000",
    "5-10 Jahre" to "5-10 lat",
    "50-100€/Monat" to "50-100€/miesiąc",
    "6 Monate im Altbau mit Charme" to "6 miesięcy w urokliwym starym budynku",
    "6 Monate im {ORT}" to "6 miesięcy w {ORT}",
    "6 Monate im {}" to "6 miesięcy w {}",
    "?" to "?",
    "Ab 100€" to "Od 100 €",
    "Ab 500€" to "Od 500 €",
    "Ab 50€" to "Od 50 €",
    "Ab und zu" to "Od czasu do czasu",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "O jakiej kwocie mówimy przed dokonaniem zakupu?",
    "Abbrechen" to "Anulować",
    "Abenteuer" to "przygoda",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Działania",
    "Alex" to "Aleks",
    "Alle" to "Wszystko",
    "Alle Pakete" to "Wszystkie pakiety",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Stracić wszystkich przyjaciół z wyjątkiem najlepszego przyjaciela",
    "Alle intimen Momente selbst initiieren" to "Inicjuj wszystkie intymne chwile samodzielnie",
    "Alles davon" to "Wszystko",
    "Alles, was noch kommt" to "Wszystko, co ma nadejść",
    "Alltagsroutine" to "Codzienna rutyna",
    "Alltägliche Berührungen" to "Codzienne dotknięcia",
    "Als es einfach klar war" to "Kiedy było już po prostu jasno",
    "Altbau mit Charme" to "Stary budynek z urokiem",
    "Am Strand" to "Na plaży",
    "Am liebsten alles zusammen" to "Najlepiej wszystko razem",
    "Am selben Tag mit Freunden/Familie" to "Tego samego dnia z przyjaciółmi/rodziną",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Holandia",
    "An das Gefühl" to "Z uczucia",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "W miejscu publicznym z dużą liczbą widzów",
    "An einen Geruch" to "Zapachu",
    "An einen Song" to "Z piosenki",
    "An etwas, das ich gesagt habe" to "O czymś, co powiedziałem",
    "Analyse starten" to "Rozpocznij analizę",
    "Analysiere eure Muster..." to "Przeanalizuj swoje wzorce...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Analizuj swoje odpowiedzi i czaty według Gottmana i GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Ananas na pizzy smakuje wyśmienicie.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Odpowiedz zdjęciem",
    "Antworten, getrennt mit |" to "Odpowiedzi oddzielone |",
    "Antwortähnlichkeit" to "Odpowiedz na podobieństwo",
    "App-Sprache auswählen" to "Wybierz język aplikacji",
    "Auf eine Bootsparty gehen" to "Idź na imprezę na łodzi",
    "Aufmerksamkeit" to "Uwaga",
    "Aufräumen und Projekte angehen" to "Posprzątaj i zajmij się projektami",
    "Aufwärmen" to "Rozgrzać się",
    "Aufwärmen: Einander kennenlernen" to "Rozgrzewka: wzajemne poznanie się",
    "Aus dem Urlaub" to "Z wakacji",
    "Aus: nur Texte, Datei bleibt winzig" to "Wyłączone: tylko SMS-y, plik pozostaje niewielki",
    "Ausgefallener Name" to "Fantazyjne imię",
    "Ausschlafen und faulenzen" to "Śpij i leniuchuj",
    "Ausschlafen und nichts tun" to "Śpij i nic nie rób",
    "Aussehen" to "Patrzeć",
    "Auto" to "samochód",
    "Außenkamin" to "Kominek zewnętrzny",
    "BEANTWORTE" to "ODPOWIEDŹ",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonezja",
    "Banane" to "banan",
    "Beantwortet" to "Odpowiedziano",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Odpowiadaj na pytania w tym samym czasie — odpowiedzi nie będą widoczne, dopóki oboje nie skończycie.",
    "Beantwortete Fragen" to "Odpowiedzi na pytania",
    "Bearbeiten" to "Redagować",
    "Bei Insider-Witzen" to "Z żartami w środku",
    "Bei Memes" to "W memach",
    "Bei einer spontanen Berührung" to "Ze spontanicznym dotykiem",
    "Beide" to "Obydwa",
    "Beide gleich" to "Obydwa takie same",
    "Beide zusammen" to "Oboje razem",
    "Beide, aber wir tun so als ob nicht" to "Jedno i drugie, ale udajemy, że nie",
    "Beides" to "Obydwa",
    "Beides wäre schlimm" to "Jedno i drugie byłoby okropne",
    "Beim Einschlafen nebeneinander" to "Zasypianie obok siebie",
    "Beim Reden" to "Podczas rozmowy",
    "Belgische Schokolade" to "Belgijska czekolada",
    "Beliebiges / letztes Paar" to "Dowolna/ostatnia para",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Słynne miejsca turystyczne zawsze są rozczarowaniem.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Opisz nasze życie seksualne za pomocą emoji.",
    "Besser kommunizieren" to "Komunikuj się lepiej",
    "Bessere Lage" to "Lepsza lokalizacja",
    "Bestellen" to "Zamówienie",
    "Besuchte Länder" to "Kraje odwiedzone",
    "Besuchte Städte" to "Odwiedzone miasta",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Wolicie ekstrawagancką propozycję czy coś subtelnego?",
    "Beziehung" to "Relacja",
    "Bibliothek" to "biblioteka",
    "Bild für '{OPTION}' gesetzt." to "Ustawiono zdjęcie dla „{OPTION}”.",
    "Bild konnte nicht gelesen werden." to "Nie można odczytać obrazu.",
    "Bild wird übernommen…" to "Zdjęcie zostało zrobione...",
    "Bild {NUMMER} von {ANZAHL}…" to "Zdjęcie {NUMMER} z {ANZAHL}…",
    "Bild ändern" to "Zmień obraz",
    "Bilder" to "Kino",
    "Bilder & Städte" to "Obrazy i miasta",
    "Bilder einzeln teilen" to "Udostępniaj obrazy pojedynczo",
    "Bilder mitschicken" to "Wysyłajcie zdjęcia",
    "Bilder werden eingelesen…" to "Obrazy są odczytywane w...",
    "Bilder werden gelesen…" to "Obrazy są odczytywane...",
    "Bilder werden gespeichert…" to "Obrazy są zapisywane...",
    "Bilder-Ordner einlesen" to "Czytaj foldery obrazów",
    "Bildgröße im Export" to "Rozmiar obrazu w eksporcie",
    "Bin manchmal unsicher" to "Czasem czuję się niepewnie",
    "Bist du ein Videospiel-Guru?" to "Czy jesteś guru gier wideo?",
    "Blau" to "Niebieski",
    "Blumenwiese" to "Łąka kwiatowa",
    "Bunte Blumenwiese" to "Kolorowa łąka kwiatowa",
    "Burger" to "Obywatele",
    "Burger King" to "Burger King",
    "Chat" to "Pogawędzić",
    "Coca-Cola" to "Coca-Cola",
    "Cookie Dough" to "Ciasto ciasteczkowe",
    "Dachgarten mit Lounge" to "Ogród na dachu z salonem",
    "Dachterrasse" to "Taras na dachu",
    "Das Wetter an dem Tag" to "Pogoda tego dnia",
    "Das erste Selfie" to "Pierwsze selfie",
    "Das erste Treffen" to "Pierwsze spotkanie",
    "Das klingt schön 🥰" to "Brzmi nieźle 🥰",
    "Das meiste weiß ich" to "Większość z tego znam",
    "Das oder Das" to "To czy tamto",
    "Das oder das" to "To czy tamto",
    "Das oder das?" to "To czy tamto?",
    "Das tägliche Leben" to "Życie codzienne",
    "Dass Zusagen gehalten werden" to "Że obietnice są dotrzymywane",
    "Dass alles meinen Stil hat" to "Że wszystko jest w moim stylu",
    "Dass ich alles erzählen kann" to "Że mogę powiedzieć wszystko",
    "Dass ich mich nicht sorgen muss" to "Że nie muszę się martwić",
    "Dass wir ungestört sind" to "Że jesteśmy niezakłóceni",
    "Dateinamen wie 01a_vanille.jpg / 01b_schoko.jpg werden automatisch als Paar erkannt." to "Nazwy plików takie jak 01a_vanille.jpg / 01b_schoko.jpg są automatycznie rozpoznawane jako para.",
    "Daten werden eingespielt…" to "Dane są importowane...",
    "Dein Name" to "Twoje imię",
    "Deine Antwort..." to "Twoja odpowiedź...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Twoje odpowiedzi zostały zapisane. Gdy tylko Partner zakończy pakiet, obie odpowiedzi będą widoczne razem.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Twoje odpowiedzi zostały zapisane. Gdy \${profile.partnerName} zakończy pakiet, obie odpowiedzi będą widoczne razem.",
    "Deine Antworten sind gespeichert. Sobald {PARTNER} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Twoje odpowiedzi zostały zapisane. Gdy {PARTNER} ukończy pakiet, obie odpowiedzi będą widoczne razem.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Spraw, aby Twój związek był pełen przygód i spontaniczny",
    "Deine Beziehung stabil und sicher machen" to "Spraw, aby Twój związek był stabilny i bezpieczny",
    "Deine eigene Antwort" to "Twoja własna odpowiedź",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Raczej podziel się swoimi najgłębszymi sekretami ze swoim partnerem",
    "Deinen besten Freund verlieren" to "Utrata najlepszego przyjaciela",
    "Dem Spiel fehlt noch ein Titel." to "Grze nadal brakuje tytułu.",
    "Denke an dich" to "Pomyśl o sobie",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Oglądanie tego samego filmu dwa razy to strata czasu.",
    "Der Blick nach draußen" to "Widok na zewnątrz",
    "Der Garten" to "Ogród",
    "Der Ort" to "Miejsce",
    "Der Ring und die Geste" to "Pierścionek i gest",
    "Der erste Kuss" to "Pierwszy pocałunek",
    "Der perfekte Heiratsantrag" to "Idealna propozycja małżeństwa",
    "Derjenige sein, der umarmt wird" to "Bądź tym, który jest przytulany",
    "Deutsch" to "niemiecki",
    "Dev" to "Rozw",
    "Diamant" to "diament",
    "Diamanten im Band" to "Diamenty w zespole",
    "Die Distanz" to "Odległość",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Spędź wakacje z rodziną swojego partnera",
    "Die Gemütlichkeit und Ruhe" to "Przytulność i spokój",
    "Die Menschen, die darin wohnen" to "Ludzie, którzy tam mieszkają",
    "Die Umgebung und Atmosphäre" to "Środowisko i atmosfera",
    "Die Worte und Emotionen" to "Słowa i emocje",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Najlepsze wyzwanie w postaci quizu rozrywkowego",
    "Diejenige sein, die umarmt" to "Bądź tym, który przytula",
    "Direkt ansprechen" to "Adresuj bezpośrednio",
    "Diskussion" to "dyskusja",
    "Diskutiere vor dem Kinderkriegen" to "Porozmawiaj przed urodzeniem dzieci",
    "Diskutiert eure Antworten" to "Omów swoje odpowiedzi",
    "Disney" to "Disney",
    "Doch, schon mal" to "Tak, już",
    "Draußen mit der Natur als Kulisse" to "Na zewnątrz z przyrodą w tle",
    "Drei-Stein-Ring" to "Trzy kamienne pierścienie",
    "Du bist dran" to "Twoja kolej",
    "Du fehlst mir" to "Tęsknię za tobą",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubaj, Zjednoczone Emiraty Arabskie",
    "Dunkles Design" to "Ciemny projekt",
    "Durch Berührung" to "Dotyk",
    "Durch Worte" to "Poprzez słowa",
    "Durch Zeit zu zweit" to "Przez czas razem",
    "Durch kleine Gesten" to "Poprzez małe gesty",
    "Durchgeplant" to "Planowany",
    "ERGEBNISSE" to "WYNIKI",
    "Egal, Hauptsache gesund" to "Nieważne, najważniejsze jest zdrowe",
    "Ehepaar Leben" to "Życie małżeństwa",
    "Eher knapp" to "Raczej blisko",
    "Eher nicht" to "Raczej nie",
    "Eher schwer" to "Niełatwy",
    "Eher schwierig" to "Niełatwy",
    "Eher zu" to "Raczej też",
    "Eifersucht ist ein Zeichen von Liebe." to "Zazdrość jest oznaką miłości.",
    "Eigenes Bild" to "Własne zdjęcie",
    "Eigenes Bild für '{OPTION}' entfernt." to "Usunięto własne zdjęcie dla „{OPTION}”.",
    "Eigenes Gemüsebeet" to "Własna grządka warzywna",
    "Ein Abenteuer in einer neuen Stadt" to "Przygoda w nowym mieście",
    "Ein Anker" to "Kotwica",
    "Ein Balkon oder Garten" to "Balkon lub ogród",
    "Ein Bild bleibt übrig und wird ignoriert." to "Pozostaje jeden obraz, który jest ignorowany.",
    "Ein Filmabend" to "Wieczór filmowy",
    "Ein Harmony-Meilenstein eurer Liebe." to "Kamień milowy harmonii Twojej miłości.",
    "Ein Herz" to "Serce",
    "Ein Herz an der Tür" to "Serce u drzwi",
    "Ein Jahr lang eine Fernbeziehung führen" to "Bądź w związku na odległość przez rok",
    "Ein Kindheitsessen" to "Jedzenie z dzieciństwa",
    "Ein Live-Musik-Konzert besuchen" to "Weź udział w koncercie muzyki na żywo",
    "Ein Museum besuchen" to "Odwiedź muzeum",
    "Ein Spieleabend" to "Wieczór gier",
    "Ein Spieleabend mit Freunden" to "Wieczór gier z przyjaciółmi",
    "Ein Urlaubsfoto" to "Zdjęcie z wakacji",
    "Ein aktives Abenteuer" to "Aktywna przygoda",
    "Ein entspannender Spa-Tag" to "Relaksujący dzień w spa",
    "Ein ganz normaler Alltagstag" to "Zupełnie normalny, codzienny dzień",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Przytulny wieczór w domu podczas burzy",
    "Ein gemütliches Date drinnen" to "Przytulna randka w pomieszczeniu",
    "Ein lustiges Bild" to "Zabawny obrazek",
    "Ein paar Handyfotos reichen" to "Wystarczy kilka zdjęć zrobionych telefonem komórkowym",
    "Ein paar Stunden" to "Kilka godzin",
    "Ein paar kulturelle Anklänge sind okay" to "Kilka odniesień kulturowych jest w porządku",
    "Ein romantischer Abend" to "Romantyczny wieczór",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Romantyczna kolacja przy świecach",
    "Ein romantisches Bild" to "Romantyczny obrazek",
    "Ein romantisches Picknick an einem schönen Ort" to "Romantyczny piknik w pięknym miejscu",
    "Ein schwerer Moment, den wir geschafft haben" to "Trudny moment, który daliśmy radę",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Wspaniała randka na świeżym powietrzu w świetle księżyca",
    "Ein ungewöhnliches Gericht" to "Nietypowe danie",
    "Ein zufälliger Schnappschuss" to "Losowe zdjęcie",
    "Einander kennenlernen" to "Poznajcie się",
    "Eine Autoreise" to "Wycieczka samochodowa",
    "Eine Brücke" to "Most",
    "Eine Date-Nacht unter den Sternen" to "Randka pod gwiazdami",
    "Eine Million Dollar gewinnen" to "Wygraj milion dolarów",
    "Eine Million Dollar verdienen" to "Zarób milion dolarów",
    "Eine Nacht in einem Club" to "Wieczór w klubie",
    "Eine Schokoladenverkostung" to "Degustacja czekolady",
    "Eine Wanderung mit Panoramablick machen" to "Wybierz się na wycieczkę z panoramicznymi widokami",
    "Eine Weinverkostung" to "Degustacja wina",
    "Eine einzige Textdatei mit Paketen und Bildern. AI Studio nimmt keine ZIPs —" to "Pojedynczy plik tekstowy zawierający pakiety i obrazy. AI Studio nie pobiera ZIP-ów —",
    "Eine gemeinsame Reise" to "Wspólna podróż",
    "Eine gemütliche Nacht zu Hause" to "Przytulna noc w domu",
    "Eine neue Sprache zu lernen ist einfach." to "Nauka nowego języka jest łatwa.",
    "Einen Film anschauen" to "Obejrzyj film",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Przez miesiąc nie rozmawialiśmy ze sobą w ogóle",
    "Einen Tanzkurs besuchen" to "Weź udział w zajęciach tanecznych",
    "Einen Vergnügungspark erkunden" to "Poznaj park rozrywki",
    "Einen Wellness-Tag" to "Dzień dobrego samopoczucia",
    "Einen sehr emotionalen Partner haben" to "Posiadanie bardzo emocjonalnego partnera",
    "Einen sehr logischen Partner haben" to "Posiadanie bardzo logicznego partnera",
    "Einer zahlt alles" to "Wszystko płaci jedna osoba",
    "Einfach mehr Alltag" to "Po prostu więcej codzienności",
    "Einfach nebeneinander sein" to "Po prostu bądźcie obok siebie",
    "Einfach und intim" to "Prosto i intymnie",
    "Einige Dinge für dich behalten" to "Zachowaj pewne rzeczy dla siebie",
    "Einmal" to "Raz",
    "Eins, das nur wir kennen" to "Takie, które tylko my znamy",
    "Einspielen" to "Zagraj",
    "Eis" to "Lód",
    "Eissorten" to "Smaki lodów",
    "Emoji" to "Emoji",
    "Englisch" to "angielski",
    "Entfernen" to "Usunąć",
    "Enthält alle Spiele, Ketten, Kategorien UND alle eingebetteten Bilder als Base64. Ideal zur Sicherung, Übertragung & Wiederherstellung." to "Obejmuje wszystkie gry, łańcuchy, kategorie ORAZ wszystkie osadzone obrazy w formacie Base64. Idealny do tworzenia kopii zapasowych, przesyłania i przywracania.",
    "Entspannte Hängematte" to "Zrelaksowany hamak",
    "Entspannung" to "relaks",
    "Entwickler Studio" to "Studio deweloperskie",
    "Entwickler Studio Öffnen" to "Otwórz Studio programistów",
    "Entwickler-Modus" to "Tryb programisty",
    "Erdbeere" to "truskawka",
    "Erfolgreich" to "Udany",
    "Ergebnisse" to "Wyniki",
    "Erst bei sehr großen Summen" to "Tylko za bardzo duże sumy",
    "Erst nur enge Freunde/Familie" to "Na początku tylko bliscy przyjaciele/rodzina",
    "Erstelle ein Ketten-Paket, um Fragen dynamisch mit bisherigen Antworten zu verknüpfen." to "Utwórz pakiet łańcuchowy, aby dynamicznie łączyć pytania z poprzednimi odpowiedziami.",
    "Erzähl mir mehr davon 💕" to "Opowiedz mi o tym więcej 💕",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Denerwuje mnie, gdy mój partner zbyt długo odpowiada na wiadomości.",
    "Essen & Genuss" to "Jedzenie i przyjemność",
    "Essensvorlieben" to "Preferencje żywieniowe",
    "Etwa eine Woche später, erst mal nur wir" to "Mniej więcej tydzień później, na początku tylko my",
    "Etwas Neues ausprobieren" to "Spróbuj czegoś nowego",
    "Etwas ganz anderes" to "Coś zupełnie innego",
    "Etwas sehr Scharfes" to "Coś bardzo ostrego",
    "Etwas, das ich selbst gern erfinde" to "Coś, co sam chętnie wymyślam",
    "Etwas, eine kleine Note wäre schön" to "Coś, mały dotyk byłby miły",
    "Export für Google AI Studio" to "Eksportuj do Google AI Studio",
    "Export wird gebaut…" to "Eksport się buduje…",
    "Familie" to "Rodzina",
    "Familie/Freunde" to "Rodzina/przyjaciele",
    "Familienmensch" to "Człowiek rodzinny",
    "Farbedelstein" to "Kolorowy kamień szlachetny",
    "Fehler bei der Analyse: {FEHLER}" to "Błąd analizy: {FEHLER}",
    "Fehler bei der Ideengenerierung: {FEHLER}" to "Błąd generowania pomysłów: {FEHLER}",
    "Fehler bei der Umformulierung: {FEHLER}" to "Błąd podczas przeredagowania: {FEHLER}",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Reklamy telewizyjne są czasami interesujące do oglądania.",
    "Fertig" to "Gotowy",
    "Fertig!" to "Kompletny!",
    "Fertig: {PAKETE} Pakete · {BILDER} Bilder · {DETAILS}" to "Gotowe: {PAKETE} pakietów · {BILDER} zdjęć · {DETAILS}",
    "Feste Date-Nights" to "Stałe noce na randki",
    "Feste Option" to "Naprawiono opcję",
    "Fester Text" to "Naprawiono tekst",
    "Feuerstelle" to "Miejsce na ognisko",
    "Filigran & schlicht" to "Filigranowe i proste",
    "Filme/Serien" to "Filmy/seriale",
    "Formuliere um..." to "Sformułuj ponownie...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Sformułuj swój projekt bez użycia przemocy: obserwacja, uczucie, potrzeba, prośba.",
    "Frage hinzufügen" to "Dodaj pytanie",
    "Frage löschen" to "Usuń pytanie",
    "Frage {NUMMER}" to "Pytanie {NUMMER}",
    "Fragen" to "Pytania",
    "Fragen & Spiele" to "Pytania i gry",
    "Fragen für jede Gelegenheit" to "Pytania na każdą okazję",
    "Fragetext" to "Tekst pytania",
    "Freier Text" to "Tekst dowolny",
    "Freizeitpark" to "Wesołe miasteczko",
    "Freunde treffen" to "spotkać przyjaciół",
    "Freundschaften mit Ex-Partnern sind okay." to "Przyjaźń z byłymi jest w porządku.",
    "Früh aufstehen" to "Aby wcześnie wstać",
    "Fußbodenheizung" to "Ogrzewanie podłogowe",
    "Führen wir getrennte oder gemeinsame Konten?" to "Czy mamy konta oddzielne czy wspólne?",
    "Für AI Studio exportieren" to "Eksport do AI Studio",
    "Für dich empfohlen" to "Polecane dla Ciebie",
    "Für die Zukunft" to "Na przyszłość",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Nie znaleziono pasujących pytań ani gier do tego wyszukiwania.",
    "Für immer" to "Na zawsze",
    "Fürsorglichkeit" to "Opiekuńczy",
    "GFK Brücke" to "Most z GRP",
    "GFK-Brücke" to "Most z GRP",
    "Galerie" to "galeria",
    "Gar nicht, der Moment gehört uns" to "Wcale nie, ta chwila jest nasza",
    "Gar nichts tun" to "Nie rób nic",
    "Geduld" to "Cierpliwości",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Idź wcześnie rano, aby zobaczyć wschód słońca",
    "Geht so" to "Idzie OK",
    "Geister existieren wirklich." to "Duchy naprawdę istnieją.",
    "Gelassenheit" to "ukojenie",
    "Gelbgold" to "Żółte złoto",
    "Geld & Finanzen" to "Pieniądze i finanse",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Wspólnie podróżujcie po świecie, odkrywajcie nowe kultury i kuchnie",
    "Gemeinsam ein Lego bauen" to "Zbuduj razem Lego",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Wypróbujcie wspólnie nowy przepis w kuchni",
    "Gemeinsame Konten" to "Wspólne konta",
    "Gemeinsame Nächte" to "Noce razem",
    "Gemeinsame Tage" to "Wspólne dni",
    "Gemischt" to "Mieszany",
    "Gemüsebeet" to "grządka warzywna",
    "Gemütliche Feuerstelle" to "Przytulne miejsce na ognisko",
    "Gesprächsanreger" to "Rozpoczęcie rozmowy",
    "Getrennte Konten" to "Oddzielne konta",
    "Getrennte Urlaube tun einer Beziehung gut." to "Oddzielne wakacje są dobre dla związku.",
    "Gewächshaus" to "szklarnia",
    "Gewählt" to "Wybrany",
    "Gewählte Antwort" to "Wybrana odpowiedź",
    "Glasfassade" to "Szklana fasada",
    "Gleichgültigkeit" to "obojętność",
    "Glücklich und frei" to "Szczęśliwy i wolny",
    "Gold" to "Złoto",
    "Gourmet Eis-Sorten" to "Odmiany lodów dla smakoszy",
    "Gravur innen" to "Grawer wewnątrz",
    "Grillplatz" to "Miejsce na grilla",
    "Groß & üppig" to "Duży i bujny",
    "Groß · 960px" to "Duży · 960 pikseli",
    "Große Familie" to "Duża rodzina",
    "Große Feier" to "Wielkie świętowanie",
    "Große Fenster" to "Duże okna",
    "Große Fensterfront" to "Duże okno z przodu",
    "Großer Außenpool" to "Duży odkryty basen",
    "Großer Garten" to "Duży ogród",
    "Großer Stein" to "Duży kamień",
    "Größere Küche" to "Większa kuchnia",
    "Gutes Essen" to "Ciesz się posiłkiem",
    "HARMONY" to "HARMONIA",
    "Habe ich" to "Ja mam",
    "Habe ich noch nie" to "Nigdy tego nie robiłem",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Czy odkryłeś jakieś zaskakujące różnice? Porozmawiaj o tym, dlaczego niektóre opcje podobają Ci się bardziej!",
    "Haha du bringst mich immer zum Lachen 😄" to "Haha zawsze mnie rozśmieszasz 😄",
    "Haus am See" to "Dom nad jeziorem",
    "Haus/Wohnung" to "Dom/mieszkanie",
    "Hazelnut" to "Orzech laskowy",
    "Heimkino" to "Kino domowe",
    "Herzhaft" to "Serdeczny",
    "Hey du 💕 wie war dein Tag?" to "Hej ty 💕 jak minął dzień?",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Nic tu teraz nie ma.\nZmień filtr lub wybierz inny temat.",
    "Hier ist gerade nichts. ↵ Wechsle den Filter oder wähle ein anderes Thema." to "Nic tu teraz nie ma. ↵ Zmień filtr lub wybierz inny temat.",
    "Hier ist gerade nichts.\\nWechsle den Filter oder wähle ein anderes Thema." to "W tej chwili nic tu nie ma.\\nZmień filtr lub wybierz inny temat.",
    "Hilfe im Alltag" to "Pomoc w życiu codziennym",
    "Himbeere" to "malina",
    "Hinzufügen" to "Dodać",
    "Hobbys" to "Hobby",
    "Hochzeit" to "Ślub",
    "Hochzeitssträuße" to "Bukiety ślubne",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Duma domu Hogwartu: Gdzie należysz?",
    "Home" to "Dom",
    "Hot Tub" to "Gorąca wanna",
    "Humor" to "Poczucie humoru",
    "Hund" to "Pies",
    "Hängematte" to "hamak",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Czy chciałbyś otrzymać list pisemny jako część wniosku?",
    "IKEA" to "IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Wolę romantyczne spacery po parku niż wyjście do kina.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Nigdy nie zasnąłem w kinie.",
    "Ich denk so oft an dich ❤️" to "Często o Was myślę ❤️",
    "Ich denke an dich" to "Myślę o tobie",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Lubię odkrywać nowe hobby lub zajęcia z moim partnerem.",
    "Ich finde eine Alternative" to "Znajdę alternatywę",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Lubię próbować nowych restauracji z moim partnerem, zamiast ciągle chodzić do tych samych miejsc.",
    "Ich hab schon an unser Wiedersehen gedacht 🥹" to "Już myślałam o naszym spotkaniu 🥹",
    "Ich habe noch nie" to "Nigdy tego nie robiłem",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Nigdy nie bałem się kolejki górskiej, a mimo to wsiadłem na nią.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Nigdy nie kupiłem biletów Fast Pass z powodu niecierpliwości.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Nigdy nie odwołałam planów pozostania w domu i oglądania programu telewizyjnego.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Nigdy nie czekałem na mój list z Hogwartu.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Nigdy nie mówiłem, że Slytherin nie jest taki zły.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Nigdy nie twierdziłem, że jestem za stary na filmy Disneya (i skrycie je lubiłem).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Nigdy celowo nie strzeliłem do kogoś z niebieskim czołgiem w Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Nigdy nie płakałam na filmie Disneya.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Nigdy nie zamykałem oczu podczas oglądania horroru.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Nigdy nie zapomniałem zapisać gry i straciłem wiele godzin postępu.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Nigdy nie opuściłem pokoju podczas żenującej sceny (czynnik wywołujący wzdrygnięcie).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Nigdy nie przyjmowałem śmiesznej pozy podczas robienia zdjęcia kolejki górskiej.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Nigdy nie grałem do późna w nocy i żałowałem, że następnego dnia byłem zmęczony.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Nigdy nie sprawdzałam w Google zakończenia filmu, bo nie mogłam się doczekać.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Nigdy nie czułem się, jakbym był na planie filmowym.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Nigdy nie opuściłem wstępu do mojego ulubionego serialu.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Nigdy nie udostępniałem nikomu hasła do serwisu Netflix.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Nigdy nie słyszałem ścieżki dźwiękowej z gry podczas pracy lub nauki.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Nigdy nie winiłem kontrolera, kiedy przegrałem.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Nigdy ze złości nie wyrzuciłem klawiatury ani kontrolera.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Nigdy nie zapomniałam mokrych ubrań w pralce przez kilka dni.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Nigdy nie wydałem prawdziwych pieniędzy na przedmioty kosmetyczne w grze.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Nigdy nie jeździłem samochodem za granicą.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Nigdy nie śpiewałam piosenki Disneya pod prysznicem.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Nigdy nie jeździłem samochodem elektrycznym.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Nigdy nie robiłem zdjęcia z maskotką parku.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Nigdy nie nazwałem zwierzaka na cześć postaci z Hogwartu.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Nigdy nie upuściłem popcornu w kinie i mimo to go zjadłem.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Nigdy w życiu codziennym nie używałem cytatów Mistrza Yody z Gwiezdnych Wojen.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Nigdy nie kupiłem drogiej pamiątki w parku rozrywki.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Nigdy nie dałem rekomendacji filmu, który druga osoba uznała za okropny.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Nigdy nie oglądałem Oscarów na żywo w środku nocy.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Nigdy nie anulowałem serialu, bo poprzedni sezon był tak zły.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Nigdy nie obejrzałem całego sezonu serialu w jeden dzień.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Nigdy nie pokonałem bossa za pierwszym razem i nie czułem się jak bóg.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Nigdy nie widziałem złoczyńcy fajniejszego od bohatera.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Nigdy nie rozpoznałem postaci z „Toy Story” w moich zabawkach.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Nigdy nie stworzyłem postaci w grze RPG opartej dokładnie na moim wyglądzie.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Nigdy nie jadłem churro w parku rozrywki.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Nigdy nie oglądałem filmu Disneya trzy razy z rzędu.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Nigdy nie słyszałem chwytliwej melodii Disneya przez cały tydzień.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Nigdy nie oglądałem filmu tylko ze względu na konkretnego aktora.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Nigdy nie słuchałem godzinami ścieżki dźwiękowej filmu.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Nigdy nie ujawniłem spoilera filmowego i od razu tego pożałowałem.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Nigdy nie spotkałem przyjaciela, który mówiłby w innym języku ojczystym.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Nigdy nie miałem przyjaciela, który przeprowadziłby się do innego kraju.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Nigdy nie uczestniczyłam w Bożym Narodzeniu w maratonie filmowym o Harrym Potterze.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Nigdy nie obejrzałem filmu Marvela do końca tylko ze względu na scenę po napisach.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Nigdy celowo nie zirytowałem NPC (postaci niezależnej).",
    "Ich habe noch nie einen Nachtzug genommen." to "Nigdy nie jechałem nocnym pociągiem.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Nigdy nie brałem udziału w teście online, żeby dowiedzieć się, jaki jest mój dom w Hogwarcie.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Nigdy nie usuwałem postów w mediach społecznościowych, ponieważ nie uzyskały wystarczającej liczby polubień.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Nigdy nie nazwałem dnia w parku rozrywki najlepszym dniem w roku.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Nigdy nie byłem w parku tematycznym i zostawałem tam od rana do wieczora.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Nigdy nie opuściłem przejażdżki Transformersem lub Marvelem całkowicie zahipnotyzowany.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Nigdy nie wpadłem w złość (Rage Quit) i nie wyszedłem z gry.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Nigdy nie czytałem żadnej z większych książek o Harrym Potterze.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Nigdy nie zachwycałem się moją ulubioną postacią w serialu.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Nigdy nie marzyłem o grze w Quidditcha.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Nigdy potajemnie nie szukałam w Google, jak rozwiązać trudny poziom.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Nigdy w tajemnicy nie liczyłam, że mój zwierzak będzie mówił tak, jak w Disneyu.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Nigdy nie zdejmowałem drabinki basenowej w Simsach.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Nigdy nie straciłem orientacji podczas jazdy na symulatorze 3D.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Nigdy nie grałem w uniwersyteckiej drużynie sportowej.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Nigdy nie czekałem w kolejce na jedną atrakcję dłużej niż dwie godziny.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Nigdy nie zamoczyłem cennych rzeczy podczas przejażdżki wodnej.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Nigdy nie kłóciłem się z przyjacielem, który dom jest najlepszy.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Nigdy nie udawałam, że mam magiczne moce jak Elsa.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Nigdy nie śmiałem się tak bardzo, że przegapiłem ważną scenę w filmie.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Nigdy nie czułem takiej adrenaliny, że od razu zapragnąłem znowu jeździć.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Nigdy nie próbowałam śpiewać ze zwierzętami takimi jak Królewna Śnieżka.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Nigdy nie marzyłam o wycieczce do Disneylandu.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Nigdy nie marzyłem o przejażdżce wodnej w Parku Jurajskim.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Nigdy nie krzyczałem na głos podczas jump-scare'a w grze.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Nigdy nie płakałem z powodu finału programu telewizyjnego.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Nigdy... nie odwołałam randki, żeby zostać w domu.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Nigdy... nie przeformułowałem wiadomości 10 razy.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Nigdy... potajemnie nie zaglądałam do telefonu mojego partnera.",
    "Ich habe noch nie!" to "nigdy!",
    "Ich habe!" to "Ja mam!",
    "Ich lache viel mit meinem Partner." to "Dużo się śmieję z moim partnerem.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Lubię poznawać hobby i zainteresowania mojego partnera.",
    "Ich liebe es" to "Kocham to",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Uwielbiam oglądać z partnerem filmy, których żadne z nas wcześniej nie widziało.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Uwielbiam dzielić się moją ulubioną muzyką z moim partnerem.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Nigdy nie musiałem biec, żeby złapać lot przesiadkowy.",
    "Ich plane gerne Dates mit meinem Partner." to "Lubię planować randki z partnerem.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Priorytetem jest dla mnie spędzanie czasu z partnerem, nawet gdy jestem zajęty.",
    "Ich schreibe meinem Partner jeden Tag." to "Codziennie piszę SMS-y do mojego partnera.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Lubię dzielić się memami i dowcipami z moim partnerem.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Lubię dzielić się z partnerem wszystkimi szczegółami mojego dnia.",
    "Ich vermiss dich gerade richtig" to "Naprawdę za tobą teraz tęsknię",
    "Ich würde es nie tun" to "Nigdy bym tego nie zrobił",
    "Ich übe noch" to "Nadal ćwiczę",
    "Ideen generieren" to "Generuj pomysły",
    "Im Haushalt helfen" to "Pomoc w domu",
    "In Chat einfügen" to "Dodaj do czatu",
    "In Stille nebeneinander" to "W ciszy obok siebie",
    "In den Bergen" to "W górach",
    "In eine Bar gehen" to "Idź do baru",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Idę do baru na plaży, żeby obejrzeć zachód słońca",
    "In einem feinen Restaurant essen gehen" to "Jedzenie w dobrej restauracji",
    "In einen Coffeeshop gehen" to "Idź do kawiarni",
    "In einer Beziehung sollte man alles voneinander wissen." to "W związku powinniście wiedzieć o sobie wszystko.",
    "Infinity-Pool" to "Basen bez krawędzi",
    "Inhalt & Bilder jetzt einspielen" to "Zaimportuj teraz zawartość i obrazy",
    "Innenpool" to "Kryty basen",
    "Intelligenz" to "inteligencja",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Mieć intymne chwile tylko wtedy, gdy inicjuje je twój partner",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Kod zaproszenia: HRM-8731 · wszystko odblokowane",
    "Island" to "Islandia",
    "Ist okay für mich" to "Dla mnie to w porządku",
    "Ist schon perfekt" to "Jest już idealnie",
    "JSON Backup Datei wird erstellt…" to "Tworzony jest plik kopii zapasowej JSON...",
    "JSON Backup wird vorbereitet…" to "Przygotowywana jest kopia zapasowa JSON…",
    "JSON oder Export-Inhalt (mit Base64) hier einfügen" to "Wklej tutaj JSON lub wyeksportuj zawartość (z Base64).",
    "JSON teilen" to "Udostępnij JSON",
    "Ja, Traditionen einbinden" to "Tak, uwzględnij tradycje",
    "Ja, absolut" to "Tak, absolutnie",
    "Ja, etwas zum Lesen und Aufbewahren" to "Tak, coś do przeczytania i zachowania",
    "Ja, genug" to "Tak, wystarczy",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Tak, w ekscytującym mieście lub atrakcji",
    "Ja, in- und auswendig" to "Tak, wewnątrz i na zewnątrz",
    "Ja, komplett überraschend" to "Tak, całkowicie zaskakujące",
    "Ja, perfekt" to "Tak, idealnie",
    "Ja, sie gehören zur Familie!" to "Tak, oni są rodziną!",
    "Ja, sofort teilen" to "Tak, udostępnij natychmiast",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Tak, zadbamy o to, aby czas rodzinny był priorytetem.",
    "Jacuzzi" to "jacuzzi",
    "Jahr zusammen 🎉" to "rok razem 🎉",
    "Jahre zusammen 🎉" to "Wspólne lata 🎉",
    "Je zwei Bilder werden ein Paar. Die Reihenfolge unten ist die Reihenfolge im Spiel —" to "Co dwa zdjęcia tworzą parę. Poniższa kolejność jest kolejnością w grze —",
    "Jede Option aus allen Spielen. Tippen und ein eigenes Bild aus der Galerie wählen." to "Każda opcja ze wszystkich gier. Stuknij i wybierz własne zdjęcie z galerii.",
    "Jeder zahlt 50%" to "Każdy płaci 50%",
    "Jerome" to "Hieronim",
    "Junge" to "Chłopiec",
    "Kamin" to "Komin",
    "Karriere & Erfolg" to "Kariera i sukces",
    "Kategorie" to "kategoria",
    "Kategorie '{TITEL}' gespeichert." to "Zapisano kategorię „{TITEL}”.",
    "Kategorie (z.B. Eis)" to "Kategoria (np. lody)",
    "Kategorie bearbeiten" to "Edytuj kategorię",
    "Kategorie-Farbe wählen" to "Wybierz kolor kategorii",
    "Kategorien" to "Kategorie",
    "Kategorien & Farben" to "Kategorie i kolory",
    "Katze" to "Kot",
    "Kein Paket gewählt" to "Nie wybrano pakietu",
    "Keine Antwort erhalten." to "Nie otrzymano odpowiedzi.",
    "Keine Bilder in diesem Ordner gefunden." to "W tym folderze nie znaleziono żadnych obrazów.",
    "Keine Musik" to "Żadnej muzyki",
    "Keine Pakete zum Exportieren." to "Brak pakietów do wyeksportowania.",
    "Keine Party nötig, privat halten" to "Żadna impreza nie jest konieczna, zachowaj prywatność",
    "Keine Privatsphäre" to "Brak prywatności",
    "Keine Treffer gefunden" to "Nie znaleziono żadnych wyników",
    "Keine eigenen Bilder vorhanden." to "Brak własnych zdjęć.",
    "Keiner" to "Nic",
    "Keiner von uns" to "Żaden z nas",
    "Kekse und ein Brief — ich musste weinen vor Freude." to "Ciasteczka i list - płakałam z radości.",
    "Kennst du die Essensvorlieben deines Partners?" to "Czy znasz preferencje żywieniowe swojego partnera?",
    "Kette '{TITEL}' gelöscht." to "Usunięto łańcuch „{TITEL}”.",
    "Kette '{TITEL}' gespeichert." to "Zapisano łańcuch „{TITEL}”.",
    "Kette bauen" to "Zbuduj łańcuch",
    "Kette bearbeiten" to "Edytuj łańcuch",
    "Kette gestartet" to "Uruchomiono łańcuch",
    "Kinder" to "Dzieci",
    "Kino" to "Kino",
    "Kirchlich" to "Kościelny",
    "Klassisch Solitär" to "Klasyczny pasjans",
    "Klassisch gebunden" to "Klasycznie oprawiona",
    "Klein & zart" to "Mały i delikatny",
    "Klein · 480px" to "Mały · 480 pikseli",
    "Kleine Geschenke" to "Małe prezenty",
    "Kleine Runde" to "Mały okrągły",
    "Kochen und Freunde einladen" to "Gotuj i zapraszaj znajomych",
    "Kochkurs" to "Lekcje gotowania",
    "Kommt auf den Tag an" to "Zależy od dnia",
    "Kommt darauf an" to "To zależy",
    "Kommt drauf an" to "To zależy",
    "Kommt mit" to "Proszę ze mną",
    "Konzert" to "koncert",
    "Kopfzeile (z.B. Weil du {A} gewählt hast …)" to "Nagłówek (np. Ponieważ wybrałeś {A}...)",
    "Kopieren" to "Kopia",
    "Koralle" to "koral",
    "Kräftige Farben" to "Mocne kolory",
    "Kräuterbeet" to "Łóżko ziołowe",
    "Kultur & Sehenswürdigkeiten" to "Kultura i zabytki",
    "Kuscheln" to "Przytulić się",
    "Kuss" to "pocałunek",
    "Kuss senden" to "Wyślij buziaka",
    "Können wir heute Abend telefonieren?" to "Czy możemy porozmawiać przez telefon dziś wieczorem?",
    "Körperliche Annäherung" to "Podejście fizyczne",
    "Körperliche Nähe" to "Bliskość fizyczna",
    "Küche" to "Kuchnia",
    "Land" to "kraj",
    "Landhaus" to "wiejski dom",
    "Landhausstil" to "Styl wiejski",
    "Lange wach bleiben" to "Nie śpij do późna",
    "Lappland" to "Laponia",
    "Lappland, Finnland" to "Laponia, Finlandia",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Niech Twój partner zainspiruje Cię do bycia najlepszą wersją siebie",
    "Lavendel" to "lawenda",
    "Leeren" to "Pusty",
    "Lehne ab" to "Spadek",
    "Leichtigkeit" to "Lekkości",
    "Leidenschaft" to "Pasja",
    "Liebe im Gleichgewicht" to "Miłość w równowadze",
    "Liebe sie, macht mehr Spaß" to "Uwielbiam je, więcej zabawy",
    "Lieber durchgeplant oder spontan?" to "Wolisz mieć to zaplanowane czy spontaniczne?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Wolisz spędzić spokojny wieczór we dwoje czy z kimś?",
    "Lieber nicht" to "Raczej nie",
    "Lieber vorher grob absprechen" to "Lepiej wcześniej porozmawiać z grubsza",
    "Lila" to "Fioletowy",
    "Limetten grün" to "Limonkowa zieleń",
    "Linke Karte (Seite A)" to "Lewa karta (strona A)",
    "Linke Option (0)" to "Opcja lewa (0)",
    "Lokal einkaufen" to "Zakupy lokalne",
    "London" to "Londyn",
    "London, England" to "Londyn, Anglia",
    "Löschen" to "Usuwać",
    "Lügen" to "Kłamstwo",
    "Magenta" to "magenta",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Wolisz propozycję publiczną czy prywatną?",
    "Malediven" to "Malediwy",
    "Man sollte nie streitend einschlafen." to "Nigdy nie powinieneś zasypiać, kłócąc się.",
    "Mango Sorbet" to "Sorbet mango",
    "Markant & breit" to "Uderzające i szerokie",
    "Marken & Alltag" to "Marki i codzienność",
    "McDonald’s" to "McDonald’s",
    "Mediterraner Innenhof" to "Śródziemnomorski dziedziniec",
    "Mehr Unterstützung" to "Więcej wsparcia",
    "Mehr gemeinsame Zeit" to "Więcej czasu razem",
    "Mehr zuhören" to "Słuchaj więcej",
    "Mehrgenerationenhaus" to "Dom wielopokoleniowy",
    "Mein Arbeitsplatz" to "Moje miejsce pracy",
    "Mein Partner" to "Mój partner",
    "Mich überraschen" to "Zaskocz mnie",
    "Mindestens zwei Bilder auswählen." to "Wybierz co najmniej dwa obrazy.",
    "Minimalistisches Interieur" to "Minimalistyczne wnętrze",
    "Missverständnisse" to "Nieporozumienia",
    "Mit Familie und engen Freunden" to "Z rodziną i bliskimi przyjaciółmi",
    "Mit Kompromissen" to "Z kompromisami",
    "Mitgefühl" to "Współczucie",
    "Mittel · 720px" to "Średni · 720 pikseli",
    "Mittelweg mit besonderen Details" to "Środek ze specjalnymi detalami",
    "Modern geometrisch" to "Nowoczesna geometria",
    "Moderne Grillstation" to "Nowoczesna stacja grillowa",
    "Moderner Name" to "Nowoczesne imię",
    "Moderner Solitär" to "Nowoczesny pasjans",
    "Moissanit" to "Moissanit",
    "Moment festhalten" to "Uchwyć chwilę",
    "Momente" to "chwile",
    "Monaco" to "Monako",
    "Moralische Werte" to "Wartości moralne",
    "Museum" to "muzeum",
    "Musik" to "Muzyka",
    "Mut" to "Odwagę",
    "Mädchen" to "Dziewczyna",
    "Möbelhaus" to "Sklep meblowy",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Czy na pewno chcesz opuścić quiz? Twoje poprzednie postępy pozostają zapisane.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Czy chciałbyś, aby w aplikacji uwzględnione były zwierzęta?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Chcesz, aby chwila była natychmiast udostępniana w mediach społecznościowych?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Być może będziemy musieli poczynić oszczędności",
    "Müssen es planen" to "Muszę to zaplanować",
    "Müssen sparen" to "Trzeba zapisać",
    "Nach oben" to "W górę",
    "Nach unten" to "Zniżkowy",
    "Nachricht an" to "Wiadomość do",
    "Name" to "nazwa",
    "Name (optional - leer lassen für kein Text)" to "Imię (opcjonalnie — pozostaw puste, aby nie było tekstu)",
    "Name (optional)" to "Imię (opcjonalnie)",
    "Name Partnerin" to "Imię partnera",
    "Namen und Startdatum eurer Beziehung." to "Imię i data rozpoczęcia związku.",
    "Natursteinfassade" to "Elewacja z kamienia naturalnego",
    "Naturteich" to "Naturalny staw",
    "Nein, einfach halten" to "Nie, po prostu trzymaj",
    "Nein, erstmal privat halten" to "Nie, na razie zachowaj to dla siebie",
    "Nein, lieber vor Ort" to "Nie, lepiej na miejscu",
    "Nein, modern halten" to "Nie, postaw na nowoczesność",
    "Nein, nur wir" to "Nie, tylko my",
    "Nein, zu ablenkend" to "Nie, zbyt rozpraszające",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Nowy budynek z inteligentnym domem",
    "Neubau mit Technik" to "Nowy budynek z technologią",
    "Neue Kategorie" to "Nowa kategoria",
    "Neue Kategorie erstellen" to "Utwórz nową kategorię",
    "Neue Kette" to "Nowy łańcuch",
    "Neue Kette erstellen" to "Utwórz nowy łańcuch",
    "Neue Liebe, neue Erfahrungen" to "Nowa miłość, nowe doświadczenia",
    "Neuen Schritt hinzufügen" to "Dodaj nowy krok",
    "Neues Hobby" to "Nowe hobby",
    "Neues Spiel" to "Nowa gra",
    "Neugier" to "Ciekawość",
    "New York" to "Nowy Jork",
    "New York, USA" to "Nowy Jork, USA",
    "Nicht gewählt" to "Nie wybrany",
    "Nicht mein Fall" to "Nie mój przypadek",
    "Nicht nötig, lieber klassisch bleiben" to "Nie jest to konieczne, lepiej pozostać klasycznym",
    "Nichts — es passt so" to "Nic - tak pasuje",
    "Nie wieder Burger" to "Nigdy więcej burgerów",
    "Nie wieder Pizza" to "Nigdy więcej pizzy",
    "Niemand" to "Nikt",
    "Niemand ohne Plan" to "Nikt bez planu",
    "Nike" to "Nike",
    "Nizza" to "Ładny",
    "Noch keine Ketten angelegt" to "Nie założono jeszcze łańcuchów",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Brak momentów.\nUwiecznijcie swoje pierwsze wspólne przeżycie 💞",
    "Noch keine Momente. ↵ Haltet euer erstes Erlebnis fest 💞" to "Brak momentów. ↵ Uwiecznijcie swoje pierwsze wspólne przeżycie 💞",
    "Noch keine Momente.\\nHaltet euer erstes Erlebnis fest 💞" to "Nie ma jeszcze żadnych chwil.\\nUchwyć swoje pierwsze doświadczenie 💞",
    "Nur Optionen ohne eigenes Bild" to "Tylko opcje bez własnego wizerunku",
    "Nur bei wichtigen Themen" to "Tylko na ważne tematy",
    "Nur wir beide" to "Tylko my dwoje",
    "Nähe & Intimität" to "Bliskość i intymność",
    "OR" to "LUB",
    "Obstgarten" to "sad",
    "Oder" to "Lub",
    "Offene Küche" to "Otwarta kuchnia",
    "Offene Wohnküche" to "Otwarta kuchnia/salon",
    "Ohne Stein" to "Bez kamienia",
    "Open End" to "Otwarte zakończenie",
    "Option suchen…" to "Opcja wyszukiwania…",
    "Orange" to "Pomarańczowy",
    "Ordner" to "Falcówka",
    "Ordner rein · Paare raus · Export für AI Studio" to "Folder w · Pary · Eksport do AI Studio",
    "Ordner wird gelesen…" to "Trwa odczytywanie folderu...",
    "Outdoor-Küche" to "Kuchnia na świeżym powietrzu",
    "Outdoor-Sofa" to "Sofa plenerowa",
    "Outdoor-Whirlpool" to "Zewnętrzna wanna z hydromasażem",
    "Ovaler Diamant" to "Owalny diament",
    "Paar" to "Para",
    "Paar / Option:" to "Para/opcja:",
    "Paar löschen" to "Usuń parę",
    "Paar {NUMMER}" to "Para {NUMMER}",
    "Paar-Statistiken" to "Statystyki par",
    "Paare mischen" to "Mieszaj pary",
    "Paare — tippe auf ein Bild, um es zu tauschen" to "Pary — dotknij obrazu, aby go zamienić",
    "Paket erstellen & freischalten" to "Utwórz i aktywuj pakiet",
    "Pakete (nichts ausgewählt = alle)" to "Pakiety (nic nie zostało wybrane = wszystkie)",
    "Pakete mit dynamischen Bauanleitungen, die sich aus bisherigen Antworten zusammensetzen." to "Pakiety z dynamicznymi instrukcjami budowania, które składają się z poprzednich odpowiedzi.",
    "Paris" to "Paryż",
    "Paris oder Rom" to "Paryż czy Rzym",
    "Paris, Frankreich" to "Paryż, Francja",
    "Partner" to "partner",
    "Partner-Simulator" to "Symulator partnera",
    "Partnerin" to "partner",
    "Party Edition" to "Wydanie imprezowe",
    "Party Edition II" to "II edycja imprezy",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Czy zwierzę w ogóle pasuje do naszego codziennego życia?",
    "Pasta" to "makaron",
    "Pastell" to "Pastel",
    "Penthouse mit Ausblick" to "Penthouse z widokiem",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pergola z salonem",
    "Pfingstrosen" to "Piwonie",
    "Pinguin" to "pingwin",
    "Pistazie" to "pistacja",
    "Pizza" to "pizza",
    "Pizzaofen" to "Piec do pizzy",
    "Platin" to "platyna",
    "PlayStation" to "PlayStation",
    "Pool" to "basen",
    "Pop" to "muzyka pop",
    "Prasselnder Kamin" to "Ryczący kominek",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Księżniczki, piraci i wróżkowy pył: quiz Disneya",
    "Privater Innenhof" to "Prywatny dziedziniec",
    "Profil" to "profil",
    "Profil bearbeiten" to "Edytuj profil",
    "Prozentual nach Einkommen" to "Procent od dochodu",
    "Quell-Paket:" to "Pakiet źródłowy:",
    "Quelle wählen:" to "Wybierz źródło:",
    "Quiz" to "kwiz",
    "Quiz verlassen" to "Opuść quiz",
    "Quiz verlassen?" to "Opuścić quiz?",
    "Rausgehen in die Natur" to "Wyjdź na łono natury",
    "Rechte Karte (Seite B)" to "Prawa karta (strona B)",
    "Rechte Option (1)" to "Właściwa opcja (1)",
    "Reden vor ..." to "Przemówienia przed...",
    "Reden vor..." to "Przemówienia przed...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Planujcie wspólne daty i godziny",
    "Reisen" to "Podróż",
    "Reiseziele" to "Miejsca docelowe",
    "Respektlosigkeit" to "brak szacunku",
    "Restaurant" to "restauracja",
    "RnB / Soul" to "RnB/Soul",
    "Rock" to "głaz",
    "Rom" to "Rzym",
    "Rom, Italien" to "Rzym, Włochy",
    "Romantik" to "romans",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Romantyczne gesty, takie jak wiadomości, notatki czy prezenty, sprawiają mi radość.",
    "Romantische Stimmung" to "Romantyczny nastrój",
    "Rosa" to "Różowy",
    "Roségold" to "Różowe złoto",
    "Rubinrot" to "Rubinowa czerwień",
    "Ruhig zu zweit" to "Cicho dla dwojga",
    "Runder Diamant" to "Okrągły diament",
    "Salted Caramel" to "Solony karmel",
    "Sammle Ideen..." to "Zbieraj pomysły...",
    "Santorini" to "Santoryn",
    "Santorini, Griechenland" to "Santoryn, Grecja",
    "Saphir" to "szafir",
    "Satzmuster (z.B. 1 Jahr lang in {})" to "Wzory zdań (np. na 1 rok w {})",
    "Satzmuster (z.B. 6 Monate im {})" to "Wzór zdania (np. 6 miesięcy w {})",
    "Saunahaus" to "Dom z sauną",
    "Schickes Restaurant oder Hotel" to "Elegancka restauracja lub hotel",
    "Schlafzimmer" to "sypialnia",
    "Schließen" to "Zamknąć",
    "Schmal & zart" to "Szczupła i delikatna",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Migawki z naszej historii miłosnej",
    "Schnelltest" to "Szybki test",
    "Schokolade" to "Czekolada",
    "Schreib frei, was dir wirklich dazu einfällt." to "Napisz swobodnie, co naprawdę przychodzi Ci do głowy.",
    "Schreibe deine eigene Antwort" to "Napisz własną odpowiedź",
    "Schritt {NUMMER}" to "Krok {NUMMER}",
    "Sehr gerne" to "Bardzo chętnie",
    "Sehr leicht" to "Bardzo lekki",
    "Sehr wichtig — Fotos und Video" to "Bardzo ważne — zdjęcia i wideo",
    "Sehr wichtig, es sollte persönlich sein" to "Bardzo ważne, powinno być osobiste",
    "Seite:" to "Strona:",
    "Selbst kochen" to "Gotuj sobie",
    "Senden" to "Wysłać",
    "Separate Küche" to "Oddzielna kuchnia",
    "Serie schauen" to "Oglądaj serię",
    "Serienmarathon auf dem Sofa" to "Serialowy maraton na kanapie",
    "Sex & Liebe" to "Seks i miłość",
    "Seychellen" to "Seszele",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Czy jesteśmy w stanie pokryć wszystkie koszty za jedno dziecko/kilka dzieci? 💰",
    "Smaragd" to "szmaragd",
    "Soll der Antrag eine Überraschung sein?" to "Czy propozycja powinna być zaskoczeniem?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Czy aplikacja powinna zawierać elementy kulturowe czy tradycyjne?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Czy aplikacja powinna zawierać elementy kulturowe czy tradycyjne?",
    "Sommerhochzeit" to "Letni ślub",
    "Sonnige Dachterrasse" to "Słoneczny taras na dachu",
    "Sonst zählt die alphabetische Reihenfolge." to "W przeciwnym razie liczy się kolejność alfabetyczna.",
    "Sowohl als auch" to "jak również",
    "Spazieren" to "Spacer",
    "Spaß & Abenteuer" to "Zabawa i przygoda",
    "Speichere Bild {NUMMER} von {ANZAHL}…" to "Zapisywanie zdjęcia {NUMMER} z {ANZAHL}…",
    "Speichern" to "Ratować",
    "Speichern & testen" to "Zapisz i przetestuj",
    "Spiel bearbeiten" to "Edytuj grę",
    "Spiel suchen…" to "Wyszukaj grę...",
    "Spiel-Emoji" to "Emoji z gry",
    "Spielbereich für Kinder" to "Miejsce zabaw dla dzieci",
    "Spiele" to "zawody sportowe",
    "Spiele & Städte bearbeiten, Ordner reinladen, Bilder anpassen" to "Edytuj gry i miasta, ładuj foldery, dostosowuj obrazy",
    "Spiele spielen und Spaß haben" to "Graj w gry i baw się dobrze",
    "Spielen" to "Grać",
    "Spieltyp" to "Typ gry",
    "Spontan" to "Spontaniczny",
    "Sportplatz" to "Boisko sportowe",
    "Spotify" to "Spotify",
    "Sprache" to "Język",
    "Stadt" to "Miasto",
    "Stadt oder Land — was ist uns wichtiger?" to "Miasto czy wieś – co jest dla nas ważniejsze?",
    "Stadtvilla" to "Willa miejska",
    "Standardbild" to "Domyślny obraz",
    "Standesamt & Party" to "Urząd stanu cywilnego i impreza",
    "Startet ein Spiel im echten Runner — genau so, wie ihr es später spielt." to "Rozpocznij grę w prawdziwym Runnerze — dokładnie tak, jak będziesz grać później.",
    "Statement-Ring" to "Pierścień oświadczenia",
    "Stilvolles Outdoor-Sofa" to "Stylowa sofa ogrodowa",
    "Stimme voll zu" to "Całkowicie się zgadzam",
    "Stimmt" to "PRAWDA",
    "Stimmt nicht" to "Nieprawda",
    "Stimmt, noch nie" to "Zgadza się, nigdy",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Dzień na plaży",
    "Streit über Haushalt" to "Spór o gospodarstwo domowe",
    "Stressig — aber jetzt wird’s besser ☺️" to "Stresujące — ale teraz wszystko się poprawia ☺️",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "Stały",
    "Suche schließen" to "Zamknij wyszukiwanie",
    "Suche zurücksetzen" to "Zresetuj wyszukiwanie",
    "Suche öffnen" to "Otwórz wyszukiwanie",
    "Suchergebnisse" to "Wyniki wyszukiwania",
    "Sushi" to "Sushi",
    "Süß" to "Słodki",
    "Tage zusammen 💞" to "Wspólne dni 💞",
    "Tauche ins Unterbewusstsein" to "Zanurz się w podświadomość",
    "Teile alle deine Hobbys mit deinem Partner" to "Podziel się wszystkimi swoimi hobby ze swoim partnerem",
    "Teils teils" to "Częściowo częściowo",
    "Testen" to "Test",
    "Themen" to "Tematy",
    "Tiefe Gespräche" to "Głębokie rozmowy",
    "Tiefgründige Gespräche führen" to "Prowadź głębokie rozmowy",
    "Tiere" to "Zwierzęta",
    "Tierpension" to "Obiekt do przyjmowania zwierząt",
    "Tiny House" to "Mały dom",
    "Tippen zum Auswählen & Scrollen" to "Kliknij, aby wybrać i przewinąć",
    "Tippen zum Zuklappen" to "Kliknij, aby zwinąć",
    "Titel" to "tytuł",
    "Titel des Ketten-Spiels" to "Tytuł gry łańcuchowej",
    "Titel des Spiels" to "Tytuł gry",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Tytuł, kategoria, temat, tagi, pytania...",
    "Tokyo, Japan" to "Tokio, Japonia",
    "Traditioneller Name" to "Tradycyjna nazwa",
    "Traumhaus Außenbereich" to "Wymarzony teren na zewnątrz domu",
    "Traumhochzeit" to "Wymarzony ślub",
    "Treffer" to "Uderzyć",
    "Tägliche Aktivität" to "Codzienna aktywność",
    "Türkis" to "Turkus",
    "Umformulieren" to "Sformułuj ponownie",
    "Unbeliebte Meinungen" to "Niepopularne opinie",
    "Unbenannte Kette" to "Nienazwany łańcuch",
    "Universal Studios Genie oder Neuling?" to "Geniusz czy nowicjusz z Universal Studios?",
    "Uns auseinanderzuleben" to "Rozejść się",
    "Unser Intimleben" to "Nasze życie intymne",
    "Unser Traumhaus" to "Nasz wymarzony dom",
    "Unser erstes Gespräch" to "Nasza pierwsza rozmowa",
    "Unser erstes Treffen" to "Nasze pierwsze spotkanie",
    "Unser erstes Videodate" to "Nasza pierwsza randka wideo",
    "Unsere Gesichter" to "Nasze twarze",
    "Unsere eigenen Träume" to "Naszych własnych marzeń",
    "Unsere nächste Reise" to "Nasza kolejna podróż",
    "Unter 1000" to "Poniżej 1000",
    "Unter 1000 im Monat" to "Poniżej 1000 miesięcznie",
    "Unter 50€/Monat" to "Poniżej 50€/miesiąc",
    "Unter Leuten" to "Wśród ludzi",
    "Unterhaltung" to "Rozrywka",
    "Untreue" to "niewierność",
    "Urlaub" to "Wakacje",
    "VS" to "VS",
    "Vanille" to "Wanilia",
    "Venedig" to "Wenecja",
    "Venedig, Italien" to "Wenecja, Włochy",
    "Verbinde dich mit" to "Połącz się z",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Połącz się z \${profile.partnerName}, aby zobaczyć odpowiedź",
    "Verbinde dich mit {PARTNER}" to "Połącz się z {PARTNER}",
    "Verbinde dich mit {PARTNER}, um die Antwort zu sehen" to "Połącz się z {PARTNER}, aby zobaczyć odpowiedź",
    "Verbindung" to "Połączenie",
    "Verbringe die Feiertage mit deiner Familie" to "Spędź wakacje z rodziną",
    "Verlobungsringe" to "Pierścionki zaręczynowe",
    "Vertrautheit" to "znajomość",
    "Verworfen" to "Wyrzucony",
    "Verworfene Antwort" to "Odrzucona odpowiedź",
    "Viel getrennt" to "Bardzo oddzielone",
    "Vielleicht ein oder zwei" to "Może jeden lub dwa",
    "Vielleicht, aber mündlich reicht" to "Być może, ale werbalnie wystarczy",
    "Vielleicht, wenn es machbar ist" to "Być może, jeśli jest to wykonalne",
    "Vielleicht, wenn es passt" to "Może, jeśli będzie pasować",
    "Vier Stunden geredet und die Zeit vergessen." to "Rozmawiałem cztery godziny i straciłem poczucie czasu.",
    "Vintage Art déco" to "Vintage Art Deco",
    "Vintage verspielt" to "Vintage zabawny",
    "Vollständiges Projekt-Backup (JSON)" to "Pełna kopia zapasowa projektu (JSON)",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Zostanie wprowadzonym w nowe hobby przez swojego partnera",
    "Vor dem Kauf eines Hauses besprechen" to "Porozmawiaj przed zakupem domu",
    "Vor der Anschaffung eines Haustiers besprechen" to "Porozmawiaj przed zakupem zwierzaka",
    "Vor der gemeinsamen Reise besprechen" to "Porozmawiajcie przed wspólną podróżą",
    "Vor nichts" to "Z niczego",
    "Vorlieben für den Antrag" to "Preferencje dla aplikacji",
    "Vorort" to "przedmieście",
    "Vorschau:" to "Zapowiedź:",
    "Walnuss" to "orzech włoski",
    "Wandern" to "Wycieczka",
    "Wann fühlst du dich mir am nächsten?" to "Kiedy czujesz się najbliżej mnie?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Kiedy czujesz się fizycznie najbliżej mnie?",
    "Was bedeutet Vertrauen für dich konkret?" to "Co konkretnie oznacza dla Ciebie zaufanie?",
    "Was entspannt dich mehr?" to "Co Cię bardziej relaksuje?",
    "Was fehlt dir über die Distanz am meisten?" to "Czego najbardziej brakuje Ci w dystansie?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Co najbardziej lubisz w swoim domu?",
    "Was hast du von deinem Partner gelernt?" to "Czego nauczyłeś się od swojego partnera?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Co sądzisz o wspólnym oglądaniu treści erotycznych?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Co sądzisz o rekwizytach (np. znakach, balonach itp.)?",
    "Was ist das Wichtigste beim Antrag?" to "Co jest najważniejsze podczas aplikowania?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Jaka jest najważniejsza rzecz, na którą zwracasz uwagę podczas spotkania seksualnego?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Jakie jest Twoje ulubione nasze zdjęcie? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Czego najbardziej się obawiasz, jeśli chodzi o wspólne mieszkanie?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Jakie jedzenie uwielbiasz, a Twój partner tego nie rozumie?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Co jest dla Ciebie absolutnym przełomem?",
    "Was ist für jeden von uns das absolute Highlight?" to "Co jest dla każdego z nas absolutną atrakcją?",
    "Was ist passiert?" to "Co się stało?",
    "Was macht einen Moment für dich romantisch?" to "Co sprawia, że ​​chwila jest dla Ciebie romantyczna?",
    "Was magst du an deinem Partner am liebsten?" to "Co najbardziej lubisz w swoim partnerze?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Co wolisz: wstawać wcześnie czy spać do późna?",
    "Was magst du lieber?" to "Co lubisz bardziej?",
    "Was möchtest du eigentlich sagen?" to "Co właściwie chcesz powiedzieć?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Co chciałbyś, żeby Twój partner robił częściej?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Co dzieje się ze zwierzęciem podczas podróży?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Co stanie się z naszym dzieckiem, gdy dorośnie?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Czego jako rodzice nie powinniśmy nigdy tracić z oczu?",
    "Was war dein schönster Moment mit mir bisher?" to "Jaki był Twój najpiękniejszy moment ze mną do tej pory?",
    "Was wir gegessen haben" to "Co jedliśmy",
    "Was wollt ihr nie vergessen?" to "Czego nigdy nie chcesz zapomnieć?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Co byłoby dla Ciebie gorsze: nigdy więcej pizzy czy nigdy więcej burgerów?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Co najbardziej chciałbyś robić w jeden dzień razem?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Co zmieniłbyś od razu, gdyby pieniądze nie stanowiły problemu?",
    "Weil du {A} gewählt hast …" to "Ponieważ wybrałeś {A}...",
    "Weil du {OPTION} gewählt hast …" to "Ponieważ wybrałeś {OPTION} …",
    "Weiter" to "Dalej",
    "Weiter spielen" to "Graj dalej",
    "Weiß ich noch nicht" to "jeszcze nie wiem",
    "Weiße Rosen" to "Białe róże",
    "Weißgold" to "Białe złoto",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Jaką cechę nasze dziecko powinno koniecznie po nas odziedziczyć?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Jakie środowisko chciałbyś otrzymać jako propozycję?",
    "Welcher Raum sagt am meisten über dich aus?" to "Który pokój mówi o Tobie najwięcej?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Jaki budżet planujemy na karmę i weterynarza?",
    "Welches Lied macht dich an? 🥵" to "Która piosenka Cię kręci? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Które wspólne zdjęcie jest Twoim ulubionym?",
    "Wellnessbad" to "Kąpiel wellness",
    "Wenn es schwierig ist" to "Kiedy jest trudno",
    "Wenn ich müde bin" to "Kiedy jestem zmęczony",
    "Wenn wir uns lange umarmen" to "Kiedy przytulamy się przez dłuższy czas",
    "Wenn wir zusammen lachen" to "Kiedy się razem śmiejemy",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Kto u Was szybciej decyduje, co zamawiacie?",
    "Wer findet die besten Restaurants?" to "Kto znajduje najlepsze restauracje?",
    "Wer gibt mehr Herzlichkeit?" to "Kto daje więcej ciepła?",
    "Wer hat den besseren Musikgeschmack?" to "Kto ma lepszy gust muzyczny?",
    "Wer hängt mehr an seinen Eltern?" to "Kto jest bardziej przywiązany do swoich rodziców?",
    "Wer ist besser organisiert?" to "Kto jest lepiej zorganizowany?",
    "Wer ist der Beste bei der Filmauswahl?" to "Kto najlepiej wybiera filmy?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Kto jest najlepszy w planowaniu romantycznych randek?",
    "Wer ist der beste Tänzer?" to "Kto jest najlepszym tancerzem?",
    "Wer ist romantischer?" to "Kto jest bardziej romantyczny?",
    "Wer kocht besser?" to "Kto gotuje lepiej?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Kto zajmuje się remontami i konserwacją?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Kto szybciej zauważa, gdy drugie źle się czuje?",
    "Wer sucht am Ende wirklich den Film aus?" to "Kto ostatecznie wybiera film?",
    "Wer vergisst eher einen Jahrestag?" to "Kto częściej zapomina o rocznicy?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Kto byłby bardziej skłonny zapomnieć swojego imienia następnego ranka?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Kto z większym prawdopodobieństwem następnego dnia znajdzie film, o którym już nie wiedział?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Kto wolałby spędzić noc na sofie nieznajomego?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Kto byłby bardziej skłonny zasnąć na imprezie i obudzić się z Sharpie na twarzy?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Kto byłby bardziej skłonny do poślizgu na parkiecie, gdyby wyglądało to na fajny ruch?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Kto z większym prawdopodobieństwem przejmie kontrolę nad playlistą Spotify podczas domowej imprezy?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Kto byłby bardziej skłonny zamówić pizzę dla wszystkich na imprezie i sam ją zjeść?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Kto częściej zasypia na imprezie?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Kto byłby bardziej skłonny nagle zacząć sprzątać na imprezie?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Kto byłby bardziej skłonny twierdzić, że jest całkowicie trzeźwy, gdy jest odwrotnie?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Kto jest bardziej skłonny do poddania się jako pierwszy w kłótni?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Kto byłby bardziej skłonny do oszukiwania w grze alkoholowej?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Kto byłby bardziej skłonny włamać się do bufetu i potajemnie zabrać jedzenie do domu?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Kto byłby bardziej skłonny opublikować w swojej relacji najbardziej żenujące zdjęcie z wieczoru?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Kto byłby bardziej skłonny zirytować DJ-a, prosząc o jego ulubioną piosenkę?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Kto byłby bardziej skłonny zaśpiewać tekst piosenki nie w tonacji, ale z przekonaniem?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Kto chętniej zamówiłby najdroższy napój w karcie i żałował?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Kto byłby bardziej skłonny zaprosić do siebie sąsiadów, gdyby skarżyli się na hałas?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Kto byłby bardziej skłonny do zbyt poważnego traktowania gier towarzyskich (takich jak piwny ping-pong)?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Kto byłby bardziej skłonny zaprzyjaźnić się z bramkarzami, aby uzyskać dostęp VIP?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Kto byłby bardziej skłonny do rozpoczęcia zaimprowizowanej bitwy karaoke?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Kto byłby bardziej skłonny otworzyć butelkę bez użycia otwieracza do butelek?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Kto byłby bardziej skłonny do wygłoszenia przemówienia, nawet gdyby nikt o to nie prosił?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Kto byłby bardziej skłonny spędzić godzinę w łazience, robiąc sobie selfie?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Kto byłby bardziej skłonny do zorganizowania żenującego występu tanecznego i uczczenia go?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Kto najchętniej zadzwoni do byłego partnera po zakończeniu imprezy?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Kto byłby bardziej skłonny niechcący urazić obcego gościa?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Kto byłby bardziej skłonny do potajemnego opuszczenia imprezy bez pożegnania?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Kto woli bawić się z pupilem gospodarzy niż rozmawiać z gośćmi?",
    "Wer würde eher spontan eine Reise buchen?" to "Kto byłby bardziej skłonny zarezerwować wycieczkę spontanicznie?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Kto byłby bardziej skłonny do wielogodzinnych głębokich rozmów w kuchni?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Kto jest bardziej narażony na przypadkowe wypicie cudzego napoju?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Kto byłby bardziej narażony na przypadkowe przewrócenie drogiego wazonu lub czegoś delikatnego?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Kto byłby bardziej skłonny do samodzielnego przygotowania skomplikowanego koktajlu i poniósłby porażkę?",
    "Wer würde eher zu spät kommen?" to "Kto częściej się spóźnia?",
    "Wer würde eher?" to "Kto by wolał?",
    "Wer übernimmt die tägliche Versorgung?" to "Kto zajmuje się codzienną pielęgnacją?",
    "Werde so akzeptiert, wie du bist" to "Bądź akceptowany takim, jakim jesteś",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Czy będziemy mieli wystarczająco dużo czasu dla dziecka/dzieci? ⏳",
    "Whirlpool" to "jacuzzi",
    "White Chocolate" to "Czekolada biała",
    "Widgets" to "Widżety",
    "Wie fühlst du dich am meisten geliebt?" to "Jak czujesz się najbardziej kochany?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Jak radzić sobie z różnymi dochodami?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Jaki jest najlepszy sposób, aby Twój partner zainicjował z Tobą seks?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "W jaki sposób Twój partner może być dla Ciebie jeszcze lepszym partnerem?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Jak długo po oświadczynach chcesz świętować z innymi?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Jak długo chcemy tam przynajmniej zostać?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Jak łatwo jest Ci rozmawiać o życzeniach?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Jak chcesz, żeby wyglądała nasza przyszłość?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Jak wygląda Twoja idealna niedziela w domu?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Co sądzisz o sprośnych rozmowach podczas seksu?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Na jaki kredyt realnie możemy sobie pozwolić?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Ile czasu chcemy spędzić osobno?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Ile łącznie chcemy wydać?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Jak znajdziemy czas na nasz związek, gdy już urodzi się dziecko?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Jak ważne jest dla Ciebie uchwycenie chwili?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Jak ważne jest dla Ciebie, aby aplikacja odzwierciedlała Twoje hobby lub zainteresowania?",
    "Wie würdest du sie/ihn nennen?" to "Jak byś go/ją nazwał?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Jaki jest Twój ulubiony sposób okazywania uczuć poza seksem?",
    "Wildblumen" to "Polne kwiaty",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Chcesz dziewczynę czy chłopca? 👶",
    "Wintergarten" to "Ogród zimowy",
    "Winterhochzeit" to "Zimowy ślub",
    "Wir" to "My",
    "Wir bestellen einfach beides" to "Po prostu zamawiamy jedno i drugie",
    "Wir brauchen ewig" to "Zajmuje nam to wieki",
    "Wir einigen uns nie" to "Nigdy nie możemy się zgodzić",
    "Wir entscheiden es gemeinsam" to "Decydujemy wspólnie",
    "Wir treffen uns in der Mitte" to "Spotkamy się w środku",
    "Wir wechseln uns ab" to "Na zmianę",
    "Wird stressig" to "Robi się stresująco",
    "Wobei lachst du am meisten?" to "Co Cię najbardziej śmieszy?",
    "Wofür sparen wir gemeinsam?" to "Na co wspólnie oszczędzamy?",
    "Wohnzimmer" to "Salon",
    "Woran erinnerst du dich am lebhaftesten?" to "Co najbardziej pamiętasz?",
    "Worauf freust du dich bei uns am meisten?" to "Czego najbardziej nie możesz się doczekać u nas?",
    "Worte/Komplimente" to "Słowa/komplementy",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Czego najbardziej się boisz w naszym związku?",
    "Wünsche? z.B. günstig, draußen" to "Życzenia? np. tanio, na zewnątrz",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Czy wolisz oświadczyć się na wakacjach (z podróżami)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube Music",
    "Zeichne für mich" to "Narysuj dla mnie",
    "Zeichne mich als Tier — welches wäre ich?" to "Narysuj mnie jako zwierzę – kim bym był?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Narysuj nasze wzajemne uczucia jako symbol.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Narysuj w jednej linii nasz wymarzony dom. Co jest najbardziej uderzającego?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Narysuj naszą pierwszą randkę – co koniecznie musi znaleźć się na obrazku?",
    "Zeichnen" to "Rysować",
    "Zeit füreinander" to "Czasu dla siebie nawzajem",
    "Zeit, wenn das Baby schläft" to "Czas, kiedy dziecko śpi",
    "Zelten gehen" to "Jedź na kemping",
    "Zitrone" to "cytrynowy",
    "Zu Hause, gemütlich und privat" to "W domu, przytulnie i prywatnie",
    "Zu einem Picknick gehen" to "Idziemy na piknik",
    "Zu einem ausgefallenen Abendessen gehen" to "Idę na wykwintną kolację",
    "Zu zweit reisen" to "Podróżuj jako para",
    "Zuhause & Alltag" to "Dom i życie codzienne",
    "Zuhören" to "Słuchać",
    "Zurück" to "Z powrotem",
    "Zurücksetzen" to "Nastawić",
    "Zusammen seit" to "Razem od",
    "Zusammen seit (TT.MM.JJJJ)" to "Razem od (DD.MM.RRRR)",
    "Zusammenziehen" to "Umawiające się",
    "Zustimmen oder Ablehnen" to "Zgódź się lub odrzuć",
    "Zwei Kreise, die sich überschneiden" to "Dwa okręgi, które się pokrywają",
    "Zwei Stühle davor" to "Przed nim dwa krzesła",
    "Zärtlich sein" to "Bądź delikatny",
    "aufwaermen" to "rozgrzać się",
    "beliebiges Paar" to "dowolna para",
    "custom_gourmet_eissorten" to "niestandardowe_gourmet_smaki lodów",
    "dasoderdas" to "to lub tamto",
    "deshalb stecken die Bilder als Base64 direkt im Kotlin-Code." to "Dlatego obrazy znajdują się w Base64 bezpośrednio w kodzie Kotlina.",
    "disney" to "Disneya",
    "eigen" to "własny",
    "entertainment" to "rozrywka",
    "essen" to "Jedzenie",
    "familie" to "rodzina",
    "games" to "zawody sportowe",
    "harrypotter" to "Harry'ego Pottera",
    "hochzeit" to "ślub",
    "iPhone" to "iPhone",
    "ichhabenochnie" to "Nigdy tego nie robiłem",
    "kinder" to "dzieci",
    "leer" to "pusty",
    "oder" to "Lub",
    "parks" to "parki",
    "party" to "impreza",
    "reden" to "rozmawiać",
    "reisen" to "podróż",
    "tot" to "martwy",
    "universal" to "uniwersalny",
    "unterhaltung" to "rozrywka",
    "verschiebe Zeilen mit den Pfeilen, wenn ein Paar nicht passt." to "przesuwaj rzędy za pomocą strzałek, jeśli para nie pasuje.",
    "wer" to "Kto",
    "werwuerde" to "kto by to zrobił",
    "zuhause" to "u siebie w domu",
    "{ANZAHL} Bilder geladen — Namen prüfen, dann erstellen." to "{ANZAHL} załadowanych zdjęć — sprawdź nazwy, a następnie utwórz pakiet.",
    "{ANZAHL} Bilder geladen." to "{ANZAHL} załadowanych zdjęć.",
    "{ANZAHL} Einträge" to "{ANZAHL} wpisów",
    "{ANZAHL} Fragen" to "{ANZAHL} pytań",
    "{ANZAHL} Paare" to "{ANZAHL} par",
    "{ANZAHL} Paare aus {ANZAHL} Bildern" to "{ANZAHL} par z {ANZAHL} zdjęć",
    "{ANZAHL} Paare · {ANZAHL} Fragen" to "{ANZAHL} par · {ANZAHL} pytań",
    "{ANZAHL} Schritt(e)" to "{ANZAHL} krok(ów)",
    "{EMOJI} {INHALT}" to "{EMOJI} {INHALT}",
    "{EMOJI} „{WIDGET}“ an {PARTNER} gesendet" to "{EMOJI} „{WIDGET}” wysłano do {PARTNER}",
    "{NUMMER}. {INHALT}" to "{NUMMER}. {INHALT}",
    "{partner}" to "{partner}",
    "{user}" to "{user}",
    "Öfter als ich zugebe" to "Częściej niż przyznaję",
    "Über 100€/Monat" to "Ponad 100€/miesiąc",
    "Über 2000 im Monat" to "Ponad 2000 miesięcznie",
    "Über 3 MB — nimm eine kleinere Bildgröße oder exportiere die Pakete einzeln." to "Ponad 3 MB — użyj mniejszego rozmiaru obrazu lub wyeksportuj pakiety pojedynczo.",
    "Über mich selbst" to "O sobie",
    "Übernehmen" to "Przejąć",
    "Überraschend" to "Zaskakujący",
    "Überraschung" to "Niespodzianka",
    "Überraschungspaket" to "Pakiet niespodzianka",
    "Überspringen" to "Pominąć",
    "Übertrieben und großartig" to "Ponad wszystko i niesamowicie",
    "• A: {OPTION} (Bild: {BILD})" to "• A: {OPTION} (Zdjęcie: {BILD})",
    "• B: {OPTION} (Bild: {BILD})" to "• B: {OPTION} (Zdjęcie: {BILD})",
    "☀️" to "☀️",
    "⚖️ Das oder Das" to "⚖️ To czy tamto",
    "⚡ Test" to "⚡ Testuj",
    "✅ Beantwortet" to "✅Odpowiedział",
    "✎ Tippe, um zu antworten" to "✎ Kliknij, aby odpowiedzieć",
    "✕ Schließen" to "✕ Zamknij",
    "✨ GFK-Brücke" to "✨ Most TWS",
    "❤️" to "❤️",
    "🎉 '{TITEL}' angelegt · {ANZAHL} Paare spielbereit" to "🎉 Utworzono „{TITEL}” · {ANZAHL} par gotowych do gry",
    "🎉 JSON inkl. Bildern & Ketten kopiert!" to "🎉 Skopiowano JSON, w tym obrazy i łańcuchy!",
    "🎉 {ANZAHL} Pakete/Ketten & Bilder erfolgreich eingespielt!" to "🎉 Pomyślnie zaimportowano {ANZAHL} pakietów/łańcuchów i zdjęć!",
    "🎨 Farben & Kategorien verwalten" to "🎨 Zarządzaj kolorami i kategoriami",
    "🏷️ Kategorien & Farben" to "🏷️ Kategorie i kolory",
    "📂 Ordner" to "📂 Folder",
    "📝 Spiele" to "📝 Gry",
    "📤 Export" to "📤 Eksport",
    "🔗 Ketten" to "🔗 Łańcuchy",
    "🔗 Ketten-Bauer" to "🔗 Pionek Łańcuchowy",
    "🔗 Ketten-Spiele" to "🔗 Gry łańcuchowe",
    "🔥 Tägliche Aktivität" to "🔥 Codzienna aktywność",
    "🖼️ Bilder" to "🖼️ Zdjęcia",
    "🗣️ Diskussion" to "🗣️ Dyskusja",
    "🛠️ Entwickler-Modus" to "🛠️ Tryb programisty",
    "🟠 Du bist dran" to "🟠 Twoja kolej",
    "🧠 Quiz" to "🧠 Quiz",
)

private fun exactPolish(text: String): String =
    TranslationCatalog.exact(text, AppLanguage.POLISH) ?: text

internal fun localizePolishDynamicContent(text: String): String? {
    Regex("^([\\p{So}\\p{Sk}\\uFE0F\\u200D]+\\s+)(.+)$").matchEntire(text)?.let {
        TranslationCatalog.exact(it.groupValues[2], AppLanguage.POLISH)?.let { translated -> return it.groupValues[1] + translated }
    }
    Regex("^(\\d+[.)]\\s+)(.+)$").matchEntire(text)?.let {
        TranslationCatalog.exact(it.groupValues[2], AppLanguage.POLISH)?.let { translated -> return it.groupValues[1] + translated }
    }
    Regex("^(\\d+) Bilder geladen — Namen prüfen, dann erstellen\\.$").matchEntire(text)?.let {
        return "${it.groupValues[1]} załadowanych zdjęć — sprawdź nazwy, a następnie utwórz pakiet."
    }
    Regex("^(\\d+) Bilder geladen\\.$").matchEntire(text)?.let {
        return "${it.groupValues[1]} załadowanych zdjęć."
    }
    Regex("^(\\d+) Paare aus (\\d+) Bildern$").matchEntire(text)?.let {
        return "${it.groupValues[1]} par z ${it.groupValues[2]} zdjęć"
    }
    Regex("^Bild (\\d+) von (\\d+)…$").matchEntire(text)?.let {
        return "Zdjęcie ${it.groupValues[1]} z ${it.groupValues[2]}…"
    }
    Regex("^Speichere Bild (\\d+) von (\\d+)…$").matchEntire(text)?.let {
        return "Zapisywanie zdjęcia ${it.groupValues[1]} z ${it.groupValues[2]}…"
    }
    Regex("^Paar (\\d+)$").matchEntire(text)?.let { return "Para ${it.groupValues[1]}" }
    Regex("^Frage (\\d+)$").matchEntire(text)?.let { return "Pytanie ${it.groupValues[1]}" }
    Regex("^Schritt (\\d+)$").matchEntire(text)?.let { return "Krok ${it.groupValues[1]}" }
    Regex("^(\\d+) Paare$").matchEntire(text)?.let { return "${it.groupValues[1]} par" }
    Regex("^(\\d+) Fragen$").matchEntire(text)?.let { return "${it.groupValues[1]} pytań" }
    Regex("^(\\d+) Schritt\\(e\\)$").matchEntire(text)?.let { return "${it.groupValues[1]} krok(ów)" }
    Regex("^(\\d+) Paare · (\\d+) Fragen$").matchEntire(text)?.let {
        return "${it.groupValues[1]} par · ${it.groupValues[2]} pytań"
    }
    Regex("^(\\d+) Einträge$").matchEntire(text)?.let { return "${it.groupValues[1]} wpisów" }
    Regex("^Fertig: (\\d+) Pakete · (\\d+) Bilder · (.+)$").matchEntire(text)?.let {
        return "Gotowe: ${it.groupValues[1]} pakietów · ${it.groupValues[2]} zdjęć · ${it.groupValues[3]}"
    }
    Regex("^🎉 (\\d+) Pakete/Ketten & Bilder erfolgreich eingespielt!$").matchEntire(text)?.let {
        return "🎉 Pomyślnie zaimportowano ${it.groupValues[1]} pakietów/łańcuchów i zdjęć!"
    }
    Regex("^🎉 '(.+)' angelegt · (\\d+) Paare spielbereit$").matchEntire(text)?.let {
        return "🎉 Utworzono „${exactPolish(it.groupValues[1])}” · ${it.groupValues[2]} par gotowych do gry"
    }
    Regex("^• ([AB]): (.+) \\(Bild: (.+)\\)$").matchEntire(text)?.let {
        return "• ${it.groupValues[1]}: ${exactPolish(it.groupValues[2])} (Zdjęcie: ${it.groupValues[3]})"
    }
    Regex("^([AB]): (.+)$").matchEntire(text)?.let {
        return "${it.groupValues[1]}: ${exactPolish(it.groupValues[2])}"
    }
    Regex("^'(.+)' gelöscht\\.$").matchEntire(text)?.let {
        return "Usunięto „${exactPolish(it.groupValues[1])}”."
    }
    Regex("^'(.+)' gespeichert\\.$").matchEntire(text)?.let {
        return "Zapisano „${exactPolish(it.groupValues[1])}”."
    }
    Regex("^Kategorie '(.+)' gespeichert\\.$").matchEntire(text)?.let {
        return "Zapisano kategorię „${exactPolish(it.groupValues[1])}”."
    }
    Regex("^Kette '(.+)' gespeichert\\.$").matchEntire(text)?.let {
        return "Zapisano łańcuch „${exactPolish(it.groupValues[1])}”."
    }
    Regex("^Kette '(.+)' gelöscht\\.$").matchEntire(text)?.let {
        return "Usunięto łańcuch „${exactPolish(it.groupValues[1])}”."
    }
    Regex("^Bild für '(.+)' gesetzt\\.$").matchEntire(text)?.let {
        return "Ustawiono zdjęcie dla „${exactPolish(it.groupValues[1])}”."
    }
    Regex("^Eigenes Bild für '(.+)' entfernt\\.$").matchEntire(text)?.let {
        return "Usunięto własne zdjęcie dla „${exactPolish(it.groupValues[1])}”."
    }
    Regex("^(.+) „(.+)\" an (.+) gesendet$").matchEntire(text)?.let {
        return "${it.groupValues[1]} „${exactPolish(it.groupValues[2])}” wysłano do ${it.groupValues[3]}"
    }
    Regex("^6 Monate im (.+)$").matchEntire(text)?.let {
        return "6 miesięcy w ${exactPolish(it.groupValues[1])}"
    }
    Regex("^1 Jahr lang in (.+)$").matchEntire(text)?.let {
        return "1 rok w ${exactPolish(it.groupValues[1])}"
    }
    Regex("^Weil du (.+) gewählt hast …$").matchEntire(text)?.let {
        return "Ponieważ wybrałeś ${exactPolish(it.groupValues[1])}…"
    }
    Regex("^Verbinde dich mit (.+), um die Antwort zu sehen$").matchEntire(text)?.let {
        return "Połącz się z ${it.groupValues[1]}, aby zobaczyć odpowiedź"
    }
    Regex("^Verbinde dich mit (.+)$").matchEntire(text)?.let {
        return "Połącz się z ${it.groupValues[1]}"
    }
    Regex("^Deine Antworten sind gespeichert\\. Sobald (.+) das Paket beendet, werden beide Antworten gemeinsam sichtbar\\.$").matchEntire(text)?.let {
        return "Twoje odpowiedzi zostały zapisane. Gdy ${it.groupValues[1]} ukończy pakiet, obie odpowiedzi będą widoczne razem."
    }
    Regex("^Fehler bei der Umformulierung: (.+)$").matchEntire(text)?.let {
        return "Błąd podczas przeredagowania: ${it.groupValues[1]}"
    }
    Regex("^Fehler bei der Analyse: (.+)$").matchEntire(text)?.let {
        return "Błąd analizy: ${it.groupValues[1]}"
    }
    Regex("^Fehler bei der Ideengenerierung: (.+)$").matchEntire(text)?.let {
        return "Błąd generowania pomysłów: ${it.groupValues[1]}"
    }
    if (text.contains(" · ")) {
        val translated = text.split(" · ").joinToString(" · ") {
            TranslationCatalog.translate(it, AppLanguage.POLISH) ?: it
        }
        if (translated != text) return translated
    }
    return null
}
