package com.example.ui

/** Complete Brazilian Portuguese Harmony catalog. */
internal val EXACT_PORTUGUESE_BRAZIL_CONTENT: Map<String, String> = mapOf(
    "Tiere" to "Animais",
    "Wer würde eher?" to "Quem preferiria?",
    "Zeichnen" to "Desenho",
    "Das oder das?" to "Isto ou aquilo?",
    "Das oder das" to "Isso ou aquilo",
    "Zustimmen oder Ablehnen" to "Concordar ou rejeitar",
    "Ich habe noch nie" to "Eu nunca",
    "Was magst du lieber?" to "O que você mais gosta?",
    "Antwort mit einem Foto" to "Responder com uma foto",
    "Tiefe Gespräche" to "Conversas profundas",
    "Reden vor ..." to "Discursos diante de...",
    "Aufwärmen" to "Aquecimento",
    "Beziehung" to "relacionamento",
    "Sex & Liebe" to "Sexo e amor",
    "Moralische Werte" to "Valores morais",
    "Geld & Finanzen" to "Dinheiro e finanças",
    "Einander kennenlernen" to "Conheça um ao outro",
    "Reisen" to "Viajar",
    "Familie" to "família",
    "Hobbys" to "Passatempos",
    "unterhaltung" to "entretenimento",
    "dasoderdas" to "isto ou aquilo",
    "hochzeit" to "casamento",
    "kinder" to "crianças",
    "reden" to "falar",
    "reisen" to "viajar",
    "familie" to "família",
    "Zuhause & Alltag" to "Casa e vida cotidiana",
    "Was gefällt dir an deinem Zuhause am besten?" to "O que você mais gosta na sua casa?",
    "Die Gemütlichkeit und Ruhe" to "O aconchego e a paz",
    "Dass alles meinen Stil hat" to "Que tudo tem meu estilo",
    "Die Menschen, die darin wohnen" to "As pessoas que moram lá",
    "Der Blick nach draußen" to "A vista lá fora",
    "Welcher Raum sagt am meisten über dich aus?" to "Qual quarto diz mais sobre você?",
    "Küche" to "Cozinha",
    "Schlafzimmer" to "quarto",
    "Wohnzimmer" to "Sala de estar",
    "Mein Arbeitsplatz" to "Meu local de trabalho",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "O que você mudaria imediatamente se o dinheiro não fosse um problema?",
    "Größere Küche" to "Cozinha maior",
    "Ein Balkon oder Garten" to "Uma varanda ou jardim",
    "Bessere Lage" to "Melhor localização",
    "Nichts — es passt so" to "Nada - cabe assim",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Como é o seu domingo perfeito em casa?",
    "Ausschlafen und nichts tun" to "Durma e não faça nada",
    "Kochen und Freunde einladen" to "Cozinhe e convide amigos",
    "Serienmarathon auf dem Sofa" to "Maratona de séries no sofá",
    "Aufräumen und Projekte angehen" to "Limpar e resolver projetos",
    "Der perfekte Heiratsantrag" to "A proposta de casamento perfeita",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Que ambiente você gostaria para uma proposta?",
    "Zu Hause, gemütlich und privat" to "Em casa, aconchegante e privado",
    "Draußen mit der Natur als Kulisse" to "Lá fora com a natureza como pano de fundo",
    "Schickes Restaurant oder Hotel" to "Restaurante ou hotel chique",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Você prefere uma proposta pública ou privada?",
    "Nur wir beide" to "Só nós dois",
    "Mit Familie und engen Freunden" to "Com a família e amigos próximos",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "Em um local público com muitos espectadores",
    "Soll der Antrag eine Überraschung sein?" to "A proposta deveria ser uma surpresa?",
    "Ja, komplett überraschend" to "Sim, completamente surpreendente",
    "Lieber vorher grob absprechen" to "É melhor discutir com antecedência",
    "Wir entscheiden es gemeinsam" to "Nós decidimos juntos",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Quão importante é para você que o momento seja capturado?",
    "Sehr wichtig — Fotos und Video" to "Muito importante – fotos e vídeo",
    "Ein paar Handyfotos reichen" to "Algumas fotos do celular são suficientes",
    "Gar nicht, der Moment gehört uns" to "De jeito nenhum, o momento é nosso",
    "Vorlieben für den Antrag" to "Preferências para o aplicativo",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Você prefere uma proposta extravagante ou algo sutil?",
    "Übertrieben und großartig" to "Exagerado e incrível",
    "Mittelweg mit besonderen Details" to "Meio termo com detalhes especiais",
    "Einfach und intim" to "Simples e íntimo",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "O que você acha dos adereços (por exemplo, placas, balões, etc.)?",
    "Liebe sie, macht mehr Spaß" to "Ame-os, mais divertido",
    "Vielleicht ein oder zwei" to "Talvez um ou dois",
    "Nein, zu ablenkend" to "Não, muito perturbador",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Quer que o momento seja compartilhado nas redes sociais instantaneamente?",
    "Ja, sofort teilen" to "Sim, compartilhe imediatamente",
    "Nein, erstmal privat halten" to "Não, mantenha isso privado por enquanto",
    "Erst nur enge Freunde/Familie" to "Apenas amigos próximos/familiares no início",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Quão importante é para você que o aplicativo reflita seus hobbies ou interesses?",
    "Sehr wichtig, es sollte persönlich sein" to "Muito importante, deve ser pessoal",
    "Etwas, eine kleine Note wäre schön" to "Algo, um pequeno toque seria bom",
    "Nicht nötig, lieber klassisch bleiben" to "Não é necessário, é melhor ficar clássico",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Você prefere propor férias (envolvendo viagens)?",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Sim, em uma cidade ou atração emocionante",
    "Vielleicht, wenn es machbar ist" to "Talvez, se for viável",
    "Nein, lieber vor Ort" to "Não, melhor no local",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Quanto tempo depois da proposta você deseja comemorar com outras pessoas?",
    "Am selben Tag mit Freunden/Familie" to "Mesmo dia com amigos/família",
    "Etwa eine Woche später, erst mal nur wir" to "Cerca de uma semana depois, apenas nós no início",
    "Keine Party nötig, privat halten" to "Nenhuma festa é necessária, mantenha-a privada",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Você gostaria de uma carta escrita como parte da inscrição?",
    "Ja, etwas zum Lesen und Aufbewahren" to "Sim, algo para ler e guardar",
    "Vielleicht, aber mündlich reicht" to "Talvez, mas verbalmente é suficiente",
    "Nein, einfach halten" to "Não, apenas segure",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "A candidatura deve conter elementos culturais ou tradicionais?",
    "Ja, Traditionen einbinden" to "Sim, incorpore tradições",
    "Ein paar kulturelle Anklänge sind okay" to "Algumas referências culturais estão bem",
    "Nein, modern halten" to "Não, mantenha-o moderno",
    "Was ist das Wichtigste beim Antrag?" to "Qual é a coisa mais importante na hora de se inscrever?",
    "Die Umgebung und Atmosphäre" to "O ambiente e a atmosfera",
    "Die Worte und Emotionen" to "As palavras e emoções",
    "Der Ring und die Geste" to "O anel e o gesto",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Você gostaria que animais de estimação fossem incluídos no aplicativo?",
    "Ja, sie gehören zur Familie!" to "Sim, eles são uma família!",
    "Vielleicht, wenn es passt" to "Talvez, se couber",
    "Nein, nur wir" to "Não, só nós",
    "Diskutiere vor dem Kinderkriegen" to "Discuta antes de ter filhos",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Somos capazes de cobrir todos os custos de um filho/vários filhos? 💰",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Talvez precisemos fazer economias",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Teremos tempo suficiente para a(s) criança(s)? ⏳",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Sim, garantiremos que o tempo em família seja uma prioridade.",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Como encontraremos tempo para nosso relacionamento quando o bebê nascer?",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Agende datas ou horários regulares juntos",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Como você quer que seja o nosso futuro?",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Viajem pelo mundo juntos, explorem novas culturas e culinárias",
    "Wie würdest du sie/ihn nennen?" to "Como você o chamaria?",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Você quer uma menina ou um menino? 👶",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "O que será do nosso filho quando ele crescer?",
    "Vor der Anschaffung eines Haustiers besprechen" to "Discuta antes de comprar um animal de estimação",
    "Wer übernimmt die tägliche Versorgung?" to "Quem cuida dos cuidados diários?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "O que acontece com o animal quando viajamos?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Que orçamento planejamos para alimentação e veterinário?",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Um animal cabe em nossa vida cotidiana?",
    "Vor der gemeinsamen Reise besprechen" to "Discuta antes de viajar juntos",
    "Wie viel wollen wir insgesamt ausgeben?" to "Quanto queremos gastar no total?",
    "Lieber durchgeplant oder spontan?" to "Você prefere que seja planejado ou espontâneo?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Quanto tempo queremos passar separados?",
    "Was ist für jeden von uns das absolute Highlight?" to "Qual é o destaque absoluto para cada um de nós?",
    "Vor dem Kauf eines Hauses besprechen" to "Discuta antes de comprar uma casa",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Quanto crédito podemos realisticamente pagar?",
    "Stadt oder Land — was ist uns wichtiger?" to "Cidade ou país – o que é mais importante para nós?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Quanto tempo queremos ficar lá pelo menos?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Quem cuida da reforma e manutenção?",
    "Reiseziele" to "Destinos",
    "Paris, Frankreich" to "Paris, França",
    "Rom, Italien" to "Roma, Itália",
    "Bali, Indonesien" to "Bali, Indonésia",
    "Santorini, Griechenland" to "Santorini, Grécia",
    "London, England" to "Londres, Inglaterra",
    "New York, USA" to "Nova York, EUA",
    "Malediven" to "Maldivas",
    "Seychellen" to "Seicheles",
    "Tokyo, Japan" to "Tóquio, Japão",
    "Dubai, VAE" to "Dubai, Emirados Árabes Unidos",
    "Venedig, Italien" to "Veneza, Itália",
    "Amsterdam, Niederlande" to "Amsterdã, Holanda",
    "Lappland, Finnland" to "Lapônia, Finlândia",
    "Island" to "Islândia",
    "Unser Traumhaus" to "Nossa casa dos sonhos",
    "Altbau mit Charme" to "Prédio antigo com charme",
    "Neubau mit Smart Home" to "Novo edifício com casa inteligente",
    "Offene Wohnküche" to "Cozinha/sala aberta",
    "Separate Küche" to "Cozinha separada",
    "Prasselnder Kamin" to "Lareira crepitante",
    "Fußbodenheizung" to "Aquecimento por piso radiante",
    "Großer Garten" to "Grande jardim",
    "Sonnige Dachterrasse" to "Terraço ensolarado",
    "Stadtvilla" to "Vila da cidade",
    "Landhaus" to "casa de campo",
    "Glasfassade" to "Fachada de vidro",
    "Natursteinfassade" to "Fachada em pedra natural",
    "Penthouse mit Ausblick" to "Cobertura com vista",
    "Haus am See" to "Casa à beira do lago",
    "Minimalistisches Interieur" to "Interior minimalista",
    "Landhausstil" to "Estilo country",
    "Bibliothek" to "Biblioteca",
    "Heimkino" to "Cinema em casa",
    "Innenpool" to "Piscina interior",
    "Wellnessbad" to "Banho de bem-estar",
    "Große Fensterfront" to "Grande janela frontal",
    "Privater Innenhof" to "Pátio privado",
    "Tiny House" to "Casa minúscula",
    "Mehrgenerationenhaus" to "Casa multigeracional",
    "Traumhaus Außenbereich" to "Área externa da casa dos sonhos",
    "Großer Außenpool" to "Grande piscina exterior",
    "Outdoor-Whirlpool" to "Banheira de hidromassagem ao ar livre",
    "Moderne Grillstation" to "Churrasqueira moderna",
    "Gemütliche Feuerstelle" to "Fogueira aconchegante",
    "Eigenes Gemüsebeet" to "Horta própria",
    "Bunte Blumenwiese" to "Prado de flores coloridas",
    "Entspannte Hängematte" to "Rede relaxada",
    "Stilvolles Outdoor-Sofa" to "Sofá elegante ao ar livre",
    "Infinity-Pool" to "Piscina infinita",
    "Naturteich" to "Lagoa natural",
    "Outdoor-Küche" to "Cozinha ao ar livre",
    "Pizzaofen" to "Forno de pizza",
    "Pergola mit Lounge" to "Pergolado com lounge",
    "Wintergarten" to "Jardim de inverno",
    "Kräuterbeet" to "Cama de ervas",
    "Obstgarten" to "pomar",
    "Dachgarten mit Lounge" to "Jardim na cobertura com lounge",
    "Mediterraner Innenhof" to "Pátio mediterrâneo",
    "Feuerstelle" to "Fogueira",
    "Außenkamin" to "Lareira externa",
    "Spielbereich für Kinder" to "Área de recreação para crianças",
    "Sportplatz" to "Campo esportivo",
    "Gewächshaus" to "estufa",
    "Saunahaus" to "Casa de sauna",
    "Aktivitäten" to "Atividades",
    "Wandern" to "Caminhadas",
    "Strandtag" to "Dia de praia",
    "Konzert" to "Concerto",
    "Kino" to "Cinema",
    "Kochkurs" to "Aula de culinária",
    "Restaurant" to "Restaurante",
    "Museum" to "Museu",
    "Freizeitpark" to "Parque de diversões",
    "Essensvorlieben" to "Preferências alimentares",
    "Pizza" to "Pizza",
    "Pasta" to "Macarrão",
    "Sushi" to "Sushi",
    "Burger" to "Hambúrgueres",
    "Süß" to "Doce",
    "Herzhaft" to "Farto",
    "Selbst kochen" to "Cozinhe você mesmo",
    "Bestellen" to "Pedido",
    "Verlobungsringe" to "Anéis de noivado",
    "Klassisch Solitär" to "Solitário clássico",
    "Vintage verspielt" to "Vintage brincalhão",
    "Gelbgold" to "Ouro amarelo",
    "Weißgold" to "Ouro branco",
    "Großer Stein" to "Pedra grande",
    "Filigran & schlicht" to "Filigrana e simples",
    "Diamant" to "Diamante",
    "Farbedelstein" to "Pedra preciosa colorida",
    "Platin" to "Platina",
    "Roségold" to "Ouro rosa",
    "Drei-Stein-Ring" to "Anel de três pedras",
    "Moderner Solitär" to "Paciência moderna",
    "Ovaler Diamant" to "Diamante oval",
    "Runder Diamant" to "Diamante redondo",
    "Schmal & zart" to "Fino e delicado",
    "Markant & breit" to "Impressionante e amplo",
    "Moissanit" to "Moissanita",
    "Saphir" to "Safira",
    "Vintage Art déco" to "Art Déco vintage",
    "Modern geometrisch" to "Geométrico moderno",
    "Gravur innen" to "Gravura dentro",
    "Diamanten im Band" to "Diamantes na banda",
    "Ohne Stein" to "Sem pedra",
    "Statement-Ring" to "Anel de declaração",
    "Hochzeitssträuße" to "Buquês de casamento",
    "Weiße Rosen" to "Rosas brancas",
    "Pfingstrosen" to "Peônias",
    "Wildblumen" to "Flores silvestres",
    "Klassisch gebunden" to "Encadernação clássica",
    "Groß & üppig" to "Grande e exuberante",
    "Klein & zart" to "Pequeno e delicado",
    "Pastell" to "Pastel",
    "Kräftige Farben" to "Cores fortes",
    "Traumhochzeit" to "Casamento dos sonhos",
    "Große Feier" to "Grande celebração",
    "Kleine Runde" to "Rodada pequena",
    "Am Strand" to "Na praia",
    "In den Bergen" to "Nas montanhas",
    "Kirchlich" to "Eclesiástico",
    "Standesamt & Party" to "Cartório e festa",
    "Sommerhochzeit" to "Casamento de verão",
    "Winterhochzeit" to "Casamento de inverno",
    "Fragen für jede Gelegenheit" to "Perguntas para todas as ocasiões",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "O que você prefere: acordar cedo ou ficar acordado até tarde?",
    "Früh aufstehen" to "Acorde cedo",
    "Lange wach bleiben" to "Fique acordado até tarde",
    "Kommt auf den Tag an" to "Depende do dia",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Você prefere uma noite tranquila a dois ou com pessoas?",
    "Ruhig zu zweit" to "Tranquilo para dois",
    "Unter Leuten" to "Entre as pessoas",
    "Gemischt" to "Misto",
    "Was entspannt dich mehr?" to "O que te relaxa mais?",
    "Musik" to "Música",
    "Spazieren" to "Caminhar",
    "Serie schauen" to "Assistir série",
    "Gar nichts tun" to "Não faça nada",
    "Wobei lachst du am meisten?" to "O que mais te faz rir?",
    "Bei Insider-Witzen" to "Com piadas internas",
    "Bei Memes" to "Em memes",
    "Wenn ich müde bin" to "Quando estou cansado",
    "Über mich selbst" to "Sobre mim",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Instantâneos da nossa história de amor",
    "Welcher Moment war für dich der Anfang von „uns\"?" to "Que momento foi o início do “nós” para você?",
    "Unser erstes Gespräch" to "Nossa primeira conversa",
    "Das erste Treffen" to "A primeira reunião",
    "Der erste Kuss" to "O primeiro beijo",
    "Als es einfach klar war" to "Quando estava claro",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Qual foto juntos é a sua favorita?",
    "Das erste Selfie" to "A primeira selfie",
    "Ein Urlaubsfoto" to "Uma foto de férias",
    "Ein zufälliger Schnappschuss" to "Um instantâneo aleatório",
    "Eins, das nur wir kennen" to "Um que só nós conhecemos",
    "Woran erinnerst du dich am lebhaftesten?" to "Do que você se lembra mais vividamente?",
    "An einen Geruch" to "De um cheiro",
    "An einen Song" to "De uma canção",
    "An etwas, das ich gesagt habe" to "Sobre algo que eu disse",
    "An das Gefühl" to "Do sentimento",
    "Aufwärmen: Einander kennenlernen" to "Aquecimento: nos conhecendo",
    "Was war dein schönster Moment mit mir bisher?" to "Qual foi o seu melhor momento comigo até agora?",
    "Unser erstes Treffen" to "Nosso primeiro encontro",
    "Ein ganz normaler Alltagstag" to "Um dia completamente normal",
    "Eine gemeinsame Reise" to "Uma jornada juntos",
    "Ein schwerer Moment, den wir geschafft haben" to "Um momento difícil que conseguimos",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "O que você mais gostaria de fazer em um dia juntos?",
    "Ausschlafen und faulenzen" to "Durma e relaxe",
    "Etwas Neues ausprobieren" to "Experimente algo novo",
    "Rausgehen in die Natur" to "Entre na natureza",
    "Freunde treffen" to "Conheça amigos",
    "Wie fühlst du dich am meisten geliebt?" to "Como você se sente mais amado?",
    "Durch Worte" to "Através de palavras",
    "Durch Zeit zu zweit" to "Através do tempo juntos",
    "Durch Berührung" to "Por toque",
    "Durch kleine Gesten" to "Através de pequenos gestos",
    "Worauf freust du dich bei uns am meisten?" to "O que você mais espera conosco?",
    "Unsere nächste Reise" to "Nossa próxima viagem",
    "Zusammenziehen" to "Contratação",
    "Einfach mehr Alltag" to "Simplesmente mais vida cotidiana",
    "Alles, was noch kommt" to "Tudo o que está por vir",
    "Wer würde eher zu spät kommen?" to "Quem tem maior probabilidade de se atrasar?",
    "Ich" to "eu",
    "Mein Partner" to "Meu parceiro",
    "Beide gleich" to "Ambos iguais",
    "Keiner von uns" to "Nenhum de nós",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Quem tem maior probabilidade de ceder primeiro em uma discussão?",
    "Kommt drauf an" to "Depende",
    "Wir treffen uns in der Mitte" to "Nos encontraremos no meio",
    "Wer würde eher spontan eine Reise buchen?" to "Quem estaria mais propenso a reservar uma viagem espontaneamente?",
    "Beide zusammen" to "Ambos juntos",
    "Niemand ohne Plan" to "Ninguém sem um plano",
    "Wer vergisst eher einen Jahrestag?" to "Quem tem maior probabilidade de esquecer um aniversário?",
    "Keiner" to "Nenhum",
    "Beide, aber wir tun so als ob nicht" to "Ambos, mas fingimos que não",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Eu nunca... cancelei um encontro para ficar em casa.",
    "Stimmt, noch nie" to "Isso mesmo, nunca",
    "Doch, schon mal" to "Sim, já",
    "Öfter als ich zugebe" to "Mais frequentemente do que admito",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Eu nunca... olhei secretamente para o telefone do meu parceiro.",
    "Einmal" to "Uma vez",
    "Ich würde es nie tun" to "eu nunca faria isso",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Eu nunca... reformulei uma mensagem 10 vezes.",
    "Ständig" to "Constantemente",
    "Nur bei wichtigen Themen" to "Somente em tópicos importantes",
    "Was bedeutet Vertrauen für dich konkret?" to "O que confiança significa especificamente para você?",
    "Dass ich alles erzählen kann" to "Que eu posso contar tudo",
    "Dass ich mich nicht sorgen muss" to "Que eu não preciso me preocupar",
    "Dass Zusagen gehalten werden" to "Que as promessas sejam cumpridas",
    "Alles davon" to "Tudo isso",
    "Was ist für dich ein absoluter Dealbreaker?" to "O que é um obstáculo absoluto para você?",
    "Lügen" to "Mentiras",
    "Respektlosigkeit" to "Desrespeito",
    "Gleichgültigkeit" to "Indiferença",
    "Untreue" to "Infidelidade",
    "Wann fühlst du dich mir am nächsten?" to "Quando você se sente mais próximo de mim?",
    "Beim Reden" to "Enquanto conversa",
    "In Stille nebeneinander" to "Em silêncio um ao lado do outro",
    "Wenn wir zusammen lachen" to "Quando rimos juntos",
    "Wenn es schwierig ist" to "Quando as coisas estão difíceis",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Do que você mais tem medo em nosso relacionamento?",
    "Uns auseinanderzuleben" to "Para crescer distante",
    "Missverständnisse" to "Mal-entendidos",
    "Die Distanz" to "A distância",
    "Vor nichts" to "De nada",
    "Führen wir getrennte oder gemeinsame Konten?" to "Temos contas separadas ou conjuntas?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Como lidamos com diferentes rendimentos?",
    "Wofür sparen wir gemeinsam?" to "Para que estamos economizando juntos?",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "De quanto estamos falando antes de fazer uma compra?",
    "Nähe & Intimität" to "Proximidade e intimidade",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Quando você se sente fisicamente mais próximo de mim?",
    "Beim Einschlafen nebeneinander" to "Adormecer um ao lado do outro",
    "Wenn wir uns lange umarmen" to "Quando nos abraçamos por muito tempo",
    "Bei einer spontanen Berührung" to "Com um toque espontâneo",
    "Was fehlt dir über die Distanz am meisten?" to "Do que você mais sente falta na distância?",
    "Körperliche Nähe" to "Proximidade física",
    "Einfach nebeneinander sein" to "Basta estar um ao lado do outro",
    "Gemeinsame Nächte" to "Noites juntos",
    "Alltägliche Berührungen" to "Toques diários",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Quão fácil é para você falar sobre desejos?",
    "Sehr leicht" to "Muito leve",
    "Geht so" to "Vai assim",
    "Eher schwer" to "Bastante difícil",
    "Ich übe noch" to "Eu ainda estou praticando",
    "Was macht einen Moment für dich romantisch?" to "O que torna um momento romântico para você?",
    "Aufmerksamkeit" to "Atenção",
    "Überraschung" to "Surpresa",
    "Vertrautheit" to "Familiaridade",
    "Dass wir ungestört sind" to "Que não somos perturbados",
    "Zeichne für mich" to "Desenhe para mim",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Desenhe nosso primeiro encontro - o que definitivamente precisa estar na foto?",
    "Der Ort" to "O lugar",
    "Was wir gegessen haben" to "O que comemos",
    "Unsere Gesichter" to "Nossos rostos",
    "Das Wetter an dem Tag" to "O clima naquele dia",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Desenhe a casa dos nossos sonhos em uma linha. Qual é a coisa mais impressionante?",
    "Große Fenster" to "Grandes janelas",
    "Der Garten" to "O jardim",
    "Ein Herz an der Tür" to "Um coração na porta",
    "Zwei Stühle davor" to "Duas cadeiras na frente dele",
    "Zeichne mich als Tier — welches wäre ich?" to "Desenhe-me como um animal - o que eu seria?",
    "Katze" to "gato",
    "Hund" to "Cachorro",
    "Pinguin" to "Pinguim",
    "Etwas ganz anderes" to "Algo completamente diferente",
    "Zeichne unser Gefühl zueinander als Symbol." to "Desenhe nossos sentimentos um pelo outro como um símbolo.",
    "Ein Herz" to "Um coração",
    "Zwei Kreise, die sich überschneiden" to "Dois círculos que se sobrepõem",
    "Eine Brücke" to "Uma ponte",
    "Ein Anker" to "Uma âncora",
    "In einer Beziehung sollte man alles voneinander wissen." to "Em um relacionamento vocês devem saber tudo um sobre o outro.",
    "Stimme voll zu" to "Concordo totalmente",
    "Eher zu" to "Em vez disso",
    "Eher nicht" to "Na verdade não",
    "Lehne ab" to "Recusar",
    "Man sollte nie streitend einschlafen." to "Você nunca deve adormecer discutindo.",
    "Getrennte Urlaube tun einer Beziehung gut." to "Férias separadas são boas para um relacionamento.",
    "Eifersucht ist ein Zeichen von Liebe." to "O ciúme é um sinal de amor.",
    "Freundschaften mit Ex-Partnern sind okay." to "Amizades com ex-namorados estão bem.",
    "Tägliche Aktivität" to "Atividade diária",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Como seu parceiro pode ser um parceiro ainda melhor para você?",
    "Kennst du die Essensvorlieben deines Partners?" to "Você conhece as preferências alimentares do seu parceiro?",
    "Das tägliche Leben" to "Vida diária",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Nunca adormeci num cinema.",
    "Ich habe noch nie!" to "Eu nunca!",
    "Ich habe!" to "Eu tenho!",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Nunca cancelei planos de ficar em casa assistindo a um programa de TV.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Nunca joguei em um time esportivo universitário.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Nunca esqueci roupas molhadas na máquina de lavar por alguns dias.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Nunca dirigi um carro elétrico.",
    "Ich habe noch nie einen Nachtzug genommen." to "Nunca peguei trem noturno.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Nunca tive que correr para pegar um voo de conexão.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Nunca dirigi um carro em um país estrangeiro.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Nunca tive um amigo que se mudou para outro país.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Nunca encontrei um amigo que falasse outra língua nativa.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Nunca excluí uma postagem nas redes sociais porque ela não recebeu curtidas suficientes.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Nunca chorei pelo final de um programa de televisão.",
    "Unser Intimleben" to "Nossa vida íntima",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Qual é a melhor maneira para seu parceiro iniciar sexo com você?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Como você se sente em relação a conversas sujas durante o sexo?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Qual é a coisa mais importante que você procura em um encontro sexual?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "O que você acha de assistir conteúdo erótico juntos?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Qual é a sua maneira favorita de demonstrar afeto fora do sexo?",
    "Beschreibe unser Sexleben mit einem Emoji." to "Descreva nossa vida sexual com um emoji.",
    "Unbeliebte Meinungen" to "Opiniões impopulares",
    "Ananas auf der Pizza schmeckt köstlich." to "Abacaxi na pizza tem um sabor delicioso.",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Locais turísticos famosos são sempre uma decepção.",
    "Geister existieren wirklich." to "Fantasmas realmente existem.",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Às vezes, os comerciais de TV são interessantes de assistir.",
    "Eine neue Sprache zu lernen ist einfach." to "Aprender um novo idioma é fácil.",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Assistir o mesmo filme duas vezes é uma perda de tempo.",
    "Ehepaar Leben" to "Vida de casal",
    "Wer ist romantischer?" to "Quem é mais romântico?",
    "Wer ist der beste Tänzer?" to "Quem é o melhor dançarino?",
    "Wer gibt mehr Herzlichkeit?" to "Quem dá mais calor?",
    "Wer hat den besseren Musikgeschmack?" to "Quem tem melhor gosto musical?",
    "Wer findet die besten Restaurants?" to "Quem encontra os melhores restaurantes?",
    "Wer hängt mehr an seinen Eltern?" to "Quem é mais apegado aos pais?",
    "Wer ist besser organisiert?" to "Quem está melhor organizado?",
    "Wer ist der Beste bei der Filmauswahl?" to "Quem é o melhor na escolha de filmes?",
    "Wer kocht besser?" to "Quem cozinha melhor?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Quem é o melhor em planejar encontros românticos?",
    "Gesprächsanreger" to "Iniciadores de conversa",
    "Was möchtest du, dass dein Partner öfter tut?" to "O que você gostaria que seu parceiro fizesse com mais frequência?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Qual é a sua foto favorita nossa? 📸",
    "Welches Lied macht dich an? 🥵" to "Qual música te excita? 🥵",
    "Was magst du an deinem Partner am liebsten?" to "O que você mais gosta no seu parceiro?",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Qual é o seu maior medo em morar junto?",
    "Was hast du von deinem Partner gelernt?" to "O que você aprendeu com seu parceiro?",
    "Liebe im Gleichgewicht" to "Amor em equilíbrio",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Deixe seu parceiro inspirar você a dar o melhor de si",
    "Werde so akzeptiert, wie du bist" to "Seja aceito como você é",
    "Ein Jahr lang eine Fernbeziehung führen" to "Tenha um relacionamento à distância por um ano",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Não conversamos um com o outro por um mês",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Ter momentos íntimos apenas quando seu parceiro os inicia",
    "Alle intimen Momente selbst initiieren" to "Inicie você mesmo todos os momentos íntimos",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Em vez disso, compartilhe seus segredos mais profundos com seu parceiro",
    "Einige Dinge für dich behalten" to "Guarde algumas coisas para você",
    "Eine Million Dollar gewinnen" to "Ganhe um milhão de dólares",
    "Eine Million Dollar verdienen" to "Ganhe um milhão de dólares",
    "Einen sehr emotionalen Partner haben" to "Ter um parceiro muito emocional",
    "Einen sehr logischen Partner haben" to "Ter um parceiro muito lógico",
    "Deine Beziehung stabil und sicher machen" to "Torne seu relacionamento estável e seguro",
    "Deine Beziehung abenteuerlich und spontan machen" to "Torne seu relacionamento aventureiro e espontâneo",
    "Deinen besten Freund verlieren" to "Perdendo seu melhor amigo",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Perca todos os seus amigos, exceto seu melhor amigo",
    "Teile alle deine Hobbys mit deinem Partner" to "Compartilhe todos os seus hobbies com seu parceiro",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Ser apresentado a novos hobbies por seu parceiro",
    "Derjenige sein, der umarmt wird" to "Seja aquele que está sendo abraçado",
    "Diejenige sein, die umarmt" to "Seja aquele que abraça",
    "Verbringe die Feiertage mit deiner Familie" to "Passe as férias com sua família",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Passe as férias com a família do seu parceiro",
    "Neue Liebe, neue Erfahrungen" to "Novo amor, novas experiências",
    "Ich lache viel mit meinem Partner." to "Eu rio muito com meu parceiro.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Gosto de descobrir novos hobbies ou atividades com meu parceiro.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Gosto de compartilhar memes e piadas com meu parceiro.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Priorizo ​​passar tempo com meu parceiro mesmo quando estou ocupado.",
    "Ich schreibe meinem Partner jeden Tag." to "Eu mando mensagens para meu parceiro todos os dias.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Gosto de compartilhar todos os detalhes do meu dia com meu parceiro.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Gosto de conhecer os hobbies e interesses do meu parceiro.",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Fico irritado quando meu parceiro demora muito para responder às mensagens.",
    "Ich plane gerne Dates mit meinem Partner." to "Gosto de planejar encontros com meu parceiro.",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Adoro assistir filmes com meu parceiro que nenhum de nós viu antes.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Adoro compartilhar minha música favorita com meu parceiro.",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Gestos românticos como mensagens, bilhetes ou presentes me deixam feliz.",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Prefiro passeios românticos no parque a ir ao cinema.",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Gosto de experimentar novos restaurantes com meu parceiro em vez de ir sempre aos mesmos lugares.",
    "Ein Filmabend" to "Uma noite de cinema",
    "Ein Spieleabend" to "Uma noite de jogo",
    "Ein aktives Abenteuer" to "Uma aventura ativa",
    "Ein entspannender Spa-Tag" to "Um relaxante dia de spa",
    "Ein gemütliches Date drinnen" to "Um encontro aconchegante dentro de casa",
    "Eine Autoreise" to "Uma viagem",
    "Einen Film anschauen" to "Assistir a um filme",
    "Gemeinsam ein Lego bauen" to "Construam um Lego juntos",
    "Eine Weinverkostung" to "Uma degustação de vinhos",
    "Eine Schokoladenverkostung" to "Uma degustação de chocolate",
    "Eine gemütliche Nacht zu Hause" to "Uma noite aconchegante em casa",
    "Ein Abenteuer in einer neuen Stadt" to "Uma aventura em uma nova cidade",
    "Zu einem Picknick gehen" to "Indo para um piquenique",
    "Zu einem ausgefallenen Abendessen gehen" to "Indo para um jantar chique",
    "Ein romantischer Abend" to "Uma noite romântica",
    "Eine Nacht in einem Club" to "Uma noite em um clube",
    "Eine Date-Nacht unter den Sternen" to "Uma noite de encontro sob as estrelas",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Um jantar romântico à luz de velas",
    "In einen Coffeeshop gehen" to "Vá a uma cafeteria",
    "In eine Bar gehen" to "Vá para um bar",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Uma noite aconchegante em casa durante uma tempestade",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Um ótimo encontro ao ar livre sob o luar",
    "Einen Vergnügungspark erkunden" to "Explore um parque de diversões",
    "Ein Museum besuchen" to "Visite um museu",
    "Ein Spieleabend mit Freunden" to "Uma noite de jogos com amigos",
    "Ein romantisches Picknick an einem schönen Ort" to "Um piquenique romântico em um lindo local",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Experimente uma nova receita juntos na cozinha",
    "In einem feinen Restaurant essen gehen" to "Comer fora em um bom restaurante",
    "Zelten gehen" to "Vá acampar",
    "Einen Wellness-Tag" to "Um dia de bem-estar",
    "Einen Tanzkurs besuchen" to "Faça uma aula de dança",
    "Eine Wanderung mit Panoramablick machen" to "Faça uma caminhada com vistas panorâmicas",
    "Spiele spielen und Spaß haben" to "Jogue e divirta-se",
    "Tiefgründige Gespräche führen" to "Tenha conversas profundas",
    "Ein Live-Musik-Konzert besuchen" to "Assistir a um concerto de música ao vivo",
    "Auf eine Bootsparty gehen" to "Vá a uma festa no barco",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Vá de manhã cedo para ver o nascer do sol",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Ir a um bar na praia para ver o pôr do sol",
    "Gourmet Eis-Sorten" to "Variedades de sorvete gourmet",
    "Vanille" to "Baunilha",
    "Schokolade" to "chocolate",
    "Erdbeere" to "Morango",
    "Zitrone" to "Limão",
    "Stracciatella" to "Stracciatella",
    "Pistazie" to "Pistache",
    "Mango Sorbet" to "Sorvete de manga",
    "Himbeere" to "Framboesa",
    "Salted Caramel" to "Caramelo salgado",
    "Cookie Dough" to "Massa de biscoito",
    "Hazelnut" to "Avelã",
    "White Chocolate" to "Chocolate branco",
    "Walnuss" to "Noz",
    "Banane" to "Banana",
    "6 Monate im Altbau mit Charme" to "6 meses em um charmoso prédio antigo",
    "📂 Ordner" to "📂 Pasta",
    "📝 Spiele" to "📝 Jogos",
    "🔗 Ketten" to "🔗 Correntes",
    "🖼️ Bilder" to "🖼️ Fotos",
    "⚡ Test" to "⚡ Teste",
    "📤 Export" to "📤 Exportações",
    "Entwickler Studio" to "Estúdio de desenvolvedor",
    "Ordner rein · Paare raus · Export für AI Studio" to "Pasta de entrada · Pares · Exportação para AI Studio",
    "Ordner wird gelesen…" to "A pasta está sendo lida...",
    "Keine Bilder in diesem Ordner gefunden." to "Nenhuma imagem encontrada nesta pasta.",
    "Bilder werden gelesen…" to "As imagens são lidas...",
    "Bilder-Ordner einlesen" to "Ler pastas de imagens",
    "Je zwei Bilder werden ein Paar. Die Reihenfolge unten ist die Reihenfolge im Spiel —" to "Cada duas fotos formam um par. A ordem abaixo é a ordem do jogo –",
    "verschiebe Zeilen mit den Pfeilen, wenn ein Paar nicht passt." to "mova as linhas com as setas se um par não corresponder.",
    "Ordner" to "pasta",
    "Bilder" to "Imagens",
    "Kategorie (z.B. Eis)" to "Categoria (por exemplo, sorvete)",
    "Name" to "nome",
    "Emoji" to "Emoji",
    "Titel des Spiels" to "Título do jogo",
    "Spiel-Emoji" to "Emoji de jogo",
    "Ein Bild bleibt übrig und wird ignoriert." to "Uma imagem permanece e é ignorada.",
    "Leeren" to "Vazio",
    "Paket erstellen & freischalten" to "Criar e ativar pacote",
    "Dateinamen wie 01a_vanille.jpg / 01b_schoko.jpg werden automatisch als Paar erkannt." to "Nomes de arquivos como 01a_vanille.jpg / 01b_schoko.jpg são automaticamente reconhecidos como um par.",
    "Sonst zählt die alphabetische Reihenfolge." to "Caso contrário, a ordem alfabética conta.",
    "Name (optional - leer lassen für kein Text)" to "Nome (opcional - deixe em branco se não houver texto)",
    "Nach oben" to "Acima",
    "Nach unten" to "Para baixo",
    "Entfernen" to "Remover",
    "Senden" to "Enviar",
    "GFK Brücke" to "Ponte GRP",
    "Spiel suchen…" to "Pesquisar jogo...",
    "Kategorien & Farben" to "Categorias e cores",
    "Neues Spiel" to "Novo jogo",
    "Alle" to "Todos",
    "⚖️ Das oder Das" to "⚖️Isso ou aquilo",
    "🧠 Quiz" to "🧠 Questionário",
    "🗣️ Diskussion" to "🗣️ Discussão",
    "Das oder Das" to "Isso ou aquilo",
    "Quiz" to "Questionário",
    "Diskussion" to "Discussão",
    "Bearbeiten" to "Editar",
    "Löschen" to "Excluir",
    "Schließen" to "Fechar",
    "Spiel bearbeiten" to "Editar jogo",
    "Speichern" to "Salvar",
    "Titel" to "Título",
    "Kategorie" to "Categoria",
    "🎨 Farben & Kategorien verwalten" to "🎨 Gerenciar cores e categorias",
    "Spieltyp" to "Tipo de jogo",
    "Paare — tippe auf ein Bild, um es zu tauschen" to "Pares — toque em uma imagem para trocar",
    "Paar" to "Casal",
    "Galerie" to "Galeria",
    "Paare mischen" to "Misture pares",
    "Fragen" to "Perguntas",
    "Frage hinzufügen" to "Adicionar pergunta",
    "Paar löschen" to "Excluir par",
    "Bild ändern" to "Alterar imagem",
    "Name (optional)" to "Nome (opcional)",
    "Fragetext" to "Texto da pergunta",
    "Frage löschen" to "Excluir pergunta",
    "Antworten, getrennt mit |" to "Respostas separadas por |",
    "Bilder & Städte" to "Imagens e cidades",
    "Jede Option aus allen Spielen. Tippen und ein eigenes Bild aus der Galerie wählen." to "Todas as opções de todos os jogos. Toque e escolha sua própria foto na galeria.",
    "Option suchen…" to "Opção de pesquisa…",
    "Nur Optionen ohne eigenes Bild" to "Apenas opções sem imagem própria",
    "Eigenes Bild" to "Própria imagem",
    "Zurücksetzen" to "Redefinir",
    "Schnelltest" to "Teste rápido",
    "Mindestens zwei Bilder auswählen." to "Selecione pelo menos duas imagens.",
    "Dem Spiel fehlt noch ein Titel." to "O jogo ainda está sem título.",
    "Bilder werden gespeichert…" to "As imagens são salvas...",
    "Bild wird übernommen…" to "A imagem foi tirada...",
    "Bilder werden eingelesen…" to "As imagens estão sendo lidas em...",
    "Bild konnte nicht gelesen werden." to "A imagem não pôde ser lida.",
    "Keine Pakete zum Exportieren." to "Nenhum pacote para exportar.",
    "Export wird gebaut…" to "A exportação está sendo construída…",
    "Über 3 MB — nimm eine kleinere Bildgröße oder exportiere die Pakete einzeln." to "Mais de 3 MB — use um tamanho de imagem menor ou exporte os pacotes individualmente.",
    "Keine eigenen Bilder vorhanden." to "Não há fotos próprias disponíveis.",
    "Startet ein Spiel im echten Runner — genau so, wie ihr es später spielt." to "Comece um jogo no Runner real — exatamente como você jogará mais tarde.",
    "Testen" to "Teste",
    "Export für Google AI Studio" to "Exportar para Google AI Studio",
    "Eine einzige Textdatei mit Paketen und Bildern. AI Studio nimmt keine ZIPs —" to "Um único arquivo de texto contendo pacotes e imagens. AI Studio não aceita ZIPs —",
    "deshalb stecken die Bilder als Base64 direkt im Kotlin-Code." to "É por isso que as imagens estão em Base64 diretamente no código Kotlin.",
    "Noch nichts zum Exportieren. Leg im Tab \"Ordner\" ein erstes Paket an." to "Nada para exportar ainda. Crie um primeiro pacote na aba “Pasta”.",
    "Pakete (nichts ausgewählt = alle)" to "Pacotes (nada selecionado = todos)",
    "Bilder mitschicken" to "Envie fotos",
    "Aus: nur Texte, Datei bleibt winzig" to "Desligado: apenas textos, o arquivo permanece pequeno",
    "Bildgröße im Export" to "Tamanho da imagem na exportação",
    "Klein · 480px" to "Pequeno · 480px",
    "Mittel · 720px" to "Médio · 720px",
    "Groß · 960px" to "Grande · 960 px",
    "Für AI Studio exportieren" to "Exportar para AI Studio",
    "Bilder einzeln teilen" to "Compartilhe imagens individualmente",
    "Vollständiges Projekt-Backup (JSON)" to "Backup completo do projeto (JSON)",
    "Enthält alle Spiele, Ketten, Kategorien UND alle eingebetteten Bilder als Base64. Ideal zur Sicherung, Übertragung & Wiederherstellung." to "Inclui todos os jogos, cadeias, categorias E todas as imagens incorporadas como Base64. Ideal para backup, transferência e restauração.",
    "Kopieren" to "Copiar",
    "JSON teilen" to "Compartilhar JSON",
    "Einspielen" to "Jogue em",
    "JSON oder Export-Inhalt (mit Base64) hier einfügen" to "Cole JSON ou exporte conteúdo (com Base64) aqui",
    "Inhalt & Bilder jetzt einspielen" to "Importe conteúdo e imagens agora",
    "🔗 Ketten-Spiele" to "🔗 Jogos em cadeia",
    "Pakete mit dynamischen Bauanleitungen, die sich aus bisherigen Antworten zusammensetzen." to "Pacotes com instruções de construção dinâmicas compostas por respostas anteriores.",
    "Neue Kette" to "Nova cadeia",
    "Kette bauen" to "Construa uma corrente",
    "1 Jahr lang in {}" to "por 1 ano em {}",
    "6 Monate im {}" to "6 meses em {}",
    "Weil du {A} gewählt hast …" to "Porque você escolheu {A}...",
    "Noch keine Ketten angelegt" to "Nenhuma corrente colocada ainda",
    "Erstelle ein Ketten-Paket, um Fragen dynamisch mit bisherigen Antworten zu verknüpfen." to "Crie um pacote em cadeia para vincular dinamicamente as perguntas às respostas anteriores.",
    "Spielen" to "Jogar",
    "Kette bearbeiten" to "Editar cadeia",
    "Neue Kette erstellen" to "Criar nova cadeia",
    "Kopfzeile (z.B. Weil du {A} gewählt hast …)" to "Cabeçalho (por exemplo, porque você escolheu {A}...)",
    "Satzmuster (z.B. 6 Monate im {})" to "Padrão de frase (por exemplo, 6 meses em {})",
    "Neuen Schritt hinzufügen" to "Adicionar nova etapa",
    "Abbrechen" to "Cancelar",
    "Speichern & testen" to "Salvar e testar",
    "Quelle wählen:" to "Selecione a fonte:",
    "Gewählt" to "Eleito",
    "Nicht gewählt" to "Não eleito",
    "Feste Option" to "Opção fixa",
    "Fester Text" to "Texto fixo",
    "Quell-Paket:" to "Pacote fonte:",
    "Türkis" to "Turquesa",
    "Limetten grün" to "Verde limão",
    "Kategorie-Farbe wählen" to "Selecione a cor da categoria",
    "Neue Kategorie erstellen" to "Criar nova categoria",
    "Kategorie bearbeiten" to "Editar categoria",
    "Neue Kategorie" to "Nova categoria",
    "leer" to "vazio",
    "Kein Paket gewählt" to "Nenhum pacote selecionado",
    "Gewählte Antwort" to "Resposta selecionada",
    "Verworfene Antwort" to "Resposta rejeitada",
    "beliebiges Paar" to "qualquer par",
    "Paris oder Rom" to "Paris ou Roma",
    "JSON Backup wird vorbereitet…" to "O backup JSON está sendo preparado…",
    "🎉 JSON inkl. Bildern & Ketten kopiert!" to "🎉 JSON incluindo imagens e cadeias copiadas!",
    "JSON Backup Datei wird erstellt…" to "O arquivo de backup JSON é criado...",
    "Daten werden eingespielt…" to "Os dados são importados...",
    "Kette gestartet" to "Cadeia iniciada",
    "🔗 Ketten-Bauer" to "🔗 Peão de Corrente",
    "Linke Karte (Seite A)" to "Cartão esquerdo (lado A)",
    "Rechte Karte (Seite B)" to "Cartão direito (lado B)",
    "Vorschau:" to "Visualização:",
    "Paar / Option:" to "Par/Opção:",
    "Beliebiges / letztes Paar" to "Qualquer/último par",
    "Seite:" to "Página:",
    "Linke Option (0)" to "Opção esquerda (0)",
    "Rechte Option (1)" to "Opção certa (1)",
    "🏷️ Kategorien & Farben" to "🏷️ Categorias e cores",
    "Titel des Ketten-Spiels" to "Título do jogo em cadeia",
    "Unbenannte Kette" to "Cadeia sem nome",
    "Verworfen" to "Descartado",
    "Freier Text" to "Texto livre",
    "Satzmuster (z.B. 1 Jahr lang in {})" to "Padrões de frase (por exemplo, por 1 ano em {})",
    "Standardbild" to "Imagem padrão",
    "eigen" to "próprio",
    "Eis" to "Sorvete",
    "Eissorten" to "Sabores de sorvete",
    "Gold" to "Ouro",
    "Rosa" to "Rosa",
    "Lila" to "Roxo",
    "Blau" to "Azul",
    "Koralle" to "Coral",
    "Smaragd" to "Esmeralda",
    "Rubinrot" to "Vermelho rubi",
    "Lavendel" to "Lavanda",
    "Magenta" to "Magenta",
    "Orange" to "Laranja",
    "Neubau mit Technik" to "Novo prédio com tecnologia",
    "Offene Küche" to "Cozinha aberta",
    "Gemüsebeet" to "horta",
    "Hängematte" to "Rede",
    "Blumenwiese" to "Prado de flores",
    "Dachterrasse" to "Terraço",
    "Grillplatz" to "Área de churrasco",
    "Kamin" to "Lareira",
    "Belgische Schokolade" to "Chocolate belga",
    "In AI Studio hochladen und schreiben: \"Ersetze GeneratedHarmonyContent.kt komplett durch den Inhalt dieser Datei.\"" to "Faça upload para o AI Studio e escreva: \"Substitua GeneratedHarmonyContent.kt inteiramente pelo conteúdo deste arquivo.\"",
    "Fragen & Spiele" to "Perguntas e jogos",
    "Kategorien" to "Categorias",
    "Themen" to "Tópicos",
    "Für dich empfohlen" to "Recomendado para você",
    "Paar-Statistiken" to "Estatísticas de pares",
    "Gemeinsame Tage" to "Dias compartilhados",
    "Beantwortete Fragen" to "Perguntas respondidas",
    "Besuchte Städte" to "Cidades visitadas",
    "Besuchte Länder" to "Países visitados",
    "Widgets" to "Widgets",
    "Du fehlst mir" to "Eu sinto sua falta",
    "Denke an dich" to "Pense em você",
    "Ich denke an dich" to "Estou pensando em você",
    "Kuss senden" to "Manda beijo",
    "Kuss" to "Beijo",
    "ERGEBNISSE" to "RESULTADOS",
    "BEANTWORTE" to "RESPOSTA",
    "Alle Pakete" to "Todos os pacotes",
    "Profil" to "Perfil",
    "Dein Name" to "Seu nome",
    "Partnerin" to "parceiro",
    "Zusammen seit" to "Juntos desde",
    "Partner-Simulator" to "Simulador de parceiro",
    "Sprache" to "idioma",
    "Deutsch" to "Alemão",
    "Englisch" to "Inglês",
    "Entwickler-Modus" to "Modo de desenvolvedor",
    "Entwickler Studio Öffnen" to "Abra o Developer Studio",
    "Profil bearbeiten" to "Editar perfil",
    "Name Partnerin" to "Nome do parceiro",
    "Hinzufügen" to "Adicionar",
    "Momente" to "momentos",
    "Was ist passiert?" to "O que aconteceu?",
    "oder" to "ou",
    "Zurück" to "Voltar",
    "Deine eigene Antwort" to "Sua própria resposta",
    "Deine Antwort..." to "Sua resposta...",
    "Übernehmen" to "Assumir",
    "Antwortähnlichkeit" to "Similaridade de resposta",
    "Diskutiert eure Antworten" to "Discuta suas respostas",
    "Fertig!" to "Pronto!",
    "✎ Tippe, um zu antworten" to "✎ Toque para responder",
    "Schreibe deine eigene Antwort" to "Escreva sua própria resposta",
    "Quiz verlassen?" to "Sair do teste?",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Você realmente quer sair do quiz? Seu progresso anterior permanece salvo.",
    "Schreib frei, was dir wirklich dazu einfällt." to "Escreva livremente o que realmente vem à mente.",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Você descobriu alguma diferença surpreendente? Fale sobre por que você gosta mais de certas opções!",
    "✕ Schließen" to "✕ Fechar",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Não há nada aqui agora. Altere o filtro ou escolha um tópico diferente.",
    "✨ GFK-Brücke" to "✨ Ponte GRP",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Reformule seu rascunho de forma não violenta: observação, sentimento, necessidade, pedido.",
    "Was möchtest du eigentlich sagen?" to "O que você realmente quer dizer?",
    "In Chat einfügen" to "Adicionar ao bate-papo",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Analise suas respostas e bate-papos de acordo com Gottman e GFK.",
    "Wünsche? z.B. günstig, draußen" to "Desejos? por exemplo barato, fora",
    "Spiele & Städte bearbeiten, Ordner reinladen, Bilder anpassen" to "Edite jogos e cidades, carregue pastas, ajuste imagens",
    "🔥 Tägliche Aktivität" to "🔥 Atividade diária",
    "+ Hinzufügen" to "+ Adicionar",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Nenhum momento ainda. Capture sua primeira experiência 💞",
    "Ein Harmony-Meilenstein eurer Liebe." to "Um marco de harmonia do seu amor.",
    "Was wollt ihr nie vergessen?" to "O que você nunca quer esquecer?",
    "🟠 Du bist dran" to "🟠 Chegou a sua vez",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Responda às perguntas ao mesmo tempo. As respostas não ficarão visíveis até que ambos terminem.",
    "Wir" to "Nós",
    "Hey du 💕 wie war dein Tag?" to "Ei você 💕 como foi seu dia?",
    "Stressig — aber jetzt wird’s besser ☺️" to "Estressante - mas as coisas estão melhorando agora ☺️",
    "Ich hab schon an unser Wiedersehen gedacht 🥹" to "Já estava pensando no nosso reencontro 🥹",
    "Unser erstes Videodate" to "Nosso primeiro encontro de vídeo",
    "Vier Stunden geredet und die Zeit vergessen." to "Conversamos por quatro horas e perdi a noção do tempo.",
    "Überraschungspaket" to "Pacote surpresa",
    "Kekse und ein Brief — ich musste weinen vor Freude." to "Biscoitos e uma carta - chorei de alegria.",
    "Das klingt schön 🥰" to "Parece legal 🥰",
    "Ich vermiss dich gerade richtig" to "Eu realmente sinto sua falta agora",
    "Erzähl mir mehr davon 💕" to "Conte-me mais sobre isso 💕",
    "Haha du bringst mich immer zum Lachen 😄" to "Haha você sempre me faz rir 😄",
    "Können wir heute Abend telefonieren?" to "Podemos conversar ao telefone esta noite?",
    "Ich denk so oft an dich ❤️" to "Penso em você tantas vezes ❤️",
    "Gemini API Key ist nicht konfiguriert. Bitte füge deinen GEMINI_API_KEY im AI Studio Secrets Panel ein." to "A chave de API Gemini não está configurada. Cole seu GEMINI_API_KEY no painel AI ​​Studio Secrets.",
    "Keine Antwort erhalten." to "Nenhuma resposta recebida.",
    "Du bist dran" to "É a sua vez",
    "Beantwortet" to "Respondido",
    "Überspringen" to "Pular",
    "Weiter" to "Próximo",
    "KI-Beziehungscoach" to "Coach de relacionamento com IA",
    "KI-Date-Ideen" to "Ideias para encontros de IA",
    "Analyse starten" to "Iniciar análise",
    "Ideen generieren" to "Gerar ideias",
    "Namen und Startdatum eurer Beziehung." to "Nome e data de início do seu relacionamento.",
    "Fertig" to "Concluído",
    "Weiter spielen" to "Continue jogando",
    "Formuliere um..." to "Reformular...",
    "Umformulieren" to "Reformular",
    "Nachricht an \$partnerName..." to "Mensagem para \$partnerName...",
    "✅ Beantwortet" to "✅ Respondido",
    "Verbinde dich mit \$partnerName" to "Conecte-se com \$partnerName",
    "1 Jahr zusammen 🎉" to "1 ano juntos 🎉",
    "2 Jahre zusammen 🎉" to "2 anos juntos 🎉",
    "3 Jahre zusammen 🎉" to "3 anos juntos 🎉",
    "\$d Tage zusammen 💞" to "\$d dias juntos 💞",
    "Moment festhalten" to "Capture o momento",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Código de convite: HRM-8731 · tudo desbloqueado",
    "✨ KI-Beziehungscoach" to "✨ Coach de relacionamento com IA",
    "Analysiere eure Muster..." to "Analise seus padrões...",
    "💡 KI-Date-Ideen" to "💡 Ideias para encontros de IA",
    "Sammle Ideen..." to "Colete ideias...",
    "🛠️ Entwickler-Modus" to "🛠️ Modo desenvolvedor",
    "Zusammen seit (TT.MM.JJJJ)" to "Juntos desde (DD.MM.AAAA)",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Suas respostas estão salvas. Assim que \${profile.partnerName} terminar o pacote, ambas as respostas ficarão visíveis juntas.",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Conecte-se a \${profile.partnerName} para ver a resposta",
    "Quiz verlassen" to "Sair do teste",
    "Ergebnisse" to "Resultados",
    "Unterhaltung" to "Entretenimento",
    "Hochzeit" to "casamento",
    "Kinder" to "Crianças",
    "Reden vor..." to "Discursos diante de...",
    "{ANZAHL} Bilder geladen — Namen prüfen, dann erstellen." to "{NUMBER} Imagens carregadas: verifique os nomes e crie.",
    "{ANZAHL} Bilder geladen." to "{NUMBER} imagens carregadas.",
    "{ANZAHL} Paare aus {ANZAHL} Bildern" to "{NUMBER} pares de {NUMBER} imagens",
    "Bild {NUMMER} von {ANZAHL}…" to "Imagem {NUMBER} de {NUMBER}…",
    "Speichere Bild {NUMMER} von {ANZAHL}…" to "Salvar imagem {NUMBER} de {NUMBER}…",
    "Paar {NUMMER}" to "Par {NUMBER}",
    "Frage {NUMMER}" to "Pergunta {NÚMERO}",
    "Schritt {NUMMER}" to "Etapa {NUMBER}",
    "{ANZAHL} Paare" to "{NUMBER} pares",
    "{ANZAHL} Fragen" to "{NUMBER} perguntas",
    "{ANZAHL} Schritt(e)" to "{NUMBER} etapas",
    "{ANZAHL} Paare · {ANZAHL} Fragen" to "{NUMBER} pares · {NUMBER} perguntas",
    "{ANZAHL} Einträge" to "{NUMBER} entradas",
    "Fertig: {PAKETE} Pakete · {BILDER} Bilder · {DETAILS}" to "Concluído: {PACKAGES} Pacotes · {IMAGES} Fotos · {DETAILS}",
    "🎉 {ANZAHL} Pakete/Ketten & Bilder erfolgreich eingespielt!" to "🎉 {NUMBER} pacotes/correntes e imagens importados com sucesso!",
    "🎉 '{TITEL}' angelegt · {ANZAHL} Paare spielbereit" to "🎉 '{TITLE}' criado · {NUMBER} pares prontos para jogar",
    "• A: {OPTION} (Bild: {BILD})" to "• A: {OPTION} (Imagem: {IMAGE})",
    "• B: {OPTION} (Bild: {BILD})" to "• B: {OPÇÃO} (Imagem: {IMAGE})",
    "'{TITEL}' gelöscht." to "'{TITLE}' excluído.",
    "'{TITEL}' gespeichert." to "'{TITLE}' salvo.",
    "Kategorie '{TITEL}' gespeichert." to "Categoria '{TITLE}' salva.",
    "Kette '{TITEL}' gespeichert." to "Cadeia '{TITLE}' salva.",
    "Kette '{TITEL}' gelöscht." to "Cadeia '{TITLE}' excluída.",
    "Bild für '{OPTION}' gesetzt." to "Imagem definida para '{OPTION}'.",
    "Eigenes Bild für '{OPTION}' entfernt." to "Imagem personalizada removida para '{OPTION}'.",
    "{EMOJI} „{WIDGET}“ an {PARTNER} gesendet" to "{EMOJI} “{WIDGET}” enviado para {PARTNER}",
    "6 Monate im {ORT}" to "6 meses em {LOCATION}",
    "1 Jahr lang in {ORT}" to "1 ano em {LOCATION}",
    "Weil du {OPTION} gewählt hast …" to "Porque você escolheu {OPTION}...",
    "Verbinde dich mit {PARTNER}, um die Antwort zu sehen" to "Conecte-se a {PARTNER} para ver a resposta",
    "Verbinde dich mit {PARTNER}" to "Conecte-se com {PARTNER}",
    "Deine Antworten sind gespeichert. Sobald {PARTNER} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Suas respostas estão salvas. Assim que {PARTNER} encerrar o pacote, ambas as respostas ficarão visíveis juntas.",
    "Fehler bei der Umformulierung: {FEHLER}" to "Erro ao reformular a redação: {ERROR}",
    "Fehler bei der Analyse: {FEHLER}" to "Erro de análise: {ERROR}",
    "Fehler bei der Ideengenerierung: {FEHLER}" to "Erro de geração de ideias: {ERROR}",
    "{EMOJI} {INHALT}" to "{EMOJI} {CONTEÚDO}",
    "{NUMMER}. {INHALT}" to "{NÚMERO}. {CONTEÚDO}",
    "HARMONY" to "HARMONIA",
    "Home" to "Página inicial",
    "Chat" to "Bate-papo",
    "Dev" to "Desenvolvedor",
    "Jerome" to "Jerônimo",
    "Alex" to "Alex",
    "OR" to "OU",
    "VS" to "VS",
    "Export teilen" to "Compartilhar exportação",
    "Bilder teilen" to "Compartilhe fotos",
)

internal fun localizeBrazilianPortugueseDynamicContent(text: String): String? {
    Regex("^(\\d+) Bilder geladen — Namen prüfen, dann erstellen\\.$").matchEntire(text)?.let {
        return "${it.groupValues[1]} imagens carregadas — revise os nomes e crie o pacote."
    }
    Regex("^(\\d+) Bilder geladen\\.$").matchEntire(text)?.let { return "${it.groupValues[1]} imagens carregadas." }
    Regex("^(\\d+) Paare aus (\\d+) Bildern$").matchEntire(text)?.let {
        return "${it.groupValues[1]} pares de ${it.groupValues[2]} imagens"
    }
    Regex("^Bild (\\d+) von (\\d+)…$").matchEntire(text)?.let {
        return "Imagem ${it.groupValues[1]} de ${it.groupValues[2]}…"
    }
    Regex("^Paar (\\d+)$").matchEntire(text)?.let { return "Par ${it.groupValues[1]}" }
    Regex("^Frage (\\d+)$").matchEntire(text)?.let { return "Pergunta ${it.groupValues[1]}" }
    Regex("^Schritt (\\d+)$").matchEntire(text)?.let { return "Etapa ${it.groupValues[1]}" }
    Regex("^(\\d+) Paare$").matchEntire(text)?.let { return "${it.groupValues[1]} pares" }
    Regex("^(\\d+) Fragen$").matchEntire(text)?.let { return "${it.groupValues[1]} perguntas" }
    Regex("^(\\d+) Einträge$").matchEntire(text)?.let { return "${it.groupValues[1]} entradas" }
    Regex("^Verbinde dich mit (.+)$").matchEntire(text)?.let {
        return "Conecte-se com ${it.groupValues[1]}"
    }
    Regex("^Fehler bei der Umformulierung: (.+)$").matchEntire(text)?.let {
        return "Falha ao reformular: ${it.groupValues[1]}"
    }
    Regex("^Fehler bei der Analyse: (.+)$").matchEntire(text)?.let {
        return "Falha na análise: ${it.groupValues[1]}"
    }
    return null
}
