package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_ROMANIAN_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 ani",
    "1000 - 1500 im Monat" to "1000 - 1500 pe lună",
    "1000 bis 3000" to "1000 până la 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 pe lună",
    "3000 bis 5000" to "3000 până la 5000",
    "5-10 Jahre" to "5-10 ani",
    "50-100€/Monat" to "50-100€/lună",
    "Ab 100€" to "De la 100€",
    "Ab 500€" to "De la 500€",
    "Ab 50€" to "De la 50€",
    "Ab und zu" to "Din când în când",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Cât trebuie să cheltuim înainte de a face o achiziție?",
    "Abbrechen" to "Anulează",
    "Abenteuer" to "Aventură",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Activități",
    "Alle" to "Toate",
    "Alle Pakete" to "Toate pachetele",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Pierde-ți toți prietenii, cu excepția celui mai bun prieten al tău",
    "Alle intimen Momente selbst initiieren" to "Inițiază tu însuți toate momentele intime",
    "Alles davon" to "Toate acestea",
    "Alles, was noch kommt" to "Tot ce urmează",
    "Alltagsroutine" to "Rutina de zi cu zi",
    "Alltägliche Berührungen" to "Atingeri de zi cu zi",
    "Altbau mit Charme" to "Clădire veche cu farmec",
    "Am Strand" to "Pe plajă",
    "Am liebsten alles zusammen" to "De preferință totul împreună",
    "Am selben Tag mit Freunden/Familie" to "În aceeași zi cu prietenii/familia",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Țările de Jos",
    "An das Gefühl" to "A sentimentului",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "Într-un loc public cu mulți spectatori",
    "An einen Geruch" to "De un miros",
    "An einen Song" to "La un cântec",
    "An etwas, das ich gesagt habe" to "Am spus ceva",
    "Analyse starten" to "Începeți analiza",
    "Analysiere eure Muster..." to "Analizează-ți tiparele...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Analizați-vă răspunsurile și conversațiile în funcție de Gottman și GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Ananasul pe pizza are un gust delicios.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Răspunde cu o fotografie",
    "Antwortähnlichkeit" to "Răspuns asemănător",
    "App-Sprache auswählen" to "Selectați limba aplicației",
    "Auf eine Bootsparty gehen" to "Merg la o petrecere cu barca",
    "Aufmerksamkeit" to "Atenție",
    "Aufräumen und Projekte angehen" to "Curățați și abordați proiecte",
    "Aufwärmen" to "Încălzește-te",
    "Aufwärmen: Einander kennenlernen" to "Încălzire: Să ne cunoaștem",
    "Aus dem Urlaub" to "Din vacanță",
    "Ausgefallener Name" to "Nume de lux",
    "Ausschlafen und faulenzen" to "Dormiți și leneviți",
    "Ausschlafen und nichts tun" to "Dormi și nu faci nimic",
    "Aussehen" to "Aspect",
    "Auto" to "Auto",
    "Außenkamin" to "Șemineu în aer liber",
    "BEANTWORTE" to "RĂSPUNS",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonezia",
    "Banane" to "Banană",
    "Beantwortet" to "A răspuns",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Răspundeți la întrebări în același timp — răspunsurile nu vor fi vizibile până când nu terminați amândoi.",
    "Beantwortete Fragen" to "S-a răspuns la întrebări",
    "Bearbeiten" to "Editați",
    "Bei Insider-Witzen" to "Pentru glume interioare",
    "Bei Memes" to "Pe meme",
    "Bei einer spontanen Berührung" to "Când este atins spontan",
    "Beide" to "Ambele",
    "Beide gleich" to "Ambele la fel",
    "Beide zusammen" to "Ambele împreună",
    "Beide, aber wir tun so als ob nicht" to "Ambele, dar ne prefacem că nu",
    "Beides" to "Ambele",
    "Beides wäre schlimm" to "Ambele ar fi rele",
    "Beim Einschlafen nebeneinander" to "Adorm unul lângă altul",
    "Beim Reden" to "În timp ce vorbești",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Locurile turistice celebre sunt întotdeauna o dezamăgire.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Descrieți viața noastră sexuală cu un emoji.",
    "Besser kommunizieren" to "Comunicați mai bine",
    "Bessere Lage" to "Locație mai bună",
    "Bestellen" to "Comanda",
    "Besuchte Länder" to "Țările vizitate",
    "Besuchte Städte" to "Orașe vizitate",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Preferi o propunere extravagantă sau ceva subtil?",
    "Beziehung" to "Relație",
    "Bibliothek" to "Biblioteca",
    "Bin manchmal unsicher" to "Uneori sunt nesigur",
    "Bist du ein Videospiel-Guru?" to "Ești un guru al jocurilor video?",
    "Blumenwiese" to "Lunca de flori",
    "Bunte Blumenwiese" to "Pajiște cu flori colorate",
    "Burger" to "Burgeri",
    "Burger King" to "Burger King",
    "Chat" to "Chat",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Aluat pentru fursecuri",
    "Dachgarten mit Lounge" to "Grădină pe acoperiș cu lounge",
    "Dachterrasse" to "Terasă pe acoperiș",
    "Das Wetter an dem Tag" to "Vremea în acea zi",
    "Das erste Selfie" to "Primul selfie",
    "Das meiste weiß ich" to "Știu majoritatea",
    "Das oder das?" to "Asta sau asta?",
    "Das tägliche Leben" to "Viața de zi cu zi",
    "Dass Zusagen gehalten werden" to "Aceste promisiuni sunt respectate",
    "Dass alles meinen Stil hat" to "Că totul are stilul meu",
    "Dass ich alles erzählen kann" to "Că pot spune totul",
    "Dass ich mich nicht sorgen muss" to "Că nu trebuie să-mi fac griji",
    "Dass wir ungestört sind" to "Că suntem netulburați",
    "Dein Name" to "Numele tău",
    "Deine Antwort..." to "Răspunsul tău...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Răspunsurile dvs. sunt salvate. De îndată ce Partenerul termină pachetul, ambele răspunsuri vor fi vizibile împreună.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Răspunsurile dvs. sunt salvate. Odată ce \${profile.partnerName} completează pachetul, ambele răspunsuri vor fi vizibile împreună.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Fă-ți relația aventuroasă și spontană",
    "Deine Beziehung stabil und sicher machen" to "Faceți-vă relația stabilă și sigură",
    "Deine eigene Antwort" to "Răspunsul tău",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Este mai bine să-ți împărtășești cele mai adânci secrete cu partenerul tău",
    "Deinen besten Freund verlieren" to "Pierderea celui mai bun prieten al tău",
    "Denke an dich" to "Gândește-te la tine",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Vizionarea aceluiași film de două ori este o pierdere de timp.",
    "Der Blick nach draußen" to "Priveliștea de afară",
    "Der Garten" to "Grădina",
    "Der Ort" to "Locul",
    "Der Ring und die Geste" to "Inelul și gestul",
    "Der perfekte Heiratsantrag" to "Cererea perfectă în căsătorie",
    "Derjenige sein, der umarmt wird" to "Fii cel îmbrățișat",
    "Deutsch" to "germană",
    "Diamant" to "Diamant",
    "Diamanten im Band" to "Diamante în trupă",
    "Die Distanz" to "Distanța",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Petreceți vacanța cu familia partenerului dvs",
    "Die Gemütlichkeit und Ruhe" to "Confortul și pacea",
    "Die Menschen, die darin wohnen" to "Oamenii care trăiesc în ea",
    "Die Umgebung und Atmosphäre" to "Mediul și atmosfera",
    "Die Worte und Emotionen" to "Cuvintele și emoțiile",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Cea mai mare provocare de trivia de divertisment",
    "Diejenige sein, die umarmt" to "Fii cel care îmbrățișează",
    "Direkt ansprechen" to "Adresă direct",
    "Diskussion" to "Discuție",
    "Diskutiere vor dem Kinderkriegen" to "Discutați înainte de a avea copii",
    "Diskutiert eure Antworten" to "Discutați răspunsurile dvs",
    "Disney" to "Disney",
    "Doch, schon mal" to "Da, da",
    "Draußen mit der Natur als Kulisse" to "Afară, cu natura pe fundal",
    "Drei-Stein-Ring" to "Inel cu trei pietre",
    "Du bist dran" to "E rândul tău",
    "Du fehlst mir" to "Mi-e dor de tine",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubai, Emiratele Arabe Unite",
    "Dunkles Design" to "Tema întunecată",
    "Durch Berührung" to "Prin atingere",
    "Durch Worte" to "Prin cuvinte",
    "Durch Zeit zu zweit" to "De-a lungul timpului împreună",
    "Durch kleine Gesten" to "Prin gesturi mici",
    "Durchgeplant" to "Bine planificat",
    "ERGEBNISSE" to "REZULTATE",
    "Egal, Hauptsache gesund" to "Oricare ar fi, principalul lucru este sănătos",
    "Ehepaar Leben" to "Viața de cuplu căsătorit",
    "Eher knapp" to "Mai degrabă aproape",
    "Eher nicht" to "Nu atât de mult",
    "Eher schwer" to "Destul de dificil",
    "Eher schwierig" to "Destul de dificil",
    "Eher zu" to "Mai mult ca",
    "Eifersucht ist ein Zeichen von Liebe." to "Gelozia este un semn de iubire.",
    "Eigenes Gemüsebeet" to "Propul petic de legume",
    "Ein Abenteuer in einer neuen Stadt" to "O aventură într-un oraș nou",
    "Ein Anker" to "O ancoră",
    "Ein Balkon oder Garten" to "Un balcon sau o grădină",
    "Ein Filmabend" to "O seară de film",
    "Ein Harmony-Meilenstein eurer Liebe." to "O piatră de hotar a armoniei iubirii tale.",
    "Ein Herz" to "O inimă",
    "Ein Herz an der Tür" to "O inimă la uşă",
    "Ein Jahr lang eine Fernbeziehung führen" to "Ai o relație la distanță timp de un an",
    "Ein Kindheitsessen" to "O masă din copilărie",
    "Ein Live-Musik-Konzert besuchen" to "Participați la un concert de muzică live",
    "Ein Museum besuchen" to "Vizitați un muzeu",
    "Ein Spieleabend" to "O noapte de joc",
    "Ein Spieleabend mit Freunden" to "O seară de joc cu prietenii",
    "Ein Urlaubsfoto" to "O fotografie din vacanță",
    "Ein aktives Abenteuer" to "O aventură activă",
    "Ein entspannender Spa-Tag" to "O zi spa relaxantă",
    "Ein ganz normaler Alltagstag" to "O zi de zi cu totul normală",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "O seară confortabilă în casă în timpul unei furtuni",
    "Ein gemütliches Date drinnen" to "O întâlnire confortabilă în casă",
    "Ein lustiges Bild" to "O poză amuzantă",
    "Ein paar Handyfotos reichen" to "Câteva fotografii de pe telefonul mobil sunt suficiente",
    "Ein paar Stunden" to "Câteva ore",
    "Ein paar kulturelle Anklänge sind okay" to "Câteva referințe culturale sunt în regulă",
    "Ein romantischer Abend" to "O seară romantică",
    "Ein romantisches Abendessen bei Kerzenlicht" to "O cină romantică la lumina lumânărilor",
    "Ein romantisches Bild" to "O imagine romantică",
    "Ein romantisches Picknick an einem schönen Ort" to "Un picnic romantic într-o locație frumoasă",
    "Ein schwerer Moment, den wir geschafft haben" to "Un moment dificil pe care l-am reușit",
    "Ein tolles Date im Freien unter dem Mondlicht" to "O întâlnire grozavă în aer liber sub lumina lunii",
    "Ein ungewöhnliches Gericht" to "Un fel de mâncare neobișnuit",
    "Ein zufälliger Schnappschuss" to "Un instantaneu aleatoriu",
    "Einander kennenlernen" to "Să ne cunoaștem",
    "Eine Autoreise" to "O călătorie",
    "Eine Brücke" to "Un pod",
    "Eine Date-Nacht unter den Sternen" to "O noapte de întâlnire sub stele",
    "Eine Million Dollar gewinnen" to "Câștigă un milion de dolari",
    "Eine Million Dollar verdienen" to "Câștigă un milion de dolari",
    "Eine Nacht in einem Club" to "O noapte într-un club",
    "Eine Schokoladenverkostung" to "O degustare de ciocolată",
    "Eine Wanderung mit Panoramablick machen" to "Faceți o drumeție cu vederi panoramice",
    "Eine Weinverkostung" to "O degustare de vinuri",
    "Eine gemeinsame Reise" to "O călătorie împreună",
    "Eine gemütliche Nacht zu Hause" to "O noapte confortabilă acasă",
    "Eine neue Sprache zu lernen ist einfach." to "Învățarea unei limbi noi este ușor.",
    "Einen Film anschauen" to "Urmăriți un film",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Nu am vorbit deloc unul cu celălalt timp de o lună",
    "Einen Tanzkurs besuchen" to "Ia un curs de dans",
    "Einen Vergnügungspark erkunden" to "Explorează un parc de distracții",
    "Einen Wellness-Tag" to "O zi de wellness",
    "Einen sehr emotionalen Partner haben" to "A avea un partener foarte emoțional",
    "Einen sehr logischen Partner haben" to "A avea un partener foarte logic",
    "Einer zahlt alles" to "O singură persoană plătește totul",
    "Einfach mehr Alltag" to "Pur și simplu mai multă viață de zi cu zi",
    "Einfach nebeneinander sein" to "Doar fiți unul lângă celălalt",
    "Einfach und intim" to "Simplu și intim",
    "Einige Dinge für dich behalten" to "Păstrează unele lucruri pentru tine",
    "Einmal" to "O dată",
    "Eins, das nur wir kennen" to "Unul pe care numai noi îl cunoaștem",
    "Englisch" to "engleză",
    "Entspannte Hängematte" to "Hamac relaxat",
    "Entspannung" to "Relaxare",
    "Erdbeere" to "Căpșuni",
    "Erfolgreich" to "Reușit",
    "Ergebnisse" to "Rezultate",
    "Erst bei sehr großen Summen" to "Numai pentru sume foarte mari",
    "Erst nur enge Freunde/Familie" to "La început numai prieteni apropiați/familie",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Mă enervează când partenerul meu durează prea mult să răspundă la mesaje.",
    "Essen & Genuss" to "Mâncare și plăcere",
    "Essensvorlieben" to "Preferințe alimentare",
    "Etwa eine Woche später, erst mal nur wir" to "Aproximativ o săptămână mai târziu, la început doar noi",
    "Etwas Neues ausprobieren" to "Încearcă ceva nou",
    "Etwas ganz anderes" to "Ceva complet diferit",
    "Etwas sehr Scharfes" to "Ceva foarte ascuțit",
    "Etwas, das ich selbst gern erfinde" to "Ceva ce îmi place să inventez eu",
    "Etwas, eine kleine Note wäre schön" to "Ceva, o mică notă ar fi bine",
    "Familie" to "Familie",
    "Familie/Freunde" to "Familie/Prieteni",
    "Familienmensch" to "Familie",
    "Farbedelstein" to "Piatră prețioasă colorată",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Reclamele TV sunt uneori interesante de vizionat.",
    "Fertig" to "Gata",
    "Fertig!" to "Gata!",
    "Feste Date-Nights" to "Nopți cu întâlnire fixă",
    "Feuerstelle" to "Foc",
    "Filigran & schlicht" to "Filigran și simplu",
    "Filme/Serien" to "Filme/serii",
    "Formuliere um..." to "Reformulați...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Reformulați schița într-un mod non-violent: observație, sentiment, nevoie, cerere.",
    "Frage hinzufügen" to "Adăugați o întrebare",
    "Fragen & Spiele" to "Întrebări și jocuri",
    "Fragen für jede Gelegenheit" to "Întrebări pentru fiecare ocazie",
    "Freizeitpark" to "Parc de distracții",
    "Freunde treffen" to "Faceți cunoștință cu prietenii",
    "Freundschaften mit Ex-Partnern sind okay." to "Prieteniile cu foștii sunt în regulă.",
    "Früh aufstehen" to "Trezește-te devreme",
    "Fußbodenheizung" to "Încălzire în pardoseală",
    "Führen wir getrennte oder gemeinsame Konten?" to "Avem conturi separate sau comune?",
    "Für dich empfohlen" to "Recomandat pentru tine",
    "Für die Zukunft" to "Pentru viitor",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Nu s-au găsit întrebări sau jocuri potrivite pentru această căutare.",
    "Für immer" to "Pentru totdeauna",
    "Fürsorglichkeit" to "Grijuliu",
    "GFK-Brücke" to "Pod GRP",
    "Galerie" to "Galerie",
    "Gar nicht, der Moment gehört uns" to "Deloc, momentul este al nostru",
    "Gar nichts tun" to "Nu face nimic",
    "Geduld" to "Răbdare",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Mergeți dimineața devreme pentru a vedea răsăritul",
    "Geht so" to "Merge așa",
    "Geister existieren wirklich." to "Fantomele chiar există.",
    "Gelassenheit" to "Seninătate",
    "Gelbgold" to "Aur galben",
    "Geld & Finanzen" to "Bani și finanțe",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Călătoriți împreună prin lume, explorați noi culturi și bucătării",
    "Gemeinsam ein Lego bauen" to "Construiți împreună un Lego",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Încercați împreună o nouă rețetă în bucătărie",
    "Gemeinsame Konten" to "Conturi comune",
    "Gemeinsame Nächte" to "Nopți împreună",
    "Gemeinsame Tage" to "Zile împreună",
    "Gemischt" to "Mixt",
    "Gemüsebeet" to "Petic de legume",
    "Gemütliche Feuerstelle" to "Semineu confortabil",
    "Gesprächsanreger" to "Începător de conversație",
    "Getrennte Konten" to "Conturi separate",
    "Getrennte Urlaube tun einer Beziehung gut." to "Vacanțele separate sunt bune pentru o relație.",
    "Gewächshaus" to "Sere",
    "Glasfassade" to "Fațadă din sticlă",
    "Gleichgültigkeit" to "Indiferență",
    "Glücklich und frei" to "Fericit și liber",
    "Gourmet Eis-Sorten" to "Soiuri de înghețată gourmet",
    "Gravur innen" to "Gravura în interior",
    "Grillplatz" to "Zona de grătar",
    "Groß & üppig" to "Mare și luxuriantă",
    "Große Familie" to "Familie mare",
    "Große Feier" to "Mare sărbătoare",
    "Große Fenster" to "Ferestre mari",
    "Große Fensterfront" to "Față de fereastră mare",
    "Großer Außenpool" to "Piscina mare în aer liber",
    "Großer Garten" to "Grădină mare",
    "Großer Stein" to "Piatră mare",
    "Größere Küche" to "Bucătărie mai mare",
    "Gutes Essen" to "Mâncare bună",
    "Habe ich" to "Am făcut-o",
    "Habe ich noch nie" to "N-am avut niciodată",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Ați descoperit diferențe surprinzătoare? Discutați de ce vă plac mai mult anumite opțiuni!",
    "Haus am See" to "Casă lângă lac",
    "Haus/Wohnung" to "Casă/apartament",
    "Hazelnut" to "Alune",
    "Heimkino" to "Home theater",
    "Herzhaft" to "Din plin",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Nu există nimic aici acum.\nSchimbați filtrul sau alegeți un alt subiect.",
    "Hilfe im Alltag" to "Ajutor în viața de zi cu zi",
    "Himbeere" to "Zmeura",
    "Hinzufügen" to "Adaugă",
    "Hobbys" to "Hobby-uri",
    "Hochzeitssträuße" to "Buchete de nuntă",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Hogwarts House Pride: Unde aparțineți?",
    "Home" to "Acasă",
    "Hot Tub" to "Cadă cu hidromasaj",
    "Humor" to "Umor",
    "Hund" to "Câine",
    "Hängematte" to "Hamac",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Doriți o scrisoare scrisă ca parte a propunerii?",
    "IKEA" to "IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Prefer plimbările romantice în parc decât să merg la cinema.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Nu am adormit niciodată într-un cinematograf.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Îmi place să descopăr noi hobby-uri sau activități împreună cu partenerul meu.",
    "Ich finde eine Alternative" to "Voi găsi o alternativă",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Îmi place să încerc restaurante noi cu partenerul meu, în loc să merg mereu în aceleași locuri.",
    "Ich habe noch nie" to "Nu am făcut-o niciodată",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Nu mi-a fost niciodată frică de un roller coaster și oricum m-am apucat de el.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Nu am cumpărat niciodată bilete Fast Pass pentru că eram nerăbdător.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Nu am anulat niciodată planurile de a sta acasă și de a viziona o emisiune TV.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Nu am așteptat niciodată scrisoarea mea de la Hogwarts.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Nu am spus niciodată că Slytherin nu a fost chiar atât de rău.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Nu am spus niciodată că sunt prea bătrân pentru filmele Disney (și că mi-am plăcut în secret).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Nu am doborât niciodată pe cineva cu un tanc albastru în Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Nu am plâns niciodată la un film Disney.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Nu mi-am acoperit niciodată ochii în timp ce mă uitam la un film de groază.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Nu am uitat niciodată să salvez un joc și am pierdut ore de progres.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "N-am părăsit niciodată camera în timpul unei scene jenante (factor cringe).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Nu am făcut niciodată o ipostază amuzantă în timp ce făceam o fotografie cu rollercoaster.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Nu am jucat niciodată până târziu în noapte și am regretat cât de obosit am fost a doua zi.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Nu am căutat niciodată pe google finalul unui film pentru că abia așteptam.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Nu m-am simțit niciodată ca pe un platou de filmare.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Nu am omis niciodată introducerea serialului meu preferat.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Nu am distribuit niciodată parola Netflix a nimănui altcuiva.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Nu am ascultat niciodată coloana sonoră a unui joc în timp ce lucram sau studiam.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Nu am dat niciodată vina pe controler când am pierdut.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Nu am aruncat niciodată tastatura sau controlerul de furie.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Nu am uitat niciodată de câteva zile hainele umede în mașina de spălat.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Nu am cheltuit niciodată bani reali pe articole cosmetice într-un joc.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Nu am condus niciodată o mașină într-o țară străină.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Nu am cântat niciodată un cântec Disney sub duș.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Nu am condus niciodată o mașină electrică.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Nu am făcut niciodată o fotografie cu o mascota din parc.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Nu am numit niciodată un animal de companie după un personaj de la Hogwarts.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Nu am scăpat niciodată floricelele de porumb într-un cinema și încă le-am mâncat.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Nu am folosit niciodată un citat din Maestrul Yoda din Războiul Stelelor în viața de zi cu zi.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Nu mi-am cumpărat niciodată un suvenir la un preț prea mare de la un parc tematic.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Nu am dat niciodată o recomandare de film pe care cealaltă persoană a considerat-o îngrozitoare.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Nu am văzut niciodată un Oscar în direct în miezul nopții.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Nu am anulat niciodată un serial pentru că ultimul sezon a fost atât de prost.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Nu m-am uitat niciodată cu exces la un sezon întreg dintr-un serial într-o singură zi.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Nu am învins niciodată un șef la prima încercare și m-am simțit ca un zeu.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Nu am găsit niciodată un răufăcător mai tare decât eroul.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Nu am recunoscut niciodată un personaj din Toy Story în propriile mele jucării.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Nu am creat niciodată un personaj într-un RPG exact ca mine.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Nu am mâncat niciodată un churro într-un parc tematic.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Nu am văzut niciodată un film Disney de trei ori la rând.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Nu am avut niciodată o melodie atrăgătoare Disney pentru o săptămână întreagă.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Nu am văzut niciodată un film doar din cauza unui anumit actor.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Nu am ascultat niciodată o coloană sonoră a unui film repetată ore întregi.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Nu am dezvăluit niciodată un spoiler de film și am regretat imediat.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Nu am găsit niciodată un prieten care să vorbească o altă limbă maternă.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Nu am avut niciodată un prieten care s-a mutat în altă țară.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Nu am făcut niciodată un maraton de film Harry Potter de Crăciun.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Nu am văzut niciodată un film Marvel până la sfârșit doar din cauza scenei post-credit.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Nu am enervat niciodată în mod intenționat un NPC (Personaj Non-Jucător).",
    "Ich habe noch nie einen Nachtzug genommen." to "Nu am luat niciodată un tren de noapte.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Nu am susținut niciodată un test online pentru a afla casa mea de la Hogwarts.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Nu am șters niciodată o postare pe rețelele sociale pentru că nu a primit suficiente aprecieri.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Nu am numit niciodată o zi la parcul tematic cea mai bună zi a anului.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Nu am vizitat niciodată un parc tematic și am stat acolo de dimineața până seara.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Nu am lăsat niciodată o călătorie cu Transformers sau Marvel complet fascinat.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Nu m-am înfuriat niciodată să renunț și să renunț la joc.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Nu am citit niciodată niciunul dintre marile volume Harry Potter.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Nu m-am bucurat niciodată de personajul meu preferat dintr-un serial.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Nu am visat niciodată să joc Quidditch.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Nu am căutat niciodată pe google în secret cum să rezolv un nivel greu.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Nu am sperat niciodată în secret că animalul meu de companie poate vorbi ca la Disney.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Nu l-am eliminat niciodată pe liderul piscinei din Sims.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Nu mi-am pierdut niciodată orientarea într-o călătorie cu simulator 3D.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Nu am jucat niciodată într-o echipă sportivă universitară.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Nu am așteptat niciodată la coadă mai mult de două ore pentru o singură atracție.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Nu mi-am udat niciodată obiectele de valoare într-o plimbare pe apă.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Nu m-am certat niciodată cu un prieten despre care casă este cea mai bună.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Nu m-am prefăcut niciodată că am puteri magice ca Elsa.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Nu am râs niciodată atât de tare încât să fi ratat o scenă importantă dintr-un film.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Nu am simțit niciodată atât de multă adrenalină încât să-mi fi dorit imediat să merg din nou.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Nu am încercat niciodată să cânt cu animale precum Alba ca Zăpada.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Nu am visat niciodată o excursie la Disneyland.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Nu am visat niciodată să merg la plimbare pe apă din Jurassic Park.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Nu am țipat niciodată cu voce tare la o sperietură sărită într-un joc.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Nu am plâns niciodată de finalul unei emisiuni TV.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Nu am... anulat niciodată o întâlnire pentru a sta acasă.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Nu am... reformulat niciodată un mesaj de 10 ori.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Nu m-am uitat niciodată în secret la telefonul mobil al partenerului meu.",
    "Ich habe noch nie!" to "Nu am făcut-o niciodată!",
    "Ich habe!" to "Am!",
    "Ich lache viel mit meinem Partner." to "Râd mult cu partenerul meu.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Îmi place să cunosc hobby-urile și interesele partenerului meu.",
    "Ich liebe es" to "Îmi place",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Îmi place să mă uit la filme cu partenerul meu pe care niciunul dintre noi nu le-a văzut până acum.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Îmi place să împărtășesc muzica mea preferată cu partenerul meu.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Nu am fost niciodată nevoit să alerg pentru a prinde un zbor de legătură.",
    "Ich plane gerne Dates mit meinem Partner." to "Îmi place să planific întâlniri cu partenerul meu.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Prioritizează petrecerea timpului cu partenerul meu chiar și atunci când sunt ocupat.",
    "Ich schreibe meinem Partner jeden Tag." to "Îi trimit un mesaj către partenerul meu în fiecare zi.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Îmi place să împărtășesc meme și glume cu partenerul meu.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Îmi place să împărtășesc toate detaliile zilei mele cu partenerul meu.",
    "Ich würde es nie tun" to "Nu aș face-o niciodată",
    "Ich übe noch" to "Încă exersez",
    "Ideen generieren" to "Generați idei",
    "Im Haushalt helfen" to "Ajutor prin casă",
    "In Chat einfügen" to "Adaugă la chat",
    "In Stille nebeneinander" to "În tăcere unul lângă altul",
    "In den Bergen" to "La munte",
    "In eine Bar gehen" to "Mergi la un bar",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Mergând la un bar de pe plajă pentru a vedea apusul",
    "In einem feinen Restaurant essen gehen" to "Mănânc într-un restaurant rafinat",
    "In einen Coffeeshop gehen" to "Mergi la o cafenea",
    "In einer Beziehung sollte man alles voneinander wissen." to "Într-o relație ar trebui să știți totul unul despre celălalt.",
    "Infinity-Pool" to "Piscina infinită",
    "Innenpool" to "Piscina interioara",
    "Intelligenz" to "Inteligență",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Să ai doar momente intime când partenerul tău le inițiază",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Cod de invitație: HRM-8731 · totul deblocat",
    "Island" to "Islanda",
    "Ist okay für mich" to "E în regulă cu mine",
    "Ist schon perfekt" to "Este perfect",
    "Ja, Traditionen einbinden" to "Da, încorporează tradițiile",
    "Ja, absolut" to "Da, absolut",
    "Ja, etwas zum Lesen und Aufbewahren" to "Da, ceva de citit și de păstrat",
    "Ja, genug" to "Da, suficient",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Da, într-un oraș sau o atracție interesantă",
    "Ja, in- und auswendig" to "Da, în interior și în exterior",
    "Ja, komplett überraschend" to "Da, complet surprinzător",
    "Ja, perfekt" to "Da, perfect",
    "Ja, sie gehören zur Familie!" to "Da, sunt familie!",
    "Ja, sofort teilen" to "Da, distribuie imediat",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Da, ne vom asigura că timpul în familie este o prioritate.",
    "Jacuzzi" to "Jacuzzi",
    "Jahr zusammen 🎉" to "an împreună 🎉",
    "Jahre zusammen 🎉" to "Ani împreună 🎉",
    "Jeder zahlt 50%" to "Toată lumea plătește 50%",
    "Junge" to "Băiat",
    "Kamin" to "Semineu",
    "Karriere & Erfolg" to "Carieră și succes",
    "Kategorien" to "Categorii",
    "Katze" to "Cat",
    "Keine Musik" to "Fără muzică",
    "Keine Party nötig, privat halten" to "Nu este nevoie de o petrecere, păstrați-o privată",
    "Keine Privatsphäre" to "Fără confidențialitate",
    "Keine Treffer gefunden" to "Nu s-au găsit potriviri",
    "Keiner" to "Niciuna",
    "Keiner von uns" to "Niciunul dintre noi",
    "Kennst du die Essensvorlieben deines Partners?" to "Cunoașteți preferințele alimentare ale partenerului dvs.?",
    "Kino" to "Cinema",
    "Kirchlich" to "Ecleziastic",
    "Klassisch Solitär" to "Solitaire clasic",
    "Klassisch gebunden" to "Legat clasic",
    "Klein & zart" to "Mic și delicat",
    "Kleine Geschenke" to "Mici cadouri",
    "Kleine Runde" to "Grup mic",
    "Kochen und Freunde einladen" to "Gătește și invită prieteni",
    "Kochkurs" to "Curs de gătit",
    "Kommt auf den Tag an" to "Depinde de zi",
    "Kommt darauf an" to "Depinde",
    "Kommt drauf an" to "Depinde",
    "Kommt mit" to "Vino cu mine",
    "Konzert" to "Concert",
    "Kräftige Farben" to "Culori puternice",
    "Kräuterbeet" to "Pat cu ierburi",
    "Kultur & Sehenswürdigkeiten" to "Cultură și obiective turistice",
    "Kuscheln" to "Imbratisari",
    "Kuss senden" to "Trimite un sărut",
    "Körperliche Annäherung" to "Abordare fizică",
    "Körperliche Nähe" to "Apropiere fizică",
    "Küche" to "Bucătărie",
    "Land" to "Țara",
    "Landhaus" to "Casă la țară",
    "Landhausstil" to "Stil casă la țară",
    "Lange wach bleiben" to "Stai până până târziu",
    "Lappland" to "Laponia",
    "Lappland, Finnland" to "Laponia, Finlanda",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Lasă-ți partenerul să te inspire să fii cel mai bun sine",
    "Lehne ab" to "Refuzați",
    "Leichtigkeit" to "Lejeritate",
    "Leidenschaft" to "Pasiune",
    "Liebe im Gleichgewicht" to "Dragoste în echilibru",
    "Liebe sie, macht mehr Spaß" to "Iubește-le, mai distracție",
    "Lieber durchgeplant oder spontan?" to "Ați prefera să fie planificat sau spontan?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Preferiți să aveți o seară liniștită în doi sau cu oameni?",
    "Lieber nicht" to "Mai bine nu",
    "Lieber vorher grob absprechen" to "Este mai bine să discutați despre lucrurile în prealabil",
    "Lokal einkaufen" to "Cumpărați local",
    "London" to "Londra",
    "London, England" to "Londra, Anglia",
    "Lügen" to "Minciuni",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Preferi o propunere publică sau privată?",
    "Malediven" to "Maldive",
    "Man sollte nie streitend einschlafen." to "Nu ar trebui să adormi niciodată certându-te.",
    "Mango Sorbet" to "Sorbet de mango",
    "Markant & breit" to "izbitor și larg",
    "Marken & Alltag" to "Mărci și viața de zi cu zi",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "Curte mediteraneană",
    "Mehr Unterstützung" to "Mai mult suport",
    "Mehr gemeinsame Zeit" to "Mai mult timp împreună",
    "Mehr zuhören" to "Ascultă mai mult",
    "Mehrgenerationenhaus" to "Casă cu mai multe generații",
    "Mein Arbeitsplatz" to "Locul meu de muncă",
    "Mein Partner" to "Partenerul meu",
    "Mich überraschen" to "Surprinde-mă",
    "Minimalistisches Interieur" to "Interior minimalist",
    "Missverständnisse" to "Neînțelegeri",
    "Mit Familie und engen Freunden" to "Cu familia și prietenii apropiați",
    "Mit Kompromissen" to "Cu compromisuri",
    "Mitgefühl" to "Compasiune",
    "Mittelweg mit besonderen Details" to "Un punct de mijloc cu detalii speciale",
    "Modern geometrisch" to "Geometric modern",
    "Moderne Grillstation" to "Stație modernă pentru grătar",
    "Moderner Name" to "Nume modern",
    "Moderner Solitär" to "Solitaire modern",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "Surprindeți momentul",
    "Momente" to "momente",
    "Monaco" to "Monaco",
    "Moralische Werte" to "Valori morale",
    "Museum" to "Muzeul",
    "Musik" to "Muzică",
    "Mut" to "Curaj",
    "Mädchen" to "Fete",
    "Möbelhaus" to "Magazin de mobilă",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Sigur vrei să părăsești testul? Progresul dvs. anterior rămâne salvat.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Ați dori ca animalele de companie să fie incluse în aplicație?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Doriți ca momentul să fie distribuit instantaneu pe rețelele sociale?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Este posibil să fie nevoie să facem economii",
    "Müssen es planen" to "Trebuie să o planificați",
    "Müssen sparen" to "Trebuie să salvați",
    "Nachricht an" to "Mesaj",
    "Name Partnerin" to "Numele partenerului",
    "Namen und Startdatum eurer Beziehung." to "Numele și data de început a relației tale.",
    "Natursteinfassade" to "Fațadă din piatră naturală",
    "Naturteich" to "Iaz natural",
    "Nein, einfach halten" to "Nu, ține-l",
    "Nein, erstmal privat halten" to "Nu, păstrați-l privat pentru moment",
    "Nein, lieber vor Ort" to "Nu, mai bine pe site",
    "Nein, modern halten" to "Nu, păstrează-l modern",
    "Nein, nur wir" to "Nu, doar noi",
    "Nein, zu ablenkend" to "Nu, prea distrag atenția",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Clădire nouă cu casă inteligentă",
    "Neubau mit Technik" to "Clădire nouă cu tehnologie",
    "Neue Liebe, neue Erfahrungen" to "Iubire nouă, experiențe noi",
    "Neues Hobby" to "Hobby nou",
    "Neues Spiel" to "Joc nou",
    "Neugier" to "Curiozitate",
    "New York" to "New York",
    "New York, USA" to "New York, SUA",
    "Nicht mein Fall" to "Nu ceașca mea de ceai",
    "Nicht nötig, lieber klassisch bleiben" to "Nu este necesar, este mai bine să rămâneți clasic",
    "Nichts — es passt so" to "Nimic - se potrivește",
    "Nie wieder Burger" to "Niciodată nu mai mulți burgeri",
    "Nie wieder Pizza" to "Niciodată să nu se mai pizza",
    "Niemand" to "Nimeni",
    "Niemand ohne Plan" to "Nimeni fără un plan",
    "Nike" to "Nike",
    "Nizza" to "Frumos",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Încă nu există momente.\nCaptură prima ta experiență 💞",
    "Nur bei wichtigen Themen" to "Numai pentru subiecte importante",
    "Nur wir beide" to "Doar noi doi",
    "Nähe & Intimität" to "Apropiere și intimitate",
    "Obstgarten" to "Livadă",
    "Oder" to "Or",
    "Offene Küche" to "Bucătărie deschisă",
    "Offene Wohnküche" to "Bucătărie/sufragerie deschisă",
    "Ohne Stein" to "Fără piatră",
    "Open End" to "Final deschis",
    "Outdoor-Küche" to "Bucătărie în aer liber",
    "Outdoor-Sofa" to "Canapea de exterior",
    "Outdoor-Whirlpool" to "Jacuzzi în aer liber",
    "Ovaler Diamant" to "Diamant oval",
    "Paar" to "Pereche",
    "Paar-Statistiken" to "Statistici de cuplu",
    "Paris" to "Paris",
    "Paris, Frankreich" to "Paris, Franța",
    "Partner" to "Partener",
    "Partner-Simulator" to "Simulator partener",
    "Partnerin" to "Partener",
    "Party Edition" to "Party Edition",
    "Party Edition II" to "Party Edition II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Se potrivește un animal în viața noastră de zi cu zi?",
    "Pasta" to "Paste",
    "Pastell" to "Pastel",
    "Penthouse mit Ausblick" to "Penthouse cu vedere",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pergola cu lounge",
    "Pfingstrosen" to "Bujori",
    "Pinguin" to "Pinguin",
    "Pistazie" to "Fistic",
    "Pizza" to "Pizza",
    "Pizzaofen" to "Cuptor pentru pizza",
    "Platin" to "Platină",
    "PlayStation" to "PlayStation",
    "Pool" to "Piscina",
    "Pop" to "Pop",
    "Prasselnder Kamin" to "Șemineu hohotitor",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Prințese, pirati și praf de zâne: test Disney",
    "Privater Innenhof" to "Curte privată",
    "Profil" to "Profil",
    "Profil bearbeiten" to "Editați profilul",
    "Prozentual nach Einkommen" to "Procent bazat pe venit",
    "Quiz verlassen" to "Renunță la test",
    "Quiz verlassen?" to "Lasă testul?",
    "Rausgehen in die Natur" to "Ieșiți în natură",
    "Reden vor ..." to "Vorbind cu...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Programați împreună întâlniri sau ore regulate",
    "Reisen" to "Călătorie",
    "Reiseziele" to "Destinații de călătorie",
    "Respektlosigkeit" to "Lipsa de respect",
    "Restaurant" to "Restaurant",
    "RnB / Soul" to "RnB / Suflet",
    "Rock" to "Rock",
    "Rom" to "Roma",
    "Rom, Italien" to "Roma, Italia",
    "Romantik" to "Romantism",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Gesturile romantice precum mesajele, notițele sau cadourile mă fac fericit.",
    "Romantische Stimmung" to "Dispoziție romantică",
    "Roségold" to "Aur roz",
    "Ruhig zu zweit" to "Liniște pentru doi",
    "Runder Diamant" to "Diamant rotund",
    "Salted Caramel" to "Caramel sărat",
    "Sammle Ideen..." to "Colectați idei...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Grecia",
    "Saphir" to "Safir",
    "Saunahaus" to "Casă saună",
    "Schickes Restaurant oder Hotel" to "Restaurant sau hotel șic",
    "Schlafzimmer" to "Dormitor",
    "Schließen" to "Închide",
    "Schmal & zart" to "Subțire și delicată",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Instantanee din povestea noastră de dragoste",
    "Schokolade" to "Ciocolată",
    "Schreib frei, was dir wirklich dazu einfällt." to "Scrieți liber ceea ce vă vine cu adevărat în minte.",
    "Schreibe deine eigene Antwort" to "Scrieți propriul răspuns",
    "Sehr gerne" to "Cu plăcere",
    "Sehr leicht" to "Foarte ușor",
    "Sehr wichtig — Fotos und Video" to "Foarte important — fotografii și videoclipuri",
    "Sehr wichtig, es sollte persönlich sein" to "Foarte important, ar trebui să fie personal",
    "Selbst kochen" to "Gătește-te singur",
    "Senden" to "Trimite",
    "Separate Küche" to "Bucătărie separată",
    "Serie schauen" to "Urmărește serialul",
    "Serienmarathon auf dem Sofa" to "Seria maraton pe canapea",
    "Sex & Liebe" to "Sex și dragoste",
    "Seychellen" to "Seychelles",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Putem acoperi toate costurile pentru un copil/mai mulți copii? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Ar trebui ca propunerea să fie o surpriză?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Aplicația ar trebui să conțină elemente culturale sau tradiționale?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Aplicația ar trebui să conțină elemente culturale sau tradiționale?",
    "Sommerhochzeit" to "Nunta de vara",
    "Sonnige Dachterrasse" to "Terasă însorită pe acoperiș",
    "Sowohl als auch" to "Atât și",
    "Spazieren" to "Fă o plimbare",
    "Spaß & Abenteuer" to "Distracție și aventură",
    "Speichern" to "Salvați",
    "Spiel bearbeiten" to "Editează jocul",
    "Spielbereich für Kinder" to "Zona de joacă pentru copii",
    "Spiele" to "Jocuri",
    "Spiele spielen und Spaß haben" to "Joacă jocuri și distrează-te",
    "Spontan" to "Spontan",
    "Sportplatz" to "Teren de sport",
    "Spotify" to "Spotify",
    "Sprache" to "Limba",
    "Stadt" to "Oraș",
    "Stadt oder Land — was ist uns wichtiger?" to "Oraș sau țară - ce este mai important pentru noi?",
    "Stadtvilla" to "Vila de oras",
    "Standesamt & Party" to "Oficiu registru și petrecere",
    "Statement-Ring" to "Inel pentru declarații",
    "Stilvolles Outdoor-Sofa" to "Canapea elegantă pentru exterior",
    "Stimme voll zu" to "Total de acord",
    "Stimmt" to "Corect",
    "Stimmt nicht" to "Nu este adevărat",
    "Stimmt, noch nie" to "Adevărat, niciodată",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Zi de plajă",
    "Streit über Haushalt" to "Litigiu asupra gospodăriei",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "În mod constant",
    "Suche schließen" to "Închide căutarea",
    "Suche zurücksetzen" to "Resetează căutarea",
    "Suche öffnen" to "Deschideți căutarea",
    "Suchergebnisse" to "Rezultatele căutării",
    "Sushi" to "Sushi",
    "Süß" to "Dulce",
    "Tage zusammen 💞" to "zile împreună 💞",
    "Tauche ins Unterbewusstsein" to "Scufundați-vă în subconștient",
    "Teile alle deine Hobbys mit deinem Partner" to "Împărtășește-ți partenerul tău toate hobby-urile",
    "Teils teils" to "Parțial parțial",
    "Testen" to "Test",
    "Themen" to "Subiecte",
    "Tiefe Gespräche" to "Conversații profunde",
    "Tiefgründige Gespräche führen" to "Aveți conversații profunde",
    "Tierpension" to "Pensiunea pentru animale",
    "Tiny House" to "Casă mică",
    "Tippen zum Auswählen & Scrollen" to "Atingeți pentru a selecta și derula",
    "Tippen zum Zuklappen" to "Atingeți pentru a restrânge",
    "Titel" to "Titlu",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Titlu, Categorie, Subiect, Etichete, Întrebări...",
    "Tokyo, Japan" to "Tokyo, Japonia",
    "Traditioneller Name" to "Nume tradițional",
    "Traumhaus Außenbereich" to "Zona exterioară a casei de vis",
    "Traumhochzeit" to "Nunta de vis",
    "Treffer" to "Lovitură",
    "Tägliche Aktivität" to "Activitate zilnică",
    "Umformulieren" to "Reformulați",
    "Unbeantwortet" to "Fără răspuns",
    "Unbeliebte Meinungen" to "Opinii nepopulare",
    "Universal Studios Genie oder Neuling?" to "Universal Studios geniu sau începător?",
    "Uns auseinanderzuleben" to "Să se despartă",
    "Unser Intimleben" to "Viața noastră intimă",
    "Unser Traumhaus" to "Casa noastră de vis",
    "Unser erstes Treffen" to "Prima noastră întâlnire",
    "Unsere Gesichter" to "Fețele noastre",
    "Unsere eigenen Träume" to "Propriile noastre vise",
    "Unsere nächste Reise" to "Următoarea noastră călătorie",
    "Unter 1000" to "Sub 1000",
    "Unter 1000 im Monat" to "Sub 1000 pe lună",
    "Unter 50€/Monat" to "Sub 50 EUR/lună",
    "Unter Leuten" to "Printre oameni",
    "Untreue" to "Infidelitate",
    "Urlaub" to "Vacanță",
    "Vanille" to "Vanilie",
    "Venedig" to "Veneția",
    "Venedig, Italien" to "Veneția, Italia",
    "Verbinde dich mit" to "Conectați-vă cu",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Conectați-vă la \${profile.partnerName} pentru a vedea răspunsul",
    "Verbindung" to "conexiune",
    "Verbringe die Feiertage mit deiner Familie" to "Petreceți vacanțele cu familia",
    "Verlobungsringe" to "Inele de logodnă",
    "Vertrautheit" to "Familiaritate",
    "Viel getrennt" to "Multă separare",
    "Vielleicht ein oder zwei" to "Poate unul sau doi",
    "Vielleicht, aber mündlich reicht" to "Poate, dar verbal este suficient",
    "Vielleicht, wenn es machbar ist" to "Poate, dacă este posibil",
    "Vielleicht, wenn es passt" to "Poate, dacă se potrivește",
    "Vintage Art déco" to "Vintage Art Deco",
    "Vintage verspielt" to "Vintage jucăuș",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Să fii prezentat de partenerul tău noile hobby-uri",
    "Vor dem Kauf eines Hauses besprechen" to "Discutați înainte de a cumpăra o casă",
    "Vor der Anschaffung eines Haustiers besprechen" to "Discutați înainte de a cumpăra un animal de companie",
    "Vor der gemeinsamen Reise besprechen" to "Discutați înainte de a călători împreună",
    "Vor nichts" to "Nimic",
    "Vorort" to "Suburbie",
    "Walnuss" to "Nuc",
    "Wandern" to "Drumeții",
    "Wann fühlst du dich mir am nächsten?" to "Când te simți cel mai aproape de mine?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Când te simți cel mai aproape fizic de mine?",
    "Was bedeutet Vertrauen für dich konkret?" to "Ce înseamnă încrederea în mod specific pentru tine?",
    "Was entspannt dich mehr?" to "Ce te relaxează mai mult?",
    "Was fehlt dir über die Distanz am meisten?" to "Ce îți lipsește cel mai mult la distanță?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Ce îți place cel mai mult la casa ta?",
    "Was hast du von deinem Partner gelernt?" to "Ce ai învățat de la partenerul tău?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Ce părere ai despre vizionarea de conținut erotic împreună?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Ce părere aveți despre recuzită (de exemplu, semne, baloane etc.)?",
    "Was ist das Wichtigste beim Antrag?" to "Care este cel mai important lucru când depuneți candidatura?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Care este cel mai important lucru pe care îl cauți într-o întâlnire sexuală?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Care este fotografia ta preferată cu noi? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Care este cea mai mare teamă a ta în legătură cu viața împreună?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Care este o mâncare pe care o iubești, dar partenerul tău nu poate înțelege?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Ce este un dealbreaker absolut pentru tine?",
    "Was ist für jeden von uns das absolute Highlight?" to "Care este punctul culminant absolut pentru fiecare dintre noi?",
    "Was ist passiert?" to "Ce sa întâmplat?",
    "Was macht einen Moment für dich romantisch?" to "Ce face un moment romantic pentru tine?",
    "Was magst du an deinem Partner am liebsten?" to "Ce îți place cel mai mult la partenerul tău?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Ce îți place mai mult: să te trezești devreme sau să stai până târziu?",
    "Was magst du lieber?" to "Care îți place mai mult?",
    "Was möchtest du eigentlich sagen?" to "Ce vrei să spui de fapt?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Ce ai vrea să facă partenerul tău mai des?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Ce se întâmplă cu animalul când călătorim?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Ce se va întâmpla cu copilul nostru când va crește?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Ce nu ar trebui să pierdem niciodată din vedere ca părinți?",
    "Was war dein schönster Moment mit mir bisher?" to "Care a fost cel mai bun moment al tău cu mine până acum?",
    "Was wir gegessen haben" to "Ce am mâncat",
    "Was wollt ihr nie vergessen?" to "Ce nu vrei să uiți niciodată?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Ce ar fi mai rău pentru tine: niciodată să nu se mai pizza sau să nu se mai facă burgeri?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Ce ți-ar plăcea cel mai mult să faci într-o zi împreună?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Ce ai schimba imediat dacă banii nu ar fi o problemă?",
    "Weiter" to "În continuare",
    "Weiter spielen" to "Continuă jocul",
    "Weiß ich noch nicht" to "Nu știu încă",
    "Weiße Rosen" to "Trandafiri albi",
    "Weißgold" to "Aur alb",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Ce calitate ar trebui să obțină cu siguranță copilul nostru de la noi?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Ce mediu ați dori pentru o propunere?",
    "Welcher Raum sagt am meisten über dich aus?" to "Care cameră spune cel mai mult despre tine?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Ce buget planificăm pentru alimente și veterinar?",
    "Welches Lied macht dich an? 🥵" to "Ce melodie te excită? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Care fotografie partajată este preferată?",
    "Wellnessbad" to "Baie de wellness",
    "Wenn es schwierig ist" to "Când lucrurile sunt dificile",
    "Wenn ich müde bin" to "Când sunt obosit",
    "Wenn wir uns lange umarmen" to "Când ne îmbrățișăm mult timp",
    "Wenn wir zusammen lachen" to "Când râdem împreună",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Cine decide mai repede ce să comande?",
    "Wer findet die besten Restaurants?" to "Cine găsește cele mai bune restaurante?",
    "Wer gibt mehr Herzlichkeit?" to "Cine dă mai multă căldură?",
    "Wer hat den besseren Musikgeschmack?" to "Cine are gusturi mai bune în muzică?",
    "Wer hängt mehr an seinen Eltern?" to "Cine este mai atașat de părinții lor?",
    "Wer ist besser organisiert?" to "Cine este mai bine organizat?",
    "Wer ist der Beste bei der Filmauswahl?" to "Cine este cel mai bun la alegerea filmelor?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Cine este cel mai bun la planificarea întâlnirilor romantice?",
    "Wer ist der beste Tänzer?" to "Cine este cel mai bun dansator?",
    "Wer ist romantischer?" to "Cine este mai romantic?",
    "Wer kocht besser?" to "Cine gătește mai bine?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Cine se ocupă de renovare și întreținere?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Cine observă mai repede când cealaltă persoană nu se simte bine?",
    "Wer sucht am Ende wirklich den Film aus?" to "Cine alege cu adevărat filmul până la urmă?",
    "Wer vergisst eher einen Jahrestag?" to "Cine este mai probabil să uite o aniversare?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Cine ar fi mai probabil să-și uite propriul nume în dimineața următoare?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Cine ar fi mai probabil să găsească a doua zi un videoclip despre care să nu știe nimic?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Cine ar prefera să petreacă noaptea pe canapeaua unui străin?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Cine ar fi mai probabil să adoarmă la o petrecere și să se trezească cu Sharpie pe față?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Cine ar fi mai probabil să alunece pe ringul de dans, dar să facă să pară o mișcare cool?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Cine este mai probabil să preia controlul asupra playlistului Spotify la o petrecere în casă?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Cine ar fi mai probabil să comande pizza pentru toată lumea la o petrecere și să o mănânce singur?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Cine are mai multe șanse să adoarmă primul la o petrecere?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Cine ar fi mai probabil să înceapă brusc să facă curățenie la o petrecere?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Cine ar fi mai probabil să pretindă că este complet treaz când este adevărat opusul?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Cine este mai probabil să cedeze primul într-o ceartă?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Cine este mai probabil să trișeze la un joc de băutură?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Cine ar fi mai probabil să atace bufetul și să ia în secret mâncare acasă?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Cine ar fi mai probabil să posteze cea mai jenantă fotografie a serii în povestea lor?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Cine ar fi mai probabil să-l enerveze pe DJ să-i ceară propria melodie preferată?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Cine ar fi mai probabil să cânte versurile unei melodii, dar cu convingere?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Cine ar fi mai probabil să comande cea mai scumpă băutură din meniu și să regrete?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Cine ar fi mai probabil să-i invite pe vecini dacă s-ar plânge de zgomot?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Cine ar lua prea în serios jocurile de petrecere (cum ar fi Beer Pong)?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Cine ar fi mai probabil să se împrietenească cu bouncers pentru a obține acces VIP?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Cine ar fi mai probabil să înceapă o bătălie spontană de karaoke?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Cine este mai probabil să deschidă o sticlă fără a folosi un deschizător de sticle?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Cine ar fi mai probabil să țină un discurs, chiar dacă absolut nimeni nu a întrebat?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Cine ar fi mai probabil să petreacă o oră în baie făcând selfie-uri?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Cine ar fi mai probabil să organizeze un spectacol de dans jenant și să-l sărbătorească?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Cine ar fi mai probabil să sune un fost partener după ce petrecerea se termină?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Cine ar fi mai probabil să jignească accidental un oaspete ciudat?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Cine ar fi mai probabil să părăsească petrecerea în secret fără să-și ia rămas bun?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Cine ar prefera să se joace cu animalul de companie al gazdei decât să vorbească cu oaspeții?",
    "Wer würde eher spontan eine Reise buchen?" to "Cine ar fi mai probabil să rezerve o călătorie spontan?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Cine ar fi mai probabil să aibă conversații profunde în bucătărie ore întregi?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Cine este mai probabil să bea accidental băutura altcuiva?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Cine ar fi mai probabil să doboare accidental o vază scumpă sau ceva fragil?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Cine ar fi mai probabil să încerce să amestece singur un cocktail complicat și să eșueze lamentabil?",
    "Wer würde eher zu spät kommen?" to "Cine este mai probabil să întârzie?",
    "Wer würde eher?" to "Cine ar prefera?",
    "Wer übernimmt die tägliche Versorgung?" to "Cine are grijă de îngrijirea zilnică?",
    "Werde so akzeptiert, wie du bist" to "Fii acceptat așa cum ești",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Vom avea suficient timp pentru copil/copii? ⏳",
    "Whirlpool" to "Cadă cu hidromasaj",
    "White Chocolate" to "Ciocolată albă",
    "Widgets" to "Widgeturi",
    "Wie fühlst du dich am meisten geliebt?" to "Cum te simți cel mai iubit?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Cum ne descurcăm cu diferite venituri?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Care este cel mai bun mod ca partenerul tău să inițieze sex cu tine?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Cum poate partenerul tău să fie un partener și mai bun pentru tine?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Cât timp după propunere vrei să sărbătorești cu alții?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Cât timp vrem să stăm acolo măcar?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Cât de ușor îți este să vorbești despre dorințe?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Cum vrei să arate viitorul nostru?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Cum arată duminica ta perfectă acasă?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Ce părere ai despre vorbele murdare în timpul sexului?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Cât credit ne putem permite în mod realist?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Cât timp vrem să petrecem separat?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Cât dorim să cheltuim în total?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Cum vom găsi timp pentru relația noastră odată ce va veni copilul?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Cât de important este pentru tine ca momentul să fie capturat?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Cât de important este pentru tine ca aplicația să reflecte hobby-urile sau interesele tale?",
    "Wie würdest du sie/ihn nennen?" to "Cum l-ai numi?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Care este modalitatea ta preferată de a arăta afecțiune în afara sexului?",
    "Wildblumen" to "Flori sălbatice",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Vrei o fată sau un băiat? 👶",
    "Wintergarten" to "Grădină de iarnă",
    "Winterhochzeit" to "Nunta de iarna",
    "Wir bestellen einfach beides" to "Pur și simplu le comandăm pe amândouă",
    "Wir brauchen ewig" to "Ne ia pentru totdeauna",
    "Wir einigen uns nie" to "Nu suntem niciodată de acord",
    "Wir entscheiden es gemeinsam" to "Ne hotărâm împreună",
    "Wir treffen uns in der Mitte" to "Ne întâlnim la mijloc",
    "Wir wechseln uns ab" to "Luăm pe rând",
    "Wird stressig" to "Devine stresant",
    "Wobei lachst du am meisten?" to "Ce te face să râzi cel mai mult?",
    "Wofür sparen wir gemeinsam?" to "Pentru ce economisim împreună?",
    "Wohnzimmer" to "Camera de zi",
    "Woran erinnerst du dich am lebhaftesten?" to "Ce vă amintiți cel mai viu?",
    "Worauf freust du dich bei uns am meisten?" to "Ce aștepți cel mai mult cu noi?",
    "Worte/Komplimente" to "Cuvinte/Complimente",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "De ce ți-e mai frică în relația noastră?",
    "Wünsche? z.B. günstig, draußen" to "Dorințe? de ex. ieftin, afara",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Ați prefera să vă propuneți în vacanță (care implică călătorii)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "Muzică YouTube",
    "Zeichne für mich" to "Desenează pentru mine",
    "Zeichne mich als Tier — welches wäre ich?" to "Desenează-mă ca pe un animal - care aș fi?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Atrageți-ne sentimentele unul față de celălalt ca simbol.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Desenați casa noastră de vis într-o singură linie. Care este cel mai izbitor lucru?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Desenează prima noastră întâlnire - ce trebuie să fie cu siguranță în imagine?",
    "Zeichnen" to "Desenează",
    "Zeit füreinander" to "Timp unul pentru celălalt",
    "Zeit, wenn das Baby schläft" to "Ora când copilul doarme",
    "Zelten gehen" to "Du-te la camping",
    "Zitrone" to "Lămâie",
    "Zu Hause, gemütlich und privat" to "Acasă, confortabil și privat",
    "Zu einem Picknick gehen" to "Merg la un picnic",
    "Zu einem ausgefallenen Abendessen gehen" to "Merg la o cină de lux",
    "Zu zweit reisen" to "Călătorește în cuplu",
    "Zuhause & Alltag" to "Acasă și viața de zi cu zi",
    "Zuhören" to "Ascultă",
    "Zurück" to "Înapoi",
    "Zusammen seit" to "Împreună de atunci",
    "Zusammen seit (TT.MM.JJJJ)" to "Împreună de la (ZZ.LL.AAAA)",
    "Zusammenziehen" to "Contract",
    "Zustimmen oder Ablehnen" to "De acord sau dezacord",
    "Zwei Kreise, die sich überschneiden" to "Două cercuri care se suprapun",
    "Zwei Stühle davor" to "Două scaune în fața lui",
    "Zärtlich sein" to "Fii tandru",
    "Öfter als ich zugebe" to "De mai multe ori decât recunosc",
    "Über 100€/Monat" to "Peste 100€/lună",
    "Über 2000 im Monat" to "Peste 2000 pe lună",
    "Über mich selbst" to "Despre mine",
    "Übernehmen" to "Aplicați",
    "Überraschend" to "Surprinzător",
    "Überraschung" to "Surpriză",
    "Überspringen" to "Omite",
    "Übertrieben und großartig" to "Peste top și minunat",
    "✎ Tippe, um zu antworten" to "✎ Atingeți pentru a răspunde",
    "✨ GFK-Brücke" to "✨ Pod GRP",
)

internal fun localizeRomanianDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_ROMANIAN_CONTENT)
