package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_RUSSIAN_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1–5 лет",
    "1000 - 1500 im Monat" to "1000 - 1500 в месяц",
    "1000 bis 3000" to "от 1000 до 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 в месяц",
    "3000 bis 5000" to "от 3000 до 5000",
    "5-10 Jahre" to "5–10 лет",
    "50-100€/Monat" to "50-100€/мес.",
    "Ab 100€" to "От 100€",
    "Ab 500€" to "От 500€",
    "Ab 50€" to "От 50€",
    "Ab und zu" to "Время от времени",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Сколько нам нужно потратить, прежде чем совершить покупку?",
    "Abbrechen" to "Отмена",
    "Abenteuer" to "Приключение",
    "Adidas" to "Адидас",
    "Aktivitäten" to "Действия",
    "Alle" to "Все",
    "Alle Pakete" to "Все пакеты",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Потеряйте всех своих друзей, кроме лучшего друга",
    "Alle intimen Momente selbst initiieren" to "Все интимные моменты инициируйте сами",
    "Alles davon" to "Всё это",
    "Alles, was noch kommt" to "Все, что будет дальше",
    "Alltagsroutine" to "Повседневная рутина",
    "Alltägliche Berührungen" to "Повседневные прикосновения",
    "Altbau mit Charme" to "Старое очаровательное здание",
    "Am Strand" to "На пляже",
    "Am liebsten alles zusammen" to "Желательно все вместе",
    "Am selben Tag mit Freunden/Familie" to "В тот же день с друзьями/семьей",
    "Amazon" to "Амазонка",
    "Amsterdam" to "Амстердам",
    "Amsterdam, Niederlande" to "Амстердам, Нидерланды",
    "An das Gefühl" to "Чувства",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "В общественном месте, где много зрителей.",
    "An einen Geruch" to "Запах",
    "An einen Song" to "Под песню",
    "An etwas, das ich gesagt habe" to "Что-то я сказал",
    "Analyse starten" to "Начать анализ",
    "Analysiere eure Muster..." to "Проанализируйте свои закономерности...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Анализируйте свои ответы и чаты по Готтману и GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Ананас в пицце очень вкусный.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Ответить с фотографией",
    "Antwortähnlichkeit" to "Сходство ответов",
    "App-Sprache auswählen" to "Выберите язык приложения",
    "Auf eine Bootsparty gehen" to "Иду на вечеринку на лодке",
    "Aufmerksamkeit" to "Внимание!",
    "Aufräumen und Projekte angehen" to "Наведите порядок и займитесь проектами",
    "Aufwärmen" to "Разминка",
    "Aufwärmen: Einander kennenlernen" to "Разминка: знакомство",
    "Aus dem Urlaub" to "Из отпуска",
    "Ausgefallener Name" to "Необычное имя",
    "Ausschlafen und faulenzen" to "Спите и бездельничайте",
    "Ausschlafen und nichts tun" to "Спи и ничего не делай.",
    "Aussehen" to "Внешний вид",
    "Auto" to "Авто",
    "Außenkamin" to "Уличный камин",
    "BEANTWORTE" to "ОТВЕТ",
    "Bali" to "Бали",
    "Bali, Indonesien" to "Бали, Индонезия",
    "Banane" to "Банан",
    "Beantwortet" to "Ответ получен",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Отвечайте на вопросы одновременно — ответы не будут видны, пока вы оба не закончите.",
    "Beantwortete Fragen" to "Ответы на вопросы",
    "Bearbeiten" to "Редактировать",
    "Bei Insider-Witzen" to "Для шуток",
    "Bei Memes" to "О мемах",
    "Bei einer spontanen Berührung" to "При спонтанном прикосновении",
    "Beide" to "Оба",
    "Beide gleich" to "Оба одинаковые",
    "Beide zusammen" to "Оба вместе",
    "Beide, aber wir tun so als ob nicht" to "И то, и другое, но мы притворяемся, что нет.",
    "Beides" to "Оба",
    "Beides wäre schlimm" to "И то и другое было бы плохо",
    "Beim Einschlafen nebeneinander" to "Засыпаем рядом друг с другом",
    "Beim Reden" to "Во время разговора",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Известные туристические места всегда разочаровывают.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Опишите нашу сексуальную жизнь с помощью смайликов.",
    "Besser kommunizieren" to "Лучше общайтесь",
    "Bessere Lage" to "Лучшее расположение",
    "Bestellen" to "Заказ",
    "Besuchte Länder" to "Посещенные страны",
    "Besuchte Städte" to "Посещенные города",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Вы предпочитаете экстравагантное предложение или что-то утонченное?",
    "Beziehung" to "Отношения",
    "Bibliothek" to "Библиотека",
    "Bin manchmal unsicher" to "Иногда я чувствую себя неуверенно",
    "Bist du ein Videospiel-Guru?" to "Вы гуру видеоигр?",
    "Blumenwiese" to "Цветочный луг",
    "Bunte Blumenwiese" to "Красочный цветочный луг",
    "Burger" to "Бургеры",
    "Burger King" to "Бургер Кинг",
    "Chat" to "Чат",
    "Coca-Cola" to "Кока-Кола",
    "Cookie Dough" to "Тесто для печенья",
    "Dachgarten mit Lounge" to "Сад на крыше с зоной отдыха",
    "Dachterrasse" to "Терраса на крыше",
    "Das Wetter an dem Tag" to "Погода в тот день",
    "Das erste Selfie" to "Первое селфи",
    "Das meiste weiß ich" to "Я знаю большую часть этого",
    "Das oder das?" to "То или это?",
    "Das tägliche Leben" to "Повседневная жизнь",
    "Dass Zusagen gehalten werden" to "Обещания выполняются",
    "Dass alles meinen Stil hat" to "Что все в моем стиле",
    "Dass ich alles erzählen kann" to "Что я могу всё рассказать",
    "Dass ich mich nicht sorgen muss" to "Что мне не о чем беспокоиться",
    "Dass wir ungestört sind" to "Что нас никто не беспокоит",
    "Dein Name" to "Ваше имя",
    "Deine Antwort..." to "Ваш ответ...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Ваши ответы сохранены. Как только Партнер завершит пакет, оба ответа будут видны вместе.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Ваши ответы сохранены. Как только \${profile.partnerName} завершит пакет, оба ответа будут видны вместе.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Сделайте ваши отношения авантюрными и спонтанными",
    "Deine Beziehung stabil und sicher machen" to "Сделайте ваши отношения стабильными и безопасными",
    "Deine eigene Antwort" to "Ваш собственный ответ",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Лучше поделиться своими сокровенными секретами со своим партнером.",
    "Deinen besten Freund verlieren" to "Потеря лучшего друга",
    "Denke an dich" to "Подумайте о себе",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Смотреть один и тот же фильм дважды — пустая трата времени.",
    "Der Blick nach draußen" to "Вид снаружи",
    "Der Garten" to "Сад",
    "Der Ort" to "Место",
    "Der Ring und die Geste" to "Кольцо и жест",
    "Der perfekte Heiratsantrag" to "Идеальное предложение руки и сердца",
    "Derjenige sein, der umarmt wird" to "Будь тем, кого обнимают",
    "Deutsch" to "немецкий",
    "Diamant" to "Алмаз",
    "Diamanten im Band" to "Бриллианты в группе",
    "Die Distanz" to "Расстояние",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Проведите каникулы с семьей вашего партнера",
    "Die Gemütlichkeit und Ruhe" to "Комфорт и покой",
    "Die Menschen, die darin wohnen" to "Люди, которые в нем живут",
    "Die Umgebung und Atmosphäre" to "Окружающая среда и атмосфера",
    "Die Worte und Emotionen" to "Слова и эмоции",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Невероятная развлекательная викторина",
    "Diejenige sein, die umarmt" to "Будь тем, кто обнимает",
    "Direkt ansprechen" to "Обращайтесь напрямую",
    "Diskussion" to "Обсуждение",
    "Diskutiere vor dem Kinderkriegen" to "Обсудите, прежде чем заводить детей",
    "Diskutiert eure Antworten" to "Обсудите свои ответы",
    "Disney" to "Дисней",
    "Doch, schon mal" to "Да, да",
    "Draußen mit der Natur als Kulisse" to "На улице на фоне природы",
    "Drei-Stein-Ring" to "Кольцо с тремя камнями",
    "Du bist dran" to "Ваша очередь",
    "Du fehlst mir" to "Я скучаю по тебе",
    "Dubai" to "Дубай",
    "Dubai, VAE" to "Дубай, ОАЭ",
    "Dunkles Design" to "Тёмная тема",
    "Durch Berührung" to "На ощупь",
    "Durch Worte" to "Через слова",
    "Durch Zeit zu zweit" to "Сквозь время вместе",
    "Durch kleine Gesten" to "Маленькими жестами",
    "Durchgeplant" to "Хорошо спланировано",
    "ERGEBNISSE" to "РЕЗУЛЬТАТЫ",
    "Egal, Hauptsache gesund" to "Как бы то ни было, главное – здоров",
    "Ehepaar Leben" to "Жизнь супружеской пары",
    "Eher knapp" to "Довольно близко",
    "Eher nicht" to "Не так уж и много.",
    "Eher schwer" to "Довольно сложно",
    "Eher schwierig" to "Довольно сложно",
    "Eher zu" to "Больше похоже",
    "Eifersucht ist ein Zeichen von Liebe." to "Ревность — признак любви.",
    "Eigenes Gemüsebeet" to "Свой огород",
    "Ein Abenteuer in einer neuen Stadt" to "Приключение в новом городе",
    "Ein Anker" to "Якорь",
    "Ein Balkon oder Garten" to "Балкон или сад.",
    "Ein Filmabend" to "Вечер кино",
    "Ein Harmony-Meilenstein eurer Liebe." to "Этап гармонии вашей любви.",
    "Ein Herz" to "Сердце",
    "Ein Herz an der Tür" to "Сердце у двери",
    "Ein Jahr lang eine Fernbeziehung führen" to "Иметь отношения на расстоянии в течение года.",
    "Ein Kindheitsessen" to "Детская еда",
    "Ein Live-Musik-Konzert besuchen" to "Посетите концерт живой музыки",
    "Ein Museum besuchen" to "Посетите музей",
    "Ein Spieleabend" to "Ночь игр",
    "Ein Spieleabend mit Freunden" to "Вечер игр с друзьями",
    "Ein Urlaubsfoto" to "Фотография из отпуска.",
    "Ein aktives Abenteuer" to "Активное приключение",
    "Ein entspannender Spa-Tag" to "Расслабляющий спа-день",
    "Ein ganz normaler Alltagstag" to "Совершенно обычный повседневный день",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Уютный вечер в доме во время грозы",
    "Ein gemütliches Date drinnen" to "Уютное свидание в помещении",
    "Ein lustiges Bild" to "Забавная картинка",
    "Ein paar Handyfotos reichen" to "Достаточно нескольких фотографий с мобильного телефона.",
    "Ein paar Stunden" to "Несколько часов",
    "Ein paar kulturelle Anklänge sind okay" to "Несколько отсылок к культуре вполне допустимы.",
    "Ein romantischer Abend" to "Романтический вечер",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Романтический ужин при свечах",
    "Ein romantisches Bild" to "Романтический образ",
    "Ein romantisches Picknick an einem schönen Ort" to "Романтический пикник в красивом месте",
    "Ein schwerer Moment, den wir geschafft haben" to "Сложный момент, с которым мы справились",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Отличное свидание на свежем воздухе под луной",
    "Ein ungewöhnliches Gericht" to "Необычное блюдо",
    "Ein zufälliger Schnappschuss" to "Случайный снимок",
    "Einander kennenlernen" to "Знакомство друг с другом",
    "Eine Autoreise" to "Путешествие",
    "Eine Brücke" to "Мост",
    "Eine Date-Nacht unter den Sternen" to "Свидание под звездами",
    "Eine Million Dollar gewinnen" to "Выиграйте миллион долларов",
    "Eine Million Dollar verdienen" to "Заработайте миллион долларов",
    "Eine Nacht in einem Club" to "Ночь в клубе",
    "Eine Schokoladenverkostung" to "Дегустация шоколада",
    "Eine Wanderung mit Panoramablick machen" to "Отправьтесь в поход с панорамным видом.",
    "Eine Weinverkostung" to "Дегустация вин",
    "Eine gemeinsame Reise" to "Совместное путешествие",
    "Eine gemütliche Nacht zu Hause" to "Уютный вечер дома",
    "Eine neue Sprache zu lernen ist einfach." to "Выучить новый язык легко.",
    "Einen Film anschauen" to "Посмотреть фильм",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Месяц вообще не разговариваем друг с другом.",
    "Einen Tanzkurs besuchen" to "Посетите уроки танцев",
    "Einen Vergnügungspark erkunden" to "Исследуйте парк развлечений",
    "Einen Wellness-Tag" to "День здоровья",
    "Einen sehr emotionalen Partner haben" to "Очень эмоциональный партнер.",
    "Einen sehr logischen Partner haben" to "Очень логичный партнер.",
    "Einer zahlt alles" to "Один человек платит за все",
    "Einfach mehr Alltag" to "Просто больше повседневной жизни",
    "Einfach nebeneinander sein" to "Просто будьте рядом друг с другом",
    "Einfach und intim" to "Просто и интимно",
    "Einige Dinge für dich behalten" to "Некоторые вещи оставьте при себе",
    "Einmal" to "Один раз",
    "Eins, das nur wir kennen" to "Тот, который знаем только мы",
    "Englisch" to "английский",
    "Entspannte Hängematte" to "Расслабленный гамак",
    "Entspannung" to "Расслабление",
    "Erdbeere" to "Клубника",
    "Erfolgreich" to "Успешно",
    "Ergebnisse" to "Результаты",
    "Erst bei sehr großen Summen" to "Только на очень большие суммы",
    "Erst nur enge Freunde/Familie" to "Сначала только близкие друзья/семья",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Меня раздражает, когда мой партнер слишком долго отвечает на сообщения.",
    "Essen & Genuss" to "Еда и развлечения",
    "Essensvorlieben" to "Предпочтения в еде",
    "Etwa eine Woche später, erst mal nur wir" to "Примерно через неделю, сначала только мы",
    "Etwas Neues ausprobieren" to "Попробуйте что-нибудь новое",
    "Etwas ganz anderes" to "Что-то совершенно другое",
    "Etwas sehr Scharfes" to "Что-то очень резкое",
    "Etwas, das ich selbst gern erfinde" to "Что-то, что я люблю изобретать сам",
    "Etwas, eine kleine Note wäre schön" to "Что-нибудь, было бы неплохо сделать небольшую заметку.",
    "Familie" to "Семья",
    "Familie/Freunde" to "Семья/Друзья",
    "Familienmensch" to "Семьянин",
    "Farbedelstein" to "Цветной драгоценный камень",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Телевизионную рекламу иногда интересно смотреть.",
    "Fertig" to "Готово.",
    "Fertig!" to "Готово!",
    "Feste Date-Nights" to "Фиксированные свидания по вечерам",
    "Feuerstelle" to "Место для костра",
    "Filigran & schlicht" to "Филигрань и простота",
    "Filme/Serien" to "Фильмы/сериалы",
    "Formuliere um..." to "Перефразируйте...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Перефразируйте свой черновик ненасильственным образом: наблюдение, чувство, потребность, просьба.",
    "Frage hinzufügen" to "Добавить вопрос",
    "Fragen & Spiele" to "Вопросы и игры",
    "Fragen für jede Gelegenheit" to "Вопросы на любой случай",
    "Freizeitpark" to "Парк развлечений",
    "Freunde treffen" to "Встречайтесь с друзьями",
    "Freundschaften mit Ex-Partnern sind okay." to "Дружба с бывшими — это нормально.",
    "Früh aufstehen" to "Вставайте рано",
    "Fußbodenheizung" to "Пол с подогревом",
    "Führen wir getrennte oder gemeinsame Konten?" to "Есть ли у нас отдельные или общие учетные записи?",
    "Für dich empfohlen" to "Рекомендуется для вас",
    "Für die Zukunft" to "На будущее",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "По этому запросу не найдено ни одного подходящего вопроса или игры.",
    "Für immer" to "Навсегда",
    "Fürsorglichkeit" to "Забота",
    "GFK-Brücke" to "Мост из стеклопластика",
    "Galerie" to "Галерея",
    "Gar nicht, der Moment gehört uns" to "Нисколько, момент наш.",
    "Gar nichts tun" to "Ничего не делайте",
    "Geduld" to "Терпение",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Идите рано утром, чтобы увидеть восход солнца.",
    "Geht so" to "Примерно так",
    "Geister existieren wirklich." to "Призраки действительно существуют.",
    "Gelassenheit" to "Спокойствие",
    "Gelbgold" to "Желтое золото",
    "Geld & Finanzen" to "Деньги и финансы",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Путешествуйте по миру вместе, изучайте новые культуры и кухни.",
    "Gemeinsam ein Lego bauen" to "Соберите LEGO вместе",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Попробуйте вместе новый рецепт на кухне.",
    "Gemeinsame Konten" to "Общие учетные записи",
    "Gemeinsame Nächte" to "Ночи вместе",
    "Gemeinsame Tage" to "Дни вместе",
    "Gemischt" to "Смешанный",
    "Gemüsebeet" to "Овощной участок",
    "Gemütliche Feuerstelle" to "Уютный камин",
    "Gesprächsanreger" to "Начало разговора",
    "Getrennte Konten" to "Отдельные учетные записи",
    "Getrennte Urlaube tun einer Beziehung gut." to "Раздельный отпуск полезен для отношений.",
    "Gewächshaus" to "Теплица",
    "Glasfassade" to "Стеклянный фасад",
    "Gleichgültigkeit" to "Безразличие",
    "Glücklich und frei" to "Счастлив и свободен",
    "Gourmet Eis-Sorten" to "Изысканные сорта мороженого",
    "Gravur innen" to "Гравировка внутри",
    "Grillplatz" to "Зона барбекю",
    "Groß & üppig" to "Большой и пышный",
    "Große Familie" to "Большая семья",
    "Große Feier" to "Большой праздник",
    "Große Fenster" to "Большие окна",
    "Große Fensterfront" to "Большое окно спереди",
    "Großer Außenpool" to "Большой открытый бассейн",
    "Großer Garten" to "Большой сад",
    "Großer Stein" to "Большой камень",
    "Größere Küche" to "Большая кухня",
    "Gutes Essen" to "Хорошая еда",
    "Habe ich" to "Я сделал",
    "Habe ich noch nie" to "У меня никогда не было",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Обнаружили ли вы какие-нибудь удивительные различия? Поговорите о том, почему определенные варианты вам нравятся больше!",
    "Haus am See" to "Дом у озера",
    "Haus/Wohnung" to "Дом/квартира",
    "Hazelnut" to "Фундук",
    "Heimkino" to "Домашний кинотеатр",
    "Herzhaft" to "Сытно",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Сейчас здесь ничего нет.\nИзмените фильтр или выберите другую тему.",
    "Hilfe im Alltag" to "Помощь в повседневной жизни",
    "Himbeere" to "Малиновый",
    "Hinzufügen" to "Добавить",
    "Hobbys" to "Хобби",
    "Hochzeitssträuße" to "Свадебные букеты",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Гордость факультета Хогвартса: где твое место?",
    "Home" to "Главная страница",
    "Hot Tub" to "Гидромассажная ванна",
    "Humor" to "юмор",
    "Hund" to "Собака",
    "Hängematte" to "гамак",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Хотите ли вы письменное письмо как часть заявления?",
    "IKEA" to "ИКЕА",
    "Ich" to "я",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Я предпочитаю романтические прогулки в парке походу в кино.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Я никогда не засыпал в кинотеатре.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Мне нравится открывать для себя новые хобби или занятия со своим партнером.",
    "Ich finde eine Alternative" to "Я найду альтернативу",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Мне нравится пробовать новые рестораны со своим партнером, вместо того, чтобы постоянно ходить в одни и те же места.",
    "Ich habe noch nie" to "Я никогда не",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Я никогда не боялся американских горок и все равно на них попал.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Я никогда не покупал билеты Fast Pass, потому что был нетерпелив.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Я никогда не отказывался от планов остаться дома и посмотреть телешоу.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Я так и не дождалась письма из Хогвартса.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Я никогда не говорил, что Слизерин на самом деле не так уж и плох.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Я никогда не говорил, что я слишком стар для фильмов Диснея (и втайне наслаждаюсь ими).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Я никогда намеренно не сбивал кого-то синим танком в Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Я никогда не плакала при просмотре фильмов Диснея.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Я никогда не закрывал глаза во время просмотра фильма ужасов.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Я никогда не забывал сохранить игру и не терял часы прогресса.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Я ни разу не выходил из комнаты во время неловкой сцены (фактор передергивания).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Я никогда не принимал смешных поз, фотографируясь с американских горок.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Я никогда не играл допоздна и не сожалел о том, насколько устал на следующий день.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Я никогда не искала в Google концовку фильма, потому что не могла дождаться.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "У меня никогда не было ощущения, будто я стою на съемочной площадке.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Я никогда не пропускал заставку моего любимого сериала.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Я никогда не передавал чужой пароль Netflix.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Я никогда не слушал саундтрек к игре во время работы или учебы.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Я никогда не винил контролёра в своих поражениях.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Я никогда в гневе не выбрасывал клавиатуру или контроллер.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Я ни разу не забывал мокрую одежду в стиральной машине на несколько дней.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Я никогда не тратил реальные деньги на косметические предметы в игре.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Я никогда не водил машину в чужой стране.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Я никогда не пел песни Диснея в душе.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Я никогда не водил электромобиль.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Я никогда не фотографировался с талисманом парка.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Я никогда не называл домашнее животное в честь персонажа Хогвартса.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Я никогда не ронял попкорн в кинотеатр и все равно его ел.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Я никогда не использовал цитату Мастера Йоды из «Звездных войн» в повседневной жизни.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Я никогда не покупал сувениры по завышенной цене в тематических парках.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Я никогда не давал рекомендаций по фильму, которые другой человек нашел бы ужасными.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Я никогда не смотрел церемонию вручения Оскара в прямом эфире посреди ночи.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Я никогда не отменял сериал из-за того, что последний сезон был настолько плохим.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Я никогда не смотрел целый сезон сериала за один день.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Я никогда не побеждал босса с первой попытки и чувствовал себя богом.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Я никогда не находил злодея круче героя.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Я никогда не узнавал персонажей «Истории игрушек» в своих игрушках.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Я никогда не создавал в ролевых играх такого персонажа, как я.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Я никогда не ел чурро в тематическом парке.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Я никогда не смотрел фильм Диснея три раза подряд.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "У меня никогда не было запоминающейся диснеевской мелодии за целую неделю.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Я никогда не смотрел фильм только из-за определенного актера.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Я никогда не слушал саундтрек к фильму на повторе часами.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Я ни разу не показывал спойлер к фильму и сразу же пожалел об этом.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Я никогда не находил друга, говорящего на другом родном языке.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "У меня никогда не было друга, который переехал бы в другую страну.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Я никогда не участвовал в марафоне фильмов о Гарри Поттере на Рождество.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Я никогда не смотрел фильмы Marvel до конца только из-за сцены после титров.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Я никогда намеренно не раздражал NPC (неигрового персонажа).",
    "Ich habe noch nie einen Nachtzug genommen." to "Я никогда не ездил на ночном поезде.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Я никогда не проходил онлайн-тест, чтобы узнать свой факультет в Хогвартсе.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Я никогда не удалял посты в социальных сетях из-за того, что они не набрали достаточно лайков.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Я никогда не называл день, проведенный в тематическом парке, лучшим днем ​​в году.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Я никогда не посещал тематические парки и оставался там с утра до ночи.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Я никогда не покидал аттракцион «Трансформеры» или «Марвел» полностью очарованным.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Я никогда не впадал в ярость и не выходил из игры.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Я никогда не читал ни одного большого тома о Гарри Поттере.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Я никогда не был в восторге от моего любимого персонажа в сериале.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Я никогда не мечтал играть в квиддич.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Я никогда тайно не гуглил, как пройти сложный уровень.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Я никогда втайне не надеялась, что мой питомец сможет говорить, как в Диснее.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Я никогда не удалял лидера пула в Sims.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Я ни разу не потерял ориентацию во время поездки на 3D-симуляторе.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Я никогда не играл в университетской спортивной команде.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Я никогда не стоял в очереди более двух часов ни на один аттракцион.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Я ни разу не промочил свои ценные вещи во время водной прогулки.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Я никогда не спорил с другом о том, какой дом лучше.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Я никогда не притворялась, что обладаю волшебными способностями, как Эльза.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Я никогда не смеялся так сильно, чтобы пропустить важную сцену в фильме.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Никогда еще я не чувствовал столько адреналина, чтобы мне сразу захотелось снова кататься.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Я никогда не пробовала петь с такими животными, как Белоснежка.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Я никогда не мечтал о поездке в Диснейленд.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Я никогда не мечтал покататься на водном аттракционе «Парк Юрского периода».",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Я никогда не кричал вслух из-за испуга в игре.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Я никогда не плакала из-за финала телешоу.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Я никогда... не отменял свидание, чтобы остаться дома.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Я никогда... не перефразировал сообщение 10 раз.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Я никогда... тайно не заглядывал в сотовый телефон моего партнера.",
    "Ich habe noch nie!" to "Никогда!",
    "Ich habe!" to "Есть!",
    "Ich lache viel mit meinem Partner." to "Я много смеюсь со своим партнером.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Мне нравится узнавать хобби и интересы моего партнера.",
    "Ich liebe es" to "Мне это нравится",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Я люблю смотреть со своим партнером фильмы, которые никто из нас раньше не смотрел.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Мне нравится делиться любимой музыкой со своим партнером.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Мне никогда не приходилось бежать, чтобы успеть на стыковочный рейс.",
    "Ich plane gerne Dates mit meinem Partner." to "Мне нравится планировать свидания со своим партнером.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Я уделяю приоритетное внимание проведению времени со своим партнером, даже когда я занят.",
    "Ich schreibe meinem Partner jeden Tag." to "Я пишу своему партнеру каждый день.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Мне нравится делиться мемами и шутками со своим партнером.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Мне нравится делиться всеми подробностями своего дня со своим партнером.",
    "Ich würde es nie tun" to "Я бы никогда этого не сделал",
    "Ich übe noch" to "Я все еще тренируюсь",
    "Ideen generieren" to "Генерируйте идеи",
    "Im Haushalt helfen" to "Помощь по дому",
    "In Chat einfügen" to "Добавить в чат",
    "In Stille nebeneinander" to "В тишине рядом друг с другом",
    "In den Bergen" to "В горах",
    "In eine Bar gehen" to "Сходить в бар",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Иду в пляжный бар, чтобы полюбоваться закатом.",
    "In einem feinen Restaurant essen gehen" to "Еда в прекрасном ресторане",
    "In einen Coffeeshop gehen" to "Сходите в кафе.",
    "In einer Beziehung sollte man alles voneinander wissen." to "В отношениях вы должны знать друг о друге все.",
    "Infinity-Pool" to "Бесконечный бассейн",
    "Innenpool" to "Крытый бассейн",
    "Intelligenz" to "Интеллект",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Интимные моменты бывают только тогда, когда их инициирует ваш партнер.",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Инвайт-код: HRM-8731 · все разблокировано",
    "Island" to "Исландия",
    "Ist okay für mich" to "Меня все устраивает",
    "Ist schon perfekt" to "Это идеально",
    "Ja, Traditionen einbinden" to "Да, учитывайте традиции",
    "Ja, absolut" to "Да, абсолютно",
    "Ja, etwas zum Lesen und Aufbewahren" to "Да, есть что почитать и сохранить",
    "Ja, genug" to "Да, достаточно",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Да, в интересном городе или достопримечательности.",
    "Ja, in- und auswendig" to "Да, внутри и снаружи.",
    "Ja, komplett überraschend" to "Да, совершенно удивительно.",
    "Ja, perfekt" to "Да, идеально",
    "Ja, sie gehören zur Familie!" to "Да, они семья!",
    "Ja, sofort teilen" to "Да, поделитесь немедленно",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Да, мы позаботимся о том, чтобы время с семьей было приоритетом.",
    "Jacuzzi" to "Джакузи",
    "Jahr zusammen 🎉" to "год вместе 🎉",
    "Jahre zusammen 🎉" to "Годы вместе 🎉",
    "Jeder zahlt 50%" to "Каждый платит 50%",
    "Junge" to "Мальчик",
    "Kamin" to "Камин",
    "Karriere & Erfolg" to "Карьера и успех",
    "Kategorien" to "Категории",
    "Katze" to "Кот",
    "Keine Musik" to "Нет музыки",
    "Keine Party nötig, privat halten" to "Не обязательно устраивать вечеринки, держите это в тайне",
    "Keine Privatsphäre" to "Никакой конфиденциальности",
    "Keine Treffer gefunden" to "Совпадений не найдено",
    "Keiner" to "Нет",
    "Keiner von uns" to "Никто из нас",
    "Kennst du die Essensvorlieben deines Partners?" to "Знаете ли вы гастрономические предпочтения вашего партнера?",
    "Kino" to "Кинотеатр",
    "Kirchlich" to "Церковный",
    "Klassisch Solitär" to "Классический пасьянс",
    "Klassisch gebunden" to "Классический переплет",
    "Klein & zart" to "Маленький и нежный",
    "Kleine Geschenke" to "Маленькие подарки",
    "Kleine Runde" to "Небольшая группа",
    "Kochen und Freunde einladen" to "Готовим и приглашаем друзей",
    "Kochkurs" to "Кулинарный мастер-класс",
    "Kommt auf den Tag an" to "Зависит от дня",
    "Kommt darauf an" to "Это зависит",
    "Kommt drauf an" to "Это зависит",
    "Kommt mit" to "Пойдем со мной",
    "Konzert" to "Концерт",
    "Kräftige Farben" to "Яркие цвета",
    "Kräuterbeet" to "Клумба с травами",
    "Kultur & Sehenswürdigkeiten" to "Культура и достопримечательности",
    "Kuscheln" to "Обнимаются",
    "Kuss senden" to "Пошли поцелуй",
    "Körperliche Annäherung" to "Физический подход",
    "Körperliche Nähe" to "Физическая близость",
    "Küche" to "Кухня",
    "Land" to "Страна",
    "Landhaus" to "Загородный дом",
    "Landhausstil" to "Стиль загородного дома",
    "Lange wach bleiben" to "Ложитесь спать поздно",
    "Lappland" to "Лапландия",
    "Lappland, Finnland" to "Лапландия, Финляндия",
    "Las Vegas" to "Лас-Вегас",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Пусть ваш партнер вдохновит вас стать лучше",
    "Lehne ab" to "Отказ",
    "Leichtigkeit" to "Легкость",
    "Leidenschaft" to "Страсть",
    "Liebe im Gleichgewicht" to "Любовь в равновесии",
    "Liebe sie, macht mehr Spaß" to "Любите их, веселее",
    "Lieber durchgeplant oder spontan?" to "Что бы вы предпочли: спланированное или спонтанное?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Вы бы предпочли провести тихий вечер вдвоем или в компании людей?",
    "Lieber nicht" to "Лучше нет",
    "Lieber vorher grob absprechen" to "Лучше заранее все примерно обсудить",
    "Lokal einkaufen" to "Делайте покупки локально",
    "London" to "Лондон",
    "London, England" to "Лондон, Англия",
    "Lügen" to "Ложь",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Вы предпочитаете публичное или частное предложение?",
    "Malediven" to "Мальдивы",
    "Man sollte nie streitend einschlafen." to "Никогда не следует засыпать во время спора.",
    "Mango Sorbet" to "Сорбет из манго",
    "Markant & breit" to "Эффектный и широкий",
    "Marken & Alltag" to "Бренды и повседневная жизнь",
    "McDonald’s" to "Макдональдс",
    "Mediterraner Innenhof" to "Средиземноморский дворик",
    "Mehr Unterstützung" to "Дополнительная поддержка",
    "Mehr gemeinsame Zeit" to "Больше времени вместе",
    "Mehr zuhören" to "Слушайте больше",
    "Mehrgenerationenhaus" to "Дом, в котором живут несколько поколений",
    "Mein Arbeitsplatz" to "Моё рабочее место",
    "Mein Partner" to "Мой партнер",
    "Mich überraschen" to "Удиви меня",
    "Minimalistisches Interieur" to "Минималистичный интерьер",
    "Missverständnisse" to "Недоразумения",
    "Mit Familie und engen Freunden" to "С семьей и близкими друзьями",
    "Mit Kompromissen" to "С компромиссами",
    "Mitgefühl" to "Сострадание",
    "Mittelweg mit besonderen Details" to "Золотая середина с особыми деталями",
    "Modern geometrisch" to "Современный геометрический",
    "Moderne Grillstation" to "Современная гриль-станция",
    "Moderner Name" to "Современное название",
    "Moderner Solitär" to "Современный пасьянс",
    "Moissanit" to "Муассанит",
    "Moment festhalten" to "Запечатлейте момент",
    "Momente" to "моменты",
    "Monaco" to "Монако",
    "Moralische Werte" to "Моральные ценности",
    "Museum" to "Музей",
    "Musik" to "Музыка",
    "Mut" to "Мужество",
    "Mädchen" to "Девушки",
    "Möbelhaus" to "Мебельный магазин",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Вы уверены, что хотите выйти из викторины? Ваш предыдущий прогресс останется сохраненным.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Хотите, чтобы в приложение были включены домашние животные?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Хотите, чтобы этот момент мгновенно был опубликован в социальных сетях?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Возможно, нам придется сэкономить.",
    "Müssen es planen" to "Нужно это спланировать",
    "Müssen sparen" to "Нужно сохранить",
    "Nachricht an" to "Сообщение",
    "Name Partnerin" to "Имя партнера",
    "Namen und Startdatum eurer Beziehung." to "Имена и дата начала ваших отношений.",
    "Natursteinfassade" to "Фасад из натурального камня",
    "Naturteich" to "Природный пруд",
    "Nein, einfach halten" to "Нет, просто подожди",
    "Nein, erstmal privat halten" to "Нет, пока держите это в тайне.",
    "Nein, lieber vor Ort" to "Нет, лучше на месте",
    "Nein, modern halten" to "Нет, пусть это будет современно.",
    "Nein, nur wir" to "Нет, только мы",
    "Nein, zu ablenkend" to "Нет, это слишком отвлекает.",
    "Netflix" to "Нетфликс",
    "Neubau mit Smart Home" to "Новостройка с умным домом",
    "Neubau mit Technik" to "Новое здание с технологиями",
    "Neue Liebe, neue Erfahrungen" to "Новая любовь, новые впечатления",
    "Neues Hobby" to "Новое хобби",
    "Neues Spiel" to "Новая игра",
    "Neugier" to "Любопытство",
    "New York" to "Нью-Йорк",
    "New York, USA" to "Нью-Йорк, США",
    "Nicht mein Fall" to "Не моя чашка чая",
    "Nicht nötig, lieber klassisch bleiben" to "Не обязательно, лучше оставаться классикой",
    "Nichts — es passt so" to "Ничего - подходит",
    "Nie wieder Burger" to "Никогда больше не гамбургеры",
    "Nie wieder Pizza" to "Никогда больше не пиццы",
    "Niemand" to "Никто",
    "Niemand ohne Plan" to "Никто без плана",
    "Nike" to "Найк",
    "Nizza" to "Красиво",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Пока нет моментов.\nЗапечатлейте свой первый опыт 💞",
    "Nur bei wichtigen Themen" to "Только для важных тем",
    "Nur wir beide" to "Только мы вдвоем",
    "Nähe & Intimität" to "Близость и интимность",
    "Obstgarten" to "Фруктовый сад",
    "Oder" to "Или",
    "Offene Küche" to "Открытая кухня",
    "Offene Wohnküche" to "Открытая кухня/гостиная",
    "Ohne Stein" to "Без камня",
    "Open End" to "Открытый финал",
    "Outdoor-Küche" to "Летняя кухня",
    "Outdoor-Sofa" to "Садовый диван",
    "Outdoor-Whirlpool" to "Гидромассажная ванна на открытом воздухе",
    "Ovaler Diamant" to "Овальный ромб",
    "Paar" to "Пара",
    "Paar-Statistiken" to "Статистика пары",
    "Paris" to "Париж",
    "Paris, Frankreich" to "Париж, Франция",
    "Partner" to "Партнер",
    "Partner-Simulator" to "Симулятор партнера",
    "Partnerin" to "Партнер",
    "Party Edition" to "Вечеринка",
    "Party Edition II" to "Вечеринка, издание II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Вписывается ли животное в нашу повседневную жизнь?",
    "Pasta" to "Макаронные изделия",
    "Pastell" to "Пастель",
    "Penthouse mit Ausblick" to "Пентхаус с видом",
    "Pepsi" to "Пепси",
    "Pergola mit Lounge" to "Пергола с гостиной",
    "Pfingstrosen" to "Пионы",
    "Pinguin" to "Пингвин",
    "Pistazie" to "Фисташковый",
    "Pizza" to "Пицца",
    "Pizzaofen" to "Печь для пиццы",
    "Platin" to "Платина",
    "PlayStation" to "PlayStation",
    "Pool" to "Пул",
    "Pop" to "Поп",
    "Prasselnder Kamin" to "Ревущий камин",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Принцессы, пираты и волшебная пыль: Дисней-викторина",
    "Privater Innenhof" to "Частный двор",
    "Profil" to "Профиль",
    "Profil bearbeiten" to "Редактировать профиль",
    "Prozentual nach Einkommen" to "Процент в зависимости от дохода",
    "Quiz verlassen" to "Выйти из викторины",
    "Quiz verlassen?" to "Выйти из викторины?",
    "Rausgehen in die Natur" to "Выйдите на природу",
    "Reden vor ..." to "Разговариваю с...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Планируйте регулярные свидания или времяпровождение вместе",
    "Reisen" to "Путешествие",
    "Reiseziele" to "Туристические направления",
    "Respektlosigkeit" to "Неуважение",
    "Restaurant" to "Ресторан",
    "RnB / Soul" to "RnB / Соул",
    "Rock" to "Рок",
    "Rom" to "Рим",
    "Rom, Italien" to "Рим, Италия",
    "Romantik" to "Романтика",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Романтические жесты, такие как сообщения, заметки или подарки, делают меня счастливым.",
    "Romantische Stimmung" to "Романтическое настроение",
    "Roségold" to "Розовое золото",
    "Ruhig zu zweit" to "Тихо для двоих",
    "Runder Diamant" to "Круглый ромб",
    "Salted Caramel" to "Соленая карамель",
    "Sammle Ideen..." to "Собирайте идеи...",
    "Santorini" to "Санторини",
    "Santorini, Griechenland" to "Санторини, Греция",
    "Saphir" to "Сапфир",
    "Saunahaus" to "Дом-сауна",
    "Schickes Restaurant oder Hotel" to "Шикарный ресторан или отель",
    "Schlafzimmer" to "Спальня",
    "Schließen" to "Закрыть",
    "Schmal & zart" to "Тонкий и нежный",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Кадры из нашей истории любви",
    "Schokolade" to "Шоколад",
    "Schreib frei, was dir wirklich dazu einfällt." to "Пишите свободно то, что действительно приходит на ум.",
    "Schreibe deine eigene Antwort" to "Напишите свой ответ",
    "Sehr gerne" to "Пожалуйста",
    "Sehr leicht" to "Очень легкий",
    "Sehr wichtig — Fotos und Video" to "Очень важно — фото и видео",
    "Sehr wichtig, es sollte persönlich sein" to "Очень важно, это должно быть личное",
    "Selbst kochen" to "Готовьте сами",
    "Senden" to "Отправить",
    "Separate Küche" to "Отдельная кухня",
    "Serie schauen" to "Посмотрите сериал",
    "Serienmarathon auf dem Sofa" to "Серийный марафон на диване",
    "Sex & Liebe" to "Секс и любовь",
    "Seychellen" to "Сейшельские острова",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Сможем ли мы покрыть все расходы на одного ребенка/нескольких детей? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Должно ли это предложение стать сюрпризом?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Должно ли приложение содержать культурные или традиционные элементы?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Должно ли приложение содержать культурные или традиционные элементы?",
    "Sommerhochzeit" to "Летняя свадьба",
    "Sonnige Dachterrasse" to "Солнечная терраса на крыше",
    "Sowohl als auch" to "И то и другое",
    "Spazieren" to "Прогуляйтесь",
    "Spaß & Abenteuer" to "Развлечения и приключения",
    "Speichern" to "Сохранить",
    "Spiel bearbeiten" to "Редактировать игру",
    "Spielbereich für Kinder" to "Игровая площадка для детей",
    "Spiele" to "Игры",
    "Spiele spielen und Spaß haben" to "Играйте в игры и получайте удовольствие",
    "Spontan" to "Спонтанно",
    "Sportplatz" to "Спортивная площадка",
    "Spotify" to "Spotify",
    "Sprache" to "Язык",
    "Stadt" to "Город",
    "Stadt oder Land — was ist uns wichtiger?" to "Город или страна – что для нас важнее?",
    "Stadtvilla" to "Городская вилла",
    "Standesamt & Party" to "ЗАГС и вечеринка",
    "Statement-Ring" to "Заявление о кольце",
    "Stilvolles Outdoor-Sofa" to "Стильный садовый диван",
    "Stimme voll zu" to "Полностью согласен",
    "Stimmt" to "Верно",
    "Stimmt nicht" to "Неправда.",
    "Stimmt, noch nie" to "Правда, никогда",
    "Stracciatella" to "Страчателла",
    "Strandtag" to "Пляжный день",
    "Streit über Haushalt" to "Спор по поводу домашнего хозяйства",
    "Studio Ghibli" to "Студия Ghibli",
    "Ständig" to "Постоянно",
    "Suche schließen" to "Закрыть поиск",
    "Suche zurücksetzen" to "Сбросить поиск",
    "Suche öffnen" to "Открыть поиск",
    "Suchergebnisse" to "Результаты поиска",
    "Sushi" to "Суши",
    "Süß" to "Мило",
    "Tage zusammen 💞" to "дни вместе 💞",
    "Tauche ins Unterbewusstsein" to "Погрузитесь в подсознание",
    "Teile alle deine Hobbys mit deinem Partner" to "Поделитесь всеми своими хобби со своим партнером.",
    "Teils teils" to "Частично частично",
    "Testen" to "Тест",
    "Themen" to "Темы",
    "Tiefe Gespräche" to "Глубокие разговоры",
    "Tiefgründige Gespräche führen" to "Ведите глубокие разговоры",
    "Tierpension" to "Пансионат для животных",
    "Tiny House" to "Крошечный дом",
    "Tippen zum Auswählen & Scrollen" to "Нажмите, чтобы выбрать и прокрутить",
    "Tippen zum Zuklappen" to "Нажмите, чтобы свернуть",
    "Titel" to "Название",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Название, Категория, Тема, Теги, Вопросы...",
    "Tokyo, Japan" to "Токио, Япония",
    "Traditioneller Name" to "Традиционное название",
    "Traumhaus Außenbereich" to "Открытая площадка дома мечты",
    "Traumhochzeit" to "Свадьба мечты",
    "Treffer" to "Хит",
    "Tägliche Aktivität" to "Ежедневная активность",
    "Umformulieren" to "Перефразировать",
    "Unbeantwortet" to "Без ответа",
    "Unbeliebte Meinungen" to "Непопулярные мнения",
    "Universal Studios Genie oder Neuling?" to "Гений или новичок Universal Studios?",
    "Uns auseinanderzuleben" to "Чтобы отдалиться друг от друга",
    "Unser Intimleben" to "Наша интимная жизнь",
    "Unser Traumhaus" to "Дом нашей мечты",
    "Unser erstes Treffen" to "Наша первая встреча",
    "Unsere Gesichter" to "Наши лица",
    "Unsere eigenen Träume" to "Наши собственные мечты",
    "Unsere nächste Reise" to "Наша следующая поездка",
    "Unter 1000" to "Менее 1000",
    "Unter 1000 im Monat" to "До 1000 в месяц",
    "Unter 50€/Monat" to "Менее 50 евро в месяц",
    "Unter Leuten" to "Среди людей",
    "Untreue" to "Неверность",
    "Urlaub" to "Отпуск",
    "Vanille" to "Ваниль",
    "Venedig" to "Венеция",
    "Venedig, Italien" to "Венеция, Италия",
    "Verbinde dich mit" to "Свяжитесь с",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Подключитесь к \${profile.partnerName}, чтобы увидеть ответ.",
    "Verbindung" to "Связь",
    "Verbringe die Feiertage mit deiner Familie" to "Проведите каникулы с семьей",
    "Verlobungsringe" to "Обручальные кольца",
    "Vertrautheit" to "знакомство",
    "Viel getrennt" to "Многое разделено",
    "Vielleicht ein oder zwei" to "Может быть, один или два",
    "Vielleicht, aber mündlich reicht" to "Возможно, но устно достаточно",
    "Vielleicht, wenn es machbar ist" to "Возможно, если это возможно",
    "Vielleicht, wenn es passt" to "Возможно, если подойдет",
    "Vintage Art déco" to "Винтажный арт-деко",
    "Vintage verspielt" to "Винтажная игривость",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Знакомство вашего партнера с новыми хобби",
    "Vor dem Kauf eines Hauses besprechen" to "Обсудите перед покупкой дома",
    "Vor der Anschaffung eines Haustiers besprechen" to "Обсудите перед покупкой домашнего животного",
    "Vor der gemeinsamen Reise besprechen" to "Обсудите перед совместной поездкой",
    "Vor nichts" to "Ничего",
    "Vorort" to "Пригород",
    "Walnuss" to "Орех",
    "Wandern" to "Походы",
    "Wann fühlst du dich mir am nächsten?" to "Когда ты чувствуешь себя ближе всего ко мне?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Когда ты чувствуешь себя физически ближе ко мне?",
    "Was bedeutet Vertrauen für dich konkret?" to "Что конкретно для вас означает доверие?",
    "Was entspannt dich mehr?" to "Что тебя больше расслабляет?",
    "Was fehlt dir über die Distanz am meisten?" to "Чего вам больше всего не хватает на расстоянии?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Что вам больше всего нравится в вашем доме?",
    "Was hast du von deinem Partner gelernt?" to "Чему вы научились у своего партнера?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Что вы думаете о совместном просмотре эротического контента?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Что вы думаете о реквизите (например, вывесках, воздушных шарах и т. д.)?",
    "Was ist das Wichtigste beim Antrag?" to "Что самое важное при подаче заявления?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Что для вас самое важное в сексуальном контакте?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Какая наша фотография тебе больше всего нравится? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Чего вы больше всего боитесь по поводу совместной жизни?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Какую еду вы любите, но не понимаете ваш партнер?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Что для вас является абсолютным препятствием?",
    "Was ist für jeden von uns das absolute Highlight?" to "Что является самым ярким событием для каждого из нас?",
    "Was ist passiert?" to "Что случилось?",
    "Was macht einen Moment für dich romantisch?" to "Что для вас делает момент романтичным?",
    "Was magst du an deinem Partner am liebsten?" to "Что вам больше всего нравится в вашем партнере?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Что тебе больше нравится: рано вставать или поздно ложиться?",
    "Was magst du lieber?" to "Что вам нравится больше?",
    "Was möchtest du eigentlich sagen?" to "Что ты вообще хочешь сказать?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Что бы вы хотели, чтобы ваш партнер делал чаще?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Что происходит с животным, когда мы путешествуем?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Что станет с нашим ребенком, когда он вырастет?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Что мы, родители, никогда не должны упускать из виду?",
    "Was war dein schönster Moment mit mir bisher?" to "Какой момент со мной был для тебя лучшим?",
    "Was wir gegessen haben" to "Что мы ели",
    "Was wollt ihr nie vergessen?" to "Что ты никогда не хочешь забывать?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Что для тебя было бы хуже: никогда больше не пиццы и не гамбургеров?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Чем бы вам больше всего хотелось заняться вместе в течение дня?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Что бы вы немедленно изменили, если бы деньги не были проблемой?",
    "Weiter" to "Далее",
    "Weiter spielen" to "Продолжить воспроизведение.",
    "Weiß ich noch nicht" to "Пока не знаю",
    "Weiße Rosen" to "Белые розы",
    "Weißgold" to "Белое золото",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Какое качество обязательно должен получить от нас наш ребенок?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Какую среду вы бы хотели видеть в своем предложении?",
    "Welcher Raum sagt am meisten über dich aus?" to "Какая комната больше всего говорит о вас?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Какой бюджет мы планируем на еду и ветеринара?",
    "Welches Lied macht dich an? 🥵" to "Какая песня тебя возбуждает? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Какая опубликованная фотография вам больше всего нравится?",
    "Wellnessbad" to "Оздоровительная ванна",
    "Wenn es schwierig ist" to "Когда все сложно",
    "Wenn ich müde bin" to "Когда я устал",
    "Wenn wir uns lange umarmen" to "Когда мы долго обнимаемся",
    "Wenn wir zusammen lachen" to "Когда мы смеемся вместе",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Кто быстрее решит, что заказать?",
    "Wer findet die besten Restaurants?" to "Кто находит лучшие рестораны?",
    "Wer gibt mehr Herzlichkeit?" to "Кто дарит больше тепла?",
    "Wer hat den besseren Musikgeschmack?" to "У кого лучший музыкальный вкус?",
    "Wer hängt mehr an seinen Eltern?" to "Кто больше привязан к своим родителям?",
    "Wer ist besser organisiert?" to "Кто лучше организован?",
    "Wer ist der Beste bei der Filmauswahl?" to "Кто лучше всех выбирает фильмы?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Кто лучше всех умеет планировать романтические свидания?",
    "Wer ist der beste Tänzer?" to "Кто лучший танцор?",
    "Wer ist romantischer?" to "Кто более романтичен?",
    "Wer kocht besser?" to "Кто готовит лучше?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Кто позаботится о ремонте и обслуживании?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Кто быстрее замечает, что другой человек плохо себя чувствует?",
    "Wer sucht am Ende wirklich den Film aus?" to "Кто в конечном итоге выберет фильм?",
    "Wer vergisst eher einen Jahrestag?" to "Кто чаще всего забывает годовщину?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Кто с большей вероятностью забудет свое имя на следующее утро?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Кто с большей вероятностью найдет на следующий день видео, о котором ничего не знает?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Кто предпочел бы провести ночь на чужом диване?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Кто с большей вероятностью заснет на вечеринке и проснется с маркером на лице?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Кто с большей вероятностью поскользнется на танцполе, но выставит это как крутой прием?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Кто с большей вероятностью возьмет под свой контроль плейлист Spotify на домашней вечеринке?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Кто с большей вероятностью закажет пиццу для всех на вечеринке и съест ее сам?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Кто чаще всего засыпает первым на вечеринке?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Кто с большей вероятностью вдруг начнет убираться на вечеринке?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Кто с большей вероятностью будет утверждать, что он совершенно трезв, когда на самом деле верно обратное?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Кто с большей вероятностью уступит в споре первым?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Кто чаще всего жульничает в игре с выпивкой?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Кто с большей вероятностью ворвется в буфет и тайно заберет еду домой?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Кто с большей вероятностью опубликует в своей истории самую неловкую фотографию вечера?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Кто с большей вероятностью будет раздражать диджея, требуя свою любимую песню?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Кто с большей вероятностью споет текст песни фальшиво, но убедительно?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Кто с большей вероятностью закажет самый дорогой напиток в меню и пожалеет об этом?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Кто с большей вероятностью пригласит к себе соседей, если они жалуются на шум?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Кто будет воспринимать игры для вечеринок (например, пивной понг) слишком серьезно?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Кто с большей вероятностью подружится с вышибалами, чтобы получить VIP-доступ?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Кто с большей вероятностью начнет спонтанную битву в караоке?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Кто с большей вероятностью откроет бутылку без открывалки?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Кто с большей вероятностью произнесет речь, даже если абсолютно никто об этом не спрашивает?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Кто с большей вероятностью проведет час в ванной, делая селфи?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Кто с большей вероятностью устроит смущающее танцевальное представление и отпразднует его?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Кто с большей вероятностью позвонит бывшему партнеру после окончания вечеринки?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Кто с большей вероятностью случайно обидит незнакомого гостя?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Кто с большей вероятностью тайно покинет вечеринку, не попрощавшись?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Кто предпочтет поиграть с питомцем хозяина, чем поговорить с гостями?",
    "Wer würde eher spontan eine Reise buchen?" to "Кто с большей вероятностью забронирует поездку спонтанно?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Кто с большей вероятностью будет часами вести глубокие разговоры на кухне?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Кто с большей вероятностью случайно выпьет чужой напиток?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Кто с большей вероятностью случайно опрокинет дорогую вазу или что-нибудь хрупкое?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Кто с большей вероятностью попытается самостоятельно приготовить сложный коктейль и потерпит неудачу?",
    "Wer würde eher zu spät kommen?" to "Кто чаще опаздывает?",
    "Wer würde eher?" to "Кто бы предпочел?",
    "Wer übernimmt die tägliche Versorgung?" to "Кто осуществляет ежедневный уход?",
    "Werde so akzeptiert, wie du bist" to "Будьте приняты такими, какие вы есть",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Хватит ли нам времени на ребенка/детей? ⏳",
    "Whirlpool" to "Гидромассажная ванна",
    "White Chocolate" to "Белый шоколад",
    "Widgets" to "Виджеты",
    "Wie fühlst du dich am meisten geliebt?" to "Как вы чувствуете себя наиболее любимым?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Как мы относимся к разным доходам?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Как лучше всего вашему партнеру начать с вами секс?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Как ваш партнер может стать для вас еще лучшим партнером?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Через какое время после предложения вы хотите отпраздновать это с другими?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Как долго мы хотим там оставаться?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Насколько легко вам говорить о желаниях?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Каким вы хотите, чтобы наше будущее выглядело?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Как выглядит ваше идеальное воскресенье дома?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Как вы относитесь к грязным разговорам во время секса?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Какой кредит мы реально можем себе позволить?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Сколько времени мы хотим проводить врозь?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Сколько всего мы готовы потратить?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Как мы найдем время для наших отношений, когда родится ребенок?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Насколько важно для вас, чтобы момент был запечатлен?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Насколько важно для вас, чтобы приложение отражало ваши хобби или интересы?",
    "Wie würdest du sie/ihn nennen?" to "Как бы вы его/ее назвали?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Какой ваш любимый способ проявить свою привязанность помимо секса?",
    "Wildblumen" to "Полевые цветы",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Ты хочешь девочку или мальчика? 👶",
    "Wintergarten" to "Зимний сад",
    "Winterhochzeit" to "Зимняя свадьба",
    "Wir bestellen einfach beides" to "Мы просто заказываем оба",
    "Wir brauchen ewig" to "Это займет у нас вечность",
    "Wir einigen uns nie" to "Мы никогда не соглашаемся",
    "Wir entscheiden es gemeinsam" to "Решаем вместе",
    "Wir treffen uns in der Mitte" to "Мы встречаемся посередине.",
    "Wir wechseln uns ab" to "Мы по очереди",
    "Wird stressig" to "Становится напряженным",
    "Wobei lachst du am meisten?" to "Что заставляет вас смеяться больше всего?",
    "Wofür sparen wir gemeinsam?" to "На что мы копим вместе?",
    "Wohnzimmer" to "Гостиная",
    "Woran erinnerst du dich am lebhaftesten?" to "Что вам запомнилось больше всего?",
    "Worauf freust du dich bei uns am meisten?" to "Чего вы больше всего ждете от нас?",
    "Worte/Komplimente" to "Слова/Комплименты",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Чего ты больше всего боишься в наших отношениях?",
    "Wünsche? z.B. günstig, draußen" to "Пожелания? например дешево, снаружи",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Вы бы предпочли сделать предложение в отпуске (включая путешествие)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "Музыка на YouTube",
    "Zeichne für mich" to "Нарисуй для меня",
    "Zeichne mich als Tier — welches wäre ich?" to "Нарисуй меня в виде животного – каким бы я был?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Нарисуйте наши чувства друг к другу как символ.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Нарисуйте дом нашей мечты в одну линию. Что самое поразительное?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Нарисуйте наше первое свидание – что обязательно должно быть на картинке?",
    "Zeichnen" to "Розыгрыш",
    "Zeit füreinander" to "Время друг для друга",
    "Zeit, wenn das Baby schläft" to "Время, когда ребенок спит",
    "Zelten gehen" to "Отправьтесь в поход",
    "Zitrone" to "Лимон",
    "Zu Hause, gemütlich und privat" to "Дома, уютно и приватно",
    "Zu einem Picknick gehen" to "Собираюсь на пикник",
    "Zu einem ausgefallenen Abendessen gehen" to "Иду на изысканный ужин",
    "Zu zweit reisen" to "Путешествуйте вдвоем",
    "Zuhause & Alltag" to "Дом и повседневная жизнь",
    "Zuhören" to "Слушай",
    "Zurück" to "Назад",
    "Zusammen seit" to "Вместе с тех пор",
    "Zusammen seit (TT.MM.JJJJ)" to "Вместе с (ДД.ММ.ГГГГ)",
    "Zusammenziehen" to "Контракт",
    "Zustimmen oder Ablehnen" to "Согласен или не согласен",
    "Zwei Kreise, die sich überschneiden" to "Два перекрывающихся круга",
    "Zwei Stühle davor" to "Перед ним два стула.",
    "Zärtlich sein" to "Будьте нежны",
    "Öfter als ich zugebe" to "Больше раз, чем я признаю",
    "Über 100€/Monat" to "Более 100€/месяц",
    "Über 2000 im Monat" to "Более 2000 в месяц",
    "Über mich selbst" to "О себе",
    "Übernehmen" to "Применить",
    "Überraschend" to "Удивительно",
    "Überraschung" to "Сюрприз",
    "Überspringen" to "Пропустить",
    "Übertrieben und großartig" to "Невероятно и потрясающе",
    "✎ Tippe, um zu antworten" to "✎ Нажмите, чтобы ответить",
    "✨ GFK-Brücke" to "✨ Мост из стеклопластика",
)

internal fun localizeRussianDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_RUSSIAN_CONTENT)
