package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_SERBIAN_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 година",
    "1000 - 1500 im Monat" to "1000 - 1500 месечно",
    "1000 bis 3000" to "1000 до 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 месечно",
    "3000 bis 5000" to "3000 до 5000",
    "5-10 Jahre" to "5-10 година",
    "50-100€/Monat" to "50-100€/месец",
    "Ab 100€" to "Од 100€",
    "Ab 500€" to "Од 500€",
    "Ab 50€" to "Од 50€",
    "Ab und zu" to "Ту и тамо",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "О коликој цени говоримо пре куповине?",
    "Abbrechen" to "Откажи",
    "Abenteuer" to "авантура",
    "Adidas" to "Адидас",
    "Aktivitäten" to "Активности",
    "Alle" to "Све",
    "Alle Pakete" to "Сви пакети",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Изгубите све своје пријатеље осим најбољег пријатеља",
    "Alle intimen Momente selbst initiieren" to "Започните сами све интимне тренутке",
    "Alles davon" to "Све то",
    "Alles, was noch kommt" to "Све што долази",
    "Alltagsroutine" to "Свакодневна рутина",
    "Alltägliche Berührungen" to "Свакодневни додири",
    "Altbau mit Charme" to "Стара зграда са шармом",
    "Am Strand" to "На плажи",
    "Am liebsten alles zusammen" to "По могућству све заједно",
    "Am selben Tag mit Freunden/Familie" to "Исти дан са пријатељима/породицом",
    "Amazon" to "Амазон",
    "Amsterdam" to "Амстердам",
    "Amsterdam, Niederlande" to "Амстердам, Холандија",
    "An das Gefühl" to "Од осећаја",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "На јавном месту са много гледалаца",
    "An einen Geruch" to "Од мириса",
    "An einen Song" to "Од песме",
    "An etwas, das ich gesagt habe" to "О нечему што сам рекао",
    "Analyse starten" to "Започните анализу",
    "Analysiere eure Muster..." to "Анализирајте своје обрасце...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Анализирајте своје одговоре и ћаскања према Готтману и ГФК-у.",
    "Ananas auf der Pizza schmeckt köstlich." to "Ананас на пици је укусан.",
    "Android" to "Андроид",
    "Antwort mit einem Foto" to "Одговорите фотографијом",
    "Antwortähnlichkeit" to "Сличност одговора",
    "App-Sprache auswählen" to "Изаберите језик апликације",
    "Auf eine Bootsparty gehen" to "Иди на забаву бродом",
    "Aufmerksamkeit" to "Пажња",
    "Aufräumen und Projekte angehen" to "Очистите и позабавите се пројектима",
    "Aufwärmen" to "Загрејте се",
    "Aufwärmen: Einander kennenlernen" to "Загрејте се: упознавање",
    "Aus dem Urlaub" to "Са одмора",
    "Ausgefallener Name" to "Фанци наме",
    "Ausschlafen und faulenzen" to "Спавајте и ленчарите",
    "Ausschlafen und nichts tun" to "Спавај и не ради ништа",
    "Aussehen" to "Погледај",
    "Auto" to "ауто",
    "Außenkamin" to "Вањски камин",
    "BEANTWORTE" to "ОДГОВОР",
    "Bali" to "Бали",
    "Bali, Indonesien" to "Бали, Индонезија",
    "Banane" to "банана",
    "Beantwortet" to "Одговорио",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Одговарајте на питања у исто време — одговори неће бити видљиви док обоје не завршите.",
    "Beantwortete Fragen" to "Одговорио на питања",
    "Bearbeiten" to "Уреди",
    "Bei Insider-Witzen" to "Са унутрашњим шалама",
    "Bei Memes" to "У мемовима",
    "Bei einer spontanen Berührung" to "Са спонтаним додиром",
    "Beide" to "И једно и друго",
    "Beide gleich" to "И једно и друго исто",
    "Beide zusammen" to "Обојица заједно",
    "Beide, aber wir tun so als ob nicht" to "И једно и друго, али ми се претварамо да нисмо",
    "Beides" to "И једно и друго",
    "Beides wäre schlimm" to "И једно и друго би било лоше",
    "Beim Einschlafen nebeneinander" to "Заспати једно поред другог",
    "Beim Reden" to "Док причам",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Позната туристичка места су увек разочарање.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Опишите наш сексуални живот помоћу емоџија.",
    "Besser kommunizieren" to "Боље комуницирајте",
    "Bessere Lage" to "Боља локација",
    "Bestellen" to "Ред",
    "Besuchte Länder" to "Посећене земље",
    "Besuchte Städte" to "Посећени градови",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Да ли више волите екстравагантан предлог или нешто суптилно?",
    "Beziehung" to "Однос",
    "Bibliothek" to "библиотека",
    "Bin manchmal unsicher" to "Понекад сам несигуран",
    "Bist du ein Videospiel-Guru?" to "Да ли сте гуру видео игара?",
    "Blumenwiese" to "Цветна ливада",
    "Bunte Blumenwiese" to "Шарена цветна ливада",
    "Burger" to "Грађани",
    "Burger King" to "Бургер Кинг",
    "Chat" to "Ћаскање",
    "Coca-Cola" to "Цоца Цола",
    "Cookie Dough" to "Тесто за колаче",
    "Dachgarten mit Lounge" to "Кровни врт са дневним боравком",
    "Dachterrasse" to "Кровна тераса",
    "Das Wetter an dem Tag" to "Време тог дана",
    "Das erste Selfie" to "Први селфи",
    "Das meiste weiß ich" to "Знам већину тога",
    "Das oder das?" to "Ово или оно?",
    "Das tägliche Leben" to "Свакодневни живот",
    "Dass Zusagen gehalten werden" to "Да се ​​обећања држе",
    "Dass alles meinen Stil hat" to "Да све има мој стил",
    "Dass ich alles erzählen kann" to "Да могу све да кажем",
    "Dass ich mich nicht sorgen muss" to "Да не морам да бринем",
    "Dass wir ungestört sind" to "Да смо неометани",
    "Dein Name" to "Твоје име",
    "Deine Antwort..." to "Ваш одговор...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Ваши одговори су сачувани. Чим Партнер заврши пакет, оба одговора ће бити видљива заједно.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Ваши одговори су сачувани. Када \${profile.partnerName} доврши пакет, оба одговора ће бити видљива заједно.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Нека ваш однос буде авантуристички и спонтан",
    "Deine Beziehung stabil und sicher machen" to "Учините своју везу стабилном и сигурном",
    "Deine eigene Antwort" to "Ваш сопствени одговор",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Радије поделите своје најдубље тајне са својим партнером",
    "Deinen besten Freund verlieren" to "Изгубити свог најбољег пријатеља",
    "Denke an dich" to "Мисли о себи",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Гледање истог филма двапут је губљење времена.",
    "Der Blick nach draußen" to "Поглед споља",
    "Der Garten" to "Башту",
    "Der Ort" to "Место",
    "Der Ring und die Geste" to "Прстен и гест",
    "Der perfekte Heiratsantrag" to "Савршена понуда за брак",
    "Derjenige sein, der umarmt wird" to "Буди онај кога грли",
    "Deutsch" to "немачки",
    "Diamant" to "дијамант",
    "Diamanten im Band" to "Дијаманти у бенду",
    "Die Distanz" to "Удаљеност",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Проведите празнике са породицом свог партнера",
    "Die Gemütlichkeit und Ruhe" to "Удобност и мир",
    "Die Menschen, die darin wohnen" to "Људи који тамо живе",
    "Die Umgebung und Atmosphäre" to "Окружење и атмосфера",
    "Die Worte und Emotionen" to "Речи и емоције",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Врхунски изазов за квиз забаве",
    "Diejenige sein, die umarmt" to "Буди онај који грли",
    "Direkt ansprechen" to "Обратите се директно",
    "Diskussion" to "дискусију",
    "Diskutiere vor dem Kinderkriegen" to "Разговарајте пре него што имате децу",
    "Diskutiert eure Antworten" to "Разговарајте о својим одговорима",
    "Disney" to "Диснеи",
    "Doch, schon mal" to "Да, већ",
    "Draußen mit der Natur als Kulisse" to "Напољу са природом као позадином",
    "Drei-Stein-Ring" to "Три камена прстена",
    "Du bist dran" to "Твој је ред",
    "Du fehlst mir" to "недостајеш ми",
    "Dubai" to "Дубаи",
    "Dubai, VAE" to "Дубаи, УАЕ",
    "Dunkles Design" to "Тамни дизајн",
    "Durch Berührung" to "На додир",
    "Durch Worte" to "Кроз речи",
    "Durch Zeit zu zweit" to "Кроз време заједно",
    "Durch kleine Gesten" to "Кроз мале гестове",
    "Durchgeplant" to "Планирано",
    "ERGEBNISSE" to "РЕЗУЛТАТИ",
    "Egal, Hauptsache gesund" to "Нема везе, главна ствар је здрава",
    "Ehepaar Leben" to "Живот брачног пара",
    "Eher knapp" to "Прилично близу",
    "Eher nicht" to "Радије не",
    "Eher schwer" to "Прилично тешко",
    "Eher schwierig" to "Прилично тешко",
    "Eher zu" to "Радије такође",
    "Eifersucht ist ein Zeichen von Liebe." to "Љубомора је знак љубави.",
    "Eigenes Gemüsebeet" to "Сопствени повртњак",
    "Ein Abenteuer in einer neuen Stadt" to "Авантура у новом граду",
    "Ein Anker" to "Сидро",
    "Ein Balkon oder Garten" to "Балкон или башта",
    "Ein Filmabend" to "Филмско вече",
    "Ein Harmony-Meilenstein eurer Liebe." to "Прекретница хармоније ваше љубави.",
    "Ein Herz" to "Срце",
    "Ein Herz an der Tür" to "Срце на вратима",
    "Ein Jahr lang eine Fernbeziehung führen" to "Имајте везу на даљину годину дана",
    "Ein Kindheitsessen" to "Оброк из детињства",
    "Ein Live-Musik-Konzert besuchen" to "Посетите музички концерт уживо",
    "Ein Museum besuchen" to "Посетите музеј",
    "Ein Spieleabend" to "Ноћ утакмице",
    "Ein Spieleabend mit Freunden" to "Вече игре са пријатељима",
    "Ein Urlaubsfoto" to "Фотографија са одмора",
    "Ein aktives Abenteuer" to "Активна авантура",
    "Ein entspannender Spa-Tag" to "Опуштајући спа дан",
    "Ein ganz normaler Alltagstag" to "Потпуно нормалан свакодневни дан",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Угодно вече у кући током грмљавине",
    "Ein gemütliches Date drinnen" to "Пријатан састанак у затвореном простору",
    "Ein lustiges Bild" to "Смешна слика",
    "Ein paar Handyfotos reichen" to "Довољно је неколико фотографија са мобилног телефона",
    "Ein paar Stunden" to "Неколико сати",
    "Ein paar kulturelle Anklänge sind okay" to "Неколико културних референци је у реду",
    "Ein romantischer Abend" to "Романтично вече",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Романтична вечера уз свеће",
    "Ein romantisches Bild" to "Романтична слика",
    "Ein romantisches Picknick an einem schönen Ort" to "Романтични пикник на прелепој локацији",
    "Ein schwerer Moment, den wir geschafft haben" to "Тежак тренутак који смо успели",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Одличан састанак на отвореном под месечином",
    "Ein ungewöhnliches Gericht" to "Необично јело",
    "Ein zufälliger Schnappschuss" to "Случајни снимак",
    "Einander kennenlernen" to "Упознајте се",
    "Eine Autoreise" to "Путовање",
    "Eine Brücke" to "Мост",
    "Eine Date-Nacht unter den Sternen" to "Ноћ за изласке под звездама",
    "Eine Million Dollar gewinnen" to "Освојите милион долара",
    "Eine Million Dollar verdienen" to "Заради милион долара",
    "Eine Nacht in einem Club" to "Ноћ у клубу",
    "Eine Schokoladenverkostung" to "Дегустација чоколаде",
    "Eine Wanderung mit Panoramablick machen" to "Крените на шетњу са панорамским погледом",
    "Eine Weinverkostung" to "Дегустација вина",
    "Eine gemeinsame Reise" to "Заједничко путовање",
    "Eine gemütliche Nacht zu Hause" to "Угодна ноћ код куће",
    "Eine neue Sprache zu lernen ist einfach." to "Учење новог језика је лако.",
    "Einen Film anschauen" to "Гледај филм",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Месец дана уопште не разговарамо",
    "Einen Tanzkurs besuchen" to "Иди на час плеса",
    "Einen Vergnügungspark erkunden" to "Истражите забавни парк",
    "Einen Wellness-Tag" to "Веллнесс дан",
    "Einen sehr emotionalen Partner haben" to "Имати веома емотивног партнера",
    "Einen sehr logischen Partner haben" to "Имати врло логичног партнера",
    "Einer zahlt alles" to "Једна особа плаћа све",
    "Einfach mehr Alltag" to "Једноставно више свакодневни живот",
    "Einfach nebeneinander sein" to "Само будите једно поред другог",
    "Einfach und intim" to "Једноставно и интимно",
    "Einige Dinge für dich behalten" to "Задржи неке ствари за себе",
    "Einmal" to "Једном",
    "Eins, das nur wir kennen" to "Онај који само ми знамо",
    "Englisch" to "енглески",
    "Entspannte Hängematte" to "Опуштена висећа мрежа",
    "Entspannung" to "опуштање",
    "Erdbeere" to "јагода",
    "Erfolgreich" to "Успешно",
    "Ergebnisse" to "Резултати",
    "Erst bei sehr großen Summen" to "Само за веома велике суме",
    "Erst nur enge Freunde/Familie" to "У почетку само блиски пријатељи/породица",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Нервира ме када мом партнеру треба предуго да одговори на поруке.",
    "Essen & Genuss" to "Храна и уживање",
    "Essensvorlieben" to "Преференце у храни",
    "Etwa eine Woche später, erst mal nur wir" to "Отприлике недељу дана касније, прво само ми",
    "Etwas Neues ausprobieren" to "Пробајте нешто ново",
    "Etwas ganz anderes" to "Нешто сасвим другачије",
    "Etwas sehr Scharfes" to "Нешто веома оштро",
    "Etwas, das ich selbst gern erfinde" to "Нешто што волим сам да измислим",
    "Etwas, eine kleine Note wäre schön" to "Нешто, мало додира би било лепо",
    "Familie" to "Породица",
    "Familie/Freunde" to "Породица/пријатељи",
    "Familienmensch" to "Породични човек",
    "Farbedelstein" to "Обојени драги камен",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "ТВ рекламе су понекад занимљиве за гледање.",
    "Fertig" to "Спреман",
    "Fertig!" to "Завршено!",
    "Feste Date-Nights" to "Ноћ са фиксним датумом",
    "Feuerstelle" to "Огњиште",
    "Filigran & schlicht" to "Филигрански и једноставно",
    "Filme/Serien" to "Филмови/серије",
    "Formuliere um..." to "Преформулирај...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Преформулирајте свој нацрт ненасилно: запажање, осећање, потреба, захтев.",
    "Frage hinzufügen" to "Додајте питање",
    "Fragen & Spiele" to "Питања и игре",
    "Fragen für jede Gelegenheit" to "Питања за сваку прилику",
    "Freizeitpark" to "Забавни парк",
    "Freunde treffen" to "упознај пријатеље",
    "Freundschaften mit Ex-Partnern sind okay." to "Пријатељства са бившим су у реду.",
    "Früh aufstehen" to "Да устанем рано",
    "Fußbodenheizung" to "Подно грејање",
    "Führen wir getrennte oder gemeinsame Konten?" to "Да ли имамо одвојене или заједничке рачуне?",
    "Für dich empfohlen" to "Препоручено за вас",
    "Für die Zukunft" to "За будућност",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Није пронађено ниједно одговарајуће питање или игре за ову претрагу.",
    "Für immer" to "Заувек",
    "Fürsorglichkeit" to "Брижна",
    "GFK-Brücke" to "ГРП мост",
    "Galerie" to "галерија",
    "Gar nicht, der Moment gehört uns" to "Никако, тренутак је наш",
    "Gar nichts tun" to "Не ради ништа",
    "Geduld" to "стрпљење",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Идите рано ујутру да видите излазак сунца",
    "Geht so" to "Иде ок",
    "Geister existieren wirklich." to "Духови заиста постоје.",
    "Gelassenheit" to "спокојство",
    "Gelbgold" to "Жуто злато",
    "Geld & Finanzen" to "Новац и финансије",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Путујте светом заједно, истражите нове културе и кухиње",
    "Gemeinsam ein Lego bauen" to "Направите Лего заједно",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Испробајте заједно нови рецепт у кухињи",
    "Gemeinsame Konten" to "Заједнички рачуни",
    "Gemeinsame Nächte" to "Заједничке ноћи",
    "Gemeinsame Tage" to "Заједнички дани",
    "Gemischt" to "Мијешано",
    "Gemüsebeet" to "повртњак",
    "Gemütliche Feuerstelle" to "Удобно огњиште",
    "Gesprächsanreger" to "Почетници разговора",
    "Getrennte Konten" to "Одвојени рачуни",
    "Getrennte Urlaube tun einer Beziehung gut." to "Раздвојени одмори су добри за везу.",
    "Gewächshaus" to "стакленика",
    "Glasfassade" to "Стаклена фасада",
    "Gleichgültigkeit" to "равнодушност",
    "Glücklich und frei" to "Срећно и слободно",
    "Gourmet Eis-Sorten" to "Гурманске сорте сладоледа",
    "Gravur innen" to "Гравирање унутра",
    "Grillplatz" to "Простор за роштиљ",
    "Groß & üppig" to "Велики и бујни",
    "Große Familie" to "Велика породица",
    "Große Feier" to "Велико славље",
    "Große Fenster" to "Велики прозори",
    "Große Fensterfront" to "Велики прозор испред",
    "Großer Außenpool" to "Велики отворени базен",
    "Großer Garten" to "Велика башта",
    "Großer Stein" to "Велики камен",
    "Größere Küche" to "Већа кухиња",
    "Gutes Essen" to "Уживајте у оброку",
    "Habe ich" to "јесам",
    "Habe ich noch nie" to "никад нисам",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Да ли сте открили неке изненађујуће разлике? Разговарајте о томе зашто вам се више свиђају одређене опције!",
    "Haus am See" to "Кућа поред језера",
    "Haus/Wohnung" to "Кућа/стан",
    "Hazelnut" to "Лешник",
    "Heimkino" to "Кућни биоскоп",
    "Herzhaft" to "Срдачно",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Овде тренутно нема ничега.\\нПромените филтер или изаберите другу тему.",
    "Hilfe im Alltag" to "Помоћ у свакодневном животу",
    "Himbeere" to "малина",
    "Hinzufügen" to "Додај",
    "Hobbys" to "Хобији",
    "Hochzeitssträuße" to "Свадбени букети",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Понос у кући Хогвортса: Где припадаш?",
    "Home" to "Хоме",
    "Hot Tub" to "Хот туб",
    "Humor" to "хумор",
    "Hund" to "Пас",
    "Hängematte" to "висећа мрежа",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Да ли бисте желели писано писмо као део апликације?",
    "IKEA" to "ИКЕА",
    "Ich" to "И",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Више волим романтичне шетње парком него одлазак у биоскоп.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Никада нисам заспао у биоскопу.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Уживам у откривању нових хобија или активности са својим партнером.",
    "Ich finde eine Alternative" to "Наћи ћу алтернативу",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Уживам да пробам нове ресторане са својим партнером уместо да увек идем на иста места.",
    "Ich habe noch nie" to "никад нисам",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Никада се нисам плашио ролеркостера и ипак сам се укрцао на њега.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Никада нисам купио карте за Фаст Пасс јер сам био нестрпљив.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Никада нисам отказао планове да останем код куће и гледам ТВ емисију.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Никада нисам чекао своје писмо из Хогвортса.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Никада нисам рекао да Слитхерин заправо није тако лош.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Никада нисам тврдио да сам престар за Дизнијеве филмове (и потајно уживао у њима).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Никада нисам намерно упуцао некога плавим тенком у Марио Карту.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Никада нисам плакала у Дизнијевом филму.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Никада нисам склопио очи док сам гледао хорор филм.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Никада нисам заборавио да сачувам игру и изгубио сате напретка.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Никада нисам излазио из собе током срамне сцене (фактор језа).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Никада нисам направио смешну позу док сам сликао тобоган.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Никада нисам играо до касно у ноћ и пожалио колико сам био уморан следећег дана.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Никада нисам гуглао крај филма јер нисам могао да чекам.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Никада се нисам осећао као да сам на филмском сету.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Никада нисам прескочио увод у моју омиљену серију.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Никада нисам делио туђу лозинку за Нетфлик.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Никада нисам чуо музику за игру док сам радио или студирао.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Никада нисам кривио контролора када сам изгубио.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Никада нисам бацио тастатуру или контролер у бесу.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Никада нисам заборавио мокру одећу у веш машини неколико дана.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Никада нисам потрошио прави новац на козметичке предмете у игрици.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Никада нисам возио ауто у страној земљи.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Никада нисам опасала Дизнијеву песму под тушем.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Никада нисам возио електрични ауто.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Никада се нисам сликао са маскотом парка.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Никада нисам дао име љубимцу по лику из Хогвортса.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Никада нисам испустио кокице у биоскоп и још увек их јео.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Никада у свакодневном животу нисам користио цитат мајстора Јоде из Ратова звезда.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Никада нисам купио прескуп сувенир у тематском парку.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Никада нисам дао препоруку за филм који је другој особи био ужасан.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Никада нисам гледао Оскаре уживо усред ноћи.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Никада нисам отказао серију јер је прошла сезона била тако лоша.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Никада нисам у једном дану одгледао целу сезону серије.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Никада нисам победио шефа из првог покушаја и осећао сам се као бог.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Никада нисам нашао зликовца који је хладнији од хероја.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Никада нисам препознао лик из Приче о играчкама у својим играчкама.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Никада нисам креирао лик у РПГ-у на основу мог изгледа.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Никада нисам јео цхурро у тематском парку.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Никада нисам гледао Дизнијев филм три пута заредом.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Никада нисам имао Дизнијеву привлачну мелодију читаву недељу.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Никада нисам гледао филм само због неког глумца.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Никада нисам сатима слушао филмску музику на понављању.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Никада нисам открио филмски спојлер и одмах сам пожалио.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Никада нисам нашао пријатеља који говори други матерњи језик.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Никада нисам имао пријатеља који се преселио у другу земљу.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Никада нисам учествовао на филмском маратону о Харију Потеру за Божић.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Никада нисам гледао Марвел филм до краја само због сцене након кредита.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Никада нисам намерно изнервирао НПЦ (Неиграчки лик).",
    "Ich habe noch nie einen Nachtzug genommen." to "Никада нисам ишао ноћним возом.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Никада нисам урадио онлајн тест да бих открио своју кућу у Хогвортсу.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Никада нисам обрисао пост на друштвеним мрежама јер није добио довољно лајкова.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Никада дан у забавном парку нисам назвао најбољим даном у години.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Никада нисам посетио тематски парк и остао тамо од јутра до мрака.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Никада нисам напустио вожњу Трансформерсима или Марвелом потпуно опчињен.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Никада нисам бацио бес (Раге Куит) и напустио игру.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Никада нисам прочитао ниједну од великих књига о Харију Потеру.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Никада нисам бунцао о свом омиљеном лику у серији.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Никада нисам сањао да играм квидич.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Никада нисам тајно гуглао како да решим тежак ниво.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Никад се потајно нисам надао да мој љубимац може да прича као они у Дизнију.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Никада нисам уклонио мердевине за базен у Симсу.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Никада нисам изгубио оријентацију у вожњи на 3Д симулатору.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Никада нисам играо у универзитетском спортском тиму.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Никада нисам чекао у реду дуже од два сата за једну атракцију.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Никада нисам смочио своје драгоцености током вожње водом.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Никада се нисам свађао са пријатељем око тога која је кућа најбоља.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Никада се нисам претварао да имам магичне моћи као Елса.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Никада се нисам толико смејао да сам пропустио важну сцену у филму.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Никада нисам осетио толико адреналина да сам одмах пожелео поново да се возим.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Никада нисам пробао да певам са животињама као што је Снежана.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Никада нисам сањао о путовању у Дизниленд.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Никада нисам сањао да се возим на води у парку Јуре.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Никада у игрици нисам вриснуо наглас на страх од скока.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Никада нисам плакао због финала телевизијске емисије.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Никад... нисам отказао састанак да бих остао код куће.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Никада нисам... преформулисао поруку 10 пута.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Никада...тајно нисам погледао у телефон свог партнера.",
    "Ich habe noch nie!" to "Никада нисам!",
    "Ich habe!" to "Имам!",
    "Ich lache viel mit meinem Partner." to "Много се смејем са својим партнером.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Волим да упознам хобије и интересовања свог партнера.",
    "Ich liebe es" to "волим то",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Волим да са својим партнером гледам филмове које нико од нас раније није видео.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Волим да делим своју омиљену музику са својим партнером.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Никада нисам морао да трчим да ухватим лет са пресједањем.",
    "Ich plane gerne Dates mit meinem Partner." to "Волим да планирам састанке са својим партнером.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Дајем приоритет провођењу времена са својим партнером чак и када сам заузет.",
    "Ich schreibe meinem Partner jeden Tag." to "Сваког дана шаљем поруке свом партнеру.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Волим да делим мемове и шале са својим партнером.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Волим да делим све детаље свог дана са својим партнером.",
    "Ich würde es nie tun" to "Ја то никада не бих урадио",
    "Ich übe noch" to "Још увек вежбам",
    "Ideen generieren" to "Генеришите идеје",
    "Im Haushalt helfen" to "Помоћ око куће",
    "In Chat einfügen" to "Додај у ћаскање",
    "In Stille nebeneinander" to "У тишини једно поред другог",
    "In den Bergen" to "У планинама",
    "In eine Bar gehen" to "Иди у бар",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Одлазак у бар на плажи да гледате залазак сунца",
    "In einem feinen Restaurant essen gehen" to "Јело напољу у фином ресторану",
    "In einen Coffeeshop gehen" to "Иди у кафић",
    "In einer Beziehung sollte man alles voneinander wissen." to "У вези треба да знате све једно о другом.",
    "Infinity-Pool" to "Инфинити поол",
    "Innenpool" to "Затворени базен",
    "Intelligenz" to "интелигенција",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Имајте интимне тренутке само када их ваш партнер иницира",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Шифра позива: ХРМ-8731 · све откључано",
    "Island" to "Исланд",
    "Ist okay für mich" to "У реду је за мене",
    "Ist schon perfekt" to "Већ је савршено",
    "Ja, Traditionen einbinden" to "Да, уградите традиције",
    "Ja, absolut" to "Да, апсолутно",
    "Ja, etwas zum Lesen und Aufbewahren" to "Да, нешто за читање и чување",
    "Ja, genug" to "Да, доста",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Да, у узбудљивом граду или атракцији",
    "Ja, in- und auswendig" to "Да, изнутра и споља",
    "Ja, komplett überraschend" to "Да, потпуно изненађујуће",
    "Ja, perfekt" to "Да, савршено",
    "Ja, sie gehören zur Familie!" to "Да, они су породица!",
    "Ja, sofort teilen" to "Да, поделите одмах",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Да, обезбедићемо да време за породицу буде приоритет.",
    "Jacuzzi" to "Јацуззи",
    "Jahr zusammen 🎉" to "године заједно 🎉",
    "Jahre zusammen 🎉" to "Године заједно 🎉",
    "Jeder zahlt 50%" to "Сви плаћају 50%",
    "Junge" to "Бои",
    "Kamin" to "Димњак",
    "Karriere & Erfolg" to "Каријера и успех",
    "Kategorien" to "Категорије",
    "Katze" to "Цат",
    "Keine Musik" to "Нема музике",
    "Keine Party nötig, privat halten" to "Није потребна забава, нека буде приватно",
    "Keine Privatsphäre" to "Нема приватности",
    "Keine Treffer gefunden" to "Нема пронађених резултата",
    "Keiner" to "Ниједан",
    "Keiner von uns" to "Нико од нас",
    "Kennst du die Essensvorlieben deines Partners?" to "Да ли знате шта воли ваш партнер у храни?",
    "Kino" to "биоскоп",
    "Kirchlich" to "Црквени",
    "Klassisch Solitär" to "Класични пасијанс",
    "Klassisch gebunden" to "Класично везано",
    "Klein & zart" to "Мала и деликатна",
    "Kleine Geschenke" to "Мали поклони",
    "Kleine Runde" to "Мала округла",
    "Kochen und Freunde einladen" to "Кувајте и позовите пријатеље",
    "Kochkurs" to "Час кувања",
    "Kommt auf den Tag an" to "Зависи од дана",
    "Kommt darauf an" to "Зависи од",
    "Kommt drauf an" to "Зависи",
    "Kommt mit" to "Пођи са мном",
    "Konzert" to "концерт",
    "Kräftige Farben" to "Јаке боје",
    "Kräuterbeet" to "Биљни кревет",
    "Kultur & Sehenswürdigkeiten" to "Култура и знаменитости",
    "Kuscheln" to "Цуддле",
    "Kuss senden" to "Пошаљи пољубац",
    "Körperliche Annäherung" to "Физички приступ",
    "Körperliche Nähe" to "Физичка близина",
    "Küche" to "Кухиња",
    "Land" to "земља",
    "Landhaus" to "сеоска кућа",
    "Landhausstil" to "Цоунтри стиле",
    "Lange wach bleiben" to "Остани будан до касно",
    "Lappland" to "Лапланд",
    "Lappland, Finnland" to "Лапонија, Финска",
    "Las Vegas" to "Лас Вегас",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Нека вас ваш партнер инспирише да будете најбољи у себи",
    "Lehne ab" to "Одбиј",
    "Leichtigkeit" to "лакоћа",
    "Leidenschaft" to "Страст",
    "Liebe im Gleichgewicht" to "Љубав у равнотежи",
    "Liebe sie, macht mehr Spaß" to "Волите их, забавније",
    "Lieber durchgeplant oder spontan?" to "Да ли бисте то радије имали планирано или спонтано?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Да ли бисте радије имали мирно вече за двоје или са људима?",
    "Lieber nicht" to "Радије не",
    "Lieber vorher grob absprechen" to "Боље је претходно отприлике разговарати",
    "Lokal einkaufen" to "Купујте локално",
    "London" to "Лондон",
    "London, England" to "Лондон, Енглеска",
    "Lügen" to "Лажи",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Да ли више волите јавни или приватни предлог?",
    "Malediven" to "Малдиви",
    "Man sollte nie streitend einschlafen." to "Никада не би требало да заспите свађајући се.",
    "Mango Sorbet" to "Манго сорбет",
    "Markant & breit" to "Упечатљив и широк",
    "Marken & Alltag" to "Брендови и свакодневни живот",
    "McDonald’s" to "МцДоналд'с",
    "Mediterraner Innenhof" to "Медитеранско двориште",
    "Mehr Unterstützung" to "Више подршке",
    "Mehr gemeinsame Zeit" to "Више времена заједно",
    "Mehr zuhören" to "Слушајте више",
    "Mehrgenerationenhaus" to "Вишегенерацијска кућа",
    "Mein Arbeitsplatz" to "Моје радно место",
    "Mein Partner" to "Мој партнер",
    "Mich überraschen" to "Изненади ме",
    "Minimalistisches Interieur" to "Минималистички ентеријер",
    "Missverständnisse" to "Неспоразуми",
    "Mit Familie und engen Freunden" to "Са породицом и блиским пријатељима",
    "Mit Kompromissen" to "Са компромисима",
    "Mitgefühl" to "саосећање",
    "Mittelweg mit besonderen Details" to "Средина са посебним детаљима",
    "Modern geometrisch" to "Модерна геометријска",
    "Moderne Grillstation" to "Модерна роштиљ станица",
    "Moderner Name" to "Савремено име",
    "Moderner Solitär" to "Модерни пасијанс",
    "Moissanit" to "Моиссаните",
    "Moment festhalten" to "Ухватите тренутак",
    "Momente" to "моменте",
    "Monaco" to "Монако",
    "Moralische Werte" to "Моралне вредности",
    "Museum" to "музеја",
    "Musik" to "Музика",
    "Mut" to "храброст",
    "Mädchen" to "Гирл",
    "Möbelhaus" to "Продавница намештаја",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Да ли стварно желите да напустите квиз? Ваш претходни напредак остаје сачуван.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Да ли бисте желели да кућни љубимци буду укључени у апликацију?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Желите да се тренутак одмах подели на друштвеним мрежама?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Можда ћемо морати да уштедимо",
    "Müssen es planen" to "Морам то испланирати",
    "Müssen sparen" to "Треба спасити",
    "Nachricht an" to "Порука за",
    "Name Partnerin" to "Име партнера",
    "Namen und Startdatum eurer Beziehung." to "Име и датум почетка ваше везе.",
    "Natursteinfassade" to "Фасада од природног камена",
    "Naturteich" to "Природни рибњак",
    "Nein, einfach halten" to "Не, само држи",
    "Nein, erstmal privat halten" to "Не, задржи приватност за сада",
    "Nein, lieber vor Ort" to "Не, боље на лицу места",
    "Nein, modern halten" to "Не, нека буде модерно",
    "Nein, nur wir" to "Не, само ми",
    "Nein, zu ablenkend" to "Не, превише омета",
    "Netflix" to "Нетфлик",
    "Neubau mit Smart Home" to "Нова зграда са паметном кућом",
    "Neubau mit Technik" to "Нова зграда са технологијом",
    "Neue Liebe, neue Erfahrungen" to "Нова љубав, нова искуства",
    "Neues Hobby" to "Нови хоби",
    "Neues Spiel" to "Нова игра",
    "Neugier" to "радозналости",
    "New York" to "Нев Иорк",
    "New York, USA" to "Њујорк, САД",
    "Nicht mein Fall" to "Није мој случај",
    "Nicht nötig, lieber klassisch bleiben" to "Није неопходно, боље је остати класичан",
    "Nichts — es passt so" to "Ништа – тако пристаје",
    "Nie wieder Burger" to "Никад више хамбургере",
    "Nie wieder Pizza" to "Никад више пица",
    "Niemand" to "Нико",
    "Niemand ohne Plan" to "Нико без плана",
    "Nike" to "Нике",
    "Nizza" to "Лепо",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Још нема тренутака.\\нСнимите своје прво искуство 💞",
    "Nur bei wichtigen Themen" to "Само о важним темама",
    "Nur wir beide" to "Само нас двоје",
    "Nähe & Intimität" to "Блискост и интимност",
    "Obstgarten" to "воћњак",
    "Oder" to "Ор",
    "Offene Küche" to "Отворена кухиња",
    "Offene Wohnküche" to "Отворена кухиња/дневни боравак",
    "Ohne Stein" to "Без камена",
    "Open End" to "Отворени завршетак",
    "Outdoor-Küche" to "Кухиња на отвореном",
    "Outdoor-Sofa" to "Спољна софа",
    "Outdoor-Whirlpool" to "Спољна врућа када",
    "Ovaler Diamant" to "Овални дијамант",
    "Paar" to "Пар",
    "Paar-Statistiken" to "Паир Статс",
    "Paris" to "Париз",
    "Paris, Frankreich" to "Париз, Француска",
    "Partner" to "партнер",
    "Partner-Simulator" to "Симулатор партнера",
    "Partnerin" to "партнер",
    "Party Edition" to "Партијско издање",
    "Party Edition II" to "Парти Едитион ИИ",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Да ли се животиња уопште уклапа у наш свакодневни живот?",
    "Pasta" to "тестенина",
    "Pastell" to "Пастел",
    "Penthouse mit Ausblick" to "Пентхоусе са погледом",
    "Pepsi" to "Пепси",
    "Pergola mit Lounge" to "Пергола са дневним боравком",
    "Pfingstrosen" to "Пеониес",
    "Pinguin" to "пингвин",
    "Pistazie" to "пистација",
    "Pizza" to "пизза",
    "Pizzaofen" to "Пећ за пицу",
    "Platin" to "платина",
    "PlayStation" to "ПлаиСтатион",
    "Pool" to "базен",
    "Pop" to "поп",
    "Prasselnder Kamin" to "Роаринг фиреплаце",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Принцезе, пирати и вилинска прашина: Дизни квиз",
    "Privater Innenhof" to "Приватно двориште",
    "Profil" to "профил",
    "Profil bearbeiten" to "Уреди профил",
    "Prozentual nach Einkommen" to "Проценат на основу прихода",
    "Quiz verlassen" to "Остави квиз",
    "Quiz verlassen?" to "Напустити квиз?",
    "Rausgehen in die Natur" to "Изађите у природу",
    "Reden vor ..." to "Говори пред...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Закажите редовне датуме или време заједно",
    "Reisen" to "Травел",
    "Reiseziele" to "Одредишта",
    "Respektlosigkeit" to "непоштовање",
    "Restaurant" to "ресторан",
    "RnB / Soul" to "РнБ/Соул",
    "Rock" to "роцк",
    "Rom" to "Рим",
    "Rom, Italien" to "Рим, Италија",
    "Romantik" to "романса",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Романтични гестови као што су поруке, белешке или поклони ме чине срећним.",
    "Romantische Stimmung" to "Романтично расположење",
    "Roségold" to "Росе голд",
    "Ruhig zu zweit" to "Тихо за двоје",
    "Runder Diamant" to "Округли дијамант",
    "Salted Caramel" to "Слана карамела",
    "Sammle Ideen..." to "Сакупљај идеје...",
    "Santorini" to "Санторини",
    "Santorini, Griechenland" to "Санторини, Грчка",
    "Saphir" to "сафир",
    "Saunahaus" to "Сауна кућа",
    "Schickes Restaurant oder Hotel" to "Шик ресторан или хотел",
    "Schlafzimmer" to "спаваћа соба",
    "Schließen" to "Затвори",
    "Schmal & zart" to "Танак и деликатан",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Снимци из наше љубавне приче",
    "Schokolade" to "Чоколада",
    "Schreib frei, was dir wirklich dazu einfällt." to "Пишите слободно шта вам заиста падне на памет.",
    "Schreibe deine eigene Antwort" to "Напишите свој одговор",
    "Sehr gerne" to "Врло радо",
    "Sehr leicht" to "Веома лагана",
    "Sehr wichtig — Fotos und Video" to "Веома важно - фотографије и видео",
    "Sehr wichtig, es sollte persönlich sein" to "Веома важно, требало би да буде лично",
    "Selbst kochen" to "Кувајте сами",
    "Senden" to "Пошаљи",
    "Separate Küche" to "Одвојена кухиња",
    "Serie schauen" to "Гледајте серије",
    "Serienmarathon auf dem Sofa" to "Серија маратон на софи",
    "Sex & Liebe" to "Сек & Лове",
    "Seychellen" to "Сејшели",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Да ли смо у могућности да покријемо све трошкове за једно дете/више деце? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Да ли предлог треба да буде изненађење?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Да ли апликација треба да садржи културне или традиционалне елементе?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Да ли апликација треба да садржи културне или традиционалне елементе?",
    "Sommerhochzeit" to "Летње венчање",
    "Sonnige Dachterrasse" to "Сунчана кровна тераса",
    "Sowohl als auch" to "Као и",
    "Spazieren" to "Шетња",
    "Spaß & Abenteuer" to "Забава и авантура",
    "Speichern" to "Сачувај",
    "Spiel bearbeiten" to "Уреди игру",
    "Spielbereich für Kinder" to "Игралиште за децу",
    "Spiele" to "игрице",
    "Spiele spielen und Spaß haben" to "Играјте игрице и забавите се",
    "Spontan" to "Спонтано",
    "Sportplatz" to "Спортски терен",
    "Spotify" to "Спотифи",
    "Sprache" to "Језик",
    "Stadt" to "Цити",
    "Stadt oder Land — was ist uns wichtiger?" to "Град или држава – шта нам је важније?",
    "Stadtvilla" to "Градска вила",
    "Standesamt & Party" to "Матични уред и странка",
    "Statement-Ring" to "Прстен за изјаве",
    "Stilvolles Outdoor-Sofa" to "Елегантна спољна софа",
    "Stimme voll zu" to "Потпуно се слажем",
    "Stimmt" to "Истина",
    "Stimmt nicht" to "Није истина",
    "Stimmt, noch nie" to "Тако је, никад",
    "Stracciatella" to "Страцциателла",
    "Strandtag" to "Дан на плажи",
    "Streit über Haushalt" to "Спор око домаћинства",
    "Studio Ghibli" to "Студио Гхибли",
    "Ständig" to "Константно",
    "Suche schließen" to "Затвори претрагу",
    "Suche zurücksetzen" to "Ресетуј претрагу",
    "Suche öffnen" to "Отворите претрагу",
    "Suchergebnisse" to "Резултати претраге",
    "Sushi" to "Сусхи",
    "Süß" to "Слатко",
    "Tage zusammen 💞" to "Дани заједно 💞",
    "Tauche ins Unterbewusstsein" to "Зароните у подсвест",
    "Teile alle deine Hobbys mit deinem Partner" to "Поделите све своје хобије са својим партнером",
    "Teils teils" to "Делимично делимично",
    "Testen" to "Тест",
    "Themen" to "Теме",
    "Tiefe Gespräche" to "Дубоки разговори",
    "Tiefgründige Gespräche führen" to "Водите дубоке разговоре",
    "Tierpension" to "Објекат за смештај животиња",
    "Tiny House" to "Мала кућа",
    "Tippen zum Auswählen & Scrollen" to "Додирните да бисте изабрали и померили",
    "Tippen zum Zuklappen" to "Додирните да бисте скупили",
    "Titel" to "наслов",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Наслов, категорија, тема, ознаке, питања...",
    "Tokyo, Japan" to "Токио, Јапан",
    "Traditioneller Name" to "Традиционални назив",
    "Traumhaus Außenbereich" to "Спољна површина куће из снова",
    "Traumhochzeit" to "Венчање из снова",
    "Treffer" to "Хит",
    "Tägliche Aktivität" to "Дневна активност",
    "Umformulieren" to "Преформулирај",
    "Unbeantwortet" to "Без одговора",
    "Unbeliebte Meinungen" to "Непопуларна мишљења",
    "Universal Studios Genie oder Neuling?" to "Универсал Студиос геније или новајлија?",
    "Uns auseinanderzuleben" to "Да се ​​растају",
    "Unser Intimleben" to "Наш интимни живот",
    "Unser Traumhaus" to "Наша кућа из снова",
    "Unser erstes Treffen" to "Наш први састанак",
    "Unsere Gesichter" to "Наша лица",
    "Unsere eigenen Träume" to "Наши сопствени снови",
    "Unsere nächste Reise" to "Наше следеће путовање",
    "Unter 1000" to "Испод 1000",
    "Unter 1000 im Monat" to "Испод 1000 месечно",
    "Unter 50€/Monat" to "Испод 50€/месец",
    "Unter Leuten" to "Међу људима",
    "Untreue" to "неверство",
    "Urlaub" to "Одмор",
    "Vanille" to "Ванила",
    "Venedig" to "Венеција",
    "Venedig, Italien" to "Венеција, Италија",
    "Verbinde dich mit" to "Повежите се са",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Повежите се са \${profile.partnerName} да бисте видели одговор",
    "Verbindung" to "Веза",
    "Verbringe die Feiertage mit deiner Familie" to "Проведите празнике са својом породицом",
    "Verlobungsringe" to "Веренички прстенови",
    "Vertrautheit" to "фамилијарност",
    "Viel getrennt" to "Много одвојено",
    "Vielleicht ein oder zwei" to "Можда један или два",
    "Vielleicht, aber mündlich reicht" to "Можда, али вербално је довољно",
    "Vielleicht, wenn es machbar ist" to "Можда, ако је изводљиво",
    "Vielleicht, wenn es passt" to "Можда, ако одговара",
    "Vintage Art déco" to "Винтаге Арт Децо",
    "Vintage verspielt" to "Винтаге разигран",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Да вас партнер упозна са новим хобијима",
    "Vor dem Kauf eines Hauses besprechen" to "Разговарајте пре куповине куће",
    "Vor der Anschaffung eines Haustiers besprechen" to "Разговарајте пре куповине кућног љубимца",
    "Vor der gemeinsamen Reise besprechen" to "Разговарајте пре заједничког путовања",
    "Vor nichts" to "Ничега",
    "Vorort" to "предграђе",
    "Walnuss" to "орах",
    "Wandern" to "Хике",
    "Wann fühlst du dich mir am nächsten?" to "Када ми се осећаш најближе?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Када ми се осећаш физички најближим?",
    "Was bedeutet Vertrauen für dich konkret?" to "Шта за вас конкретно значи поверење?",
    "Was entspannt dich mehr?" to "Шта вас више опушта?",
    "Was fehlt dir über die Distanz am meisten?" to "Шта вам највише недостаје на удаљености?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Шта највише волиш у свом дому?",
    "Was hast du von deinem Partner gelernt?" to "Шта сте научили од свог партнера?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Шта мислите о заједничком гледању еротског садржаја?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Шта мислите о реквизитима (нпр. знакови, балони, итд.)?",
    "Was ist das Wichtigste beim Antrag?" to "Шта је најважније приликом пријаве?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Шта је најважнија ствар коју тражите у сексуалном контакту?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Која је твоја омиљена наша слика? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Шта је ваш највећи страх од заједничког живота?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Коју храну волите, а ваш партнер не може да разуме?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Шта је за вас апсолутни прекид посла?",
    "Was ist für jeden von uns das absolute Highlight?" to "Шта је апсолутни врхунац за сваког од нас?",
    "Was ist passiert?" to "Шта се десило?",
    "Was macht einen Moment für dich romantisch?" to "Шта за вас чини тренутак романтичним?",
    "Was magst du an deinem Partner am liebsten?" to "Шта највише волиш код свог партнера?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Шта више волите: рано устајање или касно буђење?",
    "Was magst du lieber?" to "шта ти се више свиђа?",
    "Was möchtest du eigentlich sagen?" to "Шта заправо желиш да кажеш?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Шта бисте желели да ваш партнер чешће ради?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Шта се дешава са животињом када путујемо?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Шта ће бити с нашим дететом када порасте?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Шта као родитељи никада не смемо да изгубимо из вида?",
    "Was war dein schönster Moment mit mir bisher?" to "Који је био твој најбољи тренутак са мном до сада?",
    "Was wir gegessen haben" to "Шта смо јели",
    "Was wollt ihr nie vergessen?" to "Шта никада не желите да заборавите?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Шта би било горе за вас: никада више пица или никада више хамбургере?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Шта бисте највише волели да радите током заједничког дана?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Шта бисте одмах променили да новац није проблем?",
    "Weiter" to "Даље",
    "Weiter spielen" to "Настави да играш",
    "Weiß ich noch nicht" to "не знам још",
    "Weiße Rosen" to "Беле руже",
    "Weißgold" to "Бело злато",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Који квалитет наше дете свакако треба да добије од нас?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Какво окружење бисте желели за предлог?",
    "Welcher Raum sagt am meisten über dich aus?" to "Која соба говори највише о вама?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Који буџет планирамо за храну и ветеринара?",
    "Welches Lied macht dich an? 🥵" to "Која песма те пали? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Која заједничка фотографија вам је омиљена?",
    "Wellnessbad" to "Веллнесс купатило",
    "Wenn es schwierig ist" to "Када су ствари тешке",
    "Wenn ich müde bin" to "Кад сам уморан",
    "Wenn wir uns lange umarmen" to "Кад се дуго грлимо",
    "Wenn wir zusammen lachen" to "Кад се заједно смејемо",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Ко брже одлучује шта ће наручити?",
    "Wer findet die besten Restaurants?" to "Ко проналази најбоље ресторане?",
    "Wer gibt mehr Herzlichkeit?" to "Ко даје више топлине?",
    "Wer hat den besseren Musikgeschmack?" to "Ко има бољи укус за музику?",
    "Wer hängt mehr an seinen Eltern?" to "Ко је више привржен родитељима?",
    "Wer ist besser organisiert?" to "Ко је боље организован?",
    "Wer ist der Beste bei der Filmauswahl?" to "Ко је најбољи у избору филмова?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Ко је најбољи у планирању романтичних састанака?",
    "Wer ist der beste Tänzer?" to "Ко је најбољи плесач?",
    "Wer ist romantischer?" to "Ко је романтичнији?",
    "Wer kocht besser?" to "Ко боље кува?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Ко брине о реновирању и одржавању?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Ко брже примећује када се друга особа не осећа добро?",
    "Wer sucht am Ende wirklich den Film aus?" to "Ко заиста бира филм на крају?",
    "Wer vergisst eher einen Jahrestag?" to "Ко је вероватније да ће заборавити годишњицу?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Ко би вероватније заборавио своје име следећег јутра?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "За кога је већа вероватноћа да ће следећег дана пронаћи видео за који више није знао?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Ко би радије провео ноћ на туђој софи?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Ко би вероватније заспао на забави и пробудио се са Схарпие на лицу?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Ко би се вероватније оклизнуо на плесном подију, али да то изгледа као кул потез?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Ко ће вероватније преузети контролу над Спотифи плејлистом на кућној забави?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Ко би вероватније наручио пицу за све на забави и сам је јео?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Ко је вероватније да ће први заспати на забави?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Ко би вероватније одједном почео да чисти на забави?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Ко би вероватније тврдио да је потпуно трезан када је супротно истина?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Ко је вероватније да ће први попустити у свађи?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Ко би вероватније варао у игри опијања?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Ко би вероватније упао у бифе и тајно однео храну кући?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Ко би вероватније објавио најсрамнију фотографију вечери у својој причи?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Ко би вероватније изнервирао ДЈ-а да затражи своју омиљену песму?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Ко би вероватније певао текст песме ван тона, али са убеђењем?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Ко би вероватније наручио најскупље пиће на менију и пожалио?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Ко би вероватније позвао комшије да се жале на буку?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Ко би вероватније схватио партијске игре (као што је беер понг) превише озбиљно?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Ко би се вероватније спријатељио са избацивачима да би добио ВИП приступ?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Ко би вероватније започео импровизовану караоке битку?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Ко би вероватније отворио боцу без отварача за флаше?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Ко би вероватније одржао говор иако га апсолутно нико није питао?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Ко би вероватније провео сат времена у купатилу правећи селфије?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Ко би вероватније извео срамотну плесну представу и прославио је?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Ко би вероватније позвао бившег партнера након што се забава заврши?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Ко би вероватније случајно увредио чудног госта?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Ко би вероватније тајно напустио забаву без поздрава?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Ко би радије играо са кућним љубимцем домаћина него разговарао са гостима?",
    "Wer würde eher spontan eine Reise buchen?" to "Ко би вероватније спонтано резервисао путовање?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Ко би вероватније водио дубоке разговоре у кухињи сатима?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Ко је вероватније да случајно попије туђе пиће?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Ко би вероватније случајно оборио скупу вазу или нешто крхко?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Ко би вероватније покушао сам да помеша компликован коктел и не би успео?",
    "Wer würde eher zu spät kommen?" to "Ко је вероватније да закасни?",
    "Wer würde eher?" to "Ко би радије?",
    "Wer übernimmt die tägliche Versorgung?" to "Ко води рачуна о свакодневној нези?",
    "Werde so akzeptiert, wie du bist" to "Будите прихваћени такви какви јесте",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Хоћемо ли имати довољно времена за дете/децу? ⏳",
    "Whirlpool" to "Јацуззи",
    "White Chocolate" to "Бела чоколада",
    "Widgets" to "Видгетс",
    "Wie fühlst du dich am meisten geliebt?" to "Како се осећате највољеније?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Како се носимо са различитим приходима?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Који је најбољи начин да ваш партнер започне секс са вама?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Како ваш партнер може бити још бољи партнер за вас?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Колико дуго након просидбе желите да славите са другима?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Колико дуго желимо да останемо тамо?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Колико вам је лако да причате о жељама?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Како желите да изгледа наша будућност?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Како изгледа ваша савршена недеља код куће?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Шта мислите о прљавим причама током секса?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Колико кредита реално можемо приуштити?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Колико времена желимо да проведемо одвојено?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Колико укупно желимо да потрошимо?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Како ћемо наћи времена за нашу везу када беба дође?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Колико вам је важно да је тренутак ухваћен?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Колико вам је важно да апликација одражава ваше хобије или интересовања?",
    "Wie würdest du sie/ihn nennen?" to "Како бисте га/њу назвали?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Који је ваш омиљени начин да покажете наклоност ван секса?",
    "Wildblumen" to "Вилдфловерс",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Хоћеш девојку или дечака? 👶",
    "Wintergarten" to "Зимска башта",
    "Winterhochzeit" to "Зимско венчање",
    "Wir bestellen einfach beides" to "Наручујемо само обоје",
    "Wir brauchen ewig" to "То нам траје заувек",
    "Wir einigen uns nie" to "Никада се не слажемо",
    "Wir entscheiden es gemeinsam" to "Одлучујемо заједно",
    "Wir treffen uns in der Mitte" to "Срешћемо се у средини",
    "Wir wechseln uns ab" to "Ми се смењујемо",
    "Wird stressig" to "Постаје стресно",
    "Wobei lachst du am meisten?" to "Шта вас највише засмејава?",
    "Wofür sparen wir gemeinsam?" to "За шта штедимо заједно?",
    "Wohnzimmer" to "Дневна соба",
    "Woran erinnerst du dich am lebhaftesten?" to "Чега се најживље сећате?",
    "Worauf freust du dich bei uns am meisten?" to "Чему се највише радујете код нас?",
    "Worte/Komplimente" to "Речи/комплименти",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Чега се највише плашите у нашој вези?",
    "Wünsche? z.B. günstig, draußen" to "Жеље? нпр. јефтино, споља",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Да ли бисте радије запросили на одмору (који укључује путовања)?",
    "Xbox" to "Ксбок",
    "YouTube Music" to "ИоуТубе Мусиц",
    "Zeichne für mich" to "Цртај за мене",
    "Zeichne mich als Tier — welches wäre ich?" to "Нацртај ме као животињу - шта бих ја био?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Нацртајте наша осећања једно према другом као симбол.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Нацртајте нашу кућу из снова у једној линији. Шта је најупечатљивије?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Нацртајте наш први састанак - шта свакако треба да буде на слици?",
    "Zeichnen" to "Драв",
    "Zeit füreinander" to "Време једно за друго",
    "Zeit, wenn das Baby schläft" to "Време када беба спава",
    "Zelten gehen" to "Иди на камповање",
    "Zitrone" to "лимун",
    "Zu Hause, gemütlich und privat" to "Код куће, удобно и приватно",
    "Zu einem Picknick gehen" to "Одлазак на пикник",
    "Zu einem ausgefallenen Abendessen gehen" to "Одлазак на фенси вечеру",
    "Zu zweit reisen" to "Путујте као пар",
    "Zuhause & Alltag" to "Кућа и свакодневни живот",
    "Zuhören" to "Слушај",
    "Zurück" to "Назад",
    "Zusammen seit" to "Од тада заједно",
    "Zusammen seit (TT.MM.JJJJ)" to "Заједно од (ДД.ММ.ГГГГ)",
    "Zusammenziehen" to "Уговарање",
    "Zustimmen oder Ablehnen" to "Слажете се или одбијајте",
    "Zwei Kreise, die sich überschneiden" to "Два круга која се преклапају",
    "Zwei Stühle davor" to "Две столице испред",
    "Zärtlich sein" to "Будите нежни",
    "Öfter als ich zugebe" to "Чешће него што признајем",
    "Über 100€/Monat" to "Преко 100€/месечно",
    "Über 2000 im Monat" to "Преко 2000 месечно",
    "Über mich selbst" to "О себи",
    "Übernehmen" to "Преузми",
    "Überraschend" to "Изненађујуће",
    "Überraschung" to "Изненадјење",
    "Überspringen" to "Скип",
    "Übertrieben und großartig" to "Превише и сјајно",
    "✎ Tippe, um zu antworten" to "✎ Додирните да бисте одговорили",
    "✨ GFK-Brücke" to "✨ ГРП мост",
)

internal fun localizeSerbianDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_SERBIAN_CONTENT)
