package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_SOMALI_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 sano",
    "1000 - 1500 im Monat" to "1000 - 1500 bishii",
    "1000 bis 3000" to "1000 ilaa 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 bishii",
    "3000 bis 5000" to "3000 ilaa 5000",
    "5-10 Jahre" to "5-10 sano",
    "50-100€/Monat" to "50-100€/bishii",
    "Ab 100€" to "Laga bilaabo 100€",
    "Ab 500€" to "Laga bilaabo 500€",
    "Ab 50€" to "Laga bilaabo 50€",
    "Ab und zu" to "Had iyo jeer",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Immisa ayaan u baahanahay inaan kharash gareeyno ka hor inta aan wax iibsan?",
    "Abbrechen" to "Jooji",
    "Abenteuer" to "Adventure",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Hawlaha",
    "Alle" to "Dhammaan",
    "Alle Pakete" to "Dhammaan xirmooyinka",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Waayin dhammaan asxaabtaada marka laga reebo saaxiibkaaga ugu fiican",
    "Alle intimen Momente selbst initiieren" to "Bilow dhammaan waqtiyada dhow laftaadu",
    "Alles davon" to "Dhammaanteed",
    "Alles, was noch kommt" to "Wax kasta oo iman doona",
    "Alltagsroutine" to "Jadwal maalmeedka",
    "Alltägliche Berührungen" to "Taabashada maalin kasta",
    "Altbau mit Charme" to "Dhismihii hore oo soo jiidasho leh",
    "Am Strand" to "Xeebta",
    "Am liebsten alles zusammen" to "Way fiicantahay wax walba oo wada jira",
    "Am selben Tag mit Freunden/Familie" to "Isla maalin saaxiibo/qoys",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Netherlands",
    "An das Gefühl" to "ee dareenka",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "Meel fagaare ah oo ay ku jiraan daawadayaal badan",
    "An einen Geruch" to "Udgoon",
    "An einen Song" to "Ku socota hees",
    "An etwas, das ich gesagt habe" to "Wax aan idhi",
    "Analyse starten" to "Bilow falanqaynta",
    "Analysiere eure Muster..." to "Falanqee qaababkaaga...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Falanqee jawaabahaaga & sheekaysigaaga sida ay qabaan Gottman iyo GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Cananaaska ku jira biisa waxay dhadhamiyaan macaan.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Ku jawaab sawir",
    "Antwortähnlichkeit" to "Ka jawaab isku mid",
    "App-Sprache auswählen" to "Dooro luqadda abka",
    "Auf eine Bootsparty gehen" to "Tegitaanka xaflada doonta",
    "Aufmerksamkeit" to "Fiiro gaar ah",
    "Aufräumen und Projekte angehen" to "Nadiifi oo wax ka qabato mashaariicda",
    "Aufwärmen" to "kululee",
    "Aufwärmen: Einander kennenlernen" to "Isbarasho: Isbarashada midba midka kale",
    "Aus dem Urlaub" to "Laga bilaabo fasaxa",
    "Ausgefallener Name" to "Magac qurxoon",
    "Ausschlafen und faulenzen" to "Ku seexo oo hareerahaaga seexo",
    "Ausschlafen und nichts tun" to "Ku seexo oo waxba ha samayn",
    "Aussehen" to "Muuqashada",
    "Auto" to "Baabuur",
    "Außenkamin" to "Dabka dibadda",
    "BEANTWORTE" to "JAWAAB",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonesia",
    "Banane" to "Muuska",
    "Beantwortet" to "Waa lagu jawaabay",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Ka jawaab su'aalaha isku mar - jawaabaha lama arki doono ilaa aad labadiinuba dhammaysaan.",
    "Beantwortete Fragen" to "Su'aalaha ayaa laga jawaabay",
    "Bearbeiten" to "Wax ka beddel",
    "Bei Insider-Witzen" to "Kaftanka gudaha",
    "Bei Memes" to "Ku saabsan xusuusta",
    "Bei einer spontanen Berührung" to "Marka si kedis ah loo taabto",
    "Beide" to "Labadaba",
    "Beide gleich" to "Labaduba waa isku mid",
    "Beide zusammen" to "Labaduba waa wada",
    "Beide, aber wir tun so als ob nicht" to "Labadaba, laakiin iskamayeelin",
    "Beides" to "Labadaba",
    "Beides wäre schlimm" to "Labaduba way xumaan lahaayeen",
    "Beim Einschlafen nebeneinander" to "Is ag seexday",
    "Beim Reden" to "Markaad hadlayso",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Goobaha dalxiiska ee caanka ah had iyo jeer waa niyad jab.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Ku sharax nolosheenna galmo adigoo isticmaalaya emoji.",
    "Besser kommunizieren" to "Si wanaagsan ula xiriir",
    "Bessere Lage" to "Meesha ka wanaagsan",
    "Bestellen" to "Dalbo",
    "Besuchte Länder" to "Wadamada la booqday",
    "Besuchte Städte" to "Magaalooyinka la booqday",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Ma waxaad door bidaysaa soo jeedin xad-dhaaf ah ama wax daahsoon?",
    "Beziehung" to "Xiriirka",
    "Bibliothek" to "Maktabadda",
    "Bin manchmal unsicher" to "Marmar ammaan ma qabo",
    "Bist du ein Videospiel-Guru?" to "Ma tahay guru ciyaarta fiidyowga ah?",
    "Blumenwiese" to "Meesha ubaxa",
    "Bunte Blumenwiese" to "caws ubax midab leh",
    "Burger" to "Burgers",
    "Burger King" to "Burger King",
    "Chat" to "Sheekaysi",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "cajiinka buskudka",
    "Dachgarten mit Lounge" to "Beer saqaf leh oo leh qolka nasashada",
    "Dachterrasse" to "Barxad saqafka sare ah",
    "Das Wetter an dem Tag" to "Cimilada maalintaas",
    "Das erste Selfie" to "Sawirkii ugu horreeyay",
    "Das meiste weiß ich" to "Waan garanayaa inteeda badan",
    "Das oder das?" to "Kani ama kaas?",
    "Das tägliche Leben" to "Nolol maalmeedka",
    "Dass Zusagen gehalten werden" to "Ballanqaadyadaas waa la oofiyay",
    "Dass alles meinen Stil hat" to "In wax walba ay leeyihiin qaabkayga",
    "Dass ich alles erzählen kann" to "In aan wax walba sheegi karo",
    "Dass ich mich nicht sorgen muss" to "Taas oo ah inaanan ka welwelin",
    "Dass wir ungestört sind" to "In aanu qasnayn",
    "Dein Name" to "Magacaaga",
    "Deine Antwort..." to "Jawaabtaada...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Jawaabahaaga waa la keydiyay. Isla marka lammaanuhu dhammeeyo xirmada, labada jawaaboodba waa la wada arki doonaa.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Jawaabahaaga waa la keydiyay. Marka \${profile.partnerName} ay dhamaystirto xirmada, labada jawaaboodba waa la wada arki doonaa.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Ka dhig xidhiidhkaaga mid xamaasad leh oo iskiis ah",
    "Deine Beziehung stabil und sicher machen" to "Ka dhig xidhiidhkaaga mid xasiloon oo sugan",
    "Deine eigene Antwort" to "Jawaab adiga kuu gaar ah",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Way fiicantahay inaad la wadaagto sirahaaga qoto dheer lamaanahaaga",
    "Deinen besten Freund verlieren" to "Waayida saaxiibkaa ugu fiican",
    "Denke an dich" to "Ka fikir naftaada",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "In la daawado isla filim laba jeer waa wakhti lumis.",
    "Der Blick nach draußen" to "Aragtida dibadda",
    "Der Garten" to "Beerta",
    "Der Ort" to "Meesha",
    "Der Ring und die Geste" to "Faraantiga iyo tilmaanta",
    "Der perfekte Heiratsantrag" to "Soo jeedinta guurka ugu fiican",
    "Derjenige sein, der umarmt wird" to "Noqo kuwa la isku duubayo",
    "Deutsch" to "Jarmal",
    "Diamant" to "Dheeman",
    "Diamanten im Band" to "Dheemanka kooxda",
    "Die Distanz" to "Fogaanta",
    "Die Feiertage mit der Familie deines Partners verbringen" to "La qaado ciidaha qoyska lammaanahaaga",
    "Die Gemütlichkeit und Ruhe" to "raaxada iyo nabadda",
    "Die Menschen, die darin wohnen" to "Dadka ku dhex nool",
    "Die Umgebung und Atmosphäre" to "Deegaanka iyo jawiga",
    "Die Worte und Emotionen" to "Erayada iyo dareenka",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Loolanka madadaalada ugu dambeeya",
    "Diejenige sein, die umarmt" to "Noqo qofka habsada",
    "Direkt ansprechen" to "si toos ah u ciwaan",
    "Diskussion" to "Dood",
    "Diskutiere vor dem Kinderkriegen" to "Ka hadal ka hor intaanad carruur dhalin",
    "Diskutiert eure Antworten" to "Ka hadal jawaabahaaga",
    "Disney" to "Disney",
    "Doch, schon mal" to "Haa, haa",
    "Draußen mit der Natur als Kulisse" to "Ka baxsan dabeecadda oo ah dib-u-dhac",
    "Drei-Stein-Ring" to "Saddex faraanti dhagax ah",
    "Du bist dran" to "Waa wakhtigaaga",
    "Du fehlst mir" to "waan ku xiisay",
    "Dubai" to "Dubia",
    "Dubai, VAE" to "Dubai, UAE",
    "Dunkles Design" to "Mawduuc madow",
    "Durch Berührung" to "Taabasho ahaan",
    "Durch Worte" to "Iyadoo loo marayo erayo",
    "Durch Zeit zu zweit" to "Waqti wada jir ah",
    "Durch kleine Gesten" to "Iyadoo loo marayo dhaqdhaqaaqyo yaryar",
    "Durchgeplant" to "Si wanaagsan ayaa loo qorsheeyay",
    "ERGEBNISSE" to "Natiijooyinka",
    "Egal, Hauptsache gesund" to "Si kastaba ha ahaatee, waxa ugu muhiimsan waa caafimaad",
    "Ehepaar Leben" to "Nolosha lamaanaha is guursaday",
    "Eher knapp" to "Halkii u dhow",
    "Eher nicht" to "Aad uma badna",
    "Eher schwer" to "Halkii ay adagtahay",
    "Eher schwierig" to "Halkii ay adagtahay",
    "Eher zu" to "Wax badan oo la mid ah",
    "Eifersucht ist ein Zeichen von Liebe." to "Masayrku waa calaamad jacayl.",
    "Eigenes Gemüsebeet" to "Baro qudaar ah oo u gaar ah",
    "Ein Abenteuer in einer neuen Stadt" to "Tacabur ku taal magaalo cusub",
    "Ein Anker" to "Barroosin",
    "Ein Balkon oder Garten" to "Balakoon ama beer",
    "Ein Filmabend" to "Habeen filim",
    "Ein Harmony-Meilenstein eurer Liebe." to "Himilada is-wanaajinta ee jacaylkaaga.",
    "Ein Herz" to "Wadnaha",
    "Ein Herz an der Tür" to "Wadnaha albaabka",
    "Ein Jahr lang eine Fernbeziehung führen" to "La yeelo xiriir masaafo dheer muddo sanad ah",
    "Ein Kindheitsessen" to "Cunto caruurnimo",
    "Ein Live-Musik-Konzert besuchen" to "Ka qaybgal riwaayad muusig oo toos ah",
    "Ein Museum besuchen" to "Booqo museum",
    "Ein Spieleabend" to "Habeen ciyaar",
    "Ein Spieleabend mit Freunden" to "Habeen ciyaar saaxiibo ah",
    "Ein Urlaubsfoto" to "Sawir fasax ah",
    "Ein aktives Abenteuer" to "Tacabur firfircoon",
    "Ein entspannender Spa-Tag" to "Maalin isboorti oo nasasho leh",
    "Ein ganz normaler Alltagstag" to "Maalin maalmeed gabi ahaanba caadi ah",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Fiid raaxo leh oo guriga dhexdiisa ah inta ay duufaantu socoto",
    "Ein gemütliches Date drinnen" to "Taariikh raaxo leh gudaha gudaha",
    "Ein lustiges Bild" to "Sawir qosol leh",
    "Ein paar Handyfotos reichen" to "Dhowr sawir oo taleefanka gacanta ah ayaa ku filan",
    "Ein paar Stunden" to "Dhowr saacadood",
    "Ein paar kulturelle Anklänge sind okay" to "Dhawr tixraac dhaqameed waa caadi",
    "Ein romantischer Abend" to "Habeen jaceyl ah",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Casho shumaca jaceyl ah",
    "Ein romantisches Bild" to "Sawir jaceyl",
    "Ein romantisches Picknick an einem schönen Ort" to "Fikirka jaceylka ah ee meel qurxoon",
    "Ein schwerer Moment, den wir geschafft haben" to "Waqti adag oo aan maamulnay",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Taariikh weyn oo bannaanka ka ah iftiinka dayaxa hoostiisa",
    "Ein ungewöhnliches Gericht" to "Cunto aan caadi ahayn",
    "Ein zufälliger Schnappschuss" to "Sawir aan toos ahayn",
    "Einander kennenlernen" to "Isbarasho",
    "Eine Autoreise" to "Safar waddo",
    "Eine Brücke" to "Buundo",
    "Eine Date-Nacht unter den Sternen" to "Habeen timireed xiddigaha hoostooda",
    "Eine Million Dollar gewinnen" to "Ku guulaysta hal milyan oo doolar",
    "Eine Million Dollar verdienen" to "Hal milyan oo doolar samee",
    "Eine Nacht in einem Club" to "Habeen naadi dhexdeeda",
    "Eine Schokoladenverkostung" to "Dhadhaminta shukulaatada",
    "Eine Wanderung mit Panoramablick machen" to "Ku kaxee socod leh muuqaallo muuqaal ah",
    "Eine Weinverkostung" to "Dhadhaminta khamriga",
    "Eine gemeinsame Reise" to "Safar wada jir ah",
    "Eine gemütliche Nacht zu Hause" to "Habeen wanaagsan oo guriga ah",
    "Eine neue Sprache zu lernen ist einfach." to "Barashada luqad cusub waa sahlan tahay.",
    "Einen Film anschauen" to "Daawo filim",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Ha wada hadlin haba yaraatee hal bil",
    "Einen Tanzkurs besuchen" to "Qaado xiisad qoob ka ciyaar",
    "Einen Vergnügungspark erkunden" to "Baadh beerta madadaalada",
    "Einen Wellness-Tag" to "Maalin fayoobi",
    "Einen sehr emotionalen Partner haben" to "Lahaanshaha lamaane aad u qiiro badan",
    "Einen sehr logischen Partner haben" to "Lahaanshaha lamaane aad macquul ah",
    "Einer zahlt alles" to "Hal qof ayaa wax walba bixiya",
    "Einfach mehr Alltag" to "Si fudud nolol maalmeedka oo badan",
    "Einfach nebeneinander sein" to "Kaliya is xiga",
    "Einfach und intim" to "Fudud oo qarsoodi ah",
    "Einige Dinge für dich behalten" to "Waxyaabaha qaar naftaada ku hay",
    "Einmal" to "Hal mar",
    "Eins, das nur wir kennen" to "Mid aan naqaan oo keliya",
    "Englisch" to "Ingiriis",
    "Entspannte Hängematte" to "Maqaar dabacsan",
    "Entspannung" to "Nasashada",
    "Erdbeere" to "Strawberry",
    "Erfolgreich" to "Guulaystay",
    "Ergebnisse" to "Natiijooyinka",
    "Erst bei sehr großen Summen" to "Kaliya lacag aad u badan",
    "Erst nur enge Freunde/Familie" to "Kaliya saaxiibada dhow / qoyska marka hore",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Way i cadhaysiisaa marka lammaanahaygu ay waqti dheer ku qaadato ka jawaabista fariimaha.",
    "Essen & Genuss" to "Cunto & raaxaysi",
    "Essensvorlieben" to "Dookhyada cuntada",
    "Etwa eine Woche später, erst mal nur wir" to "Qiyaastii toddobaad ka dib, annaga oo keliya marka hore",
    "Etwas Neues ausprobieren" to "Isku day wax cusub",
    "Etwas ganz anderes" to "Wax gabi ahaanba ka duwan",
    "Etwas sehr Scharfes" to "Wax aad u af badan",
    "Etwas, das ich selbst gern erfinde" to "Wax aan jeclahay in aan naftayda hindiso",
    "Etwas, eine kleine Note wäre schön" to "Wax, qoraal yar ayaa fiicnaan lahayd",
    "Familie" to "Qoyska",
    "Familie/Freunde" to "Qoys/Saaxiibayaal",
    "Familienmensch" to "Nin qoys",
    "Farbedelstein" to "Dhagaxa dahabka ah ee midabka leh",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Xayeysiisyada TV-ga mararka qaarkood waa kuwo xiise leh in la daawado.",
    "Fertig" to "La sameeyay",
    "Fertig!" to "La sameeyay!",
    "Feste Date-Nights" to "Habeenada taariikhda go'an",
    "Feuerstelle" to "Godka dabka",
    "Filigran & schlicht" to "Filim & fudud",
    "Filme/Serien" to "Filimaan/taxane",
    "Formuliere um..." to "Ku celi...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Ku soo celi qoraalkaaga qaab aan rabshad lahayn: u fiirsasho, dareen, baahi, codsi.",
    "Frage hinzufügen" to "ku dar su'aal",
    "Fragen & Spiele" to "Su'aalaha & Ciyaaraha",
    "Fragen für jede Gelegenheit" to "Su'aalaha munaasabad kasta",
    "Freizeitpark" to "Beerta madaddaalada",
    "Freunde treffen" to "La kulan saaxiibo",
    "Freundschaften mit Ex-Partnern sind okay." to "Saaxiibtinimada exes waa caadi.",
    "Früh aufstehen" to "Goor hore kac",
    "Fußbodenheizung" to "Kuleylinta dhulka hoostiisa",
    "Führen wir getrennte oder gemeinsame Konten?" to "Ma leennahay xisaabaadyo gaar ah ama wadajir?",
    "Für dich empfohlen" to "Lagugula taliyay adiga",
    "Für die Zukunft" to "Mustaqbalka",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Wax su'aalo ah ama ciyaaro u dhigma looma helin raadintan.",
    "Für immer" to "Waligeed",
    "Fürsorglichkeit" to "Daryeel",
    "GFK-Brücke" to "buundada GRP",
    "Galerie" to "Gallery",
    "Gar nicht, der Moment gehört uns" to "Haba yaraatee, hadda annagaa iska leh",
    "Gar nichts tun" to "waxba ha samayn",
    "Geduld" to "Dulqaad",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Tag aroortii hore si aad u aragto qorrax ka soo baxa",
    "Geht so" to "u socda sidan",
    "Geister existieren wirklich." to "Jinniyadu runtii way jiraan.",
    "Gelassenheit" to "Deganaansho",
    "Gelbgold" to "Dahab jaale ah",
    "Geld & Finanzen" to "Lacagta & Maaliyadda",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Si wadajir ah ugu safra aduunka, sahamiya dhaqamo cusub iyo cunnooyinka",
    "Gemeinsam ein Lego bauen" to "Wada dhisa Lego",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Isku day cunto kariye cusub si wadajir ah jikada dhexdeeda",
    "Gemeinsame Konten" to "Xisaabaadka la wadaago",
    "Gemeinsame Nächte" to "Habeeno wada jira",
    "Gemeinsame Tage" to "Maalmo wada jira",
    "Gemischt" to "Isku qasan",
    "Gemüsebeet" to "balastar khudaar ah",
    "Gemütliche Feuerstelle" to "Dab dab raaxo leh",
    "Gesprächsanreger" to "Bilowga wada sheekeysiga",
    "Getrennte Konten" to "Koontooyin kala duwan",
    "Getrennte Urlaube tun einer Beziehung gut." to "Fasaxyada kala duwan ayaa u roon xiriirka.",
    "Gewächshaus" to "Guriga cagaaran",
    "Glasfassade" to "Wajiga muraayadda",
    "Gleichgültigkeit" to "Dareen la'aan",
    "Glücklich und frei" to "Farxad iyo bilaash",
    "Gourmet Eis-Sorten" to "Noocyo kala duwan oo jalaato ah",
    "Gravur innen" to "Ku dhejinta gudaha",
    "Grillplatz" to "Meesha Barbecue",
    "Groß & üppig" to "Wayn oo qurux badan",
    "Große Familie" to "Qoyska weyn",
    "Große Feier" to "Dabaaldeg weyn",
    "Große Fenster" to "Daaqadaha waaweyn",
    "Große Fensterfront" to "Daaqad weyn oo hore",
    "Großer Außenpool" to "Barkad weyn oo bannaanka ah",
    "Großer Garten" to "Beer weyn",
    "Großer Stein" to "Dhagax weyn",
    "Größere Küche" to "Jikada ka weyn",
    "Gutes Essen" to "Cunto wanaagsan",
    "Habe ich" to "waan sameeyay",
    "Habe ich noch nie" to "Waligey ma haysto",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Miyaad heshay farqi la yaab leh? Ka hadal sababta aad u jeceshahay xulashooyinka qaarkood si ka wanaagsan!",
    "Haus am See" to "Guri u dhow harada",
    "Haus/Wohnung" to "Guri/aqal",
    "Hazelnut" to "Hazelnut",
    "Heimkino" to "Tiyaatarka guriga",
    "Herzhaft" to "Wacan",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Halkan waxba hadda ma jiraan.\nBeddel shaandhada ama dooro mawduuc kale.",
    "Hilfe im Alltag" to "Caawin nolol maalmeedka",
    "Himbeere" to "Raspberry",
    "Hinzufügen" to "Ku dar",
    "Hobbys" to "Hiwaayadaha",
    "Hochzeitssträuße" to "bouquets arooska",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Kibirka Guriga Hogwarts: Xageed ka tirsan tahay?",
    "Home" to "Guriga",
    "Hot Tub" to "Tusbada kulul",
    "Humor" to "Kaftan",
    "Hund" to "Eey",
    "Hängematte" to "Hammock",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Ma jeceshahay warqad qoran oo qayb ka ah soo jeedinta?",
    "IKEA" to "IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Waxaan doorbidayaa socodka jacaylka ee beerta si aan u aado shineemo.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Waligay kuma dhex seexan shineemo.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Waxaan ku raaxaystaa in aan la helo hiwaayad ama waxqabadyo cusub lammaanahayga.",
    "Ich finde eine Alternative" to "Waxaan heli doonaa beddel kale",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Waxaan ku raaxaystaa in aan lammaanahayga isku dayo makhaayado cusub intii aan mar walba aadi lahaa isku meel.",
    "Ich habe noch nie" to "Weligay ma haysto",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Waligay kama baqayn roller coaster oo si kastaba waan ku galay.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Waligey ma iibsan tigidhada Pass Pass-ka ah sababtoo ah samir la'aan baan ahaa.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Waligay ma burin qorshayaasha aan guriga ku joogo oo aan daawado bandhig TV.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Waligay ma sugin warqaddayda Hogwarts.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Weligay ma odhan in Slytherin runtii sidaas uma xuma.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Waligey ma dhihin waan aad ugu da'weynahay filimada Disney (oo si qarsoodi ah ayaan ugu riyaaqay).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Waligay si ula kac ah uma toogan qof wata taangiga buluuga ah ee Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Waligay kamaan oohin filimka Disney",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Weligay indhaha ma daboolin markaan daawanayo filim cabsi leh.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Weligay ma ilaawin inaan badbaadiyo ciyaar oo aan lumiyay saacado horumar ah.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Weligay qolka kama tegin inta lagu jiro muuqaal ceeb ah (cunsurka qallafsan).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Weligay ma samayn muuqaal qosol leh markaan qaadayo sawir rullalula.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Weligay habeen dambe ma dheelin oo ka qoomameeyay daalkaygii maalintii xigtay.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Waligey ma gelin google-ka dhamaadka filim sababtoo ah ma sugi karin",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Waligay ma dareemin inaan taaganahay meel filim ah.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Weligay ma dhaafin hordhaca taxanaha aan jeclahay.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Waligay lama wadaagin qof kale lambarka sirta ah ee Netflix.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Weligay ma dhegaysan dhawaaqa ciyaarta marka aan shaqaynayo ama wax baranayo.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Waligay ma eedayn maamulaha markii aan guuldaraystay.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Waligay ma tuurin kiiboodhka ama kontoroolka cadho.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Weligay ma ilaawin dharka qoyan ee mashiinka dharka lagu dhaqo dhowr maalmood.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Waligay lacag dhab ah kuma bixin alaabta qurxinta ciyaarta dhexdeeda.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Waligey baabuur kuma wadan wadan shisheeye.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Weligay ma xidhin suunka heesta Disney ee qubeyska.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Waligay ma wadin baabuur koronto ah.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Weligay sawir kama qaadin mascot beerta.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Weligay xayawaan uma magacaabin dabeecada Hogwarts.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Waligay ma daadin salool masraxa filimada oo weli waan cunay.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Waligey uma isticmaalin oraah ka timid Master Yoda ee Star Wars nolol maalmeedka.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Weligay maan gadan alaab qaali ah oo xusuus ah oo ku taal beerta theme.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Waligey ma aanan siin talo-bixin filim in qofka kale uu arkay wax laga cabsado.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Waligay ma daawan Oscars si toos ah saq dhexe.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Waligay ma burin taxane ah sababtoo ah xilli ciyaareedkii u dambeeyay aad buu u xumaa.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Weligay maan daawatay si aad ah xilli dhan oo taxane ah hal maalin gudaheed.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Waligay kama badin madax isku daygii ugu horreeyay oo waxaan dareemay sidii ilaah.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Weligay ma helin qaboojiye shar leh oo ka badan geesiga.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Weligay ma aqoonsan jilaa Sheeko Toy ah oo ku jirta alaabtayda ay carruurtu ku ciyaarto.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Waligay ma samayn jile RPG sida saxda ah aniga oo kale.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Waligay churro kuma cunin beerta theme.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Weligay maan daawan filimka Disney saddex jeer oo isku xigta.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Weligay ma helin laxanka Disney soo jiidashada toddobaad dhan.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Waligey ma daawan filim jilaa gaar ah dartiis.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Weligay ma dhegaysan cod-qaad filim oo ku celcelinaya saacado.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Waligay ma daaha ka qaadin filim kharibaya oo isla markiiba waan ka qoomameeyay.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Weligay ma helin saaxiib ku hadla af kale oo hooyo.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Waligey ma helin saaxiib u guuray waddan kale.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Weligay ma samayn maaratoonka Harry Potter wakhtiga Kirismaska.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Waligey ma daawan filim Marvel ah ilaa dhamaadka kaliya sababtoo ah muuqaalka deynta ka dib.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Waligey si ula kac ah uma xanaaqin NPC (dabeecad aan ciyaartoy ahayn).",
    "Ich habe noch nie einen Nachtzug genommen." to "Waligay ma qaadan tareen habeenimo ah.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Waligey ma qaadin imtixaan onlayn ah si aan u ogaado gurigayga Hogwarts.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Weligay ma tirtirin qoraal baraha bulshada ah sababtoo ah ma helin wax ku filan oo jecel.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Weligay maalin uma yeedhin goobta beerta mawduuca maalinta ugu fiican sanadka.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Waligay maan booqan goob lagu nasto oo mawduuca laga dhigto oo aan halkaas joogay subax ilaa habeenimo.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Weligay kama tegin Transformers ama fuulista la yaabka leh oo gebi ahaanba la yaabay.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Weligay cadho ma tuurin oo iska daa ciyaarta.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Weligay ma akhriyin mid ka mid ah buugaagta Harry Potter ee waaweyn.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Waligay kama aan xanaaqin jilaha aan ugu jeclaa taxanaha.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Waligay kuma riyoon inaan ciyaaro Quidditch.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Waligey si qarsoodi ah uma gelin Google sida loo xalliyo heer adag.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Waligay si qarsoodi ah uma rajaynayn in xayawaankaygu u hadli karo sida Disney.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Waligay kama saarin hogaamiyaha barkada Sims.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Waligay igama lumin dareenkayga fuulista jilbaha 3D.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Waligay kamaan ciyaarin koox isboorti oo jaamacadeed.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Waligay ma sugin safka in ka badan laba saacadood hal soo jiidasho.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Waligay ma helin alaabtayda qaaliga ah ee qoyan korka biyaha.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Waligay saaxiib kalamaan doodin guriga kan ugu fiican.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Waligay iskama dhigin inaan leeyahay awood sixir ah sida Elsa.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Waligay si adag uma qoslin taas oo aan seegay muuqaal muhiim ah oo filim ah.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Waligay ma dareemin wax adrenaline ah oo aan isla markiiba doonayay inaan mar kale fuulo.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Weligay iskuma dayin inaan kula heeso xayawaanka sida Snow White.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Waligay kuma riyoon safar aan ku aado Disneyland.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Waligay kuma riyoon inaan raaco raacitaanka biyaha Jurassic Park.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Waligay qeylo dheer uma qeylin cabsi bood ah oo ciyaarta dhexdeeda ah.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Waligay kama oohin dhamaadka bandhiga TV-ga.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Weligay... ma burin taariikh aan guriga ku joogo.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Weligay... maan soo celin fariin 10 jeer ah.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Waligey... si qarsoodi ah uma eegin taleefanka gacanta ee lammaanahayga.",
    "Ich habe noch nie!" to "Weligay ma haysto!",
    "Ich habe!" to "Waxaan haystaa!",
    "Ich lache viel mit meinem Partner." to "Aad ayaan ugu qoslaa lammaanahayga.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Waxaan jeclahay inaan barto waxyaabaha uu xiiseeyo lammaanahayga.",
    "Ich liebe es" to "waan jeclahay",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Waxaan jeclahay daawashada filimaanta lamaanaheyga oo aan labadayada midna horay u arag.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Waxaan jeclahay la wadaaga muusigga aan jeclahay lammaanahayga.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Waligay ma cararin si aan u qabto duulimaad xiriirinaya",
    "Ich plane gerne Dates mit meinem Partner." to "Waxaan jeclahay qorsheynta taariikhaha lammaanahayga.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Waxaan mudnaanta siiya la-qaadista waqtiga lammaanahayga xitaa marka aan mashquul ahay.",
    "Ich schreibe meinem Partner jeden Tag." to "Waxaan fariin u diraa lamaanahayga maalin kasta.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Waxaan jeclahay la wadaaga sheekooyinka iyo kaftanka lamaanahayga.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Waxaan jeclahay inaan dhammaan macluumaadka maalintayda la wadaago lammaanahayga.",
    "Ich würde es nie tun" to "Weligay ma yeeli doono",
    "Ich übe noch" to "Weli waan ku celcelinayaa",
    "Ideen generieren" to "Abuur fikrado",
    "Im Haushalt helfen" to "Caawinta agagaarka guriga",
    "In Chat einfügen" to "Ku dar wada sheekaysi",
    "In Stille nebeneinander" to "Aamusnaanta dhinacba midka kale",
    "In den Bergen" to "Buuraha dhexdiisa",
    "In eine Bar gehen" to "Tag baar",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Tagitaanka baar xeebta si aad u daawato qorrax dhaca",
    "In einem feinen Restaurant essen gehen" to "Wax ka cunida meel maqaaxi fiican ah",
    "In einen Coffeeshop gehen" to "Tag dukaan kafeega",
    "In einer Beziehung sollte man alles voneinander wissen." to "Xariirka dhexdiisa waa inaad taqaanaa wax walba oo midba midka kale ku saabsan.",
    "Infinity-Pool" to "barkadda Infinity",
    "Innenpool" to "Barkad gudaha ah",
    "Intelligenz" to "Sirdoonka",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Kaliya inaad haysato waqtiyo dhow marka lamaanahaagu uu bilaabo",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Koodhka martiqaadka: HRM-8731 · wax kasta oo furan",
    "Island" to "Iceland",
    "Ist okay für mich" to "Waa ila sax aniga",
    "Ist schon perfekt" to "Way qumman tahay",
    "Ja, Traditionen einbinden" to "Haa, ku dar caadooyinka",
    "Ja, absolut" to "Haa, gabi ahaanba",
    "Ja, etwas zum Lesen und Aufbewahren" to "Haa, wax la akhriyo oo la xafido",
    "Ja, genug" to "Haa, ku filan",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Haa, magaalo xiiso leh ama soo jiidasho leh",
    "Ja, in- und auswendig" to "Haa, gudaha iyo dibadda",
    "Ja, komplett überraschend" to "Haa, gabi ahaanba la yaab",
    "Ja, perfekt" to "Haa, qumman",
    "Ja, sie gehören zur Familie!" to "Haa, waa qoys!",
    "Ja, sofort teilen" to "Haa, isla markiiba wadaag",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Haa, waxaanu hubin doonaa in wakhtiga qoysku yahay mudnaanta.",
    "Jacuzzi" to "Jacuzzi",
    "Jahr zusammen 🎉" to "sanad wada jir 🎉",
    "Jahre zusammen 🎉" to "Sannado wada jir ah 🎉",
    "Jeder zahlt 50%" to "Qof kastaa wuxuu bixiyaa 50%",
    "Junge" to "Wiil",
    "Kamin" to "Dabka",
    "Karriere & Erfolg" to "Xirfadda & Guusha",
    "Kategorien" to "Qaybaha",
    "Katze" to "Bisad",
    "Keine Musik" to "Muusig ma jiro",
    "Keine Party nötig, privat halten" to "Looma baahna xaflad, si gaar ah u dhig",
    "Keine Privatsphäre" to "Ma jiro sir",
    "Keine Treffer gefunden" to "Wax u dhigma lama helin",
    "Keiner" to "Midna",
    "Keiner von uns" to "Midkeenna midna",
    "Kennst du die Essensvorlieben deines Partners?" to "Ma garanaysaa dookhyada cuntada lamaanahaaga?",
    "Kino" to "Shineemo",
    "Kirchlich" to "Wadaadka",
    "Klassisch Solitär" to "Solitaire Classic",
    "Klassisch gebunden" to "qadiimiga ku xidhan",
    "Klein & zart" to "Yar & jilicsan",
    "Kleine Geschenke" to "Hadiyadaha yaryar",
    "Kleine Runde" to "Koox yar",
    "Kochen und Freunde einladen" to "Karinta iyo martiqaadida saaxiibada",
    "Kochkurs" to "fasalka karinta",
    "Kommt auf den Tag an" to "Waxay kuxirantahay maalinta",
    "Kommt darauf an" to "Waxay kuxirantahay",
    "Kommt drauf an" to "Waxay kuxirantahay",
    "Kommt mit" to "I raac",
    "Konzert" to "Riwaayad",
    "Kräftige Farben" to "Midabada adag",
    "Kräuterbeet" to "Sariir dhireed",
    "Kultur & Sehenswürdigkeiten" to "Dhaqanka & Muuqaalka",
    "Kuscheln" to "koolkoolin",
    "Kuss senden" to "Dir dhunkasho",
    "Körperliche Annäherung" to "Habka jireed",
    "Körperliche Nähe" to "Isku soo dhawaansho jidheed",
    "Küche" to "Jikada",
    "Land" to "Dalka",
    "Landhaus" to "Guriga dalka",
    "Landhausstil" to "Habka guriga dalka",
    "Lange wach bleiben" to "Soo raagi",
    "Lappland" to "Lapland",
    "Lappland, Finnland" to "Lapland, Finland",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "U oggolow lammaanahaagu inuu kugu dhiirrigeliyo inaad noqoto naftaada ugu fiican",
    "Lehne ab" to "diiday",
    "Leichtigkeit" to "Iftiin",
    "Leidenschaft" to "Jacayl",
    "Liebe im Gleichgewicht" to "Jacaylku dheelitiran",
    "Liebe sie, macht mehr Spaß" to "Jeclow iyaga, madadaalo badan",
    "Lieber durchgeplant oder spontan?" to "Ma jeclaan lahayd inaad u qorsheysato ama si kedis ah u qorsheysna?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Ma jeclaan lahayd inaad u hesho fiidkii xasilloon laba ama dad?",
    "Lieber nicht" to "Maya",
    "Lieber vorher grob absprechen" to "Way fiicantahay in hore looga wadahadlo arrimaha",
    "Lokal einkaufen" to "ku dukaamayso gudaha",
    "London" to "London",
    "London, England" to "London, England",
    "Lügen" to "Been",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Ma jeceshahay soo jeedin dadweyne ama mid gaar ah?",
    "Malediven" to "Maldives",
    "Man sollte nie streitend einschlafen." to "Waa inaadan waligaa seexan adigoo doodaya.",
    "Mango Sorbet" to "Mango Sorbet",
    "Markant & breit" to "Waxqabad & ballaaran",
    "Marken & Alltag" to "Noocyada iyo nolol maalmeedka",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "Barxadda Mediterranean",
    "Mehr Unterstützung" to "Taageero badan",
    "Mehr gemeinsame Zeit" to "Waqti dheeri ah oo wada jira",
    "Mehr zuhören" to "Wax badan dhegayso",
    "Mehrgenerationenhaus" to "Guri jiilal badan",
    "Mein Arbeitsplatz" to "Goobta shaqadayda",
    "Mein Partner" to "Lamaanahayga",
    "Mich überraschen" to "I yaabin",
    "Minimalistisches Interieur" to "gudaha ugu yar",
    "Missverständnisse" to "Ismaandhaaf",
    "Mit Familie und engen Freunden" to "Qoyska iyo saaxiibada dhow",
    "Mit Kompromissen" to "Iyada oo tanaasul la sameeyay",
    "Mitgefühl" to "Naxariista",
    "Mittelweg mit besonderen Details" to "Dhulka dhexe oo leh tafaasiil gaar ah",
    "Modern geometrisch" to "Joomatari casriga ah",
    "Moderne Grillstation" to "Saldhigga wax lagu dubay ee casriga ah",
    "Moderner Name" to "Magaca casriga ah",
    "Moderner Solitär" to "Solitaire casriga ah",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "Qabo wakhtiga",
    "Momente" to "daqiiqado",
    "Monaco" to "Monaco",
    "Moralische Werte" to "Qiimaha akhlaaqda",
    "Museum" to "Matxafka",
    "Musik" to "Muusiga",
    "Mut" to "Geesinimo",
    "Mädchen" to "Gabdhaha",
    "Möbelhaus" to "Dukaanka alaabta guriga",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Ma hubtaa inaad rabto inaad ka baxdo kediska? Horumarkaagii hore waxa uu ahaanayaa mid kaydsan",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Ma jeclaan lahayd in xayawaannada guriga lagu joogo lagu daro codsiga?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Ma doonaysaa in wakhtigan isla markiiba lagu wadaago warbaahinta bulshada?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Waxa laga yaabaa inaan u baahanahay inaan samayno kayd",
    "Müssen es planen" to "Waxaan u baahanahay in la qorsheeyo",
    "Müssen sparen" to "Waxa loo baahan yahay in la kaydiyo",
    "Nachricht an" to "Fariinta",
    "Name Partnerin" to "Magaca lammaanaha",
    "Namen und Startdatum eurer Beziehung." to "Magacyada iyo taariikhda bilawga xidhiidhkaaga.",
    "Natursteinfassade" to "Waji dhagax dabiici ah",
    "Naturteich" to "Balli dabiici ah",
    "Nein, einfach halten" to "Maya, kaliya hay",
    "Nein, erstmal privat halten" to "Maya, si gaar ah u dhig hadda",
    "Nein, lieber vor Ort" to "Maya, ku fiican goobta",
    "Nein, modern halten" to "Maya, ha ahaato mid casri ah",
    "Nein, nur wir" to "Maya, annaga oo keliya",
    "Nein, zu ablenkend" to "Maya, aad u mashquuliya",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Dhisme cusub oo leh guri caqli badan",
    "Neubau mit Technik" to "Dhisme cusub oo tignoolajiyadeed leh",
    "Neue Liebe, neue Erfahrungen" to "Jacayl cusub, waayo-aragnimo cusub",
    "Neues Hobby" to "Hiwaayad cusub",
    "Neues Spiel" to "Ciyaar cusub",
    "Neugier" to "xiisaha",
    "New York" to "New York",
    "New York, USA" to "New York, USA",
    "Nicht mein Fall" to "Ma aha koobka shaaha",
    "Nicht nötig, lieber klassisch bleiben" to "Looma baahna, way fiicantahay inaad ahaato mid caadi ah",
    "Nichts — es passt so" to "Waxba - way ku habboon tahay",
    "Nie wieder Burger" to "Mar dambe ha burger",
    "Nie wieder Pizza" to "Weligaa ha u soo noqon biisa",
    "Niemand" to "Qofna",
    "Niemand ohne Plan" to "Qof aan qorshe lahayn ma jiro",
    "Nike" to "Nike",
    "Nizza" to "Wacan",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Wax daqiiqado ah wali ma jiraan.\n Qabo khibradaada ugu horeysa 💞",
    "Nur bei wichtigen Themen" to "Kaliya mawduucyada muhiimka ah",
    "Nur wir beide" to "Kaliya labadeena",
    "Nähe & Intimität" to "Isku soo dhawaanshaha & Xidhiidhka",
    "Obstgarten" to "Beerta beerta",
    "Oder" to "Mise",
    "Offene Küche" to "Jikada furan",
    "Offene Wohnküche" to "Jikada/qolka fadhiga furan",
    "Ohne Stein" to "Dhagax la'aan",
    "Open End" to "Dhammaad furan",
    "Outdoor-Küche" to "Jikada dibadda",
    "Outdoor-Sofa" to "Fadhi bannaanka",
    "Outdoor-Whirlpool" to "Wareegga bannaanka",
    "Ovaler Diamant" to "Dheeman oval ah",
    "Paar" to "Lammaane",
    "Paar-Statistiken" to "Tirada lamaanaha",
    "Paris" to "Paris",
    "Paris, Frankreich" to "Paris, Faransiiska",
    "Partner" to "Lamaane",
    "Partner-Simulator" to "Jiliyaha shuraakada",
    "Partnerin" to "Lamaane",
    "Party Edition" to "Daabacaadda Xisbiga",
    "Party Edition II" to "Daabacaadda Xisbiga II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Xayawaanku xitaa ma ku habboon yahay nolol maalmeedkeena?",
    "Pasta" to "Baasto",
    "Pastell" to "Pastel",
    "Penthouse mit Ausblick" to "Penthouse oo muuqaal leh",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pergola oo leh qolka fadhiga",
    "Pfingstrosen" to "Peonies",
    "Pinguin" to "Penguin",
    "Pistazie" to "Pistachio",
    "Pizza" to "Pizza",
    "Pizzaofen" to "Foornada Pizza-da",
    "Platin" to "Platinum",
    "PlayStation" to "PlayStation",
    "Pool" to "Barkadda",
    "Pop" to "Boob",
    "Prasselnder Kamin" to "Dab dab ciyaya",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Boqorada, Budhcad-badeedda iyo Siigada Carafka: Disney Quiz",
    "Privater Innenhof" to "Barxad gaar ah",
    "Profil" to "Xogta",
    "Profil bearbeiten" to "Wax ka beddel astaanta guud",
    "Prozentual nach Einkommen" to "Boqolleyda ku salaysan dakhliga",
    "Quiz verlassen" to "Jooji su'aalaha",
    "Quiz verlassen?" to "Ka tag kedis?",
    "Rausgehen in die Natur" to "U bax dabeecadda",
    "Reden vor ..." to "Isagoo la hadlaya...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Jadwal u samee taariikhaha caadiga ah ama wakhti wadajir ah",
    "Reisen" to "Socdaalka",
    "Reiseziele" to "Goobaha safarka",
    "Respektlosigkeit" to "Xushmad-darro",
    "Restaurant" to "Makhaayada",
    "RnB / Soul" to "RnB / naf",
    "Rock" to "Dhagax",
    "Rom" to "Rome",
    "Rom, Italien" to "Rome, Italy",
    "Romantik" to "Jaceyl",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Tilmaamaha jaceylka ah sida fariimaha, qoraalada ama hadiyadaha ayaa iga farxiya.",
    "Romantische Stimmung" to "Dareen jacayl",
    "Roségold" to "Dahab Rose ah",
    "Ruhig zu zweit" to "Deggan laba",
    "Runder Diamant" to "Dheeman wareegsan",
    "Salted Caramel" to "Karmel cusbo leh",
    "Sammle Ideen..." to "Ururi fikradaha...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Giriiga",
    "Saphir" to "Sapphire",
    "Saunahaus" to "Guriga saunada",
    "Schickes Restaurant oder Hotel" to "Makhaayada quruxda badan ama hudheelka",
    "Schlafzimmer" to "Qolka jiifka",
    "Schließen" to "Xir",
    "Schmal & zart" to "Caato ah oo jilicsan",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Sawirro laga qaaday sheekadeena jacaylka",
    "Schokolade" to "Chocolate",
    "Schreib frei, was dir wirklich dazu einfällt." to "Si xor ah u qor waxa runtii maskaxda ku soo dhaca.",
    "Schreibe deine eigene Antwort" to "Jawaabtaada qor",
    "Sehr gerne" to "Waa lagu soo dhaweynayaa",
    "Sehr leicht" to "Aad u khafiif ah",
    "Sehr wichtig — Fotos und Video" to "Aad muhiim u ah - sawiro iyo muuqaal",
    "Sehr wichtig, es sollte persönlich sein" to "Aad muhiim u ah, waa inay ahaataa mid gaar ah",
    "Selbst kochen" to "Naftaada kari",
    "Senden" to "Dir",
    "Separate Küche" to "Jikada goonida ah",
    "Serie schauen" to "Daawo taxanaha",
    "Serienmarathon auf dem Sofa" to "Taxanaha maratoonka fadhiga fadhiga",
    "Sex & Liebe" to "Galmada & Jacaylka",
    "Seychellen" to "Seychelles",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Ma awoodnaa inaan daboolno dhammaan kharashyada hal cunug/carruur badan? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Soo jeedintu ma tahay mid la yaab leh?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Codsiga miyuu ka kooban yahay waxyaabo dhaqameed ama dhaqameed?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Codsiga miyuu ka kooban yahay waxyaabo dhaqameed ama dhaqameed?",
    "Sommerhochzeit" to "Arooska xagaaga",
    "Sonnige Dachterrasse" to "Barxad saqafka sare ee qoraxda leh",
    "Sowohl als auch" to "Labada iyo",
    "Spazieren" to "Soco",
    "Spaß & Abenteuer" to "Madadaalo & Kacsi",
    "Speichern" to "Keydi",
    "Spiel bearbeiten" to "Wax ka beddel ciyaarta",
    "Spielbereich für Kinder" to "Goobta ciyaarta ee carruurta",
    "Spiele" to "Ciyaaraha",
    "Spiele spielen und Spaß haben" to "Ciyaar ciyaar oo madadaalo",
    "Spontan" to "Kadis ah",
    "Sportplatz" to "Garoonka ciyaaraha",
    "Spotify" to "Spotify",
    "Sprache" to "Luuqadda",
    "Stadt" to "Magaalada",
    "Stadt oder Land — was ist uns wichtiger?" to "Magaalada ama dalka - maxaa noo muhiim ah?",
    "Stadtvilla" to "Villa magaalada",
    "Standesamt & Party" to "Xafiiska diiwaanka & xisbiga",
    "Statement-Ring" to "Faraantiga warbixinta",
    "Stilvolles Outdoor-Sofa" to "Fadhi bannaanka oo qurxoon",
    "Stimme voll zu" to "Si buuxda u oggolow",
    "Stimmt" to "Sax",
    "Stimmt nicht" to "Run maaha",
    "Stimmt, noch nie" to "Run, weligeed",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Maalinta xeebta",
    "Streit über Haushalt" to "Muranka qoyska",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "Si joogto ah",
    "Suche schließen" to "Xidh raadinta",
    "Suche zurücksetzen" to "Dib u deji raadinta",
    "Suche öffnen" to "Raadin furan",
    "Suchergebnisse" to "Natiijooyinka raadinta",
    "Sushi" to "Suushi",
    "Süß" to "Macaan",
    "Tage zusammen 💞" to "maalmo wada socda 💞",
    "Tauche ins Unterbewusstsein" to "U quuso miyir-qabka hoose",
    "Teile alle deine Hobbys mit deinem Partner" to "La wadaag dhammaan hiwaayadahaaga lamaanahaaga",
    "Teils teils" to "Qayb qayb",
    "Testen" to "Imtixaan",
    "Themen" to "Mowduucyada",
    "Tiefe Gespräche" to "Sheeko qoto dheer",
    "Tiefgründige Gespräche führen" to "Wada sheekaysi qoto dheer",
    "Tierpension" to "Hoyga xoolaha",
    "Tiny House" to "Guri yar",
    "Tippen zum Auswählen & Scrollen" to "Taabo si aad u doorato oo u rogto",
    "Tippen zum Zuklappen" to "Taabo si aad u burburto",
    "Titel" to "Cinwaanka",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Ciwaanka, Qaybta, Mawduuca, Tagsyada, Su'aalaha...",
    "Tokyo, Japan" to "Tokyo, Japan",
    "Traditioneller Name" to "Magaca dhaqameed",
    "Traumhaus Außenbereich" to "Guriga riyada ee bannaanka",
    "Traumhochzeit" to "Riyo aroos",
    "Treffer" to "Ku dhufo",
    "Tägliche Aktivität" to "Dhaqdhaqaaq maalmeed",
    "Umformulieren" to "Ku celi",
    "Unbeantwortet" to "Looma jawaabin",
    "Unbeliebte Meinungen" to "Fikrado aan la jeclayn",
    "Universal Studios Genie oder Neuling?" to "Garaadka guud ee Studios mise qof cusub?",
    "Uns auseinanderzuleben" to "Si ay u kala baxaan",
    "Unser Intimleben" to "Nolosheenna dhow",
    "Unser Traumhaus" to "Gurigayaga riyada",
    "Unser erstes Treffen" to "Kulankeena kowaad",
    "Unsere Gesichter" to "Wajiyadayada",
    "Unsere eigenen Träume" to "Riyadayada gaarka ah",
    "Unsere nächste Reise" to "Safarkayaga xiga",
    "Unter 1000" to "Ka hooseeya 1000",
    "Unter 1000 im Monat" to "In ka yar 1000 bishii",
    "Unter 50€/Monat" to "Ka hooseeya 50€/bishii",
    "Unter Leuten" to "Dadka dhexdiisa",
    "Untreue" to "Gaalnimo",
    "Urlaub" to "Fasaxa",
    "Vanille" to "Vanilla",
    "Venedig" to "Venice",
    "Venedig, Italien" to "Venice, Italy",
    "Verbinde dich mit" to "Ku xidhnow",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Ku xidh \${profile.partnerName} si aad u aragto jawaabta",
    "Verbindung" to "ku xidhidh",
    "Verbringe die Feiertage mit deiner Familie" to "La bixi fasaxyada qoyskaaga",
    "Verlobungsringe" to "Faraantiga ka qaybgalka",
    "Vertrautheit" to "Aqoon",
    "Viel getrennt" to "Kala fogaansho badan",
    "Vielleicht ein oder zwei" to "Malaha hal ama laba",
    "Vielleicht, aber mündlich reicht" to "Waa laga yaabaa, laakiin hadal ayaa ku filan",
    "Vielleicht, wenn es machbar ist" to "Waxaa laga yaabaa, haddii ay suurtagal tahay",
    "Vielleicht, wenn es passt" to "Waxaa laga yaabaa, haddii ay ku habboon tahay",
    "Vintage Art déco" to "Vintage Art Deco",
    "Vintage verspielt" to "Ciyaarta canabka ah",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "In lammaanahaagu ku baro hiwaayad cusub",
    "Vor dem Kauf eines Hauses besprechen" to "Ka hadal intaadan guri iibsan",
    "Vor der Anschaffung eines Haustiers besprechen" to "Ka hadal ka hor intaadan iibsan xayawaanka rabaayada ah",
    "Vor der gemeinsamen Reise besprechen" to "Ka wada hadla intaadan u safrin",
    "Vor nichts" to "Waxba",
    "Vorort" to "Xaafad",
    "Walnuss" to "Walnut",
    "Wandern" to "Socodka",
    "Wann fühlst du dich mir am nächsten?" to "Goormaad dareentaa inaad iigu dhowdahay?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Goorma ayaad dareentaa inaad iigu dhowdahay jir ahaan?",
    "Was bedeutet Vertrauen für dich konkret?" to "Waa maxay kalsoonidu adiga gaar ahaan?",
    "Was entspannt dich mehr?" to "Maxaa intaa ka sii nasinaya?",
    "Was fehlt dir über die Distanz am meisten?" to "Maxaad inta badan ka tabanaysaa masaafada?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Maxaad ugu jeceshahay gurigaaga?",
    "Was hast du von deinem Partner gelernt?" to "Maxaad ka baratay lammaanahaaga?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Maxaad u malaynaysaa daawashada waxyaabaha kacsiga leh?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Maxaad u malaynaysaa agabka (tusaale calamadaha, buufinnada, iwm.)?",
    "Was ist das Wichtigste beim Antrag?" to "Waa maxay waxa ugu muhiimsan marka la codsanayo?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Waa maxay waxa ugu muhiimsan ee aad ka raadiso kulanka galmada?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Waa maxay sawirka aad noogu jeceshahay? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Waa maxay cabsidaada ugu weyn ee ku saabsan inaad wada noolaato?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Waa maxay cuntada aad jeceshahay balse lamaanahaagu aanu fahmi karin?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Waa maxay iibiyaha saxda ah adiga?",
    "Was ist für jeden von uns das absolute Highlight?" to "Waa maxay muujinta buuxda ee mid kasta oo inaga mid ah?",
    "Was ist passiert?" to "Maxaa dhacay?",
    "Was macht einen Moment für dich romantisch?" to "Maxaa kaa dhigaya daqiiqad jaceyl adiga?",
    "Was magst du an deinem Partner am liebsten?" to "Maxaad ugu jeceshahay lamaanahaaga?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Maxaad si ka wanaagsan u jeceshahay: goor hore oo aad kacdo ama aad soo daahdo?",
    "Was magst du lieber?" to "Kee baad jeceshahay ka wanaagsan?",
    "Was möchtest du eigentlich sagen?" to "Maxaad dhab ahaantii rabtaa inaad tiraahdo?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Maxaad jeclaan lahayd in lammaanahaagu uu sameeyo marar badan?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Maxaa ku dhacaya xayawaanka markaan safrayno?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Maxaa ku dhici doona ubadkeena markuu weynaado?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Maxaan waligeen lumin aragtida waalid ahaan?",
    "Was war dein schönster Moment mit mir bisher?" to "Maxay ahayd wakhtigaa kuugu fiicnayd ila hadda?",
    "Was wir gegessen haben" to "Waxa aanu cunnay",
    "Was wollt ihr nie vergessen?" to "Maxaadan weligaa rabin inaad illowdo?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Maxaa adiga kuugu daran: dib ha u dhigin pizza ama dib ha u dhigin?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Maxaad jeceshahay inaad sameyso maalin wadajir ah?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Maxaad isla markiiba bedeli lahayd haddii lacagtu aanay ahayn arrin?",
    "Weiter" to "Xiga",
    "Weiter spielen" to "Sii wad ciyaarista",
    "Weiß ich noch nicht" to "Ma garanayo weli",
    "Weiße Rosen" to "Ubax cad",
    "Weißgold" to "Dahab cad",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Waa maxay tayada ay tahay in uu ilmahaagu naga helo?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Deegaankee ayaad u doonaysaa soo jeedin?",
    "Welcher Raum sagt am meisten über dich aus?" to "Qolkee ayaa adiga kuugu badan?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Waa maxay miisaaniyada aanu u qorshaynaa cuntada iyo dhakhtarka xoolaha?",
    "Welches Lied macht dich an? 🥵" to "Heestee ayaa ku darinaysa? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Sawirkee la wadaaga ayaa aad ugu jeceshahay?",
    "Wellnessbad" to "Qubeyska fayoqabka",
    "Wenn es schwierig ist" to "Marka arrimuhu adag yihiin",
    "Wenn ich müde bin" to "Markaan daalanahay",
    "Wenn wir uns lange umarmen" to "Marka aan isku duubno waqti dheer",
    "Wenn wir zusammen lachen" to "Markaan wada qosno",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Yaa si degdeg ah u go'aaminaya waxa la dalbanayo?",
    "Wer findet die besten Restaurants?" to "Yaa hela maqaayadaha ugu fiican?",
    "Wer gibt mehr Herzlichkeit?" to "Yaa siiya diirimaad badan?",
    "Wer hat den besseren Musikgeschmack?" to "Kumaa ugu dhadhanka fiican muusiga?",
    "Wer hängt mehr an seinen Eltern?" to "Yaa aad ugu dheggan waalidkood?",
    "Wer ist besser organisiert?" to "Yaa si fiican u abaabulan?",
    "Wer ist der Beste bei der Filmauswahl?" to "Yaa ugu fiican doorashada filimada?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Yaa ugu fiican qorsheynta taariikhaha jaceylka?",
    "Wer ist der beste Tänzer?" to "Waa kee qoob ka ciyaarka ugu fiican?",
    "Wer ist romantischer?" to "Yaa ka jaceyl badan?",
    "Wer kocht besser?" to "Yaa si fiican wax u kariya?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Yaa daryeela dayactirka iyo dayactirka?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Yaa si degdeg ah u fiirsada marka qofka kale aanu ladnayn?",
    "Wer sucht am Ende wirklich den Film aus?" to "Yaa runtii doorta filimka dhamaadka?",
    "Wer vergisst eher einen Jahrestag?" to "Yaa u badan inuu iloobo sannad-guurada?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Yaa aad ugu dhow inuu ilaabo magacooda subaxda xiga?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Yaa aad ugu dhow inuu helo fiidiyoow maalinta xigta oo aysan waxba ka ogeyn?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Yaa jeclaan lahaa inuu habeenkii ku seexdo fadhiga qof qalaad?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Yaa aad ugu dhow inuu ku seexdo xaflad oo uu ku tooso Sharpie wejigooda?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Kumaa aad ugu dhow inuu ku dul simbiroobo sagxada qoob ka ciyaarka balse ka dhigaya mid u eg dhaqaaq fiican?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Yaa aad ugu dhow inuu gacanta ku dhigo liiska heesaha Spotify ee xaflad guri?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Kumaa aad ugu dhow inuu ka dalbado biisa qof walba xaflada oo uu isagu cuno?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Yaa u badan inuu marka hore seexdo xaflad?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Yaa aad ugu dhow inuu si lama filaan ah u nadiifiyo xaflad?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Yaa aad ugu dhow inuu sheegto inuu miyir qabo marka caksigeeda run tahay?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Yaa u badan inuu marka hore bixiyo dood?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Yaa u badan inuu khiyaaneeyo ciyaarta la cabbo?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Yaa aad ugu dhow inuu soo weeraro buffet-ka oo si qarsoodi ah cunto ugu qaado guriga?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Yaa aad ugu dhow inuu soo dhejiyo sawirka ugu ceebta badan fiidkii sheekadooda?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Yaa aad uga cadhaysiin lahaa DJ inuu codsado heesta ay jecel yihiin?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Yaa aad ugu heesi kara heesaha heesta furaha furaha ah, laakiin la xukumay?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Yaa aad ugu dhow inuu dalbado cabitaanka ugu qaalisan liiska oo ka shallayn lahaa?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Yaa u badan inuu ku martiqaado deriska hadday ka cawdaan buuqa?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Yaa si dhab ah ugu qaadan lahaa ciyaaraha xaflada (sida Beer Pong)?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Yaa aad ugu dhow inuu la saaxiibo bouncers si ay u helaan VIP-da?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Yaa aad ugu dhow inuu bilaabo dagaal karaoke iskiis ah?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Yaa u badan inuu furo dhalo isagoon isticmaalin furaha dhalada?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Yaa aad ugu dhow inuu khudbad jeediyo in kasta oo aan gabi ahaanba cidina waxba weydiin?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Yaa aad ugu dhow inuu saacad ku qaato musqusha isagoo iska sawiraya?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Yaa aad ugu dhow inuu soo bandhigo bandhig qoob ka ciyaar ceeb ah oo u dabaaldego?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Yaa aad ugu dhow inuu waco lammaanihii hore ka dib marka xafladda dhammaato?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Yaa aad ugu dhow inuu si lama filaan ah u xumeeyo marti qariib ah?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Yaa u badan inuu si qarsoodi ah uga tago xisbiga isagoon macsalaamayn?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Yaa doorbidi lahaa inuu la ciyaaro xayawaanka martida loo yahay intuu la hadli lahaa martida?",
    "Wer würde eher spontan eine Reise buchen?" to "Yaa aad ugu dhow inuu ballansamo safar iskiis ah?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Yaa aad ugu dhow inuu saacado badan kula sheekaysto jikada dhexdeeda?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Yaa u badan inuu si lama filaan ah u cabbo cabitaan qof kale?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Yaa aad ugu dhow inuu si lama filaan ah u garaaco weel qaali ah ama shay jilicsan?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Kumaa aad ugu dhow inay isku dayaan inay isku daraan cocktail adag laftooda oo ay si xun u fashilmaan?",
    "Wer würde eher zu spät kommen?" to "Yaa u badan inuu soo daaho?",
    "Wer würde eher?" to "Yaa doorbidi lahaa?",
    "Wer übernimmt die tägliche Versorgung?" to "Yaa daryeela daryeelka maalinlaha ah?",
    "Werde so akzeptiert, wie du bist" to "Laguu aqbal sidaad tahay",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Ma heli doonaa wakhti ku filan ilmaha/carruurta? ⏳",
    "Whirlpool" to "Webiga kulul",
    "White Chocolate" to "Shukulaato cad",
    "Widgets" to "Widgets",
    "Wie fühlst du dich am meisten geliebt?" to "Sidee u aragtaa in lagugu jecel yahay?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Sideen ula macaamilnaa dakhliyada kala duwan?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Waa maxay habka ugu wanagsan ee lamaanahaaga uu kula bilaabo galmo?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Sidee buu lammaanahaagu kuugu noqon karaa lammaane ka sii wanaagsan?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Muddo intee le'eg ayaa soo jeedinta ka dib aad doonaysaa inaad dadka kale la dabbaaldegto?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Ilaa intee ayaan rabnaa inaan halkaas sii joogno ugu yaraan?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Sidee bay kuugu fududahay inaad ka hadasho rabitaanka?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Maxaad doonaysaa in mustaqbalkayagu u ekaado?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Sidee bay u egtahay axadaada qumman ee guriga?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Sidee u aragtaa hadalka wasakhaysan xilliga galmada?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Intee in le'eg ayaynu si dhab ah u awoodi karnaa?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Intee in le'eg ayaynu rabnaa inaan kala maqno?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Intee in le'eg ayaan rabnaa inaan ku bixinno wadar ahaan?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Sideen waqti ugu helnaa xiriirkeena marka ilmuhu yimaado?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Sidee ayay muhiim kuugu tahay in wakhtiga la qabtay?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Sidee buu muhiim kuugu yahay in codsigu ka tarjumo waxyaabaha aad xiiseyso?",
    "Wie würdest du sie/ihn nennen?" to "Maxaad ugu yeedhi lahayd isaga/iyada?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Waa maxay habka aad ugu jeceshahay inaad u muujiso jacayl ka baxsan galmada?",
    "Wildblumen" to "Ubaxyada duurjoogta ah",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Ma rabtaa gabadh ama wiil? 👶",
    "Wintergarten" to "Beerta jiilaalka",
    "Winterhochzeit" to "Aroos jiilaal",
    "Wir bestellen einfach beides" to "Kaliya waxaan dalbanaa labadaba",
    "Wir brauchen ewig" to "Wey nagu qaadataa waligaa",
    "Wir einigen uns nie" to "Marna ma ogolin",
    "Wir entscheiden es gemeinsam" to "Si wadajir ah ayaan u go'aansannay",
    "Wir treffen uns in der Mitte" to "Waxaan ku kulmaynaa bartamaha",
    "Wir wechseln uns ab" to "Waxaan qaadanaa markooda",
    "Wird stressig" to "Walaaca",
    "Wobei lachst du am meisten?" to "Maxaa kaa qosli kara?",
    "Wofür sparen wir gemeinsam?" to "Maxaan u wada badbaadinaa?",
    "Wohnzimmer" to "Qolka fadhiga",
    "Woran erinnerst du dich am lebhaftesten?" to "Maxaad si cad u xasuusataa?",
    "Worauf freust du dich bei uns am meisten?" to "Maxaad aadka noogu sugaysaa?",
    "Worte/Komplimente" to "Kelmado/Bogaadin",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Maxaad ugu baqaysaa xiriirkayaga?",
    "Wünsche? z.B. günstig, draußen" to "rabitaanno? tusaale. jaban, dibadda",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Ma doorbidi lahayd inaad soo jeediso fasaxa (ku lug leh safarka)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "Muusiga YouTube",
    "Zeichne für mich" to "I sawir",
    "Zeichne mich als Tier — welches wäre ich?" to "I sawir sida xayawaanka - kee baan noqon lahaa?",
    "Zeichne unser Gefühl zueinander als Symbol." to "U sawir dareenkeena dhanka kale calaamad ahaan.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Ku sawir gurigayaga riyada hal sadar. Waa maxay waxa ugu yaabka badan?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Sawir taariikhdayada koowaad - maxaa xaqiiqdii u baahan in sawirka ku jira?",
    "Zeichnen" to "Barbardhac",
    "Zeit füreinander" to "Waqtiga midba midka kale",
    "Zeit, wenn das Baby schläft" to "Waqtiga ilmuhu seexdo",
    "Zelten gehen" to "Tag xero",
    "Zitrone" to "Liin dhanaan",
    "Zu Hause, gemütlich und privat" to "Guriga, raaxo leh oo gaar ah",
    "Zu einem Picknick gehen" to "Tagitaanka dalxiis",
    "Zu einem ausgefallenen Abendessen gehen" to "Aada casho qurxoon",
    "Zu zweit reisen" to "U safra lamaane ahaan",
    "Zuhause & Alltag" to "Guriga & nolol maalmeedka",
    "Zuhören" to "Dhageyso",
    "Zurück" to "Dib u noqo",
    "Zusammen seit" to "Wadajir tan iyo",
    "Zusammen seit (TT.MM.JJJJ)" to "Wada jir ilaa (DD.MM.YYY)",
    "Zusammenziehen" to "Qandaraas",
    "Zustimmen oder Ablehnen" to "Oggol ama diid",
    "Zwei Kreise, die sich überschneiden" to "Laba wareeg oo is dul saaran",
    "Zwei Stühle davor" to "Laba kursi ayaa hortiisa yaal",
    "Zärtlich sein" to "Noqo hindise",
    "Öfter als ich zugebe" to "Waqtiyo ka badan inta aan qirto",
    "Über 100€/Monat" to "In ka badan 100€/bishii",
    "Über 2000 im Monat" to "In ka badan 2000 bishii",
    "Über mich selbst" to "Ku saabsan naftayda",
    "Übernehmen" to "Codso",
    "Überraschend" to "yaab leh",
    "Überraschung" to "Yaab",
    "Überspringen" to "Ka bood",
    "Übertrieben und großartig" to "Ka sarreeya oo cajiib ah",
    "✎ Tippe, um zu antworten" to "✎ Taabo si aad uga jawaabto",
    "✨ GFK-Brücke" to "✨ buundada GRP",
)

internal fun localizeSomaliDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_SOMALI_CONTENT)
