package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_SWAHILI_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "Miaka 1-5",
    "1000 - 1500 im Monat" to "1000 - 1500 kwa mwezi",
    "1000 bis 3000" to "1000 hadi 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 kwa mwezi",
    "3000 bis 5000" to "3000 hadi 5000",
    "5-10 Jahre" to "Miaka 5-10",
    "50-100€/Monat" to "50-100€/mwezi",
    "Ab 100€" to "Kutoka 100€",
    "Ab 500€" to "Kutoka 500€",
    "Ab 50€" to "Kutoka 50€",
    "Ab und zu" to "Kila mara",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Tunahitaji kutumia kiasi gani kabla ya kufanya ununuzi?",
    "Abbrechen" to "Ghairi",
    "Abenteuer" to "Vituko",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Shughuli",
    "Alle" to "Zote",
    "Alle Pakete" to "Vifurushi vyote",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Wapoteze marafiki zako wote isipokuwa rafiki yako wa karibu",
    "Alle intimen Momente selbst initiieren" to "Anzisha matukio yote ya karibu wewe mwenyewe",
    "Alles davon" to "Yote",
    "Alles, was noch kommt" to "Kila kitu kitakachokuja",
    "Alltagsroutine" to "Utaratibu wa kila siku",
    "Alltägliche Berührungen" to "Miguso ya kila siku",
    "Altbau mit Charme" to "Jengo la zamani lenye haiba",
    "Am Strand" to "Ufukweni",
    "Am liebsten alles zusammen" to "Ikiwezekana kila kitu pamoja",
    "Am selben Tag mit Freunden/Familie" to "Siku hiyo hiyo na marafiki/familia",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Uholanzi",
    "An das Gefühl" to "Ya hisia",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "Katika sehemu ya umma yenye watazamaji wengi",
    "An einen Geruch" to "Ya harufu",
    "An einen Song" to "Kwa wimbo",
    "An etwas, das ich gesagt habe" to "Kitu nilichosema",
    "Analyse starten" to "Anza uchanganuzi",
    "Analysiere eure Muster..." to "Changanua ruwaza zako...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Changanua majibu na gumzo zako kulingana na Gottman na GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Nanasi kwenye pizza ladha tamu.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Jibu kwa picha",
    "Antwortähnlichkeit" to "Jibu kufanana",
    "App-Sprache auswählen" to "Chagua lugha ya programu",
    "Auf eine Bootsparty gehen" to "Kwenda kwenye karamu ya mashua",
    "Aufmerksamkeit" to "Makini",
    "Aufräumen und Projekte angehen" to "Safisha na ushughulikie miradi",
    "Aufwärmen" to "Pasha joto",
    "Aufwärmen: Einander kennenlernen" to "Kuongeza joto: Kufahamiana",
    "Aus dem Urlaub" to "Kutoka likizo",
    "Ausgefallener Name" to "Jina zuri",
    "Ausschlafen und faulenzen" to "Lala ndani na ulegee",
    "Ausschlafen und nichts tun" to "Lala ndani na usifanye lolote",
    "Aussehen" to "Muonekano",
    "Auto" to "Otomatiki",
    "Außenkamin" to "Sehemu ya moto ya nje",
    "BEANTWORTE" to "JIBU",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonesia",
    "Banane" to "Ndizi",
    "Beantwortet" to "Imejibu",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Jibu maswali kwa wakati mmoja — majibu hayataonekana hadi nyinyi wawili mumalize.",
    "Beantwortete Fragen" to "Maswali yaliyojibu",
    "Bearbeiten" to "Hariri",
    "Bei Insider-Witzen" to "Kwa vicheshi vya ndani",
    "Bei Memes" to "Kwenye meme",
    "Bei einer spontanen Berührung" to "Inapoguswa moja kwa moja",
    "Beide" to "Zote mbili",
    "Beide gleich" to "Zote mbili sawa",
    "Beide zusammen" to "Zote kwa pamoja",
    "Beide, aber wir tun so als ob nicht" to "Zote mbili, lakini tunajifanya kuwa hatufanyi hivyo",
    "Beides" to "Zote mbili",
    "Beides wäre schlimm" to "Zote mbili zitakuwa mbaya",
    "Beim Einschlafen nebeneinander" to "Kulala karibu na kila mmoja",
    "Beim Reden" to "Wakati wa kuzungumza",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Maeneo maarufu ya watalii huwa ya kukatisha tamaa kila wakati.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Eleza maisha yetu ya ngono kwa emoji.",
    "Besser kommunizieren" to "Wasiliana vyema zaidi",
    "Bessere Lage" to "Mahali pazuri zaidi",
    "Bestellen" to "Agizo",
    "Besuchte Länder" to "Nchi zilizotembelewa",
    "Besuchte Städte" to "Miji iliyotembelewa",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Je, unapendelea pendekezo la kupita kiasi au jambo lisiloeleweka?",
    "Beziehung" to "Uhusiano",
    "Bibliothek" to "Maktaba",
    "Bin manchmal unsicher" to "Wakati mwingine mimi si salama",
    "Bist du ein Videospiel-Guru?" to "Je, wewe ni gwiji wa mchezo wa video?",
    "Blumenwiese" to "Meadow ya maua",
    "Bunte Blumenwiese" to "Meadow ya maua yenye rangi ya kuvutia",
    "Burger" to "Burgers",
    "Burger King" to "Burger King",
    "Chat" to "Soga",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Unga wa Vidakuzi",
    "Dachgarten mit Lounge" to "Bustani ya paa yenye sebule",
    "Dachterrasse" to "Mtaro wa paa",
    "Das Wetter an dem Tag" to "Hali ya hewa siku hiyo",
    "Das erste Selfie" to "Selfie ya kwanza",
    "Das meiste weiß ich" to "Ninaijua zaidi",
    "Das oder das?" to "Hii au ile?",
    "Das tägliche Leben" to "Maisha ya kila siku",
    "Dass Zusagen gehalten werden" to "Ahadi hizo hutimizwa",
    "Dass alles meinen Stil hat" to "Kwamba kila kitu kina mtindo wangu",
    "Dass ich alles erzählen kann" to "Kwamba naweza kusema kila kitu",
    "Dass ich mich nicht sorgen muss" to "Kwamba sihitaji kuwa na wasiwasi",
    "Dass wir ungestört sind" to "Kwamba hatuna usumbufu",
    "Dein Name" to "Jina lako",
    "Deine Antwort..." to "Jibu lako...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Majibu yako yamehifadhiwa. Mshirika akishamaliza kifurushi, majibu yote mawili yataonekana pamoja.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Majibu yako yamehifadhiwa. Mara baada ya \${profile.partnerName} kukamilisha kifurushi, majibu yote mawili yataonekana kwa pamoja.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Fanya uhusiano wako kuwa wa kuvutia na wa hiari",
    "Deine Beziehung stabil und sicher machen" to "Fanya uhusiano wako uwe thabiti na salama",
    "Deine eigene Antwort" to "Jibu lako mwenyewe",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Ni bora kushiriki siri zako za kina na mpenzi wako",
    "Deinen besten Freund verlieren" to "Kupoteza rafiki yako bora",
    "Denke an dich" to "Jifikirie mwenyewe",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Kutazama filamu moja mara mbili ni kupoteza muda.",
    "Der Blick nach draußen" to "Mwonekano wa nje",
    "Der Garten" to "Bustani",
    "Der Ort" to "Mahali",
    "Der Ring und die Geste" to "Pete na ishara",
    "Der perfekte Heiratsantrag" to "Pendekezo kamili la ndoa",
    "Derjenige sein, der umarmt wird" to "Kuwa wewe unayekumbatiwa",
    "Deutsch" to "Kijerumani",
    "Diamant" to "Almasi",
    "Diamanten im Band" to "Almasi kwenye bendi",
    "Die Distanz" to "Umbali",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Tumia likizo pamoja na familia ya mwenza wako",
    "Die Gemütlichkeit und Ruhe" to "Faraja na amani",
    "Die Menschen, die darin wohnen" to "Watu wanaoishi humo",
    "Die Umgebung und Atmosphäre" to "Mazingira na angahewa",
    "Die Worte und Emotionen" to "Maneno na hisia",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Changamoto kuu ya trivia ya burudani",
    "Diejenige sein, die umarmt" to "Kuwa mtu anayekumbatiana",
    "Direkt ansprechen" to "Anwani moja kwa moja",
    "Diskussion" to "Majadiliano",
    "Diskutiere vor dem Kinderkriegen" to "Jadili kabla ya kupata watoto",
    "Diskutiert eure Antworten" to "Jadili majibu yako",
    "Disney" to "Disney",
    "Doch, schon mal" to "Ndiyo, ndiyo",
    "Draußen mit der Natur als Kulisse" to "Nje na asili kama mandhari",
    "Drei-Stein-Ring" to "Pete tatu za mawe",
    "Du bist dran" to "Ni zamu yako",
    "Du fehlst mir" to "Nimekukumbuka",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubai, UAE",
    "Dunkles Design" to "Mandhari meusi",
    "Durch Berührung" to "Kwa kugusa",
    "Durch Worte" to "Kupitia maneno",
    "Durch Zeit zu zweit" to "Kupitia muda wa pamoja",
    "Durch kleine Gesten" to "Kupitia ishara ndogo",
    "Durchgeplant" to "Imepangwa vizuri",
    "ERGEBNISSE" to "MATOKEO",
    "Egal, Hauptsache gesund" to "Vyovyote vile, jambo kuu ni afya",
    "Ehepaar Leben" to "Maisha ya wanandoa",
    "Eher knapp" to "Badala yake karibu",
    "Eher nicht" to "Sio sana",
    "Eher schwer" to "Ni ngumu zaidi",
    "Eher schwierig" to "Ni ngumu zaidi",
    "Eher zu" to "Zaidi kama",
    "Eifersucht ist ein Zeichen von Liebe." to "Wivu ni ishara ya upendo.",
    "Eigenes Gemüsebeet" to "Kiraka cha mboga mwenyewe",
    "Ein Abenteuer in einer neuen Stadt" to "Tukio katika jiji jipya",
    "Ein Anker" to "Nanga",
    "Ein Balkon oder Garten" to "Balcony au bustani",
    "Ein Filmabend" to "Usiku wa filamu",
    "Ein Harmony-Meilenstein eurer Liebe." to "Hatua muhimu ya maelewano ya upendo wako.",
    "Ein Herz" to "Moyo",
    "Ein Herz an der Tür" to "Moyo mlangoni",
    "Ein Jahr lang eine Fernbeziehung führen" to "Kuwa na uhusiano wa masafa marefu kwa mwaka mmoja",
    "Ein Kindheitsessen" to "Mlo wa utotoni",
    "Ein Live-Musik-Konzert besuchen" to "Hudhuria tamasha la muziki la moja kwa moja",
    "Ein Museum besuchen" to "Tembelea jumba la makumbusho",
    "Ein Spieleabend" to "Usiku wa mchezo",
    "Ein Spieleabend mit Freunden" to "Usiku wa mchezo na marafiki",
    "Ein Urlaubsfoto" to "Picha ya likizo",
    "Ein aktives Abenteuer" to "Matukio ya kusisimua",
    "Ein entspannender Spa-Tag" to "Siku ya mapumziko ya spa",
    "Ein ganz normaler Alltagstag" to "Siku ya kawaida kabisa ya kila siku",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Jioni tulivu ndani ya nyumba wakati wa mvua ya radi",
    "Ein gemütliches Date drinnen" to "Tarehe ya kupendeza ndani ya nyumba",
    "Ein lustiges Bild" to "Picha ya kuchekesha",
    "Ein paar Handyfotos reichen" to "Picha chache za simu ya mkononi zinatosha",
    "Ein paar Stunden" to "Saa chache",
    "Ein paar kulturelle Anklänge sind okay" to "Marejeleo machache ya kitamaduni ni sawa",
    "Ein romantischer Abend" to "Jioni ya mapenzi",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Chakula cha jioni cha kimapenzi cha mishumaa",
    "Ein romantisches Bild" to "Picha ya kimapenzi",
    "Ein romantisches Picknick an einem schönen Ort" to "Pikiniki ya kimapenzi katika eneo zuri",
    "Ein schwerer Moment, den wir geschafft haben" to "Wakati mgumu ambao tuliweza",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Tarehe nzuri nje ya mwanga wa mwezi",
    "Ein ungewöhnliches Gericht" to "Mlo usio wa kawaida",
    "Ein zufälliger Schnappschuss" to "Picha ya nasibu",
    "Einander kennenlernen" to "Kufahamiana",
    "Eine Autoreise" to "Safari ya barabarani",
    "Eine Brücke" to "Daraja",
    "Eine Date-Nacht unter den Sternen" to "Usiku wa tarehe chini ya nyota",
    "Eine Million Dollar gewinnen" to "Shinda dola milioni moja",
    "Eine Million Dollar verdienen" to "Pata dola milioni moja",
    "Eine Nacht in einem Club" to "Usiku katika kilabu",
    "Eine Schokoladenverkostung" to "Kuonja chokoleti",
    "Eine Wanderung mit Panoramablick machen" to "Chukua matembezi ukiwa na mitazamo ya mandhari",
    "Eine Weinverkostung" to "Kuonja divai",
    "Eine gemeinsame Reise" to "Safari ya pamoja",
    "Eine gemütliche Nacht zu Hause" to "Usiku tulivu nyumbani",
    "Eine neue Sprache zu lernen ist einfach." to "Kujifunza lugha mpya ni rahisi.",
    "Einen Film anschauen" to "Tazama filamu",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Bila kuzungumza na kila mmoja kwa mwezi",
    "Einen Tanzkurs besuchen" to "Chukua darasa la dansi",
    "Einen Vergnügungspark erkunden" to "Gundua bustani ya burudani",
    "Einen Wellness-Tag" to "Siku ya afya njema",
    "Einen sehr emotionalen Partner haben" to "Kuwa na mpenzi mwenye hisia sana",
    "Einen sehr logischen Partner haben" to "Kuwa na mshirika mwenye mantiki sana",
    "Einer zahlt alles" to "Mtu mmoja hulipa kila kitu",
    "Einfach mehr Alltag" to "Kwa urahisi zaidi maisha ya kila siku",
    "Einfach nebeneinander sein" to "Kuweni karibu na kila mmoja",
    "Einfach und intim" to "Rahisi na ya karibu",
    "Einige Dinge für dich behalten" to "Weka baadhi ya mambo kwako",
    "Einmal" to "Mara moja",
    "Eins, das nur wir kennen" to "Moja ambayo sisi tu tunaijua",
    "Englisch" to "Kiingereza",
    "Entspannte Hängematte" to "Hammoki iliyotulia",
    "Entspannung" to "Kupumzika",
    "Erdbeere" to "Strawberry",
    "Erfolgreich" to "Imefaulu",
    "Ergebnisse" to "Matokeo",
    "Erst bei sehr großen Summen" to "Kwa kiasi kikubwa sana pekee",
    "Erst nur enge Freunde/Familie" to "Marafiki wa karibu/familia pekee mwanzoni",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Huniudhi mwenzangu anapochukua muda mrefu kujibu ujumbe.",
    "Essen & Genuss" to "Chakula na starehe",
    "Essensvorlieben" to "Mapendeleo ya chakula",
    "Etwa eine Woche später, erst mal nur wir" to "Takriban wiki moja baadaye, sisi tu mwanzoni",
    "Etwas Neues ausprobieren" to "Jaribu kitu kipya",
    "Etwas ganz anderes" to "Kitu tofauti kabisa",
    "Etwas sehr Scharfes" to "Kitu kikali sana",
    "Etwas, das ich selbst gern erfinde" to "Kitu ninachopenda kubuni mwenyewe",
    "Etwas, eine kleine Note wäre schön" to "Kitu, dokezo dogo litakuwa zuri",
    "Familie" to "Familia",
    "Familie/Freunde" to "Familia/Marafiki",
    "Familienmensch" to "Mwanafamilia",
    "Farbedelstein" to "Mawe ya vito ya rangi",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Matangazo ya televisheni wakati fulani huvutia kutazama.",
    "Fertig" to "Imekamilika",
    "Fertig!" to "Imekamilika!",
    "Feste Date-Nights" to "Tarehe zisizohamishika za usiku",
    "Feuerstelle" to "Shimo la moto",
    "Filigran & schlicht" to "Filigree & simple",
    "Filme/Serien" to "Filamu/mfululizo",
    "Formuliere um..." to "Tamka upya...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Andika upya rasimu yako kwa njia isiyo ya vurugu: uchunguzi, hisia, hitaji, ombi.",
    "Frage hinzufügen" to "Ongeza swali",
    "Fragen & Spiele" to "Maswali na Michezo",
    "Fragen für jede Gelegenheit" to "Maswali kwa kila tukio",
    "Freizeitpark" to "Bustani ya burudani",
    "Freunde treffen" to "Kutana na marafiki",
    "Freundschaften mit Ex-Partnern sind okay." to "Urafiki na watu wa zamani ni sawa.",
    "Früh aufstehen" to "Amka mapema",
    "Fußbodenheizung" to "Kupasha joto chini ya sakafu",
    "Führen wir getrennte oder gemeinsame Konten?" to "Je, tuna akaunti tofauti au za pamoja?",
    "Für dich empfohlen" to "Imependekezwa kwako",
    "Für die Zukunft" to "Kwa siku zijazo",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Hakuna maswali au michezo inayolingana iliyopatikana kwa utafutaji huu.",
    "Für immer" to "Milele",
    "Fürsorglichkeit" to "Kujali",
    "GFK-Brücke" to "daraja la GRP",
    "Galerie" to "Matunzio",
    "Gar nicht, der Moment gehört uns" to "Hata kidogo, wakati ni wetu",
    "Gar nichts tun" to "Usifanye chochote",
    "Geduld" to "Subira",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Nenda mapema asubuhi ili uone mawio ya jua",
    "Geht so" to "Huenda hivi",
    "Geister existieren wirklich." to "Mizimu ipo kweli.",
    "Gelassenheit" to "Utulivu",
    "Gelbgold" to "Dhahabu ya manjano",
    "Geld & Finanzen" to "Pesa na Fedha",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Safiri ulimwenguni pamoja, chunguza tamaduni na vyakula vipya",
    "Gemeinsam ein Lego bauen" to "Jenga Lego pamoja",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Jaribu mapishi mapya pamoja jikoni",
    "Gemeinsame Konten" to "Akaunti zinazoshirikiwa",
    "Gemeinsame Nächte" to "Usiku pamoja",
    "Gemeinsame Tage" to "Siku pamoja",
    "Gemischt" to "Mchanganyiko",
    "Gemüsebeet" to "Kiraka cha mboga",
    "Gemütliche Feuerstelle" to "Mahali pazuri pa moto",
    "Gesprächsanreger" to "Kianzilishi cha mazungumzo",
    "Getrennte Konten" to "Tenganisha akaunti",
    "Getrennte Urlaube tun einer Beziehung gut." to "Likizo tofauti ni nzuri kwa uhusiano.",
    "Gewächshaus" to "Greenhouse",
    "Glasfassade" to "Ukuzaji wa glasi",
    "Gleichgültigkeit" to "Kutojali",
    "Glücklich und frei" to "Furaha na bila malipo",
    "Gourmet Eis-Sorten" to "Aina za aiskrimu za kupendeza",
    "Gravur innen" to "Inachonga ndani",
    "Grillplatz" to "Eneo la nyama choma",
    "Groß & üppig" to "Kubwa na maridadi",
    "Große Familie" to "Familia kubwa",
    "Große Feier" to "Sherehe kubwa",
    "Große Fenster" to "Dirisha kubwa",
    "Große Fensterfront" to "Dirisha kubwa la mbele",
    "Großer Außenpool" to "Bwawa kubwa la nje",
    "Großer Garten" to "Bustani kubwa",
    "Großer Stein" to "Jiwe kubwa",
    "Größere Küche" to "Jikoni kubwa zaidi",
    "Gutes Essen" to "Chakula kizuri",
    "Habe ich" to "Nilifanya hivyo",
    "Habe ich noch nie" to "Sijawahi",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Je, umegundua tofauti zozote za kushangaza? Ongea kuhusu kwa nini unapenda chaguo fulani bora!",
    "Haus am See" to "Nyumba karibu na ziwa",
    "Haus/Wohnung" to "Nyumba/ghorofa",
    "Hazelnut" to "Hazelnut",
    "Heimkino" to "Ukumbi wa michezo wa nyumbani",
    "Herzhaft" to "Ya moyoni",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Hakuna kitu hapa kwa sasa.\nBadilisha kichujio au uchague mada tofauti.",
    "Hilfe im Alltag" to "Msaada katika maisha ya kila siku",
    "Himbeere" to "Raspberry",
    "Hinzufügen" to "Ongeza",
    "Hobbys" to "Hobbies",
    "Hochzeitssträuße" to "Maua ya harusi",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Hogwarts House Pride: Where Do You Belong?",
    "Home" to "Nyumbani",
    "Hot Tub" to "Bafu ya Moto",
    "Humor" to "Ucheshi",
    "Hund" to "Mbwa",
    "Hängematte" to "Hammock",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Je, ungependa barua iliyoandikwa kama sehemu ya pendekezo?",
    "IKEA" to "IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Ninapendelea matembezi ya kimapenzi katika bustani badala ya kwenda kwenye sinema.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Sijawahi kusinzia katika ukumbi wa sinema.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Ninafurahia kugundua mambo mapya au shughuli na mwenzangu.",
    "Ich finde eine Alternative" to "Nitapata njia mbadala",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Ninafurahia kujaribu mikahawa mipya na mshirika wangu badala ya kwenda sehemu moja kila wakati.",
    "Ich habe noch nie" to "Sijawahi",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Sijawahi kuogopa roller coaster na hata hivyo niliipanda.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Sijawahi kununua tikiti za Fast Pass kwa sababu sikuwa na subira.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Sijawahi kughairi mipango ya kukaa nyumbani na kutazama kipindi cha televisheni.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Sijawahi kungoja barua yangu kutoka Hogwarts.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Sijawahi kusema kwamba Slytherin hakuwa mbaya hivyo.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Sijawahi kusema nilikuwa mzee sana kwa filamu za Disney (na nilizifurahia kwa siri).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Sijawahi kumpiga mtu kimakusudi kwa tanki la bluu huko Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Sijawahi kulia kwenye filamu ya Disney.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Sijawahi kufunika macho yangu wakati nikitazama filamu ya kutisha.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Sijawahi kusahau kuokoa mchezo na kupoteza saa za kucheza.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Sijawahi kutoka chumbani wakati wa tukio la aibu (kigeugeu).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Sijawahi kufanya mkao wa kuchekesha wakati nikipiga picha ya rollercoaster.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Sijawahi kucheza hadi usiku na nilijuta jinsi nilivyochoka siku iliyofuata.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Sijawahi google mwisho wa filamu kwa sababu sikuweza kusubiri.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Sijawahi kuhisi kama nilikuwa nimesimama kwenye seti ya filamu.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Sijawahi kuruka utangulizi wa mfululizo ninaoupenda.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Sijawahi kushiriki nenosiri la Netflix la mtu mwingine yeyote.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Sijawahi kusikiliza wimbo wa mchezo nikifanya kazi au kusoma.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Sijawahi kulaumu kidhibiti nilipopoteza.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Sijawahi kutupa kibodi au kidhibiti kwa hasira.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Sijawahi kusahau nguo zilizolowa kwenye mashine ya kufulia kwa siku chache.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Sijawahi kutumia pesa halisi kununua vipodozi katika mchezo.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Sijawahi kuendesha gari katika nchi ya kigeni.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Sijawahi kushinda wimbo wa Disney kwenye bafu.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Sijawahi kuendesha gari la umeme.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Sijawahi kupiga picha na mbuga.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Sijawahi kumtaja mnyama kipenzi baada ya mhusika Hogwarts.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Sijawahi kudondosha popcorn kwenye jumba la sinema na bado nikazila.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Sijawahi kutumia nukuu kutoka kwa Master Yoda kutoka Star Wars katika maisha ya kila siku.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Sijawahi kununua zawadi ya bei ya juu katika bustani ya mandhari.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Sijawahi kutoa pendekezo la filamu ambalo mtu mwingine aliona kuwa mbaya.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Sijawahi kutazama Tuzo za Oscar moja kwa moja katikati ya usiku.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Sijawahi kughairi mfululizo kwa sababu msimu uliopita ulikuwa mbaya sana.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Sijawahi kutazama sana msimu mzima wa mfululizo kwa siku moja.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Sijawahi kumshinda bosi kwenye jaribio la kwanza na kujisikia kama mungu.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Sijawahi kupata mtu mbaya kuliko shujaa.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Sijawahi kumtambua mhusika wa Hadithi ya Toy katika vifaa vyangu vya kuchezea.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Sijawahi kutengeneza mhusika katika RPG kama mimi.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Sijawahi kula churro kwenye bustani ya mandhari.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Sijawahi kutazama filamu ya Disney mara tatu mfululizo.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Sijawahi kuwa na wimbo wa kuvutia wa Disney kwa wiki nzima.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Sijawahi kutazama filamu kwa sababu tu ya mwigizaji fulani.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Sijawahi kusikiliza wimbo wa filamu unaorudiwa kwa saa nyingi.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Sijawahi kufichua kiharibu filamu na mara moja nikajuta.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Sijawahi kupata rafiki ambaye anazungumza lugha nyingine ya asili.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Sijawahi kuwa na rafiki ambaye alihamia nchi nyingine.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Sijawahi kufanya marathoni ya filamu ya Harry Potter wakati wa Krismasi.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Sijawahi kutazama filamu ya Marvel hadi mwisho kwa sababu tu ya tukio la baada ya mkopo.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Sijawahi kukasirisha NPC kwa makusudi (Mhusika Asiye Mchezaji).",
    "Ich habe noch nie einen Nachtzug genommen." to "Sijawahi kupanda treni ya usiku.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Sijawahi kufanya jaribio la mtandaoni ili kujua nyumba yangu ya Hogwarts.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Sijawahi kufuta chapisho la mtandao wa kijamii kwa sababu halijawapendeza vya kutosha.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Sijawahi kuita siku moja kwenye bustani ya mandhari siku bora zaidi ya mwaka.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Sijawahi kutembelea bustani ya mandhari na kukaa hapo kuanzia asubuhi hadi usiku.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Sijawahi kuacha safari ya Transfoma au Marvel nikivutiwa kabisa.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Sijawahi kuacha hasira na kuacha mchezo.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Sijawahi kusoma juzuu zozote za Harry Potter.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Sijawahi kutusi kuhusu mhusika ninayempenda katika mfululizo.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Sijawahi kuota kucheza Quidditch.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Sijawahi google kwa siri jinsi ya kutatua kiwango kigumu.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Sijawahi kutumaini kwa siri kwamba kipenzi changu angeweza kuzungumza kama katika Disney.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Sijawahi kumwondoa kiongozi wa bwawa katika Sims.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Sijawahi kupoteza fani zangu katika safari ya kiigaji cha 3D.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Sijawahi kucheza kwenye timu ya michezo ya chuo kikuu.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Sijawahi kusubiri kwenye foleni kwa zaidi ya saa mbili kwa kivutio kimoja.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Sijawahi kupata vitu vyangu vya thamani kwenye safari ya maji.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Sijawahi kugombana na rafiki kuhusu ni nyumba ipi iliyo bora zaidi.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Sijawahi kujifanya kuwa na nguvu za kichawi kama Elsa.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Sijawahi kucheka sana hivi kwamba nilikosa tukio muhimu katika filamu.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Sijawahi kuhisi adrenaline nyingi hivi kwamba nilitaka kupanda tena mara moja.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Sijawahi kujaribu kuimba na wanyama kama Snow White.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Sijawahi kuota kuhusu safari ya kwenda Disneyland.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Sijawahi kuota kuhusu kupanda majini kwenye Jurassic Park.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Sijawahi kupiga kelele kwa sauti ya kutisha katika mchezo.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Sijawahi kulia kuhusu mwisho wa kipindi cha televisheni.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Sijawahi... kughairi tarehe ya kukaa nyumbani.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Sijawahi... kutafsiri tena ujumbe mara 10.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Sijawahi... nilitazama kwa siri simu ya mwenzangu.",
    "Ich habe noch nie!" to "Sijawahi!",
    "Ich habe!" to "Ninayo!",
    "Ich lache viel mit meinem Partner." to "Ninacheka sana na mwenzangu.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Ninapenda kujua mambo anayopenda na mapendeleo ya mwenzangu.",
    "Ich liebe es" to "Ninaipenda",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Ninapenda kutazama filamu na mwenzangu ambazo hakuna hata mmoja wetu aliyewahi kuona hapo awali.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Ninapenda kushiriki muziki ninaoupenda na mshirika wangu.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Sijawahi kulazimika kukimbia ili kupata ndege inayounganisha.",
    "Ich plane gerne Dates mit meinem Partner." to "Ninapenda kupanga tarehe na mshirika wangu.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Ninatanguliza kutumia wakati na mwenza wangu hata ninapokuwa na shughuli nyingi.",
    "Ich schreibe meinem Partner jeden Tag." to "Humtumia mpenzi wangu SMS kila siku.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Ninapenda kushiriki meme na vicheshi na mwenzangu.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Ninapenda kushiriki maelezo yote ya siku yangu na mshirika wangu.",
    "Ich würde es nie tun" to "Singeweza kamwe kuifanya",
    "Ich übe noch" to "Bado ninafanya mazoezi",
    "Ideen generieren" to "Tengeneza mawazo",
    "Im Haushalt helfen" to "Msaada kuzunguka nyumba",
    "In Chat einfügen" to "Ongeza kwenye gumzo",
    "In Stille nebeneinander" to "Katika ukimya karibu na kila mmoja",
    "In den Bergen" to "Milimani",
    "In eine Bar gehen" to "Nenda kwenye baa",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Kwenda kwenye baa ya ufuo ili kutazama machweo",
    "In einem feinen Restaurant essen gehen" to "Kula nje katika mkahawa mzuri",
    "In einen Coffeeshop gehen" to "Nenda kwenye duka la kahawa",
    "In einer Beziehung sollte man alles voneinander wissen." to "Katika uhusiano unapaswa kujua kila kitu kuhusu kila mmoja.",
    "Infinity-Pool" to "Bwawa la Infinity",
    "Innenpool" to "Bwawa la kuogelea la ndani",
    "Intelligenz" to "Akili",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Kuwa na matukio ya karibu pekee wakati mwenzi wako anapoyaanzisha",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Nambari ya mwaliko: HRM-8731 · kila kitu kimefunguliwa",
    "Island" to "Isilandi",
    "Ist okay für mich" to "Ni sawa na mimi",
    "Ist schon perfekt" to "Ni kamili",
    "Ja, Traditionen einbinden" to "Ndiyo, jumuisha mila",
    "Ja, absolut" to "Ndiyo, kabisa",
    "Ja, etwas zum Lesen und Aufbewahren" to "Ndiyo, kitu cha kusoma na kuhifadhi",
    "Ja, genug" to "Ndiyo, inatosha",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Ndiyo, katika jiji la kusisimua au kivutio",
    "Ja, in- und auswendig" to "Ndiyo, ndani na nje",
    "Ja, komplett überraschend" to "Ndiyo, inashangaza kabisa",
    "Ja, perfekt" to "Ndiyo, ni kamili",
    "Ja, sie gehören zur Familie!" to "Ndiyo, wao ni familia!",
    "Ja, sofort teilen" to "Ndiyo, shiriki mara moja",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Ndiyo, tutahakikisha kwamba wakati wa familia ni jambo la kwanza.",
    "Jacuzzi" to "Jacuzzi",
    "Jahr zusammen 🎉" to "mwaka pamoja 🎉",
    "Jahre zusammen 🎉" to "Miaka pamoja 🎉",
    "Jeder zahlt 50%" to "Kila mtu hulipa 50%",
    "Junge" to "Kijana",
    "Kamin" to "Mahali pa moto",
    "Karriere & Erfolg" to "Kazi na Mafanikio",
    "Kategorien" to "Kategoria",
    "Katze" to "Paka",
    "Keine Musik" to "Hakuna muziki",
    "Keine Party nötig, privat halten" to "Hakuna haja ya sherehe, iwe ya faragha",
    "Keine Privatsphäre" to "Hakuna faragha",
    "Keine Treffer gefunden" to "Hakuna zinazolingana zilizopatikana",
    "Keiner" to "Hakuna",
    "Keiner von uns" to "Hakuna hata mmoja wetu",
    "Kennst du die Essensvorlieben deines Partners?" to "Je, unajua mapendeleo ya chakula ya mwenzako?",
    "Kino" to "Sinema",
    "Kirchlich" to "Kikanisa",
    "Klassisch Solitär" to "Solitaire ya zamani",
    "Klassisch gebunden" to "Inayofuata kanuni",
    "Klein & zart" to "Ndogo na maridadi",
    "Kleine Geschenke" to "Zawadi ndogo",
    "Kleine Runde" to "Kikundi kidogo",
    "Kochen und Freunde einladen" to "Kupika na kuwaalika marafiki",
    "Kochkurs" to "Darasa la upishi",
    "Kommt auf den Tag an" to "Inategemea siku",
    "Kommt darauf an" to "Inategemea",
    "Kommt drauf an" to "Inategemea",
    "Kommt mit" to "Njoo pamoja nami",
    "Konzert" to "Tamasha",
    "Kräftige Farben" to "Rangi thabiti",
    "Kräuterbeet" to "Kitanda cha mimea",
    "Kultur & Sehenswürdigkeiten" to "Utamaduni na Vivutio",
    "Kuscheln" to "Kubembelezana",
    "Kuss senden" to "Tuma busu",
    "Körperliche Annäherung" to "Mbinu ya kimwili",
    "Körperliche Nähe" to "Ukaribu wa kimwili",
    "Küche" to "Jikoni",
    "Land" to "Nchi",
    "Landhaus" to "Nyumba ya nchi",
    "Landhausstil" to "Mtindo wa nyumba ya nchi",
    "Lange wach bleiben" to "Usikeshe usiku kucha",
    "Lappland" to "Lapland",
    "Lappland, Finnland" to "Lapland, Ufini",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Mruhusu mshirika wako akutie moyo kuwa mtu bora zaidi",
    "Lehne ab" to "Kataa",
    "Leichtigkeit" to "Wepesi",
    "Leidenschaft" to "Shauku",
    "Liebe im Gleichgewicht" to "Upendo kwa usawa",
    "Liebe sie, macht mehr Spaß" to "Zipende, za kufurahisha zaidi",
    "Lieber durchgeplant oder spontan?" to "Je, ungependa kuipanga au iwe ya pekee?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Je, ungependa kuwa na jioni tulivu kwa watu wawili au pamoja na watu?",
    "Lieber nicht" to "Si bora",
    "Lieber vorher grob absprechen" to "Ni bora kujadili mambo takribani kabla",
    "Lokal einkaufen" to "Nunua ndani ya nchi",
    "London" to "London",
    "London, England" to "London, Uingereza",
    "Lügen" to "Uongo",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Je, unapendelea pendekezo la umma au la kibinafsi?",
    "Malediven" to "Maldivi",
    "Man sollte nie streitend einschlafen." to "Hupaswi kamwe kulala kwa kubishana.",
    "Mango Sorbet" to "Mango Sorbet",
    "Markant & breit" to "Inavutia & pana",
    "Marken & Alltag" to "Biashara na maisha ya kila siku",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "ua wa Mediterania",
    "Mehr Unterstützung" to "Usaidizi zaidi",
    "Mehr gemeinsame Zeit" to "Wakati zaidi pamoja",
    "Mehr zuhören" to "Sikiliza zaidi",
    "Mehrgenerationenhaus" to "Nyumba ya vizazi vingi",
    "Mein Arbeitsplatz" to "Mahali pangu pa kazi",
    "Mein Partner" to "Mshirika wangu",
    "Mich überraschen" to "Nishangae",
    "Minimalistisches Interieur" to "Mambo ya ndani ya chini kabisa",
    "Missverständnisse" to "Kutoelewana",
    "Mit Familie und engen Freunden" to "Pamoja na familia na marafiki wa karibu",
    "Mit Kompromissen" to "Pamoja na maelewano",
    "Mitgefühl" to "Huruma",
    "Mittelweg mit besonderen Details" to "Eneo la kati lenye maelezo maalum",
    "Modern geometrisch" to "Jiometri ya kisasa",
    "Moderne Grillstation" to "Kituo cha kisasa cha grill",
    "Moderner Name" to "Jina la kisasa",
    "Moderner Solitär" to "Solitaire ya kisasa",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "Nasa tukio",
    "Momente" to "matukio",
    "Monaco" to "Monako",
    "Moralische Werte" to "Maadili",
    "Museum" to "Makumbusho",
    "Musik" to "Muziki",
    "Mut" to "Ujasiri",
    "Mädchen" to "Wasichana",
    "Möbelhaus" to "Duka la fanicha",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Je, una uhakika ungependa kuondoka kwenye chemsha bongo? Maendeleo yako ya awali yanasalia kuhifadhiwa.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Je, ungependa wanyama kipenzi wajumuishwe kwenye programu?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Je, ungependa tukio hili lishirikiwe papo hapo kwenye mitandao ya kijamii?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Huenda tukahitaji kuweka akiba",
    "Müssen es planen" to "Unahitaji kuipanga",
    "Müssen sparen" to "Unahitaji kuhifadhi",
    "Nachricht an" to "Ujumbe",
    "Name Partnerin" to "Jina la mshirika",
    "Namen und Startdatum eurer Beziehung." to "Majina na tarehe ya kuanza kwa uhusiano wako.",
    "Natursteinfassade" to "Kitambaa cha mawe asilia",
    "Naturteich" to "Bwawa la asili",
    "Nein, einfach halten" to "Hapana, shikilia tu",
    "Nein, erstmal privat halten" to "Hapana, iweke faragha kwa sasa",
    "Nein, lieber vor Ort" to "Hapana, bora kwenye tovuti",
    "Nein, modern halten" to "Hapana, iendelee kuwa ya kisasa",
    "Nein, nur wir" to "Hapana, sisi tu",
    "Nein, zu ablenkend" to "Hapana, inakengeusha sana",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Jengo jipya lenye nyumba mahiri",
    "Neubau mit Technik" to "Jengo jipya lenye teknolojia",
    "Neue Liebe, neue Erfahrungen" to "Mapenzi mapya, matukio mapya",
    "Neues Hobby" to "Hobby mpya",
    "Neues Spiel" to "Mchezo mpya",
    "Neugier" to "Udadisi",
    "New York" to "New York",
    "New York, USA" to "New York, Marekani",
    "Nicht mein Fall" to "Si kikombe changu cha chai",
    "Nicht nötig, lieber klassisch bleiben" to "Si lazima, ni bora kusalia classical",
    "Nichts — es passt so" to "Hakuna - inafaa",
    "Nie wieder Burger" to "Usiwahi tena burger",
    "Nie wieder Pizza" to "Usiwahi pizza tena",
    "Niemand" to "Hakuna mtu",
    "Niemand ohne Plan" to "Hakuna mtu asiye na mpango",
    "Nike" to "Nike",
    "Nizza" to "Nzuri",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Bado hakuna muda mfupi.\nNasa matumizi yako ya kwanza 💞",
    "Nur bei wichtigen Themen" to "Kwa mada muhimu pekee",
    "Nur wir beide" to "Sisi wawili tu",
    "Nähe & Intimität" to "Ukaribu na Ukaribu",
    "Obstgarten" to "Bustani",
    "Oder" to "Au",
    "Offene Küche" to "Jikoni wazi",
    "Offene Wohnküche" to "Jikoni/sebule iliyo wazi",
    "Ohne Stein" to "Bila jiwe",
    "Open End" to "Mwisho wazi",
    "Outdoor-Küche" to "Jiko la nje",
    "Outdoor-Sofa" to "Sofa ya nje",
    "Outdoor-Whirlpool" to "Kimbunga cha nje",
    "Ovaler Diamant" to "Almasi ya mviringo",
    "Paar" to "Jozi",
    "Paar-Statistiken" to "Takwimu za wanandoa",
    "Paris" to "Paris",
    "Paris, Frankreich" to "Paris, Ufaransa",
    "Partner" to "Mshirika",
    "Partner-Simulator" to "Mwigizaji mshirika",
    "Partnerin" to "Mshirika",
    "Party Edition" to "Toleo la Sherehe",
    "Party Edition II" to "Toleo la Sherehe II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Je, mnyama hata anafaa katika maisha yetu ya kila siku?",
    "Pasta" to "Pasta",
    "Pastell" to "Pastel",
    "Penthouse mit Ausblick" to "Upenu wenye mwonekano",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pergola yenye sebule",
    "Pfingstrosen" to "Peoni",
    "Pinguin" to "Pengwini",
    "Pistazie" to "Pistachio",
    "Pizza" to "Piza",
    "Pizzaofen" to "Tanuri ya pizza",
    "Platin" to "Platinamu",
    "PlayStation" to "PlayStation",
    "Pool" to "Dimbwi",
    "Pop" to "Pop",
    "Prasselnder Kamin" to "Sehemu ya moto inayonguruma",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Mabinti wa Kifalme, Maharamia na Vumbi la Fairy: Maswali ya Disney",
    "Privater Innenhof" to "Ua wa kibinafsi",
    "Profil" to "Wasifu",
    "Profil bearbeiten" to "Badilisha wasifu",
    "Prozentual nach Einkommen" to "Asilimia kulingana na mapato",
    "Quiz verlassen" to "Acha chemsha bongo",
    "Quiz verlassen?" to "Ungependa kuacha swali?",
    "Rausgehen in die Natur" to "Ondoka kwenye asili",
    "Reden vor ..." to "Akizungumza na...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Ratibu tarehe au saa za kawaida pamoja",
    "Reisen" to "Safiri",
    "Reiseziele" to "Maeneo ya kusafiri",
    "Respektlosigkeit" to "Kutoheshimu",
    "Restaurant" to "Mkahawa",
    "RnB / Soul" to "RnB / Soul",
    "Rock" to "Mwamba",
    "Rom" to "Roma",
    "Rom, Italien" to "Roma, Italia",
    "Romantik" to "Mapenzi",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Ishara za kimapenzi kama vile ujumbe, madokezo au zawadi hunifurahisha.",
    "Romantische Stimmung" to "Hali ya kimahaba",
    "Roségold" to "Dhahabu ya waridi",
    "Ruhig zu zweit" to "Kimya kwa mbili",
    "Runder Diamant" to "Almasi ya pande zote",
    "Salted Caramel" to "Caramel yenye chumvi",
    "Sammle Ideen..." to "Kusanya mawazo...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Ugiriki",
    "Saphir" to "Sapphire",
    "Saunahaus" to "Nyumba ya Sauna",
    "Schickes Restaurant oder Hotel" to "Mkahawa wa kisasa au hoteli",
    "Schlafzimmer" to "Chumba cha kulala",
    "Schließen" to "Funga",
    "Schmal & zart" to "Nyembamba na maridadi",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Picha kutoka kwa hadithi yetu ya mapenzi",
    "Schokolade" to "Chokoleti",
    "Schreib frei, was dir wirklich dazu einfällt." to "Andika kwa uhuru kile kinachokuja akilini.",
    "Schreibe deine eigene Antwort" to "Andika jibu lako mwenyewe",
    "Sehr gerne" to "Karibu",
    "Sehr leicht" to "Nyepesi sana",
    "Sehr wichtig — Fotos und Video" to "Muhimu sana — picha na video",
    "Sehr wichtig, es sollte persönlich sein" to "Muhimu sana, inapaswa kuwa ya kibinafsi",
    "Selbst kochen" to "Jipike mwenyewe",
    "Senden" to "Tuma",
    "Separate Küche" to "Jikoni tofauti",
    "Serie schauen" to "Tazama mfululizo",
    "Serienmarathon auf dem Sofa" to "Mfululizo wa mbio za marathoni kwenye sofa",
    "Sex & Liebe" to "Ngono na Mapenzi",
    "Seychellen" to "Shelisheli",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Je, tunaweza kulipia gharama zote kwa mtoto mmoja/watoto wengi? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Je, pendekezo hilo linafaa kuwa la mshangao?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Je, programu inapaswa kuwa na vipengele vya kitamaduni au vya kitamaduni?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Je, programu inapaswa kuwa na vipengele vya kitamaduni au vya kitamaduni?",
    "Sommerhochzeit" to "Harusi ya kiangazi",
    "Sonnige Dachterrasse" to "Mtaro wa paa wenye jua",
    "Sowohl als auch" to "Wote na",
    "Spazieren" to "Tembea",
    "Spaß & Abenteuer" to "Furaha na Vituko",
    "Speichern" to "Hifadhi",
    "Spiel bearbeiten" to "Badilisha mchezo",
    "Spielbereich für Kinder" to "Eneo la kucheza la watoto",
    "Spiele" to "Michezo",
    "Spiele spielen und Spaß haben" to "Cheza michezo na ufurahie",
    "Spontan" to "Ya Papo Hapo",
    "Sportplatz" to "Uwanja wa michezo",
    "Spotify" to "Spotify",
    "Sprache" to "Lugha",
    "Stadt" to "Jiji",
    "Stadt oder Land — was ist uns wichtiger?" to "Jiji au nchi - ni nini muhimu zaidi kwetu?",
    "Stadtvilla" to "Nyumba ya jiji",
    "Standesamt & Party" to "Ofisi ya Usajili na sherehe",
    "Statement-Ring" to "Pete ya taarifa",
    "Stilvolles Outdoor-Sofa" to "Sofa maridadi ya nje",
    "Stimme voll zu" to "Nakubali kabisa",
    "Stimmt" to "Sawa",
    "Stimmt nicht" to "Si kweli",
    "Stimmt, noch nie" to "Kweli, kamwe",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Siku ya ufukweni",
    "Streit über Haushalt" to "Mzozo kuhusu kaya",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "Daima",
    "Suche schließen" to "Funga utafutaji",
    "Suche zurücksetzen" to "Weka upya utafutaji",
    "Suche öffnen" to "Fungua utafutaji",
    "Suchergebnisse" to "Matokeo ya utafutaji",
    "Sushi" to "Sushi",
    "Süß" to "Tamu",
    "Tage zusammen 💞" to "siku pamoja 💞",
    "Tauche ins Unterbewusstsein" to "Ingia kwenye fahamu ndogo",
    "Teile alle deine Hobbys mit deinem Partner" to "Shiriki mambo unayopenda yote na mshirika wako",
    "Teils teils" to "Kwa kiasi fulani",
    "Testen" to "Jaribio",
    "Themen" to "Mada",
    "Tiefe Gespräche" to "Mazungumzo ya kina",
    "Tiefgründige Gespräche führen" to "Kuwa na mazungumzo ya kina",
    "Tierpension" to "Bweni la wanyama",
    "Tiny House" to "Nyumba Ndogo",
    "Tippen zum Auswählen & Scrollen" to "Gusa ili uchague na usogeze",
    "Tippen zum Zuklappen" to "Gusa ili ukunje",
    "Titel" to "Kichwa",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Kichwa, Kitengo, Mada, Lebo, Maswali...",
    "Tokyo, Japan" to "Tokyo, Japani",
    "Traditioneller Name" to "Jina la jadi",
    "Traumhaus Außenbereich" to "Eneo la nje la nyumba ya ndoto",
    "Traumhochzeit" to "Ndoto ya harusi",
    "Treffer" to "Hit",
    "Tägliche Aktivität" to "Shughuli za kila siku",
    "Umformulieren" to "Tamka upya",
    "Unbeantwortet" to "Haijajibiwa",
    "Unbeliebte Meinungen" to "Maoni yasiyopendwa",
    "Universal Studios Genie oder Neuling?" to "gwiji wa Universal Studios au mgeni?",
    "Uns auseinanderzuleben" to "Kukua kando",
    "Unser Intimleben" to "Maisha yetu ya karibu",
    "Unser Traumhaus" to "Nyumba yetu ya ndoto",
    "Unser erstes Treffen" to "Mkutano wetu wa kwanza",
    "Unsere Gesichter" to "Nyuso zetu",
    "Unsere eigenen Träume" to "Ndoto zetu wenyewe",
    "Unsere nächste Reise" to "Safari yetu inayofuata",
    "Unter 1000" to "Chini ya 1000",
    "Unter 1000 im Monat" to "Chini ya 1000 kwa mwezi",
    "Unter 50€/Monat" to "Chini ya 50€/mwezi",
    "Unter Leuten" to "Miongoni mwa watu",
    "Untreue" to "Ukafiri",
    "Urlaub" to "Likizo",
    "Vanille" to "Vanila",
    "Venedig" to "Venice",
    "Venedig, Italien" to "Venice, Italia",
    "Verbinde dich mit" to "Ungana na",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Unganisha kwenye \${profile.partnerName} ili kuona jibu",
    "Verbindung" to "muunganisho",
    "Verbringe die Feiertage mit deiner Familie" to "Tumia likizo pamoja na familia yako",
    "Verlobungsringe" to "Pete za uchumba",
    "Vertrautheit" to "Kufahamiana",
    "Viel getrennt" to "Matengano mengi",
    "Vielleicht ein oder zwei" to "Labda moja au mbili",
    "Vielleicht, aber mündlich reicht" to "Labda, lakini kwa maneno inatosha",
    "Vielleicht, wenn es machbar ist" to "Labda, ikiwezekana",
    "Vielleicht, wenn es passt" to "Labda, ikiwa inafaa",
    "Vintage Art déco" to "Deco ya Sanaa ya Zamani",
    "Vintage verspielt" to "Zamani za kucheza",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Kutambulishwa kwa mambo mapya ya kupendeza na mpenzi wako",
    "Vor dem Kauf eines Hauses besprechen" to "Jadili kabla ya kununua nyumba",
    "Vor der Anschaffung eines Haustiers besprechen" to "Jadili kabla ya kununua mnyama kipenzi",
    "Vor der gemeinsamen Reise besprechen" to "Jadili kabla ya kusafiri pamoja",
    "Vor nichts" to "Hakuna",
    "Vorort" to "Kitongoji",
    "Walnuss" to "Walnut",
    "Wandern" to "Kutembea kwa miguu",
    "Wann fühlst du dich mir am nächsten?" to "Je, unahisi kuwa karibu nami wakati gani zaidi?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Je, ni wakati gani unahisi kuwa karibu nami kimwili?",
    "Was bedeutet Vertrauen für dich konkret?" to "Kuamini kunamaanisha nini kwako haswa?",
    "Was entspannt dich mehr?" to "Ni nini kinachokupumzisha zaidi?",
    "Was fehlt dir über die Distanz am meisten?" to "Unakosa nini zaidi kuhusu umbali?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Je, unapenda nini zaidi kuhusu nyumba yako?",
    "Was hast du von deinem Partner gelernt?" to "Umejifunza nini kutoka kwa mwenzako?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Una maoni gani kuhusu kutazama maudhui ya ashiki pamoja?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Una maoni gani kuhusu vifaa (k.m. ishara, puto, n.k.)?",
    "Was ist das Wichtigste beim Antrag?" to "Ni jambo gani muhimu zaidi unapotuma ombi?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Je, ni jambo gani muhimu zaidi unalotafuta katika ngono?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Je, ni picha gani unayoipenda zaidi? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Ni nini hofu yako kubwa kuhusu kuishi pamoja?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Ni chakula gani unachopenda lakini mwenzi wako haelewi?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Je, ni mvunjaji wa dili kabisa kwako?",
    "Was ist für jeden von uns das absolute Highlight?" to "Ni jambo gani linaloangaziwa kabisa kwa kila mmoja wetu?",
    "Was ist passiert?" to "Nini kilifanyika?",
    "Was macht einen Moment für dich romantisch?" to "Ni nini kinachokufanya uwe wa kimapenzi?",
    "Was magst du an deinem Partner am liebsten?" to "Je, unapenda nini zaidi kuhusu mpenzi wako?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Unapenda nini bora zaidi: kuamka mapema au kuchelewa kulala?",
    "Was magst du lieber?" to "Unapenda kipi bora zaidi?",
    "Was möchtest du eigentlich sagen?" to "Unataka kusema nini hasa?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Je, ungependa mpenzi wako afanye nini mara nyingi zaidi?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Nini kinatokea kwa mnyama tunaposafiri?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Mtoto wetu atakapokuwa mtu mzima itakuwaje?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Tukiwa wazazi hatupaswi kamwe kusahau nini?",
    "Was war dein schönster Moment mit mir bisher?" to "Ni wakati gani mzuri zaidi ukiwa nami kufikia sasa?",
    "Was wir gegessen haben" to "Tulichokula",
    "Was wollt ihr nie vergessen?" to "Ni nini ambacho hutaki kamwe kusahau?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Nini kingekuwa mbaya zaidi kwako: usiwahi pizza tena au usiwaze burger tena?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Je, ungependa kufanya nini zaidi mkiwa pamoja?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Ungebadilisha nini mara moja ikiwa pesa si suala?",
    "Weiter" to "Inayofuata",
    "Weiter spielen" to "Endelea kucheza",
    "Weiß ich noch nicht" to "Bado sijui",
    "Weiße Rosen" to "Mawaridi meupe",
    "Weißgold" to "Dhahabu nyeupe",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Mtoto wetu anapaswa kupata sifa gani kutoka kwetu?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Je, ungependa mazingira gani kwa pendekezo?",
    "Welcher Raum sagt am meisten über dich aus?" to "Ni chumba gani kinasema zaidi kukuhusu?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Je, tunapanga bajeti gani kwa ajili ya chakula na daktari wa mifugo?",
    "Welches Lied macht dich an? 🥵" to "Wimbo gani huwasha? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Ni picha gani iliyoshirikiwa unayopenda zaidi?",
    "Wellnessbad" to "Bafu ya afya",
    "Wenn es schwierig ist" to "Mambo yanapokuwa magumu",
    "Wenn ich müde bin" to "Ninapokuwa nimechoka",
    "Wenn wir uns lange umarmen" to "Tunapokumbatiana kwa muda mrefu",
    "Wenn wir zusammen lachen" to "Tunapocheka pamoja",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Ni nani anayeamua kwa haraka zaidi aagiza nini?",
    "Wer findet die besten Restaurants?" to "Nani hupata mikahawa bora zaidi?",
    "Wer gibt mehr Herzlichkeit?" to "Ni nani anayetoa uchangamfu zaidi?",
    "Wer hat den besseren Musikgeschmack?" to "Ni nani ana ladha bora katika muziki?",
    "Wer hängt mehr an seinen Eltern?" to "Ni nani anayeshikamana zaidi na wazazi wao?",
    "Wer ist besser organisiert?" to "Ni nani aliye na mpangilio mzuri zaidi?",
    "Wer ist der Beste bei der Filmauswahl?" to "Ni nani bora katika kuchagua filamu?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Nani ni bora katika kupanga tarehe za kimapenzi?",
    "Wer ist der beste Tänzer?" to "Je, mchezaji bora zaidi ni nani?",
    "Wer ist romantischer?" to "Nani ana mapenzi zaidi?",
    "Wer kocht besser?" to "Nani anapika vizuri zaidi?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Ni nani anayeshughulikia ukarabati na matengenezo?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Nani hutambua haraka wakati mtu mwingine hajisikii vizuri?",
    "Wer sucht am Ende wirklich den Film aus?" to "Ni nani hasa anayechagua filamu mwishoni?",
    "Wer vergisst eher einen Jahrestag?" to "Ni nani anaye uwezekano mkubwa wa kusahau maadhimisho?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Je, ni nani atakayesahau jina lake asubuhi iliyofuata?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Ni nani angekuwa na uwezekano mkubwa wa kupata video siku iliyofuata ambayo hawakujua chochote kuihusu?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Nani angependelea kulala kwenye sofa ya mtu asiyemfahamu?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Je, ni nani atakayelala kwenye karamu na kuamka wakiwa na Sharpie usoni?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Ni nani atakayeweza kuteleza kwenye sakafu ya dansi lakini kuifanya ionekane kama hatua nzuri?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Ni nani anaye uwezekano mkubwa wa kudhibiti orodha ya kucheza ya Spotify kwenye sherehe ya nyumbani?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Ni nani anayeweza kuagiza pizza kwa kila mtu kwenye karamu na kuila yeye mwenyewe?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Ni nani anaye uwezekano mkubwa wa kusinzia kwanza kwenye sherehe?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Ni nani anaye uwezekano mkubwa wa kuanza kusafisha ghafla kwenye sherehe?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Ni nani angekuwa na uwezekano mkubwa wa kudai kuwa na akili timamu wakati kinyume chake ni kweli?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Ni nani anayeelekea zaidi kutoa wa kwanza katika mabishano?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Ni nani anaye uwezekano mkubwa wa kudanganya kwenye mchezo wa unywaji pombe?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Ni nani angekuwa na uwezekano mkubwa wa kuvamia bafe na kupeleka chakula nyumbani kwa siri?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Je!",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Je, nani anaweza kuudhi DJ kuomba wimbo wake anaoupenda zaidi?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Je!",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Ni nani atakayeweza kuagiza kinywaji cha bei ghali zaidi kwenye menyu na kujuta?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Ni nani angekuwa na uwezekano mkubwa zaidi wa kuwaalika majirani iwapo wangelalamika kuhusu kelele hiyo?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Nani angechukulia michezo ya karamu (kama vile Bia Pong) kwa umakini sana?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Ni nani angekuwa na uwezekano mkubwa wa kufanya urafiki na wapiga filimbi kupata ufikiaji wa VIP?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Je!",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Ni nani anaye uwezekano mkubwa wa kufungua chupa bila kutumia kopo?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Ni nani angekuwa na uwezekano mkubwa wa kutoa hotuba ingawa hakuna aliyeuliza?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Je!",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Je!",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Je!",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Ni nani anaye uwezekano mkubwa wa kumuudhi mgeni asiye wa kawaida kimakosa?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Ni nani angekuwa na uwezekano mkubwa wa kuondoka kwenye sherehe kwa siri bila kuaga?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Ni nani angependelea kucheza na kipenzi cha mwenyeji kuliko kuzungumza na wageni?",
    "Wer würde eher spontan eine Reise buchen?" to "Je!",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Ni nani angekuwa na uwezekano mkubwa wa kuwa na mazungumzo ya kina jikoni kwa saa nyingi?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Ni nani anaye uwezekano mkubwa wa kunywa kinywaji cha mtu mwingine kwa bahati mbaya?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Ni nani anayeweza kugonga kwa bahati mbaya chombo cha bei ghali au kitu dhaifu?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Ni nani angekuwa na uwezekano zaidi wa kujaribu kuchanganya cocktail ngumu wenyewe na kushindwa vibaya?",
    "Wer würde eher zu spät kommen?" to "Ni nani anaye uwezekano mkubwa wa kuchelewa?",
    "Wer würde eher?" to "Nani angependelea?",
    "Wer übernimmt die tägliche Versorgung?" to "Nani hutunza utunzaji wa kila siku?",
    "Werde so akzeptiert, wie du bist" to "ukubaliwe jinsi ulivyo",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Je, tutakuwa na muda wa kutosha kwa ajili ya mtoto/watoto? ⏳",
    "Whirlpool" to "Bafu moto",
    "White Chocolate" to "Chokoleti Nyeupe",
    "Widgets" to "Wijeti",
    "Wie fühlst du dich am meisten geliebt?" to "Je, unahisije kupendwa zaidi?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Je, tunashughulikia vipi mapato tofauti?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Ni ipi njia bora ya mwenzi wako kuanzisha mapenzi na wewe?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Je, mpenzi wako anawezaje kuwa mshirika bora zaidi kwako?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Je, ungependa kusherehekea pamoja na wengine kwa muda gani baada ya pendekezo?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Je, tunataka kukaa hapo kwa muda gani angalau?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Je, ni rahisi vipi kwako kuzungumza kuhusu matakwa?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Unataka maisha yetu ya baadaye yaweje?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Je, Jumapili yako nzuri ukiwa nyumbani inaonekanaje?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Unahisije kuhusu mazungumzo machafu wakati wa ngono?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Je, tunaweza kumudu kiasi gani cha mkopo kihalisi?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Je, ni muda gani tunataka kutumia kando?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Je, tungependa kutumia kiasi gani kwa jumla?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Tutapataje wakati wa uhusiano wetu mara tu mtoto atakapokuja?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Je, kuna umuhimu gani kwako kwamba wakati unanaswa?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Je, kuna umuhimu gani kwako kwamba ombi lionyeshe mambo unayopenda au mambo yanayokuvutia?",
    "Wie würdest du sie/ihn nennen?" to "Ungemwitaje?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Je, ni njia gani unayopenda zaidi ya kuonyesha upendo nje ya ngono?",
    "Wildblumen" to "Maua ya mwituni",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Je, unataka msichana au mvulana? 👶",
    "Wintergarten" to "Bustani ya majira ya baridi",
    "Winterhochzeit" to "Harusi ya majira ya baridi",
    "Wir bestellen einfach beides" to "Tunaagiza zote mbili",
    "Wir brauchen ewig" to "Inatuchukua milele",
    "Wir einigen uns nie" to "Hatukubali kamwe",
    "Wir entscheiden es gemeinsam" to "Tunaamua pamoja",
    "Wir treffen uns in der Mitte" to "Tunakutana katikati",
    "Wir wechseln uns ab" to "Tunapokezana",
    "Wird stressig" to "Hupata mfadhaiko",
    "Wobei lachst du am meisten?" to "Ni nini kinachokufanya ucheke zaidi?",
    "Wofür sparen wir gemeinsam?" to "Je, tunaweka akiba kwa ajili ya nini pamoja?",
    "Wohnzimmer" to "Sebule",
    "Woran erinnerst du dich am lebhaftesten?" to "Je, unakumbuka nini kwa uwazi zaidi?",
    "Worauf freust du dich bei uns am meisten?" to "Je, unatazamia nini zaidi ukiwa nasi?",
    "Worte/Komplimente" to "Maneno/Pongezi",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Je, unaogopa nini zaidi katika uhusiano wetu?",
    "Wünsche? z.B. günstig, draußen" to "Je! k.m. nafuu, nje",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Je, ungependa kupendekeza likizo (inayohusisha kusafiri)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube Music",
    "Zeichne für mich" to "Chora kwa ajili yangu",
    "Zeichne mich als Tier — welches wäre ich?" to "Nichore kama mnyama - ningekuwa yupi?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Chora hisia zetu kuelekea kila mmoja kama ishara.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Chora nyumba yetu ya ndoto katika mstari mmoja. Ni jambo gani la kushangaza zaidi?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Chora tarehe yetu ya kwanza - ni nini kinapaswa kuwa kwenye picha?",
    "Zeichnen" to "Droo",
    "Zeit füreinander" to "Wakati wa kila mmoja",
    "Zeit, wenn das Baby schläft" to "Wakati mtoto analala",
    "Zelten gehen" to "Nenda kambini",
    "Zitrone" to "Ndimu",
    "Zu Hause, gemütlich und privat" to "Nyumbani, tulivu na faragha",
    "Zu einem Picknick gehen" to "Kwenda kwenye picnic",
    "Zu einem ausgefallenen Abendessen gehen" to "Kwenda kwa chakula cha jioni cha kupendeza",
    "Zu zweit reisen" to "Safirini kama wanandoa",
    "Zuhause & Alltag" to "Nyumbani na maisha ya kila siku",
    "Zuhören" to "Sikiliza",
    "Zurück" to "Nyuma",
    "Zusammen seit" to "Pamoja tangu",
    "Zusammen seit (TT.MM.JJJJ)" to "Pamoja tangu (DD.MM.YYYY)",
    "Zusammenziehen" to "Mkataba",
    "Zustimmen oder Ablehnen" to "Kubali au Usikubali",
    "Zwei Kreise, die sich überschneiden" to "Miduara miwili inayopishana",
    "Zwei Stühle davor" to "Viti viwili mbele yake",
    "Zärtlich sein" to "Kuwa mpole",
    "Öfter als ich zugebe" to "Mara nyingi kuliko ninavyokubali",
    "Über 100€/Monat" to "Zaidi ya 100€/mwezi",
    "Über 2000 im Monat" to "Zaidi ya 2000 kwa mwezi",
    "Über mich selbst" to "Kunihusu",
    "Übernehmen" to "Tuma ombi",
    "Überraschend" to "Inashangaza",
    "Überraschung" to "Mshangao",
    "Überspringen" to "Ruka",
    "Übertrieben und großartig" to "Juu na ya kupendeza",
    "✎ Tippe, um zu antworten" to "✎ Gusa ili kujibu",
    "✨ GFK-Brücke" to "✨ daraja la GRP",
)

internal fun localizeSwahiliDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_SWAHILI_CONTENT)
