package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_SWEDISH_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 år",
    "1000 - 1500 im Monat" to "1000 - 1500 per månad",
    "1000 bis 3000" to "1000 till 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 per månad",
    "3000 bis 5000" to "3000 till 5000",
    "5-10 Jahre" to "5-10 år",
    "50-100€/Monat" to "50-100€/månad",
    "Ab 100€" to "Från 100€",
    "Ab 500€" to "Från 500 €",
    "Ab 50€" to "Från 50€",
    "Ab und zu" to "Då och då",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Vilken summa pratar vi om innan vi gör ett köp?",
    "Abbrechen" to "Avbryt",
    "Abenteuer" to "Äventyr",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Aktiviteter",
    "Alle" to "Alla",
    "Alle Pakete" to "Alla paket",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Förlora alla dina vänner utom din bästa vän",
    "Alle intimen Momente selbst initiieren" to "Initiera alla intima stunder själv",
    "Alles davon" to "Alltihop",
    "Alles, was noch kommt" to "Allt som kommer",
    "Alltagsroutine" to "Vardagsrutin",
    "Alltägliche Berührungen" to "Vardagliga inslag",
    "Altbau mit Charme" to "Gammal byggnad med charm",
    "Am Strand" to "På stranden",
    "Am liebsten alles zusammen" to "Helst allt tillsammans",
    "Am selben Tag mit Freunden/Familie" to "Samma dag med vänner/familj",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Nederländerna",
    "An das Gefühl" to "Av känslan",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "På en offentlig plats med många åskådare",
    "An einen Geruch" to "Av en lukt",
    "An einen Song" to "Till en låt",
    "An etwas, das ich gesagt habe" to "Något jag sa",
    "Analyse starten" to "Starta analysen",
    "Analysiere eure Muster..." to "Analysera dina mönster...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Analysera dina svar och chattar enligt Gottman och GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Ananas på pizza smakar gott.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Svara med ett foto",
    "Antwortähnlichkeit" to "Svarslikhet",
    "App-Sprache auswählen" to "Välj appspråk",
    "Auf eine Bootsparty gehen" to "Går på en båtfest",
    "Aufmerksamkeit" to "Observera",
    "Aufräumen und Projekte angehen" to "Städa upp och ta itu med projekt",
    "Aufwärmen" to "Värm upp",
    "Aufwärmen: Einander kennenlernen" to "Uppvärmning: Att lära känna varandra",
    "Aus dem Urlaub" to "Från semestern",
    "Ausgefallener Name" to "Snyggt namn",
    "Ausschlafen und faulenzen" to "Sov ut och lata dig",
    "Ausschlafen und nichts tun" to "Sov ut och gör ingenting",
    "Aussehen" to "Utseende",
    "Auto" to "Auto",
    "Außenkamin" to "Utomhus öppen spis",
    "BEANTWORTE" to "SVAR",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonesien",
    "Banane" to "Banan",
    "Beantwortet" to "Besvarade",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Svara på frågor samtidigt – svaren kommer inte att synas förrän ni båda är klara.",
    "Beantwortete Fragen" to "Besvarade frågor",
    "Bearbeiten" to "Redigera",
    "Bei Insider-Witzen" to "För inre skämt",
    "Bei Memes" to "På memes",
    "Bei einer spontanen Berührung" to "Vid spontan beröring",
    "Beide" to "Båda",
    "Beide gleich" to "Båda samma",
    "Beide zusammen" to "Båda tillsammans",
    "Beide, aber wir tun so als ob nicht" to "Båda, men vi låtsas inte",
    "Beides" to "Båda",
    "Beides wäre schlimm" to "Båda skulle vara dåliga",
    "Beim Einschlafen nebeneinander" to "Somnar bredvid varandra",
    "Beim Reden" to "Medan du pratar",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Kända turistplatser är alltid en besvikelse.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Beskriv vårt sexliv med en emoji.",
    "Besser kommunizieren" to "Kommunicera bättre",
    "Bessere Lage" to "Bättre plats",
    "Bestellen" to "Beställning",
    "Besuchte Länder" to "Besökta länder",
    "Besuchte Städte" to "Besökta städer",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Föredrar du ett extravagant förslag eller något subtilt?",
    "Beziehung" to "Förhållande",
    "Bibliothek" to "Bibliotek",
    "Bin manchmal unsicher" to "Jag är ibland osäker",
    "Bist du ein Videospiel-Guru?" to "Är du en videospelsguru?",
    "Blumenwiese" to "Blomsteräng",
    "Bunte Blumenwiese" to "Färgglad blomsteräng",
    "Burger" to "Hamburgare",
    "Burger King" to "Burger King",
    "Chat" to "Chatta",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Kakedeg",
    "Dachgarten mit Lounge" to "Takträdgård med lounge",
    "Dachterrasse" to "Takterrass",
    "Das Wetter an dem Tag" to "Vädret den dagen",
    "Das erste Selfie" to "Den första selfien",
    "Das meiste weiß ich" to "Jag kan det mesta",
    "Das oder das?" to "Detta eller det?",
    "Das tägliche Leben" to "Dagligt liv",
    "Dass Zusagen gehalten werden" to "Att löften hålls",
    "Dass alles meinen Stil hat" to "Att allt har min stil",
    "Dass ich alles erzählen kann" to "Att jag kan berätta allt",
    "Dass ich mich nicht sorgen muss" to "Att jag inte behöver oroa mig",
    "Dass wir ungestört sind" to "Att vi är ostörda",
    "Dein Name" to "Ditt namn",
    "Deine Antwort..." to "Ditt svar...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Dina svar är sparade. Så snart Partner avslutar paketet kommer båda svaren att synas tillsammans.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Dina svar är sparade. Så snart \${profile.partnerName} avslutar paketet kommer båda svaren att synas tillsammans.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Gör ditt förhållande äventyrligt och spontant",
    "Deine Beziehung stabil und sicher machen" to "Gör din relation stabil och säker",
    "Deine eigene Antwort" to "Ditt eget svar",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Det är bättre att dela dina djupaste hemligheter med din partner",
    "Deinen besten Freund verlieren" to "Att förlora din bästa vän",
    "Denke an dich" to "Tänk på dig själv",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Att se samma film två gånger är ett slöseri med tid.",
    "Der Blick nach draußen" to "Utsikten utanför",
    "Der Garten" to "Trädgården",
    "Der Ort" to "Platsen",
    "Der Ring und die Geste" to "Ringen och gesten",
    "Der perfekte Heiratsantrag" to "Det perfekta äktenskapsförslaget",
    "Derjenige sein, der umarmt wird" to "Var den som kramas",
    "Deutsch" to "Tyska",
    "Diamant" to "Diamant",
    "Diamanten im Band" to "Diamanter i bandet",
    "Die Distanz" to "Avståndet",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Tillbringa semestern med din partners familj",
    "Die Gemütlichkeit und Ruhe" to "Trösten och lugnet",
    "Die Menschen, die darin wohnen" to "Människorna som bor i den",
    "Die Umgebung und Atmosphäre" to "Miljön och atmosfären",
    "Die Worte und Emotionen" to "Orden och känslorna",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Den ultimata underhållningstriviautmaningen",
    "Diejenige sein, die umarmt" to "Var den som kramar",
    "Direkt ansprechen" to "Adress direkt",
    "Diskussion" to "Diskussion",
    "Diskutiere vor dem Kinderkriegen" to "Diskutera innan du skaffar barn",
    "Diskutiert eure Antworten" to "Diskutera dina svar",
    "Disney" to "Disney",
    "Doch, schon mal" to "Ja, ja",
    "Draußen mit der Natur als Kulisse" to "Ute med naturen som bakgrund",
    "Drei-Stein-Ring" to "Ring i tre sten",
    "Du bist dran" to "Det är din tur",
    "Du fehlst mir" to "Jag saknar dig",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubai, Förenade Arabemiraten",
    "Dunkles Design" to "Mörkt tema",
    "Durch Berührung" to "Genom beröring",
    "Durch Worte" to "Genom ord",
    "Durch Zeit zu zweit" to "Genom tiden tillsammans",
    "Durch kleine Gesten" to "Genom små gester",
    "Durchgeplant" to "Väl planerad",
    "ERGEBNISSE" to "RESULTAT",
    "Egal, Hauptsache gesund" to "Vad som än är, huvudsaken är frisk",
    "Ehepaar Leben" to "Äkta parliv",
    "Eher knapp" to "Ganska nära",
    "Eher nicht" to "Inte så mycket",
    "Eher schwer" to "Ganska svårt",
    "Eher schwierig" to "Ganska svårt",
    "Eher zu" to "Mer som",
    "Eifersucht ist ein Zeichen von Liebe." to "Svartsjuka är ett tecken på kärlek.",
    "Eigenes Gemüsebeet" to "Eget grönsaksplåster",
    "Ein Abenteuer in einer neuen Stadt" to "Ett äventyr i en ny stad",
    "Ein Anker" to "Ett ankare",
    "Ein Balkon oder Garten" to "En balkong eller trädgård",
    "Ein Filmabend" to "En filmkväll",
    "Ein Harmony-Meilenstein eurer Liebe." to "En harmonisk milstolpe i din kärlek.",
    "Ein Herz" to "Ett hjärta",
    "Ein Herz an der Tür" to "Ett hjärta vid dörren",
    "Ein Jahr lang eine Fernbeziehung führen" to "Ha ett långdistansförhållande i ett år",
    "Ein Kindheitsessen" to "En barndomsmåltid",
    "Ein Live-Musik-Konzert besuchen" to "Gå på en livemusikkonsert",
    "Ein Museum besuchen" to "Besök ett museum",
    "Ein Spieleabend" to "En spelkväll",
    "Ein Spieleabend mit Freunden" to "En spelkväll med vänner",
    "Ein Urlaubsfoto" to "Ett semesterfoto",
    "Ein aktives Abenteuer" to "Ett aktivt äventyr",
    "Ein entspannender Spa-Tag" to "En avkopplande spadag",
    "Ein ganz normaler Alltagstag" to "En helt vanlig vardag",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "En mysig kväll i huset under ett åskväder",
    "Ein gemütliches Date drinnen" to "En mysig dejt inomhus",
    "Ein lustiges Bild" to "En rolig bild",
    "Ein paar Handyfotos reichen" to "Några mobiltelefonfoton räcker",
    "Ein paar Stunden" to "Några timmar",
    "Ein paar kulturelle Anklänge sind okay" to "Några kulturella referenser är okej",
    "Ein romantischer Abend" to "En romantisk kväll",
    "Ein romantisches Abendessen bei Kerzenlicht" to "En romantisk middag med levande ljus",
    "Ein romantisches Bild" to "En romantisk bild",
    "Ein romantisches Picknick an einem schönen Ort" to "En romantisk picknick på en vacker plats",
    "Ein schwerer Moment, den wir geschafft haben" to "Ett svårt ögonblick som vi klarade av",
    "Ein tolles Date im Freien unter dem Mondlicht" to "En fantastisk dejt utomhus under månskenet",
    "Ein ungewöhnliches Gericht" to "En ovanlig maträtt",
    "Ein zufälliger Schnappschuss" to "En slumpmässig ögonblicksbild",
    "Einander kennenlernen" to "Att lära känna varandra",
    "Eine Autoreise" to "En roadtrip",
    "Eine Brücke" to "En bro",
    "Eine Date-Nacht unter den Sternen" to "En dejtkväll under stjärnorna",
    "Eine Million Dollar gewinnen" to "Vinn en miljon dollar",
    "Eine Million Dollar verdienen" to "Tjäna en miljon dollar",
    "Eine Nacht in einem Club" to "En natt på en klubb",
    "Eine Schokoladenverkostung" to "En chokladprovning",
    "Eine Wanderung mit Panoramablick machen" to "Ta en vandring med panoramautsikt",
    "Eine Weinverkostung" to "En vinprovning",
    "Eine gemeinsame Reise" to "En resa tillsammans",
    "Eine gemütliche Nacht zu Hause" to "En mysig kväll hemma",
    "Eine neue Sprache zu lernen ist einfach." to "Det är lätt att lära sig ett nytt språk.",
    "Einen Film anschauen" to "Titta på en film",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Att inte prata med varandra alls på en månad",
    "Einen Tanzkurs besuchen" to "Ta en dansklass",
    "Einen Vergnügungspark erkunden" to "Utforska en nöjespark",
    "Einen Wellness-Tag" to "En friskvårdsdag",
    "Einen sehr emotionalen Partner haben" to "Att ha en väldigt känslosam partner",
    "Einen sehr logischen Partner haben" to "Att ha en mycket logisk partner",
    "Einer zahlt alles" to "En person betalar allt",
    "Einfach mehr Alltag" to "Helt enkelt mer vardag",
    "Einfach nebeneinander sein" to "Var bara bredvid varandra",
    "Einfach und intim" to "Enkelt och intimt",
    "Einige Dinge für dich behalten" to "Håll några saker för dig själv",
    "Einmal" to "En gång",
    "Eins, das nur wir kennen" to "En som bara vi känner till",
    "Englisch" to "Engelska",
    "Entspannte Hängematte" to "Avslappnad hängmatta",
    "Entspannung" to "Avkoppling",
    "Erdbeere" to "Jordgubbe",
    "Erfolgreich" to "Lyckad",
    "Ergebnisse" to "resultat",
    "Erst bei sehr großen Summen" to "Endast för mycket stora summor",
    "Erst nur enge Freunde/Familie" to "Endast nära vänner/familj till en början",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Det irriterar mig när min partner tar för lång tid på sig att svara på meddelanden.",
    "Essen & Genuss" to "Mat och njutning",
    "Essensvorlieben" to "Matpreferenser",
    "Etwa eine Woche später, erst mal nur wir" to "Ungefär en vecka senare, bara vi först",
    "Etwas Neues ausprobieren" to "Prova något nytt",
    "Etwas ganz anderes" to "Något helt annat",
    "Etwas sehr Scharfes" to "Något väldigt skarpt",
    "Etwas, das ich selbst gern erfinde" to "Något jag gillar att hitta på själv",
    "Etwas, eine kleine Note wäre schön" to "Något, en liten anteckning skulle vara trevligt",
    "Familie" to "Familj",
    "Familie/Freunde" to "Familj/vänner",
    "Familienmensch" to "Familjefar",
    "Farbedelstein" to "Färgad ädelsten",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "TV-reklam är ibland intressant att titta på.",
    "Fertig" to "Klart",
    "Fertig!" to "Klart!",
    "Feste Date-Nights" to "Fasta datum nätter",
    "Feuerstelle" to "Eldstad",
    "Filigran & schlicht" to "Filigran och enkel",
    "Filme/Serien" to "Filmer/serier",
    "Formuliere um..." to "Omformulera...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Omformulera ditt utkast på ett icke-våldsamt sätt: observation, känsla, behov, begäran.",
    "Frage hinzufügen" to "Lägg till fråga",
    "Fragen & Spiele" to "Frågor och spel",
    "Fragen für jede Gelegenheit" to "Frågor för alla tillfällen",
    "Freizeitpark" to "Nöjespark",
    "Freunde treffen" to "Träffa vänner",
    "Freundschaften mit Ex-Partnern sind okay." to "Vänskap med ex är okej.",
    "Früh aufstehen" to "Gå upp tidigt",
    "Fußbodenheizung" to "Golvvärme",
    "Führen wir getrennte oder gemeinsame Konten?" to "Har vi separata eller gemensamma konton?",
    "Für dich empfohlen" to "Rekommenderas för dig",
    "Für die Zukunft" to "För framtiden",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Inga matchande frågor eller spel hittades för denna sökning.",
    "Für immer" to "För alltid",
    "Fürsorglichkeit" to "Omtänksam",
    "GFK-Brücke" to "GRP-bro",
    "Galerie" to "Galleri",
    "Gar nicht, der Moment gehört uns" to "Inte alls, ögonblicket är vårt",
    "Gar nichts tun" to "Gör ingenting",
    "Geduld" to "Tålamod",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Gå tidigt på morgonen för att se soluppgången",
    "Geht so" to "Det fungerar så här",
    "Geister existieren wirklich." to "Spöken finns verkligen.",
    "Gelassenheit" to "Lugn",
    "Gelbgold" to "Gult guld",
    "Geld & Finanzen" to "Pengar och finans",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Res världen tillsammans, utforska nya kulturer och kök",
    "Gemeinsam ein Lego bauen" to "Bygg ett Lego tillsammans",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Testa ett nytt recept tillsammans i köket",
    "Gemeinsame Konten" to "Delade konton",
    "Gemeinsame Nächte" to "Nätter tillsammans",
    "Gemeinsame Tage" to "Dagar tillsammans",
    "Gemischt" to "Blandat",
    "Gemüsebeet" to "Grönsaksplåster",
    "Gemütliche Feuerstelle" to "Mysig öppen spis",
    "Gesprächsanreger" to "Konversationsstartare",
    "Getrennte Konten" to "Separata konton",
    "Getrennte Urlaube tun einer Beziehung gut." to "Separata semestrar är bra för ett förhållande.",
    "Gewächshaus" to "Växthus",
    "Glasfassade" to "Glasfasad",
    "Gleichgültigkeit" to "Likgiltighet",
    "Glücklich und frei" to "Glad och fri",
    "Gourmet Eis-Sorten" to "Gourmetglassvarianter",
    "Gravur innen" to "Gravyr inuti",
    "Grillplatz" to "Grillplats",
    "Groß & üppig" to "Stort och frodigt",
    "Große Familie" to "Stor familj",
    "Große Feier" to "Stort firande",
    "Große Fenster" to "Stora fönster",
    "Große Fensterfront" to "Stort fönster fram",
    "Großer Außenpool" to "Stor utomhuspool",
    "Großer Garten" to "Stor trädgård",
    "Großer Stein" to "Stor sten",
    "Größere Küche" to "Större kök",
    "Gutes Essen" to "God mat",
    "Habe ich" to "Det gjorde jag",
    "Habe ich noch nie" to "Det har jag aldrig gjort",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Har du upptäckt några överraskande skillnader? Prata om varför du gillar vissa alternativ bättre!",
    "Haus am See" to "Hus vid sjön",
    "Haus/Wohnung" to "Hus/lägenhet",
    "Hazelnut" to "Hasselnöt",
    "Heimkino" to "Hemmabio",
    "Herzhaft" to "Hjärtligt",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Det finns ingenting här just nu.\nÄndra filtret eller välj ett annat tema.",
    "Hilfe im Alltag" to "Hjälp i vardagen",
    "Himbeere" to "Hallon",
    "Hinzufügen" to "Lägg till",
    "Hobbys" to "Hobbyer",
    "Hochzeitssträuße" to "Bröllopsbuketter",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Hogwarts House Pride: Where Do You Belong?",
    "Home" to "Hem",
    "Hot Tub" to "Bubbelbad",
    "Humor" to "Humor",
    "Hund" to "Hund",
    "Hängematte" to "Hängmatta",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Vill du ha ett skriftligt brev som en del av förslaget?",
    "IKEA" to "IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Jag föredrar romantiska promenader i parken framför att gå på bio.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Jag har aldrig somnat på en biograf.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Jag tycker om att upptäcka nya hobbyer eller aktiviteter med min partner.",
    "Ich finde eine Alternative" to "Jag ska hitta ett alternativ",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Jag tycker om att prova nya restauranger med min partner istället för att alltid gå till samma ställen.",
    "Ich habe noch nie" to "Det har jag aldrig",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Jag har aldrig varit rädd för en berg-och dalbana och jag åkte på den ändå.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Jag har aldrig köpt Fast Pass-biljetter eftersom jag var otålig.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Jag har aldrig avbrutit planerna på att stanna hemma och titta på ett tv-program.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Jag har aldrig väntat på mitt brev från Hogwarts.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Jag har aldrig sagt att Slytherin faktiskt inte var så ond.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Jag har aldrig sagt att jag var för gammal för Disney-filmer (och gillade dem i hemlighet).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Jag har aldrig avsiktligt skjutit ner någon med en blå tank i Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Jag har aldrig gråtit på en Disneyfilm.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Jag har aldrig täckt mina ögon när jag tittat på en skräckfilm.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Jag har aldrig glömt att spara ett spel och tappat timmar av framsteg.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Jag har aldrig lämnat rummet under en pinsam scen (cringe factor).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Jag har aldrig gjort en rolig pose när jag tagit en berg-och-dalbana.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Jag har aldrig spelat långt in på natten och ångrat hur trött jag var dagen efter.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Jag har aldrig googlat slutet på en film eftersom jag inte kunde vänta.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Jag har aldrig känt att jag stod på en filmuppsättning.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Jag har aldrig hoppat över introt av min favoritserie.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Jag har aldrig delat någon annans Netflix-lösenord.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Jag har aldrig lyssnat på ett spels soundtrack när jag jobbade eller studerade.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Jag har aldrig skyllt på kontrollern när jag förlorade.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Jag har aldrig kastat tangentbordet eller handkontrollen i ilska.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Jag har aldrig glömt blöta kläder i tvättmaskinen på några dagar.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Jag har aldrig spenderat riktiga pengar på kosmetiska föremål i ett spel.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Jag har aldrig kört bil i ett främmande land.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Jag har aldrig bältat ut en Disney-låt i duschen.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Jag har aldrig kört elbil.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Jag har aldrig tagit ett foto med en parkmaskot.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Jag har aldrig döpt ett husdjur efter en Hogwarts-karaktär.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Jag har aldrig tappat popcorn i en biograf och fortfarande ätit det.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Jag har aldrig använt ett citat från Master Yoda från Star Wars i vardagen.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Jag har aldrig köpt en för dyr souvenir i en nöjespark.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Jag har aldrig gett en filmrekommendation som den andra personen tyckte var hemsk.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Jag har aldrig sett en Oscar live mitt i natten.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Jag har aldrig ställt in en serie eftersom förra säsongen var så dålig.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Jag har aldrig binge-tittat på en hel säsong av en serie på en dag.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Jag har aldrig besegrat en chef på första försöket och känt mig som en gud.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Jag har aldrig hittat en skurk coolare än hjälten.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Jag har aldrig känt igen en Toy Story-karaktär i mina egna leksaker.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Jag har aldrig gjort en karaktär i ett RPG exakt som jag.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Jag har aldrig ätit en churro i en nöjespark.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Jag har aldrig sett en Disney-film tre gånger i rad.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Jag har aldrig haft en Disney catchy låt på en hel vecka.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Jag har aldrig sett en film bara på grund av en viss skådespelare.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Jag har aldrig lyssnat på ett filmljudspår på repeat i timmar.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Jag har aldrig avslöjat en filmspoiler och ångrade mig direkt.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Jag har aldrig hittat en vän som talar ett annat modersmål.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Jag har aldrig haft en vän som flyttat till ett annat land.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Jag har aldrig gjort ett Harry Potter-filmmaraton på julen.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Jag har aldrig sett en Marvel-film förrän i slutet bara på grund av post-credit-scenen.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Jag har aldrig medvetet irriterat en NPC (Non-Player Character).",
    "Ich habe noch nie einen Nachtzug genommen." to "Jag har aldrig åkt nattåg.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Jag har aldrig gjort ett onlinetest för att ta reda på mitt Hogwarts-hus.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Jag har aldrig tagit bort ett inlägg på sociala medier eftersom det inte fick tillräckligt många likes.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Jag har aldrig kallat en dag i nöjesparken för den bästa dagen på året.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Jag har aldrig besökt en nöjespark och stannat där från morgon till kväll.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Jag har aldrig lämnat en Transformers eller Marvel-resa helt fascinerad.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Jag har aldrig kastat en rage quit och lämnat spelet.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Jag har aldrig läst någon av de stora Harry Potter-volymerna.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Jag har aldrig tjatat om min favoritkaraktär i en serie.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Jag har aldrig drömt om att spela Quidditch.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Jag har aldrig i hemlighet googlat hur man löser en svår nivå.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Jag har aldrig i hemlighet hoppats att mitt husdjur skulle kunna prata som i Disney.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Jag har aldrig tagit bort poolledaren i Sims.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Jag har aldrig tappat koll på en 3D-simulatortur.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Jag har aldrig spelat i ett universitetsidrottslag.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Jag har aldrig stått i kö i mer än två timmar för en enda attraktion.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Jag har aldrig fått mina värdesaker blöta på en vattentur.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Jag har aldrig bråkat med en vän om vilket hus som är bäst.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Jag har aldrig låtsats ha magiska krafter som Elsa.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Jag har aldrig skrattat så mycket att jag missat en viktig scen i en film.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Jag har aldrig känt så mycket adrenalin att jag genast velat åka igen.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Jag har aldrig provat att sjunga med djur som Snövit.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Jag har aldrig drömt om en resa till Disneyland.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Jag har aldrig drömt om att åka Jurassic Park-vattenturen.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Jag har aldrig skrikit högt vid en hoppskräck i ett spel.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Jag har aldrig gråtit över finalen i ett tv-program.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Jag har aldrig... ställt in ett datum för att stanna hemma.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Jag har aldrig... formulerat om ett meddelande 10 gånger.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Jag har aldrig... i hemlighet tittat på min partners mobiltelefon.",
    "Ich habe noch nie!" to "Jag har aldrig!",
    "Ich habe!" to "Jag har!",
    "Ich lache viel mit meinem Partner." to "Jag skrattar mycket med min partner.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Jag gillar att lära känna min partners hobbyer och intressen.",
    "Ich liebe es" to "Jag älskar det",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Jag älskar att titta på filmer med min partner som ingen av oss har sett tidigare.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Jag älskar att dela min favoritmusik med min partner.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Jag har aldrig behövt springa för att hinna med ett anslutningsflyg.",
    "Ich plane gerne Dates mit meinem Partner." to "Jag gillar att planera dejter med min partner.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Jag prioriterar att umgås med min partner även när jag är upptagen.",
    "Ich schreibe meinem Partner jeden Tag." to "Jag sms:ar min partner varje dag.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Jag gillar att dela memes och skämt med min partner.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Jag gillar att dela alla detaljer om min dag med min partner.",
    "Ich würde es nie tun" to "Jag skulle aldrig göra det",
    "Ich übe noch" to "Jag övar fortfarande",
    "Ideen generieren" to "Generera idéer",
    "Im Haushalt helfen" to "Hjälp i huset",
    "In Chat einfügen" to "Lägg till i chatten",
    "In Stille nebeneinander" to "I tysthet bredvid varandra",
    "In den Bergen" to "I bergen",
    "In eine Bar gehen" to "Gå till en bar",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Går till en strandbar för att titta på solnedgången",
    "In einem feinen Restaurant essen gehen" to "Äta ute på en fin restaurang",
    "In einen Coffeeshop gehen" to "Gå till ett kafé",
    "In einer Beziehung sollte man alles voneinander wissen." to "I ett förhållande borde ni veta allt om varandra.",
    "Infinity-Pool" to "Infinitypool",
    "Innenpool" to "Inomhuspool",
    "Intelligenz" to "Intelligens",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Att bara ha intima stunder när din partner initierar dem",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Inbjudningskod: HRM-8731 · allt upplåst",
    "Island" to "Island",
    "Ist okay für mich" to "Det är okej med mig",
    "Ist schon perfekt" to "Det är perfekt",
    "Ja, Traditionen einbinden" to "Ja, införliva traditioner",
    "Ja, absolut" to "Ja, absolut",
    "Ja, etwas zum Lesen und Aufbewahren" to "Ja, något att läsa och behålla",
    "Ja, genug" to "Ja, nog",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Ja, i en spännande stad eller attraktion",
    "Ja, in- und auswendig" to "Ja, inifrån och ut",
    "Ja, komplett überraschend" to "Ja, helt överraskande",
    "Ja, perfekt" to "Ja, perfekt",
    "Ja, sie gehören zur Familie!" to "Ja, de är familj!",
    "Ja, sofort teilen" to "Ja, dela omedelbart",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Ja, vi kommer att se till att familjetid är en prioritet.",
    "Jacuzzi" to "Jacuzzi",
    "Jahr zusammen 🎉" to "år tillsammans 🎉",
    "Jahre zusammen 🎉" to "år tillsammans 🎉",
    "Jeder zahlt 50%" to "Alla betalar 50 %",
    "Junge" to "Pojke",
    "Kamin" to "Öppen spis",
    "Karriere & Erfolg" to "Karriär och framgång",
    "Kategorien" to "Kategorier",
    "Katze" to "Kat",
    "Keine Musik" to "Ingen musik",
    "Keine Party nötig, privat halten" to "Ingen fest behövs, håll den privat",
    "Keine Privatsphäre" to "Ingen integritet",
    "Keine Treffer gefunden" to "Inga träffar hittades",
    "Keiner" to "Inga",
    "Keiner von uns" to "Ingen av oss",
    "Kennst du die Essensvorlieben deines Partners?" to "Känner du till din partners matpreferenser?",
    "Kino" to "Bio",
    "Kirchlich" to "Kyrkligt",
    "Klassisch Solitär" to "Klassisk patiens",
    "Klassisch gebunden" to "Klassiskt bunden",
    "Klein & zart" to "Liten & delikat",
    "Kleine Geschenke" to "Små presenter",
    "Kleine Runde" to "Liten grupp",
    "Kochen und Freunde einladen" to "Lagar mat och bjuder in vänner",
    "Kochkurs" to "Matlagningskurs",
    "Kommt auf den Tag an" to "Beror på dagen",
    "Kommt darauf an" to "Det beror på",
    "Kommt drauf an" to "Det beror på",
    "Kommt mit" to "Följ med mig",
    "Konzert" to "Konsert",
    "Kräftige Farben" to "Starka färger",
    "Kräuterbeet" to "Örtbädd",
    "Kultur & Sehenswürdigkeiten" to "Kultur och sevärdheter",
    "Kuscheln" to "Gos",
    "Kuss senden" to "Skicka en kyss",
    "Körperliche Annäherung" to "Fysiskt tillvägagångssätt",
    "Körperliche Nähe" to "Fysisk närhet",
    "Küche" to "Kök",
    "Land" to "Land",
    "Landhaus" to "Hus på landet",
    "Landhausstil" to "Lantlig husstil",
    "Lange wach bleiben" to "Var uppe sent",
    "Lappland" to "Lappland",
    "Lappland, Finnland" to "Lappland, Finland",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Låt din partner inspirera dig att vara ditt bästa jag",
    "Lehne ab" to "Avslå",
    "Leichtigkeit" to "Lätthet",
    "Leidenschaft" to "Passion",
    "Liebe im Gleichgewicht" to "Kärlek i balans",
    "Liebe sie, macht mehr Spaß" to "Älskar dem, roligare",
    "Lieber durchgeplant oder spontan?" to "Skulle du hellre ha det planerat eller spontant?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Skulle du hellre ha en lugn kväll för två eller med folk?",
    "Lieber nicht" to "Bättre inte",
    "Lieber vorher grob absprechen" to "Det är bättre att diskutera saker ungefär i förväg",
    "Lokal einkaufen" to "Handla lokalt",
    "London" to "London",
    "London, England" to "London, England",
    "Lügen" to "Lögner",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Föredrar du ett offentligt eller privat förslag?",
    "Malediven" to "Maldiverna",
    "Man sollte nie streitend einschlafen." to "Du bör aldrig somna och bråka.",
    "Mango Sorbet" to "Mangosorbet",
    "Markant & breit" to "Slående & bred",
    "Marken & Alltag" to "Varumärken & vardag",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "Medelhavets innergård",
    "Mehr Unterstützung" to "Mer stöd",
    "Mehr gemeinsame Zeit" to "Mer tid tillsammans",
    "Mehr zuhören" to "Lyssna mer",
    "Mehrgenerationenhaus" to "Flergenerationshus",
    "Mein Arbeitsplatz" to "Min arbetsplats",
    "Mein Partner" to "Min partner",
    "Mich überraschen" to "Överraska mig",
    "Minimalistisches Interieur" to "Minimalistisk interiör",
    "Missverständnisse" to "Missförstånd",
    "Mit Familie und engen Freunden" to "Med familj och nära vänner",
    "Mit Kompromissen" to "Med kompromisser",
    "Mitgefühl" to "Medkänsla",
    "Mittelweg mit besonderen Details" to "Mellangrund med speciella detaljer",
    "Modern geometrisch" to "Modern geometrisk",
    "Moderne Grillstation" to "Modern grillstation",
    "Moderner Name" to "Modernt namn",
    "Moderner Solitär" to "Modern patiens",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "Fånga ögonblicket",
    "Momente" to "ögonblick",
    "Monaco" to "Monaco",
    "Moralische Werte" to "Moraliska värderingar",
    "Museum" to "Museum",
    "Musik" to "Musik",
    "Mut" to "Mod",
    "Mädchen" to "Flickor",
    "Möbelhaus" to "Möbelaffär",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Är du säker på att du vill lämna frågesporten? Dina tidigare framsteg förblir sparade.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Vill du att husdjur ska inkluderas i ansökan?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Vill du att ögonblicket ska delas direkt på sociala medier?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Vi kan behöva göra besparingar",
    "Müssen es planen" to "Måste planera det",
    "Müssen sparen" to "Behöver spara",
    "Nachricht an" to "Meddelande",
    "Name Partnerin" to "Namn på partner",
    "Namen und Startdatum eurer Beziehung." to "Namn och startdatum för ditt förhållande.",
    "Natursteinfassade" to "Fasad av natursten",
    "Naturteich" to "Naturlig damm",
    "Nein, einfach halten" to "Nej, håll ut",
    "Nein, erstmal privat halten" to "Nej, håll det privat tills vidare",
    "Nein, lieber vor Ort" to "Nej, bättre på plats",
    "Nein, modern halten" to "Nej, håll det modernt",
    "Nein, nur wir" to "Nej, bara vi",
    "Nein, zu ablenkend" to "Nej, för distraherande",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Ny byggnad med smarta hem",
    "Neubau mit Technik" to "Ny byggnad med teknik",
    "Neue Liebe, neue Erfahrungen" to "Ny kärlek, nya upplevelser",
    "Neues Hobby" to "Ny hobby",
    "Neues Spiel" to "Nytt spel",
    "Neugier" to "Nyfikenhet",
    "New York" to "New York",
    "New York, USA" to "New York, USA",
    "Nicht mein Fall" to "Inte min kopp te",
    "Nicht nötig, lieber klassisch bleiben" to "Inte nödvändigt, det är bättre att förbli klassisk",
    "Nichts — es passt so" to "Ingenting - det passar",
    "Nie wieder Burger" to "Aldrig mer hamburgare",
    "Nie wieder Pizza" to "Aldrig pizza igen",
    "Niemand" to "Ingen",
    "Niemand ohne Plan" to "Ingen utan en plan",
    "Nike" to "Nike",
    "Nizza" to "Trevligt",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Inga ögonblick än.\nFånga din första upplevelse 💞",
    "Nur bei wichtigen Themen" to "Endast för viktiga ämnen",
    "Nur wir beide" to "Bara vi två",
    "Nähe & Intimität" to "Närhet och intimitet",
    "Obstgarten" to "Orchard",
    "Oder" to "Eller",
    "Offene Küche" to "Öppet kök",
    "Offene Wohnküche" to "Öppet kök/vardagsrum",
    "Ohne Stein" to "Utan sten",
    "Open End" to "Öppen slut",
    "Outdoor-Küche" to "Utekök",
    "Outdoor-Sofa" to "Utomhussoffa",
    "Outdoor-Whirlpool" to "Bubbelpool utomhus",
    "Ovaler Diamant" to "Oval diamant",
    "Paar" to "Par",
    "Paar-Statistiken" to "Parstatistik",
    "Paris" to "Paris",
    "Paris, Frankreich" to "Paris, Frankrike",
    "Partner" to "Partner",
    "Partner-Simulator" to "Partnersimulator",
    "Partnerin" to "Partner",
    "Party Edition" to "Party Edition",
    "Party Edition II" to "Party Edition II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Passar ett djur ens in i vår vardag?",
    "Pasta" to "Pasta",
    "Pastell" to "Pastell",
    "Penthouse mit Ausblick" to "Takvåning med utsikt",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Pergola med lounge",
    "Pfingstrosen" to "Pioner",
    "Pinguin" to "Pingvin",
    "Pistazie" to "Pistage",
    "Pizza" to "Pizza",
    "Pizzaofen" to "Pizzaugn",
    "Platin" to "Platina",
    "PlayStation" to "PlayStation",
    "Pool" to "Pool",
    "Pop" to "Pop",
    "Prasselnder Kamin" to "Rytande öppen spis",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Prinsessor, pirater och Fairy Dust: Disney Quiz",
    "Privater Innenhof" to "Privat innergård",
    "Profil" to "Profil",
    "Profil bearbeiten" to "Redigera profil",
    "Prozentual nach Einkommen" to "Procent baserad på inkomst",
    "Quiz verlassen" to "Avsluta frågesport",
    "Quiz verlassen?" to "Vill du avsluta frågesporten?",
    "Rausgehen in die Natur" to "Gå ut i naturen",
    "Reden vor ..." to "Tal till...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Schemalägg vanliga datum eller tid tillsammans",
    "Reisen" to "Resor",
    "Reiseziele" to "Resmål",
    "Respektlosigkeit" to "Respektlöshet",
    "Restaurant" to "Restaurang",
    "RnB / Soul" to "RnB / Soul",
    "Rock" to "Rock",
    "Rom" to "Rom",
    "Rom, Italien" to "Rom, Italien",
    "Romantik" to "Romantik",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Romantiska gester som meddelanden, anteckningar eller presenter gör mig glad.",
    "Romantische Stimmung" to "Romantisk stämning",
    "Roségold" to "Rose guld",
    "Ruhig zu zweit" to "Tyst för två",
    "Runder Diamant" to "Rund diamant",
    "Salted Caramel" to "Saltad karamell",
    "Sammle Ideen..." to "Samla idéer...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Grekland",
    "Saphir" to "Safir",
    "Saunahaus" to "Bastuhus",
    "Schickes Restaurant oder Hotel" to "Chic restaurang eller hotell",
    "Schlafzimmer" to "Sovrum",
    "Schließen" to "Stäng",
    "Schmal & zart" to "Smal & delikat",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Ögonblicksbilder från vår kärlekshistoria",
    "Schokolade" to "Choklad",
    "Schreib frei, was dir wirklich dazu einfällt." to "Skriv fritt vad du verkligen tänker på.",
    "Schreibe deine eigene Antwort" to "Skriv ditt eget svar",
    "Sehr gerne" to "Du är välkommen",
    "Sehr leicht" to "Mycket lätt",
    "Sehr wichtig — Fotos und Video" to "Mycket viktigt — foton och video",
    "Sehr wichtig, es sollte persönlich sein" to "Mycket viktigt, det ska vara personligt",
    "Selbst kochen" to "Laga mat själv",
    "Senden" to "Skicka",
    "Separate Küche" to "Separat kök",
    "Serie schauen" to "Se serien",
    "Serienmarathon auf dem Sofa" to "Seriemaraton i soffan",
    "Sex & Liebe" to "Sex och kärlek",
    "Seychellen" to "Seychellerna",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Kan vi täcka alla kostnader för ett barn/flera barn? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Bör förslaget vara en överraskning?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Bör applikationen innehålla kulturella eller traditionella inslag?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Bör applikationen innehålla kulturella eller traditionella inslag?",
    "Sommerhochzeit" to "Sommarbröllop",
    "Sonnige Dachterrasse" to "Solig takterrass",
    "Sowohl als auch" to "Både och",
    "Spazieren" to "Ta en promenad",
    "Spaß & Abenteuer" to "Nöje och äventyr",
    "Speichern" to "Spara",
    "Spiel bearbeiten" to "Redigera spel",
    "Spielbereich für Kinder" to "Lekplats för barn",
    "Spiele" to "Spel",
    "Spiele spielen und Spaß haben" to "Spela spel och ha kul",
    "Spontan" to "Spontant",
    "Sportplatz" to "Idrottsplan",
    "Spotify" to "Spotify",
    "Sprache" to "Språk",
    "Stadt" to "Stad",
    "Stadt oder Land — was ist uns wichtiger?" to "Stad eller land – vad är viktigast för oss?",
    "Stadtvilla" to "Stadsvilla",
    "Standesamt & Party" to "Registerkontor och parti",
    "Statement-Ring" to "Uttalande ring",
    "Stilvolles Outdoor-Sofa" to "Snygg utomhussoffa",
    "Stimme voll zu" to "Håller helt med",
    "Stimmt" to "Okej",
    "Stimmt nicht" to "Inte sant",
    "Stimmt, noch nie" to "Sant, aldrig",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Stranddag",
    "Streit über Haushalt" to "Tvist om hushåll",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "Ständigt",
    "Suche schließen" to "Stäng sökning",
    "Suche zurücksetzen" to "Återställ sökning",
    "Suche öffnen" to "Öppna sökning",
    "Suchergebnisse" to "Sökresultat",
    "Sushi" to "Sushi",
    "Süß" to "Söt",
    "Tage zusammen 💞" to "Dagar tillsammans 💞",
    "Tauche ins Unterbewusstsein" to "Dyk ner i det undermedvetna",
    "Teile alle deine Hobbys mit deinem Partner" to "Dela alla dina hobbyer med din partner",
    "Teils teils" to "Delvis delvis",
    "Testen" to "Test",
    "Themen" to "Ämnen",
    "Tiefe Gespräche" to "Djupa konversationer",
    "Tiefgründige Gespräche führen" to "Ha djupa konversationer",
    "Tierpension" to "Djurpensionat",
    "Tiny House" to "Litet hus",
    "Tippen zum Auswählen & Scrollen" to "Tryck för att välja och bläddra",
    "Tippen zum Zuklappen" to "Tryck för att komprimera",
    "Titel" to "Titel",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Titel, Kategori, Ämne, Taggar, Frågor...",
    "Tokyo, Japan" to "Tokyo, Japan",
    "Traditioneller Name" to "Traditionellt namn",
    "Traumhaus Außenbereich" to "Drömhus utomhusområde",
    "Traumhochzeit" to "Drömbröllop",
    "Treffer" to "Hit",
    "Tägliche Aktivität" to "Daglig aktivitet",
    "Umformulieren" to "Omformulera",
    "Unbeantwortet" to "Obesvarad",
    "Unbeliebte Meinungen" to "Impopulära åsikter",
    "Universal Studios Genie oder Neuling?" to "Universal Studios geni eller nybörjare?",
    "Uns auseinanderzuleben" to "Växer isär",
    "Unser Intimleben" to "Vårt intima liv",
    "Unser Traumhaus" to "Vårt drömhus",
    "Unser erstes Treffen" to "Vårt första möte",
    "Unsere Gesichter" to "Våra ansikten",
    "Unsere eigenen Träume" to "Våra egna drömmar",
    "Unsere nächste Reise" to "Vår nästa resa",
    "Unter 1000" to "Under 1000",
    "Unter 1000 im Monat" to "Under 1000 per månad",
    "Unter 50€/Monat" to "Under 50€/månad",
    "Unter Leuten" to "Bland människor",
    "Untreue" to "Otrohet",
    "Urlaub" to "Semester",
    "Vanille" to "Vanilj",
    "Venedig" to "Venedig",
    "Venedig, Italien" to "Venedig, Italien",
    "Verbinde dich mit" to "Anslut med",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Anslut till \${profile.partnerName} för att se svaret",
    "Verbindung" to "anslutning",
    "Verbringe die Feiertage mit deiner Familie" to "Tillbringa semestern med din familj",
    "Verlobungsringe" to "Förlovningsringar",
    "Vertrautheit" to "Bekantskap",
    "Viel getrennt" to "Mycket separation",
    "Vielleicht ein oder zwei" to "Kanske en eller två",
    "Vielleicht, aber mündlich reicht" to "Kanske, men muntligt räcker",
    "Vielleicht, wenn es machbar ist" to "Kanske, om det är möjligt",
    "Vielleicht, wenn es passt" to "Kanske, om det passar",
    "Vintage Art déco" to "Vintage art déco",
    "Vintage verspielt" to "Vintage lekfull",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Att bli introducerad till nya hobbyer av din partner",
    "Vor dem Kauf eines Hauses besprechen" to "Diskutera innan du köper ett hus",
    "Vor der Anschaffung eines Haustiers besprechen" to "Diskutera innan du köper ett husdjur",
    "Vor der gemeinsamen Reise besprechen" to "Diskutera innan du reser tillsammans",
    "Vor nichts" to "Ingenting",
    "Vorort" to "Förort",
    "Walnuss" to "Valnöt",
    "Wandern" to "Vandring",
    "Wann fühlst du dich mir am nächsten?" to "När känner du dig närmast mig?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "När känner du dig fysiskt närmast mig?",
    "Was bedeutet Vertrauen für dich konkret?" to "Vad betyder förtroende för dig specifikt?",
    "Was entspannt dich mehr?" to "Vad gör dig mer avslappnad?",
    "Was fehlt dir über die Distanz am meisten?" to "Vad saknar du mest med distansen?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Vad gillar du mest med ditt hem?",
    "Was hast du von deinem Partner gelernt?" to "Vad har du lärt dig av din partner?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Vad tycker du om att titta på erotiskt innehåll tillsammans?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Vad tycker du om rekvisita (t.ex. skyltar, ballonger, etc.)?",
    "Was ist das Wichtigste beim Antrag?" to "Vad är det viktigaste när du ansöker?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Vad är det viktigaste du letar efter i ett sexuellt möte?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Vilken är din favoritbild på oss? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Vad är din största rädsla för att bo tillsammans?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Vad är en mat du älskar men din partner inte kan förstå?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Vad är en absolut dealbreaker för dig?",
    "Was ist für jeden von uns das absolute Highlight?" to "Vilken är den absoluta höjdpunkten för var och en av oss?",
    "Was ist passiert?" to "Vad hände?",
    "Was macht einen Moment für dich romantisch?" to "Vad gör ett ögonblick romantiskt för dig?",
    "Was magst du an deinem Partner am liebsten?" to "Vad gillar du mest med din partner?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Vad gillar du bäst: gå upp tidigt eller vara uppe sent?",
    "Was magst du lieber?" to "Vilket gillar du bäst?",
    "Was möchtest du eigentlich sagen?" to "Vad vill du egentligen säga?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Vad skulle du vilja att din partner skulle göra oftare?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Vad händer med djuret när vi reser?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Vad kommer att bli av vårt barn när det växer upp?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Vad ska vi aldrig tappa ur sikte som föräldrar?",
    "Was war dein schönster Moment mit mir bisher?" to "Vilket var ditt bästa ögonblick med mig hittills?",
    "Was wir gegessen haben" to "Vad vi åt",
    "Was wollt ihr nie vergessen?" to "Vad vill du aldrig glömma?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Vad skulle vara värre för dig: aldrig pizza igen eller aldrig hamburgare igen?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Vad skulle du helst vilja göra på en dag tillsammans?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Vad skulle du ändra omedelbart om pengar inte var ett problem?",
    "Weiter" to "Nästa",
    "Weiter spielen" to "Fortsätt spela",
    "Weiß ich noch nicht" to "Jag vet inte än",
    "Weiße Rosen" to "Vita rosor",
    "Weißgold" to "Vitt guld",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Vilken kvalitet ska vårt barn definitivt få av oss?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Vilken miljö skulle du vilja ha för ett förslag?",
    "Welcher Raum sagt am meisten über dich aus?" to "Vilket rum säger mest om dig?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Vilken budget planerar vi för mat och veterinär?",
    "Welches Lied macht dich an? 🥵" to "Vilken låt tänder dig? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Vilket delat foto är din favorit?",
    "Wellnessbad" to "Hälsobad",
    "Wenn es schwierig ist" to "När saker är svåra",
    "Wenn ich müde bin" to "När jag är trött",
    "Wenn wir uns lange umarmen" to "När vi kramas länge",
    "Wenn wir zusammen lachen" to "När vi skrattar tillsammans",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Vem bestämmer snabbare vad som ska beställas?",
    "Wer findet die besten Restaurants?" to "Vem hittar de bästa restaurangerna?",
    "Wer gibt mehr Herzlichkeit?" to "Vem ger mer värme?",
    "Wer hat den besseren Musikgeschmack?" to "Vem har bättre musiksmak?",
    "Wer hängt mehr an seinen Eltern?" to "Vem är mer fäst vid sina föräldrar?",
    "Wer ist besser organisiert?" to "Vem är mer organiserad?",
    "Wer ist der Beste bei der Filmauswahl?" to "Vem är bäst på att välja filmer?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Vem är bäst på att planera romantiska dejter?",
    "Wer ist der beste Tänzer?" to "Vem är den bästa dansaren?",
    "Wer ist romantischer?" to "Vem är mer romantisk?",
    "Wer kocht besser?" to "Vem lagar bättre mat?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Vem tar hand om renovering och underhåll?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Vem märker snabbare när den andra personen inte mår bra?",
    "Wer sucht am Ende wirklich den Film aus?" to "Vem väljer egentligen filmen i slutändan?",
    "Wer vergisst eher einen Jahrestag?" to "Vem är mer benägen att glömma en årsdag?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Vem skulle vara mer benägen att glömma sitt eget namn nästa morgon?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Vem skulle vara mer sannolikt att hitta en video nästa dag som de inte visste något om?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Vem skulle hellre tillbringa natten i en främlings soffa?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Vem skulle vara mer benägen att somna på en fest och vakna upp med Sharpie i ansiktet?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Vem skulle vara mer benägen att halka på dansgolvet men få det att se ut som ett coolt drag?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Vem är mer benägen att ta kontroll över Spotify-spellistan på en hemmafest?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Vem skulle vara mer benägen att beställa pizza till alla på en fest och äta den själva?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Vem är mer benägen att somna först på en fest?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Vem skulle vara mer benägen att plötsligt börja städa upp på en fest?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Vem skulle vara mer benägen att hävda sig vara helt nykter när motsatsen är sant?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Vem är mer benägen att ge efter först i ett argument?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Vem är mer benägen att fuska vid ett dryckesspel?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Vem skulle vara mer benägen att plundra buffén och i hemlighet ta med sig mat hem?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Vem skulle vara mer benägen att lägga upp kvällens mest pinsamma foto i sin berättelse?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Vem skulle vara mer benägen att irritera DJ:n för att begära sin favoritlåt?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Vem skulle vara mer benägen att sjunga med i texten till en låt felaktigt, men med övertygelse?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Vem skulle vara mer benägen att beställa den dyraste drinken på menyn och ångra sig?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Vem skulle vara mer benägen att bjuda över grannarna om de klagade på oväsen?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Vem skulle ta partyspel (som Beer Pong) på för stort allvar?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Vem skulle vara mer benägen att bli vän med studsarna för att få VIP-åtkomst?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Vem skulle vara mer benägen att starta en spontan karaokestrid?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Vem är mer benägen att öppna en flaska utan att använda en flasköppnare?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Vem skulle vara mer benägen att hålla ett tal trots att absolut ingen frågade?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Vem skulle vara mer benägen att tillbringa en timme i badrummet och ta selfies?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Vem skulle vara mer benägen att sätta upp en pinsam dansföreställning och fira den?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Vem skulle vara mer benägen att ringa en ex-partner efter att festen är över?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Vem skulle vara mer benägen att av misstag förolämpa en främmande gäst?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Vem skulle vara mer benägen att i hemlighet lämna festen utan att säga adjö?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Vem skulle hellre leka med värdens husdjur än att prata med gästerna?",
    "Wer würde eher spontan eine Reise buchen?" to "Vem skulle vara mer benägen att boka en resa spontant?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Vem skulle vara mer benägen att ha djupa samtal i köket i timmar?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Vem är mer benägen att av misstag dricka någon annans drink?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Vem skulle vara mer benägen att av misstag välta en dyr vas eller något ömtåligt?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Vem skulle vara mer benägen att försöka blanda en komplicerad cocktail själv och misslyckas totalt?",
    "Wer würde eher zu spät kommen?" to "Vem är mer benägen att komma för sent?",
    "Wer würde eher?" to "Vem skulle föredra?",
    "Wer übernimmt die tägliche Versorgung?" to "Vem tar hand om den dagliga vården?",
    "Werde so akzeptiert, wie du bist" to "Bli accepterad som du är",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Kommer vi att ha tillräckligt med tid för barnet/barnen? ⏳",
    "Whirlpool" to "Badtunna",
    "White Chocolate" to "Vit choklad",
    "Widgets" to "Widgets",
    "Wie fühlst du dich am meisten geliebt?" to "Hur känner du dig mest älskad?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Hur hanterar vi olika inkomster?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Vilket är det bästa sättet för din partner att inleda sex med dig?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Hur kan din partner bli en ännu bättre partner för dig?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Hur lång tid efter förslaget vill du fira med andra?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Hur länge vill vi åtminstone stanna där?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Hur lätt är det för dig att prata om önskemål?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Hur vill du att vår framtid ska se ut?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Hur ser din perfekta söndag hemma ut?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Hur känner du för smutsigt prat under sex?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Hur mycket kredit har vi realistiskt råd med?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Hur mycket tid vill vi spendera isär?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Hur mycket vill vi spendera totalt?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Hur ska vi hitta tid för vårt förhållande när barnet väl kommer?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Hur viktigt är det för dig att ögonblicket fångas?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Hur viktigt är det för dig att ansökan speglar dina hobbyer eller intressen?",
    "Wie würdest du sie/ihn nennen?" to "Vad skulle du kalla honom/henne?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Vilket är ditt favoritsätt att visa tillgivenhet utanför sex?",
    "Wildblumen" to "Vilda blommor",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Vill du ha en tjej eller en pojke? 👶",
    "Wintergarten" to "Vinterträdgård",
    "Winterhochzeit" to "Vinterbröllop",
    "Wir bestellen einfach beides" to "Vi beställer bara båda",
    "Wir brauchen ewig" to "Det tar oss för evigt",
    "Wir einigen uns nie" to "Vi är aldrig överens",
    "Wir entscheiden es gemeinsam" to "Vi bestämmer tillsammans",
    "Wir treffen uns in der Mitte" to "Vi möts i mitten",
    "Wir wechseln uns ab" to "Vi turas om",
    "Wird stressig" to "Blir stressigt",
    "Wobei lachst du am meisten?" to "Vad får dig att skratta mest?",
    "Wofür sparen wir gemeinsam?" to "Vad sparar vi till tillsammans?",
    "Wohnzimmer" to "Vardagsrum",
    "Woran erinnerst du dich am lebhaftesten?" to "Vad minns du mest levande?",
    "Worauf freust du dich bei uns am meisten?" to "Vad ser du mest fram emot med oss?",
    "Worte/Komplimente" to "Ord/komplimanger",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Vad är du mest rädd för i vårt förhållande?",
    "Wünsche? z.B. günstig, draußen" to "Önskar? till exempel billigt, utanför",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Föredrar du att fria på semester (inklusive resor)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube Music",
    "Zeichne für mich" to "Rita åt mig",
    "Zeichne mich als Tier — welches wäre ich?" to "Rita mig som ett djur - vilket skulle jag vara?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Rita våra känslor för varandra som en symbol.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Rita vårt drömhus på en rad. Vad är det mest slående?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Rita vår första dejt – vad behöver definitivt vara med på bilden?",
    "Zeichnen" to "Rita",
    "Zeit füreinander" to "Dags för varandra",
    "Zeit, wenn das Baby schläft" to "Tid då barnet sover",
    "Zelten gehen" to "Gå och campa",
    "Zitrone" to "Citron",
    "Zu Hause, gemütlich und privat" to "Hemma, mysigt och privat",
    "Zu einem Picknick gehen" to "Går på picknick",
    "Zu einem ausgefallenen Abendessen gehen" to "Går på en fin middag",
    "Zu zweit reisen" to "Res som ett par",
    "Zuhause & Alltag" to "Hem och vardag",
    "Zuhören" to "Lyssna",
    "Zurück" to "Tillbaka",
    "Zusammen seit" to "Tillsammans sedan dess",
    "Zusammen seit (TT.MM.JJJJ)" to "Tillsammans sedan (DD.MM.ÅÅÅÅ)",
    "Zusammenziehen" to "Kontrakt",
    "Zustimmen oder Ablehnen" to "Håller med eller håller inte med",
    "Zwei Kreise, die sich überschneiden" to "Två cirklar som överlappar varandra",
    "Zwei Stühle davor" to "Två stolar framför den",
    "Zärtlich sein" to "Var öm",
    "Öfter als ich zugebe" to "Fler gånger än jag erkänner",
    "Über 100€/Monat" to "Över 100€/månad",
    "Über 2000 im Monat" to "Över 2000 i månaden",
    "Über mich selbst" to "Om mig själv",
    "Übernehmen" to "Ansök",
    "Überraschend" to "Överraskande",
    "Überraschung" to "Överraskning",
    "Überspringen" to "Hoppa över",
    "Übertrieben und großartig" to "Överdrivet och fantastiskt",
    "✎ Tippe, um zu antworten" to "✎ Tryck för att svara",
    "✨ GFK-Brücke" to "✨ GRP bro",
)

internal fun localizeSwedishDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_SWEDISH_CONTENT)
