package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_THAI_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 ปี",
    "1000 - 1500 im Monat" to "1000 - 1500 ต่อเดือน",
    "1000 bis 3000" to "1,000 ถึง 3,000",
    "1500 - 2000 im Monat" to "1500 - 2000 ต่อเดือน",
    "3000 bis 5000" to "3,000 ถึง 5,000",
    "5-10 Jahre" to "5-10 ปี",
    "50-100€/Monat" to "50-100€/เดือน",
    "Ab 100€" to "จาก 100€",
    "Ab 500€" to "จาก 500€",
    "Ab 50€" to "จาก 50€",
    "Ab und zu" to "เป็นระยะๆ",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "เราต้องใช้เงินเท่าไหร่ก่อนตัดสินใจซื้อ?",
    "Abbrechen" to "ยกเลิก",
    "Abenteuer" to "ผจญภัย",
    "Adidas" to "อาดิดาส",
    "Aktivitäten" to "กิจกรรม",
    "Alle" to "ทั้งหมด",
    "Alle Pakete" to "ทุกแพ็คเกจ",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "สูญเสียเพื่อนของคุณทั้งหมด ยกเว้นเพื่อนสนิทของคุณ",
    "Alle intimen Momente selbst initiieren" to "เริ่มต้นทุกช่วงเวลาแห่งความใกล้ชิดด้วยตัวคุณเอง",
    "Alles davon" to "ทั้งหมดเลย",
    "Alles, was noch kommt" to "ทุกสิ่งที่กำลังจะเกิดขึ้น",
    "Alltagsroutine" to "กิจวัตรประจำวัน",
    "Alltägliche Berührungen" to "สัมผัสได้ทุกวัน",
    "Altbau mit Charme" to "ตึกเก่ามีเสน่ห์",
    "Am Strand" to "บนชายหาด",
    "Am liebsten alles zusammen" to "รวมทุกอย่างเลยดีกว่า",
    "Am selben Tag mit Freunden/Familie" to "วันเดียวกันกับเพื่อน/ครอบครัว",
    "Amazon" to "อเมซอน",
    "Amsterdam" to "อัมสเตอร์ดัม",
    "Amsterdam, Niederlande" to "อัมสเตอร์ดัม เนเธอร์แลนด์",
    "An das Gefühl" to "แห่งความรู้สึก",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "ในสถานที่สาธารณะที่มีผู้ชมมากมาย",
    "An einen Geruch" to "ของกลิ่น",
    "An einen Song" to "สู่บทเพลง",
    "An etwas, das ich gesagt habe" to "บางสิ่งที่ฉันพูด",
    "Analyse starten" to "เริ่มการวิเคราะห์",
    "Analysiere eure Muster..." to "วิเคราะห์รูปแบบของคุณ...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "วิเคราะห์คำตอบและแชทของคุณตาม Gottman และ GFK",
    "Ananas auf der Pizza schmeckt köstlich." to "สับปะรดบนพิซซ่ารสชาติอร่อย",
    "Android" to "แอนดรอยด์",
    "Antwort mit einem Foto" to "ตอบพร้อมรูปถ่าย",
    "Antwortähnlichkeit" to "ตอบความเหมือน",
    "App-Sprache auswählen" to "เลือกภาษาของแอป",
    "Auf eine Bootsparty gehen" to "ไปปาร์ตี้ทางเรือ",
    "Aufmerksamkeit" to "โปรดทราบ",
    "Aufräumen und Projekte angehen" to "ทำความสะอาดและจัดการโครงการ",
    "Aufwärmen" to "วอร์มอัพ",
    "Aufwärmen: Einander kennenlernen" to "วอร์มอัพ : ทำความรู้จักกัน",
    "Aus dem Urlaub" to "จากวันหยุด",
    "Ausgefallener Name" to "ชื่อเก๋",
    "Ausschlafen und faulenzen" to "นอนพักผ่อนไปรอบๆ",
    "Ausschlafen und nichts tun" to "นอนแล้วไม่ทำอะไรเลย",
    "Aussehen" to "ดู",
    "Auto" to "รถ",
    "Außenkamin" to "เตาผิงกลางแจ้ง",
    "BEANTWORTE" to "คำตอบ",
    "Bali" to "บาหลี",
    "Bali, Indonesien" to "บาหลี, อินโดนีเซีย",
    "Banane" to "กล้วย",
    "Beantwortet" to "ตอบแล้ว",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "ตอบคำถามพร้อมกัน — คำตอบจะไม่ปรากฏให้เห็นจนกว่าคุณจะทำเสร็จทั้งคู่",
    "Beantwortete Fragen" to "ตอบคำถามแล้ว",
    "Bearbeiten" to "แก้ไข",
    "Bei Insider-Witzen" to "สำหรับเรื่องตลกวงใน",
    "Bei Memes" to "บนมีม",
    "Bei einer spontanen Berührung" to "เมื่อสัมผัสอย่างเป็นธรรมชาติ",
    "Beide" to "ทั้งคู่",
    "Beide gleich" to "เหมือนกันทั้งคู่",
    "Beide zusammen" to "กันทั้งคู่",
    "Beide, aber wir tun so als ob nicht" to "ทั้งคู่ แต่เราแกล้งทำเป็นว่าไม่",
    "Beides" to "ทั้งคู่",
    "Beides wäre schlimm" to "คงจะแย่ทั้งคู่",
    "Beim Einschlafen nebeneinander" to "เผลอหลับไปข้างกัน",
    "Beim Reden" to "ขณะที่กำลังพูดอยู่",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "ที่เที่ยวชื่อดังมักจะผิดหวังเสมอ",
    "Beschreibe unser Sexleben mit einem Emoji." to "บรรยายชีวิตเซ็กซ์ของเราด้วยอิโมจิ",
    "Besser kommunizieren" to "สื่อสารได้ดีขึ้น",
    "Bessere Lage" to "ตำแหน่งที่ดีขึ้น",
    "Bestellen" to "สั่งซื้อ",
    "Besuchte Länder" to "ประเทศที่เยี่ยมชม",
    "Besuchte Städte" to "เมืองต่างๆ ที่มาเยือน",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "คุณชอบข้อเสนอที่ฟุ่มเฟือยหรืออะไรที่ละเอียดอ่อนหรือไม่?",
    "Beziehung" to "ความสัมพันธ์",
    "Bibliothek" to "ห้องสมุด",
    "Bin manchmal unsicher" to "บางครั้งฉันก็ไม่มั่นใจ",
    "Bist du ein Videospiel-Guru?" to "คุณเป็นกูรูด้านวิดีโอเกมหรือเปล่า?",
    "Blumenwiese" to "ทุ่งดอกไม้",
    "Bunte Blumenwiese" to "ทุ่งดอกไม้หลากสีสัน",
    "Burger" to "เบอร์เกอร์",
    "Burger King" to "เบอร์เกอร์คิง",
    "Chat" to "แชท",
    "Coca-Cola" to "โคคา โคล่า",
    "Cookie Dough" to "แป้งคุกกี้",
    "Dachgarten mit Lounge" to "สวนดาดฟ้าพร้อมห้องนั่งเล่น",
    "Dachterrasse" to "ระเบียงดาดฟ้า",
    "Das Wetter an dem Tag" to "อากาศวันนั้น.",
    "Das erste Selfie" to "เซลฟี่ครั้งแรก",
    "Das meiste weiß ich" to "ฉันรู้เกือบหมดแล้ว",
    "Das oder das?" to "นี่หรือนั่น?",
    "Das tägliche Leben" to "ชีวิตประจำวัน",
    "Dass Zusagen gehalten werden" to "คำสัญญานั้นถูกรักษา",
    "Dass alles meinen Stil hat" to "ว่าทุกอย่างก็เป็นสไตล์ของผม",
    "Dass ich alles erzählen kann" to "ที่บอกได้ทุกเรื่อง",
    "Dass ich mich nicht sorgen muss" to "ที่ฉันไม่ต้องกังวล",
    "Dass wir ungestört sind" to "ว่าเราไม่รบกวน",
    "Dein Name" to "ชื่อของคุณ",
    "Deine Antwort..." to "คำตอบของคุณ...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "คำตอบของคุณจะถูกบันทึกไว้ ทันทีที่พันธมิตรทำแพ็คเกจเสร็จ คำตอบทั้งสองก็จะปรากฏพร้อมกัน",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "คำตอบของคุณจะถูกบันทึกไว้ เมื่อ \${profile.partnerName} เสร็จสิ้นแพ็คเกจแล้ว คำตอบทั้งสองจะปรากฏพร้อมกัน",
    "Deine Beziehung abenteuerlich und spontan machen" to "ทำให้ความสัมพันธ์ของคุณน่าตื่นเต้นและเป็นธรรมชาติ",
    "Deine Beziehung stabil und sicher machen" to "ทำให้ความสัมพันธ์ของคุณมั่นคงและปลอดภัย",
    "Deine eigene Antwort" to "คำตอบของคุณเอง",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "เป็นการดีกว่าที่จะแบ่งปันความลับที่ลึกที่สุดของคุณกับคู่ของคุณ",
    "Deinen besten Freund verlieren" to "การสูญเสียเพื่อนสนิทของคุณ",
    "Denke an dich" to "คิดถึงตัวเอง",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "การดูหนังเรื่องเดียวกันสองครั้งทำให้เสียเวลา",
    "Der Blick nach draußen" to "วิวภายนอก",
    "Der Garten" to "สวน",
    "Der Ort" to "สถานที่",
    "Der Ring und die Geste" to "แหวนและท่าทาง",
    "Der perfekte Heiratsantrag" to "การขอแต่งงานที่สมบูรณ์แบบ",
    "Derjenige sein, der umarmt wird" to "จงเป็นคนที่ถูกกอด",
    "Deutsch" to "เยอรมัน",
    "Diamant" to "เพชร",
    "Diamanten im Band" to "เพชรในวง",
    "Die Distanz" to "ระยะทาง",
    "Die Feiertage mit der Familie deines Partners verbringen" to "ใช้เวลาช่วงวันหยุดกับครอบครัวคู่รักของคุณ",
    "Die Gemütlichkeit und Ruhe" to "ความสบายและความสงบ",
    "Die Menschen, die darin wohnen" to "ผู้คนที่อาศัยอยู่ในนั้น",
    "Die Umgebung und Atmosphäre" to "สิ่งแวดล้อมและบรรยากาศ",
    "Die Worte und Emotionen" to "คำพูดและอารมณ์",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "สุดยอดความบันเทิงเกร็ดความรู้",
    "Diejenige sein, die umarmt" to "จงเป็นคนที่กอด",
    "Direkt ansprechen" to "ที่อยู่โดยตรง",
    "Diskussion" to "การสนทนา",
    "Diskutiere vor dem Kinderkriegen" to "พูดคุยก่อนมีลูก",
    "Diskutiert eure Antworten" to "อภิปรายคำตอบของคุณ",
    "Disney" to "ดิสนีย์",
    "Doch, schon mal" to "ใช่ ใช่",
    "Draußen mit der Natur als Kulisse" to "ภายนอกที่มีธรรมชาติเป็นฉากหลัง",
    "Drei-Stein-Ring" to "แหวนหินสามวง",
    "Du bist dran" to "ถึงตาคุณแล้ว",
    "Du fehlst mir" to "ฉันคิดถึงเธอ",
    "Dubai" to "ดูไบ",
    "Dubai, VAE" to "ดูไบ สหรัฐอาหรับเอมิเรตส์",
    "Dunkles Design" to "ธีมสีเข้ม",
    "Durch Berührung" to "โดยการสัมผัส",
    "Durch Worte" to "ผ่านคำพูด",
    "Durch Zeit zu zweit" to "ผ่านกาลเวลาร่วมกัน",
    "Durch kleine Gesten" to "ผ่านท่าทางเล็กๆ น้อยๆ",
    "Durchgeplant" to "วางแผนมาอย่างดี",
    "ERGEBNISSE" to "ผลลัพธ์",
    "Egal, Hauptsache gesund" to "ยังไงก็ตาม สิ่งสำคัญคือสุขภาพดี",
    "Ehepaar Leben" to "ชีวิตคู่.",
    "Eher knapp" to "ค่อนข้างใกล้เคียง",
    "Eher nicht" to "ไม่มากหรอก",
    "Eher schwer" to "ค่อนข้างยาก",
    "Eher schwierig" to "ค่อนข้างยาก",
    "Eher zu" to "เหมือนอีก",
    "Eifersucht ist ein Zeichen von Liebe." to "ความหึงหวงคือสัญลักษณ์แห่งความรัก",
    "Eigenes Gemüsebeet" to "เป็นเจ้าของแผ่นผัก",
    "Ein Abenteuer in einer neuen Stadt" to "การผจญภัยในเมืองใหม่",
    "Ein Anker" to "สมอเรือ",
    "Ein Balkon oder Garten" to "ระเบียงหรือสวน",
    "Ein Filmabend" to "คืนแห่งการดูหนัง",
    "Ein Harmony-Meilenstein eurer Liebe." to "ความกลมเกลียวแห่งความรักของคุณ",
    "Ein Herz" to "หัวใจ",
    "Ein Herz an der Tür" to "หัวใจที่ประตู",
    "Ein Jahr lang eine Fernbeziehung führen" to "มีความสัมพันธ์ทางไกลเป็นเวลาหนึ่งปี",
    "Ein Kindheitsessen" to "อาหารในวัยเด็ก",
    "Ein Live-Musik-Konzert besuchen" to "ร่วมชมคอนเสิร์ตดนตรีสด",
    "Ein Museum besuchen" to "เยี่ยมชมพิพิธภัณฑ์",
    "Ein Spieleabend" to "คืนเกม",
    "Ein Spieleabend mit Freunden" to "คืนเกมกับเพื่อน",
    "Ein Urlaubsfoto" to "ภาพวันหยุด",
    "Ein aktives Abenteuer" to "การผจญภัยที่กระตือรือร้น",
    "Ein entspannender Spa-Tag" to "วันสปาผ่อนคลาย",
    "Ein ganz normaler Alltagstag" to "วันธรรมดาๆ ของทุกๆ วัน",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "ค่ำคืนอันแสนสบายในบ้านท่ามกลางพายุฝนฟ้าคะนอง",
    "Ein gemütliches Date drinnen" to "นัดเดทสบายๆ ในบ้าน",
    "Ein lustiges Bild" to "ภาพตลกๆ",
    "Ein paar Handyfotos reichen" to "รูปจากมือถือไม่กี่รูปก็เพียงพอแล้ว",
    "Ein paar Stunden" to "ไม่กี่ชั่วโมง",
    "Ein paar kulturelle Anklänge sind okay" to "การอ้างอิงทางวัฒนธรรมบางส่วนก็ใช้ได้",
    "Ein romantischer Abend" to "ค่ำคืนสุดโรแมนติก",
    "Ein romantisches Abendessen bei Kerzenlicht" to "ดินเนอร์ใต้แสงเทียนแสนโรแมนติก",
    "Ein romantisches Bild" to "ภาพโรแมนติก",
    "Ein romantisches Picknick an einem schönen Ort" to "ปิกนิกสุดโรแมนติกในสถานที่สวยงาม",
    "Ein schwerer Moment, den wir geschafft haben" to "ช่วงเวลาที่ยากลำบากที่เราจัดการได้",
    "Ein tolles Date im Freien unter dem Mondlicht" to "นัดที่ยอดเยี่ยมกลางแจ้งใต้แสงจันทร์",
    "Ein ungewöhnliches Gericht" to "เมนูที่ไม่ธรรมดา",
    "Ein zufälliger Schnappschuss" to "สแน็ปช็อตแบบสุ่ม",
    "Einander kennenlernen" to "ทำความรู้จักกัน",
    "Eine Autoreise" to "การเดินทางบนท้องถนน",
    "Eine Brücke" to "สะพาน",
    "Eine Date-Nacht unter den Sternen" to "คืนเดทใต้แสงดาว",
    "Eine Million Dollar gewinnen" to "ชิงเงินล้าน",
    "Eine Million Dollar verdienen" to "สร้างเงินล้าน",
    "Eine Nacht in einem Club" to "ค่ำคืนหนึ่งในคลับ",
    "Eine Schokoladenverkostung" to "ชิมช็อคโกแลต",
    "Eine Wanderung mit Panoramablick machen" to "เดินป่าชมวิวแบบพาโนรามา",
    "Eine Weinverkostung" to "การชิมไวน์",
    "Eine gemeinsame Reise" to "การเดินทางร่วมกัน",
    "Eine gemütliche Nacht zu Hause" to "ค่ำคืนอันแสนสบายที่บ้าน",
    "Eine neue Sprache zu lernen ist einfach." to "การเรียนรู้ภาษาใหม่เป็นเรื่องง่าย",
    "Einen Film anschauen" to "ดูหนัง",
    "Einen Monat lang überhaupt nicht miteinander reden" to "ไม่ได้คุยกันเลยเป็นเดือน",
    "Einen Tanzkurs besuchen" to "เรียนเต้น",
    "Einen Vergnügungspark erkunden" to "สำรวจสวนสนุก",
    "Einen Wellness-Tag" to "วันแห่งสุขภาพที่ดี",
    "Einen sehr emotionalen Partner haben" to "การมีคู่ครองที่สะเทือนอารมณ์มาก",
    "Einen sehr logischen Partner haben" to "การมีคู่ครองที่สมเหตุสมผล",
    "Einer zahlt alles" to "คนหนึ่งจ่ายทุกอย่าง",
    "Einfach mehr Alltag" to "ชีวิตประจำวันที่เรียบง่ายยิ่งขึ้น",
    "Einfach nebeneinander sein" to "ขอแค่ได้อยู่ข้างๆกัน",
    "Einfach und intim" to "เรียบง่ายและใกล้ชิด",
    "Einige Dinge für dich behalten" to "เก็บบางอย่างไว้กับตัวเอง",
    "Einmal" to "ครั้งหนึ่ง",
    "Eins, das nur wir kennen" to "หนึ่งเดียวที่เรารู้",
    "Englisch" to "อังกฤษ",
    "Entspannte Hängematte" to "เปลญวนผ่อนคลาย",
    "Entspannung" to "ผ่อนคลาย",
    "Erdbeere" to "สตรอเบอร์รี่",
    "Erfolgreich" to "สำเร็จ",
    "Ergebnisse" to "ผลลัพธ์",
    "Erst bei sehr großen Summen" to "สำหรับผลรวมที่มากเท่านั้น",
    "Erst nur enge Freunde/Familie" to "ในตอนแรกมีเพียงเพื่อนสนิท/ครอบครัวเท่านั้น",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "มันทำให้ฉันรำคาญเมื่อคู่ของฉันใช้เวลาตอบข้อความนานเกินไป",
    "Essen & Genuss" to "อาหารและความเพลิดเพลิน",
    "Essensvorlieben" to "การตั้งค่าอาหาร",
    "Etwa eine Woche später, erst mal nur wir" to "ประมาณหนึ่งสัปดาห์ต่อมา มีเพียงเราในตอนแรก",
    "Etwas Neues ausprobieren" to "ลองอะไรใหม่ๆ",
    "Etwas ganz anderes" to "มีบางอย่างที่แตกต่างไปจากเดิมอย่างสิ้นเชิง",
    "Etwas sehr Scharfes" to "บางอย่างคมมาก",
    "Etwas, das ich selbst gern erfinde" to "ของที่ชอบประดิษฐ์เอง",
    "Etwas, eine kleine Note wäre schön" to "อะไรสักอย่าง โน้ตเล็กๆ น้อยๆ คงจะดี",
    "Familie" to "ครอบครัว",
    "Familie/Freunde" to "ครอบครัว/เพื่อน",
    "Familienmensch" to "คนในครอบครัว",
    "Farbedelstein" to "พลอยสี",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "บางครั้งโฆษณาทางทีวีก็ดูน่าสนใจ",
    "Fertig" to "เสร็จแล้ว",
    "Fertig!" to "เสร็จแล้ว!",
    "Feste Date-Nights" to "คืนวันที่คงที่",
    "Feuerstelle" to "หลุมไฟ",
    "Filigran & schlicht" to "ลวดลายและเรียบง่าย",
    "Filme/Serien" to "ภาพยนตร์/ซีรีส์",
    "Formuliere um..." to "ใช้ถ้อยคำใหม่...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "ใช้ถ้อยคำร่างใหม่ในลักษณะที่ไม่ใช้ความรุนแรง: การสังเกต ความรู้สึก ความต้องการ การร้องขอ",
    "Frage hinzufügen" to "เพิ่มคำถาม",
    "Fragen & Spiele" to "คำถามและเกม",
    "Fragen für jede Gelegenheit" to "คำถามสำหรับทุกโอกาส",
    "Freizeitpark" to "สวนสนุก",
    "Freunde treffen" to "พบปะเพื่อนฝูง",
    "Freundschaften mit Ex-Partnern sind okay." to "มิตรภาพกับแฟนเก่าก็โอเค",
    "Früh aufstehen" to "ตื่นเช้ากันเถอะ",
    "Fußbodenheizung" to "ระบบทำความร้อนใต้พื้น",
    "Führen wir getrennte oder gemeinsame Konten?" to "เรามีบัญชีแยกหรือบัญชีร่วมหรือไม่?",
    "Für dich empfohlen" to "แนะนำสำหรับคุณ",
    "Für die Zukunft" to "เพื่ออนาคต",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "ไม่พบคำถามหรือเกมที่ตรงกันสำหรับการค้นหานี้",
    "Für immer" to "ตลอดไป",
    "Fürsorglichkeit" to "ความห่วงใย",
    "GFK-Brücke" to "สะพาน GRP",
    "Galerie" to "แกลเลอรี่",
    "Gar nicht, der Moment gehört uns" to "ไม่เลย ขณะนี้เป็นของเรา",
    "Gar nichts tun" to "ไม่ต้องทำอะไรเลย",
    "Geduld" to "ความอดทน",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "ไปแต่เช้าเพื่อดูพระอาทิตย์ขึ้น",
    "Geht so" to "เป็นแบบนี้ครับ",
    "Geister existieren wirklich." to "ผีมีอยู่จริง",
    "Gelassenheit" to "ความสงบ",
    "Gelbgold" to "เยลโลว์โกลด์",
    "Geld & Finanzen" to "เงินและการเงิน",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "ท่องเที่ยวไปทั่วโลกด้วยกัน สำรวจวัฒนธรรม และอาหารใหม่ๆ",
    "Gemeinsam ein Lego bauen" to "ต่อเลโก้ด้วยกัน",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "ลองสูตรใหม่ด้วยกันในครัว",
    "Gemeinsame Konten" to "บัญชีที่ใช้ร่วมกัน",
    "Gemeinsame Nächte" to "ค่ำคืนด้วยกัน",
    "Gemeinsame Tage" to "วันที่อยู่ด้วยกัน",
    "Gemischt" to "มิกซ์",
    "Gemüsebeet" to "แผ่นแปะผัก",
    "Gemütliche Feuerstelle" to "เตาผิงแสนสบาย",
    "Gesprächsanreger" to "เริ่มต้นการสนทนา",
    "Getrennte Konten" to "แยกบัญชี",
    "Getrennte Urlaube tun einer Beziehung gut." to "วันหยุดที่แยกจากกันเป็นสิ่งที่ดีสำหรับความสัมพันธ์",
    "Gewächshaus" to "เรือนกระจก",
    "Glasfassade" to "ซุ้มกระจก",
    "Gleichgültigkeit" to "ความเฉยเมย",
    "Glücklich und frei" to "มีความสุขและอิสระ",
    "Gourmet Eis-Sorten" to "ไอศกรีมพันธุ์กูร์เมต์",
    "Gravur innen" to "งานแกะสลักด้านใน",
    "Grillplatz" to "พื้นที่บาร์บีคิว",
    "Groß & üppig" to "ใหญ่และเขียวชอุ่ม",
    "Große Familie" to "ครอบครัวใหญ่",
    "Große Feier" to "การเฉลิมฉลองครั้งใหญ่",
    "Große Fenster" to "หน้าต่างบานใหญ่",
    "Große Fensterfront" to "หน้าต่างบานใหญ่ด้านหน้า",
    "Großer Außenpool" to "สระว่ายน้ำกลางแจ้งขนาดใหญ่",
    "Großer Garten" to "สวนขนาดใหญ่",
    "Großer Stein" to "หินก้อนใหญ่",
    "Größere Küche" to "ห้องครัวใหญ่ขึ้น",
    "Gutes Essen" to "อาหารอร่อย",
    "Habe ich" to "ฉันทำ",
    "Habe ich noch nie" to "ฉันไม่เคยมี",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "คุณเคยค้นพบความแตกต่างที่น่าประหลาดใจบ้างไหม? พูดคุยว่าทำไมคุณถึงชอบตัวเลือกบางอย่างมากกว่า!",
    "Haus am See" to "บ้านริมทะเลสาบ",
    "Haus/Wohnung" to "บ้าน/อพาร์ทเมนต์",
    "Hazelnut" to "เฮเซลนัท",
    "Heimkino" to "โฮมเธียเตอร์",
    "Herzhaft" to "อิ่มอร่อย",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "ไม่มีอะไรที่นี่ตอนนี้\nเปลี่ยนตัวกรองหรือเลือกหัวข้ออื่น",
    "Hilfe im Alltag" to "ตัวช่วยในชีวิตประจำวัน",
    "Himbeere" to "ราสเบอร์รี่",
    "Hinzufügen" to "เพิ่ม",
    "Hobbys" to "งานอดิเรก",
    "Hochzeitssträuße" to "ช่อดอกไม้งานแต่งงาน",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "ความภาคภูมิใจของบ้านฮอกวอตส์: คุณอยู่ที่ไหน?",
    "Home" to "บ้าน",
    "Hot Tub" to "อ่างน้ำร้อน",
    "Humor" to "อารมณ์ขัน",
    "Hund" to "สุนัข",
    "Hängematte" to "เปลญวน",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "คุณต้องการจดหมายเป็นลายลักษณ์อักษรเป็นส่วนหนึ่งของใบสมัครหรือไม่?",
    "IKEA" to "อิเกีย",
    "Ich" to "ฉัน",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "ฉันชอบเดินเล่นในสวนสาธารณะแสนโรแมนติกมากกว่าไปดูหนัง",
    "Ich bin noch nie in einem Kino eingeschlafen." to "ฉันไม่เคยหลับในโรงหนัง",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "ฉันสนุกกับการค้นพบงานอดิเรกหรือกิจกรรมใหม่ๆ กับคู่ของฉัน",
    "Ich finde eine Alternative" to "ฉันจะหาทางเลือกอื่น",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "ฉันสนุกกับการลองร้านอาหารใหม่ๆ กับคู่รัก แทนที่จะไปร้านอาหารเดิมๆ เสมอๆ",
    "Ich habe noch nie" to "ฉันไม่เคย",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "ฉันไม่เคยกลัวรถไฟเหาะมาก่อน แต่ยังไงก็ตาม",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "ฉันไม่เคยซื้อตั๋ว Fast Pass เพราะใจร้อน",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "ฉันไม่เคยยกเลิกแผนการอยู่บ้านดูรายการทีวีเลย",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "ฉันไม่เคยรอจดหมายจากฮอกวอตส์เลย",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "ฉันไม่เคยบอกว่าสลิธีรินไม่ได้แย่ขนาดนั้นจริงๆ",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "ฉันไม่เคยบอกว่าฉันแก่เกินไปสำหรับหนังดิสนีย์ (และแอบชอบมัน)",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "ฉันไม่เคยจงใจยิงใครด้วยรถถังสีน้ำเงินใน Mario Kart เลย",
    "Ich habe noch nie bei einem Disney-Film geweint." to "ฉันไม่เคยร้องไห้กับหนังดิสนีย์เลย",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "ฉันไม่เคยหลับตาเวลาดูหนังสยองขวัญเลย",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "ฉันไม่เคยลืมที่จะบันทึกเกมและสูญเสียความคืบหน้าไปหลายชั่วโมง",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "ฉันไม่เคยออกจากห้องระหว่างที่มีฉากน่าเขินอายเลย (ปัจจัยประจบประแจง)",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "ฉันไม่เคยโพสท่าตลกๆ ขณะถ่ายรูปรถไฟเหาะเลย",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "ฉันไม่เคยเล่นเกมดึกดื่นและเสียใจที่เหนื่อยในวันรุ่งขึ้น",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "ฉันไม่เคยค้นหาตอนจบของหนังเลยเพราะรอไม่ไหวแล้ว",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "ฉันไม่เคยรู้สึกเหมือนยืนอยู่บนกองถ่ายหนังเลย",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "ฉันไม่เคยข้ามอินโทรซีรีส์โปรดของฉันเลย",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "ฉันไม่เคยแชร์รหัสผ่าน Netflix ของใครเลย",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "ฉันไม่เคยฟังเพลงประกอบเกมขณะทำงานหรือเรียนเลย",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "ฉันไม่เคยตำหนิผู้ควบคุมเมื่อฉันแพ้",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "ฉันไม่เคยทิ้งคีย์บอร์ดหรือคอนโทรลเลอร์ด้วยความโกรธ",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "ฉันไม่เคยลืมเสื้อผ้าที่เปียกในเครื่องซักผ้ามาสองสามวันแล้ว",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "ฉันไม่เคยใช้เงินจริงกับไอเทมตกแต่งในเกมเลย",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "ฉันไม่เคยขับรถไปต่างประเทศเลย",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "ฉันไม่เคยเปิดเพลงดิสนีย์ตอนอาบน้ำเลย",
    "Ich habe noch nie ein Elektroauto gefahren." to "ฉันไม่เคยขับรถไฟฟ้าเลย",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "ฉันไม่เคยถ่ายรูปกับมาสคอตของสวนสาธารณะเลย",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "ฉันไม่เคยตั้งชื่อสัตว์เลี้ยงตามตัวละครของฮอกวอตส์เลย",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "ฉันไม่เคยทำป๊อปคอร์นในโรงหนังแต่ก็ยังกินอยู่",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "ฉันไม่เคยใช้คำพูดของ Master Yoda จาก Star Wars ในชีวิตประจำวันเลย",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "ฉันไม่เคยซื้อของที่ระลึกราคาแพงเกินไปที่สวนสนุกเลย",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "ฉันไม่เคยให้คำแนะนำภาพยนตร์ที่คนอื่นมองว่าแย่เลย",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "ฉันไม่เคยดูออสการ์สดกลางดึกเลย",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "ฉันไม่เคยยกเลิกซีรีย์เลยเพราะซีซั่นที่แล้วห่วยมาก",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "ฉันไม่เคยดูซีรีส์เรื่องเดียวจบทั้งซีซั่นในวันเดียวเลย",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "ฉันไม่เคยเอาชนะบอสได้ในครั้งแรกและรู้สึกเหมือนเป็นพระเจ้า",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "ไม่เคยเจอตัวร้ายที่เท่กว่าพระเอกเลย",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "ฉันไม่เคยจำตัวละคร Toy Story ในของเล่นของตัวเองมาก่อนเลย",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "ฉันไม่เคยสร้างตัวละครในเกม RPG เหมือนฉันเลย",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "ฉันไม่เคยกินชูโรที่สวนสนุกเลย",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "ฉันไม่เคยดูหนังของดิสนีย์ถึงสามครั้งติดต่อกันเลย",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "ฉันไม่เคยมีเพลงที่ติดหูของดิสนีย์เลยตลอดทั้งสัปดาห์",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "ฉันไม่เคยดูภาพยนตร์เพียงเพราะนักแสดงบางคนเลย",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "ฉันไม่เคยฟังเพลงประกอบภาพยนตร์ซ้ำหลายชั่วโมงเลย",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "ฉันไม่เคยเปิดเผยสปอยล์หนังเลยและเสียใจทันที",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "ฉันไม่เคยพบเพื่อนที่พูดภาษาอื่นเลย",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "ฉันไม่เคยมีเพื่อนที่ย้ายไปอยู่ต่างประเทศเลย",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "ฉันไม่เคยดูภาพยนตร์แฮร์รี่ พอตเตอร์มาราธอนในวันคริสต์มาสเลย",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "ฉันไม่เคยดูหนัง Marvel เลยจนจบเพียงเพราะฉากท้ายเครดิต",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "ฉันไม่เคยตั้งใจรบกวน NPC (ตัวละครที่ไม่ใช่ผู้เล่น)",
    "Ich habe noch nie einen Nachtzug genommen." to "ฉันไม่เคยนั่งรถไฟกลางคืนเลย",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "ฉันไม่เคยทำแบบทดสอบออนไลน์เพื่อค้นหาบ้านฮอกวอตส์ของฉันเลย",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "ฉันไม่เคยลบโพสต์บนโซเชียลมีเดียเลยเพราะมันมีจำนวนไลค์ไม่เพียงพอ",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "ฉันไม่เคยเรียกวันที่สวนสนุกเป็นวันที่ดีที่สุดของปีเลย",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "ฉันไม่เคยไปสวนสนุกเลยและพักที่นี่ตั้งแต่เช้าจรดค่ำ",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "ฉันไม่เคยปล่อยให้เครื่องเล่น Transformers หรือ Marvel หลงใหลเลยแม้แต่น้อย",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "ฉันไม่เคยโกรธเลยเลิกแล้วออกจากเกม",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "ฉันไม่เคยอ่านแฮร์รี่ พอตเตอร์เล่มใหญ่ๆ เลย",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "ฉันไม่เคยคลั่งไคล้ตัวละครที่ฉันชื่นชอบในซีรีส์เลย",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "ฉันไม่เคยฝันที่จะเล่นควิดดิชเลย",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "ฉันไม่เคยแอบกูเกิ้ลวิธีแก้ด่านยากๆ เลย",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "ฉันไม่เคยแอบหวังว่าสัตว์เลี้ยงของฉันจะพูดได้เหมือนในดิสนีย์",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "ฉันไม่เคยลบผู้นำกลุ่มใน Sims ออกเลย",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "ฉันไม่เคยสูญเสียทิศทางในเครื่องเล่นจำลอง 3 มิติ",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "ฉันไม่เคยเล่นทีมกีฬามหาวิทยาลัยเลย",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "ฉันไม่เคยต่อคิวนานเกินสองชั่วโมงเพื่อเข้าชมสถานที่ท่องเที่ยวแห่งใดแห่งหนึ่ง",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "ฉันไม่เคยทำให้ของมีค่าของฉันเปียกขณะเล่นน้ำเลย",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "ฉันไม่เคยเถียงกับเพื่อนว่าบ้านไหนดีที่สุด",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "ฉันไม่เคยเสแสร้งว่ามีพลังวิเศษเหมือนเอลซ่าเลย",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "ฉันไม่เคยหัวเราะหนักมากจนพลาดฉากสำคัญในหนังเลย",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "ฉันไม่เคยรู้สึกถึงอะดรีนาลีนมากจนอยากขี่อีกครั้งในทันที",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "ฉันไม่เคยลองร้องเพลงร่วมกับสัตว์อย่างสโนว์ไวท์เลย",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "ฉันไม่เคยฝันว่าจะได้ไปเที่ยวดิสนีย์แลนด์เลย",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "ฉันไม่เคยฝันที่จะได้นั่งเครื่องเล่นน้ำ Jurassic Park มาก่อนเลย",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "ฉันไม่เคยกรีดร้องออกมาดังๆ เลยตอนกระโดดตกใจในเกม",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "ฉันไม่เคยร้องไห้กับตอนจบของรายการทีวีเลย",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "ไม่เคย... ยกเลิกเดทที่จะอยู่บ้านเลย",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "ฉันไม่เคย... เรียบเรียงข้อความซ้ำ 10 ครั้งเลย",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "ฉันไม่เคย... แอบดูโทรศัพท์มือถือของคู่ฉันเลย",
    "Ich habe noch nie!" to "ฉันไม่เคย!",
    "Ich habe!" to "มีแล้ว!",
    "Ich lache viel mit meinem Partner." to "ฉันหัวเราะมากกับคู่ของฉัน",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "ฉันชอบที่จะรู้จักงานอดิเรกและความสนใจของคู่ของฉัน",
    "Ich liebe es" to "ฉันชอบมัน",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "ฉันชอบดูหนังกับคู่ของฉันซึ่งเราทั้งสองคนไม่เคยดูมาก่อน",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "ฉันชอบแบ่งปันเพลงโปรดกับคู่ของฉัน",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "ฉันไม่เคยต้องวิ่งเพื่อขึ้นเครื่องเลย",
    "Ich plane gerne Dates mit meinem Partner." to "ฉันชอบวางแผนเดตกับคู่ของฉัน",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "ฉันให้ความสำคัญกับการใช้เวลาร่วมกับคู่ของฉันแม้ว่าฉันจะยุ่งก็ตาม",
    "Ich schreibe meinem Partner jeden Tag." to "ฉันส่งข้อความหาคู่ของฉันทุกวัน",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "ฉันชอบแบ่งปันมีมและเรื่องตลกกับคู่ของฉัน",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "ฉันชอบแบ่งปันรายละเอียดทั้งหมดของวันของฉันกับคู่ของฉัน",
    "Ich würde es nie tun" to "ฉันจะไม่มีวันทำมัน",
    "Ich übe noch" to "ฉันยังคงฝึกซ้อมอยู่",
    "Ideen generieren" to "สร้างสรรค์ไอเดีย",
    "Im Haushalt helfen" to "ช่วยเหลือเรื่องบ้าน",
    "In Chat einfügen" to "เพิ่มในแชท",
    "In Stille nebeneinander" to "ในความเงียบงันที่อยู่เคียงข้างกัน",
    "In den Bergen" to "ในภูเขา",
    "In eine Bar gehen" to "ไปที่บาร์",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "ไปบาร์ริมชายหาดเพื่อชมพระอาทิตย์ตก",
    "In einem feinen Restaurant essen gehen" to "กินข้าวนอกบ้านในร้านอาหารหรูๆ",
    "In einen Coffeeshop gehen" to "ไปร้านกาแฟ",
    "In einer Beziehung sollte man alles voneinander wissen." to "ในความสัมพันธ์คุณควรรู้ทุกอย่างเกี่ยวกับกันและกัน",
    "Infinity-Pool" to "สระว่ายน้ำอินฟินิตี้",
    "Innenpool" to "สระว่ายน้ำในร่ม",
    "Intelligenz" to "ความฉลาด",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "มีเฉพาะช่วงเวลาที่ใกล้ชิดเมื่อคู่ของคุณเริ่มต้นเท่านั้น",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "รหัสเชิญ: HRM-8731 · ปลดล็อคทุกอย่างแล้ว",
    "Island" to "ไอซ์แลนด์",
    "Ist okay für mich" to "ฉันไม่เป็นไร",
    "Ist schon perfekt" to "เป๊ะเลย",
    "Ja, Traditionen einbinden" to "ใช่ ผสมผสานประเพณีเข้าด้วยกัน",
    "Ja, absolut" to "ใช่เลย",
    "Ja, etwas zum Lesen und Aufbewahren" to "ใช่ มีบางอย่างให้อ่านและเก็บไว้",
    "Ja, genug" to "ใช่แล้ว พอแล้ว",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "ใช่แล้ว ในเมืองหรือสถานที่ท่องเที่ยวที่น่าตื่นเต้น",
    "Ja, in- und auswendig" to "ใช่ ทั้งภายในและภายนอก",
    "Ja, komplett überraschend" to "ใช่ น่าแปลกใจมาก",
    "Ja, perfekt" to "ใช่ สมบูรณ์แบบ",
    "Ja, sie gehören zur Familie!" to "ใช่แล้ว พวกเขาคือครอบครัว!",
    "Ja, sofort teilen" to "ใช่แล้ว แชร์ทันที",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "ใช่ เราจะทำให้แน่ใจว่าเวลาของครอบครัวเป็นสิ่งสำคัญที่สุด",
    "Jacuzzi" to "อ่างจากุซซี่",
    "Jahr zusammen 🎉" to "อยู่ด้วยกันตลอดปี 🎉",
    "Jahre zusammen 🎉" to "อยู่ด้วยกันตลอดปี 🎉",
    "Jeder zahlt 50%" to "ทุกคนจ่าย 50%",
    "Junge" to "ไอ้หนู",
    "Kamin" to "เตาผิง",
    "Karriere & Erfolg" to "อาชีพและความสำเร็จ",
    "Kategorien" to "หมวดหมู่",
    "Katze" to "แมว",
    "Keine Musik" to "ไม่มีดนตรี",
    "Keine Party nötig, privat halten" to "ไม่ต้องปาร์ตี้ เก็บไว้เป็นส่วนตัว",
    "Keine Privatsphäre" to "ไม่มีความเป็นส่วนตัว",
    "Keine Treffer gefunden" to "ไม่พบรายการที่ตรงกัน",
    "Keiner" to "ไม่มี",
    "Keiner von uns" to "พวกเราไม่มีใคร",
    "Kennst du die Essensvorlieben deines Partners?" to "คุณรู้จักความชอบด้านอาหารของคู่ของคุณไหม?",
    "Kino" to "ภาพยนตร์",
    "Kirchlich" to "นักบวช",
    "Klassisch Solitär" to "เล่นไพ่คนเดียวคลาสสิก",
    "Klassisch gebunden" to "ผูกพันแบบคลาสสิก",
    "Klein & zart" to "เล็กและละเอียดอ่อน",
    "Kleine Geschenke" to "ของขวัญเล็กๆ น้อยๆ",
    "Kleine Runde" to "กลุ่มเล็ก",
    "Kochen und Freunde einladen" to "ทำอาหารชวนเพื่อน",
    "Kochkurs" to "คลาสเรียนทำอาหาร",
    "Kommt auf den Tag an" to "ขึ้นอยู่กับวัน",
    "Kommt darauf an" to "มันขึ้นอยู่กับ",
    "Kommt drauf an" to "มันขึ้นอยู่กับ",
    "Kommt mit" to "มากับฉันสิ",
    "Konzert" to "คอนเสิร์ต",
    "Kräftige Farben" to "สีสันสดใส",
    "Kräuterbeet" to "เตียงสมุนไพร",
    "Kultur & Sehenswürdigkeiten" to "วัฒนธรรมและสถานที่ท่องเที่ยว",
    "Kuscheln" to "กอดกัน",
    "Kuss senden" to "ส่งจูบ",
    "Körperliche Annäherung" to "การเข้าใกล้ทางกายภาพ",
    "Körperliche Nähe" to "ความใกล้ชิดทางกาย",
    "Küche" to "ครัว",
    "Land" to "ประเทศ",
    "Landhaus" to "บ้านในชนบท",
    "Landhausstil" to "บ้านสไตล์คันทรี่",
    "Lange wach bleiben" to "นอนดึกนะ",
    "Lappland" to "แลปแลนด์",
    "Lappland, Finnland" to "แลปแลนด์ ฟินแลนด์",
    "Las Vegas" to "ลาสเวกัส",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Let your partner inspire you to be your best self",
    "Lehne ab" to "ปฏิเสธ",
    "Leichtigkeit" to "ความบางเบา",
    "Leidenschaft" to "ความหลงใหล",
    "Liebe im Gleichgewicht" to "รักสมดุล",
    "Liebe sie, macht mehr Spaß" to "รักพวกเขา สนุกกว่า",
    "Lieber durchgeplant oder spontan?" to "Would you rather have it planned out or spontaneous?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Would you rather have a quiet evening for two or with people?",
    "Lieber nicht" to "ไม่ดีกว่า",
    "Lieber vorher grob absprechen" to "It's better to discuss things roughly beforehand",
    "Lokal einkaufen" to "ช้อปในพื้นที่",
    "London" to "ลอนดอน",
    "London, England" to "ลอนดอน ประเทศอังกฤษ",
    "Lügen" to "คำโกหก",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "คุณชอบข้อเสนอสาธารณะหรือส่วนตัวมากกว่ากัน?",
    "Malediven" to "มัลดีฟส์",
    "Man sollte nie streitend einschlafen." to "คุณไม่ควรเผลอหลับไปเถียงกัน",
    "Mango Sorbet" to "เชอร์เบทมะม่วง",
    "Markant & breit" to "โดดเด่น & กว้าง",
    "Marken & Alltag" to "แบรนด์และชีวิตประจำวัน",
    "McDonald’s" to "แมคโดนัลด์",
    "Mediterraner Innenhof" to "ลานเมดิเตอร์เรเนียน",
    "Mehr Unterstützung" to "การสนับสนุนเพิ่มเติม",
    "Mehr gemeinsame Zeit" to "มีเวลาอยู่ด้วยกันมากขึ้น",
    "Mehr zuhören" to "ฟังให้มากขึ้น",
    "Mehrgenerationenhaus" to "บ้านหลายชั่วอายุคน",
    "Mein Arbeitsplatz" to "ที่ทำงานของฉัน",
    "Mein Partner" to "คู่หูของฉัน",
    "Mich überraschen" to "เซอร์ไพรส์ฉันหน่อย",
    "Minimalistisches Interieur" to "ภายในสไตล์มินิมอล",
    "Missverständnisse" to "ความเข้าใจผิด",
    "Mit Familie und engen Freunden" to "กับครอบครัวและเพื่อนสนิท",
    "Mit Kompromissen" to "ด้วยการประนีประนอม",
    "Mitgefühl" to "ความเมตตา",
    "Mittelweg mit besonderen Details" to "พื้นกลางพร้อมรายละเอียดพิเศษ",
    "Modern geometrisch" to "เรขาคณิตสมัยใหม่",
    "Moderne Grillstation" to "เตาย่างสไตล์โมเดิร์น",
    "Moderner Name" to "ชื่อสมัยใหม่",
    "Moderner Solitär" to "เล่นไพ่คนเดียวที่ทันสมัย",
    "Moissanit" to "มอยซาไนต์",
    "Moment festhalten" to "บันทึกช่วงเวลาสำคัญ",
    "Momente" to "ช่วงเวลา",
    "Monaco" to "โมนาโก",
    "Moralische Werte" to "คุณค่าทางศีลธรรม",
    "Museum" to "พิพิธภัณฑ์",
    "Musik" to "ดนตรี",
    "Mut" to "ความกล้าหาญ",
    "Mädchen" to "สาวๆ",
    "Möbelhaus" to "ร้านเฟอร์นิเจอร์",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "คุณแน่ใจหรือว่าต้องการออกจากแบบทดสอบ? ความคืบหน้าก่อนหน้าของคุณยังคงถูกบันทึกไว้",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "คุณต้องการให้รวมสัตว์เลี้ยงไว้ในใบสมัครหรือไม่?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "ต้องการแชร์ช่วงเวลาบนโซเชียลมีเดียทันทีหรือไม่?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "เราอาจจะต้องออมเงิน",
    "Müssen es planen" to "จำเป็นต้องวางแผน",
    "Müssen sparen" to "จำเป็นต้องบันทึก",
    "Nachricht an" to "ข้อความ",
    "Name Partnerin" to "ชื่อหุ้นส่วน",
    "Namen und Startdatum eurer Beziehung." to "ชื่อและวันที่เริ่มต้นความสัมพันธ์ของคุณ",
    "Natursteinfassade" to "ซุ้มหินธรรมชาติ",
    "Naturteich" to "บ่อน้ำธรรมชาติ",
    "Nein, einfach halten" to "ไม่ แค่จับมันไว้",
    "Nein, erstmal privat halten" to "ไม่ เก็บเป็นความลับไว้ก่อน",
    "Nein, lieber vor Ort" to "ไม่ ดีกว่าที่ไซต์งาน",
    "Nein, modern halten" to "ไม่ ทำให้มันทันสมัยอยู่เสมอ",
    "Nein, nur wir" to "ไม่ แค่พวกเราเท่านั้น",
    "Nein, zu ablenkend" to "ไม่ กวนใจเกินไป",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "อาคารใหม่พร้อมบ้านอัจฉริยะ",
    "Neubau mit Technik" to "อาคารใหม่พร้อมเทคโนโลยี",
    "Neue Liebe, neue Erfahrungen" to "รักครั้งใหม่ ประสบการณ์ใหม่",
    "Neues Hobby" to "งานอดิเรกใหม่",
    "Neues Spiel" to "เกมใหม่",
    "Neugier" to "ความอยากรู้อยากเห็น",
    "New York" to "นิวยอร์ก",
    "New York, USA" to "นิวยอร์ก สหรัฐอเมริกา",
    "Nicht mein Fall" to "ไม่ใช่ถ้วยชาของฉัน",
    "Nicht nötig, lieber klassisch bleiben" to "ไม่จำเป็น เก็บความคลาสสิกไว้ดีกว่า",
    "Nichts — es passt so" to "ไม่มีอะไร - มันพอดี",
    "Nie wieder Burger" to "ไม่มีเบอร์เกอร์อีกต่อไป",
    "Nie wieder Pizza" to "ไม่ต้องพิซซ่าอีกต่อไป",
    "Niemand" to "ไม่มีใคร",
    "Niemand ohne Plan" to "ไม่มีใครไม่มีแผน",
    "Nike" to "ไนกี้",
    "Nizza" to "เยี่ยมเลย",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "ยังไม่มีช่วงเวลาใดๆ\nบันทึกประสบการณ์ครั้งแรกของคุณ 💞",
    "Nur bei wichtigen Themen" to "เฉพาะหัวข้อสำคัญเท่านั้น",
    "Nur wir beide" to "แค่เราสองคน",
    "Nähe & Intimität" to "ความใกล้ชิดและความใกล้ชิด",
    "Obstgarten" to "สวนผลไม้",
    "Oder" to "หรือ",
    "Offene Küche" to "ครัวเปิด",
    "Offene Wohnküche" to "ห้องครัว/ห้องนั่งเล่นแบบเปิด",
    "Ohne Stein" to "ไร้หิน",
    "Open End" to "เปิดตอนจบ",
    "Outdoor-Küche" to "ครัวนอกบ้าน",
    "Outdoor-Sofa" to "โซฟาสนาม",
    "Outdoor-Whirlpool" to "อ่างน้ำวนกลางแจ้ง",
    "Ovaler Diamant" to "เพชรทรงรี",
    "Paar" to "จับคู่",
    "Paar-Statistiken" to "สถิติคู่รัก",
    "Paris" to "ปารีส",
    "Paris, Frankreich" to "ปารีส ฝรั่งเศส",
    "Partner" to "พันธมิตร",
    "Partner-Simulator" to "โปรแกรมจำลองพันธมิตร",
    "Partnerin" to "พันธมิตร",
    "Party Edition" to "ฉบับปาร์ตี้",
    "Party Edition II" to "ปาร์ตี้ฉบับที่ 2",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "สัตว์ยังเข้ากับชีวิตประจำวันของเราได้ด้วยเหรอ?",
    "Pasta" to "พาสต้า",
    "Pastell" to "สีพาสเทล",
    "Penthouse mit Ausblick" to "เพนท์เฮาส์พร้อมวิว",
    "Pepsi" to "เป๊ปซี่",
    "Pergola mit Lounge" to "ซุ้มไม้เลื้อยพร้อมเลานจ์",
    "Pfingstrosen" to "ดอกโบตั๋น",
    "Pinguin" to "เพนกวิน",
    "Pistazie" to "พิสตาชิโอ",
    "Pizza" to "พิซซ่า",
    "Pizzaofen" to "เตาอบพิซซ่า",
    "Platin" to "แพลตตินัม",
    "PlayStation" to "เพลย์สเตชัน",
    "Pool" to "สระน้ำ",
    "Pop" to "ป็อป",
    "Prasselnder Kamin" to "เตาผิงคำราม",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "เจ้าหญิง โจรสลัด และฝุ่นนางฟ้า: แบบทดสอบดิสนีย์",
    "Privater Innenhof" to "ลานส่วนตัว",
    "Profil" to "โปรไฟล์",
    "Profil bearbeiten" to "แก้ไขโปรไฟล์",
    "Prozentual nach Einkommen" to "เปอร์เซ็นต์ตามรายได้",
    "Quiz verlassen" to "ออกจากแบบทดสอบ",
    "Quiz verlassen?" to "ออกจากแบบทดสอบเหรอ?",
    "Rausgehen in die Natur" to "ออกไปสู่ธรรมชาติ",
    "Reden vor ..." to "พูดคุยกับ...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "กำหนดวันหรือเวลาปกติร่วมกัน",
    "Reisen" to "ท่องเที่ยว",
    "Reiseziele" to "จุดหมายปลายทางการท่องเที่ยว",
    "Respektlosigkeit" to "การไม่เคารพ",
    "Restaurant" to "ร้านอาหาร",
    "RnB / Soul" to "RnB / โซล",
    "Rock" to "ร็อค",
    "Rom" to "โรม",
    "Rom, Italien" to "โรม อิตาลี",
    "Romantik" to "โรแมนติก",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "ท่าทางโรแมนติก เช่น ข้อความ โน้ต หรือของขวัญ ทำให้ฉันมีความสุข",
    "Romantische Stimmung" to "อารมณ์โรแมนติก",
    "Roségold" to "สีโรสโกลด์",
    "Ruhig zu zweit" to "เงียบสำหรับสองคน",
    "Runder Diamant" to "เพชรกลม",
    "Salted Caramel" to "คาราเมลเค็ม",
    "Sammle Ideen..." to "รวบรวมไอเดีย...",
    "Santorini" to "ซานโตรินี",
    "Santorini, Griechenland" to "ซานโตรินี กรีซ",
    "Saphir" to "แซฟไฟร์",
    "Saunahaus" to "บ้านซาวน่า",
    "Schickes Restaurant oder Hotel" to "ร้านอาหารหรือโรงแรมสุดชิค",
    "Schlafzimmer" to "ห้องนอน",
    "Schließen" to "ปิด",
    "Schmal & zart" to "เพรียวบางและละเอียดอ่อน",
    "Schnappschüsse aus unserer Liebesgeschichte" to "รวมภาพเรื่องราวความรักของเรา",
    "Schokolade" to "ช็อคโกแลต",
    "Schreib frei, was dir wirklich dazu einfällt." to "เขียนสิ่งที่อยู่ในใจได้อย่างอิสระ",
    "Schreibe deine eigene Antwort" to "เขียนคำตอบของคุณเอง",
    "Sehr gerne" to "ยินดีครับ",
    "Sehr leicht" to "เบามาก",
    "Sehr wichtig — Fotos und Video" to "สำคัญมาก — ภาพถ่ายและวิดีโอ",
    "Sehr wichtig, es sollte persönlich sein" to "สำคัญมาก ควรเป็นเรื่องส่วนตัว",
    "Selbst kochen" to "ทำอาหารเอง.",
    "Senden" to "ส่ง",
    "Separate Küche" to "ครัวแยก",
    "Serie schauen" to "ชมซีรีส์",
    "Serienmarathon auf dem Sofa" to "ซีรีส์มาราธอนบนโซฟา",
    "Sex & Liebe" to "เซ็กส์ & ความรัก",
    "Seychellen" to "เซเชลส์",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "เราสามารถรับผิดชอบค่าใช้จ่ายทั้งหมดสำหรับเด็กหนึ่งคนหรือหลายคนได้หรือไม่? 💰",
    "Soll der Antrag eine Überraschung sein?" to "ข้อเสนอควรจะเซอร์ไพรส์ไหม?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "แอปพลิเคชันควรมีองค์ประกอบทางวัฒนธรรมหรือดั้งเดิมหรือไม่",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "แอปพลิเคชันควรมีองค์ประกอบทางวัฒนธรรมหรือดั้งเดิมหรือไม่",
    "Sommerhochzeit" to "งานแต่งงานหน้าร้อน",
    "Sonnige Dachterrasse" to "ระเบียงดาดฟ้ารับแสงแดด",
    "Sowohl als auch" to "ทั้งและ",
    "Spazieren" to "เดินเล่น.",
    "Spaß & Abenteuer" to "ความสนุกและการผจญภัย",
    "Speichern" to "บันทึก",
    "Spiel bearbeiten" to "แก้ไขเกม",
    "Spielbereich für Kinder" to "พื้นที่เล่นสำหรับเด็ก",
    "Spiele" to "เกมส์",
    "Spiele spielen und Spaß haben" to "เล่นเกมให้สนุกนะ",
    "Spontan" to "เป็นธรรมชาติ",
    "Sportplatz" to "สนามกีฬา",
    "Spotify" to "สปอทิฟาย",
    "Sprache" to "ภาษา",
    "Stadt" to "เมือง",
    "Stadt oder Land — was ist uns wichtiger?" to "เมืองหรือประเทศ - อะไรสำคัญสำหรับเรามากกว่ากัน?",
    "Stadtvilla" to "ซิตี้วิลล่า",
    "Standesamt & Party" to "สำนักงานทะเบียนและฝ่ายบุคคล",
    "Statement-Ring" to "วงแหวนแถลงการณ์",
    "Stilvolles Outdoor-Sofa" to "โซฟากลางแจ้งมีสไตล์",
    "Stimme voll zu" to "เห็นด้วยอย่างยิ่ง",
    "Stimmt" to "ใช่แล้ว",
    "Stimmt nicht" to "ไม่จริง",
    "Stimmt, noch nie" to "จริง ไม่เคยเลย",
    "Stracciatella" to "สแตรคเซียเตลล่า",
    "Strandtag" to "วันชายหาด",
    "Streit über Haushalt" to "ข้อพิพาทเรื่องครัวเรือน",
    "Studio Ghibli" to "สตูดิโอจิบลิ",
    "Ständig" to "อย่างต่อเนื่อง",
    "Suche schließen" to "ปิดการค้นหา",
    "Suche zurücksetzen" to "รีเซ็ตการค้นหา",
    "Suche öffnen" to "เปิดการค้นหา",
    "Suchergebnisse" to "ผลการค้นหา",
    "Sushi" to "ซูชิ",
    "Süß" to "หวานใจ",
    "Tage zusammen 💞" to "วันที่อยู่ด้วยกัน 💞",
    "Tauche ins Unterbewusstsein" to "ดำดิ่งสู่จิตใต้สำนึก",
    "Teile alle deine Hobbys mit deinem Partner" to "แบ่งปันงานอดิเรกทั้งหมดของคุณกับคู่ของคุณ",
    "Teils teils" to "บางส่วน",
    "Testen" to "ทดสอบ",
    "Themen" to "หัวข้อ",
    "Tiefe Gespräche" to "บทสนทนาอันลึกซึ้ง",
    "Tiefgründige Gespräche führen" to "มีบทสนทนาที่ลึกซึ้ง",
    "Tierpension" to "โรงพักเลี้ยงสัตว์",
    "Tiny House" to "บ้านจิ๋ว",
    "Tippen zum Auswählen & Scrollen" to "แตะเพื่อเลือกและเลื่อน",
    "Tippen zum Zuklappen" to "แตะเพื่อยุบ",
    "Titel" to "หัวข้อ",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "หัวข้อ หมวดหมู่ หัวข้อ แท็ก คำถาม...",
    "Tokyo, Japan" to "โตเกียว ประเทศญี่ปุ่น",
    "Traditioneller Name" to "ชื่อดั้งเดิม",
    "Traumhaus Außenbereich" to "พื้นที่นอกบ้านบ้านในฝัน",
    "Traumhochzeit" to "งานแต่งงานในฝัน",
    "Treffer" to "ฮิตเลย",
    "Tägliche Aktivität" to "กิจกรรมประจำวัน",
    "Umformulieren" to "ใช้ถ้อยคำใหม่",
    "Unbeantwortet" to "ยังไม่มีคำตอบ",
    "Unbeliebte Meinungen" to "ความคิดเห็นที่ไม่เป็นที่นิยม",
    "Universal Studios Genie oder Neuling?" to "อัจฉริยะ Universal Studios หรือมือใหม่?",
    "Uns auseinanderzuleben" to "ที่จะแยกจากกัน",
    "Unser Intimleben" to "ชีวิตส่วนตัวของเรา",
    "Unser Traumhaus" to "บ้านในฝันของเรา",
    "Unser erstes Treffen" to "การพบกันครั้งแรกของเรา",
    "Unsere Gesichter" to "ใบหน้าของเรา",
    "Unsere eigenen Träume" to "ความฝันของเราเอง",
    "Unsere nächste Reise" to "ทริปต่อไปของเรา",
    "Unter 1000" to "ต่ำกว่า 1,000",
    "Unter 1000 im Monat" to "ต่ำกว่า 1,000 ต่อเดือน",
    "Unter 50€/Monat" to "ต่ำกว่า 50€/เดือน",
    "Unter Leuten" to "ท่ามกลางผู้คน",
    "Untreue" to "การนอกใจ",
    "Urlaub" to "วันหยุด",
    "Vanille" to "วานิลลา",
    "Venedig" to "เวนิส",
    "Venedig, Italien" to "เวนิส, อิตาลี",
    "Verbinde dich mit" to "เชื่อมต่อกับ",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "เชื่อมต่อกับ \${profile.partnerName} เพื่อดูคำตอบ",
    "Verbindung" to "การเชื่อมต่อ",
    "Verbringe die Feiertage mit deiner Familie" to "ใช้เวลาช่วงวันหยุดกับครอบครัวของคุณ",
    "Verlobungsringe" to "แหวนหมั้น",
    "Vertrautheit" to "ความคุ้นเคย",
    "Viel getrennt" to "แยกกันมาก",
    "Vielleicht ein oder zwei" to "อาจจะหนึ่งหรือสอง",
    "Vielleicht, aber mündlich reicht" to "อาจจะ แต่ด้วยวาจาก็เพียงพอแล้ว",
    "Vielleicht, wenn es machbar ist" to "บางที ถ้าเป็นไปได้",
    "Vielleicht, wenn es passt" to "บางทีถ้ามันพอดี",
    "Vintage Art déco" to "วินเทจ อาร์ตเดโค",
    "Vintage verspielt" to "วินเทจขี้เล่น",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "ได้รับการแนะนำให้รู้จักกับงานอดิเรกใหม่ ๆ จากคู่ของคุณ",
    "Vor dem Kauf eines Hauses besprechen" to "พูดคุยก่อนซื้อบ้าน",
    "Vor der Anschaffung eines Haustiers besprechen" to "พูดคุยก่อนซื้อสัตว์เลี้ยง",
    "Vor der gemeinsamen Reise besprechen" to "พูดคุยก่อนออกเดินทางกัน",
    "Vor nichts" to "ไม่มีอะไร",
    "Vorort" to "ชานเมือง",
    "Walnuss" to "วอลนัท",
    "Wandern" to "เดินป่า",
    "Wann fühlst du dich mir am nächsten?" to "เมื่อไหร่ที่คุณรู้สึกใกล้ชิดฉันมากที่สุด?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "เมื่อไหร่ที่คุณรู้สึกใกล้ชิดกับฉันมากที่สุด?",
    "Was bedeutet Vertrauen für dich konkret?" to "ความไว้วางใจมีความหมายต่อคุณเป็นพิเศษอย่างไร?",
    "Was entspannt dich mehr?" to "อะไรทำให้คุณผ่อนคลายได้มากกว่านี้?",
    "Was fehlt dir über die Distanz am meisten?" to "คุณคิดถึงอะไรมากที่สุดเกี่ยวกับระยะทาง?",
    "Was gefällt dir an deinem Zuhause am besten?" to "บ้านของคุณชอบอะไรมากที่สุด?",
    "Was hast du von deinem Partner gelernt?" to "คุณได้เรียนรู้อะไรจากคู่ของคุณ?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "คุณคิดอย่างไรกับการดูเนื้อหาอีโรติกด้วยกัน?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "คุณคิดอย่างไรเกี่ยวกับอุปกรณ์ประกอบฉาก (เช่น ป้าย ลูกโป่ง ฯลฯ)?",
    "Was ist das Wichtigste beim Antrag?" to "สิ่งสำคัญที่สุดในการสมัครคืออะไร?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "อะไรคือสิ่งที่สำคัญที่สุดที่คุณมองหาในการมีเซ็กส์?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "รูปไหนของพวกเราที่คุณชอบที่สุด? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "อะไรคือสิ่งที่คุณกลัวที่สุดในการอยู่ด้วยกัน?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "อาหารอะไรที่คุณชอบแต่คู่ไม่เข้าใจ?",
    "Was ist für dich ein absoluter Dealbreaker?" to "อะไรคือตัวทำลายล้างที่แท้จริงสำหรับคุณ?",
    "Was ist für jeden von uns das absolute Highlight?" to "อะไรคือไฮไลท์ที่แท้จริงของพวกเราแต่ละคน?",
    "Was ist passiert?" to "เกิดอะไรขึ้น?",
    "Was macht einen Moment für dich romantisch?" to "อะไรที่ทำให้ช่วงเวลาโรแมนติกสำหรับคุณ?",
    "Was magst du an deinem Partner am liebsten?" to "คุณชอบอะไรในตัวคู่ของคุณมากที่สุด?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "คุณชอบอะไรมากกว่า: ตื่นเช้าหรือนอนดึก?",
    "Was magst du lieber?" to "ชอบอันไหนมากกว่ากัน?",
    "Was möchtest du eigentlich sagen?" to "จริงๆ แล้วคุณอยากจะพูดอะไรล่ะ?",
    "Was möchtest du, dass dein Partner öfter tut?" to "คุณอยากให้คู่ของคุณทำอะไรบ่อยขึ้น?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "จะเกิดอะไรขึ้นกับสัตว์เมื่อเราเดินทาง?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "เมื่อลูกของเราโตขึ้นจะเป็นอย่างไร?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "อะไรที่เราไม่ควรมองข้ามในฐานะพ่อแม่?",
    "Was war dein schönster Moment mit mir bisher?" to "ช่วงเวลาที่ดีที่สุดของคุณกับฉันจนถึงตอนนี้คืออะไร?",
    "Was wir gegessen haben" to "สิ่งที่เรากินไป",
    "Was wollt ihr nie vergessen?" to "อะไรที่คุณไม่เคยอยากจะลืม?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "อะไรจะแย่ไปกว่านั้นสำหรับคุณ: ไม่เคยพิซซ่าอีกต่อไปหรือไม่เคยเบอร์เกอร์อีกต่อไป?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "วันๆ คุณอยากทำอะไรด้วยกันมากที่สุด?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "คุณจะเปลี่ยนอะไรทันทีถ้าเงินไม่ใช่ปัญหา?",
    "Weiter" to "ถัดไป",
    "Weiter spielen" to "เล่นต่อ",
    "Weiß ich noch nicht" to "ยังไม่รู้เลย",
    "Weiße Rosen" to "กุหลาบขาว",
    "Weißgold" to "ทองคำขาว",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "ลูกของเราควรจะได้คุณภาพอะไรจากเราอย่างแน่นอน?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "คุณต้องการสร้างสภาพแวดล้อมแบบใดสำหรับข้อเสนอ",
    "Welcher Raum sagt am meisten über dich aus?" to "ห้องไหนที่พูดถึงคุณมากที่สุด?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "เราวางแผนเรื่องอาหารและสัตวแพทย์ไว้เท่าไร?",
    "Welches Lied macht dich an? 🥵" to "เพลงไหนโดนใจคุณ? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "ภาพไหนที่คุณชอบที่สุด?",
    "Wellnessbad" to "อาบน้ำเพื่อสุขภาพ",
    "Wenn es schwierig ist" to "เมื่อมีสิ่งที่ยากลำบาก",
    "Wenn ich müde bin" to "เมื่อฉันเหนื่อย",
    "Wenn wir uns lange umarmen" to "เมื่อเรากอดกันนานๆ",
    "Wenn wir zusammen lachen" to "เมื่อเราหัวเราะด้วยกัน",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "ใครตัดสินใจได้เร็วกว่าจะสั่งอะไร?",
    "Wer findet die besten Restaurants?" to "ใครเจอร้านอาหารเด็ดสุดบ้าง?",
    "Wer gibt mehr Herzlichkeit?" to "ใครให้ความอบอุ่นมากกว่ากัน?",
    "Wer hat den besseren Musikgeschmack?" to "ใครมีรสนิยมทางดนตรีมากกว่ากัน?",
    "Wer hängt mehr an seinen Eltern?" to "ใครผูกพันกับพ่อแม่มากกว่ากัน?",
    "Wer ist besser organisiert?" to "ใครจัดได้ดีกว่ากัน?",
    "Wer ist der Beste bei der Filmauswahl?" to "ใครคือคนเลือกหนังได้เก่งที่สุด?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "ใครเก่งที่สุดในการวางแผนเดตสุดโรแมนติก?",
    "Wer ist der beste Tänzer?" to "ใครคือนักเต้นที่เก่งที่สุด?",
    "Wer ist romantischer?" to "ใครโรแมนติกกว่ากัน?",
    "Wer kocht besser?" to "ใครทำอาหารเก่งกว่ากัน?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "ใครดูแลเรื่องการปรับปรุงและบำรุงรักษา?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "ใครสังเกตได้เร็วกว่าเมื่ออีกคนไม่สบาย?",
    "Wer sucht am Ende wirklich den Film aus?" to "สุดท้ายแล้วใครเลือกหนังเรื่องนี้กันแน่?",
    "Wer vergisst eher einen Jahrestag?" to "ใครมีโอกาสลืมวันครบรอบมากกว่ากัน?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "เช้าวันรุ่งขึ้นใครจะลืมชื่อตัวเองได้มากกว่านี้?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "วันรุ่งขึ้นใครจะเจอวิดีโอที่พวกเขาไม่รู้อะไรมากกว่ากัน?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "ใครอยากจะไปค้างคืนบนโซฟาของคนแปลกหน้าล่ะ?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "ใครจะเผลอหลับไปในงานปาร์ตี้แล้วตื่นมาโดยมี Sharpie อยู่บนใบหน้ามากกว่ากัน?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "ใครจะมีโอกาสลื่นล้มบนแดนซ์ฟลอร์แต่ทำให้ดูเป็นท่าเท่ๆ บ้าง?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "ใครมีแนวโน้มที่จะควบคุมเพลย์ลิสต์ Spotify ในงานปาร์ตี้ที่บ้านมากกว่ากัน?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "ใครจะสั่งพิซซ่าให้ทุกคนในงานปาร์ตี้ไปกินเองมากกว่ากัน?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "ใครมีแนวโน้มจะหลับก่อนในงานปาร์ตี้มากกว่ากัน?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "ใครมีแนวโน้มที่จะเริ่มทำความสะอาดในงานปาร์ตี้กะทันหันมากกว่ากัน?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "ใครจะมีแนวโน้มที่จะอ้างว่าเป็นคนเงียบขรึมมากกว่ากันเมื่อสิ่งที่ตรงกันข้ามเป็นจริง?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "ใครมีแนวโน้มที่จะยอมแพ้ก่อนในการโต้แย้ง?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "ใครมีแนวโน้มที่จะโกงเกมดื่มมากกว่ากัน?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "ใครจะมีโอกาสบุกกินบุฟเฟ่ต์แล้วแอบเอาอาหารกลับบ้านไปมากกว่านี้?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "ใครจะโพสต์ภาพค่ำคืนที่น่าอับอายที่สุดในเรื่องราวของพวกเขาได้มากกว่านี้?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "ใครจะรำคาญดีเจให้ขอเพลงโปรดของตัวเองมากกว่ากัน?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "ใครจะร้องเพลงนอกคีย์ได้มากกว่ากัน แต่ด้วยความมั่นใจ?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "ใครจะสั่งเครื่องดื่มที่แพงที่สุดในเมนูแล้วเสียใจมากกว่ากัน?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "ใครมีแนวโน้มที่จะเชิญเพื่อนบ้านมามากกว่าถ้าพวกเขาบ่นเรื่องเสียงดัง?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "ใครล่ะจะจริงจังกับเกมปาร์ตี้ (อย่างเบียร์ปอง) เกินไป?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "ใครมีแนวโน้มจะผูกมิตรกับฮือฮาเพื่อเข้าถึง VIP ได้มากกว่ากัน?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "ใครจะมีโอกาสได้เริ่มการต่อสู้คาราโอเกะที่เกิดขึ้นเองมากกว่ากัน?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "ใครมีโอกาสเปิดขวดโดยไม่ใช้ที่เปิดขวดมากกว่ากัน?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "ใครจะมีโอกาสพูดมากกว่ากันทั้งๆ ที่ไม่มีใครถามเลย?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "ใครมีแนวโน้มจะใช้เวลาหนึ่งชั่วโมงในห้องน้ำเพื่อเซลฟี่มากกว่ากัน?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "ใครจะกล้าเต้นโชว์น่าอายและเฉลิมฉลองมากกว่ากัน?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "ใครน่าจะโทรหาแฟนเก่าหลังปาร์ตี้จบมากกว่ากัน?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "ใครจะมีโอกาสทำให้แขกแปลกหน้าขุ่นเคืองโดยไม่ตั้งใจมากกว่ากัน?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "ใครจะมีโอกาสแอบออกจากปาร์ตี้โดยไม่บอกลามากกว่ากัน?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "ใครจะเล่นกับสัตว์เลี้ยงของเจ้าบ้านมากกว่าพูดคุยกับแขก?",
    "Wer würde eher spontan eine Reise buchen?" to "ใครจะมีโอกาสจองทริปมากกว่ากัน?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "ใครน่าจะคุยกันแบบเจาะลึกในครัวนานหลายชั่วโมงมากกว่ากัน?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "ใครมีโอกาสเผลอดื่มเครื่องดื่มของคนอื่นมากกว่ากัน?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "ใครจะมีโอกาสไปล้มแจกันราคาแพงหรือสิ่งของที่เปราะบางโดยไม่ได้ตั้งใจ?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "ใครเล่าจะมีแนวโน้มที่จะลองผสมค็อกเทลที่ซับซ้อนด้วยตัวเองแล้วล้มเหลวอย่างน่าสังเวช?",
    "Wer würde eher zu spät kommen?" to "ใครจะสายมากกว่ากัน?",
    "Wer würde eher?" to "ใครจะชอบล่ะ?",
    "Wer übernimmt die tägliche Versorgung?" to "ใครดูแลเรื่องการดูแลประจำวัน?",
    "Werde so akzeptiert, wie du bist" to "เป็นที่ยอมรับในแบบที่เป็นคุณ",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "เราจะมีเวลาให้ลูกเพียงพอหรือไม่? ⏳",
    "Whirlpool" to "อ่างน้ำร้อน",
    "White Chocolate" to "ไวท์ช็อกโกแลต",
    "Widgets" to "วิดเจ็ต",
    "Wie fühlst du dich am meisten geliebt?" to "รู้สึกยังไงบ้างที่ถูกรักมากที่สุด?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "เราจะจัดการกับรายได้ที่แตกต่างกันอย่างไร?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "อะไรคือวิธีที่ดีที่สุดสำหรับคู่ของคุณในการเริ่มมีเซ็กส์กับคุณ?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "คู่ของคุณจะเป็นคู่ที่ดียิ่งขึ้นสำหรับคุณได้อย่างไร?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "คุณอยากจะเฉลิมฉลองร่วมกับคนอื่นๆ หลังจากการขอแต่งงานนานแค่ไหน?",
    "Wie lange wollen wir dort mindestens bleiben?" to "เราอยากจะอยู่ที่นั่นนานแค่ไหน?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "คุณพูดเรื่องความปรารถนาได้ง่ายแค่ไหน?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "คุณอยากให้อนาคตของเราเป็นอย่างไร?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "วันอาทิตย์ที่บ้านของคุณสมบูรณ์แบบเป็นยังไง?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "คุณรู้สึกอย่างไรกับการพูดจาลามกระหว่างมีเซ็กส์?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "เราสามารถจ่ายเครดิตได้เท่าไรตามความเป็นจริง?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "เราอยากจะอยู่ห่างกันนานแค่ไหน?",
    "Wie viel wollen wir insgesamt ausgeben?" to "เราต้องการใช้จ่ายทั้งหมดเท่าไร?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "เมื่อลูกมาแล้ว เราจะหาเวลามาสานสัมพันธ์ได้อย่างไร?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "การจับภาพช่วงเวลานั้นสำคัญกับคุณแค่ไหน?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "การที่ใบสมัครสะท้อนถึงงานอดิเรกหรือความสนใจของคุณมีความสำคัญต่อคุณเพียงใด?",
    "Wie würdest du sie/ihn nennen?" to "คุณจะเรียกเขา/เธอว่าอะไร?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "วิธีไหนที่คุณชอบที่สุดในการแสดงความรักนอกเหนือจากเรื่องเซ็กส์?",
    "Wildblumen" to "ดอกไม้ป่า",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "อยากได้ผู้หญิงหรือผู้ชายล่ะ? .",
    "Wintergarten" to "สวนฤดูหนาว",
    "Winterhochzeit" to "งานแต่งงานหน้าหนาว",
    "Wir bestellen einfach beides" to "เราเพิ่งสั่งทั้งสองอย่าง",
    "Wir brauchen ewig" to "มันจะพาเราไปตลอดกาล",
    "Wir einigen uns nie" to "เราไม่เคยตกลงกัน",
    "Wir entscheiden es gemeinsam" to "เราตัดสินใจร่วมกัน",
    "Wir treffen uns in der Mitte" to "เราพบกันกลางทาง",
    "Wir wechseln uns ab" to "เราผลัดกัน",
    "Wird stressig" to "เริ่มเครียด",
    "Wobei lachst du am meisten?" to "อะไรทำให้คุณหัวเราะได้มากที่สุด?",
    "Wofür sparen wir gemeinsam?" to "เราจะออมเงินเพื่ออะไรด้วยกัน?",
    "Wohnzimmer" to "ห้องนั่งเล่น",
    "Woran erinnerst du dich am lebhaftesten?" to "จำอะไรได้ชัดเจนที่สุด?",
    "Worauf freust du dich bei uns am meisten?" to "คุณตั้งตารออะไรกับเรามากที่สุด?",
    "Worte/Komplimente" to "คำพูด/คำชมเชย",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "อะไรที่คุณกลัวที่สุดในความสัมพันธ์ของเรา?",
    "Wünsche? z.B. günstig, draußen" to "ความปรารถนาเหรอ? เช่น ราคาถูกข้างนอก",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "คุณอยากจะขอแต่งงานในช่วงวันหยุด (เกี่ยวกับการท่องเที่ยว) ไหม?",
    "Xbox" to "Xbox",
    "YouTube Music" to "ยูทูปมิวสิค",
    "Zeichne für mich" to "วาดรูปให้หน่อยสิ",
    "Zeichne mich als Tier — welches wäre ich?" to "วาดฉันเป็นสัตว์ - ฉันจะเป็นตัวอะไร?",
    "Zeichne unser Gefühl zueinander als Symbol." to "ดึงความรู้สึกของเราเข้าหากันเป็นสัญลักษณ์",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "วาดบ้านในฝันของเราเป็นเส้นเดียว อะไรคือสิ่งที่โดดเด่นที่สุด?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "วาดเดตแรกของเรา - ในภาพต้องมีอะไรแน่นอน?",
    "Zeichnen" to "วาด",
    "Zeit füreinander" to "ถึงเวลาของกันและกัน",
    "Zeit, wenn das Baby schläft" to "เวลาที่ลูกน้อยนอนหลับ",
    "Zelten gehen" to "ไปแคมป์ปิ้งกัน",
    "Zitrone" to "เลมอน",
    "Zu Hause, gemütlich und privat" to "อยู่บ้านแสนสบายและเป็นส่วนตัว",
    "Zu einem Picknick gehen" to "ไปปิกนิก",
    "Zu einem ausgefallenen Abendessen gehen" to "ไปดินเนอร์สุดหรู",
    "Zu zweit reisen" to "เที่ยวกันเป็นคู่",
    "Zuhause & Alltag" to "บ้านและชีวิตประจำวัน",
    "Zuhören" to "ฟังนะ",
    "Zurück" to "กลับ",
    "Zusammen seit" to "ร่วมกันตั้งแต่",
    "Zusammen seit (TT.MM.JJJJ)" to "กันตั้งแต่ (DD.MM.YYYY)",
    "Zusammenziehen" to "สัญญา",
    "Zustimmen oder Ablehnen" to "เห็นด้วยหรือไม่เห็นด้วย",
    "Zwei Kreise, die sich überschneiden" to "วงกลมสองวงที่ทับซ้อนกัน",
    "Zwei Stühle davor" to "มีเก้าอี้สองตัวอยู่ข้างหน้า",
    "Zärtlich sein" to "จงอ่อนโยน",
    "Öfter als ich zugebe" to "หลายครั้งเกินกว่าจะยอมรับ",
    "Über 100€/Monat" to "มากกว่า 100€/เดือน",
    "Über 2000 im Monat" to "มากกว่า 2,000 ต่อเดือน",
    "Über mich selbst" to "เกี่ยวกับตัวฉัน",
    "Übernehmen" to "ใช้",
    "Überraschend" to "น่าประหลาดใจ",
    "Überraschung" to "เซอร์ไพรส์",
    "Überspringen" to "ข้าม",
    "Übertrieben und großartig" to "เหนือชั้นและสุดยอดมาก",
    "✎ Tippe, um zu antworten" to "✎ แตะเพื่อตอบกลับ",
    "✨ GFK-Brücke" to "✨ สะพาน GRP",
)

internal fun localizeThaiDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_THAI_CONTENT)
