package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_TURKISH_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 yıl",
    "1000 - 1500 im Monat" to "Ayda 1000 - 1500",
    "1000 bis 3000" to "1000 - 3000",
    "1500 - 2000 im Monat" to "Ayda 1500 - 2000",
    "3000 bis 5000" to "3000 - 5000",
    "5-10 Jahre" to "5-10 yıl",
    "50-100€/Monat" to "50-100€/ay",
    "Ab 100€" to "100€'dan başlayan fiyatlarla",
    "Ab 500€" to "500€'dan başlayan fiyatlarla",
    "Ab 50€" to "50€'dan başlayan fiyatlarla",
    "Ab und zu" to "Ara sıra",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Bir satın alma işlemi yapmadan önce ne kadar harcamamız gerekiyor?",
    "Abbrechen" to "İptal",
    "Abenteuer" to "Macera",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Faaliyetler",
    "Alle" to "Hepsi",
    "Alle Pakete" to "Tüm paketler",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "En iyi arkadaşınız dışında tüm arkadaşlarınızı kaybedin",
    "Alle intimen Momente selbst initiieren" to "Tüm samimi anları kendiniz başlatın",
    "Alles davon" to "Hepsi",
    "Alles, was noch kommt" to "Gelecek her şey",
    "Alltagsroutine" to "Günlük rutin",
    "Alltägliche Berührungen" to "Günlük dokunuşlar",
    "Altbau mit Charme" to "Cazibeli eski bina",
    "Am Strand" to "Sahilde",
    "Am liebsten alles zusammen" to "Tercihen her şey bir arada",
    "Am selben Tag mit Freunden/Familie" to "Arkadaşlarınızla/ailenizle aynı gün",
    "Amazon" to "Amazon",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Hollanda",
    "An das Gefühl" to "Duygudan",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "Çok sayıda seyircinin olduğu halka açık bir yerde",
    "An einen Geruch" to "Bir koku",
    "An einen Song" to "Bir şarkıya",
    "An etwas, das ich gesagt habe" to "Söylediğim bir şey",
    "Analyse starten" to "Analizi başlat",
    "Analysiere eure Muster..." to "Kalıplarınızı analiz edin...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Cevaplarınızı ve sohbetlerinizi Gottman ve GFK'ye göre analiz edin.",
    "Ananas auf der Pizza schmeckt köstlich." to "Pizzanın üzerindeki ananasın tadı çok lezzetli.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Fotoğrafla yanıtla",
    "Antwortähnlichkeit" to "Cevap benzerliği",
    "App-Sprache auswählen" to "Uygulama dilini seçin",
    "Auf eine Bootsparty gehen" to "Bir tekne partisine gitmek",
    "Aufmerksamkeit" to "Dikkat",
    "Aufräumen und Projekte angehen" to "Projeleri temizleyin ve ele alın",
    "Aufwärmen" to "Isınma",
    "Aufwärmen: Einander kennenlernen" to "Isınma: Birbirimizi tanıma",
    "Aus dem Urlaub" to "Tatilden",
    "Ausgefallener Name" to "Süslü isim",
    "Ausschlafen und faulenzen" to "Uyu ve tembellik yap",
    "Ausschlafen und nichts tun" to "Uyu ve hiçbir şey yapma",
    "Aussehen" to "Görünüm",
    "Auto" to "Otomatik",
    "Außenkamin" to "Dış mekan şöminesi",
    "BEANTWORTE" to "CEVAP",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Endonezya",
    "Banane" to "Muz",
    "Beantwortet" to "Yanıtlandı",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Soruları aynı anda yanıtlayın; ikiniz de bitirene kadar yanıtlar görünmeyecek.",
    "Beantwortete Fragen" to "Soruları yanıtladı",
    "Bearbeiten" to "Düzenle",
    "Bei Insider-Witzen" to "İçeriden şakalar için",
    "Bei Memes" to "Memler hakkında",
    "Bei einer spontanen Berührung" to "Kendiliğinden dokunulduğunda",
    "Beide" to "İkisi de",
    "Beide gleich" to "İkisi de aynı",
    "Beide zusammen" to "İkisi bir arada",
    "Beide, aber wir tun so als ob nicht" to "Her ikisi de, ama biz yokmuş gibi davranıyoruz",
    "Beides" to "İkisi de",
    "Beides wäre schlimm" to "Her ikisi de kötü olurdu",
    "Beim Einschlafen nebeneinander" to "Yan yana uykuya dalmak",
    "Beim Reden" to "Konuşurken",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Ünlü turistik yerler her zaman hayal kırıklığı yaratır.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Seks hayatımızı bir emojiyle anlatın.",
    "Besser kommunizieren" to "Daha iyi iletişim kurun",
    "Bessere Lage" to "Daha iyi konum",
    "Bestellen" to "Sipariş",
    "Besuchte Länder" to "Ziyaret edilen ülkeler",
    "Besuchte Städte" to "Ziyaret edilen şehirler",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Abartılı bir teklifi mi yoksa incelikli bir teklifi mi tercih edersiniz?",
    "Beziehung" to "İlişki",
    "Bibliothek" to "Kütüphane",
    "Bin manchmal unsicher" to "Bazen güvensiz oluyorum",
    "Bist du ein Videospiel-Guru?" to "Bir video oyunu gurusu musunuz?",
    "Blumenwiese" to "Çiçek çayırı",
    "Bunte Blumenwiese" to "Renkli çiçek çayırı",
    "Burger" to "Burgerler",
    "Burger King" to "Burger King",
    "Chat" to "Sohbet",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Kurabiye Hamuru",
    "Dachgarten mit Lounge" to "Salonlu çatı bahçesi",
    "Dachterrasse" to "Çatı terası",
    "Das Wetter an dem Tag" to "O günün hava durumu",
    "Das erste Selfie" to "İlk selfie",
    "Das meiste weiß ich" to "Çoğunu biliyorum",
    "Das oder das?" to "Bu mu, bu mu?",
    "Das tägliche Leben" to "Günlük yaşam",
    "Dass Zusagen gehalten werden" to "Verilen sözler tutuluyor",
    "Dass alles meinen Stil hat" to "Her şeyin benim tarzım olduğunu",
    "Dass ich alles erzählen kann" to "Her şeyi anlatabildiğimi",
    "Dass ich mich nicht sorgen muss" to "Endişelenmeme gerek yok",
    "Dass wir ungestört sind" to "Rahatsız edilmediğimizi",
    "Dein Name" to "Adınız",
    "Deine Antwort..." to "Cevabınız...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Yanıtlarınız kaydedildi. İş Ortağı paketi bitirir bitirmez her iki yanıt da birlikte görünecektir.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Yanıtlarınız kaydedildi. \${profile.partnerName} paketi tamamladıktan sonra her iki yanıt da birlikte görünecektir.",
    "Deine Beziehung abenteuerlich und spontan machen" to "İlişkinizi macera dolu ve spontane hale getirin",
    "Deine Beziehung stabil und sicher machen" to "İlişkinizi istikrarlı ve güvenli hale getirin",
    "Deine eigene Antwort" to "Kendi cevabınız",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "En derin sırlarınızı partnerinizle paylaşmak daha iyidir",
    "Deinen besten Freund verlieren" to "En iyi arkadaşını kaybetmek",
    "Denke an dich" to "Kendinizi düşünün",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Aynı filmi iki kez izlemek zaman kaybıdır.",
    "Der Blick nach draußen" to "Dışarıdaki manzara",
    "Der Garten" to "Bahçe",
    "Der Ort" to "Yer",
    "Der Ring und die Geste" to "Yüzük ve jest",
    "Der perfekte Heiratsantrag" to "Mükemmel evlilik teklifi",
    "Derjenige sein, der umarmt wird" to "Sarılan kişi olun",
    "Deutsch" to "Almanca",
    "Diamant" to "Elmas",
    "Diamanten im Band" to "Gruptaki elmaslar",
    "Die Distanz" to "Mesafe",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Tatilinizi eşinizin ailesiyle geçirin",
    "Die Gemütlichkeit und Ruhe" to "Konfor ve huzur",
    "Die Menschen, die darin wohnen" to "İçinde yaşayan insanlar",
    "Die Umgebung und Atmosphäre" to "Çevre ve atmosfer",
    "Die Worte und Emotionen" to "Kelimeler ve duygular",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "En üst düzey eğlence bilgi yarışması",
    "Diejenige sein, die umarmt" to "Sarılan kişi olun",
    "Direkt ansprechen" to "Doğrudan adres",
    "Diskussion" to "Tartışma",
    "Diskutiere vor dem Kinderkriegen" to "Çocuk sahibi olmadan önce tartışın",
    "Diskutiert eure Antworten" to "Cevaplarınızı tartışın",
    "Disney" to "Disney",
    "Doch, schon mal" to "Evet, evet",
    "Draußen mit der Natur als Kulisse" to "Arka planda doğayla birlikte dışarıda",
    "Drei-Stein-Ring" to "Üç taşlı yüzük",
    "Du bist dran" to "Sıra sizde",
    "Du fehlst mir" to "Seni özledim",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubai, BAE",
    "Dunkles Design" to "Koyu tema",
    "Durch Berührung" to "Dokunarak",
    "Durch Worte" to "Kelimeler aracılığıyla",
    "Durch Zeit zu zweit" to "Zaman geçtikçe birlikte",
    "Durch kleine Gesten" to "Küçük hareketlerle",
    "Durchgeplant" to "İyi planlanmış",
    "ERGEBNISSE" to "SONUÇLAR",
    "Egal, Hauptsache gesund" to "Her neyse, asıl önemli olan sağlıklı",
    "Ehepaar Leben" to "Evli çiftin hayatı",
    "Eher knapp" to "Oldukça yakın",
    "Eher nicht" to "Pek değil",
    "Eher schwer" to "Oldukça zor",
    "Eher schwierig" to "Oldukça zor",
    "Eher zu" to "Daha çok benzer",
    "Eifersucht ist ein Zeichen von Liebe." to "Kıskançlık sevginin bir işaretidir.",
    "Eigenes Gemüsebeet" to "Kendi sebze bahçesi",
    "Ein Abenteuer in einer neuen Stadt" to "Yeni bir şehirde bir macera",
    "Ein Anker" to "Bir sunucu",
    "Ein Balkon oder Garten" to "Bir balkon veya bahçe",
    "Ein Filmabend" to "Bir film gecesi",
    "Ein Harmony-Meilenstein eurer Liebe." to "Aşkınızın uyumunun bir dönüm noktası.",
    "Ein Herz" to "Bir kalp",
    "Ein Herz an der Tür" to "Kapıda bir kalp",
    "Ein Jahr lang eine Fernbeziehung führen" to "Bir yıldır uzak mesafe ilişkisi var",
    "Ein Kindheitsessen" to "Çocukluk yemeği",
    "Ein Live-Musik-Konzert besuchen" to "Canlı müzik konserine katılın",
    "Ein Museum besuchen" to "Bir müzeyi ziyaret edin",
    "Ein Spieleabend" to "Bir oyun gecesi",
    "Ein Spieleabend mit Freunden" to "Arkadaşlarla bir oyun gecesi",
    "Ein Urlaubsfoto" to "Bir tatil fotoğrafı",
    "Ein aktives Abenteuer" to "Aktif bir macera",
    "Ein entspannender Spa-Tag" to "Rahatlatıcı bir spa günü",
    "Ein ganz normaler Alltagstag" to "Tamamen normal bir günlük gün",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Fırtına sırasında evde rahat bir akşam",
    "Ein gemütliches Date drinnen" to "İç mekanda rahat bir randevu",
    "Ein lustiges Bild" to "Komik bir resim",
    "Ein paar Handyfotos reichen" to "Birkaç cep telefonu fotoğrafı yeterli",
    "Ein paar Stunden" to "Birkaç saat",
    "Ein paar kulturelle Anklänge sind okay" to "Birkaç kültürel referansta sorun yok",
    "Ein romantischer Abend" to "Romantik bir akşam",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Mum ışığında romantik bir akşam yemeği",
    "Ein romantisches Bild" to "Romantik bir görüntü",
    "Ein romantisches Picknick an einem schönen Ort" to "Güzel bir yerde romantik bir piknik",
    "Ein schwerer Moment, den wir geschafft haben" to "Başardığımız zor bir an",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Ay ışığı altında açık havada harika bir randevu",
    "Ein ungewöhnliches Gericht" to "Alışılmadık bir yemek",
    "Ein zufälliger Schnappschuss" to "Rastgele bir anlık görüntü",
    "Einander kennenlernen" to "Birbirimizi tanımak",
    "Eine Autoreise" to "Bir yolculuk",
    "Eine Brücke" to "Bir köprü",
    "Eine Date-Nacht unter den Sternen" to "Yıldızların altında bir randevu gecesi",
    "Eine Million Dollar gewinnen" to "Bir milyon dolar kazanın",
    "Eine Million Dollar verdienen" to "Bir milyon dolar kazanın",
    "Eine Nacht in einem Club" to "Kulüpte bir gece",
    "Eine Schokoladenverkostung" to "Çikolata tadımı",
    "Eine Wanderung mit Panoramablick machen" to "Panoramik manzaralı yürüyüşe çıkın",
    "Eine Weinverkostung" to "Şarap tadımı",
    "Eine gemeinsame Reise" to "Birlikte bir yolculuk",
    "Eine gemütliche Nacht zu Hause" to "Evde rahat bir gece",
    "Eine neue Sprache zu lernen ist einfach." to "Yeni bir dil öğrenmek kolaydır.",
    "Einen Film anschauen" to "Film izleyin",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Bir aydır birbirimizle hiç konuşmuyoruz",
    "Einen Tanzkurs besuchen" to "Dans dersi alın",
    "Einen Vergnügungspark erkunden" to "Bir eğlence parkını keşfedin",
    "Einen Wellness-Tag" to "Sağlıklı bir gün",
    "Einen sehr emotionalen Partner haben" to "Çok duygusal bir partnere sahip olmak",
    "Einen sehr logischen Partner haben" to "Çok mantıklı bir ortağa sahip olmak",
    "Einer zahlt alles" to "Bir kişi her şeyi öder",
    "Einfach mehr Alltag" to "Daha fazla günlük yaşam",
    "Einfach nebeneinander sein" to "Sadece yan yana olun",
    "Einfach und intim" to "Basit ve samimi",
    "Einige Dinge für dich behalten" to "Bazı şeyleri kendinize saklayın",
    "Einmal" to "Bir kez",
    "Eins, das nur wir kennen" to "Yalnızca bizim bildiğimiz",
    "Englisch" to "İngilizce",
    "Entspannte Hängematte" to "Rahat hamak",
    "Entspannung" to "Gevşeme",
    "Erdbeere" to "Çilek",
    "Erfolgreich" to "Başarılı",
    "Ergebnisse" to "Sonuçlar",
    "Erst bei sehr großen Summen" to "Yalnızca çok büyük meblağlar için",
    "Erst nur enge Freunde/Familie" to "İlk başta yalnızca yakın arkadaşlar/aile",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Partnerimin mesajlara yanıt vermesinin çok uzun sürmesi beni rahatsız ediyor.",
    "Essen & Genuss" to "Yemek ve eğlence",
    "Essensvorlieben" to "Yemek tercihleri",
    "Etwa eine Woche später, erst mal nur wir" to "Yaklaşık bir hafta sonra, ilk başta sadece biz",
    "Etwas Neues ausprobieren" to "Yeni bir şey deneyin",
    "Etwas ganz anderes" to "Tamamen farklı bir şey",
    "Etwas sehr Scharfes" to "Çok keskin bir şey",
    "Etwas, das ich selbst gern erfinde" to "Kendim icat etmekten hoşlandığım bir şey",
    "Etwas, eine kleine Note wäre schön" to "Bir şey, küçük bir not güzel olurdu",
    "Familie" to "Aile",
    "Familie/Freunde" to "Aile/Arkadaşlar",
    "Familienmensch" to "Aile babası",
    "Farbedelstein" to "Renkli değerli taş",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "TV reklamlarını izlemek bazen ilgi çekicidir.",
    "Fertig" to "Bitti",
    "Fertig!" to "Bitti!",
    "Feste Date-Nights" to "Sabit tarih geceleri",
    "Feuerstelle" to "Ateş çukuru",
    "Filigran & schlicht" to "Telkari ve sade",
    "Filme/Serien" to "Filmler/dizi",
    "Formuliere um..." to "Yeniden ifade et...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Taslağınızı şiddet içermeyen bir şekilde yeniden ifade edin: gözlem, duygu, ihtiyaç, istek.",
    "Frage hinzufügen" to "Soru ekle",
    "Fragen & Spiele" to "Sorular ve Oyunlar",
    "Fragen für jede Gelegenheit" to "Her duruma uygun sorular",
    "Freizeitpark" to "Eğlence parkı",
    "Freunde treffen" to "Arkadaşlarla tanışın",
    "Freundschaften mit Ex-Partnern sind okay." to "Eski sevgililerle arkadaşlıklar sorun değil.",
    "Früh aufstehen" to "Erken kalk",
    "Fußbodenheizung" to "Yerden ısıtma",
    "Führen wir getrennte oder gemeinsame Konten?" to "Ayrı veya ortak hesaplarımız var mı?",
    "Für dich empfohlen" to "Sizin için önerildi",
    "Für die Zukunft" to "Gelecek için",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Bu aramada eşleşen soru veya oyun bulunamadı.",
    "Für immer" to "Sonsuza kadar",
    "Fürsorglichkeit" to "Şefkatli",
    "GFK-Brücke" to "GRP köprüsü",
    "Galerie" to "Galeri",
    "Gar nicht, der Moment gehört uns" to "Hiç de değil, an bizim",
    "Gar nichts tun" to "Hiçbir şey yapma",
    "Geduld" to "Sabır",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Güneşin doğuşunu görmek için sabah erkenden gidin",
    "Geht so" to "Şöyle gider",
    "Geister existieren wirklich." to "Hayaletler gerçekten var.",
    "Gelassenheit" to "Huzur",
    "Gelbgold" to "Sarı altın",
    "Geld & Finanzen" to "Para ve Finans",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Birlikte dünyayı dolaşın, yeni kültürleri ve mutfakları keşfedin",
    "Gemeinsam ein Lego bauen" to "Birlikte bir Lego yapın",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Mutfakta birlikte yeni bir tarif deneyin",
    "Gemeinsame Konten" to "Paylaşılan hesaplar",
    "Gemeinsame Nächte" to "Birlikte geceler",
    "Gemeinsame Tage" to "Birlikte geçirdiğimiz günler",
    "Gemischt" to "Karışık",
    "Gemüsebeet" to "Sebze bahçesi",
    "Gemütliche Feuerstelle" to "Rahat şömine",
    "Gesprächsanreger" to "Konuşmayı başlatan",
    "Getrennte Konten" to "Ayrı hesaplar",
    "Getrennte Urlaube tun einer Beziehung gut." to "Ayrı tatiller bir ilişki için iyidir.",
    "Gewächshaus" to "Sera",
    "Glasfassade" to "Cam cephe",
    "Gleichgültigkeit" to "Kayıtsızlık",
    "Glücklich und frei" to "Mutlu ve özgür",
    "Gourmet Eis-Sorten" to "Gurme dondurma çeşitleri",
    "Gravur innen" to "İç kısımdaki gravür",
    "Grillplatz" to "Barbekü alanı",
    "Groß & üppig" to "Büyük ve gösterişli",
    "Große Familie" to "Büyük aile",
    "Große Feier" to "Büyük kutlama",
    "Große Fenster" to "Büyük pencereler",
    "Große Fensterfront" to "Büyük pencere önü",
    "Großer Außenpool" to "Büyük açık havuz",
    "Großer Garten" to "Büyük bahçe",
    "Großer Stein" to "Büyük taş",
    "Größere Küche" to "Daha büyük mutfak",
    "Gutes Essen" to "İyi yemek",
    "Habe ich" to "Yaptım",
    "Habe ich noch nie" to "Hiç sahip olmadım",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Herhangi bir şaşırtıcı farklılık keşfettiniz mi? Neden belirli seçenekleri daha çok beğendiğinizi konuşun!",
    "Haus am See" to "Göl kenarındaki ev",
    "Haus/Wohnung" to "Ev/apartman dairesi",
    "Hazelnut" to "Fındık",
    "Heimkino" to "Ev sineması",
    "Herzhaft" to "Samimi",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Şu anda burada hiçbir şey yok.\nFiltreyi değiştirin veya farklı bir konu seçin.",
    "Hilfe im Alltag" to "Günlük yaşamda yardım",
    "Himbeere" to "Ahududu",
    "Hinzufügen" to "Ekle",
    "Hobbys" to "Hobiler",
    "Hochzeitssträuße" to "Düğün buketleri",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Hogwarts Binasının Gururu: Nereye Aitsiniz?",
    "Home" to "Ana Sayfa",
    "Hot Tub" to "Jakuzi",
    "Humor" to "Mizah",
    "Hund" to "Köpek",
    "Hängematte" to "Hamak",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Teklifin bir parçası olarak yazılı bir mektup ister misiniz?",
    "IKEA" to "IKEA",
    "Ich" to "ben",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Sinemaya gitmektense parkta romantik yürüyüşleri tercih ederim.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Sinemada hiç uyumadım.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Partnerimle yeni hobiler veya aktiviteler keşfetmekten keyif alıyorum.",
    "Ich finde eine Alternative" to "Bir alternatif bulacağım",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Her zaman aynı yerlere gitmek yerine partnerimle yeni restoranlar denemekten keyif alıyorum.",
    "Ich habe noch nie" to "Hiç",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Hız treninden hiç korkmadım ve yine de ona bindim.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Sabırsız olduğum için hiç Fast Pass bileti almadım.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Evde kalıp TV programı izleme planlarımı hiçbir zaman iptal etmedim.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Hogwarts'tan gelen mektubumu hiç beklemedim.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Slytherin'in o kadar da kötü olmadığını hiçbir zaman söylemedim.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Hiçbir zaman Disney filmleri için çok yaşlı olduğumu söylemedim (ve gizlice onlardan keyif aldım).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Mario Kart'ta asla mavi tanklı birini kasıtlı olarak vurmadım.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Hiçbir Disney filminde ağlamadım.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Korku filmi izlerken hiçbir zaman gözlerimi kapatmadım.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Hiçbir zaman bir oyunu kaydetmeyi unutup saatler süren ilerlemeyi kaybetmedim.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Utanç verici bir sahne sırasında odadan hiç ayrılmadım (utanç verici faktör).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Hız treni fotoğrafı çekerken hiç komik bir poz vermedim.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Hiç gece geç saatlere kadar oyun oynamadım ve ertesi gün ne kadar yorgun olduğuma pişman olmadım.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Bekleyemediğim için hiçbir filmin sonunu Google'da aramadım.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Hiçbir zaman kendimi bir film setindeymiş gibi hissetmedim.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "En sevdiğim dizinin girişini hiç atlamadım.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Hiçbir zaman başka kimsenin Netflix şifresini paylaşmadım.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Çalışırken veya ders çalışırken hiç oyunun müziğini dinlemedim.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Kaybettiğimde asla kontrol cihazını suçlamadım.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Klavyeyi veya kumandayı hiçbir zaman öfkeyle atmadım.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Birkaç gündür çamaşır makinesindeki ıslak kıyafetleri hiç unutmadım.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Bir oyunda kozmetik öğelere hiçbir zaman gerçek para harcamadım.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Yabancı bir ülkede hiç araba kullanmadım.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Hiçbir zaman duşta bir Disney şarkısını yüksek sesle söylemedim.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Hiç elektrikli araba kullanmadım.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Hiç bir park maskotuyla fotoğraf çekmedim.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Hiçbir zaman bir evcil hayvana bir Hogwarts karakterinin adını vermedim.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Hiçbir zaman sinema salonunda patlamış mısır düşürüp yine de yemedim.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Günlük yaşamda Star Wars'tan Usta Yoda'dan bir alıntı hiç kullanmadım.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Hiçbir zaman bir tema parkından aşırı pahalı bir hediyelik eşya satın almadım.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Hiçbir zaman diğer kişinin berbat bulduğu bir film tavsiyesi vermedim.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Hiç gece yarısı bir Oscar törenini canlı izlemedim.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Geçen sezon çok kötü olduğu için hiçbir diziyi iptal etmedim.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Hiçbir zaman bir dizinin tüm sezonunu bir günde art arda izlemedim.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Hiçbir zaman bir patronu ilk denemede yenmedim ve kendimi bir tanrı gibi hissettim.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Hiçbir zaman kahramandan daha havalı bir kötü adam bulamadım.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Kendi oyuncaklarımda hiçbir Oyuncak Hikayesi karakterini tanımadım.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Hiçbir zaman bir RPG'de tam olarak kendime benzeyen bir karakter yaratmadım.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Tema parkında hiç churro yemedim.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Hiç bir Disney filmini arka arkaya üç kez izlemedim.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Bir hafta boyunca hiç akılda kalıcı bir Disney melodisi duymadım.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Hiçbir filmi sırf belli bir oyuncu yüzünden izlemedim.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Hiç bir film müziğini saatlerce tekrar tekrar dinlemedim.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Hiçbir zaman bir film spoiler'ı açıklamadım ve hemen pişman oldum.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Hiçbir zaman başka bir anadil konuşan bir arkadaş bulamadım.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Hiç başka bir ülkeye taşınan bir arkadaşım olmadı.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Noel'de hiç Harry Potter film maratonuna katılmadım.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Sırf jenerik sonrası sahne yüzünden hiçbir Marvel filmini sonuna kadar izlemedim.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Hiçbir zaman bir NPC'yi (Oyuncu Olmayan Karakter) kasıtlı olarak rahatsız etmedim.",
    "Ich habe noch nie einen Nachtzug genommen." to "Hiç gece trenine binmedim.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Hogwarts'taki evimi öğrenmek için hiçbir zaman çevrimiçi bir teste girmedim.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Hiçbir sosyal medya gönderisini yeterince beğeni almadığı için silmedim.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Tema parkındaki bir günü hiçbir zaman yılın en iyi günü olarak adlandırmadım.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Hiç bir tema parkını ziyaret etmedim ve sabahtan akşama kadar orada kaldım.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Hiçbir zaman bir Transformers veya Marvel yolculuğunu tamamen büyülenmiş halde bırakmadım.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Hiçbir zaman öfkelenip oyunu bırakmadım.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Harry Potter'ın büyük ciltlerinden hiçbirini okumadım.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Hiçbir dizide en sevdiğim karakterden övgüyle bahsetmedim.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Quidditch oynamayı hiç hayal etmedim.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Zor bir seviyenin nasıl çözüleceğini asla gizlice Google'da aramadım.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Hiçbir zaman evcil hayvanımın Disney'deki gibi konuşabileceğini gizlice ummadım.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Sims'te havuz liderini hiçbir zaman kaldırmadım.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "3D simülatör sürüşünde yönümü hiç kaybetmedim.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Hiç bir üniversitenin spor takımında oynamadım.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Tek bir eğlence için hiçbir zaman iki saatten fazla sırada beklemedim.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Su yolculuğunda değerli eşyalarımı hiç ıslatmadım.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Bir arkadaşımla hangi evin en iyi olduğu konusunda hiç tartışmadım.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Hiçbir zaman Elsa gibi sihirli güçlere sahip olduğumu iddia etmedim.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Hiçbir filmde önemli bir sahneyi kaçıracak kadar gülmemiştim.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Hiç bu kadar adrenalin hissetmemiştim ki, hemen tekrar binmek istedim.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Pamuk Prenses gibi hayvanlarla şarkı söylemeyi hiç denemedim.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Hiçbir zaman Disneyland'a bir gezi hayal etmedim.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Jurassic Park'ta su yolculuğuna çıkmayı hiç hayal etmedim.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Hiçbir oyunda bir atlama korkusu karşısında yüksek sesle çığlık atmadım.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Hiçbir TV şovunun finalinde ağlamadım.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Ben hiçbir zaman... evde kalmak için bir randevuyu iptal etmedim.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Hiçbir zaman... bir mesajı 10 kez yeniden yazmadım.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Ben hiçbir zaman... ortağımın cep telefonuna gizlice bakmadım.",
    "Ich habe noch nie!" to "Hiç yapmadım!",
    "Ich habe!" to "Yaptım!",
    "Ich lache viel mit meinem Partner." to "Partnerimle çok gülüyorum.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Partnerimin hobilerini ve ilgi alanlarını tanımayı severim.",
    "Ich liebe es" to "Onu seviyorum",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Partnerimle ikimizin de daha önce izlemediği filmleri izlemeyi seviyorum.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "En sevdiğim müziği partnerimle paylaşmayı seviyorum.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Hiçbir zaman aktarmalı bir uçuşa yetişmek için koşmam gerekmedi.",
    "Ich plane gerne Dates mit meinem Partner." to "Partnerimle randevu planlamayı seviyorum.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Meşgul olduğumda bile partnerimle vakit geçirmeye öncelik veriyorum.",
    "Ich schreibe meinem Partner jeden Tag." to "Partnerime her gün mesaj atıyorum.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Partnerimle memleri ve şakaları paylaşmayı seviyorum.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Günümün tüm ayrıntılarını partnerimle paylaşmayı seviyorum.",
    "Ich würde es nie tun" to "Bunu asla yapmam",
    "Ich übe noch" to "Hala pratik yapıyorum",
    "Ideen generieren" to "Fikir üretin",
    "Im Haushalt helfen" to "Ev işlerinde yardım",
    "In Chat einfügen" to "Sohbete ekle",
    "In Stille nebeneinander" to "Sessizce yan yana",
    "In den Bergen" to "Dağlarda",
    "In eine Bar gehen" to "Bir bara gidin",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Gün batımını izlemek için sahil barına gitmek",
    "In einem feinen Restaurant essen gehen" to "Güzel bir restoranda yemek yemek",
    "In einen Coffeeshop gehen" to "Bir kafeye git",
    "In einer Beziehung sollte man alles voneinander wissen." to "Bir ilişkide birbiriniz hakkında her şeyi bilmelisiniz.",
    "Infinity-Pool" to "Sonsuzluk havuzu",
    "Innenpool" to "Kapalı havuz",
    "Intelligenz" to "Zeka",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Yalnızca partnerinizin başlattığı samimi anlar yaşamak",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Davet kodu: HRM-8731 · her şeyin kilidi açıldı",
    "Island" to "İzlanda",
    "Ist okay für mich" to "Benim için sorun değil",
    "Ist schon perfekt" to "Mükemmel",
    "Ja, Traditionen einbinden" to "Evet, gelenekleri birleştirin",
    "Ja, absolut" to "Evet, kesinlikle",
    "Ja, etwas zum Lesen und Aufbewahren" to "Evet, okunacak ve saklanacak bir şey",
    "Ja, genug" to "Evet, yeterli",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Evet, heyecan verici bir şehirde veya turistik mekanda",
    "Ja, in- und auswendig" to "Evet, içte ve dışta",
    "Ja, komplett überraschend" to "Evet, tamamen şaşırtıcı",
    "Ja, perfekt" to "Evet, mükemmel",
    "Ja, sie gehören zur Familie!" to "Evet, onlar bir aile!",
    "Ja, sofort teilen" to "Evet, hemen paylaşın",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Evet, aile zamanının öncelikli olmasını sağlayacağız.",
    "Jacuzzi" to "Jakuzi",
    "Jahr zusammen 🎉" to "yıl boyunca birlikte 🎉",
    "Jahre zusammen 🎉" to "Birlikte yıllar 🎉",
    "Jeder zahlt 50%" to "Herkes %50 öder",
    "Junge" to "Oğlan",
    "Kamin" to "Şömine",
    "Karriere & Erfolg" to "Kariyer ve Başarı",
    "Kategorien" to "Kategoriler",
    "Katze" to "Kedi",
    "Keine Musik" to "Müzik yok",
    "Keine Party nötig, privat halten" to "Partiye gerek yok, gizli tutun",
    "Keine Privatsphäre" to "Gizlilik yok",
    "Keine Treffer gefunden" to "Eşleşme bulunamadı",
    "Keiner" to "Hiçbiri",
    "Keiner von uns" to "Hiçbirimiz",
    "Kennst du die Essensvorlieben deines Partners?" to "Partnerinizin yemek tercihlerini biliyor musunuz?",
    "Kino" to "Sinema",
    "Kirchlich" to "Dini",
    "Klassisch Solitär" to "Klasik solitaire",
    "Klassisch gebunden" to "Klasik olarak bağlı",
    "Klein & zart" to "Küçük ve narin",
    "Kleine Geschenke" to "Küçük hediyeler",
    "Kleine Runde" to "Küçük grup",
    "Kochen und Freunde einladen" to "Yemek pişirme ve arkadaşları davet etme",
    "Kochkurs" to "Yemek pişirme dersi",
    "Kommt auf den Tag an" to "Güne bağlıdır",
    "Kommt darauf an" to "Duruma göre değişir",
    "Kommt drauf an" to "Duruma göre değişir",
    "Kommt mit" to "Benimle gel",
    "Konzert" to "Konser",
    "Kräftige Farben" to "Güçlü renkler",
    "Kräuterbeet" to "Bitki yatağı",
    "Kultur & Sehenswürdigkeiten" to "Kültür ve Görülecek Yerler",
    "Kuscheln" to "Sarılma",
    "Kuss senden" to "Bir öpücük gönder",
    "Körperliche Annäherung" to "Fiziksel yaklaşım",
    "Körperliche Nähe" to "Fiziksel yakınlık",
    "Küche" to "Mutfak",
    "Land" to "Ülke",
    "Landhaus" to "Kır evi",
    "Landhausstil" to "Kır evi tarzı",
    "Lange wach bleiben" to "Geç saatlere kadar uyanık kalın",
    "Lappland" to "Laponya",
    "Lappland, Finnland" to "Lapland, Finlandiya",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Partnerinizin size en iyi haliniz olmanız için ilham vermesine izin verin",
    "Lehne ab" to "Reddet",
    "Leichtigkeit" to "Hafiflik",
    "Leidenschaft" to "Tutku",
    "Liebe im Gleichgewicht" to "Dengede aşk",
    "Liebe sie, macht mehr Spaß" to "Onları seviyorum, daha eğlenceli",
    "Lieber durchgeplant oder spontan?" to "Planlı mı yoksa kendiliğinden mi olmasını tercih edersiniz?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "İki kişilik mi yoksa insanlarla sakin bir akşam mı geçirmeyi tercih edersiniz?",
    "Lieber nicht" to "Olmasa daha iyi",
    "Lieber vorher grob absprechen" to "Bazı şeyleri önceden kabaca tartışmak daha iyidir",
    "Lokal einkaufen" to "Yerel olarak alışveriş yapın",
    "London" to "Londra",
    "London, England" to "Londra, İngiltere",
    "Lügen" to "Yalanlar",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Herkese açık bir teklifi mi yoksa özel bir teklifi mi tercih edersiniz?",
    "Malediven" to "Maldivler",
    "Man sollte nie streitend einschlafen." to "Asla tartışırken uykuya dalmamalısınız.",
    "Mango Sorbet" to "Mango Şerbeti",
    "Markant & breit" to "Çarpıcı ve geniş",
    "Marken & Alltag" to "Markalar ve günlük yaşam",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "Akdeniz avlusu",
    "Mehr Unterstützung" to "Daha fazla destek",
    "Mehr gemeinsame Zeit" to "Birlikte daha fazla zaman",
    "Mehr zuhören" to "Daha fazlasını dinle",
    "Mehrgenerationenhaus" to "Çok kuşaklı ev",
    "Mein Arbeitsplatz" to "İş yerim",
    "Mein Partner" to "Ortağım",
    "Mich überraschen" to "Şaşırt beni",
    "Minimalistisches Interieur" to "Minimalist iç mekan",
    "Missverständnisse" to "Yanlış anlamalar",
    "Mit Familie und engen Freunden" to "Aileniz ve yakın arkadaşlarınızla",
    "Mit Kompromissen" to "Uzlaşmalarla",
    "Mitgefühl" to "Şefkat",
    "Mittelweg mit besonderen Details" to "Özel ayrıntılarla orta yol",
    "Modern geometrisch" to "Modern geometrik",
    "Moderne Grillstation" to "Modern ızgara istasyonu",
    "Moderner Name" to "Modern ad",
    "Moderner Solitär" to "Modern solitaire",
    "Moissanit" to "Mozanit",
    "Moment festhalten" to "Anı yakalayın",
    "Momente" to "anlar",
    "Monaco" to "Monako",
    "Moralische Werte" to "Ahlaki değerler",
    "Museum" to "Müze",
    "Musik" to "Müzik",
    "Mut" to "Cesaret",
    "Mädchen" to "Kızlar",
    "Möbelhaus" to "Mobilya mağazası",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Testten ayrılmak istediğinizden emin misiniz? Önceki ilerlemeniz kayıtlı kalır.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Evcil hayvanların uygulamaya dahil edilmesini ister misiniz?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Anın sosyal medyada anında paylaşılmasını ister misiniz?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Tasarruf etmemiz gerekebilir",
    "Müssen es planen" to "Planlamam gerekiyor",
    "Müssen sparen" to "Kaydetmeniz gerekiyor",
    "Nachricht an" to "Mesaj",
    "Name Partnerin" to "İş ortağının adı",
    "Namen und Startdatum eurer Beziehung." to "İlişkinizin isimleri ve başlangıç tarihi.",
    "Natursteinfassade" to "Doğal taş cephe",
    "Naturteich" to "Doğal gölet",
    "Nein, einfach halten" to "Hayır, sadece tut",
    "Nein, erstmal privat halten" to "Hayır, şimdilik gizli kalsın",
    "Nein, lieber vor Ort" to "Hayır, sitede daha iyi",
    "Nein, modern halten" to "Hayır, modern tutun",
    "Nein, nur wir" to "Hayır, sadece biz",
    "Nein, zu ablenkend" to "Hayır, çok dikkat dağıtıcı",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Akıllı ev içeren yeni bina",
    "Neubau mit Technik" to "Teknolojiyle donatılmış yeni bina",
    "Neue Liebe, neue Erfahrungen" to "Yeni aşk, yeni deneyimler",
    "Neues Hobby" to "Yeni hobi",
    "Neues Spiel" to "Yeni oyun",
    "Neugier" to "Merak",
    "New York" to "New York",
    "New York, USA" to "New York, ABD",
    "Nicht mein Fall" to "Bana göre değil",
    "Nicht nötig, lieber klassisch bleiben" to "Gerek yok, klasik kalmak daha iyi",
    "Nichts — es passt so" to "Hiçbir şey - uyuyor",
    "Nie wieder Burger" to "Bir daha asla hamburger yemeyeceğim",
    "Nie wieder Pizza" to "Bir daha pizza yemeyeceğim",
    "Niemand" to "Hiç kimse",
    "Niemand ohne Plan" to "Planı olmayan kimse",
    "Nike" to "Nike",
    "Nizza" to "Güzel",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Henüz an yok.\nİlk deneyiminizi yakalayın 💞",
    "Nur bei wichtigen Themen" to "Yalnızca önemli konular için",
    "Nur wir beide" to "Sadece ikimiz",
    "Nähe & Intimität" to "Yakınlık ve Samimiyet",
    "Obstgarten" to "Meyve Bahçesi",
    "Oder" to "Veya",
    "Offene Küche" to "Açık mutfak",
    "Offene Wohnküche" to "Açık mutfak/oturma odası",
    "Ohne Stein" to "Taşsız",
    "Open End" to "Açık son",
    "Outdoor-Küche" to "Açık mutfak",
    "Outdoor-Sofa" to "Dış mekan kanepesi",
    "Outdoor-Whirlpool" to "Açık hava jakuzisi",
    "Ovaler Diamant" to "Oval elmas",
    "Paar" to "Çift",
    "Paar-Statistiken" to "Çift istatistikleri",
    "Paris" to "Paris",
    "Paris, Frankreich" to "Paris, Fransa",
    "Partner" to "Ortak",
    "Partner-Simulator" to "İş ortağı simülatörü",
    "Partnerin" to "Ortak",
    "Party Edition" to "Parti Sürümü",
    "Party Edition II" to "Parti Sürümü II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Bir hayvan günlük yaşamımıza sığar mı?",
    "Pasta" to "Makarna",
    "Pastell" to "Pastel",
    "Penthouse mit Ausblick" to "Manzaralı çatı katı",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "Salonlu Pergola",
    "Pfingstrosen" to "Şakayıklar",
    "Pinguin" to "Penguen",
    "Pistazie" to "Antep fıstığı",
    "Pizza" to "Pizza",
    "Pizzaofen" to "Pizza fırını",
    "Platin" to "Platin",
    "PlayStation" to "PlayStation",
    "Pool" to "Havuz",
    "Pop" to "Pop",
    "Prasselnder Kamin" to "Kükreyen şömine",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Prensesler, Korsanlar ve Peri Tozu: Disney Testi",
    "Privater Innenhof" to "Özel avlu",
    "Profil" to "Profili",
    "Profil bearbeiten" to "Profili düzenle",
    "Prozentual nach Einkommen" to "Gelire dayalı yüzde",
    "Quiz verlassen" to "Testten çık",
    "Quiz verlassen?" to "Testten çıkılsın mı?",
    "Rausgehen in die Natur" to "Doğaya çıkın",
    "Reden vor ..." to "Konuşuyorum...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Birlikte düzenli tarihler veya saatler planlayın",
    "Reisen" to "Seyahat",
    "Reiseziele" to "Seyahat hedefleri",
    "Respektlosigkeit" to "Saygısızlık",
    "Restaurant" to "Restoran",
    "RnB / Soul" to "RnB / Ruh",
    "Rock" to "Rock",
    "Rom" to "Roma",
    "Rom, Italien" to "Roma, İtalya",
    "Romantik" to "Romantizm",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Mesaj, not veya hediye gibi romantik jestler beni mutlu ediyor.",
    "Romantische Stimmung" to "Romantik ruh hali",
    "Roségold" to "Pembe altın",
    "Ruhig zu zweit" to "İki kişilik sessizlik",
    "Runder Diamant" to "Yuvarlak elmas",
    "Salted Caramel" to "Tuzlu Karamel",
    "Sammle Ideen..." to "Fikir toplayın...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Yunanistan",
    "Saphir" to "Safir",
    "Saunahaus" to "Sauna evi",
    "Schickes Restaurant oder Hotel" to "Şık restoran veya otel",
    "Schlafzimmer" to "Yatak odası",
    "Schließen" to "Kapat",
    "Schmal & zart" to "İnce ve narin",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Aşk hikayemizden anlık görüntüler",
    "Schokolade" to "Çikolata",
    "Schreib frei, was dir wirklich dazu einfällt." to "Aklınıza gerçekten geleni özgürce yazın.",
    "Schreibe deine eigene Antwort" to "Kendi cevabınızı yazın",
    "Sehr gerne" to "Rica ederim",
    "Sehr leicht" to "Çok hafif",
    "Sehr wichtig — Fotos und Video" to "Çok önemli — fotoğraf ve video",
    "Sehr wichtig, es sollte persönlich sein" to "Çok önemli, kişisel olmalı",
    "Selbst kochen" to "Kendin pişir",
    "Senden" to "Gönder",
    "Separate Küche" to "Ayrı mutfak",
    "Serie schauen" to "Diziyi izle",
    "Serienmarathon auf dem Sofa" to "Koltukta dizi maratonu",
    "Sex & Liebe" to "Seks ve Aşk",
    "Seychellen" to "Seyşeller",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Bir çocuk/birden fazla çocuk için tüm masrafları karşılayabilir miyiz? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Teklif sürpriz mi olmalı?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Uygulama kültürel mi yoksa geleneksel unsurlar mı içermeli?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Uygulama kültürel mi yoksa geleneksel unsurlar mı içermeli?",
    "Sommerhochzeit" to "Yaz düğünü",
    "Sonnige Dachterrasse" to "Güneşli çatı terası",
    "Sowohl als auch" to "Her ikisi de ve",
    "Spazieren" to "Yürüyüşe çıkın",
    "Spaß & Abenteuer" to "Eğlence ve Macera",
    "Speichern" to "Kaydet",
    "Spiel bearbeiten" to "Oyunu düzenle",
    "Spielbereich für Kinder" to "Çocuklar için oyun alanı",
    "Spiele" to "Oyunlar",
    "Spiele spielen und Spaß haben" to "Oyun oynayın ve eğlenin",
    "Spontan" to "Kendiliğinden",
    "Sportplatz" to "Spor sahası",
    "Spotify" to "Spotify",
    "Sprache" to "Dil",
    "Stadt" to "Şehir",
    "Stadt oder Land — was ist uns wichtiger?" to "Şehir mi, ülke mi; bizim için hangisi daha önemli?",
    "Stadtvilla" to "Şehir villası",
    "Standesamt & Party" to "Sicil dairesi ve parti",
    "Statement-Ring" to "Bildiri yüzüğü",
    "Stilvolles Outdoor-Sofa" to "Şık dış mekan kanepesi",
    "Stimme voll zu" to "Tamamen katılıyorum",
    "Stimmt" to "Doğru",
    "Stimmt nicht" to "Doğru değil",
    "Stimmt, noch nie" to "Doğru, asla",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Plaj günü",
    "Streit über Haushalt" to "Hane halkıyla ilgili anlaşmazlık",
    "Studio Ghibli" to "Stüdyo Ghibli",
    "Ständig" to "Sürekli",
    "Suche schließen" to "Aramayı kapat",
    "Suche zurücksetzen" to "Aramayı sıfırla",
    "Suche öffnen" to "Aramayı aç",
    "Suchergebnisse" to "Arama sonuçları",
    "Sushi" to "Suşi",
    "Süß" to "Tatlı",
    "Tage zusammen 💞" to "birlikte günler 💞",
    "Tauche ins Unterbewusstsein" to "Bilinçaltına dalın",
    "Teile alle deine Hobbys mit deinem Partner" to "Tüm hobilerinizi partnerinizle paylaşın",
    "Teils teils" to "Kısmen kısmen",
    "Testen" to "Testi",
    "Themen" to "Konular",
    "Tiefe Gespräche" to "Derin sohbetler",
    "Tiefgründige Gespräche führen" to "Derin sohbetler yapın",
    "Tierpension" to "Hayvan pansiyonu",
    "Tiny House" to "Minik Ev",
    "Tippen zum Auswählen & Scrollen" to "Seçmek ve kaydırmak için dokunun",
    "Tippen zum Zuklappen" to "Daraltmak için dokunun",
    "Titel" to "Başlık",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Başlık, Kategori, Konu, Etiketler, Sorular...",
    "Tokyo, Japan" to "Tokyo, Japonya",
    "Traditioneller Name" to "Geleneksel ad",
    "Traumhaus Außenbereich" to "Rüya evinin açık alanı",
    "Traumhochzeit" to "Rüya gibi bir düğün",
    "Treffer" to "Hit",
    "Tägliche Aktivität" to "Günlük aktivite",
    "Umformulieren" to "Yeniden ifade etme",
    "Unbeantwortet" to "Cevapsız",
    "Unbeliebte Meinungen" to "Popüler olmayan görüşler",
    "Universal Studios Genie oder Neuling?" to "Universal Studios dehası mı yoksa acemi mi?",
    "Uns auseinanderzuleben" to "Ayrı büyümek",
    "Unser Intimleben" to "Samimi hayatımız",
    "Unser Traumhaus" to "Hayallerimizin evi",
    "Unser erstes Treffen" to "İlk buluşmamız",
    "Unsere Gesichter" to "Yüzlerimiz",
    "Unsere eigenen Träume" to "Kendi hayallerimiz",
    "Unsere nächste Reise" to "Bir sonraki gezimiz",
    "Unter 1000" to "1000'in altında",
    "Unter 1000 im Monat" to "Ayda 1000'in altında",
    "Unter 50€/Monat" to "Aylık 50€'nun altında",
    "Unter Leuten" to "İnsanlar arasında",
    "Untreue" to "Sadakatsizlik",
    "Urlaub" to "Tatil",
    "Vanille" to "Vanilya",
    "Venedig" to "Venedik",
    "Venedig, Italien" to "Venedik, İtalya",
    "Verbinde dich mit" to "ile bağlantı kurun",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Cevabı görmek için \${profile.partnerName}'a bağlanın",
    "Verbindung" to "bağlantısı",
    "Verbringe die Feiertage mit deiner Familie" to "Tatilinizi ailenizle geçirin",
    "Verlobungsringe" to "Nişan yüzükleri",
    "Vertrautheit" to "Aşinalık",
    "Viel getrennt" to "Çok fazla ayrılık",
    "Vielleicht ein oder zwei" to "Belki bir veya iki",
    "Vielleicht, aber mündlich reicht" to "Belki, ama sözlü olarak yeterli",
    "Vielleicht, wenn es machbar ist" to "Belki, eğer mümkünse",
    "Vielleicht, wenn es passt" to "Belki, eğer uyarsa",
    "Vintage Art déco" to "Vintage Art Deco",
    "Vintage verspielt" to "Vintage eğlenceli",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Partneriniz tarafından yeni hobilerle tanıştırılmak",
    "Vor dem Kauf eines Hauses besprechen" to "Ev satın almadan önce tartışın",
    "Vor der Anschaffung eines Haustiers besprechen" to "Bir evcil hayvan satın almadan önce tartışın",
    "Vor der gemeinsamen Reise besprechen" to "Birlikte seyahat etmeden önce tartışın",
    "Vor nichts" to "Hiçbir şey",
    "Vorort" to "Banliyö",
    "Walnuss" to "Ceviz",
    "Wandern" to "Yürüyüş",
    "Wann fühlst du dich mir am nächsten?" to "Ne zaman bana en yakın hissediyorsun?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Ne zaman fiziksel olarak bana yakın hissediyorsun?",
    "Was bedeutet Vertrauen für dich konkret?" to "Güven sizin için özellikle ne anlama geliyor?",
    "Was entspannt dich mehr?" to "Seni daha çok ne rahatlatır?",
    "Was fehlt dir über die Distanz am meisten?" to "Uzaklığa dair en çok neyi özlüyorsunuz?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Evinizin en çok neyi seviyorsunuz?",
    "Was hast du von deinem Partner gelernt?" to "Partnerinizden ne öğrendiniz?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Birlikte erotik içerik izleme konusunda ne düşünüyorsunuz?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Aksesuarlar (ör. tabelalar, balonlar vb.) hakkında ne düşünüyorsunuz?",
    "Was ist das Wichtigste beim Antrag?" to "Başvururken en önemli şey nedir?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Cinsel bir karşılaşmada aradığınız en önemli şey nedir?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "En sevdiğiniz fotoğrafımız hangisi? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Birlikte yaşamakla ilgili en büyük korkunuz nedir?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Sevdiğiniz ama partnerinizin anlayamadığı yiyecek nedir?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Sizin için kesinlikle anlaşmayı bozan şey nedir?",
    "Was ist für jeden von uns das absolute Highlight?" to "Her birimiz için mutlak öne çıkan şey nedir?",
    "Was ist passiert?" to "Ne oldu?",
    "Was macht einen Moment für dich romantisch?" to "Bir anı sizin için romantik kılan şey nedir?",
    "Was magst du an deinem Partner am liebsten?" to "Partnerinizin en çok neyi seviyorsunuz?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Hangisini daha çok seviyorsunuz: erken kalkmak mı yoksa geç kalmak mı?",
    "Was magst du lieber?" to "Hangisini daha çok seviyorsunuz?",
    "Was möchtest du eigentlich sagen?" to "Aslında ne söylemek istiyorsun?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Partnerinizin neyi daha sık yapmasını istersiniz?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Seyahat ettiğimizde hayvana ne olur?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Büyüdüğünde çocuğumuza ne olacak?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Ebeveyn olarak neyi asla gözden kaçırmamalıyız?",
    "Was war dein schönster Moment mit mir bisher?" to "Şu ana kadar benimle geçirdiğin en güzel anın neydi?",
    "Was wir gegessen haben" to "Ne yedik",
    "Was wollt ihr nie vergessen?" to "Neyi asla unutmak istemezsin?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Sizin için hangisi daha kötü olabilir: bir daha pizza yememek mi, yoksa bir daha hamburger yememek mi?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Birlikte bir günde en çok ne yapmak istersiniz?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Para sorun olmasaydı hemen neyi değiştirirdiniz?",
    "Weiter" to "Sonraki",
    "Weiter spielen" to "Oynamaya devam et",
    "Weiß ich noch nicht" to "Henüz bilmiyorum",
    "Weiße Rosen" to "Beyaz güller",
    "Weißgold" to "Beyaz altın",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Çocuğumuz bizden mutlaka hangi niteliği almalıdır?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Bir teklif için nasıl bir ortam istersiniz?",
    "Welcher Raum sagt am meisten über dich aus?" to "Hangi oda senin hakkında en çok şey söylüyor?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Mama ve veteriner için ne kadar bütçe planlıyoruz?",
    "Welches Lied macht dich an? 🥵" to "Hangi şarkı sizi heyecanlandırıyor? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Hangi paylaşılan fotoğraf favoriniz?",
    "Wellnessbad" to "Sağlık banyosu",
    "Wenn es schwierig ist" to "İşler zor olduğunda",
    "Wenn ich müde bin" to "Yorulduğumda",
    "Wenn wir uns lange umarmen" to "Uzun süre sarıldığımızda",
    "Wenn wir zusammen lachen" to "Birlikte güldüğümüzde",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Ne sipariş edeceğine kim daha çabuk karar veriyor?",
    "Wer findet die besten Restaurants?" to "En iyi restoranları kim buluyor?",
    "Wer gibt mehr Herzlichkeit?" to "Kim daha fazla sıcaklık veriyor?",
    "Wer hat den besseren Musikgeschmack?" to "Kimin müzik zevki daha iyi?",
    "Wer hängt mehr an seinen Eltern?" to "Kim ebeveynlerine daha bağlı?",
    "Wer ist besser organisiert?" to "Kim daha iyi organize olmuş?",
    "Wer ist der Beste bei der Filmauswahl?" to "Film seçmede en iyi kim?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Romantik randevuları planlamada en iyi kim?",
    "Wer ist der beste Tänzer?" to "En iyi dansçı kim?",
    "Wer ist romantischer?" to "Kim daha romantik?",
    "Wer kocht besser?" to "Kim daha iyi yemek pişiriyor?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Yenileme ve bakımla kim ilgileniyor?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Karşısındaki kişinin kendini iyi hissetmediğini kim daha çabuk fark eder?",
    "Wer sucht am Ende wirklich den Film aus?" to "Sonunda filmi gerçekten kim seçiyor?",
    "Wer vergisst eher einen Jahrestag?" to "Kimin yıldönümünü unutma olasılığı daha yüksektir?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Ertesi sabah kimin kendi adını unutma olasılığı daha yüksektir?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Kimin ertesi gün hakkında hiçbir şey bilmediği bir video bulma olasılığı daha yüksektir?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Kim geceyi bir yabancının kanepesinde geçirmeyi tercih eder?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Kimin bir partide uyuyakalması ve yüzünde Sharpie ile uyanması daha muhtemeldir?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Kimin dans pistinde kayması ama bunu harika bir hareket gibi göstermesi daha muhtemeldir?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Bir ev partisinde Spotify çalma listesinin kontrolünü kimin ele geçirme olasılığı daha yüksektir?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Kimin bir partideki herkese pizza sipariş edip onu kendisinin yeme olasılığı daha yüksektir?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Bir partide ilk kimin uykuya dalma olasılığı daha yüksektir?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Kimin bir partide birdenbire temizlik yapmaya başlama olasılığı daha yüksektir?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Tam tersi doğruyken kim tamamen ayık olduğunu iddia edebilir?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Bir tartışmada kimin ilk önce teslim olma olasılığı daha yüksektir?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Kimin içki oyununda hile yapma olasılığı daha yüksektir?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Kimin büfeye baskın yapıp gizlice eve yiyecek götürme olasılığı daha yüksektir?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Gecenin en utanç verici fotoğrafını kimin hikayesinde yayınlama olasılığı daha yüksektir?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "DJ'i kendi favori şarkısını istemesi için rahatsız etme olasılığı daha yüksek olan kimdir?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Bir şarkının sözlerini kimin akortsuz ama inançla söyleme olasılığı daha yüksektir?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Menüdeki en pahalı içeceği kim sipariş edip pişman olur?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Gürültüden şikayetçi olsalar komşuları kimin davet etme olasılığı daha yüksek olurdu?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Parti oyunlarını (Beer Pong gibi) kim fazla ciddiye alır?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "VIP erişimi elde etmek için kimin fedailerle arkadaş olma olasılığı daha yüksektir?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Kimin kendiliğinden bir karaoke savaşı başlatma olasılığı daha yüksektir?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Kimin şişe açacağı kullanmadan şişe açma olasılığı daha yüksektir?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Kesinlikle kimse sormasa bile kimin konuşma yapma olasılığı daha yüksektir?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Kimin banyoda selfie çekerek bir saat geçirme olasılığı daha yüksektir?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Kimin utanç verici bir dans performansı sergileyip bunu kutlaması daha muhtemel?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Parti bittikten sonra kimin eski partnerini arama olasılığı daha yüksektir?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Garip bir konuğu kazara rahatsız etme olasılığı kimde daha yüksektir?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Kimin veda etmeden partiden gizlice ayrılma olasılığı daha yüksektir?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Kim misafirlerle konuşmak yerine ev sahibinin evcil hayvanıyla oynamayı tercih eder?",
    "Wer würde eher spontan eine Reise buchen?" to "Kimin spontane bir gezi rezervasyonu yapma olasılığı daha yüksektir?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Kimin mutfakta saatlerce derin sohbetler yapma olasılığı daha yüksektir?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Kimin yanlışlıkla başkasının içkisini içme olasılığı daha yüksektir?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Kimin yanlışlıkla pahalı bir vazoyu veya kırılabilir bir şeyi devirme olasılığı daha yüksektir?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Kimin karmaşık bir kokteyli kendi başına karıştırmaya çalışması ve sefil bir şekilde başarısız olması daha muhtemeldir?",
    "Wer würde eher zu spät kommen?" to "Kimin geç kalma olasılığı daha yüksek?",
    "Wer würde eher?" to "Kim tercih eder?",
    "Wer übernimmt die tägliche Versorgung?" to "Günlük bakımı kim hallediyor?",
    "Werde so akzeptiert, wie du bist" to "Olduğun gibi kabul edil",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Çocuğa/çocuklara yeterli zaman ayırabilecek miyiz? ⏳",
    "Whirlpool" to "Jakuzi",
    "White Chocolate" to "Beyaz Çikolata",
    "Widgets" to "Widget'lar",
    "Wie fühlst du dich am meisten geliebt?" to "En çok nasıl sevildiğinizi hissediyorsunuz?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Farklı gelirlerle nasıl başa çıkacağız?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Partnerinizin sizinle seks başlatmasının en iyi yolu nedir?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Partneriniz sizin için nasıl daha iyi bir partner olabilir?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Tekliften ne kadar sonra başkalarıyla kutlamak istiyorsunuz?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Orada en az ne kadar kalmak istiyoruz?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Dilekler hakkında konuşmak sizin için ne kadar kolay?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Geleceğimizin nasıl görünmesini istiyorsunuz?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Evinizdeki mükemmel Pazar günü nasıl geçiyor?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Seks sırasında müstehcen konuşmalar hakkında ne düşünüyorsunuz?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Gerçekçi olarak ne kadar krediyi karşılayabiliriz?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Ayrı ne kadar zaman geçirmek istiyoruz?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Toplamda ne kadar harcamak istiyoruz?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Bebek doğduğunda ilişkimize nasıl zaman bulacağız?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Anın yakalanması sizin için ne kadar önemli?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Uygulamanın hobilerinizi veya ilgi alanlarınızı yansıtması sizin için ne kadar önemli?",
    "Wie würdest du sie/ihn nennen?" to "Ona ne ad verirsiniz?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Seks dışında sevginizi göstermenin en sevdiğiniz yolu nedir?",
    "Wildblumen" to "Kır çiçekleri",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Kız mı erkek mi istiyorsun? 👶",
    "Wintergarten" to "Kış bahçesi",
    "Winterhochzeit" to "Kış düğünü",
    "Wir bestellen einfach beides" to "İkisini de sipariş ediyoruz",
    "Wir brauchen ewig" to "Bu bizi sonsuza kadar götürür",
    "Wir einigen uns nie" to "Asla aynı fikirde değiliz",
    "Wir entscheiden es gemeinsam" to "Birlikte karar veriyoruz",
    "Wir treffen uns in der Mitte" to "Ortada buluşuyoruz",
    "Wir wechseln uns ab" to "Sırayla yapıyoruz",
    "Wird stressig" to "Stresli oluyor",
    "Wobei lachst du am meisten?" to "Seni en çok ne güldürüyor?",
    "Wofür sparen wir gemeinsam?" to "Birlikte ne için tasarruf yapıyoruz?",
    "Wohnzimmer" to "Oturma odası",
    "Woran erinnerst du dich am lebhaftesten?" to "En canlı şekilde neyi hatırlıyorsunuz?",
    "Worauf freust du dich bei uns am meisten?" to "Bizimle en çok neyi sabırsızlıkla bekliyorsunuz?",
    "Worte/Komplimente" to "Kelimeler/İltifatlar",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "İlişkimizde en çok korktuğunuz şey nedir?",
    "Wünsche? z.B. günstig, draußen" to "Dilekleriniz? örneğin ucuz, dışarıda",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Tatilde (seyahat dahil) evlenme teklif etmeyi mi tercih edersiniz?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube Müzik",
    "Zeichne für mich" to "Benim için çiz",
    "Zeichne mich als Tier — welches wäre ich?" to "Beni bir hayvan olarak çiz - hangisi olurdum?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Birbirimize olan duygularımızı bir sembol olarak çizin.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Hayallerimizin evini tek çizgide çizin. En dikkat çekici şey nedir?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "İlk randevumuzu çizin - resimde kesinlikle ne olması gerekiyor?",
    "Zeichnen" to "Çekiliş",
    "Zeit füreinander" to "Birbirimiz için zaman",
    "Zeit, wenn das Baby schläft" to "Bebeğin uyuduğu zaman",
    "Zelten gehen" to "Kamp yapmaya gidin",
    "Zitrone" to "Limon",
    "Zu Hause, gemütlich und privat" to "Evde, rahat ve özel",
    "Zu einem Picknick gehen" to "Pikniğe gitmek",
    "Zu einem ausgefallenen Abendessen gehen" to "Süslü bir akşam yemeğine gidiyorum",
    "Zu zweit reisen" to "Çift olarak seyahat edin",
    "Zuhause & Alltag" to "Ev ve günlük yaşam",
    "Zuhören" to "Dinle",
    "Zurück" to "Geri",
    "Zusammen seit" to "O zamandan beri birlikte",
    "Zusammen seit (TT.MM.JJJJ)" to "(GG.AA.YYYY) tarihinden beri birlikteyiz",
    "Zusammenziehen" to "Sözleşme",
    "Zustimmen oder Ablehnen" to "Katılıyorum veya Katılmıyorum",
    "Zwei Kreise, die sich überschneiden" to "Üst üste binen iki daire",
    "Zwei Stühle davor" to "Önünde iki sandalye",
    "Zärtlich sein" to "Şefkatli olun",
    "Öfter als ich zugebe" to "İtiraf ettiğimden çok daha fazla",
    "Über 100€/Monat" to "Aylık 100€'dan fazla",
    "Über 2000 im Monat" to "Ayda 2000'den fazla",
    "Über mich selbst" to "Kendim hakkında",
    "Übernehmen" to "Uygula",
    "Überraschend" to "Şaşırtıcı",
    "Überraschung" to "Sürpriz",
    "Überspringen" to "Atla",
    "Übertrieben und großartig" to "Aşırı ve muhteşem",
    "✎ Tippe, um zu antworten" to "✎ Yanıtlamak için dokunun",
    "✨ GFK-Brücke" to "✨ GRP köprüsü",
)

internal fun localizeTurkishDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_TURKISH_CONTENT)
