package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_UKRAINIAN_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 років",
    "1000 - 1500 im Monat" to "1000 - 1500 в місяць",
    "1000 bis 3000" to "Від 1000 до 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 в місяць",
    "3000 bis 5000" to "Від 3000 до 5000",
    "5-10 Jahre" to "5-10 років",
    "50-100€/Monat" to "50-100€/міс",
    "Ab 100€" to "Від 100€",
    "Ab 500€" to "Від 500 євро",
    "Ab 50€" to "Від 50€",
    "Ab und zu" to "Час від часу",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Скільки нам потрібно витратити, перш ніж зробити покупку?",
    "Abbrechen" to "Скасувати",
    "Abenteuer" to "Пригоди",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Діяльність",
    "Alle" to "Всі",
    "Alle Pakete" to "Усі пакети",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Втратити всіх своїх друзів, крім найкращого друга",
    "Alle intimen Momente selbst initiieren" to "Ініціюйте всі інтимні моменти самі",
    "Alles davon" to "Все",
    "Alles, was noch kommt" to "Все, що буде",
    "Alltagsroutine" to "Повсякденна рутина",
    "Alltägliche Berührungen" to "Щоденні штрихи",
    "Altbau mit Charme" to "Стара будівля з шармом",
    "Am Strand" to "На пляжі",
    "Am liebsten alles zusammen" to "Бажано все разом",
    "Am selben Tag mit Freunden/Familie" to "У той самий день з друзями/родиною",
    "Amazon" to "Amazon",
    "Amsterdam" to "Амстердам",
    "Amsterdam, Niederlande" to "Амстердам, Нідерланди",
    "An das Gefühl" to "Відчуття",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "У громадському місці з великою кількістю глядачів",
    "An einen Geruch" to "Запаху",
    "An einen Song" to "Під пісню",
    "An etwas, das ich gesagt habe" to "Щось я сказав",
    "Analyse starten" to "Розпочати аналіз",
    "Analysiere eure Muster..." to "Аналізуйте свої візерунки...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Проаналізуйте свої відповіді та чати відповідно до Готтмана та GFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Ананас у піці дуже смачний.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Надішліть фотографію у відповідь",
    "Antwortähnlichkeit" to "Подібність відповіді",
    "App-Sprache auswählen" to "Виберіть мову програми",
    "Auf eine Bootsparty gehen" to "Йду на вечірку на човні",
    "Aufmerksamkeit" to "Увага",
    "Aufräumen und Projekte angehen" to "Прибирайте та виконуйте проекти",
    "Aufwärmen" to "Розминка",
    "Aufwärmen: Einander kennenlernen" to "Розминка: Знайомство",
    "Aus dem Urlaub" to "З відпустки",
    "Ausgefallener Name" to "Чудове ім'я",
    "Ausschlafen und faulenzen" to "Виспатися та відпочити",
    "Ausschlafen und nichts tun" to "Спати і нічого не робити",
    "Aussehen" to "Зовнішній вигляд",
    "Auto" to "Авто",
    "Außenkamin" to "Відкритий камін",
    "BEANTWORTE" to "ВІДПОВІДЬ",
    "Bali" to "Балі",
    "Bali, Indonesien" to "Балі, Індонезія",
    "Banane" to "Банан",
    "Beantwortet" to "Відповів",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Відповідайте на запитання одночасно — відповіді не буде видно, доки ви обидва не закінчите.",
    "Beantwortete Fragen" to "Відповіді на запитання",
    "Bearbeiten" to "Редагувати",
    "Bei Insider-Witzen" to "Для внутрішніх жартів",
    "Bei Memes" to "Про меми",
    "Bei einer spontanen Berührung" to "При спонтанному дотику",
    "Beide" to "Обидва",
    "Beide gleich" to "Обидва однакові",
    "Beide zusammen" to "Обидва разом",
    "Beide, aber wir tun so als ob nicht" to "Обидва, але ми вдаємо, що ні",
    "Beides" to "Обидва",
    "Beides wäre schlimm" to "І те, і інше було б погано",
    "Beim Einschlafen nebeneinander" to "Засинають один біля одного",
    "Beim Reden" to "Під час розмови",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Відомі туристичні місця завжди розчаровують.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Опишіть наше сексуальне життя за допомогою емодзі.",
    "Besser kommunizieren" to "Спілкуйтеся краще",
    "Bessere Lage" to "Краще розташування",
    "Bestellen" to "Замовити",
    "Besuchte Länder" to "Відвідані країни",
    "Besuchte Städte" to "Відвідані міста",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Ви віддаєте перевагу екстравагантній пропозиції чи чомусь тонкому?",
    "Beziehung" to "Стосунки",
    "Bibliothek" to "Бібліотека",
    "Bin manchmal unsicher" to "Іноді я невпевнений",
    "Bist du ein Videospiel-Guru?" to "Ви гуру відеоігор?",
    "Blumenwiese" to "Квіткова галявина",
    "Bunte Blumenwiese" to "Барвиста квіткова галявина",
    "Burger" to "Бургери",
    "Burger King" to "Burger King",
    "Chat" to "Побалакати",
    "Coca-Cola" to "Coca Cola",
    "Cookie Dough" to "Тісто для печива",
    "Dachgarten mit Lounge" to "Сад на даху з лаунжем",
    "Dachterrasse" to "Тераса на даху",
    "Das Wetter an dem Tag" to "Погода того дня",
    "Das erste Selfie" to "Перше селфі",
    "Das meiste weiß ich" to "Більшу частину я знаю",
    "Das oder das?" to "Це чи те?",
    "Das tägliche Leben" to "Повсякденне життя",
    "Dass Zusagen gehalten werden" to "Що обіцянки виконуються",
    "Dass alles meinen Stil hat" to "Що все має мій стиль",
    "Dass ich alles erzählen kann" to "Що я все можу розповісти",
    "Dass ich mich nicht sorgen muss" to "Мені не потрібно турбуватися",
    "Dass wir ungestört sind" to "Що нас не турбують",
    "Dein Name" to "Ваше ім'я",
    "Deine Antwort..." to "Ваша відповідь...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Ваші відповіді збережено. Як тільки Партнер завершить пакет, обидві відповіді будуть видимі разом.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Ваші відповіді збережено. Коли \${profile.partnerName} завершить пакет, обидві відповіді будуть видимі разом.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Зробіть ваші стосунки авантюрними та спонтанними",
    "Deine Beziehung stabil und sicher machen" to "Зробіть ваші стосунки стабільними та безпечними",
    "Deine eigene Antwort" to "Ваша відповідь",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Краще поділитися своїми найпотаємнішими секретами з партнером",
    "Deinen besten Freund verlieren" to "Втрата найкращого друга",
    "Denke an dich" to "Подумайте про себе",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Двічі переглядати один і той же фільм — марна трата часу.",
    "Der Blick nach draußen" to "Вид ззовні",
    "Der Garten" to "Сад",
    "Der Ort" to "Місце",
    "Der Ring und die Geste" to "Дзвінок і жест",
    "Der perfekte Heiratsantrag" to "Ідеальна пропозиція одружитися",
    "Derjenige sein, der umarmt wird" to "Будь тим, кого обіймають",
    "Deutsch" to "Німецька",
    "Diamant" to "Діамант",
    "Diamanten im Band" to "Діаманти в групі",
    "Die Distanz" to "Відстань",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Проведіть канікули з родиною вашого партнера",
    "Die Gemütlichkeit und Ruhe" to "Комфорт і спокій",
    "Die Menschen, die darin wohnen" to "Люди, які в ньому живуть",
    "Die Umgebung und Atmosphäre" to "Середовище та атмосфера",
    "Die Worte und Emotionen" to "Слова та емоції",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Неперевершене розважальне завдання",
    "Diejenige sein, die umarmt" to "Будь тим, хто обіймає",
    "Direkt ansprechen" to "Звертатися безпосередньо",
    "Diskussion" to "Обговорення",
    "Diskutiere vor dem Kinderkriegen" to "Обговоріть, перш ніж мати дітей",
    "Diskutiert eure Antworten" to "Обговоріть свої відповіді",
    "Disney" to "Дісней",
    "Doch, schon mal" to "Так, так",
    "Draußen mit der Natur als Kulisse" to "На вулиці з природою як фоном",
    "Drei-Stein-Ring" to "Каблучка з трьох каменів",
    "Du bist dran" to "Ваша черга",
    "Du fehlst mir" to "Я сумую за тобою",
    "Dubai" to "Дубай",
    "Dubai, VAE" to "Дубай, ОАЕ",
    "Dunkles Design" to "Темна тема",
    "Durch Berührung" to "На дотик",
    "Durch Worte" to "Через слова",
    "Durch Zeit zu zweit" to "Крізь час разом",
    "Durch kleine Gesten" to "Маленькими жестами",
    "Durchgeplant" to "Добре сплановано",
    "ERGEBNISSE" to "РЕЗУЛЬТАТИ",
    "Egal, Hauptsache gesund" to "Як би там не було, головне здоров'я",
    "Ehepaar Leben" to "Життя сімейної пари",
    "Eher knapp" to "Досить близько",
    "Eher nicht" to "Не дуже",
    "Eher schwer" to "Досить важко",
    "Eher schwierig" to "Досить важко",
    "Eher zu" to "Скоріше",
    "Eifersucht ist ein Zeichen von Liebe." to "Ревнощі - ознака кохання.",
    "Eigenes Gemüsebeet" to "Власна грядка",
    "Ein Abenteuer in einer neuen Stadt" to "Пригода в новому місті",
    "Ein Anker" to "Якір",
    "Ein Balkon oder Garten" to "Балкон чи сад",
    "Ein Filmabend" to "Кіновечір",
    "Ein Harmony-Meilenstein eurer Liebe." to "Віха гармонії вашого кохання.",
    "Ein Herz" to "Серце",
    "Ein Herz an der Tür" to "Серце біля дверей",
    "Ein Jahr lang eine Fernbeziehung führen" to "Мати стосунки на відстані рік",
    "Ein Kindheitsessen" to "Страва дитинства",
    "Ein Live-Musik-Konzert besuchen" to "Відвідайте концерт живої музики",
    "Ein Museum besuchen" to "Відвідайте музей",
    "Ein Spieleabend" to "Ігровий вечір",
    "Ein Spieleabend mit Freunden" to "Вечір гри з друзями",
    "Ein Urlaubsfoto" to "Фото з відпустки",
    "Ein aktives Abenteuer" to "Активна пригода",
    "Ein entspannender Spa-Tag" to "Розслаблюючий спа-день",
    "Ein ganz normaler Alltagstag" to "Цілком звичайний щоденний день",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Затишний вечір у домі під час грози",
    "Ein gemütliches Date drinnen" to "Затишне побачення в приміщенні",
    "Ein lustiges Bild" to "Смішна картинка",
    "Ein paar Handyfotos reichen" to "Кілька фотографій на мобільний телефон достатньо",
    "Ein paar Stunden" to "Кілька годин",
    "Ein paar kulturelle Anklänge sind okay" to "Кілька культурних посилань — це добре",
    "Ein romantischer Abend" to "Романтичний вечір",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Романтична вечеря при свічках",
    "Ein romantisches Bild" to "Романтичний образ",
    "Ein romantisches Picknick an einem schönen Ort" to "Романтичний пікнік у гарному місці",
    "Ein schwerer Moment, den wir geschafft haben" to "Складний момент, який ми впоралися",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Чудове побачення на природі під місячним світлом",
    "Ein ungewöhnliches Gericht" to "Незвичайна страва",
    "Ein zufälliger Schnappschuss" to "Випадковий знімок",
    "Einander kennenlernen" to "Знайомство",
    "Eine Autoreise" to "Дорожня подорож",
    "Eine Brücke" to "Міст",
    "Eine Date-Nacht unter den Sternen" to "Ніч побачень під зірками",
    "Eine Million Dollar gewinnen" to "Виграй мільйон доларів",
    "Eine Million Dollar verdienen" to "Заробіть мільйон доларів",
    "Eine Nacht in einem Club" to "Ніч у клубі",
    "Eine Schokoladenverkostung" to "Дегустація шоколаду",
    "Eine Wanderung mit Panoramablick machen" to "Здійсніть прогулянку з панорамними краєвидами",
    "Eine Weinverkostung" to "Дегустація вина",
    "Eine gemeinsame Reise" to "Спільна подорож",
    "Eine gemütliche Nacht zu Hause" to "Затишна ніч вдома",
    "Eine neue Sprache zu lernen ist einfach." to "Вивчити нову мову легко.",
    "Einen Film anschauen" to "Подивіться фільм",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Взагалі не спілкувалися один з одним місяць",
    "Einen Tanzkurs besuchen" to "Відвідайте уроки танців",
    "Einen Vergnügungspark erkunden" to "Дослідіть парк розваг",
    "Einen Wellness-Tag" to "Оздоровчий день",
    "Einen sehr emotionalen Partner haben" to "Мати дуже емоційного партнера",
    "Einen sehr logischen Partner haben" to "Мати дуже логічного партнера",
    "Einer zahlt alles" to "Одна людина оплачує все",
    "Einfach mehr Alltag" to "Просто більше повсякденного життя",
    "Einfach nebeneinander sein" to "Просто будьте поруч",
    "Einfach und intim" to "Просто та інтимно",
    "Einige Dinge für dich behalten" to "Тримайте деякі речі при собі",
    "Einmal" to "Раз",
    "Eins, das nur wir kennen" to "Знаємо лише ми",
    "Englisch" to "Англійська",
    "Entspannte Hängematte" to "Спокійний гамак",
    "Entspannung" to "Релаксація",
    "Erdbeere" to "Полуниця",
    "Erfolgreich" to "Успішно",
    "Ergebnisse" to "Результати",
    "Erst bei sehr großen Summen" to "Тільки на дуже великі суми",
    "Erst nur enge Freunde/Familie" to "Спочатку лише близькі друзі/родина",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Мене дратує, коли мій партнер надто довго відповідає на повідомлення.",
    "Essen & Genuss" to "Їжа та задоволення",
    "Essensvorlieben" to "Харчові переваги",
    "Etwa eine Woche später, erst mal nur wir" to "Приблизно через тиждень, спочатку тільки ми",
    "Etwas Neues ausprobieren" to "Спробуйте щось нове",
    "Etwas ganz anderes" to "Щось зовсім інше",
    "Etwas sehr Scharfes" to "Щось дуже гостре",
    "Etwas, das ich selbst gern erfinde" to "Щось, що я люблю винаходити сам",
    "Etwas, eine kleine Note wäre schön" to "Щось, маленька замітка була б непоганою",
    "Familie" to "Сім'я",
    "Familie/Freunde" to "Сім'я/Друзі",
    "Familienmensch" to "Сім'янин",
    "Farbedelstein" to "Кольоровий дорогоцінний камінь",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Телевізійну рекламу іноді цікаво дивитися.",
    "Fertig" to "Готово",
    "Fertig!" to "Готово!",
    "Feste Date-Nights" to "Ночі з фіксованими датами",
    "Feuerstelle" to "Вогнище",
    "Filigran & schlicht" to "Філігранно та просто",
    "Filme/Serien" to "Фільми/серіали",
    "Formuliere um..." to "Перефразуйте...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Перефразуйте свою чернетку ненасильницьким способом: спостереження, відчуття, потреба, запит.",
    "Frage hinzufügen" to "Додайте запитання",
    "Fragen & Spiele" to "Запитання та ігри",
    "Fragen für jede Gelegenheit" to "Питання на будь-який випадок",
    "Freizeitpark" to "Парк розваг",
    "Freunde treffen" to "Зустрітися з друзями",
    "Freundschaften mit Ex-Partnern sind okay." to "Дружба з колишніми — це добре.",
    "Früh aufstehen" to "Вставай рано",
    "Fußbodenheizung" to "Підігрів підлоги",
    "Führen wir getrennte oder gemeinsame Konten?" to "Ми маємо окремі чи спільні рахунки?",
    "Für dich empfohlen" to "Рекомендовано для вас",
    "Für die Zukunft" to "На майбутнє",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Для цього пошуку не знайдено відповідних запитань чи ігор.",
    "Für immer" to "Назавжди",
    "Fürsorglichkeit" to "Турбота",
    "GFK-Brücke" to "GRP міст",
    "Galerie" to "Галерея",
    "Gar nicht, der Moment gehört uns" to "Зовсім ні, мить за нами",
    "Gar nichts tun" to "Нічого не робити",
    "Geduld" to "Терпіння",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Ідіть рано вранці, щоб побачити схід сонця",
    "Geht so" to "Виходить так",
    "Geister existieren wirklich." to "Привиди дійсно існують.",
    "Gelassenheit" to "Безтурботність",
    "Gelbgold" to "Жовте золото",
    "Geld & Finanzen" to "Гроші та фінанси",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Подорожуйте світом разом, досліджуйте нові культури та кухні",
    "Gemeinsam ein Lego bauen" to "Побудуйте Lego разом",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Випробуйте новий рецепт разом на кухні",
    "Gemeinsame Konten" to "Спільні облікові записи",
    "Gemeinsame Nächte" to "Ночі разом",
    "Gemeinsame Tage" to "Дні разом",
    "Gemischt" to "Змішаний",
    "Gemüsebeet" to "Овоч",
    "Gemütliche Feuerstelle" to "Затишний камін",
    "Gesprächsanreger" to "Початок розмови",
    "Getrennte Konten" to "Окремі облікові записи",
    "Getrennte Urlaube tun einer Beziehung gut." to "Роздільні відпустки корисні для стосунків.",
    "Gewächshaus" to "Теплиця",
    "Glasfassade" to "Скляний фасад",
    "Gleichgültigkeit" to "Байдужість",
    "Glücklich und frei" to "Щасливі та вільні",
    "Gourmet Eis-Sorten" to "Вишукані сорти морозива",
    "Gravur innen" to "Гравірування всередині",
    "Grillplatz" to "Зона барбекю",
    "Groß & üppig" to "Великий і пишний",
    "Große Familie" to "Велика родина",
    "Große Feier" to "Велике свято",
    "Große Fenster" to "Великі вікна",
    "Große Fensterfront" to "Велике вікно спереду",
    "Großer Außenpool" to "Великий відкритий басейн",
    "Großer Garten" to "Великий сад",
    "Großer Stein" to "Великий камінь",
    "Größere Küche" to "Більша кухня",
    "Gutes Essen" to "Хороша їжа",
    "Habe ich" to "Я так і зробив",
    "Habe ich noch nie" to "Ніколи",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Ви виявили якісь дивовижні відмінності? Обговоріть, чому вам більше подобаються певні варіанти!",
    "Haus am See" to "Будинок біля озера",
    "Haus/Wohnung" to "Будинок/квартира",
    "Hazelnut" to "Фундук",
    "Heimkino" to "Домашній кінотеатр",
    "Herzhaft" to "Ситний",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Зараз тут нічого немає.\nЗмініть фільтр або виберіть іншу тему.",
    "Hilfe im Alltag" to "Допомога в побуті",
    "Himbeere" to "Малина",
    "Hinzufügen" to "Дод",
    "Hobbys" to "Хобі",
    "Hochzeitssträuße" to "Весільні букети",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Гордість Гоґвортс Хаус: Де ти належиш?",
    "Home" to "Дім",
    "Hot Tub" to "Гідромасажна ванна",
    "Humor" to "гумор",
    "Hund" to "собака",
    "Hängematte" to "гамак",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Бажаєте отримати письмовий лист як частину заявки?",
    "IKEA" to "IKEA",
    "Ich" to "я",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Я віддаю перевагу романтичним прогулянкам у парку, ніж походу в кіно.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Я ніколи не засинав у кіно.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Мені подобається відкривати нові хобі чи заняття з моїм партнером.",
    "Ich finde eine Alternative" to "Я знайду альтернативу",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Мені подобається пробувати нові ресторани зі своїм партнером замість того, щоб постійно ходити в одні й ті самі місця.",
    "Ich habe noch nie" to "Ніколи",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Я ніколи не боявся американських гірок, і все одно сів на них.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Я ніколи не купував квитки Fast Pass, тому що мав нетерпіння.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Я ніколи не скасовував планів залишитися вдома і подивитися телешоу.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Я ніколи не чекала свого листа з Гоґвортсу.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Я ніколи не казав, що Слизерин був не таким вже й поганим.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Я ніколи не казав, що був занадто старим для фільмів Діснея (і таємно ними користувався).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Я ніколи навмисно не збивав когось синім танком у Mario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Я ніколи не плакала під час перегляду фільму Disney.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Я ніколи не прикривав очі під час перегляду фільму жахів.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Я ніколи не забував зберегти гру і не втрачав години прогресу.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Я ніколи не виходив з кімнати під час незручної сцени (кринг-фактор).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Я ніколи не займав кумедну позу під час фото з американських гірок.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Я ніколи не грав до пізньої ночі і не шкодував про те, що втомився наступного дня.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Я ніколи не шукав у Google кінцівку фільму, бо не міг дочекатися.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Я ніколи не відчував, що стою на знімальному майданчику.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Я ніколи не пропускав інтро свого улюбленого серіалу.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Я ніколи не ділився чужим паролем Netflix.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Я ніколи не слухав саундтрек гри під час роботи чи навчання.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Я ніколи не звинувачував контролер, коли програвав.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Я ніколи не викидав клавіатуру чи контролер у гніві.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Я ніколи не забував мокрий одяг у пральній машині на кілька днів.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Я ніколи не витрачав реальні гроші на косметичні речі в грі.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Я ніколи не водив машину в чужій країні.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Я ніколи не співав пісні Діснея в душі.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Я ніколи не їздив на електромобілі.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Я ніколи не фотографувався з талісманом парку.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Я ніколи не називав домашнього улюбленця на честь героя Хогвартсу.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Я ніколи не кидав попкорн у кінотеатрі і все одно його їв.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Я ніколи не використовував у повсякденному житті цитату Майстра Йоди із «Зоряних воєн».",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Я ніколи не купував дорогий сувенір у тематичному парку.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Я ніколи не рекомендував фільм, який інший вважав би жахливим.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Я ніколи не дивився церемонію вручення Оскара в прямому ефірі серед ночі.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Я ніколи не скасовував серіал, тому що минулий сезон був таким поганим.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Я ніколи не дивився цілий сезон серіалу за один день.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Я ніколи не перемагав боса з першої спроби і почувався богом.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Я ніколи не знаходив лиходія крутішого за героя.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Я ніколи не впізнав персонажа Історії іграшок у своїх іграшках.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Я ніколи не створював такого персонажа в RPG, як я.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Я ніколи не їв чуро в тематичному парку.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Я ніколи не дивився фільм Діснея тричі поспіль.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Я жодного разу не слухав захоплюючу мелодію Disney протягом цілого тижня.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Я ніколи не дивився фільм тільки через певного актора.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Я ніколи не слухав саундтрек до фільму в режимі повторення годинами.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Я ніколи не показував спойлер фільму і відразу пошкодував про це.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Я ніколи не знайшов друга, який би говорив іншою рідною мовою.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "У мене ніколи не було друга, який би переїхав до іншої країни.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Я ніколи не брав участь у кіномарафоні про Гаррі Поттера на Різдво.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Я ніколи не дивився фільм Marvel до кінця лише через сцену після титрів.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Я ніколи навмисно не дратував NPC (персонаж, який не є гравцем).",
    "Ich habe noch nie einen Nachtzug genommen." to "I've never taken a night train.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Я ніколи не складав онлайн-тест, щоб дізнатися про свій будинок у Гоґвортсі.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Я ніколи не видаляв публікації в соціальних мережах, тому що вони не набрали достатньо лайків.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Я ніколи не називав день у тематичному парку найкращим днем ​​у році.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Я ніколи не був у парку розваг і не залишався там з ранку до вечора.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Я ніколи не виїжджав із атракціонів «Трансформери» чи «Марвел» повністю зачарований.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Я ніколи не кидав гніву, щоб кинути і кинути гру.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Я ніколи не читав великих томів Гаррі Поттера.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Я ніколи не захоплювався моїм улюбленим персонажем серіалу.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Я ніколи не мріяв грати в квідич.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Я ніколи таємно не гуглив, як вирішити складний рівень.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Я ніколи таємно не сподівався, що мій вихованець може говорити, як у Disney.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Я ніколи не видаляв лідера пулу в Sims.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Я ніколи не втрачав орієнтації в 3D-симуляторі.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Я ніколи не грав в університетській спортивній команді.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Я ніколи не чекав у черзі довше двох годин на один атракціон.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Я ніколи не мочив свої цінні речі під час водної прогулянки.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Я ніколи не сперечався з другом про те, який будинок найкращий.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Я ніколи не вдавав, що маю магічні здібності, як Ельза.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Я ніколи не сміявся так сильно, щоб пропустити важливу сцену у фільмі.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Я ніколи не відчував стільки адреналіну, щоб одразу хотілося знову покататися.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Я ніколи не пробував співати з такими тваринами, як Білосніжка.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Я ніколи не мріяв про поїздку в Діснейленд.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Я ніколи не мріяв покататися на водному парку Юрського періоду.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Я ніколи не кричав вголос від переляку в грі.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Я ніколи не плакала над фіналом телешоу.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Я ніколи... не скасовував побачення, щоб залишитися вдома.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Я ніколи... не перефразував повідомлення 10 разів.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Я ніколи... таємно не дивився на мобільний телефон свого партнера.",
    "Ich habe noch nie!" to "Ніколи!",
    "Ich habe!" to "Я маю!",
    "Ich lache viel mit meinem Partner." to "Я багато сміюся зі своїм партнером.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Мені подобається знайомитися з хобі та інтересами мого партнера.",
    "Ich liebe es" to "Мені це подобається",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Я люблю дивитися фільми зі своїм партнером, яких ніхто з нас раніше не бачив.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Я люблю ділитися своєю улюбленою музикою зі своїм партнером.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Мені ніколи не доводилося бігти, щоб встигнути на стикувальний рейс.",
    "Ich plane gerne Dates mit meinem Partner." to "Мені подобається планувати побачення зі своїм партнером.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Я надаю перевагу проведенню часу з партнером, навіть коли я зайнятий.",
    "Ich schreibe meinem Partner jeden Tag." to "Я щодня пишу своєму партнеру.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Мені подобається ділитися мемами та жартами зі своїм партнером.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Мені подобається ділитися всіма подробицями мого дня зі своїм партнером.",
    "Ich würde es nie tun" to "Я б ніколи цього не зробив",
    "Ich übe noch" to "Я все ще тренуюся",
    "Ideen generieren" to "Генеруйте ідеї",
    "Im Haushalt helfen" to "Допомога по дому",
    "In Chat einfügen" to "Додати до чату",
    "In Stille nebeneinander" to "У тиші один біля одного",
    "In den Bergen" to "В горах",
    "In eine Bar gehen" to "Іди в бар",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Йду в бар на пляжі спостерігати захід сонця",
    "In einem feinen Restaurant essen gehen" to "Їжа в чудовому ресторані",
    "In einen Coffeeshop gehen" to "Сходіть до кафе",
    "In einer Beziehung sollte man alles voneinander wissen." to "У стосунках ви повинні знати одне про одного все.",
    "Infinity-Pool" to "Пейзажний басейн",
    "Innenpool" to "Критий басейн",
    "Intelligenz" to "Інтелект",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Інтимні моменти лише тоді, коли їх ініціює ваш партнер",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Код запрошення: HRM-8731 · все розблоковано",
    "Island" to "Ісландія",
    "Ist okay für mich" to "Зі мною все гаразд",
    "Ist schon perfekt" to "Ідеально",
    "Ja, Traditionen einbinden" to "Так, включайте традиції",
    "Ja, absolut" to "Так, точно",
    "Ja, etwas zum Lesen und Aufbewahren" to "Так, щось читати і зберігати",
    "Ja, genug" to "Так, досить",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Так, у захоплюючому місті чи пам’ятці",
    "Ja, in- und auswendig" to "Так, всередині і зовні",
    "Ja, komplett überraschend" to "Так, абсолютно несподівано",
    "Ja, perfekt" to "Так, чудово",
    "Ja, sie gehören zur Familie!" to "Так, вони сім'я!",
    "Ja, sofort teilen" to "Так, поділіться негайно",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Так, ми гарантуємо, що сімейний час буде пріоритетом.",
    "Jacuzzi" to "Джакузі",
    "Jahr zusammen 🎉" to "рік разом 🎉",
    "Jahre zusammen 🎉" to "Роки разом 🎉",
    "Jeder zahlt 50%" to "Кожен платить 50%",
    "Junge" to "Хлопчик",
    "Kamin" to "Камін",
    "Karriere & Erfolg" to "Кар'єра та успіх",
    "Kategorien" to "Категорії",
    "Katze" to "Кот",
    "Keine Musik" to "Без музики",
    "Keine Party nötig, privat halten" to "Немає потреби в вечірці, нехай це буде приватно",
    "Keine Privatsphäre" to "Жодного приватного життя",
    "Keine Treffer gefunden" to "Збігів не знайдено",
    "Keiner" to "Жодного",
    "Keiner von uns" to "Ніхто з нас",
    "Kennst du die Essensvorlieben deines Partners?" to "Чи знаєте ви харчові уподобання свого партнера?",
    "Kino" to "кіно",
    "Kirchlich" to "Церковний",
    "Klassisch Solitär" to "Класичний пасьянс",
    "Klassisch gebunden" to "У класичній палітурці",
    "Klein & zart" to "Маленький і делікатний",
    "Kleine Geschenke" to "Маленькі подарунки",
    "Kleine Runde" to "Маленький круглий",
    "Kochen und Freunde einladen" to "Готуйте і запрошуйте друзів",
    "Kochkurs" to "Кулінарний клас",
    "Kommt auf den Tag an" to "Залежить від дня",
    "Kommt darauf an" to "Це залежить",
    "Kommt drauf an" to "Це залежить",
    "Kommt mit" to "Ходімо зі мною",
    "Konzert" to "Концерт",
    "Kräftige Farben" to "Яскраві кольори",
    "Kräuterbeet" to "Трав'яна грядка",
    "Kultur & Sehenswürdigkeiten" to "Культура та пам'ятки",
    "Kuscheln" to "Обійми",
    "Kuss senden" to "Надішліть поцілунок",
    "Körperliche Annäherung" to "Фізичний підхід",
    "Körperliche Nähe" to "Фізична близькість",
    "Küche" to "Кухня",
    "Land" to "Країна",
    "Landhaus" to "Заміський будинок",
    "Landhausstil" to "Стиль сільського будинку",
    "Lange wach bleiben" to "Залишайся допізна",
    "Lappland" to "Лапландія",
    "Lappland, Finnland" to "Лапландія, Фінляндія",
    "Las Vegas" to "Лас-Вегас",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Дозвольте своєму партнеру надихнути вас бути найкращим собою",
    "Lehne ab" to "Відхилитися",
    "Leichtigkeit" to "Легкість",
    "Leidenschaft" to "Пристрасть",
    "Liebe im Gleichgewicht" to "Любов у балансі",
    "Liebe sie, macht mehr Spaß" to "Любіть їх, веселіше",
    "Lieber durchgeplant oder spontan?" to "Ви б віддали перевагу, щоб це було сплановано чи спонтанно?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Ти віддаєш перевагу спокійному вечору вдвох чи з людьми?",
    "Lieber nicht" to "Краще ні",
    "Lieber vorher grob absprechen" to "Краще все приблизно обговорити заздалегідь",
    "Lokal einkaufen" to "Купуйте на місці",
    "London" to "Лондон",
    "London, England" to "Лондон, Англія",
    "Lügen" to "Брехня",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Ви віддаєте перевагу публічну чи приватну пропозицію?",
    "Malediven" to "Мальдіви",
    "Man sollte nie streitend einschlafen." to "Ви ніколи не повинні засинати, сварячись.",
    "Mango Sorbet" to "Сорбет з манго",
    "Markant & breit" to "Яскравий і широкий",
    "Marken & Alltag" to "Бренди та повсякденне життя",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "Середземноморський дворик",
    "Mehr Unterstützung" to "Більше підтримки",
    "Mehr gemeinsame Zeit" to "Більше часу разом",
    "Mehr zuhören" to "Слухай далі",
    "Mehrgenerationenhaus" to "Будинок багатьох поколінь",
    "Mein Arbeitsplatz" to "Моє робоче місце",
    "Mein Partner" to "Мій партнер",
    "Mich überraschen" to "Здивуйте мене",
    "Minimalistisches Interieur" to "Мінімалістичний інтер'єр",
    "Missverständnisse" to "Непорозуміння",
    "Mit Familie und engen Freunden" to "З родиною та близькими друзями",
    "Mit Kompromissen" to "З компромісами",
    "Mitgefühl" to "Співчуття",
    "Mittelweg mit besonderen Details" to "Середина з особливими деталями",
    "Modern geometrisch" to "Сучасна геометрична",
    "Moderne Grillstation" to "Сучасна гриль-станція",
    "Moderner Name" to "Сучасна назва",
    "Moderner Solitär" to "Сучасний пасьянс",
    "Moissanit" to "Муасаніт",
    "Moment festhalten" to "Ловіть момент",
    "Momente" to "моменти",
    "Monaco" to "Монако",
    "Moralische Werte" to "Моральні цінності",
    "Museum" to "музей",
    "Musik" to "музика",
    "Mut" to "мужність",
    "Mädchen" to "дівчина",
    "Möbelhaus" to "Меблевий магазин",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Ви справді хочете залишити вікторину? Ваш попередній прогрес залишається збереженим.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Чи бажаєте ви, щоб домашні тварини були включені в додаток?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Хочете, щоб цей момент миттєво поділився в соціальних мережах?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Можливо, нам знадобиться заощадити",
    "Müssen es planen" to "Це потрібно спланувати",
    "Müssen sparen" to "Потрібно зберегти",
    "Nachricht an" to "Повідомлення",
    "Name Partnerin" to "Ім'я партнера",
    "Namen und Startdatum eurer Beziehung." to "Імена та дата початку ваших стосунків.",
    "Natursteinfassade" to "Фасад з натурального каменю",
    "Naturteich" to "Природний ставок",
    "Nein, einfach halten" to "Ні, просто потримай",
    "Nein, erstmal privat halten" to "Ні, поки що залишити це приватним",
    "Nein, lieber vor Ort" to "Ні, краще на місці",
    "Nein, modern halten" to "Ні, залишайся сучасним",
    "Nein, nur wir" to "Ні, тільки ми",
    "Nein, zu ablenkend" to "Ні, надто відволікає",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Новобудова з розумним будинком",
    "Neubau mit Technik" to "Новобудова з технікою",
    "Neue Liebe, neue Erfahrungen" to "Нове кохання, нові враження",
    "Neues Hobby" to "Нове хобі",
    "Neues Spiel" to "Нова гра",
    "Neugier" to "Цікавість",
    "New York" to "Нью-Йорк",
    "New York, USA" to "Нью-Йорк, США",
    "Nicht mein Fall" to "Не моя чашка чаю",
    "Nicht nötig, lieber klassisch bleiben" to "Не обов'язково, краще залишитися класичним",
    "Nichts — es passt so" to "Нічого - підходить",
    "Nie wieder Burger" to "Ніколи більше бургерів",
    "Nie wieder Pizza" to "Ніколи більше піца",
    "Niemand" to "Ніхто",
    "Niemand ohne Plan" to "Ніхто без плану",
    "Nike" to "Nike",
    "Nizza" to "Гарно",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Ще немає моментів.\nЗробіть свій перший досвід 💞",
    "Nur bei wichtigen Themen" to "Тільки для важливих тем",
    "Nur wir beide" to "Тільки ми двоє",
    "Nähe & Intimität" to "Близькість і інтимність",
    "Obstgarten" to "Фруктовий сад",
    "Oder" to "Або",
    "Offene Küche" to "Відкрита кухня",
    "Offene Wohnküche" to "Відкрита кухня/вітальня",
    "Ohne Stein" to "Без каменю",
    "Open End" to "Відкритий фінал",
    "Outdoor-Küche" to "Летня кухня",
    "Outdoor-Sofa" to "Розкладний диван",
    "Outdoor-Whirlpool" to "Відкрита джакузі",
    "Ovaler Diamant" to "Діамант овальної форми",
    "Paar" to "Пара",
    "Paar-Statistiken" to "Статистика пари",
    "Paris" to "Париж",
    "Paris, Frankreich" to "Париж, Франція",
    "Partner" to "Партнер",
    "Partner-Simulator" to "Симулятор партнера",
    "Partnerin" to "Партнер",
    "Party Edition" to "Party Edition",
    "Party Edition II" to "Party Edition II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Чи вписується тварина в наше повсякденне життя?",
    "Pasta" to "Макарони",
    "Pastell" to "Пастель",
    "Penthouse mit Ausblick" to "Пентхаус з видом",
    "Pepsi" to "Пепсі",
    "Pergola mit Lounge" to "Пергола з кімнатою відпочинку",
    "Pfingstrosen" to "Півонії",
    "Pinguin" to "Пінгвін",
    "Pistazie" to "Фісташка",
    "Pizza" to "Піца",
    "Pizzaofen" to "Піч для піци",
    "Platin" to "Платина",
    "PlayStation" to "PlayStation",
    "Pool" to "Басейн",
    "Pop" to "Поп",
    "Prasselnder Kamin" to "Горить камін",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Принцеси, пірати та казковий пил: вікторина Disney",
    "Privater Innenhof" to "Власний двір",
    "Profil" to "Профіль",
    "Profil bearbeiten" to "Редагувати профіль",
    "Prozentual nach Einkommen" to "Відсоток на основі доходу",
    "Quiz verlassen" to "Вийти з тесту",
    "Quiz verlassen?" to "Вийти з тесту?",
    "Rausgehen in die Natur" to "Вирушайте на природу",
    "Reden vor ..." to "Розмовляючи з...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Призначайте регулярні дати або час разом",
    "Reisen" to "Подорож",
    "Reiseziele" to "Напрямки подорожей",
    "Respektlosigkeit" to "Неповага",
    "Restaurant" to "Ресторан",
    "RnB / Soul" to "RnB / Соул",
    "Rock" to "Рок",
    "Rom" to "Рим",
    "Rom, Italien" to "Рим, Італія",
    "Romantik" to "Романтика",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Романтичні жести, такі як повідомлення, нотатки чи подарунки, роблять мене щасливим.",
    "Romantische Stimmung" to "Романтичний настрій",
    "Roségold" to "Рожеве золото",
    "Ruhig zu zweit" to "Тиша для двох",
    "Runder Diamant" to "Круглий діамант",
    "Salted Caramel" to "Солона карамель",
    "Sammle Ideen..." to "Зберіть ідеї...",
    "Santorini" to "Санторіні",
    "Santorini, Griechenland" to "Санторіні, Греція",
    "Saphir" to "Сапфір",
    "Saunahaus" to "Сауна",
    "Schickes Restaurant oder Hotel" to "Шикарний ресторан чи готель",
    "Schlafzimmer" to "Спальня",
    "Schließen" to "Закрити",
    "Schmal & zart" to "Тонкий і ніжний",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Кадри з нашої історії кохання",
    "Schokolade" to "Шоколад",
    "Schreib frei, was dir wirklich dazu einfällt." to "Пишіть вільно те, що справді спадає на думку.",
    "Schreibe deine eigene Antwort" to "Напишіть власну відповідь",
    "Sehr gerne" to "Ні за що",
    "Sehr leicht" to "Дуже легкий",
    "Sehr wichtig — Fotos und Video" to "Дуже важливо — фото та відео",
    "Sehr wichtig, es sollte persönlich sein" to "Дуже важливо, це має бути особистим",
    "Selbst kochen" to "Готуйте самі",
    "Senden" to "Надіслати",
    "Separate Küche" to "Окрема кухня",
    "Serie schauen" to "Дивіться серіал",
    "Serienmarathon auf dem Sofa" to "Серіал Марафон на дивані",
    "Sex & Liebe" to "Секс і кохання",
    "Seychellen" to "Сейшельські острови",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Чи можемо ми покрити всі витрати на одну дитину/кількох дітей? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Чи має пропозиція бути сюрпризом?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Чи має програма містити культурні чи традиційні елементи?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Чи має додаток містити культурні чи традиційні елементи?",
    "Sommerhochzeit" to "Літнє весілля",
    "Sonnige Dachterrasse" to "Сонячна тераса на даху",
    "Sowohl als auch" to "І та, і",
    "Spazieren" to "Прогуляйтеся",
    "Spaß & Abenteuer" to "Розваги та пригоди",
    "Speichern" to "Зберегти",
    "Spiel bearbeiten" to "Редагувати гру",
    "Spielbereich für Kinder" to "Ігрова зона для дітей",
    "Spiele" to "Ігри",
    "Spiele spielen und Spaß haben" to "Грайте в ігри та розважайтеся",
    "Spontan" to "Спонтанно",
    "Sportplatz" to "Спортмайданчик",
    "Spotify" to "Spotify",
    "Sprache" to "Мова",
    "Stadt" to "Місто",
    "Stadt oder Land — was ist uns wichtiger?" to "Місто чи країна – що для нас важливіше?",
    "Stadtvilla" to "Міська вілла",
    "Standesamt & Party" to "ЗАГС & вечірка",
    "Statement-Ring" to "Виразна каблучка",
    "Stilvolles Outdoor-Sofa" to "Стильний вуличний диван",
    "Stimme voll zu" to "Цілком згоден",
    "Stimmt" to "Так",
    "Stimmt nicht" to "Неправда",
    "Stimmt, noch nie" to "Правда, ніколи",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Пляжний день",
    "Streit über Haushalt" to "Побутова суперечка",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "Постійно",
    "Suche schließen" to "Закрити пошук",
    "Suche zurücksetzen" to "Скинути пошук",
    "Suche öffnen" to "Відкрити пошук",
    "Suchergebnisse" to "Результати пошуку",
    "Sushi" to "Суші",
    "Süß" to "Мило",
    "Tage zusammen 💞" to "дні разом 💞",
    "Tauche ins Unterbewusstsein" to "Пориньте в підсвідомість",
    "Teile alle deine Hobbys mit deinem Partner" to "Поділіться всіма своїми захопленнями зі своїм партнером",
    "Teils teils" to "Частково частково",
    "Testen" to "Тест",
    "Themen" to "Теми",
    "Tiefe Gespräche" to "Глибокі розмови",
    "Tiefgründige Gespräche führen" to "Ведіть глибокі розмови",
    "Tierpension" to "Пансіонат для тварин",
    "Tiny House" to "Крихітний будинок",
    "Tippen zum Auswählen & Scrollen" to "Торкніться, щоб вибрати та прокрутити",
    "Tippen zum Zuklappen" to "Торкніться, щоб згорнути",
    "Titel" to "Назва",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Назва, категорія, тема, теги, запитання...",
    "Tokyo, Japan" to "Токіо, Японія",
    "Traditioneller Name" to "Традиційна назва",
    "Traumhaus Außenbereich" to "Будинок мрії відкритий майданчик",
    "Traumhochzeit" to "Весілля мрії",
    "Treffer" to "Хіт",
    "Tägliche Aktivität" to "Щоденна активність",
    "Umformulieren" to "Перефразуйте",
    "Unbeantwortet" to "Без відповіді",
    "Unbeliebte Meinungen" to "Непопулярні думки",
    "Universal Studios Genie oder Neuling?" to "Геній Universal Studios чи новачок?",
    "Uns auseinanderzuleben" to "Розростатися",
    "Unser Intimleben" to "Наше інтимне життя",
    "Unser Traumhaus" to "Будинок нашої мрії",
    "Unser erstes Treffen" to "Наша перша зустріч",
    "Unsere Gesichter" to "Наші обличчя",
    "Unsere eigenen Träume" to "Наші власні мрії",
    "Unsere nächste Reise" to "Наша наступна подорож",
    "Unter 1000" to "Менше 1000",
    "Unter 1000 im Monat" to "Менше 1000 на місяць",
    "Unter 50€/Monat" to "Менше 50 євро/місяць",
    "Unter Leuten" to "Серед людей",
    "Untreue" to "Невірність",
    "Urlaub" to "Канікули",
    "Vanille" to "Ваніль",
    "Venedig" to "Венеція",
    "Venedig, Italien" to "Венеція, Італія",
    "Verbinde dich mit" to "Підключитися до",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Підключіться до \${profile.partnerName}, щоб побачити відповідь",
    "Verbindung" to "підключення",
    "Verbringe die Feiertage mit deiner Familie" to "Проведіть свята з родиною",
    "Verlobungsringe" to "Обручки",
    "Vertrautheit" to "Знайомство",
    "Viel getrennt" to "Багато розлуки",
    "Vielleicht ein oder zwei" to "Можливо один чи два",
    "Vielleicht, aber mündlich reicht" to "Можливо, але усно достатньо",
    "Vielleicht, wenn es machbar ist" to "Можливо, якщо це можливо",
    "Vielleicht, wenn es passt" to "Можливо, якщо підходить",
    "Vintage Art déco" to "Вінтажний арт-деко",
    "Vintage verspielt" to "Вінтажний грайливий",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Знайомство вашого партнера з новими захопленнями",
    "Vor dem Kauf eines Hauses besprechen" to "Обговоріть перед покупкою будинку",
    "Vor der Anschaffung eines Haustiers besprechen" to "Обговоріть перед покупкою домашньої тварини",
    "Vor der gemeinsamen Reise besprechen" to "Обговоріть перед спільною подорожжю",
    "Vor nichts" to "Нічого",
    "Vorort" to "Передмістя",
    "Walnuss" to "Горіх",
    "Wandern" to "Піші прогулянки",
    "Wann fühlst du dich mir am nächsten?" to "Коли ти відчуваєш мене ближче?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Коли ти відчуваєш себе фізично найближчим до мене?",
    "Was bedeutet Vertrauen für dich konkret?" to "Що конкретно для вас означає довіра?",
    "Was entspannt dich mehr?" to "Що вас більше розслабляє?",
    "Was fehlt dir über die Distanz am meisten?" to "Чого тобі найбільше не вистачає на відстані?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Що вам найбільше подобається у вашому домі?",
    "Was hast du von deinem Partner gelernt?" to "Чого ви навчилися у свого партнера?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Що ви думаєте про спільний перегляд еротичного контенту?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Що ви думаєте про реквізит (наприклад, знаки, повітряні кулі тощо)?",
    "Was ist das Wichtigste beim Antrag?" to "Що найважливіше при подачі заявки?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Що є найважливішим для вас у сексуальних стосунках?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Яка наша улюблена фотографія? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Чого ти найбільше боїшся щодо спільного життя?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Яку їжу ви любите, але ваш партнер не може зрозуміти?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Що для вас є абсолютним перешкодою?",
    "Was ist für jeden von uns das absolute Highlight?" to "Що є головним для кожного з нас?",
    "Was ist passiert?" to "Що сталося?",
    "Was macht einen Moment für dich romantisch?" to "Що робить момент романтичним для вас?",
    "Was magst du an deinem Partner am liebsten?" to "Що вам найбільше подобається у вашому партнері?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Що тобі більше подобається: рано вставати чи пізно спати?",
    "Was magst du lieber?" to "Що тобі більше подобається?",
    "Was möchtest du eigentlich sagen?" to "Що ти насправді хочеш сказати?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Що б ви хотіли, щоб ваш партнер робив частіше?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Що відбувається з твариною, коли ми подорожуємо?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Що буде з нашою дитиною, коли вона виросте?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Чого ми ніколи не повинні випускати з уваги як батьки?",
    "Was war dein schönster Moment mit mir bisher?" to "Який момент зі мною був найкращим?",
    "Was wir gegessen haben" to "Що ми їли",
    "Was wollt ihr nie vergessen?" to "Що ти ніколи не хочеш забувати?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Що для вас було б гірше: більше ніколи не їсти піцу чи більше ніколи не брати гамбургерів?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Що б ти найбільше хотів робити в один день разом?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Що б ви негайно змінили, якби гроші не були проблемою?",
    "Weiter" to "Далі",
    "Weiter spielen" to "Продовжуйте грати",
    "Weiß ich noch nicht" to "Я ще не знаю",
    "Weiße Rosen" to "Білі троянди",
    "Weißgold" to "Біле золото",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Яку якість неодмінно повинна отримати від нас наша дитина?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Яке середовище ви хотіли б отримати для пропозиції?",
    "Welcher Raum sagt am meisten über dich aus?" to "Яка кімната говорить про вас найбільше?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Який бюджет ми плануємо на харчування та ветеринара?",
    "Welches Lied macht dich an? 🥵" to "Яка пісня тебе збуджує? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Яка спільна фотографія вам подобається?",
    "Wellnessbad" to "Оздоровча ванна",
    "Wenn es schwierig ist" to "Коли все важко",
    "Wenn ich müde bin" to "Коли я втомився",
    "Wenn wir uns lange umarmen" to "Коли ми довго обіймаємося",
    "Wenn wir zusammen lachen" to "Коли ми сміємося разом",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Хто швидше вирішує, що замовити?",
    "Wer findet die besten Restaurants?" to "Хто знаходить найкращі ресторани?",
    "Wer gibt mehr Herzlichkeit?" to "Хто дарує більше тепла?",
    "Wer hat den besseren Musikgeschmack?" to "Хто має кращий музичний смак?",
    "Wer hängt mehr an seinen Eltern?" to "Хто більше прив'язаний до своїх батьків?",
    "Wer ist besser organisiert?" to "Хто краще організований?",
    "Wer ist der Beste bei der Filmauswahl?" to "Хто найкраще обирає фільми?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Хто найкраще планує романтичні побачення?",
    "Wer ist der beste Tänzer?" to "Хто найкращий танцюрист?",
    "Wer ist romantischer?" to "Хто романтичніший?",
    "Wer kocht besser?" to "Хто готує краще?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Хто займається ремонтом та обслуговуванням?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Хто швидше помічає, коли іншій людині погано?",
    "Wer sucht am Ende wirklich den Film aus?" to "Хто врешті-решт обирає фільм?",
    "Wer vergisst eher einen Jahrestag?" to "Хто швидше забуде річницю?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Хто з більшою ймовірністю забуде своє ім’я наступного ранку?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Хто, швидше за все, наступного дня знайде відео, про яке нічого не знає?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Хто краще проведе ніч на чужому дивані?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Хто, швидше за все, засне на вечірці та прокинеться з шарпі на обличчі?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Хто з більшою ймовірністю послизнеться на танцполі, але зробить це крутим кроком?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Хто, швидше за все, візьме під контроль список відтворення Spotify на домашній вечірці?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Хто з більшою ймовірністю замовить піцу для всіх на вечірці та з’їсть її сам?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Хто з більшою ймовірністю засне першим на вечірці?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Хто з більшою ймовірністю раптово почне прибирати на вечірці?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Хто з більшою ймовірністю стверджуватиме, що він абсолютно тверезий, коли все навпаки?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Хто, швидше за все, поступиться першим у суперечці?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Хто, швидше за все, шахраюватиме в грі з випивкою?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Хто з більшою ймовірністю нападе на буфет і таємно принесе їжу додому?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Хто, швидше за все, опублікує у своїй історії найнезручніше фото вечора?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Хто з більшою ймовірністю буде дратувати ді-джея, вимагаючи його улюбленої пісні?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Хто з більшою ймовірністю заспіває текст пісні без тональності, але переконано?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Хто з більшою ймовірністю замовить найдорожчий напій у меню і пошкодує про це?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Хто з більшою ймовірністю запросив би сусідів, якби вони скаржилися на шум?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Хто сприйме вечірні ігри (наприклад, Beer Pong) надто серйозно?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Хто з більшою ймовірністю подружиться з вишибалами, щоб отримати VIP-доступ?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Хто з більшою ймовірністю розпочне спонтанний караоке-батл?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Хто, швидше за все, відкриє пляшку без відкривачки?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Хто з більшою ймовірністю виголосив би промову, навіть якщо про це ніхто не просив?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Хто, швидше за все, проведе годину у ванній, роблячи селфі?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Хто з більшою ймовірністю влаштує ганебний танцювальний виступ і відсвяткує це?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Хто швидше зателефонує колишньому партнеру після вечірки?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Хто з більшою ймовірністю випадково образить незнайомого гостя?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Хто, швидше за все, таємно покине вечірку, не попрощавшись?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Кому краще погратися з домашнім улюбленцем господаря, ніж поговорити з гостями?",
    "Wer würde eher spontan eine Reise buchen?" to "Хто з більшою ймовірністю забронює подорож спонтанно?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Хто з більшою ймовірністю буде вести глибокі розмови на кухні годинами?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Хто, швидше за все, випадково вип’є чужий напій?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Хто, швидше за все, випадково перекине дорогу вазу чи щось крихке?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Хто з більшою ймовірністю спробує сам змішати складний коктейль і зазнає невдачі?",
    "Wer würde eher zu spät kommen?" to "Хто швидше запізниться?",
    "Wer würde eher?" to "Кому краще?",
    "Wer übernimmt die tägliche Versorgung?" to "Хто піклується про щоденний догляд?",
    "Werde so akzeptiert, wie du bist" to "Будьте прийняті такими, які ви є",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Чи вистачить нам часу на дитину/дітей? ⏳",
    "Whirlpool" to "Гідромасажна ванна",
    "White Chocolate" to "Білий шоколад",
    "Widgets" to "Віджети",
    "Wie fühlst du dich am meisten geliebt?" to "Як ти почуваєшся, що тебе найбільше люблять?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Як нам бути з різними доходами?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Який найкращий спосіб для вашого партнера розпочати з вами секс?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Як ваш партнер може бути ще кращим партнером для вас?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Скільки часу після пропозиції ти хочеш святкувати з іншими?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Принаймні як довго ми хочемо там залишатися?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Наскільки легко тобі говорити про бажання?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Яким би ви хотіли бачити наше майбутнє?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Як виглядає ваша ідеальна неділя вдома?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Як ти ставишся до лихослів'я під час сексу?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Скільки кредитів ми реально можемо собі дозволити?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Скільки часу ми хочемо проводити окремо?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Скільки ми хочемо витратити загалом?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Як ми знайдемо час для наших стосунків, коли народиться дитина?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Наскільки для вас важливо, щоб момент був зафіксований?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Наскільки для вас важливо, щоб програма відображала ваші хобі чи інтереси?",
    "Wie würdest du sie/ihn nennen?" to "Як би ти назвав його/її?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Який твій улюблений спосіб проявити прихильність поза сексом?",
    "Wildblumen" to "Польові квіти",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Ти хочеш дівчинку чи хлопчика? 👶",
    "Wintergarten" to "Зимовий сад",
    "Winterhochzeit" to "Зимове весілля",
    "Wir bestellen einfach beides" to "Ми просто замовляємо обидва",
    "Wir brauchen ewig" to "Це забере нас назавжди",
    "Wir einigen uns nie" to "Ми ніколи не погоджуємось",
    "Wir entscheiden es gemeinsam" to "Вирішуємо разом",
    "Wir treffen uns in der Mitte" to "Ми зустрічаємось посередині",
    "Wir wechseln uns ab" to "Ми по черзі",
    "Wird stressig" to "Становиться стресом",
    "Wobei lachst du am meisten?" to "Що змушує вас смітися найбільше?",
    "Wofür sparen wir gemeinsam?" to "На що ми збираємося разом?",
    "Wohnzimmer" to "Вітальня",
    "Woran erinnerst du dich am lebhaftesten?" to "Що запам'яталося найяскравіше?",
    "Worauf freust du dich bei uns am meisten?" to "Чого ви найбільше чекаєте з нами?",
    "Worte/Komplimente" to "Слова/Компліменти",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Чого ти найбільше боїшся в наших стосунках?",
    "Wünsche? z.B. günstig, draußen" to "Бажання? напр. дешево, ззовні",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Чи хотіли б ви зробити пропозицію у відпустці (зокрема подорожі)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "YouTube Music",
    "Zeichne für mich" to "Намалюй для мене",
    "Zeichne mich als Tier — welches wäre ich?" to "Намалюй мене твариною - ким би я був?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Намалюйте наші почуття один до одного як символ.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Намалюйте будинок нашої мрії в одну лінію. Що найбільше вражає?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Намалюй наше перше побачення - що обов'язково повинно бути на картинці?",
    "Zeichnen" to "Нічия",
    "Zeit füreinander" to "Час один для одного",
    "Zeit, wenn das Baby schläft" to "Час, коли дитина спить",
    "Zelten gehen" to "Ідіть у похід",
    "Zitrone" to "Лимон",
    "Zu Hause, gemütlich und privat" to "Вдома, затишно та приватно",
    "Zu einem Picknick gehen" to "Збираюся на пікнік",
    "Zu einem ausgefallenen Abendessen gehen" to "Збираюся на шикарну вечерю",
    "Zu zweit reisen" to "Подорожуй удвох",
    "Zuhause & Alltag" to "Дім і побут",
    "Zuhören" to "Слухай",
    "Zurück" to "Назад",
    "Zusammen seit" to "Разом з тих пір",
    "Zusammen seit (TT.MM.JJJJ)" to "Разом з (ДД.ММ.РРРР)",
    "Zusammenziehen" to "Контракт",
    "Zustimmen oder Ablehnen" to "Погоджуюсь чи не погоджуюсь",
    "Zwei Kreise, die sich überschneiden" to "Два кола, які перекриваються",
    "Zwei Stühle davor" to "Два стільці перед ним",
    "Zärtlich sein" to "Будь ніжною",
    "Öfter als ich zugebe" to "Більше разів, ніж я визнаю",
    "Über 100€/Monat" to "Понад 100 євро/місяць",
    "Über 2000 im Monat" to "Понад 2000 на місяць",
    "Über mich selbst" to "Про себе",
    "Übernehmen" to "Застосувати",
    "Überraschend" to "Дивно",
    "Überraschung" to "Сюрприз",
    "Überspringen" to "Пропустити",
    "Übertrieben und großartig" to "Неперевершено та приголомшливо",
    "✎ Tippe, um zu antworten" to "✎ Торкніться, щоб відповісти",
    "✨ GFK-Brücke" to "✨ GRP міст",
)

internal fun localizeUkrainianDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_UKRAINIAN_CONTENT)
