package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_URDU_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 سال",
    "1000 - 1500 im Monat" to "1000 - 1500 فی مہینہ",
    "1000 bis 3000" to "1000 سے 3000 تک",
    "1500 - 2000 im Monat" to "1500 - 2000 فی مہینہ",
    "3000 bis 5000" to "3000 سے 5000",
    "5-10 Jahre" to "5-10 سال",
    "50-100€/Monat" to "50-100€/ماہ",
    "Ab 100€" to "100€ سے",
    "Ab 500€" to "500€ سے",
    "Ab 50€" to "50€ سے",
    "Ab und zu" to "ہر وقت اور پھر",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "خریداری کرنے سے پہلے ہمیں کتنا خرچ کرنا ہوگا؟",
    "Abbrechen" to "منسوخ کریں۔",
    "Abenteuer" to "ایڈونچر",
    "Adidas" to "ایڈیڈاس",
    "Aktivitäten" to "سرگرمیاں",
    "Alle" to "سبھی",
    "Alle Pakete" to "تمام پیکیجز",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "اپنے بہترین دوست کے علاوہ اپنے تمام دوستوں کو کھو دیں۔",
    "Alle intimen Momente selbst initiieren" to "تمام مباشرت لمحات خود شروع کریں۔",
    "Alles davon" to "یہ سب",
    "Alles, was noch kommt" to "ہر وہ چیز جو آنے والی ہے۔",
    "Alltagsroutine" to "روزمرہ کا معمول",
    "Alltägliche Berührungen" to "ہر روز چھوتا ہے۔",
    "Altbau mit Charme" to "دلکش پرانی عمارت",
    "Am Strand" to "ساحل سمندر پر",
    "Am liebsten alles zusammen" to "ترجیحا سب کچھ ایک ساتھ",
    "Am selben Tag mit Freunden/Familie" to "ایک ہی دن دوستوں/خاندان کے ساتھ",
    "Amazon" to "ایمیزون",
    "Amsterdam" to "ایمسٹرڈیم",
    "Amsterdam, Niederlande" to "ایمسٹرڈیم، نیدرلینڈز",
    "An das Gefühl" to "احساس کا",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "ایک عوامی جگہ پر جہاں بہت سے تماشائی ہوں۔",
    "An einen Geruch" to "ایک بو کی",
    "An einen Song" to "ایک گانے کے لیے",
    "An etwas, das ich gesagt habe" to "کچھ میں نے کہا",
    "Analyse starten" to "تجزیہ شروع کریں۔",
    "Analysiere eure Muster..." to "اپنے پیٹرن کا تجزیہ کریں...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Gottman اور GFK کے مطابق اپنے جوابات اور چیٹس کا تجزیہ کریں۔",
    "Ananas auf der Pizza schmeckt köstlich." to "پیزا پر انناس کا ذائقہ مزیدار ہوتا ہے۔",
    "Android" to "Android",
    "Antwort mit einem Foto" to "تصویر کے ساتھ جواب دیں۔",
    "Antwortähnlichkeit" to "جواب میں مماثلت",
    "App-Sprache auswählen" to "ایپ کی زبان منتخب کریں۔",
    "Auf eine Bootsparty gehen" to "بوٹ پارٹی میں جانا",
    "Aufmerksamkeit" to "توجہ",
    "Aufräumen und Projekte angehen" to "منصوبوں کو صاف اور نمٹائیں۔",
    "Aufwärmen" to "وارم اپ",
    "Aufwärmen: Einander kennenlernen" to "وارم اپ: ایک دوسرے کو جاننا",
    "Aus dem Urlaub" to "چھٹیوں سے",
    "Ausgefallener Name" to "فینسی نام",
    "Ausschlafen und faulenzen" to "اندر سوئیں اور آس پاس آرام کریں۔",
    "Ausschlafen und nichts tun" to "اندر سوئیں اور کچھ نہ کریں۔",
    "Aussehen" to "ظاہری شکل",
    "Auto" to "آٹو",
    "Außenkamin" to "بیرونی چمنی",
    "BEANTWORTE" to "جواب",
    "Bali" to "بالی",
    "Bali, Indonesien" to "بالی، انڈونیشیا",
    "Banane" to "کیلا",
    "Beantwortet" to "جواب دیا گیا۔",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "ایک ہی وقت میں سوالات کے جوابات دیں — جوابات تب تک نظر نہیں آئیں گے جب تک کہ آپ دونوں ختم نہ کر لیں۔",
    "Beantwortete Fragen" to "سوالات کے جوابات",
    "Bearbeiten" to "ترمیم کریں۔",
    "Bei Insider-Witzen" to "اندرونی لطیفوں کے لیے",
    "Bei Memes" to "میمز پر",
    "Bei einer spontanen Berührung" to "جب بے ساختہ چھو لیا جائے۔",
    "Beide" to "دونوں",
    "Beide gleich" to "دونوں ایک جیسے ہیں۔",
    "Beide zusammen" to "دونوں ایک ساتھ",
    "Beide, aber wir tun so als ob nicht" to "دونوں، لیکن ہم دکھاوا نہیں کرتے",
    "Beides" to "دونوں",
    "Beides wäre schlimm" to "دونوں خراب ہوں گے۔",
    "Beim Einschlafen nebeneinander" to "ایک دوسرے کے ساتھ سو جانا",
    "Beim Reden" to "بات کرتے ہوئے",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "مشہور سیاحتی مقامات ہمیشہ مایوسی کا شکار ہوتے ہیں۔",
    "Beschreibe unser Sexleben mit einem Emoji." to "ایک ایموجی کے ساتھ ہماری جنسی زندگی کو بیان کریں۔",
    "Besser kommunizieren" to "بہتر بات چیت کریں۔",
    "Bessere Lage" to "بہتر مقام",
    "Bestellen" to "آرڈر",
    "Besuchte Länder" to "ممالک کا دورہ کیا گیا۔",
    "Besuchte Städte" to "شہروں کا دورہ کیا۔",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "کیا آپ ایک غیر معمولی تجویز کو ترجیح دیتے ہیں یا کوئی لطیف چیز؟",
    "Beziehung" to "رشتہ",
    "Bibliothek" to "لائبریری",
    "Bin manchmal unsicher" to "میں بعض اوقات غیر محفوظ ہو جاتا ہوں۔",
    "Bist du ein Videospiel-Guru?" to "کیا آپ ویڈیو گیم کے گرو ہیں؟",
    "Blumenwiese" to "پھولوں کا میدان",
    "Bunte Blumenwiese" to "رنگین پھولوں کا میدان",
    "Burger" to "برگر",
    "Burger King" to "برگر کنگ",
    "Chat" to "چیٹ",
    "Coca-Cola" to "کوکا کولا",
    "Cookie Dough" to "کوکی آٹا",
    "Dachgarten mit Lounge" to "لاؤنج کے ساتھ چھت کا باغ",
    "Dachterrasse" to "چھت کی چھت",
    "Das Wetter an dem Tag" to "اس دن کا موسم",
    "Das erste Selfie" to "پہلی سیلفی",
    "Das meiste weiß ich" to "میں اس میں سے زیادہ تر جانتا ہوں۔",
    "Das oder das?" to "یہ یا وہ؟",
    "Das tägliche Leben" to "روزمرہ کی زندگی",
    "Dass Zusagen gehalten werden" to "وہ وعدے پورے ہوتے ہیں۔",
    "Dass alles meinen Stil hat" to "کہ ہر چیز کا میرا انداز ہے۔",
    "Dass ich alles erzählen kann" to "کہ میں سب کچھ بتا سکتا ہوں۔",
    "Dass ich mich nicht sorgen muss" to "کہ مجھے پریشان ہونے کی ضرورت نہیں ہے۔",
    "Dass wir ungestört sind" to "کہ ہم پریشان نہیں ہیں۔",
    "Dein Name" to "آپ کا نام",
    "Deine Antwort..." to "آپ کا جواب...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "آپ کے جوابات محفوظ ہیں۔ جیسے ہی پارٹنر پیکج مکمل کرے گا، دونوں جوابات ایک ساتھ نظر آئیں گے۔",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "آپ کے جوابات محفوظ ہیں۔ ایک بار جب \${profile.partnerName} پیکج مکمل کر لیتا ہے، دونوں جوابات ایک ساتھ نظر آئیں گے۔",
    "Deine Beziehung abenteuerlich und spontan machen" to "اپنے تعلقات کو مہم جوئی اور بے ساختہ بنائیں",
    "Deine Beziehung stabil und sicher machen" to "اپنے تعلقات کو مستحکم اور محفوظ بنائیں",
    "Deine eigene Antwort" to "آپ کا اپنا جواب",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "اپنے ساتھی کے ساتھ اپنے گہرے رازوں کو شیئر کرنا بہتر ہے۔",
    "Deinen besten Freund verlieren" to "اپنے بہترین دوست کو کھونا",
    "Denke an dich" to "اپنے بارے میں سوچو",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "ایک ہی فلم کو دو بار دیکھنا وقت کا ضیاع ہے۔",
    "Der Blick nach draußen" to "باہر کا منظر",
    "Der Garten" to "باغ",
    "Der Ort" to "جگہ",
    "Der Ring und die Geste" to "انگوٹھی اور اشارہ",
    "Der perfekte Heiratsantrag" to "شادی کی کامل تجویز",
    "Derjenige sein, der umarmt wird" to "گلے ملنے والے بنیں۔",
    "Deutsch" to "جرمن",
    "Diamant" to "ہیرا",
    "Diamanten im Band" to "بینڈ میں ہیرے",
    "Die Distanz" to "فاصلہ",
    "Die Feiertage mit der Familie deines Partners verbringen" to "چھٹیاں اپنے ساتھی کی فیملی کے ساتھ گزاریں۔",
    "Die Gemütlichkeit und Ruhe" to "سکون اور سکون",
    "Die Menschen, die darin wohnen" to "وہ لوگ جو اس میں رہتے ہیں۔",
    "Die Umgebung und Atmosphäre" to "ماحول اور ماحول",
    "Die Worte und Emotionen" to "الفاظ اور جذبات",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "حتمی تفریحی ٹریویا چیلنج",
    "Diejenige sein, die umarmt" to "گلے لگانے والے بنیں۔",
    "Direkt ansprechen" to "براہ راست خطاب کریں۔",
    "Diskussion" to "بحث",
    "Diskutiere vor dem Kinderkriegen" to "بچے پیدا کرنے سے پہلے بحث کریں۔",
    "Diskutiert eure Antworten" to "اپنے جوابات پر تبادلہ خیال کریں۔",
    "Disney" to "ڈزنی",
    "Doch, schon mal" to "ہاں، ہاں",
    "Draußen mit der Natur als Kulisse" to "ایک پس منظر کے طور پر فطرت کے ساتھ باہر",
    "Drei-Stein-Ring" to "تین پتھر کی انگوٹھی",
    "Du bist dran" to "اب آپ کی باری ہے۔",
    "Du fehlst mir" to "مجھے آپ کی یاد آتی ہے۔",
    "Dubai" to "دبئی",
    "Dubai, VAE" to "دبئی، متحدہ عرب امارات",
    "Dunkles Design" to "ڈارک تھیم",
    "Durch Berührung" to "ٹچ کے ذریعے",
    "Durch Worte" to "الفاظ کے ذریعے",
    "Durch Zeit zu zweit" to "وقت کے ساتھ ساتھ",
    "Durch kleine Gesten" to "چھوٹے اشاروں کے ذریعے",
    "Durchgeplant" to "اچھی طرح سے منصوبہ بندی کی گئی ہے۔",
    "ERGEBNISSE" to "نتائج",
    "Egal, Hauptsache gesund" to "جو بھی ہو، بنیادی چیز صحت مند ہے۔",
    "Ehepaar Leben" to "شادی شدہ جوڑے کی زندگی",
    "Eher knapp" to "بلکہ قریب",
    "Eher nicht" to "اتنا زیادہ نہیں۔",
    "Eher schwer" to "بلکہ مشکل",
    "Eher schwierig" to "بلکہ مشکل",
    "Eher zu" to "مزید پسند",
    "Eifersucht ist ein Zeichen von Liebe." to "حسد محبت کی علامت ہے۔",
    "Eigenes Gemüsebeet" to "اپنی سبزیوں کا پیچ",
    "Ein Abenteuer in einer neuen Stadt" to "ایک نئے شہر میں ایک مہم جوئی",
    "Ein Anker" to "ایک اینکر",
    "Ein Balkon oder Garten" to "ایک بالکونی یا باغ",
    "Ein Filmabend" to "ایک فلمی رات",
    "Ein Harmony-Meilenstein eurer Liebe." to "آپ کی محبت میں ہم آہنگی کا سنگ میل۔",
    "Ein Herz" to "ایک دل",
    "Ein Herz an der Tür" to "دروازے پر ایک دل",
    "Ein Jahr lang eine Fernbeziehung führen" to "ایک سال تک لمبی دوری کا رشتہ رکھیں",
    "Ein Kindheitsessen" to "بچپن کا کھانا",
    "Ein Live-Musik-Konzert besuchen" to "لائیو میوزک کنسرٹ میں شرکت کریں۔",
    "Ein Museum besuchen" to "ایک میوزیم کا دورہ کریں",
    "Ein Spieleabend" to "کھیل کی رات",
    "Ein Spieleabend mit Freunden" to "دوستوں کے ساتھ کھیل کی رات",
    "Ein Urlaubsfoto" to "چھٹی کی تصویر",
    "Ein aktives Abenteuer" to "ایک فعال مہم جوئی",
    "Ein entspannender Spa-Tag" to "ایک آرام دہ سپا دن",
    "Ein ganz normaler Alltagstag" to "ایک مکمل طور پر عام روزمرہ کا دن",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "گرج چمک کے دوران گھر میں ایک آرام دہ شام",
    "Ein gemütliches Date drinnen" to "گھر کے اندر ایک آرام دہ تاریخ",
    "Ein lustiges Bild" to "ایک مضحکہ خیز تصویر",
    "Ein paar Handyfotos reichen" to "سیل فون کی چند تصاویر ہی کافی ہیں۔",
    "Ein paar Stunden" to "چند گھنٹے",
    "Ein paar kulturelle Anklänge sind okay" to "چند ثقافتی حوالے ٹھیک ہیں۔",
    "Ein romantischer Abend" to "ایک رومانوی شام",
    "Ein romantisches Abendessen bei Kerzenlicht" to "ایک رومانوی کینڈل لائٹ ڈنر",
    "Ein romantisches Bild" to "ایک رومانوی تصویر",
    "Ein romantisches Picknick an einem schönen Ort" to "ایک خوبصورت جگہ پر ایک رومانوی پکنک",
    "Ein schwerer Moment, den wir geschafft haben" to "ایک مشکل لمحہ جسے ہم نے سنبھال لیا۔",
    "Ein tolles Date im Freien unter dem Mondlicht" to "چاندنی کے نیچے باہر ایک زبردست تاریخ",
    "Ein ungewöhnliches Gericht" to "ایک غیر معمولی ڈش",
    "Ein zufälliger Schnappschuss" to "ایک بے ترتیب سنیپ شاٹ",
    "Einander kennenlernen" to "ایک دوسرے کو جانیں۔",
    "Eine Autoreise" to "سڑک کا سفر",
    "Eine Brücke" to "ایک پل",
    "Eine Date-Nacht unter den Sternen" to "ستاروں کے نیچے ایک تاریخ کی رات",
    "Eine Million Dollar gewinnen" to "ایک ملین ڈالر جیتیں۔",
    "Eine Million Dollar verdienen" to "ایک ملین ڈالر کمائیں۔",
    "Eine Nacht in einem Club" to "کلب میں ایک رات",
    "Eine Schokoladenverkostung" to "ایک چاکلیٹ چکھنا",
    "Eine Wanderung mit Panoramablick machen" to "پینورامک نظاروں کے ساتھ پیدل سفر کریں۔",
    "Eine Weinverkostung" to "شراب چکھنا",
    "Eine gemeinsame Reise" to "ایک ساتھ سفر",
    "Eine gemütliche Nacht zu Hause" to "گھر میں ایک آرام دہ رات",
    "Eine neue Sprache zu lernen ist einfach." to "نئی زبان سیکھنا آسان ہے۔",
    "Einen Film anschauen" to "ایک فلم دیکھیں",
    "Einen Monat lang überhaupt nicht miteinander reden" to "ایک مہینے سے ایک دوسرے سے بالکل بات نہیں کرتے",
    "Einen Tanzkurs besuchen" to "ڈانس کی کلاس لیں۔",
    "Einen Vergnügungspark erkunden" to "ایک تفریحی پارک دریافت کریں۔",
    "Einen Wellness-Tag" to "تندرستی کا دن",
    "Einen sehr emotionalen Partner haben" to "ایک بہت جذباتی ساتھی ہونا",
    "Einen sehr logischen Partner haben" to "ایک بہت ہی منطقی ساتھی ہونا",
    "Einer zahlt alles" to "ایک شخص سب کچھ ادا کرتا ہے۔",
    "Einfach mehr Alltag" to "بس زیادہ روزمرہ کی زندگی",
    "Einfach nebeneinander sein" to "بس ایک دوسرے کے قریب رہیں",
    "Einfach und intim" to "سادہ اور مباشرت",
    "Einige Dinge für dich behalten" to "کچھ چیزیں اپنے پاس رکھیں",
    "Einmal" to "ایک بار",
    "Eins, das nur wir kennen" to "ایک جسے صرف ہم جانتے ہیں۔",
    "Englisch" to "انگریزی",
    "Entspannte Hängematte" to "آرام دہ جھولا",
    "Entspannung" to "آرام",
    "Erdbeere" to "اسٹرابیری",
    "Erfolgreich" to "کامیاب",
    "Ergebnisse" to "نتائج",
    "Erst bei sehr großen Summen" to "صرف بہت بڑی رقم کے لیے",
    "Erst nur enge Freunde/Familie" to "پہلے صرف قریبی دوست/خاندان",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "جب میرا ساتھی پیغامات کا جواب دینے میں بہت زیادہ وقت لیتا ہے تو یہ مجھے پریشان کرتا ہے۔",
    "Essen & Genuss" to "کھانا اور لطف اندوزی۔",
    "Essensvorlieben" to "کھانے کی ترجیحات",
    "Etwa eine Woche später, erst mal nur wir" to "تقریباً ایک ہفتہ بعد، پہلے صرف ہم",
    "Etwas Neues ausprobieren" to "کچھ نیا کرنے کی کوشش کریں۔",
    "Etwas ganz anderes" to "کچھ بالکل مختلف",
    "Etwas sehr Scharfes" to "کچھ بہت تیز",
    "Etwas, das ich selbst gern erfinde" to "کوئی ایسی چیز جسے میں خود ایجاد کرنا پسند کرتا ہوں۔",
    "Etwas, eine kleine Note wäre schön" to "کچھ، ایک چھوٹا سا نوٹ اچھا ہو گا۔",
    "Familie" to "خاندان",
    "Familie/Freunde" to "خاندان/دوست",
    "Familienmensch" to "خاندانی آدمی",
    "Farbedelstein" to "رنگین قیمتی پتھر",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "ٹی وی اشتہارات بعض اوقات دیکھنے میں دلچسپ ہوتے ہیں۔",
    "Fertig" to "ہو گیا۔",
    "Fertig!" to "ہو گیا!",
    "Feste Date-Nights" to "مقررہ تاریخ کی راتیں۔",
    "Feuerstelle" to "آگ کا گڑھا",
    "Filigran & schlicht" to "فلیگری اور سادہ",
    "Filme/Serien" to "فلمیں/سیریز",
    "Formuliere um..." to "ریفریج...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "اپنے مسودے کو غیر متشدد طریقے سے دوبارہ بیان کریں: مشاہدہ، احساس، ضرورت، درخواست۔",
    "Frage hinzufügen" to "سوال شامل کریں۔",
    "Fragen & Spiele" to "سوالات اور گیمز",
    "Fragen für jede Gelegenheit" to "ہر موقع کے لیے سوالات",
    "Freizeitpark" to "تفریحی پارک",
    "Freunde treffen" to "دوستوں سے ملو",
    "Freundschaften mit Ex-Partnern sind okay." to "exes کے ساتھ دوستی ٹھیک ہے۔",
    "Früh aufstehen" to "جلدی اٹھو",
    "Fußbodenheizung" to "زیریں منزل حرارت",
    "Führen wir getrennte oder gemeinsame Konten?" to "کیا ہمارے الگ اکاؤنٹ ہیں یا مشترکہ؟",
    "Für dich empfohlen" to "آپ کے لیے تجویز کردہ",
    "Für die Zukunft" to "مستقبل کے لیے",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "اس تلاش کے لیے کوئی مماثل سوالات یا گیمز نہیں ملے۔",
    "Für immer" to "ہمیشہ کے لیے",
    "Fürsorglichkeit" to "دیکھ بھال کرنا",
    "GFK-Brücke" to "GRP پل",
    "Galerie" to "گیلری",
    "Gar nicht, der Moment gehört uns" to "ہرگز نہیں، یہ لمحہ ہمارا ہے۔",
    "Gar nichts tun" to "کچھ نہ کریں۔",
    "Geduld" to "صبر",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "طلوع آفتاب دیکھنے کے لیے صبح سویرے جائیں۔",
    "Geht so" to "اس طرح جاتا ہے۔",
    "Geister existieren wirklich." to "بھوت واقعی موجود ہیں۔",
    "Gelassenheit" to "سکون",
    "Gelbgold" to "پیلا سونا",
    "Geld & Finanzen" to "پیسہ اور خزانہ",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "ایک ساتھ دنیا کا سفر کریں، نئی ثقافتوں اور کھانوں کو دریافت کریں",
    "Gemeinsam ein Lego bauen" to "مل کر لیگو بنائیں",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "باورچی خانے میں ایک ساتھ مل کر ایک نئی ترکیب آزمائیں۔",
    "Gemeinsame Konten" to "مشترکہ اکاؤنٹس",
    "Gemeinsame Nächte" to "راتیں ایک ساتھ",
    "Gemeinsame Tage" to "دن ایک ساتھ",
    "Gemischt" to "مخلوط",
    "Gemüsebeet" to "سبزیوں کا پیچ",
    "Gemütliche Feuerstelle" to "آرام دہ چمنی",
    "Gesprächsanreger" to "گفتگو کا آغاز",
    "Getrennte Konten" to "الگ اکاؤنٹس",
    "Getrennte Urlaube tun einer Beziehung gut." to "الگ الگ چھٹیاں رشتے کے لیے اچھی ہیں۔",
    "Gewächshaus" to "گرین ہاؤس",
    "Glasfassade" to "شیشے کا اگواڑا",
    "Gleichgültigkeit" to "بے حسی",
    "Glücklich und frei" to "خوش اور مفت",
    "Gourmet Eis-Sorten" to "نفیس آئس کریم کی اقسام",
    "Gravur innen" to "اندر کندہ کاری",
    "Grillplatz" to "باربی کیو ایریا",
    "Groß & üppig" to "بڑا اور سرسبز",
    "Große Familie" to "بڑا خاندان",
    "Große Feier" to "بڑا جشن",
    "Große Fenster" to "بڑی کھڑکیاں",
    "Große Fensterfront" to "بڑی کھڑکی کے سامنے",
    "Großer Außenpool" to "بڑا آؤٹ ڈور پول",
    "Großer Garten" to "بڑا باغ",
    "Großer Stein" to "بڑا پتھر",
    "Größere Küche" to "بڑا کچن",
    "Gutes Essen" to "اچھا کھانا",
    "Habe ich" to "میں نے کیا۔",
    "Habe ich noch nie" to "میرے پاس کبھی نہیں ہے۔",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "کیا آپ نے کوئی حیران کن فرق دریافت کیا ہے؟ اس بارے میں بات کریں کہ آپ کو کچھ اختیارات کیوں بہتر پسند ہیں!",
    "Haus am See" to "جھیل کے کنارے گھر",
    "Haus/Wohnung" to "گھر/اپارٹمنٹ",
    "Hazelnut" to "ہیزلنٹ",
    "Heimkino" to "ہوم تھیٹر",
    "Herzhaft" to "دل سے",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "اس وقت یہاں کچھ بھی نہیں ہے۔\nفلٹر تبدیل کریں یا کوئی دوسرا موضوع منتخب کریں۔",
    "Hilfe im Alltag" to "روزمرہ کی زندگی میں مدد کریں۔",
    "Himbeere" to "رسبری",
    "Hinzufügen" to "شامل کریں۔",
    "Hobbys" to "مشاغل",
    "Hochzeitssträuße" to "شادی کے گلدستے",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "ہاگ وارٹس ہاؤس پرائیڈ: آپ کا تعلق کہاں سے ہے؟",
    "Home" to "گھر",
    "Hot Tub" to "ہاٹ ٹب",
    "Humor" to "مزاح",
    "Hund" to "کتا",
    "Hängematte" to "Hammock",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "کیا آپ تجویز کے حصے کے طور پر ایک تحریری خط چاہیں گے؟",
    "IKEA" to "IKEA",
    "Ich" to "میں",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "میں سینما جانے کے بجائے پارک میں رومانوی چہل قدمی کو ترجیح دیتا ہوں۔",
    "Ich bin noch nie in einem Kino eingeschlafen." to "میں کبھی سنیما میں نہیں سوا۔",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "مجھے اپنے ساتھی کے ساتھ نئے مشاغل یا سرگرمیاں دریافت کرنے میں مزہ آتا ہے۔",
    "Ich finde eine Alternative" to "میں ایک متبادل تلاش کروں گا۔",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "مجھے ہمیشہ ایک ہی جگہ پر جانے کے بجائے اپنے ساتھی کے ساتھ نئے ریستوران آزمانے میں مزہ آتا ہے۔",
    "Ich habe noch nie" to "میں نے کبھی نہیں کیا۔",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "میں کبھی بھی رولر کوسٹر سے خوفزدہ نہیں ہوا اور بہرحال میں اس پر چڑھ گیا۔",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "میں نے کبھی فاسٹ پاس ٹکٹ نہیں خریدے کیونکہ میں بے صبر تھا۔",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "میں نے کبھی گھر میں رہنے اور ٹی وی شو دیکھنے کا منصوبہ منسوخ نہیں کیا۔",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "میں نے کبھی بھی ہاگ وارٹس کے اپنے خط کا انتظار نہیں کیا۔",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "میں نے کبھی نہیں کہا کہ سلیترین درحقیقت اتنی بری نہیں تھی۔",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "میں نے کبھی نہیں کہا کہ میں Disney فلموں کے لیے بہت بوڑھا تھا (اور خفیہ طور پر ان سے لطف اندوز ہوا)۔",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "میں نے کبھی جان بوجھ کر ماریو کارٹ میں نیلے ٹینک والے کسی کو گولی نہیں ماری۔",
    "Ich habe noch nie bei einem Disney-Film geweint." to "میں کبھی بھی ڈزنی فلم میں نہیں رویا۔",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "میں نے ہارر مووی دیکھتے ہوئے اپنی آنکھیں کبھی نہیں ڈھانپیں۔",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "میں کبھی بھی گیم کو بچانا نہیں بھولا اور اس کی پیشرفت کے اوقات ضائع ہوئے۔",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "میں نے شرمناک منظر (کرینج فیکٹر) کے دوران کبھی بھی کمرے سے باہر نہیں نکلا۔",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "میں نے رولر کوسٹر کی تصویر کھینچتے ہوئے کبھی کوئی مضحکہ خیز پوز نہیں کیا۔",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "میں نے کبھی بھی رات گئے تک گیم نہیں کھیلی اور افسوس ہوا کہ میں اگلے دن کتنا تھکا ہوا تھا۔",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "میں نے کبھی بھی فلم کا اختتام گوگل نہیں کیا کیونکہ میں انتظار نہیں کر سکتا تھا۔",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "میں نے کبھی ایسا محسوس نہیں کیا کہ میں کسی فلم کے سیٹ پر کھڑا ہوں۔",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "میں نے اپنی پسندیدہ سیریز کا تعارف کبھی نہیں چھوڑا۔",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "میں نے کبھی کسی اور کا Netflix پاس ورڈ شیئر نہیں کیا۔",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "میں نے کام یا پڑھائی کے دوران کبھی گیم کا ساؤنڈ ٹریک نہیں سنا۔",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "جب میں ہار گیا تو میں نے کنٹرولر پر کبھی الزام نہیں لگایا۔",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "میں نے غصے میں کبھی کی بورڈ یا کنٹرولر نہیں پھینکا۔",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "میں کچھ دنوں تک واشنگ مشین میں گیلے کپڑوں کو نہیں بھولا۔",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "میں نے کبھی بھی گیم میں کاسمیٹک اشیاء پر حقیقی رقم خرچ نہیں کی۔",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "میں نے کبھی بھی غیر ملک میں کار نہیں چلائی۔",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "میں نے شاور میں کبھی بھی ڈزنی کا گانا نہیں لگایا۔",
    "Ich habe noch nie ein Elektroauto gefahren." to "میں نے کبھی الیکٹرک کار نہیں چلائی۔",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "میں نے کبھی پارک کے شوبنکر کے ساتھ تصویر نہیں لی۔",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "میں نے کبھی بھی کسی پالتو جانور کا نام Hogwarts کے کردار کے نام پر نہیں رکھا۔",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "میں نے کبھی فلم تھیٹر میں پاپ کارن نہیں گرایا اور اب بھی کھایا ہے۔",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "میں نے روزمرہ کی زندگی میں کبھی بھی اسٹار وار سے ماسٹر یوڈا کا اقتباس استعمال نہیں کیا۔",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "میں نے کبھی تھیم پارک میں زیادہ قیمت والی یادگار نہیں خریدی۔",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "میں نے کبھی بھی فلم کی سفارش نہیں کی ہے کہ دوسرے شخص کو خوفناک لگے۔",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "میں نے کبھی بھی آسکر کو آدھی رات کو لائیو نہیں دیکھا۔",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "میں نے کبھی کوئی سیریز منسوخ نہیں کی کیونکہ پچھلا سیزن بہت خراب تھا۔",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "میں نے کبھی بھی سیریز کا پورا سیزن ایک دن میں نہیں دیکھا۔",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "میں نے پہلی کوشش میں کبھی کسی باس کو شکست نہیں دی اور مجھے خدا کی طرح محسوس ہوا۔",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "مجھے ہیرو سے زیادہ ٹھنڈا ولن نہیں ملا۔",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "میں نے اپنے کھلونوں میں کھلونا کہانی کے کردار کو کبھی نہیں پہچانا۔",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "میں نے کبھی بھی RPG میں بالکل میرے جیسا کردار نہیں بنایا۔",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "میں نے کبھی تھیم پارک میں چورو نہیں کھایا۔",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "میں نے کبھی بھی ڈزنی کی فلم لگاتار تین بار نہیں دیکھی۔",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "میں نے پورے ایک ہفتے سے کبھی بھی ڈزنی کی دلکش دھن نہیں کی۔",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "میں نے کبھی بھی صرف ایک خاص اداکار کی وجہ سے کوئی فلم نہیں دیکھی۔",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "میں نے کبھی بھی فلم کا ساؤنڈ ٹریک گھنٹوں تک دہرانے پر نہیں سنا۔",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "میں نے کبھی بھی فلم کو خراب کرنے کا انکشاف نہیں کیا اور فوری طور پر اس پر افسوس کا اظہار کیا۔",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "مجھے کبھی کوئی ایسا دوست نہیں ملا جو دوسری مادری زبان بولتا ہو۔",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "میرا کبھی کوئی دوست نہیں تھا جو کسی دوسرے ملک میں چلا گیا ہو۔",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "میں نے کرسمس پر ہیری پوٹر فلم میراتھن کبھی نہیں کی ہے۔",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "میں نے آخر تک مارول فلم کبھی نہیں دیکھی صرف کریڈٹ کے بعد کے منظر کی وجہ سے۔",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "میں نے کبھی جان بوجھ کر NPC (نان پلیئر کریکٹر) کو ناراض نہیں کیا۔",
    "Ich habe noch nie einen Nachtzug genommen." to "میں نے کبھی رات کی ٹرین نہیں لی۔",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "میں نے اپنے ہاگ وارٹس کے گھر کا پتہ لگانے کے لیے کبھی آن لائن ٹیسٹ نہیں دیا۔",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "میں نے کبھی بھی سوشل میڈیا پوسٹ کو ڈیلیٹ نہیں کیا کیونکہ اسے کافی لائکس نہیں ملے۔",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "میں نے کبھی تھیم پارک میں کسی دن کو سال کا بہترین دن نہیں کہا۔",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "میں نے کبھی کسی تھیم پارک کا دورہ نہیں کیا اور صبح سے رات تک وہاں رہا۔",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "میں نے کبھی بھی ٹرانسفارمرز یا مارول سواری کو مکمل طور پر متوجہ نہیں چھوڑا۔",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "میں نے کبھی غصہ نہیں چھوڑا اور کھیل چھوڑ دیا۔",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "میں نے ہیری پوٹر کی کوئی بڑی جلد نہیں پڑھی۔",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "میں نے کبھی کسی سیریز میں اپنے پسندیدہ کردار کے بارے میں بات نہیں کی۔",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "میں نے کبھی Quidditch کھیلنے کا خواب نہیں دیکھا۔",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "میں نے کبھی بھی خفیہ طور پر گوگل نہیں کیا کہ مشکل سطح کو کیسے حل کیا جائے۔",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "میں نے کبھی بھی خفیہ طور پر امید نہیں کی کہ میرے پالتو جانور اس طرح بات کر سکتے ہیں جیسے وہ ڈزنی میں کرتے ہیں۔",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "میں نے سمز میں پول کی سیڑھی کو کبھی نہیں ہٹایا۔",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "میں نے 3D سمیلیٹر سواری میں اپنے بیرنگ کبھی نہیں کھوئے ہیں۔",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "میں نے کبھی یونیورسٹی کی اسپورٹس ٹیم میں نہیں کھیلا۔",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "میں نے کبھی بھی کسی ایک کشش کے لیے دو گھنٹے سے زیادہ لائن میں انتظار نہیں کیا۔",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "میں نے کبھی بھی پانی کی سواری پر اپنا قیمتی سامان گیلا نہیں کیا۔",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "میں نے کبھی کسی دوست سے بحث نہیں کی کہ کون سا گھر سب سے اچھا ہے۔",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "میں نے کبھی بھی ایلسا جیسی جادوئی طاقتوں کا بہانہ نہیں کیا۔",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "میں کبھی اتنا زور سے نہیں ہنسا کہ میں نے کسی فلم کا کوئی اہم سین یاد کیا ہو۔",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "میں نے کبھی اتنی زیادہ ایڈرینالین محسوس نہیں کی کہ میں فوری طور پر دوبارہ سواری کرنا چاہتا ہوں۔",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "میں نے کبھی سنو وائٹ جیسے جانوروں کے ساتھ گانے کی کوشش نہیں کی۔",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "میں نے کبھی ڈزنی لینڈ کے سفر کا خواب نہیں دیکھا۔",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "میں نے جراسک پارک کی پانی کی سواری پر سوار ہونے کا خواب کبھی نہیں دیکھا۔",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "میں نے کبھی کسی گیم میں چھلانگ لگانے کے خوف پر اونچی آواز میں نہیں چیخا۔",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "میں ٹی وی شو کے اختتام پر کبھی نہیں رویا۔",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "میں نے کبھی... گھر رہنے کی تاریخ منسوخ نہیں کی۔",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "میں نے کبھی بھی کسی پیغام کو 10 بار ریفریج نہیں کیا۔",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "میں نے کبھی... چپکے سے اپنے ساتھی کے سیل فون کو نہیں دیکھا۔",
    "Ich habe noch nie!" to "میں نے کبھی نہیں!",
    "Ich habe!" to "میرے پاس ہے!",
    "Ich lache viel mit meinem Partner." to "میں اپنے ساتھی کے ساتھ بہت ہنستا ہوں۔",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "میں اپنے ساتھی کے مشاغل اور دلچسپیوں کو جاننا پسند کرتا ہوں۔",
    "Ich liebe es" to "مجھے یہ پسند ہے۔",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "مجھے اپنے ساتھی کے ساتھ ایسی فلمیں دیکھنا پسند ہے جو ہم میں سے کسی نے پہلے نہیں دیکھی ہیں۔",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "مجھے اپنے ساتھی کے ساتھ اپنی پسندیدہ موسیقی کا اشتراک کرنا پسند ہے۔",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "مجھے کبھی بھی کنیکٹنگ فلائٹ پکڑنے کے لیے بھاگنا نہیں پڑا۔",
    "Ich plane gerne Dates mit meinem Partner." to "مجھے اپنے ساتھی کے ساتھ تاریخوں کی منصوبہ بندی کرنا پسند ہے۔",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "میں مصروف ہونے کے باوجود اپنے ساتھی کے ساتھ وقت گزارنے کو ترجیح دیتا ہوں۔",
    "Ich schreibe meinem Partner jeden Tag." to "میں ہر روز اپنے پارٹنر کو میسج کرتا ہوں۔",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "مجھے اپنے ساتھی کے ساتھ میمز اور لطیفے بانٹنا پسند ہے۔",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "میں اپنے ساتھی کے ساتھ اپنے دن کی تمام تفصیلات شیئر کرنا پسند کرتا ہوں۔",
    "Ich würde es nie tun" to "میں یہ کبھی نہیں کروں گا۔",
    "Ich übe noch" to "میں ابھی بھی مشق کر رہا ہوں۔",
    "Ideen generieren" to "خیالات پیدا کریں۔",
    "Im Haushalt helfen" to "گھر کے آس پاس مدد کریں۔",
    "In Chat einfügen" to "چیٹ میں شامل کریں۔",
    "In Stille nebeneinander" to "ایک دوسرے کے ساتھ خاموشی میں",
    "In den Bergen" to "پہاڑوں میں",
    "In eine Bar gehen" to "ایک بار میں جائیں۔",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "غروب آفتاب دیکھنے کے لیے بیچ بار میں جانا",
    "In einem feinen Restaurant essen gehen" to "ایک عمدہ ریستوراں میں باہر کھانا",
    "In einen Coffeeshop gehen" to "ایک کافی شاپ پر جائیں۔",
    "In einer Beziehung sollte man alles voneinander wissen." to "رشتے میں آپ کو ایک دوسرے کے بارے میں سب کچھ معلوم ہونا چاہیے۔",
    "Infinity-Pool" to "انفینٹی پول",
    "Innenpool" to "انڈور پول",
    "Intelligenz" to "ذہانت",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "صرف اس وقت مباشرت لمحات ہیں جب آپ کا ساتھی ان کی شروعات کرتا ہے۔",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "دعوتی کوڈ: HRM-8731 · سب کچھ کھلا",
    "Island" to "آئس لینڈ",
    "Ist okay für mich" to "یہ میرے ساتھ ٹھیک ہے۔",
    "Ist schon perfekt" to "یہ کامل ہے۔",
    "Ja, Traditionen einbinden" to "ہاں، روایات کو شامل کریں۔",
    "Ja, absolut" to "جی ہاں، بالکل",
    "Ja, etwas zum Lesen und Aufbewahren" to "ہاں، کچھ پڑھنے اور رکھنے کے لیے",
    "Ja, genug" to "ہاں، کافی ہے۔",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "جی ہاں، ایک دلچسپ شہر یا پرکشش مقام میں",
    "Ja, in- und auswendig" to "ہاں، اندر اور باہر",
    "Ja, komplett überraschend" to "ہاں، بالکل حیران کن",
    "Ja, perfekt" to "جی ہاں، کامل",
    "Ja, sie gehören zur Familie!" to "ہاں، وہ خاندانی ہیں!",
    "Ja, sofort teilen" to "ہاں، فوراً شئیر کریں۔",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "ہاں، ہم اس بات کو یقینی بنائیں گے کہ خاندان کا وقت ایک ترجیح ہے۔",
    "Jacuzzi" to "جاکوزی",
    "Jahr zusammen 🎉" to "سال ایک ساتھ 🎉",
    "Jahre zusammen 🎉" to "سال ایک ساتھ 🎉",
    "Jeder zahlt 50%" to "ہر کوئی 50% ادا کرتا ہے",
    "Junge" to "لڑکا",
    "Kamin" to "چمنی",
    "Karriere & Erfolg" to "کیریئر اور کامیابی",
    "Kategorien" to "زمرہ جات",
    "Katze" to "بلی",
    "Keine Musik" to "کوئی موسیقی نہیں۔",
    "Keine Party nötig, privat halten" to "پارٹی کی ضرورت نہیں، اسے نجی رکھیں",
    "Keine Privatsphäre" to "کوئی رازداری نہیں۔",
    "Keine Treffer gefunden" to "کوئی مماثلت نہیں ملی",
    "Keiner" to "کوئی نہیں۔",
    "Keiner von uns" to "ہم میں سے کوئی نہیں۔",
    "Kennst du die Essensvorlieben deines Partners?" to "کیا آپ اپنے ساتھی کی کھانے کی ترجیحات کو جانتے ہیں؟",
    "Kino" to "سنیما",
    "Kirchlich" to "کلیسیائی",
    "Klassisch Solitär" to "کلاسک سولٹیئر",
    "Klassisch gebunden" to "کلاسیکی طور پر پابند",
    "Klein & zart" to "چھوٹا اور نازک",
    "Kleine Geschenke" to "چھوٹے تحائف",
    "Kleine Runde" to "چھوٹا گروپ",
    "Kochen und Freunde einladen" to "کھانا پکانا اور دوستوں کو مدعو کرنا",
    "Kochkurs" to "کوکنگ کلاس",
    "Kommt auf den Tag an" to "دن پر منحصر ہے۔",
    "Kommt darauf an" to "یہ منحصر ہے۔",
    "Kommt drauf an" to "یہ منحصر ہے۔",
    "Kommt mit" to "میرے ساتھ چلو",
    "Konzert" to "کنسرٹ",
    "Kräftige Farben" to "مضبوط رنگ",
    "Kräuterbeet" to "جڑی بوٹیوں کا بستر",
    "Kultur & Sehenswürdigkeiten" to "ثقافت اور مقامات",
    "Kuscheln" to "لپٹنا",
    "Kuss senden" to "ایک بوسہ بھیجیں۔",
    "Körperliche Annäherung" to "جسمانی نقطہ نظر",
    "Körperliche Nähe" to "جسمانی قربت",
    "Küche" to "باورچی خانہ",
    "Land" to "ملک",
    "Landhaus" to "کنٹری ہاؤس",
    "Landhausstil" to "کنٹری ہاؤس اسٹائل",
    "Lange wach bleiben" to "دیر تک جاگتے رہیں",
    "Lappland" to "لیپ لینڈ",
    "Lappland, Finnland" to "لیپ لینڈ، فن لینڈ",
    "Las Vegas" to "لاس ویگاس",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "اپنے پارٹنر کو آپ کو بہترین خود بننے کی ترغیب دینے دیں۔",
    "Lehne ab" to "انکار",
    "Leichtigkeit" to "ہلکا پن",
    "Leidenschaft" to "جذبہ",
    "Liebe im Gleichgewicht" to "توازن میں محبت",
    "Liebe sie, macht mehr Spaß" to "ان سے پیار کرو، زیادہ مزہ",
    "Lieber durchgeplant oder spontan?" to "کیا آپ اس کی منصوبہ بندی کرنا چاہیں گے یا اچانک؟",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "کیا آپ دو لوگوں کے ساتھ یا لوگوں کے ساتھ ایک پرسکون شام گزارنا پسند کریں گے؟",
    "Lieber nicht" to "بہتر نہ ہو۔",
    "Lieber vorher grob absprechen" to "بہتر ہے کہ چیزوں پر پہلے سے بات کرلی جائے۔",
    "Lokal einkaufen" to "مقامی طور پر خریداری کریں۔",
    "London" to "لندن",
    "London, England" to "لندن، انگلینڈ",
    "Lügen" to "جھوٹ",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "کیا آپ عوامی یا نجی تجویز کو ترجیح دیتے ہیں؟",
    "Malediven" to "مالدیپ",
    "Man sollte nie streitend einschlafen." to "آپ کو بحث کرتے ہوئے کبھی نہیں سونا چاہیے۔",
    "Mango Sorbet" to "آم کا شربت",
    "Markant & breit" to "حیرت انگیز اور وسیع",
    "Marken & Alltag" to "برانڈز اور روزمرہ کی زندگی",
    "McDonald’s" to "میکڈونلڈز",
    "Mediterraner Innenhof" to "بحیرہ روم کا صحن",
    "Mehr Unterstützung" to "مزید تعاون",
    "Mehr gemeinsame Zeit" to "مزید وقت ایک ساتھ",
    "Mehr zuhören" to "مزید سنیں۔",
    "Mehrgenerationenhaus" to "کثیر نسل کا گھر",
    "Mein Arbeitsplatz" to "میرے کام کی جگہ",
    "Mein Partner" to "میرا ساتھی",
    "Mich überraschen" to "مجھے حیران کر دیں۔",
    "Minimalistisches Interieur" to "کم سے کم داخلہ",
    "Missverständnisse" to "غلط فہمیاں",
    "Mit Familie und engen Freunden" to "خاندان اور قریبی دوستوں کے ساتھ",
    "Mit Kompromissen" to "سمجھوتوں کے ساتھ",
    "Mitgefühl" to "ہمدردی",
    "Mittelweg mit besonderen Details" to "خصوصی تفصیلات کے ساتھ درمیانی زمین",
    "Modern geometrisch" to "جدید جیومیٹرک",
    "Moderne Grillstation" to "جدید گرل اسٹیشن",
    "Moderner Name" to "جدید نام",
    "Moderner Solitär" to "جدید سولٹیئر",
    "Moissanit" to "موسیانائٹ",
    "Moment festhalten" to "لمحے کو کیپچر کریں۔",
    "Momente" to "لمحات",
    "Monaco" to "موناکو",
    "Moralische Werte" to "اخلاقی اقدار",
    "Museum" to "میوزیم",
    "Musik" to "موسیقی",
    "Mut" to "ہمت",
    "Mädchen" to "لڑکیاں",
    "Möbelhaus" to "فرنیچر کی دکان",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "کیا آپ واقعی کوئز چھوڑنا چاہتے ہیں؟ آپ کی پچھلی پیش رفت محفوظ رہتی ہے۔",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "کیا آپ پالتو جانور کو درخواست میں شامل کرنا چاہیں گے؟",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "اس لمحے کو سوشل میڈیا پر فوری طور پر شیئر کرنا چاہتے ہیں؟",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "ہمیں بچت کرنے کی ضرورت پڑسکتی ہے۔",
    "Müssen es planen" to "اس کی منصوبہ بندی کرنے کی ضرورت ہے۔",
    "Müssen sparen" to "بچانے کی ضرورت ہے۔",
    "Nachricht an" to "پیغام",
    "Name Partnerin" to "ساتھی کا نام",
    "Namen und Startdatum eurer Beziehung." to "آپ کے رشتے کے نام اور آغاز کی تاریخ۔",
    "Natursteinfassade" to "قدرتی پتھر کا اگواڑا",
    "Naturteich" to "قدرتی تالاب",
    "Nein, einfach halten" to "نہیں، بس اسے پکڑو",
    "Nein, erstmal privat halten" to "نہیں، اسے ابھی کے لیے نجی رکھیں",
    "Nein, lieber vor Ort" to "نہیں، سائٹ پر بہتر ہے۔",
    "Nein, modern halten" to "نہیں، اسے جدید رکھیں",
    "Nein, nur wir" to "نہیں، صرف ہم",
    "Nein, zu ablenkend" to "نہیں، بہت پریشان کن",
    "Netflix" to "نیٹ فلکس",
    "Neubau mit Smart Home" to "سمارٹ ہوم کے ساتھ نئی عمارت",
    "Neubau mit Technik" to "ٹیکنالوجی کے ساتھ نئی عمارت",
    "Neue Liebe, neue Erfahrungen" to "نئی محبت، نئے تجربات",
    "Neues Hobby" to "نیا مشغلہ",
    "Neues Spiel" to "نیا گیم",
    "Neugier" to "تجسس",
    "New York" to "نیویارک",
    "New York, USA" to "نیویارک، امریکہ",
    "Nicht mein Fall" to "میری چائے کا کپ نہیں۔",
    "Nicht nötig, lieber klassisch bleiben" to "ضروری نہیں، کلاسک رہنا ہی بہتر ہے۔",
    "Nichts — es passt so" to "کچھ نہیں - یہ فٹ بیٹھتا ہے۔",
    "Nie wieder Burger" to "پھر کبھی برگر نہیں۔",
    "Nie wieder Pizza" to "پھر کبھی پیزا نہ کریں۔",
    "Niemand" to "کوئی نہیں۔",
    "Niemand ohne Plan" to "بغیر کسی منصوبے کے کوئی نہیں۔",
    "Nike" to "نائکی",
    "Nizza" to "اچھا",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "ابھی کوئی لمحات نہیں ہیں۔\nاپنا پہلا تجربہ حاصل کریں 💞",
    "Nur bei wichtigen Themen" to "صرف اہم موضوعات کے لیے",
    "Nur wir beide" to "بس ہم دونوں",
    "Nähe & Intimität" to "قربت اور قربت",
    "Obstgarten" to "باغ",
    "Oder" to "یا",
    "Offene Küche" to "کھلی کچہری",
    "Offene Wohnküche" to "کھلا کچن/لونگ روم",
    "Ohne Stein" to "بغیر پتھر کے",
    "Open End" to "اوپن اینڈنگ",
    "Outdoor-Küche" to "آؤٹ ڈور کچن",
    "Outdoor-Sofa" to "بیرونی صوفہ",
    "Outdoor-Whirlpool" to "بیرونی بھنور",
    "Ovaler Diamant" to "اوول ہیرا",
    "Paar" to "جوڑا",
    "Paar-Statistiken" to "جوڑے کے اعدادوشمار",
    "Paris" to "پیرس",
    "Paris, Frankreich" to "پیرس، فرانس",
    "Partner" to "پارٹنر",
    "Partner-Simulator" to "پارٹنر سمیلیٹر",
    "Partnerin" to "پارٹنر",
    "Party Edition" to "پارٹی ایڈیشن",
    "Party Edition II" to "پارٹی ایڈیشن II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "کیا کوئی جانور ہماری روزمرہ کی زندگی میں بھی فٹ بیٹھتا ہے؟",
    "Pasta" to "پاستا",
    "Pastell" to "پیسٹل",
    "Penthouse mit Ausblick" to "ایک منظر کے ساتھ پینٹ ہاؤس",
    "Pepsi" to "پیپسی",
    "Pergola mit Lounge" to "لاؤنج کے ساتھ پرگوولا",
    "Pfingstrosen" to "چپراسی",
    "Pinguin" to "پینگوئن",
    "Pistazie" to "پستا",
    "Pizza" to "پیزا",
    "Pizzaofen" to "پیزا اوون",
    "Platin" to "پلاٹینم",
    "PlayStation" to "پلے اسٹیشن",
    "Pool" to "پول",
    "Pop" to "پاپ",
    "Prasselnder Kamin" to "گرجتی چمنی",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "شہزادیاں، قزاق اور پریوں کی دھول: ڈزنی کوئز",
    "Privater Innenhof" to "نجی صحن",
    "Profil" to "پروفائل",
    "Profil bearbeiten" to "پروفائل میں ترمیم کریں۔",
    "Prozentual nach Einkommen" to "آمدنی کی بنیاد پر فیصد",
    "Quiz verlassen" to "کوئز چھوڑیں۔",
    "Quiz verlassen?" to "کوئز چھوڑیں؟",
    "Rausgehen in die Natur" to "فطرت سے باہر نکلیں۔",
    "Reden vor ..." to "سے بات کرتے ہوئے...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "باقاعدہ تاریخیں یا وقت ایک ساتھ شیڈول کریں۔",
    "Reisen" to "سفر",
    "Reiseziele" to "سفر کے مقامات",
    "Respektlosigkeit" to "بے عزتی۔",
    "Restaurant" to "ریسٹورنٹ",
    "RnB / Soul" to "RnB / روح",
    "Rock" to "راک",
    "Rom" to "روم",
    "Rom, Italien" to "روم، اٹلی",
    "Romantik" to "رومانس",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "رومانوی اشارے جیسے پیغامات، نوٹ یا تحائف مجھے خوش کرتے ہیں۔",
    "Romantische Stimmung" to "رومانوی مزاج",
    "Roségold" to "گلاب سونا",
    "Ruhig zu zweit" to "دو کے لیے خاموش",
    "Runder Diamant" to "گول ہیرا",
    "Salted Caramel" to "نمکین کیریمل",
    "Sammle Ideen..." to "خیالات جمع کریں...",
    "Santorini" to "سینٹورینی",
    "Santorini, Griechenland" to "سینٹورینی، یونان",
    "Saphir" to "نیلم",
    "Saunahaus" to "سونا ہاؤس",
    "Schickes Restaurant oder Hotel" to "وضع دار ریستوراں یا ہوٹل",
    "Schlafzimmer" to "بیڈروم",
    "Schließen" to "بند",
    "Schmal & zart" to "پتلا اور نازک",
    "Schnappschüsse aus unserer Liebesgeschichte" to "ہماری محبت کی کہانی سے سنیپ شاٹس",
    "Schokolade" to "چاکلیٹ",
    "Schreib frei, was dir wirklich dazu einfällt." to "آزادانہ طور پر لکھیں جو واقعی ذہن میں آئے",
    "Schreibe deine eigene Antwort" to "اپنا جواب خود لکھیں۔",
    "Sehr gerne" to "آپ کا استقبال ہے۔",
    "Sehr leicht" to "بہت ہلکا",
    "Sehr wichtig — Fotos und Video" to "بہت اہم — تصاویر اور ویڈیو",
    "Sehr wichtig, es sollte persönlich sein" to "بہت اہم، یہ ذاتی ہونا چاہیے۔",
    "Selbst kochen" to "خود پکائیں",
    "Senden" to "بھیجیں۔",
    "Separate Küche" to "علیحدہ کچن",
    "Serie schauen" to "سیریز دیکھیں",
    "Serienmarathon auf dem Sofa" to "صوفے پر میراتھن سیریز",
    "Sex & Liebe" to "جنس اور محبت",
    "Seychellen" to "سیشلز",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "کیا ہم ایک بچے/متعدد بچوں کے تمام اخراجات پورے کر سکتے ہیں؟ 💰",
    "Soll der Antrag eine Überraschung sein?" to "کیا تجویز حیرت انگیز ہونی چاہئے؟",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "کیا ایپلی کیشن ثقافتی یا روایتی عناصر پر مشتمل ہونا چاہئے؟",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "کیا ایپلی کیشن ثقافتی یا روایتی عناصر پر مشتمل ہونا چاہئے؟",
    "Sommerhochzeit" to "سمر ویڈنگ",
    "Sonnige Dachterrasse" to "دھوپ والی چھت",
    "Sowohl als auch" to "دونوں اور",
    "Spazieren" to "چہل قدمی کریں۔",
    "Spaß & Abenteuer" to "تفریح اور مہم جوئی",
    "Speichern" to "محفوظ کریں۔",
    "Spiel bearbeiten" to "گیم میں ترمیم کریں۔",
    "Spielbereich für Kinder" to "بچوں کے لیے کھیل کا علاقہ",
    "Spiele" to "گیمز",
    "Spiele spielen und Spaß haben" to "گیمز کھیلیں اور مزے کریں۔",
    "Spontan" to "بے ساختہ",
    "Sportplatz" to "کھیلوں کا میدان",
    "Spotify" to "Spotify",
    "Sprache" to "زبان",
    "Stadt" to "شہر",
    "Stadt oder Land — was ist uns wichtiger?" to "شہر یا ملک - ہمارے لیے زیادہ اہم کیا ہے",
    "Stadtvilla" to "سٹی ولا",
    "Standesamt & Party" to "رجسٹری آفس اور پارٹی",
    "Statement-Ring" to "بیان کی انگوٹھی",
    "Stilvolles Outdoor-Sofa" to "اسٹائلش آؤٹ ڈور صوفہ",
    "Stimme voll zu" to "بالکل متفق",
    "Stimmt" to "سچ ہے۔",
    "Stimmt nicht" to "سچ نہیں ہے۔",
    "Stimmt, noch nie" to "سچ ہے، کبھی نہیں۔",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "ساحل سمندر کا دن",
    "Streit über Haushalt" to "گھریلو تنازعہ",
    "Studio Ghibli" to "اسٹوڈیو گھبلی۔",
    "Ständig" to "مسلسل",
    "Suche schließen" to "تلاش بند کریں۔",
    "Suche zurücksetzen" to "تلاش کو دوبارہ ترتیب دیں۔",
    "Suche öffnen" to "تلاش کھولیں۔",
    "Suchergebnisse" to "تلاش کے نتائج",
    "Sushi" to "سشی",
    "Süß" to "میٹھا",
    "Tage zusammen 💞" to "دن ایک ساتھ 💞",
    "Tauche ins Unterbewusstsein" to "لاشعور میں غوطہ لگائیں۔",
    "Teile alle deine Hobbys mit deinem Partner" to "اپنے تمام مشاغل اپنے ساتھی کے ساتھ بانٹیں۔",
    "Teils teils" to "جزوی طور پر جزوی طور پر",
    "Testen" to "ٹیسٹ",
    "Themen" to "موضوعات",
    "Tiefe Gespräche" to "گہری گفتگو",
    "Tiefgründige Gespräche führen" to "گہری گفتگو کریں۔",
    "Tierpension" to "اینیمل بورڈنگ ہاؤس",
    "Tiny House" to "چھوٹا گھر",
    "Tippen zum Auswählen & Scrollen" to "منتخب کرنے اور اسکرول کرنے کے لیے تھپتھپائیں۔",
    "Tippen zum Zuklappen" to "گرنے کے لیے تھپتھپائیں۔",
    "Titel" to "عنوان",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "عنوان، زمرہ، موضوع، ٹیگز، سوالات...",
    "Tokyo, Japan" to "ٹوکیو، جاپان",
    "Traditioneller Name" to "روایتی نام",
    "Traumhaus Außenbereich" to "ڈریم ہاؤس آؤٹ ڈور ایریا",
    "Traumhochzeit" to "خوابوں کی شادی",
    "Treffer" to "ہٹ",
    "Tägliche Aktivität" to "روزانہ کی سرگرمی",
    "Umformulieren" to "دوبارہ بیان کریں۔",
    "Unbeantwortet" to "جواب نہیں دیا گیا۔",
    "Unbeliebte Meinungen" to "غیر مقبول رائے",
    "Universal Studios Genie oder Neuling?" to "یونیورسل اسٹوڈیوز جینیئس یا نیا؟",
    "Uns auseinanderzuleben" to "الگ ہونے کے لیے",
    "Unser Intimleben" to "ہماری مباشرت زندگی",
    "Unser Traumhaus" to "ہمارے خوابوں کا گھر",
    "Unser erstes Treffen" to "ہماری پہلی ملاقات",
    "Unsere Gesichter" to "ہمارے چہرے",
    "Unsere eigenen Träume" to "ہمارے اپنے خواب",
    "Unsere nächste Reise" to "ہمارا اگلا سفر",
    "Unter 1000" to "1000 سے کم",
    "Unter 1000 im Monat" to "فی مہینہ 1000 سے کم",
    "Unter 50€/Monat" to "50€/ماہ سے کم",
    "Unter Leuten" to "لوگوں کے درمیان",
    "Untreue" to "بے وفائی",
    "Urlaub" to "چھٹی",
    "Vanille" to "ونیلا",
    "Venedig" to "وینس",
    "Venedig, Italien" to "وینس، اٹلی",
    "Verbinde dich mit" to "کے ساتھ جڑیں۔",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "جواب دیکھنے کے لیے \${profile.partnerName} سے جڑیں",
    "Verbindung" to "کنکشن",
    "Verbringe die Feiertage mit deiner Familie" to "چھٹیاں اپنے خاندان کے ساتھ گزاریں۔",
    "Verlobungsringe" to "منگنی بج رہی ہے۔",
    "Vertrautheit" to "واقفیت",
    "Viel getrennt" to "بہت سی جدائی",
    "Vielleicht ein oder zwei" to "شاید ایک یا دو",
    "Vielleicht, aber mündlich reicht" to "ہو سکتا ہے، لیکن زبانی طور پر کافی ہے۔",
    "Vielleicht, wenn es machbar ist" to "ہو سکتا ہے، اگر یہ ممکن ہو۔",
    "Vielleicht, wenn es passt" to "شاید، اگر یہ فٹ بیٹھتا ہے۔",
    "Vintage Art déco" to "ونٹیج آرٹ ڈیکو",
    "Vintage verspielt" to "ونٹیج چنچل",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "آپ کے ساتھی کے ذریعہ نئے مشاغل سے متعارف کرایا جانا",
    "Vor dem Kauf eines Hauses besprechen" to "گھر خریدنے سے پہلے بحث کریں۔",
    "Vor der Anschaffung eines Haustiers besprechen" to "پالتو جانور خریدنے سے پہلے بحث کریں۔",
    "Vor der gemeinsamen Reise besprechen" to "ایک ساتھ سفر کرنے سے پہلے بات چیت کریں۔",
    "Vor nichts" to "کچھ نہیں۔",
    "Vorort" to "مضافاتی علاقہ",
    "Walnuss" to "اخروٹ",
    "Wandern" to "پیدل سفر",
    "Wann fühlst du dich mir am nächsten?" to "آپ مجھے کب سب سے قریب محسوس کرتے ہیں؟",
    "Wann fühlst du dich mir körperlich am nächsten?" to "آپ جسمانی طور پر میرے سب سے زیادہ قریب کب محسوس کرتے ہیں؟",
    "Was bedeutet Vertrauen für dich konkret?" to "خاص طور پر آپ کے لیے اعتماد کا کیا مطلب ہے؟",
    "Was entspannt dich mehr?" to "آپ کو کس چیز سے زیادہ سکون ملتا ہے؟",
    "Was fehlt dir über die Distanz am meisten?" to "فاصلے کے بارے میں آپ کو سب سے زیادہ کیا یاد آتا ہے؟",
    "Was gefällt dir an deinem Zuhause am besten?" to "آپ کو اپنے گھر کے بارے میں سب سے زیادہ کیا پسند ہے؟",
    "Was hast du von deinem Partner gelernt?" to "آپ نے اپنے ساتھی سے کیا سیکھا؟",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "شہوانی، شہوت انگیز مواد کو ایک ساتھ دیکھنے کے بارے میں آپ کا کیا خیال ہے؟",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "پرپس کے بارے میں آپ کا کیا خیال ہے (جیسے نشانیاں، غبارے وغیرہ)؟",
    "Was ist das Wichtigste beim Antrag?" to "درخواست دیتے وقت سب سے اہم چیز کیا ہے؟",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "آپ جنسی مقابلے میں سب سے اہم چیز کیا دیکھتے ہیں؟",
    "Was ist dein Lieblingsfoto von uns? 📸" to "آپ کی ہماری پسندیدہ تصویر کون سی ہے؟ 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "ایک ساتھ رہنے کے بارے میں آپ کا سب سے بڑا خوف کیا ہے؟",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "وہ کونسا کھانا ہے جسے آپ پسند کرتے ہیں لیکن آپ کا ساتھی سمجھ نہیں سکتا؟",
    "Was ist für dich ein absoluter Dealbreaker?" to "آپ کے لیے مطلق ڈیل بریکر کیا ہے؟",
    "Was ist für jeden von uns das absolute Highlight?" to "ہم میں سے ہر ایک کے لیے مطلق خاص بات کیا ہے؟",
    "Was ist passiert?" to "کیا ہوا؟",
    "Was macht einen Moment für dich romantisch?" to "کیا چیز آپ کے لیے ایک لمحے کو رومانوی بناتی ہے؟",
    "Was magst du an deinem Partner am liebsten?" to "آپ کو اپنے ساتھی کے بارے میں سب سے زیادہ کیا پسند ہے؟",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "آپ کو کیا اچھا لگتا ہے: جلدی اٹھنا یا دیر سے جاگنا؟",
    "Was magst du lieber?" to "آپ کو کون سا زیادہ پسند ہے؟",
    "Was möchtest du eigentlich sagen?" to "آپ اصل میں کہنا کیا چاہتے ہیں؟",
    "Was möchtest du, dass dein Partner öfter tut?" to "آپ اپنے ساتھی کو زیادہ کثرت سے کیا کرنا چاہیں گے؟",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "جب ہم سفر کرتے ہیں تو جانور کا کیا ہوتا ہے؟",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "ہمارے بچے کے بڑے ہونے پر اس کا کیا بنے گا؟",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "والدین کے طور پر ہمیں کس چیز سے کبھی بھی محروم نہیں ہونا چاہئے؟",
    "Was war dein schönster Moment mit mir bisher?" to "میرے ساتھ آپ کا اب تک کا بہترین لمحہ کون سا تھا؟",
    "Was wir gegessen haben" to "ہم نے کیا کھایا",
    "Was wollt ihr nie vergessen?" to "آپ کیا بھولنا نہیں چاہتے؟",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "آپ کے لیے کیا برا ہوگا: دوبارہ کبھی پیزا نہیں یا پھر کبھی برگر نہیں؟",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "آپ ایک دن سب سے زیادہ کیا کرنا پسند کریں گے؟",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "اگر پیسے کا مسئلہ نہ ہوتا تو آپ فوری طور پر کیا تبدیل کریں گے؟",
    "Weiter" to "اگلا",
    "Weiter spielen" to "کھیلنا جاری رکھیں",
    "Weiß ich noch nicht" to "میں ابھی تک نہیں جانتا",
    "Weiße Rosen" to "سفید گلاب",
    "Weißgold" to "سفید سونا",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "ہمارے بچے کو یقینی طور پر ہم سے کیا معیار حاصل کرنا چاہئے؟",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "آپ تجویز کے لیے کیا ماحول چاہیں گے؟",
    "Welcher Raum sagt am meisten über dich aus?" to "کون سا کمرہ آپ کے بارے میں سب سے زیادہ کہتا ہے؟",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "ہم خوراک اور ڈاکٹر کے لیے کس بجٹ کی منصوبہ بندی کرتے ہیں؟",
    "Welches Lied macht dich an? 🥵" to "کون سا گانا آپ کو آن کرتا ہے؟ 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "کون سی تصویر آپ کی پسندیدہ ہے؟",
    "Wellnessbad" to "تندرستی کا غسل",
    "Wenn es schwierig ist" to "جب چیزیں مشکل ہوں۔",
    "Wenn ich müde bin" to "جب میں تھک جاتا ہوں۔",
    "Wenn wir uns lange umarmen" to "جب ہم دیر تک گلے لگتے ہیں۔",
    "Wenn wir zusammen lachen" to "جب ہم ایک ساتھ ہنستے ہیں۔",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "کون زیادہ تیزی سے فیصلہ کرتا ہے کہ کیا آرڈر کرنا ہے؟",
    "Wer findet die besten Restaurants?" to "بہترین ریستوراں کون تلاش کرتا ہے؟",
    "Wer gibt mehr Herzlichkeit?" to "کون زیادہ گرمجوشی دیتا ہے؟",
    "Wer hat den besseren Musikgeschmack?" to "موسیقی میں کس کا ذوق بہتر ہے؟",
    "Wer hängt mehr an seinen Eltern?" to "اپنے والدین کے ساتھ کون زیادہ لگاؤ ​​رکھتا ہے؟",
    "Wer ist besser organisiert?" to "کون بہتر منظم ہے؟",
    "Wer ist der Beste bei der Filmauswahl?" to "فلموں کے انتخاب میں سب سے بہتر کون ہے؟",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "رومانوی تاریخوں کی منصوبہ بندی میں سب سے بہتر کون ہے؟",
    "Wer ist der beste Tänzer?" to "بہترین ڈانسر کون ہے؟",
    "Wer ist romantischer?" to "کون زیادہ رومانٹک ہے؟",
    "Wer kocht besser?" to "کون بہتر کھانا پکاتا ہے؟",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "تزئین و آرائش اور دیکھ بھال کا خیال کون رکھتا ہے؟",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "دوسرے شخص کی طبیعت ٹھیک نہ ہونے پر کون جلدی نوٹس لیتا ہے؟",
    "Wer sucht am Ende wirklich den Film aus?" to "آخر میں فلم کا انتخاب کون کرتا ہے؟",
    "Wer vergisst eher einen Jahrestag?" to "سالگرہ کو بھلانے کا زیادہ امکان کون ہے؟",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "اگلی صبح کون اپنا نام بھول جائے گا؟",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "اگلے دن ایسی ویڈیو کس کو ملے گی جس کے بارے میں وہ کچھ نہیں جانتے ہوں گے؟",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "اجنبی کے صوفے پر رات کون گزارے گا؟",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "پارٹی میں سونے اور چہرے پر شارپی کے ساتھ جاگنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "کون ڈانس فلور پر پھسلنے کا زیادہ امکان رکھتا ہے لیکن اسے ایک ٹھنڈی حرکت کی طرح دکھاتا ہے؟",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "ہاؤس پارٹی میں اسپاٹائف پلے لسٹ کو کس کے کنٹرول میں لینے کا زیادہ امکان ہے؟",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "پارٹی میں سب کے لیے پیزا آرڈر کرنے اور خود کھانے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "پارٹی میں سب سے پہلے کس کے سو جانے کا زیادہ امکان ہوتا ہے؟",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "پارٹی میں اچانک صفائی شروع کرنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "جب اس کے برعکس سچ ہو تو مکمل طور پر ہوشیار ہونے کا دعویٰ کرنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "دلیل میں سب سے پہلے کس کا زیادہ امکان ہے؟",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "شراب پینے کے کھیل میں دھوکہ دینے کا زیادہ امکان کون ہے؟",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "بوفے پر چھاپہ مارنے اور چپکے سے کھانا گھر لے جانے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "اپنی کہانی میں شام کی سب سے شرمناک تصویر پوسٹ کرنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "اپنے پسندیدہ گانے کی درخواست کرنے پر DJ کو کون ناراض کرے گا؟",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "ایک گانے کے بول گانے کا زیادہ امکان کون ہوگا، لیکن یقین کے ساتھ؟",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "مینو پر سب سے مہنگے مشروبات کا آرڈر دینے اور اس پر افسوس کرنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "اگر پڑوسیوں نے شور کی شکایت کی تو کون زیادہ ان کو مدعو کرے گا؟",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "پارٹی گیمز (جیسے بیئر پونگ) کو زیادہ سنجیدگی سے لینے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "VIP رسائی حاصل کرنے کے لیے باؤنسرز سے دوستی کرنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "فوری طور پر کراوکی جنگ شروع کرنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "بوتل کھولنے والا استعمال کیے بغیر بوتل کھولنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "کسی نے نہ پوچھنے کے باوجود تقریر کرنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "باتھ روم میں سیلفی لینے میں ایک گھنٹہ گزارنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "ایک شرمناک ڈانس پرفارمنس پیش کرنے اور اسے منانے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "پارٹی ختم ہونے کے بعد سابق پارٹنر کو فون کرنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "غلطی سے کسی اجنبی مہمان کو ناراض کرنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "الوداع کہے بغیر خفیہ طور پر پارٹی چھوڑنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "مہمانوں سے بات کرنے کے بجائے میزبان کے پالتو جانور کے ساتھ کون کھیلنا پسند کرے گا؟",
    "Wer würde eher spontan eine Reise buchen?" to "بے ساختہ ٹرپ بک کرنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "باورچی خانے میں گھنٹوں گہری گفتگو کرنے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "غلطی سے کسی اور کا مشروب پینے کا زیادہ امکان کون ہے؟",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "اتفاقی طور پر مہنگے گلدان یا کسی نازک چیز پر دستک دینے کا زیادہ امکان کون ہوگا؟",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "کون زیادہ امکان ہو گا کہ وہ خود ایک پیچیدہ کاک ٹیل کو ملانے کی کوشش کرے اور بری طرح ناکام ہو؟",
    "Wer würde eher zu spät kommen?" to "دیر ہونے کا زیادہ امکان کون ہے؟",
    "Wer würde eher?" to "اس کے بجائے کون کرے گا؟",
    "Wer übernimmt die tägliche Versorgung?" to "روزانہ کی دیکھ بھال کون کرتا ہے؟",
    "Werde so akzeptiert, wie du bist" to "جیسا آپ ہیں قبول کریں۔",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "کیا ہمارے پاس بچے/بچوں کے لیے کافی وقت ہوگا؟ ⏳",
    "Whirlpool" to "ہاٹ ٹب",
    "White Chocolate" to "سفید چاکلیٹ",
    "Widgets" to "وجیٹس",
    "Wie fühlst du dich am meisten geliebt?" to "آپ سب سے زیادہ پیارے کیسے محسوس کرتے ہیں؟",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "ہم مختلف آمدنیوں سے کیسے نمٹتے ہیں؟",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "آپ کے ساتھی کے لیے آپ کے ساتھ سیکس شروع کرنے کا بہترین طریقہ کیا ہے؟",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "آپ کا ساتھی آپ کے لیے اس سے بھی بہتر پارٹنر کیسے ہو سکتا ہے؟",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "تجویز کے کتنے عرصے بعد آپ دوسروں کے ساتھ جشن منانا چاہتے ہیں؟",
    "Wie lange wollen wir dort mindestens bleiben?" to "ہم وہاں کم از کم کب تک رہنا چاہتے ہیں؟",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "آپ کے لیے خواہشات پر بات کرنا کتنا آسان ہے؟",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "آپ ہمارا مستقبل کیسا دیکھنا چاہتے ہیں؟",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "گھر میں آپ کا کامل اتوار کیسا لگتا ہے؟",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "آپ جنسی تعلقات کے دوران گندی گفتگو کے بارے میں کیسا محسوس کرتے ہیں؟",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "ہم حقیقت میں کتنا کریڈٹ لے سکتے ہیں؟",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "ہم کتنا وقت الگ کرنا چاہتے ہیں؟",
    "Wie viel wollen wir insgesamt ausgeben?" to "ہم کل کتنا خرچ کرنا چاہتے ہیں؟",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "بچے کے آنے کے بعد ہم اپنے رشتے کے لیے وقت کیسے نکالیں گے؟",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "یہ آپ کے لیے کتنا اہم ہے کہ اس لمحے کو پکڑ لیا گیا ہے؟",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "آپ کے لیے یہ کتنا اہم ہے کہ ایپلی کیشن آپ کے شوق یا دلچسپیوں کی عکاسی کرتی ہے؟",
    "Wie würdest du sie/ihn nennen?" to "آپ اسے کیا پکاریں گے؟",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "سیکس سے باہر پیار ظاہر کرنے کا آپ کا پسندیدہ طریقہ کیا ہے؟",
    "Wildblumen" to "جنگلی پھول",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "آپ کو لڑکی چاہیے یا لڑکا؟ 👶",
    "Wintergarten" to "موسم سرما کا باغ",
    "Winterhochzeit" to "موسم سرما کی شادی",
    "Wir bestellen einfach beides" to "ہم صرف دونوں کا آرڈر دیتے ہیں۔",
    "Wir brauchen ewig" to "یہ ہمیں ہمیشہ کے لیے لے جاتا ہے۔",
    "Wir einigen uns nie" to "ہم کبھی متفق نہیں ہوتے",
    "Wir entscheiden es gemeinsam" to "ہم مل کر فیصلہ کرتے ہیں۔",
    "Wir treffen uns in der Mitte" to "ہم درمیان میں ملتے ہیں۔",
    "Wir wechseln uns ab" to "ہم باری باری لیتے ہیں۔",
    "Wird stressig" to "تناؤ کا شکار ہو جاتا ہے۔",
    "Wobei lachst du am meisten?" to "آپ کو سب سے زیادہ کس چیز سے ہنسی آتی ہے؟",
    "Wofür sparen wir gemeinsam?" to "ہم مل کر کیا بچا رہے ہیں؟",
    "Wohnzimmer" to "رہنے کا کمرہ",
    "Woran erinnerst du dich am lebhaftesten?" to "آپ کو سب سے زیادہ واضح طور پر کیا یاد ہے؟",
    "Worauf freust du dich bei uns am meisten?" to "آپ ہمارے ساتھ سب سے زیادہ کس چیز کے منتظر ہیں؟",
    "Worte/Komplimente" to "الفاظ/تعریفات",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "آپ ہمارے رشتے میں سب سے زیادہ کس چیز سے ڈرتے ہیں؟",
    "Wünsche? z.B. günstig, draußen" to "خواہشات؟ جیسے سستا، باہر",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "کیا آپ چھٹیوں پر تجویز کرنا پسند کریں گے (جس میں سفر شامل ہے)؟",
    "Xbox" to "ایکس بکس",
    "YouTube Music" to "YouTube Music",
    "Zeichne für mich" to "میرے لیے ڈرا کرو",
    "Zeichne mich als Tier — welches wäre ich?" to "مجھے ایک جانور کی طرح کھینچیں - میں کون سا بنوں گا؟",
    "Zeichne unser Gefühl zueinander als Symbol." to "ایک علامت کے طور پر ہمارے جذبات کو ایک دوسرے کی طرف کھینچیں۔",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "ہمارے خوابوں کے گھر کو ایک لائن میں کھینچیں۔ سب سے زیادہ حیران کن چیز کیا ہے؟",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "ہماری پہلی تاریخ ڈرا کریں - تصویر میں یقینی طور پر کیا ہونا چاہئے؟",
    "Zeichnen" to "ڈرا",
    "Zeit füreinander" to "ایک دوسرے کے لیے وقت",
    "Zeit, wenn das Baby schläft" to "وہ وقت جب بچہ سوتا ہے۔",
    "Zelten gehen" to "کیمپنگ پر جائیں۔",
    "Zitrone" to "لیموں",
    "Zu Hause, gemütlich und privat" to "گھر میں، آرام دہ اور نجی",
    "Zu einem Picknick gehen" to "پکنک پر جانا",
    "Zu einem ausgefallenen Abendessen gehen" to "ایک فینسی ڈنر پر جانا",
    "Zu zweit reisen" to "ایک جوڑے کے طور پر سفر کریں۔",
    "Zuhause & Alltag" to "گھر اور روزمرہ کی زندگی",
    "Zuhören" to "سنو",
    "Zurück" to "واپس",
    "Zusammen seit" to "تب سے ایک ساتھ",
    "Zusammen seit (TT.MM.JJJJ)" to "ایک ساتھ جب سے (DD.MM.YYYY)",
    "Zusammenziehen" to "معاہدہ",
    "Zustimmen oder Ablehnen" to "اتفاق یا اختلاف",
    "Zwei Kreise, die sich überschneiden" to "دو دائرے جو اوورلیپ ہوتے ہیں۔",
    "Zwei Stühle davor" to "اس کے سامنے دو کرسیاں",
    "Zärtlich sein" to "نرم رہیں",
    "Öfter als ich zugebe" to "میں تسلیم کرتا ہوں اس سے زیادہ بار",
    "Über 100€/Monat" to "100€/ماہ سے زیادہ",
    "Über 2000 im Monat" to "ماہانہ 2000 سے زیادہ",
    "Über mich selbst" to "اپنے بارے میں",
    "Übernehmen" to "اپلائی کریں۔",
    "Überraschend" to "حیران کن",
    "Überraschung" to "حیرت",
    "Überspringen" to "چھوڑ دیں۔",
    "Übertrieben und großartig" to "سب سے اوپر اور زبردست",
    "✎ Tippe, um zu antworten" to "✎ جواب دینے کے لیے تھپتھپائیں۔",
    "✨ GFK-Brücke" to "✨ GRP پل",
)

internal fun localizeUrduDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_URDU_CONTENT)
