package com.example.ui

/** Generated production locale catalog aligned to the current Harmony customer catalog. */
internal val EXACT_XHOSA_CONTENT: Map<String, String> = mapOf(
    "1-5 Jahre" to "1-5 iminyaka",
    "1000 - 1500 im Monat" to "1000 - 1500 ngenyanga",
    "1000 bis 3000" to "1000 ukuya kwi-3000",
    "1500 - 2000 im Monat" to "1500 - 2000 ngenyanga",
    "3000 bis 5000" to "3000 ukuya kwi-5000",
    "5-10 Jahre" to "5-10 iminyaka",
    "50-100€/Monat" to "50-100€/ngenyanga",
    "Ab 100€" to "Ukusuka kwi-100€",
    "Ab 500€" to "Ukusuka kwi-500€",
    "Ab 50€" to "Ukusuka kwi-50€",
    "Ab und zu" to "Ngoku nangoko",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Sithetha ngantoni phambi kokuthenga?",
    "Abbrechen" to "Rhoxisa",
    "Abenteuer" to "adventure",
    "Adidas" to "Adidas",
    "Aktivitäten" to "Imisebenzi",
    "Alle" to "Konke",
    "Alle Pakete" to "Zonke iipakethe",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Ulahlekelwe ngabahlobo bakho bonke ngaphandle komhlobo wakho osenyongweni",
    "Alle intimen Momente selbst initiieren" to "Qalisa onke amaxesha asondeleyo ngokwakho",
    "Alles davon" to "Yonke",
    "Alles, was noch kommt" to "Yonke into ezayo",
    "Alltagsroutine" to "Inkqubo yemihla ngemihla",
    "Alltägliche Berührungen" to "Ukuchukumisa yonke imihla",
    "Altbau mit Charme" to "Isakhiwo esidala esinomtsalane",
    "Am Strand" to "Elwandle",
    "Am liebsten alles zusammen" to "Ngokuqhelekileyo yonke into kunye",
    "Am selben Tag mit Freunden/Familie" to "Usuku olunye nabahlobo/nosapho",
    "Amazon" to "Amazon",
    "Amsterdam" to "eAmsterdam",
    "Amsterdam, Niederlande" to "eAmsterdam, eNetherlands",
    "An das Gefühl" to "Ngemvakalelo",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "Kwindawo kawonke-wonke enababukeli abaninzi",
    "An einen Geruch" to "Yevumba",
    "An einen Song" to "Yengoma",
    "An etwas, das ich gesagt habe" to "Ngento endiyithethileyo",
    "Analyse starten" to "Qala uhlalutyo",
    "Analysiere eure Muster..." to "Hlalutya iipateni zakho...",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Hlalutya iimpendulo zakho kunye neencoko ngokweGottman kunye neGFK.",
    "Ananas auf der Pizza schmeckt köstlich." to "Iphayinaphu kwipizza incasa kamnandi.",
    "Android" to "Android",
    "Antwort mit einem Foto" to "Phendula ngefoto",
    "Antwortähnlichkeit" to "Phendula ukufana",
    "App-Sprache auswählen" to "Khetha ulwimi lwe-app",
    "Auf eine Bootsparty gehen" to "Yiya kwitheko lesikhephe",
    "Aufmerksamkeit" to "Ingqalelo",
    "Aufräumen und Projekte angehen" to "Coca kwaye ujongane neeprojekthi",
    "Aufwärmen" to "Shushubeza",
    "Aufwärmen: Einander kennenlernen" to "Zifudumeze: ukwazana",
    "Aus dem Urlaub" to "Ukusuka kwiholide",
    "Ausgefallener Name" to "Igama elimnandi",
    "Ausschlafen und faulenzen" to "Lala ngaphakathi kwaye ukonqena",
    "Ausschlafen und nichts tun" to "Lala ungenzi nto",
    "Aussehen" to "Jonga",
    "Auto" to "imoto",
    "Außenkamin" to "Iziko langaphandle",
    "BEANTWORTE" to "IMPENDULO",
    "Bali" to "Bali",
    "Bali, Indonesien" to "EBali, eIndonesia",
    "Banane" to "ibhanana",
    "Beantwortet" to "Waphendula",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Phendula imibuzo ngexesha elinye — iimpendulo aziyi kubonakala de nigqibe nobabini.",
    "Beantwortete Fragen" to "Uphendulwe imibuzo",
    "Bearbeiten" to "Hlela",
    "Bei Insider-Witzen" to "Ngeziqhulo zangaphakathi",
    "Bei Memes" to "Kwiimemes",
    "Bei einer spontanen Berührung" to "Ngokuchukumisa okuzenzekelayo",
    "Beide" to "Zombini",
    "Beide gleich" to "Zombini ziyafana",
    "Beide zusammen" to "Zombini kunye",
    "Beide, aber wir tun so als ob nicht" to "Zombini, kodwa singenzi ngathi",
    "Beides" to "Zombini",
    "Beides wäre schlimm" to "Zombini ziya kuba zimbi",
    "Beim Einschlafen nebeneinander" to "Ukulala ecaleni komnye",
    "Beim Reden" to "Ngethuba sithetha",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Iindawo zabakhenkethi ezidumileyo zihlala zidanile.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Chaza ubomi bethu bokwabelana ngesondo nge-emoji.",
    "Besser kommunizieren" to "Nxibelelana ngcono",
    "Bessere Lage" to "Indawo engcono",
    "Bestellen" to "Umyalelo",
    "Besuchte Länder" to "Amazwe atyelelwe",
    "Besuchte Städte" to "Izixeko ezityelelweyo",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Ngaba ukhetha isindululo esibaxayo okanye into efihlakeleyo?",
    "Beziehung" to "Ubudlelwane",
    "Bibliothek" to "ithala leencwadi",
    "Bin manchmal unsicher" to "Ndikhe ndingazithembanga",
    "Bist du ein Videospiel-Guru?" to "Ngaba ungumdlali wevidiyo?",
    "Blumenwiese" to "Idlelo leentyatyambo",
    "Bunte Blumenwiese" to "Idlelo leentyatyambo elimibalabala",
    "Burger" to "Abemi",
    "Burger King" to "Burger King",
    "Chat" to "Ncokola",
    "Coca-Cola" to "Coca cola",
    "Cookie Dough" to "Ikhukhi intlama",
    "Dachgarten mit Lounge" to "Igadi yophahla enendawo yokuphumla",
    "Dachterrasse" to "Ithafa eluphahleni",
    "Das Wetter an dem Tag" to "Imozulu ngaloo mini",
    "Das erste Selfie" to "I selfie yokuqala",
    "Das meiste weiß ich" to "Ndiyazi uninzi lwalo",
    "Das oder das?" to "Le okanye leya?",
    "Das tägliche Leben" to "Ubomi bemihla ngemihla",
    "Dass Zusagen gehalten werden" to "Ezo zithembiso ziyagcinwa",
    "Dass alles meinen Stil hat" to "Ukuba yonke into inesitayile sam",
    "Dass ich alles erzählen kann" to "Ukuze ndikwazi ukuxelela yonke into",
    "Dass ich mich nicht sorgen muss" to "Oko ndingabi naxhala",
    "Dass wir ungestört sind" to "Ukuba asiphazamiseki",
    "Dein Name" to "Ingama lakho",
    "Deine Antwort..." to "Impendulo Yakho...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Iimpendulo zakho zigciniwe. Nje ukuba uMlingane agqibe iphakheji, zombini iimpendulo ziya kubonakala kunye.",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Iimpendulo zakho zigciniwe. Nje ukuba \${profile.partnerName} igqibe ipakethe, zombini iimpendulo ziya kubonakala kunye.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Yenza ubudlelwane bakho bube bukudala kwaye buzenzekele",
    "Deine Beziehung stabil und sicher machen" to "Yenza ubudlelwane bakho buzinze kwaye bukhuseleke",
    "Deine eigene Antwort" to "Eyakho impendulo",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Kungcono wabelane ngeemfihlo zakho ezinzulu kunye neqabane lakho",
    "Deinen besten Freund verlieren" to "Ukuphulukana nomhlobo wakho osenyongweni",
    "Denke an dich" to "Cinga ngawe",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Ukubukela ifilimu enye kabini kukuchitha ixesha.",
    "Der Blick nach draußen" to "Umbono ngaphandle",
    "Der Garten" to "Umyezo",
    "Der Ort" to "Indawo",
    "Der Ring und die Geste" to "Umsesane kunye nentshukumo",
    "Der perfekte Heiratsantrag" to "Isindululo somtshato esigqibeleleyo",
    "Derjenige sein, der umarmt wird" to "Yiba ngulo uwolwayo",
    "Deutsch" to "IsiJamani",
    "Diamant" to "idayimani",
    "Diamanten im Band" to "Iidayimani kwiqela",
    "Die Distanz" to "Umgama",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Zichithe iiholide kunye nosapho lweqabane lakho",
    "Die Gemütlichkeit und Ruhe" to "Ukonwaba kunye noxolo",
    "Die Menschen, die darin wohnen" to "Abantu abahlala apho",
    "Die Umgebung und Atmosphäre" to "Okusingqongileyo kunye nomoya",
    "Die Worte und Emotionen" to "Amazwi kunye neemvakalelo",
    "Die ultimative Entertainment-Quiz-Herausforderung" to "Umngeni wokugqibela wemibuzo yokuzonwabisa",
    "Diejenige sein, die umarmt" to "Yiba ngulowo uyanga",
    "Direkt ansprechen" to "Idilesi ngqo",
    "Diskussion" to "ingxoxo",
    "Diskutiere vor dem Kinderkriegen" to "Xoxani phambi kokuba nibe nabantwana",
    "Diskutiert eure Antworten" to "Xoxa ngeempendulo zakho",
    "Disney" to "Disney",
    "Doch, schon mal" to "Ewe, sele",
    "Draußen mit der Natur als Kulisse" to "Ngaphandle ngendalo njengemva",
    "Drei-Stein-Ring" to "Izangqa ezintathu zamatye",
    "Du bist dran" to "Licala lakho",
    "Du fehlst mir" to "Ndiyakukhumbula",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "I-Dubai, i-UAE",
    "Dunkles Design" to "Uyilo olumnyama",
    "Durch Berührung" to "Ngokuchukumisa",
    "Durch Worte" to "Ngamazwi",
    "Durch Zeit zu zweit" to "Ngexesha kunye",
    "Durch kleine Gesten" to "Ngokusebenzisa izijekulo ezincinci",
    "Durchgeplant" to "Icwangcisiwe",
    "ERGEBNISSE" to "IZIPHUMO",
    "Egal, Hauptsache gesund" to "Kungakhathaliseki, into ephambili isempilweni",
    "Ehepaar Leben" to "Ubomi besibini esitshatileyo",
    "Eher knapp" to "Kunokuba uvale",
    "Eher nicht" to "Endaweni yoko",
    "Eher schwer" to "Kunokuba nzima",
    "Eher schwierig" to "Kunokuba nzima",
    "Eher zu" to "Kungcono kakhulu",
    "Eifersucht ist ein Zeichen von Liebe." to "Umona luphawu lothando.",
    "Eigenes Gemüsebeet" to "Isiqwenga semifuno",
    "Ein Abenteuer in einer neuen Stadt" to "I-adventure kwisixeko esitsha",
    "Ein Anker" to "I-ankile",
    "Ein Balkon oder Garten" to "I-balcony okanye igadi",
    "Ein Filmabend" to "Ubusuku bemuvi",
    "Ein Harmony-Meilenstein eurer Liebe." to "Inkqubela phambili yothando lwakho.",
    "Ein Herz" to "Intliziyo",
    "Ein Herz an der Tür" to "Intliziyo emnyango",
    "Ein Jahr lang eine Fernbeziehung führen" to "Yiba nobudlelwane bomgama omde unyaka",
    "Ein Kindheitsessen" to "Isidlo sabantwana",
    "Ein Live-Musik-Konzert besuchen" to "Yiya kwikonsathi yomculo edlalwa ngqo",
    "Ein Museum besuchen" to "Ndwendwela imyuziyam",
    "Ein Spieleabend" to "Ubusuku bomdlalo",
    "Ein Spieleabend mit Freunden" to "Ubusuku bomdlalo kunye nabahlobo",
    "Ein Urlaubsfoto" to "Ifoto yeholide",
    "Ein aktives Abenteuer" to "I-adventure esebenzayo",
    "Ein entspannender Spa-Tag" to "Usuku lokuphumla lwe-spa",
    "Ein ganz normaler Alltagstag" to "Usuku oluqhelekileyo lwemihla ngemihla",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Ubusuku obupholileyo endlwini ngexesha lokuduma kwezulu",
    "Ein gemütliches Date drinnen" to "Umhla opholileyo ngaphakathi",
    "Ein lustiges Bild" to "Umfanekiso ohlekisayo",
    "Ein paar Handyfotos reichen" to "Iifoto ezimbalwa zeselfowuni zanele",
    "Ein paar Stunden" to "Iiyure ezimbalwa",
    "Ein paar kulturelle Anklänge sind okay" to "Iimbekiselo ezimbalwa zenkcubeko zilungile",
    "Ein romantischer Abend" to "Ubusuku bothando",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Isidlo sothando ngekhandlela",
    "Ein romantisches Bild" to "Umfanekiso wothando",
    "Ein romantisches Picknick an einem schönen Ort" to "Ipikiniki yothando kwindawo entle",
    "Ein schwerer Moment, den wir geschafft haben" to "Umzuzu onzima esikwazileyo",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Umhla omkhulu ngaphandle phantsi kokukhanya kwenyanga",
    "Ein ungewöhnliches Gericht" to "Isitya esingaqhelekanga",
    "Ein zufälliger Schnappschuss" to "Umfanekiso okhawulezayo",
    "Einander kennenlernen" to "Yazanani",
    "Eine Autoreise" to "Uhambo lwendlela",
    "Eine Brücke" to "Ibhulorho",
    "Eine Date-Nacht unter den Sternen" to "Ubusuku bomhla phantsi kweenkwenkwezi",
    "Eine Million Dollar gewinnen" to "Phumelela isigidi seerandi",
    "Eine Million Dollar verdienen" to "Yenza isigidi seedola",
    "Eine Nacht in einem Club" to "Ubusuku kwiklabhu",
    "Eine Schokoladenverkostung" to "Ukungcamla itshokolethi",
    "Eine Wanderung mit Panoramablick machen" to "Thatha uhambo olunemibono yepanoramic",
    "Eine Weinverkostung" to "Ukungcamla iwayini",
    "Eine gemeinsame Reise" to "Uhambo kunye",
    "Eine gemütliche Nacht zu Hause" to "Ubusuku obupholileyo ekhaya",
    "Eine neue Sprache zu lernen ist einfach." to "Ukufunda ulwimi olutsha kulula.",
    "Einen Film anschauen" to "Bukela imuvi",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Iphele inyanga bengathethisani tu",
    "Einen Tanzkurs besuchen" to "Thatha iklasi yomdaniso",
    "Einen Vergnügungspark erkunden" to "Jonga ipaki yokonwabisa",
    "Einen Wellness-Tag" to "Usuku lwempilo",
    "Einen sehr emotionalen Partner haben" to "Ukuba neqabane elineemvakalelo kakhulu",
    "Einen sehr logischen Partner haben" to "Ukuba neqabane elinengqondo kakhulu",
    "Einer zahlt alles" to "Umntu omnye uhlawula yonke into",
    "Einfach mehr Alltag" to "Ngokulula ngakumbi ubomi bemihla ngemihla",
    "Einfach nebeneinander sein" to "Yibani nje ecaleni komnye",
    "Einfach und intim" to "Elula kwaye esondeleyo",
    "Einige Dinge für dich behalten" to "Zigcine kuwe ezinye izinto",
    "Einmal" to "Kanye",
    "Eins, das nur wir kennen" to "Inye kuphela esiyaziyo",
    "Englisch" to "IsiNgesi",
    "Entspannte Hängematte" to "I-hammock ekhululekile",
    "Entspannung" to "ukuphumla",
    "Erdbeere" to "Ndingathanda ipere yezinto zokukhafula kwiishethi",
    "Erfolgreich" to "Iphumelele",
    "Ergebnisse" to "Iziphumo",
    "Erst bei sehr großen Summen" to "Kuphela ngeemali ezinkulu kakhulu",
    "Erst nur enge Freunde/Familie" to "Kuphela ngabahlobo abasondeleyo / usapho ekuqaleni",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Iyandicaphukisa xa iqabane lam lithatha ixesha elide ukuphendula imiyalezo.",
    "Essen & Genuss" to "Ukutya & nolonwabo",
    "Essensvorlieben" to "Ukhetho lokutya",
    "Etwa eine Woche später, erst mal nur wir" to "Malunga neveki kamva, thina kuqala",
    "Etwas Neues ausprobieren" to "Zama into entsha",
    "Etwas ganz anderes" to "Into eyahlukileyo ngokupheleleyo",
    "Etwas sehr Scharfes" to "Into ebukhali kakhulu",
    "Etwas, das ich selbst gern erfinde" to "Into endithanda ukuyiqulunqa",
    "Etwas, eine kleine Note wäre schön" to "Into ethile, ukubamba kancinci kuya kuba kuhle",
    "Familie" to "Usapho",
    "Familie/Freunde" to "Usapho/abahlobo",
    "Familienmensch" to "Indoda yosapho",
    "Farbedelstein" to "Ilitye elinqabileyo elinemibala",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Iintengiso zeTV ngamanye amaxesha zinomdla wokubukela.",
    "Fertig" to "Ulungile",
    "Fertig!" to "Gqibezela!",
    "Feste Date-Nights" to "Ubusuku obumiselweyo",
    "Feuerstelle" to "Umgodi womlilo",
    "Filigran & schlicht" to "I-Filigree & elula",
    "Filme/Serien" to "Iifilimu/uthotho",
    "Formuliere um..." to "Phinda uchaze...",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Phinda uchaze uyilo lwakho ngokungenabundlobongela: ukujonga, iimvakalelo, imfuno, isicelo.",
    "Frage hinzufügen" to "Yongeza umbuzo",
    "Fragen & Spiele" to "Imibuzo & imidlalo",
    "Fragen für jede Gelegenheit" to "Imibuzo ngamaxesha onke",
    "Freizeitpark" to "Ipaki yokonwabisa",
    "Freunde treffen" to "dibana nabahlobo",
    "Freundschaften mit Ex-Partnern sind okay." to "Ubuhlobo kunye exes kulungile.",
    "Früh aufstehen" to "Ukuvuka kusasa",
    "Fußbodenheizung" to "Ukufudumeza umgangatho ophantsi",
    "Führen wir getrennte oder gemeinsame Konten?" to "Ngaba sinee-akhawunti ezahlukeneyo okanye ezidibeneyo?",
    "Für dich empfohlen" to "Indululelwe wena",
    "Für die Zukunft" to "Ngekamva",
    "Für diese Suche wurden keine passenden Fragen oder Spiele gefunden." to "Akukho mibuzo ingqamanayo okanye imidlalo efunyenweyo kolu phendlo.",
    "Für immer" to "Ngonaphakade",
    "Fürsorglichkeit" to "Ukukhathala",
    "GFK-Brücke" to "GRP ibhulorho",
    "Galerie" to "igalari",
    "Gar nicht, der Moment gehört uns" to "Akunjalo tu, umzuzu ngowethu",
    "Gar nichts tun" to "Ungenzi nto konke konke",
    "Geduld" to "umonde",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Yiya kwakusasa ukuze ubone ukuphuma kwelanga",
    "Geht so" to "Ihamba kakuhle",
    "Geister existieren wirklich." to "Imimoya ikhona ngokwenene.",
    "Gelassenheit" to "ukuzola",
    "Gelbgold" to "Igolide etyheli",
    "Geld & Finanzen" to "Imali kunye neMali",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Hambani kunye nehlabathi kunye, phonononga iinkcubeko ezintsha kunye nokutya",
    "Gemeinsam ein Lego bauen" to "Yakhani iLego kunye",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Zama iresiphi entsha kunye ekhitshini",
    "Gemeinsame Konten" to "Iiakhawunti ezidibeneyo",
    "Gemeinsame Nächte" to "Ubusuku kunye",
    "Gemeinsame Tage" to "Iintsuku ekwabelwana ngazo",
    "Gemischt" to "Ixutyiwe",
    "Gemüsebeet" to "isiqwenga semifuno",
    "Gemütliche Feuerstelle" to "Umgodi opholileyo womlilo",
    "Gesprächsanreger" to "Abaqalisi bencoko",
    "Getrennte Konten" to "Iiakhawunti ezahlukeneyo",
    "Getrennte Urlaube tun einer Beziehung gut." to "Iiholide ezahlukeneyo zilungile kubudlelwane.",
    "Gewächshaus" to "indlu eluhlaza",
    "Glasfassade" to "I-facade yeglasi",
    "Gleichgültigkeit" to "ukungakhathali",
    "Glücklich und frei" to "Ukonwaba kwaye ukhululekile",
    "Gourmet Eis-Sorten" to "Iintlobo ze-ayisikrimu ze-gourmet",
    "Gravur innen" to "Ukrola ngaphakathi",
    "Grillplatz" to "Indawo yeBarbecue",
    "Groß & üppig" to "Enkulu & intle",
    "Große Familie" to "Usapho olukhulu",
    "Große Feier" to "Umbhiyozo omkhulu",
    "Große Fenster" to "Iifestile ezinkulu",
    "Große Fensterfront" to "Ifestile enkulu ngaphambili",
    "Großer Außenpool" to "Ichibi elikhulu langaphandle",
    "Großer Garten" to "Isitiya esikhulu",
    "Großer Stein" to "Ilitye elikhulu",
    "Größere Küche" to "Ikhitshi elikhulu",
    "Gutes Essen" to "Konwabele ukutya kwakho",
    "Habe ich" to "Ndine",
    "Habe ich noch nie" to "Andizange ndibe nayo",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Ngaba ufumene umahluko omangalisayo? Thetha malunga nokuba kutheni uthanda iinketho ezithile ngcono!",
    "Haus am See" to "Indlu ngasechibini",
    "Haus/Wohnung" to "Indlu/indlu",
    "Hazelnut" to "Ihazelnut",
    "Heimkino" to "Ithiyetha yasekhaya",
    "Herzhaft" to "Intliziyo",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Akukho nto apha ngoku.\nShintsha isihluzo okanye khetha isihloko esahlukileyo.",
    "Hilfe im Alltag" to "Uncedo kubomi bemihla ngemihla",
    "Himbeere" to "irasbheri",
    "Hinzufügen" to "Yongeza",
    "Hobbys" to "Izinto azithandayo",
    "Hochzeitssträuße" to "Iintyatyambo zomtshato",
    "Hogwarts Haus Stolz: Wo gehörst du hin?" to "Hogwarts House Pride: Ungowaphi?",
    "Home" to "Ekhaya",
    "Hot Tub" to "Ithabhu eshushu",
    "Humor" to "uburharha",
    "Hund" to "Inja",
    "Hängematte" to "ihammokhi",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Ngaba ungathanda ileta ebhaliweyo njengenxalenye yesicelo?",
    "IKEA" to "I-IKEA",
    "Ich" to "I",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Ndikhetha ukuhamba ngothando epakini ukuya kwi-cinema.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Zange ndalala ecinema.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Ndiyakonwabela ukufumanisa izinto ezintsha zokuzonwabisa okanye imisebenzi kunye neqabane lam.",
    "Ich finde eine Alternative" to "Ndiza kufumana enye indlela",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Ndiyakonwabela ukuzama iindawo zokutyela ezintsha neqabane lam endaweni yokusoloko ndisiya kwindawo enye.",
    "Ich habe noch nie" to "Andizange",
    "Ich habe noch nie Angst vor einer Achterbahn gehabt und bin trotzdem eingestiegen." to "Andizange ndoyike i-roller coaster kwaye ndakhwela kuyo.",
    "Ich habe noch nie Fast-Pass-Tickets gekauft, weil ich ungeduldig war." to "Zange ndawathenga amatikiti eFast Pass kuba ndandingenamonde.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Andizange ndizirhoxise izicwangciso zokuhlala ekhaya ndibukele inkqubo yeTV.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Andizange ndilinde ileta yam evela eHogwarts.",
    "Ich habe noch nie behauptet, Slytherin sei eigentlich gar nicht so böse." to "Andizange nditsho ukuba uSlytherin wayengekho mbi kangako.",
    "Ich habe noch nie behauptet, ich sei zu alt für Disney-Filme (und es heimlich genossen)." to "Andizange ndibange ukuba ndimdala kakhulu kwiimuvi zeDisney (kwaye ndizonwabele ngasese).",
    "Ich habe noch nie bei Mario Kart absichtlich jemanden mit einem blauen Panzer abgeschossen." to "Andizange ngabom ndadubula umntu ngetanki eluhlaza eMario Kart.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Andizange ndakhala kwi-movie ye-Disney.",
    "Ich habe noch nie bei einem Horrorfilm die Augen zugehalten." to "Zange ndiwavale amehlo ndibukele imovie eyothusayo.",
    "Ich habe noch nie bei einem Spiel vergessen zu speichern und stundenlangen Fortschritt verloren." to "Andizange ndilibale ukugcina umdlalo kunye neeyure ezilahlekileyo zenkqubela phambili.",
    "Ich habe noch nie bei einer peinlichen Szene den Raum verlassen (Cringe-Faktor)." to "Andizange ndilishiye igumbi ngexesha leentloni (i-cringe factor).",
    "Ich habe noch nie beim Achterbahn-Foto eine lustige Pose gemacht." to "Andizange ndenze into ehlekisayo ngelixa ndithatha ifoto ye-roller coaster.",
    "Ich habe noch nie bis spät in die Nacht gezockt und am nächsten Tag bereut, wie müde ich war." to "Andizange ndidlale kude kube sebusuku kwaye ndazisola ngendlela endandidinwe ngayo ngosuku olulandelayo.",
    "Ich habe noch nie das Ende eines Films gegoogelt, weil ich nicht abwarten konnte." to "Andizange ndijonge isiphelo semuvi kuba andikwazanga kulinda.",
    "Ich habe noch nie das Gefühl gehabt, in einem Filmset zu stehen." to "Zange ndizive ngathi ndikwiseti yefilim.",
    "Ich habe noch nie das Intro meiner Lieblingsserie übersprungen." to "Andizange nditsibe isingeniso sothotho lwam endiluthandayo.",
    "Ich habe noch nie das Netflix-Passwort von jemand anderem mitbenutzt." to "Andizange ndabelane nge-password yeNetflix yomnye umntu.",
    "Ich habe noch nie den Soundtrack eines Spiels beim Arbeiten oder Lernen gehört." to "Andizange ndive isandi somdlalo ngelixa ndisebenza okanye ndifunda.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Andizange ndisole umlawuli xa ndilahlekile.",
    "Ich habe noch nie die Tastatur oder den Controller vor Wut weggeworfen." to "Zange ndilahle ikeyboard or controller ngumsindo.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Andizange ndiyilibale impahla emanzi kumatshini wokuhlamba iintsuku ezimbalwa.",
    "Ich habe noch nie echtes Geld für kosmetische Items in einem Spiel ausgegeben." to "Andizange ndichithe imali yokwenyani kwizinto zokuthambisa kumdlalo.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Andizange ndihambe ngemoto kwilizwe lasemzini.",
    "Ich habe noch nie ein Disney-Lied unter der Dusche geschmettert." to "Andizange ndikhuphe ingoma yeDisney kwishawari.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Andizange ndiqhube imoto yombane.",
    "Ich habe noch nie ein Foto mit einem Park-Maskottchen gemacht." to "Andizange ndithathe ifoto nge-mascot yasepaki.",
    "Ich habe noch nie ein Haustier nach einem Charakter aus Hogwarts benannt." to "Andizange ndiyithiye isilwanyana sasekhaya ngegama lomlinganiswa waseHogwarts.",
    "Ich habe noch nie ein Popcorn im Kino fallen gelassen und es trotzdem gegessen." to "Andizange ndiwise popcorn kwindawo yemiboniso bhanyabhanya kwaye ndisayityile.",
    "Ich habe noch nie ein Zitat von Meister Yoda aus Star Wars im Alltag verwendet." to "Andizange ndisebenzise isicatshulwa esivela ku-Master Yoda kwi-Star Wars kubomi bemihla ngemihla.",
    "Ich habe noch nie ein überteuertes Souvenir im Freizeitpark gekauft." to "Andizange ndithenge isikhumbuzo esixabisa kakhulu kwipaki yomxholo.",
    "Ich habe noch nie eine Film-Empfehlung gegeben, die der andere furchtbar fand." to "Andizange ndinike ingcebiso yefilimu ukuba omnye umntu wayifumanisa imbi.",
    "Ich habe noch nie eine Oscar-Verleihung live mitten in der Nacht verfolgt." to "Andizange ndibukele iOscars ezinzulwini zobusuku.",
    "Ich habe noch nie eine Serie abgebrochen, weil die letzte Staffel so schlecht war." to "Andizange ndiyirhoxise i-series kuba isizini yokugqibela ibimbi kakhulu.",
    "Ich habe noch nie eine ganze Serienstaffel an einem Tag durchgeschaut (Binge-Watching)." to "Andizange ndibukele ixesha lonke lochungechunge ngosuku olunye.",
    "Ich habe noch nie einen Boss beim ersten Versuch besiegt und mich wie ein Gott gefühlt." to "Andizange ndibethe umphathi kwi-try yokuqala kwaye ndaziva njengothixo.",
    "Ich habe noch nie einen Bösewicht cooler als den Helden gefunden." to "Andizange ndifumane i-villain epholileyo kuneqhawe.",
    "Ich habe noch nie einen Charakter aus Toy Story in meinem eigenen Spielzeug wiedererkannt." to "Andizange ndibone umlinganiswa weBali leToyi kwizinto zokudlala zam.",
    "Ich habe noch nie einen Charakter in einem RPG genau nach meinem Aussehen erstellt." to "Andizange ndidale umlinganiswa kwi-RPG esekelwe kanye kwinkangeleko yam.",
    "Ich habe noch nie einen Churro in einem Themenpark gegessen." to "Andizange ndiyitye i-churro kwi-theme park.",
    "Ich habe noch nie einen Disney-Film dreimal hintereinander geschaut." to "Andizange ndibukele imuvi yeDisney kathathu ngokulandelelana.",
    "Ich habe noch nie einen Disney-Ohrwurm für eine ganze Woche gehabt." to "Andizange ndibe neculo elimnandi likaDisney iveki yonke.",
    "Ich habe noch nie einen Film nur wegen eines bestimmten Schauspielers geschaut." to "Andizange ndibukele imuvi ngenxa nje yomdlali othile.",
    "Ich habe noch nie einen Film-Soundtrack stundenlang auf Repeat gehört." to "Andizange ndimamele isandi somboniso bhanyabhanya siphindaphindwa iiyure.",
    "Ich habe noch nie einen Film-Spoiler verraten und es sofort bereut." to "Andizange ndityhile i-spoiler ye-movie kwaye ngoko nangoko ndazisola.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Andizange ndifumane umhlobo othetha olunye ulwimi.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Andizange ndibe nomhlobo owafudukela kwelinye ilizwe.",
    "Ich habe noch nie einen Harry-Potter-Film-Marathon an Weihnachten gemacht." to "Andizange ndenze umdyarho bhanyabhanya kaHarry Potter ngeKrisimesi.",
    "Ich habe noch nie einen Marvel-Film nur wegen der Post-Credit-Scene bis zum Ende geschaut." to "Andizange ndibukele imuvi yeMarvel de kube sekupheleni ngenxa yendawo yetyala.",
    "Ich habe noch nie einen NPC (Non-Player Character) absichtlich geärgert." to "Andizange ngabom ndicaphukise i-NPC (Umlinganiswa ongeyena uMdlali).",
    "Ich habe noch nie einen Nachtzug genommen." to "Andizange ndithathe uloliwe wasebusuku.",
    "Ich habe noch nie einen Online-Test gemacht, um mein Hogwarts-Haus herauszufinden." to "Andizange ndithathe uvavanyo lwe-intanethi ukufumana indlu yam yaseHogwarts.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Andizange ndiyicime iposi yemidiya yoluntu kuba ayizange ifumane ukuthandwa ngokwaneleyo.",
    "Ich habe noch nie einen Tag im Themenpark als den besten Tag des Jahres bezeichnet." to "Andizange ndibize usuku kwipaki yomxholo usuku oluhle kakhulu lonyaka.",
    "Ich habe noch nie einen Themenpark besucht und von morgens bis abends durchgehalten." to "Andizange ndindwendwele ipaki yomxholo kwaye ndihlala apho ukusuka kusasa ukuya ebusuku.",
    "Ich habe noch nie einen Transformers- oder Marvel-Ride völlig fasziniert verlassen." to "Andizange ndishiye iTransformers okanye iMarvel ikhwele iphazamiseke ngokupheleleyo.",
    "Ich habe noch nie einen Wutanfall bekommen (Rage Quit) und das Spiel beendet." to "Andizange ndiphose umsindo (Rage Quit) kwaye ndiyeke umdlalo.",
    "Ich habe noch nie einen der dicken Harry Potter Bände gelesen." to "Andizange ndifunde naziphi na iincwadi ezinkulu zikaHarry Potter.",
    "Ich habe noch nie für meinen Lieblingscharakter in einer Serie geschwärmt." to "Andizange ndakhe ndadlalisa ngomlinganiswa endimthandayo kuthotho.",
    "Ich habe noch nie geträumt, Quidditch zu spielen." to "Andizange ndiphuphe ngokudlala iQuidditch.",
    "Ich habe noch nie heimlich gegoogelt, wie man ein schweres Level löst." to "Andizange ndifihle google indlela yokusombulula inqanaba elinzima.",
    "Ich habe noch nie heimlich gehofft, dass mein Haustier sprechen kann wie bei Disney." to "Andizange ndithembe ngasese ukuba isilwanyana sam singathetha njengokuba benza eDisney.",
    "Ich habe noch nie in Sims den Pool-Leiter entfernt." to "Andizange ndiyisuse ileli yepool eSims.",
    "Ich habe noch nie in einem 3D-Simulator-Ride die Orientierung verloren." to "Andizange ndiphulukane neebheringi zam kuhambo lwe-3D simulator.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Andizange ndadlala kwiqela lezemidlalo laseyunivesithi.",
    "Ich habe noch nie mehr als zwei Stunden für eine einzige Attraktion angestanden." to "Andizange ndilinde emgceni isithuba esingaphezu kweeyure ezimbini ukuze ndibe nomtsalane omnye.",
    "Ich habe noch nie meine Wertsachen bei einer Wasserbahn nass gemacht." to "Andizange ndifumane izinto zam zexabiso ezimanzi xa ndihamba ngamanzi.",
    "Ich habe noch nie mit einem Freund gestritten, welches Haus das beste ist." to "Andizange ndixabane nomhlobo wam malunga nokuba yeyiphi indlu egqwesileyo.",
    "Ich habe noch nie so getan, als hätte ich Zauberkräfte wie Elsa." to "Zange ndizenze ngathi ndinamandla omlingo njengoElsa.",
    "Ich habe noch nie so laut gelacht, dass ich eine wichtige Film-Szene verpasst habe." to "Andizange ndihleke kakhulu kangangokuba ndaphoswa ngumboniso obalulekileyo kwimuvi.",
    "Ich habe noch nie so viel Adrenalin gespürt, dass ich direkt nochmal fahren wollte." to "Andizange ndibe ne-adrenaline eninzi kangangokuba ndafuna ngokukhawuleza ukukhwela kwakhona.",
    "Ich habe noch nie versucht, mit Tieren zu singen wie Schneewittchen." to "Andizange ndizame ukucula nezilwanyana ezifana ne-Snow White.",
    "Ich habe noch nie von einem Ausflug ins Disneyland geträumt." to "Andizange ndiphuphe uhambo oluya eDisneyland.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Andizange ndiphuphe ngokukhwela amanzi eJurassic Park.",
    "Ich habe noch nie vor einem Jump-Scare im Spiel laut geschrien." to "Andizange ndikhale kakhulu kukoyika ukutsiba emdlalweni.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Andizange ndikhale ngokugqitywa komdlalo kamabonakude.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Andizange...ndirhoxise usuku lokuhlala ekhaya.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Andizange... ndiphinde ndaguqulela umyalezo izihlandlo ezili-10.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Zange...ndajonga iphone yeqabane lam emfihlakalweni.",
    "Ich habe noch nie!" to "Andizange!",
    "Ich habe!" to "Ndine!",
    "Ich lache viel mit meinem Partner." to "Ndihleka kakhulu neqabane lam.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Ndiyathanda ukwazi izinto ezithandwa liqabane lam kunye nezinto anomdla kuzo.",
    "Ich liebe es" to "Ndiyayithanda",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Ndiyakuthanda ukubukela iimuvi neqabane lam ekungekho namnye kuthi owake wazibona ngaphambili.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Ndiyakuthanda ukwabelana nomculo wam endiwuthandayo kunye neqabane lam.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Zange kufuneke ndibaleke ukuze ndibambe inqwelomoya exhumayo.",
    "Ich plane gerne Dates mit meinem Partner." to "Ndiyayithanda imihla yokucwangcisa kunye neqabane lam.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Ndibeka phambili ixesha endilichitha neqabane lam nokuba ndixakekile.",
    "Ich schreibe meinem Partner jeden Tag." to "Ndibhalela iqabane lam yonke imihla.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Ndiyathanda ukwabelana ngeememes kunye neziqhulo kunye neqabane lam.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Ndiyathanda ukwabelana ngazo zonke iinkcukacha zosuku lwam kunye neqabane lam.",
    "Ich würde es nie tun" to "Andisoze ndiyenze",
    "Ich übe noch" to "Ndisazilolonga",
    "Ideen generieren" to "Velisa izimvo",
    "Im Haushalt helfen" to "Uncedo malunga nendlu",
    "In Chat einfügen" to "Yongeza kwincoko",
    "In Stille nebeneinander" to "Kwathi cwaka ecaleni komnye",
    "In den Bergen" to "Ezintabeni",
    "In eine Bar gehen" to "Yiya kwibhari",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Ukuya kwibar yaselwandle ukuze ubukele ukutshona kwelanga",
    "In einem feinen Restaurant essen gehen" to "Ukutya kwindawo yokutyela elungileyo",
    "In einen Coffeeshop gehen" to "Yiya kwivenkile yekofu",
    "In einer Beziehung sollte man alles voneinander wissen." to "Kubudlelwane kufuneka wazi yonke into omnye komnye.",
    "Infinity-Pool" to "Infinity pool",
    "Innenpool" to "Iphuli yangaphakathi",
    "Intelligenz" to "ubukrelekrele",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Ukuba namaxesha asondeleleneyo kuphela xa iqabane lakho liwasungula",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Ikhowudi yokumema: HRM-8731 · yonke into ivuliwe",
    "Island" to "Ayisilend",
    "Ist okay für mich" to "Kulungile kum",
    "Ist schon perfekt" to "Sele igqibelele",
    "Ja, Traditionen einbinden" to "Ewe, bandakanya izithethe",
    "Ja, absolut" to "Ewe, ngokupheleleyo",
    "Ja, etwas zum Lesen und Aufbewahren" to "Ewe, kukho into yokufunda nokugcina",
    "Ja, genug" to "Ewe, ngokwaneleyo",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Ewe, kwisixeko esinomdla okanye umtsalane",
    "Ja, in- und auswendig" to "Ewe, ngaphakathi nangaphandle",
    "Ja, komplett überraschend" to "Ewe, imangalisa ngokupheleleyo",
    "Ja, perfekt" to "Ewe, igqibelele",
    "Ja, sie gehören zur Familie!" to "Ewe, bayintsapho!",
    "Ja, sofort teilen" to "Ewe, yabelana ngoko nangoko",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Ewe, siya kuqinisekisa ukuba ixesha lentsapho libalulekile.",
    "Jacuzzi" to "IJacuzzi",
    "Jahr zusammen 🎉" to "unyaka kunye 🎉",
    "Jahre zusammen 🎉" to "Iminyaka kunye 🎉",
    "Jeder zahlt 50%" to "Wonke umntu ubhatala 50%",
    "Junge" to "Inkwenkwe",
    "Kamin" to "Itshimini",
    "Karriere & Erfolg" to "Umsebenzi & Impumelelo",
    "Kategorien" to "Iindidi",
    "Katze" to "Ikati",
    "Keine Musik" to "Akukho mculo",
    "Keine Party nötig, privat halten" to "Akukho qela liyimfuneko, ligcine ngasese",
    "Keine Privatsphäre" to "Akukho mfihlo",
    "Keine Treffer gefunden" to "Akukho ziphumo zifunyenweyo",
    "Keiner" to "Akukho nanye",
    "Keiner von uns" to "Akukho namnye kuthi",
    "Kennst du die Essensvorlieben deines Partners?" to "Ngaba uyazazi izinto ezikhethwa liqabane lakho?",
    "Kino" to "icinema",
    "Kirchlich" to "Icawa",
    "Klassisch Solitär" to "Classic solitaire",
    "Klassisch gebunden" to "Ibotshelelwe ngokwesiko",
    "Klein & zart" to "Incinci kwaye ithambile",
    "Kleine Geschenke" to "Izipho ezincinci",
    "Kleine Runde" to "Umjikelo omncinci",
    "Kochen und Freunde einladen" to "Pheka kwaye umeme abahlobo",
    "Kochkurs" to "Iklasi yokupheka",
    "Kommt auf den Tag an" to "Kuxhomekeke kumhla",
    "Kommt darauf an" to "Ixhomekeke ku",
    "Kommt drauf an" to "Kuyaxhomekeka",
    "Kommt mit" to "Yiza nama",
    "Konzert" to "ikonsathi",
    "Kräftige Farben" to "Imibala eyomeleleyo",
    "Kräuterbeet" to "Ibhedi yemifuno",
    "Kultur & Sehenswürdigkeiten" to "INkcubeko kunye neMibono",
    "Kuscheln" to "Cuddle",
    "Kuss senden" to "Thumela ukwanga",
    "Körperliche Annäherung" to "Indlela yokwenza izinto ngokwasemzimbeni",
    "Körperliche Nähe" to "Ukusondelelana ngokwasemzimbeni",
    "Küche" to "Ikhitshi",
    "Land" to "ilizwe",
    "Landhaus" to "indlu yelizwe",
    "Landhausstil" to "Isimbo selizwe",
    "Lange wach bleiben" to "Hlala uphaphile emva kwexesha",
    "Lappland" to "Lapland",
    "Lappland, Finnland" to "Lapland, eFinland",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Vumela iqabane lakho likukhuthaze ukuba ube ngoyena mntu ulungileyo",
    "Lehne ab" to "Yala",
    "Leichtigkeit" to "ukukhululeka",
    "Leidenschaft" to "Umdla",
    "Liebe im Gleichgewicht" to "Uthando ngokulinganisela",
    "Liebe sie, macht mehr Spaß" to "Bathande, kumnandi ngakumbi",
    "Lieber durchgeplant oder spontan?" to "Ungathanda ukuyicwangcisa okanye izenzekele?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Ungathanda ukuba nengokuhlwa ezolileyo yababini okanye nabantu?",
    "Lieber nicht" to "Endaweni yoko",
    "Lieber vorher grob absprechen" to "Kungcono ukuxoxa kwangaphambili",
    "Lokal einkaufen" to "Thenga ekuhlaleni",
    "London" to "eLondon",
    "London, England" to "eLondon, eNgilani",
    "Lügen" to "Ubuxoki",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Ngaba ukhetha isindululo sikawonke-wonke okanye sabucala?",
    "Malediven" to "Maldivs",
    "Man sollte nie streitend einschlafen." to "Ungaze ulale nixambulisana.",
    "Mango Sorbet" to "Mango sorbet",
    "Markant & breit" to "Ukubetha & banzi",
    "Marken & Alltag" to "Brands & ubomi bemihla ngemihla",
    "McDonald’s" to "McDonald's",
    "Mediterraner Innenhof" to "Intendelezo yeMeditera",
    "Mehr Unterstützung" to "Inkxaso engakumbi",
    "Mehr gemeinsame Zeit" to "Ixesha elingakumbi kunye",
    "Mehr zuhören" to "Mamela ngakumbi",
    "Mehrgenerationenhaus" to "Indlu yezizwe ngezizwe",
    "Mein Arbeitsplatz" to "Indawo yam yokusebenza",
    "Mein Partner" to "Iqabane lam",
    "Mich überraschen" to "Ndothuse",
    "Minimalistisches Interieur" to "Minimalist yangaphakathi",
    "Missverständnisse" to "Ukungaqondi kakuhle",
    "Mit Familie und engen Freunden" to "Kunye nosapho kunye nabahlobo abasenyongweni",
    "Mit Kompromissen" to "Ngokuvumelana",
    "Mitgefühl" to "uvelwano",
    "Mittelweg mit besonderen Details" to "Umhlaba ophakathi oneenkcukacha ezikhethekileyo",
    "Modern geometrisch" to "Ijometri yanamhlanje",
    "Moderne Grillstation" to "Isikhululo segrill sanamhlanje",
    "Moderner Name" to "Igama langoku",
    "Moderner Solitär" to "I-solitaire yanamhlanje",
    "Moissanit" to "Moissanite",
    "Moment festhalten" to "Thatha umzuzu",
    "Momente" to "imizuzu",
    "Monaco" to "Monakho",
    "Moralische Werte" to "Imilinganiselo yokuziphatha",
    "Museum" to "imyuziyam",
    "Musik" to "Umculo",
    "Mut" to "isibindi",
    "Mädchen" to "Ntombazana",
    "Möbelhaus" to "Ivenkile yefenitshala",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Ngaba ngokwenene ufuna ukuyishiya imibuzo? Inkqubela yakho yangaphambili ihleli igciniwe.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Ngaba ungathanda ukuba izilwanyana zasekhaya zibandakanywe kwisicelo?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Ngaba ufuna umzuzu wokwabelwana ngawo kwimidiya yoluntu ngokukhawuleza?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Kusenokufuneka senze ukonga",
    "Müssen es planen" to "Kufuneka uyicwangcise",
    "Müssen sparen" to "Kufuneka ugcine",
    "Nachricht an" to "Umyalezo oya ku",
    "Name Partnerin" to "Igama lomlingane",
    "Namen und Startdatum eurer Beziehung." to "Igama kunye nomhla wokuqala wobudlelwane bakho.",
    "Natursteinfassade" to "I-facade yamatye yendalo",
    "Naturteich" to "Idama lendalo",
    "Nein, einfach halten" to "Hayi, yibambe nje",
    "Nein, erstmal privat halten" to "Hayi, yigcine bucala okwangoku",
    "Nein, lieber vor Ort" to "Hayi, ngcono kwisiza",
    "Nein, modern halten" to "Hayi, yigcine ngokwale mihla",
    "Nein, nur wir" to "Hayi, thina kuphela",
    "Nein, zu ablenkend" to "Hayi, iyaphazamisa kakhulu",
    "Netflix" to "Netflix",
    "Neubau mit Smart Home" to "Isakhiwo esitsha esinekhaya elikrelekrele",
    "Neubau mit Technik" to "Isakhiwo esitsha ngeteknoloji",
    "Neue Liebe, neue Erfahrungen" to "Uthando olutsha, amava amatsha",
    "Neues Hobby" to "Ukuzonwabisa okutsha",
    "Neues Spiel" to "Umdlalo omtsha",
    "Neugier" to "umdla",
    "New York" to "inew York",
    "New York, USA" to "ENew York, eU.SA",
    "Nicht mein Fall" to "Ayilotyala lam",
    "Nicht nötig, lieber klassisch bleiben" to "Akuyomfuneko, kungcono ukuhlala classic",
    "Nichts — es passt so" to "Akukho nto - ingena ngolo hlobo",
    "Nie wieder Burger" to "Ungaze uphinde ube neebhega",
    "Nie wieder Pizza" to "Ungaze uphinde ube yipizza",
    "Niemand" to "Akukho namnye",
    "Niemand ohne Plan" to "Akukho mntu ungenalo icebo",
    "Nike" to "Nike",
    "Nizza" to "Intle",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Akukho mzuzu okwangoku.\nBamba amava akho okuqala 💞",
    "Nur bei wichtigen Themen" to "Kuphela kwizihloko ezibalulekileyo",
    "Nur wir beide" to "Sisobabini nje",
    "Nähe & Intimität" to "Ukusondelana kunye nokusondelana",
    "Obstgarten" to "igadi yeziqhamo",
    "Oder" to "Okanye",
    "Offene Küche" to "Vula ikhitshi",
    "Offene Wohnküche" to "Vula ikhitshi / igumbi lokuhlala",
    "Ohne Stein" to "Ngaphandle kwelitye",
    "Open End" to "Vula isiphelo",
    "Outdoor-Küche" to "Ikhitshi langaphandle",
    "Outdoor-Sofa" to "Isofa yangaphandle",
    "Outdoor-Whirlpool" to "Ibhafu eshushu yangaphandle",
    "Ovaler Diamant" to "Idayimani embhoxo",
    "Paar" to "Isibini",
    "Paar-Statistiken" to "Izibalo-manani ezimbini",
    "Paris" to "EParis",
    "Paris, Frankreich" to "EParis, eFransi",
    "Partner" to "iqabane",
    "Partner-Simulator" to "Isifanisi somlingani",
    "Partnerin" to "iqabane",
    "Party Edition" to "Uhlelo lweqela",
    "Party Edition II" to "Party Edition II",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Ngaba isilwanyana singena kubomi bethu bemihla ngemihla?",
    "Pasta" to "ipasta",
    "Pastell" to "Pastel",
    "Penthouse mit Ausblick" to "Penthouse ngombono",
    "Pepsi" to "Pepsi",
    "Pergola mit Lounge" to "I-Pergola enendawo yokuphumla",
    "Pfingstrosen" to "Iipeonies",
    "Pinguin" to "ipenguin",
    "Pistazie" to "ipistachio",
    "Pizza" to "ipizza",
    "Pizzaofen" to "I-oveni yepizza",
    "Platin" to "iplatinam",
    "PlayStation" to "Isikhululo sokudlala",
    "Pool" to "ichibi",
    "Pop" to "pop",
    "Prasselnder Kamin" to "Iziko eligqumayo",
    "Prinzessinnen, Piraten und Feenstaub: Disney-Quiz" to "Iinkosazana, amaPirates kunye nothuli lweNtsomi: Disney Quiz",
    "Privater Innenhof" to "Intendelezo yabucala",
    "Profil" to "iprofayile",
    "Profil bearbeiten" to "Hlengahlengisa iprofayile yakho",
    "Prozentual nach Einkommen" to "Ipesenti esekelwe kwingeniso",
    "Quiz verlassen" to "Shiya imibuzo",
    "Quiz verlassen?" to "Yeka ikhwizi?",
    "Rausgehen in die Natur" to "Phuma uye kwindalo",
    "Reden vor ..." to "Iintetho phambi...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Cwangcisa imihla eqhelekileyo okanye ixesha kunye",
    "Reisen" to "Ukuhamba",
    "Reiseziele" to "Iindawo ekuya kuzo",
    "Respektlosigkeit" to "ukungabi nantlonipho",
    "Restaurant" to "yokutyela",
    "RnB / Soul" to "RnB/Umphefumlo",
    "Rock" to "iliwa",
    "Rom" to "eRoma",
    "Rom, Italien" to "eRoma, eItali",
    "Romantik" to "uthando",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Izijekulo zothando njengemiyalezo, amanqaku okanye izipho ziyandonwabisa.",
    "Romantische Stimmung" to "Umoya wothando",
    "Roségold" to "Igolide eRose",
    "Ruhig zu zweit" to "Kuthuleke kabini",
    "Runder Diamant" to "Idayimani engqukuva",
    "Salted Caramel" to "I-caramel enetyuwa",
    "Sammle Ideen..." to "Qokelela izimvo...",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, eGrisi",
    "Saphir" to "isafire",
    "Saunahaus" to "Indlu ye-sauna",
    "Schickes Restaurant oder Hotel" to "Indawo yokutyela yeChic okanye ihotele",
    "Schlafzimmer" to "igumbi lokulala",
    "Schließen" to "Vala",
    "Schmal & zart" to "Ibhityile kwaye ithambile",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Iifoto ezivela kwibali lethu lothando",
    "Schokolade" to "Itshokholethi",
    "Schreib frei, was dir wirklich dazu einfällt." to "Bhala ngokukhululekileyo into ethi qatha engqondweni.",
    "Schreibe deine eigene Antwort" to "Bhala eyakho impendulo",
    "Sehr gerne" to "Ngovuyo olukhulu",
    "Sehr leicht" to "Ukukhanya kakhulu",
    "Sehr wichtig — Fotos und Video" to "Kubaluleke kakhulu - iifoto kunye nevidiyo",
    "Sehr wichtig, es sollte persönlich sein" to "Okubaluleke kakhulu, ifanele ibe yeyobuqu",
    "Selbst kochen" to "Ziphekele",
    "Senden" to "Thumela",
    "Separate Küche" to "Ikhitshi elahlukileyo",
    "Serie schauen" to "Bukela uthotho",
    "Serienmarathon auf dem Sofa" to "Series marathon esofeni",
    "Sex & Liebe" to "Isondo & Uthando",
    "Seychellen" to "Seytshels",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Ngaba siyakwazi ukuhlawula zonke iindleko zomntwana omnye/abantwana abaninzi? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Ngaba isiphakamiso kufuneka sibe yinto emangalisayo?",
    "Sollte der Antrag kulturelle oder traditionalle Elemente enthalten?" to "Ngaba isicelo kufuneka siqulathe izinto zenkcubeko okanye zemveli?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Ngaba isicelo kufuneka siqulathe izinto zenkcubeko okanye zemveli?",
    "Sommerhochzeit" to "Umtshato wasehlotyeni",
    "Sonnige Dachterrasse" to "Ithafa eliseluphahleni elinelanga",
    "Sowohl als auch" to "Njengo",
    "Spazieren" to "Skrola",
    "Spaß & Abenteuer" to "Ulonwabo & Uhambo",
    "Speichern" to "Gcina",
    "Spiel bearbeiten" to "Hlela umdlalo",
    "Spielbereich für Kinder" to "Indawo yokudlala yabantwana",
    "Spiele" to "imidlalo",
    "Spiele spielen und Spaß haben" to "Dlala imidlalo kwaye wonwabe",
    "Spontan" to "Ngokuzenzekelayo",
    "Sportplatz" to "Ibala lezemidlalo",
    "Spotify" to "Spotify",
    "Sprache" to "Ulwimi",
    "Stadt" to "Isixeko",
    "Stadt oder Land — was ist uns wichtiger?" to "Isixeko okanye ilizwe – yintoni eyona nto ibalulekileyo kuthi?",
    "Stadtvilla" to "Indlu yedolophu",
    "Standesamt & Party" to "Iofisi yobhaliso kunye neqela",
    "Statement-Ring" to "Ingxelo ring",
    "Stilvolles Outdoor-Sofa" to "Isofa yangaphandle enesitayile",
    "Stimme voll zu" to "Ndivuma ngokupheleleyo",
    "Stimmt" to "Yinyani",
    "Stimmt nicht" to "Ayonyani",
    "Stimmt, noch nie" to "Injalo, soze",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Usuku lolwandle",
    "Streit über Haushalt" to "Ingxabano ngekhaya",
    "Studio Ghibli" to "Studio Ghibli",
    "Ständig" to "rhoqo",
    "Suche schließen" to "Vala uphendlo",
    "Suche zurücksetzen" to "Lungisa uphendlo",
    "Suche öffnen" to "Vula uphendlo",
    "Suchergebnisse" to "Iziphumo zokukhangela",
    "Sushi" to "Sushi",
    "Süß" to "Sweet",
    "Tage zusammen 💞" to "Iintsuku kunye 💞",
    "Tauche ins Unterbewusstsein" to "Ngena kwi-subconscious",
    "Teile alle deine Hobbys mit deinem Partner" to "Yabelana ngazo zonke izinto ozonwabisa ngazo neqabane lakho",
    "Teils teils" to "Ngokuyinxenye",
    "Testen" to "Uvavanyo",
    "Themen" to "Izihloko",
    "Tiefe Gespräche" to "Iincoko ezinzulu",
    "Tiefgründige Gespräche führen" to "Yiba neencoko ezinzulu",
    "Tierpension" to "Indawo yokuhlala yezilwanyana",
    "Tiny House" to "Indlu encinci",
    "Tippen zum Auswählen & Scrollen" to "Cofa ukukhetha & uskrola",
    "Tippen zum Zuklappen" to "Cofa ukuze uvale",
    "Titel" to "isihloko",
    "Titel, Kategorie, Thema, Tags, Fragen..." to "Isihloko, Udidi, Umxholo, Iithegi, Imibuzo...",
    "Tokyo, Japan" to "ETokyo, eJapan",
    "Traditioneller Name" to "Igama lemveli",
    "Traumhaus Außenbereich" to "Phupha indawo yangaphandle yendlu",
    "Traumhochzeit" to "Umtshato wokuphupha",
    "Treffer" to "Betha",
    "Tägliche Aktivität" to "Umsebenzi wemihla ngemihla",
    "Umformulieren" to "Phinda uchaze",
    "Unbeantwortet" to "Akaphendulwa",
    "Unbeliebte Meinungen" to "Izimvo ezingathandwayo",
    "Universal Studios Genie oder Neuling?" to "Ingqondi kwi-Universal Studios okanye i-wbie?",
    "Uns auseinanderzuleben" to "Ukukhula ngokwahlukeneyo",
    "Unser Intimleben" to "Ubomi bethu obusondeleyo",
    "Unser Traumhaus" to "Indlu yethu yamaphupha",
    "Unser erstes Treffen" to "Intlanganiso yethu yokuqala",
    "Unsere Gesichter" to "Ubuso bethu",
    "Unsere eigenen Träume" to "Amaphupha ethu",
    "Unsere nächste Reise" to "Uhambo lwethu olulandelayo",
    "Unter 1000" to "Ngaphantsi kwe-1000",
    "Unter 1000 im Monat" to "Ngaphantsi kwe-1000 ngenyanga",
    "Unter 50€/Monat" to "Ngaphantsi kwe-50 € / ngenyanga",
    "Unter Leuten" to "Phakathi kwabantu",
    "Untreue" to "ukungathembeki",
    "Urlaub" to "Ikhefu",
    "Vanille" to "Ivanila",
    "Venedig" to "eVenice",
    "Venedig, Italien" to "IVenice, eItali",
    "Verbinde dich mit" to "Qhagamshelana ne",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Qhagamshela ku \${profile.partnerName} ukubona impendulo",
    "Verbindung" to "Uqhagamshelwano",
    "Verbringe die Feiertage mit deiner Familie" to "Chitha iiholide kunye nosapho lwakho",
    "Verlobungsringe" to "Amakhonkco othethathethwano",
    "Vertrautheit" to "ukuqhelana",
    "Viel getrennt" to "Yahlukene kakhulu",
    "Vielleicht ein oder zwei" to "Mhlawumbi enye okanye ezimbini",
    "Vielleicht, aber mündlich reicht" to "Mhlawumbi, kodwa ngomlomo kwanele",
    "Vielleicht, wenn es machbar ist" to "Mhlawumbi, ukuba kunokwenzeka",
    "Vielleicht, wenn es passt" to "Mhlawumbi, ukuba iyalingana",
    "Vintage Art déco" to "IVintage Art Deco",
    "Vintage verspielt" to "Ukudlala kwangaphambili",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Ukwaziswa kwizinto ezintsha zokuzonwabisa liqabane lakho",
    "Vor dem Kauf eines Hauses besprechen" to "Xoxani phambi kokuthenga indlu",
    "Vor der Anschaffung eines Haustiers besprechen" to "Xoxani phambi kokuthenga isilwanyana sasekhaya",
    "Vor der gemeinsamen Reise besprechen" to "Xoxani phambi kokuba nihambe kunye",
    "Vor nichts" to "Akukho nto",
    "Vorort" to "ihlomela ledolophu",
    "Walnuss" to "iwalnut",
    "Wandern" to "Ukunyuka",
    "Wann fühlst du dich mir am nächsten?" to "Uziva usondele nini kum?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Xa uziva usondele kum ngokwasemzimbeni?",
    "Was bedeutet Vertrauen für dich konkret?" to "Kuthetha ntoni ukuthembela kuwe ngokukodwa?",
    "Was entspannt dich mehr?" to "Yintoni ekuphumza ngakumbi?",
    "Was fehlt dir über die Distanz am meisten?" to "Yintoni oyikhumbulayo kakhulu malunga nomgama?",
    "Was gefällt dir an deinem Zuhause am besten?" to "Yintoni oyithanda kakhulu ngekhaya lakho?",
    "Was hast du von deinem Partner gelernt?" to "Ufunde ntoni kwiqabane lakho?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Ucinga ntoni ngokubukela umxholo ovuselela inkanuko kunye?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Ucinga ntoni malunga nezixhaso (umz. iimpawu, iibhaluni, njl.)?",
    "Was ist das Wichtigste beim Antrag?" to "Yeyiphi eyona nto ibalulekileyo xa ufaka isicelo?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Yeyiphi eyona nto ibalulekileyo oyijongayo xa udibana ngesondo?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Yeyiphi ifoto oyithandayo kuthi? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Loluphi olona loyiko lwakho ngokuhlala kunye?",
    "Was ist ein Essen, das du liebst, dein Partner aber nicht verstehen kann?" to "Yintoni ukutya okuthandayo kodwa iqabane lakho alikuqondi?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Yintoni i-dealbreaker epheleleyo kuwe?",
    "Was ist für jeden von uns das absolute Highlight?" to "Yeyiphi eyona nto ibalulekileyo kuye ngamnye wethu?",
    "Was ist passiert?" to "Kweneke ntoni?",
    "Was macht einen Moment für dich romantisch?" to "Yintoni eyenza umzuzu wothando kuwe?",
    "Was magst du an deinem Partner am liebsten?" to "Yintoni oyithanda kakhulu ngeqabane lakho?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Ukhetha ntoni: ukuvuka kusasa okanye ukuhlala kude kube sebusuku?",
    "Was magst du lieber?" to "Yintoni oyithanda ngcono?",
    "Was möchtest du eigentlich sagen?" to "Ufuna ukuthini kanye kanye?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Yintoni ongathanda ukuba iqabane lakho lenze rhoqo?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Kwenzeka ntoni kwisilwanyana xa sihamba?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Kuza kwenzeka ntoni ngomntwana wethu xa sele ekhulile?",
    "Was sollten wir als Eltern niemals aus den Augen verlieren?" to "Yintoni esingamele siyilibale njengabazali?",
    "Was war dein schönster Moment mit mir bisher?" to "Ngowuphi umzuzu ongcono kunam ukuza kuthi ga ngoku?",
    "Was wir gegessen haben" to "Satya ntoni",
    "Was wollt ihr nie vergessen?" to "Yintoni ongasoze ufune ukuyilibala?",
    "Was wäre für dich schlimmer: nie wieder Pizza oder nie wieder Burger?" to "Yintoni eya kuba mbi kuwe: ungaze uphinde ube yi-pizza okanye ungaze uphinde ube neebhega kwakhona?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Yintoni ongathanda ukuyenza ngosuku kunye?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Yintoni obuya kuyitshintsha ngokukhawuleza ukuba imali ibingeyongxaki?",
    "Weiter" to "Ngokubhekele phaya",
    "Weiter spielen" to "Qhubeka udlala",
    "Weiß ich noch nicht" to "andazi okwangoku",
    "Weiße Rosen" to "Iirozi ezimhlophe",
    "Weißgold" to "Igolide emhlophe",
    "Welche Eigenschaft sollte unser Kind unbedingt von uns mitbekommen?" to "Luluphi uphawu afanele alufumane ngokuqinisekileyo umntwana wethu kuthi?",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Yeyiphi imeko-bume ongayifuna kwisindululo?",
    "Welcher Raum sagt am meisten über dich aus?" to "Leliphi igumbi elithetha kakhulu ngawe?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Loluphi uhlahlo lwabiwo-mali esilucwangcisela ukutya kunye nogqirha wezilwanyana?",
    "Welches Lied macht dich an? 🥵" to "Yeyiphi ingoma ekuvulela yona? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Yeyiphi ifoto kunye oyithandayo?",
    "Wellnessbad" to "Ukuhlamba impilo",
    "Wenn es schwierig ist" to "Xa izinto zinzima",
    "Wenn ich müde bin" to "Xa ndidiniwe",
    "Wenn wir uns lange umarmen" to "Xa siwolana ixesha elide",
    "Wenn wir zusammen lachen" to "Xa sihleka kunye",
    "Wer entscheidet bei euch schneller, was bestellt wird?" to "Ngubani owenza isigqibo ngokukhawuleza ukuba makayiodole ngantoni?",
    "Wer findet die besten Restaurants?" to "Ngubani ofumana eyona ndawo yokutyela?",
    "Wer gibt mehr Herzlichkeit?" to "Ngubani onika ukufudumala ngakumbi?",
    "Wer hat den besseren Musikgeschmack?" to "Ngubani owuthanda ngcono umculo?",
    "Wer hängt mehr an seinen Eltern?" to "Ngoobani abasondele ngakumbi kubazali babo?",
    "Wer ist besser organisiert?" to "Ngubani olungelelaniswe ngcono?",
    "Wer ist der Beste bei der Filmauswahl?" to "Ngubani oyena ubalaseleyo ekukhetheni iifilimu?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Ngubani oyena ulungileyo ekucwangciseni imihla yothando?",
    "Wer ist der beste Tänzer?" to "Ngubani oyena mdanisi ubalaseleyo?",
    "Wer ist romantischer?" to "Ngubani othandana kakhulu?",
    "Wer kocht besser?" to "Ngubani opheka ngcono?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Ngubani onyamekela ukulungiswa nokugcinwa?",
    "Wer merkt schneller, wenn es dem anderen nicht gut geht?" to "Ngubani oqaphela ngokukhawuleza xa omnye umntu engaphilanga?",
    "Wer sucht am Ende wirklich den Film aus?" to "Ngubani ngokwenene okhetha ifilimu ekugqibeleni?",
    "Wer vergisst eher einen Jahrestag?" to "Ngubani onokuthi alibale isikhumbuzo?",
    "Wer würde eher am nächsten Morgen seinen eigenen Namen vergessen?" to "Ngoobani abanokuthi balibale igama labo ngentsasa elandelayo?",
    "Wer würde eher am nächsten Tag ein Video finden, von dem er nichts mehr wusste?" to "Ngubani onokuthi afumane ividiyo ngosuku olulandelayo abangasaziyo?",
    "Wer würde eher auf dem Sofa eines Fremden übernachten?" to "Ngubani onokuchitha ubusuku kwisofa yomntu angamaziyo?",
    "Wer würde eher auf der Party einschlafen und mit Edding im Gesicht aufwachen?" to "Ngubani onokuthi alale ethekweni aze avuke kunye noSharpie ebusweni babo?",
    "Wer würde eher auf der Tanzfläche ausrutschen, es aber wie einen coolen Move aussehen lassen?" to "Ngubani onokuthi atyibilike kumgangatho wokudanisa kodwa awenze abukeke njengentshukumo epholileyo?",
    "Wer würde eher auf einer Hausparty die Kontrolle über die Spotify-Playlist an sich reißen?" to "Ngubani onokuthi alawule uluhlu lwadlalwayo lweSpotify kwitheko lasekhaya?",
    "Wer würde eher auf einer Party Pizza für alle bestellen und sie selbst aufessen?" to "Ngubani onokuthi aodole ipizza kumntu wonke epatini kwaye azitye ngokwakhe?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Ngubani onokuthi alale kuqala ethekweni?",
    "Wer würde eher auf einer Party plötzlich anfangen aufzuräumen?" to "Ngubani onokuthi ngokukhawuleza aqalise ukucoca kwitheko?",
    "Wer würde eher behaupten, komplett nüchtern zu sein, während das Gegenteil der Fall ist?" to "Ngubani onokuthi akanxilanga ngokupheleleyo xa kuyinyaniso okwahlukileyo koko?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Ngubani odla ngokunikezela kuqala kwingxabano?",
    "Wer würde eher bei einem Trinkspiel betrügen?" to "Ngubani onokuqhatha kumdlalo wokusela?",
    "Wer würde eher das Buffet plündern und heimlich Essen mit nach Hause nehmen?" to "Ngubani onokuthi agqogqe i-buffet aze agoduke nokutya ngokufihlakeleyo?",
    "Wer würde eher das peinlichste Foto des Abends in seiner Story posten?" to "Ngubani onokuthi athumele eyona foto ihlazo yangorhatya kwibali labo?",
    "Wer würde eher den DJ nerven, um den eigenen Lieblingssong zu wünschen?" to "Ngubani onokucaphukisa u-DJ ukuba acele ingoma yakhe ayithandayo?",
    "Wer würde eher den Text eines Songs falsch mitsingen, aber voller Überzeugung?" to "Ngubani onokuthi acule amazwi engoma ngaphandle kwesitshixo, kodwa ngokuqiniseka?",
    "Wer würde eher den teuersten Drink auf der Karte bestellen und es bereuen?" to "Ngubani onokuthi aodole esona siselo sibiza kakhulu kwimenyu kwaye azisole?",
    "Wer würde eher die Nachbarn einladen, wenn sie sich über den Lärm beschweren?" to "Ngoobani ebenokumema abamelwane xa bekhalazela loo ngxolo?",
    "Wer würde eher die Party-Spiele (wie Beer Pong) viel zu ernst nehmen?" to "Ngubani onokuthi athathe imidlalo yepati (efana ne-pong yebhiya) ngokubaluleke kakhulu?",
    "Wer würde eher die Türsteher anfreunden, um VIP-Zugang zu bekommen?" to "Ngubani onokuba ngumhlobo wee-bouncers ukufumana ukufikelela kwi-VIP?",
    "Wer würde eher ein spontanes Karaoke-Battle starten?" to "Ngubani onokuthi aqalise umlo wekaraoke we-impromptu?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Ngubani onokuvula ibhotile ngaphandle kokusebenzisa isivuli seebhotile?",
    "Wer würde eher eine Rede halten, obwohl absolut niemand danach gefragt hat?" to "Ngubani obeya kunikela intetho nangona kungekho mntu ubuzayo?",
    "Wer würde eher eine Stunde im Badezimmer verbringen, um Selfies zu machen?" to "Ngubani onokuchitha iyure kwigumbi lokuhlambela ethatha ii-selfies?",
    "Wer würde eher eine peinliche Tanz-Performance hinlegen und es feiern?" to "Ngubani onokuthi abeke umdaniso ohlazisayo aze awubhiyozele?",
    "Wer würde eher einen Ex-Partner anrufen, nachdem die Party vorbei ist?" to "Ngubani onokuthi abize iqabane langaphambili emva kokuba itheko liphelile?",
    "Wer würde eher einen fremden Gast versehentlich beleidigen?" to "Ngubani onokuthi ngempazamo akhubekise undwendwe olungaqhelekanga?",
    "Wer würde eher heimlich die Party verlassen, ohne sich zu verabschieden?" to "Ngubani onokuthi ashiye iqela ngokufihlakeleyo ngaphandle kokuvalelisa?",
    "Wer würde eher mit dem Haustier des Gastgebers spielen, anstatt mit den Gästen zu reden?" to "Ngubani ongakhetha ukudlala nesilo-qabane somninimzi kunokuba athethe neendwendwe?",
    "Wer würde eher spontan eine Reise buchen?" to "Ngubani onokubhukisha uhambo ngokuzenzekela?",
    "Wer würde eher stundenlang tiefgründige Gespräche in der Küche führen?" to "Ngubani onokuba neencoko ezinzulu ekhitshini kangangeeyure?",
    "Wer würde eher versehentlich das Getränk von jemand anderem trinken?" to "Ngubani onokuthi ngempazamo asele isiselo somnye umntu?",
    "Wer würde eher versehentlich eine teure Vase oder etwas Zerbrechliches umwerfen?" to "Ngubani onokuthi ngempazamo abethe ivazi yexabiso eliphezulu okanye into eethe-ethe?",
    "Wer würde eher versuchen, einen komplizierten Cocktail selbst zu mixen und kläglich scheitern?" to "Ngubani onokuzama ukuxuba i-cocktail enzima ngokwabo kwaye basilele kabuhlungu?",
    "Wer würde eher zu spät kommen?" to "Ngubani odla ngokufika emva kwexesha?",
    "Wer würde eher?" to "Ngubani ongakhetha?",
    "Wer übernimmt die tägliche Versorgung?" to "Ngubani onyamekela ukhathalelo lwemihla ngemihla?",
    "Werde so akzeptiert, wie du bist" to "Yamkeleka njengoko unjalo",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Ngaba siya kuba nexesha elaneleyo lomntwana/labantwana? ⏳",
    "Whirlpool" to "IJacuzzi",
    "White Chocolate" to "itshokolethi emhlophe",
    "Widgets" to "Iwijethi",
    "Wie fühlst du dich am meisten geliebt?" to "Uziva njani uthandwa kakhulu?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Sihlangabezana njani nemivuzo eyahlukeneyo?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Yeyiphi eyona ndlela ilungileyo yokuba iqabane lakho liqalise ukwabelana ngesondo nawe?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Iqabane lakho linokuba liqabane elingcono na kuwe?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Kude kube nini emva kwesindululo ufuna ukubhiyozela nabanye?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Sifuna ukuhlala ixesha elingakanani apho ubuncinci?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Kulula kangakanani kuwe ukuthetha ngeminqweno?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Ufuna libe njani ikamva lethu?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Injani iCawe yakho egqibeleleyo ekhaya?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Uziva njani ngentetho emdaka ngexesha lokwabelana ngesondo?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Ingakanani ikhredithi esinokuyihlawula ngokwenene?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Lingakanani ixesha esifuna ukulichitha sodwa?",
    "Wie viel wollen wir insgesamt ausgeben?" to "Sifuna ukuchitha malini xa iyonke?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Sizakulifumana njani ixesha lobudlelwane bethu xa umntwana efikile?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Kubaluleke kangakanani kuwe ukuba umzuzu ubanjiwe?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Kubaluleke kangakanani kuwe ukuba isicelo sibonise izinto ozonwabisa ngazo okanye izinto onomdla kuzo?",
    "Wie würdest du sie/ihn nennen?" to "Ungambiza ngantoni?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Yeyiphi indlela oyithandayo yokubonisa uthando ngaphandle kwesondo?",
    "Wildblumen" to "Iintyatyambo zasendle",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Ngaba ufuna intombazana okanye inkwenkwe? 👶",
    "Wintergarten" to "Isitiya sasebusika",
    "Winterhochzeit" to "Umtshato wasebusika",
    "Wir bestellen einfach beides" to "Siodola nje sobabini",
    "Wir brauchen ewig" to "Kusithatha ngonaphakade",
    "Wir einigen uns nie" to "Asizange sivume",
    "Wir entscheiden es gemeinsam" to "Sigqiba kunye",
    "Wir treffen uns in der Mitte" to "Sodibana phakathi",
    "Wir wechseln uns ab" to "Siyatshintshana",
    "Wird stressig" to "Ufumana uxinzelelo",
    "Wobei lachst du am meisten?" to "Yintoni ekwenza uhleke kakhulu?",
    "Wofür sparen wir gemeinsam?" to "Sigcinela ntoni kunye?",
    "Wohnzimmer" to "Egumbini lokuhlala",
    "Woran erinnerst du dich am lebhaftesten?" to "Yintoni oyikhumbula ngokucacileyo?",
    "Worauf freust du dich bei uns am meisten?" to "Yintoni ojonge phambili kuyo kunye nathi?",
    "Worte/Komplimente" to "Amagama/izincomo",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Yintoni oyoyika kakhulu kubudlelwane bethu?",
    "Wünsche? z.B. günstig, draußen" to "Iminqweno? umz. cheap, ngaphandle",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Ungathanda ukwenza isindululo ngeholide (ebandakanya uhambo)?",
    "Xbox" to "Xbox",
    "YouTube Music" to "Umculo kaYouTube",
    "Zeichne für mich" to "Nditsalele mna",
    "Zeichne mich als Tier — welches wäre ich?" to "Nditsale njengesilwanyana-ndiyakuba yintoni?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Zoba iimvakalelo zethu omnye komnye njengophawu.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Zoba indlu yethu yamaphupha kumgca omnye. Yeyiphi eyona nto ibetha kakhulu?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Zoba umhla wethu wokuqala - yintoni ekufuneka ngokuqinisekileyo ibe kumfanekiso?",
    "Zeichnen" to "Zoba",
    "Zeit füreinander" to "Ixesha lomnye nomnye",
    "Zeit, wenn das Baby schläft" to "Ixesha apho umntwana elele",
    "Zelten gehen" to "Yiya enkampini",
    "Zitrone" to "ilamuni",
    "Zu Hause, gemütlich und privat" to "Ekhaya, kupholile kwaye kuyimfihlo",
    "Zu einem Picknick gehen" to "Ukuya kwipikiniki",
    "Zu einem ausgefallenen Abendessen gehen" to "Ukuya kwisidlo sangokuhlwa esimnandi",
    "Zu zweit reisen" to "Hambani njengesibini",
    "Zuhause & Alltag" to "Ikhaya & ubomi bemihla ngemihla",
    "Zuhören" to "Phulaphula",
    "Zurück" to "Emva",
    "Zusammen seit" to "Kunye ukususela ngoko",
    "Zusammen seit (TT.MM.JJJJ)" to "Sikunye ukusukela (DD.MM.YYYY)",
    "Zusammenziehen" to "Ikhontrakthi",
    "Zustimmen oder Ablehnen" to "Vuma okanye uyala",
    "Zwei Kreise, die sich überschneiden" to "Izangqa ezibini ezidibanayo",
    "Zwei Stühle davor" to "Izitulo ezibini phambi kwayo",
    "Zärtlich sein" to "Yiba nobubele",
    "Öfter als ich zugebe" to "Ngokufuthi kunokuba ndivuma",
    "Über 100€/Monat" to "Ngaphezulu kwe-100 € / ngenyanga",
    "Über 2000 im Monat" to "Ngaphezu kwama-2000 ngenyanga",
    "Über mich selbst" to "Malunga nam",
    "Übernehmen" to "Thatha indawo",
    "Überraschend" to "Iyamangalisa",
    "Überraschung" to "Ukumangaliswa",
    "Überspringen" to "Tsiba",
    "Übertrieben und großartig" to "Ngaphezulu kwaye ilungile",
    "✎ Tippe, um zu antworten" to "✎ Cofa ukuze uphendule",
    "✨ GFK-Brücke" to "✨ ibhulorho ye-GRP",
)

internal fun localizeXhosaDynamicContent(text: String): String? =
    localizeGeneratedLocaleDynamicContent(text, EXACT_XHOSA_CONTENT)
